My Project: src/bele.h File Reference
bele.h File Reference
#include "bele_policy.h"
Classes
struct BE16
classes for portable unaligned access
struct BE32
struct BE64
struct LE16
struct LE32
struct LE64
Namespaces
namespace upx
some global overloads
namespace N_BELE_CTP
Provide namespaces and classes to abstract endianness policies.
namespace N_BELE_RTP
Macros
#define bele_constexpr /*empty*/
#define REQUIRE_XE16 /*empty*/
XE - eXtended Endian compatibility try to detect XX16 vs XX32 vs XX64 size mismatches.
#define REQUIRE_XE24 /*empty*/
#define REQUIRE_XE32 /*empty*/
#define REQUIRE_XE64 /*empty*/
#define ne16_to_be16(v) bswap16(v)
#define ne32_to_be32(v) bswap32(v)
#define ne64_to_be64(v) bswap64(v)
#define ne16_to_le16(v) no_bswap16(v)
#define ne32_to_le32(v) no_bswap32(v)
#define ne64_to_le64(v) no_bswap64(v)
#define REQUIRE_UINT32 template <class T, class = std::enable_if_t<std::is_same_v<T, upx_uint32_t>, T> >
#define REQUIRE_UINT64 template <class T, class = std::enable_if_t<std::is_same_v<T, upx_uint64_t>, T> >
#define TT_UPX_IS_INTEGRAL(T)
#define ne16_compare le16_compare
#define ne32_compare le32_compare
#define ne64_compare le64_compare
#define ne16_compare_signed le16_compare_signed
#define ne32_compare_signed le32_compare_signed
#define ne64_compare_signed le64_compare_signed
#define BELE_CTP 1
#define BELE_RTP 1
Typedefs
typedef void XE16
typedef void XE24
typedef void XE32
typedef void XE64
typedef LE16 NE16
typedef LE32 NE32
typedef LE64 NE64
Functions
forceinline bele_constexpr unsigned get_ne16 (const byte *p) noexcept
core - NE
forceinline bele_constexpr unsigned get_ne32 (const byte *p) noexcept
forceinline bele_constexpr upx_uint64_t get_ne64 (const byte *p) noexcept
forceinline bele_constexpr void set_ne16 (byte *p, unsigned v) noexcept
forceinline bele_constexpr void set_ne32 (byte *p, unsigned v) noexcept
forceinline bele_constexpr void set_ne64 (byte *p, upx_uint64_t v) noexcept
REQUIRE_XE16 forceinline bele_constexpr unsigned get_ne16 (const XE16 *p) noexcept
core - NE
REQUIRE_XE32 forceinline bele_constexpr unsigned get_ne32 (const XE32 *p) noexcept
REQUIRE_XE64 forceinline bele_constexpr upx_uint64_t get_ne64 (const XE64 *p) noexcept
REQUIRE_XE16 forceinline bele_constexpr void set_ne16 (XE16 *p, unsigned v) noexcept
REQUIRE_XE32 forceinline bele_constexpr void set_ne32 (XE32 *p, unsigned v) noexcept
REQUIRE_XE64 forceinline bele_constexpr void set_ne64 (XE64 *p, upx_uint64_t v) noexcept
forceinline constexpr unsigned bswap16 (unsigned v) noexcept
core - bswap
forceinline constexpr unsigned bswap32 (unsigned v) noexcept
forceinline constexpr upx_uint64_t bswap64 (upx_uint64_t v) noexcept
forceinline constexpr unsigned no_bswap16 (unsigned v) noexcept
forceinline constexpr unsigned no_bswap32 (unsigned v) noexcept
forceinline constexpr upx_uint64_t no_bswap64 (upx_uint64_t v) noexcept
REQUIRE_XE16 bele_constexpr unsigned get_be16 (const XE16 *p) noexcept
get/set 16/32/64
REQUIRE_XE32 bele_constexpr unsigned get_be32 (const XE32 *p) noexcept
REQUIRE_XE64 bele_constexpr upx_uint64_t get_be64 (const XE64 *p) noexcept
REQUIRE_XE16 bele_constexpr unsigned get_le16 (const XE16 *p) noexcept
REQUIRE_XE32 bele_constexpr unsigned get_le32 (const XE32 *p) noexcept
REQUIRE_XE64 bele_constexpr upx_uint64_t get_le64 (const XE64 *p) noexcept
REQUIRE_XE16 bele_constexpr void set_be16 (XE16 *p, unsigned v) noexcept
REQUIRE_XE32 bele_constexpr void set_be32 (XE32 *p, unsigned v) noexcept
REQUIRE_XE64 bele_constexpr void set_be64 (XE64 *p, upx_uint64_t v) noexcept
REQUIRE_XE16 bele_constexpr void set_le16 (XE16 *p, unsigned v) noexcept
REQUIRE_XE32 bele_constexpr void set_le32 (XE32 *p, unsigned v) noexcept
REQUIRE_XE64 bele_constexpr void set_le64 (XE64 *p, upx_uint64_t v) noexcept
constexpr unsigned get_be24 (const byte *p) noexcept
get/set 24/26
constexpr unsigned get_le24 (const byte *p) noexcept
constexpr void set_be24 (byte *p, unsigned v) noexcept
constexpr void set_le24 (byte *p, unsigned v) noexcept
REQUIRE_XE24 forceinline bele_constexpr unsigned get_be24 (const XE24 *p) noexcept
REQUIRE_XE24 forceinline bele_constexpr unsigned get_le24 (const XE24 *p) noexcept
REQUIRE_XE24 forceinline bele_constexpr void set_be24 (XE24 *p, unsigned v) noexcept
REQUIRE_XE24 forceinline bele_constexpr void set_le24 (XE24 *p, unsigned v) noexcept
REQUIRE_XE32 bele_constexpr unsigned get_le26 (const XE32 *p) noexcept
REQUIRE_XE32 bele_constexpr unsigned get_le19_5 (const XE32 *p) noexcept
REQUIRE_XE32 bele_constexpr unsigned get_le14_5 (const XE32 *p) noexcept
REQUIRE_XE32 bele_constexpr void set_le26 (XE32 *p, unsigned v) noexcept
REQUIRE_XE32 bele_constexpr void set_le19_5 (XE32 *p, unsigned v) noexcept
REQUIRE_XE32 bele_constexpr void set_le14_5 (XE32 *p, unsigned v) noexcept
forceinline constexpr int sign_extend (unsigned v, unsigned bits) noexcept
get signed values
forceinline constexpr upx_int64_t sign_extend (upx_uint64_t v, unsigned bits) noexcept
REQUIRE_XE16 bele_constexpr int get_be16_signed (const XE16 *p) noexcept
REQUIRE_XE24 bele_constexpr int get_be24_signed (const XE24 *p) noexcept
REQUIRE_XE32 bele_constexpr int get_be32_signed (const XE32 *p) noexcept
REQUIRE_XE64 bele_constexpr upx_int64_t get_be64_signed (const XE64 *p) noexcept
REQUIRE_XE16 bele_constexpr int get_le16_signed (const XE16 *p) noexcept
REQUIRE_XE24 bele_constexpr int get_le24_signed (const XE24 *p) noexcept
REQUIRE_XE32 bele_constexpr int get_le32_signed (const XE32 *p) noexcept
REQUIRE_XE64 bele_constexpr upx_int64_t get_le64_signed (const XE64 *p) noexcept
template<class T >
bele_constexpr T * operator+ (T *ptr, const BE16 &v) noexcept
global operators (pointer addition/subtraction)
template<class T >
bele_constexpr T * operator- (T *ptr, const BE16 &v) noexcept
template<class T >
bele_constexpr T * operator+ (T *ptr, const BE32 &v) noexcept
template<class T >
bele_constexpr T * operator- (T *ptr, const BE32 &v) noexcept
template<class T >
bele_constexpr T * operator+ (T *ptr, const LE16 &v) noexcept
template<class T >
bele_constexpr T * operator- (T *ptr, const LE16 &v) noexcept
template<class T >
bele_constexpr T * operator+ (T *ptr, const LE32 &v) noexcept
template<class T >
bele_constexpr T * operator- (T *ptr, const LE32 &v) noexcept
template<class T >
T * operator+ (T *ptr, const BE64 &v) noexcept DELETED_FUNCTION
template<class T >
T * operator- (T *ptr, const BE64 &v) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (T *ptr, const LE64 &v) noexcept DELETED_FUNCTION
template<class T >
T * operator- (T *ptr, const LE64 &v) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (const BE16 &v, T *ptr) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (const BE32 &v, T *ptr) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (const LE16 &v, T *ptr) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (const LE32 &v, T *ptr) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (const BE64 &v, T *ptr) noexcept DELETED_FUNCTION
template<class T >
T * operator+ (const LE64 &v, T *ptr) noexcept DELETED_FUNCTION
REQUIRE_UINT32 bele_constexpr T upx::align_down (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_down (const BE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_down (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_down (const LE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_up (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_up (const LE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_up (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::align_up (const BE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const T &a, const BE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const BE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const BE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::min (const T &a, const BE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::min (const BE64 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const T &a, const LE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const LE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::min (const LE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::min (const T &a, const LE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::min (const LE64 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const T &a, const BE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const BE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const BE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::max (const T &a, const BE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::max (const BE64 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const T &a, const LE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const LE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T upx::max (const LE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::max (const T &a, const LE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T upx::max (const LE64 &a, const T &b) noexcept
int __acc_cdecl_qsort be16_compare (const void *, const void *)
misc support
int __acc_cdecl_qsort be24_compare (const void *, const void *)
int __acc_cdecl_qsort be32_compare (const void *, const void *)
int __acc_cdecl_qsort be64_compare (const void *, const void *)
int __acc_cdecl_qsort le16_compare (const void *, const void *)
int __acc_cdecl_qsort le24_compare (const void *, const void *)
int __acc_cdecl_qsort le32_compare (const void *, const void *)
int __acc_cdecl_qsort le64_compare (const void *, const void *)
int __acc_cdecl_qsort be16_compare_signed (const void *, const void *)
int __acc_cdecl_qsort be24_compare_signed (const void *, const void *)
int __acc_cdecl_qsort be32_compare_signed (const void *, const void *)
int __acc_cdecl_qsort be64_compare_signed (const void *, const void *)
int __acc_cdecl_qsort le16_compare_signed (const void *, const void *)
int __acc_cdecl_qsort le24_compare_signed (const void *, const void *)
int __acc_cdecl_qsort le32_compare_signed (const void *, const void *)
int __acc_cdecl_qsort le64_compare_signed (const void *, const void *)
TT_UPX_IS_INTEGRAL (BE16)
TT_UPX_IS_INTEGRAL (BE32)
TT_UPX_IS_INTEGRAL (BE64)
TT_UPX_IS_INTEGRAL (LE16)
TT_UPX_IS_INTEGRAL (LE32)
TT_UPX_IS_INTEGRAL (LE64)
const N_BELE_RTP::AbstractPolicy * N_BELE_CTP::getRTP (const BEPolicy *) noexcept
const N_BELE_RTP::AbstractPolicy * N_BELE_CTP::getRTP (const LEPolicy *) noexcept
Variables
const BEPolicy N_BELE_CTP::be_policy
const LEPolicy N_BELE_CTP::le_policy
const BEPolicy N_BELE_RTP::be_policy
const LEPolicy N_BELE_RTP::le_policy
Macro Definition Documentation
bele_constexpr
#define bele_constexpr /*empty*/
Definition at line 41 of file bele.h.
BELE_CTP
#define BELE_CTP 1
Definition at line 1134 of file bele.h.
BELE_RTP
#define BELE_RTP 1
Definition at line 1139 of file bele.h.
ne16_compare
#define ne16_compare le16_compare
Definition at line 1102 of file bele.h.
ne16_compare_signed
#define ne16_compare_signed le16_compare_signed
Definition at line 1105 of file bele.h.
ne16_to_be16
#define ne16_to_be16 (v) bswap16(v)
Definition at line 298 of file bele.h.
ne16_to_le16
#define ne16_to_le16 (v) no_bswap16(v)
Definition at line 301 of file bele.h.
ne32_compare
#define ne32_compare le32_compare
Definition at line 1103 of file bele.h.
ne32_compare_signed
#define ne32_compare_signed le32_compare_signed
Definition at line 1106 of file bele.h.
ne32_to_be32
#define ne32_to_be32 (v) bswap32(v)
Definition at line 299 of file bele.h.
ne32_to_le32
#define ne32_to_le32 (v) no_bswap32(v)
Definition at line 302 of file bele.h.
ne64_compare
#define ne64_compare le64_compare
Definition at line 1104 of file bele.h.
ne64_compare_signed
#define ne64_compare_signed le64_compare_signed
Definition at line 1107 of file bele.h.
ne64_to_be64
#define ne64_to_be64 (v) bswap64(v)
Definition at line 300 of file bele.h.
ne64_to_le64
#define ne64_to_le64 (v) no_bswap64(v)
Definition at line 303 of file bele.h.
REQUIRE_UINT32
#define REQUIRE_UINT32 template <class T, class = std::enable_if_t<std::is_same_v<T, upx_uint32_t>, T> >
Definition at line 959 of file bele.h.
REQUIRE_UINT64
#define REQUIRE_UINT64 template <class T, class = std::enable_if_t<std::is_same_v<T, upx_uint64_t>, T> >
Definition at line 961 of file bele.h.
REQUIRE_XE16
#define REQUIRE_XE16 /*empty*/
XE - eXtended Endian compatibility try to detect XX16 vs XX32 vs XX64 size mismatches.
Definition at line 60 of file bele.h.
REQUIRE_XE24
#define REQUIRE_XE24 /*empty*/
Definition at line 61 of file bele.h.
REQUIRE_XE32
#define REQUIRE_XE32 /*empty*/
Definition at line 62 of file bele.h.
REQUIRE_XE64
#define REQUIRE_XE64 /*empty*/
Definition at line 63 of file bele.h.
TT_UPX_IS_INTEGRAL
#define TT_UPX_IS_INTEGRAL (T)
Value:
    template <>                                                                                    \
    struct upx_is_integral<T> : public std::true_type {};                                          \
    template <>                                                                                    \
    struct upx_is_integral<const T> : public std::true_type {};                                    \
    template <>                                                                                    \
    struct upx_is_integral<volatile T> : public std::true_type {};                                 \
    template <>                                                                                    \
    struct upx_is_integral<const volatile T> : public std::true_type {}
Definition at line 1070 of file bele.h.
Typedef Documentation
NE16
typedef LE16 NE16
Definition at line 1099 of file bele.h.
NE32
typedef LE32 NE32
Definition at line 1100 of file bele.h.
NE64
typedef LE64 NE64
Definition at line 1101 of file bele.h.
XE16
typedef void XE16
Definition at line 64 of file bele.h.
XE24
typedef void XE24
Definition at line 65 of file bele.h.
XE32
typedef void XE32
Definition at line 66 of file bele.h.
XE64
typedef void XE64
Definition at line 67 of file bele.h.
Function Documentation
be16_compare()
int __acc_cdecl_qsort be16_compare (const void * e1, const void * e2)
misc support
misc support
Definition at line 569 of file util.cpp.
{
    const unsigned d1 = get_be16(e1);
    const unsigned d2 = get_be16(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be16().
Referenced by BEPolicy::u16_compare().
be16_compare_signed()
int __acc_cdecl_qsort be16_compare_signed (const void * e1, const void * e2)
Definition at line 617 of file util.cpp.
{
    const int d1 = get_be16_signed(e1);
    const int d2 = get_be16_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be16_signed().
Referenced by BEPolicy::u16_compare_signed().
be24_compare()
int __acc_cdecl_qsort be24_compare (const void * e1, const void * e2)
Definition at line 575 of file util.cpp.
{
    const unsigned d1 = get_be24(e1);
    const unsigned d2 = get_be24(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be24().
Referenced by BEPolicy::u24_compare().
be24_compare_signed()
int __acc_cdecl_qsort be24_compare_signed (const void * e1, const void * e2)
Definition at line 623 of file util.cpp.
{
    const int d1 = get_be24_signed(e1);
    const int d2 = get_be24_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be24_signed().
Referenced by BEPolicy::u24_compare_signed().
be32_compare()
int __acc_cdecl_qsort be32_compare (const void * e1, const void * e2)
Definition at line 581 of file util.cpp.
{
    const unsigned d1 = get_be32(e1);
    const unsigned d2 = get_be32(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be32().
Referenced by BEPolicy::u32_compare().
be32_compare_signed()
int __acc_cdecl_qsort be32_compare_signed (const void * e1, const void * e2)
Definition at line 629 of file util.cpp.
{
    const int d1 = get_be32_signed(e1);
    const int d2 = get_be32_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be32_signed().
Referenced by BEPolicy::u32_compare_signed().
be64_compare()
int __acc_cdecl_qsort be64_compare (const void * e1, const void * e2)
Definition at line 587 of file util.cpp.
{
    const upx_uint64_t d1 = get_be64(e1);
    const upx_uint64_t d2 = get_be64(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be64().
Referenced by BEPolicy::u64_compare().
be64_compare_signed()
int __acc_cdecl_qsort be64_compare_signed (const void * e1, const void * e2)
Definition at line 635 of file util.cpp.
{
    const upx_int64_t d1 = get_be64_signed(e1);
    const upx_int64_t d2 = get_be64_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be64_signed().
Referenced by BEPolicy::u64_compare_signed().
bswap16()
forceinline constexpr unsigned bswap16 (unsigned v) constexpr noexcept
core - bswap
Definition at line 264 of file bele.h.
{
#if defined(__riscv) && __riscv_xlen == 64
    return (unsigned) __builtin_bswap64(upx_uint64_t(v) << 48);
#else
    // return __builtin_bswap16(upx_uint16_t(v & 0xffff));
    return __builtin_bswap32(v << 16);
#endif
}
bswap32()
forceinline constexpr unsigned bswap32 (unsigned v) constexpr noexcept
Definition at line 272 of file bele.h.
{
#if defined(__riscv) && __riscv_xlen == 64
    return (unsigned) __builtin_bswap64(upx_uint64_t(v) << 32);
#else
    return __builtin_bswap32(v);
#endif
}
bswap64()
forceinline constexpr upx_uint64_t bswap64 (upx_uint64_t v) constexpr noexcept
Definition at line 279 of file bele.h.
{ return __builtin_bswap64(v); }
get_be16()
REQUIRE_XE16 bele_constexpr unsigned get_be16 (const XE16 * p) inline noexcept
get/set 16/32/64
Definition at line 311 of file bele.h.
{
    return ne16_to_be16(get_ne16(p));
}
References get_ne16(), and ne16_to_be16.
Referenced by be16_compare(), f_ct16_e8_bswap_be(), f_ct16_e8e9_bswap_be(), f_ct16_e9_bswap_be(), BEPolicy::get16(), get_be16_signed(), BE16::operator unsigned(), BE16::operator&=(), BE16::operator*=(), BE16::operator+=(), BE16::operator-=(), BE16::operator/=(), BE16::operator<<=(), BE16::operator>>=(), BE16::operator^=(), BE16::operator|=(), ElfLinkerArmBE::relocate1(), ElfLinkerM68k::relocate1(), ElfLinkerMipsBE::relocate1(), ElfLinkerPpc64::relocate1(), s_ct16_e8_bswap_le(), s_ct16_e8e9_bswap_le(), s_ct16_e9_bswap_le(), TEST_CASE(), u_ct16_e8_bswap_le(), u_ct16_e8e9_bswap_le(), u_ct16_e9_bswap_le(), u_ctsw16_e8_e9(), u_ctsw16_e9_e8(), u_sw16_e8(), u_sw16_e8e9(), u_sw16_e9(), and upx_compiler_sanity_check().
get_be16_signed()
REQUIRE_XE16 bele_constexpr int get_be16_signed (const XE16 * p) inline noexcept
Definition at line 433 of file bele.h.
{
    unsigned v = get_be16(p);
    return sign_extend(v, 16);
}
References get_be16(), and sign_extend().
Referenced by be16_compare_signed(), BEPolicy::get16_signed(), and upx_compiler_sanity_check().
get_be24() [1/2]
constexpr unsigned get_be24 (const byte * p) inline constexpr noexcept
get/set 24/26
Definition at line 356 of file bele.h.
{
    return upx::compile_time::get_be24(p);
}
References upx::compile_time::get_be24().
Referenced by be24_compare(), f_ct24arm_be(), BEPolicy::get24(), get_be24(), get_be24_signed(), ElfLinkerArmBE::relocate1(), s_ct24arm_be(), u_ct24arm_be(), and upx_compiler_sanity_check().
get_be24() [2/2]
REQUIRE_XE24 forceinline bele_constexpr unsigned get_be24 (const XE24 * p) noexcept
Definition at line 366 of file bele.h.
{
    return get_be24(upx::ptr_static_cast<const byte *>(p));
}
References get_be24().
get_be24_signed()
REQUIRE_XE24 bele_constexpr int get_be24_signed (const XE24 * p) inline noexcept
Definition at line 439 of file bele.h.
{
    unsigned v = get_be24(p);
    return sign_extend(v, 24);
}
References get_be24(), and sign_extend().
Referenced by be24_compare_signed(), BEPolicy::get24_signed(), and upx_compiler_sanity_check().
get_be32()
REQUIRE_XE32 bele_constexpr unsigned get_be32 (const XE32 * p) inline noexcept
Definition at line 315 of file bele.h.
{
    return ne32_to_be32(get_ne32(p));
}
References get_ne32(), and ne32_to_be32.
Referenced by be32_compare(), check_relocs(), PackHeader::decodePackHeaderFromBuf(), F(), f_ct32_e8_bswap_be(), f_ct32_e8e9_bswap_be(), f_ct32_e9_bswap_be(), BEPolicy::get32(), get_be32_signed(), BE32::operator unsigned(), BE32::operator&=(), BE32::operator*=(), BE32::operator+=(), BE32::operator-=(), BE32::operator/=(), BE32::operator<<=(), BE32::operator>>=(), BE32::operator^=(), BE32::operator|=(), PackTos::pack(), ElfLinkerArmBE::relocate1(), ElfLinkerM68k::relocate1(), ElfLinkerMipsBE::relocate1(), ElfLinkerPpc32::relocate1(), ElfLinkerPpc64::relocate1(), s_ct32_e8_bswap_le(), s_ct32_e8e9_bswap_le(), s_ct32_e9_bswap_le(), TEST_CASE(), u_ct32_e8_bswap_le(), u_ct32_e8e9_bswap_le(), u_ct32_e9_bswap_le(), u_ctsw32_e8_e9(), u_ctsw32_e9_e8(), u_sw32_e8(), u_sw32_e8e9(), u_sw32_e9(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), and upx_compiler_sanity_check().
get_be32_signed()
REQUIRE_XE32 bele_constexpr int get_be32_signed (const XE32 * p) inline noexcept
Definition at line 445 of file bele.h.
{
    unsigned v = get_be32(p);
    return sign_extend(v, 32);
}
References get_be32(), and sign_extend().
Referenced by be32_compare_signed(), BEPolicy::get32_signed(), handle_allegropak(), and upx_compiler_sanity_check().
get_be64()
REQUIRE_XE64 bele_constexpr upx_uint64_t get_be64 (const XE64 * p) inline noexcept
Definition at line 319 of file bele.h.
{
    return ne64_to_be64(get_ne64(p));
}
References get_ne64(), and ne64_to_be64.
Referenced by be64_compare(), BEPolicy::get64(), get_be64_signed(), BE64::operator upx_uint64_t(), BE64::operator&=(), BE64::operator*=(), BE64::operator+=(), BE64::operator-=(), BE64::operator/=(), BE64::operator<<=(), BE64::operator>>=(), BE64::operator^=(), BE64::operator|=(), ElfLinkerPpc64::relocate1(), TEST_CASE(), and upx_compiler_sanity_check().
get_be64_signed()
REQUIRE_XE64 bele_constexpr upx_int64_t get_be64_signed (const XE64 * p) inline noexcept
Definition at line 451 of file bele.h.
{
    upx_uint64_t v = get_be64(p);
    return sign_extend(v, 64);
}
References get_be64(), and sign_extend().
Referenced by be64_compare_signed(), BEPolicy::get64_signed(), and upx_compiler_sanity_check().
get_le14_5()
REQUIRE_XE32 bele_constexpr unsigned get_le14_5 (const XE32 * p) inline noexcept
Definition at line 389 of file bele.h.
{
    return (get_le32(p) >> 5) & 0x00003fff;
}
References get_le32().
get_le16()
REQUIRE_XE16 bele_constexpr unsigned get_le16 (const XE16 * p) inline noexcept
Definition at line 323 of file bele.h.
{
    return ne16_to_le16(get_ne16(p));
}
References get_ne16(), and ne16_to_le16.
Referenced by PeFile::Resource::build(), PeFile::Resource::convert(), PackWcle::decodeEntryTable(), PackHeader::decodePackHeaderFromBuf(), PackWcle::encodeEntryTable(), f_ct16_e8(), f_ct16_e8_bswap_le(), f_ct16_e8e9(), f_ct16_e8e9_bswap_le(), f_ct16_e9(), f_ct16_e9_bswap_le(), f_ctsw16_e8_e9(), f_ctsw16_e9_e8(), f_sw16_e8(), f_sw16_e8e9(), f_sw16_e9(), LEPolicy::get16(), get_le16_signed(), ElfLinker::init(), lame_print_unicode(), le16_compare(), match(), LE16::operator unsigned(), LE16::operator&=(), LE16::operator*=(), LE16::operator+=(), LE16::operator-=(), LE16::operator/=(), LE16::operator<<=(), LE16::operator>>=(), LE16::operator^=(), LE16::operator|=(), optimize_relocs(), PackExe::pack(), PackSys::patchLoader(), PeFile::processResources(), PackDjgpp2::readFileHeader(), PeFile::rebuildImports(), PeFile::rebuildResources(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerArmLE::relocate1(), ElfLinkerMipsLE::relocate1(), ElfLinkerPpc64le::relocate1(), ElfLinkerX86::relocate1(), s_ct16_e8(), s_ct16_e8_bswap_be(), s_ct16_e8e9(), s_ct16_e8e9_bswap_be(), s_ct16_e9(), s_ct16_e9_bswap_be(), s_ctsw16_e8_e9(), s_ctsw16_e9_e8(), s_sw16_e8(), s_sw16_e8e9(), s_sw16_e9(), TEST_CASE(), u_ct16_e8(), u_ct16_e8_bswap_be(), u_ct16_e8e9(), u_ct16_e8e9_bswap_be(), u_ct16_e9(), u_ct16_e9_bswap_be(), Packer::unoptimizeReloc(), PackExe::unpack(), and upx_compiler_sanity_check().
get_le16_signed()
REQUIRE_XE16 bele_constexpr int get_le16_signed (const XE16 * p) inline noexcept
Definition at line 457 of file bele.h.
{
    unsigned v = get_le16(p);
    return sign_extend(v, 16);
}
References get_le16(), and sign_extend().
Referenced by LEPolicy::get16_signed(), le16_compare_signed(), PackWcle::preprocessFixups(), and upx_compiler_sanity_check().
get_le19_5()
REQUIRE_XE32 bele_constexpr unsigned get_le19_5 (const XE32 * p) inline noexcept
Definition at line 385 of file bele.h.
{
    return (get_le32(p) >> 5) & 0x0007ffff;
}
References get_le32().
get_le24() [1/2]
constexpr unsigned get_le24 (const byte * p) inline constexpr noexcept
Definition at line 359 of file bele.h.
{
    return upx::compile_time::get_le24(p);
}
References upx::compile_time::get_le24().
Referenced by PackHeader::decodePackHeaderFromBuf(), f_ct24arm_le(), LEPolicy::get24(), get_le24(), get_le24_signed(), le24_compare(), ElfLinkerArmLE::relocate1(), s_ct24arm_le(), u_ct24arm_le(), and upx_compiler_sanity_check().
get_le24() [2/2]
REQUIRE_XE24 forceinline bele_constexpr unsigned get_le24 (const XE24 * p) noexcept
Definition at line 370 of file bele.h.
{
    return get_le24(upx::ptr_static_cast<const byte *>(p));
}
References get_le24().
get_le24_signed()
REQUIRE_XE24 bele_constexpr int get_le24_signed (const XE24 * p) inline noexcept
Definition at line 463 of file bele.h.
{
    unsigned v = get_le24(p);
    return sign_extend(v, 24);
}
References get_le24(), and sign_extend().
Referenced by LEPolicy::get24_signed(), le24_compare_signed(), and upx_compiler_sanity_check().
get_le26()
REQUIRE_XE32 bele_constexpr unsigned get_le26 (const XE32 * p) inline noexcept
Definition at line 383 of file bele.h.
{ return get_le32(p) & 0x03ffffff; }
References get_le32().
Referenced by f_ct26arm_le(), s_ct26arm_le(), u_ct26arm_le(), and upx_compiler_sanity_check().
get_le32()
REQUIRE_XE32 bele_constexpr unsigned get_le32 (const XE32 * p) inline noexcept
Definition at line 327 of file bele.h.
{
    return ne32_to_le32(get_ne32(p));
}
References get_ne32(), and ne32_to_le32.
Referenced by PackLinuxI386::buildLinuxLoader(), PackLinuxI386sh::buildLoader(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), PeFile::Export::convert(), LeFile::countFixups(), PackWcle::decodeEntryTable(), PackWcle::decodeFixups(), PackWcle::decodeImage(), PackWcle::decodeObjectTable(), PackHeader::decodePackHeaderFromBuf(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PackWcle::encodeEntryTable(), F(), f_ct32_e8(), f_ct32_e8_bswap_le(), f_ct32_e8e9(), f_ct32_e8e9_bswap_le(), f_ct32_e9(), f_ct32_e9_bswap_le(), f_ctsw32_e8_e9(), f_ctsw32_e9_e8(), f_sw32_e8(), f_sw32_e8e9(), f_sw32_e9(), LEPolicy::get32(), get_le14_5(), get_le19_5(), get_le26(), get_le32_signed(), get_packheader_checksum(), ElfLinker::init(), is_dlm(), le32_compare(), LE32::operator unsigned(), LE32::operator&=(), LE32::operator*=(), LE32::operator+=(), LE32::operator-=(), LE32::operator/=(), LE32::operator<<=(), LE32::operator>>=(), LE32::operator^=(), LE32::operator|=(), optimize_relocs(), Packer::optimizeReloc(), PackExe::pack(), PackTmt::pack(), PackWcle::preprocessFixups(), PeFile::processLoadConf(), PeFile32::processRelocs(), PackHeader::putPackHeader(), PeFile::readFileHeader(), LeFile::readFixups(), PeFile::Reloc::readFromRelocationBlock(), PeFile::rebuildImports(), PeFile::rebuildRelocs(), PeFile::rebuildResources(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerArmLE::relocate1(), ElfLinkerMipsLE::relocate1(), ElfLinkerPpc64le::relocate1(), ElfLinkerX86::relocate1(), Packer::relocateLoader(), s_ct32_e8(), s_ct32_e8_bswap_be(), s_ct32_e8e9(), s_ct32_e8e9_bswap_be(), s_ct32_e9(), s_ct32_e9_bswap_be(), s_ctsw32_e8_e9(), s_ctsw32_e9_e8(), s_sw32_e8(), s_sw32_e8e9(), s_sw32_e9(), set_le14_5(), set_le19_5(), TEST_CASE(), u_ct32_e8(), u_ct32_e8_bswap_be(), u_ct32_e8e9(), u_ct32_e8e9_bswap_be(), u_ct32_e9(), u_ct32_e9_bswap_be(), Packer::unoptimizeReloc(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackTmt::unpack(), PackUnix::unpack(), PackWcle::unpack(), PeFile::unpack0(), and upx_compiler_sanity_check().
get_le32_signed()
REQUIRE_XE32 bele_constexpr int get_le32_signed (const XE32 * p) inline noexcept
Definition at line 469 of file bele.h.
{
    unsigned v = get_le32(p);
    return sign_extend(v, 32);
}
References get_le32(), and sign_extend().
Referenced by LEPolicy::get32_signed(), le32_compare_signed(), and upx_compiler_sanity_check().
get_le64()
REQUIRE_XE64 bele_constexpr upx_uint64_t get_le64 (const XE64 * p) inline noexcept
Definition at line 331 of file bele.h.
{
    return ne64_to_le64(get_ne64(p));
}
References get_ne64(), and ne64_to_le64.
Referenced by LEPolicy::get64(), get_le64_signed(), le64_compare(), LE64::operator upx_uint64_t(), LE64::operator&=(), LE64::operator*=(), LE64::operator+=(), LE64::operator-=(), LE64::operator/=(), LE64::operator<<=(), LE64::operator>>=(), LE64::operator^=(), LE64::operator|=(), Packer::optimizeReloc(), PeFile64::processRelocs(), PeFile::rebuildRelocs(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerPpc64le::relocate1(), TEST_CASE(), Packer::unoptimizeReloc(), and upx_compiler_sanity_check().
get_le64_signed()
REQUIRE_XE64 bele_constexpr upx_int64_t get_le64_signed (const XE64 * p) inline noexcept
Definition at line 475 of file bele.h.
{
    upx_uint64_t v = get_le64(p);
    return sign_extend(v, 64);
}
References get_le64(), and sign_extend().
Referenced by LEPolicy::get64_signed(), le64_compare_signed(), and upx_compiler_sanity_check().
get_ne16() [1/2]
forceinline bele_constexpr unsigned get_ne16 (const byte * p) noexcept
core - NE
Definition at line 111 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
    if (upx_is_constant_evaluated())
        return upx::compile_time::get_ne16(p);
    else
#endif
    {
        upx_uint16_t v = 0;
        upx_memcpy_inline(&v, p, sizeof(v));
        return v;
    }
}
References upx::compile_time::get_ne16(), and upx_memcpy_inline.
Referenced by get_be16(), get_le16(), get_ne16(), and upx_compiler_sanity_check().
get_ne16() [2/2]
REQUIRE_XE16 forceinline bele_constexpr unsigned get_ne16 (const XE16 * p) noexcept
core - NE
Definition at line 191 of file bele.h.
{
    return get_ne16(upx::ptr_static_cast<const byte *>(p));
}
References get_ne16().
get_ne32() [1/2]
forceinline bele_constexpr unsigned get_ne32 (const byte * p) noexcept
Definition at line 124 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
    if (upx_is_constant_evaluated())
        return upx::compile_time::get_ne32(p);
    else
#endif
    {
        upx_uint32_t v = 0;
        upx_memcpy_inline(&v, p, sizeof(v));
        return v;
    }
}
References upx::compile_time::get_ne32(), and upx_memcpy_inline.
Referenced by MemBuffer::checkState(), get_be32(), get_le32(), get_ne32(), reloc_entry_compare(), reloc_entry_decode(), set_le26(), TEST_CASE(), and upx_compiler_sanity_check().
get_ne32() [2/2]
REQUIRE_XE32 forceinline bele_constexpr unsigned get_ne32 (const XE32 * p) noexcept
Definition at line 196 of file bele.h.
{
    return get_ne32(upx::ptr_static_cast<const byte *>(p));
}
References get_ne32().
get_ne64() [1/2]
forceinline bele_constexpr upx_uint64_t get_ne64 (const byte * p) noexcept
Definition at line 137 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
    if (upx_is_constant_evaluated())
        return upx::compile_time::get_ne64(p);
    else
#endif
    {
        upx_uint64_t v = 0;
        upx_memcpy_inline(&v, p, sizeof(v));
        return v;
    }
}
References upx::compile_time::get_ne64(), and upx_memcpy_inline.
Referenced by get_be64(), get_le64(), get_ne64(), and upx_compiler_sanity_check().
get_ne64() [2/2]
REQUIRE_XE64 forceinline bele_constexpr upx_uint64_t get_ne64 (const XE64 * p) noexcept
Definition at line 201 of file bele.h.
{
    return get_ne64(upx::ptr_static_cast<const byte *>(p));
}
References get_ne64().
le16_compare()
int __acc_cdecl_qsort le16_compare (const void * e1, const void * e2)
Definition at line 593 of file util.cpp.
{
    const unsigned d1 = get_le16(e1);
    const unsigned d2 = get_le16(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le16().
Referenced by LEPolicy::u16_compare().
le16_compare_signed()
int __acc_cdecl_qsort le16_compare_signed (const void * e1, const void * e2)
Definition at line 641 of file util.cpp.
{
    const int d1 = get_le16_signed(e1);
    const int d2 = get_le16_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le16_signed().
Referenced by LEPolicy::u16_compare_signed().
le24_compare()
int __acc_cdecl_qsort le24_compare (const void * e1, const void * e2)
Definition at line 599 of file util.cpp.
{
    const unsigned d1 = get_le24(e1);
    const unsigned d2 = get_le24(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le24().
Referenced by LEPolicy::u24_compare().
le24_compare_signed()
int __acc_cdecl_qsort le24_compare_signed (const void * e1, const void * e2)
Definition at line 647 of file util.cpp.
{
    const int d1 = get_le24_signed(e1);
    const int d2 = get_le24_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le24_signed().
Referenced by LEPolicy::u24_compare_signed().
le32_compare()
int __acc_cdecl_qsort le32_compare (const void * e1, const void * e2)
Definition at line 605 of file util.cpp.
{
    const unsigned d1 = get_le32(e1);
    const unsigned d2 = get_le32(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le32().
Referenced by Packer::optimizeReloc(), PackExe::pack(), PeFile32::processRelocs(), PeFile64::processRelocs(), and LEPolicy::u32_compare().
le32_compare_signed()
int __acc_cdecl_qsort le32_compare_signed (const void * e1, const void * e2)
Definition at line 653 of file util.cpp.
{
    const int d1 = get_le32_signed(e1);
    const int d2 = get_le32_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le32_signed().
Referenced by LEPolicy::u32_compare_signed().
le64_compare()
int __acc_cdecl_qsort le64_compare (const void * e1, const void * e2)
Definition at line 611 of file util.cpp.
{
    const upx_uint64_t d1 = get_le64(e1);
    const upx_uint64_t d2 = get_le64(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le64().
Referenced by LEPolicy::u64_compare().
le64_compare_signed()
int __acc_cdecl_qsort le64_compare_signed (const void * e1, const void * e2)
Definition at line 659 of file util.cpp.
{
    const upx_int64_t d1 = get_le64_signed(e1);
    const upx_int64_t d2 = get_le64_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le64_signed().
Referenced by LEPolicy::u64_compare_signed().
no_bswap16()
forceinline constexpr unsigned no_bswap16 (unsigned v) constexpr noexcept
Definition at line 283 of file bele.h.
{
    // mask is needed so that for all v: bswap16(bswap16(v)) == no_bswap16(v)
    return v & 0xffff;
}
no_bswap32()
forceinline constexpr unsigned no_bswap32 (unsigned v) constexpr noexcept
Definition at line 287 of file bele.h.
{ return v; }
no_bswap64()
forceinline constexpr upx_uint64_t no_bswap64 (upx_uint64_t v) constexpr noexcept
Definition at line 288 of file bele.h.
{ return v; }
operator+() [1/12]
template<class T > T * operator+ (const BE16 & v, T * ptr) noexcept
operator+() [2/12]
template<class T > T * operator+ (const BE32 & v, T * ptr) noexcept
operator+() [3/12]
template<class T > T * operator+ (const BE64 & v, T * ptr) noexcept
operator+() [4/12]
template<class T > T * operator+ (const LE16 & v, T * ptr) noexcept
operator+() [5/12]
template<class T > T * operator+ (const LE32 & v, T * ptr) noexcept
operator+() [6/12]
template<class T > T * operator+ (const LE64 & v, T * ptr) noexcept
operator+() [7/12]
template<class T > bele_constexpr T * operator+ (T * ptr, const BE16 & v) inline noexcept
global operators (pointer addition/subtraction)
Definition at line 895 of file bele.h.
{
    return ptr + unsigned(v);
}
References ptr.
operator+() [8/12]
template<class T > bele_constexpr T * operator+ (T * ptr, const BE32 & v) inline noexcept
Definition at line 903 of file bele.h.
{
    return ptr + unsigned(v);
}
References ptr.
operator+() [9/12]
template<class T > T * operator+ (T * ptr, const BE64 & v) noexcept
operator+() [10/12]
template<class T > bele_constexpr T * operator+ (T * ptr, const LE16 & v) inline noexcept
Definition at line 911 of file bele.h.
{
    return ptr + unsigned(v);
}
References ptr.
operator+() [11/12]
template<class T > bele_constexpr T * operator+ (T * ptr, const LE32 & v) inline noexcept
Definition at line 919 of file bele.h.
{
    return ptr + unsigned(v);
}
References ptr.
operator+() [12/12]
template<class T > T * operator+ (T * ptr, const LE64 & v) noexcept
operator-() [1/6]
template<class T > bele_constexpr T * operator- (T * ptr, const BE16 & v) inline noexcept
Definition at line 899 of file bele.h.
{
    return ptr - unsigned(v);
}
References ptr.
operator-() [2/6]
template<class T > bele_constexpr T * operator- (T * ptr, const BE32 & v) inline noexcept
Definition at line 907 of file bele.h.
{
    return ptr - unsigned(v);
}
References ptr.
operator-() [3/6]
template<class T > T * operator- (T * ptr, const BE64 & v) noexcept
operator-() [4/6]
template<class T > bele_constexpr T * operator- (T * ptr, const LE16 & v) inline noexcept
Definition at line 915 of file bele.h.
{
    return ptr - unsigned(v);
}
References ptr.
operator-() [5/6]
template<class T > bele_constexpr T * operator- (T * ptr, const LE32 & v) inline noexcept
Definition at line 923 of file bele.h.
{
    return ptr - unsigned(v);
}
References ptr.
operator-() [6/6]
template<class T > T * operator- (T * ptr, const LE64 & v) noexcept
set_be16()
REQUIRE_XE16 bele_constexpr void set_be16 (XE16 * p, unsigned v) inline noexcept
Definition at line 336 of file bele.h.
{ set_ne16(p, ne16_to_be16(v)); }
References ne16_to_be16, and set_ne16().
Referenced by ElfLinkerM68k::alignCode(), f_ct16_e8_bswap_le(), f_ct16_e8e9_bswap_le(), f_ct16_e9_bswap_le(), f_ctsw16_e8_e9(), f_ctsw16_e9_e8(), f_sw16_e8(), f_sw16_e8e9(), f_sw16_e9(), find_be16(), BE16::make(), BE16::operator&=(), BE16::operator*=(), BE16::operator+=(), BE16::operator-=(), BE16::operator/=(), BE16::operator<<=(), BE16::operator=(), BE16::operator>>=(), BE16::operator^=(), BE16::operator|=(), Packer::patch_be16(), ElfLinkerArmBE::relocate1(), ElfLinkerM68k::relocate1(), ElfLinkerMipsBE::relocate1(), ElfLinkerPpc64::relocate1(), BEPolicy::set16(), u_ct16_e8_bswap_be(), u_ct16_e8e9_bswap_be(), and u_ct16_e9_bswap_be().
set_be24() [1/2]
constexpr void set_be24 (byte * p, unsigned v) inline constexpr noexcept
Definition at line 362 of file bele.h.
{ upx::compile_time::set_be24(p, v); }
References upx::compile_time::set_be24().
Referenced by f_ct24arm_be(), ElfLinkerArmBE::relocate1(), BEPolicy::set24(), set_be24(), and u_ct24arm_be().
set_be24() [2/2]
REQUIRE_XE24 forceinline bele_constexpr void set_be24 (XE24 * p, unsigned v) noexcept
Definition at line 374 of file bele.h.
{
    set_be24(upx::ptr_static_cast<byte *>(p), v);
}
References set_be24().
set_be32()
REQUIRE_XE32 bele_constexpr void set_be32 (XE32 * p, unsigned v) inline noexcept
Definition at line 338 of file bele.h.
{ set_ne32(p, ne32_to_be32(v)); }
References ne32_to_be32, and set_ne32().
Referenced by F(), f_ct32_e8_bswap_le(), f_ct32_e8e9_bswap_le(), f_ct32_e9_bswap_le(), f_ctsw32_e8_e9(), f_ctsw32_e9_e8(), f_sw32_e8(), f_sw32_e8e9(), f_sw32_e9(), find_be32(), BE32::make(), BE32::operator&=(), BE32::operator*=(), BE32::operator+=(), BE32::operator-=(), BE32::operator/=(), BE32::operator<<=(), BE32::operator=(), BE32::operator>>=(), BE32::operator^=(), BE32::operator|=(), Packer::optimizeReloc(), PackVmlinuxBase< TElfClass >::pack(), Packer::patch_be32(), PackHeader::putPackHeader(), ElfLinkerArmBE::relocate1(), ElfLinkerM68k::relocate1(), ElfLinkerMipsBE::relocate1(), ElfLinkerPpc32::relocate1(), ElfLinkerPpc64::relocate1(), BEPolicy::set32(), TEST_CASE(), u_ct32_e8_bswap_be(), u_ct32_e8e9_bswap_be(), u_ct32_e9_bswap_be(), and Packer::unoptimizeReloc().
set_be64()
REQUIRE_XE64 bele_constexpr void set_be64 (XE64 * p, upx_uint64_t v) inline noexcept
Definition at line 340 of file bele.h.
{
    set_ne64(p, ne64_to_be64(v));
}
References ne64_to_be64, and set_ne64().
Referenced by find_be64(), BE64::make(), BE64::operator&=(), BE64::operator*=(), BE64::operator+=(), BE64::operator-=(), BE64::operator/=(), BE64::operator<<=(), BE64::operator=(), BE64::operator>>=(), BE64::operator^=(), BE64::operator|=(), Packer::optimizeReloc(), ElfLinkerPpc64::relocate1(), BEPolicy::set64(), TEST_CASE(), and Packer::unoptimizeReloc().
set_le14_5()
REQUIRE_XE32 bele_constexpr void set_le14_5 (XE32 * p, unsigned v) inline noexcept
Definition at line 406 of file bele.h.
{
    set_le32(p, (get_le32(p) & 0xfff8001f) | ((v & 0x00003fff) << 5));
}
References get_le32(), and set_le32().
set_le16()
REQUIRE_XE16 bele_constexpr void set_le16 (XE16 * p, unsigned v) inline noexcept
Definition at line 344 of file bele.h.
{ set_ne16(p, ne16_to_le16(v)); }
References ne16_to_le16, and set_ne16().
Referenced by PackWcle::decodeEntryTable(), PackWcle::decodeFixups(), PackWcle::encodeEntryTable(), PackWcle::encodeFixups(), f_ct16_e8(), f_ct16_e8_bswap_be(), f_ct16_e8e9(), f_ct16_e8e9_bswap_be(), f_ct16_e9(), f_ct16_e9_bswap_be(), find_le16(), LE16::make(), LE16::operator&=(), LE16::operator*=(), LE16::operator+=(), LE16::operator-=(), LE16::operator/=(), LE16::operator<<=(), LE16::operator=(), LE16::operator>>=(), LE16::operator^=(), LE16::operator|=(), optimize_relocs(), PackExe::pack(), PeFile::pack0(), PackLinuxElf::pack2_shlib_overlay_init(), Packer::patch_le16(), PeFile::processImports0(), PeFile::processResources(), PackHeader::putPackHeader(), PeFile::rebuildResources(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerArmLE::relocate1(), ElfLinkerMipsLE::relocate1(), ElfLinkerPpc64le::relocate1(), ElfLinkerX86::relocate1(), LEPolicy::set16(), u_ct16_e8(), u_ct16_e8_bswap_le(), u_ct16_e8e9(), u_ct16_e8e9_bswap_le(), u_ct16_e9(), u_ct16_e9_bswap_le(), u_ctsw16_e8_e9(), u_ctsw16_e9_e8(), u_sw16_e8(), u_sw16_e8e9(), u_sw16_e9(), and PackExe::unpack().
set_le19_5()
REQUIRE_XE32 bele_constexpr void set_le19_5 (XE32 * p, unsigned v) inline noexcept
Definition at line 402 of file bele.h.
{
    set_le32(p, (get_le32(p) & 0xff00001f) | ((v & 0x0007ffff) << 5));
}
References get_le32(), and set_le32().
set_le24() [1/2]
constexpr void set_le24 (byte * p, unsigned v) inline constexpr noexcept
Definition at line 363 of file bele.h.
{ upx::compile_time::set_le24(p, v); }
References upx::compile_time::set_le24().
Referenced by f_ct24arm_le(), PackHeader::putPackHeader(), ElfLinkerArmLE::relocate1(), LEPolicy::set24(), set_le24(), and u_ct24arm_le().
set_le24() [2/2]
REQUIRE_XE24 forceinline bele_constexpr void set_le24 (XE24 * p, unsigned v) noexcept
Definition at line 378 of file bele.h.
{
    set_le24(upx::ptr_static_cast<byte *>(p), v);
}
References set_le24().
set_le26()
REQUIRE_XE32 bele_constexpr void set_le26 (XE32 * p, unsigned v) inline noexcept
Definition at line 394 of file bele.h.
{
    // preserve the top 6 bits
    //   set_le32(p, (get_le32(p) & 0xfc000000) | (v & 0x03ffffff));
    // optimized version, saving a runtime bswap32
    set_ne32(p, (get_ne32(p) & ne32_to_le32(0xfc000000)) |
                    (ne32_to_le32(v) & ne32_to_le32(0x03ffffff)));
}
References get_ne32(), ne32_to_le32, and set_ne32().
Referenced by f_ct26arm_le(), u_ct26arm_le(), and upx_compiler_sanity_check().
set_le32()
REQUIRE_XE32 bele_constexpr void set_le32 (XE32 * p, unsigned v) inline noexcept
Definition at line 346 of file bele.h.
{ set_ne32(p, ne32_to_le32(v)); }
References ne32_to_le32, and set_ne32().
Referenced by PeFile::Export::build(), PackWcle::decodeEntryTable(), PackWcle::decodeFixupPageTable(), PackWcle::decodeFixups(), PackWcle::encodeEntryTable(), PackWcle::encodeFixupPageTable(), F(), f_ct32_e8(), f_ct32_e8_bswap_be(), f_ct32_e8e9(), f_ct32_e8e9_bswap_be(), f_ct32_e9(), f_ct32_e9_bswap_be(), find_le32(), LE32::make(), LE32::operator&=(), LE32::operator*=(), LE32::operator+=(), LE32::operator-=(), LE32::operator/=(), LE32::operator<<=(), LE32::operator=(), LE32::operator>>=(), LE32::operator^=(), LE32::operator|=(), Packer::optimizeReloc(), PackExe::pack(), PackTmt::pack(), PackUnix::pack(), PackWcle::pack(), PeFile::pack0(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), Packer::patch_le32(), PackWcle::preprocessFixups(), PeFile::processImports0(), PeFile32::processRelocs(), PeFile::processResources(), PeFile::processTls1(), PackHeader::putPackHeader(), PeFile::rebuildRelocs(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerArmLE::relocate1(), ElfLinkerMipsLE::relocate1(), ElfLinkerPpc64le::relocate1(), ElfLinkerX86::relocate1(), LEPolicy::set32(), set_le14_5(), set_le19_5(), TEST_CASE(), u_ct32_e8(), u_ct32_e8_bswap_le(), u_ct32_e8e9(), u_ct32_e8e9_bswap_le(), u_ct32_e9(), u_ct32_e9_bswap_le(), u_ctsw32_e8_e9(), u_ctsw32_e9_e8(), u_sw32_e8(), u_sw32_e8e9(), u_sw32_e9(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackTmt::unpack(), and PackUnix::writePackHeader().
set_le64()
REQUIRE_XE64 bele_constexpr void set_le64 (XE64 * p, upx_uint64_t v) inline noexcept
Definition at line 348 of file bele.h.
{
    set_ne64(p, ne64_to_le64(v));
}
References ne64_to_le64, and set_ne64().
Referenced by find_le64(), LE64::make(), LE64::operator&=(), LE64::operator*=(), LE64::operator+=(), LE64::operator-=(), LE64::operator/=(), LE64::operator<<=(), LE64::operator=(), LE64::operator>>=(), LE64::operator^=(), LE64::operator|=(), PeFile64::processRelocs(), PeFile::rebuildRelocs(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerPpc64le::relocate1(), LEPolicy::set64(), and TEST_CASE().
set_ne16() [1/2]
forceinline bele_constexpr void set_ne16 (byte * p, unsigned v) noexcept
Definition at line 150 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
    if (upx_is_constant_evaluated())
        upx::compile_time::set_ne16(p, upx_uint16_t(v & 0xffff));
    else
#endif
    {
        upx_uint16_t vv = upx_uint16_t(v & 0xffff);
        upx_memcpy_inline(p, &vv, sizeof(vv));
    }
}
References upx::compile_time::set_ne16(), and upx_memcpy_inline.
Referenced by set_be16(), set_le16(), set_ne16(), and upx_compiler_sanity_check().
set_ne16() [2/2]
REQUIRE_XE16 forceinline bele_constexpr void set_ne16 (XE16 * p, unsigned v) noexcept
Definition at line 206 of file bele.h.
{
    set_ne16(upx::ptr_static_cast<byte *>(p), v);
}
References set_ne16().
set_ne32() [1/2]
forceinline bele_constexpr void set_ne32 (byte * p, unsigned v) noexcept
Definition at line 162 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
    if (upx_is_constant_evaluated())
        upx::compile_time::set_ne32(p, v);
    else
#endif
    {
        upx_uint32_t vv = v;
        upx_memcpy_inline(p, &vv, sizeof(vv));
    }
}
References upx::compile_time::set_ne32(), and upx_memcpy_inline.
Referenced by MemBuffer::alloc(), MemBuffer::dealloc(), reloc_entry_encode(), set_be32(), set_le26(), set_le32(), set_ne32(), TEST_CASE(), and upx_compiler_sanity_check().
set_ne32() [2/2]
REQUIRE_XE32 forceinline bele_constexpr void set_ne32 (XE32 * p, unsigned v) noexcept
Definition at line 211 of file bele.h.
{
    set_ne32(upx::ptr_static_cast<byte *>(p), v);
}
References set_ne32().
set_ne64() [1/2]
forceinline bele_constexpr void set_ne64 (byte * p, upx_uint64_t v) noexcept
Definition at line 174 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
    if (upx_is_constant_evaluated())
        upx::compile_time::set_ne64(p, v);
    else
#endif
    {
        upx_uint64_t vv = v;
        upx_memcpy_inline(p, &vv, sizeof(vv));
    }
}
References upx::compile_time::set_ne64(), and upx_memcpy_inline.
Referenced by set_be64(), set_le64(), set_ne64(), and upx_compiler_sanity_check().
set_ne64() [2/2]
REQUIRE_XE64 forceinline bele_constexpr void set_ne64 (XE64 * p, upx_uint64_t v) noexcept
Definition at line 216 of file bele.h.
{
    set_ne64(upx::ptr_static_cast<byte *>(p), v);
}
References set_ne64().
sign_extend() [1/2]
forceinline constexpr int sign_extend (unsigned v, unsigned bits) constexpr noexcept
get signed values
Definition at line 414 of file bele.h.
{
#if (ACC_ARCH_M68K) // no barrel shifter
    const unsigned sign_bit = 1u << (bits - 1);
    return ACC_ICAST(int, (v & (sign_bit - 1)) - (v & sign_bit));
#else
    return ACC_ICAST(int, v << (32 - bits)) >> (32 - bits);
#endif
}
References ACC_ICAST.
Referenced by get_be16_signed(), get_be24_signed(), get_be32_signed(), get_be64_signed(), get_le16_signed(), get_le24_signed(), get_le32_signed(), get_le64_signed(), and upx_compiler_sanity_check().
sign_extend() [2/2]
forceinline constexpr upx_int64_t sign_extend (upx_uint64_t v, unsigned bits) constexpr noexcept
Definition at line 423 of file bele.h.
{
#if (ACC_ARCH_M68K) // no barrel shifter
    const upx_uint64_t sign_bit = upx_uint64_t(1) << (bits - 1);
    return ACC_ICAST(upx_int64_t, (v & (sign_bit - 1)) - (v & sign_bit));
#else
    return ACC_ICAST(upx_int64_t, v << (64 - bits)) >> (64 - bits);
#endif
}
References ACC_ICAST.
TT_UPX_IS_INTEGRAL() [1/6]
TT_UPX_IS_INTEGRAL (BE16)
TT_UPX_IS_INTEGRAL() [2/6]
TT_UPX_IS_INTEGRAL (BE32)
TT_UPX_IS_INTEGRAL() [3/6]
TT_UPX_IS_INTEGRAL (BE64)
TT_UPX_IS_INTEGRAL() [4/6]
TT_UPX_IS_INTEGRAL (LE16)
TT_UPX_IS_INTEGRAL() [5/6]
TT_UPX_IS_INTEGRAL (LE32)
TT_UPX_IS_INTEGRAL() [6/6]
TT_UPX_IS_INTEGRAL (LE64)