My Project: src/stub/src/include/bsd.h File Reference
bsd.h File Reference
Classes
struct timeval
struct timespec
struct Elf32_Ehdr
struct Elf64_Ehdr
struct Elf32_Phdr
struct Elf64_Phdr
struct Elf32_auxv_t
struct Elf64_auxv_t
struct b_info
struct l_info
struct p_info
Macros
#define ACC_UNUSED(var) ((void) var)
#define SEEK_SET 0
#define SEEK_CUR 1
#define O_RDONLY 00
#define O_WRONLY 01
#define O_RDWR 02
#define O_CREAT 0100
#define O_EXCL 0200
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define F_OK 0
#define F_GETFD 1
#define F_SETFD 2
#define FD_CLOEXEC 1
#define ENOENT 2
#define EINTR 4
#define PROT_READ 0x1
#define PROT_WRITE 0x2
#define PROT_EXEC 0x4
#define PROT_NONE 0x0
#define MAP_SHARED 0x01
#define MAP_PRIVATE 0x02
#define MAP_FIXED 0x10
#define MAP_ANONYMOUS 0x1000 /* differs from Linux */
#define MAP_DENYWRITE 0x0 /* does not exist on BSD ? */
#define EI_NIDENT 16
#define AT_NULL 0
#define AT_IGNORE 1
#define AT_PHDR 3
#define AT_PHENT 4
#define AT_PHNUM 5
#define AT_PAGESZ 6
#define AT_BASE 7
#define AT_ENTRY 9
#define ET_EXEC 2
#define ET_DYN 3
#define PF_X 1
#define PF_W 2
#define PF_R 4
#define PT_LOAD 1
#define PT_INTERP 3
#define PT_PHDR 6
#define OVERHEAD 2048
UPX stuff.
#define UPX_MAGIC_LE32 0x21585055
#define UPX2 0x32585055
#define UPX3 0x33585055
#define UPX4 0x34585055
#define nrv_byte unsigned char
#define nrv_bytep unsigned char *
#define nrv_voidp void *
#define CONST_CAST(type, var) ((type) ((uintptr_t) (var)))
#define __attribute_cdecl /*empty*/
Typedefs
typedef long ptrdiff_t
typedef long ssize_t
typedef unsigned long size_t
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef int int32_t
typedef unsigned uint32_t
typedef long long int64_t
typedef unsigned long long uint64_t
typedef size_t uintptr_t
typedef long off_t
typedef void * caddr_t
typedef unsigned pid_t
typedef uint16_t Elf32_Half
<elf.h>
typedef uint16_t Elf64_Half
typedef uint32_t Elf32_Word
typedef int32_t Elf32_Sword
typedef uint32_t Elf64_Word
typedef int32_t Elf64_Sword
typedef uint64_t Elf32_Xword
typedef int64_t Elf32_Sxword
typedef uint64_t Elf64_Xword
typedef int64_t Elf64_Sxword
typedef uint32_t Elf32_Addr
typedef uint64_t Elf64_Addr
typedef uint32_t Elf32_Off
typedef uint64_t Elf64_Off
typedef uint16_t Elf32_Section
typedef uint16_t Elf64_Section
typedef Elf32_Half Elf32_Versym
typedef Elf64_Half Elf64_Versym
typedef int nrv_int
typedef int nrv_int32
typedef unsigned int nrv_uint
typedef unsigned int nrv_uint32
Functions
int access (char const *, int)
syscalls
void * brk (void *)
int close (int)
int execve (char const *, char const *const *, char const *const *)
void exit (int) __attribute__((__noreturn__
int fcntl (int, int, long)
int ftruncate (int, size_t)
pid_t fork (void)
pid_t getpid (void)
int gettimeofday (struct timeval *, void *)
void * mmap (void *, size_t, int, int, int, off_t)
int munmap (void *, size_t)
int mprotect (void const *, size_t, int)
int nanosleep (struct timespec const *, struct timespec *)
int open (char const *, unsigned, unsigned)
ssize_t read (int, void *, size_t)
pid_t waitpid (pid_t, int *, int)
ssize_t write (int, void const *, size_t)
int unlink (char const *)
Variables
void __nothrow__
Macro Definition Documentation
__attribute_cdecl
#define __attribute_cdecl /*empty*/
Definition at line 362 of file bsd.h.
ACC_UNUSED
#define ACC_UNUSED (var) ((void) var)
Definition at line 44 of file bsd.h.
AT_BASE
#define AT_BASE 7
Definition at line 270 of file bsd.h.
AT_ENTRY
#define AT_ENTRY 9
Definition at line 271 of file bsd.h.
AT_IGNORE
#define AT_IGNORE 1
Definition at line 265 of file bsd.h.
AT_NULL
#define AT_NULL 0
Definition at line 264 of file bsd.h.
AT_PAGESZ
#define AT_PAGESZ 6
Definition at line 269 of file bsd.h.
AT_PHDR
#define AT_PHDR 3
Definition at line 266 of file bsd.h.
AT_PHENT
#define AT_PHENT 4
Definition at line 267 of file bsd.h.
AT_PHNUM
#define AT_PHNUM 5
Definition at line 268 of file bsd.h.
CONST_CAST
#define CONST_CAST (type, var) ((type) ((uintptr_t) (var)))
Definition at line 348 of file bsd.h.
EI_NIDENT
#define EI_NIDENT 16
Definition at line 185 of file bsd.h.
EINTR
#define EINTR 4
Definition at line 121 of file bsd.h.
ENOENT
#define ENOENT 2
Definition at line 120 of file bsd.h.
ET_DYN
#define ET_DYN 3
Definition at line 274 of file bsd.h.
ET_EXEC
#define ET_EXEC 2
Definition at line 273 of file bsd.h.
F_GETFD
#define F_GETFD 1
Definition at line 115 of file bsd.h.
F_OK
#define F_OK 0
Definition at line 113 of file bsd.h.
F_SETFD
#define F_SETFD 2
Definition at line 116 of file bsd.h.
FD_CLOEXEC
#define FD_CLOEXEC 1
Definition at line 117 of file bsd.h.
MAP_ANONYMOUS
#define MAP_ANONYMOUS 0x1000 /* differs from Linux */
Definition at line 132 of file bsd.h.
MAP_DENYWRITE
#define MAP_DENYWRITE 0x0 /* does not exist on BSD ? */
Definition at line 133 of file bsd.h.
MAP_FIXED
#define MAP_FIXED 0x10
Definition at line 131 of file bsd.h.
MAP_PRIVATE
#define MAP_PRIVATE 0x02
Definition at line 130 of file bsd.h.
MAP_SHARED
#define MAP_SHARED 0x01
Definition at line 129 of file bsd.h.
nrv_byte
#define nrv_byte unsigned char
Definition at line 316 of file bsd.h.
nrv_bytep
#define nrv_bytep unsigned char *
Definition at line 317 of file bsd.h.
nrv_voidp
#define nrv_voidp void *
Definition at line 318 of file bsd.h.
O_CREAT
#define O_CREAT 0100
Definition at line 107 of file bsd.h.
O_EXCL
#define O_EXCL 0200
Definition at line 108 of file bsd.h.
O_RDONLY
#define O_RDONLY 00
Definition at line 104 of file bsd.h.
O_RDWR
#define O_RDWR 02
Definition at line 106 of file bsd.h.
O_WRONLY
#define O_WRONLY 01
Definition at line 105 of file bsd.h.
OVERHEAD
#define OVERHEAD 2048
UPX stuff.
Definition at line 290 of file bsd.h.
PF_R
#define PF_R 4
Definition at line 278 of file bsd.h.
PF_W
#define PF_W 2
Definition at line 277 of file bsd.h.
PF_X
#define PF_X 1
Definition at line 276 of file bsd.h.
PROT_EXEC
#define PROT_EXEC 0x4
Definition at line 126 of file bsd.h.
PROT_NONE
#define PROT_NONE 0x0
Definition at line 127 of file bsd.h.
PROT_READ
#define PROT_READ 0x1
Definition at line 124 of file bsd.h.
PROT_WRITE
#define PROT_WRITE 0x2
Definition at line 125 of file bsd.h.
PT_INTERP
#define PT_INTERP 3
Definition at line 281 of file bsd.h.
PT_LOAD
#define PT_LOAD 1
Definition at line 280 of file bsd.h.
PT_PHDR
#define PT_PHDR 6
Definition at line 282 of file bsd.h.
R_OK
#define R_OK 4
Definition at line 110 of file bsd.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 102 of file bsd.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 101 of file bsd.h.
UPX2
#define UPX2 0x32585055
Definition at line 297 of file bsd.h.
UPX3
#define UPX3 0x33585055
Definition at line 298 of file bsd.h.
UPX4
#define UPX4 0x34585055
Definition at line 299 of file bsd.h.
UPX_MAGIC_LE32
#define UPX_MAGIC_LE32 0x21585055
Definition at line 292 of file bsd.h.
W_OK
#define W_OK 2
Definition at line 111 of file bsd.h.
X_OK
#define X_OK 1
Definition at line 112 of file bsd.h.
Typedef Documentation
caddr_t
typedef void* caddr_t
Definition at line 76 of file bsd.h.
Elf32_Addr
typedef uint32_t Elf32_Addr
Definition at line 175 of file bsd.h.
Elf32_Half
typedef uint16_t Elf32_Half
<elf.h>
Definition at line 165 of file bsd.h.
Elf32_Off
typedef uint32_t Elf32_Off
Definition at line 177 of file bsd.h.
Elf32_Section
typedef uint16_t Elf32_Section
Definition at line 179 of file bsd.h.
Elf32_Sword
typedef int32_t Elf32_Sword
Definition at line 168 of file bsd.h.
Elf32_Sxword
typedef int64_t Elf32_Sxword
Definition at line 172 of file bsd.h.
Elf32_Versym
typedef Elf32_Half Elf32_Versym
Definition at line 181 of file bsd.h.
Elf32_Word
typedef uint32_t Elf32_Word
Definition at line 167 of file bsd.h.
Elf32_Xword
typedef uint64_t Elf32_Xword
Definition at line 171 of file bsd.h.
Elf64_Addr
typedef uint64_t Elf64_Addr
Definition at line 176 of file bsd.h.
Elf64_Half
typedef uint16_t Elf64_Half
Definition at line 166 of file bsd.h.
Elf64_Off
typedef uint64_t Elf64_Off
Definition at line 178 of file bsd.h.
Elf64_Section
typedef uint16_t Elf64_Section
Definition at line 180 of file bsd.h.
Elf64_Sword
typedef int32_t Elf64_Sword
Definition at line 170 of file bsd.h.
Elf64_Sxword
typedef int64_t Elf64_Sxword
Definition at line 174 of file bsd.h.
Elf64_Versym
typedef Elf64_Half Elf64_Versym
Definition at line 182 of file bsd.h.
Elf64_Word
typedef uint32_t Elf64_Word
Definition at line 169 of file bsd.h.
Elf64_Xword
typedef uint64_t Elf64_Xword
Definition at line 173 of file bsd.h.
int32_t
typedef int int32_t
Definition at line 58 of file bsd.h.
int64_t
typedef long long int64_t
Definition at line 67 of file bsd.h.
nrv_int
typedef int nrv_int
Definition at line 312 of file bsd.h.
nrv_int32
typedef int nrv_int32
Definition at line 313 of file bsd.h.
nrv_uint
typedef unsigned int nrv_uint
Definition at line 314 of file bsd.h.
nrv_uint32
typedef unsigned int nrv_uint32
Definition at line 315 of file bsd.h.
off_t
typedef long off_t
Definition at line 73 of file bsd.h.
pid_t
typedef unsigned pid_t
Definition at line 77 of file bsd.h.
ptrdiff_t
typedef long ptrdiff_t
Definition at line 52 of file bsd.h.
size_t
typedef unsigned long size_t
Definition at line 54 of file bsd.h.
ssize_t
typedef long ssize_t
Definition at line 53 of file bsd.h.
uint16_t
typedef unsigned short uint16_t
Definition at line 57 of file bsd.h.
uint32_t
typedef unsigned uint32_t
Definition at line 59 of file bsd.h.
uint64_t
typedef unsigned long long uint64_t
Definition at line 68 of file bsd.h.
uint8_t
typedef unsigned char uint8_t
Definition at line 56 of file bsd.h.
uintptr_t
typedef size_t uintptr_t
Definition at line 70 of file bsd.h.
Function Documentation
access()
int access (char const * , int)
syscalls
brk()
void * brk (void *)
close()
int close (int)
Referenced by FileBase::close_noexcept(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), and file_exists().
execve()
int execve (char const * , char const *const * , char const *const *)
exit()
void exit (int)
Referenced by do_exit().
fcntl()
int fcntl (int , int , long)
fork()
pid_t fork (void)
ftruncate()
int ftruncate (int , size_t)
getpid()
pid_t getpid (void)
Referenced by upx_rand_init().
gettimeofday()
int gettimeofday (struct timeval * , void *)
Referenced by upx_rand_init().
mmap()
void * mmap (void * , size_t , int , int , int , off_t)
mprotect()
int mprotect (void const * , size_t , int)
munmap()
int munmap (void * , size_t)
nanosleep()
int nanosleep (struct timespec const * , struct timespec *)
open()
int open (char const * , unsigned , unsigned)
Referenced by FileBase::do_sopen(), and file_exists().
read()
ssize_t read (int , void * , size_t)
unlink()
int unlink (char const *)
Referenced by FileBase::unlink_noexcept().
waitpid()
pid_t waitpid (pid_t , int * , int)
write()
ssize_t write (int , void const * , size_t)
Variable Documentation
__nothrow__
void __nothrow__
Definition at line 144 of file bsd.h.