My Project: PackMaster Class Reference
PackMaster Class Reference final
dispatch to a concrete subclass of class PackerBase; see work.cpp
#include <packmast.h>
Public Types
typedef tribool(* visit_func_t) (PackerBase *pb, void *user)
Public Member Functions
PackMaster (InputFile *f, Options *o=nullptr) noexcept
~PackMaster () noexcept
void pack (OutputFile *fo) may_throw
delegation from work.cpp
void unpack (OutputFile *fo) may_throw
void test () may_throw
void list () may_throw
void fileInfo () may_throw
Static Public Member Functions
static noinline PackerBase * visitAllPackers (visit_func_t, InputFile *f, const Options *, void *user) may_throw
Private Member Functions
OwningPointer (PackerBase) packer
Static Private Member Functions
static PackerBase * getPacker (InputFile *f) may_throw
static PackerBase * getUnpacker (InputFile *f) may_throw
Private Attributes
InputFile *const fi
Options local_options
Options * saved_opt = nullptr
Detailed Description
dispatch to a concrete subclass of class PackerBase; see work.cpp
Definition at line 38 of file packmast.h.
Member Typedef Documentation
visit_func_t
typedef tribool(* PackMaster::visit_func_t) (PackerBase *pb, void *user)
Definition at line 49 of file packmast.h.
Constructor & Destructor Documentation
PackMaster()
PackMaster::PackMaster (InputFile * f, Options * o = nullptr) explicit noexcept
Definition at line 62 of file packmast.cpp.
                                                        : fi(f) {
    // replace global options with local options
    if (o != nullptr) {
#if WITH_THREADS
        // TODO later: check for possible "noexcept" violation here
        std::lock_guard<std::mutex> lock(opt_lock_mutex);
#endif
        saved_opt = o;
        memcpy(&this->local_options, o, sizeof(*o)); // struct copy
        opt = &this->local_options;
    }
}
References memcpy(), and opt.
~PackMaster()
PackMaster::~PackMaster () noexcept
Definition at line 75 of file packmast.cpp.
{
    upx::owner_delete(packer);
    // restore global options
    if (saved_opt != nullptr) {
#if WITH_THREADS
        // TODO later: check for possible "noexcept" violation here
        std::lock_guard<std::mutex> lock(opt_lock_mutex);
#endif
        opt = saved_opt;
        saved_opt = nullptr;
    }
}
References opt, upx::owner_delete(), and saved_opt.
Member Function Documentation
fileInfo()
void PackMaster::fileInfo ()
Definition at line 281 of file packmast.cpp.
{
    assert(packer == nullptr);
    packer = visitAllPackers(try_can_unpack, fi, opt, fi);
    if (!packer)
        packer = visitAllPackers(try_can_pack, fi, opt, fi);
    if (!packer)
        throwUnknownExecutableFormat(nullptr, 1); // make a warning here
    packer->doFileInfo();
}
References fi, opt, throwUnknownExecutableFormat(), try_can_pack(), try_can_unpack(), and visitAllPackers().
Referenced by do_one_file().
getPacker()
PackerBase * PackMaster::getPacker (InputFile * f) static private
Definition at line 239 of file packmast.cpp.
{
    PackerBase *pb = visitAllPackers(try_can_pack, f, opt, f);
    if (!pb)
        throwUnknownExecutableFormat();
    return pb;
}
References opt, throwUnknownExecutableFormat(), and try_can_pack().
getUnpacker()
PackerBase * PackMaster::getUnpacker (InputFile * f) static private
Definition at line 246 of file packmast.cpp.
{
    PackerBase *pb = visitAllPackers(try_can_unpack, f, opt, f);
    if (!pb)
        throwNotPacked();
    return pb;
}
References opt, throwNotPacked(), and try_can_unpack().
Referenced by list(), and test().
list()
void PackMaster::list ()
Definition at line 275 of file packmast.cpp.
{
    assert(packer == nullptr);
    packer = getUnpacker(fi);
    packer->doList();
}
References fi, and getUnpacker().
Referenced by do_one_file().
OwningPointer()
PackMaster::OwningPointer (PackerBase) private
pack()
void PackMaster::pack (OutputFile * fo)
delegation from work.cpp
Definition at line 257 of file packmast.cpp.
{
    assert(packer == nullptr);
    packer = getPacker(fi);
    packer->doPack(fo);
}
Referenced by do_one_file().
test()
void PackMaster::test ()
Definition at line 269 of file packmast.cpp.
{
    assert(packer == nullptr);
    packer = getUnpacker(fi);
    packer->doTest();
}
References fi, and getUnpacker().
Referenced by do_one_file().
unpack()
void PackMaster::unpack (OutputFile * fo)
Definition at line 263 of file packmast.cpp.
{
    assert(packer == nullptr);
    packer = getUnpacker(fi);
    packer->doUnpack(fo);
}
Referenced by do_one_file().
visitAllPackers()
PackerBase * PackMaster::visitAllPackers (visit_func_t func, InputFile * f, const Options * o, void * user) static
Definition at line 135 of file packmast.cpp.
{
#define VISIT(Klass)                                                                               \
    do {                                                                                           \
        static_assert(std::is_class_v<Klass>);                                                     \
        static_assert(std::is_nothrow_destructible_v<Klass>);                                      \
        auto pb = std::unique_ptr<PackerBase>(new Klass(f));                                       \
        if (o->debug.debug_level)                                                                  \
            fprintf(stderr, "visitAllPackers: (ver=%d, fmt=%3d) %s\n", pb->getVersion(),           \
                    pb->getFormat(), #Klass);                                                      \
        pb->assertPacker();                                                                        \
        tribool r = func(pb.get(), user);                                                          \
        if (r)                                                                                     \
            return pb.release(); /* success */                                                     \
        if (r.isThird())                                                                           \
            return nullptr; /* stop and fail early */                                              \
    } while (0)
    // NOTE: order of tries is important !!!
    //
    // .exe
    //
    if (!o->dos_exe.force_stub) {
        // dos32
        VISIT(PackDjgpp2);
        VISIT(PackTmt);
        VISIT(PackWcle);
        // Windows
        // VISIT(PackW64PeArm64EC); // NOT YET IMPLEMENTED
        // VISIT(PackW64PeArm64); // NOT YET IMPLEMENTED
        VISIT(PackW64PeAmd64);
        VISIT(PackW32PeI386);
        VISIT(PackWinCeArm);
    }
    VISIT(PackExe); // dos/exe
    //
    // linux kernel
    //
    VISIT(PackVmlinuxARMEL);
    VISIT(PackVmlinuxARMEB);
    VISIT(PackVmlinuxPPC32);
    VISIT(PackVmlinuxPPC64LE);
    VISIT(PackVmlinuxAMD64);
    VISIT(PackVmlinuxI386);
#if (WITH_ZLIB)
    VISIT(PackVmlinuzI386);
    VISIT(PackBvmlinuzI386);
    VISIT(PackVmlinuzARMEL);
#endif
    //
    // linux
    //
    if (!o->o_unix.force_execve) {
        if (o->o_unix.use_ptinterp) {
            VISIT(PackLinuxElf32x86interp);
        }
        VISIT(PackFreeBSDElf32x86);
        VISIT(PackNetBSDElf32x86);
        VISIT(PackOpenBSDElf32x86);
        VISIT(PackLinuxElf32x86);
        VISIT(PackLinuxElf64amd);
        VISIT(PackLinuxElf32armLe);
        VISIT(PackLinuxElf32armBe);
        VISIT(PackLinuxElf64arm);
        VISIT(PackLinuxElf32ppc);
        VISIT(PackLinuxElf64ppc);
        VISIT(PackLinuxElf64ppcle);
        VISIT(PackLinuxElf32mipsel);
        VISIT(PackLinuxElf32mipseb);
        VISIT(PackLinuxI386sh);
    }
    VISIT(PackBSDI386);
    VISIT(PackMachFat);   // cafebabe conflict
    VISIT(PackLinuxI386); // cafebabe conflict
    // Mach (Darwin / macOS)
    VISIT(PackDylibAMD64);
    VISIT(PackMachPPC32); // TODO: this works with upx 3.91..3.94 but got broken in 3.95; FIXME
    VISIT(PackMachI386);
    VISIT(PackMachAMD64);
    VISIT(PackMachARMEL);
    VISIT(PackMachARM64EL);
    // 2010-03-12  omit these because PackMachBase<T>::pack4dylib (p_mach.cpp)
    // does not understand what the Darwin (Apple Mac OS X) dynamic loader
    // assumes about .dylib file structure.
    //   VISIT(PackDylibI386);
    //   VISIT(PackDylibPPC32);
    //
    // misc
    //
    VISIT(PackTos); // atari/tos
    VISIT(PackPs1); // ps1/exe
    VISIT(PackSys); // dos/sys
    VISIT(PackCom); // dos/com
    return nullptr;
#undef VISIT
}
References VISIT.
Referenced by fileInfo(), and list_all_packers().
Member Data Documentation
fi
InputFile* const PackMaster::fi private
Definition at line 58 of file packmast.h.
Referenced by fileInfo(), list(), and test().
local_options
Options PackMaster::local_options private
Definition at line 60 of file packmast.h.
saved_opt
Options* PackMaster::saved_opt = nullptr private
Definition at line 61 of file packmast.h.
Referenced by ~PackMaster().
The documentation for this class was generated from the following files:
src/packmast.h
src/packmast.cpp