My Project: ElfLinkerArmBE Class Reference
ElfLinkerArmBE Class Reference final
#include <linker.h>
Public Member Functions
ElfLinkerArmBE () noexcept
Public Member Functions inherited from ElfLinker
ElfLinker (const N_BELE_RTP::AbstractPolicy *b=&N_BELE_RTP::le_policy) noexcept
ElfLinker.
virtual ~ElfLinker () noexcept
void init (const void *pdata, int plen, unsigned pxtra=0)
int addLoader (const char *sname)
void addLoader (const char *s, va_list ap)
void addLoaderVA (const char *s,...)
Section * addSection (const char *sname, const void *sdata, int slen, unsigned p2align)
int getSection (const char *sname, int *slen=nullptr) const
int getSectionSize (const char *sname) const
byte * getLoader (int *llen=nullptr) const
void defineSymbol (const char *name, upx_uint64_t value)
Symbol * findSymbol (const char *name, bool fatal=true) const
upx_uint64_t getSymbolOffset (const char *) const
void dumpSymbol (const Symbol *, unsigned flags, FILE *fp) const
void dumpSymbols (unsigned flags=0, FILE *fp=nullptr) const
void alignWithByte (unsigned len, byte b)
virtual void alignCode (unsigned len)
virtual void alignData (unsigned len)
void defineSymbol (const char *name, int value)
void defineSymbol (const char *name, unsigned value)
void defineSymbol (const char *name, unsigned long value)
Protected Member Functions
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type) override
Protected Member Functions inherited from ElfLinker
void preprocessSections (char *start, char const *end)
void preprocessSymbols (char *start, char const *end)
void preprocessRelocations (char *start, char const *end)
Section * findSection (const char *name, bool fatal=true) const
Symbol * addSymbol (const char *name, const char *section, upx_uint64_t offset)
Relocation * addRelocation (const char *section, unsigned off, const char *type, const char *symbol, upx_uint64_t add)
void relocate ()
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type)
Private Types
typedef ElfLinker super
Additional Inherited Members
Public Attributes inherited from ElfLinker
const N_BELE_RTP::AbstractPolicy *const bele
Protected Attributes inherited from ElfLinker
byte * input = nullptr
int inputlen = 0
byte * output = nullptr
int outputlen = 0
unsigned output_capacity = 0
Section * head = nullptr
Section * tail = nullptr
Section ** sections = nullptr
Symbol ** symbols = nullptr
Relocation ** relocations = nullptr
unsigned nsections = 0
unsigned nsections_capacity = 0
unsigned nsymbols = 0
unsigned nsymbols_capacity = 0
unsigned nrelocations = 0
unsigned nrelocations_capacity = 0
bool reloc_done = false
Detailed Description
Definition at line 171 of file linker.h.
Member Typedef Documentation
super
typedef ElfLinker ElfLinkerArmBE::super private
Definition at line 172 of file linker.h.
Constructor & Destructor Documentation
ElfLinkerArmBE()
ElfLinkerArmBE::ElfLinkerArmBE () inline explicit noexcept
Definition at line 174 of file linker.h.
: super(&N_BELE_RTP::be_policy) {}
Member Function Documentation
relocate1()
void ElfLinkerArmBE::relocate1 (const Relocation * rel, byte * location, upx_uint64_t value, const char * type) override protected virtual
Reimplemented from ElfLinker.
Definition at line 602 of file linker.cpp.
{
    if (!strcmp(type, "R_ARM_PC24") || !strcmp(type, "R_ARM_CALL") ||
        !strcmp(type, "R_ARM_JUMP24")) {
        value -= rel->section->offset + rel->offset;
        set_be24(1 + location, get_be24(1 + location) + value / 4);
    } else if (strcmp(type, "R_ARM_ABS32") == 0) {
        set_be32(location, get_be32(location) + value);
    } else if (strcmp(type, "R_ARM_THM_CALL") == 0 || strcmp(type, "R_ARM_THM_XPC22") == 0 ||
               strcmp(type, "R_ARM_THM_PC22") == 0) {
        value -= rel->section->offset + rel->offset;
        value += ((get_be16(location) & 0x7ff) << 12);
        value += (get_be16(location + 2) & 0x7ff) << 1;
        set_be16(location, 0xf000 + ((value >> 12) & 0x7ff));
        set_be16(location + 2, 0xf800 + ((value >> 1) & 0x7ff));
        //(b, 0xF000 + ((v - 1) / 2) * 0x10000);
        // set_be32(location, get_be32(location) + value / 4);
    } else if (0 == strcmp("R_ARM_ABS8", type)) {
        *location += value;
    } else
        super::relocate1(rel, location, value, type);
}
References get_be16(), get_be24(), get_be32(), ElfLinker::Section::offset, ElfLinker::Relocation::offset, ElfLinker::Relocation::section, set_be16(), set_be24(), set_be32(), and strcmp().
The documentation for this class was generated from the following files:
src/linker.h
src/linker.cpp