My Project: FileBase Class Reference
FileBase Class Reference
#include <file.h>
Public Member Functions
bool close_noexcept () noexcept
void closex () may_throw
bool isOpen () const noexcept
int getFd () const noexcept
const char * getName () const noexcept
virtual upx_off_t seek (upx_off_t off, int whence)
upx_off_t tell () const
virtual upx_off_t st_size () const
virtual void set_extent (upx_off_t offset, upx_off_t length)
Static Public Member Functions
static void chmod (const char *name, int mode) may_throw
static file-related util functions; will throw on error
static void rename (const char *old_, const char *new_) may_throw
static void unlink (const char *name) may_throw
static bool unlink_noexcept (const char *name) noexcept
Public Attributes
struct stat st = {}
Protected Member Functions
FileBase () noexcept=default
virtual ~FileBase () may_throw
FileBase.
bool do_sopen ()
Protected Attributes
int _fd = -1
int _flags = 0
int _shflags = 0
int _mode = 0
const char * _name = nullptr
upx_off_t _offset = 0
upx_off_t _length = 0
Detailed Description
Definition at line 34 of file file.h.
Constructor & Destructor Documentation
FileBase()
FileBase::FileBase () explicit protected default noexcept
~FileBase()
FileBase::~FileBase () protected virtual
FileBase.
Definition at line 75 of file file.cpp.
{
#if 0 && defined(__GNUC__) // debug
    if (isOpen())
        fprintf(stderr, "%s: %s\n", _name, __PRETTY_FUNCTION__);
#endif
    if (std::uncaught_exceptions() == 0)
        closex(); // may_throw
    else
        close_noexcept(); // currently in exception unwinding, use noexcept variant
}
References _name, close_noexcept(), closex(), and isOpen().
Member Function Documentation
chmod()
void FileBase::chmod (const char * name, int mode) static
static file-related util functions; will throw on error
Definition at line 35 of file file.cpp.
{
    assert(name != nullptr && name[0] != 0);
#if HAVE_CHMOD
    if (::chmod(name, mode) != 0)
        throwIOException(name, errno);
#else
    UNUSED(name);
    UNUSED(mode);
    // no error
#endif
}
References chmod(), throwIOException(), and UNUSED.
Referenced by chmod().
close_noexcept()
bool FileBase::close_noexcept () noexcept
Definition at line 109 of file file.cpp.
{
    bool ok = true;
    if (isOpen() && _fd != STDIN_FILENO && _fd != STDOUT_FILENO && _fd != STDERR_FILENO)
        if (::close(_fd) == -1)
            ok = false;
    _fd = -1;
    _flags = 0;
    _mode = 0;
    _name = nullptr;
    _offset = 0;
    _length = 0;
    return ok;
}
References _fd, _flags, _length, _mode, _name, _offset, close(), isOpen(), STDERR_FILENO, STDIN_FILENO, and STDOUT_FILENO.
Referenced by closex(), and ~FileBase().
closex()
void FileBase::closex ()
Definition at line 123 of file file.cpp.
{
    if (!close_noexcept())
        throwIOException("close failed", errno);
}
References close_noexcept(), and throwIOException().
Referenced by anonymous_namespace{work.cpp}::copy_file_contents(), do_one_file(), OutputFile::dump(), OutputFile::openStdout(), InputFile::sopen(), OutputFile::sopen(), and ~FileBase().
do_sopen()
bool FileBase::do_sopen () protected
Definition at line 86 of file file.cpp.
{
    if (_shflags < 0)
        _fd = ::open(_name, _flags, _mode);
    else {
#if (ACC_OS_DOS32) && defined(__DJGPP__)
        _fd = ::open(_name, _flags | _shflags, _mode);
#elif (ACC_ARCH_M68K && ACC_OS_TOS && ACC_CC_GNUC) && defined(__MINT__)
        _fd = ::open(_name, _flags | (_shflags & O_SHMODE), _mode);
#elif defined(SH_DENYRW)
        _fd = ::sopen(_name, _flags, _shflags, _mode);
#else
        throwInternalError("bad usage of do_sopen()");
#endif
    }
    if (_fd < 0)
        return false;
    st.st_size = 0;
    if (::fstat(_fd, &st) != 0)
        throwIOException(_name, errno);
    _length = st.st_size;
    return true;
}
References _fd, _flags, _length, _mode, _name, _shflags, open(), st, throwInternalError(), and throwIOException().
Referenced by InputFile::sopen(), and OutputFile::sopen().
getFd()
int FileBase::getFd () const inline noexcept
Definition at line 43 of file file.h.
{ return _fd; }
References _fd.
Referenced by anonymous_namespace{work.cpp}::copy_file_contents(), do_one_file(), InputFile::dupFd(), and TEST_CASE().
getName()
const char * FileBase::getName () const inline noexcept
Definition at line 44 of file file.h.
{ return _name; }
References _name.
Referenced by PackCom::canPack(), PackExe::canPack(), PackMachFat::canPack(), PackSys::canPack(), PackPs1::checkFileHeader(), PackLinuxI386sh::getShellName(), UiPacker::printInfo(), PeFile::processResources(), PeFile::readSectionHeaders(), UiPacker::startCallback(), UiPacker::uiFileInfoStart(), UiPacker::uiList(), UiPacker::uiPackEnd(), UiPacker::uiTestStart(), and UiPacker::uiUnpackEnd().
isOpen()
bool FileBase::isOpen () const inline noexcept
Definition at line 42 of file file.h.
{ return _fd >= 0; }
References _fd.
Referenced by close_noexcept(), do_one_file(), InputFile::dupFd(), InputFile::read(), seek(), tell(), TEST_CASE(), OutputFile::write(), and ~FileBase().
rename()
void FileBase::rename (const char * old_, const char * new_) static
Definition at line 47 of file file.cpp.
{
#if (ACC_OS_DOS32) && defined(__DJGPP__)
    if (::_rename(old_, new_) != 0)
#else
    if (::rename(old_, new_) != 0)
#endif
        throwIOException("rename error", errno);
}
References rename(), and throwIOException().
Referenced by do_one_file(), and rename().
seek()
upx_off_t FileBase::seek (upx_off_t off, int whence) virtual
Reimplemented in InputFile, and OutputFile.
Definition at line 129 of file file.cpp.
{
    if (!isOpen())
        throwIOException("bad seek 1");
    mem_size_assert(1, off >= 0 ? off : -off); // sanity check
    if (whence == SEEK_SET) {
        if (off < 0)
            throwIOException("bad seek 2");
        off += _offset;
    } else if (whence == SEEK_END) {
        if (off > 0)
            throwIOException("bad seek 3");
        off += _offset + _length;
        whence = SEEK_SET;
    } else if (whence == SEEK_CUR) {
    } else
        throwInternalError("bad seek: whence");
    upx_off_t l = ::lseek(_fd, off, whence);
    if (l < 0)
        throwIOException("seek error", errno);
    return l - _offset;
}
References _fd, _length, _offset, isOpen(), lseek(), mem_size_assert(), SEEK_CUR, SEEK_END, SEEK_SET, throwInternalError(), and throwIOException().
Referenced by InputFile::seek(), and OutputFile::seek().
set_extent()
void FileBase::set_extent (upx_off_t offset, upx_off_t length) virtual
Reimplemented in OutputFile.
Definition at line 160 of file file.cpp.
{
    _offset = offset;
    _length = length;
}
References _length, and _offset.
Referenced by PackMachFat::canPack(), PackMachFat::canUnpack(), PackMachFat::pack(), OutputFile::set_extent(), and PackMachFat::unpack().
st_size()
upx_off_t FileBase::st_size () const virtual
Reimplemented in OutputFile.
Definition at line 165 of file file.cpp.
{ return _length; }
References _length.
Referenced by PackUnix::canUnpack(), PackLinuxI386sh::getShellName(), and TEST_CASE().
tell()
upx_off_t FileBase::tell () const
Definition at line 151 of file file.cpp.
{
    if (!isOpen())
        throwIOException("bad tell");
    upx_off_t l = ::lseek(_fd, 0, SEEK_CUR);
    if (l < 0)
        throwIOException("tell error", errno);
    return l - _offset;
}
References _fd, _offset, isOpen(), lseek(), SEEK_CUR, and throwIOException().
Referenced by funpad4(), PackTmt::pack(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_shlib_1(), and PackLinuxElf64::un_shlib_1().
unlink()
void FileBase::unlink (const char * name) static
Definition at line 66 of file file.cpp.
{
    if (!unlink_noexcept(name))
        throwIOException(name, errno);
}
References throwIOException(), and unlink_noexcept().
Referenced by do_one_file().
unlink_noexcept()
bool FileBase::unlink_noexcept (const char * name) static noexcept
Definition at line 56 of file file.cpp.
{
    assert_noexcept(name != nullptr && name[0] != 0);
    bool success = ::unlink(name) == 0;
#if HAVE_CHMOD
    if (!success)
        success = (::chmod(name, 0666) == 0 && ::unlink(name) == 0);
#endif
    return success;
}
References assert_noexcept, and unlink().
Referenced by do_one_file(), unlink(), and unlink_ofile().
Member Data Documentation
_fd
int FileBase::_fd = -1 protected
Definition at line 60 of file file.h.
Referenced by close_noexcept(), do_sopen(), getFd(), isOpen(), OutputFile::openStdout(), InputFile::read(), seek(), OutputFile::set_extent(), OutputFile::st_size(), tell(), OutputFile::unset_extent(), and OutputFile::write().
_flags
int FileBase::_flags = 0 protected
Definition at line 61 of file file.h.
Referenced by close_noexcept(), do_sopen(), OutputFile::openStdout(), InputFile::sopen(), and OutputFile::sopen().
_length
upx_off_t FileBase::_length = 0 protected
Definition at line 66 of file file.h.
Referenced by close_noexcept(), do_sopen(), OutputFile::openStdout(), seek(), InputFile::seek(), OutputFile::seek(), set_extent(), OutputFile::set_extent(), InputFile::sopen(), OutputFile::sopen(), st_size(), and OutputFile::unset_extent().
_mode
int FileBase::_mode = 0 protected
Definition at line 63 of file file.h.
Referenced by close_noexcept(), do_sopen(), OutputFile::openStdout(), InputFile::sopen(), and OutputFile::sopen().
_name
const char* FileBase::_name = nullptr protected
Definition at line 64 of file file.h.
Referenced by close_noexcept(), do_sopen(), getName(), OutputFile::openStdout(), OutputFile::set_extent(), InputFile::sopen(), OutputFile::sopen(), OutputFile::st_size(), and ~FileBase().
_offset
upx_off_t FileBase::_offset = 0 protected
Definition at line 65 of file file.h.
Referenced by close_noexcept(), OutputFile::openStdout(), seek(), set_extent(), InputFile::sopen(), OutputFile::sopen(), tell(), and OutputFile::unset_extent().
_shflags
int FileBase::_shflags = 0 protected
Definition at line 62 of file file.h.
Referenced by do_sopen(), OutputFile::openStdout(), InputFile::sopen(), and OutputFile::sopen().
st
struct stat FileBase::st = {}
Definition at line 69 of file file.h.
Referenced by PackUnix::canPack(), do_sopen(), Packer::getRandomId(), handle_allegropak(), and OutputFile::set_extent().
The documentation for this class was generated from the following files:
src/file.h
src/file.cpp