My Project: OutputFile Class Reference
OutputFile Class Reference final
#include <file.h>
Public Member Functions
OutputFile () noexcept=default
void sopen (const char *name, int flags, int shflags, int mode)
OutputFile.
void open (const char *name, int flags, int mode)
bool openStdout (int flags=0, bool force=false)
void write (SPAN_0(const void) buf, upx_int64_t blen)
virtual upx_off_t seek (upx_off_t off, int whence) override
virtual upx_off_t st_size () const override
virtual void set_extent (upx_off_t offset, upx_off_t length) override
upx_off_t unset_extent ()
upx_off_t getBytesWritten () const
void rewrite (SPAN_P(const void) buf, int len)
Public Member Functions inherited from FileBase
bool close_noexcept () noexcept
void closex () may_throw
bool isOpen () const noexcept
int getFd () const noexcept
const char * getName () const noexcept
virtual upx_off_t seek (upx_off_t off, int whence)
upx_off_t tell () const
virtual upx_off_t st_size () const
virtual void set_extent (upx_off_t offset, upx_off_t length)
Static Public Member Functions
static void dump (const char *name, SPAN_P(const void) buf, int len, int flags=-1)
Static Public Member Functions inherited from FileBase
static void chmod (const char *name, int mode) may_throw
static file-related util functions; will throw on error
static void rename (const char *old_, const char *new_) may_throw
static void unlink (const char *name) may_throw
static bool unlink_noexcept (const char *name) noexcept
Protected Attributes
upx_off_t bytes_written = 0
Protected Attributes inherited from FileBase
int _fd = -1
int _flags = 0
int _shflags = 0
int _mode = 0
const char * _name = nullptr
upx_off_t _offset = 0
upx_off_t _length = 0
Private Types
typedef FileBase super
Additional Inherited Members
Public Attributes inherited from FileBase
struct stat st = {}
Protected Member Functions inherited from FileBase
FileBase () noexcept=default
virtual ~FileBase () may_throw
FileBase.
bool do_sopen ()
Detailed Description
Definition at line 101 of file file.h.
Member Typedef Documentation
super
typedef FileBase OutputFile::super private
Definition at line 102 of file file.h.
Constructor & Destructor Documentation
OutputFile()
OutputFile::OutputFile () explicit default noexcept
Member Function Documentation
dump()
void OutputFile::dump (const char * name, SPAN_P(const void) buf, int len, int flags = -1) static
Definition at line 367 of file file.cpp.
{
    if (flags < 0)
        flags = O_CREAT | O_TRUNC;
    flags |= O_WRONLY | O_BINARY;
    OutputFile f;
    f.open(name, flags, 0600);
    f.write(raw_bytes(buf, len), len);
    f.closex();
}
References buf, FileBase::closex(), O_BINARY, O_CREAT, O_WRONLY, open(), raw_bytes(), and write().
Referenced by PackDjgpp2::pack(), PackTos::pack(), PeFile::pack0(), and write().
getBytesWritten()
upx_off_t OutputFile::getBytesWritten () const inline
Definition at line 119 of file file.h.
{ return bytes_written; }
Referenced by Packer::checkFinalCompressionRatio(), PackPs1::pack(), PeFile::pack0(), PackMachBase< TMachClass >::pack1(), PackMachBase< TMachClass >::pack2(), PackUnix::pack3(), PackLinuxElf32x86interp::pack3(), PackMachBase< TMachClass >::pack3(), PackDylibPPC32::pack3(), PackDylibPPC64::pack3(), PackDylibI386::pack3(), PackDylibAMD64::pack3(), PackLinuxI386::pack4(), PackMachBase< TMachClass >::pack4(), PackMachBase< TMachClass >::pack4dylib(), TEST_CASE(), UiPacker::uiUnpackEnd(), PackPs1::unpack(), PeFile::unpack0(), and PackLinuxI386::updateLoader().
open()
void OutputFile::open (const char * name, int flags, int mode) inline
Definition at line 108 of file file.h.
{ sopen(name, flags, -1, mode); }
References InputFile::sopen().
Referenced by dump().
openStdout()
bool OutputFile::openStdout (int flags = 0, bool force = false)
Definition at line 257 of file file.cpp.
{
    closex();
    int fd = STDOUT_FILENO;
    if (!force && acc_isatty(fd))
        return false;
    _name = "<stdout>";
    _flags = flags;
    _shflags = -1;
    _mode = 0;
    _offset = 0;
    _length = 0;
    if (flags && acc_set_binmode(fd, 1) == -1)
        throwIOException(_name, errno);
    _fd = fd;
    return true;
}
References FileBase::_fd, FileBase::_flags, FileBase::_length, FileBase::_mode, FileBase::_name, FileBase::_offset, FileBase::_shflags, FileBase::closex(), STDOUT_FILENO, and throwIOException().
Referenced by do_one_file().
rewrite()
void OutputFile::rewrite (SPAN_P(const void) buf, int len)
Definition at line 314 of file file.cpp.
{
    assert(!opt->to_stdout);
    write(buf, len);
    bytes_written -= len; // restore
}
References buf, bytes_written, opt, and write().
Referenced by PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackNetBSDElf32x86::generateElfHdr(), PackMachFat::pack(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxI386::pack4(), PackMachBase< TMachClass >::pack4dylib(), PackMachPPC32::threado_rewrite(), PackMachPPC64::threado_rewrite(), PackMachI386::threado_rewrite(), PackMachAMD64::threado_rewrite(), PackMachARMEL::threado_rewrite(), PackMachARM64EL::threado_rewrite(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackMachFat::unpack(), PackUnix::unpackExtent(), PackLinuxElf32::unRel32(), and PackLinuxElf64::unRela64().
seek()
upx_off_t OutputFile::seek (upx_off_t off, int whence) override virtual
Reimplemented from FileBase.
Definition at line 320 of file file.cpp.
{
    mem_size_assert(1, off >= 0 ? off : -off); // sanity check
    assert(!opt->to_stdout);
    switch (whence) {
    case SEEK_SET:
        if (bytes_written < off)
            bytes_written = off;
        _length = bytes_written; // cheap, lazy update; needed?
        break;
    case SEEK_END:
        _length = bytes_written; // necessary
        break;
    }
    return super::seek(off, whence);
}
References FileBase::_length, bytes_written, mem_size_assert(), opt, FileBase::seek(), SEEK_END, and SEEK_SET.
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), anonymous_namespace{work.cpp}::copy_file_contents(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackNetBSDElf32x86::generateElfHdr(), PackMachFat::pack(), PackVmlinuxBase< TElfClass >::pack(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxI386::pack4(), PackMachBase< TMachClass >::pack4dylib(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachBase< TMachClass >::unpack(), PackMachFat::unpack(), PackLinuxElf32::unRel32(), and PackLinuxElf64::unRela64().
set_extent()
void OutputFile::set_extent (upx_off_t offset, upx_off_t length) override virtual
Reimplemented from FileBase.
Definition at line 346 of file file.cpp.
{
    super::set_extent(offset, length);
    bytes_written = 0;
    if (0 == offset && 0xffffffffLL == length) { // TODO: check all callers of this method
        st.st_size = 0;
        if (::fstat(_fd, &st) != 0)
            throwIOException(_name, errno);
        _length = st.st_size - offset;
    }
}
References FileBase::_fd, FileBase::_length, FileBase::_name, bytes_written, FileBase::set_extent(), FileBase::st, and throwIOException().
Referenced by PackMachFat::pack(), and PackMachFat::unpack().
sopen()
void OutputFile::sopen (const char * name, int flags, int shflags, int mode)
OutputFile.
Definition at line 235 of file file.cpp.
{
    closex();
    _name = name;
    _flags = flags;
    _shflags = shflags;
    _mode = mode;
    _offset = 0;
    _length = 0;
    if (!super::do_sopen()) {
#if 0
        // don't throw FileNotFound here -- this is confusing
        if (errno == ENOENT)
            throw FileNotFoundException(_name,errno);
        else
#endif
        if (errno == EEXIST)
            throw FileAlreadyExistsException(_name, errno);
        else
            throwIOException(_name, errno);
    }
}
References FileBase::_flags, FileBase::_length, FileBase::_mode, FileBase::_name, FileBase::_offset, FileBase::_shflags, FileBase::closex(), FileBase::do_sopen(), ENOENT, and throwIOException().
Referenced by anonymous_namespace{work.cpp}::copy_file_contents(), and do_one_file().
st_size()
upx_off_t OutputFile::st_size () const override virtual
Reimplemented from FileBase.
Definition at line 303 of file file.cpp.
{
    if (opt->to_stdout) {     // might be a pipe ==> .st_size is invalid
        return bytes_written; // too big if seek()+write() instead of rewrite()
    }
    struct stat my_st;
    my_st.st_size = 0;
    if (::fstat(_fd, &my_st) != 0)
        throwIOException(_name, errno);
    return my_st.st_size;
}
References FileBase::_fd, FileBase::_name, bytes_written, opt, and throwIOException().
Referenced by fpad4(), fpad8(), fpadN(), PackUnix::pack(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), and UiPacker::uiPackEnd().
unset_extent()
upx_off_t OutputFile::unset_extent ()
Definition at line 357 of file file.cpp.
{
    upx_off_t l = ::lseek(_fd, 0, SEEK_END);
    if (l < 0)
        throwIOException("lseek error", errno);
    _offset = 0;
    _length = l;
    bytes_written = _length;
    return _length;
}
References FileBase::_fd, FileBase::_length, FileBase::_offset, bytes_written, lseek(), SEEK_END, and throwIOException().
Referenced by PackMachFat::pack(), and PackMachFat::unpack().
write()
void OutputFile::write (SPAN_0(const void) buf, upx_int64_t blen)
Definition at line 274 of file file.cpp.
{
    if (!isOpen() || blen < 0)
        throwIOException("bad write");
    // allow nullptr if blen == 0
    if (blen == 0)
        return;
    int len = (int) mem_size(1, blen); // sanity check
    errno = 0;
#if WITH_XSPAN >= 2
    NO_fprintf(stderr, "write %p %zd (%p) %d\n", buf.raw_ptr(), buf.raw_size_in_bytes(),
               buf.raw_base(), len);
#endif
    long l = acc_safe_hwrite(_fd, raw_bytes(buf, len), len);
    if (l != len)
        throwIOException("write error", errno);
    bytes_written += len;
#if TESTING && 0
    static upx_std_atomic(bool) dumping;
    if (!dumping) {
        dumping = true;
        char fn[64];
        static int part = 0;
        snprintf(fn, sizeof(fn), "upx-dump-%04d.data", part++);
        OutputFile::dump(fn, buf, len);
        dumping = false;
    }
#endif
}
References FileBase::_fd, buf, bytes_written, dump(), FileBase::isOpen(), mem_size(), NO_fprintf(), raw_bytes(), snprintf, throwIOException(), and upx_std_atomic.
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), anonymous_namespace{work.cpp}::copy_file_contents(), Packer::copyOverlay(), dump(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), fpad4(), fpad8(), fpadN(), PackLinuxI386::generateElfHdr(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), handle_allegropak(), Packer::handleStub(), PackDjgpp2::handleStub(), PackDjgpp2::pack(), PackExe::pack(), PackMachFat::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackVmlinuxBase< TElfClass >::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PeFile::pack0(), PackLinuxElf32x86interp::pack1(), PackMachBase< TMachClass >::pack1(), PackMachPPC32::pack1_setup_threado(), PackMachPPC64::pack1_setup_threado(), PackMachI386::pack1_setup_threado(), PackMachAMD64::pack1_setup_threado(), PackMachARMEL::pack1_setup_threado(), PackMachARM64EL::pack1_setup_threado(), PackUnix::pack2(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackUnix::pack3(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf32x86interp::pack3(), PackMachBase< TMachClass >::pack3(), PackDylibPPC32::pack3(), PackDylibPPC64::pack3(), PackDylibI386::pack3(), PackDylibAMD64::pack3(), PackLinuxElf::pack3(), PackUnix::pack4(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxI386::pack4(), PackMachBase< TMachClass >::pack4(), PackMachBase< TMachClass >::pack4dylib(), PackUnix::packExtent(), PackCom::patchLoader(), PackSys::patchLoader(), rewrite(), PackMachPPC32::threado_write(), PackMachPPC64::threado_write(), PackMachI386::threado_write(), PackMachAMD64::threado_write(), PackMachARMEL::threado_write(), PackMachARM64EL::threado_write(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackMachBase< TMachClass >::unpack(), PackMachFat::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackUnix::unpack(), PackVmlinuxBase< TElfClass >::unpack(), PeFile::unpack0(), PackUnix::unpackExtent(), PackVmlinuxI386::write_vmlinux_head(), PackVmlinuxARMEL::write_vmlinux_head(), PackVmlinuxARMEB::write_vmlinux_head(), PackVmlinuxAMD64::write_vmlinux_head(), PackVmlinuzARMEL::write_vmlinuz_head(), LeFile::writeEntryTable(), LeFile::writeFile(), LeFile::writeFixupPageTable(), LeFile::writeFixups(), LeFile::writeImage(), LeFile::writeNonResidentNames(), LeFile::writeObjectTable(), PackUnix::writePackHeader(), LeFile::writePageMap(), and LeFile::writeResidentNames().
Member Data Documentation
bytes_written
upx_off_t OutputFile::bytes_written = 0 protected
Definition at line 128 of file file.h.
Referenced by rewrite(), seek(), set_extent(), st_size(), unset_extent(), and write().
The documentation for this class was generated from the following files:
src/file.h
src/file.cpp