My Project: PeFile Class Reference
PeFile Class Reference abstract
#include <pefile.h>
Classes
struct ddirs_t
class Export
struct import_desc
class ImportLinker
class Interval
struct pe_section_t
class Reloc
class Resource
struct tls_traits
struct tls_traits< LE32 >
TLS handling.
struct tls_traits< LE64 >
Public Member Functions
virtual int getVersion () const override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Types
enum {
IMAGE_FILE_MACHINE_UNKNOWN = 0 , IMAGE_FILE_MACHINE_AMD64 = 0x8664 , IMAGE_FILE_MACHINE_ARM = 0x01c0 , IMAGE_FILE_MACHINE_ARMNT = 0x01c4 ,
IMAGE_FILE_MACHINE_ARM64 = 0xaa64 , IMAGE_FILE_MACHINE_ARM64EC = 0xa641 , IMAGE_FILE_MACHINE_I386 = 0x014c , IMAGE_FILE_MACHINE_IA64 = 0x200 ,
IMAGE_FILE_MACHINE_LOONGARCH32 = 0x6232 , IMAGE_FILE_MACHINE_LOONGARCH64 = 0x6264 , IMAGE_FILE_MACHINE_RISCV32 = 0x5032 , IMAGE_FILE_MACHINE_RISCV64 = 0x5064 ,
IMAGE_FILE_MACHINE_RISCV128 = 0x5128 , IMAGE_FILE_MACHINE_THUMB = 0x01c2
}
enum {
PEDIR_EXPORT = 0 , PEDIR_IMPORT = 1 , PEDIR_RESOURCE = 2 , PEDIR_EXCEPTION = 3 ,
PEDIR_SECURITY = 4 , PEDIR_BASERELOC = 5 , PEDIR_DEBUG = 6 , PEDIR_ARCHITECTURE = 7 ,
PEDIR_GLOBALPTR = 8 , PEDIR_TLS = 9 , PEDIR_LOAD_CONFIG = 10 , PEDIR_BOUND_IMPORT = 11 ,
PEDIR_IAT = 12 , PEDIR_DELAY_IMPORT = 13 , PEDIR_COM_DESCRIPTOR = 14
}
enum : unsigned {
IMAGE_SCN_CNT_CODE = 0x00000020 , IMAGE_SCN_CNT_INITIALIZED_DATA = 0x00000040 , IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080 , IMAGE_SCN_LNK_OTHER = 0x00000100 ,
IMAGE_SCN_LNK_INFO = 0x00000200 , IMAGE_SCN_LNK_REMOVE = 0x00000800 , IMAGE_SCN_LNK_COMDAT = 0x00001000 , IMAGE_SCN_GPREL = 0x00008000 ,
IMAGE_SCN_MEM_PURGEABLE = 0x00020000 , IMAGE_SCN_MEM_16BIT = 0x00020000 , IMAGE_SCN_MEM_LOCKED = 0x00040000 , IMAGE_SCN_MEM_PRELOAD = 0x00080000 ,
IMAGE_SCN_ALIGN_1BYTES = 0x00100000 , IMAGE_SCN_ALIGN_2BYTES = 0x00200000 , IMAGE_SCN_ALIGN_4BYTES = 0x00300000 , IMAGE_SCN_ALIGN_8BYTES = 0x00400000 ,
IMAGE_SCN_ALIGN_16BYTES = 0x00500000 , IMAGE_SCN_ALIGN_32BYTES = 0x00600000 , IMAGE_SCN_ALIGN_64BYTES = 0x00700000 , IMAGE_SCN_ALIGN_128BYTES = 0x00800000 ,
IMAGE_SCN_ALIGN_256BYTES = 0x00900000 , IMAGE_SCN_ALIGN_512BYTES = 0x00A00000 , IMAGE_SCN_ALIGN_1024BYTES = 0x00B00000 , IMAGE_SCN_ALIGN_2048BYTES = 0x00C00000 ,
IMAGE_SCN_ALIGN_4096BYTES = 0x00D00000 , IMAGE_SCN_ALIGN_8192BYTES = 0x00E00000 , IMAGE_SCN_LNK_NRELOC_OVFL = 0x01000000 , IMAGE_SCN_MEM_DISCARDABLE = 0x02000000 ,
IMAGE_SCN_MEM_NOT_CACHED = 0x04000000 , IMAGE_SCN_MEM_NOT_PAGED = 0x08000000 , IMAGE_SCN_MEM_SHARED = 0x10000000 , IMAGE_SCN_MEM_EXECUTE = 0x20000000 ,
IMAGE_SCN_MEM_READ = 0x40000000 , IMAGE_SCN_MEM_WRITE = 0x80000000
}
enum {
IMAGE_FILE_RELOCS_STRIPPED = 0x0001 , IMAGE_FILE_EXECUTABLE_IMAGE = 0x0002 , IMAGE_FILE_LINE_NUMS_STRIPPED = 0x0004 , IMAGE_FILE_LOCAL_SYMS_STRIPPED = 0x0008 ,
IMAGE_FILE_AGGRESSIVE_WS_TRIM = 0x0010 , IMAGE_FILE_LARGE_ADDRESS_AWARE = 0x0020 , IMAGE_FILE_BYTES_REVERSED_LO = 0x0080 , IMAGE_FILE_32BIT_MACHINE = 0x0100 ,
IMAGE_FILE_DEBUG_STRIPPED = 0x0200 , IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x0400 , IMAGE_FILE_NET_RUN_FROM_SWAP = 0x0800 , IMAGE_FILE_SYSTEM = 0x1000 ,
IMAGE_FILE_DLL = 0x2000 , IMAGE_FILE_UP_SYSTEM_ONLY = 0x4000 , IMAGE_FILE_BYTES_REVERSE_HI = 0x8000
}
enum {
IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA = 0x0020 , IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE = 0x0040 , IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY = 0x0080 , IMAGE_DLLCHARACTERISTICS_NX_COMPAT = 0x0100 ,
IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x0200 , IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x0400 , IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x0800 , IMAGE_DLLCHARACTERISTICS_APPCONTAINER = 0x1000 ,
IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x2000 , IMAGE_DLLCHARACTERISTICS_GUARD_CF = 0x4000 , IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000
}
enum {
IMAGE_SUBSYSTEM_UNKNOWN = 0 , IMAGE_SUBSYSTEM_NATIVE = 1 , IMAGE_SUBSYSTEM_WINDOWS_GUI = 2 , IMAGE_SUBSYSTEM_WINDOWS_CUI = 3 ,
IMAGE_SUBSYSTEM_WINDOWS_OS2_CUI = 5 , IMAGE_SUBSYSTEM_WINDOWS_POSIX_CUI = 7 , IMAGE_SUBSYSTEM_NATIVE_WINDOWS = 8 , IMAGE_SUBSYSTEM_WINDOWS_CE_GUI = 9 ,
IMAGE_SUBSYSTEM_EFI_APPLICATION = 10 , IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER = 11 , IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER = 12 , IMAGE_SUBSYSTEM_EFI_ROM = 13 ,
IMAGE_SUBSYSTEM_XBOX = 14 , IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION = 16
}
enum {
RT_CURSOR = 1 , RT_BITMAP , RT_ICON , RT_MENU ,
RT_DIALOG , RT_STRING , RT_FONTDIR , RT_FONT ,
RT_ACCELERATOR , RT_RCDATA , RT_MESSAGETABLE , RT_GROUP_CURSOR ,
RT_GROUP_ICON = 14 , RT_VERSION = 16 , RT_DLGINCLUDE , RT_PLUGPLAY = 19 ,
RT_VXD , RT_ANICURSOR , RT_ANIICON , RT_HTML ,
RT_MANIFEST , RT_LAST
}
enum {
IMAGE_REL_BASED_ABSOLUTE = 0 , IMAGE_REL_BASED_IGNORE = 0 , IMAGE_REL_BASED_HIGH = 1 , IMAGE_REL_BASED_LOW = 2 ,
IMAGE_REL_BASED_HIGHLOW = 3 , IMAGE_REL_BASED_HIGHADJ = 4 , IMAGE_REL_BASED_MIPS_JMPADDR = 5 , IMAGE_REL_BASED_ARM_MOV32 = 5 ,
IMAGE_REL_BASED_THUMB_MOV32 = 7 , IMAGE_REL_BASED_MIPS_JMPADDR16 = 9 , IMAGE_REL_BASED_IA64_IMM64 = 9 , IMAGE_REL_BASED_DIR64 = 10
}
Protected Member Functions
PeFile (InputFile *f)
void readSectionHeaders (unsigned objs, unsigned sizeof_ih)
pack
unsigned readSections (unsigned objs, unsigned usize, unsigned ih_filealign, unsigned ih_datasize)
void checkHeaderValues (unsigned subsystem, unsigned mask, unsigned ih_entry, unsigned ih_filealign)
unsigned handleStripRelocs (upx_uint64_t ih_imagebase, upx_uint64_t default_imagebase, LE16 &dllflags)
virtual bool needForceOption () const =0
virtual void callCompressWithFilters (Filter &, int filter_strategy, unsigned ih_codebase)
virtual void defineSymbols (unsigned ncsection, unsigned upxsection, unsigned sizeof_oh, unsigned isize_isplit, unsigned s1addr)=0
virtual void addNewRelocations (Reloc &, unsigned)
void callProcessStubRelocs (Reloc &rel, unsigned &ic)
void callProcessResources (Resource &res, unsigned &ic)
virtual unsigned getProcessImportParam (unsigned)
virtual void setOhDataBase (const pe_section_t *osection)=0
virtual void setOhHeaderSize (const pe_section_t *osection)=0
virtual bool canUnpackVersion (int version) const override
virtual int readFileHeader ()
virtual bool testUnpackVersion (int version) const override
virtual void readPeHeader ()=0
template<typename LEXX , typename ord_mask_t >
unsigned processImports0 (ord_mask_t ord_mask)
virtual unsigned processImports ()=0
virtual void processImports2 (unsigned, unsigned)
SPAN_0 (byte) oimport
virtual const char * kernelDll () const
void addKernelImport (const char *)
virtual void addStubImports ()
virtual void processRelocs ()=0
SPAN_0 (byte) orelocs
void processExports (Export *)
void processExports (Export *, unsigned)
SPAN_0 (byte) oexport
void processResources (Resource *)
void processResources (Resource *, unsigned)
SPAN_0 (byte) oresources
template<typename LEXX >
void processTls1 (Interval *iv, typename tls_traits< LEXX >::cb_value_t imagebase, unsigned imagesize)
template<typename LEXX >
void processTls2 (Reloc *rel, const Interval *iv, unsigned newaddr, typename tls_traits< LEXX >::cb_value_t imagebase)
virtual void processTls (Interval *iv)=0
virtual void processTls (Reloc *r, const Interval *iv, unsigned a)=0
SPAN_0 (byte) otls
void processLoadConf (Reloc *, const Interval *, unsigned)
void processLoadConf (Interval *)
Load Configuration handling.
unsigned stripDebug (unsigned)
LE32 & IDSIZE (unsigned x)
import handling
LE32 & IDADDR (unsigned x)
LE32 & ODSIZE (unsigned x)
LE32 & ODADDR (unsigned x)
const LE32 & IDSIZE (unsigned x) const
const LE32 & IDADDR (unsigned x) const
SPAN_0 (pe_section_t) isection
unsigned tryremove (unsigned, unsigned)
pack0
create UPX0 section
Reduct the file size.
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header .
Parameters
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header .
Parameters
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
Parameters
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
Parameters
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Remarks
None.
virtual ~PeFile () noexcept
create UPX0 section
template<typename LEXX , typename ht >
void pack0 (OutputFile *fo, ht &ih, ht &oh, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only)
create UPX0 section
template<typename ht , typename LEXX , typename ord_mask_t >
void unpack0 (OutputFile *fo, const ht &ih, ht &oh, ord_mask_t ord_mask, bool set_oft)
create UPX0 section
int canUnpack0 (unsigned max_sections, unsigned objs, unsigned ih_entry, unsigned ih_size)
create UPX0 section
template<typename LEXX , typename ord_mask_t >
void rebuildImports (SPAN_S(byte) &extra_info, ord_mask_t ord_mask, bool set_oft)
create UPX0 section
upx_uint64_t ilinkerGetAddress (const char *, const char *) const
create UPX0 section
void rebuildRelocs (SPAN_S(byte) &, unsigned bits, unsigned flags, upx_uint64_t imagebase)
unpack
void rebuildExports ()
create UPX0 section
void rebuildResources (SPAN_S(byte) &, unsigned)
create UPX0 section
void rebuildTls ()
create UPX0 section
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Static Protected Member Functions
static int checkMachine (unsigned cpu)
util
static unsigned virta2objnum (unsigned, SPAN_0(pe_section_t), unsigned)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes
unsigned pe_offset
MemBuffer mb_oimport
unsigned soimport
byte * oimpdlls = nullptr
unsigned soimpdlls
ImportLinker * ilinker = nullptr
MemBuffer mb_orelocs
unsigned sorelocs
byte * oxrelocs = nullptr
unsigned soxrelocs
MemBuffer mb_oexport
unsigned soexport
MemBuffer mb_oresources
unsigned soresources
MemBuffer mb_otls
unsigned sotls
unsigned tlsindex
unsigned tlscb_ptr
unsigned tls_handler_offset = 0
bool use_tls_callbacks = false
MemBuffer mb_oloadconf
byte * oloadconf = nullptr
unsigned soloadconf
unsigned icondir_offset
int icondir_count
bool importbyordinal = false
bool kernel32ordinal = false
unsigned rvamin
unsigned cimports
unsigned crelocs
int big_relocs
ddirs_t * iddirs = nullptr
ddirs_t * oddirs = nullptr
MemBuffer mb_isection
bool isdll = false
bool isrtm = false
bool isefi = false
bool use_dep_hack = true
bool use_clear_dirty_stack = true
bool use_stub_relocs = true
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Detailed Description
Definition at line 30 of file pefile.h.
Member Typedef Documentation
super
typedef Packer PeFile::super private
Definition at line 31 of file pefile.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
IMAGE_FILE_MACHINE_UNKNOWN
IMAGE_FILE_MACHINE_AMD64
IMAGE_FILE_MACHINE_ARM
IMAGE_FILE_MACHINE_ARMNT
IMAGE_FILE_MACHINE_ARM64
IMAGE_FILE_MACHINE_ARM64EC
IMAGE_FILE_MACHINE_I386
IMAGE_FILE_MACHINE_IA64
IMAGE_FILE_MACHINE_LOONGARCH32
IMAGE_FILE_MACHINE_LOONGARCH64
IMAGE_FILE_MACHINE_RISCV32
IMAGE_FILE_MACHINE_RISCV64
IMAGE_FILE_MACHINE_RISCV128
IMAGE_FILE_MACHINE_THUMB
Definition at line 236 of file pefile.h.
         {
        IMAGE_FILE_MACHINE_UNKNOWN = 0,
        IMAGE_FILE_MACHINE_AMD64 = 0x8664,   // win64/pe (amd64)
        IMAGE_FILE_MACHINE_ARM = 0x01c0,     // wince/arm (Windows CE)
        IMAGE_FILE_MACHINE_ARMNT = 0x01c4,   // win32/arm
        IMAGE_FILE_MACHINE_ARM64 = 0xaa64,   // win64/arm64
        IMAGE_FILE_MACHINE_ARM64EC = 0xa641, // win64/arm64ec
        IMAGE_FILE_MACHINE_I386 = 0x014c,    // win32/pe (i386)
        IMAGE_FILE_MACHINE_IA64 = 0x200,
        IMAGE_FILE_MACHINE_LOONGARCH32 = 0x6232,
        IMAGE_FILE_MACHINE_LOONGARCH64 = 0x6264,
        IMAGE_FILE_MACHINE_RISCV32 = 0x5032,
        IMAGE_FILE_MACHINE_RISCV64 = 0x5064,
        IMAGE_FILE_MACHINE_RISCV128 = 0x5128,
        IMAGE_FILE_MACHINE_THUMB = 0x01c2, // wince/arm (Windows CE)
    };
anonymous enum
anonymous enum protected
Enumerator
PEDIR_EXPORT
PEDIR_IMPORT
PEDIR_RESOURCE
PEDIR_EXCEPTION
PEDIR_SECURITY
PEDIR_BASERELOC
PEDIR_DEBUG
PEDIR_ARCHITECTURE
PEDIR_GLOBALPTR
PEDIR_TLS
PEDIR_LOAD_CONFIG
PEDIR_BOUND_IMPORT
PEDIR_IAT
PEDIR_DELAY_IMPORT
PEDIR_COM_DESCRIPTOR
Definition at line 253 of file pefile.h.
         {
        PEDIR_EXPORT = 0,
        PEDIR_IMPORT = 1,
        PEDIR_RESOURCE = 2,
        PEDIR_EXCEPTION = 3, // Exception table
        PEDIR_SECURITY = 4,  // Certificate table (file pointer)
        PEDIR_BASERELOC = 5,
        PEDIR_DEBUG = 6,
        PEDIR_ARCHITECTURE = 7, // Architecture-specific data
        PEDIR_GLOBALPTR = 8,    // Global pointer
        PEDIR_TLS = 9,
        PEDIR_LOAD_CONFIG = 10, // Load Config Table
        PEDIR_BOUND_IMPORT = 11,
        PEDIR_IAT = 12,
        PEDIR_DELAY_IMPORT = 13,   // Delay Import Descriptor
        PEDIR_COM_DESCRIPTOR = 14, // Com+ Runtime Header
    };
anonymous enum
anonymous enum : unsigned protected
Enumerator
IMAGE_SCN_CNT_CODE
IMAGE_SCN_CNT_INITIALIZED_DATA
IMAGE_SCN_CNT_UNINITIALIZED_DATA
IMAGE_SCN_LNK_OTHER
IMAGE_SCN_LNK_INFO
IMAGE_SCN_LNK_REMOVE
IMAGE_SCN_LNK_COMDAT
IMAGE_SCN_GPREL
IMAGE_SCN_MEM_PURGEABLE
IMAGE_SCN_MEM_16BIT
IMAGE_SCN_MEM_LOCKED
IMAGE_SCN_MEM_PRELOAD
IMAGE_SCN_ALIGN_1BYTES
IMAGE_SCN_ALIGN_2BYTES
IMAGE_SCN_ALIGN_4BYTES
IMAGE_SCN_ALIGN_8BYTES
IMAGE_SCN_ALIGN_16BYTES
IMAGE_SCN_ALIGN_32BYTES
IMAGE_SCN_ALIGN_64BYTES
IMAGE_SCN_ALIGN_128BYTES
IMAGE_SCN_ALIGN_256BYTES
IMAGE_SCN_ALIGN_512BYTES
IMAGE_SCN_ALIGN_1024BYTES
IMAGE_SCN_ALIGN_2048BYTES
IMAGE_SCN_ALIGN_4096BYTES
IMAGE_SCN_ALIGN_8192BYTES
IMAGE_SCN_LNK_NRELOC_OVFL
IMAGE_SCN_MEM_DISCARDABLE
IMAGE_SCN_MEM_NOT_CACHED
IMAGE_SCN_MEM_NOT_PAGED
IMAGE_SCN_MEM_SHARED
IMAGE_SCN_MEM_EXECUTE
IMAGE_SCN_MEM_READ
IMAGE_SCN_MEM_WRITE
Definition at line 272 of file pefile.h.
         : unsigned {
        IMAGE_SCN_CNT_CODE = 0x00000020,
        IMAGE_SCN_CNT_INITIALIZED_DATA = 0x00000040,
        IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080,
        IMAGE_SCN_LNK_OTHER = 0x00000100,
        IMAGE_SCN_LNK_INFO = 0x00000200,
        IMAGE_SCN_LNK_REMOVE = 0x00000800,
        IMAGE_SCN_LNK_COMDAT = 0x00001000,
        IMAGE_SCN_GPREL = 0x00008000,
        IMAGE_SCN_MEM_PURGEABLE = 0x00020000,
        IMAGE_SCN_MEM_16BIT = 0x00020000,
        IMAGE_SCN_MEM_LOCKED = 0x00040000,
        IMAGE_SCN_MEM_PRELOAD = 0x00080000,
        IMAGE_SCN_ALIGN_1BYTES = 0x00100000,
        IMAGE_SCN_ALIGN_2BYTES = 0x00200000,
        IMAGE_SCN_ALIGN_4BYTES = 0x00300000,
        IMAGE_SCN_ALIGN_8BYTES = 0x00400000,
        IMAGE_SCN_ALIGN_16BYTES = 0x00500000,
        IMAGE_SCN_ALIGN_32BYTES = 0x00600000,
        IMAGE_SCN_ALIGN_64BYTES = 0x00700000,
        IMAGE_SCN_ALIGN_128BYTES = 0x00800000,
        IMAGE_SCN_ALIGN_256BYTES = 0x00900000,
        IMAGE_SCN_ALIGN_512BYTES = 0x00A00000,
        IMAGE_SCN_ALIGN_1024BYTES = 0x00B00000,
        IMAGE_SCN_ALIGN_2048BYTES = 0x00C00000,
        IMAGE_SCN_ALIGN_4096BYTES = 0x00D00000,
        IMAGE_SCN_ALIGN_8192BYTES = 0x00E00000,
        IMAGE_SCN_LNK_NRELOC_OVFL = 0x01000000,
        IMAGE_SCN_MEM_DISCARDABLE = 0x02000000,
        IMAGE_SCN_MEM_NOT_CACHED = 0x04000000,
        IMAGE_SCN_MEM_NOT_PAGED = 0x08000000,
        IMAGE_SCN_MEM_SHARED = 0x10000000,
        IMAGE_SCN_MEM_EXECUTE = 0x20000000,
        IMAGE_SCN_MEM_READ = 0x40000000,
        IMAGE_SCN_MEM_WRITE = 0x80000000,
    };
anonymous enum
anonymous enum protected
Enumerator
IMAGE_FILE_RELOCS_STRIPPED
IMAGE_FILE_EXECUTABLE_IMAGE
IMAGE_FILE_LINE_NUMS_STRIPPED
IMAGE_FILE_LOCAL_SYMS_STRIPPED
IMAGE_FILE_AGGRESSIVE_WS_TRIM
IMAGE_FILE_LARGE_ADDRESS_AWARE
IMAGE_FILE_BYTES_REVERSED_LO
IMAGE_FILE_32BIT_MACHINE
IMAGE_FILE_DEBUG_STRIPPED
IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP
IMAGE_FILE_NET_RUN_FROM_SWAP
IMAGE_FILE_SYSTEM
IMAGE_FILE_DLL
IMAGE_FILE_UP_SYSTEM_ONLY
IMAGE_FILE_BYTES_REVERSE_HI
Definition at line 309 of file pefile.h.
         {
        IMAGE_FILE_RELOCS_STRIPPED = 0x0001,
        IMAGE_FILE_EXECUTABLE_IMAGE = 0x0002,
        IMAGE_FILE_LINE_NUMS_STRIPPED = 0x0004,
        IMAGE_FILE_LOCAL_SYMS_STRIPPED = 0x0008,
        IMAGE_FILE_AGGRESSIVE_WS_TRIM = 0x0010,
        IMAGE_FILE_LARGE_ADDRESS_AWARE = 0x0020,
        IMAGE_FILE_BYTES_REVERSED_LO = 0x0080,
        IMAGE_FILE_32BIT_MACHINE = 0x0100,
        IMAGE_FILE_DEBUG_STRIPPED = 0x0200,
        IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x0400,
        IMAGE_FILE_NET_RUN_FROM_SWAP = 0x0800,
        IMAGE_FILE_SYSTEM = 0x1000,
        IMAGE_FILE_DLL = 0x2000,
        IMAGE_FILE_UP_SYSTEM_ONLY = 0x4000,
        IMAGE_FILE_BYTES_REVERSE_HI = 0x8000,
    };
anonymous enum
anonymous enum protected
Enumerator
IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA
IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE
IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY
IMAGE_DLLCHARACTERISTICS_NX_COMPAT
IMAGE_DLLCHARACTERISTICS_NO_ISOLATION
IMAGE_DLLCHARACTERISTICS_NO_SEH
IMAGE_DLLCHARACTERISTICS_NO_BIND
IMAGE_DLLCHARACTERISTICS_APPCONTAINER
IMAGE_DLLCHARACTERISTICS_WDM_DRIVER
IMAGE_DLLCHARACTERISTICS_GUARD_CF
IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE
Definition at line 327 of file pefile.h.
         {
        IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA = 0x0020,
        IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE = 0x0040,
        IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY = 0x0080,
        IMAGE_DLLCHARACTERISTICS_NX_COMPAT = 0x0100,
        IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x0200,
        IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x0400,
        IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x0800,
        IMAGE_DLLCHARACTERISTICS_APPCONTAINER = 0x1000,
        IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x2000,
        IMAGE_DLLCHARACTERISTICS_GUARD_CF = 0x4000,
        IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000,
    };
anonymous enum
anonymous enum protected
Enumerator
IMAGE_SUBSYSTEM_UNKNOWN
IMAGE_SUBSYSTEM_NATIVE
IMAGE_SUBSYSTEM_WINDOWS_GUI
IMAGE_SUBSYSTEM_WINDOWS_CUI
IMAGE_SUBSYSTEM_WINDOWS_OS2_CUI
IMAGE_SUBSYSTEM_WINDOWS_POSIX_CUI
IMAGE_SUBSYSTEM_NATIVE_WINDOWS
IMAGE_SUBSYSTEM_WINDOWS_CE_GUI
IMAGE_SUBSYSTEM_EFI_APPLICATION
IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER
IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER
IMAGE_SUBSYSTEM_EFI_ROM
IMAGE_SUBSYSTEM_XBOX
IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION
Definition at line 341 of file pefile.h.
         {
        IMAGE_SUBSYSTEM_UNKNOWN = 0,
        IMAGE_SUBSYSTEM_NATIVE = 1,
        IMAGE_SUBSYSTEM_WINDOWS_GUI = 2, // Graphical User Interface
        IMAGE_SUBSYSTEM_WINDOWS_CUI = 3, // Character User Interface
        IMAGE_SUBSYSTEM_WINDOWS_OS2_CUI = 5,
        IMAGE_SUBSYSTEM_WINDOWS_POSIX_CUI = 7,
        IMAGE_SUBSYSTEM_NATIVE_WINDOWS = 8,
        IMAGE_SUBSYSTEM_WINDOWS_CE_GUI = 9,
        IMAGE_SUBSYSTEM_EFI_APPLICATION = 10,
        IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER = 11,
        IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER = 12,
        IMAGE_SUBSYSTEM_EFI_ROM = 13,
        IMAGE_SUBSYSTEM_XBOX = 14,
        IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION = 16,
    };
anonymous enum
anonymous enum protected
Enumerator
RT_CURSOR
RT_BITMAP
RT_ICON
RT_MENU
RT_DIALOG
RT_STRING
RT_FONTDIR
RT_FONT
RT_ACCELERATOR
RT_RCDATA
RT_MESSAGETABLE
RT_GROUP_CURSOR
RT_GROUP_ICON
RT_VERSION
RT_DLGINCLUDE
RT_PLUGPLAY
RT_VXD
RT_ANICURSOR
RT_ANIICON
RT_HTML
RT_MANIFEST
RT_LAST
Definition at line 359 of file pefile.h.
         {
        RT_CURSOR = 1,
        RT_BITMAP,
        RT_ICON,
        RT_MENU,
        RT_DIALOG,
        RT_STRING,
        RT_FONTDIR,
        RT_FONT,
        RT_ACCELERATOR,
        RT_RCDATA,
        RT_MESSAGETABLE,
        RT_GROUP_CURSOR,
        RT_GROUP_ICON = 14,
        RT_VERSION = 16,
        RT_DLGINCLUDE,
        RT_PLUGPLAY = 19,
        RT_VXD,
        RT_ANICURSOR,
        RT_ANIICON,
        RT_HTML,
        RT_MANIFEST,
        RT_LAST
    };
anonymous enum
anonymous enum protected
Enumerator
IMAGE_REL_BASED_ABSOLUTE
IMAGE_REL_BASED_IGNORE
IMAGE_REL_BASED_HIGH
IMAGE_REL_BASED_LOW
IMAGE_REL_BASED_HIGHLOW
IMAGE_REL_BASED_HIGHADJ
IMAGE_REL_BASED_MIPS_JMPADDR
IMAGE_REL_BASED_ARM_MOV32
IMAGE_REL_BASED_THUMB_MOV32
IMAGE_REL_BASED_MIPS_JMPADDR16
IMAGE_REL_BASED_IA64_IMM64
IMAGE_REL_BASED_DIR64
Definition at line 384 of file pefile.h.
         {                            // 4-bit reloc_type in IMAGE_BASE_RELOCATION relocations
        IMAGE_REL_BASED_ABSOLUTE = 0, // this relocation is ignored
        IMAGE_REL_BASED_IGNORE = 0,   // (unofficial UPX name)
        IMAGE_REL_BASED_HIGH = 1,
        IMAGE_REL_BASED_LOW = 2,
        IMAGE_REL_BASED_HIGHLOW = 3,
        IMAGE_REL_BASED_HIGHADJ = 4,
        IMAGE_REL_BASED_MIPS_JMPADDR = 5,
        IMAGE_REL_BASED_ARM_MOV32 = 5,
        IMAGE_REL_BASED_THUMB_MOV32 = 7,
        IMAGE_REL_BASED_MIPS_JMPADDR16 = 9,
        IMAGE_REL_BASED_IA64_IMM64 = 9,
        IMAGE_REL_BASED_DIR64 = 10,
    };
Constructor & Destructor Documentation
PeFile()
PeFile::PeFile (InputFile * f) explicit protected
Definition at line 70 of file pefile.cpp.
                           : super(f) {
    bele = &N_BELE_RTP::le_policy;
    COMPILE_TIME_ASSERT(sizeof(ddirs_t) == 8)
    COMPILE_TIME_ASSERT(sizeof(pe_section_t) == 40)
    COMPILE_TIME_ASSERT_ALIGNED1(ddirs_t)
    COMPILE_TIME_ASSERT_ALIGNED1(pe_section_t)
    COMPILE_TIME_ASSERT(RT_LAST == TABLESIZE(opt->win32_pe.compress_rt))
    isection = nullptr;
    oimport = nullptr;
    oimpdlls = nullptr;
    orelocs = nullptr;
    oexport = nullptr;
    otls = nullptr;
    oresources = nullptr;
    oxrelocs = nullptr;
    icondir_offset = 0;
    icondir_count = 0;
    importbyordinal = false;
    kernel32ordinal = false;
    tlsindex = 0;
    big_relocs = 0;
    sorelocs = 0;
    soxrelocs = 0;
    sotls = 0;
    ilinker = nullptr;
    use_tls_callbacks = false;
    oloadconf = nullptr;
    soloadconf = 0;
    isdll = false;
    isrtm = false;
    isefi = false;
    use_dep_hack = true;
    use_clear_dirty_stack = true;
    use_stub_relocs = true;
}
References Packer::bele, big_relocs, COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, icondir_count, icondir_offset, ilinker, importbyordinal, isdll, isefi, isrtm, kernel32ordinal, N_BELE_RTP::le_policy, oimpdlls, oloadconf, opt, oxrelocs, RT_LAST, soloadconf, sorelocs, sotls, soxrelocs, TABLESIZE, tlsindex, use_clear_dirty_stack, use_dep_hack, use_stub_relocs, and use_tls_callbacks.
~PeFile()
PeFile::~PeFile () protected virtual noexcept
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 3149 of file pefile.cpp.
{
    oimpdlls = nullptr;
    delete[] oxrelocs;
    delete ilinker;
    // delete res;
}
References ilinker, oimpdlls, and oxrelocs.
Member Function Documentation
addKernelImport()
void PeFile::addKernelImport (const char * name) protected
Definition at line 943 of file pefile.cpp.
{ ilinker->add_import(kernelDll(), name); }
References PeFile::ImportLinker::add_import(), ilinker, and kernelDll().
Referenced by addStubImports(), and PackWinCeArm::addStubImports().
addNewRelocations()
virtual void PeFile::addNewRelocations (Reloc & , unsigned) inline protected virtual
Reimplemented in PackW32PeI386, and PackWinCeArm.
Definition at line 57 of file pefile.h.
{}
Referenced by pack0().
addStubImports()
void PeFile::addStubImports () protected virtual
Reimplemented in PackWinCeArm.
Definition at line 945 of file pefile.cpp.
{
    addKernelImport("LoadLibraryA");
    addKernelImport("GetProcAddress");
    if (!isdll)
        addKernelImport("ExitProcess");
    addKernelImport("VirtualProtect");
}
References addKernelImport(), and isdll.
Referenced by processImports0().
callCompressWithFilters()
void PeFile::callCompressWithFilters (Filter & ft, int filter_strategy, unsigned ih_codebase) protected virtual
Reimplemented in PackWinCeArm.
Definition at line 2248 of file pefile.cpp.
{
    compressWithFilters(&ft, 2048, NULL_cconf, filter_strategy, ih_codebase, rvamin, 0, nullptr, 0);
}
References Packer::compressWithFilters(), NULL_cconf, and rvamin.
Referenced by pack0().
callProcessResources()
void PeFile::callProcessResources (Resource & res, unsigned & ic) protected
Definition at line 2262 of file pefile.cpp.
{
    if (soresources)
        processResources(&res, ic);
    ODADDR(PEDIR_RESOURCE) = soresources ? ic : 0;
    ODSIZE(PEDIR_RESOURCE) = soresources;
    ic += soresources;
}
References ODADDR(), ODSIZE(), PEDIR_RESOURCE, processResources(), and soresources.
Referenced by pack0().
callProcessStubRelocs()
void PeFile::callProcessStubRelocs (Reloc & rel, unsigned & ic) protected
Definition at line 2252 of file pefile.cpp.
{
    // WinCE wants relocation data at the beginning of a section
    rel.finish(oxrelocs, soxrelocs);
    if (opt->win32_pe.strip_relocs)
        soxrelocs = 0;
    ODADDR(PEDIR_BASERELOC) = soxrelocs ? ic : 0;
    ODSIZE(PEDIR_BASERELOC) = soxrelocs;
    ic += soxrelocs;
}
References PeFile::Reloc::finish(), ODADDR(), ODSIZE(), opt, oxrelocs, PEDIR_BASERELOC, and soxrelocs.
Referenced by pack0().
canUnpack0()
int PeFile::canUnpack0 (unsigned max_sections, unsigned objs, unsigned ih_entry, unsigned ih_size) protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 3090 of file pefile.cpp.
{
    const unsigned min_sections = isefi ? 2 : 3;
    if (objs < min_sections)
        return -1;
    mb_isection.alloc(mem_size(sizeof(pe_section_t), objs));
    isection = SPAN_S_MAKE(pe_section_t, mb_isection); // => isection now is a SPAN_S
    fi->seek(pe_offset + ih_size, SEEK_SET);
    fi->readx(isection, sizeof(pe_section_t) * objs);
    bool is_packed = (objs <= max_sections && (IDSIZE(15) || ih_entry > isection[1].vaddr));
    bool found_ph = false;
    if (memcmp(isection[0].name, "UPX", 3) == 0) {
        // current version
        fi->seek(isection[1].rawdataptr - 64, SEEK_SET);
        found_ph = readPackHeader(1024);
        if (!found_ph) {
            // old versions
            fi->seek(isection[2].rawdataptr, SEEK_SET);
            found_ph = readPackHeader(1024);
        }
    }
    if (is_packed && found_ph)
        return true;
    if (!is_packed && !found_ph)
        return -1;
    if (is_packed && ih_entry < isection[2].vaddr) {
        byte buf[256];
        bool x = false;
        memset(buf, 0, sizeof(buf));
        try {
            fi->seek(ih_entry - isection[1].vaddr + isection[1].rawdataptr, SEEK_SET);
            fi->read(buf, sizeof(buf));
            // FIXME this is for x86
            static const byte magic[] = "\x8b\x1e\x83\xee\xfc\x11\xdb";
            // mov ebx, [esi];    sub esi, -4;    adc ebx,ebx
            int offset = find(buf, sizeof(buf), magic, 7);
            if (offset >= 0 && find(buf + offset + 1, sizeof(buf) - offset - 1, magic, 7) >= 0)
                x = true;
        } catch (...) {
            // x = true;
        }
        if (x)
            throwCantUnpack("file is modified/hacked/protected; take care!!!");
        else
            throwCantUnpack("file is possibly modified/hacked/protected; take care!");
        return false; // not reached
    }
    // FIXME: what should we say here ?
    // throwCantUnpack("file is possibly modified/hacked/protected; take care!");
    return false;
}
References MemBuffer::alloc(), buf, PackerBase::fi, find(), IDSIZE(), isefi, mb_isection, mem_size(), memcmp(), memset(), pe_offset, InputFile::read(), Packer::readPackHeader(), InputFile::readx(), InputFile::seek(), SEEK_SET, SPAN_S_MAKE, and throwCantUnpack().
Referenced by PeFile32::canUnpack(), and PeFile64::canUnpack().
canUnpackVersion()
virtual bool PeFile::canUnpackVersion (int version) const inline override protected virtual
Reimplemented from Packer.
Definition at line 101 of file pefile.h.
{
        return (version >= 12 && version <= 13);
    }
Referenced by testUnpackVersion().
checkHeaderValues()
void PeFile::checkHeaderValues (unsigned subsystem, unsigned mask, unsigned ih_entry, unsigned ih_filealign) protected
Definition at line 2136 of file pefile.cpp.
{
    if ((1u << subsystem) & ~mask) {
        char buf[100];
        upx_safe_snprintf(buf, sizeof(buf), "PE: subsystem %u is not supported", subsystem);
        throwCantPack(buf);
    }
    // check CLR Runtime Header directory entry
    if (IDSIZE(PEDIR_COM_DESCRIPTOR))
        throwCantPack(".NET files are not yet supported");
    if (isection == nullptr)
        throwCantPack("No section was found");
    if (memcmp(isection[0].name, "UPX", 3) == 0)
        throwAlreadyPackedByUPX();
    if (!opt->force && IDSIZE(15))
        throwCantPack("file is possibly packed/protected (try --force)");
    if (ih_entry && ih_entry < rvamin)
        throwCantPack("run a virus scanner on this file!");
    const unsigned fam1 = ih_filealign - 1;
    if (!upx::has_single_bit(ih_filealign)) { // ih_filealign is not a power of 2
        char buf[32];
        snprintf(buf, sizeof(buf), "bad file alignment %#x", 1 + fam1);
        throwCantPack(buf);
    }
}
References buf, upx::has_single_bit(), IDSIZE(), memcmp(), opt, PEDIR_COM_DESCRIPTOR, rvamin, snprintf, throwAlreadyPackedByUPX(), throwCantPack(), and upx_safe_snprintf().
Referenced by pack0().
checkMachine()
int PeFile::checkMachine (unsigned cpu) static protected
util
Definition at line 125 of file pefile.cpp.
{
    // unsupported
    if (cpu == IMAGE_FILE_MACHINE_IA64)
        throwCantPack("win64/ia64 is not supported");
    if (cpu == IMAGE_FILE_MACHINE_LOONGARCH64)
        throwCantPack("win64/loong64 is not supported");
    if (cpu == IMAGE_FILE_MACHINE_RISCV64)
        throwCantPack("win64/riscv64 is not supported");
    // known but not (yet?) supported
    if (cpu == IMAGE_FILE_MACHINE_ARMNT)
        throwCantPack("win32/armnt is not supported"); // obsolete
    if (cpu == IMAGE_FILE_MACHINE_ARM64)
        throwCantPack("win64/arm64 is not yet supported");
    // FIXME: it seems that arm64ec actually uses MACHINE_AMD64 ???
    if (cpu == IMAGE_FILE_MACHINE_ARM64EC)
        throwCantPack("win64/arm64ec is not yet supported");
    // supported
    if (cpu == IMAGE_FILE_MACHINE_AMD64)
        return UPX_F_W64PE_AMD64;
    if (cpu == IMAGE_FILE_MACHINE_ARM || cpu == IMAGE_FILE_MACHINE_THUMB)
        return UPX_F_WINCE_ARM;
    if (cpu >= IMAGE_FILE_MACHINE_I386 && cpu <= 0x150) // what is this 0x150 ???
        return UPX_F_W32PE_I386;
    // other or unknown (alpha, mips, powerpc, sh, etc.)
    throwCantPack("pefile: unsupported machine %#x", cpu);
    return 0; // pacify msvc
}
References IMAGE_FILE_MACHINE_AMD64, IMAGE_FILE_MACHINE_ARM, IMAGE_FILE_MACHINE_ARM64, IMAGE_FILE_MACHINE_ARM64EC, IMAGE_FILE_MACHINE_ARMNT, IMAGE_FILE_MACHINE_I386, IMAGE_FILE_MACHINE_IA64, IMAGE_FILE_MACHINE_LOONGARCH64, IMAGE_FILE_MACHINE_RISCV64, IMAGE_FILE_MACHINE_THUMB, throwCantPack(), UPX_F_W32PE_I386, UPX_F_W64PE_AMD64, and UPX_F_WINCE_ARM.
Referenced by PackW32PeI386::canPack(), PackW64PeAmd64::canPack(), PackW64PeArm64::canPack(), PackW64PeArm64EC::canPack(), and PackWinCeArm::canPack().
defineSymbols()
virtual void PeFile::defineSymbols (unsigned ncsection, unsigned upxsection, unsigned sizeof_oh, unsigned isize_isplit, unsigned s1addr) protected pure virtual
Implemented in PackW32PeI386, PackW64PeAmd64, PackW64PeArm64, and PackWinCeArm.
Referenced by pack0().
getProcessImportParam()
virtual unsigned PeFile::getProcessImportParam (unsigned) inline protected virtual
Reimplemented in PackWinCeArm.
Definition at line 60 of file pefile.h.
{ return 0; }
Referenced by pack0().
getVersion()
virtual int PeFile::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 33 of file pefile.h.
{ return 13; }
handleStripRelocs()
unsigned PeFile::handleStripRelocs (upx_uint64_t ih_imagebase, upx_uint64_t default_imagebase, LE16 & dllflags) protected
Definition at line 2167 of file pefile.cpp.
{
    if (opt->win32_pe.strip_relocs < 0) {
        if (isdll || isefi || dllflags & IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE)
            opt->win32_pe.strip_relocs = false;
        else
            opt->win32_pe.strip_relocs = ih_imagebase >= default_imagebase;
    }
    if (opt->win32_pe.strip_relocs) {
        if (isdll || isefi)
            throwCantPack("--strip-relocs is not allowed with DLL and EFI images");
        if (dllflags & IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE) {
            if (opt->force) // Disable ASLR
            {
                // The bit is set, so clear it with XOR
                dllflags ^= IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE;
                // HIGH_ENTROPY_VA has no effect without DYNAMIC_BASE, so clear
                // it also if set
                dllflags &= ~(unsigned) IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA;
            } else
                throwCantPack("--strip-relocs is not allowed with ASLR (use "
                              "with --force to remove)");
        }
        if (!opt->force && ih_imagebase < default_imagebase)
            throwCantPack("--strip-relocs may not support this imagebase (try "
                          "with --force)");
        return IMAGE_FILE_RELOCS_STRIPPED;
    } else
        info("Base relocations stripping is disabled for this image");
    return 0;
}
References IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE, IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA, IMAGE_FILE_RELOCS_STRIPPED, info(), isdll, isefi, opt, and throwCantPack().
Referenced by pack0().
IDADDR() [1/2]
LE32 & PeFile::IDADDR (unsigned x) protected
Definition at line 690 of file pefile.cpp.
{ return iddirs[x].vaddr; }
References iddirs, and PeFile::ddirs_t::vaddr.
Referenced by pack0(), processExports(), processImports0(), processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), processResources(), processTls1(), rebuildExports(), rebuildImports(), rebuildResources(), and stripDebug().
IDADDR() [2/2]
const LE32 & PeFile::IDADDR (unsigned x) const protected
Definition at line 694 of file pefile.cpp.
{ return iddirs[x].vaddr; }
References iddirs, and PeFile::ddirs_t::vaddr.
IDSIZE() [1/2]
LE32 & PeFile::IDSIZE (unsigned x) protected
import handling
Definition at line 689 of file pefile.cpp.
{ return iddirs[x].size; }
References iddirs, and PeFile::ddirs_t::size.
Referenced by canUnpack0(), checkHeaderValues(), PackW32PeI386::needForceOption(), pack0(), processExports(), processImports0(), processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), processResources(), PackWinCeArm::processTls(), processTls1(), readSections(), rebuildResources(), and stripDebug().
IDSIZE() [2/2]
const LE32 & PeFile::IDSIZE (unsigned x) const protected
Definition at line 693 of file pefile.cpp.
{ return iddirs[x].size; }
References iddirs, and PeFile::ddirs_t::size.
ilinkerGetAddress()
upx_uint64_t PeFile::ilinkerGetAddress (const char * d, const char * n) const protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 3145 of file pefile.cpp.
{
    return ilinker->getAddress(d, n);
}
References PeFile::ImportLinker::getAddress(), ilinker, and n.
Referenced by PackW32PeI386::defineSymbols(), and PackW64PeAmd64::defineSymbols().
kernelDll()
virtual const char * PeFile::kernelDll () const inline protected virtual
Reimplemented in PackWinCeArm.
Definition at line 128 of file pefile.h.
{ return "KERNEL32.DLL"; }
Referenced by addKernelImport(), and processImports0().
needForceOption()
virtual bool PeFile::needForceOption () const protected pure virtual
Implemented in PackW32PeI386, PackW64PeAmd64, PackW64PeArm64, and PackWinCeArm.
Referenced by pack0().
ODADDR()
LE32 & PeFile::ODADDR (unsigned x) protected
Definition at line 692 of file pefile.cpp.
{ return oddirs[x].vaddr; }
References oddirs, and PeFile::ddirs_t::vaddr.
Referenced by callProcessResources(), callProcessStubRelocs(), pack0(), rebuildExports(), rebuildImports(), rebuildRelocs(), rebuildResources(), and unpack0().
ODSIZE()
LE32 & PeFile::ODSIZE (unsigned x) protected
Definition at line 691 of file pefile.cpp.
{ return oddirs[x].size; }
References oddirs, and PeFile::ddirs_t::size.
Referenced by callProcessResources(), callProcessStubRelocs(), pack0(), rebuildExports(), rebuildImports(), rebuildRelocs(), rebuildResources(), and unpack0().
pack0()
template<typename LEXX , typename ht > void PeFile::pack0 (OutputFile * fo, ht & ih, ht & oh, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only) protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 2309 of file pefile.cpp.
{
    // FIXME: we need to think about better support for --exact
    if (opt->exact)
        throwCantPackExact();
    const unsigned objs = ih.objects;
    readSectionHeaders(objs, sizeof(ih));
    if (!opt->force && needForceOption())
        throwCantPack("unexpected value in PE header (try --force)");
    if (ih.dllflags & IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY) {
        if (opt->force)
            ih.dllflags &= ~(unsigned) IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY;
        else
            throwCantPack("image forces integrity check (use --force to remove)");
    }
    checkHeaderValues(ih.subsystem, subsystem_mask, ih.entry, ih.filealign);
    // remove certificate directory entry
    if (IDSIZE(PEDIR_SECURITY))
        IDSIZE(PEDIR_SECURITY) = IDADDR(PEDIR_SECURITY) = 0;
    if (ih.flags & IMAGE_FILE_RELOCS_STRIPPED)
        opt->win32_pe.strip_relocs = true;
    else
        ih.flags |= handleStripRelocs(ih.imagebase, default_imagebase, ih.dllflags);
    if (isefi) {
        // PIC for EFI only to avoid false positive detections of Win32 images
        // without relocations fixed address is smaller
        if (!opt->win32_pe.strip_relocs)
            use_stub_relocs = false;
        // EFI build tools already clear DOS stub
        // and small file alignment benefits from extra space
        byte stub[0x40];
        memset(stub, 0, sizeof(stub));
        set_le16(stub, 'M' + 'Z' * 256);
        set_le32(stub + sizeof(stub) - sizeof(LE32), sizeof(stub));
        fo->write(stub, sizeof(stub));
        pe_offset = sizeof(stub);
    } else
        handleStub(fi, fo, pe_offset);
    unsigned overlaystart = readSections(objs, ih.imagesize, ih.filealign, ih.datasize);
    unsigned overlay = file_size_u - stripDebug(overlaystart);
    if (overlay >= file_size_u)
        overlay = 0;
    checkOverlay(overlay);
    if (ih.dllflags & IMAGE_DLLCHARACTERISTICS_GUARD_CF) {
        if (opt->force) {
            const unsigned lcsize = IDSIZE(PEDIR_LOAD_CONFIG);
            const unsigned lcaddr = IDADDR(PEDIR_LOAD_CONFIG);
            const unsigned gfpos = 14 * sizeof(ih.imagebase) + 6 * sizeof(LE32) + 4 * sizeof(LE16);
            if (lcaddr && lcsize >= gfpos + sizeof(LE32))
                // GuardFlags: Set IMAGE_GUARD_SECURITY_COOKIE_UNUSED
                // and clear the rest
                set_le32(ibuf.subref("bad guard flags at %#x", lcaddr + gfpos, sizeof(LE32)),
                         0x00000800);
            ih.dllflags ^= IMAGE_DLLCHARACTERISTICS_GUARD_CF;
        } else
            throwCantPack("GUARD_CF enabled PE files are not supported (use --force to disable)");
    }
    Resource res(ibuf, ibuf + ibuf.getSize());
    Interval tlsiv(ibuf);
    Interval loadconfiv(ibuf);
    Export xport((char *) (byte *) ibuf);
    const unsigned dllstrings = processImports();
    processTls(&tlsiv); // call before processRelocs!!
    processLoadConf(&loadconfiv);
    processResources(&res);
    processExports(&xport);
    processRelocs();
    // OutputFile::dump("x1", ibuf, usize);
    // some checks for broken linkers - disable filter if necessary
    bool allow_filter = true;
    if (/*FIXME ih.codebase == ih.database
        ||*/ ih.codebase + ih.codesize > ih.imagesize ||
        (isection[virta2objnum(ih.codebase, isection, objs)].flags & IMAGE_SCN_CNT_CODE) == 0)
        allow_filter = false;
    const unsigned oam1 = ih.objectalign - 1;
    if (!upx::has_single_bit(ih.objectalign)) { // ih.objectalign is not a power of 2
        char buf[32];
        snprintf(buf, sizeof(buf), "bad object alignment %#x", 1 + oam1);
        throwCantPack(buf);
    }
    // FIXME: if the last object has a bss then this won't work
    // newvsize = (isection[objs-1].vaddr + isection[objs-1].size + oam1) &~ oam1;
    // temporary solution:
    unsigned newvsize = (isection[objs - 1].vaddr + isection[objs - 1].vsize + oam1) & ~oam1;
    NO_fprintf(stderr, "newvsize=%x objs=%d\n", newvsize, objs);
    if ((upx_uint64_t) newvsize + soimport + sorelocs > ibuf.getSize())
        throwInternalError("buffer too small 2");
    memcpy(ibuf + newvsize, oimport, soimport);
    memcpy(ibuf + newvsize + soimport, orelocs, sorelocs);
    cimports = newvsize - rvamin;  // rva of preprocessed imports
    crelocs = cimports + soimport; // rva of preprocessed fixups
    ph.u_len = newvsize + soimport + sorelocs;
    // some extra_info data for uncompression support
    unsigned s = 0;
    byte *const p1 = ibuf.subref("bad ph.u_len %#x", ph.u_len, sizeof(ih));
    memcpy(p1 + s, &ih, sizeof(ih));
    s += sizeof(ih);
    memcpy(p1 + s, isection, ih.objects * sizeof(*isection));
    s += ih.objects * sizeof(*isection);
    if (soimport) {
        set_le32(p1 + s, cimports);
        set_le32(p1 + s + 4, dllstrings);
        s += 8;
    }
    if (sorelocs) {
        set_le32(p1 + s, crelocs);
        p1[s + 4] = (byte) (big_relocs & 6);
        s += 5;
    }
    if (soresources) {
        set_le16(p1 + s, icondir_count);
        s += 2;
    }
    // end of extra_info data
    set_le32(p1 + s, ptr_diff_bytes(p1, ibuf) - rvamin);
    s += 4;
    ph.u_len += s;
    obuf.allocForCompression(ph.u_len);
    // prepare packheader
    if (ph.u_len < rvamin) { // readSectionHeaders() should have caught this
        char buf[64];
        snprintf(buf, sizeof(buf), "bad PE header  ph.u_len=%#x  rvamin=%#x", ph.u_len, rvamin);
        throwInternalError(buf);
    }
    ph.u_len -= rvamin;
    // prepare filter
    Filter ft(ph.level);
    ft.buf_len = ih.codesize;
    ft.addvalue = ih.codebase - rvamin;
    // compress
    int filter_strategy = allow_filter ? 0 : -3;
    // disable filters for files with broken headers
    if (ih.codebase + ih.codesize > ph.u_len) {
        ft.buf_len = 1;
        filter_strategy = -3;
    }
    callCompressWithFilters(ft, filter_strategy, ih.codebase);
    // info: see buildLoader()
    newvsize = (ph.u_len + rvamin + ph.overlap_overhead + oam1) & ~oam1;
    if (tlsindex && ((newvsize - ph.c_len - 1024 + oam1) & ~oam1) > tlsindex + 4)
        tlsindex = 0;
    const int oh_filealign = UPX_MIN(ih.filealign, 0x200u);
    const unsigned fam1 = oh_filealign - 1;
    int identsize = 0;
    const unsigned codesize = getLoaderSection("IDENTSTR", &identsize);
    assert(identsize > 0);
    unsigned ic;
    getLoaderSection("UPX1HEAD", (int *) &ic);
    identsize += ic;
    const bool has_oxrelocs =
        !opt->win32_pe.strip_relocs && (use_stub_relocs || sotls || loadconfiv.ivnum);
    const bool has_ncsection = has_oxrelocs || soimpdlls || soexport || soresources;
    const unsigned oobjs = last_section_rsrc_only ? 4 : has_ncsection ? 3 : 2;
    pe_section_t osection[4];
    memset(osection, 0, sizeof(osection));
    // section 0 : bss
    //         1 : [ident + header] + packed_data + unpacker + tls + loadconf
    //         2 : not compressed data
    //         3 : resource data -- wince/arm 5 needs a new section for this
    // the last section should start with the resource data, because lots of lame
    // windoze codes assume that resources starts on the beginning of a section
    // note: there should be no data in the last section which needs fixup
    // identsplit - number of ident + (upx header) bytes to put into the PE header
    const unsigned sizeof_osection = sizeof(osection[0]) * oobjs;
    int identsplit = pe_offset + sizeof_osection + sizeof(ht);
    if ((identsplit & fam1) == 0)
        identsplit = 0;
    else if (((identsplit + identsize) ^ identsplit) < oh_filealign)
        identsplit = identsize;
    else
        identsplit = ALIGN_UP_GAP(identsplit, oh_filealign);
    ic = identsize - identsplit;
    const unsigned c_len =
        ((ph.c_len + ic) & 15) == 0 ? ph.c_len : ph.c_len + 16 - ((ph.c_len + ic) & 15);
    obuf.clear(ph.c_len, c_len - ph.c_len);
    const unsigned aligned_sotls = ALIGN_UP(sotls, usizeof(LEXX));
    const unsigned s1size =
        ALIGN_UP(ic + c_len + codesize, usizeof(LEXX)) + aligned_sotls + soloadconf;
    const unsigned s1addr = (newvsize - (ic + c_len) + oam1) & ~oam1;
    const unsigned ncsection = (s1addr + s1size + oam1) & ~oam1;
    const unsigned upxsection = s1addr + ic + c_len;
    Reloc rel(1024); // new stub relocations are put here
    addNewRelocations(rel, upxsection);
    // new PE header
    memcpy(&oh, &ih, sizeof(oh));
    oh.filealign = oh_filealign; // identsplit depends on this
    oh.entry = upxsection;
    oh.objects = oobjs;
    oh.chksum = 0;
    // fill the data directory
    ODADDR(PEDIR_DEBUG) = 0;
    ODSIZE(PEDIR_DEBUG) = 0;
    ODADDR(PEDIR_IAT) = 0;
    ODSIZE(PEDIR_IAT) = 0;
    ODADDR(PEDIR_BOUND_IMPORT) = 0;
    ODSIZE(PEDIR_BOUND_IMPORT) = 0;
    // tls & loadconf are put into section 1
    ic = s1addr + s1size - aligned_sotls - soloadconf;
    if (use_tls_callbacks)
        tls_handler_offset = linker->getSymbolOffset("PETLSC2") + upxsection;
    processTls(&rel, &tlsiv, ic);
    ODADDR(PEDIR_TLS) = aligned_sotls ? ic : 0;
    ODSIZE(PEDIR_TLS) = aligned_sotls ? (sizeof(LEXX) == 4 ? 0x18 : 0x28) : 0;
    ic += aligned_sotls;
    processLoadConf(&rel, &loadconfiv, ic);
    ODADDR(PEDIR_LOAD_CONFIG) = soloadconf ? ic : 0;
    ODSIZE(PEDIR_LOAD_CONFIG) = soloadconf;
    ic += soloadconf;
    const bool rel_at_sections_start = last_section_rsrc_only;
    ic = ncsection;
    if (!last_section_rsrc_only)
        callProcessResources(res, ic);
    if (rel_at_sections_start)
        callProcessStubRelocs(rel, ic);
    processImports2(ic, getProcessImportParam(upxsection));
    ODADDR(PEDIR_IMPORT) = soimpdlls ? ic : 0;
    ODSIZE(PEDIR_IMPORT) = soimpdlls;
    ic += soimpdlls;
    processExports(&xport, ic);
    ODADDR(PEDIR_EXPORT) = soexport ? ic : 0;
    ODSIZE(PEDIR_EXPORT) = soexport;
    if (!isdll && opt->win32_pe.compress_exports) {
        ODADDR(PEDIR_EXPORT) = IDADDR(PEDIR_EXPORT);
        ODSIZE(PEDIR_EXPORT) = IDSIZE(PEDIR_EXPORT);
    }
    ic += soexport;
    if (!rel_at_sections_start)
        callProcessStubRelocs(rel, ic);
    // when the resource is put alone into section 3
    const unsigned res_start = (ic + oam1) & ~oam1;
    if (last_section_rsrc_only)
        callProcessResources(res, ic = res_start);
    defineSymbols(ncsection, upxsection, sizeof(oh), identsize - identsplit, s1addr);
    defineFilterSymbols(&ft);
    relocateLoader();
    const unsigned lsize = getLoaderSize();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, lsize);
    const unsigned ncsize =
        soxrelocs + soimpdlls + soexport + (!last_section_rsrc_only ? soresources : 0);
    assert((soxrelocs == 0) == !has_oxrelocs);
    assert((ncsize == 0) == !has_ncsection);
    // this one is tricky: it seems windoze touches 4 bytes after
    // the end of the relocation data - so we have to increase
    // the virtual size of this section
    const unsigned ncsize_virt_increase = soxrelocs && (ncsize & oam1) == 0 ? 8 : 0;
    // fill the sections
    strcpy(osection[0].name, "UPX0");
    strcpy(osection[1].name, "UPX1");
    // after some windoze debugging I found that the name of the sections
    // DOES matter :( .rsrc is used by oleaut32.dll (TYPELIBS)
    // and because of this lame dll, the resource stuff must be the
    // first in the 3rd section - the author of this dll seems to be
    // too idiot to use the data directories... M$ suxx 4 ever!
    // ... even worse: exploder.exe in NiceTry also depends on this to
    // locate version info
    strcpy(osection[2].name, !last_section_rsrc_only && soresources ? ".rsrc" : "UPX2");
    osection[0].vaddr = rvamin;
    osection[1].vaddr = s1addr;
    osection[2].vaddr = ncsection;
    osection[0].size = 0;
    osection[1].size = (s1size + fam1) & ~fam1;
    osection[2].size = (ncsize + fam1) & ~fam1;
    osection[0].vsize = osection[1].vaddr - osection[0].vaddr;
    if (!last_section_rsrc_only) {
        osection[1].vsize = (osection[1].size + oam1) & ~oam1;
        osection[2].vsize = (osection[2].size + ncsize_virt_increase + oam1) & ~oam1;
        oh.imagesize = osection[2].vaddr + osection[2].vsize;
        osection[0].rawdataptr = (pe_offset + sizeof(ht) + sizeof_osection + fam1) & ~(size_t) fam1;
        osection[1].rawdataptr = osection[0].rawdataptr;
    } else {
        osection[1].vsize = osection[1].size;
        osection[2].vsize = osection[2].size;
        osection[0].rawdataptr = 0;
        osection[1].rawdataptr = (pe_offset + sizeof(ht) + sizeof_osection + fam1) & ~(size_t) fam1;
    }
    osection[2].rawdataptr = osection[1].rawdataptr + osection[1].size;
    osection[0].flags = IMAGE_SCN_CNT_UNINITIALIZED_DATA | IMAGE_SCN_MEM_READ |
                        IMAGE_SCN_MEM_WRITE | IMAGE_SCN_MEM_EXECUTE;
    osection[1].flags = IMAGE_SCN_CNT_INITIALIZED_DATA | IMAGE_SCN_MEM_READ | IMAGE_SCN_MEM_WRITE |
                        IMAGE_SCN_MEM_EXECUTE;
    osection[2].flags = IMAGE_SCN_CNT_INITIALIZED_DATA | IMAGE_SCN_MEM_READ | IMAGE_SCN_MEM_WRITE;
    if (last_section_rsrc_only) {
        strcpy(osection[3].name, ".rsrc");
        osection[3].vaddr = res_start;
        osection[3].size = (soresources + fam1) & ~fam1;
        osection[3].vsize = osection[3].size;
        osection[3].rawdataptr = osection[2].rawdataptr + osection[2].size;
        osection[2].flags = IMAGE_SCN_CNT_INITIALIZED_DATA | IMAGE_SCN_MEM_READ;
        osection[3].flags = IMAGE_SCN_CNT_INITIALIZED_DATA | IMAGE_SCN_MEM_READ;
        oh.imagesize = (osection[3].vaddr + osection[3].vsize + oam1) & ~oam1;
        if (soresources == 0) {
            oh.objects = 3;
            mem_clear(&osection[3]);
        }
    }
    oh.bsssize = osection[0].vsize;
    oh.datasize = osection[2].vsize + (oobjs > 3 ? osection[3].vsize : 0);
    setOhDataBase(osection);
    oh.codesize = osection[1].vsize;
    oh.codebase = osection[1].vaddr;
    setOhHeaderSize(osection);
    if (rvamin < osection[0].rawdataptr) {
        throwCantPack("object alignment too small rvamin=%#x oraw=%#x", rvamin,
                      unsigned(osection[0].rawdataptr));
    }
    if (opt->win32_pe.strip_relocs)
        oh.flags |= IMAGE_FILE_RELOCS_STRIPPED;
    ibuf.clear(0, oh.filealign);
    info("Image size change: %u -> %u KiB", ih.imagesize / 1024, oh.imagesize / 1024);
    infoHeader("[Writing compressed file]");
    // write loader + compressed file
    fo->write(&oh, sizeof(oh));
    fo->write(osection, sizeof(osection[0]) * oobjs);
    // some alignment
    if (identsplit == identsize) {
        unsigned n = osection[!last_section_rsrc_only ? 0 : 1].rawdataptr - fo->getBytesWritten() -
                     identsize;
        assert(n <= oh.filealign);
        fo->write(ibuf, n);
    }
    fo->write(loader + codesize, identsize);
    infoWriting("loader", fo->getBytesWritten());
    fo->write(obuf, c_len);
    infoWriting("compressed data", c_len);
    fo->write(loader, codesize);
    if (opt->debug.dump_stub_loader)
        OutputFile::dump(opt->debug.dump_stub_loader, loader, codesize);
    if ((ic = fo->getBytesWritten() & (sizeof(LEXX) - 1)) != 0)
        fo->write(ibuf, sizeof(LEXX) - ic);
    fo->write(otls, aligned_sotls);
    fo->write(oloadconf, soloadconf);
    if ((ic = fo->getBytesWritten() & fam1) != 0)
        fo->write(ibuf, oh.filealign - ic);
    if (!last_section_rsrc_only)
        fo->write(oresources, soresources);
    else
        fo->write(oxrelocs, soxrelocs);
    fo->write(oimpdlls, soimpdlls);
    fo->write(oexport, soexport);
    if (!last_section_rsrc_only)
        fo->write(oxrelocs, soxrelocs);
    if ((ic = fo->getBytesWritten() & fam1) != 0)
        fo->write(ibuf, oh.filealign - ic);
    if (last_section_rsrc_only) {
        fo->write(oresources, soresources);
        if ((ic = fo->getBytesWritten() & fam1) != 0)
            fo->write(ibuf, oh.filealign - ic);
    }
#if 0
    printf("%-13s: program hdr  : %8d bytes\n", getName(), (int) sizeof(oh));
    printf("%-13s: sections     : %8d bytes\n", getName(), (int) sizeof(osection[0]) * oobjs);
    printf("%-13s: ident        : %8d bytes\n", getName(), (int) identsize);
    printf("%-13s: compressed   : %8d bytes\n", getName(), (int) c_len);
    printf("%-13s: decompressor : %8d bytes\n", getName(), (int) codesize);
    printf("%-13s: tls          : %8d bytes\n", getName(), (int) sotls);
    printf("%-13s: aligned_tls  : %8d bytes\n", getName(), (int) aligned_sotls);
    printf("%-13s: resources    : %8d bytes\n", getName(), (int) soresources);
    printf("%-13s: imports      : %8d bytes\n", getName(), (int) soimpdlls);
    printf("%-13s: exports      : %8d bytes\n", getName(), (int) soexport);
    printf("%-13s: relocs       : %8d bytes\n", getName(), (int) soxrelocs);
    printf("%-13s: loadconf     : %8d bytes\n", getName(), (int) soloadconf);
    // linker->dumpSymbols();
#endif
    // verify
    verifyOverlappingDecompression();
    // copy the overlay
    copyOverlay(fo, overlay, obuf);
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References addNewRelocations(), Filter::addvalue, ALIGN_UP, ALIGN_UP_GAP, MemBuffer::allocForCompression(), big_relocs, buf, Filter::buf_len, PackHeader::c_len, callCompressWithFilters(), callProcessResources(), callProcessStubRelocs(), Packer::checkFinalCompressionRatio(), checkHeaderValues(), Packer::checkOverlay(), cimports, MemBuffer::clear(), Packer::copyOverlay(), crelocs, Packer::defineFilterSymbols(), defineSymbols(), OutputFile::dump(), PackerBase::fi, PackerBase::file_size_u, PeFile::pe_section_t::flags, OutputFile::getBytesWritten(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSize(), PackerBase::getName(), getProcessImportParam(), MemBuffer::getSize(), handleStripRelocs(), Packer::handleStub(), upx::has_single_bit(), Packer::ibuf, icondir_count, IDADDR(), IDSIZE(), IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY, IMAGE_DLLCHARACTERISTICS_GUARD_CF, IMAGE_FILE_RELOCS_STRIPPED, IMAGE_SCN_CNT_CODE, IMAGE_SCN_CNT_INITIALIZED_DATA, IMAGE_SCN_CNT_UNINITIALIZED_DATA, IMAGE_SCN_MEM_EXECUTE, IMAGE_SCN_MEM_READ, IMAGE_SCN_MEM_WRITE, info(), infoHeader(), infoWriting(), isdll, isefi, PeFile::Interval::ivnum, PackHeader::level, mem_clear(), memcpy(), memset(), n, needForceOption(), NO_fprintf(), Packer::obuf, ODADDR(), ODSIZE(), oh, oimpdlls, oloadconf, opt, PackHeader::overlap_overhead, oxrelocs, Packer::patchPackHeader(), pe_offset, PEDIR_BOUND_IMPORT, PEDIR_DEBUG, PEDIR_EXPORT, PEDIR_IAT, PEDIR_IMPORT, PEDIR_LOAD_CONFIG, PEDIR_SECURITY, PEDIR_TLS, PackerBase::ph, processExports(), processImports(), processImports2(), processLoadConf(), processRelocs(), processResources(), processTls(), ptr_diff_bytes(), PeFile::pe_section_t::rawdataptr, readSectionHeaders(), readSections(), Packer::relocateLoader(), rvamin, set_le16(), set_le32(), setOhDataBase(), setOhHeaderSize(), PeFile::pe_section_t::size, snprintf, soexport, soimpdlls, soimport, soloadconf, sorelocs, soresources, sotls, soxrelocs, strcpy(), stripDebug(), MemBuffer::subref(), throwCantPack(), throwCantPackExact(), throwInternalError(), throwNotCompressible(), tls_handler_offset, tlsindex, PackHeader::u_len, UPX_MIN, use_stub_relocs, use_tls_callbacks, usizeof, PeFile::pe_section_t::vaddr, Packer::verifyOverlappingDecompression(), virta2objnum(), PeFile::pe_section_t::vsize, and OutputFile::write().
processExports() [1/2]
void PeFile::processExports (Export * xport) protected
Definition at line 1305 of file pefile.cpp.
{
    soexport = ALIGN_UP(IDSIZE(PEDIR_EXPORT), 4u);
    if (soexport == 0)
        return;
    if (!isdll && opt->win32_pe.compress_exports) {
        infoWarning("exports compressed, --compress-exports=0 might be needed");
        soexport = 0;
        return;
    }
    xport->convert(IDADDR(PEDIR_EXPORT), IDSIZE(PEDIR_EXPORT));
    soexport = ALIGN_UP(xport->getsize(), 4u);
    mb_oexport.alloc(soexport);
    mb_oexport.clear();
    oexport = mb_oexport;
}
References ALIGN_UP, MemBuffer::alloc(), MemBuffer::clear(), PeFile::Export::convert(), PeFile::Export::getsize(), IDADDR(), IDSIZE(), infoWarning(), isdll, mb_oexport, opt, PEDIR_EXPORT, and soexport.
Referenced by pack0(), and rebuildExports().
processExports() [2/2]
void PeFile::processExports (Export * xport, unsigned newoffs) protected
Definition at line 1322 of file pefile.cpp.
{
    if (soexport)
        xport->build((char *) raw_bytes(oexport, 0), newoffs);
}
References PeFile::Export::build(), raw_bytes(), and soexport.
processImports()
virtual unsigned PeFile::processImports () protected pure virtual
Implemented in PeFile32, and PeFile64.
Referenced by pack0().
processImports0()
template<typename LEXX , typename ord_mask_t > unsigned PeFile::processImports0 (ord_mask_t ord_mask) protected
Definition at line 965 of file pefile.cpp.
                                                    { // pass 1
    if (isefi) {
        if (IDSIZE(PEDIR_IMPORT))
            throwCantPack("imports not supported on EFI");
        return 0;
    }
    unsigned dllnum = 0;
    const unsigned skip = IDADDR(PEDIR_IMPORT);
    const unsigned take = IDSIZE(PEDIR_IMPORT);
    import_desc *const im_start = (import_desc *) ibuf.subref("bad import %#x", skip, take);
    if (IDADDR(PEDIR_IMPORT) != 0) {
        for (const import_desc *im = im_start;; ++dllnum, ++im) {
            const unsigned skip2 = ptr_udiff_bytes(im, ibuf);
            (void) ibuf.subref("bad import %#x", skip2, sizeof(*im));
            if (im->dllname == 0)
                break;
        }
    }
    if (dllnum > 4096) // just some arbitrary limit/sanity check
        throwCantPack("too many DLL imports %u", dllnum);
    struct UDll final {
        const byte *name;
        const byte *shname;
        unsigned ordinal;
        unsigned iat;
        const LEXX *lookupt;
        unsigned original_position;
        bool isk32;
        static int __acc_cdecl_qsort compare(const void *aa, const void *bb) {
            const UDll *a = *(const UDll *const *) aa;
            const UDll *b = *(const UDll *const *) bb;
            if (a->original_position == b->original_position) // identical object, poor qsort()
                return 0;
            if (a->isk32 != b->isk32)
                return a->isk32 ? -1 : 1;
            if ((*a->lookupt != 0) != (*b->lookupt != 0))
                return (*a->lookupt != 0) ? -1 : 1;
            int rc = strcasecmp(a->name, b->name);
            if (rc != 0)
                return rc;
            if ((a->ordinal != 0) != (b->ordinal != 0))
                return (a->ordinal != 0) ? -1 : 1;
            if (a->shname && b->shname) {
                rc = (int) (upx_safe_strlen(a->shname) - upx_safe_strlen(b->shname));
                if (rc != 0)
                    return rc;
                rc = strcmp(a->shname, b->shname);
                if (rc != 0)
                    return rc;
            } else if ((a->shname != nullptr) != (b->shname != nullptr))
                return (a->shname != nullptr) ? -1 : 1;
            // What could remain?
            // make sort order deterministic
            return a->original_position < b->original_position ? -1 : 1;
        }
    };
    // +1 for dllnum=0
    Array(UDll, dlls, dllnum + 1);
    Array(UDll *, idlls, dllnum + 1);
    soimport = 1024; // safety
    for (unsigned ic = 0; ic < dllnum; ic++) {
        const import_desc *const im = im_start + ic;
        idlls[ic] = dlls + ic;
        dlls[ic].name = ibuf.subref("bad dllname %#x", im->dllname, 1);
        dlls[ic].shname = nullptr;
        dlls[ic].ordinal = 0;
        dlls[ic].iat = im->iat;
        const unsigned skip2 = (im->oft ? im->oft : im->iat);
        dlls[ic].lookupt = (LEXX *) ibuf.subref("bad dll lookupt %#x", skip2, sizeof(LEXX));
        dlls[ic].original_position = ic;
        dlls[ic].isk32 = strcasecmp(kernelDll(), dlls[ic].name) == 0;
        soimport += strlen(dlls[ic].name) + 1 + 4;
        for (IPTR_VAR(const LEXX, tarr, dlls[ic].lookupt); *tarr; tarr += 1) {
            if (*tarr & ord_mask) {
                importbyordinal = true;
                soimport += 2; // ordinal num: 2 bytes
                dlls[ic].ordinal = *tarr & 0xffff;
            } else {
                // it's an import by name
                IPTR_VAR(const byte, const name, ibuf + (*tarr + 2));
                unsigned len = strlen(name);
                soimport += len + 1;
                if (dlls[ic].shname == nullptr || len < strlen(dlls[ic].shname))
                    dlls[ic].shname = ibuf + (*tarr + 2);
            }
            soimport++; // separator
        }
    }
    mb_oimport.alloc(soimport);
    mb_oimport.clear();
    oimport = mb_oimport;
    // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
    upx_qsort(idlls, dllnum, sizeof(idlls[0]), UDll::compare);
    info("Processing imports: %d DLLs", dllnum);
    for (unsigned ic = 0; ic < dllnum; ic++) {
        info("  DLL %3d %s %s", ic, idlls[ic]->name, idlls[ic]->shname);
    }
    ilinker = new ImportLinker(sizeof(LEXX));
    // create the new import table
    addStubImports();
    for (unsigned ic = 0; ic < dllnum; ic++) {
        if (idlls[ic]->isk32) {
            // for kernel32.dll we need to put all the imported
            // ordinals into the output import table, as on
            // some versions of windows GetProcAddress does not resolve them
            if (strcasecmp(idlls[ic]->name, "kernel32.dll"))
                continue;
            if (idlls[ic]->ordinal)
                for (const LEXX *tarr = idlls[ic]->lookupt; *tarr; tarr++)
                    if (*tarr & ord_mask) {
                        ilinker->add_import(kernelDll(), *tarr & 0xffff);
                        kernel32ordinal = true;
                    }
        } else if (!ilinker->hasDll(idlls[ic]->name)) {
            if (idlls[ic]->shname && !idlls[ic]->ordinal)
                ilinker->add_import(idlls[ic]->name, idlls[ic]->shname);
            else
                ilinker->add_import(idlls[ic]->name, idlls[ic]->ordinal);
        }
    }
    soimpdlls = ilinker->build();
    Interval names(ibuf), iats(ibuf), lookups(ibuf);
    // create the preprocessed data
    SPAN_S_VAR(byte, ppi, oimport); // preprocessed imports
    for (unsigned ic = 0; ic < dllnum; ic++) {
        const LEXX *tarr = idlls[ic]->lookupt;
        set_le32(ppi, ilinker->getAddress(idlls[ic]->name));
        set_le32(ppi + 4, idlls[ic]->iat - rvamin);
        ppi += 8;
        for (; *tarr; tarr++)
            if (*tarr & ord_mask) {
                const unsigned ord = *tarr & 0xffff;
                if (idlls[ic]->isk32 && kernel32ordinal) {
                    *ppi++ = 0xfe; // signed + odd parity
                    set_le32(ppi, ilinker->getAddress(idlls[ic]->name, ord));
                    ppi += 4;
                } else {
                    *ppi++ = 0xff;
                    set_le16(ppi, ord);
                    ppi += 2;
                }
            } else {
                *ppi++ = 1;
                const unsigned skip2 = 2 + *tarr;
                const unsigned take2 = 1 + strlen(ibuf.subref("bad import name %#x", skip2, 1));
                memcpy(ppi, ibuf.subref("bad import name %#x", skip2, take2), take2);
                ppi += take2;
                names.add_interval(*tarr, 2 + take2);
            }
        ppi++;
        const unsigned esize = ptr_udiff_bytes(tarr, idlls[ic]->lookupt);
        lookups.add_interval(idlls[ic]->lookupt, esize);
        if (ptr_diff_bytes(ibuf.subref("bad import name %#x", idlls[ic]->iat, 1),
                           idlls[ic]->lookupt) != 0) {
            memcpy(ibuf.subref("bad import name %#x", idlls[ic]->iat, esize), idlls[ic]->lookupt,
                   esize);
            iats.add_interval(idlls[ic]->iat, esize);
        }
        names.add_interval(idlls[ic]->name, strlen(idlls[ic]->name) + 1 + 1);
    }
    ppi += 4;
    assert(ppi < oimport + soimport);
    soimport = ptr_diff_bytes(ppi, oimport);
    if (soimport == 4)
        soimport = 0;
    // OutputFile::dump("x0.imp", oimport, soimport);
    unsigned ilen = 0;
    names.flatten();
    if (names.ivnum > 1) {
        // The area occupied by the dll and imported names is not continuous
        // so to still support uncompression, I can't zero the iat area.
        // This decreases compression ratio, so FIXME somehow.
        infoWarning("can't remove unneeded imports");
        ilen += sizeof(import_desc) * dllnum;
#if TESTING
        if (opt->verbose > 3)
            names.dump();
#endif
        // do some work for the unpacker
        for (unsigned ic = 0; ic < dllnum; ic++) {
            import_desc *const im = im_start + ic;
            memset(im, FILLVAL, sizeof(*im));
            im->dllname = ptr_udiff_bytes(dlls[idlls[ic]->original_position].name, ibuf);
        }
    } else {
        iats.add_interval(im_start, sizeof(import_desc) * dllnum);
        // zero unneeded data
        iats.clear();
        lookups.clear();
    }
    names.clear();
    iats.add_interval(&names);
    iats.add_interval(&lookups);
    iats.flatten();
    for (unsigned ic = 0; ic < iats.ivnum; ic++)
        ilen += iats.ivarr[ic].len;
    info("Imports: original size: %u bytes, preprocessed size: %u bytes", ilen, soimport);
    return names.ivnum == 1 ? names.ivarr[0].start : 0;
}
References __acc_cdecl_qsort, PeFile::ImportLinker::add_import(), PeFile::Interval::add_interval(), addStubImports(), MemBuffer::alloc(), Array, b, PeFile::ImportLinker::build(), PeFile::Interval::clear(), MemBuffer::clear(), PeFile::import_desc::dllname, FILLVAL, PeFile::ImportLinker::getAddress(), PeFile::ImportLinker::hasDll(), PeFile::import_desc::iat, Packer::ibuf, IDADDR(), IDSIZE(), ilinker, importbyordinal, info(), infoWarning(), IPTR_VAR, isefi, kernel32ordinal, kernelDll(), mb_oimport, memcpy(), memset(), PeFile::import_desc::oft, opt, PEDIR_IMPORT, ptr_diff_bytes(), ptr_udiff_bytes(), rvamin, set_le16(), set_le32(), soimpdlls, soimport, SPAN_S_VAR, strcasecmp(), strcmp(), strlen, MemBuffer::subref(), throwCantPack(), upx_qsort, and upx_safe_strlen().
processImports2()
void PeFile::processImports2 (unsigned myimport, unsigned) protected virtual
Reimplemented in PackWinCeArm.
Definition at line 953 of file pefile.cpp.
                                                        { // pass 2
    COMPILE_TIME_ASSERT(sizeof(import_desc) == 20)
    if (ilinker == nullptr)
        return;
    ilinker->relocate_import(myimport);
    int len;
    oimpdlls = ilinker->getLoader(&len);
    assert(len == (int) soimpdlls);
    // OutputFile::dump("x1.imp", oimpdlls, soimpdlls);
}
References COMPILE_TIME_ASSERT, ElfLinker::getLoader(), ilinker, oimpdlls, PeFile::ImportLinker::relocate_import(), and soimpdlls.
Referenced by pack0(), and PackWinCeArm::processImports2().
processLoadConf() [1/2]
void PeFile::processLoadConf (Interval * iv) protected
Load Configuration handling.
Definition at line 1522 of file pefile.cpp.
                                         { // pass 1
    if (IDSIZE(PEDIR_LOAD_CONFIG) == 0)
        return;
    const unsigned lcaddr = IDADDR(PEDIR_LOAD_CONFIG);
    const byte *const loadconf = ibuf.subref("bad loadconf %#x", lcaddr, 4);
    soloadconf = get_le32(loadconf);
    if (soloadconf == 0)
        return;
    static constexpr unsigned MAX_SOLOADCONF = 256; // XXX FIXME: Why?
    if (soloadconf > MAX_SOLOADCONF)
        info("Load Configuration directory %u > %u", soloadconf, MAX_SOLOADCONF);
    // if there were relocation entries referring to the load config table
    // then we need them for the copy of the table too
    const unsigned skip = IDADDR(PEDIR_BASERELOC);
    const unsigned take = IDSIZE(PEDIR_BASERELOC);
    Reloc rel(ibuf.subref("bad reloc %#x", skip, take), take);
    unsigned pos, type;
    while (rel.next(pos, type))
        if (pos >= lcaddr && pos < lcaddr + soloadconf) {
            iv->add_interval(pos - lcaddr, type);
            NO_printf("loadconf reloc detected: %x\n", pos);
        }
    mb_oloadconf.alloc(soloadconf);
    oloadconf = (byte *) mb_oloadconf.getVoidPtr();
    memcpy(oloadconf, loadconf, soloadconf);
}
References PeFile::Interval::add_interval(), MemBuffer::alloc(), get_le32(), MemBuffer::getVoidPtr(), Packer::ibuf, IDADDR(), IDSIZE(), info(), mb_oloadconf, memcpy(), PeFile::Reloc::next(), NO_printf(), oloadconf, PEDIR_BASERELOC, PEDIR_LOAD_CONFIG, soloadconf, and MemBuffer::subref().
processLoadConf() [2/2]
void PeFile::processLoadConf (Reloc * rel, const Interval * iv, unsigned newaddr) protected
Definition at line 1552 of file pefile.cpp.
{
    // now we have the address of the new load config table
    // so we can create the new relocation entries
    for (unsigned ic = 0; ic < iv->ivnum; ic++) {
        rel->add_reloc(iv->ivarr[ic].start + newaddr, iv->ivarr[ic].len);
        NO_printf("loadconf reloc added: %x %d\n", iv->ivarr[ic].start + newaddr,
                  iv->ivarr[ic].len);
    }
}
References PeFile::Reloc::add_reloc(), PeFile::Interval::ivarr, PeFile::Interval::ivnum, PeFile::Interval::interval::len, NO_printf(), and PeFile::Interval::interval::start.
Referenced by pack0().
processRelocs()
virtual void PeFile::processRelocs () protected pure virtual
Implemented in PeFile32, and PeFile64.
Referenced by pack0().
processResources() [1/2]
void PeFile::processResources (Resource * res) protected
Definition at line 1916 of file pefile.cpp.
{
    const unsigned vaddr = IDADDR(PEDIR_RESOURCE);
    if ((soresources = IDSIZE(PEDIR_RESOURCE)) == 0)
        return;
    // setup default options for resource compression
    if (opt->win32_pe.compress_resources.isThird())
        opt->win32_pe.compress_resources = !isefi;
    if (!opt->win32_pe.compress_resources) {
        opt->win32_pe.compress_icons = false;
        for (int i = 0; i < RT_LAST; i++)
            opt->win32_pe.compress_rt[i] = false;
    }
    if (opt->win32_pe.compress_rt[RT_STRING].isThird()) {
        // by default, don't compress RT_STRINGs of screensavers (".scr")
        opt->win32_pe.compress_rt[RT_STRING] = true;
        if (fn_has_ext(fi->getName(), "scr"))
            opt->win32_pe.compress_rt[RT_STRING] = false;
    }
    res->init(ibuf.subref("bad res %#x", vaddr, 1));
    for (soresources = res->dirsize(); res->next(); soresources += 4 + res->size())
        ;
    mb_oresources.alloc(soresources);
    mb_oresources.clear();
    oresources = mb_oresources; // => SPAN_S
    SPAN_S_VAR(byte, ores, oresources + res->dirsize());
    char *keep_icons = nullptr; // icon ids in the first icon group
    const auto keep_icons_deleter = upx::ArrayDeleter(&keep_icons, 1); // don't leak memory
    unsigned iconsin1stdir = 0;
    if (opt->win32_pe.compress_icons == 2)
        while (res->next()) // there is no rewind() in Resource
            if (res->itype() == RT_GROUP_ICON && iconsin1stdir == 0) {
                iconsin1stdir = get_le16(ibuf.subref("bad resoff %#x", res->offs() + 4, 2));
                delete[] keep_icons;
                keep_icons = nullptr;
                keep_icons = New(char, 1 + iconsin1stdir * 9);
                *keep_icons = 0;
                for (unsigned ic = 0; ic < iconsin1stdir; ic++)
                    upx_safe_snprintf(
                        keep_icons + strlen(keep_icons), 9, "3/%u,",
                        get_le16(ibuf.subref("bad resoff %#x", res->offs() + 6 + ic * 14 + 12, 2)));
                if (*keep_icons)
                    keep_icons[strlen(keep_icons) - 1] = 0;
            }
    // the icon id which should not be compressed when compress_icons == 1
    unsigned first_icon_id = (unsigned) -1;
    if (opt->win32_pe.compress_icons == 1)
        while (res->next())
            if (res->itype() == RT_GROUP_ICON && first_icon_id == (unsigned) -1)
                first_icon_id = get_le16(ibuf.subref("bad resoff %#x", res->offs() + 6 + 12, 2));
    bool compress_icon = opt->win32_pe.compress_icons > 1;
    bool compress_idir = opt->win32_pe.compress_icons == 3;
    // some statistics
    unsigned usize = 0;
    unsigned csize = 0;
    unsigned unum = 0;
    unsigned cnum = 0;
    while (res->next()) {
        const unsigned rtype = res->itype();
        bool do_compress = true;
        if (!opt->win32_pe.compress_resources)
            do_compress = false;
        else if (rtype == RT_ICON) // icon
        {
            if (opt->win32_pe.compress_icons == 0)
                do_compress = false;
            else if (opt->win32_pe.compress_icons == 1)
                if ((first_icon_id == (unsigned) -1 || first_icon_id == res->iname()))
                    do_compress = compress_icon;
        } else if (rtype == RT_GROUP_ICON) // icon directory
            do_compress = compress_idir && opt->win32_pe.compress_icons;
        else if (rtype > 0 && rtype < RT_LAST)
            do_compress = opt->win32_pe.compress_rt[rtype] ? true : false;
        if (do_compress && keep_icons)
            do_compress &=
                !match(res->itype(), res->ntype(), res->iname(), res->nname(), keep_icons);
        if (do_compress)
            do_compress &= !match(res->itype(), res->ntype(), res->iname(), res->nname(),
                                  "TYPELIB,REGISTRY,16");
        if (do_compress)
            do_compress &= !match(res->itype(), res->ntype(), res->iname(), res->nname(),
                                  opt->win32_pe.keep_resource);
        if (do_compress) {
            csize += res->size();
            cnum++;
            continue;
        }
        usize += res->size();
        unum++;
        set_le32(ores, res->offs()); // save original offset
        ores += 4;
        const unsigned take = res->size();
        ICHECK(ibuf + res->offs(), take);
        memcpy(ores, ibuf.subref("bad resoff %#x", res->offs(), take), take);
        ibuf.fill(res->offs(), take, FILLVAL);
        res->newoffs() = ptr_diff_bytes(ores, oresources);
        if (rtype == RT_ICON && opt->win32_pe.compress_icons == 1)
            compress_icon = true;
        else if (rtype == RT_GROUP_ICON) {
            if (opt->win32_pe.compress_icons == 1) {
                icondir_offset = 4 + ptr_diff_bytes(ores, oresources);
                icondir_count = get_le16(oresources + icondir_offset);
                set_le16(oresources + icondir_offset, 1);
            }
            compress_idir = true;
        }
        ores += res->size();
    }
    soresources = ptr_diff_bytes(ores, oresources);
    if (!res->clear()) {
        // The area occupied by the resource directory is not continuous
        // so to still support uncompression, I can't zero this area.
        // This decreases compression ratio, so FIXME somehow.
        infoWarning("can't remove unneeded resource directory");
    }
    info("Resources: compressed %u (%u bytes), not compressed %u (%u bytes)", cnum, csize, unum,
         usize);
}
References MemBuffer::alloc(), PeFile::Resource::clear(), MemBuffer::clear(), PeFile::Resource::dirsize(), PackerBase::fi, MemBuffer::fill(), FILLVAL, fn_has_ext(), get_le16(), FileBase::getName(), Packer::ibuf, ICHECK, icondir_count, icondir_offset, IDADDR(), IDSIZE(), PeFile::Resource::iname(), info(), infoWarning(), PeFile::Resource::init(), isefi, PeFile::Resource::itype(), match(), mb_oresources, memcpy(), New, PeFile::Resource::newoffs(), PeFile::Resource::next(), PeFile::Resource::nname(), PeFile::Resource::ntype(), PeFile::Resource::offs(), opt, PEDIR_RESOURCE, ptr_diff_bytes(), RT_GROUP_ICON, RT_ICON, RT_LAST, RT_STRING, set_le16(), set_le32(), PeFile::Resource::size(), soresources, SPAN_S_VAR, strlen, MemBuffer::subref(), and upx_safe_snprintf().
Referenced by callProcessResources(), and pack0().
processResources() [2/2]
void PeFile::processResources (Resource * res, unsigned newaddr) protected
Definition at line 1867 of file pefile.cpp.
{
    if (IDSIZE(PEDIR_RESOURCE) == 0)
        return;
    while (res->next())
        if (res->newoffs())
            res->newoffs() += newaddr;
    if (res->dirsize()) {
        byte *p = res->build();
        memcpy(oresources, p, res->dirsize());
    }
}
References PeFile::Resource::build(), PeFile::Resource::dirsize(), IDSIZE(), memcpy(), PeFile::Resource::newoffs(), PeFile::Resource::next(), and PEDIR_RESOURCE.
processTls() [1/2]
virtual void PeFile::processTls (Interval * iv) protected pure virtual
Implemented in PackWinCeArm, PeFile32, and PeFile64.
Referenced by pack0().
processTls() [2/2]
virtual void PeFile::processTls (Reloc * r, const Interval * iv, unsigned a) protected pure virtual
Implemented in PeFile32, and PeFile64.
processTls1()
template<typename LEXX > void PeFile::processTls1 (Interval * iv, typename tls_traits< LEXX >::cb_value_t imagebase, unsigned imagesize) protected
Definition at line 1376 of file pefile.cpp.
                                             { // pass 1
    typedef typename tls_traits<LEXX>::tls tls;
    typedef typename tls_traits<LEXX>::cb_value_t cb_value_t;
    constexpr unsigned cb_size = tls_traits<LEXX>::cb_size;
    COMPILE_TIME_ASSERT(sizeof(tls) == tls_traits<LEXX>::sotls)
    COMPILE_TIME_ASSERT_ALIGNED1(tls)
    if (isefi && IDSIZE(PEDIR_TLS))
        throwCantPack("TLS not supported on EFI");
    const unsigned take = ALIGN_UP(IDSIZE(PEDIR_TLS), 4u);
    sotls = take;
    if (!sotls)
        return;
    const unsigned skip = IDADDR(PEDIR_TLS);
    const tls *const tlsp = (const tls *) ibuf.subref("bad tls %#x", skip, sizeof(tls));
    // note: TLS callbacks are not implemented in Windows 95/98/ME
    if (tlsp->callbacks) {
        if (tlsp->callbacks < imagebase)
            throwCantPack("invalid TLS callback");
        else if (tlsp->callbacks - imagebase + 4 >= imagesize)
            throwCantPack("invalid TLS callback");
        cb_value_t v =
            *(LEXX *) ibuf.subref("bad TLS %#x", (tlsp->callbacks - imagebase), sizeof(LEXX));
        if (v != 0) {
            // count number of callbacks, just for information string - Stefan Widmann
            unsigned num_callbacks = 0;
            unsigned callback_offset = 0;
            while (*(LEXX *) ibuf.subref(
                "bad TLS %#x", tlsp->callbacks - imagebase + callback_offset, sizeof(LEXX))) {
                // increment number of callbacks
                num_callbacks++;
                callback_offset += cb_size;
            }
            info("TLS: %u callback(s) found, adding TLS callback handler", num_callbacks);
            // set flag to include necessary sections in loader
            use_tls_callbacks = true;
            // define linker symbols
            tlscb_ptr = tlsp->callbacks;
        }
    }
    const unsigned tlsdatastart = tlsp->datastart - imagebase;
    const unsigned tlsdataend = tlsp->dataend - imagebase;
    // now some ugly stuff: find the relocation entries in the tls data area
    const unsigned skip2 = IDADDR(PEDIR_BASERELOC);
    const unsigned take2 = IDSIZE(PEDIR_BASERELOC);
    Reloc rel(ibuf.subref("bad tls reloc %#x", skip2, take2), take2);
    unsigned pos, type;
    while (rel.next(pos, type))
        if (pos >= tlsdatastart && pos < tlsdataend)
            iv->add_interval(pos, type);
    sotls = sizeof(tls) + tlsdataend - tlsdatastart;
    // if TLS callbacks are used, we need two more {D|Q}WORDS at the end of the TLS
    // ... and those dwords should be correctly aligned
    if (use_tls_callbacks)
        sotls = ALIGN_UP(sotls, cb_size) + 2 * cb_size;
    const unsigned aligned_sotls = ALIGN_UP(sotls, usizeof(LEXX));
    // the PE loader wants this stuff uncompressed
    mb_otls.alloc(aligned_sotls);
    mb_otls.clear();
    otls = mb_otls; // => otls now is a SPAN_S
    const unsigned skip1 = IDADDR(PEDIR_TLS);
    const unsigned take1 = sizeof(tls);
    memcpy(otls, ibuf.subref("bad tls %#x", skip1, take1), take1);
    // WARNING: this can access data in BSS
    const unsigned take3 = sotls - sizeof(tls);
    memcpy(otls + sizeof(tls), ibuf.subref("bad tls %#x", tlsdatastart, take3), take3);
    tlsindex = tlsp->tlsindex - imagebase;
    // NEW: subtract two dwords if TLS callbacks are used - Stefan Widmann
    info("TLS: %u bytes tls data and %u relocations added",
         sotls - (unsigned) sizeof(tls) - (use_tls_callbacks ? 2 * cb_size : 0), iv->ivnum);
    // makes sure tls index is zero after decompression
    if (tlsindex && tlsindex < imagesize)
        set_le32(ibuf.subref("bad tlsindex %#x", tlsindex, sizeof(unsigned)), 0);
}
References PeFile::Interval::add_interval(), ALIGN_UP, MemBuffer::alloc(), MemBuffer::clear(), COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, Packer::ibuf, IDADDR(), IDSIZE(), info(), isefi, PeFile::Interval::ivnum, mb_otls, memcpy(), PeFile::Reloc::next(), PEDIR_BASERELOC, PEDIR_TLS, set_le32(), sotls, MemBuffer::subref(), throwCantPack(), tlscb_ptr, tlsindex, use_tls_callbacks, and usizeof.
processTls2()
template<typename LEXX > void PeFile::processTls2 (Reloc * rel, const Interval * iv, unsigned newaddr, typename tls_traits< LEXX >::cb_value_t imagebase) protected
Definition at line 1462 of file pefile.cpp.
                                                                        { // pass 2
    typedef typename tls_traits<LEXX>::tls tls;
    typedef typename tls_traits<LEXX>::cb_value_t cb_value_t;
    constexpr unsigned cb_size = tls_traits<LEXX>::cb_size;
    constexpr unsigned reloc_type = tls_traits<LEXX>::reloc_type;
    static_assert(reloc_type > IMAGE_REL_BASED_IGNORE && reloc_type < 16);
    constexpr int tls_handler_offset_reloc = tls_traits<LEXX>::tls_handler_offset_reloc;
    if (sotls == 0)
        return;
    // add new relocation entries
    if (tls_handler_offset > 0 && tls_handler_offset_reloc > 0)
        rel->add_reloc(tls_handler_offset + tls_handler_offset_reloc, reloc_type);
    unsigned ic;
    // NEW: if TLS callbacks are used, relocate the VA of the callback chain, too - Stefan Widmann
    for (ic = 0; ic < (use_tls_callbacks ? 4 * cb_size : 3 * cb_size); ic += cb_size)
        rel->add_reloc(newaddr + ic, reloc_type);
    SPAN_S_VAR(tls, const tlsp, mb_otls);
    // now the relocation entries in the tls data area
    for (ic = 0; ic < iv->ivnum; ic += 4) {
        SPAN_S_VAR(byte, const pp,
                   otls + (iv->ivarr[ic].start - (tlsp->datastart - imagebase) + sizeof(tls)));
        LEXX *const p = (LEXX *) raw_bytes(pp, sizeof(LEXX));
        cb_value_t kc = *p;
        if (kc < tlsp->dataend && kc >= tlsp->datastart) {
            kc += newaddr + sizeof(tls) - tlsp->datastart;
            *p = kc + imagebase;
            rel->add_reloc(kc, iv->ivarr[ic].len);
        } else
            rel->add_reloc(kc - imagebase, iv->ivarr[ic].len);
    }
    const unsigned tls_data_size = tlsp->dataend - tlsp->datastart;
    tlsp->datastart = newaddr + sizeof(tls) + imagebase;
    tlsp->dataend = tlsp->datastart + tls_data_size;
    // NEW: if we have TLS callbacks to handle, we create a pointer to the new callback chain -
    // Stefan Widmann
    tlsp->callbacks = (use_tls_callbacks ? newaddr + sotls + imagebase - 2 * cb_size : 0);
    if (use_tls_callbacks) {
        // set handler offset
        SPAN_S_VAR(byte, pp, otls);
        pp = otls + (sotls - 2 * cb_size);
        *(LEXX *) raw_bytes(pp, sizeof(LEXX)) = tls_handler_offset + imagebase;
        pp = otls + (sotls - 1 * cb_size);
        *(LEXX *) raw_bytes(pp, sizeof(LEXX)) = 0; // end of one-item list
        // add relocation for TLS handler offset
        rel->add_reloc(newaddr + sotls - 2 * cb_size, reloc_type);
    }
}
References PeFile::Reloc::add_reloc(), IMAGE_REL_BASED_IGNORE, PeFile::Interval::ivarr, PeFile::Interval::ivnum, PeFile::Interval::interval::len, mb_otls, raw_bytes(), sotls, SPAN_S_VAR, PeFile::Interval::interval::start, tls_handler_offset, and use_tls_callbacks.
readFileHeader()
int PeFile::readFileHeader () protected virtual
Reimplemented in PackW32PeI386.
Definition at line 156 of file pefile.cpp.
{
    struct alignas(1) ExeHeader final {
        LE16 mz;
        LE16 m512;
        LE16 p512;
        char _[18];
        LE16 relocoffs;
        char __[34];
        LE32 nexepos;
    };
    COMPILE_TIME_ASSERT(sizeof(ExeHeader) == 64)
    COMPILE_TIME_ASSERT_ALIGNED1(ExeHeader)
    COMPILE_TIME_ASSERT(sizeof(((ExeHeader *) nullptr)->_) == 18)
    COMPILE_TIME_ASSERT(sizeof(((ExeHeader *) nullptr)->__) == 34)
    ExeHeader h;
    int ic;
    pe_offset = 0;
    for (ic = 0; ic < 20; ic++) {
        fi->seek(pe_offset, SEEK_SET);
        fi->readx(&h, sizeof(h));
        if (h.mz == 'M' + 'Z' * 256) // dos exe
        {
            if (h.nexepos && h.nexepos < sizeof(ExeHeader)) {
                // Overlapping MZ and PE headers by 'leanify', etc.
                char buf[64];
                snprintf(buf, sizeof(buf), "PE and MZ header overlap: %#x < %#x",
                         (unsigned) h.nexepos, (unsigned) sizeof(ExeHeader));
                throwCantPack(buf);
            }
            const unsigned delta = (h.relocoffs >= 0x40)
                                       ? h.nexepos // new format exe
                                       : (h.p512 * 512 + h.m512 - h.m512 ? 512 : h.nexepos);
            if ((pe_offset + delta) < delta // wrap-around
                || (pe_offset + delta) > file_size_u) {
                char buf[64];
                snprintf(buf, sizeof(buf), "bad PE delta %#x at offset %#x", delta, pe_offset);
                throwCantPack(buf);
            }
            pe_offset += delta;
        } else if (get_le32((const byte *) &h) == 'P' + 'E' * 256)
            break;
        else
            return 0;
    }
    if (ic == 20)
        return 0;
    fi->seek(pe_offset, SEEK_SET);
    readPeHeader();
    return getFormat();
}
References buf, COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, PackerBase::fi, PackerBase::file_size_u, get_le32(), PackerBase::getFormat(), pe_offset, readPeHeader(), InputFile::readx(), InputFile::seek(), SEEK_SET, snprintf, and throwCantPack().
Referenced by PackW64PeAmd64::canPack(), PackW64PeArm64::canPack(), PackW64PeArm64EC::canPack(), PackWinCeArm::canPack(), and PackW32PeI386::readFileHeader().
readPeHeader()
virtual void PeFile::readPeHeader () protected pure virtual
Implemented in PeFile32, and PeFile64.
Referenced by readFileHeader().
readSectionHeaders()
void PeFile::readSectionHeaders (unsigned objs, unsigned sizeof_ih) protected
pack
Definition at line 2098 of file pefile.cpp.
{
    if (objs == 0)
        return;
    mb_isection.alloc(mem_size(sizeof(pe_section_t), objs));
    isection = SPAN_S_MAKE(pe_section_t, mb_isection); // => isection now is a SPAN_S
    if (file_size_u < pe_offset + sizeof_ih + sizeof(pe_section_t) * objs) {
        char buf[32];
        snprintf(buf, sizeof(buf), "too many sections %d", objs);
        throwCantPack(buf);
    }
    fi->seek(pe_offset + sizeof_ih, SEEK_SET);
    fi->readx(isection, sizeof(pe_section_t) * objs);
    rvamin = isection[0].vaddr;
    const unsigned rvalast = isection[-1 + objs].vsize + isection[-1 + objs].vaddr;
    for (unsigned j = 0; j < objs; ++j) { // expect: first is min, last is max
        unsigned lo = isection[j].vaddr, hi = isection[j].vsize + lo;
        if (hi < lo) { // this checks first and last sections, too!
            char buf[64];
            snprintf(buf, sizeof(buf), "bad section[%d] wrap-around %#x %#x", j, lo, hi - lo);
            throwCantPack(buf);
        }
        if (lo < rvamin) {
            char buf[64];
            snprintf(buf, sizeof(buf), "bad section .rva [%d] %#x < [0] %#x", j, lo, rvamin);
            throwCantPack(buf);
        }
        if (rvalast < hi) {
            char buf[80];
            snprintf(buf, sizeof(buf), "bad section .rva+.vsize  [%d] %#x > [%d] %#x", j, hi,
                     (-1 + objs), rvalast);
            throwCantPack(buf);
        }
    }
    infoHeader("[Processing %s, format %s, %d sections]", fn_basename(fi->getName()), getName(),
               objs);
}
References MemBuffer::alloc(), buf, PackerBase::fi, PackerBase::file_size_u, fn_basename(), PackerBase::getName(), FileBase::getName(), infoHeader(), mb_isection, mem_size(), pe_offset, InputFile::readx(), rvamin, InputFile::seek(), SEEK_SET, snprintf, SPAN_S_MAKE, and throwCantPack().
Referenced by pack0().
readSections()
unsigned PeFile::readSections (unsigned objs, unsigned usize, unsigned ih_filealign, unsigned ih_datasize) protected
Definition at line 2199 of file pefile.cpp.
{
    const unsigned xtrasize = UPX_MAX(ih_datasize, 65536u) + IDSIZE(PEDIR_IMPORT) +
                              IDSIZE(PEDIR_BOUND_IMPORT) + IDSIZE(PEDIR_IAT) +
                              IDSIZE(PEDIR_DELAY_IMPORT) + IDSIZE(PEDIR_BASERELOC);
    ibuf.alloc(usize + xtrasize);
    // BOUND IMPORT support. FIXME: is this ok?
    ibufgood = isection[0].rawdataptr;
    fi->seek(0, SEEK_SET);
    fi->readx(ibuf, ibufgood);
    // Interval holes(ibuf);
    unsigned ic, jc, overlaystart = 0;
    ibuf.clear(0, usize);
    for (ic = jc = 0; ic < objs; ic++) {
        if (isection[ic].rawdataptr && overlaystart < isection[ic].rawdataptr + isection[ic].size)
            overlaystart = ALIGN_UP(isection[ic].rawdataptr + isection[ic].size, ih_filealign);
        if (isection[ic].vsize == 0)
            isection[ic].vsize = isection[ic].size;
        if ((isection[ic].flags & IMAGE_SCN_CNT_UNINITIALIZED_DATA) ||
            isection[ic].rawdataptr == 0 || (isection[ic].flags & IMAGE_SCN_LNK_INFO)) {
            // holes.add_interval(isection[ic].vaddr, isection[ic].vsize);
            continue;
        }
        if (isection[ic].vaddr + isection[ic].size > usize)
            throwCantPack("section size problem");
        if (!isrtm && ((isection[ic].flags & (IMAGE_SCN_MEM_WRITE | IMAGE_SCN_MEM_SHARED)) ==
                       (IMAGE_SCN_MEM_WRITE | IMAGE_SCN_MEM_SHARED)))
            if (!opt->force)
                throwCantPack("writable shared sections not supported (try --force)");
        if (jc && isection[ic].rawdataptr - jc > ih_filealign && !opt->force)
            throwCantPack("superfluous data between sections (try --force)");
        fi->seek(isection[ic].rawdataptr, SEEK_SET);
        jc = isection[ic].size;
        if (jc > isection[ic].vsize)
            jc = isection[ic].vsize;
        if (isection[ic].vsize == 0) // hack for some tricky programs - may this break other progs?
            jc = isection[ic].vsize = isection[ic].size;
        if (isection[ic].vaddr + jc > ibuf.getSize())
            throwInternalError("buffer too small 1");
        fi->readx(ibuf.subref("bad section %#x", isection[ic].vaddr, jc), jc);
        ibufgood = upx::umax(ibufgood, jc + isection[ic].vaddr); // FIXME: simplistic
        jc += isection[ic].rawdataptr;
    }
    return overlaystart;
}
References ALIGN_UP, MemBuffer::alloc(), MemBuffer::clear(), PackerBase::fi, MemBuffer::getSize(), Packer::ibuf, Packer::ibufgood, IDSIZE(), IMAGE_SCN_CNT_UNINITIALIZED_DATA, IMAGE_SCN_LNK_INFO, IMAGE_SCN_MEM_SHARED, IMAGE_SCN_MEM_WRITE, isrtm, opt, PEDIR_BASERELOC, PEDIR_BOUND_IMPORT, PEDIR_DELAY_IMPORT, PEDIR_IAT, PEDIR_IMPORT, InputFile::readx(), InputFile::seek(), SEEK_SET, size(), MemBuffer::subref(), throwCantPack(), throwInternalError(), upx::umax(), and UPX_MAX.
Referenced by pack0().
rebuildExports()
void PeFile::rebuildExports () protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 2814 of file pefile.cpp.
{
    if (ODSIZE(PEDIR_EXPORT) == 0 || ODADDR(PEDIR_EXPORT) == IDADDR(PEDIR_EXPORT))
        return; // nothing to do
    opt->win32_pe.compress_exports = 0;
    Export xport((char *) (byte *) ibuf - isection[2].vaddr);
    processExports(&xport);
    processExports(&xport, ODADDR(PEDIR_EXPORT));
    omemcpy(obuf + (ODADDR(PEDIR_EXPORT) - rvamin), oexport, soexport);
}
References Packer::ibuf, IDADDR(), Packer::obuf, ODADDR(), ODSIZE(), omemcpy, opt, PEDIR_EXPORT, processExports(), rvamin, and soexport.
Referenced by unpack0().
rebuildImports()
template<typename LEXX , typename ord_mask_t > void PeFile::rebuildImports (SPAN_S(byte) & extra_info, ord_mask_t ord_mask, bool set_oft) protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 2877 of file pefile.cpp.
{
    if (ODADDR(PEDIR_IMPORT) == 0 || ODSIZE(PEDIR_IMPORT) <= sizeof(import_desc))
        return;
    OPTR_VAR(const byte, const imdata, obuf + mem_size(1, get_le32(extra_info)));
    const unsigned inamespos = mem_size(1, get_le32(extra_info + 4));
    extra_info += 8;
    unsigned sdllnames = 0;
    IPTR_VAR_OFFSET(const byte, const import, IDADDR(PEDIR_IMPORT) - isection[2].vaddr);
    OPTR_VAR(const byte, p, raw_bytes(imdata, 4));
    for (; get_le32(p) != 0; ++p) {
        const byte *dname = raw_bytes(import + mem_size(1, get_le32(p)), 1);
        const unsigned dlen = strlen(dname);
        ICHECK(dname, dlen + 1);
        sdllnames += dlen + 1;
        for (p += 8; *p;)
            if (*p == 1)
                p += 1 + strlen(p + 1) + 1;
            else if (*p == 0xff)
                p += 3; // ordinal
            else
                p += 5;
    }
    sdllnames = ALIGN_UP(sdllnames, 2u);
    // INFO: use VPtr for "virtual pointer" pointing before a buffer
    VPtr<byte> const Obuf{obuf, rvamin};
    SPAN_S_VAR(import_desc, im, (import_desc *) raw_bytes(Obuf + ODADDR(PEDIR_IMPORT), 0), obuf);
    SPAN_0_VAR(byte, dllnames, inamespos ? raw_bytes(Obuf + inamespos, 0) : nullptr, obuf);
    SPAN_0_VAR(byte, const importednames_start, inamespos ? dllnames + sdllnames : nullptr);
    SPAN_0_VAR(byte, importednames, importednames_start);
    for (p = imdata; get_le32(p) != 0; ++p) {
        // restore the name of the dll
        const byte *dname = raw_bytes(import + get_le32(p), 1);
        const unsigned dlen = strlen(dname);
        ICHECK(dname, dlen + 1);
        const unsigned iatoffs = get_le32(p + 4) + rvamin;
        if (inamespos) {
            // now I rebuild the dll names
            omemcpy(dllnames, dname, dlen + 1);
            im->dllname = ptr_udiff_bytes(dllnames, obuf) + rvamin;
            //;;;printf("\ndll: %s:",dllnames);
            dllnames += dlen + 1;
        } else {
            omemcpy(Obuf + im->dllname, dname, dlen + 1);
        }
        im->iat = iatoffs;
        if (set_oft)
            im->oft = iatoffs;
        OPTR_VAR(LEXX, newiat, (LEXX *) raw_bytes(Obuf + iatoffs, 0));
        // restore the imported names+ordinals
        for (p += 8; *p; ++newiat)
            if (*p == 1) {
                const unsigned ilen = strlen(++p) + 1;
                if (inamespos) {
                    if (ptr_udiff_bytes(importednames, importednames_start) & 1)
                        importednames -= 1;
                    omemcpy(importednames + 2, p, ilen);
                    //;;;printf(" %s",importednames+2);
                    *newiat = ptr_udiff_bytes(importednames, obuf) + rvamin;
                    importednames += 2 + ilen;
                } else {
                    // Beware overlap!
                    omemmove(Obuf + (*newiat + 2), p, ilen);
                }
                p += ilen;
            } else if (*p == 0xff) {
                *newiat = get_le16(p + 1) + ord_mask;
                //;;;printf(" %x",(unsigned)*newiat);
                p += 3;
            } else {
                *newiat = *(const LEXX *) raw_bytes(import + get_le32(p + 1), sizeof(LEXX));
                assert(*newiat & ord_mask);
                p += 5;
            }
        *newiat = 0;
        im++;
    }
    // memset(imdata, 0, ptr_udiff_bytes(p, imdata));
}
References ALIGN_UP, get_le16(), get_le32(), ICHECK, IDADDR(), IPTR_VAR_OFFSET, mem_size(), Packer::obuf, ODADDR(), ODSIZE(), omemcpy, omemmove, OPTR_VAR, PEDIR_IMPORT, ptr_udiff_bytes(), raw_bytes(), rvamin, SPAN_0_VAR, SPAN_S_VAR, and strlen.
rebuildRelocs()
void PeFile::rebuildRelocs (SPAN_S(byte) & extra_info, unsigned bits, unsigned flags, upx_uint64_t imagebase) protected
unpack
Definition at line 2752 of file pefile.cpp.
{
    assert(bits == 32 || bits == 64);
    if (!ODADDR(PEDIR_BASERELOC) || !ODSIZE(PEDIR_BASERELOC) ||
        (flags & IMAGE_FILE_RELOCS_STRIPPED))
        return;
    if (ODSIZE(PEDIR_BASERELOC) == 8) // some tricky dlls use this
    {
        omemcpy(obuf + (ODADDR(PEDIR_BASERELOC) - rvamin), "\x0\x0\x0\x0\x8\x0\x0\x0", 8);
        return;
    }
    const unsigned orig_crelocs = mem_size(1, get_le32(extra_info));
    const byte big = extra_info[4];
    extra_info += 5;
    SPAN_S_VAR(const byte, rdata, obuf + orig_crelocs, obuf);
    MemBuffer mb_wrkmem;
    unsigned relocnum = unoptimizeReloc(rdata, mb_wrkmem, obuf, orig_crelocs, bits, true);
    // 16-bit relocations
    unsigned r16 = 0;
    if (big & 6) { // count 16-bit relocations
        SPAN_S_VAR(const LE32, q, SPAN_TYPE_CAST(const LE32, rdata));
        while (*q++)
            r16++;
        if ((big & 6) == 6)
            while (*++q)
                r16++;
    }
    Reloc rel(relocnum + r16);
    if (big & 6) { // add 16-bit relocations
        SPAN_S_VAR(const LE32, q, SPAN_TYPE_CAST(const LE32, rdata));
        while (*q)
            rel.add_reloc(*q++ + rvamin, (big & 4) ? IMAGE_REL_BASED_LOW : IMAGE_REL_BASED_HIGH);
        if ((big & 6) == 6)
            while (*++q)
                rel.add_reloc(*q + rvamin, IMAGE_REL_BASED_HIGH);
        // rdata = (const byte *) raw_bytes(q, 0); // advance rdata
    }
    SPAN_S_VAR(byte, const wrkmem, mb_wrkmem);
    for (unsigned ic = 0; ic < relocnum; ic++) {
        OPTR_VAR(byte, const p, obuf + get_le32(wrkmem + 4 * ic));
        if (bits == 32)
            set_le32(p, get_le32(p) + imagebase + rvamin);
        else
            set_le64(p, get_le64(p) + imagebase + rvamin);
        rel.add_reloc(rvamin + get_le32(wrkmem + 4 * ic),
                      bits == 32 ? IMAGE_REL_BASED_HIGHLOW : IMAGE_REL_BASED_DIR64);
    }
    rel.finish(oxrelocs, soxrelocs);
    omemcpy(obuf + (ODADDR(PEDIR_BASERELOC) - rvamin), oxrelocs, soxrelocs);
    delete[] oxrelocs;
    oxrelocs = nullptr;
    mb_wrkmem.dealloc();
    ODSIZE(PEDIR_BASERELOC) = soxrelocs;
}
References PeFile::Reloc::add_reloc(), MemBuffer::dealloc(), PeFile::Reloc::finish(), get_le32(), get_le64(), IMAGE_FILE_RELOCS_STRIPPED, IMAGE_REL_BASED_DIR64, IMAGE_REL_BASED_HIGH, IMAGE_REL_BASED_HIGHLOW, IMAGE_REL_BASED_LOW, mem_size(), Packer::obuf, ODADDR(), ODSIZE(), omemcpy, OPTR_VAR, oxrelocs, PEDIR_BASERELOC, r16, rvamin, set_le32(), set_le64(), soxrelocs, SPAN_S_VAR, SPAN_TYPE_CAST, and Packer::unoptimizeReloc().
Referenced by unpack0().
rebuildResources()
void PeFile::rebuildResources (SPAN_S(byte) & extra_info, unsigned lastvaddr) protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 2840 of file pefile.cpp.
{
    if (ODSIZE(PEDIR_RESOURCE) == 0 || IDSIZE(PEDIR_RESOURCE) == 0)
        return;
    icondir_count = get_le16(extra_info);
    extra_info += 2;
    const unsigned vaddr = IDADDR(PEDIR_RESOURCE);
    if (vaddr < lastvaddr || (vaddr - lastvaddr) > ibuf.getSize())
        throwCantUnpack("corrupted PE header");
    // INFO: use VPtr for "virtual pointer" pointing before a buffer
    VPtr<const byte> const r{ibuf, lastvaddr};
    Resource res(raw_bytes(r + vaddr, 0), ibuf, ibuf + ibuf.getSize());
    while (res.next())
        if (res.offs() > vaddr) {
            ICHECK(r + (res.offs() - 4), 4);
            unsigned origoffs = get_le32(r + (res.offs() - 4));
            res.newoffs() = origoffs;
            omemcpy(obuf + (origoffs - rvamin), r + res.offs(), res.size());
            if (icondir_count && res.itype() == RT_GROUP_ICON) {
                set_le16(obuf + (origoffs - rvamin + 4), icondir_count);
                icondir_count = 0;
            }
        }
    if (res.dirsize()) {
        byte *p = res.build();
        OCHECK(obuf + (ODADDR(PEDIR_RESOURCE) - rvamin), 16);
        // write back when the original is zeroed
        if (get_le32(obuf + (ODADDR(PEDIR_RESOURCE) - rvamin + 12)) == 0)
            omemcpy(obuf + (ODADDR(PEDIR_RESOURCE) - rvamin), p, res.dirsize());
    }
}
References PeFile::Resource::build(), PeFile::Resource::dirsize(), get_le16(), get_le32(), MemBuffer::getSize(), Packer::ibuf, ICHECK, icondir_count, IDADDR(), IDSIZE(), PeFile::Resource::itype(), PeFile::Resource::newoffs(), PeFile::Resource::next(), Packer::obuf, OCHECK, ODADDR(), ODSIZE(), PeFile::Resource::offs(), omemcpy, PEDIR_RESOURCE, raw_bytes(), RT_GROUP_ICON, rvamin, set_le16(), PeFile::Resource::size(), and throwCantUnpack().
Referenced by unpack0().
rebuildTls()
void PeFile::rebuildTls () protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 2825 of file pefile.cpp.
{
    // this is an easy one : just do nothing ;-)
}
Referenced by unpack0().
setOhDataBase()
virtual void PeFile::setOhDataBase (const pe_section_t * osection) protected pure virtual
Implemented in PackW64PeAmd64, PackW64PeArm64, PackW32PeI386, and PackWinCeArm.
Referenced by pack0().
setOhHeaderSize()
virtual void PeFile::setOhHeaderSize (const pe_section_t * osection) protected pure virtual
Implemented in PackW32PeI386, PackW64PeAmd64, PackW64PeArm64, and PackWinCeArm.
Referenced by pack0(), and unpack0().
SPAN_0() [1/6]
PeFile::SPAN_0 (byte) protected
SPAN_0() [2/6]
PeFile::SPAN_0 (byte) protected
SPAN_0() [3/6]
PeFile::SPAN_0 (byte) protected
SPAN_0() [4/6]
PeFile::SPAN_0 (byte) protected
SPAN_0() [5/6]
PeFile::SPAN_0 (byte) protected
SPAN_0() [6/6]
PeFile::SPAN_0 (pe_section_t) protected
stripDebug()
unsigned PeFile::stripDebug (unsigned overlaystart) protected
Definition at line 2068 of file pefile.cpp.
{
    if (IDADDR(PEDIR_DEBUG) == 0)
        return overlaystart;
    struct alignas(1) DebugDir final {
        byte _[16]; // flags, time/date, version, type
        LE32 size;
        byte __[4]; // rva
        LE32 fpos;
    };
    COMPILE_TIME_ASSERT(sizeof(DebugDir) == 28)
    COMPILE_TIME_ASSERT_ALIGNED1(DebugDir)
    COMPILE_TIME_ASSERT(sizeof(((DebugDir *) nullptr)->_) == 16)
    COMPILE_TIME_ASSERT(sizeof(((DebugDir *) nullptr)->__) == 4)
    const unsigned skip = IDADDR(PEDIR_DEBUG);
    const unsigned take = IDSIZE(PEDIR_DEBUG);
    const DebugDir *dd = (const DebugDir *) ibuf.subref("bad debug %#x", skip, take);
    for (unsigned ic = 0; ic < IDSIZE(PEDIR_DEBUG) / sizeof(DebugDir); ic++, dd++)
        if (overlaystart == dd->fpos)
            overlaystart += dd->size;
    ibuf.fill(IDADDR(PEDIR_DEBUG), IDSIZE(PEDIR_DEBUG), FILLVAL);
    return overlaystart;
}
References COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, MemBuffer::fill(), FILLVAL, Packer::ibuf, IDADDR(), IDSIZE(), PEDIR_DEBUG, size(), and MemBuffer::subref().
Referenced by pack0().
testUnpackVersion()
bool PeFile::testUnpackVersion (int version) const override protected virtual
Reimplemented from Packer.
Definition at line 108 of file pefile.cpp.
{
    if (version != ph_version && ph_version != -1)
        throwCantUnpack("program has been modified; run a virus checker!");
    if (!canUnpackVersion(version))
        throwCantUnpack("this program is packed with an obsolete version and cannot be unpacked");
    return true;
}
References canUnpackVersion(), Packer::ph_version, and throwCantUnpack().
tryremove()
unsigned PeFile::tryremove (unsigned vaddr, unsigned objs) protected
Definition at line 2058 of file pefile.cpp.
{
    unsigned ic = virta2objnum(vaddr, isection, objs);
    if (ic && ic == objs - 1) {
        NO_fprintf(stderr, "removed section: %d size: 0x%x\n", ic, (int) isection[ic].size);
        info("removed section: %d size: 0x%x", ic, (int) isection[ic].size);
        objs--;
    }
    return objs;
}
References info(), NO_fprintf(), size(), and virta2objnum().
Referenced by PeFile32::processRelocs(), and PeFile64::processRelocs().
unpack0()
template<typename ht , typename LEXX , typename ord_mask_t > void PeFile::unpack0 (OutputFile * fo, const ht & ih, ht & oh, ord_mask_t ord_mask, bool set_oft) protected
create UPX0 section
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header.
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Definition at line 2968 of file pefile.cpp.
{
    // infoHeader("[Processing %s, format %s, %d sections]", fn_basename(fi->getName()), getName(),
    // objs);
    handleStub(fi, fo, pe_offset);
    if (ih.filealign == 0)
        throwCantUnpack("unexpected value in the PE header");
    const unsigned iobjs = ih.objects;
    const unsigned overlay =
        file_size_u -
        ALIGN_UP(isection[iobjs - 1].rawdataptr + isection[iobjs - 1].size, ih.filealign);
    checkOverlay(overlay);
    ibuf.alloc(ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    fi->seek(isection[1].rawdataptr - 64 + ph.buf_offset + ph.getPackHeaderSize(), SEEK_SET);
    fi->readx(ibuf, ibufgood = ph.c_len);
    // decompress
    decompress(ibuf, obuf);
    unsigned skip = get_le32(obuf + (ph.u_len - 4));
    unsigned take = sizeof(oh);
    SPAN_S_VAR(byte, extra_info, obuf);
    extra_info = obuf.subref("bad extra_info offset %#x", skip, take);
    // byte *const eistart = raw_bytes(extra_info, 0);
    memcpy(&oh, extra_info, take);
    extra_info += take;
    skip += take;
    unsigned objs = oh.objects;
    if ((int) objs <= 0 || (iobjs > 2 && isection[2].size == 0))
        throwCantUnpack("unexpected value in the PE header");
    Array(pe_section_t, osection, objs);
    take = sizeof(pe_section_t) * objs;
    extra_info = obuf.subref("bad extra section size at %#x", skip, take);
    memcpy(osection, extra_info, take);
    extra_info += take;
    skip += take;
    rvamin = osection[0].vaddr;
    if (iobjs > 2) {
        // read the noncompressed section
        const unsigned size = isection[2].size;
        ibuf.dealloc();
        ibuf.alloc(size + 1);
        fi->seek(isection[2].rawdataptr, SEEK_SET);
        fi->readx(ibuf, ibufgood = size);
        ibuf[size] = 0; // allow strlen() up to 'size'
    }
    // unfilter
    if (ph.filter) {
        Filter ft(ph.level);
        ft.init(ph.filter, oh.codebase - rvamin);
        ft.cto = (byte) ph.filter_cto;
        OCHECK(obuf + (oh.codebase - rvamin), oh.codesize);
        ft.unfilter(obuf + (oh.codebase - rvamin), oh.codesize);
    }
    // FIXME: ih.flags is checked here because of a bug in UPX 0.92
    if (ih.flags & IMAGE_FILE_RELOCS_STRIPPED) {
        oh.flags |= IMAGE_FILE_RELOCS_STRIPPED;
        ODADDR(PEDIR_BASERELOC) = 0;
        ODSIZE(PEDIR_BASERELOC) = 0;
    }
    rebuildImports<LEXX>(extra_info, ord_mask, set_oft);
    rebuildRelocs(extra_info, sizeof(ih.imagebase) * 8, oh.flags, oh.imagebase);
    rebuildTls();
    rebuildExports();
    if (iobjs > 3) {
        // read the resource section if present
        ibuf.dealloc();
        ibuf.alloc(isection[3].size);
        fi->seek(isection[3].rawdataptr, SEEK_SET);
        fi->readx(ibuf, ibufgood = isection[3].size);
    }
    rebuildResources(extra_info, isection[ih.objects - 1].vaddr);
    // FIXME: this does bad things if the relocation section got removed
    //  during compression ...
    // memset(eistart, 0, ptr_udiff_bytes(extra_info, eistart) + 4);
    // fill the data directory
    ODADDR(PEDIR_DEBUG) = 0;
    ODSIZE(PEDIR_DEBUG) = 0;
    ODADDR(PEDIR_IAT) = 0;
    ODSIZE(PEDIR_IAT) = 0;
    ODADDR(PEDIR_BOUND_IMPORT) = 0;
    ODSIZE(PEDIR_BOUND_IMPORT) = 0;
    setOhHeaderSize(osection);
    oh.chksum = 0;
    // write decompressed file
    if (fo) {
        unsigned ic = 0;
        while (ic < objs && osection[ic].rawdataptr == 0)
            ic++;
        ibuf.dealloc();
        ibuf.alloc(osection[ic].rawdataptr);
        ibuf.clear();
        infoHeader("[Writing uncompressed file]");
        // write header + decompressed file
        fo->write(&oh, sizeof(oh));
        fo->write(osection, objs * sizeof(pe_section_t));
        fo->write(ibuf, osection[ic].rawdataptr - fo->getBytesWritten());
        for (ic = 0; ic < objs; ic++)
            if (osection[ic].rawdataptr)
                fo->write(obuf + (osection[ic].vaddr - rvamin),
                          ALIGN_UP(osection[ic].size, oh.filealign));
        copyOverlay(fo, overlay, obuf);
    }
    ibuf.dealloc();
}
References ALIGN_UP, MemBuffer::alloc(), MemBuffer::allocForDecompression(), Array, PackHeader::buf_offset, PackHeader::c_len, Packer::checkOverlay(), MemBuffer::clear(), Packer::copyOverlay(), Filter::cto, MemBuffer::dealloc(), Packer::decompress(), PackerBase::fi, PackerBase::file_size_u, PackHeader::filter, PackHeader::filter_cto, get_le32(), OutputFile::getBytesWritten(), PackHeader::getPackHeaderSize(), Packer::handleStub(), Packer::ibuf, Packer::ibufgood, IMAGE_FILE_RELOCS_STRIPPED, infoHeader(), Filter::init(), PackHeader::level, memcpy(), Packer::obuf, OCHECK, ODADDR(), ODSIZE(), oh, pe_offset, PEDIR_BASERELOC, PEDIR_BOUND_IMPORT, PEDIR_DEBUG, PEDIR_IAT, PackerBase::ph, InputFile::readx(), rebuildExports(), rebuildRelocs(), rebuildResources(), rebuildTls(), rvamin, InputFile::seek(), SEEK_SET, setOhHeaderSize(), size(), SPAN_S_VAR, MemBuffer::subref(), throwCantUnpack(), PackHeader::u_len, Filter::unfilter(), and OutputFile::write().
virta2objnum()
unsigned PeFile::virta2objnum (unsigned addr, SPAN_0(pe_section_t) sect, unsigned objs) static protected
Definition at line 2047 of file pefile.cpp.
{
    unsigned ic;
    for (ic = 0; ic < objs; ic++) {
        if (sect->vaddr <= addr && sect->vaddr + sect->vsize > addr)
            return ic;
        sect++;
    }
    // throwCantPack("virta2objnum() failed");
    return ic;
}
References PeFile::pe_section_t::vaddr, and PeFile::pe_section_t::vsize.
Referenced by pack0(), and tryremove().
Member Data Documentation
big_relocs
int PeFile::big_relocs protected
Definition at line 191 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), pack0(), PeFile(), PeFile32::processRelocs(), and PeFile64::processRelocs().
cimports
unsigned PeFile::cimports protected
Definition at line 189 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PackWinCeArm::defineSymbols(), and pack0().
crelocs
unsigned PeFile::crelocs protected
Definition at line 190 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PackWinCeArm::defineSymbols(), and pack0().
icondir_count
int PeFile::icondir_count protected
Definition at line 184 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), pack0(), PeFile(), processResources(), and rebuildResources().
icondir_offset
unsigned PeFile::icondir_offset protected
Definition at line 183 of file pefile.h.
Referenced by PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PeFile(), and processResources().
iddirs
ddirs_t* PeFile::iddirs = nullptr protected
Definition at line 197 of file pefile.h.
Referenced by IDADDR(), IDSIZE(), PeFile32::PeFile32(), and PeFile64::PeFile64().
ilinker
ImportLinker* PeFile::ilinker = nullptr protected
Definition at line 127 of file pefile.h.
Referenced by addKernelImport(), PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), ilinkerGetAddress(), PeFile(), processImports0(), processImports2(), and ~PeFile().
importbyordinal
bool PeFile::importbyordinal = false protected
Definition at line 186 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PeFile(), and processImports0().
isdll
bool PeFile::isdll = false protected
Definition at line 226 of file pefile.h.
Referenced by addStubImports(), PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackWinCeArm::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), handleStripRelocs(), PackW32PeI386::needForceOption(), PackW64PeAmd64::needForceOption(), pack0(), PeFile(), processExports(), PeFile32::readPeHeader(), and PeFile64::readPeHeader().
isefi
bool PeFile::isefi = false protected
Definition at line 228 of file pefile.h.
Referenced by PackW64PeAmd64::buildLoader(), canUnpack0(), handleStripRelocs(), pack0(), PeFile(), processImports0(), processResources(), processTls1(), PeFile32::readPeHeader(), and PeFile64::readPeHeader().
isrtm
bool PeFile::isrtm = false protected
Definition at line 227 of file pefile.h.
Referenced by PackW32PeI386::getName(), PeFile(), PackW32PeI386::readFileHeader(), and readSections().
kernel32ordinal
bool PeFile::kernel32ordinal = false protected
Definition at line 187 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PeFile(), and processImports0().
mb_isection
MemBuffer PeFile::mb_isection protected
Definition at line 224 of file pefile.h.
Referenced by canUnpack0(), and readSectionHeaders().
mb_oexport
MemBuffer PeFile::mb_oexport protected
Definition at line 144 of file pefile.h.
Referenced by processExports().
mb_oimport
MemBuffer PeFile::mb_oimport protected
Definition at line 122 of file pefile.h.
Referenced by processImports0().
mb_oloadconf
MemBuffer PeFile::mb_oloadconf protected
Definition at line 177 of file pefile.h.
Referenced by processLoadConf().
mb_orelocs
MemBuffer PeFile::mb_orelocs protected
Definition at line 135 of file pefile.h.
Referenced by PeFile32::processRelocs(), and PeFile64::processRelocs().
mb_oresources
MemBuffer PeFile::mb_oresources protected
Definition at line 151 of file pefile.h.
Referenced by processResources().
mb_otls
MemBuffer PeFile::mb_otls protected
Definition at line 167 of file pefile.h.
Referenced by processTls1(), and processTls2().
oddirs
ddirs_t* PeFile::oddirs = nullptr protected
Definition at line 198 of file pefile.h.
Referenced by ODADDR(), ODSIZE(), PeFile32::PeFile32(), and PeFile64::PeFile64().
oimpdlls
byte* PeFile::oimpdlls = nullptr protected
Definition at line 125 of file pefile.h.
Referenced by pack0(), PeFile(), processImports2(), PackWinCeArm::processImports2(), and ~PeFile().
oloadconf
byte* PeFile::oloadconf = nullptr protected
Definition at line 178 of file pefile.h.
Referenced by pack0(), PeFile(), and processLoadConf().
oxrelocs
byte* PeFile::oxrelocs = nullptr protected
Definition at line 138 of file pefile.h.
Referenced by callProcessStubRelocs(), pack0(), PeFile(), rebuildRelocs(), and ~PeFile().
pe_offset
unsigned PeFile::pe_offset protected
Definition at line 113 of file pefile.h.
Referenced by canUnpack0(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), pack0(), readFileHeader(), readSectionHeaders(), PackW32PeI386::setOhHeaderSize(), PackW64PeAmd64::setOhHeaderSize(), and unpack0().
rvamin
unsigned PeFile::rvamin protected
Definition at line 188 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), callCompressWithFilters(), PackWinCeArm::callCompressWithFilters(), checkHeaderValues(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PackWinCeArm::defineSymbols(), pack0(), processImports0(), PeFile32::processRelocs(), PeFile64::processRelocs(), readSectionHeaders(), rebuildExports(), rebuildImports(), rebuildRelocs(), rebuildResources(), and unpack0().
soexport
unsigned PeFile::soexport protected
Definition at line 146 of file pefile.h.
Referenced by pack0(), processExports(), and rebuildExports().
soimpdlls
unsigned PeFile::soimpdlls protected
Definition at line 126 of file pefile.h.
Referenced by pack0(), processImports0(), and processImports2().
soimport
unsigned PeFile::soimport protected
Definition at line 124 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), pack0(), and processImports0().
soloadconf
unsigned PeFile::soloadconf protected
Definition at line 179 of file pefile.h.
Referenced by pack0(), PeFile(), and processLoadConf().
sorelocs
unsigned PeFile::sorelocs protected
Definition at line 137 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackWinCeArm::buildLoader(), pack0(), PeFile(), PeFile32::processRelocs(), and PeFile64::processRelocs().
soresources
unsigned PeFile::soresources protected
Definition at line 153 of file pefile.h.
Referenced by callProcessResources(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), pack0(), and processResources().
sotls
unsigned PeFile::sotls protected
Definition at line 169 of file pefile.h.
Referenced by pack0(), PeFile(), PackWinCeArm::processTls(), processTls1(), and processTls2().
soxrelocs
unsigned PeFile::soxrelocs protected
Definition at line 139 of file pefile.h.
Referenced by callProcessStubRelocs(), PackWinCeArm::defineSymbols(), pack0(), PeFile(), and rebuildRelocs().
tls_handler_offset
unsigned PeFile::tls_handler_offset = 0 protected
Definition at line 172 of file pefile.h.
Referenced by pack0(), and processTls2().
tlscb_ptr
unsigned PeFile::tlscb_ptr protected
Definition at line 171 of file pefile.h.
Referenced by PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), and processTls1().
tlsindex
unsigned PeFile::tlsindex protected
Definition at line 170 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), pack0(), PeFile(), and processTls1().
use_clear_dirty_stack
bool PeFile::use_clear_dirty_stack = true protected
Definition at line 230 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PeFile(), PeFile32::readPeHeader(), and PeFile64::readPeHeader().
use_dep_hack
bool PeFile::use_dep_hack = true protected
Definition at line 229 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PeFile(), PeFile32::readPeHeader(), and PeFile64::readPeHeader().
use_stub_relocs
bool PeFile::use_stub_relocs = true protected
Definition at line 231 of file pefile.h.
Referenced by PackW32PeI386::addNewRelocations(), PackW32PeI386::buildLoader(), PackW32PeI386::defineSymbols(), pack0(), PackW64PeAmd64::PackW64PeAmd64(), and PeFile().
use_tls_callbacks
bool PeFile::use_tls_callbacks = false protected
Definition at line 173 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), pack0(), PeFile(), processTls1(), and processTls2().
The documentation for this class was generated from the following files:
src/pefile.h
src/pefile.cpp