My Project: PeFile::Resource Class Reference
PeFile::Resource Class Reference final
#include <pefile.h>
Classes
struct res_data
struct res_dir
struct res_dir_entry
resource handling
struct upx_rbranch
struct upx_rleaf
struct upx_rnode
Public Member Functions
Resource (const byte *ibufstart, const byte *ibufen)
Resource (const byte *p, const byte *ibufstart, const byte *ibufend)
~Resource () noexcept
void init (const byte *)
unsigned dirsize () const
bool next ()
unsigned itype () const
const byte * ntype () const
unsigned size () const
unsigned offs () const
unsigned & newoffs ()
byte * build ()
bool clear ()
void dump () const
unsigned iname () const
const byte * nname () const
Private Member Functions
void check (const res_dir *, unsigned)
upx_rnode * convert (const void *, upx_rnode *, unsigned)
void build (const upx_rnode *, unsigned &, unsigned &, unsigned)
void clear (byte *, unsigned, Interval *)
void dump (const upx_rnode *, unsigned) const
void destroy (upx_rnode *urd, unsigned level) noexcept
void ibufcheck (const void *m, unsigned size)
Private Member Functions inherited from upx::noncopyable
forceinline constexpr noncopyable () noexcept
forceinline ~noncopyable () noexcept=default
Private Attributes
MemBuffer mb_start
const byte * start = nullptr
byte * newstart = nullptr
upx_rnode * root = nullptr
upx_rleaf * head = nullptr
upx_rleaf * current = nullptr
unsigned dsize = 0
unsigned ssize = 0
const byte * ibufstart = nullptr
const byte * ibufend = nullptr
Detailed Description
Definition at line 461 of file pefile.h.
Constructor & Destructor Documentation
Resource() [1/2]
PeFile::Resource::Resource (const byte * ibufstart, const byte * ibufen) explicit
Definition at line 1608 of file pefile.cpp.
                                                                     : root(nullptr) {
    ibufstart = ibufstart_;
    ibufend = ibufend_;
}
References ibufend, and ibufstart.
Resource() [2/2]
PeFile::Resource::Resource (const byte * p, const byte * ibufstart, const byte * ibufend) explicit
Definition at line 1613 of file pefile.cpp.
{
    ibufstart = ibufstart_;
    ibufend = ibufend_;
    newstart = nullptr;
    init(p);
}
~Resource()
PeFile::Resource::~Resource () noexcept
Definition at line 1620 of file pefile.cpp.
{
    if (root) {
        destroy(root, 0);
        root = nullptr;
    }
}
Member Function Documentation
build() [1/2]
byte * PeFile::Resource::build ()
Definition at line 1781 of file pefile.cpp.
{
    mb_start.dealloc();
    newstart = nullptr;
    if (dirsize()) {
        mb_start.alloc(dirsize());
        newstart = static_cast<byte *>(mb_start.getVoidPtr());
        unsigned bpos = 0, spos = dsize;
        build(root, bpos, spos, 0);
        // dirsize() is 4 bytes aligned, so we may need to zero
        // up to 2 bytes to make valgrind happy
        while (spos < dirsize())
            newstart[spos++] = 0;
    }
    return newstart;
}
build() [2/2]
void PeFile::Resource::build (const upx_rnode * node, unsigned & bpos, unsigned & spos, unsigned level) private
Definition at line 1741 of file pefile.cpp.
{
    if (level == 3) {
        if (bpos + sizeof(res_data) > dirsize())
            throwCantUnpack("corrupted resources");
        res_data *l = (res_data *) (newstart + bpos);
        const upx_rleaf *leaf = (const upx_rleaf *) node;
        *l = leaf->data;
        if (leaf->newoffset)
            l->offset = leaf->newoffset;
        bpos += sizeof(*l);
        return;
    }
    if (bpos + sizeof(res_dir) > dirsize())
        throwCantUnpack("corrupted resources");
    res_dir *const b = (res_dir *) (newstart + bpos);
    const upx_rbranch *branch = (const upx_rbranch *) node;
    *b = branch->data;
    bpos += b->Sizeof();
    res_dir_entry *be = b->entries;
    for (unsigned ic = 0; ic < branch->nc; ic++, be++) {
        xcheck(branch->children[ic]);
        be->tnl = branch->children[ic]->id;
        be->child = bpos + ((level < 2) ? 0x80000000 : 0);
        const byte *p;
        if ((p = branch->children[ic]->name) != nullptr) {
            be->tnl = spos + 0x80000000;
            if (spos + get_le16(p) * 2 + 2 > dirsize())
                throwCantUnpack("corrupted resources");
            memcpy(newstart + spos, p, get_le16(p) * 2 + 2);
            spos += get_le16(p) * 2 + 2;
        }
        build(branch->children[ic], bpos, spos, level + 1);
    }
}
References b, PeFile::Resource::res_dir_entry::child, PeFile::Resource::upx_rbranch::children, PeFile::Resource::upx_rbranch::data, PeFile::Resource::upx_rleaf::data, get_le16(), PeFile::Resource::upx_rnode::id, memcpy(), PeFile::Resource::upx_rnode::name, PeFile::Resource::upx_rbranch::nc, PeFile::Resource::upx_rleaf::newoffset, PeFile::Resource::res_data::offset, throwCantUnpack(), PeFile::Resource::res_dir_entry::tnl, and xcheck().
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
check()
void PeFile::Resource::check (const res_dir * node, unsigned level) private
Definition at line 1671 of file pefile.cpp.
{
    ibufcheck(node, sizeof(*node));
    int ic = node->identr + node->namedentr;
    if (ic == 0)
        return;
    for (const res_dir_entry *rde = node->entries; --ic >= 0; rde++) {
        ibufcheck(rde, sizeof(*rde));
        if (((rde->child & 0x80000000) == 0) ^ (level == 2))
            throwCantPack("unsupported resource structure");
        else if (level != 2)
            check((const res_dir *) (start + (rde->child & 0x7fffffff)), level + 1);
    }
}
References PeFile::Resource::res_dir::entries, PeFile::Resource::res_dir::identr, PeFile::Resource::res_dir::namedentr, and throwCantPack().
clear() [1/2]
bool PeFile::Resource::clear ()
Definition at line 1853 of file pefile.cpp.
{
    newstart = const_cast<byte *>(start);
    Interval iv(newstart);
    clear(newstart, 0, &iv);
    iv.flatten();
    if (iv.ivnum == 1)
        iv.clear();
#if TESTING
    if (opt->verbose > 3)
        iv.dump();
#endif
    return iv.ivnum == 1;
}
References PeFile::Interval::clear(), PeFile::Interval::dump(), PeFile::Interval::flatten(), PeFile::Interval::ivnum, and opt.
clear() [2/2]
void PeFile::Resource::clear (byte * node, unsigned level, Interval * iv) private
Definition at line 1840 of file pefile.cpp.
{
    if (level == 3)
        iv->add_interval(node, sizeof(res_data));
    else {
        const res_dir *const rd = (res_dir *) node;
        const unsigned n = rd->identr + rd->namedentr;
        const res_dir_entry *rde = rd->entries;
        for (unsigned ic = 0; ic < n; ic++, rde++)
            clear(newstart + (rde->child & 0x7fffffff), level + 1, iv);
        iv->add_interval(rd, rd->Sizeof());
    }
}
References PeFile::Interval::add_interval(), PeFile::Resource::res_dir_entry::child, PeFile::Resource::res_dir::entries, PeFile::Resource::res_dir::identr, n, PeFile::Resource::res_dir::namedentr, and PeFile::Resource::res_dir::Sizeof().
Referenced by PeFile::processResources().
convert()
PeFile::Resource::upx_rnode * PeFile::Resource::convert (const void * rnode, upx_rnode * parent, unsigned level) private
Definition at line 1690 of file pefile.cpp.
{
    if (level == 3) {
        const res_data *node = ACC_STATIC_CAST(const res_data *, rnode);
        ibufcheck(node, sizeof(*node));
        upx_rleaf *leaf = new upx_rleaf;
        leaf->id = 0;
        leaf->name = nullptr;
        leaf->parent = parent;
        leaf->next = head;
        leaf->newoffset = 0;
        leaf->data = *node;
        head = leaf; // append node to a linked list for traversal
        dsize += sizeof(res_data);
        return leaf;
    }
    const res_dir *node = ACC_STATIC_CAST(const res_dir *, rnode);
    ibufcheck(node, sizeof(*node));
    int ic = node->identr + node->namedentr;
    if (ic == 0)
        return nullptr;
    upx_rbranch *branch = new upx_rbranch;
    branch->id = 0;
    branch->name = nullptr;
    branch->parent = parent;
    branch->nc = ic;
    branch->children = New(upx_rnode *, ic);
    branch->data = *node;
    for (const res_dir_entry *rde = node->entries + ic - 1; --ic >= 0; rde--) {
        upx_rnode *child = convert(start + (rde->child & 0x7fffffff), branch, level + 1);
        xcheck(child);
        branch->children[ic] = child;
        child->id = rde->tnl;
        if (child->id & 0x80000000) {
            const byte *p = start + (child->id & 0x7fffffff);
            ibufcheck(p, 2);
            const unsigned len = 2 + 2 * get_le16(p);
            ibufcheck(p, len);
            child->name = New(byte, len);
            memcpy(child->name, p, len); // copy unicode string
            ssize += len;                // size of unicode strings
        }
    }
    dsize += node->Sizeof();
    return branch;
}
References ACC_STATIC_CAST, PeFile::Resource::upx_rbranch::children, PeFile::Resource::upx_rbranch::data, PeFile::Resource::upx_rleaf::data, PeFile::Resource::res_dir::entries, get_le16(), PeFile::Resource::upx_rnode::id, PeFile::Resource::res_dir::identr, memcpy(), PeFile::Resource::upx_rnode::name, PeFile::Resource::res_dir::namedentr, PeFile::Resource::upx_rbranch::nc, New, PeFile::Resource::upx_rleaf::newoffset, PeFile::Resource::upx_rleaf::next, PeFile::Resource::upx_rnode::parent, PeFile::Resource::res_dir::Sizeof(), and xcheck().
destroy()
void PeFile::Resource::destroy (upx_rnode * urd, unsigned level) private noexcept
Definition at line 1799 of file pefile.cpp.
{
    xcheck(node);
    if (level == 3) {
        upx_rleaf *leaf = ACC_STATIC_CAST(upx_rleaf *, node);
        delete[] leaf->name;
        leaf->name = nullptr;
        delete leaf;
    } else {
        upx_rbranch *branch = ACC_STATIC_CAST(upx_rbranch *, node);
        delete[] branch->name;
        branch->name = nullptr;
        for (int ic = branch->nc; --ic >= 0;)
            destroy(branch->children[ic], level + 1);
        delete[] branch->children;
        branch->children = nullptr;
        delete branch;
    }
}
References ACC_STATIC_CAST, PeFile::Resource::upx_rbranch::children, PeFile::Resource::upx_rnode::name, PeFile::Resource::upx_rbranch::nc, and xcheck().
dirsize()
unsigned PeFile::Resource::dirsize () const
Definition at line 1627 of file pefile.cpp.
{ return ALIGN_UP(dsize + ssize, 4u); }
References ALIGN_UP.
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
dump() [1/2]
void PeFile::Resource::dump () const
Definition at line 1645 of file pefile.cpp.
{ dump(root, 0); }
dump() [2/2]
void PeFile::Resource::dump (const upx_rnode * node, unsigned level) const private
Definition at line 1823 of file pefile.cpp.
{
    if (level) {
        for (unsigned ic = 1; ic < level; ic++)
            printf("\t\t");
        if (node->name)
            lame_print_unicode(node->name);
        else
            printf("0x%x", node->id);
        printf("\n");
    }
    if (level == 3)
        return;
    const upx_rbranch *const branch = (const upx_rbranch *) node;
    for (unsigned ic = 0; ic < branch->nc; ic++)
        dump(branch->children[ic], level + 1);
}
References PeFile::Resource::upx_rbranch::children, PeFile::Resource::upx_rnode::id, lame_print_unicode(), PeFile::Resource::upx_rnode::name, and PeFile::Resource::upx_rbranch::nc.
ibufcheck()
void PeFile::Resource::ibufcheck (const void * m, unsigned size) private
Definition at line 1685 of file pefile.cpp.
{
    if (m < ibufstart || m > ibufend - siz)
        throwCantUnpack("corrupted resources");
}
References throwCantUnpack().
iname()
unsigned PeFile::Resource::iname () const
Definition at line 1647 of file pefile.cpp.
{ return current->parent->id; }
Referenced by PeFile::processResources().
init()
void PeFile::Resource::init (const byte * res)
Definition at line 1656 of file pefile.cpp.
{
    COMPILE_TIME_ASSERT(sizeof(res_dir_entry) == 8)
    COMPILE_TIME_ASSERT(sizeof(res_dir) == 16 + 8)
    COMPILE_TIME_ASSERT(sizeof(res_data) == 16)
    COMPILE_TIME_ASSERT_ALIGNED1(res_dir_entry)
    COMPILE_TIME_ASSERT_ALIGNED1(res_dir)
    COMPILE_TIME_ASSERT_ALIGNED1(res_data)
    start = res;
    root = head = current = nullptr;
    dsize = ssize = 0;
    check((const res_dir *) start, 0);
    root = convert(start, nullptr, 0);
}
References COMPILE_TIME_ASSERT, and COMPILE_TIME_ASSERT_ALIGNED1.
Referenced by PeFile::processResources().
itype()
unsigned PeFile::Resource::itype () const
Definition at line 1635 of file pefile.cpp.
{ return current->parent->parent->id; }
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
newoffs()
unsigned & PeFile::Resource::newoffs ()
Definition at line 1643 of file pefile.cpp.
{ return current->newoffset; }
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
next()
bool PeFile::Resource::next ()
Definition at line 1629 of file pefile.cpp.
{
    // wow, builtin autorewind... :-)
    current = current ? current->next : head;
    return current != nullptr;
}
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
nname()
const byte * PeFile::Resource::nname () const
Definition at line 1649 of file pefile.cpp.
{ return current->parent->name; }
Referenced by PeFile::processResources().
ntype()
const byte * PeFile::Resource::ntype () const
Definition at line 1637 of file pefile.cpp.
{ return current->parent->parent->name; }
Referenced by PeFile::processResources().
offs()
unsigned PeFile::Resource::offs () const
Definition at line 1641 of file pefile.cpp.
{ return current->data.offset; }
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
size()
unsigned PeFile::Resource::size () const
Definition at line 1639 of file pefile.cpp.
{ return ALIGN_UP(current->data.size, 4u); }
References ALIGN_UP.
Referenced by PeFile::processResources(), and PeFile::rebuildResources().
Member Data Documentation
current
upx_rleaf* PeFile::Resource::current = nullptr private
Definition at line 474 of file pefile.h.
dsize
unsigned PeFile::Resource::dsize = 0 private
Definition at line 475 of file pefile.h.
head
upx_rleaf* PeFile::Resource::head = nullptr private
Definition at line 473 of file pefile.h.
ibufend
const byte* PeFile::Resource::ibufend = nullptr private
Definition at line 479 of file pefile.h.
Referenced by Resource().
ibufstart
const byte* PeFile::Resource::ibufstart = nullptr private
Definition at line 478 of file pefile.h.
Referenced by Resource().
mb_start
MemBuffer PeFile::Resource::mb_start private
Definition at line 469 of file pefile.h.
newstart
byte* PeFile::Resource::newstart = nullptr private
Definition at line 471 of file pefile.h.
root
upx_rnode* PeFile::Resource::root = nullptr private
Definition at line 472 of file pefile.h.
ssize
unsigned PeFile::Resource::ssize = 0 private
Definition at line 476 of file pefile.h.
start
const byte* PeFile::Resource::start = nullptr private
Definition at line 470 of file pefile.h.
The documentation for this class was generated from the following files:
src/pefile.h
src/pefile.cpp