My Project: PackDjgpp2 Class Reference
PackDjgpp2 Class Reference final
djgpp2/coff
#include <p_djgpp2.h>
Classes
struct coff_header_t
struct external_scnhdr_t
Public Member Functions
PackDjgpp2 (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
void handleStub (OutputFile *fo)
util
int readFileHeader ()
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const override
Find overhead for in-place decompression in a heuristic way (using a binary search).
virtual void buildLoader (const Filter *ft) override
virtual Linker * newLinker () const override
void stripDebug ()
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
unsigned coff_offset
coff_header_t coff_hdr
external_scnhdr_t * text = nullptr
external_scnhdr_t * data = nullptr
external_scnhdr_t * bss = nullptr
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
djgpp2/coff
Definition at line 34 of file p_djgpp2.h.
Member Typedef Documentation
super
typedef Packer PackDjgpp2::super private
Definition at line 35 of file p_djgpp2.h.
Constructor & Destructor Documentation
PackDjgpp2()
static const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT PackDjgpp2::PackDjgpp2 (InputFile * f) explicit
Definition at line 44 of file p_djgpp2.cpp.
                                   : super(f), coff_offset(0) {
    bele = &N_BELE_RTP::le_policy;
    COMPILE_TIME_ASSERT(sizeof(external_scnhdr_t) == 40)
    COMPILE_TIME_ASSERT(sizeof(coff_header_t) == 0xa8)
    COMPILE_TIME_ASSERT_ALIGNED1(external_scnhdr_t)
    COMPILE_TIME_ASSERT_ALIGNED1(coff_header_t)
    COMPILE_TIME_ASSERT(sizeof(stub_i386_dos32_djgpp2_stubify) == 2048)
    COMPILE_TIME_ASSERT(STUB_I386_DOS32_DJGPP2_STUBIFY_ADLER32 == 0xbf689ba8)
    COMPILE_TIME_ASSERT(STUB_I386_DOS32_DJGPP2_STUBIFY_CRC32 == 0x2ae982b2)
    // printf("0x%08x\n", upx_adler32(stubify_stub, sizeof(stubify_stub)));
    // assert(upx_adler32(stubify_stub, sizeof(stubify_stub)) == STUBIFY_STUB_ADLER32);
}
References Packer::bele, COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, N_BELE_RTP::le_policy, stub_i386_dos32_djgpp2_stubify, STUB_I386_DOS32_DJGPP2_STUBIFY_ADLER32, and STUB_I386_DOS32_DJGPP2_STUBIFY_CRC32.
Member Function Documentation
buildLoader()
void PackDjgpp2::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 76 of file p_djgpp2.cpp.
{
    // prepare loader
    initLoader(stub_i386_dos32_djgpp2, sizeof(stub_i386_dos32_djgpp2));
    addLoader("IDENTSTR,DJ2MAIN1", ft->id ? "DJCALLT1" : "",
              ph.first_offset_found == 1 ? "DJ2MAIN2" : "",
              M_IS_LZMA(ph.method) ? "LZMA_INIT_STACK" : "", getDecompressorSections(),
              M_IS_LZMA(ph.method) ? "LZMA_DONE_STACK" : "", "DJ2BSS00");
    if (ft->id) {
        assert(ft->calls > 0);
        addLoader("DJCALLT2");
        addFilter32(ft->id);
    }
    addLoader("DJRETURN,+40C,UPX1HEAD");
}
References Packer::addFilter32(), Packer::addLoader(), Filter::calls, PackHeader::first_offset_found, Packer::getDecompressorSections(), Filter::id, Packer::initLoader(), M_IS_LZMA, PackHeader::method, PackerBase::ph, and stub_i386_dos32_djgpp2.
canPack()
tribool PackDjgpp2::canPack () override virtual
Implements PackerBase.
Definition at line 200 of file p_djgpp2.cpp.
{
    if (!readFileHeader())
        return false;
    if (is_dlm(fi, coff_offset))
        throwCantPack("can't handle DLM");
    if (opt->force == 0)
        if (text->size != coff_hdr.a_tsize || data->size != coff_hdr.a_dsize)
            throwAlreadyPacked();
    // Check for gap in vaddr between text and data, or between data and bss.
    if (text->vaddr + text->size != data->vaddr || data->vaddr + data->size != bss->vaddr) {
        // "Non-standard" layout of text,data,bss: not contiguous in vaddr.
        // But should be OK if no overlap.
        // Check for no overlap of text and data:
        // neither by vaddr, nor by image data
        if (text->vaddr + text->size <= data->vaddr &&
            data->scnptr - text->scnptr <= data->vaddr - text->vaddr) {
            // Examples: Quake1; FreePascal(DOS) install.exe (github-issue45)
            // Hack: enlarge text image data to eliminate the gap.
            text->size = coff_hdr.a_tsize = data->scnptr - text->scnptr;
            // But complain if this causes overlap in vaddr
            if (text->vaddr + text->size > data->vaddr)
                throwAlreadyPacked();
        } else
            throwAlreadyPacked();
    }
    // FIXME: check for Linux etc.
    return true;
}
References PackDjgpp2::coff_header_t::a_dsize, PackDjgpp2::coff_header_t::a_tsize, bss, coff_hdr, coff_offset, data, PackerBase::fi, is_dlm(), opt, readFileHeader(), PackDjgpp2::external_scnhdr_t::scnptr, PackDjgpp2::external_scnhdr_t::size, text, throwAlreadyPacked(), throwCantPack(), and PackDjgpp2::external_scnhdr_t::vaddr.
canUnpack()
tribool PackDjgpp2::canUnpack () override virtual
Implements PackerBase.
Definition at line 349 of file p_djgpp2.cpp.
{
    if (!readFileHeader())
        return false;
    if (is_dlm(fi, coff_offset))
        throwCantUnpack("can't handle DLM");
    fi->seek(coff_offset, SEEK_SET);
    return readPackHeader(4096) ? 1 : -1;
}
References coff_offset, PackerBase::fi, is_dlm(), readFileHeader(), Packer::readPackHeader(), InputFile::seek(), SEEK_SET, and throwCantUnpack().
findOverlapOverhead()
unsigned PackDjgpp2::findOverlapOverhead (const byte * buf, const byte * tbuf, unsigned range = 0, unsigned upper_limit = ~0u) const override protected virtual
Find overhead for in-place decompression in a heuristic way (using a binary search).
Return 0 on error.
To speed up things:
you can pass the range of an acceptable interval (so that we can succeed early)
you can enforce an upper_limit (so that we can fail early)
Reimplemented from Packer.
Definition at line 69 of file p_djgpp2.cpp.
{
    unsigned o = super::findOverlapOverhead(buf, tbuf, range, upper_limit);
    o = (o + 0x3ff) & ~0x1ff;
    return o;
}
References buf, and Packer::findOverlapOverhead().
getCompressionMethods()
const int * PackDjgpp2::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 59 of file p_djgpp2.cpp.
{
    return Packer::getDefaultCompressionMethods_le32(method, level);
}
References Packer::getDefaultCompressionMethods_le32().
getFilters()
const int * PackDjgpp2::getFilters () const override virtual
Implements PackerBase.
Definition at line 63 of file p_djgpp2.cpp.
{
    static const int filters[] = {0x26, 0x24,           0x49, 0x46, 0x16, 0x13,  0x14,
                                  0x11, FT_ULTRA_BRUTE, 0x25, 0x15, 0x12, FT_END};
    return filters;
}
References FT_END, and FT_ULTRA_BRUTE.
getFormat()
virtual int PackDjgpp2::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 40 of file p_djgpp2.h.
{ return UPX_F_DJGPP2_COFF; }
References UPX_F_DJGPP2_COFF.
getFullName()
virtual const char * PackDjgpp2::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 42 of file p_djgpp2.h.
{
        return "i386-dos32.djgpp2.coff";
    }
getName()
virtual const char * PackDjgpp2::getName () const inline override virtual
Implements PackerBase.
Definition at line 41 of file p_djgpp2.h.
{ return "djgpp2/coff"; }
Referenced by pack().
getVersion()
virtual int PackDjgpp2::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 39 of file p_djgpp2.h.
{ return 14; }
handleStub()
void PackDjgpp2::handleStub (OutputFile * fo) protected
util
Definition at line 95 of file p_djgpp2.cpp.
{
    if (fo && !opt->djgpp2_coff.coff) {
        if (coff_offset > 0) {
            // copy stub from exe
            Packer::handleStub(fi, fo, coff_offset);
        } else {
            // "stubify" stub
            info("Adding stub: %zd bytes", sizeof(stub_i386_dos32_djgpp2_stubify));
            fo->write(stub_i386_dos32_djgpp2_stubify, sizeof(stub_i386_dos32_djgpp2_stubify));
        }
    }
}
References coff_offset, PackerBase::fi, Packer::handleStub(), info(), opt, stub_i386_dos32_djgpp2_stubify, and OutputFile::write().
Referenced by pack(), and unpack().
newLinker()
Linker * PackDjgpp2::newLinker () const override protected virtual
Implements Packer.
Definition at line 57 of file p_djgpp2.cpp.
{ return new ElfLinkerX86; }
pack()
void PackDjgpp2::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 236 of file p_djgpp2.cpp.
{
    handleStub(fo);
    // patch coff header #1: "strip" debug info
    stripDebug();
    // read file
    const unsigned size = text->size + data->size;
    const unsigned tpos = text->scnptr;
    const unsigned hdrsize = 20 + 28 + mem_size(sizeof(external_scnhdr_t), coff_hdr.f_nscns);
    const unsigned usize = size + hdrsize;
    if (hdrsize < sizeof(coff_hdr) || hdrsize > tpos)
        throwCantPack("coff header error");
    ibuf.alloc(usize);
    obuf.allocForCompression(usize);
    fi->seek(coff_offset, SEEK_SET);
    fi->readx(ibuf, hdrsize); // orig. coff header
    fi->seek(coff_offset + tpos, SEEK_SET);
    fi->readx(ibuf + hdrsize, size);
    // prepare packheader
    ph.u_len = usize;
    // prepare filter
    Filter ft(ph.level);
    ft.buf_len = usize - data->size;
    ft.addvalue = text->vaddr - hdrsize;
    // compress
    upx_compress_config_t cconf;
    cconf.reset();
    // limit stack size needed for runtime decompression
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    compressWithFilters(&ft, 512, &cconf);
    // patch coff header #2
    const unsigned lsize = getLoaderSize();
    assert(lsize % 4 == 0);
    text->size = lsize;    // new size of .text
    data->size = ph.c_len; // new size of .data
    unsigned stack = 1024 + ph.overlap_overhead + getDecompressorWrkmemSize();
    stack = ALIGN_UP(stack, 16u);
    if (bss->size < stack) // give it a .bss
        bss->size = stack;
    text->scnptr = sizeof(coff_hdr);
    data->scnptr = text->scnptr + text->size;
    data->vaddr = bss->vaddr + ((data->scnptr + data->size) & 0x1ff) - data->size +
                  ph.overlap_overhead - 0x200;
    coff_hdr.f_nscns = 3;
    linker->defineSymbol("original_entry", coff_hdr.a_entry);
    linker->defineSymbol("length_of_bss", ph.overlap_overhead / 4);
    defineDecompressorSymbols();
    // Just need no overlap; non-contiguous (gap length > 0)) is OK
    assert(bss->vaddr >= ((size + 0x1ff) & ~0x1ff) + (text->vaddr & ~0x1ff));
    linker->defineSymbol("stack_for_lzma", bss->vaddr + bss->size);
    linker->defineSymbol("start_of_uncompressed", text->vaddr - hdrsize);
    linker->defineSymbol("start_of_compressed", data->vaddr);
    defineFilterSymbols(&ft);
    // we should not overwrite our decompressor during unpacking
    // the original coff header (which is put just before the
    // beginning of the original .text section)
    assert(text->vaddr > hdrsize + lsize + sizeof(coff_hdr));
    // patch coff header #3
    text->vaddr = sizeof(coff_hdr);
    coff_hdr.a_entry = sizeof(coff_hdr) + getLoaderSection("DJ2MAIN1");
    bss->vaddr += ph.overlap_overhead;
    bss->size -= ph.overlap_overhead;
    // because of a feature (bug?) in stub.asm we need some padding
    memcpy(obuf + data->size, "UPX", 3);
    data->size = ALIGN_UP(data->size, 4u);
    linker->defineSymbol("DJ2MAIN1", coff_hdr.a_entry);
    relocateLoader();
    // prepare loader
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, lsize);
    // write coff header, loader and compressed file
    fo->write(&coff_hdr, sizeof(coff_hdr));
    fo->write(loader, lsize);
    if (opt->debug.dump_stub_loader)
        OutputFile::dump(opt->debug.dump_stub_loader, loader, lsize);
    fo->write(obuf, data->size);
#if 0
    printf("%-13s: coff hdr   : %8d bytes\n", getName(), (int) sizeof(coff_hdr));
    printf("%-13s: loader     : %8d bytes\n", getName(), (int) lsize);
    printf("%-13s: compressed : %8d bytes\n", getName(), (int) data->size);
#endif
    // verify
    verifyOverlappingDecompression();
    // handle overlay
    // FIXME: only Allegro pakfiles are supported
    handle_allegropak(fi, fo);
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References PackDjgpp2::coff_header_t::a_entry, Filter::addvalue, ALIGN_UP, MemBuffer::alloc(), MemBuffer::allocForCompression(), bss, Filter::buf_len, PackHeader::c_len, Packer::checkFinalCompressionRatio(), coff_hdr, coff_offset, Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, data, Packer::defineDecompressorSymbols(), Packer::defineFilterSymbols(), OutputFile::dump(), PackDjgpp2::coff_header_t::f_nscns, PackerBase::fi, Packer::getDecompressorWrkmemSize(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSize(), getName(), handle_allegropak(), handleStub(), Packer::ibuf, PackHeader::level, lzma_compress_config_t::max_num_probs, mem_size(), memcpy(), Packer::obuf, opt, PackHeader::overlap_overhead, Packer::patchPackHeader(), PackerBase::ph, InputFile::readx(), Packer::relocateLoader(), upx_compress_config_t::reset(), PackDjgpp2::external_scnhdr_t::scnptr, InputFile::seek(), SEEK_SET, PackDjgpp2::external_scnhdr_t::size, size(), stripDebug(), text, throwCantPack(), throwNotCompressible(), PackHeader::u_len, PackDjgpp2::external_scnhdr_t::vaddr, Packer::verifyOverlappingDecompression(), and OutputFile::write().
readFileHeader()
int PackDjgpp2::readFileHeader () protected
Definition at line 152 of file p_djgpp2.cpp.
{
    byte hdr[0x1c];
    byte magic[8];
    fi->seek(0, SEEK_SET);
    fi->readx(hdr, sizeof(hdr));
    if (get_le16(hdr) == 0x5a4d) // MZ exe signature, stubbed?
    {
        coff_offset = 512 * get_le16(hdr + 4);
        if (get_le16(hdr + 2) != 0)
            coff_offset += get_le16(hdr + 2) - 512;
        fi->seek(512, SEEK_SET);
        fi->readx(magic, 8);
        if (memcmp("go32stub", magic, 8) != 0)
            return 0; // not V2 image
        fi->seek(coff_offset, SEEK_SET);
        if (fi->read(&coff_hdr, sizeof(coff_hdr)) != sizeof(coff_hdr))
            throwCantPack("skipping djgpp symlink");
    } else {
        fi->seek(coff_offset, SEEK_SET);
        fi->readx(&coff_hdr, 0xa8);
    }
    if (coff_hdr.f_magic != 0x014c) // I386MAGIC
        return 0;
    if ((coff_hdr.f_flags & 2) == 0) // F_EXEC - COFF executable
        return 0;
    if (coff_hdr.a_magic != 0413) // ZMAGIC - demand load format
        return 0;
    // FIXME: check for Linux etc.
    text = &coff_hdr.sh[0];
    data = &coff_hdr.sh[1];
    bss = &coff_hdr.sh[2];
    return UPX_F_DJGPP2_COFF;
}
References PackDjgpp2::coff_header_t::a_magic, bss, coff_hdr, coff_offset, data, PackDjgpp2::coff_header_t::f_flags, PackDjgpp2::coff_header_t::f_magic, PackerBase::fi, get_le16(), memcmp(), InputFile::read(), InputFile::readx(), InputFile::seek(), SEEK_SET, PackDjgpp2::coff_header_t::sh, text, throwCantPack(), and UPX_F_DJGPP2_COFF.
Referenced by canPack(), and canUnpack().
stripDebug()
void PackDjgpp2::stripDebug () protected
Definition at line 189 of file p_djgpp2.cpp.
{
    coff_hdr.f_symptr = 0;
    coff_hdr.f_nsyms = 0;
    coff_hdr.f_flags = 0x10f; // 0x100: "32 bit machine: LSB first"
    memset(text->misc, 0, 12);
}
References coff_hdr, PackDjgpp2::coff_header_t::f_flags, PackDjgpp2::coff_header_t::f_nsyms, PackDjgpp2::coff_header_t::f_symptr, memset(), PackDjgpp2::external_scnhdr_t::misc, and text.
Referenced by pack().
unpack()
void PackDjgpp2::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 362 of file p_djgpp2.cpp.
{
    handleStub(fo);
    ibuf.alloc(ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    fi->seek(coff_offset + ph.buf_offset + ph.getPackHeaderSize(), SEEK_SET);
    fi->readx(ibuf, ph.c_len);
    // decompress
    decompress(ibuf, obuf);
    coff_header_t *const chdr = (coff_header_t *) raw_bytes(obuf, sizeof(coff_header_t));
    text = &chdr->sh[0];
    data = &chdr->sh[1];
    bss = &chdr->sh[2];
    const unsigned hdrsize = 20 + 28 + mem_size(sizeof(external_scnhdr_t), chdr->f_nscns);
    if (hdrsize < sizeof(coff_hdr) || hdrsize > text->scnptr || hdrsize > ph.u_len)
        throwCantUnpack("coff header error");
    unsigned addvalue;
    if (ph.version >= 14)
        addvalue = text->vaddr - hdrsize;
    else
        addvalue = text->vaddr & ~0x1ff; // for old versions
    // unfilter
    if (ph.filter) {
        Filter ft(ph.level);
        ft.init(ph.filter, addvalue);
        ft.cto = (byte) ph.filter_cto;
        if (ph.version < 11) {
            byte ctobuf[4];
            fi->readx(ctobuf, 4);
            ft.cto = (byte) (get_le32(ctobuf) >> 24);
        }
        ft.unfilter(obuf, ph.u_len - data->size);
    }
    if (ph.version < 14) {
        // fixup for the aligning bug in strip 2.8+
        text->scnptr &= 0x1ff;
        data->scnptr = text->scnptr + text->size;
        // write decompressed file
        if (fo)
            fo->write(obuf, ph.u_len);
    } else {
        // write the header
        // some padding might be required between the end
        // of the header and the start of the .text section
        const unsigned padding = text->scnptr - hdrsize;
        ibuf.clear(0, padding);
        if (fo) {
            fo->write(obuf, hdrsize);
            fo->write(ibuf, padding);
            fo->write(obuf + hdrsize, ph.u_len - hdrsize);
        }
    }
    if (fo)
        handle_allegropak(fi, fo);
}
References MemBuffer::alloc(), MemBuffer::allocForDecompression(), bss, PackHeader::buf_offset, PackHeader::c_len, MemBuffer::clear(), coff_hdr, coff_offset, Filter::cto, data, Packer::decompress(), PackDjgpp2::coff_header_t::f_nscns, PackerBase::fi, PackHeader::filter, PackHeader::filter_cto, get_le32(), PackHeader::getPackHeaderSize(), handle_allegropak(), handleStub(), Packer::ibuf, Filter::init(), PackHeader::level, mem_size(), Packer::obuf, PackerBase::ph, raw_bytes(), InputFile::readx(), PackDjgpp2::external_scnhdr_t::scnptr, InputFile::seek(), SEEK_SET, PackDjgpp2::coff_header_t::sh, PackDjgpp2::external_scnhdr_t::size, text, throwCantUnpack(), PackHeader::u_len, Filter::unfilter(), PackDjgpp2::external_scnhdr_t::vaddr, PackHeader::version, and OutputFile::write().
Member Data Documentation
bss
external_scnhdr_t* PackDjgpp2::bss = nullptr protected
Definition at line 100 of file p_djgpp2.h.
Referenced by canPack(), pack(), readFileHeader(), and unpack().
coff_hdr
coff_header_t PackDjgpp2::coff_hdr protected
Definition at line 97 of file p_djgpp2.h.
Referenced by canPack(), pack(), readFileHeader(), stripDebug(), and unpack().
coff_offset
unsigned PackDjgpp2::coff_offset protected
Definition at line 63 of file p_djgpp2.h.
Referenced by canPack(), canUnpack(), handleStub(), pack(), readFileHeader(), and unpack().
data
external_scnhdr_t* PackDjgpp2::data = nullptr protected
Definition at line 99 of file p_djgpp2.h.
Referenced by canPack(), pack(), readFileHeader(), and unpack().
text
external_scnhdr_t* PackDjgpp2::text = nullptr protected
Definition at line 98 of file p_djgpp2.h.
Referenced by canPack(), pack(), readFileHeader(), stripDebug(), and unpack().
The documentation for this class was generated from the following files:
src/p_djgpp2.h
src/p_djgpp2.cpp