My Project: PackLinuxElf64arm Class Reference
PackLinuxElf64arm Class Reference
#include <p_lx_elf.h>
Public Member Functions
PackLinuxElf64arm (InputFile *f)
virtual ~PackLinuxElf64arm ()
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getFilters () const override
Public Member Functions inherited from PackLinuxElf64
PackLinuxElf64 (InputFile *f)
virtual ~PackLinuxElf64 ()
Public Member Functions inherited from PackLinuxElf
PackLinuxElf (InputFile *f)
virtual ~PackLinuxElf ()
virtual int getVersion () const override
virtual bool canUnpackVersion (int version) const override
virtual tribool canUnpack () override
Generic Unix canUnpack().
Public Member Functions inherited from PackUnix
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual void pack1 (OutputFile *, Filter &) override
virtual void buildLoader (const Filter *) override
virtual Linker * newLinker () const override
virtual void defineSymbols (Filter const *) override
Protected Member Functions inherited from PackLinuxElf64Le
PackLinuxElf64Le (InputFile *f)
Protected Member Functions inherited from PackLinuxElf64
virtual void PackLinuxElf64help1 (InputFile *f)
virtual int checkEhdr (Elf64_Ehdr const *ehdr) const
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
virtual upx_uint64_t canPack_Shdr (Elf64_Phdr const *pload_x0)
virtual void pack1 (OutputFile *, Filter &) override
virtual void asl_pack2_Shdrs (OutputFile *, unsigned pre_xct_top)
virtual int pack2 (OutputFile *, Filter &) override
virtual int pack2_shlib (OutputFile *fo, Filter &ft, unsigned pre_xct_top)
virtual off_t pack3 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
virtual unsigned forward_Shdrs (OutputFile *fo, Elf64_Ehdr *ehdro)
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual void un_asl_dynsym (unsigned orig_file_size, OutputFile *)
virtual void un_shlib_1 (OutputFile *const fo, MemBuffer &o_elfhdrs, unsigned &c_adler, unsigned &u_adler, unsigned const orig_file_size)
virtual void un_DT_INIT (unsigned old_dtinit, Elf64_Phdr const *phdro, Elf64_Phdr const *dynhdr, OutputFile *fo)
virtual void unRela64 (upx_uint64_t dt_rela, Elf64_Rela *rela0, unsigned relasz, upx_uint64_t const old_dtinit, OutputFile *fo)
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka) override
virtual void defineSymbols (Filter const *) override
virtual void buildLinuxLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const *ft)
virtual off_t getbrk (const Elf64_Phdr *phdr, int e_phnum) const
virtual void patchLoader () override
virtual void updateLoader (OutputFile *fo) override
virtual unsigned find_LOAD_gap (Elf64_Phdr const *const phdri, unsigned const k, unsigned const e_phnum)
bool calls_crt1 (Elf64_Rela const *rela, int sz)
virtual Elf64_Sym const * elf_lookup (char const *) const
virtual upx_uint64_t elf_get_offset_from_address (upx_uint64_t) const
virtual Elf64_Phdr const * elf_find_Phdr_for_va (upx_uint64_t addr, Elf64_Phdr const *phdr, unsigned phnum)
Elf64_Phdr const * elf_find_ptype (unsigned type, Elf64_Phdr const *phdr0, unsigned phnum)
Elf64_Shdr const * elf_find_section_name (char const *) const
Elf64_Shdr * elf_find_section_type (unsigned) const
Elf64_Dyn * elf_find_dynptr (unsigned) const
unsigned elf_find_table_size (unsigned dt_type, unsigned sh_type)
void sort_DT64_offsets (Elf64_Dyn const *const dynp0)
int is_LOAD (Elf64_Phdr const *phdr) const
upx_uint64_t check_pt_load (Elf64_Phdr const *)
upx_uint64_t check_pt_dynamic (Elf64_Phdr const *)
void invert_pt_dynamic (Elf64_Dyn const *, upx_uint64_t dt_filesz)
void * elf_find_dynamic (unsigned) const
Elf64_Dyn const * elf_has_dynamic (unsigned) const
virtual upx_uint64_t elf_unsigned_dynamic (unsigned) const override
unsigned find_dt_ndx (u64_t rva)
virtual int adjABS (Elf64_Sym *sym, unsigned long delta)
void add_phdrx (Elf64_Phdr const *)
char const * get_str_name (unsigned st_name, unsigned symnum) const
char const * get_dynsym_name (unsigned symnum, unsigned relnum) const
packed_struct (cprElfHdr1)
packed_struct (cprElfHdr2)
packed_struct (cprElfHdr3)
packed_struct (cprElfHdr4)
packed_struct (cprElfShdr3)
Protected Member Functions inherited from PackLinuxElf
virtual const int * getCompressionMethods (int method, int level) const override
virtual void pack1 (OutputFile *, Filter &) override=0
virtual int pack2 (OutputFile *, Filter &) override=0
virtual off_t pack3 (OutputFile *, Filter &) override=0
virtual unsigned pack2_shlib_overlay_init (OutputFile *fo)
virtual unsigned pack2_shlib_overlay_compress (MemBuffer &obuf, MemBuffer &ibuf, unsigned u_len)
virtual unsigned pack2_shlib_overlay_write (OutputFile *fo, MemBuffer &obuf, unsigned hdr_u_len, unsigned hdr_c_len)
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka)=0
virtual void defineSymbols (Filter const *)
virtual void addStubEntrySections (Filter const *, unsigned m_decompr)
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual upx_uint64_t elf_unsigned_dynamic (unsigned) const =0
Protected Member Functions inherited from PackUnix
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Private Types
typedef PackLinuxElf64Le super
Additional Inherited Members
Public Types inherited from PackUnix
typedef Packer super
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PackUnix
enum { OVERHEAD = 2048 }
Static Protected Member Functions inherited from PackLinuxElf64
static void compileTimeAssertions ()
Static Protected Member Functions inherited from PackLinuxElf
static unsigned elf_hash (char const *)
static unsigned gnu_hash (char const *)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes inherited from PackLinuxElf64
Elf64_Ehdr ehdri
Elf64_Phdr * phdri
Elf64_Shdr * shdri
Elf64_Shdr * shdro
Elf64_Phdr const * phdrx [END_PHDRX]
unsigned n_phdrx
unsigned sz_phdrx
upx_uint64_t e_phoff
upx_uint64_t e_shoff
upx_uint64_t sz_dynseg
unsigned n_jmp_slot
upx_uint64_t page_mask
Elf64_Dyn * dynseg
unsigned int const * hashtab
unsigned int const * hashend
unsigned int const * gashtab
unsigned int const * gashend
Elf64_Sym * dynsym
Elf64_Sym const * jni_onload_sym
Elf64_Shdr * sec_strndx
Elf64_Shdr * sec_dynsym
Elf64_Shdr const * sec_dynstr
Elf64_Shdr * sec_arm_attr
cprElfHdr4 elfout
cprElfShdr3 shdrout
Protected Attributes inherited from PackLinuxElf
unsigned old_data_off
unsigned old_data_len
unsigned e_type
unsigned e_phnum
unsigned e_shnum
unsigned e_shstrndx
MemBuffer file_image
MemBuffer lowmem
MemBuffer mb_shdr
MemBuffer mb_dt_offsets
unsigned * dt_offsets
unsigned symnum_max
unsigned strtab_max
char const * dynstr
unsigned sz_phdrs
unsigned sz_elf_hdrs
unsigned sz_pack2
unsigned sz_pack2a
unsigned lg2_page
unsigned page_size
bool is_pie
unsigned is_asl
unsigned xct_off
unsigned hatch_off
unsigned o_binfo
upx_off_t so_slide
upx_uint64_t load_va
upx_uint64_t xct_va
upx_uint64_t jni_onload_va
upx_uint64_t user_init_va
void * user_init_rp
upx_uint64_t plt_va
upx_uint64_t plt_off
unsigned user_init_off
unsigned linfo_off
unsigned loader_offset
upx_uint16_t e_machine
unsigned char ei_class
unsigned char ei_data
unsigned char ei_osabi
unsigned char prev_method
char const * osabi_note
unsigned upx_dt_init
unsigned dt_table [DT_NUM]
MemBuffer mb_shstrtab
char const * shstrtab
MemBuffer jump_slots
MemBuffer buildid_data
MemBuffer note_body
unsigned note_size
int o_elf_shnum
Protected Attributes inherited from PackUnix
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Static Protected Attributes inherited from PackLinuxElf64
static unsigned const END_PHDRX = 5
Static Protected Attributes inherited from PackLinuxElf
static unsigned int const asl_delta = (1u<<12)
static unsigned const DT_NUM = 34
static const unsigned char o_shstrtab []
Detailed Description
Definition at line 533 of file p_lx_elf.h.
Member Typedef Documentation
super
typedef PackLinuxElf64Le PackLinuxElf64arm::super private
Definition at line 535 of file p_lx_elf.h.
Constructor & Destructor Documentation
PackLinuxElf64arm()
PackLinuxElf64arm::PackLinuxElf64arm (InputFile * f)
Definition at line 1328 of file p_lx_elf.cpp.
    : super(f)
{
    e_machine = Elf64_Ehdr::EM_AARCH64;
    ei_class = Elf64_Ehdr::ELFCLASS64;
    ei_data = Elf64_Ehdr::ELFDATA2LSB;
    ei_osabi  = Elf32_Ehdr::ELFOSABI_LINUX;
}
References PackLinuxElf::e_machine, PackLinuxElf::ei_class, PackLinuxElf::ei_data, and PackLinuxElf::ei_osabi.
~PackLinuxElf64arm()
PackLinuxElf64arm::~PackLinuxElf64arm () virtual
Definition at line 1341 of file p_lx_elf.cpp.
{
}
Member Function Documentation
buildLoader()
static const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT void PackLinuxElf64arm::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 2130 of file p_lx_elf.cpp.
{
    if (0!=xct_off) {  // shared library
        buildLinuxLoader(
            stub_arm64_linux_elf_so_entry, sizeof(stub_arm64_linux_elf_so_entry),
            stub_arm64_linux_elf_so_fold,  sizeof(stub_arm64_linux_elf_so_fold), ft);
        return;
    }
    buildLinuxLoader(
        stub_arm64_linux_elf_entry, sizeof(stub_arm64_linux_elf_entry),
        stub_arm64_linux_elf_fold,  sizeof(stub_arm64_linux_elf_fold), ft);
}
References PackLinuxElf64::buildLinuxLoader(), stub_arm64_linux_elf_entry, stub_arm64_linux_elf_fold, stub_arm64_linux_elf_so_entry, stub_arm64_linux_elf_so_fold, and PackLinuxElf::xct_off.
defineSymbols()
void PackLinuxElf64arm::defineSymbols (Filter const * ft) override protected virtual
Reimplemented from PackLinuxElf64.
Definition at line 5972 of file p_lx_elf.cpp.
{
    PackLinuxElf64::defineSymbols(ft);
#define MAP_PRIVATE      2     /* UNIX standard */
#define MAP_FIXED     0x10     /* UNIX standard */
#define MAP_ANONYMOUS 0x20     /* UNIX standard */
#define MAP_PRIVANON     3     /* QNX anonymous private memory */
    unsigned mflg = MAP_PRIVATE | MAP_ANONYMOUS;
    //if (ARM_is_QNX())
    //    mflg = MAP_PRIVANON;
    linker->defineSymbol("MFLG", mflg);
}
References PackLinuxElf64::defineSymbols(), MAP_ANONYMOUS, and MAP_PRIVATE.
getFilters()
int const * PackLinuxElf64arm::getFilters () const override virtual
Reimplemented from PackUnix.
Definition at line 1187 of file p_lx_elf.cpp.
{
    static const int filters[] = {
        0x52,
    FT_END };
    return filters;
}
References FT_END.
getFormat()
virtual int PackLinuxElf64arm::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 539 of file p_lx_elf.h.
{ return UPX_F_LINUX_ELF64_ARM64; }
References UPX_F_LINUX_ELF64_ARM64.
getFullName()
virtual const char * PackLinuxElf64arm::getFullName (const options_t *) const inline override virtual
Definition at line 541 of file p_lx_elf.h.
{ return "arm64-linux.elf"; }
getName()
virtual const char * PackLinuxElf64arm::getName () const inline override virtual
Implements PackerBase.
Definition at line 540 of file p_lx_elf.h.
{ return "linux/arm64"; }
newLinker()
Linker * PackLinuxElf64arm::newLinker () const override protected virtual
Implements Packer.
Definition at line 1126 of file p_lx_elf.cpp.
{
    return new ElfLinkerArm64LE;
}
pack1()
void PackLinuxElf64arm::pack1 (OutputFile * fo, Filter & ft) override protected virtual
Reimplemented from PackLinuxElf64.
Definition at line 5215 of file p_lx_elf.cpp.
{
    super::pack1(fo, ft);
    if (0!=xct_off)  // shared library
        return;
    generateElfHdr(fo, stub_arm64_linux_elf_fold, getbrk(phdri, e_phnum) );
}
References PackLinuxElf::e_phnum, PackLinuxElf64::generateElfHdr(), PackLinuxElf64::getbrk(), PackLinuxElf::pack1(), PackLinuxElf64::phdri, stub_arm64_linux_elf_fold, and PackLinuxElf::xct_off.
The documentation for this class was generated from the following files:
src/p_lx_elf.h
src/p_lx_elf.cpp