My Project: PackUnix Class Reference
PackUnix Class Reference abstract
Abstract class for all Unix-type packers.
#include <p_unix.h>
Classes
struct Extent
Public Types
typedef Packer super
Public Member Functions
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Types
enum { OVERHEAD = 2048 }
Protected Member Functions
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
Abstract class for all Unix-type packers.
Already provides most of the functionality.
Definition at line 43 of file p_unix.h.
Member Typedef Documentation
super
typedef Packer PackUnix::super
Definition at line 47 of file p_unix.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
OVERHEAD
Definition at line 135 of file p_unix.h.
{ OVERHEAD = 2048 };
Constructor & Destructor Documentation
~PackUnix()
PackUnix::~PackUnix ()
Definition at line 64 of file p_unix.cpp.
{
    opt->o_unix.android_shlib = saved_opt_android_shlib;
}
References opt, and saved_opt_android_shlib.
PackUnix()
PackUnix::PackUnix (InputFile * f) protected
Definition at line 49 of file p_unix.cpp.
                               :
    super(f), exetype(0), blocksize(0), overlay_offset(0), lsize(0),
    methods_used(0), szb_info(sizeof(b_info))
{
    COMPILE_TIME_ASSERT(sizeof(Elf32_Ehdr) == 52)
    COMPILE_TIME_ASSERT(sizeof(Elf32_Phdr) == 32)
    COMPILE_TIME_ASSERT(sizeof(b_info) == 12)
    COMPILE_TIME_ASSERT(sizeof(l_info) == 12)
    COMPILE_TIME_ASSERT(sizeof(p_info) == 12)
    // Disable --android-shlib, file-by-file; undecided how to fix.
    saved_opt_android_shlib = opt->o_unix.android_shlib;
    opt->o_unix.android_shlib = 0;
}
References COMPILE_TIME_ASSERT, opt, and saved_opt_android_shlib.
Member Function Documentation
canPack()
tribool PackUnix::canPack () override virtual
Implements PackerBase.
Reimplemented in PackLinuxElf32, PackLinuxElf64, PackLinuxI386, PackLinuxElf32x86interp, PackLinuxI386sh, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, and PackMachBase< MachClass_BE64 >.
Definition at line 70 of file p_unix.cpp.
{
    if (exetype == 0)
        return false;
#if defined(__unix__)
    // must be executable by owner
    if ((fi->st.st_mode & S_IXUSR) == 0)
        throwCantPack("file not executable; try 'chmod +x'");
#endif
    if (file_size < 4096)
        throwCantPack("file is too small");
    // info: currently the header is 36 (32+4) bytes before EOF
    unsigned char buf[256];
    fi->seek(-(off_t)sizeof(buf), SEEK_END);
    fi->readx(buf, sizeof(buf));
    checkAlreadyPacked(buf, sizeof(buf));
    return true;
}
References buf, Packer::checkAlreadyPacked(), exetype, PackerBase::fi, PackerBase::file_size, InputFile::readx(), InputFile::seek(), SEEK_END, FileBase::st, and throwCantPack().
Referenced by PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), and PackLinuxI386::canPack().
canUnpack()
tribool PackUnix::canUnpack () override virtual
Generic Unix canUnpack().
Implements PackerBase.
Reimplemented in PackLinuxElf, PackLinuxElf32, PackLinuxElf64, PackLinuxElf32x86, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, and PackMachBase< MachClass_BE64 >.
Definition at line 560 of file p_unix.cpp.
{
    int const small = 32 + sizeof(overlay_offset);
    // Allow zero-filled last page, for Mac OS X code signing.
    int bufsize = 2*4096 + 2*small +1;
    if (bufsize > fi->st_size())
        bufsize = fi->st_size();
    MemBuffer buf(bufsize);
    fi->seek(-(off_t)bufsize, SEEK_END);
    fi->readx(buf, bufsize);
    return find_overlay_offset(buf);
}
References buf, PackerBase::fi, find_overlay_offset(), overlay_offset, InputFile::readx(), InputFile::seek(), SEEK_END, and FileBase::st_size().
Referenced by PackLinuxElf::canUnpack().
checkCompressionRatio()
bool PackUnix::checkCompressionRatio (unsigned , unsigned) const override protected virtual
Generic Unix pack().
Subclasses must provide patchLoader().
A typical compressed Unix executable looks like this:
loader stub
12 bytes header info
the compressed blocks, each with a 8 byte header for block sizes
4 bytes block end marker (uncompressed size 0)
32 bytes UPX packheader
4 bytes overlay offset (needed for decompression)
Reimplemented from Packer.
Definition at line 126 of file p_unix.cpp.
{
    return true;
}
find_overlay_offset()
int PackUnix::find_overlay_offset (MemBuffer const & buf)
Definition at line 574 of file p_unix.cpp.
{
    int const small = 32 + sizeof(overlay_offset);
    int const bufsize = buf.getSize();
    int i = bufsize;
    while (i > small && 0 == buf[--i]) { }
    i -= small;
    // allow incompressible extents
    if (i < 0 || !getPackHeader(buf + i, bufsize - i, true))
        return false;
    int l = ph.buf_offset + ph.getPackHeaderSize();
    if (l < 0 || i + l + 4 > bufsize)
        throwCantUnpack("file corrupted");
    overlay_offset = get_te32(buf + i + l);
    if ((off_t)overlay_offset >= file_size)
        throwCantUnpack("file corrupted");
    return true;
}
References buf, PackHeader::buf_offset, PackerBase::file_size, Packer::get_te32(), Packer::getPackHeader(), PackHeader::getPackHeaderSize(), overlay_offset, PackerBase::ph, and throwCantUnpack().
Referenced by canUnpack().
getFilters()
virtual const int * PackUnix::getFilters () const inline override virtual
Implements PackerBase.
Reimplemented in PackLinuxElf64amd, PackLinuxElf64arm, PackLinuxElf32ppc, PackLinuxElf64ppcle, PackLinuxElf64ppc, PackLinuxElf32x86, PackLinuxElf32armLe, PackLinuxElf32armBe, PackLinuxElf32mipseb, PackLinuxElf32mipsel, PackLinuxI386, PackLinuxI386sh, PackMachPPC32, PackMachPPC64, PackMachI386, PackMachAMD64, PackMachARMEL, and PackMachARM64EL.
Definition at line 52 of file p_unix.h.
{ return nullptr; }
Referenced by PackLinuxElf32::pack1(), and PackLinuxElf64::pack1().
getStrategy()
int PackUnix::getStrategy (Filter &) virtual
Definition at line 136 of file p_unix.cpp.
{
    // Called just before reading and compressing each block.
    // Might want to adjust blocksize, etc.
    // If user specified the filter, then use it (-2==filter_strategy).
    // Else try the first two filters, and pick the better (2==filter_strategy).
    return (opt->no_filter ? -3 : ((opt->filter > 0) ? -2 : 2));
}
References opt.
Referenced by pack2(), and packExtent().
getVersion()
virtual int PackUnix::getVersion () const inline override virtual
Implements PackerBase.
Reimplemented in PackLinuxElf, PackLinuxElf32x86interp, PackLinuxI386sh, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, and PackMachBase< MachClass_BE64 >.
Definition at line 51 of file p_unix.h.
{ return 13; }
pack()
void PackUnix::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 283 of file p_unix.cpp.
{
    Filter ft(ph.level);
    ft.addvalue = 0;
    b_len = 0;
    progid = 0;
    // set options
    blocksize = opt->o_unix.blocksize;
    if (blocksize <= 0)
        blocksize = BLOCKSIZE;
    if ((off_t)blocksize > file_size)
        blocksize = file_size;
    // init compression buffers
    ibuf.alloc(blocksize);
    obuf.allocForCompression(blocksize);
    fi->seek(0, SEEK_SET);
    pack1(fo, ft);  // generate Elf header, etc.
    // Shlib probably did not generate Elf header yet.
    if (fo->st_size()) { // Only append if pack1 actually wrote something.
        p_info hbuf;
        set_te32(&hbuf.p_progid, progid);
        set_te32(&hbuf.p_filesize, file_size);
        set_te32(&hbuf.p_blocksize, blocksize);
        fo->write(&hbuf, sizeof(hbuf));
    }
    // append the compressed body
    if (pack2(fo, ft)) {
        // write block end marker (uncompressed size 0)
        b_info hdr; memset(&hdr, 0, sizeof(hdr));
        set_le32(&hdr.sz_cpr, UPX_MAGIC_LE32);
        fo->write(&hdr, sizeof(hdr));
    }
    pack3(fo, ft);  // append loader
    pack4(fo, ft);  // append PackHeader and overlay_offset; update Elf header
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References Filter::addvalue, MemBuffer::alloc(), MemBuffer::allocForCompression(), b_len, BLOCKSIZE, blocksize, Packer::checkFinalCompressionRatio(), PackerBase::fi, PackerBase::file_size, Packer::ibuf, PackHeader::level, memset(), Packer::obuf, opt, p_info::p_blocksize, p_info::p_filesize, p_info::p_progid, pack1(), pack2(), pack3(), pack4(), PackerBase::ph, progid, InputFile::seek(), SEEK_SET, set_le32(), Packer::set_te32(), OutputFile::st_size(), b_info::sz_cpr, throwNotCompressible(), UPX_MAGIC_LE32, and OutputFile::write().
Referenced by PackMachFat::pack().
pack1()
void PackUnix::pack1 (OutputFile * , Filter &) protected virtual
Reimplemented in PackLinuxElf32, PackLinuxElf64, PackLinuxElf64amd, PackLinuxElf64arm, PackLinuxElf32ppc, PackLinuxElf64ppcle, PackLinuxElf64ppc, PackLinuxElf32x86, PackBSDElf32x86, PackLinuxElf32armLe, PackLinuxElf32armBe, PackLinuxElf32mipseb, PackLinuxElf32mipsel, PackLinuxI386, PackBSDI386, PackLinuxElf32x86interp, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, PackLinuxElf, and PackLinuxI386sh.
Definition at line 131 of file p_unix.cpp.
{
    // derived class usually provides this
}
Referenced by pack().
pack2()
int PackUnix::pack2 (OutputFile * fo, Filter & ft) protected virtual
Reimplemented in PackLinuxElf32, PackLinuxElf64, PackLinuxElf32x86interp, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, and PackLinuxElf.
Definition at line 146 of file p_unix.cpp.
{
    // compress blocks
    total_in = 0;
    total_out = 0;
// FIXME: ui_total_passes is not correct with multiple blocks...
//    ui_total_passes = (file_size + blocksize - 1) / blocksize;
//    if (ui_total_passes == 1)
//        ui_total_passes = 0;
    unsigned remaining = file_size;
    unsigned n_block = 0;
    while (remaining > 0)
    {
        // FIXME: disable filters if we have more than one block.
        // FIXME: There is only 1 un-filter in the stub [as of 2002-11-10].
        // So the next block really has no choice!
        // This merely prevents an assert() in compressWithFilters(),
        // which assumes it has free choice on each call [block].
        // And if the choices aren't the same on each block,
        // then un-filtering will give incorrect results.
        int filter_strategy = getStrategy(ft);
        if (file_size > (off_t)blocksize)
            filter_strategy = -3;      // no filters
        int l = fi->readx(ibuf, UPX_MIN(blocksize, remaining));
        remaining -= l;
        // Note: compression for a block can fail if the
        //       file is e.g. blocksize + 1 bytes long
        // compress
        ph.overlap_overhead = 0;
        ph.c_len = ph.u_len = l;
        ft.buf_len = l;
        // compressWithFilters() updates u_adler _inside_ compress();
        // that is, AFTER filtering.  We want BEFORE filtering,
        // so that decompression checks the end-to-end checksum.
        unsigned const end_u_adler = upx_adler32(ibuf, ph.u_len, ph.u_adler);
        compressWithFilters(&ft, OVERHEAD, NULL_cconf, filter_strategy,
            !!n_block++);  // check compression ratio only on first block
        if (ph.c_len < ph.u_len) {
            const upx_bytep tbuf = nullptr;
            if (ft.id == 0) tbuf = ibuf;
            ph.overlap_overhead = OVERHEAD;
            if (!testOverlappingDecompression(obuf, tbuf, ph.overlap_overhead)) {
                // not in-place compressible
                ph.c_len = ph.u_len;
            }
        }
        if (ph.c_len >= ph.u_len) {
            // block is not compressible
            ph.c_len = ph.u_len;
            // must manually update checksum of compressed data
            ph.c_adler = upx_adler32(ibuf, ph.u_len, ph.saved_c_adler);
        }
        // write block header
        b_info blk_info;
        memset(&blk_info, 0, sizeof(blk_info));
        set_te32(&blk_info.sz_unc, ph.u_len);
        set_te32(&blk_info.sz_cpr, ph.c_len);
        if (ph.c_len < ph.u_len) {
            blk_info.b_method = (unsigned char) ph.method;
            blk_info.b_ftid = (unsigned char) ph.filter;
            blk_info.b_cto8 = (unsigned char) ph.filter_cto;
        }
        fo->write(&blk_info, sizeof(blk_info));
        b_len += sizeof(b_info);
        // write compressed data
        if (ph.c_len < ph.u_len) {
            fo->write(obuf, ph.c_len);
            verifyOverlappingDecompression();  // uses ph.u_adler
        }
        else {
            fo->write(ibuf, ph.u_len);
        }
        ph.u_adler = end_u_adler;
        total_in += ph.u_len;
        total_out += ph.c_len;
    }
    // update header with totals
    ph.u_len = total_in;
    ph.c_len = total_out;
    if ((off_t)total_in != file_size) {
        throwEOFException();
    }
    return 1;  // default: write end-of-compression bhdr next
}
References b_info::b_cto8, b_info::b_ftid, b_len, b_info::b_method, blocksize, Filter::buf_len, PackHeader::c_adler, PackHeader::c_len, Packer::compressWithFilters(), PackerBase::fi, PackerBase::file_size, PackHeader::filter, PackHeader::filter_cto, getStrategy(), Packer::ibuf, Filter::id, memset(), PackHeader::method, NULL_cconf, Packer::obuf, OVERHEAD, PackHeader::overlap_overhead, PackerBase::ph, InputFile::readx(), PackHeader::saved_c_adler, Packer::set_te32(), b_info::sz_cpr, b_info::sz_unc, Packer::testOverlappingDecompression(), throwEOFException(), total_in, total_out, PackHeader::u_adler, PackHeader::u_len, upx_adler32(), upx_bytep, UPX_MIN, Packer::verifyOverlappingDecompression(), and OutputFile::write().
Referenced by pack().
pack3()
off_t PackUnix::pack3 (OutputFile * fo, Filter & ft) protected virtual
Reimplemented in PackLinuxElf32, PackLinuxElf64, PackLinuxElf32x86interp, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, PackDylibPPC32, PackDylibPPC64, PackDylibI386, PackDylibAMD64, PackLinuxElf, and PackLinuxI386sh.
Definition at line 258 of file p_unix.cpp.
{
    if (nullptr==linker) {
        // If no filter, then linker is not constructed by side effect
        // of packExtent calling compressWithFilters.
        // This is typical after "/usr/bin/patchelf --set-rpath".
        buildLoader(&ft);
    }
    upx_byte *p = getLoader();
    lsize = getLoaderSize();
    updateLoader(fo);
    patchLoaderChecksum();
    fo->write(p, lsize);
    return fo->getBytesWritten();
}
References Packer::buildLoader(), OutputFile::getBytesWritten(), Packer::getLoader(), Packer::getLoaderSize(), lsize, patchLoaderChecksum(), updateLoader(), upx_byte, and OutputFile::write().
Referenced by pack(), PackDylibPPC32::pack3(), PackDylibPPC64::pack3(), PackDylibI386::pack3(), PackDylibAMD64::pack3(), PackLinuxElf::pack3(), and PackLinuxI386sh::pack3().
pack4()
void PackUnix::pack4 (OutputFile * fo, Filter &) protected virtual
Reimplemented in PackLinuxElf32, PackLinuxElf64, PackLinuxI386, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, PackDylibPPC32, PackDylibPPC64, PackDylibI386, and PackDylibAMD64.
Definition at line 274 of file p_unix.cpp.
{
    writePackHeader(fo);
    unsigned tmp;
    set_te32(&tmp, overlay_offset);
    fo->write(&tmp, sizeof(tmp));
}
References overlay_offset, Packer::set_te32(), OutputFile::write(), and writePackHeader().
Referenced by pack(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), and PackLinuxI386::pack4().
packed_struct() [1/3]
PackUnix::packed_struct (b_info) inline protected
Definition at line 109 of file p_unix.h.
                          { // 12-byte header before each compressed block
        NE32 sz_unc;  // uncompressed_size
        NE32 sz_cpr;  //   compressed_size
        unsigned char b_method;  // compression algorithm
        unsigned char b_ftid;  // filter id
        unsigned char b_cto8;  // filter parameter
        unsigned char b_extra;
    };
packed_struct() [2/3]
PackUnix::packed_struct (l_info) inline protected
Definition at line 118 of file p_unix.h.
                          { // 12-byte trailer in header for loader
        LE32 l_checksum;
        LE32 l_magic;
        LE16 l_lsize;
        unsigned char l_version;
        unsigned char l_format;
    };
packed_struct() [3/3]
PackUnix::packed_struct (p_info) inline protected
Definition at line 126 of file p_unix.h.
                          { // 12-byte packed program header
        NE32 p_progid;
        NE32 p_filesize;
        NE32 p_blocksize;
    };
packExtent()
void PackUnix::packExtent (const Extent & x, Filter * ft, OutputFile * fo, unsigned hdr_len = 0, unsigned b_extra = 0, bool inhibit_compression_check = false) protected virtual
Definition at line 331 of file p_unix.cpp.
{
    unsigned const init_u_adler = ph.u_adler;
    unsigned const init_c_adler = ph.c_adler;
    MemBuffer hdr_ibuf;
    if (hdr_u_len) {
        hdr_ibuf.alloc(hdr_u_len);
        fi->seek(0, SEEK_SET);
        int l = fi->readx(hdr_ibuf, hdr_u_len);
        (void)l;
    }
    fi->seek(x.offset, SEEK_SET);
    for (off_t rest = x.size; 0 != rest; ) {
        int const filter_strategy = ft ? getStrategy(*ft) : 0;
        int l = fi->readx(ibuf, UPX_MIN(rest, (off_t)blocksize));
        if (l == 0) {
            break;
        }
        rest -= l;
        // Note: compression for a block can fail if the
        //       file is e.g. blocksize + 1 bytes long
        // compress
        ph.c_len = ph.u_len = l;
        ph.overlap_overhead = 0;
        unsigned end_u_adler = 0;
        if (ft) {
            // compressWithFilters() updates u_adler _inside_ compress();
            // that is, AFTER filtering.  We want BEFORE filtering,
            // so that decompression checks the end-to-end checksum.
            end_u_adler = upx_adler32(ibuf, ph.u_len, ph.u_adler);
            ft->buf_len = l;
                // compressWithFilters() requirements?
            ph.filter = 0;
            ph.filter_cto = 0;
            ft->id = 0;
            ft->cto = 0;
            compressWithFilters(ft, OVERHEAD, NULL_cconf, filter_strategy,
                                0, 0, 0, hdr_ibuf, hdr_u_len, inhibit_compression_check);
        }
        else {
            (void) compress(ibuf, ph.u_len, obuf);    // ignore return value
        }
        if (ph.c_len < ph.u_len) {
            const upx_bytep tbuf = nullptr;
            if (ft == nullptr || ft->id == 0) tbuf = ibuf;
            ph.overlap_overhead = OVERHEAD;
            if (!testOverlappingDecompression(obuf, tbuf, ph.overlap_overhead)) {
                // not in-place compressible
                ph.c_len = ph.u_len;
            }
        }
        if (ph.c_len >= ph.u_len) {
            // block is not compressible
            ph.c_len = ph.u_len;
            memcpy(obuf, ibuf, ph.c_len);
            // must update checksum of compressed data
            ph.c_adler = upx_adler32(ibuf, ph.u_len, ph.c_adler);
        }
        // write block sizes
        b_info tmp;
        if (hdr_u_len) {
            unsigned hdr_c_len = 0;
            MemBuffer hdr_obuf;
            hdr_obuf.allocForCompression(hdr_u_len);
            int r = upx_compress(hdr_ibuf, hdr_u_len, hdr_obuf, &hdr_c_len, nullptr,
                ph_forced_method(ph.method), 10, nullptr, nullptr);
            if (r != UPX_E_OK)
                throwInternalError("header compression failed");
            if (hdr_c_len >= hdr_u_len)
                throwInternalError("header compression size increase");
            ph.saved_u_adler = upx_adler32(hdr_ibuf, hdr_u_len, init_u_adler);
            ph.saved_c_adler = upx_adler32(hdr_obuf, hdr_c_len, init_c_adler);
            ph.u_adler = upx_adler32(ibuf, ph.u_len, ph.saved_u_adler);
            ph.c_adler = upx_adler32(obuf, ph.c_len, ph.saved_c_adler);
            end_u_adler = ph.u_adler;
            memset(&tmp, 0, sizeof(tmp));
            set_te32(&tmp.sz_unc, hdr_u_len);
            set_te32(&tmp.sz_cpr, hdr_c_len);
            tmp.b_method = (unsigned char) ph_forced_method(ph.method);
            tmp.b_extra = b_extra;
            fo->write(&tmp, sizeof(tmp));
            total_out += sizeof(tmp);
            b_len += sizeof(b_info);
            fo->write(hdr_obuf, hdr_c_len);
            total_out += hdr_c_len;
            total_in  += hdr_u_len;
            hdr_u_len = 0;  // compress hdr one time only
        }
        memset(&tmp, 0, sizeof(tmp));
        set_te32(&tmp.sz_unc, ph.u_len);
        set_te32(&tmp.sz_cpr, ph.c_len);
        if (ph.c_len < ph.u_len) {
            tmp.b_method = (unsigned char) ph.method;
            if (ft) {
                tmp.b_ftid = (unsigned char) ft->id;
                tmp.b_cto8 = ft->cto;
            }
        }
        tmp.b_extra = b_extra;
        fo->write(&tmp, sizeof(tmp));
        total_out += sizeof(tmp);
        b_len += sizeof(b_info);
        if (ft) {
            ph.u_adler = end_u_adler;
        }
        // write compressed data
        if (ph.c_len < ph.u_len) {
            fo->write(obuf, ph.c_len);
            total_out += ph.c_len;
            // Checks ph.u_adler after decompression, after unfiltering
            verifyOverlappingDecompression(ft);
        }
        else {
            fo->write(ibuf, ph.u_len);
            total_out += ph.u_len;
        }
        total_in += ph.u_len;
    }
}
References MemBuffer::alloc(), MemBuffer::allocForCompression(), b_info::b_cto8, b_info::b_ftid, b_len, b_info::b_method, blocksize, Filter::buf_len, PackHeader::c_adler, PackHeader::c_len, Packer::compress(), Packer::compressWithFilters(), Filter::cto, PackerBase::fi, PackHeader::filter, PackHeader::filter_cto, getStrategy(), Packer::ibuf, Filter::id, memcpy(), memset(), PackHeader::method, NULL_cconf, Packer::obuf, PackUnix::Extent::offset, OVERHEAD, PackHeader::overlap_overhead, PackerBase::ph, ph_forced_method(), InputFile::readx(), PackHeader::saved_c_adler, PackHeader::saved_u_adler, InputFile::seek(), SEEK_SET, Packer::set_te32(), PackUnix::Extent::size, b_info::sz_cpr, b_info::sz_unc, Packer::testOverlappingDecompression(), throwInternalError(), total_in, total_out, PackHeader::u_adler, PackHeader::u_len, upx_adler32(), upx_bytep, upx_compress(), UPX_E_OK, UPX_MIN, Packer::verifyOverlappingDecompression(), and OutputFile::write().
Referenced by PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack3(), and PackLinuxElf64::pack3().
patchLoader()
virtual void PackUnix::patchLoader () protected pure virtual
Implemented in PackLinuxElf32, PackLinuxElf64, PackLinuxI386, PackLinuxI386sh, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, and PackMachBase< MachClass_BE64 >.
patchLoaderChecksum()
void PackUnix::patchLoaderChecksum () protected virtual
Reimplemented in PackLinuxI386, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, and PackMachBase< MachClass_BE64 >.
Definition at line 245 of file p_unix.cpp.
{
    unsigned char *const ptr = getLoader();
    l_info *const lp = &linfo;
    // checksum for loader; also some PackHeader info
    lp->l_magic = UPX_MAGIC_LE32;  // LE32 always
    set_te16(&lp->l_lsize, (upx_uint16_t) lsize);
    lp->l_version = (unsigned char) ph.version;
    lp->l_format  = (unsigned char) ph.format;
    // INFO: lp->l_checksum is currently unused
    set_te32(&lp->l_checksum, upx_adler32(ptr, lsize));
}
References PackHeader::format, Packer::getLoader(), l_info::l_checksum, l_info::l_format, l_info::l_lsize, l_info::l_magic, l_info::l_version, linfo, lsize, PackerBase::ph, ptr, Packer::set_te16(), Packer::set_te32(), upx_adler32(), UPX_MAGIC_LE32, and PackHeader::version.
Referenced by pack3().
unpack()
void PackUnix::unpack (OutputFile * fo) override virtual
Generic Unix unpack().
This code looks much like the one in stub/l_linux.c See notes there.
Implements Packer.
Reimplemented in PackLinuxElf, PackLinuxElf32, PackLinuxElf64, PackLinuxElf32x86interp, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, and PackMachBase< MachClass_BE64 >.
Definition at line 602 of file p_unix.cpp.
{
    b_info bhdr;
    unsigned c_adler = upx_adler32(nullptr, 0);
    unsigned u_adler = upx_adler32(nullptr, 0);
    if (ph.version <= 11) {
        szb_info = sizeof(bhdr.sz_unc) + sizeof(bhdr.sz_cpr);  // old style
    }
    // defaults for ph.version == 8
    unsigned orig_file_size = 0;
    blocksize = 512 * 1024;
    fi->seek(overlay_offset, SEEK_SET);
    if (ph.version > 8)
    {
        p_info hbuf;
        fi->readx(&hbuf, sizeof(hbuf));
        orig_file_size = get_te32(&hbuf.p_filesize);
        blocksize = get_te32(&hbuf.p_blocksize);
        off_t max_inflated = file_size * 273;  // zlib limit (256 + 16 + 1)
        if (max_inflated < orig_file_size
        ||  max_inflated < blocksize
        ||  file_size > (off_t)orig_file_size
        ||  blocksize > orig_file_size) {
            throwCantUnpack("file header corrupted");
        }
    }
    else
    {
        // skip 4 bytes (program id)
        fi->seek(4, SEEK_CUR);
    }
    if ((int)(blocksize + OVERHEAD) < 0)
        throwCantUnpack("blocksize corrupted");
    ibuf.alloc(blocksize + OVERHEAD);
    // decompress blocks
    total_in = 0;
    total_out = 0;
    memset(&bhdr, 0, sizeof(bhdr));
    for (;;)
    {
#define buf ibuf
        int i;
        unsigned sz_unc, sz_cpr;
        fi->readx(&bhdr, szb_info);
        ph.u_len = sz_unc = get_te32(&bhdr.sz_unc);
        ph.c_len = sz_cpr = get_te32(&bhdr.sz_cpr);
        if (sz_unc == 0)                   // uncompressed size 0 -> EOF
        {
            // note: must reload sz_cpr as magic is always stored le32
            sz_cpr = get_le32(&bhdr.sz_cpr);
            if (sz_cpr != UPX_MAGIC_LE32)  // sz_cpr must be h->magic
                throwCompressedDataViolation();
            break;
        }
        // Minimum compressed length: LZMA has 5-byte info header.
        // NRV_d8 has 1-byte initial 8 flag bits, plus end-of-block marker
        // (32 bit look-back offset of all 1s: encoded as 24 pairs of bits
        // {not last, 1} then low 8-bits of 0xff; total: 8 + 2*24 + 8 bits
        // ==> 8 bytes)
        if (sz_unc <= 0 || sz_cpr <= 5u
        ||  sz_cpr > sz_unc || sz_unc > blocksize)
            throwCantUnpack("corrupt b_info %#x %#x", sz_unc, sz_cpr);
        // Compressed output has control bytes such as the 32-bit
        // first flag bits of NRV_d32, the 5-byte info of LZMA, etc.
        // Fuzzers may try sz_cpr shorter than possible.
        // Use some OVERHEAD for safety.
        i = blocksize + OVERHEAD - upx::umax(12u, sz_cpr);
        if (i < 0)
            throwCantUnpack("corrupt b_info %#x %#x", sz_cpr, blocksize);
        fi->readx(buf+i, sz_cpr);
        // update checksum of compressed data
        c_adler = upx_adler32(buf + i, sz_cpr, c_adler);
        // decompress
        if (sz_cpr < sz_unc) {
            decompress(buf+i, buf, false);
            if (0!=bhdr.b_ftid) {
                Filter ft(ph.level);
                ft.init(bhdr.b_ftid);
                ft.cto = bhdr.b_cto8;
                ft.unfilter(buf, sz_unc);
            }
            i = 0;
        }
        // update checksum of uncompressed data
        u_adler = upx_adler32(buf + i, sz_unc, u_adler);
        total_in  += sz_cpr;
        total_out += sz_unc;
        // write block
        if (fo)
            fo->write(buf + i, sz_unc);
#undef buf
    }
    // update header with totals
    ph.c_len = total_in;
    ph.u_len = total_out;
    // all bytes must be written
    if (ph.version > 8 && total_out != orig_file_size)
        throwEOFException();
    // finally test the checksums
    if (ph.c_adler != c_adler || ph.u_adler != u_adler)
        throwChecksumError();
}
References MemBuffer::alloc(), b_info::b_cto8, b_info::b_ftid, blocksize, buf, PackHeader::c_adler, PackHeader::c_len, Filter::cto, Packer::decompress(), PackerBase::fi, PackerBase::file_size, get_le32(), Packer::get_te32(), Packer::ibuf, Filter::init(), PackHeader::level, memset(), OVERHEAD, overlay_offset, p_info::p_blocksize, p_info::p_filesize, PackerBase::ph, InputFile::readx(), InputFile::seek(), SEEK_CUR, SEEK_SET, b_info::sz_cpr, b_info::sz_unc, szb_info, throwCantUnpack(), throwChecksumError(), throwCompressedDataViolation(), throwEOFException(), total_in, total_out, PackHeader::u_adler, PackHeader::u_len, upx::umax(), Filter::unfilter(), upx_adler32(), UPX_MAGIC_LE32, PackHeader::version, and OutputFile::write().
unpackExtent()
unsigned PackUnix::unpackExtent (unsigned wanted, OutputFile * fo, unsigned & c_adler, unsigned & u_adler, bool first_PF_X, int is_rewrite = false) protected virtual
Definition at line 470 of file p_unix.cpp.
{
    b_info hdr; memset(&hdr, 0, sizeof(hdr));
    unsigned inlen = 0; // output index (if-and-only-if peeking)
    while (wanted) {
        fi->readx(&hdr, szb_info);
        int const sz_unc = ph.u_len = get_te32(&hdr.sz_unc);
        int const sz_cpr = ph.c_len = get_te32(&hdr.sz_cpr);
        ph.filter_cto = hdr.b_cto8;
        if (sz_unc == 0 || M_LZMA < hdr.b_method) {
            throwCantUnpack("corrupt b_info");
            break;
        }
        if (sz_unc <= 0 || sz_cpr <= 0)
            throwCantUnpack("corrupt b_info");
        if (sz_cpr > sz_unc || sz_unc > (int)blocksize)
            throwCantUnpack("corrupt b_info");
        // place the input for overlapping de-compression
        int j = inlen + sz_unc + OVERHEAD - sz_cpr;
        if (ibuf.getSize() < (unsigned)(j + sz_cpr)) {
            throwCantUnpack("corrupt b_info");
        }
        fi->readx(ibuf+j, sz_cpr);
        total_in += sz_cpr;
        // update checksum of compressed data
        c_adler = upx_adler32(ibuf + j, sz_cpr, c_adler);
        if (sz_cpr < sz_unc) { // block was compressed
            decompress(ibuf+j, ibuf+inlen, false);
            if (12==szb_info) { // modern per-block filter
                if (hdr.b_ftid) {
                    Filter ft(ph.level);  // FIXME: ph.level for b_info?
                    ft.init(hdr.b_ftid, 0);
                    ft.cto = hdr.b_cto8;
                    ft.unfilter(ibuf+inlen, sz_unc);
                }
            }
            else { // ancient per-file filter
                if (first_PF_X) { // Elf32_Ehdr is never filtered
                    first_PF_X = false;  // but everything else might be
                }
                else if (ph.filter) {
                    Filter ft(ph.level);
                    ft.init(ph.filter, 0);
                    ft.cto = (unsigned char) ph.filter_cto;
                    ft.unfilter(ibuf+inlen, sz_unc);
                }
            }
        }
        else if (sz_cpr == sz_unc) { // slide literal (non-compressible) block
            memmove(&ibuf[inlen], &ibuf[j], sz_unc);
        }
        // update checksum of uncompressed data
        u_adler = upx_adler32(ibuf + inlen, sz_unc, u_adler);
        // write block
        if (fo) {
            if (is_rewrite) {
                fo->rewrite(ibuf, sz_unc);
            }
            else {
                fo->write(ibuf, sz_unc);
                total_out += sz_unc;
            }
        }
        else if (is_rewrite < 0) { // append to &ibuf[inlen]
            inlen += sz_unc;  // accounting; data is already there
            if (wanted <= (unsigned)sz_unc)  // done
                break;
        }
        else if (wanted < (unsigned)sz_unc) // mismatched end-of-block
            throwCantUnpack("corrupt b_info");
        else { // "upx -t": (!fo && !(is_rewrite < 0))
            // No output.
        }
        wanted -= sz_unc;
    }
    return inlen;
}
References b_info::b_cto8, b_info::b_ftid, b_info::b_method, blocksize, PackHeader::c_len, Filter::cto, Packer::decompress(), PackerBase::fi, PackHeader::filter, PackHeader::filter_cto, Packer::get_te32(), MemBuffer::getSize(), Packer::ibuf, Filter::init(), PackHeader::level, M_LZMA, memmove(), memset(), OVERHEAD, PackerBase::ph, InputFile::readx(), OutputFile::rewrite(), b_info::sz_cpr, b_info::sz_unc, szb_info, throwCantUnpack(), total_in, total_out, PackHeader::u_len, Filter::unfilter(), upx_adler32(), and OutputFile::write().
Referenced by PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), and PackLinuxElf32x86interp::unpack().
updateLoader()
virtual void PackUnix::updateLoader (OutputFile *) protected pure virtual
Implemented in PackLinuxElf32armLe, PackLinuxElf32armBe, PackLinuxElf32mipseb, PackLinuxElf32mipsel, PackLinuxI386, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, PackLinuxElf32, and PackLinuxElf64.
Referenced by pack3().
writePackHeader()
void PackUnix::writePackHeader (OutputFile * fo) protected virtual
Definition at line 93 of file p_unix.cpp.
{
    unsigned char buf[32];
    memset(buf, 0, sizeof(buf));
    const int hsize = ph.getPackHeaderSize();
    assert((unsigned)hsize <= sizeof(buf));
    // note: magic constants are always le32
    set_le32(buf+0, UPX_MAGIC_LE32);
    set_le32(buf+4, UPX_MAGIC2_LE32);
    checkPatch(nullptr, 0, 0, 0);  // reset
    patchPackHeader(buf, hsize);
    checkPatch(nullptr, 0, 0, 0);  // reset
    fo->write(buf, hsize);
}
References buf, Packer::checkPatch(), PackHeader::getPackHeaderSize(), memset(), Packer::patchPackHeader(), PackerBase::ph, set_le32(), UPX_MAGIC2_LE32, UPX_MAGIC_LE32, and OutputFile::write().
Referenced by pack4().
Member Data Documentation
b_len
unsigned PackUnix::b_len protected
Definition at line 103 of file p_unix.h.
Referenced by pack(), pack2(), and packExtent().
blocksize
unsigned PackUnix::blocksize protected
Definition at line 94 of file p_unix.h.
Referenced by PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386sh::getShellName(), pack(), pack2(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), packExtent(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), unpack(), and unpackExtent().
exetype
int PackUnix::exetype protected
Definition at line 93 of file p_unix.h.
Referenced by PackLinuxI386::buildLoader(), PackBSDI386::buildLoader(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), canPack(), PackLinuxElf32::canPackOSABI(), and PackLinuxI386sh::getShellName().
linfo
struct l_info PackUnix::linfo protected
Definition at line 132 of file p_unix.h.
Referenced by PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxElf32::packed_struct(), PackLinuxElf64::packed_struct(), PackLinuxI386::packed_struct(), patchLoaderChecksum(), PackLinuxElf32::unpack(), and PackLinuxElf64::unpack().
loader
MemBuffer PackUnix::loader protected
Definition at line 98 of file p_unix.h.
lsize
int PackUnix::lsize protected
Definition at line 99 of file p_unix.h.
Referenced by PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), pack3(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf32x86interp::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), patchLoaderChecksum(), PackLinuxI386::patchLoaderChecksum(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), and PackLinuxElf64::unpack().
methods_used
unsigned PackUnix::methods_used protected
Definition at line 104 of file p_unix.h.
Referenced by PackLinuxElf32::buildLinuxLoader(), and PackLinuxElf64::buildLinuxLoader().
overlay_offset
unsigned PackUnix::overlay_offset protected
Definition at line 96 of file p_unix.h.
Referenced by canUnpack(), find_overlay_offset(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf::pack3(), pack4(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxI386::pack4(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), and unpack().
progid
unsigned PackUnix::progid protected
Definition at line 95 of file p_unix.h.
Referenced by PackLinuxI386::buildLoader(), PackBSDI386::buildLoader(), pack(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxI386::pack1(), and PackBSDI386::pack1().
pt_dynamic
MemBuffer PackUnix::pt_dynamic protected
Definition at line 100 of file p_unix.h.
saved_opt_android_shlib
unsigned PackUnix::saved_opt_android_shlib protected
Definition at line 106 of file p_unix.h.
Referenced by PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackUnix(), and ~PackUnix().
sz_dynamic
int PackUnix::sz_dynamic protected
Definition at line 101 of file p_unix.h.
szb_info
unsigned PackUnix::szb_info protected
Definition at line 105 of file p_unix.h.
Referenced by PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), unpack(), and unpackExtent().
total_in
unsigned PackUnix::total_in protected
Definition at line 91 of file p_unix.h.
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), pack2(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), packExtent(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), unpack(), and unpackExtent().
total_out
unsigned PackUnix::total_out protected
Definition at line 91 of file p_unix.h.
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), pack2(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), packExtent(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), unpack(), and unpackExtent().
The documentation for this class was generated from the following files:
src/p_unix.h
src/p_unix.cpp