My Project: MemBufferBase< T > Class Template Reference
MemBufferBase< T > Class Template Reference
MemBufferBase provides some base functionality for treating a MemBuffer as a pointer.
#include <membuffer.h>
Public Types
typedef T element_type
typedef std::add_lvalue_reference< T >::type reference
typedef std::add_pointer< T >::type pointer
typedef unsigned size_type
typedef pointer iterator
typedef std::add_pointer< constT >::type const_iterator
Public Member Functions
MemBufferBase () noexcept
forceinline ~MemBufferBase () noexcept
operator pointer () const noexcept
reference operator[] (ptrdiff_t i) const may_throw
reference operator* () const DELETED_FUNCTION
pointer operator-> () const DELETED_FUNCTION
iterator begin () const may_throw
const_iterator cbegin () const may_throw
iterator end () const may_throw
const_iterator cend () const may_throw
template<class U >
std::enable_if< std::is_integral< U >::value, pointer >::type operator+ (U n) const may_throw
pointer raw_ptr () const noexcept
size_type raw_size_in_bytes () const noexcept
pointer raw_bytes (size_t bytes) const may_throw
Protected Attributes
pointer ptr
size_type size_in_bytes
Static Protected Attributes
static const size_t element_size = sizeof(element_type)
Private Member Functions
template<class U >
std::enable_if< std::is_integral< U >::value, pointer >::type operator- (U n) const DELETED_FUNCTION
Detailed Description
template<class T>
class MemBufferBase< T >
MemBufferBase provides some base functionality for treating a MemBuffer as a pointer.
Definition at line 39 of file membuffer.h.
Member Typedef Documentation
const_iterator
template<class T > typedef std::add_pointer<constT>::type MemBufferBase< T >::const_iterator
Definition at line 46 of file membuffer.h.
element_type
template<class T > typedef T MemBufferBase< T >::element_type
Definition at line 41 of file membuffer.h.
iterator
template<class T > typedef pointer MemBufferBase< T >::iterator
Definition at line 45 of file membuffer.h.
pointer
template<class T > typedef std::add_pointer<T>::type MemBufferBase< T >::pointer
Definition at line 43 of file membuffer.h.
reference
template<class T > typedef std::add_lvalue_reference<T>::type MemBufferBase< T >::reference
Definition at line 42 of file membuffer.h.
size_type
template<class T > typedef unsigned MemBufferBase< T >::size_type
Definition at line 44 of file membuffer.h.
Constructor & Destructor Documentation
MemBufferBase()
template<class T > MemBufferBase< T >::MemBufferBase () inline explicit noexcept
Definition at line 55 of file membuffer.h.
: ptr(nullptr), size_in_bytes(0) {}
~MemBufferBase()
template<class T > forceinline MemBufferBase< T >::~MemBufferBase () inline noexcept
Definition at line 56 of file membuffer.h.
{}
Member Function Documentation
begin()
template<class T > iterator MemBufferBase< T >::begin () const inline
Definition at line 74 of file membuffer.h.
{
        if very_unlikely (ptr == nullptr)
            throwCantPack("MemBuffer begin() unexpected NULL ptr");
        return ptr;
    }
References MemBufferBase< T >::ptr, throwCantPack(), and very_unlikely.
Referenced by TEST_CASE().
cbegin()
template<class T > const_iterator MemBufferBase< T >::cbegin () const inline
Definition at line 79 of file membuffer.h.
{
        if very_unlikely (ptr == nullptr)
            throwCantPack("MemBuffer cbegin() unexpected NULL ptr");
        return ptr;
    }
References MemBufferBase< T >::ptr, throwCantPack(), and very_unlikely.
Referenced by TEST_CASE().
cend()
template<class T > const_iterator MemBufferBase< T >::cend () const inline
Definition at line 89 of file membuffer.h.
{
        if very_unlikely (ptr == nullptr)
            throwCantPack("MemBuffer cend() unexpected NULL ptr");
        return ptr + size_in_bytes / element_size;
    }
References MemBufferBase< T >::element_size, MemBufferBase< T >::ptr, MemBufferBase< T >::size_in_bytes, throwCantPack(), and very_unlikely.
Referenced by TEST_CASE().
end()
template<class T > iterator MemBufferBase< T >::end () const inline
Definition at line 84 of file membuffer.h.
{
        if very_unlikely (ptr == nullptr)
            throwCantPack("MemBuffer end() unexpected NULL ptr");
        return ptr + size_in_bytes / element_size;
    }
References MemBufferBase< T >::element_size, MemBufferBase< T >::ptr, MemBufferBase< T >::size_in_bytes, throwCantPack(), and very_unlikely.
Referenced by TEST_CASE().
operator pointer()
template<class T > MemBufferBase< T >::operator pointer () const inline noexcept
Definition at line 60 of file membuffer.h.
{ return ptr; }
References MemBufferBase< T >::ptr.
operator*()
template<class T > reference MemBufferBase< T >::operator* () const
operator+()
template<class T > template<class U > std::enable_if< std::is_integral< U >::value, pointer >::type MemBufferBase< T >::operator+ (U n) const inline
Definition at line 97 of file membuffer.h.
                  {
        size_t bytes = mem_size(element_size, n); // check mem_size
        return raw_bytes(bytes) + n;              // and check bytes
    }
References MemBufferBase< T >::element_size, mem_size(), n, and MemBufferBase< T >::raw_bytes().
operator-()
template<class T > template<class U > std::enable_if< std::is_integral< U >::value, pointer >::type MemBufferBase< T >::operator- (U n) const private
operator->()
template<class T > pointer MemBufferBase< T >::operator-> () const
operator[]()
template<class T > reference MemBufferBase< T >::operator[] (ptrdiff_t i) const inline
Definition at line 63 of file membuffer.h.
{
        // NOTE: &array[SIZE] is *not* legal for containers like std::vector and MemBuffer !
        if very_unlikely (i < 0 || mem_size(element_size, i) + element_size > size_in_bytes)
            throwCantPack("MemBuffer invalid array index %td (%u bytes)", i, size_in_bytes);
        return ptr[i];
    }
References MemBufferBase< T >::element_size, mem_size(), MemBufferBase< T >::ptr, MemBufferBase< T >::size_in_bytes, throwCantPack(), and very_unlikely.
raw_bytes()
template<class T > pointer MemBufferBase< T >::raw_bytes (size_t bytes) const inline
Definition at line 112 of file membuffer.h.
{
        if (bytes > 0) {
            if very_unlikely (ptr == nullptr)
                throwCantPack("MemBuffer raw_bytes unexpected NULL ptr");
            if very_unlikely (bytes > size_in_bytes)
                throwCantPack("MemBuffer raw_bytes invalid size");
        }
        return ptr;
    }
References MemBufferBase< T >::ptr, MemBufferBase< T >::size_in_bytes, throwCantPack(), and very_unlikely.
Referenced by MemBufferBase< T >::operator+(), raw_bytes(), and raw_index_bytes().
raw_ptr()
template<class T > pointer MemBufferBase< T >::raw_ptr () const inline noexcept
Definition at line 109 of file membuffer.h.
{ return ptr; }
References MemBufferBase< T >::ptr.
Referenced by TEST_CASE().
raw_size_in_bytes()
template<class T > size_type MemBufferBase< T >::raw_size_in_bytes () const inline noexcept
Definition at line 110 of file membuffer.h.
{ return size_in_bytes; }
References MemBufferBase< T >::size_in_bytes.
Referenced by TEST_CASE().
Member Data Documentation
element_size
template<class T > const size_t MemBufferBase< T >::element_size = sizeof(element_type) static protected
Definition at line 48 of file membuffer.h.
Referenced by MemBufferBase< T >::cend(), MemBufferBase< T >::end(), MemBufferBase< T >::operator+(), and MemBufferBase< T >::operator[]().
ptr
template<class T > pointer MemBufferBase< T >::ptr protected
Definition at line 51 of file membuffer.h.
Referenced by MemBufferBase< T >::begin(), MemBufferBase< T >::cbegin(), MemBufferBase< T >::cend(), MemBufferBase< T >::end(), MemBufferBase< T >::operator pointer(), MemBufferBase< T >::operator[](), MemBufferBase< T >::raw_bytes(), and MemBufferBase< T >::raw_ptr().
size_in_bytes
template<class T > size_type MemBufferBase< T >::size_in_bytes protected
Definition at line 52 of file membuffer.h.
Referenced by MemBufferBase< T >::cend(), MemBufferBase< T >::end(), MemBufferBase< T >::operator[](), MemBufferBase< T >::raw_bytes(), and MemBufferBase< T >::raw_size_in_bytes().
The documentation for this class was generated from the following file:
src/util/membuffer.h