My Project: ElfLinkerMipsLE Class Reference
ElfLinkerMipsLE Class Reference final
#include <linker.h>
Protected Member Functions
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type) override
Protected Member Functions inherited from ElfLinker
void preprocessSections (char *start, char const *end)
void preprocessSymbols (char *start, char const *end)
void preprocessRelocations (char *start, char const *end)
Section * findSection (const char *name, bool fatal=true) const
Symbol * addSymbol (const char *name, const char *section, upx_uint64_t offset)
Relocation * addRelocation (const char *section, unsigned off, const char *type, const char *symbol, upx_uint64_t add)
void relocate ()
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type)
Private Types
typedef ElfLinker super
Additional Inherited Members
Public Member Functions inherited from ElfLinker
ElfLinker (const N_BELE_RTP::AbstractPolicy *b=&N_BELE_RTP::le_policy) noexcept
ElfLinker.
virtual ~ElfLinker () noexcept
void init (const void *pdata, int plen, unsigned pxtra=0)
int addLoader (const char *sname)
void addLoader (const char *s, va_list ap)
void addLoaderVA (const char *s,...)
Section * addSection (const char *sname, const void *sdata, int slen, unsigned p2align)
int getSection (const char *sname, int *slen=nullptr) const
int getSectionSize (const char *sname) const
byte * getLoader (int *llen=nullptr) const
void defineSymbol (const char *name, upx_uint64_t value)
Symbol * findSymbol (const char *name, bool fatal=true) const
upx_uint64_t getSymbolOffset (const char *) const
void dumpSymbol (const Symbol *, unsigned flags, FILE *fp) const
void dumpSymbols (unsigned flags=0, FILE *fp=nullptr) const
void alignWithByte (unsigned len, byte b)
virtual void alignCode (unsigned len)
virtual void alignData (unsigned len)
void defineSymbol (const char *name, int value)
void defineSymbol (const char *name, unsigned value)
void defineSymbol (const char *name, unsigned long value)
Public Attributes inherited from ElfLinker
const N_BELE_RTP::AbstractPolicy *const bele
Protected Attributes inherited from ElfLinker
byte * input = nullptr
int inputlen = 0
byte * output = nullptr
int outputlen = 0
unsigned output_capacity = 0
Section * head = nullptr
Section * tail = nullptr
Section ** sections = nullptr
Symbol ** symbols = nullptr
Relocation ** relocations = nullptr
unsigned nsections = 0
unsigned nsections_capacity = 0
unsigned nsymbols = 0
unsigned nsymbols_capacity = 0
unsigned nrelocations = 0
unsigned nrelocations_capacity = 0
bool reloc_done = false
Detailed Description
Definition at line 206 of file linker.h.
Member Typedef Documentation
super
typedef ElfLinker ElfLinkerMipsLE::super private
Definition at line 207 of file linker.h.
Member Function Documentation
relocate1()
void ElfLinkerMipsLE::relocate1 (const Relocation * rel, byte * location, upx_uint64_t value, const char * type) override protected virtual
Reimplemented from ElfLinker.
Definition at line 747 of file linker.cpp.
{
#define MIPS_HI(a)   (((a) >> 16) + (((a) &0x8000) >> 15))
#define MIPS_LO(a)   ((a) &0xffff)
#define MIPS_PC16(a) ((a) >> 2)
#define MIPS_PC26(a) (((a) &0x0fffffff) >> 2)
    if (strcmp(type, "R_MIPS_HI16") == 0)
        set_le16(location, get_le16(location) + MIPS_HI(value));
    else if (strcmp(type, "R_MIPS_LO16") == 0)
        set_le16(location, get_le16(location) + MIPS_LO(value));
    else if (strcmp(type, "R_MIPS_PC16") == 0) {
        value -= rel->section->offset + rel->offset;
        set_le16(location, get_le16(location) + MIPS_PC16(value));
    } else if (strcmp(type, "R_MIPS_26") == 0)
        set_le32(location, get_le32(location) + MIPS_PC26(value));
    else if (strcmp(type, "R_MIPS_32") == 0)
        set_le32(location, get_le32(location) + value);
    else
        super::relocate1(rel, location, value, type);
#undef MIPS_HI
#undef MIPS_LO
#undef MIPS_PC16
#undef MIPS_PC26
}
References get_le16(), get_le32(), MIPS_HI, MIPS_LO, MIPS_PC16, MIPS_PC26, ElfLinker::Section::offset, ElfLinker::Relocation::offset, ElfLinker::Relocation::section, set_le16(), set_le32(), and strcmp().
The documentation for this class was generated from the following files:
src/linker.h
src/linker.cpp