My Project: PeFile::ImportLinker Class Reference
PeFile::ImportLinker Class Reference final
Classes
struct TStr
Public Member Functions
ImportLinker (unsigned thunk_size_)
template<typename C >
void add_import (const C *dll, unsigned ordinal)
template<typename C1 , typename C2 >
void add_import (const C1 *dll, const C2 *proc)
unsigned build ()
void relocate_import (unsigned myimport)
template<typename C1 , typename C2 >
upx_uint64_t getAddress (const C1 *dll, const C2 *proc) const
template<typename C >
upx_uint64_t getAddress (const C *dll, unsigned ordinal) const
template<typename C >
upx_uint64_t getAddress (const C *dll) const
template<typename C >
bool hasDll (const C *dll) const
Public Member Functions inherited from ElfLinker
ElfLinker (const N_BELE_RTP::AbstractPolicy *b=&N_BELE_RTP::le_policy) noexcept
ElfLinker.
virtual ~ElfLinker () noexcept
void init (const void *pdata, int plen, unsigned pxtra=0)
int addLoader (const char *sname)
void addLoader (const char *s, va_list ap)
void addLoaderVA (const char *s,...)
Section * addSection (const char *sname, const void *sdata, int slen, unsigned p2align)
int getSection (const char *sname, int *slen=nullptr) const
int getSectionSize (const char *sname) const
byte * getLoader (int *llen=nullptr) const
void defineSymbol (const char *name, upx_uint64_t value)
Symbol * findSymbol (const char *name, bool fatal=true) const
upx_uint64_t getSymbolOffset (const char *) const
void dumpSymbol (const Symbol *, unsigned flags, FILE *fp) const
void dumpSymbols (unsigned flags=0, FILE *fp=nullptr) const
void alignWithByte (unsigned len, byte b)
virtual void alignCode (unsigned len)
virtual void alignData (unsigned len)
void defineSymbol (const char *name, int value)
void defineSymbol (const char *name, unsigned value)
void defineSymbol (const char *name, unsigned long value)
Private Types
enum {
descriptor_id = 'D' , thunk_id , dll_name_id , proc_name_id ,
ordinal_id , thunk_separator_first , thunk_separator , thunk_separator_last ,
procname_separator
}
Private Member Functions
void add_import (const char *dll, const char *proc, unsigned ordinal)
virtual void alignCode (unsigned len) override
const Section * getThunk (const char *dll, const char *proc, char tsep) const
Static Private Member Functions
static void encode_name (SPAN_P(const char) name, SPAN_S(char) buf)
static char * name_for_dll (const char *dll, char first_char)
static char * name_for_proc (const char *dll, const char *proc, char first_char, char separator)
static int __acc_cdecl_qsort compare (const void *aa, const void *bb)
Private Attributes
unsigned thunk_size
Static Private Attributes
static const char zeros [sizeof(import_desc)] = {0}
Additional Inherited Members
Public Attributes inherited from ElfLinker
const N_BELE_RTP::AbstractPolicy *const bele
Protected Member Functions inherited from ElfLinkerAMD64
virtual void alignCode (unsigned len) override
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type) override
ElfLinker arch subclasses FIXME: add more displacement overflow checks FIXME: add support for our special "ignore_reloc_overflow" section.
Protected Member Functions inherited from ElfLinker
void preprocessSections (char *start, char const *end)
void preprocessSymbols (char *start, char const *end)
void preprocessRelocations (char *start, char const *end)
Section * findSection (const char *name, bool fatal=true) const
Symbol * addSymbol (const char *name, const char *section, upx_uint64_t offset)
Relocation * addRelocation (const char *section, unsigned off, const char *type, const char *symbol, upx_uint64_t add)
void relocate ()
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type)
Protected Attributes inherited from ElfLinker
byte * input = nullptr
int inputlen = 0
byte * output = nullptr
int outputlen = 0
unsigned output_capacity = 0
Section * head = nullptr
Section * tail = nullptr
Section ** sections = nullptr
Symbol ** symbols = nullptr
Relocation ** relocations = nullptr
unsigned nsections = 0
unsigned nsections_capacity = 0
unsigned nsymbols = 0
unsigned nsymbols_capacity = 0
unsigned nrelocations = 0
unsigned nrelocations_capacity = 0
bool reloc_done = false
Detailed Description
Definition at line 709 of file pefile.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
descriptor_id
thunk_id
dll_name_id
proc_name_id
ordinal_id
thunk_separator_first
thunk_separator
thunk_separator_last
procname_separator
Definition at line 759 of file pefile.cpp.
         {
        // the order of identifiers is very important below!!
        descriptor_id = 'D',
        thunk_id,
        dll_name_id,
        proc_name_id,
        ordinal_id,
        thunk_separator_first,
        thunk_separator,
        thunk_separator_last,
        procname_separator,
    };
Constructor & Destructor Documentation
ImportLinker()
PeFile::ImportLinker::ImportLinker (unsigned thunk_size_) inline explicit
Definition at line 840 of file pefile.cpp.
                                                : thunk_size(thunk_size_) {
        assert(thunk_size == 4 || thunk_size == 8);
        addSection("*UND*", nullptr, 0, 0);
        addSymbol("*UND*", "*UND*", 0);
        addSection("*ZSTART", nullptr, 0, 0);
        addSymbol("*ZSTART", "*ZSTART", 0);
        Section *s = addSection("Dzero", zeros, sizeof(import_desc), 0);
        assert(s->name[0] == descriptor_id);
        // one trailing 00 byte after the last proc name
        addSection("Zzero", zeros, 1, 0);
    }
References ElfLinker::addSection(), ElfLinker::addSymbol(), descriptor_id, ElfLinker::Section::name, thunk_size, and zeros.
Member Function Documentation
add_import() [1/3]
template<typename C > void PeFile::ImportLinker::add_import (const C * dll, unsigned ordinal) inline
Definition at line 854 of file pefile.cpp.
{
        ACC_COMPILE_TIME_ASSERT(sizeof(C) == 1) // "char" or "byte"
        assert(ordinal < 0x10000);
        char ord[1 + 5 + 1];
        upx_safe_snprintf(ord, sizeof(ord), "%c%05u", ordinal_id, ordinal);
        add_import((const char *) dll, ordinal ? ord : nullptr, ordinal);
    }
References ACC_COMPILE_TIME_ASSERT, add_import(), C, ordinal_id, and upx_safe_snprintf().
add_import() [2/3]
template<typename C1 , typename C2 > void PeFile::ImportLinker::add_import (const C1 * dll, const C2 * proc) inline
Definition at line 863 of file pefile.cpp.
{
        ACC_COMPILE_TIME_ASSERT(sizeof(C1) == 1) // "char" or "byte"
        ACC_COMPILE_TIME_ASSERT(sizeof(C2) == 1) // "char" or "byte"
        assert(proc);
        add_import((const char *) dll, (const char *) proc, 0);
    }
References ACC_COMPILE_TIME_ASSERT, and add_import().
add_import() [3/3]
void PeFile::ImportLinker::add_import (const char * dll, const char * proc, unsigned ordinal) inline private
Definition at line 775 of file pefile.cpp.
{
        TStr sdll(name_for_dll(dll, dll_name_id));
        TStr desc_name(name_for_dll(dll, descriptor_id));
        char tsep = thunk_separator;
        if (findSection(sdll, false) == nullptr) {
            tsep = thunk_separator_first;
            addSection(sdll, dll, strlen(dll) + 1, 0); // name of the dll
            addSymbol(sdll, sdll, 0);
            addSection(desc_name, zeros, sizeof(zeros), 0); // descriptor
            addRelocation(desc_name, offsetof(import_desc, dllname), "R_X86_64_32", sdll, 0);
        }
        TStr thunk(proc == nullptr ? name_for_dll(dll, thunk_id)
                                   : name_for_proc(dll, proc, thunk_id, tsep));
        if (findSection(thunk, false) != nullptr)
            return; // we already have this dll/proc
        addSection(thunk, zeros, thunk_size, 0);
        addSymbol(thunk, thunk, 0);
        if (tsep == thunk_separator_first) {
            addRelocation(desc_name, offsetof(import_desc, iat), "R_X86_64_32", thunk, 0);
            TStr last_thunk(name_for_proc(dll, "X", thunk_id, thunk_separator_last));
            addSection(last_thunk, zeros, thunk_size, 0);
        }
        const char *reltype = thunk_size == 4 ? "R_X86_64_32" : "R_X86_64_64";
        if (ordinal != 0u) {
            addRelocation(thunk, 0, reltype, "*UND*", ordinal | (1ull << (thunk_size * 8 - 1)));
        } else if (proc != nullptr) {
            TStr proc_name(name_for_proc(dll, proc, proc_name_id, procname_separator));
            addSection(proc_name, zeros, 2, 1); // 2 bytes of word aligned "hint"
            addSymbol(proc_name, proc_name, 0);
            addRelocation(thunk, 0, reltype, proc_name, 0);
            strcat(proc_name, "X");
            addSection(proc_name, proc, strlen(proc), 0); // the name of the symbol
        } else
            infoWarning("empty import: %s", dll);
    }
References ElfLinker::addRelocation(), ElfLinker::addSection(), ElfLinker::addSymbol(), descriptor_id, dll_name_id, ElfLinker::findSection(), infoWarning(), name_for_dll(), name_for_proc(), proc_name_id, procname_separator, strlen, thunk_id, thunk_separator, thunk_separator_first, thunk_separator_last, thunk_size, and zeros.
Referenced by add_import(), PeFile::addKernelImport(), and PeFile::processImports0().
alignCode()
virtual void PeFile::ImportLinker::alignCode (unsigned len) inline override private virtual
Reimplemented from ElfLinkerAMD64.
Definition at line 830 of file pefile.cpp.
{ alignWithByte(len, 0); }
References ElfLinker::alignWithByte().
build()
unsigned PeFile::ImportLinker::build () inline
Definition at line 870 of file pefile.cpp.
                     {
        assert(output == nullptr);
        int osize = 4 + 2 * nsections; // upper limit for alignments
        for (unsigned ic = 0; ic < nsections; ic++)
            osize += sections[ic]->size;
        output_capacity = osize;
        output = New(byte, output_capacity);
        outputlen = 0;
        // sort the sections by name before adding them all
        // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
        upx_qsort(sections, nsections, sizeof(sections[0]), ImportLinker::compare);
        for (unsigned ic = 0; ic < nsections; ic++)
            addLoader(sections[ic]->name);
        addLoader("+40D");
        assert(outputlen <= osize);
        // OutputFile::dump("il0.imp", output, outputlen);
        return outputlen;
    }
References ElfLinker::addLoader(), compare(), New, ElfLinker::nsections, ElfLinker::output, ElfLinker::output_capacity, ElfLinker::outputlen, ElfLinker::sections, size(), and upx_qsort.
Referenced by PeFile::processImports0().
compare()
static int __acc_cdecl_qsort PeFile::ImportLinker::compare (const void * aa, const void * bb) inline static private
Definition at line 817 of file pefile.cpp.
{
        const Section *a = *(const Section *const *) aa;
        const Section *b = *(const Section *const *) bb;
        if (a->sort_id == b->sort_id) // identical object, poor qsort() implementation
            return 0;
        int rc = strcmp(a->name, b->name);
        if (rc != 0)
            return rc;
        // What could remain?
        // make sort order deterministic
        return a->sort_id < b->sort_id ? -1 : 1;
    }
References b, ElfLinker::Section::name, ElfLinker::Section::sort_id, and strcmp().
Referenced by build().
encode_name()
static void PeFile::ImportLinker::encode_name (SPAN_P(const char) name, SPAN_S(char) buf) inline static private
Definition at line 722 of file pefile.cpp.
{
        while (*name) {
            *buf++ = 'a' + ((*name >> 4) & 0xf);
            *buf++ = 'a' + (*name & 0xf);
            name++;
        }
        *buf = 0;
    }
References buf.
Referenced by name_for_dll(), and name_for_proc().
getAddress() [1/3]
template<typename C > upx_uint64_t PeFile::ImportLinker::getAddress (const C * dll) const inline
Definition at line 927 of file pefile.cpp.
{
        ACC_COMPILE_TIME_ASSERT(sizeof(C) == 1) // "char" or "byte"
        TStr sdll(name_for_dll((const char *) dll, dll_name_id));
        return findSection(sdll, true)->offset;
    }
References ACC_COMPILE_TIME_ASSERT, C, dll_name_id, ElfLinker::findSection(), name_for_dll(), and ElfLinker::Section::offset.
getAddress() [2/3]
template<typename C > upx_uint64_t PeFile::ImportLinker::getAddress (const C * dll, unsigned ordinal) const inline
Definition at line 913 of file pefile.cpp.
{
        ACC_COMPILE_TIME_ASSERT(sizeof(C) == 1) // "char" or "byte"
        assert(ordinal > 0 && ordinal < 0x10000);
        char ord[1 + 5 + 1];
        upx_safe_snprintf(ord, sizeof(ord), "%c%05u", ordinal_id, ordinal);
        const Section *s = getThunk((const char *) dll, ord, thunk_separator_first);
        if (s == nullptr)
            s = getThunk((const char *) dll, ord, thunk_separator);
        if (s == nullptr)
            throwInternalError("entry not found");
        return s->offset;
    }
References ACC_COMPILE_TIME_ASSERT, C, getThunk(), ElfLinker::Section::offset, ordinal_id, throwInternalError(), thunk_separator, thunk_separator_first, and upx_safe_snprintf().
getAddress() [3/3]
template<typename C1 , typename C2 > upx_uint64_t PeFile::ImportLinker::getAddress (const C1 * dll, const C2 * proc) const inline
Definition at line 901 of file pefile.cpp.
{
        ACC_COMPILE_TIME_ASSERT(sizeof(C1) == 1) // "char" or "byte"
        ACC_COMPILE_TIME_ASSERT(sizeof(C2) == 1) // "char" or "byte"
        const Section *s = getThunk((const char *) dll, (const char *) proc, thunk_separator_first);
        if (s == nullptr)
            s = getThunk((const char *) dll, (const char *) proc, thunk_separator);
        if (s == nullptr)
            throwInternalError("entry not found");
        return s->offset;
    }
References ACC_COMPILE_TIME_ASSERT, getThunk(), ElfLinker::Section::offset, throwInternalError(), thunk_separator, and thunk_separator_first.
Referenced by PeFile::ilinkerGetAddress(), and PeFile::processImports0().
getThunk()
const Section * PeFile::ImportLinker::getThunk (const char * dll, const char * proc, char tsep) const inline private
Definition at line 832 of file pefile.cpp.
{
        assert(dll);
        assert(proc);
        TStr thunk(name_for_proc(dll, proc, thunk_id, tsep));
        return findSection(thunk, false);
    }
References ElfLinker::findSection(), name_for_proc(), and thunk_id.
Referenced by getAddress().
hasDll()
template<typename C > bool PeFile::ImportLinker::hasDll (const C * dll) const inline
Definition at line 934 of file pefile.cpp.
{
        ACC_COMPILE_TIME_ASSERT(sizeof(C) == 1) // "char" or "byte"
        TStr sdll(name_for_dll((const char *) dll, dll_name_id));
        return findSection(sdll, false) != nullptr;
    }
References ACC_COMPILE_TIME_ASSERT, C, dll_name_id, ElfLinker::findSection(), and name_for_dll().
Referenced by PeFile::processImports0().
name_for_dll()
static char * PeFile::ImportLinker::name_for_dll (const char * dll, char first_char) inline static private
Definition at line 731 of file pefile.cpp.
{
        assert(dll != nullptr);
        const unsigned l = strlen(dll);
        assert(l > 0);
        const unsigned new_size = 1 + 3 * l + 1;
        char *const new_name = New(char, new_size);
        SPAN_S_VAR(char, const name, new_name, new_size);
        name[0] = first_char;
        SPAN_S_VAR(char, n, name + (1 + 2 * l));
        do {
            *n++ = tolower((uchar) *dll);
        } while (*dll++);
        encode_name(new_name + (1 + 2 * l), name + 1);
        return new_name;
    }
References encode_name(), n, New, SPAN_S_VAR, and strlen.
Referenced by add_import(), getAddress(), hasDll(), and name_for_proc().
name_for_proc()
static char * PeFile::ImportLinker::name_for_proc (const char * dll, const char * proc, char first_char, char separator) inline static private
Definition at line 747 of file pefile.cpp.
{
        const unsigned new_size = 1 + 2 * strlen(dll) + 1 + 2 * strlen(proc) + 1 + 1;
        TStr dll_name(name_for_dll(dll, first_char));
        char *const new_name = New(char, new_size);
        SPAN_S_VAR(char, const name, new_name, new_size);
        upx_safe_snprintf(new_name, new_size, "%s%c", (const char *) dll_name, separator);
        encode_name(proc, name + strlen(name));
        return new_name;
    }
References encode_name(), name_for_dll(), New, SPAN_S_VAR, strlen, and upx_safe_snprintf().
Referenced by add_import(), and getThunk().
relocate_import()
void PeFile::ImportLinker::relocate_import (unsigned myimport) inline
Definition at line 892 of file pefile.cpp.
{
        assert(nsections > 0);
        assert(output);
        defineSymbol("*ZSTART", /*0xffffffffff1000ull + 0 * */ myimport);
        ElfLinkerAMD64::relocate();
        // OutputFile::dump("il1.imp", output, outputlen);
    }
References ElfLinker::defineSymbol(), ElfLinker::nsections, ElfLinker::output, and ElfLinker::relocate().
Referenced by PeFile::processImports2().
Member Data Documentation
thunk_size
unsigned PeFile::ImportLinker::thunk_size private
Definition at line 773 of file pefile.cpp.
Referenced by add_import(), and ImportLinker().
zeros
const char PeFile::ImportLinker::zeros = {0} static private
Definition at line 757 of file pefile.cpp.
Referenced by add_import(), and ImportLinker().
The documentation for this class was generated from the following file:
src/pefile.cpp