My Project: Packer Class Reference
Packer Class Reference abstract
Packer: default implementation base class for all current packers.
#include <packer.h>
Public Member Functions
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Static Public Member Functions
static bool isValidCompressionMethod (int method)
compression method util
Protected Member Functions
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Static Protected Member Functions
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Attributes
void * last_patch = nullptr
int last_patch_len = 0
int last_patch_off = 0
Additional Inherited Members
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Detailed Description
Packer: default implementation base class for all current packers.
Packer can be viewed as "PackerDefaultImplVersion1"; it is grown historically and really would benefit from a decomposition
Definition at line 106 of file packer.h.
Constructor & Destructor Documentation
Packer()
Packer::Packer (InputFile * f) explicit protected
Definition at line 47 of file packer.cpp.
: PackerBase(f) { uip = new UiPacker(this); }
References PackerBase::UiPacker.
~Packer()
Packer::~Packer () virtual noexcept
Definition at line 49 of file packer.cpp.
{
    upx::owner_delete(uip);
    upx::owner_delete(linker);
    assert_noexcept(linker == nullptr);
}
References assert_noexcept, and upx::owner_delete().
Member Function Documentation
addFilter32()
void Packer::addFilter32 (int filter_id) protected virtual
Definition at line 55 of file packer_f.cpp.
{
    assert(filter_id > 0);
    assert(isValidFilter(filter_id));
    if (filter_id < 0x80) {
        if (0x50 == (0xF0 & filter_id)) {
            addLoader("ctok32.00",
                      ((0x50 == filter_id)   ? "ctok32.50"
                       : (0x51 == filter_id) ? "ctok32.51"
                                             : ""),
                      "ctok32.10");
        } else if ((filter_id & 0xf) % 3 == 0) {
            if (filter_id < 0x40) {
                addLoader("CALLTR00", (filter_id > 0x20) ? "CTCLEVE1" : "", "CALLTR01",
                          (filter_id & 0xf) > 3
                              ? (filter_id > 0x20 ? "CTBSHR01,CTBSWA01" : "CTBROR01,CTBSWA01")
                              : "",
                          "CALLTR02");
            } else if (0x40 == (0xF0 & filter_id)) {
                addLoader("ctok32.00");
                if (9 <= (0xf & filter_id)) {
                    addLoader("ctok32.10");
                }
                addLoader("ctok32.20");
                if (9 <= (0xf & filter_id)) {
                    addLoader("ctok32.30");
                }
                addLoader("ctok32.40");
            }
        } else
            addLoader("CALLTR10", (filter_id & 0xf) % 3 == 1 ? "CALLTRE8" : "CALLTRE9", "CALLTR11",
                      (filter_id > 0x20) ? "CTCLEVE2" : "", "CALLTR12",
                      (filter_id & 0xf) > 3
                          ? (filter_id > 0x20 ? "CTBSHR11,CTBSWA11" : "CTBROR11,CTBSWA11")
                          : "",
                      "CALLTR13");
    }
    if (0x80 == (filter_id & 0xF0)) {
        const bool x386 = (opt->cpu_x86 <= opt->CPU_386);
        const unsigned n_mru = ph.n_mru ? 1 + ph.n_mru : 0;
        const bool mrupwr2 = (0 != n_mru) && 0 == ((n_mru - 1) & n_mru);
        const unsigned f_call = f80_call(filter_id);
        const unsigned f_jmp1 = f80_jmp1(filter_id);
        const unsigned f_jcc2 = f80_jcc2(filter_id);
        if (NOFILT != f_jcc2) {
            addLoader("LXJCC010");
            if (n_mru) {
                addLoader("LXMRU045");
            } else {
                addLoader("LXMRU046");
            }
            if (0 == n_mru || MRUFLT != f_jcc2) {
                addLoader("LXJCC020");
            } else { // 0 != n_mru
                addLoader("LXJCC021");
            }
            if (NOFILT != f_jcc2) {
                addLoader("LXJCC023");
            }
        }
        addLoader("LXUNF037");
        if (x386) {
            if (n_mru) {
                addLoader("LXUNF386");
            }
            addLoader("LXUNF387");
            if (n_mru) {
                addLoader("LXUNF388");
            }
        } else {
            addLoader("LXUNF486");
            if (n_mru) {
                addLoader("LXUNF487");
            }
        }
        if (n_mru) {
            addLoader("LXMRU065");
            if (256 == n_mru) {
                addLoader("MRUBYTE3");
            } else {
                addLoader("MRUARB30");
                if (mrupwr2) {
                    addLoader("MRUBITS3");
                } else {
                    addLoader("MRUARB40");
                }
            }
            addLoader("LXMRU070");
            if (256 == n_mru) {
                addLoader("MRUBYTE4");
            } else if (mrupwr2) {
                addLoader("MRUBITS4");
            } else {
                addLoader("MRUARB50");
            }
            addLoader("LXMRU080");
            if (256 == n_mru) {
                addLoader("MRUBYTE5");
            } else {
                addLoader("MRUARB60");
                if (mrupwr2) {
                    addLoader("MRUBITS5");
                } else {
                    addLoader("MRUARB70");
                }
            }
            addLoader("LXMRU090");
            if (256 == n_mru) {
                addLoader("MRUBYTE6");
            } else {
                addLoader("MRUARB80");
                if (mrupwr2) {
                    addLoader("MRUBITS6");
                } else {
                    addLoader("MRUARB90");
                }
            }
            addLoader("LXMRU100");
        }
        addLoader("LXUNF040");
        if (n_mru) {
            addLoader("LXMRU110");
        } else {
            addLoader("LXMRU111");
        }
        addLoader("LXUNF041");
        addLoader("LXUNF042");
        if (n_mru) {
            addLoader("LXMRU010");
            if (NOFILT != f_jmp1 && NOFILT == f_call) {
                addLoader("LXJMPA00");
            } else {
                addLoader("LXCALLB0");
            }
            addLoader("LXUNF021");
        } else {
            addLoader("LXMRU022");
            if (NOFILT != f_jmp1 && NOFILT == f_call) {
                addLoader("LXJMPA01");
            } else {
                addLoader("LXCALLB1");
            }
        }
        if (n_mru) {
            if (256 != n_mru && mrupwr2) {
                addLoader("MRUBITS1");
            }
            addLoader("LXMRU030");
            if (256 == n_mru) {
                addLoader("MRUBYTE1");
            } else {
                addLoader("MRUARB10");
            }
            addLoader("LXMRU040");
        }
        addLoader("LXUNF030");
        if (NOFILT != f_jcc2) {
            addLoader("LXJCC000");
        }
        if (NOFILT != f_call || NOFILT != f_jmp1) { // at least one is filtered
            // shift opcode origin to zero
            if (0 == n_mru) {
                addLoader("LXCJ0MRU");
            } else {
                addLoader("LXCJ1MRU");
            }
            // determine if in range
            if ((NOFILT != f_call) && (NOFILT != f_jmp1)) { // unfilter both
                addLoader("LXCALJMP");
            }
            if ((NOFILT == f_call) ^ (NOFILT == f_jmp1)) { // unfilter just one
                if (0 == n_mru) {
                    addLoader("LXCALL00");
                } else {
                    addLoader("LXCALL01");
                }
            }
            // determine if mru applies
            if (0 == n_mru || !((FNOMRU == f_call) || (FNOMRU == f_jmp1))) {
                // no mru, or no exceptions
                addLoader("LXCJ2MRU");
            } else {
                // mru on one, but not the other
                addLoader("LXCJ4MRU");
                if (MRUFLT == f_jmp1) { // JMP only
                    addLoader("LXCJ6MRU");
                } else if (MRUFLT == f_call) { // CALL only
                    addLoader("LXCJ7MRU");
                }
                addLoader("LXCJ8MRU");
            }
        }
        addLoader("LXUNF034");
        if (n_mru) {
            addLoader("LXMRU055");
            if (256 == n_mru) {
                addLoader("MRUBYTE2");
            } else if (mrupwr2) {
                addLoader("MRUBITS2");
            } else {
                addLoader("MRUARB20");
            }
            addLoader("LXMRU057");
        }
    }
}
References addLoader(), f80_call(), f80_jcc2(), f80_jmp1(), FNOMRU, isValidFilter(), MRUFLT, PackHeader::n_mru, NOFILT, opt, and PackerBase::ph.
Referenced by PackLinuxElf32x86::addStubEntrySections(), PackLinuxI386::buildLinuxLoader(), PackDjgpp2::buildLoader(), PackTmt::buildLoader(), PackVmlinuxI386::buildLoader(), PackVmlinuxARMEL::buildLoader(), PackVmlinuxARMEB::buildLoader(), PackVmlinuxPPC32::buildLoader(), PackVmlinuxPPC64LE::buildLoader(), PackVmlinuxAMD64::buildLoader(), PackVmlinuzI386::buildLoader(), PackBvmlinuzI386::buildLoader(), PackVmlinuzARMEL::buildLoader(), PackW32PeI386::buildLoader(), PackWcle::buildLoader(), and PackLinuxElf32x86interp::pack3().
addLoader() [1/10]
void Packer::addLoader (C a) protected
Definition at line 773 of file packer.cpp.
{ addLoaderVA(a, N); }
References addLoaderVA(), and N.
Referenced by PackCom::addFilter16(), addFilter32(), PackExe::addLoaderEpilogue(), PackMachPPC32::addStubEntrySections(), PackMachI386::addStubEntrySections(), PackMachAMD64::addStubEntrySections(), PackMachARMEL::addStubEntrySections(), PackMachARM64EL::addStubEntrySections(), PackLinuxElf::addStubEntrySections(), PackLinuxElf32x86::addStubEntrySections(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackLinuxI386::buildLinuxLoader(), PackCom::buildLoader(), PackDjgpp2::buildLoader(), PackExe::buildLoader(), PackPs1::buildLoader(), PackSys::buildLoader(), PackTmt::buildLoader(), PackTos::buildLoader(), PackVmlinuxI386::buildLoader(), PackVmlinuxARMEL::buildLoader(), PackVmlinuxARMEB::buildLoader(), PackVmlinuxPPC32::buildLoader(), PackVmlinuxPPC64LE::buildLoader(), PackVmlinuxAMD64::buildLoader(), PackVmlinuzI386::buildLoader(), PackBvmlinuzI386::buildLoader(), PackVmlinuzARMEL::buildLoader(), PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackWcle::buildLoader(), PackWinCeArm::buildLoader(), and PackLinuxElf32x86interp::pack3().
addLoader() [2/10]
void Packer::addLoader (C a, C b) protected
Definition at line 774 of file packer.cpp.
{ addLoaderVA(a, b, N); }
References addLoaderVA(), b, and N.
addLoader() [3/10]
void Packer::addLoader (C a, C b, C c) protected
Definition at line 775 of file packer.cpp.
{ addLoaderVA(a, b, c, N); }
References addLoaderVA(), b, and N.
addLoader() [4/10]
void Packer::addLoader (C a, C b, C c, C d) protected
Definition at line 776 of file packer.cpp.
{ addLoaderVA(a, b, c, d, N); }
References addLoaderVA(), b, and N.
addLoader() [5/10]
void Packer::addLoader (C a, C b, C c, C d, C e) protected
Definition at line 777 of file packer.cpp.
{ addLoaderVA(a, b, c, d, e, N); }
References addLoaderVA(), b, and N.
addLoader() [6/10]
void Packer::addLoader (C a, C b, C c, C d, C e, C f) protected
Definition at line 778 of file packer.cpp.
{ addLoaderVA(a, b, c, d, e, f, N); }
References addLoaderVA(), b, and N.
addLoader() [7/10]
void Packer::addLoader (C a, C b, C c, C d, C e, C f, C g) protected
Definition at line 779 of file packer.cpp.
{ addLoaderVA(a, b, c, d, e, f, g, N); }
References addLoaderVA(), b, and N.
addLoader() [8/10]
void Packer::addLoader (C a, C b, C c, C d, C e, C f, C g, C h) protected
Definition at line 780 of file packer.cpp.
{
    addLoaderVA(a, b, c, d, e, f, g, h, N);
}
References addLoaderVA(), b, and N.
addLoader() [9/10]
void Packer::addLoader (C a, C b, C c, C d, C e, C f, C g, C h, C i) protected
Definition at line 783 of file packer.cpp.
{
    addLoaderVA(a, b, c, d, e, f, g, h, i, N);
}
References addLoaderVA(), b, and N.
addLoader() [10/10]
void Packer::addLoader (C a, C b, C c, C d, C e, C f, C g, C h, C i, C j) protected
Definition at line 786 of file packer.cpp.
{
    addLoaderVA(a, b, c, d, e, f, g, h, i, j, N);
}
References addLoaderVA(), b, and N.
addLoaderVA()
void Packer::addLoaderVA (const char * s, ...) protected
Definition at line 792 of file packer.cpp.
{
    va_list ap;
    va_start(ap, s);
    linker->addLoader(s, ap);
    va_end(ap);
}
Referenced by addLoader().
assertPacker()
void Packer::assertPacker () const override virtual
Implements PackerBase.
Definition at line 56 of file packer.cpp.
{
#if DEBUG
    assert(getFormat() > 0);
    assert(getFormat() < 255);
    assert(getVersion() >= 11);
    assert(getVersion() <= 14);
    assert(strlen(getName()) <= 15);
    // info: 36 is the limit for show_all_packers() in help.cpp, but 32 should be enough for now
    assert(strlen(getFullName(nullptr)) <= 32);
    assert(strlen(getFullName(opt)) <= 32);
    if (bele == nullptr)
        fprintf(stderr, "%s\n", getName());
    assert(bele != nullptr);
    if (getFormat() != UPX_F_MACH_FAT) // macho/fat is multiarch
    {
        const N_BELE_RTP::AbstractPolicy *format_bele;
        if (getFormat() < 128)
            format_bele = &N_BELE_RTP::le_policy;
        else
            format_bele = &N_BELE_RTP::be_policy;
        if (bele != format_bele)
            fprintf(stderr, "%s\n", getName());
        assert(bele == format_bele);
    }
    Linker *l = newLinker();
    assert(l != nullptr);
    if (bele != l->bele)
        fprintf(stderr, "%s\n", getName());
    assert(bele == l->bele);
    delete l;
#endif
}
References N_BELE_RTP::be_policy, ElfLinker::bele, bele, PackerBase::getFormat(), PackerBase::getFullName(), PackerBase::getName(), PackerBase::getVersion(), N_BELE_RTP::le_policy, newLinker(), opt, strlen, and UPX_F_MACH_FAT.
buildLoader()
virtual void Packer::buildLoader (const Filter * ft) protected pure virtual
Implemented in PackLinuxElf64amd, PackLinuxElf64arm, PackLinuxElf32ppc, PackLinuxElf64ppcle, PackLinuxElf64ppc, PackLinuxElf32x86, PackBSDElf32x86, PackLinuxElf32armLe, PackLinuxElf32armBe, PackLinuxElf32mipseb, PackLinuxElf32mipsel, PackLinuxI386, PackBSDI386, PackLinuxI386sh, PackCom, PackDjgpp2, PackExe, PackNetBSDElf32x86, PackOpenBSDElf32x86, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, PackMachFat, PackPs1, PackSys, PackTmt, PackTos, PackVmlinuxI386, PackVmlinuxARMEL, PackVmlinuxARMEB, PackVmlinuxPPC32, PackVmlinuxPPC64LE, PackVmlinuxAMD64, PackVmlinuzI386, PackBvmlinuzI386, PackVmlinuzARMEL, PackW32PeI386, PackW64PeAmd64, PackW64PeArm64, PackWcle, and PackWinCeArm.
Referenced by compressWithFilters(), and PackUnix::pack3().
canUnpackFormat()
virtual bool Packer::canUnpackFormat (int format) const inline virtual
Reimplemented in PackExe.
Definition at line 125 of file packer.h.
{ return (format == getFormat()); }
References PackerBase::getFormat().
Referenced by testUnpackFormat().
canUnpackVersion()
virtual bool Packer::canUnpackVersion (int version) const inline virtual
Reimplemented in PackExe, PackLinuxElf, PackLinuxI386sh, and PeFile.
Definition at line 124 of file packer.h.
{ return (version >= 8); }
Referenced by testUnpackVersion().
checkAlreadyPacked()
void Packer::checkAlreadyPacked (const void * b, int blen) final protected virtual
Definition at line 575 of file packer.cpp.
{
    assert(blen >= 4);
    int boff = find_le32(b, blen, UPX_MAGIC_LE32);
    if (boff < 0)
        return;
    // FIXME: could add some more checks to verify that this
    //   is a real PackHeader, e.g.
    //
    // PackHeader tmp;
    // if (!tmp.decodePackHeaderFromBuf((byte *)b + boff, blen - boff))
    //    return;
    //
    // This also would require that the buffer in 'b' holds
    // the full PackHeader, and not only the 4 magic bytes.
    throwAlreadyPacked();
}
References b, find_le32(), throwAlreadyPacked(), and UPX_MAGIC_LE32.
Referenced by PackCom::canPack(), PackMachFat::canPack(), PackPs1::canPack(), PackSys::canPack(), PackTos::canPack(), PackUnix::canPack(), PackVmlinuzI386::decompressKernel(), and PackExe::pack().
checkCompressionRatio()
bool Packer::checkCompressionRatio (unsigned u_len, unsigned c_len) const protected virtual
Reimplemented in PackUnix.
Definition at line 291 of file packer.cpp.
{
    return checkDefaultCompressionRatio(u_len, c_len);
}
References checkDefaultCompressionRatio().
Referenced by compress(), and compressWithFilters().
checkDefaultCompressionRatio()
bool Packer::checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const protected virtual
Definition at line 273 of file packer.cpp.
{
    assert((int) u_len > 0);
    assert((int) c_len > 0);
    if (c_len >= u_len)
        return false;
    unsigned gain = u_len - c_len;
    if (gain < 512) // need at least 512 bytes gain
        return false;
#if 1
    if (gain >= 4096) // ok if we have at least 4096 bytes gain
        return true;
#endif
    if (gain >= u_len / 16) // ok if we have at least 6.25% gain
        return true;
    return false;
}
Referenced by checkCompressionRatio(), and checkFinalCompressionRatio().
checkFinalCompressionRatio()
bool Packer::checkFinalCompressionRatio (const OutputFile * fo) const protected virtual
Definition at line 295 of file packer.cpp.
{
    const unsigned u_len = file_size;
    const unsigned c_len = fo->getBytesWritten();
    return checkDefaultCompressionRatio(u_len, c_len);
}
References checkDefaultCompressionRatio(), PackerBase::file_size, and OutputFile::getBytesWritten().
Referenced by PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), and PeFile::pack0().
checkOverlay()
void Packer::checkOverlay (unsigned overlay) protected virtual
Definition at line 430 of file packer.cpp.
{
    if ((int) overlay < 0 || overlay > file_size_u)
        throw OverlayException("invalid overlay size; file is possibly corrupt");
    if (overlay == 0)
        return;
    info("Found overlay: %d bytes", overlay);
    if (opt->overlay == opt->SKIP_OVERLAY)
        throw OverlayException("file has overlay -- skipped; try '--overlay=copy'");
}
References PackerBase::file_size_u, info(), and opt.
Referenced by PackExe::pack(), PackTmt::pack(), PackTos::pack(), PackWcle::pack(), PeFile::pack0(), PackExe::unpack(), PackTmt::unpack(), PackTos::unpack(), PackWcle::unpack(), and PeFile::unpack0().
checkPatch()
void Packer::checkPatch (void * b, int blen, int boff, int size) protected
patch util for loader
Definition at line 598 of file packer.cpp.
{
    if (b == nullptr && blen == 0 && boff == 0 && size == 0) {
        // reset
        last_patch = nullptr;
        last_patch_len = 0;
        last_patch_off = 0;
        return;
    }
    if (b == nullptr || blen <= 0 || boff < 0 || size <= 0)
        throwBadLoader();
    if (boff + size <= 0 || boff + size > blen)
        throwBadLoader();
    // printf("checkPatch: %p %5d %5d %2d\n", b, blen, boff, size);
    if (b == last_patch) {
        if (boff + size > last_patch_off)
            throwInternalError("invalid patch order");
        // The next check is not strictly necessary, but the buffer
        // length should better not increase...
        if (blen > last_patch_len)
            throwInternalError("invalid patch order (length)");
    } else
        last_patch = b;
    last_patch_len = blen;
    last_patch_off = boff;
}
References b, last_patch, last_patch_len, last_patch_off, size(), throwBadLoader(), and throwInternalError().
Referenced by PackLinuxElf32x86::buildLoader(), PackBSDElf32x86::buildLoader(), PackLinuxI386::buildLoader(), PackBSDI386::buildLoader(), PackLinuxI386sh::buildLoader(), PackNetBSDElf32x86::buildLoader(), PackOpenBSDElf32x86::buildLoader(), patch_be16(), patch_be32(), patch_le16(), patch_le32(), patchPackHeader(), and PackUnix::writePackHeader().
compress()
bool Packer::compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t * cconf = nullptr) protected
compress - wrap call to low-level upx_compress()
Definition at line 154 of file packer.cpp.
{
    ph.u_len = i_len;
    ph.c_len = 0;
    assert(ph.level >= 1);
    assert(ph.level <= 10);
    // Avoid too many progress bar updates. 64 is s->bar_len in ui.cpp.
    unsigned step = (ph.u_len < 64 * 1024) ? 0 : ph.u_len / 64;
    // save current checksums
    ph.saved_u_adler = ph.u_adler;
    ph.saved_c_adler = ph.c_adler;
    // update checksum of uncompressed data
    ph.u_adler = upx_adler32(raw_bytes(i_ptr, ph.u_len), ph.u_len, ph.u_adler);
    // set compression parameters
    upx_compress_config_t cconf;
    cconf.reset();
    if (cconf_parm)
        cconf = *cconf_parm;
    // cconf options
    int method = ph_forced_method(ph.method);
    if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) {
        if (opt->crp.crp_ucl.c_flags != -1)
            cconf.conf_ucl.c_flags = opt->crp.crp_ucl.c_flags;
        if (opt->crp.crp_ucl.p_level != -1)
            cconf.conf_ucl.p_level = opt->crp.crp_ucl.p_level;
        if (opt->crp.crp_ucl.h_level != -1)
            cconf.conf_ucl.h_level = opt->crp.crp_ucl.h_level;
        if (opt->crp.crp_ucl.max_offset != UINT_MAX &&
            opt->crp.crp_ucl.max_offset < cconf.conf_ucl.max_offset)
            cconf.conf_ucl.max_offset = opt->crp.crp_ucl.max_offset;
        if (opt->crp.crp_ucl.max_match != UINT_MAX &&
            opt->crp.crp_ucl.max_match < cconf.conf_ucl.max_match)
            cconf.conf_ucl.max_match = opt->crp.crp_ucl.max_match;
#if (WITH_NRV)
        if ((ph.level >= 7 || (ph.level >= 4 && ph.u_len >= 512 * 1024)) && !opt->prefer_ucl)
            step = 0;
#endif
    }
    if (M_IS_LZMA(method)) {
        upx::oassign(cconf.conf_lzma.pos_bits, opt->crp.crp_lzma.pos_bits);
        upx::oassign(cconf.conf_lzma.lit_pos_bits, opt->crp.crp_lzma.lit_pos_bits);
        upx::oassign(cconf.conf_lzma.lit_context_bits, opt->crp.crp_lzma.lit_context_bits);
        upx::oassign(cconf.conf_lzma.dict_size, opt->crp.crp_lzma.dict_size);
        upx::oassign(cconf.conf_lzma.num_fast_bytes, opt->crp.crp_lzma.num_fast_bytes);
    }
    if (M_IS_DEFLATE(method)) {
        upx::oassign(cconf.conf_zlib.mem_level, opt->crp.crp_zlib.mem_level);
        upx::oassign(cconf.conf_zlib.window_bits, opt->crp.crp_zlib.window_bits);
        upx::oassign(cconf.conf_zlib.strategy, opt->crp.crp_zlib.strategy);
    }
    if (uip->ui_pass >= 0)
        uip->ui_pass++;
    uip->startCallback(ph.u_len, step, uip->ui_pass, uip->ui_total_passes);
    uip->firstCallback();
    // OutputFile::dump("data.raw", in, ph.u_len);
    // compress
    int r = upx_compress(raw_bytes(i_ptr, ph.u_len), ph.u_len, raw_bytes(o_ptr, 0), &ph.c_len,
                         uip->getCallback(), method, ph.level, &cconf, &ph.compress_result);
    // uip->finalCallback(ph.u_len, ph.c_len);
    uip->endCallback();
    if (r == UPX_E_OUT_OF_MEMORY)
        throwOutOfMemoryException();
    if (r != UPX_E_OK)
        throwInternalError("compression failed");
    if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) {
        const ucl_uint *res = ph.compress_result.result_ucl.result;
        // ph.min_offset_found = res[0];
        ph.max_offset_found = res[1];
        // ph.min_match_found = res[2];
        ph.max_match_found = res[3];
        // ph.min_run_found = res[4];
        ph.max_run_found = res[5];
        ph.first_offset_found = res[6];
        // ph.same_match_offsets_found = res[7];
        if (cconf_parm) {
            assert(cconf.conf_ucl.max_offset == 0 ||
                   cconf.conf_ucl.max_offset >= ph.max_offset_found);
            assert(cconf.conf_ucl.max_match == 0 || cconf.conf_ucl.max_match >= ph.max_match_found);
        }
    }
    NO_printf("\nPacker::compress: %d/%d: %7d -> %7d\n", method, ph.level, ph.u_len, ph.c_len);
    if (!checkCompressionRatio(ph.u_len, ph.c_len))
        return false;
    // return in any case if not compressible
    if (ph.c_len >= ph.u_len)
        return false;
    // update checksum of compressed data
    ph.c_adler = upx_adler32(raw_bytes(o_ptr, ph.c_len), ph.c_len, ph.c_adler);
    // Decompress and verify. Skip this when using the fastest level.
    if (!ph_skipVerify(ph)) {
        // decompress
        unsigned new_len = ph.u_len;
        r = upx_decompress(raw_bytes(o_ptr, ph.c_len), ph.c_len, raw_bytes(i_ptr, ph.u_len),
                           &new_len, method, &ph.compress_result);
        if (r == UPX_E_OUT_OF_MEMORY)
            throwOutOfMemoryException();
        // printf("%d %d: %d %d %d\n", method, r, ph.c_len, ph.u_len, new_len);
        if (r != UPX_E_OK)
            throwInternalError("decompression failed");
        if (new_len != ph.u_len)
            throwInternalError("decompression failed (size error)");
        // verify decompression
        if (ph.u_adler != upx_adler32(raw_bytes(i_ptr, ph.u_len), ph.u_len, ph.saved_u_adler))
            throwInternalError("decompression failed (checksum error)");
    }
    return true;
}
References PackHeader::c_adler, PackHeader::c_len, checkCompressionRatio(), PackHeader::compress_result, upx_compress_config_t::conf_lzma, upx_compress_config_t::conf_ucl, upx_compress_config_t::conf_zlib, lzma_compress_config_t::dict_size, PackHeader::first_offset_found, PackHeader::level, lzma_compress_config_t::lit_context_bits, lzma_compress_config_t::lit_pos_bits, M_IS_DEFLATE, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, PackHeader::max_match_found, PackHeader::max_offset_found, PackHeader::max_run_found, zlib_compress_config_t::mem_level, PackHeader::method, NO_printf(), lzma_compress_config_t::num_fast_bytes, upx::oassign(), opt, PackerBase::ph, ph_forced_method(), ph_skipVerify(), lzma_compress_config_t::pos_bits, raw_bytes(), upx_compress_config_t::reset(), ucl_compress_result_t::result, upx_compress_result_t::result_ucl, PackHeader::saved_c_adler, PackHeader::saved_u_adler, zlib_compress_config_t::strategy, throwInternalError(), throwOutOfMemoryException(), PackHeader::u_adler, PackHeader::u_len, upx_adler32(), upx_compress(), upx_decompress(), UPX_E_OK, UPX_E_OUT_OF_MEMORY, and zlib_compress_config_t::window_bits.
Referenced by compressWithFilters(), and PackUnix::packExtent().
compressWithFilters() [1/3]
void Packer::compressWithFilters (byte * i_ptr, unsigned i_len, byte * o_ptr, byte * f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter * parm_ft, unsigned overlap_range, upx_compress_config_t const * cconf, int filter_strategy, bool inhibit_compression_check = false) protected
Definition at line 1010 of file packer.cpp.
{
    parm_ft->buf_len = f_len;
    // struct copies
    const PackHeader orig_ph = this->ph;
    PackHeader best_ph = this->ph;
    const Filter orig_ft = *parm_ft;
    Filter best_ft = *parm_ft;
    //
    best_ph.c_len = i_len;
    best_ph.overlap_overhead = 0;
    unsigned best_ph_lsize = 0;
    unsigned best_hdr_c_len = 0;
    // preconditions
    assert(orig_ph.filter == 0);
    assert(orig_ft.id == 0);
    // prepare methods and filters
    int methods[MAX_METHODS];
    int nmethods = prepareMethods(methods, ph.method, getCompressionMethods(M_ALL, ph.level));
    assert_noexcept(nmethods > 0);
    assert_noexcept(nmethods < (int) MAX_METHODS);
    int filters[MAX_FILTERS];
    int nfilters = prepareFilters(filters, filter_strategy, getFilters());
    assert_noexcept(nfilters > 0);
    assert_noexcept(nfilters < (int) MAX_FILTERS);
#if 0
    printf("compressWithFilters: m(%d):", nmethods);
    for (int i = 0; i < nmethods; i++)
        printf(" %#x", methods[i]);
    printf(" f(%d):", nfilters);
    for (int i = 0; i < nfilters; i++)
        printf(" %#x", filters[i]);
    printf("\n");
#endif
    // update total_passes; previous (ui_total_passes > 0) means incremental
    if (!ph_is_forced_method(ph.method)) {
        if (uip->ui_total_passes > 0)
            uip->ui_total_passes -= 1;
        if (filter_strategy < 0)
            uip->ui_total_passes += nmethods;
        else
            uip->ui_total_passes += nfilters * nmethods;
    }
    // Working buffer for compressed data. Don't waste memory and allocate as needed.
    byte *o_tmp = o_ptr;
    MemBuffer o_tmp_buf;
    // compress using all methods/filters
    int nfilters_success_total = 0;
    for (int mm = 0; mm < nmethods; mm++) // for all methods
    {
        NO_printf("\nmethod %d (%d of %d)\n", methods[mm], 1 + mm, nmethods);
        assert(isValidCompressionMethod(methods[mm]));
        unsigned hdr_c_len = 0;
        if (hdr_ptr != nullptr && hdr_len) {
            if (nfilters_success_total != 0 && o_tmp == o_ptr) {
                // do not overwrite o_ptr
                o_tmp_buf.allocForCompression(UPX_MAX(hdr_len, i_len));
                o_tmp = o_tmp_buf;
            }
            int r = upx_compress(hdr_ptr, hdr_len, o_tmp, &hdr_c_len, nullptr, methods[mm], 10,
                                 nullptr, nullptr);
            if (r != UPX_E_OK)
                throwInternalError("header compression failed");
            if (hdr_c_len >= hdr_len)
                throwInternalError("header compression size increase");
        }
        int nfilters_success_mm = 0;
        for (int ff = 0; ff < nfilters; ff++) // for all filters
        {
            assert(isValidFilter(filters[ff]));
            // get fresh packheader
            ph = orig_ph;
            ph.method = methods[mm];
            ph.filter = filters[ff];
            ph.overlap_overhead = 0;
            // get fresh filter
            Filter ft = orig_ft;
            ft.init(ph.filter, orig_ft.addvalue);
            // filter
            optimizeFilter(&ft, f_ptr, f_len);
            bool success = ft.filter(f_ptr, f_len);
            if (ft.id != 0 && ft.calls == 0) {
                // filter did not do anything - no need to call ft.unfilter()
                success = false;
            }
            if (!success) {
                // filter failed or was useless
                if (filter_strategy >= 0) {
                    // adjust ui passes
                    if (uip->ui_pass >= 0)
                        uip->ui_pass++;
                }
                continue;
            }
            // filter success
            NO_printf("\nfilter: id 0x%02x size %6d, calls %5d/%5d/%3d/%5d/%5d, cto 0x%02x\n",
                      ft.id, ft.buf_len, ft.calls, ft.noncalls, ft.wrongcalls, ft.firstcall,
                      ft.lastcall, ft.cto);
            if (nfilters_success_total != 0 && o_tmp == o_ptr) {
                o_tmp_buf.allocForCompression(i_len);
                o_tmp = o_tmp_buf;
            }
            nfilters_success_total++;
            nfilters_success_mm++;
            ph.filter_cto = ft.cto;
            ph.n_mru = ft.n_mru;
            // compress
            if (compress(i_ptr, i_len, o_tmp, cconf)) {
                unsigned lsize = 0;
                // findOverlapOperhead() might be slow; omit if already too big.
                if (ph.c_len + lsize + hdr_c_len <=
                    best_ph.c_len + best_ph_lsize + best_hdr_c_len) {
                    // get results
                    ph.overlap_overhead = findOverlapOverhead(o_tmp, i_ptr, overlap_range);
                    if (-4 < filter_strategy) {
                        buildLoader(&ft);
                        lsize = getLoaderSize();
                        assert(lsize > 0);
                    }
                }
                NO_printf("\n%2d %02x: %d +%4d +%3d = %d  (best: %d +%4d +%3d = %d)\n", ph.method,
                          ph.filter, ph.c_len, lsize, hdr_c_len, ph.c_len + lsize + hdr_c_len,
                          best_ph.c_len, best_ph_lsize, best_hdr_c_len,
                          best_ph.c_len + best_ph_lsize + best_hdr_c_len);
                bool update = false;
                if (ph.c_len + lsize + hdr_c_len < best_ph.c_len + best_ph_lsize + best_hdr_c_len)
                    update = true;
                else if (ph.c_len + lsize + hdr_c_len ==
                         best_ph.c_len + best_ph_lsize + best_hdr_c_len) {
                    // prefer smaller loaders
                    if (lsize + hdr_c_len < best_ph_lsize + best_hdr_c_len)
                        update = true;
                    else if (lsize + hdr_c_len == best_ph_lsize + best_hdr_c_len) {
                        // prefer less overlap_overhead
                        if (ph.overlap_overhead < best_ph.overlap_overhead)
                            update = true;
                    }
                }
                if (update) {
                    assert((int) ph.overlap_overhead > 0);
                    // update o_ptr[] with best version
                    if (o_tmp != o_ptr)
                        memcpy(o_ptr, o_tmp, ph.c_len);
                    // save compression results
                    best_ph = ph;
                    best_ph_lsize = lsize;
                    best_hdr_c_len = hdr_c_len;
                    best_ft = ft;
                }
            }
            // restore - unfilter with verify
            ft.unfilter(f_ptr, f_len, true);
            if (filter_strategy < 0)
                break;
        }
        assert(nfilters_success_mm > 0);
    }
    // postconditions 1)
    assert(nfilters_success_total > 0);
    assert(best_ph.u_len == orig_ph.u_len);
    assert(best_ph.filter == best_ft.id);
    assert(best_ph.filter_cto == best_ft.cto);
    // FIXME  assert(best_ph.n_mru == best_ft.n_mru);
    // copy back results
    this->ph = best_ph;
    *parm_ft = best_ft;
    // Finally, check compression ratio.
    // Might be inhibited when blocksize < file_size, for instance.
    if (!inhibit_compression_check) {
        if (best_ph.c_len + best_ph_lsize >= best_ph.u_len)
            throwNotCompressible();
        if (!checkCompressionRatio(best_ph.u_len, best_ph.c_len))
            throwNotCompressible();
        // postconditions 2)
        assert(best_ph.overlap_overhead > 0);
    }
    // convenience
    buildLoader(&best_ft);
}
References Filter::addvalue, MemBuffer::allocForCompression(), assert_noexcept, Filter::buf_len, buildLoader(), PackHeader::c_len, Filter::calls, checkCompressionRatio(), compress(), Filter::cto, Filter::filter(), PackHeader::filter, PackHeader::filter_cto, findOverlapOverhead(), Filter::firstcall, PackerBase::getCompressionMethods(), PackerBase::getFilters(), getLoaderSize(), Filter::id, Filter::init(), isValidCompressionMethod(), isValidFilter(), Filter::lastcall, PackHeader::level, M_ALL, PackerBase::MAX_FILTERS, PackerBase::MAX_METHODS, memcpy(), PackHeader::method, Filter::n_mru, PackHeader::n_mru, NO_printf(), Filter::noncalls, optimizeFilter(), PackHeader::overlap_overhead, PackerBase::ph, ph_is_forced_method(), prepareFilters(), prepareMethods(), throwInternalError(), throwNotCompressible(), PackHeader::u_len, Filter::unfilter(), upx_compress(), UPX_E_OK, UPX_MAX, and Filter::wrongcalls.
compressWithFilters() [2/3]
void Packer::compressWithFilters (Filter * ft, const unsigned overlap_range, const upx_compress_config_t * cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check = false) protected
Definition at line 1221 of file packer.cpp.
{
    ibuf.checkState();
    obuf.checkState();
    byte *i_ptr = ibuf + ibuf_off;
    unsigned i_len = ph.u_len;
    byte *o_ptr = obuf + obuf_off;
    unsigned f_len = ft->buf_len ? ft->buf_len : i_len;
    if (filter_strategy <= -3) {
        filter_off = 0;
        f_len = 0;
    }
    byte *f_ptr = ibuf + filter_off;
    assert(f_ptr + f_len <= i_ptr + i_len);
    // call the first one in this file
    compressWithFilters(i_ptr, i_len, o_ptr, f_ptr, f_len, hdr_ptr, hdr_len, ft, overlap_range,
                        cconf, filter_strategy, inhibit_compression_check);
    ibuf.checkState();
    obuf.checkState();
}
References Filter::buf_len, MemBuffer::checkState(), compressWithFilters(), ibuf, obuf, PackerBase::ph, and PackHeader::u_len.
compressWithFilters() [3/3]
void Packer::compressWithFilters (Filter * ft, const unsigned overlap_range, const upx_compress_config_t * cconf, int filter_strategy = 0, bool inhibit_compression_check = false) protected
Definition at line 1213 of file packer.cpp.
{
    // call the subroutine immediately below
    compressWithFilters(ft, overlap_range, cconf, filter_strategy, 0, 0, 0, nullptr, 0,
                        inhibit_compression_check);
}
References compressWithFilters().
Referenced by PeFile::callCompressWithFilters(), PackWinCeArm::callCompressWithFilters(), compressWithFilters(), PackWcle::encodeImage(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackUnix::pack2(), and PackUnix::packExtent().
copyOverlay()
void Packer::copyOverlay (OutputFile * fo, unsigned overlay, MemBuffer & buf, bool do_seek = true) protected virtual
Definition at line 440 of file packer.cpp.
{
    assert((int) overlay >= 0);
    assert(overlay < file_size_u);
    buf.checkState();
    if (!fo || overlay == 0)
        return;
    if (opt->overlay != opt->COPY_OVERLAY) {
        assert(opt->overlay == opt->STRIP_OVERLAY);
        infoWarning("stripping overlay: %d bytes", overlay);
        return;
    }
    info("Copying overlay: %d bytes", overlay);
    if (do_seek)
        fi->seek(-(upx_off_t) overlay, SEEK_END);
    // get buffer size, align to improve i/o speed
    unsigned buf_size = buf.getSize();
    if (buf_size > 65536)
        buf_size = ALIGN_DOWN(buf_size, 4096u);
    assert((int) buf_size > 0);
    do {
        unsigned len = overlay < buf_size ? overlay : buf_size;
        fi->readx(buf, len);
        fo->write(buf, len);
        overlay -= len;
    } while (overlay > 0);
    buf.checkState();
}
References ALIGN_DOWN, buf, PackerBase::fi, PackerBase::file_size_u, info(), infoWarning(), opt, InputFile::readx(), InputFile::seek(), SEEK_END, and OutputFile::write().
Referenced by PackExe::pack(), PackTmt::pack(), PackTos::pack(), PackWcle::pack(), PeFile::pack0(), PackExe::unpack(), PackTmt::unpack(), PackTos::unpack(), PackWcle::unpack(), and PeFile::unpack0().
decompress()
void Packer::decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum = true, Filter * ft = nullptr) protected
decompress
Definition at line 305 of file packer.cpp.
{
    ph_decompress(ph, in, out, verify_checksum, ft);
}
References PackerBase::ph, and ph_decompress().
Referenced by PackWcle::decodeImage(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackUnix::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), PeFile::unpack0(), PackUnix::unpackExtent(), and verifyOverlappingDecompression().
defineDecompressorSymbols()
void Packer::defineDecompressorSymbols () protected virtual
Reimplemented in PackVmlinuxI386, PackVmlinuxARMEL, PackVmlinuxARMEB, PackVmlinuxPPC32, PackVmlinuxPPC64LE, PackVmlinuxAMD64, and PackVmlinuzARMEL.
Definition at line 251 of file packer_c.cpp.
{
    if (callsManyTimes(ph.format)) {
        // ELF calls the decompressor many times; the parameters change!
        return;
    }
    if (M_IS_LZMA(ph.method)) {
        const lzma_compress_result_t *res = &ph.compress_result.result_lzma;
        upx_uint32_t properties = // lc, lp, pb, dummy
            (res->lit_context_bits << 0) | (res->lit_pos_bits << 8) | (res->pos_bits << 16);
        if (bele->isBE()) // big endian - bswap32
            properties = bswap32(properties);
        linker->defineSymbol("lzma_properties", properties);
        // len - 2 because of properties
        if (linker->findSymbol("lzma_c_len", false)) {
            linker->defineSymbol("lzma_c_len", ph.c_len - 2);
        }
        if (linker->findSymbol("lzma_u_len", false)) {
            linker->defineSymbol("lzma_u_len", ph.u_len);
        }
        unsigned stack = getDecompressorWrkmemSize();
        linker->defineSymbol("lzma_stack_adjust", 0u - stack);
        if (ph.format == UPX_F_DOS_EXE) {
            linker->defineSymbol("lzma_properties_hi", properties >> 16); // pb
            linker->defineSymbol("lzma_c_len_hi", (ph.c_len - 2) >> 16);
            linker->defineSymbol("lzma_u_len_hi", ph.u_len >> 16);
            linker->defineSymbol("lzma_u_len_segment", (ph.u_len & 0xf0000) >> 4);
        }
    }
}
References bele, bswap32, PackHeader::c_len, callsManyTimes(), PackHeader::compress_result, PackHeader::format, getDecompressorWrkmemSize(), lzma_compress_result_t::lit_context_bits, lzma_compress_result_t::lit_pos_bits, M_IS_LZMA, PackHeader::method, PackerBase::ph, lzma_compress_result_t::pos_bits, upx_compress_result_t::result_lzma, PackHeader::u_len, and UPX_F_DOS_EXE.
Referenced by PackExe::buildLoader(), PackVmlinuxI386::defineDecompressorSymbols(), PackVmlinuxARMEL::defineDecompressorSymbols(), PackVmlinuxARMEB::defineDecompressorSymbols(), PackVmlinuxPPC32::defineDecompressorSymbols(), PackVmlinuxPPC64LE::defineDecompressorSymbols(), PackVmlinuxAMD64::defineDecompressorSymbols(), PackVmlinuzARMEL::defineDecompressorSymbols(), PackW32PeI386::defineSymbols(), PackWinCeArm::defineSymbols(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), and PackWcle::pack().
defineFilterSymbols()
void Packer::defineFilterSymbols (const Filter * ft) protected virtual
Reimplemented in PackWinCeArm.
Definition at line 274 of file packer_f.cpp.
{
    if (ft->id == 0) {
        linker->defineSymbol("filter_length", 0);
        linker->defineSymbol("filter_cto", 0);
        return;
    }
    assert(ft->calls > 0);
    assert(ft->buf_len > 0);
    if (ft->id >= 0x40 && ft->id <= 0x4f) {
        linker->defineSymbol("filter_length", ft->buf_len);
        linker->defineSymbol("filter_cto", ft->cto);
    } else if (ft->id >= 0x50 && ft->id <= 0x5f) {
        linker->defineSymbol("filter_id", ft->id);
        linker->defineSymbol("filter_cto", ft->cto);
    } else if ((ft->id & 0xf) % 3 == 0) {
        linker->defineSymbol("filter_length", ft->calls);
        linker->defineSymbol("filter_cto", ft->cto);
    } else {
        linker->defineSymbol("filter_length", ft->lastcall - ft->calls * 4);
        linker->defineSymbol("filter_cto", ft->cto);
    }
#if 0
    if (0x80 == (ft->id & 0xF0)) {
        const int mru = ph.n_mru ? 1 + ph.n_mru : 0;
        if (mru && mru != 256) {
            const unsigned is_pwr2 = (0 == ((mru - 1) & mru));
            // patch_le32(0x80 + (char *) loader, lsize - 0x80, "NMRU", mru - is_pwr2);
        }
    }
#endif
}
References Filter::buf_len, Filter::calls, Filter::cto, Filter::id, Filter::lastcall, PackHeader::n_mru, and PackerBase::ph.
Referenced by PackDjgpp2::pack(), PackTmt::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), and PeFile::pack0().
doFileInfo()
void Packer::doFileInfo () final override virtual
Implements PackerBase.
Definition at line 117 of file packer.cpp.
{
    uip->uiFileInfoStart();
    fileInfo();
    uip->uiFileInfoEnd();
}
References fileInfo().
doList()
void Packer::doList () final override virtual
Implements PackerBase.
Definition at line 111 of file packer.cpp.
                    {
    uip->uiListStart();
    list();
    uip->uiListEnd();
}
References list().
doPack()
void Packer::doPack (OutputFile * fo) final override virtual
public entries called from class PackMaster
Implements PackerBase.
Definition at line 93 of file packer.cpp.
{
    uip->uiPackStart(fo);
    pack(fo);
    uip->uiPackEnd(fo);
}
References pack().
doTest()
void Packer::doTest () final override virtual
Implements PackerBase.
Definition at line 105 of file packer.cpp.
                    {
    uip->uiTestStart();
    test();
    uip->uiTestEnd();
}
References test().
doUnpack()
void Packer::doUnpack (OutputFile * fo) final override virtual
Implements PackerBase.
Definition at line 99 of file packer.cpp.
{
    uip->uiUnpackStart(fo);
    unpack(fo);
    uip->uiUnpackEnd(fo);
}
References unpack().
fileInfo()
void Packer::fileInfo () protected virtual
Reimplemented in PackTos.
Definition at line 131 of file packer.cpp.
                      {
    // FIXME: subclasses should list their sections here
    // We also should try to get a nice layout...
}
Referenced by doFileInfo().
findOverlapOverhead()
unsigned Packer::findOverlapOverhead (const byte * buf, const byte * tbuf, unsigned range = 0, unsigned upper_limit = ~0u) const protected virtual
Find overhead for in-place decompression in a heuristic way (using a binary search).
Return 0 on error.
To speed up things:
you can pass the range of an acceptable interval (so that we can succeed early)
you can enforce an upper_limit (so that we can fail early)
Reimplemented in PackDjgpp2, and PackTmt.
Definition at line 368 of file packer.cpp.
{
    assert((int) range >= 0);
    // prepare to deal with very pessimistic values
    unsigned low = 1;
    unsigned high = UPX_MIN(ph.u_len + 512, upper_limit);
    // but be optimistic for first try (speedup)
    unsigned m = UPX_MIN(16u, high);
    //
    unsigned overhead = 0;
    unsigned nr = 0; // statistics
    while (high >= low) {
        assert(m >= low);
        assert(m <= high);
        assert(m < overhead || overhead == 0);
        nr++;
        bool success = testOverlappingDecompression(buf, tbuf, m);
        // printf("testOverlapOverhead(%d): %d %d: %d -> %d\n", nr, low, high, m, (int)success);
        if (success) {
            overhead = m;
            // Succeed early if m lies in [low .. low+range-1], i.e. if
            // if the range of the current interval is <= range.
            //   if (m <= low + range - 1)
            //   if (m <  low + range)
            if (m - low < range) // avoid underflow
                break;
            high = m - 1;
        } else
            low = m + 1;
        m = (low & high) + ((low ^ high) >> 1); // avoid overflow
    }
    // printf("findOverlapOverhead: %d (%d tries)\n", overhead, nr);
    if (overhead == 0)
        throwInternalError("this is an oo bug");
    UNUSED(nr);
    return overhead;
}
References buf, PackerBase::ph, testOverlappingDecompression(), throwInternalError(), PackHeader::u_len, UNUSED, and UPX_MIN.
Referenced by compressWithFilters(), PackDjgpp2::findOverlapOverhead(), and PackTmt::findOverlapOverhead().
get_te16()
unsigned Packer::get_te16 (const void * p) const inline protected noexcept
Definition at line 281 of file packer.h.
{ return bele->get16(p); }
References bele.
Referenced by PackLinuxElf32::ARM_is_QNX(), PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackLinuxI386sh::buildLoader(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), PackLinuxElf32::canUnpack(), PackLinuxElf64::canUnpack(), PackLinuxElf32::checkEhdr(), PackLinuxElf64::checkEhdr(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), PackLinuxElf32::invert_pt_dynamic(), PackLinuxElf64::invert_pt_dynamic(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf::pack3(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), and PackLinuxElf64::updateLoader().
get_te32()
unsigned Packer::get_te32 (const void * p) const inline protected noexcept
Definition at line 282 of file packer.h.
{ return bele->get32(p); }
References bele.
Referenced by PackLinuxElf32::adjABS(), PackLinuxElf64::adjABS(), PackLinuxElf32::ARM_is_QNX(), PackLinuxElf32::ARM_updateLoader(), PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf32::asl_slide_Shdrs(), PackLinuxElf32::calls_crt1(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), PackLinuxElf32::canPack_Shdr(), PackLinuxElf64::canPack_Shdr(), PackLinuxElf32::canPackOSABI(), PackLinuxElf32::check_pt_dynamic(), PackLinuxElf32::check_pt_load(), PackLinuxElf32::checkEhdr(), PackLinuxElf64::checkEhdr(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackLinuxElf32::elf_find_dynamic(), PackLinuxElf32::elf_find_dynptr(), PackLinuxElf32::elf_find_Phdr_for_va(), PackLinuxElf32::elf_find_ptype(), PackLinuxElf64::elf_find_ptype(), PackLinuxElf32::elf_find_section_name(), PackLinuxElf64::elf_find_section_name(), PackLinuxElf32::elf_find_section_type(), PackLinuxElf64::elf_find_section_type(), PackLinuxElf32::elf_find_table_size(), PackLinuxElf32::elf_get_offset_from_Phdrs(), PackLinuxElf32::elf_has_dynamic(), PackLinuxElf32::elf_lookup(), PackLinuxElf64::elf_lookup(), PackLinuxElf32::elf_unsigned_dynamic(), PackLinuxElf32::find_LOAD_gap(), PackUnix::find_overlay_offset(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), PackLinuxElf32::get_dynsym_name(), PackLinuxElf64::get_dynsym_name(), PackLinuxElf32::getbase(), PackLinuxElf32::getbrk(), PackLinuxElf32::invert_pt_dynamic(), PackLinuxElf64::invert_pt_dynamic(), PackLinuxElf32::is_LOAD(), PackLinuxElf64::is_LOAD(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32armLe::pack1(), PackLinuxElf32armBe::pack1(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), PackVmlinuzARMEL::readFileHeader(), PackLinuxElf32::sort_DT32_offsets(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackUnix::unpack(), PackUnix::unpackExtent(), PackLinuxElf32::unRel32(), PackLinuxElf32::updateLoader(), and PackVmlinuzARMEL::write_vmlinuz_head().
get_te64()
upx_uint64_t Packer::get_te64 (const void * p) const inline protected noexcept
Definition at line 284 of file packer.h.
{ return bele->get64(p); }
References bele.
Referenced by PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf64::buildLinuxLoader(), PackLinuxElf64::calls_crt1(), PackLinuxElf64::canPack(), PackLinuxElf64::canPack_Shdr(), PackLinuxElf64::check_pt_dynamic(), PackLinuxElf64::check_pt_load(), PackLinuxElf64::checkEhdr(), PackLinuxElf64::elf_find_dynamic(), PackLinuxElf64::elf_find_dynptr(), PackLinuxElf64::elf_find_Phdr_for_va(), PackLinuxElf64::elf_find_table_size(), PackLinuxElf64::elf_get_offset_from_address(), PackLinuxElf64::elf_has_dynamic(), PackLinuxElf64::elf_lookup(), PackLinuxElf64::elf_unsigned_dynamic(), PackLinuxElf64::find_LOAD_gap(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf64::generateElfHdr(), PackLinuxElf64::getbrk(), PackLinuxElf64::invert_pt_dynamic(), PackLinuxElf64::pack1(), PackLinuxElf64::pack3(), PackLinuxElf64::pack4(), PackLinuxElf64::PackLinuxElf64help1(), PackLinuxElf64::sort_DT64_offsets(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf64::un_shlib_1(), PackLinuxElf64::unpack(), PackLinuxElf64::unRela64(), and PackLinuxElf64::updateLoader().
get_te64_32()
unsigned Packer::get_te64_32 (const void * p) const inline protected
Definition at line 283 of file packer.h.
{ return (unsigned) bele->get64(p); }
References bele.
Referenced by PackLinuxElf64::pack2(), PackLinuxElf64::pack2_shlib(), and PackLinuxElf64::pack3().
getDecompressorSections()
const char * Packer::getDecompressorSections () const protected virtual
Definition at line 124 of file packer_c.cpp.
{
    // clang-format off
    static const char nrv2b_le32_small[] =
        "N2BSMA10,N2BDEC10,N2BSMA20,N2BDEC20,N2BSMA30,"
        "N2BDEC30,N2BSMA40,N2BSMA50,N2BDEC50,N2BSMA60,"
        "N2BDEC60";
    static const char nrv2b_le32_fast[] =
        "N2BFAS10,+80CXXXX,N2BFAS11,N2BDEC10,N2BFAS20,"
        "N2BDEC20,N2BFAS30,N2BDEC30,N2BFAS40,N2BFAS50,"
        "N2BDEC50,N2BFAS60,+40CXXXX,N2BFAS61,N2BDEC60";
    static const char nrv2d_le32_small[] =
        "N2DSMA10,N2DDEC10,N2DSMA20,N2DDEC20,N2DSMA30,"
        "N2DDEC30,N2DSMA40,N2DSMA50,N2DDEC50,N2DSMA60,"
        "N2DDEC60";
    static const char nrv2d_le32_fast[] =
        "N2DFAS10,+80CXXXX,N2DFAS11,N2DDEC10,N2DFAS20,"
        "N2DDEC20,N2DFAS30,N2DDEC30,N2DFAS40,N2DFAS50,"
        "N2DDEC50,N2DFAS60,+40CXXXX,N2DFAS61,N2DDEC60";
    static const char nrv2e_le32_small[] =
        "N2ESMA10,N2EDEC10,N2ESMA20,N2EDEC20,N2ESMA30,"
        "N2EDEC30,N2ESMA40,N2ESMA50,N2EDEC50,N2ESMA60,"
        "N2EDEC60";
    static const char nrv2e_le32_fast[] =
        "N2EFAS10,+80CXXXX,N2EFAS11,N2EDEC10,N2EFAS20,"
        "N2EDEC20,N2EFAS30,N2EDEC30,N2EFAS40,N2EFAS50,"
        "N2EDEC50,N2EFAS60,+40CXXXX,N2EFAS61,N2EDEC60";
#if 0
    static const char cl1b_le32_small[] =
        "CL1ENTER,CL1SMA10,CL1RLOAD,"
        "CL1WID01,CL1SMA1B,"
        "CL1WID02,CL1SMA1B,"
        "CL1WID03,CL1SMA1B,"
        "CL1WID04,CL1SMA1B,"
        "CL1WID05,CL1SMA1B,"
        "CL1WID06,CL1SMA1B,"
        "CL1WID07,CL1SMA1B,"
        "CL1WID08,CL1SMA1B,"
        "CL1WID09,CL1SMA1B,"
        "CL1WID10,"
        "CL1START,"
        "CL1TOP00,CL1SMA1B,"
        "CL1TOP01,CL1SMA1B,"
        "CL1TOP02,CL1SMA1B,"
        "CL1TOP03,CL1SMA1B,"
        "CL1TOP04,CL1SMA1B,"
        "CL1TOP05,CL1SMA1B,"
        "CL1TOP06,CL1SMA1B,"
        "CL1TOP07,CL1SMA1B,"
        "CL1OFF01,CL1SMA1B,"
        "CL1OFF02,CL1SMA1B,"
        "CL1OFF03,CL1SMA1B,"
        "CL1OFF04,"
        "CL1LEN00,CL1SMA1B,"
        "CL1LEN01,CL1SMA1B,"
        "CL1LEN02,"
        "CL1COPY0";
    static const char cl1b_le32_fast[] =
        "CL1ENTER,"          "CL1RLOAD,"
        "CL1WID01,CL1FAS1B,"
        "CL1WID02,CL1FAS1B,"
        "CL1WID03,CL1FAS1B,"
        "CL1WID04,CL1FAS1B,"
        "CL1WID05,CL1FAS1B,"
        "CL1WID06,CL1FAS1B,"
        "CL1WID07,CL1FAS1B,"
        "CL1WID08,CL1FAS1B,"
        "CL1WID09,CL1FAS1B,"
        "CL1WID10,"
        "CL1START,"
        "CL1TOP00,CL1FAS1B,"
        "CL1TOP01,CL1FAS1B,"
        "CL1TOP02,CL1FAS1B,"
        "CL1TOP03,CL1FAS1B,"
        "CL1TOP04,CL1FAS1B,"
        "CL1TOP05,CL1FAS1B,"
        "CL1TOP06,CL1FAS1B,"
        "CL1TOP07,CL1FAS1B,"
        "CL1OFF01,CL1FAS1B,"
        "CL1OFF02,CL1FAS1B,"
        "CL1OFF03,CL1FAS1B,"
        "CL1OFF04,"
        "CL1LEN00,CL1FAS1B,"
        "CL1LEN01,CL1FAS1B,"
        "CL1LEN02,"
        "CL1COPY0";
#endif
    static const char lzma_small[] =
        "LZMA_DEC00,LZMA_DEC10,LZMA_DEC30";
    static const char lzma_fast[] =
        "LZMA_DEC00,LZMA_DEC20,LZMA_DEC30";
    static const char lzma_elf_small[] =
        "LZMA_ELF00,LZMA_DEC10,LZMA_DEC30";
    static const char lzma_elf_fast[] =
        "LZMA_ELF00,LZMA_DEC20,LZMA_DEC30";
    // clang-format on
    const unsigned method = ph_forced_method(ph.method);
    if (method == M_NRV2B_LE32)
        return opt->small ? nrv2b_le32_small : nrv2b_le32_fast;
    if (method == M_NRV2D_LE32)
        return opt->small ? nrv2d_le32_small : nrv2d_le32_fast;
    if (method == M_NRV2E_LE32)
        return opt->small ? nrv2e_le32_small : nrv2e_le32_fast;
    //    if (method == M_CL1B_LE32)
    //        return opt->small ? cl1b_le32_small  : cl1b_le32_fast;
    if (M_IS_LZMA(method)) {
        if (callsManyTimes(ph.format)) {
            return opt->small ? lzma_elf_small : lzma_elf_fast;
        }
        return opt->small ? lzma_small : lzma_fast;
    }
    throwInternalError("bad decompressor");
    return nullptr;
}
References callsManyTimes(), PackHeader::format, M_IS_LZMA, M_NRV2B_LE32, M_NRV2D_LE32, M_NRV2E_LE32, PackHeader::method, opt, PackerBase::ph, ph_forced_method(), and throwInternalError().
Referenced by PackLinuxElf32x86::addStubEntrySections(), PackLinuxI386::buildLinuxLoader(), PackDjgpp2::buildLoader(), PackTmt::buildLoader(), PackVmlinuxI386::buildLoader(), PackVmlinuxAMD64::buildLoader(), PackVmlinuzI386::buildLoader(), PackBvmlinuzI386::buildLoader(), PackW32PeI386::buildLoader(), PackWcle::buildLoader(), and PackLinuxElf32x86interp::pack3().
getDecompressorWrkmemSize()
unsigned Packer::getDecompressorWrkmemSize () const protected virtual
Definition at line 239 of file packer_c.cpp.
{
    unsigned size = 0;
    if (M_IS_LZMA(ph.method)) {
        const lzma_compress_result_t *res = &ph.compress_result.result_lzma;
        // FIXME - this is for i386 only
        size = 8 + 4 + ALIGN_UP(2 * res->num_probs, 4u);
        size = ALIGN_UP(size, 16u);
    }
    assert((int) size >= 0);
    return size;
}
References ALIGN_UP, PackHeader::compress_result, M_IS_LZMA, PackHeader::method, lzma_compress_result_t::num_probs, PackerBase::ph, upx_compress_result_t::result_lzma, and size().
Referenced by PackLinuxI386::buildLinuxLoader(), PackExe::buildLoader(), defineDecompressorSymbols(), PackWcle::encodeObjectTable(), PackDjgpp2::pack(), PackPs1::pack(), PackTos::pack(), and PackBvmlinuzI386::pack().
getDefaultCompressionMethods_8()
const int * Packer::getDefaultCompressionMethods_8 (int method, int level, int small = -1) const protected
Definition at line 40 of file packer_c.cpp.
{
#define M_LZMA_003 (M_LZMA | 0x00300)
#define M_LZMA_407 (M_LZMA | 0x40700)
    static const int m_all[] = {M_NRV2B_8,     M_NRV2D_8,  M_NRV2E_8,  M_LZMA,
                                M_ULTRA_BRUTE, M_LZMA_003, M_LZMA_407, M_END};
    // static const int m_cl1b[]  = { M_CL1B_8, M_END };
    static const int m_lzma[] = {M_LZMA, M_END};
    static const int m_nrv2b[] = {M_NRV2B_8, M_END};
    static const int m_nrv2d[] = {M_NRV2D_8, M_END};
    static const int m_nrv2e[] = {M_NRV2E_8, M_END};
    if (method == M_ALL)
        return m_all;
    // if (M_IS_CL1B(method))  return m_cl1b;
    if (M_IS_LZMA(method))
        return m_lzma;
    if (M_IS_NRV2B(method))
        return m_nrv2b;
    if (M_IS_NRV2D(method))
        return m_nrv2d;
    if (M_IS_NRV2E(method))
        return m_nrv2e;
    if (small < 0)
        small = file_size <= 512 * 1024;
    if (level == 1 || small)
        return m_nrv2b;
    return m_nrv2e;
}
References PackerBase::file_size, M_ALL, M_END, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_LZMA, M_LZMA_003, M_LZMA_407, M_NRV2B_8, M_NRV2D_8, M_NRV2E_8, and M_ULTRA_BRUTE.
Referenced by PackExe::getCompressionMethods(), PackLinuxElf32armLe::getCompressionMethods(), PackLinuxElf32armBe::getCompressionMethods(), PackMachARMEL::getCompressionMethods(), PackPs1::getCompressionMethods(), PackTos::getCompressionMethods(), PackVmlinuxARMEL::getCompressionMethods(), PackVmlinuxARMEB::getCompressionMethods(), PackVmlinuzARMEL::getCompressionMethods(), and PackWinCeArm::getCompressionMethods().
getDefaultCompressionMethods_le32()
const int * Packer::getDefaultCompressionMethods_le32 (int method, int level, int small = -1) const protected
Definition at line 69 of file packer_c.cpp.
{
    static const int m_all[] = {M_NRV2B_LE32,  M_NRV2D_LE32, M_NRV2E_LE32, M_LZMA,
                                M_ULTRA_BRUTE, M_LZMA_003,   M_LZMA_407,   M_END};
    // static const int m_cl1b[]  = { M_CL1B_LE32, M_END };
    static const int m_lzma[] = {M_LZMA, M_END};
    static const int m_nrv2b[] = {M_NRV2B_LE32, M_END};
    static const int m_nrv2d[] = {M_NRV2D_LE32, M_END};
    static const int m_nrv2e[] = {M_NRV2E_LE32, M_END};
    if (method == M_ALL)
        return m_all;
    // if (M_IS_CL1B(method))  return m_cl1b;
    if (M_IS_LZMA(method))
        return m_lzma;
    if (M_IS_NRV2B(method))
        return m_nrv2b;
    if (M_IS_NRV2D(method))
        return m_nrv2d;
    if (M_IS_NRV2E(method))
        return m_nrv2e;
    if (small < 0)
        small = file_size <= 512 * 1024;
    if (level == 1 || small)
        return m_nrv2b;
    return m_nrv2e;
}
References PackerBase::file_size, M_ALL, M_END, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_LZMA, M_LZMA_003, M_LZMA_407, M_NRV2B_LE32, M_NRV2D_LE32, M_NRV2E_LE32, and M_ULTRA_BRUTE.
Referenced by PackDjgpp2::getCompressionMethods(), PackLinuxElf::getCompressionMethods(), PackLinuxI386::getCompressionMethods(), PackMachBase< TMachClass >::getCompressionMethods(), PackPs1::getCompressionMethods(), PackTmt::getCompressionMethods(), PackVmlinuxI386::getCompressionMethods(), PackVmlinuxPPC32::getCompressionMethods(), PackVmlinuxPPC64LE::getCompressionMethods(), PackVmlinuxAMD64::getCompressionMethods(), PackVmlinuzI386::getCompressionMethods(), PackW32PeI386::getCompressionMethods(), PackW64PeAmd64::getCompressionMethods(), PackW64PeArm64::getCompressionMethods(), and PackWcle::getCompressionMethods().
getLoader()
byte * Packer::getLoader () const protected virtual
Definition at line 799 of file packer.cpp.
{
    int size = -1;
    byte *oloader = linker->getLoader(&size);
    if (oloader == nullptr || size <= 0)
        throwBadLoader();
    return oloader;
}
References size(), and throwBadLoader().
Referenced by PackExe::buildLoader(), PackPs1::buildLoader(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackUnix::pack3(), PackLinuxElf32x86interp::pack3(), PackCom::patchLoader(), PackSys::patchLoader(), PackUnix::patchLoaderChecksum(), PackLinuxI386::patchLoaderChecksum(), relocateLoader(), and PackLinuxElf64::updateLoader().
getLoaderSection()
int Packer::getLoaderSection (const char * name, int * slen = nullptr) const protected virtual
Definition at line 820 of file packer.cpp.
{
    int size = -1;
    int ostart = linker->getSection(name, &size);
    if (ostart < 0 || size <= 0)
        throwBadLoader();
    if (slen)
        *slen = size;
    return ostart;
}
References size(), and throwBadLoader().
Referenced by PackDjgpp2::pack(), PackExe::pack(), PackTmt::pack(), PackWcle::pack(), and PeFile::pack0().
getLoaderSectionStart()
int Packer::getLoaderSectionStart (const char * name, int * slen = nullptr) const protected virtual
Definition at line 831 of file packer.cpp.
{
    int size = -1;
    int ostart = linker->getSection(name, &size);
    if (ostart < 0 || size < 0)
        throwBadLoader();
    if (slen)
        *slen = size;
    return ostart;
}
References size(), and throwBadLoader().
Referenced by PackBvmlinuzI386::buildLoader(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackBvmlinuzI386::pack(), PackWcle::pack(), PackCom::patchLoader(), PackSys::patchLoader(), and relocateLoader().
getLoaderSize()
int Packer::getLoaderSize () const protected virtual
Definition at line 807 of file packer.cpp.
{
    int size = -1;
    byte *oloader = linker->getLoader(&size);
    if (oloader == nullptr || size <= 0)
        throwBadLoader();
    return size;
}
References size(), and throwBadLoader().
Referenced by PackExe::buildLoader(), PackBvmlinuzI386::buildLoader(), compressWithFilters(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackUnix::pack3(), and PackLinuxElf32x86interp::pack3().
getPackHeader()
bool Packer::getPackHeader (const void * b, int blen, bool allow_incompressible = false) final protected virtual
Definition at line 530 of file packer.cpp.
{
    auto bb = (const byte *) b;
    if (!ph.decodePackHeaderFromBuf(SPAN_S_MAKE(const byte, bb, blen), blen))
        return false;
    if (ph.version > getVersion())
        throwCantUnpack("need a newer version of UPX");
    // Some formats might be able to unpack old versions because
    // their implementation hasn't changed. Ask them.
    if (opt->cmd != CMD_FILEINFO)
        if (!testUnpackVersion(ph.version))
            return false;
    if (ph.c_len > ph.u_len || (ph.c_len == ph.u_len && !allow_incompressible) ||
        ph.c_len >= file_size_u || ph.version <= 0 || ph.version >= 0xff)
        throwCantUnpack("header corrupted");
    else if (ph.u_len > ph.u_file_size) {
#if 0
        // FIXME: does this check make sense w.r.t. overlays ???
        if (ph.format == UPX_F_WIN32_PE || ph.format == UPX_F_DOS_EXE)
            // may get longer
            ((void)0);
        else
            throwCantUnpack("header size corrupted");
#endif
    }
    if (!isValidCompressionMethod(ph.method))
        throwCantUnpack("unknown compression method (try a newer version of UPX)");
    // Some formats might be able to unpack "subformats". Ask them.
    if (!testUnpackFormat(ph.format))
        return false;
    return true;
}
References b, PackHeader::c_len, CMD_FILEINFO, PackHeader::decodePackHeaderFromBuf(), PackerBase::file_size_u, PackHeader::format, PackerBase::getVersion(), isValidCompressionMethod(), PackHeader::method, opt, PackerBase::ph, SPAN_S_MAKE, testUnpackFormat(), testUnpackVersion(), throwCantUnpack(), PackHeader::u_file_size, PackHeader::u_len, UPX_F_DOS_EXE, and PackHeader::version.
Referenced by PackUnix::find_overlay_offset(), and readPackHeader().
getRandomId()
unsigned Packer::getRandomId () const protected virtual
Definition at line 471 of file packer.cpp.
{
    if (opt->debug.disable_random_id)
        return 0x01020304;
    unsigned id = 0;
    while (id == 0) {
        id ^= (unsigned) fi->st.st_ino;
        id ^= (unsigned) fi->st.st_atime;
        id ^= (unsigned) upx_rand();
    }
    return id;
}
References PackerBase::fi, opt, FileBase::st, and upx_rand().
Referenced by PackLinuxI386::pack1(), and PackBSDI386::pack1().
handleStub()
void Packer::handleStub (InputFile * fi, OutputFile * fo, unsigned size) static protected
Copy stub from exe.
file i/o utils
Parameters
InputFile *fif
Source file where OutputFile *fo will be copied.
OutputFile *fo
Destination file oubject file where OutputFile *fo will be copied.
unsigned size
Size of the destination stub. Should be same as InputFile *fif.
Todo:
ensure if there is not a more posix friendly method to store the destination stub size for cpp. Might be better with str.length(). Might avoid memory corruption.
Returns
void.
Definition at line 415 of file packer.cpp.
{
    if (fo) {
        if (size > 0) {
            // copy stub from exe
            info("Copying original stub: %u bytes", size);
            ByteArray(stub, size);
            fif->seek(0, SEEK_SET);
            fif->readx(stub, size);
            fo->write(stub, size);
        } else {
            // no stub
        }
    }
}
References ByteArray, info(), InputFile::readx(), InputFile::seek(), SEEK_SET, size(), and OutputFile::write().
Referenced by PackDjgpp2::handleStub(), PackWcle::handleStub(), PackTmt::pack(), PeFile::pack0(), PackTmt::unpack(), and PeFile::unpack0().
hasLoaderSection()
bool Packer::hasLoaderSection (const char * name) const protected virtual
Definition at line 815 of file packer.cpp.
{
    void *section = linker->findSection(name, false);
    return section != nullptr;
}
Referenced by PackMachPPC32::addStubEntrySections(), PackMachI386::addStubEntrySections(), PackMachAMD64::addStubEntrySections(), PackMachARMEL::addStubEntrySections(), PackMachARM64EL::addStubEntrySections(), PackLinuxElf::addStubEntrySections(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackVmlinuxPPC32::buildLoader(), and PackVmlinuxPPC64LE::buildLoader().
initLoader()
void Packer::initLoader (const void * pdata, int plen, int small = -1, int pextra = 0) protected virtual
Definition at line 760 of file packer.cpp.
{
    upx::owner_delete(linker);
    linker = newLinker();
    assert(bele == linker->bele);
    linker->init(pdata, plen, pextra);
    unsigned size;
    char const *const ident = getIdentstr(&size, small);
    linker->addSection("IDENTSTR", ident, size, 0);
}
References bele, getIdentstr(), newLinker(), upx::owner_delete(), and size().
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackLinuxI386::buildLinuxLoader(), PackCom::buildLoader(), PackDjgpp2::buildLoader(), PackExe::buildLoader(), PackPs1::buildLoader(), PackSys::buildLoader(), PackTmt::buildLoader(), PackTos::buildLoader(), PackVmlinuxI386::buildLoader(), PackVmlinuxARMEL::buildLoader(), PackVmlinuxARMEB::buildLoader(), PackVmlinuxPPC32::buildLoader(), PackVmlinuxPPC64LE::buildLoader(), PackVmlinuxAMD64::buildLoader(), PackVmlinuzI386::buildLoader(), PackBvmlinuzI386::buildLoader(), PackVmlinuzARMEL::buildLoader(), PackW32PeI386::buildLoader(), PackW64PeAmd64::buildLoader(), PackWcle::buildLoader(), PackWinCeArm::buildLoader(), and PackLinuxElf32x86interp::pack3().
initPackHeader()
void Packer::initPackHeader () final override virtual
packheader util
Implements PackerBase.
Definition at line 488 of file packer.cpp.
{
    ph.reset();
    ph.version = getVersion();
    ph.format = getFormat();
    ph.method = M_NONE;
    ph.level = -1;
    ph.u_adler = ph.c_adler = ph.saved_u_adler = ph.saved_c_adler = upx_adler32(nullptr, 0);
    ph.buf_offset = 0;
    ph.u_file_size = file_size;
}
References PackHeader::buf_offset, PackHeader::c_adler, PackerBase::file_size, PackHeader::format, PackerBase::getFormat(), PackerBase::getVersion(), PackHeader::level, M_NONE, PackHeader::method, PackerBase::ph, PackHeader::reset(), PackHeader::saved_c_adler, PackHeader::saved_u_adler, PackHeader::u_adler, PackHeader::u_file_size, upx_adler32(), and PackHeader::version.
Referenced by PackMachFat::pack(), and PackMachFat::unpack().
isValidCompressionMethod()
bool Packer::isValidCompressionMethod (int method) static
compression method util
Definition at line 36 of file packer_c.cpp.
{
    return M_IS_LZMA(m) || M_IS_NRV2B(m) || M_IS_NRV2D(m) || M_IS_NRV2E(m);
}
References M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, and M_IS_NRV2E.
Referenced by anonymous_namespace{help.cpp}::PackerNames::add(), compressWithFilters(), getPackHeader(), prepareMethods(), set_method(), and updatePackHeader().
isValidFilter()
bool Packer::isValidFilter (int filter_id) const protected virtual
filter util; see class FilterImpl
Definition at line 37 of file packer_f.cpp.
{
    return Filter::isValidFilter(filter_id, getFilters());
}
References PackerBase::getFilters(), and Filter::isValidFilter().
Referenced by PackCom::addFilter16(), addFilter32(), compressWithFilters(), and patchPackHeader().
list()
void Packer::list () protected virtual
Reimplemented in PackMachFat.
Definition at line 129 of file packer.cpp.
{ uip->uiList(); }
Referenced by doList().
newLinker()
virtual Linker * Packer::newLinker () const protected pure virtual
Implemented in PackCom, PackDjgpp2, PackExe, PackLinuxElf64amd, PackLinuxElf64arm, PackLinuxElf32ppc, PackLinuxElf64ppcle, PackLinuxElf64ppc, PackLinuxElf32x86, PackLinuxElf32armLe, PackLinuxElf32armBe, PackLinuxElf32mipseb, PackLinuxElf32mipsel, PackLinuxI386, PackMachPPC32, PackMachPPC64, PackMachI386, PackMachAMD64, PackMachARMEL, PackMachARM64EL, PackMachFat, PackPs1, PackTmt, PackTos, PackVmlinuxI386, PackVmlinuxARMEL, PackVmlinuxARMEB, PackVmlinuxPPC32, PackVmlinuxPPC64LE, PackVmlinuxAMD64, PackVmlinuzI386, PackVmlinuzARMEL, PackW32PeI386, PackW64PeAmd64, PackW64PeArm64, PackWcle, and PackWinCeArm.
Referenced by assertPacker(), and initLoader().
optimizeFilter()
virtual void Packer::optimizeFilter (Filter * , const byte * , unsigned) const inline protected virtual
Definition at line 228 of file packer.h.
{}
Referenced by PackLinuxI386sh::buildLoader(), and compressWithFilters().
optimizeReloc()
unsigned Packer::optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int * big) static protected
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
Definition at line 37 of file packer_r.cpp.
{
    assert(bits == 32 || bits == 64);
    mem_size_assert(1, image_size);
#if WITH_XSPAN >= 2
    ptr_check_no_overlap(relocs.data(), relocs.size_bytes(), image.data(image_size), image_size,
                         out.data(), out.size_bytes());
#endif
    SPAN_S_VAR(byte, fix, out);
    *big = 0;
    if (opt->exact)
        throwCantPackExact();
    if (relocnum == 0)
        return 0;
    upx_qsort(raw_bytes(relocs, 4 * relocnum), relocnum, 4, le32_compare);
    if (0) {
        printf("optimizeReloc: u_reloc %9u checksum=0x%08x\n", 4 * relocnum,
               upx_adler32(relocs, 4 * relocnum));
        printf("optimizeReloc: u_image %9u checksum=0x%08x\n", image_size,
               upx_adler32(image, image_size));
    }
    unsigned pc = (unsigned) -4;
    for (unsigned i = 0; i < relocnum; i++) {
        unsigned delta = get_le32(relocs + i * 4) - pc;
        if (delta == 0)
            continue;
        else if ((int) delta < 4)
            throwCantPack("overlapping fixups");
        else if (delta < 0xf0)
            *fix++ = (byte) delta;
        else if (delta < 0x100000) {
            *fix++ = (byte) (0xf0 + (delta >> 16));
            *fix++ = (byte) delta;
            *fix++ = (byte) (delta >> 8);
        } else {
            *big = 1;
            *fix++ = 0xf0;
            *fix++ = 0;
            *fix++ = 0;
            set_le32(fix, delta);
            fix += 4;
        }
        pc += delta;
        if (pc + 4 > image_size)
            throwCantPack("bad reloc[%#x] = %#x", i, pc);
        if (bswap) {
            if (bits == 32)
                set_be32(image + pc, get_le32(image + pc));
            else
                set_be64(image + pc, get_le64(image + pc));
        }
    }
    *fix++ = 0; // end marker
    const unsigned bytes = ptr_udiff_bytes(fix, out);
    if (0) {
        printf("optimizeReloc: c_reloc %9u checksum=0x%08x\n", bytes, upx_adler32(out, bytes));
        printf("optimizeReloc: c_image %9u checksum=0x%08x\n", image_size,
               upx_adler32(image, image_size));
    }
    return bytes;
}
References get_le32(), get_le64(), le32_compare(), mem_size_assert(), opt, ptr_check_no_overlap(), ptr_udiff_bytes(), raw_bytes(), set_be32(), set_be64(), set_le32(), SPAN_S_VAR, throwCantPack(), throwCantPackExact(), upx_adler32(), and upx_qsort.
Referenced by PackTmt::pack(), PackWcle::preprocessFixups(), PeFile32::processRelocs(), and PeFile64::processRelocs().
OwningPointer() [1/2]
Packer::OwningPointer (Linker) protected
OwningPointer() [2/2]
Packer::OwningPointer (UiPacker) protected
pack()
virtual void Packer::pack (OutputFile * fo) protected pure virtual
Implemented in PackCom, PackDjgpp2, PackExe, PackMachFat, PackPs1, PackTmt, PackTos, PackUnix, PackVmlinuxBase< TElfClass >, PackVmlinuxBase< ElfClass_LE64 >, PackVmlinuxBase< ElfClass_BE32 >, PackVmlinuxBase< ElfClass_LE32 >, PackVmlinuzI386, PackBvmlinuzI386, PackVmlinuzARMEL, PackW32PeI386, PackW64PeAmd64, PackW64PeArm64, PackWcle, and PackWinCeArm.
Referenced by doPack().
patch_be16() [1/2]
int Packer::patch_be16 (void * b, int blen, const void * old, unsigned new_) protected
Definition at line 634 of file packer.cpp.
{
    int boff = find(b, blen, old, 2);
    checkPatch(b, blen, boff, 2);
    byte *p = (byte *) b + boff;
    set_be16(p, new_);
    return boff;
}
References b, checkPatch(), find(), and set_be16().
patch_be16() [2/2]
int Packer::patch_be16 (void * b, int blen, unsigned old, unsigned new_) protected
Definition at line 624 of file packer.cpp.
{
    int boff = find_be16(b, blen, old);
    checkPatch(b, blen, boff, 2);
    byte *p = (byte *) b + boff;
    set_be16(p, new_);
    return boff;
}
References b, checkPatch(), find_be16(), and set_be16().
patch_be32() [1/2]
int Packer::patch_be32 (void * b, int blen, const void * old, unsigned new_) protected
Definition at line 654 of file packer.cpp.
{
    int boff = find(b, blen, old, 4);
    checkPatch(b, blen, boff, 4);
    byte *p = (byte *) b + boff;
    set_be32(p, new_);
    return boff;
}
References b, checkPatch(), find(), and set_be32().
patch_be32() [2/2]
int Packer::patch_be32 (void * b, int blen, unsigned old, unsigned new_) protected
Definition at line 644 of file packer.cpp.
{
    int boff = find_be32(b, blen, old);
    checkPatch(b, blen, boff, 4);
    byte *p = (byte *) b + boff;
    set_be32(p, new_);
    return boff;
}
References b, checkPatch(), find_be32(), and set_be32().
patch_le16() [1/2]
int Packer::patch_le16 (void * b, int blen, const void * old, unsigned new_) protected
Definition at line 674 of file packer.cpp.
{
    int boff = find(b, blen, old, 2);
    checkPatch(b, blen, boff, 2);
    byte *p = (byte *) b + boff;
    set_le16(p, new_);
    return boff;
}
References b, checkPatch(), find(), and set_le16().
patch_le16() [2/2]
int Packer::patch_le16 (void * b, int blen, unsigned old, unsigned new_) protected
Definition at line 664 of file packer.cpp.
{
    int boff = find_le16(b, blen, old);
    checkPatch(b, blen, boff, 2);
    byte *p = (byte *) b + boff;
    set_le16(p, new_);
    return boff;
}
References b, checkPatch(), find_le16(), and set_le16().
patch_le32() [1/2]
int Packer::patch_le32 (void * b, int blen, const void * old, unsigned new_) protected
Definition at line 694 of file packer.cpp.
{
    int boff = find(b, blen, old, 4);
    checkPatch(b, blen, boff, 4);
    byte *p = (byte *) b + boff;
    set_le32(p, new_);
    return boff;
}
References b, checkPatch(), find(), and set_le32().
patch_le32() [2/2]
int Packer::patch_le32 (void * b, int blen, unsigned old, unsigned new_) protected
Definition at line 684 of file packer.cpp.
{
    int boff = find_le32(b, blen, old);
    checkPatch(b, blen, boff, 4);
    byte *p = (byte *) b + boff;
    set_le32(p, new_);
    return boff;
}
References b, checkPatch(), find_le32(), and set_le32().
Referenced by PackLinuxI386::buildLoader(), PackBSDI386::buildLoader(), and PackLinuxI386sh::buildLoader().
patchPackHeader()
int Packer::patchPackHeader (void * b, int blen) final protected virtual
Definition at line 515 of file packer.cpp.
{
    assert(isValidFilter(ph.filter));
    const int size = ph.getPackHeaderSize();
    if (linker->findSection("UPX1HEAD", false))
        assert(size == linker->getSectionSize("UPX1HEAD"));
    int boff = find_le32(b, blen, UPX_MAGIC_LE32);
    checkPatch(b, blen, boff, size);
    auto bb = (byte *) b;
    ph.putPackHeader(SPAN_S_MAKE(byte, bb + boff, blen, bb));
    return boff;
}
References b, checkPatch(), PackHeader::filter, find_le32(), PackHeader::getPackHeaderSize(), isValidFilter(), PackerBase::ph, PackHeader::putPackHeader(), size(), SPAN_S_MAKE, and UPX_MAGIC_LE32.
Referenced by PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackCom::patchLoader(), PackSys::patchLoader(), and PackUnix::writePackHeader().
prepareMethods()
int Packer::prepareMethods (int * methods, int ph_method, const int * all_methods) const protected
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
Needs buildLoader().
Required inputs: this->ph ulen parm_ft clevel addvalue buf_len (optional)
updates this->ph
updates *ft
i_ptr[] is restored to the original unfiltered version
o_ptr[] contains the best compressed version
filter_strategy: n: try the first N filters, use best one -1: try all filters, use first working one -2: try only the opt->filter filter -3: use no filter at all -4: use no filter at all, and build no loader, either
This has been prepared for generalization into class Packer so that opt->all_methods and/or opt->all_filters are available for all executable formats.
It will replace the tryFilters() / compress() call sequence.
2006-02-15: hdr_buf and hdr_u_len are default empty input "header" array to fix a 2-pass problem with Elf headers. As of today there can be only one decompression method per executable output file, and that method is the one that gives best compression for .text and loader. However, the Elf headers precede .text in the output file, and are written first. "--brute" compression often compressed the Elf headers using nrv2b but the .text (and loader) with nrv2e. This often resulted in SIGSEGV during decompression. The workaround is for hdr_buf and hdr_u_len to describe the Elf headers (typically less than 512 bytes) when .text is passed in, and include them in the calculation of shortest output. Then the result this->ph.method will say which [single] method to use for everything. The Elf headers are never filtered. They are short enough (< 512 bytes) that compressing them more than once per method (once here when choosing, once again just before writing [because compressWithFilters discards]) is OK because of the simplicity of not having two output arrays.
Definition at line 908 of file packer.cpp.
{
    int nmethods = 0;
    if (!opt->all_methods || all_methods == nullptr || (-0x80 == (ph_method >> 24))) {
        methods[nmethods++] = ph_forced_method(ph_method);
        return nmethods;
    }
    for (int mm = 0; all_methods[mm] != M_END; ++mm) {
        int method = all_methods[mm];
        if (method == M_ULTRA_BRUTE && !opt->ultra_brute)
            break;
        if (method == M_SKIP || method == M_ULTRA_BRUTE)
            continue;
        if (opt->all_methods && opt->all_methods_use_lzma != 1 && M_IS_LZMA(method))
            continue;
        // check duplicate
        assert(Packer::isValidCompressionMethod(method));
        for (int i = 0; i < nmethods; i++)
            assert(method != methods[i]);
        // use this method
        methods[nmethods++] = method;
    }
    // debug
    if (opt->debug.use_random_method && nmethods >= 2) {
        int method = methods[upx_rand() % nmethods];
        NO_printf("\nuse_random_method = %#x (%d)\n", method, nmethods);
        methods[0] = method;
        nmethods = 1;
    }
    return nmethods;
}
References isValidCompressionMethod(), M_END, M_IS_LZMA, M_SKIP, M_ULTRA_BRUTE, NO_printf(), opt, ph_forced_method(), and upx_rand().
Referenced by compressWithFilters(), PackLinuxElf32::pack1(), and PackLinuxElf64::pack1().
readPackHeader()
bool Packer::readPackHeader (int len, bool allow_incompressible = false) final protected virtual
Definition at line 566 of file packer.cpp.
{
    assert(len > 0);
    MemBuffer buf(len);
    len = fi->read(buf, len);
    if (len <= 0)
        return false;
    return getPackHeader(buf, len, allow_incompressible);
}
References buf, PackerBase::fi, getPackHeader(), and InputFile::read().
Referenced by PackCom::canUnpack(), PackDjgpp2::canUnpack(), PackExe::canUnpack(), PackPs1::canUnpack(), PackTmt::canUnpack(), PackTos::canUnpack(), PackVmlinuzI386::canUnpack(), PackVmlinuzARMEL::canUnpack(), PackWcle::canUnpack(), and PeFile::canUnpack0().
relocateLoader()
void Packer::relocateLoader () protected virtual
Definition at line 841 of file packer.cpp.
{
    linker->relocate();
#if 0
    // "relocate" packheader
    if (linker->findSection("UPX1HEAD", false))
    {
        int lsize = -1;
        int loff = getLoaderSectionStart("UPX1HEAD", &lsize);
        assert(lsize == ph.getPackHeaderSize());
        byte *p = getLoader() + loff;
        assert(get_le32(p) == UPX_MAGIC_LE32);
        //patchPackHeader(p, lsize);
        ph.putPackHeader(p);
    }
#endif
}
References get_le32(), getLoader(), getLoaderSectionStart(), PackHeader::getPackHeaderSize(), PackerBase::ph, PackHeader::putPackHeader(), and UPX_MAGIC_LE32.
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackLinuxI386::buildLinuxLoader(), PackExe::buildLoader(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackCom::patchLoader(), and PackSys::patchLoader().
set_te16()
void Packer::set_te16 (void * p, unsigned v) inline protected noexcept
Definition at line 285 of file packer.h.
{ bele->set16(p, v); }
References bele.
Referenced by PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackUnix::patchLoaderChecksum(), and PackLinuxI386::patchLoaderChecksum().
set_te32()
void Packer::set_te32 (void * p, unsigned v) inline protected noexcept
Definition at line 286 of file packer.h.
{ bele->set32(p, v); }
References bele.
Referenced by PackLinuxElf32::ARM_updateLoader(), PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf32::asl_slide_Shdrs(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackLinuxElf32::canPack_Shdr(), PackLinuxElf64::canPack_Shdr(), PackVmlinuzARMEL::decompressKernel(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), PackUnix::pack(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32armLe::pack1(), PackLinuxElf32armBe::pack1(), PackUnix::pack2(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackLinuxElf::pack2_shlib_overlay_init(), PackLinuxElf::pack2_shlib_overlay_write(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf::pack3(), PackUnix::pack4(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackUnix::packExtent(), PackUnix::patchLoaderChecksum(), PackLinuxI386::patchLoaderChecksum(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf32::unRel32(), PackLinuxElf32::updateLoader(), and PackVmlinuzARMEL::write_vmlinuz_head().
set_te64()
void Packer::set_te64 (void * p, upx_uint64_t v) inline protected noexcept
Definition at line 287 of file packer.h.
{ bele->set64(p, v); }
References bele.
Referenced by PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf64::canPack_Shdr(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf64::generateElfHdr(), PackLinuxElf64::pack1(), PackLinuxElf64::pack3(), PackLinuxElf64::pack4(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf64::unRela64(), and PackLinuxElf64::updateLoader().
test()
void Packer::test () protected virtual
default actions
Definition at line 127 of file packer.cpp.
{ unpack(nullptr); }
References unpack().
Referenced by doTest().
testOverlappingDecompression()
bool Packer::testOverlappingDecompression (const byte * buf, const byte * tbuf, unsigned overlap_overhead) const protected virtual
overlapping decompression
Definition at line 313 of file packer.cpp.
{
    return ph_testOverlappingDecompression(ph, buf, tbuf, overlap_overhead);
}
References buf, PackerBase::ph, and ph_testOverlappingDecompression().
Referenced by findOverlapOverhead(), PackUnix::pack2(), and PackUnix::packExtent().
testUnpackFormat()
bool Packer::testUnpackFormat (int format) const protected virtual
Definition at line 144 of file packer.cpp.
{
    if (format != ph_format && ph_format != -1)
        throwCantUnpack("program has been modified; run a virus checker!");
    return canUnpackFormat(format);
}
References canUnpackFormat(), ph_format, and throwCantUnpack().
Referenced by getPackHeader().
testUnpackVersion()
bool Packer::testUnpackVersion (int version) const protected virtual
Reimplemented in PeFile.
Definition at line 136 of file packer.cpp.
{
    if (version != ph_version && ph_version != -1)
        throwCantUnpack("program has been modified; run a virus checker!");
    if (!canUnpackVersion(version))
        throwCantUnpack("I am not compatible with older versions of UPX");
    return true;
}
References canUnpackVersion(), ph_version, and throwCantUnpack().
Referenced by getPackHeader().
unoptimizeReloc()
unsigned Packer::unoptimizeReloc (SPAN_S(const byte) & in, MemBuffer & out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap) static protected
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Definition at line 109 of file packer_r.cpp.
{
    assert(bits == 32 || bits == 64);
    mem_size_assert(1, image_size);
#if WITH_XSPAN >= 2
    ptr_check_no_overlap(in.data(), in.size_bytes(), image.data(image_size), image_size);
#endif
    SPAN_S_VAR(const byte, fix, in);
    // count
    unsigned relocnum = 0;
    for (fix = in; *fix; fix++, relocnum++) {
        if (*fix >= 0xf0) {
            if (*fix == 0xf0 && get_le16(fix + 1) == 0)
                fix += 4;
            fix += 2;
        }
    }
    NO_fprintf(stderr, "relocnum=%x\n", relocnum);
    if (0) {
        const unsigned bytes = ptr_udiff_bytes(fix + 1, in);
        printf("unoptimizeReloc: c_reloc %9u checksum=0x%08x\n", bytes, upx_adler32(in, bytes));
        printf("unoptimizeReloc: c_image %9u checksum=0x%08x\n", image_size,
               upx_adler32(image, image_size));
    }
    out.alloc(mem_size(4, relocnum + 1)); // one extra entry
    SPAN_S_VAR(LE32, relocs, out);
    fix = in;
    unsigned pc = (unsigned) -4;
    for (unsigned i = 0; i < relocnum; i++) {
        unsigned delta;
        if (*fix < 0xf0)
            delta = *fix++;
        else {
            delta = (*fix & 0x0f) * 0x10000 + get_le16(fix + 1);
            fix += 3;
            if (delta == 0) {
                delta = get_le32(fix);
                fix += 4;
            }
        }
        if ((int) delta < 4)
            throwCantUnpack("overlapping fixups");
        pc += delta;
        if (pc + 4 > image_size)
            throwCantUnpack("bad reloc[%#x] = %#x", i, pc);
        *relocs++ = pc;
        if (bswap) {
            if (bits == 32)
                set_be32(image + pc, get_le32(image + pc));
            else
                set_be64(image + pc, get_le64(image + pc));
        }
    }
    in = fix + 1; // advance
    assert(relocnum == ptr_udiff_bytes(relocs, raw_bytes(out, 0)) / 4);
    if (0) {
        printf("unoptimizeReloc: u_reloc %9u checksum=0x%08x\n", 4 * relocnum,
               upx_adler32(out, 4 * relocnum));
        printf("unoptimizeReloc: u_image %9u checksum=0x%08x\n", image_size,
               upx_adler32(image, image_size));
    }
    return relocnum;
}
References MemBuffer::alloc(), get_le16(), get_le32(), get_le64(), mem_size(), mem_size_assert(), NO_fprintf(), ptr_check_no_overlap(), ptr_udiff_bytes(), raw_bytes(), set_be32(), set_be64(), SPAN_S_VAR, throwCantUnpack(), and upx_adler32().
Referenced by PackWcle::decodeFixups(), PeFile::rebuildRelocs(), and PackTmt::unpack().
unpack()
virtual void Packer::unpack (OutputFile * fo) protected pure virtual
Implemented in PackCom, PackDjgpp2, PackExe, PackLinuxElf, PackLinuxElf32, PackLinuxElf64, PackLinuxElf32x86interp, PackMachBase< TMachClass >, PackMachBase< MachClass_LE64 >, PackMachBase< MachClass_LE32 >, PackMachBase< MachClass_BE32 >, PackMachBase< MachClass_BE64 >, PackMachFat, PackPs1, PackTmt, PackTos, PackUnix, PackVmlinuxBase< TElfClass >, PackVmlinuxBase< ElfClass_LE64 >, PackVmlinuxBase< ElfClass_BE32 >, PackVmlinuxBase< ElfClass_LE32 >, PackVmlinuzI386, PackVmlinuzARMEL, PackWcle, PeFile32, and PeFile64.
Referenced by doUnpack(), and test().
updatePackHeader()
void Packer::updatePackHeader () final override virtual
Implements PackerBase.
Definition at line 500 of file packer.cpp.
{
    assert(opt->cmd == CMD_COMPRESS);
    //
    const int *m = getCompressionMethods(opt->method, opt->level);
    ph.method = m[0];
    ph.level = opt->level;
    if (ph.level < 0)
        ph.level = file_size < 512 * 1024 ? 8 : 7;
    //
    assert(isValidCompressionMethod(ph.method));
    assert(1 <= ph.level && ph.level <= 10);
}
References CMD_COMPRESS, PackerBase::file_size, PackerBase::getCompressionMethods(), isValidCompressionMethod(), PackHeader::level, PackHeader::method, opt, and PackerBase::ph.
Referenced by PackMachFat::pack().
verifyOverlappingDecompression() [1/2]
void Packer::verifyOverlappingDecompression (byte * o_ptr, unsigned o_size, Filter * ft = nullptr) protected
Definition at line 346 of file packer.cpp.
{
    assert(ph.c_len < ph.u_len);
    assert((int) ph.overlap_overhead > 0);
    if (ph_skipVerify(ph))
        return;
    unsigned offset = (ph.u_len + ph.overlap_overhead) - ph.c_len;
    if (offset + ph.c_len > o_size)
        return;
    memmove(o_ptr + offset, o_ptr, ph.c_len);
    decompress(o_ptr + offset, o_ptr, true, ft);
}
References PackHeader::c_len, decompress(), memmove(), PackHeader::overlap_overhead, PackerBase::ph, ph_skipVerify(), and PackHeader::u_len.
verifyOverlappingDecompression() [2/2]
void Packer::verifyOverlappingDecompression (Filter * ft = nullptr) protected
Definition at line 318 of file packer.cpp.
{
    assert(ph.c_len < ph.u_len);
    assert((int) ph.overlap_overhead > 0);
    // Idea:
    //   obuf[] was allocated with MemBuffer::allocForCompression(), and
    //   its contents are no longer needed, i.e. the compressed data
    //   must have been already written.
    //   We now can perform a real overlapping decompression and
    //   verify the checksum.
    //
    // Note:
    //   This verify is just because of complete paranoia that there
    //   could be a hidden bug in the upx_test_overlap implementation,
    //   and it should not be necessary at all.
    //
    // See also:
    //   Filter::verifyUnfilter()
    if (ph_skipVerify(ph))
        return;
    unsigned offset = (ph.u_len + ph.overlap_overhead) - ph.c_len;
    if (offset + ph.c_len > obuf.getSize())
        return;
    memmove(obuf + offset, obuf, ph.c_len);
    decompress(obuf + offset, obuf, true, ft);
    obuf.checkState();
}
References PackHeader::c_len, MemBuffer::checkState(), decompress(), MemBuffer::getSize(), memmove(), obuf, PackHeader::overlap_overhead, PackerBase::ph, ph_skipVerify(), and PackHeader::u_len.
Referenced by PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackUnix::pack2(), and PackUnix::packExtent().
Member Data Documentation
bele
const N_BELE_RTP::AbstractPolicy* Packer::bele = nullptr protected
Definition at line 342 of file packer.h.
Referenced by assertPacker(), PackLinuxI386::buildLinuxLoader(), defineDecompressorSymbols(), get_te16(), get_te32(), get_te64(), get_te64_32(), initLoader(), PackBvmlinuzI386::pack(), PackCom::PackCom(), PackDjgpp2::PackDjgpp2(), PackExe::PackExe(), PackLinuxElf32Be::PackLinuxElf32Be(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf32Le::PackLinuxElf32Le(), PackLinuxElf64Be::PackLinuxElf64Be(), PackLinuxElf64::PackLinuxElf64help1(), PackLinuxElf64Le::PackLinuxElf64Le(), PackLinuxI386::PackLinuxI386(), PackMachBase< TMachClass >::PackMachBase(), PackMachFat::PackMachFat(), PackPs1::PackPs1(), PackTmt::PackTmt(), PackTos::PackTos(), PackUnixBe32::PackUnixBe32(), PackUnixLe32::PackUnixLe32(), PackVmlinuzARMEL::PackVmlinuzARMEL(), PackVmlinuzI386::PackVmlinuzI386(), PackWcle::PackWcle(), PeFile::PeFile(), set_te16(), set_te32(), and set_te64().
ibuf
MemBuffer Packer::ibuf protected
Definition at line 349 of file packer.h.
Referenced by compressWithFilters(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackWcle::encodeImage(), PackPs1::findBssSection(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PeFile::pack0(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackUnix::pack2(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackUnix::packExtent(), PackSys::patchLoader(), PeFile::processImports0(), PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), PeFile::processTls1(), PeFile::readSections(), PeFile::rebuildExports(), PeFile::rebuildResources(), PeFile::stripDebug(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackUnix::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), PeFile::unpack0(), and PackUnix::unpackExtent().
ibufgood
unsigned Packer::ibufgood = 0 protected
Definition at line 351 of file packer.h.
Referenced by PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::readSections(), and PeFile::unpack0().
last_patch
void* Packer::last_patch = nullptr private
Definition at line 361 of file packer.h.
Referenced by checkPatch().
last_patch_len
int Packer::last_patch_len = 0 private
Definition at line 362 of file packer.h.
Referenced by checkPatch().
last_patch_off
int Packer::last_patch_off = 0 private
Definition at line 363 of file packer.h.
Referenced by checkPatch().
obuf
MemBuffer Packer::obuf protected
Definition at line 350 of file packer.h.
Referenced by compressWithFilters(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackW32PeI386::defineSymbols(), PackW64PeAmd64::defineSymbols(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PeFile::pack0(), PackUnix::pack2(), PackUnix::packExtent(), PackCom::patchLoader(), PackSys::patchLoader(), PackVmlinuzI386::readKernel(), PackVmlinuzARMEL::readKernel(), PeFile::rebuildExports(), PeFile::rebuildImports(), PeFile::rebuildRelocs(), PeFile::rebuildResources(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), PeFile::unpack0(), and verifyOverlappingDecompression().
ph_format
int Packer::ph_format = -1 protected
Definition at line 345 of file packer.h.
Referenced by testUnpackFormat().
ph_version
int Packer::ph_version = -1 protected
Definition at line 346 of file packer.h.
Referenced by testUnpackVersion(), and PeFile::testUnpackVersion().
The documentation for this class was generated from the following files:
src/packer.h
src/packer.cpp
src/packer_c.cpp
src/packer_f.cpp
src/packer_r.cpp