My Project: Throwable Class Reference
Throwable Class Reference
exceptions
#include <except.h>
Classes
struct Stats
Public Member Functions
Throwable (const Throwable &) noexcept
virtual ~Throwable () noexcept
const char * getMsg () const noexcept
int getErrno () const noexcept
bool isWarning () const noexcept
Protected Member Functions
Throwable (const char *m=nullptr, int e=0, bool w=false) noexcept
Protected Attributes
bool is_warning = false
Private Types
typedef std::exception super
Private Member Functions
OwningPointer (char) msg
Throwable & operator= (const Throwable &) noexcept DELETED_FUNCTION
Private Attributes
int err = 0
Static Private Attributes
static Stats stats
Detailed Description
exceptions
Definition at line 34 of file except.h.
Member Typedef Documentation
super
typedef std::exception Throwable::super private
Definition at line 35 of file except.h.
Constructor & Destructor Documentation
Throwable() [1/2]
Throwable::Throwable (const char * m = nullptr, int e = 0, bool w = false) protected noexcept
Definition at line 36 of file except.cpp.
                                                          : super(),
                                                              msg(nullptr),
                                                              err(e),
                                                              is_warning(w) {
    if (m != nullptr) {
        msg = strdup(m);
        assert_noexcept(msg != nullptr);
    }
    NO_fprintf(stderr, "construct exception: %zu %zu %s\n", size_t(stats.counter_current),
               size_t(stats.counter_total), (const char *) msg);
    stats.counter_current += 1;
    stats.counter_total += 1;
}
References assert_noexcept, and NO_fprintf().
Throwable() [2/2]
Throwable::Throwable (const Throwable & other) noexcept
Definition at line 50 of file except.cpp.
                                                    : super(other),
                                                        msg(nullptr),
                                                        err(other.err),
                                                        is_warning(other.is_warning) {
    if (other.msg != nullptr) {
        msg = strdup(other.msg);
        assert_noexcept(msg != nullptr);
    }
    NO_fprintf(stderr, "copy construct exception: %zu %zu %s\n", size_t(stats.counter_current),
               size_t(stats.counter_total), (const char *) msg);
    stats.counter_current += 1;
    stats.counter_total += 1;
}
References assert_noexcept, and NO_fprintf().
~Throwable()
Throwable::~Throwable () virtual noexcept
Definition at line 64 of file except.cpp.
{
    stats.counter_current -= 1;
    NO_fprintf(stderr, "destruct exception: %zu %zu %s\n", size_t(stats.counter_current),
               size_t(stats.counter_total), (const char *) msg);
    upx::owner_free(msg);
}
References NO_fprintf(), upx::owner_free(), and stats.
Member Function Documentation
getErrno()
int Throwable::getErrno () const inline noexcept
Definition at line 44 of file except.h.
{ return err; }
References err.
getMsg()
const char * Throwable::getMsg () const inline noexcept
Definition at line 43 of file except.h.
{ return msg; }
isWarning()
bool Throwable::isWarning () const inline noexcept
Definition at line 45 of file except.h.
{ return is_warning; }
References is_warning.
Referenced by do_files().
operator=()
Throwable & Throwable::operator= (const Throwable &) private noexcept
OwningPointer()
Throwable::OwningPointer (char) private
Member Data Documentation
err
int Throwable::err = 0 private
Definition at line 49 of file except.h.
Referenced by getErrno().
is_warning
bool Throwable::is_warning = false protected
Definition at line 51 of file except.h.
Referenced by AlreadyPackedException::AlreadyPackedException(), and isWarning().
stats
Throwable::Stats Throwable::stats static private
Definition at line 69 of file except.h.
Referenced by ~Throwable().
The documentation for this class was generated from the following files:
src/except.h
src/except.cpp