My Project: PackVmlinuxI386 Class Reference
PackVmlinuxI386 Class Reference
#include <p_vmlinx.h>
Public Member Functions
PackVmlinuxI386 (InputFile *f)
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
Public Member Functions inherited from PackVmlinuxBase< ElfClass_LE32 >
PackVmlinuxBase (InputFile *, unsigned, unsigned, unsigned, char const *)
virtual ~PackVmlinuxBase ()
virtual int getVersion () const override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual void buildLoader (const Filter *ft) override
virtual void defineDecompressorSymbols () override
virtual Linker * newLinker () const override
virtual bool is_valid_e_entry (Addr) override
virtual bool has_valid_vmlinux_head () override
virtual unsigned write_vmlinux_head (OutputFile *fo, Shdr *stxt) override
Protected Member Functions inherited from PackVmlinuxBase< ElfClass_LE32 >
virtual Shdr const * getElfSections ()
virtual int getStrategy (Filter &)
virtual bool is_valid_e_entry (Addr)=0
virtual bool has_valid_vmlinux_head ()=0
virtual tribool canPack () override
virtual void pack (OutputFile *fo) override
virtual tribool canUnpack () override
virtual void unpack (OutputFile *fo) override
virtual unsigned write_vmlinux_head (OutputFile *fo, Shdr *stxt)=0
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Private Types
typedef PackVmlinuxBase< ElfClass_LE32 > super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PackVmlinuxBase< ElfClass_LE32 >
typedef ElfClass_LE32 ElfClass
typedef ElfClass::BeLePolicy BeLePolicy
typedef ElfClass::ElfITypes ElfITypes
typedef ElfClass::TE16 TE16
typedef ElfClass::TE32 TE32
typedef ElfClass::TE64 TE64
typedef ElfITypes::Addr Addr
typedef ElfClass::Ehdr Ehdr
typedef ElfClass::Shdr Shdr
typedef ElfClass::Phdr Phdr
typedef ElfClass::Dyn Dyn
typedef ElfClass::Sym Sym
Static Protected Member Functions inherited from PackVmlinuxBase< ElfClass_LE32 >
static int __acc_cdecl_qsort compare_Phdr (void const *aa, void const *bb)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes inherited from PackVmlinuxBase< ElfClass_LE32 >
unsigned int const my_e_machine
unsigned char const my_elfclass
unsigned char const my_elfdata
char const *const my_boot_label
int n_ptload
unsigned sz_ptload
unsigned paddr_min
Phdr * phdri
Shdr * shdri
char * shstrtab
Shdr * p_text
Shdr * p_note0
Shdr * p_note1
Ehdr ehdri
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Detailed Description
Definition at line 98 of file p_vmlinx.h.
Member Typedef Documentation
super
typedef PackVmlinuxBase<ElfClass_LE32> PackVmlinuxI386::super private
Definition at line 100 of file p_vmlinx.h.
Constructor & Destructor Documentation
PackVmlinuxI386()
PackVmlinuxI386::PackVmlinuxI386 (InputFile * f) inline
Definition at line 102 of file p_vmlinx.h.
                                  : super(f, Ehdr::EM_386,
        Ehdr::ELFCLASS32, Ehdr::ELFDATA2LSB, "startup_32") { }
Member Function Documentation
buildLoader()
void PackVmlinuxI386::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 787 of file p_vmlinx.cpp.
{
    // prepare loader
    initLoader(stub_i386_linux_kernel_vmlinux, sizeof(stub_i386_linux_kernel_vmlinux));
    addLoader("LINUX000",
              (0x40==(0xf0 & ft->id)) ? "LXCKLLT1" : (ft->id ? "LXCALLT1" : ""),
              "LXMOVEUP",
              getDecompressorSections(),
              nullptr
             );
    if (ft->id) {
        assert(ft->calls > 0);
        if (0x40==(0xf0 & ft->id)) {
            addLoader("LXCKLLT9", nullptr);
        }
        else {
            addLoader("LXCALLT9", nullptr);
        }
        addFilter32(ft->id);
    }
    addLoader("LINUX990",
              ((ph.first_offset_found == 1) ? "LINUX991" : ""),
              "LINUX992,IDENTSTR,UPX1HEAD", nullptr);
}
References Packer::addFilter32(), Packer::addLoader(), Filter::calls, PackHeader::first_offset_found, Packer::getDecompressorSections(), Filter::id, Packer::initLoader(), PackerBase::ph, and stub_i386_linux_kernel_vmlinux.
defineDecompressorSymbols()
void PackVmlinuxI386::defineDecompressorSymbols () override protected virtual
Reimplemented from Packer.
Definition at line 1050 of file p_vmlinx.cpp.
{
    super::defineDecompressorSymbols();
    linker->defineSymbol("ENTRY_POINT", phdri[0].p_paddr);
    linker->defineSymbol("PHYSICAL_START", phdri[0].p_paddr);
}
References Packer::defineDecompressorSymbols(), and PackVmlinuxBase< ElfClass_LE32 >::phdri.
getCompressionMethods()
const int * PackVmlinuxI386::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 689 of file p_vmlinx.cpp.
{
    return Packer::getDefaultCompressionMethods_le32(method, level);
}
References Packer::getDefaultCompressionMethods_le32().
getFilters()
const int * PackVmlinuxI386::getFilters () const override virtual
Implements PackerBase.
Definition at line 695 of file p_vmlinx.cpp.
{
    static const int filters[] = {
        0x49, 0x46,
    FT_END };
    return filters;
}
References FT_END.
getFormat()
virtual int PackVmlinuxI386::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 104 of file p_vmlinx.h.
{ return UPX_F_VMLINUX_i386; }
References UPX_F_VMLINUX_i386.
getFullName()
virtual const char * PackVmlinuxI386::getFullName (const options_t *) const inline override virtual
Definition at line 106 of file p_vmlinx.h.
{ return "i386-linux.kernel.vmlinux"; }
getName()
virtual const char * PackVmlinuxI386::getName () const inline override virtual
Implements PackerBase.
Definition at line 105 of file p_vmlinx.h.
{ return "vmlinux/i386"; }
has_valid_vmlinux_head()
bool PackVmlinuxI386::has_valid_vmlinux_head () override protected virtual
Implements PackVmlinuxBase< ElfClass_LE32 >.
Definition at line 1186 of file p_vmlinx.cpp.
{
    unsigned char buf[5];
    fi->seek(p_text->sh_offset + sizeof(stub_i386_linux_kernel_vmlinux_head) -5, SEEK_SET);
    fi->readx(&buf[0], 5);
    if (0xE8!=buf[0] ||  BeLePolicy::get32(&buf[1]) != ph.c_len)
    {
        return false;
    }
    return true;
}
References buf, PackHeader::c_len, PackerBase::fi, PackVmlinuxBase< ElfClass_LE32 >::p_text, PackerBase::ph, InputFile::readx(), InputFile::seek(), SEEK_SET, and stub_i386_linux_kernel_vmlinux_head.
is_valid_e_entry()
bool PackVmlinuxI386::is_valid_e_entry (Addr e_entry) override protected virtual
Definition at line 775 of file p_vmlinx.cpp.
{
    return 0==(0x000fffff & e_entry); // entry on whole 1 MiB
}
newLinker()
Linker * PackVmlinuxI386::newLinker () const override protected virtual
Implements Packer.
Definition at line 781 of file p_vmlinx.cpp.
{
    return new ElfLinkerX86;
}
write_vmlinux_head()
static const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT unsigned PackVmlinuxI386::write_vmlinux_head (OutputFile * fo, Shdr * stxt) override protected virtual
Definition at line 986 of file p_vmlinx.cpp.
{
    // COMPRESSED_LENGTH
    fo->write(&stub_i386_linux_kernel_vmlinux_head[0],
        sizeof(stub_i386_linux_kernel_vmlinux_head)-(1+ 4) +1);
    TE32 tmp_u32; tmp_u32 = ph.c_len; fo->write(&tmp_u32, 4);
    stxt->sh_size += sizeof(stub_i386_linux_kernel_vmlinux_head);
    return sizeof(stub_i386_linux_kernel_vmlinux_head);
}
References PackHeader::c_len, PackerBase::ph, stub_i386_linux_kernel_vmlinux_head, and OutputFile::write().
The documentation for this class was generated from the following files:
src/p_vmlinx.h
src/p_vmlinx.cpp