My Project: PackPs1 Class Reference
PackPs1 Class Reference final
ps1/exe
#include <p_ps1.h>
Classes
struct bss_nfo
struct ps1_exe_chb_t
struct ps1_exe_hb_t
struct ps1_exe_t
Public Member Functions
PackPs1 (InputFile *f)
ps1 exe looks like this:
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
void putBkupHeader (const byte *src, byte *dst, unsigned *len)
bool getBkupHeader (byte *src, byte *dst)
bool readBkupHeader ()
virtual void buildLoader (const Filter *ft) override
bool findBssSection ()
virtual Linker * newLinker () const override
int readFileHeader ()
util readFileHeader() reads ih and checks for illegal values checkFileHeader() checks ih for legal but unsupported values
bool checkFileHeader ()
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
ps1_exe_t ih = {}
ps1_exe_t oh = {}
ps1_exe_hb_t bh = {}
bool isCon = false
bool is32Bit = false
bool buildPart2 = false
bool foundBss = false
unsigned ram_size = 0
unsigned sa_cnt = 0
unsigned overlap = 0
unsigned sz_lunc = 0
unsigned sz_lcpr = 0
unsigned pad_code = 0
unsigned bss_start = 0
unsigned bss_end = 0
unsigned fdata_size = 0
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
ps1/exe
Definition at line 38 of file p_ps1.h.
Member Typedef Documentation
super
typedef Packer PackPs1::super private
Definition at line 39 of file p_ps1.h.
Constructor & Destructor Documentation
PackPs1()
PackPs1::PackPs1 (InputFile * f) explicit
ps1 exe looks like this:
<header> 2048 bytes
<body> plain binary
header: contains the ps1_exe_t structure 188 bytes at offset zero rest is filled with zeros to reach the required cd mode 2 data sector size of 2048 bytes body: contains the binary data / code of the executable reqiures: executable code must be aligned to 4 must be aligned to 2048 to run from a CD optional: not aligned to 2048 (for console run only)
Definition at line 77 of file p_ps1.cpp.
    : super(f), isCon(!opt->ps1_exe.boot_only), is32Bit(!opt->ps1_exe.do_8bit) {
    bele = &N_BELE_RTP::le_policy;
    COMPILE_TIME_ASSERT(sizeof(ps1_exe_t) == 136)
    COMPILE_TIME_ASSERT(sizeof(ps1_exe_hb_t) == 44)
    COMPILE_TIME_ASSERT(sizeof(ps1_exe_chb_t) == 5)
    COMPILE_TIME_ASSERT_ALIGNED1(ps1_exe_t)
    COMPILE_TIME_ASSERT_ALIGNED1(ps1_exe_hb_t)
    COMPILE_TIME_ASSERT_ALIGNED1(ps1_exe_chb_t)
    COMPILE_TIME_ASSERT(PS_HDR_SIZE > sizeof(ps1_exe_t))
    COMPILE_TIME_ASSERT(SZ_IH_BKUP == 40)
    fdata_size = file_size - PS_HDR_SIZE;
    ram_size = !opt->ps1_exe.do_8mib ? 0x200000 : 0x800000;
}
References Packer::bele, COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, fdata_size, PackerBase::file_size, N_BELE_RTP::le_policy, opt, PS_HDR_SIZE, ram_size, and SZ_IH_BKUP.
Member Function Documentation
buildLoader()
void PackPs1::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 252 of file p_ps1.cpp.
{
    const char *method = nullptr;
    if (ph.method == M_NRV2B_8)
        method = isCon ? "nrv2b.small,8bit.sub,nrv.done" : "nrv2b.8bit,nrv.done";
    else if (ph.method == M_NRV2D_8)
        method = isCon ? "nrv2d.small,8bit.sub,nrv.done" : "nrv2d.8bit,nrv.done";
    else if (ph.method == M_NRV2E_8)
        method = isCon ? "nrv2e.small,8bit.sub,nrv.done" : "nrv2e.8bit,nrv.done";
    else if (ph.method == M_NRV2B_LE32)
        method = isCon ? "nrv2b.small,32bit.sub,nrv.done" : "nrv2b.32bit,nrv.done";
    else if (ph.method == M_NRV2D_LE32)
        method = isCon ? "nrv2d.small,32bit.sub,nrv.done" : "nrv2d.32bit,nrv.done";
    else if (ph.method == M_NRV2E_LE32)
        method = isCon ? "nrv2e.small,32bit.sub,nrv.done" : "nrv2e.32bit,nrv.done";
    else if (M_IS_LZMA(ph.method))
        method = "nrv2b.small,8bit.sub,nrv.done,lzma.prep";
    else
        throwInternalError("unknown compression method");
    unsigned sa_tmp = sa_cnt;
    if (ph.overlap_overhead > sa_cnt) {
        if (!opt->force) {
            infoWarning("not in-place decompressible");
            throwCantPack("packed data overlap (try --force)");
        } else
            sa_tmp += overlap = ALIGN_UP((ph.overlap_overhead - sa_tmp), 4u);
    }
    if (isCon || M_IS_LZMA(ph.method))
        foundBss = findBssSection();
    if (M_IS_LZMA(ph.method) && !buildPart2) {
        initLoader(stub_mipsel_r3000_ps1, sizeof(stub_mipsel_r3000_ps1));
        addLoader("decompressor.start", isCon ? "LZMA_DEC20" : "LZMA_DEC10", "lzma.init", nullptr);
        addLoader(sa_tmp > (0x10000 << 2) ? "memset.long" : "memset.short",
                  !foundBss ? "con.exit" : "bss.exit", nullptr);
    } else {
        if (M_IS_LZMA(ph.method) && buildPart2) {
            sz_lcpr = MemBuffer::getSizeForCompression(sz_lunc);
            byte *cprLoader = New(byte, sz_lcpr); // FIXME: does this leak? => should put into class
            int r = upx_compress(getLoader(), sz_lunc, cprLoader, &sz_lcpr, nullptr, M_NRV2B_8, 10,
                                 nullptr, nullptr);
            if (r != UPX_E_OK || sz_lcpr >= sz_lunc)
                throwInternalError("loader compression failed");
            initLoader(stub_mipsel_r3000_ps1, sizeof(stub_mipsel_r3000_ps1),
                       isCon || !M_IS_LZMA(ph.method) ? 0 : 1);
            linker->addSection("lzma.exec", cprLoader, sz_lcpr, 0);
        } else
            initLoader(stub_mipsel_r3000_ps1, sizeof(stub_mipsel_r3000_ps1));
        pad_code = ALIGN_UP_GAP((ph.c_len + (isCon ? sz_lcpr : 0)), 4u);
        assert(pad_code < 4);
        static const byte pad_buffer[4] = {0, 0, 0, 0};
        linker->addSection("pad.code", pad_buffer, pad_code, 0);
        if (isCon) {
            if (M_IS_LZMA(ph.method))
                addLoader(!foundBss ? "con.start" : "bss.con.start", method,
                          ih.tx_ptr & 0xffff ? "dec.ptr" : "dec.ptr.hi", "con.entry", "pad.code",
                          "lzma.exec", nullptr);
            else
                addLoader(!foundBss ? "con.start" : "bss.con.start", "con.mcpy",
                          ph.c_len & 3 ? "con.padcd" : "",
                          ih.tx_ptr & 0xffff ? "dec.ptr" : "dec.ptr.hi", "con.entry", method,
                          sa_cnt ? sa_cnt > (0x10000 << 2) ? "memset.long" : "memset.short" : "",
                          !foundBss ? "con.exit" : "bss.exit", "pad.code", nullptr);
        } else {
            if (M_IS_LZMA(ph.method))
                addLoader(!foundBss ? "cdb.start.lzma" : "bss.cdb.start.lzma", "pad.code",
                          !foundBss ? "cdb.entry.lzma" : "bss.cdb.entry.lzma", method,
                          "cdb.lzma.cpr", ih.tx_ptr & 0xffff ? "dec.ptr" : "dec.ptr.hi",
                          "lzma.exec", nullptr);
            else {
                assert(foundBss != true);
                addLoader("cdb.start", "pad.code", "cdb.entry",
                          ih.tx_ptr & 0xffff ? "cdb.dec.ptr" : "cdb.dec.ptr.hi", method,
                          sa_cnt ? sa_cnt > (0x10000 << 2) ? "memset.long" : "memset.short" : "",
                          "cdb.exit", nullptr);
            }
        }
        addLoader("UPX1HEAD", "IDENTSTR", nullptr);
    }
}
References Packer::addLoader(), ALIGN_UP, ALIGN_UP_GAP, buildPart2, PackHeader::c_len, findBssSection(), foundBss, Packer::getLoader(), MemBuffer::getSizeForCompression(), ih, infoWarning(), Packer::initLoader(), isCon, M_IS_LZMA, M_NRV2B_8, M_NRV2B_LE32, M_NRV2D_8, M_NRV2D_LE32, M_NRV2E_8, M_NRV2E_LE32, PackHeader::method, New, opt, overlap, PackHeader::overlap_overhead, pad_code, PackerBase::ph, sa_cnt, stub_mipsel_r3000_ps1, sz_lcpr, sz_lunc, throwCantPack(), throwInternalError(), PackPs1::ps1_exe_t::tx_ptr, upx_compress(), and UPX_E_OK.
Referenced by pack().
canPack()
tribool PackPs1::canPack () override virtual
Implements PackerBase.
Definition at line 219 of file p_ps1.cpp.
{
    byte buf[PS_HDR_SIZE - sizeof(ps1_exe_t)];
    if (!readFileHeader())
        return false;
    fi->readx(buf, sizeof(buf));
    checkAlreadyPacked(buf, sizeof(buf));
    for (size_t i = 0; i < sizeof(buf); i++)
        if (buf[i] != 0) {
            if (!opt->force)
                throwCantPack("unknown data in header (try --force)");
            else {
                opt->info_mode += !opt->info_mode ? 1 : 0;
                infoWarning("clearing header, keeping backup file");
                opt->backup = 1;
                break;
            }
        }
    if (!checkFileHeader())
        throwCantPack("unsupported header flags (try --force)");
    if (!opt->force && file_size < PS_MIN_SIZE)
        throwCantPack("file is too small (try --force)");
    if (!opt->force && file_size_u > PS_MAX_SIZE)
        throwCantPack("file is too big (try --force)");
    return true;
}
References buf, Packer::checkAlreadyPacked(), checkFileHeader(), PackerBase::fi, PackerBase::file_size, PackerBase::file_size_u, infoWarning(), opt, PS_HDR_SIZE, PS_MAX_SIZE, PS_MIN_SIZE, readFileHeader(), InputFile::readx(), and throwCantPack().
canUnpack()
tribool PackPs1::canUnpack () override virtual
Implements PackerBase.
Definition at line 613 of file p_ps1.cpp.
{
    if (!readFileHeader())
        return false;
    if (!readPackHeader(CD_SEC))
        return false;
    // check header as set by packer
    if (!readBkupHeader() || ph.c_len >= fdata_size)
        throwCantUnpack("header damaged");
    // generic check
    if (!checkFileHeader())
        throwCantUnpack("unsupported header flags");
    return true;
}
References PackHeader::c_len, CD_SEC, checkFileHeader(), fdata_size, PackerBase::ph, readBkupHeader(), readFileHeader(), Packer::readPackHeader(), and throwCantUnpack().
checkFileHeader()
bool PackPs1::checkFileHeader () protected
Definition at line 191 of file p_ps1.cpp.
{
    if (fdata_size != ih.tx_len || (ih.tx_len & 3)) {
        if (!opt->force)
            throwCantPack("file size entry damaged (try --force)");
        else {
            opt->info_mode += !opt->info_mode ? 1 : 0;
            infoWarning("fixing damaged header, keeping backup file");
            opt->backup = 1;
            ih.tx_len = fdata_size;
        }
    }
    if (!opt->force && (ih.da_ptr != 0 || ih.da_len != 0 || ih.bs_ptr != 0 || ih.bs_len != 0)) {
        infoWarning("unsupported header field entry");
        return false;
    }
    if (ih.is_ptr < (EXE_BS | (PS_RAM_SIZE - PS_STACK_SIZE))) {
        if (!opt->force)
            return false;
        else
            infoWarning("%s: stack pointer offset low", fi->getName());
    }
    return true;
}
References PackPs1::ps1_exe_t::bs_len, PackPs1::ps1_exe_t::bs_ptr, PackPs1::ps1_exe_t::da_len, PackPs1::ps1_exe_t::da_ptr, EXE_BS, fdata_size, PackerBase::fi, FileBase::getName(), ih, infoWarning(), PackPs1::ps1_exe_t::is_ptr, opt, PS_RAM_SIZE, PS_STACK_SIZE, throwCantPack(), and PackPs1::ps1_exe_t::tx_len.
Referenced by canPack(), and canUnpack().
findBssSection()
bool PackPs1::findBssSection () protected
Definition at line 358 of file p_ps1.cpp.
{
    byte reg;
    const LE32 *const p1 = ACC_CCAST(const LE32 *, ibuf + (ih.epc - ih.tx_ptr));
    if ((ih.epc - ih.tx_ptr + (BSS_CHK_LIMIT * 4)) > fdata_size)
        return false;
    // check 18 opcodes for sw zero,0(x)
    for (signed i = BSS_CHK_LIMIT; i >= 0; i--) {
        upx_uint16_t op = p1[i] >> 16;
        if (IS_SW_ZERO(op)) {
            // found! get reg (x) for bss_start
            reg = REG1(op);
            for (; i >= 0; i--) {
                const bss_nfo *const p = ACC_CCAST(const bss_nfo *, &p1[i]);
                upx_uint16_t op1 = p->op1, op2 = p->op2;
                // check for la (x),bss_start
                if ((IS_LUI(op1) && REG2(op1) == reg) && (IS_ADDIU(op2) && REG1(op2) == reg)) {
                    op1 = p->op3, op2 = p->op4;
                    // check for la (y),bss_end
                    if (IS_LUI(op1) && IS_ADDIU(op2)) {
                        // bss section info found!
                        bss_start = MIPS_IMM(p->hi1, p->lo1);
                        bss_end = MIPS_IMM(p->hi2, p->lo2);
                        if (0 < ALIGN_DOWN(bss_end - bss_start, 4u)) {
                            unsigned wkmem_sz = M_IS_LZMA(ph.method) ? 32768 : 800;
                            unsigned end_offs = ih.tx_ptr + fdata_size + overlap;
                            if (bss_end > (end_offs + wkmem_sz))
                                return isCon || (!isCon && M_IS_LZMA(ph.method));
                            else
                                return false;
                        }
                    } else
                        return false;
                }
            }
        }
    }
    return false;
}
References ACC_CCAST, ALIGN_DOWN, BSS_CHK_LIMIT, bss_end, bss_start, PackPs1::ps1_exe_t::epc, fdata_size, PackPs1::bss_nfo::hi1, PackPs1::bss_nfo::hi2, Packer::ibuf, ih, IS_ADDIU, IS_LUI, IS_SW_ZERO, isCon, PackPs1::bss_nfo::lo1, PackPs1::bss_nfo::lo2, M_IS_LZMA, PackHeader::method, MIPS_IMM, PackPs1::bss_nfo::op1, PackPs1::bss_nfo::op2, PackPs1::bss_nfo::op3, PackPs1::bss_nfo::op4, overlap, PackerBase::ph, REG1, REG2, and PackPs1::ps1_exe_t::tx_ptr.
Referenced by buildLoader().
getBkupHeader()
bool PackPs1::getBkupHeader (byte * src, byte * dst) protected
Definition at line 168 of file p_ps1.cpp.
{
    ps1_exe_chb_t *src = (ps1_exe_chb_t *) p;
    if (src && (src->id == '1' && src->len < SZ_IH_BKUP) && dst) {
        ByteArray(unc_bh, MemBuffer::getSizeForDecompression(SZ_IH_BKUP));
        unsigned sz_bh = SZ_IH_BKUP;
        int r = upx_decompress((const byte *) &src->ih_bkup, src->len, unc_bh, &sz_bh, M_NRV2E_8,
                               nullptr);
        if (r == UPX_E_OUT_OF_MEMORY)
            throwOutOfMemoryException();
        if (r != UPX_E_OK || sz_bh != SZ_IH_BKUP)
            throwInternalError("header decompression failed");
        unsigned ad = upx_adler32(unc_bh, SZ_IH_BKUP);
        unsigned ch = src->ih_csum;
        if (ad != RE_ADLER16(ad, ch))
            throwInternalError("backup header damaged");
        memcpy(dst, unc_bh, SZ_IH_BKUP);
    } else
        return false;
    return true;
}
References ByteArray, ch, MemBuffer::getSizeForDecompression(), PackPs1::ps1_exe_chb_t::id, PackPs1::ps1_exe_chb_t::ih_bkup, PackPs1::ps1_exe_chb_t::ih_csum, PackPs1::ps1_exe_chb_t::len, M_NRV2E_8, memcpy(), RE_ADLER16, SZ_IH_BKUP, throwInternalError(), throwOutOfMemoryException(), upx_adler32(), upx_decompress(), UPX_E_OK, and UPX_E_OUT_OF_MEMORY.
Referenced by readBkupHeader().
getCompressionMethods()
const int * PackPs1::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 95 of file p_ps1.cpp.
{
    if (is32Bit)
        return Packer::getDefaultCompressionMethods_le32(method, level);
    else
        return Packer::getDefaultCompressionMethods_8(method, level);
}
References Packer::getDefaultCompressionMethods_8(), Packer::getDefaultCompressionMethods_le32(), and is32Bit.
getFilters()
const int * PackPs1::getFilters () const override virtual
Implements PackerBase.
Definition at line 102 of file p_ps1.cpp.
{ return nullptr; }
getFormat()
virtual int PackPs1::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 44 of file p_ps1.h.
{ return UPX_F_PS1_EXE; }
References UPX_F_PS1_EXE.
getFullName()
virtual const char * PackPs1::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 46 of file p_ps1.h.
{ return "mipsel.r3000-ps1"; }
getName()
virtual const char * PackPs1::getName () const inline override virtual
Implements PackerBase.
Definition at line 45 of file p_ps1.h.
{ return "ps1/exe"; }
Referenced by pack().
getVersion()
virtual int PackPs1::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 43 of file p_ps1.h.
{ return 13; }
newLinker()
Linker * PackPs1::newLinker () const override protected virtual
Implements Packer.
Definition at line 104 of file p_ps1.cpp.
{ return new ElfLinkerMipsLE; }
pack()
void PackPs1::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 406 of file p_ps1.cpp.
{
    ibuf.alloc(fdata_size);
    obuf.allocForCompression(fdata_size);
    const byte *p_scan = ibuf + fdata_size;
    // read file
    fi->seek(PS_HDR_SIZE, SEEK_SET);
    fi->readx(ibuf, fdata_size);
    // scan EOF for 2048 bytes sector alignment
    // the removed space will secure in-place decompression
    while (!(*--p_scan)) {
        if (sa_cnt++ > (0x10000 << 5) || sa_cnt >= fdata_size - 1024)
            break;
    }
    if (sa_cnt > (0x10000 << 2))
        sa_cnt = ALIGN_DOWN(sa_cnt, 32u);
    else
        sa_cnt = ALIGN_DOWN(sa_cnt, 4u);
    // prepare packheader
    ph.u_len = (fdata_size - sa_cnt);
    ph.filter = 0;
    Filter ft(ph.level);
    // compress (max_match = 65535)
    upx_compress_config_t cconf;
    cconf.reset();
    cconf.conf_ucl.max_match = 65535;
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    compressWithFilters(&ft, sa_cnt, &cconf);
    if (overlap) {
        opt->info_mode += !opt->info_mode ? 1 : 0;
        infoWarning("overlap - relocating load address (+%d bytes)", overlap);
        sa_cnt += overlap;
    }
    /*
        if (bss_start && bss_end && !foundBss)
            infoWarning("%s: .bss section too small - use stack", fi->getName());
    */
    unsigned lzma_init = 0;
    if (M_IS_LZMA(ph.method)) {
        sz_lunc = getLoaderSize();
        lzma_init = 0u - (sz_lunc - linker->getSymbolOffset("lzma.init"));
        defineDecompressorSymbols();
        linker->defineSymbol("entry", ih.epc);
        linker->defineSymbol("SC", sa_cnt > (0x10000 << 2) ? sa_cnt >> 5 : sa_cnt >> 2);
        relocateLoader();
        buildPart2 = true;
        buildLoader(&ft);
    }
    memcpy(&oh, &ih, sizeof(ih));
    unsigned sz_cbh;
    putBkupHeader((const byte *) &ih.epc, (byte *) &bh, &sz_cbh);
    if (ih.is_ptr < (EXE_BS | (PS_RAM_SIZE - PS_STACK_SIZE)))
        oh.is_ptr = (EXE_BS | (PS_RAM_SIZE - 16));
    if (ih.da_ptr != 0 || ih.da_len != 0 || ih.bs_ptr != 0 || ih.bs_len != 0)
        oh.da_ptr = oh.da_len = oh.bs_ptr = oh.bs_len = 0;
    const int lsize = getLoaderSize();
    unsigned filelen = ALIGN_UP(ih.tx_len, 4u);
    const unsigned decomp_data_start = ih.tx_ptr;
    const unsigned comp_data_start = (decomp_data_start + filelen + overlap) - ph.c_len;
    const int h_len = lsize - getLoaderSectionStart("UPX1HEAD");
    int d_len = 0;
    int e_len = 0;
    if (isCon) {
        e_len = lsize - h_len;
        d_len = e_len - getLoaderSectionStart("con.entry");
    } else {
        const char *entry_lzma = !foundBss ? "cdb.entry.lzma" : "bss.cdb.entry.lzma";
        d_len = (lsize - h_len) -
                getLoaderSectionStart(M_IS_LZMA(ph.method) ? entry_lzma : "cdb.entry");
        e_len = (lsize - d_len) - h_len;
    }
    linker->defineSymbol("entry", ih.epc);
    linker->defineSymbol("SC", MIPS_LO(sa_cnt > (0x10000 << 2) ? sa_cnt >> 5 : sa_cnt >> 2));
    linker->defineSymbol("DECO", decomp_data_start);
    linker->defineSymbol("ldr_sz", M_IS_LZMA(ph.method) ? sz_lunc + 16 : (d_len - pad_code));
    if (foundBss) {
        if (M_IS_LZMA(ph.method))
            linker->defineSymbol("wrkmem",
                                 bss_end - 160 - getDecompressorWrkmemSize() - (sz_lunc + 16));
        else
            linker->defineSymbol("wrkmem", bss_end - 16 - (d_len - pad_code));
    }
    const unsigned entry = comp_data_start - e_len;
    oh.epc = oh.tx_ptr = entry;
    oh.tx_len = ph.c_len + e_len;
    unsigned pad = 0;
    if (!opt->ps1_exe.no_align || !isCon) {
        pad = oh.tx_len;
        oh.tx_len = ALIGN_UP(oh.tx_len, CD_SEC + 0u);
        pad = oh.tx_len - pad;
        oh.tx_ptr -= pad;
    }
    ibuf.clear(0, fdata_size);
    byte *paddata = ibuf;
    if (M_IS_LZMA(ph.method)) {
        linker->defineSymbol("lzma_init_off", lzma_init);
        linker->defineSymbol("gb_e", linker->getSymbolOffset("gb8_e"));
    } else if (isCon)
        linker->defineSymbol("gb_e", linker->getSymbolOffset(is32Bit ? "gb32_e" : "gb8_e"));
    if (isCon) {
        linker->defineSymbol("PAD", pad_code);
        if (M_IS_LZMA(ph.method))
            linker->defineSymbol("DCRT", (entry + getLoaderSectionStart("lzma.exec")));
        else
            linker->defineSymbol("DCRT", (entry + (e_len - d_len)));
    } else {
        linker->defineSymbol("PSVR", FIX_PSVR);
        linker->defineSymbol("CPDO", comp_data_start);
        if (M_IS_LZMA(ph.method)) {
            unsigned entry_lzma =
                getLoaderSectionStart(!foundBss ? "cdb.entry.lzma" : "bss.cdb.entry.lzma");
            linker->defineSymbol("lzma_cpr", getLoaderSectionStart("lzma.exec") - entry_lzma);
        }
    }
    relocateLoader();
    // linker->dumpSymbols();
    MemBuffer loader(lsize);
    assert(lsize == getLoaderSize());
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, lsize);
    if (!isCon && M_IS_LZMA(ph.method) && (HD_CODE_OFS + d_len + h_len) > CD_SEC)
        throwInternalError("lzma --boot-only loader > 2048");
    // ps1_exe_t structure
    fo->write(&oh, sizeof(oh));
    fo->write(&bh, sz_cbh);
    // decompressor
    fo->write(loader + e_len, isCon ? h_len : (d_len + h_len));
    // header size is 2048 bytes + sector alignment
    fo->write(paddata, (pad + PS_HDR_SIZE) - fo->getBytesWritten());
    // entry
    fo->write(loader, e_len);
    // compressed body
    fo->write(obuf, ph.c_len);
    verifyOverlappingDecompression();
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
#if 0
    printf("%-13s: uncompressed  : %8d bytes\n", getName(), (int) ph.u_len);
    printf("%-13s: compressed    : %8d bytes\n", getName(), (int) ph.c_len);
    printf("%-13s: decompressor  : %8d bytes\n", getName(), (int) lsize - h_len - pad_code);
    printf("%-13s: header comp   : %8d bytes\n", getName(), (int) sz_cbh);
    printf("%-13s: overlap       : %8d bytes\n", getName(), (int) overlap);
    printf("%-13s: load address  : %08X bytes\n", getName(), (unsigned) oh.tx_ptr);
    printf("%-13s: code entry    : %08X bytes\n", getName(), (unsigned) oh.epc);
    printf("%-13s: bbs start     : %08X bytes\n", getName(), (unsigned) bss_start);
    printf("%-13s: bbs end       : %08X bytes\n", getName(), (unsigned) bss_end);
    printf("%-13s: eof in mem IF : %08X bytes\n", getName(), (unsigned) ih.tx_ptr + ih.tx_len);
    printf("%-13s: eof in mem OF : %08X bytes\n", getName(), (unsigned) oh.tx_ptr + oh.tx_len);
    byte i = 0;
    if (isCon) {
        if (foundBss)
            i = 1;
    } else {
        i = 2;
        if (M_IS_LZMA(ph.method)) {
            if (!foundBss)
                i = 3;
            else
                i = 4;
        }
    }
    const char *loader_method[] = {"con/stack", "con/bss", "cdb", "cdb/stack", "cdb/bss"};
    char method_name[32 + 1];
    set_method_name(method_name, sizeof(method_name), ph.method, ph.level);
    printf("%-13s: methods       : %s, %s\n", getName(), method_name, loader_method[i]);
#endif
}
References ALIGN_DOWN, ALIGN_UP, MemBuffer::alloc(), MemBuffer::allocForCompression(), bh, PackPs1::ps1_exe_t::bs_len, PackPs1::ps1_exe_t::bs_ptr, bss_end, bss_start, buildLoader(), buildPart2, PackHeader::c_len, CD_SEC, Packer::checkFinalCompressionRatio(), MemBuffer::clear(), Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, upx_compress_config_t::conf_ucl, PackPs1::ps1_exe_t::da_len, PackPs1::ps1_exe_t::da_ptr, Packer::defineDecompressorSymbols(), PackPs1::ps1_exe_t::epc, EXE_BS, fdata_size, PackerBase::fi, PackHeader::filter, FIX_PSVR, foundBss, OutputFile::getBytesWritten(), Packer::getDecompressorWrkmemSize(), Packer::getLoader(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), getName(), HD_CODE_OFS, Packer::ibuf, ih, infoWarning(), is32Bit, PackPs1::ps1_exe_t::is_ptr, isCon, PackHeader::level, M_IS_LZMA, lzma_compress_config_t::max_num_probs, memcpy(), PackHeader::method, MIPS_LO, Packer::obuf, oh, opt, overlap, pad_code, Packer::patchPackHeader(), PackerBase::ph, PS_HDR_SIZE, PS_RAM_SIZE, PS_STACK_SIZE, putBkupHeader(), InputFile::readx(), Packer::relocateLoader(), upx_compress_config_t::reset(), sa_cnt, InputFile::seek(), SEEK_SET, set_method_name(), sz_lunc, throwInternalError(), throwNotCompressible(), PackPs1::ps1_exe_t::tx_len, PackPs1::ps1_exe_t::tx_ptr, PackHeader::u_len, Packer::verifyOverlappingDecompression(), and OutputFile::write().
putBkupHeader()
void PackPs1::putBkupHeader (const byte * src, byte * dst, unsigned * len) protected
Definition at line 143 of file p_ps1.cpp.
{
    unsigned sz_cbh = MemBuffer::getSizeForCompression(SZ_IH_BKUP);
    if (src && dst) {
        ByteArray(cpr_bh, sz_cbh);
        memset(cpr_bh, 0, sizeof(bh));
        ps1_exe_chb_t *p = (ps1_exe_chb_t *) cpr_bh;
        int r = upx_compress(src, SZ_IH_BKUP, &p->ih_bkup, &sz_cbh, nullptr, M_NRV2E_8, 10, nullptr,
                             nullptr);
        if (r != UPX_E_OK || sz_cbh >= SZ_IH_BKUP)
            throwInternalError("header compression failed");
        INIT_BH_BKUP(p, sz_cbh);
        *len = ALIGN_UP(sz_cbh + usizeof(ps1_exe_chb_t) - 1, 4u);
        p->ih_csum = ADLER16(upx_adler32(&ih.epc, SZ_IH_BKUP));
        memcpy(dst, cpr_bh, SZ_IH_BKUP);
    } else
        throwInternalError("header compression failed");
}
References ADLER16, ALIGN_UP, bh, ByteArray, PackPs1::ps1_exe_t::epc, MemBuffer::getSizeForCompression(), ih, PackPs1::ps1_exe_chb_t::ih_bkup, PackPs1::ps1_exe_chb_t::ih_csum, INIT_BH_BKUP, M_NRV2E_8, memcpy(), memset(), SZ_IH_BKUP, throwInternalError(), upx_adler32(), upx_compress(), UPX_E_OK, and usizeof.
Referenced by pack().
readBkupHeader()
bool PackPs1::readBkupHeader () protected
Definition at line 122 of file p_ps1.cpp.
{
    fi->seek(sizeof(ps1_exe_t) + 8, SEEK_SET);
    fi->readx(&bh, sizeof(bh));
    if (bh.ih_csum != upx_adler32(&bh, SZ_IH_BKUP)) {
        byte buf[sizeof(bh)];
        fi->seek(sizeof(ps1_exe_t), SEEK_SET);
        fi->readx(buf, sizeof(bh));
        if (!getBkupHeader(buf, (byte *) &bh))
            return false;
    }
    return true;
}
References bh, buf, PackerBase::fi, getBkupHeader(), PackPs1::ps1_exe_hb_t::ih_csum, InputFile::readx(), InputFile::seek(), SEEK_SET, SZ_IH_BKUP, and upx_adler32().
Referenced by canUnpack().
readFileHeader()
int PackPs1::readFileHeader () protected
util readFileHeader() reads ih and checks for illegal values checkFileHeader() checks ih for legal but unsupported values
Definition at line 112 of file p_ps1.cpp.
{
    fi->seek(0, SEEK_SET);
    fi->readx(&ih, sizeof(ih));
    if (memcmp(&ih.id[0], "PS-X EXE", 8) != 0 && memcmp(&ih.id[0], "EXE X-SP", 8) != 0)
        return 0;
    if (ih.text != 0 || ih.data != 0)
        return 0;
    return UPX_F_PS1_EXE;
}
References PackPs1::ps1_exe_t::data, PackerBase::fi, PackPs1::ps1_exe_t::id, ih, memcmp(), InputFile::readx(), InputFile::seek(), SEEK_SET, PackPs1::ps1_exe_t::text, and UPX_F_PS1_EXE.
Referenced by canPack(), and canUnpack().
unpack()
void PackPs1::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 631 of file p_ps1.cpp.
{
    // restore orig exec hdr
    memcpy(&oh, &ih, sizeof(ih));
    memcpy((void *) &oh.epc, &bh, SZ_IH_BKUP);
    // check for removed sector alignment
    assert(oh.tx_len >= ph.u_len);
    const unsigned pad = oh.tx_len - ph.u_len;
    ibuf.alloc(fdata_size > PS_HDR_SIZE ? fdata_size : PS_HDR_SIZE);
    obuf.allocForDecompression(ph.u_len, pad);
    fi->seek(PS_HDR_SIZE, SEEK_SET);
    fi->readx(ibuf, fdata_size);
    // decompress
    decompress(ibuf + (fdata_size - ph.c_len), obuf);
    // write decompressed file
    if (fo) {
        // write header
        fo->write(&oh, sizeof(oh));
        // align the ps exe header (mode 2 sector data size)
        ibuf.clear();
        fo->write(ibuf, PS_HDR_SIZE - fo->getBytesWritten());
        // write uncompressed data + pad
        obuf.clear(ph.u_len, pad);
        fo->write(obuf, ph.u_len + pad);
    }
}
References MemBuffer::alloc(), MemBuffer::allocForDecompression(), bh, PackHeader::c_len, MemBuffer::clear(), Packer::decompress(), PackPs1::ps1_exe_t::epc, fdata_size, PackerBase::fi, OutputFile::getBytesWritten(), Packer::ibuf, ih, memcpy(), Packer::obuf, oh, PackerBase::ph, PS_HDR_SIZE, InputFile::readx(), InputFile::seek(), SEEK_SET, SZ_IH_BKUP, PackPs1::ps1_exe_t::tx_len, PackHeader::u_len, and OutputFile::write().
Member Data Documentation
bh
ps1_exe_hb_t PackPs1::bh = {} protected
Definition at line 112 of file p_ps1.h.
Referenced by pack(), putBkupHeader(), readBkupHeader(), and unpack().
bss_end
unsigned PackPs1::bss_end = 0 protected
Definition at line 122 of file p_ps1.h.
Referenced by findBssSection(), and pack().
bss_start
unsigned PackPs1::bss_start = 0 protected
Definition at line 122 of file p_ps1.h.
Referenced by findBssSection(), and pack().
buildPart2
bool PackPs1::buildPart2 = false protected
Definition at line 116 of file p_ps1.h.
Referenced by buildLoader(), and pack().
fdata_size
unsigned PackPs1::fdata_size = 0 protected
Definition at line 124 of file p_ps1.h.
Referenced by canUnpack(), checkFileHeader(), findBssSection(), pack(), PackPs1(), and unpack().
foundBss
bool PackPs1::foundBss = false protected
Definition at line 117 of file p_ps1.h.
Referenced by buildLoader(), and pack().
ih
ps1_exe_t PackPs1::ih = {} protected
Definition at line 111 of file p_ps1.h.
Referenced by buildLoader(), checkFileHeader(), findBssSection(), pack(), putBkupHeader(), readFileHeader(), and unpack().
is32Bit
bool PackPs1::is32Bit = false protected
Definition at line 115 of file p_ps1.h.
Referenced by getCompressionMethods(), and pack().
isCon
bool PackPs1::isCon = false protected
Definition at line 114 of file p_ps1.h.
Referenced by buildLoader(), findBssSection(), and pack().
oh
ps1_exe_t PackPs1::oh = {} protected
Definition at line 111 of file p_ps1.h.
Referenced by pack(), and unpack().
overlap
unsigned PackPs1::overlap = 0 protected
Definition at line 119 of file p_ps1.h.
Referenced by buildLoader(), findBssSection(), and pack().
pad_code
unsigned PackPs1::pad_code = 0 protected
Definition at line 121 of file p_ps1.h.
Referenced by buildLoader(), and pack().
ram_size
unsigned PackPs1::ram_size = 0 protected
Definition at line 118 of file p_ps1.h.
Referenced by PackPs1().
sa_cnt
unsigned PackPs1::sa_cnt = 0 protected
Definition at line 119 of file p_ps1.h.
Referenced by buildLoader(), and pack().
sz_lcpr
unsigned PackPs1::sz_lcpr = 0 protected
Definition at line 120 of file p_ps1.h.
Referenced by buildLoader().
sz_lunc
unsigned PackPs1::sz_lunc = 0 protected
Definition at line 120 of file p_ps1.h.
Referenced by buildLoader(), and pack().
The documentation for this class was generated from the following files:
src/p_ps1.h
src/p_ps1.cpp