My Project: PeFile32 Class Reference
PeFile32 Class Reference
#include <pefile.h>
Classes
struct pe_header_t
Protected Member Functions
virtual void processRelocs () override
pack0
create UPX0 section
Reduct the file size.
Parameters
fo The OutputFile class to the path where the new file will be created.
ih Input PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header .
Parameters
oh Output PE header.
Native windows data structure required by the os to be understood and to make a valid executable. The documentation of this data type is present there: https://www.vergiliusproject.com/kernels/x64/windows-11/23h2/_IMAGE_FILE_HEADER and described there: https://wiki.osdev.org/PE#PE_header .
Parameters
subsystem_mask Permission mask for UPX0, UPX1, etc... sections.
Number between 0 and 255 to indicate the section permissions of the section UPX0, UPX1, etc...
Parameters
default_imagebase Base address of the image base of the process.
Very first start of where is stored the data and the code run by the OS.
Parameters
last_section_rsrc_only This is true when the last PE section of the compressed file must only contain resources and must be called "rsrc"
Returns
void, in any circonstance.
Remarks
None.
PeFile32 (InputFile *f)
PeFile32.
virtual ~PeFile32 () noexcept
PeFile32.
void pack0 (OutputFile *fo, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only)
PeFile32.
virtual void unpack (OutputFile *fo) override
PeFile32.
virtual tribool canUnpack () override
PeFile32.
virtual void readPeHeader () override
PeFile32.
virtual unsigned processImports () override
PeFile32.
virtual void processTls (Interval *) override
PeFile32.
virtual void processTls (Reloc *, const Interval *, unsigned) override
PeFile32.
Protected Member Functions inherited from PeFile
PeFile (InputFile *f)
void readSectionHeaders (unsigned objs, unsigned sizeof_ih)
pack
unsigned readSections (unsigned objs, unsigned usize, unsigned ih_filealign, unsigned ih_datasize)
void checkHeaderValues (unsigned subsystem, unsigned mask, unsigned ih_entry, unsigned ih_filealign)
unsigned handleStripRelocs (upx_uint64_t ih_imagebase, upx_uint64_t default_imagebase, LE16 &dllflags)
virtual bool needForceOption () const =0
virtual void callCompressWithFilters (Filter &, int filter_strategy, unsigned ih_codebase)
virtual void defineSymbols (unsigned ncsection, unsigned upxsection, unsigned sizeof_oh, unsigned isize_isplit, unsigned s1addr)=0
virtual void addNewRelocations (Reloc &, unsigned)
void callProcessStubRelocs (Reloc &rel, unsigned &ic)
void callProcessResources (Resource &res, unsigned &ic)
virtual unsigned getProcessImportParam (unsigned)
virtual void setOhDataBase (const pe_section_t *osection)=0
virtual void setOhHeaderSize (const pe_section_t *osection)=0
virtual bool canUnpackVersion (int version) const override
virtual int readFileHeader ()
virtual bool testUnpackVersion (int version) const override
virtual void readPeHeader ()=0
template<typename LEXX , typename ord_mask_t >
unsigned processImports0 (ord_mask_t ord_mask)
virtual unsigned processImports ()=0
virtual void processImports2 (unsigned, unsigned)
SPAN_0 (byte) oimport
virtual const char * kernelDll () const
void addKernelImport (const char *)
virtual void addStubImports ()
virtual void processRelocs ()=0
SPAN_0 (byte) orelocs
void processExports (Export *)
void processExports (Export *, unsigned)
SPAN_0 (byte) oexport
void processResources (Resource *)
void processResources (Resource *, unsigned)
SPAN_0 (byte) oresources
template<typename LEXX >
void processTls1 (Interval *iv, typename tls_traits< LEXX >::cb_value_t imagebase, unsigned imagesize)
template<typename LEXX >
void processTls2 (Reloc *rel, const Interval *iv, unsigned newaddr, typename tls_traits< LEXX >::cb_value_t imagebase)
virtual void processTls (Interval *iv)=0
virtual void processTls (Reloc *r, const Interval *iv, unsigned a)=0
SPAN_0 (byte) otls
void processLoadConf (Reloc *, const Interval *, unsigned)
void processLoadConf (Interval *)
Load Configuration handling.
unsigned stripDebug (unsigned)
LE32 & IDSIZE (unsigned x)
import handling
LE32 & IDADDR (unsigned x)
LE32 & ODSIZE (unsigned x)
LE32 & ODADDR (unsigned x)
const LE32 & IDSIZE (unsigned x) const
const LE32 & IDADDR (unsigned x) const
SPAN_0 (pe_section_t) isection
unsigned tryremove (unsigned, unsigned)
virtual ~PeFile () noexcept
create UPX0 section
template<typename LEXX , typename ht >
void pack0 (OutputFile *fo, ht &ih, ht &oh, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only)
create UPX0 section
template<typename ht , typename LEXX , typename ord_mask_t >
void unpack0 (OutputFile *fo, const ht &ih, ht &oh, ord_mask_t ord_mask, bool set_oft)
create UPX0 section
int canUnpack0 (unsigned max_sections, unsigned objs, unsigned ih_entry, unsigned ih_size)
create UPX0 section
template<typename LEXX , typename ord_mask_t >
void rebuildImports (SPAN_S(byte) &extra_info, ord_mask_t ord_mask, bool set_oft)
create UPX0 section
upx_uint64_t ilinkerGetAddress (const char *, const char *) const
create UPX0 section
void rebuildRelocs (SPAN_S(byte) &, unsigned bits, unsigned flags, upx_uint64_t imagebase)
unpack
void rebuildExports ()
create UPX0 section
void rebuildResources (SPAN_S(byte) &, unsigned)
create UPX0 section
void rebuildTls ()
create UPX0 section
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
pe_header_t ih = {}
pe_header_t oh = {}
Protected Attributes inherited from PeFile
unsigned pe_offset
MemBuffer mb_oimport
unsigned soimport
byte * oimpdlls = nullptr
unsigned soimpdlls
ImportLinker * ilinker = nullptr
MemBuffer mb_orelocs
unsigned sorelocs
byte * oxrelocs = nullptr
unsigned soxrelocs
MemBuffer mb_oexport
unsigned soexport
MemBuffer mb_oresources
unsigned soresources
MemBuffer mb_otls
unsigned sotls
unsigned tlsindex
unsigned tlscb_ptr
unsigned tls_handler_offset = 0
bool use_tls_callbacks = false
MemBuffer mb_oloadconf
byte * oloadconf = nullptr
unsigned soloadconf
unsigned icondir_offset
int icondir_count
bool importbyordinal = false
bool kernel32ordinal = false
unsigned rvamin
unsigned cimports
unsigned crelocs
int big_relocs
ddirs_t * iddirs = nullptr
ddirs_t * oddirs = nullptr
MemBuffer mb_isection
bool isdll = false
bool isrtm = false
bool isefi = false
bool use_dep_hack = true
bool use_clear_dirty_stack = true
bool use_stub_relocs = true
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef PeFile super
Additional Inherited Members
Public Member Functions inherited from PeFile
virtual int getVersion () const override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PeFile
enum {
IMAGE_FILE_MACHINE_UNKNOWN = 0 , IMAGE_FILE_MACHINE_AMD64 = 0x8664 , IMAGE_FILE_MACHINE_ARM = 0x01c0 , IMAGE_FILE_MACHINE_ARMNT = 0x01c4 ,
IMAGE_FILE_MACHINE_ARM64 = 0xaa64 , IMAGE_FILE_MACHINE_ARM64EC = 0xa641 , IMAGE_FILE_MACHINE_I386 = 0x014c , IMAGE_FILE_MACHINE_IA64 = 0x200 ,
IMAGE_FILE_MACHINE_LOONGARCH32 = 0x6232 , IMAGE_FILE_MACHINE_LOONGARCH64 = 0x6264 , IMAGE_FILE_MACHINE_RISCV32 = 0x5032 , IMAGE_FILE_MACHINE_RISCV64 = 0x5064 ,
IMAGE_FILE_MACHINE_RISCV128 = 0x5128 , IMAGE_FILE_MACHINE_THUMB = 0x01c2
}
enum {
PEDIR_EXPORT = 0 , PEDIR_IMPORT = 1 , PEDIR_RESOURCE = 2 , PEDIR_EXCEPTION = 3 ,
PEDIR_SECURITY = 4 , PEDIR_BASERELOC = 5 , PEDIR_DEBUG = 6 , PEDIR_ARCHITECTURE = 7 ,
PEDIR_GLOBALPTR = 8 , PEDIR_TLS = 9 , PEDIR_LOAD_CONFIG = 10 , PEDIR_BOUND_IMPORT = 11 ,
PEDIR_IAT = 12 , PEDIR_DELAY_IMPORT = 13 , PEDIR_COM_DESCRIPTOR = 14
}
enum : unsigned {
IMAGE_SCN_CNT_CODE = 0x00000020 , IMAGE_SCN_CNT_INITIALIZED_DATA = 0x00000040 , IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080 , IMAGE_SCN_LNK_OTHER = 0x00000100 ,
IMAGE_SCN_LNK_INFO = 0x00000200 , IMAGE_SCN_LNK_REMOVE = 0x00000800 , IMAGE_SCN_LNK_COMDAT = 0x00001000 , IMAGE_SCN_GPREL = 0x00008000 ,
IMAGE_SCN_MEM_PURGEABLE = 0x00020000 , IMAGE_SCN_MEM_16BIT = 0x00020000 , IMAGE_SCN_MEM_LOCKED = 0x00040000 , IMAGE_SCN_MEM_PRELOAD = 0x00080000 ,
IMAGE_SCN_ALIGN_1BYTES = 0x00100000 , IMAGE_SCN_ALIGN_2BYTES = 0x00200000 , IMAGE_SCN_ALIGN_4BYTES = 0x00300000 , IMAGE_SCN_ALIGN_8BYTES = 0x00400000 ,
IMAGE_SCN_ALIGN_16BYTES = 0x00500000 , IMAGE_SCN_ALIGN_32BYTES = 0x00600000 , IMAGE_SCN_ALIGN_64BYTES = 0x00700000 , IMAGE_SCN_ALIGN_128BYTES = 0x00800000 ,
IMAGE_SCN_ALIGN_256BYTES = 0x00900000 , IMAGE_SCN_ALIGN_512BYTES = 0x00A00000 , IMAGE_SCN_ALIGN_1024BYTES = 0x00B00000 , IMAGE_SCN_ALIGN_2048BYTES = 0x00C00000 ,
IMAGE_SCN_ALIGN_4096BYTES = 0x00D00000 , IMAGE_SCN_ALIGN_8192BYTES = 0x00E00000 , IMAGE_SCN_LNK_NRELOC_OVFL = 0x01000000 , IMAGE_SCN_MEM_DISCARDABLE = 0x02000000 ,
IMAGE_SCN_MEM_NOT_CACHED = 0x04000000 , IMAGE_SCN_MEM_NOT_PAGED = 0x08000000 , IMAGE_SCN_MEM_SHARED = 0x10000000 , IMAGE_SCN_MEM_EXECUTE = 0x20000000 ,
IMAGE_SCN_MEM_READ = 0x40000000 , IMAGE_SCN_MEM_WRITE = 0x80000000
}
enum {
IMAGE_FILE_RELOCS_STRIPPED = 0x0001 , IMAGE_FILE_EXECUTABLE_IMAGE = 0x0002 , IMAGE_FILE_LINE_NUMS_STRIPPED = 0x0004 , IMAGE_FILE_LOCAL_SYMS_STRIPPED = 0x0008 ,
IMAGE_FILE_AGGRESSIVE_WS_TRIM = 0x0010 , IMAGE_FILE_LARGE_ADDRESS_AWARE = 0x0020 , IMAGE_FILE_BYTES_REVERSED_LO = 0x0080 , IMAGE_FILE_32BIT_MACHINE = 0x0100 ,
IMAGE_FILE_DEBUG_STRIPPED = 0x0200 , IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x0400 , IMAGE_FILE_NET_RUN_FROM_SWAP = 0x0800 , IMAGE_FILE_SYSTEM = 0x1000 ,
IMAGE_FILE_DLL = 0x2000 , IMAGE_FILE_UP_SYSTEM_ONLY = 0x4000 , IMAGE_FILE_BYTES_REVERSE_HI = 0x8000
}
enum {
IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA = 0x0020 , IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE = 0x0040 , IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY = 0x0080 , IMAGE_DLLCHARACTERISTICS_NX_COMPAT = 0x0100 ,
IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x0200 , IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x0400 , IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x0800 , IMAGE_DLLCHARACTERISTICS_APPCONTAINER = 0x1000 ,
IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x2000 , IMAGE_DLLCHARACTERISTICS_GUARD_CF = 0x4000 , IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000
}
enum {
IMAGE_SUBSYSTEM_UNKNOWN = 0 , IMAGE_SUBSYSTEM_NATIVE = 1 , IMAGE_SUBSYSTEM_WINDOWS_GUI = 2 , IMAGE_SUBSYSTEM_WINDOWS_CUI = 3 ,
IMAGE_SUBSYSTEM_WINDOWS_OS2_CUI = 5 , IMAGE_SUBSYSTEM_WINDOWS_POSIX_CUI = 7 , IMAGE_SUBSYSTEM_NATIVE_WINDOWS = 8 , IMAGE_SUBSYSTEM_WINDOWS_CE_GUI = 9 ,
IMAGE_SUBSYSTEM_EFI_APPLICATION = 10 , IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER = 11 , IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER = 12 , IMAGE_SUBSYSTEM_EFI_ROM = 13 ,
IMAGE_SUBSYSTEM_XBOX = 14 , IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION = 16
}
enum {
RT_CURSOR = 1 , RT_BITMAP , RT_ICON , RT_MENU ,
RT_DIALOG , RT_STRING , RT_FONTDIR , RT_FONT ,
RT_ACCELERATOR , RT_RCDATA , RT_MESSAGETABLE , RT_GROUP_CURSOR ,
RT_GROUP_ICON = 14 , RT_VERSION = 16 , RT_DLGINCLUDE , RT_PLUGPLAY = 19 ,
RT_VXD , RT_ANICURSOR , RT_ANIICON , RT_HTML ,
RT_MANIFEST , RT_LAST
}
enum {
IMAGE_REL_BASED_ABSOLUTE = 0 , IMAGE_REL_BASED_IGNORE = 0 , IMAGE_REL_BASED_HIGH = 1 , IMAGE_REL_BASED_LOW = 2 ,
IMAGE_REL_BASED_HIGHLOW = 3 , IMAGE_REL_BASED_HIGHADJ = 4 , IMAGE_REL_BASED_MIPS_JMPADDR = 5 , IMAGE_REL_BASED_ARM_MOV32 = 5 ,
IMAGE_REL_BASED_THUMB_MOV32 = 7 , IMAGE_REL_BASED_MIPS_JMPADDR16 = 9 , IMAGE_REL_BASED_IA64_IMM64 = 9 , IMAGE_REL_BASED_DIR64 = 10
}
Static Protected Member Functions inherited from PeFile
static int checkMachine (unsigned cpu)
util
static unsigned virta2objnum (unsigned, SPAN_0(pe_section_t), unsigned)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
Definition at line 550 of file pefile.h.
Member Typedef Documentation
super
typedef PeFile PeFile32::super private
Definition at line 551 of file pefile.h.
Constructor & Destructor Documentation
PeFile32()
PeFile32::PeFile32 (InputFile * f) explicit protected
PeFile32.
Definition at line 3160 of file pefile.cpp.
                               : super(f) {
    COMPILE_TIME_ASSERT(sizeof(pe_header_t) == 248)
    COMPILE_TIME_ASSERT_ALIGNED1(pe_header_t)
    iddirs = ih.ddirs;
    oddirs = oh.ddirs;
}
References COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, PeFile32::pe_header_t::ddirs, PeFile::iddirs, ih, PeFile::oddirs, and oh.
~PeFile32()
PeFile32::~PeFile32 () protected virtual noexcept
PeFile32.
Definition at line 3168 of file pefile.cpp.
{}
Member Function Documentation
canUnpack()
tribool PeFile32::canUnpack () override protected virtual
PeFile32.
Implements PackerBase.
Definition at line 3195 of file pefile.cpp.
{
    if (!canPack()) // this calls readFileHeader() and readPeHeader()
        return false;
    return canUnpack0(getFormat() == UPX_F_WINCE_ARM ? 4 : 3, ih.objects, ih.entry, sizeof(ih));
}
References PackerBase::canPack(), PeFile::canUnpack0(), PeFile32::pe_header_t::entry, PackerBase::getFormat(), ih, PeFile32::pe_header_t::objects, and UPX_F_WINCE_ARM.
pack0()
void PeFile32::pack0 (OutputFile * fo, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only) protected
PeFile32.
Definition at line 3184 of file pefile.cpp.
{
    super::pack0<LE32>(fo, ih, oh, subsystem_mask, default_imagebase, last_section_rsrc_only);
    // infoWarning("End of PeFile32::pack0");
}
References ih, and oh.
Referenced by PackW32PeI386::pack(), and PackWinCeArm::pack().
processImports()
unsigned PeFile32::processImports () override protected virtual
PeFile32.
Implements PeFile.
Definition at line 3201 of file pefile.cpp.
                                  { // pass 1
    return processImports0<LE32>(1u << 31);
}
processRelocs()
void PeFile32::processRelocs () override protected virtual
Implements PeFile.
Definition at line 501 of file pefile.cpp.
{
    big_relocs = 0;
    const unsigned skip1 = IDADDR(PEDIR_BASERELOC);
    const unsigned take1 = IDSIZE(PEDIR_BASERELOC);
    Reloc rel(ibuf.subref("bad reloc %#x", skip1, take1), take1);
    const unsigned *const counts = rel.getcounts();
    unsigned relocnum = 0;
    for (unsigned ic = 1; ic < 16; ic++)
        relocnum += counts[ic];
    for (unsigned ic = 0; ic < 16; ic++)
        NO_printf("reloc counts[%u] %u\n", ic, counts[ic]);
    if (opt->win32_pe.strip_relocs || relocnum == 0) {
        if (IDSIZE(PEDIR_BASERELOC)) {
            ibuf.fill(IDADDR(PEDIR_BASERELOC), IDSIZE(PEDIR_BASERELOC), FILLVAL);
            ih.objects = tryremove(IDADDR(PEDIR_BASERELOC), ih.objects);
        }
        mb_orelocs.alloc(1);
        mb_orelocs.clear();
        orelocs = mb_orelocs; // => orelocs now is a SPAN_S
        sorelocs = 0;
        return;
    }
    for (unsigned ic = IMAGE_REL_BASED_HIGHADJ; ic < 16; ic++)
        if (counts[ic])
            infoWarning("skipping unsupported relocation type %d (%d)", ic, counts[ic]);
    LE32 *fix[4];
    auto fix_deleter = upx::ArrayDeleter(fix, 0); // don't leak memory
    for (unsigned ic = 0; ic <= IMAGE_REL_BASED_HIGHLOW; ic++) {
        fix[ic] = New(LE32, counts[ic]);
        fix_deleter.count += 1;
    }
    unsigned xcounts[4];
    memset(xcounts, 0, sizeof(xcounts));
    // prepare sorting
    unsigned pos, reloc_type;
    while (rel.next(pos, reloc_type)) {
        // FIXME add check for relocations which try to modify the
        // PE header or other relocation records
        if (pos >= ih.imagesize)
            continue; // skip out-of-bounds record
        if (reloc_type <= IMAGE_REL_BASED_HIGHLOW)
            fix[reloc_type][xcounts[reloc_type]++] = pos - rvamin;
    }
    // remove duplicated records
    for (unsigned ic = 1; ic <= IMAGE_REL_BASED_HIGHLOW; ic++) {
        upx_qsort(fix[ic], xcounts[ic], 4, le32_compare);
        unsigned prev = ~0u;
        unsigned jc = 0;
        for (unsigned kc = 0; kc < xcounts[ic]; kc++)
            if (fix[ic][kc] != prev)
                prev = fix[ic][jc++] = fix[ic][kc];
        NO_printf("reloc xcounts[%u] %u->%u\n", ic, xcounts[ic], jc);
        xcounts[ic] = jc;
    }
    // preprocess "type 3" relocation records
    for (unsigned ic = 0; ic < xcounts[IMAGE_REL_BASED_HIGHLOW]; ic++) {
        pos = fix[3][ic] + rvamin;
        unsigned w = get_le32(ibuf.subref("bad reloc type 3 %#x", pos, sizeof(LE32)));
        set_le32(ibuf + pos, w - ih.imagebase - rvamin);
    }
    ibuf.fill(IDADDR(PEDIR_BASERELOC), IDSIZE(PEDIR_BASERELOC), FILLVAL);
    mb_orelocs.alloc(mem_size(4, relocnum, 8192)); // 8192 - safety
    orelocs = mb_orelocs;                          // => orelocs now is a SPAN_S
    sorelocs = optimizeReloc(xcounts[3], (byte *) fix[3], orelocs, ibuf + rvamin, ibufgood - rvamin,
                             32, true, &big_relocs);
    // Malware that hides behind UPX often has PE header info that is
    // deliberately corrupt.  Sometimes it is even tuned to cause us trouble!
    // Use an extra check to avoid AccessViolation (SIGSEGV) when appending
    // the relocs into one array.
    if ((4 * relocnum + 8192) <
        (sorelocs + 4 * (2 + xcounts[IMAGE_REL_BASED_LOW] + xcounts[IMAGE_REL_BASED_HIGH])))
        throwCantUnpack("Invalid relocs");
    // append relocs type "LOW" then "HIGH"
    for (unsigned ic = IMAGE_REL_BASED_LOW; ic >= IMAGE_REL_BASED_HIGH; ic--) {
        memcpy(orelocs + sorelocs, fix[ic], 4 * xcounts[ic]);
        sorelocs += 4 * xcounts[ic];
        set_le32(orelocs + sorelocs, 0);
        if (xcounts[ic]) {
            sorelocs += 4;
            big_relocs |= 2 * ic;
        }
    }
    info("Relocations: original size: %u bytes, preprocessed size: %u bytes",
         (unsigned) IDSIZE(PEDIR_BASERELOC), sorelocs);
}
References MemBuffer::alloc(), PeFile::big_relocs, MemBuffer::clear(), MemBuffer::fill(), FILLVAL, get_le32(), PeFile::Reloc::getcounts(), Packer::ibuf, Packer::ibufgood, PeFile::IDADDR(), PeFile::IDSIZE(), PeFile::IMAGE_REL_BASED_HIGH, PeFile::IMAGE_REL_BASED_HIGHADJ, PeFile::IMAGE_REL_BASED_HIGHLOW, PeFile::IMAGE_REL_BASED_LOW, info(), infoWarning(), le32_compare(), PeFile::mb_orelocs, mem_size(), memcpy(), memset(), New, PeFile::Reloc::next(), NO_printf(), opt, Packer::optimizeReloc(), PeFile::PEDIR_BASERELOC, PeFile::rvamin, set_le32(), PeFile::sorelocs, MemBuffer::subref(), throwCantUnpack(), PeFile::tryremove(), and upx_qsort.
processTls() [1/2]
void PeFile32::processTls (Interval * iv) override protected virtual
PeFile32.
Implements PeFile.
Reimplemented in PackWinCeArm.
Definition at line 3205 of file pefile.cpp.
{ processTls1<LE32>(iv, ih.imagebase, ih.imagesize); }
References ih, PeFile32::pe_header_t::imagebase, and PeFile32::pe_header_t::imagesize.
processTls() [2/2]
void PeFile32::processTls (Reloc * r, const Interval * iv, unsigned a) override protected virtual
PeFile32.
Implements PeFile.
Definition at line 3207 of file pefile.cpp.
{
    processTls2<LE32>(r, iv, a, ih.imagebase);
}
References ih, and PeFile32::pe_header_t::imagebase.
readPeHeader()
void PeFile32::readPeHeader () override protected virtual
PeFile32.
Implements PeFile.
Definition at line 3170 of file pefile.cpp.
{
    fi->readx(&ih, sizeof(ih));
    if (31 < (unsigned) ih.subsystem) {
        throwCantPack("bad ih.subsystem 0x%x", (unsigned) ih.subsystem);
    }
    isefi = ((1u << ih.subsystem) &
             ((1u << IMAGE_SUBSYSTEM_EFI_APPLICATION) |
              (1u << IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER) |
              (1u << IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER) | (1u << IMAGE_SUBSYSTEM_EFI_ROM))) != 0;
    isdll = !isefi && (ih.flags & IMAGE_FILE_DLL) != 0;
    use_dep_hack &= !isefi;
    use_clear_dirty_stack &= !isefi;
}
References PackerBase::fi, PeFile32::pe_header_t::flags, ih, PeFile::IMAGE_FILE_DLL, PeFile::IMAGE_SUBSYSTEM_EFI_APPLICATION, PeFile::IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER, PeFile::IMAGE_SUBSYSTEM_EFI_ROM, PeFile::IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER, PeFile::isdll, PeFile::isefi, InputFile::readx(), PeFile32::pe_header_t::subsystem, throwCantPack(), PeFile::use_clear_dirty_stack, and PeFile::use_dep_hack.
unpack()
void PeFile32::unpack (OutputFile * fo) override protected virtual
PeFile32.
Implements Packer.
Definition at line 3190 of file pefile.cpp.
{
    bool set_oft = getFormat() == UPX_F_WINCE_ARM;
    unpack0<pe_header_t, LE32>(fo, ih, oh, 1U << 31, set_oft);
}
References PackerBase::getFormat(), ih, oh, and UPX_F_WINCE_ARM.
Member Data Documentation
ih
pe_header_t PeFile32::ih = {} protected
Definition at line 608 of file pefile.h.
Referenced by PackW32PeI386::buildLoader(), PackW32PeI386::canPack(), PackWinCeArm::canPack(), canUnpack(), PackW32PeI386::defineSymbols(), PackWinCeArm::defineSymbols(), PackW32PeI386::getCompressionMethods(), PackW32PeI386::needForceOption(), PackWinCeArm::needForceOption(), pack0(), PeFile32(), processTls(), readPeHeader(), and unpack().
oh
pe_header_t PeFile32::oh = {} protected
Definition at line 608 of file pefile.h.
Referenced by pack0(), PeFile32(), PackW32PeI386::setOhDataBase(), PackWinCeArm::setOhDataBase(), PackW32PeI386::setOhHeaderSize(), PackWinCeArm::setOhHeaderSize(), and unpack().
The documentation for this class was generated from the following files:
src/pefile.h
src/pefile.cpp