My Project: PackMachARMEL Class Reference
PackMachARMEL Class Reference
#include <p_mach.h>
Public Member Functions
PackMachARMEL (InputFile *f)
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
Public Member Functions inherited from PackMachBase< MachClass_LE32 >
PackMachBase (InputFile *, unsigned cpuid, unsigned filetype, unsigned t_flavor, unsigned ts_word_cnt, unsigned tc_size, unsigned page_shift)
virtual ~PackMachBase ()
virtual int getVersion () const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual void pack1 (OutputFile *, Filter &) override
virtual int pack2 (OutputFile *, Filter &) override
virtual off_t pack3 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
virtual void pack4dylib (OutputFile *, Filter &, Addr init_address)
virtual int threado_size () const=0
virtual void threado_setPC (upx_uint64_t pc)=0
virtual void threado_rewrite (OutputFile *)=0
virtual void threado_write (OutputFile *)=0
virtual void pack1_setup_threado (OutputFile *const fo)=0
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
virtual upx_uint64_t get_mod_init_func (Mach_segment_command const *segptr)
virtual unsigned find_SEGMENT_gap (unsigned const k, unsigned pos_eof)
Public Member Functions inherited from PackUnix
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack1_setup_threado (OutputFile *const fo) override
virtual Linker * newLinker () const override
virtual void addStubEntrySections (Filter const *) override
packed_struct (Mach_thread_command)
int threado_size () const override
void threado_setPC (upx_uint64_t pc) override
void threado_rewrite (OutputFile *fo) override
void threado_write (OutputFile *fo) override
upx_uint64_t threadc_getPC (void const *ptr) override
Protected Member Functions inherited from PackMachBase< MachClass_LE32 >
virtual void patchLoader () override
virtual void patchLoaderChecksum () override
virtual void updateLoader (OutputFile *) override
virtual void buildLoader (const Filter *ft) override
virtual void buildMachLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const *ft)
virtual void defineSymbols (Filter const *)
virtual void addStubEntrySections (Filter const *)
virtual upx_uint64_t threadc_getPC (void const *)=0
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from PackUnix
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
Copy stub from exe.
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
Mach_thread_command threado
Protected Attributes inherited from PackMachBase< MachClass_LE32 >
upx_uint64_t entryVMA
upx_uint64_t my_page_size
upx_uint64_t my_page_mask
unsigned my_cputype
unsigned my_cpusubtype
unsigned my_filetype
unsigned my_thread_flavor
unsigned my_thread_state_word_count
unsigned my_thread_command_size
unsigned n_segment
unsigned sz_segment
unsigned sz_mach_headers
unsigned sz_stub_entry
unsigned sz_stub_fold
unsigned sz_stub_main
upx_byte const * stub_entry
upx_byte const * stub_fold
upx_byte const * stub_main
MemBuffer rawmseg_buf
Mach_segment_command * rawmseg
MemBuffer msegcmd_buf
Mach_segment_command * msegcmd
unsigned o__mod_init_func
upx_uint64_t prev_mod_init_func
upx_uint64_t pagezero_vmsize
upx_uint64_t vma_max
Mach_header mhdri
Mach_header mhdro
Mach_segment_command segZERO
Mach_segment_command segXHDR
Mach_section_command secXHDR
Mach_segment_command segTEXT
Mach_section_command secTEXT
Mach_segment_command segLINK
Mach_linkedit_data_command linkitem
Mach_uuid_command cmdUUID
Mach_source_version_command cmdSRCVER
Mach_version_min_command cmdVERMIN
struct l_info linfo
Protected Attributes inherited from PackUnix
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef PackMachBase< MachClass_LE32 > super
Additional Inherited Members
Public Types inherited from PackUnix
typedef Packer super
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PackMachBase< MachClass_LE32 >
typedef MachClass_LE32 MachClass
typedef MachClass::BeLePolicy BeLePolicy
typedef MachClass::MachITypes MachITypes
typedef MachClass::TE16 TE16
typedef MachClass::TE32 TE32
typedef MachClass::TE64 TE64
typedef MachClass::Addr Addr
typedef MachClass::Mach_header Mach_header
typedef MachClass::Mach_command Mach_command
typedef MachClass::Mach_segment_command Mach_segment_command
typedef MachClass::Mach_section_command Mach_section_command
typedef MachClass::Mach_symtab_command Mach_symtab_command
typedef MachClass::Mach_dysymtab_command Mach_dysymtab_command
typedef MachClass::Mach_segsplit_info_command Mach_segsplit_info_command
typedef MachClass::Mach_routines_command Mach_routines_command
typedef MachClass::Mach_twolevel_hints_command Mach_twolevel_hints_command
typedef MachClass::Mach_linkedit_data_command Mach_linkedit_data_command
typedef MachClass::Mach_uuid_command Mach_uuid_command
typedef MachClass::Mach_main_command Mach_main_command
typedef MachClass::Mach_load_dylib_command Mach_load_dylib_command
typedef MachClass::Mach_dylib Mach_dylib
typedef MachClass::Mach_load_dylinker_command Mach_load_dylinker_command
typedef MachClass::Mach_dyld_info_only_command Mach_dyld_info_only_command
typedef MachClass::Mach_version_min_command Mach_version_min_command
typedef MachClass::Mach_source_version_command Mach_source_version_command
Protected Types inherited from PackUnix
enum { OVERHEAD = 2048 }
Static Protected Member Functions inherited from PackMachBase< MachClass_LE32 >
static int __acc_cdecl_qsort compare_segment_command (void const *aa, void const *bb)
static void compileTimeAssertions ()
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
Definition at line 1134 of file p_mach.h.
Member Typedef Documentation
super
typedef PackMachBase<MachClass_LE32> PackMachARMEL::super private
Definition at line 1136 of file p_mach.h.
Constructor & Destructor Documentation
PackMachARMEL()
PackMachARMEL::PackMachARMEL (InputFile * f)
Definition at line 314 of file p_mach.cpp.
                                         : super(f, Mach_header::CPU_TYPE_ARM,
        Mach_header::MH_EXECUTE, (unsigned)Mach_thread_command::ARM_THREAD_STATE,
        sizeof(Mach_ARM_thread_state)>>2, sizeof(threado), 12)
{ }
Member Function Documentation
addStubEntrySections()
void PackMachARMEL::addStubEntrySections (Filter const *) override protected virtual
Reimplemented from PackMachBase< MachClass_LE32 >.
Definition at line 443 of file p_mach.cpp.
{
    addLoader("MACHMAINX", nullptr);
   //addLoader(getDecompressorSections(), nullptr);
    addLoader(
        ( M_IS_NRV2E(ph.method) ? "NRV_HEAD,NRV2E,NRV_TAIL"
        : M_IS_NRV2D(ph.method) ? "NRV_HEAD,NRV2D,NRV_TAIL"
        : M_IS_NRV2B(ph.method) ? "NRV_HEAD,NRV2B,NRV_TAIL"
        : M_IS_LZMA(ph.method)  ? "LZMA_ELF00,LZMA_DEC20,LZMA_DEC30"
        : nullptr), nullptr);
    if (hasLoaderSection("CFLUSH"))
        addLoader("CFLUSH");
    addLoader("MACHMAINY,IDENTSTR,+40,MACHMAINZ,FOLDEXEC", nullptr);
}
References Packer::addLoader(), Packer::hasLoaderSection(), M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, PackHeader::method, and PackerBase::ph.
getCompressionMethods()
const int * PackMachARMEL::getCompressionMethods (int method, int level) const override protected virtual
Reimplemented from PackMachBase< MachClass_LE32 >.
Definition at line 264 of file p_mach.cpp.
{
    // Un-aligned fetch does not work on 32-bit ARM, so use 8-bit methods
    return Packer::getDefaultCompressionMethods_8(method, level);
}
References Packer::getDefaultCompressionMethods_8().
getFilters()
int const * PackMachARMEL::getFilters () const override protected virtual
Reimplemented from PackUnix.
Definition at line 324 of file p_mach.cpp.
{
    static const int filters[] = { 0x50, FT_END };
    return filters;
}
References FT_END.
getFormat()
virtual int PackMachARMEL::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 1141 of file p_mach.h.
{ return UPX_F_MACH_ARM; }
References UPX_F_MACH_ARM.
getFullName()
virtual const char * PackMachARMEL::getFullName (const options_t *) const inline override virtual
Definition at line 1143 of file p_mach.h.
{ return "arm-darwin.macho"; }
getName()
virtual const char * PackMachARMEL::getName () const inline override virtual
Implements PackerBase.
Definition at line 1142 of file p_mach.h.
{ return "macho/arm"; }
newLinker()
Linker * PackMachARMEL::newLinker () const override protected virtual
Implements Packer.
Definition at line 356 of file p_mach.cpp.
{
    return new ElfLinkerArmLE;
}
pack1_setup_threado()
void PackMachARMEL::pack1_setup_threado (OutputFile *const fo) override protected virtual
Implements PackMachBase< MachClass_LE32 >.
Definition at line 1278 of file p_mach.cpp.
{
    threado.cmd = Mach_command::LC_UNIXTHREAD;
    threado.cmdsize = sizeof(threado);
    threado.flavor = my_thread_flavor;
    threado.count =  my_thread_state_word_count;
    memset(&threado.state, 0, sizeof(threado.state));
    fo->write(&threado, sizeof(threado));
}
References memset(), PackMachBase< MachClass_LE32 >::my_thread_flavor, PackMachBase< MachClass_LE32 >::my_thread_state_word_count, threado, and OutputFile::write().
packed_struct()
PackMachARMEL::packed_struct (Mach_thread_command) inline protected
Definition at line 1152 of file p_mach.h.
{
        LE32 cmd;            /* LC_THREAD or  LC_UNIXTHREAD */
        LE32 cmdsize;        /* total size of this command */
        LE32 flavor;
        LE32 count;          /* sizeof(following_thread_state)/4 */
        Mach_ARM_thread_state state;
    #define WANT_MACH_THREAD_ENUM 1
    #include "p_mach_enum.h"
    };
threadc_getPC()
upx_uint64_t PackMachARMEL::threadc_getPC (void const * ptr) inline override protected virtual
Implements PackMachBase< MachClass_LE32 >.
Definition at line 1175 of file p_mach.h.
{
        Mach_thread_command const *tc = (Mach_thread_command const *)ptr;
        if (tc->cmd!=Mach_segment_command::LC_UNIXTHREAD
        ||  tc->cmdsize!=sizeof(threado)
        ||  tc->flavor!=my_thread_flavor
        ||  tc->count!=my_thread_state_word_count) {
            return ~0ull;
        }
        return tc->state.pc;
    }
References PackMachBase< MachClass_LE32 >::my_thread_flavor, PackMachBase< MachClass_LE32 >::my_thread_state_word_count, ptr, and threado.
threado_rewrite()
void PackMachARMEL::threado_rewrite (OutputFile * fo) inline override protected virtual
Implements PackMachBase< MachClass_LE32 >.
Definition at line 1172 of file p_mach.h.
{ fo->rewrite(&threado, sizeof(threado)); }
References OutputFile::rewrite(), and threado.
threado_setPC()
void PackMachARMEL::threado_setPC (upx_uint64_t pc) inline override protected virtual
Implements PackMachBase< MachClass_LE32 >.
Definition at line 1164 of file p_mach.h.
{
        memset(&threado, 0, sizeof(threado));
        threado.cmd = Mach_segment_command::LC_UNIXTHREAD;
        threado.cmdsize = sizeof(threado);
        threado.flavor = my_thread_flavor;
        threado.count =  my_thread_state_word_count;
        threado.state.pc = pc;
    }
References memset(), PackMachBase< MachClass_LE32 >::my_thread_flavor, PackMachBase< MachClass_LE32 >::my_thread_state_word_count, and threado.
threado_size()
int PackMachARMEL::threado_size () const inline override protected virtual
Implements PackMachBase< MachClass_LE32 >.
Definition at line 1163 of file p_mach.h.
{ return sizeof(threado); }
References threado.
threado_write()
void PackMachARMEL::threado_write (OutputFile * fo) inline override protected virtual
Implements PackMachBase< MachClass_LE32 >.
Definition at line 1173 of file p_mach.h.
{ return   fo->write(&threado, sizeof(threado)); }
References threado, and OutputFile::write().
Member Data Documentation
threado
Mach_thread_command PackMachARMEL::threado protected
Definition at line 1162 of file p_mach.h.
Referenced by pack1_setup_threado(), threadc_getPC(), threado_rewrite(), threado_setPC(), threado_size(), and threado_write().
The documentation for this class was generated from the following files:
src/p_mach.h
src/p_mach.cpp