My Project: PackLinuxI386 Class Reference
PackLinuxI386 Class Reference
linux/386 (generic "execve" format)
#include <p_lx_exc.h>
Classes
struct Elf32_Note
Public Member Functions
PackLinuxI386 (InputFile *f)
linux/386 (generic "execve" format)
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka)
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void buildLoader (const Filter *) override
virtual tribool canPack () override
Public Member Functions inherited from PackUnix
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Types
enum { UPX_ELF_MAGIC = 0x5850557f }
Protected Types inherited from PackUnix
enum { OVERHEAD = 2048 }
Protected Member Functions
virtual void pack1 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
virtual Linker * newLinker () const override
virtual int getLoaderPrefixSize () const
virtual void buildLinuxLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const *ft)
virtual void patchLoader () override
virtual void patchLoaderChecksum () override
virtual void updateLoader (OutputFile *) override
virtual int checkEhdr (const Elf_LE32_Ehdr *ehdr) const
some ELF utility functions
packed_struct (cprElfHdr1)
packed_struct (cprElfHdr2)
packed_struct (cprElfHdr3)
Protected Member Functions inherited from PackUnixLe32
PackUnixLe32 (InputFile *f)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from PackUnix
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Static Protected Member Functions
static void compileTimeAssertions ()
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes
unsigned n_mru
cprElfHdr3 elfout
struct PackLinuxI386::Elf32_Note elfnote
unsigned char ei_osabi
char const * osabi_note
Protected Attributes inherited from PackUnix
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef PackUnixLe32 super
Additional Inherited Members
Public Types inherited from PackUnix
typedef Packer super
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Detailed Description
linux/386 (generic "execve" format)
Definition at line 41 of file p_lx_exc.h.
Member Typedef Documentation
super
typedef PackUnixLe32 PackLinuxI386::super private
Definition at line 43 of file p_lx_exc.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
UPX_ELF_MAGIC
Definition at line 85 of file p_lx_exc.h.
         {
        UPX_ELF_MAGIC = 0x5850557f          // "\x7fUPX"
    };
Constructor & Destructor Documentation
PackLinuxI386()
PackLinuxI386::PackLinuxI386 (InputFile * f)
linux/386 (generic "execve" format)
Definition at line 57 of file p_lx_exc.cpp.
                                         : super(f),
    ei_osabi(Elf32_Ehdr::ELFOSABI_LINUX), osabi_note(nullptr)
{
    bele = &N_BELE_RTP::le_policy;
}
References Packer::bele, and N_BELE_RTP::le_policy.
Member Function Documentation
buildLinuxLoader()
void PackLinuxI386::buildLinuxLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const * ft) protected virtual
Definition at line 288 of file p_lx_exc.cpp.
{
    initLoader(proto, szproto);
    unsigned fold_hdrlen = 0;
  if (0 < szfold) {
    cprElfHdr1 const *const hf = (cprElfHdr1 const *)fold;
    fold_hdrlen = usizeof(hf->ehdr) + hf->ehdr.e_phentsize * hf->ehdr.e_phnum +
         usizeof(l_info);
    if (0 == get_le32(fold_hdrlen + fold)) {
        // inconsistent SIZEOF_HEADERS in *.lds (ld, binutils)
        fold_hdrlen = upx::umax(0x80u, fold_hdrlen);
    }
  }
    // This adds the definition to the "library", to be used later.
    // NOTE: the stub is NOT compressed!  The savings is not worth it.
    linker->addSection("FOLDEXEC", fold + fold_hdrlen, szfold - fold_hdrlen, 0);
    n_mru = ft->n_mru;
// Rely on "+80CXXXX" [etc] in getDecompressorSections() packer_c.cpp */
//    // Here is a quick summary of the format of the output file:
//    linker->setLoaderAlignOffset(
//            // Elf32_Edhr
//        sizeof(elfout.ehdr) +
//            // Elf32_Phdr: 1 for exec86, 2 for sh86, 3 for elf86
//        (elfout.ehdr.e_phentsize * elfout.ehdr.e_phnum) +
//            // checksum UPX! lsize version format
//        sizeof(l_info) +
//            // PT_DYNAMIC with DT_NEEDED "forwarded" from original file
//        ((elfout.ehdr.e_phnum==3) ? (unsigned) elfout.phdr[2].p_memsz : 0) +
//            // p_progid, p_filesize, p_blocksize
//        sizeof(p_info) +
//            // compressed data
//        b_len + ph.c_len);
//            // entry to stub
    addLoader("LEXEC000", nullptr);
    if (ft->id) {
        if (n_mru) {
            addLoader("LEXEC009", nullptr);
        }
    }
    addLoader("LEXEC010", nullptr);
    linker->defineSymbol("filter_cto", ft->cto);
    linker->defineSymbol("filter_length",
                         (ft->id & 0xf) % 3 == 0 ? ft->calls :
                         ft->lastcall - ft->calls * 4);
    addLoader(getDecompressorSections(), nullptr);
    addLoader("LEXEC015", nullptr);
    if (ft->id) {
        {  // decompr, unfilter not separate
            if (0x80==(ft->id & 0xF0)) {
                addLoader("LEXEC110", nullptr);
                if (n_mru) {
                    addLoader("LEXEC100", nullptr);
                }
                // bug in APP: jmp and label must be in same .asx/.asy
                addLoader("LEXEC016", nullptr);
            }
        }
        addFilter32(ft->id);
        {  // decompr always unfilters
            addLoader("LEXEC017", nullptr);
        }
    }
    else {
        addLoader("LEXEC017", nullptr);
    }
    addLoader("IDENTSTR", nullptr);
    addLoader("LEXEC020", nullptr);
    addLoader("FOLDEXEC", nullptr);
    if (M_IS_LZMA(ph.method)) {
        const lzma_compress_result_t *res = &ph.compress_result.result_lzma;
        upx_uint32_t properties = // lc, lp, pb, dummy
            (res->lit_context_bits << 0) |
            (res->lit_pos_bits << 8) |
            (res->pos_bits << 16);
        if (bele->isBE()) // big endian - bswap32
            properties = bswap32(properties);
        linker->defineSymbol("lzma_properties", properties);
        // These lengths assume only one block (typ. 524288 bytes: 0.5 MiB).
        // i386 handles more than one block, and computes the lengths
        // dynamically from struct b_info.  Why do others need these?
        if (linker->findSymbol("lzma_c_len", false)) {
            // -2 for properties
            linker->defineSymbol("lzma_c_len", ph.c_len - 2);
        }
        if (linker->findSymbol("lzma_u_len", false)) {
            linker->defineSymbol("lzma_u_len", ph.c_len);
        }
        unsigned const stack = getDecompressorWrkmemSize();
        linker->defineSymbol("lzma_stack_adjust", 0u - stack);
    }
    if (0x80==(ft->id & 0xF0)) {
        int const mru = ft->n_mru ? 1+ ft->n_mru : 0;
        if (mru && mru!=256) {
            unsigned const is_pwr2 = (0==((mru -1) & mru));
            linker->defineSymbol("NMRU", mru - is_pwr2);
        }
    }
    relocateLoader();
}
References Packer::addFilter32(), Packer::addLoader(), Packer::bele, bswap32, PackHeader::c_len, Filter::calls, PackHeader::compress_result, Filter::cto, get_le32(), Packer::getDecompressorSections(), Packer::getDecompressorWrkmemSize(), Filter::id, Packer::initLoader(), Filter::lastcall, lzma_compress_result_t::lit_context_bits, lzma_compress_result_t::lit_pos_bits, M_IS_LZMA, PackHeader::method, Filter::n_mru, n_mru, PackerBase::ph, lzma_compress_result_t::pos_bits, Packer::relocateLoader(), upx_compress_result_t::result_lzma, upx::umax(), and usizeof.
Referenced by buildLoader(), PackBSDI386::buildLoader(), and PackLinuxI386sh::buildLoader().
buildLoader()
void PackLinuxI386::buildLoader (const Filter * ft) override virtual
Implements Packer.
Reimplemented in PackBSDI386, and PackLinuxI386sh.
Definition at line 402 of file p_lx_exc.cpp.
{
    unsigned const sz_fold = sizeof(stub_i386_linux_elf_execve_fold);
    MemBuffer buf(sz_fold);
    memcpy(buf, stub_i386_linux_elf_execve_fold, sz_fold);
    // patch loader
    // note: we only can use /proc/<pid>/fd when exetype > 0.
    //   also, we sleep much longer when compressing a script.
    checkPatch(nullptr, 0, 0, 0);  // reset
    patch_le32(buf,sz_fold,"UPX4",exetype > 0 ? 3 : 15);   // sleep time
    patch_le32(buf,sz_fold,"UPX3",progid);
    patch_le32(buf,sz_fold,"UPX2",exetype > 0 ? 0 : 0x7fffffff);
    buildLinuxLoader(
        stub_i386_linux_elf_execve_entry, sizeof(stub_i386_linux_elf_execve_entry),
        buf, sz_fold, ft );
}
References buf, buildLinuxLoader(), Packer::checkPatch(), PackUnix::exetype, memcpy(), Packer::patch_le32(), PackUnix::progid, stub_i386_linux_elf_execve_entry, and stub_i386_linux_elf_execve_fold.
canPack()
tribool PackLinuxI386::canPack () override virtual
Reimplemented from PackUnix.
Reimplemented in PackLinuxI386sh.
Definition at line 498 of file p_lx_exc.cpp.
{
    if (exetype != 0)
        return super::canPack();
    Elf_LE32_Ehdr ehdr;
    unsigned char *buf = ehdr.e_ident;
    fi->seek(0, SEEK_SET);
    fi->readx(&ehdr, sizeof(ehdr));
    fi->seek(0, SEEK_SET);
    exetype = 0;
    const unsigned l = get_le32(buf);
    int elf = checkEhdr(&ehdr);
    if (elf >= 0) {
        // NOTE: ELF executables are now handled by p_lx_elf.cpp,
        //   so we only handle them here if force_execve
        if (elf == 0 && opt->o_unix.force_execve) {
            exetype = 1;
            unsigned osabi0 = ehdr.e_ident[Elf32_Ehdr::EI_OSABI];
            switch (osabi0) {
            case Elf32_Ehdr::ELFOSABI_LINUX:
            case Elf32_Ehdr::ELFOSABI_FREEBSD:
            case Elf32_Ehdr::ELFOSABI_NETBSD:
            case Elf32_Ehdr::ELFOSABI_OPENBSD:
                ei_osabi = osabi0;  // Proudly declares its osabi in Ehdr.
                break;
            default:
            unsigned const e_phnum = get_te16(&ehdr.e_phnum);
            if (e_phnum<=(512/sizeof(Elf32_Phdr))) {
                union {
                    unsigned char buf2[512];
                    //Elf32_Phdr phdr;
                } u;
                fi->seek(get_te32(&ehdr.e_phoff), SEEK_SET);
                fi->readx(u.buf2, sizeof(u.buf2));
                fi->seek(0, SEEK_SET);
                Elf32_Phdr const *phdr = (Elf32_Phdr *) u.buf2;
                for (unsigned j=0; j < e_phnum; ++phdr, ++j) {
                    if (phdr->PT_NOTE == get_te32(&phdr->p_type)) {
                        unsigned const offset = get_te32(&phdr->p_offset);
                        struct Elf32_Note note; memset(&note, 0, sizeof(note));
                        fi->seek(offset, SEEK_SET);
                        fi->readx(&note, sizeof(note));
                        fi->seek(0, SEEK_SET);
                        if (4==get_te32(&note.descsz)
                        &&  1==get_te32(&note.type)
                        &&  0==note.end ) {
                            if (0==strcmp("NetBSD", (char const *)note.text)) {
                                ei_osabi = Elf32_Ehdr::ELFOSABI_NETBSD;
                                break;
                            }
                            if (0==strcmp("OpenBSD", (char const *)note.text)) {
                                ei_osabi = Elf32_Ehdr::ELFOSABI_OPENBSD;
                                break;
                            }
                        }
                    }
                }
            }
            }
        }
        if (UPX_F_BSD_i386==getFormat()
        && !(Elf32_Ehdr::ELFOSABI_FREEBSD==ei_osabi
          || Elf32_Ehdr::ELFOSABI_NETBSD ==ei_osabi
          || Elf32_Ehdr::ELFOSABI_OPENBSD==ei_osabi )) {
            return false;
        }
    }
    else if (l == 0x00640107 || l == 0x00640108 || l == 0x0064010b || l == 0x006400cc)
    {
        // OMAGIC / NMAGIC / ZMAGIC / QMAGIC
        exetype = 2;
        // FIXME: N_TRSIZE, N_DRSIZE
        // FIXME: check for aout shared libraries
    }
    else { // shell scripts and other interpreters
        if (Elf32_Ehdr::ELFOSABI_LINUX!=ei_osabi) {
            return false;  // so far, only Linux has runtime stub for shell
        }
        else if (!memcmp(buf, "#!/", 3))                    // #!/bin/sh
            exetype = -1;
        else if (!memcmp(buf, "#! /", 4))                   // #! /bin/sh
            exetype = -1;
        else if (!memcmp(buf, "\xca\xfe\xba\xbe", 4))       // Java bytecode
            exetype = -2;
    }
    return super::canPack();
}
References buf, PackUnix::canPack(), checkEhdr(), PackLinuxI386::Elf32_Note::descsz, ei_osabi, PackLinuxI386::Elf32_Note::end, PackUnix::exetype, PackerBase::fi, get_le32(), Packer::get_te16(), Packer::get_te32(), getFormat(), memcmp(), memset(), opt, Elf32_Phdr::p_offset, Elf32_Phdr::p_type, InputFile::readx(), InputFile::seek(), SEEK_SET, strcmp(), PackLinuxI386::Elf32_Note::text, PackLinuxI386::Elf32_Note::type, and UPX_F_BSD_i386.
Referenced by PackLinuxI386sh::getShellName().
checkEhdr()
int PackLinuxI386::checkEhdr (const Elf_LE32_Ehdr * ehdr) const protected virtual
some ELF utility functions
Definition at line 453 of file p_lx_exc.cpp.
{
    const unsigned char * const buf = ehdr->e_ident;
    if (memcmp(buf, "\x7f\x45\x4c\x46\x01\x01\x01", 7)) // ELF 32-bit LSB
        return -1;
    // now check the ELF header
    if (!memcmp(buf+8, "FreeBSD", 7))                  // branded
        return 1;
    if (ehdr->e_type != Elf32_Ehdr::ET_EXEC
    &&  ehdr->e_type != Elf32_Ehdr::ET_DYN )           // executable
        return 2;
    if (ehdr->e_machine != Elf32_Ehdr::EM_386)         // Intel 80386
        return 3;
    if (ehdr->e_version != Elf32_Ehdr::EV_CURRENT)     // version
        return 4;
    if (ehdr->e_phnum < 1)
        return 5;
    if (ehdr->e_phentsize != sizeof(Elf32_Phdr))
        return 6;
    // check for Linux kernels
    if (ehdr->e_entry == 0xC0100000)                    // uncompressed vmlinux
        return 1000;
    if (ehdr->e_entry == 0x00001000)                    // compressed vmlinux
        return 1001;
    if (ehdr->e_entry == 0x00100000)                    // compressed bvmlinux
        return 1002;
    // FIXME: add more checks for kernels
    // FIXME: add special checks for other ELF i386 formats, like
    //        NetBSD, OpenBSD, Solaris, ....
    // success
    return 0;
}
References buf, and memcmp().
Referenced by canPack().
compileTimeAssertions()
static void PackLinuxI386::compileTimeAssertions () inline static protected
Definition at line 122 of file p_lx_exc.h.
{
        COMPILE_TIME_ASSERT(sizeof(cprElfHdr1) == 52 + 1*32 + 12)
        COMPILE_TIME_ASSERT(sizeof(cprElfHdr2) == 52 + 2*32 + 12)
        COMPILE_TIME_ASSERT(sizeof(cprElfHdr3) == 52 + 3*32 + 12)
        COMPILE_TIME_ASSERT_ALIGNED1(cprElfHdr1)
        COMPILE_TIME_ASSERT_ALIGNED1(cprElfHdr2)
        COMPILE_TIME_ASSERT_ALIGNED1(cprElfHdr3)
    }
References COMPILE_TIME_ASSERT, and COMPILE_TIME_ASSERT_ALIGNED1.
generateElfHdr()
void PackLinuxI386::generateElfHdr (OutputFile * fo, void const * proto, unsigned const brka) virtual
Definition at line 129 of file p_lx_exc.cpp.
{
    cprElfHdr2 *const h2 = (cprElfHdr2 *)(void *)&elfout;
    cprElfHdr3 *const h3 = (cprElfHdr3 *)(void *)&elfout;
    memcpy(h3, proto, sizeof(*h3));  // reads beyond, but OK
    assert(h2->ehdr.e_phoff     == sizeof(Elf32_Ehdr));
    assert(h2->ehdr.e_shoff     == 0);
    assert(h2->ehdr.e_ehsize    == sizeof(Elf32_Ehdr));
    assert(h2->ehdr.e_phentsize == sizeof(Elf32_Phdr));
    assert(h2->ehdr.e_shnum     == 0);
#if 0  //{
    unsigned identsize;
    char const *const ident = getIdentstr(&identsize);
#endif  //}
    h2->phdr[0].p_filesz = sizeof(*h2);  // + identsize;
    h2->phdr[0].p_memsz  = h2->phdr[0].p_filesz;
    // Info for OS kernel to set the brk()
    if (brka) {
        set_stub_brk(&h2->phdr[1], brka);
    }
    if (ph.format==UPX_F_LINUX_i386
    ||  ph.format==UPX_F_LINUX_SH_i386
    ||  ph.format==UPX_F_BSD_i386
    ) {
        // SELinux, PAx, grSecurity demand no PF_W if PF_X.
        // kernel-2.6.12-2.3.legacy_FC3 has a bug which demands
        // a PT_LOAD with PF_W, else SIGSEGV when clearing page fragment
        // on low page of ".bss", which is the high page of .text.
        // So the minimum number of PT_LOAD is 2.
        assert(h2->ehdr.e_phnum==2);
        memset(&h2->linfo, 0, sizeof(h2->linfo));
        fo->write(h2, sizeof(*h2));
    }
    else if (ph.format==UPX_F_LINUX_ELFI_i386) {
        assert(h3->ehdr.e_phnum==3);
        memset(&h3->linfo, 0, sizeof(h3->linfo));
        fo->write(h3, sizeof(*h3));
    }
    else {
        assert(false);  // unknown ph.format, PackUnix::generateElfHdr
    }
}
References elfout, PackHeader::format, getIdentstr(), memcpy(), memset(), PackerBase::ph, set_stub_brk(), UPX_F_BSD_i386, UPX_F_LINUX_ELFI_i386, UPX_F_LINUX_i386, UPX_F_LINUX_SH_i386, and OutputFile::write().
Referenced by pack1(), PackBSDI386::pack1(), and PackLinuxI386sh::pack1().
getCompressionMethods()
static const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT const int * PackLinuxI386::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 88 of file p_lx_exc.cpp.
{
    return Packer::getDefaultCompressionMethods_le32(method, level);
}
References Packer::getDefaultCompressionMethods_le32().
getFilters()
const int * PackLinuxI386::getFilters () const override virtual
Reimplemented from PackUnix.
Reimplemented in PackLinuxI386sh.
Definition at line 93 of file p_lx_exc.cpp.
{
    static const int filters[] = {
        0x49, 0x46,
        0x26, 0x24, 0x11, 0x14, 0x13, 0x16, 0x25, 0x15, 0x12,
#if 0
// 0x80..0x87 are regarded as "untested".
        0x83, 0x86, 0x80, 0x84, 0x87, 0x81, 0x82, 0x85,
        0x24, 0x16, 0x13, 0x14, 0x11, 0x25, 0x15, 0x12,
#endif
    FT_END };
    return filters;
}
References FT_END.
getFormat()
virtual int PackLinuxI386::getFormat () const inline override virtual
Implements PackerBase.
Reimplemented in PackBSDI386, and PackLinuxI386sh.
Definition at line 51 of file p_lx_exc.h.
{ return UPX_F_LINUX_i386; }
References UPX_F_LINUX_i386.
Referenced by canPack().
getFullName()
virtual const char * PackLinuxI386::getFullName (const options_t *) const inline override virtual
Reimplemented in PackBSDI386, and PackLinuxI386sh.
Definition at line 53 of file p_lx_exc.h.
{ return "i386-linux.elf.execve"; }
getLoaderPrefixSize()
int PackLinuxI386::getLoaderPrefixSize () const protected virtual
Definition at line 442 of file p_lx_exc.cpp.
{
    return 116;
}
getName()
virtual const char * PackLinuxI386::getName () const inline override virtual
Implements PackerBase.
Reimplemented in PackBSDI386, and PackLinuxI386sh.
Definition at line 52 of file p_lx_exc.h.
{ return "linux.exec/i386"; }
newLinker()
Linker * PackLinuxI386::newLinker () const override protected virtual
Implements Packer.
Definition at line 282 of file p_lx_exc.cpp.
{
    return new ElfLinkerX86;
}
pack1()
void PackLinuxI386::pack1 (OutputFile * fo, Filter &) override protected virtual
Reimplemented from PackUnix.
Reimplemented in PackBSDI386, and PackLinuxI386sh.
Definition at line 181 of file p_lx_exc.cpp.
{
    // create a pseudo-unique program id for our paranoid stub
    progid = getRandomId();
    generateElfHdr(fo, stub_i386_linux_elf_execve_fold, 0);
}
References generateElfHdr(), Packer::getRandomId(), PackUnix::progid, and stub_i386_linux_elf_execve_fold.
pack4()
void PackLinuxI386::pack4 (OutputFile * fo, Filter & ft) override protected virtual
Reimplemented from PackUnix.
Definition at line 199 of file p_lx_exc.cpp.
{
    overlay_offset = sizeof(elfout.ehdr) +
        (elfout.ehdr.e_phentsize * elfout.ehdr.e_phnum) +
        sizeof(l_info) +
        ((elfout.ehdr.e_phnum==3) ? (unsigned) elfout.phdr[2].p_memsz : 0) ;
    unsigned nw = fo->getBytesWritten();
    elfout.phdr[0].p_filesz = nw;
    nw = 0u-((0u-elfout.phdr[0].p_align) & (0u-nw));  // ALIGN_UP
    super::pack4(fo, ft);  // write PackHeader and overlay_offset
    set_stub_brk(&elfout.phdr[1], nw + elfout.phdr[0].p_vaddr);
#if 0  // {
    // /usr/bin/strip from RedHat 8.0 (binutils-2.13.90.0.2-2)
    // generates a 92-byte [only] output, because the "linking view"
    // is empty.  This code supplies a "linking view".
    // However, 'strip' then generates _plausible_ junk that gets
    // "Illegal instruction"  because 'strip' changes p_hdr[1].p_align,
    // .p_offset, and .p_vaddr incorrectly.  So the "cure" is worse than
    // the disease.  It is obvious that a 92-byte file is bad,
    // but it is not obvious that the changed .p_align is bad.
    // Also, having a totally empty "linking view" is easier for 'strip'
    // to fix: just detect that, and do nothing.
    // So, we don't use this code for now [2003-01-11].
    // Supply a "linking view" that covers everything,
    // so that 'strip' does not omit everything.
    Elf_LE32_Shdr shdr;
    // The section header string table.
    char const shstrtab[] = "\0.\0.shstrtab";
    unsigned eod = elfout.phdr[0].p_filesz;
    elfout.ehdr.e_shoff = eod;
    elfout.ehdr.e_shentsize = sizeof(shdr);
    elfout.ehdr.e_shnum = 3;
    elfout.ehdr.e_shstrndx = 2;
    // An empty Elf32_Shdr for space as a null index.
    memset(&shdr, 0, sizeof(shdr));
    shdr.sh_type = Elf32_Shdr::SHT_NULL;
    fo->write(&shdr, sizeof(shdr));
    // Cover all the bits we need at runtime.
    memset(&shdr, 0, sizeof(shdr));
    shdr.sh_name = 1;
    shdr.sh_type = Elf32_Shdr::SHT_PROGBITS;
    shdr.sh_flags = Elf32_Shdr::SHF_ALLOC;
    shdr.sh_addr = elfout.phdr[0].p_vaddr;
    shdr.sh_offset = overlay_offset;
    shdr.sh_size = eod - overlay_offset;
    shdr.sh_addralign = 4096;
    fo->write(&shdr, sizeof(shdr));
    // A section header for the section header string table.
    memset(&shdr, 0, sizeof(shdr));
    shdr.sh_name = 3;
    shdr.sh_type = Elf32_Shdr::SHT_STRTAB;
    shdr.sh_offset = 3*sizeof(shdr) + eod;
    shdr.sh_size = sizeof(shstrtab);
    fo->write(&shdr, sizeof(shdr));
    fo->write(shstrtab, sizeof(shstrtab));
#endif  // }
    // Cannot pre-round .p_memsz.  If .p_filesz < .p_memsz, then kernel
    // tries to make .bss, which requires PF_W.
    // But strict SELinux (or PaX, grSecurity) disallows PF_W with PF_X.
#if 0  /*{*/
#undef PAGE_MASK
#define PAGE_MASK (~0u<<12)
    // pre-calculate for benefit of runtime disappearing act via munmap()
    elfout.phdr[0].p_memsz =  PAGE_MASK & (~PAGE_MASK + elfout.phdr[0].p_filesz);
#undef PAGE_MASK
#else  /*}{*/
    elfout.phdr[0].p_memsz =  elfout.phdr[0].p_filesz;
#endif  /*}*/
    // rewrite Elf header
    fo->seek(0, SEEK_SET);
    fo->rewrite(&elfout, overlay_offset);
}
References elfout, OutputFile::getBytesWritten(), memset(), PackUnix::overlay_offset, PackUnix::pack4(), PAGE_MASK, OutputFile::rewrite(), OutputFile::seek(), SEEK_SET, set_stub_brk(), shstrtab, and OutputFile::write().
packed_struct() [1/3]
PackLinuxI386::packed_struct (cprElfHdr1) inline protected
Definition at line 91 of file p_lx_exc.h.
{
        Elf_LE32_Ehdr ehdr;
        Elf_LE32_Phdr phdr[1];
        l_info linfo;
    };
References PackUnix::linfo.
packed_struct() [2/3]
PackLinuxI386::packed_struct (cprElfHdr2) inline protected
Definition at line 97 of file p_lx_exc.h.
{
        Elf_LE32_Ehdr ehdr;
        Elf_LE32_Phdr phdr[2];
        l_info linfo;
    };
References PackUnix::linfo.
packed_struct() [3/3]
PackLinuxI386::packed_struct (cprElfHdr3) inline protected
Definition at line 103 of file p_lx_exc.h.
{
        Elf_LE32_Ehdr ehdr;
        Elf_LE32_Phdr phdr[3];
        l_info linfo;
    };
References PackUnix::linfo.
patchLoader()
void PackLinuxI386::patchLoader () override protected virtual
Implements PackUnix.
Reimplemented in PackLinuxI386sh.
Definition at line 593 of file p_lx_exc.cpp.
{ }
patchLoaderChecksum()
void PackLinuxI386::patchLoaderChecksum () override protected virtual
Reimplemented from PackUnix.
Definition at line 596 of file p_lx_exc.cpp.
{
    unsigned char *const ptr = getLoader();
    l_info *const lp = (l_info *)(sizeof(elfout.ehdr) +
        (elfout.ehdr.e_phnum * elfout.ehdr.e_phentsize) + (char *)&elfout );
    // checksum for loader + p_info
    lp->l_checksum = 0;
    lp->l_magic = UPX_ELF_MAGIC;
    set_te16(&lp->l_lsize, (upx_uint16_t) lsize);
    lp->l_version = (unsigned char) ph.version;
    lp->l_format  = (unsigned char) ph.format;
    // INFO: lp->l_checksum is currently unused
    set_te32(&lp->l_checksum, upx_adler32(ptr, lsize));
}
References elfout, PackHeader::format, Packer::getLoader(), l_info::l_checksum, l_info::l_format, l_info::l_lsize, l_info::l_magic, l_info::l_version, PackUnix::lsize, PackerBase::ph, ptr, Packer::set_te16(), Packer::set_te32(), upx_adler32(), UPX_ELF_MAGIC, and PackHeader::version.
updateLoader()
void PackLinuxI386::updateLoader (OutputFile * fo) override protected virtual
Implements PackUnix.
Definition at line 612 of file p_lx_exc.cpp.
{
    elfout.ehdr.e_entry = fo->getBytesWritten() + elfout.phdr[0].p_vaddr;
}
References elfout, and OutputFile::getBytesWritten().
Member Data Documentation
ei_osabi
unsigned char PackLinuxI386::ei_osabi protected
Definition at line 119 of file p_lx_exc.h.
Referenced by canPack(), and PackBSDI386::PackBSDI386().
elfnote
struct PackLinuxI386::Elf32_Note PackLinuxI386::elfnote protected
elfout
cprElfHdr3 PackLinuxI386::elfout protected
Definition at line 109 of file p_lx_exc.h.
Referenced by generateElfHdr(), PackLinuxI386sh::pack3(), pack4(), patchLoaderChecksum(), and updateLoader().
n_mru
unsigned PackLinuxI386::n_mru protected
Definition at line 89 of file p_lx_exc.h.
Referenced by buildLinuxLoader().
osabi_note
char const* PackLinuxI386::osabi_note protected
Definition at line 120 of file p_lx_exc.h.
The documentation for this class was generated from the following files:
src/p_lx_exc.h
src/p_lx_exc.cpp