My Project: PeFile::Reloc Class Reference
PeFile::Reloc Class Reference final
#include <pefile.h>
Classes
struct BaseReloc
struct RelocationBlock
Public Member Functions
Reloc (byte *ptr, unsigned bytes)
Reloc (unsigned relocnum)
~Reloc () noexcept
bool next (unsigned &result_pos, unsigned &result_reloc_type)
const unsigned * getcounts () const
void add_reloc (unsigned pos, unsigned reloc_type)
void finish (byte *(&result_ptr), unsigned &result_size)
Private Member Functions
SPAN_0 (byte) start_buf
bool readFromRelocationBlock (byte *)
void initSpans ()
Private Member Functions inherited from upx::noncopyable
forceinline constexpr noncopyable () noexcept
forceinline ~noncopyable () noexcept=default
Private Attributes
byte * start = nullptr
unsigned start_size_in_bytes = 0
bool start_did_alloc = false
RelocationBlock rb
unsigned counts [16] = {}
Detailed Description
Definition at line 426 of file pefile.h.
Constructor & Destructor Documentation
Reloc() [1/2]
PeFile::Reloc::Reloc (byte * ptr, unsigned bytes) explicit
Definition at line 333 of file pefile.cpp.
{
    assert(opt->cmd == CMD_COMPRESS);
    start_size_in_bytes = mem_size(1, bytes);
    start = ptr;
    initSpans();
    // fill counts
    unsigned pos, reloc_type;
    while (next(pos, reloc_type))
        counts[reloc_type]++;
}
References CMD_COMPRESS, mem_size(), opt, and ptr.
Reloc() [2/2]
PeFile::Reloc::Reloc (unsigned relocnum) explicit
Definition at line 344 of file pefile.cpp.
{
    start_size_in_bytes = mem_size(RELOC_ENTRY_SIZE, relocnum, RELOC_INPLACE_OFFSET, 8192);
    start = new byte[start_size_in_bytes]; // => transfer ownership to oxrelocs[] in finish()
    start_did_alloc = true;
    initSpans();
}
References mem_size(), RELOC_ENTRY_SIZE, and RELOC_INPLACE_OFFSET.
~Reloc()
PeFile::Reloc::~Reloc () noexcept
Definition at line 325 of file pefile.cpp.
{
    COMPILE_TIME_ASSERT(sizeof(BaseReloc) == 8)
    COMPILE_TIME_ASSERT_ALIGNED1(BaseReloc)
    if (start_did_alloc) // don't leak memory on exceptions
        delete[] start;
}
References COMPILE_TIME_ASSERT, and COMPILE_TIME_ASSERT_ALIGNED1.
Member Function Documentation
add_reloc()
void PeFile::Reloc::add_reloc (unsigned pos, unsigned reloc_type)
Definition at line 422 of file pefile.cpp.
{
    assert(start_did_alloc);
    // assert(reloc_type != IMAGE_REL_BASED_IGNORE);
    if (reloc_type == IMAGE_REL_BASED_IGNORE)
        return;
    auto entry_ptr = start_buf + mem_size(RELOC_ENTRY_SIZE, counts[0], RELOC_INPLACE_OFFSET);
    reloc_entry_encode(entry_ptr, pos, reloc_type);
    counts[0] += 1;
}
References PeFile::IMAGE_REL_BASED_IGNORE, mem_size(), reloc_entry_encode(), RELOC_ENTRY_SIZE, and RELOC_INPLACE_OFFSET.
Referenced by PackW32PeI386::addNewRelocations(), PackWinCeArm::addNewRelocations(), PeFile::processLoadConf(), PeFile::processTls2(), and PeFile::rebuildRelocs().
finish()
void PeFile::Reloc::finish (byte *& result_ptr, unsigned & result_size)
Definition at line 432 of file pefile.cpp.
{
    assert(start_did_alloc);
    // sort in-place relocs
    upx_qsort(
        raw_index_bytes(start_buf, RELOC_INPLACE_OFFSET, mem_size(RELOC_ENTRY_SIZE, counts[0])),
        counts[0], RELOC_ENTRY_SIZE, reloc_entry_compare);
    auto finish_block = [](SPAN_S(BaseReloc) rel) -> byte * {
        unsigned sob = rel->size_of_block;
        assert(sob >= 10 && (sob & 1) == 0);
        auto end = SPAN_TYPE_CAST(byte, rel) + sob;
        while ((sob & 3) != 0) { // UPX: we want align by 4 here
            *end++ = 0;          // clear byte (i.e. write IMAGE_REL_BASED_IGNORE)
            sob += 1;
        }
        rel->size_of_block = sob;
        return raw_bytes(end, 0);
    };
    rb.reset();
    unsigned prev_pos = 0;
    unsigned current_page = 0;
    for (unsigned ic = 0; ic < counts[0]; ic++) {
        const auto entry_ptr = start_buf + mem_size(RELOC_ENTRY_SIZE, ic, RELOC_INPLACE_OFFSET);
        unsigned pos, reloc_type;
        reloc_entry_decode(entry_ptr, &pos, &reloc_type);
        if (ic > 0 && pos == prev_pos) {
            if (ALWAYS_CHECK_STRICT_RELOCS)
                throwCantPack("duplicate relocs");
            else if (!opt->force)
                throwCantPack("duplicate relocs (try --force)");
        }
        prev_pos = pos;
        if (ic == 0 || pos - current_page >= 0x1000) {
            current_page = pos & ~0xfff; // page start
            // prepare next block for writing
            byte *next_rb = (rb.rel == nullptr) ? start : finish_block(rb.rel);
            rb.rel = (BaseReloc *) next_rb;
            rb.rel1 = (LE16 *) (next_rb + 8);
            rb.rel->virtual_address = current_page;
            rb.rel->size_of_block = 8;
        }
        // check for in-place overflow
        if (ptr_diff_bytes(rb.rel1, entry_ptr) >= 0) {
            // info: if this is indeed a valid file we must increase RELOC_INPLACE_OFFSET
            throwCantPack("too many inplace relocs");
        }
        // write LE16 IMAGE_BASE_RELOCATION relocation
        *rb.rel1++ = (reloc_type << 12) | (pos & 0xfff);
        rb.rel->size_of_block += 2;
    }
    result_size = 0; // result_size can be 0 in 64-bit mode
    if (rb.rel != nullptr)
        result_size = ptr_udiff_bytes(finish_block(rb.rel), start);
    assert((result_size & 3) == 0);
    // transfer ownership
    assert(start_did_alloc);
    result_ptr = start;
    start_did_alloc = false;
#if DEBUG || 1 // safety, as we are really finished
    ptr_invalidate_and_poison(start);
    start_size_in_bytes = 0;
    SPAN_INVALIDATE(start_buf);
    SPAN_INVALIDATE(rb.rel);
    SPAN_INVALIDATE(rb.rel1);
    rb.count = 0xdeaddead;
#endif
}
References ALWAYS_CHECK_STRICT_RELOCS, mem_size(), opt, ptr_diff_bytes(), ptr_invalidate_and_poison(), ptr_udiff_bytes(), raw_bytes(), raw_index_bytes(), reloc_entry_compare(), reloc_entry_decode(), RELOC_ENTRY_SIZE, RELOC_INPLACE_OFFSET, SPAN_INVALIDATE, SPAN_S, SPAN_TYPE_CAST, throwCantPack(), and upx_qsort.
Referenced by PeFile::callProcessStubRelocs(), and PeFile::rebuildRelocs().
getcounts()
const unsigned * PeFile::Reloc::getcounts () const inline
Definition at line 456 of file pefile.h.
{ return counts; }
Referenced by PeFile32::processRelocs(), and PeFile64::processRelocs().
initSpans()
void PeFile::Reloc::initSpans () private
Definition at line 351 of file pefile.cpp.
{
    start_buf = SPAN_0_MAKE(byte, start, start_size_in_bytes); // => now a SPAN_S
    rb.rel = SPAN_TYPE_CAST(BaseReloc, start_buf);             // SPAN_0
    rb.rel1 = SPAN_TYPE_CAST(LE16, start_buf);                 // SPAN_0
    rb.reset();
}
References SPAN_0_MAKE, and SPAN_TYPE_CAST.
next()
bool PeFile::Reloc::next (unsigned & result_pos, unsigned & result_reloc_type)
Definition at line 400 of file pefile.cpp.
{
    assert(!start_did_alloc);
    for (;;) {
        // search current block
        while (rb.count > 0) {
            rb.count -= 1;
            const unsigned value = *rb.rel1++;
            result_pos = rb.rel->virtual_address + (value & 0xfff);
            result_reloc_type = (value >> 12) & 0xf;
            NO_printf("Reloc::next %#x %d\n", result_pos, result_reloc_type);
            if (result_reloc_type != IMAGE_REL_BASED_IGNORE)
                return true; // success
        }
        // advance to next block
        byte *next_rb = (rb.rel == nullptr) ? start : (byte *) raw_bytes(rb.rel1, 0);
        if (!readFromRelocationBlock(next_rb)) {
            rb.reset();   // rewind
            return false; // EOF
        }
    }
}
References PeFile::IMAGE_REL_BASED_IGNORE, NO_printf(), and raw_bytes().
Referenced by PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), and PeFile::processTls1().
readFromRelocationBlock()
bool PeFile::Reloc::readFromRelocationBlock (byte * next_rb) private
Definition at line 359 of file pefile.cpp.
                                                       { // set rb
    assert(!start_did_alloc);
    const unsigned off = ptr_udiff_bytes(next_rb, start);
    assert((off & 1) == 0);
    rb.reset();
    if (off >= start_size_in_bytes) { // permissive: use ">=" instead of strict "=="
        if (off > start_size_in_bytes) {
            // MAYBE TODO later: could add a warning here?
        }
        return false; // EOF
    }
    if (start_size_in_bytes - off < 8)
        throwCantPack("relocs overflow");
    const unsigned sob = get_le32(start_buf + (off + 4)); // size_of_block
#if 1
    // ignore a dubious single empty relocation block with sob == 0
    if (sob == 0 && (off == 0 && start_size_in_bytes == 8))
        return false; // EOF
#endif
    if (ALWAYS_CHECK_STRICT_RELOCS) {
        if (sob < 8)
            throwCantPack("bad reloc size_of_block %u", sob);
        if (start_size_in_bytes - off < sob)
            throwCantPack("overflow reloc size_of_block %u", sob);
        if ((sob & 1) != 0)
            throwCantPack("odd reloc size_of_block %u", sob);
    } else if (!opt->force) {
        if (sob < 8)
            throwCantPack("bad reloc size_of_block %u (try --force)", sob);
        if (start_size_in_bytes - off < sob)
            throwCantPack("overflow reloc size_of_block %u (try --force)", sob);
        if ((sob & 1) != 0)
            throwCantPack("odd reloc size_of_block %u (try --force)", sob);
    }
    // success
    rb.rel = (BaseReloc *) next_rb;   // SPAN checked
    rb.rel1 = (LE16 *) (next_rb + 8); // SPAN checked
    rb.count = sob < 8 ? 0 : (sob - 8) / sizeof(LE16);
    return true;
}
References ALWAYS_CHECK_STRICT_RELOCS, get_le32(), opt, ptr_udiff_bytes(), and throwCantPack().
SPAN_0()
PeFile::Reloc::SPAN_0 (byte) private
Member Data Documentation
counts
unsigned PeFile::Reloc::counts[16] = {} private
Definition at line 447 of file pefile.h.
rb
RelocationBlock PeFile::Reloc::rb private
Definition at line 444 of file pefile.h.
start
byte* PeFile::Reloc::start = nullptr private
Definition at line 428 of file pefile.h.
start_did_alloc
bool PeFile::Reloc::start_did_alloc = false private
Definition at line 430 of file pefile.h.
start_size_in_bytes
unsigned PeFile::Reloc::start_size_in_bytes = 0 private
Definition at line 429 of file pefile.h.
The documentation for this class was generated from the following files:
src/pefile.h
src/pefile.cpp