My Project: FilterImpl Class Reference
FilterImpl Class Reference final
We don't want a full OO interface here because of certain implementation speed reasons.
#include <filter.h>
Classes
struct FilterEntry
Private Member Functions
FilterImpl () noexcept DELETED_FUNCTION
Static Private Member Functions
static const FilterEntry * getFilter (int id)
get a FilterEntry
Static Private Attributes
static const FilterEntry filters []
database for use in class Filter
static const int n_filters = TABLESIZE(filters)
Friends
class Filter
Detailed Description
We don't want a full OO interface here because of certain implementation speed reasons.
This class is private to Filter - don't look.
Definition at line 99 of file filter.h.
Constructor & Destructor Documentation
FilterImpl()
FilterImpl::FilterImpl () explicit private noexcept
Member Function Documentation
getFilter()
const FilterImpl::FilterEntry * FilterImpl::getFilter (int id) static private
get a FilterEntry
Definition at line 47 of file filter.cpp.
{
    static upx_uint8_t filter_map[256];
    static upx_std_once_flag init_done;
    upx_std_call_once(init_done, []() noexcept {
        // init the filter_map[] (using a lambda function)
        assert_noexcept(n_filters <= 254); // as 0xff means "empty slot"
        memset(filter_map, 0xff, sizeof(filter_map));
        for (int i = 0; i < n_filters; i++) {
            int filter_id = filters[i].id;
            assert_noexcept(filter_id >= 0 && filter_id <= 255);
            assert_noexcept(filter_map[filter_id] == 0xff);
            filter_map[filter_id] = (upx_uint8_t) i;
        }
    });
    if (id < 0 || id > 255)
        return nullptr;
    unsigned index = filter_map[id];
    if (index == 0xff) // empty slot
        return nullptr;
    assert_noexcept(filters[index].id == id);
    return &filters[index];
}
References assert_noexcept, filters, FilterImpl::FilterEntry::id, index, memset(), n_filters, upx_std_call_once(), and upx_std_once_flag.
Referenced by Filter::filter(), Filter::isValidFilter(), Filter::scan(), and Filter::unfilter().
Friends And Related Function Documentation
Filter
friend class Filter friend
Definition at line 100 of file filter.h.
Member Data Documentation
filters
const FilterImpl::FilterEntry FilterImpl::filters static private
database for use in class Filter
Definition at line 119 of file filter.h.
Referenced by getFilter().
n_filters
const int FilterImpl::n_filters = TABLESIZE(filters) static private
Definition at line 120 of file filter.h.
Referenced by getFilter().
The documentation for this class was generated from the following files:
src/filter.h
src/filter.cpp
src/filter/filter_impl.cpp