My Project: MemBuffer Class Reference
MemBuffer Class Reference final
MemBuffer.
#include <membuffer.h>
Classes
struct Stats
Public Member Functions
MemBuffer () noexcept
MemBuffer (upx_uint64_t bytes) may_throw
~MemBuffer () noexcept
void alloc (upx_uint64_t bytes) may_throw
void allocForCompression (unsigned uncompressed_size, unsigned extra=0) may_throw
void allocForDecompression (unsigned uncompressed_size, unsigned extra=0) may_throw
void dealloc () noexcept
void checkState () const may_throw
void * getVoidPtr () noexcept
const void * getVoidPtr () const noexcept
unsigned getSizeInBytes () const noexcept
unsigned getSize () const noexcept
noinline void fill (unsigned off, unsigned len, int value) may_throw
forceinline void clear (unsigned off, unsigned len) may_throw
forceinline void clear () may_throw
forceinline pointer subref (const char *errfmt, size_t skip, size_t take) may_throw
Public Member Functions inherited from MemBufferBase< byte >
MemBufferBase () noexcept
forceinline ~MemBufferBase () noexcept
operator pointer () const noexcept
reference operator[] (ptrdiff_t i) const may_throw
reference operator* () const DELETED_FUNCTION
pointer operator-> () const DELETED_FUNCTION
iterator begin () const may_throw
const_iterator cbegin () const may_throw
iterator end () const may_throw
const_iterator cend () const may_throw
std::enable_if< std::is_integral< U >::value, pointer >::type operator+ (U n) const may_throw
pointer raw_ptr () const noexcept
size_type raw_size_in_bytes () const noexcept
pointer raw_bytes (size_t bytes) const may_throw
Static Public Member Functions
static unsigned getSizeForCompression (unsigned uncompressed_size, unsigned extra=0) may_throw
static unsigned getSizeForDecompression (unsigned uncompressed_size, unsigned extra=0) may_throw
Private Member Functions
void * subref_impl (const char *errfmt, size_t skip, size_t take) may_throw
Static Private Attributes
static Stats stats
Additional Inherited Members
Public Types inherited from MemBufferBase< byte >
typedef byte element_type
typedef std::add_lvalue_reference< byte >::type reference
typedef std::add_pointer< byte >::type pointer
typedef unsigned size_type
typedef pointer iterator
typedef std::add_pointer< constT >::type const_iterator
Protected Attributes inherited from MemBufferBase< byte >
pointer ptr
size_type size_in_bytes
Static Protected Attributes inherited from MemBufferBase< byte >
static const size_t element_size
Detailed Description
MemBuffer.
Definition at line 187 of file membuffer.h.
Constructor & Destructor Documentation
MemBuffer() [1/2]
MemBuffer::MemBuffer () inline explicit noexcept
Definition at line 189 of file membuffer.h.
: MemBufferBase<byte>() {}
MemBuffer() [2/2]
MemBuffer::MemBuffer (upx_uint64_t bytes) explicit
Definition at line 78 of file membuffer.cpp.
                                                 : MemBufferBase<byte>() {
    static_assert(element_size == 1);
    alloc(bytes);
    debug_set(debug.last_return_address_alloc, upx_return_address());
}
References debug_set, and upx_return_address.
~MemBuffer()
MemBuffer::~MemBuffer () noexcept
Definition at line 84 of file membuffer.cpp.
{ this->dealloc(); }
References dealloc().
Member Function Documentation
alloc()
void MemBuffer::alloc (upx_uint64_t bytes)
Definition at line 170 of file membuffer.cpp.
{
    // INFO: we don't automatically free a used buffer
    assert(ptr == nullptr);
    assert(size_in_bytes == 0);
    //
    assert(bytes > 0);
    debug_set(debug.last_return_address_alloc, upx_return_address());
    size_t malloc_bytes = mem_size(1, bytes); // check size
    if (use_simple_mcheck())
        malloc_bytes += 32;
    byte *p = (byte *) ::malloc(malloc_bytes);
    NO_printf("MemBuffer::alloc %llu: %p\n", bytes, p);
    if (!p)
        throwOutOfMemoryException();
    size_in_bytes = ACC_ICONV(unsigned, bytes);
    if (use_simple_mcheck()) {
        p += 16;
        // store magic constants to detect buffer overruns
        set_ne32(p - 8, size_in_bytes);
        set_ne32(p - 4, MAGIC1(p));
        set_ne32(p + size_in_bytes + 0, MAGIC2(p));
        set_ne32(p + size_in_bytes + 4, stats.global_alloc_counter);
    }
    ptr = upx::ptr_static_cast<pointer>(p);
#if !defined(__SANITIZE_MEMORY__) && DEBUG
    memset(ptr, 0xfb, size_in_bytes);
    (void) VALGRIND_MAKE_MEM_UNDEFINED(ptr, size_in_bytes);
#endif
    stats.global_alloc_counter += 1;
    stats.global_total_bytes += size_in_bytes;
    stats.global_total_active_bytes += size_in_bytes;
#if DEBUG || 1
    checkState();
#endif
}
References ACC_ICONV, debug_set, MAGIC1, MAGIC2, mem_size(), memset(), NO_printf(), ptr, set_ne32(), size_in_bytes, throwOutOfMemoryException(), upx_return_address, use_simple_mcheck(), and VALGRIND_MAKE_MEM_UNDEFINED.
Referenced by alloc_file_image(), allocForCompression(), allocForDecompression(), PeFile::canUnpack0(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackWcle::encodeImage(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackUnix::packExtent(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), PeFile::processExports(), PeFile::processImports0(), PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), PeFile::processTls1(), LeFile::readImage(), PackVmlinuzI386::readKernel(), PackVmlinuzARMEL::readKernel(), PackWcle::readObjectTable(), PeFile::readSectionHeaders(), PeFile::readSections(), PackLinuxElf32::sort_DT32_offsets(), PackLinuxElf64::sort_DT64_offsets(), TEST_CASE(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), Packer::unoptimizeReloc(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackUnix::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), and PeFile::unpack0().
allocForCompression()
void MemBuffer::allocForCompression (unsigned uncompressed_size, unsigned extra = 0)
Definition at line 125 of file membuffer.cpp.
{
    unsigned bytes = getSizeForCompression(uncompressed_size, extra);
    alloc(bytes);
    debug_set(debug.last_return_address_alloc, upx_return_address());
}
References alloc(), debug_set, getSizeForCompression(), and upx_return_address.
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackExe::buildLoader(), Packer::compressWithFilters(), PackWcle::encodeImage(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackVmlinuxBase< TElfClass >::pack(), PeFile::pack0(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackUnix::packExtent(), PackVmlinuzI386::readKernel(), and PackVmlinuzARMEL::readKernel().
allocForDecompression()
void MemBuffer::allocForDecompression (unsigned uncompressed_size, unsigned extra = 0)
Definition at line 131 of file membuffer.cpp.
{
    unsigned bytes = getSizeForDecompression(uncompressed_size, extra);
    alloc(bytes);
    debug_set(debug.last_return_address_alloc, upx_return_address());
}
References alloc(), debug_set, getSizeForDecompression(), and upx_return_address.
Referenced by PackWcle::decodeImage(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), and PeFile::unpack0().
checkState()
void MemBuffer::checkState () const
Definition at line 155 of file membuffer.cpp.
{
    if (!ptr)
        throwInternalError("block not allocated");
    assert(size_in_bytes > 0);
    if (use_simple_mcheck()) {
        const byte *p = (const byte *) ptr;
        if (get_ne32(p - 4) != MAGIC1(p))
            throwInternalError("memory clobbered before allocated block 1");
        if (get_ne32(p - 8) != size_in_bytes)
            throwInternalError("memory clobbered before allocated block 2");
        if (get_ne32(p + size_in_bytes) != MAGIC2(p))
            throwInternalError("memory clobbered past end of allocated block");
    }
}
References get_ne32(), MAGIC1, MAGIC2, MemBufferBase< byte >::ptr, MemBufferBase< byte >::size_in_bytes, throwInternalError(), and use_simple_mcheck().
Referenced by Packer::compressWithFilters(), dealloc(), fill(), TEST_CASE(), and Packer::verifyOverlappingDecompression().
clear() [1/2]
forceinline void MemBuffer::clear () inline
Definition at line 213 of file membuffer.h.
{ fill(0, size_in_bytes, 0); }
References fill(), and MemBufferBase< byte >::size_in_bytes.
clear() [2/2]
forceinline void MemBuffer::clear (unsigned off, unsigned len) inline
Definition at line 212 of file membuffer.h.
{ fill(off, len, 0); }
References fill().
Referenced by fpadN(), PackPs1::pack(), PeFile::pack0(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackMachBase< TMachClass >::pack1(), PeFile::processExports(), PeFile::processImports0(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), PeFile::processTls1(), LeFile::readImage(), PeFile::readSections(), PackLinuxElf32::sort_DT32_offsets(), PackLinuxElf64::sort_DT64_offsets(), TEST_CASE(), PackDjgpp2::unpack(), PackPs1::unpack(), and PeFile::unpack0().
dealloc()
void MemBuffer::dealloc () noexcept
Definition at line 206 of file membuffer.cpp.
{
    if (ptr != nullptr) {
        debug_set(debug.last_return_address_dealloc, upx_return_address());
#if DEBUG || 1
        // info: calling checkState() here violates "noexcept", so we need a try block
        bool shall_check = true;
        // bool shall_check = (std::uncaught_exceptions() == 0); // only if not unwinding
        // TODO later: add a priority() method to class Throwable
        if (shall_check) {
            try {
                checkState();
            } catch (const Throwable &e) {
                printErr("unknown", e);
                std::terminate();
            } catch (...) {
                std::terminate();
            }
        }
#endif
        stats.global_dealloc_counter += 1;
        stats.global_total_active_bytes -= size_in_bytes;
        if (use_simple_mcheck()) {
            byte *p = (byte *) ptr;
            // clear magic constants
            set_ne32(p - 8, 0);
            set_ne32(p - 4, 0);
            set_ne32(p + size_in_bytes, 0);
            set_ne32(p + size_in_bytes + 4, 0);
            //
            ::free(p - 16); // NOLINT(clang-analyzer-unix.Malloc) // see NOTE above
        } else {
            ::free(ptr); // NOLINT(clang-analyzer-unix.Malloc) // see NOTE above
        }
        ptr = nullptr;
        size_in_bytes = 0;
    } else {
        assert_noexcept(size_in_bytes == 0);
    }
}
References assert_noexcept, checkState(), debug_set, printErr(), MemBufferBase< byte >::ptr, set_ne32(), MemBufferBase< byte >::size_in_bytes, stats, upx_return_address, and use_simple_mcheck().
Referenced by PackWcle::decodeFixups(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackWcle::encodeImage(), PackTmt::pack(), PackWcle::pack(), PackVmlinuzI386::readKernel(), PackVmlinuzARMEL::readKernel(), PeFile::rebuildRelocs(), PackWcle::unpack(), PeFile::unpack0(), and ~MemBuffer().
fill()
void MemBuffer::fill (unsigned off, unsigned len, int value)
Definition at line 137 of file membuffer.cpp.
{
    debug_set(debug.last_return_address_fill, upx_return_address());
    checkState();
    if (off > size_in_bytes || len > size_in_bytes || off + len > size_in_bytes)
        throwCantPack("MemBuffer::fill out of range; take care!");
    if (len > 0)
        memset(ptr + off, value, len);
}
References checkState(), debug_set, memset(), MemBufferBase< byte >::ptr, MemBufferBase< byte >::size_in_bytes, throwCantPack(), and upx_return_address.
Referenced by clear(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), and PeFile::stripDebug().
getSize()
unsigned MemBuffer::getSize () const inline noexcept
Definition at line 208 of file membuffer.h.
{ return size_in_bytes; } // note: element_size == 1
References MemBufferBase< byte >::size_in_bytes.
Referenced by alloc_file_image(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackMachBase< TMachClass >::canUnpack(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackWcle::encodeImage(), PackLinuxElf64::find_dt_ndx(), PackLinuxElf32::find_dt_ndx(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackLinuxElf::pack3(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), PeFile::readSections(), PeFile::rebuildResources(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackMachBase< TMachClass >::unpack(), PackUnix::unpackExtent(), PackLinuxElf64::unRela64(), and Packer::verifyOverlappingDecompression().
getSizeForCompression()
unsigned MemBuffer::getSizeForCompression (unsigned uncompressed_size, unsigned extra = 0) static
Definition at line 103 of file membuffer.cpp.
{
    if (uncompressed_size == 0)
        throwCantPack("invalid uncompressed_size");
    const size_t z = uncompressed_size; // fewer keystrokes and display columns
    size_t bytes = mem_size(1, z);      // check size
    // All literal: 1 bit overhead per literal byte; from UCL documentation
    bytes = upx::umax(bytes, z + z / 8 + 256);
    // zstd: ZSTD_COMPRESSBOUND
    bytes = upx::umax(bytes, z + (z >> 8) + ((z < (128 << 10)) ? (((128 << 10) - z) >> 11) : 0));
    // add extra and 256 safety for various rounding/alignments
    bytes = mem_size(1, bytes, extra, 256);
    return ACC_ICONV(unsigned, bytes);
}
References ACC_ICONV, mem_size(), throwCantPack(), and upx::umax().
Referenced by allocForCompression(), PackExe::buildLoader(), PackPs1::buildLoader(), PackExe::pack(), PackPs1::putBkupHeader(), TEST_CASE(), and upx_compress().
getSizeForDecompression()
unsigned MemBuffer::getSizeForDecompression (unsigned uncompressed_size, unsigned extra = 0) static
Definition at line 118 of file membuffer.cpp.
{
    if (uncompressed_size == 0)
        throwCantPack("invalid uncompressed_size");
    size_t bytes = mem_size(1, uncompressed_size, extra); // check size
    return ACC_ICONV(unsigned, bytes);
}
References ACC_ICONV, mem_size(), and throwCantPack().
Referenced by allocForDecompression(), PackPs1::getBkupHeader(), and TEST_CASE().
getSizeInBytes()
unsigned MemBuffer::getSizeInBytes () const inline noexcept
Definition at line 207 of file membuffer.h.
{ return size_in_bytes; }
References MemBufferBase< byte >::size_in_bytes.
getVoidPtr() [1/2]
const void * MemBuffer::getVoidPtr () const inline noexcept
Definition at line 206 of file membuffer.h.
{ return (const void *) ptr; }
References MemBufferBase< byte >::ptr.
getVoidPtr() [2/2]
void * MemBuffer::getVoidPtr () inline noexcept
Definition at line 205 of file membuffer.h.
{ return (void *) ptr; }
References MemBufferBase< byte >::ptr.
Referenced by alloc_file_image(), PackMachBase< TMachClass >::buildMachLoader(), PackLinuxElf64::find_dt_ndx(), PackLinuxElf32::find_dt_ndx(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf32::invert_pt_dynamic(), PackLinuxElf64::invert_pt_dynamic(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), PeFile::processLoadConf(), PackLinuxElf32::sort_DT32_offsets(), PackLinuxElf64::sort_DT64_offsets(), TEST_CASE(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackMachBase< TMachClass >::unpack(), and PackLinuxElf64::unRela64().
subref()
forceinline pointer MemBuffer::subref (const char * errfmt, size_t skip, size_t take) inline
Definition at line 219 of file membuffer.h.
{
        return (pointer) subref_impl(errfmt, skip, take);
    }
References subref_impl().
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PeFile::pack0(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PeFile::processImports0(), PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), PeFile::processTls1(), PeFile::readSections(), PeFile::stripDebug(), TEST_CASE(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), and PeFile::unpack0().
subref_impl()
void * MemBuffer::subref_impl (const char * errfmt, size_t skip, size_t take) private
Definition at line 88 of file membuffer.cpp.
{
    debug_set(debug.last_return_address_subref, upx_return_address());
    // check overrun and wrap-around
    if (skip + take > size_in_bytes || skip + take < skip) {
        char buf[100];
        // printf is using unsigned formatting
        if (!errfmt || !errfmt[0])
            errfmt = "bad subref %#x %#x";
        upx_safe_snprintf(buf, sizeof(buf), errfmt, (unsigned) skip, (unsigned) take);
        throwCantPack(buf);
    }
    return ptr + skip;
}
References buf, debug_set, MemBufferBase< byte >::ptr, MemBufferBase< byte >::size_in_bytes, throwCantPack(), upx_return_address, and upx_safe_snprintf().
Referenced by subref().
Member Data Documentation
stats
MemBuffer::Stats MemBuffer::stats static private
Definition at line 239 of file membuffer.h.
Referenced by dealloc().
The documentation for this class was generated from the following files:
src/util/membuffer.h
src/util/membuffer.cpp