My Project: PackWcle Class Reference
PackWcle Class Reference final
watcom/le
#include <p_wcle.h>
Public Member Functions
PackWcle (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual void handleStub (OutputFile *fo)
util
virtual void buildLoader (const Filter *ft) override
virtual Linker * newLinker () const override
virtual void readObjectTable () override
virtual void encodeObjectTable ()
virtual void decodeObjectTable ()
virtual void encodeFixupPageTable ()
virtual void decodeFixupPageTable ()
virtual void encodePageMap () override
virtual void encodeEntryTable ()
virtual void decodeEntryTable ()
virtual void preprocessFixups ()
virtual void encodeFixups ()
virtual void decodeFixups ()
virtual void encodeImage (Filter *ft)
virtual void decodeImage ()
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Member Functions inherited from LeFile
LeFile (InputFile *) noexcept
virtual ~LeFile () noexcept
virtual bool readFileHeader ()
virtual void writeFile (OutputFile *, bool)
virtual void readObjectTable ()
virtual void writeObjectTable ()
virtual void readFixupPageTable ()
virtual void writeFixupPageTable ()
virtual void readPageMap ()
virtual void writePageMap ()
virtual void encodePageMap ()
virtual void decodePageMap ()
virtual void readResidentNames ()
virtual void writeResidentNames ()
virtual void encodeResidentNames ()
virtual void decodeResidentNames ()
virtual void readNonResidentNames ()
virtual void writeNonResidentNames ()
virtual void encodeNonResidentNames ()
virtual void decodeNonResidentNames ()
virtual void readEntryTable ()
virtual void writeEntryTable ()
virtual void readFixups ()
virtual void writeFixups ()
virtual void readImage ()
virtual void writeImage ()
void countFixups (unsigned *) const
unsigned getImageSize () const
SPAN_0 (byte) iimage
SPAN_0 (byte) oimage
Static Protected Member Functions
static void virt2rela (const le_object_table_entry_t *, unsigned *objn, unsigned *addr)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes
MemBuffer iobject_desc
int big_relocs = 0
bool has_extra_code = false
unsigned neweip = 0
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Protected Attributes inherited from LeFile
InputFile * fif = nullptr
OutputFile * fof = nullptr
unsigned le_offset = 0
unsigned exe_offset = 0
le_header_t ih = {}
le_header_t oh = {}
le_object_table_entry_t * iobject_table = nullptr
le_object_table_entry_t * oobject_table = nullptr
unsigned * ifpage_table = nullptr
unsigned * ofpage_table = nullptr
le_pagemap_entry_t * ipm_entries = nullptr
le_pagemap_entry_t * opm_entries = nullptr
byte * ires_names = nullptr
byte * ores_names = nullptr
byte * ifixups = nullptr
byte * ofixups = nullptr
byte * inonres_names = nullptr
byte * ononres_names = nullptr
MemBuffer mb_iimage
MemBuffer mb_oimage
byte * ientries = nullptr
byte * oentries = nullptr
unsigned soobject_table = 0
unsigned sofpage_table = 0
unsigned sopm_entries = 0
unsigned sores_names = 0
unsigned sofixups = 0
unsigned sononres_names = 0
unsigned soimage = 0
unsigned soentries = 0
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from LeFile
enum { FIXUP_EXTRA = 3 }
Detailed Description
watcom/le
Definition at line 34 of file p_wcle.h.
Member Typedef Documentation
super
typedef Packer PackWcle::super private
Definition at line 35 of file p_wcle.h.
Constructor & Destructor Documentation
PackWcle()
PackWcle::PackWcle (InputFile * f) inline explicit
Definition at line 38 of file p_wcle.h.
: super(f), LeFile(f) { bele = &N_BELE_RTP::le_policy; }
References Packer::bele, and N_BELE_RTP::le_policy.
Member Function Documentation
buildLoader()
void PackWcle::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 84 of file p_wcle.cpp.
{
    // prepare loader
    initLoader(stub_i386_dos32_watcom_le, sizeof(stub_i386_dos32_watcom_le));
    addLoader("IDENTSTR,WCLEMAIN", ph.first_offset_found == 1 ? "WCLEMAIN02" : "",
              "WCLEMAIN03,UPX1HEAD,WCLECUTP");
    // fake alignment for the start of the decompressor
    linker->defineSymbol("WCLECUTP", 0x1000);
    addLoader(getDecompressorSections(), "WCLEMAI2");
    if (ft->id) {
        assert(ft->calls > 0);
        addLoader(ft->addvalue ? "WCCTTPOS" : "WCCTTNUL");
        addFilter32(ft->id);
    }
#if 1
    // FIXME: if (has_relocation)
    { addLoader("WCRELOC1,RELOC320", big_relocs ? "REL32BIG" : "", "RELOC32J"); }
#endif
    addLoader(has_extra_code ? "WCRELSEL" : "", "WCLEMAI4");
}
References Packer::addFilter32(), Packer::addLoader(), Filter::addvalue, big_relocs, Filter::calls, PackHeader::first_offset_found, Packer::getDecompressorSections(), has_extra_code, Filter::id, Packer::initLoader(), PackerBase::ph, and stub_i386_dos32_watcom_le.
canPack()
tribool PackWcle::canPack () override virtual
Implements PackerBase.
Definition at line 115 of file p_wcle.cpp.
{
    if (!LeFile::readFileHeader())
        return false;
    return true;
}
References LeFile::readFileHeader().
canUnpack()
tribool PackWcle::canUnpack () override virtual
Implements PackerBase.
Definition at line 734 of file p_wcle.cpp.
{
    if (!LeFile::readFileHeader())
        return false;
    fi->seek(exe_offset + ih.data_pages_offset, SEEK_SET);
    // FIXME: 1024 could be too large for some files
    // int len = 1024;
    int len = UPX_MIN(getImageSize(), 256u);
    if (len == 0)
        return false;
    return readPackHeader(len) ? 1 : -1;
}
References LeFile::le_header_t::data_pages_offset, LeFile::exe_offset, PackerBase::fi, LeFile::getImageSize(), LeFile::ih, LeFile::readFileHeader(), Packer::readPackHeader(), InputFile::seek(), SEEK_SET, and UPX_MIN.
decodeEntryTable()
void PackWcle::decodeEntryTable () protected virtual
Definition at line 701 of file p_wcle.cpp.
{
    unsigned count, object, n, r;
    SPAN_S_VAR(byte, p, ientries, soentries);
    n = 0;
    while (*p) {
        count = *p;
        n += count;
        if (p[1] == 0) // unused bundle
            p += 2;
        else if (p[1] == 3) // 32-bit offset bundle
        {
            object = get_le16(p + 2);
            if (object != 1)
                throwCantUnpack("corrupted entry found");
            object = soobject_table;
            r = get_le32(p + 5);
            virt2rela(oobject_table, &object, &r);
            set_le16(p + 2, object--);
            p += 4;
            for (; count; count--, p += 5)
                set_le32(p + 1, get_le32(p + 1) - OOT(object, my_base_address));
        } else
            throwCantUnpack("unsupported bundle type in entry table");
    }
    // if (Opt_debug) printf("\n%d entries decoded.\n",n);
    UNUSED(n);
    soentries = ptr_udiff_bytes(p, ientries) + 1;
    oentries = ientries;
    ientries = nullptr;
}
References get_le16(), get_le32(), LeFile::ientries, my_base_address, n, LeFile::oentries, LeFile::oobject_table, OOT, ptr_udiff_bytes(), set_le16(), set_le32(), LeFile::soentries, LeFile::soobject_table, SPAN_S_VAR, throwCantUnpack(), UNUSED, and virt2rela().
Referenced by unpack().
decodeFixupPageTable()
void PackWcle::decodeFixupPageTable () protected virtual
Definition at line 653 of file p_wcle.cpp.
{
    ofpage_table = New(unsigned, sofpage_table = 1 + opages);
    set_le32(ofpage_table, 0);
    // the rest of ofpage_table is filled by decodeFixups()
}
References New, LeFile::ofpage_table, opages, set_le32(), and LeFile::sofpage_table.
Referenced by unpack().
decodeFixups()
void PackWcle::decodeFixups () protected virtual
Definition at line 527 of file p_wcle.cpp.
{
    mb_iimage.dealloc();
    iimage = nullptr;
    SPAN_S_VAR(const byte, p, oimage + soimage);
    MemBuffer mb_relocs;
    const unsigned fixupn = unoptimizeReloc(p, mb_relocs, oimage, soimage, 32, true);
    MemBuffer wrkmem(8 * fixupn + 8);
    unsigned ic, jc, o, r;
    for (ic = 0; ic < fixupn; ic++) {
        jc = get_le32(mb_relocs + 4 * ic);
        set_le32(wrkmem + ic * 8, jc);
        o = soobject_table;
        r = get_le32(oimage + jc);
        virt2rela(oobject_table, &o, &r);
        set_le32(wrkmem + ic * 8 + 4, OOT(o - 1, my_base_address));
        set_le32(oimage + jc, r);
    }
    set_le32(wrkmem + ic * 8, 0xFFFFFFFF); // end of 32-bit offset fixups
    mb_relocs.dealloc();                   // done
    // selector fixups then self-relative fixups
    SPAN_S_VAR(const byte, selector_fixups, p);
    // Find selfrel_fixups by skipping over selector_fixups.
    SPAN_S_VAR(const byte, q, selector_fixups);
    // The code is a subroutine that ends in RET (0xC3).
    while (*q != 0xC3) {
        // Defend against tampered selector_fixups; see PackWcle::preprocessFixups().
        // selector_fixups[] is x386 code with 9-byte blocks of 2 instructions each:
        // "\x8C\xCB\x66\x89\x9D"  // mov bx, cs ; mov [xxx+ebp], bx
        // "\x8C\xCA\x66\x89\x95"
        // and where byte [+1] also can be '\xDA' or '\xDB'.
        if (0x8C != q[0] || 0x66 != q[2] || 0x89 != q[3]) { // Unexpected; tampering?
            // Try to recover by looking for the RET.
            const byte *q2 = (const byte *) memchr(q, 0xC3, 9);
            if (q2) { // Assume recovery
                q = q2;
                break;
            }
        }
        // Guard against run-away.
        static byte const blank[9] = {0};
        // catastrophic worst case or no-good early warning
        if (ptr_diff_bytes(oimage + ph.u_len - sizeof(blank), raw_bytes(q, 0)) < 0 ||
            !memcmp(blank, q, sizeof(blank))) {
            char msg[50];
            snprintf(msg, sizeof(msg), "bad selector_fixups %d",
                     ptr_diff_bytes(q, selector_fixups));
            throwCantPack(msg);
        }
        q += 9;
    }
    unsigned selectlen = ptr_udiff_bytes(q, selector_fixups) / 9;
    SPAN_S_VAR(const byte, selfrel_fixups, q + 1); // Skip the 0xC3
    const unsigned fbytes = fixupn * 9 + 1000 + selectlen * 5;
    ofixups = New(byte, fbytes);
    SPAN_S_VAR(byte, fp, ofixups, fbytes, ofixups);
    for (ic = 1, jc = 0; ic <= opages; ic++) {
        // self relative fixups
        while ((r = get_le32(selfrel_fixups)) / mps == ic - 1) {
            fp[0] = 8;
            set_le16(fp + 2, r & (mps - 1));
            o = 4 + get_le32(oimage + r);
            set_le32(oimage + r, 0);
            r += o;
            o = soobject_table;
            virt2rela(oobject_table, &o, &r);
            fp[4] = (byte) o;
            set_le32(fp + 5, r);
            fp[1] = (byte) (r > 0xFFFF ? 0x10 : 0);
            fp += fp[1] ? 9 : 7;
            selfrel_fixups += 4;
            dputc('r', stdout);
        }
        // selector fixups
        while (selectlen && (r = get_le32(selector_fixups + 5)) / mps == ic - 1) {
            fp[0] = 2;
            fp[1] = 0;
            set_le16(fp + 2, r & (mps - 1));
            unsigned x = selector_fixups[1] > 0xD0 ? oh.init_ss_object : oh.init_cs_object;
            fp[4] = (byte) x;
            fp += 5;
            selector_fixups += 9;
            selectlen--;
            dputc('s', stdout);
        }
        // 32 bit offset fixups
        while (get_le32(wrkmem + 4 * jc) < mem_size(mps, ic)) {
            if (jc > 1 &&
                ((get_le32(wrkmem + 4 * (jc - 2)) + 3) & (mps - 1)) < 3) // cross page fixup?
            {
                r = get_le32(oimage + get_le32(wrkmem + 4 * (jc - 2)));
                fp[0] = 7;
                fp[1] = (byte) (r > 0xFFFF ? 0x10 : 0);
                set_le16(fp + 2, get_le32(wrkmem + 4 * (jc - 2)) | ~3);
                set_le32(fp + 5, r);
                o = soobject_table;
                r = get_le32(wrkmem + 4 * (jc - 1));
                virt2rela(oobject_table, &o, &r);
                fp[4] = (byte) o;
                fp += fp[1] ? 9 : 7;
                dputc('0', stdout);
            }
            o = soobject_table;
            r = get_le32(wrkmem + 4 * (jc + 1));
            virt2rela(oobject_table, &o, &r);
            r = get_le32(oimage + get_le32(wrkmem + 4 * jc));
            fp[0] = 7;
            fp[1] = (byte) (r > 0xFFFF ? 0x10 : 0);
            set_le16(fp + 2, get_le32(wrkmem + 4 * jc) & (mps - 1));
            fp[4] = (byte) o;
            set_le32(fp + 5, r);
            fp += fp[1] ? 9 : 7;
            jc += 2;
        }
        set_le32(ofpage_table + ic, ptr_udiff_bytes(fp, ofixups));
    }
    for (ic = 0; ic < FIXUP_EXTRA; ic++)
        *fp++ = 0;
    sofixups = ptr_udiff_bytes(fp, ofixups);
}
References MemBuffer::dealloc(), dputc, LeFile::FIXUP_EXTRA, get_le32(), LeFile::le_header_t::init_cs_object, LeFile::le_header_t::init_ss_object, LeFile::mb_iimage, mem_size(), memchr(), memcmp(), mps, my_base_address, New, LeFile::ofixups, LeFile::ofpage_table, LeFile::oh, LeFile::oobject_table, OOT, opages, PackerBase::ph, ptr_diff_bytes(), ptr_udiff_bytes(), raw_bytes(), set_le16(), set_le32(), snprintf, LeFile::sofixups, LeFile::soimage, LeFile::soobject_table, SPAN_S_VAR, throwCantPack(), PackHeader::u_len, Packer::unoptimizeReloc(), and virt2rela().
Referenced by unpack().
decodeImage()
void PackWcle::decodeImage () protected virtual
Definition at line 691 of file p_wcle.cpp.
{
    mb_oimage.allocForDecompression(ph.u_len);
    oimage = mb_oimage; // => now a SPAN_S
    decompress(iimage + ph.buf_offset + ph.getPackHeaderSize(), oimage);
    soimage = get_le32(oimage + ph.u_len - 5);
    opages = soimage / mps;
    oh.memory_page_size = mps;
}
References MemBuffer::allocForDecompression(), PackHeader::buf_offset, Packer::decompress(), get_le32(), PackHeader::getPackHeaderSize(), LeFile::mb_oimage, LeFile::le_header_t::memory_page_size, mps, LeFile::oh, opages, PackerBase::ph, LeFile::soimage, and PackHeader::u_len.
Referenced by unpack().
decodeObjectTable()
void PackWcle::decodeObjectTable () protected virtual
Definition at line 659 of file p_wcle.cpp.
{
    soobject_table = oimage[ph.u_len - 1];
    oobject_table = New(le_object_table_entry_t, soobject_table);
    unsigned jc, ic = soobject_table * sizeof(*oobject_table);
    const unsigned extradata = ph.version == 10 ? 17 : 13;
    memcpy(oobject_table, oimage + ph.u_len - extradata - ic, ic);
    if (ph.version >= 12)
        oh.automatic_data_object = oimage[ph.u_len - ic - 14];
    for (ic = jc = 0; ic < soobject_table; ic++) {
        OOT(ic, my_base_address) = jc;
        jc += (OOT(ic, virtual_size) + mps - 1) & ~(mps - 1);
    }
    // restore original cs:eip & ss:esp
    ic = soobject_table;
    jc = get_le32(oimage + ph.u_len - (ph.version < 11 ? 13 : 9));
    virt2rela(oobject_table, &ic, &jc);
    oh.init_cs_object = ic;
    oh.init_eip_offset = jc;
    ic = soobject_table;
    if (ph.version < 10)
        jc = ih.init_esp_offset;
    else
        jc = get_le32(oimage + ph.u_len - (ph.version == 10 ? 17 : 13));
    virt2rela(oobject_table, &ic, &jc);
    oh.init_ss_object = ic;
    oh.init_esp_offset = jc;
}
References LeFile::le_header_t::automatic_data_object, get_le32(), LeFile::ih, LeFile::le_header_t::init_cs_object, LeFile::le_header_t::init_eip_offset, LeFile::le_header_t::init_esp_offset, LeFile::le_header_t::init_ss_object, memcpy(), mps, my_base_address, New, LeFile::oh, LeFile::oobject_table, OOT, PackerBase::ph, LeFile::soobject_table, PackHeader::u_len, PackHeader::version, and virt2rela().
Referenced by unpack().
encodeEntryTable()
void PackWcle::encodeEntryTable () protected virtual
Definition at line 128 of file p_wcle.cpp.
{
    unsigned count, object, n;
    byte *p = ientries;
    n = 0;
    while (*p) {
        count = *p;
        n += count;
        if (p[1] == 0) // unused bundle
            p += 2;
        else if (p[1] == 3) // 32-bit bundle
        {
            object = get_le16(p + 2) - 1;
            set_le16(p + 2, 1);
            p += 4;
            for (; count; count--, p += 5)
                set_le32(p + 1, IOT(object, my_base_address) + get_le32(p + 1));
        } else
            throwCantPack("unsupported bundle type in entry table");
    }
    // if (Opt_debug) printf("%d entries encoded.\n",n);
    UNUSED(n);
    soentries = ptr_udiff_bytes(p, ientries) + 1;
    oentries = ientries;
    ientries = nullptr;
}
References get_le16(), get_le32(), LeFile::ientries, IOT, my_base_address, n, LeFile::oentries, ptr_udiff_bytes(), set_le16(), set_le32(), LeFile::soentries, throwCantPack(), and UNUSED.
Referenced by pack().
encodeFixupPageTable()
void PackWcle::encodeFixupPageTable () protected virtual
Definition at line 221 of file p_wcle.cpp.
{
    unsigned ic;
    ofpage_table = New(unsigned, sofpage_table = 1 + opages);
    for (ofpage_table[0] = ic = 0; ic < opages; ic++)
        set_le32(ofpage_table + ic + 1, sofixups - FIXUP_EXTRA);
}
References LeFile::FIXUP_EXTRA, New, LeFile::ofpage_table, opages, set_le32(), LeFile::sofixups, and LeFile::sofpage_table.
Referenced by pack().
encodeFixups()
void PackWcle::encodeFixups () protected virtual
Definition at line 228 of file p_wcle.cpp.
{
    sofixups = 1 * 7 + FIXUP_EXTRA;
    ofixups = New(byte, sofixups);
    memset(ofixups, 0, sofixups);
    ofixups[0] = 7;
    set_le16(ofixups + 2, (LE_STUB_EDI + neweip) & (mps - 1));
    ofixups[4] = 1;
}
References LeFile::FIXUP_EXTRA, LE_STUB_EDI, memset(), mps, New, neweip, LeFile::ofixups, set_le16(), and LeFile::sofixups.
Referenced by pack().
encodeImage()
void PackWcle::encodeImage (Filter * ft) protected virtual
Definition at line 378 of file p_wcle.cpp.
{
    // concatenate image & preprocessed fixups
    unsigned isize = soimage + sofixups;
    ibuf.alloc(isize);
    memcpy(ibuf, iimage, soimage);
    memcpy(ibuf + soimage, ifixups, sofixups);
    delete[] ifixups;
    ifixups = nullptr;
    mb_oimage.allocForCompression(isize, RESERVED + 512);
    oimage = mb_oimage; // => now a SPAN_S
    // prepare packheader
    ph.u_len = isize;
    // prepare filter [already done]
    // compress
    upx_compress_config_t cconf;
    cconf.reset();
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    compressWithFilters(ibuf, isize, raw_bytes(oimage + RESERVED, mb_oimage.getSize() - RESERVED),
                        ibuf + ft->addvalue, ft->buf_len, nullptr, 0, ft, 512, &cconf, 0);
    ibuf.dealloc();
    soimage = ph.c_len;
    while (soimage & 3)
        oimage[RESERVED + soimage++] = 0;
}
References Filter::addvalue, MemBuffer::alloc(), MemBuffer::allocForCompression(), Filter::buf_len, PackHeader::c_len, Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, MemBuffer::dealloc(), MemBuffer::getSize(), Packer::ibuf, LeFile::ifixups, lzma_compress_config_t::max_num_probs, LeFile::mb_oimage, memcpy(), PackerBase::ph, raw_bytes(), RESERVED, upx_compress_config_t::reset(), LeFile::sofixups, LeFile::soimage, and PackHeader::u_len.
Referenced by pack().
encodeObjectTable()
void PackWcle::encodeObjectTable () protected virtual
Definition at line 176 of file p_wcle.cpp.
{
    unsigned ic, jc;
    soobject_table = 2;
    oobject_table = New(le_object_table_entry_t, soobject_table);
    memset(oobject_table, 0, mem_size(sizeof(*oobject_table), soobject_table));
    // object #1:
    OOT(0, base_address) = IOT(0, base_address);
    ic = IOT(objects - 1, my_base_address) + IOT(objects - 1, virtual_size);
    jc = mem_size(mps, pages, sofixups, 1024);
    if (ic < jc)
        ic = jc;
    unsigned csection = (ic + ph.overlap_overhead + mps - 1) & ~(mps - 1);
    OOT(0, virtual_size) = csection + mps;
    OOT(0, flags) = LEOF_READ | LEOF_EXEC | LEOF_HUGE32 | LEOF_PRELOAD;
    OOT(0, pagemap_index) = 1;
    OOT(0, npages) = opages;
    // object #2: stack
    OOT(1, base_address) = (OOT(0, base_address) + OOT(0, virtual_size) + mps - 1) & ~(mps - 1);
    OOT(1, virtual_size) = mps + getDecompressorWrkmemSize();
    OOT(1, flags) = LEOF_READ | LEOF_HUGE32 | LEOF_WRITE;
    OOT(1, pagemap_index) = 1;
    oh.init_cs_object = 1;
    oh.init_eip_offset = neweip;
    oh.init_ss_object = 2;
    oh.init_esp_offset = OOT(1, virtual_size);
    oh.automatic_data_object = 2;
}
References LeFile::le_header_t::automatic_data_object, Packer::getDecompressorWrkmemSize(), LeFile::le_header_t::init_cs_object, LeFile::le_header_t::init_eip_offset, LeFile::le_header_t::init_esp_offset, LeFile::le_header_t::init_ss_object, IOT, LEOF_EXEC, LEOF_HUGE32, LEOF_PRELOAD, LEOF_READ, LEOF_WRITE, mem_size(), memset(), mps, my_base_address, New, neweip, objects, LeFile::oh, LeFile::oobject_table, OOT, opages, PackHeader::overlap_overhead, pages, PackerBase::ph, LeFile::sofixups, and LeFile::soobject_table.
Referenced by pack().
encodePageMap()
void PackWcle::encodePageMap () override protected virtual
Reimplemented from LeFile.
Definition at line 211 of file p_wcle.cpp.
{
    opm_entries = New(le_pagemap_entry_t, sopm_entries = opages);
    for (unsigned ic = 0; ic < sopm_entries; ic++) {
        opm_entries[ic].l = (byte) (ic + 1);
        opm_entries[ic].m = (byte) ((ic + 1) >> 8);
        opm_entries[ic].h = 0;
        opm_entries[ic].type = 0;
    }
}
References LeFile::le_pagemap_entry_t::h, LeFile::le_pagemap_entry_t::l, LeFile::le_pagemap_entry_t::m, New, opages, LeFile::opm_entries, LeFile::sopm_entries, and LeFile::le_pagemap_entry_t::type.
Referenced by pack().
getCompressionMethods()
const int * PackWcle::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 72 of file p_wcle.cpp.
{
    return Packer::getDefaultCompressionMethods_le32(method, level);
}
References Packer::getDefaultCompressionMethods_le32().
getFilters()
const int * PackWcle::getFilters () const override virtual
Implements PackerBase.
Definition at line 76 of file p_wcle.cpp.
{
    static const int filters[] = {0x26, 0x24,           0x49, 0x46, 0x16, 0x13,  0x14,
                                  0x11, FT_ULTRA_BRUTE, 0x25, 0x15, 0x12, FT_END};
    return filters;
}
References FT_END, and FT_ULTRA_BRUTE.
getFormat()
virtual int PackWcle::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 40 of file p_wcle.h.
{ return UPX_F_WATCOM_LE; }
References UPX_F_WATCOM_LE.
getFullName()
virtual const char * PackWcle::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 42 of file p_wcle.h.
{
        return "i386-dos32.watcom.le";
    }
getName()
virtual const char * PackWcle::getName () const inline override virtual
Implements PackerBase.
Definition at line 41 of file p_wcle.h.
{ return "watcom/le"; }
getVersion()
virtual int PackWcle::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 39 of file p_wcle.h.
{ return 13; }
handleStub()
void PackWcle::handleStub (OutputFile * fo) protected virtual
util
Definition at line 110 of file p_wcle.cpp.
{
    if (fo && !opt->watcom_le.le)
        Packer::handleStub(fi, fo, le_offset);
}
References PackerBase::fi, Packer::handleStub(), LeFile::le_offset, and opt.
Referenced by pack(), and unpack().
newLinker()
Linker * PackWcle::newLinker () const override protected virtual
Implements Packer.
Definition at line 82 of file p_wcle.cpp.
{ return new ElfLinkerX86; }
pack()
void PackWcle::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 406 of file p_wcle.cpp.
{
    handleStub(fo);
    if (ih.byte_order || ih.word_order || ih.exe_format_level || ih.cpu_type < 2 ||
        ih.cpu_type > 5 || ih.target_os != 1 || ih.module_type != 0x200 ||
        ih.object_iterate_data_map_offset || ih.resource_entries || ih.module_directives_entries ||
        ih.imported_modules_count || ih.object_table_entries > 255)
        throwCantPack("watcom/le: unexpected value in header");
    readObjectTable();
    readPageMap();
    readResidentNames();
    readEntryTable();
    readFixupPageTable();
    readFixups();
    readImage();
    readNonResidentNames();
    //    if (find_le32(iimage,20,get_le32("UPX ")) >= 0)
    if (find_le32(raw_bytes(iimage, soimage), UPX_MIN(soimage, 256u), UPX_MAGIC_LE32) >= 0)
        throwAlreadyPacked();
    if (ih.init_ss_object != objects)
        throwCantPack("the stack is not in the last object");
    preprocessFixups();
    const unsigned text_size = mem_size(mps, IOT(ih.init_cs_object - 1, npages));
    const unsigned text_vaddr = IOT(ih.init_cs_object - 1, my_base_address);
    // attach some useful data at the end of preprocessed fixups
    ifixups[sofixups++] = (byte) (ih.automatic_data_object & 0xff);
    unsigned ic = objects * sizeof(*iobject_table);
    memcpy(ifixups + sofixups, iobject_desc, ic);
    iobject_desc.dealloc();
    sofixups += ic;
    set_le32(ifixups + sofixups,
             ih.init_esp_offset + IOT(ih.init_ss_object - 1, my_base_address)); // old stack pointer
    set_le32(ifixups + sofixups + 4, ih.init_eip_offset + text_vaddr);          // real entry point
    set_le32(ifixups + sofixups + 8,
             mem_size(mps, pages)); // virtual address of unpacked relocations
    ifixups[sofixups + 12] = (byte) (unsigned) objects;
    sofixups += 13;
    // prepare filter
    Filter ft(ph.level);
    ft.buf_len = text_size;
    ft.addvalue = text_vaddr;
    // compress
    encodeImage(&ft);
    const unsigned lsize = getLoaderSize();
    neweip = getLoaderSection("WCLEMAIN");
    int e_len = getLoaderSectionStart("WCLECUTP");
    const unsigned d_len = lsize - e_len;
    assert(e_len > 0 && e_len < RESERVED);
    memmove(oimage + e_len, oimage + RESERVED, soimage);
    soimage += lsize;
    opages = (soimage + mps - 1) / mps;
    oh.bytes_on_last_page = soimage % mps;
    encodeObjectTable();
    encodeFixups();
    encodeFixupPageTable();
    encodePageMap();
    encodeEntryTable();
    encodeResidentNames();
    encodeNonResidentNames();
    // patch loader
    ic = (OOT(0, virtual_size) - d_len) & ~15;
    assert(ic > ((ph.u_len + ph.overlap_overhead + 31) & ~15));
    linker->defineSymbol("WCLECUTP", ic);
    linker->defineSymbol("original_entry", ih.init_eip_offset + text_vaddr);
    linker->defineSymbol("original_stack",
                         ih.init_esp_offset + IOT(ih.init_ss_object - 1, my_base_address));
    linker->defineSymbol("start_of_relocs", mem_size(mps, pages));
    defineDecompressorSymbols();
    defineFilterSymbols(&ft);
    linker->defineSymbol("filter_buffer_start", text_vaddr);
    unsigned jpos = (((ph.c_len + 3) & ~3) + d_len + 3) / 4;
    linker->defineSymbol("words_to_copy", jpos);
    linker->defineSymbol("copy_dest", ((ic + d_len + 3) & ~3) - 4);
    linker->defineSymbol("copy_source", e_len + jpos * 4 - 4);
    relocateLoader();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, lsize);
    memcpy(oimage, loader, e_len);
    memcpy(oimage + soimage - d_len, loader + e_len, d_len);
    writeFile(fo, opt->watcom_le.le);
    // verify
    verifyOverlappingDecompression(mb_oimage + e_len, mb_oimage.getSize() - e_len);
    // copy the overlay
    const unsigned overlaystart = ih.data_pages_offset + exe_offset + getImageSize();
    const unsigned overlay = file_size - overlaystart - ih.non_resident_name_table_length;
    checkOverlay(overlay);
    copyOverlay(fo, overlay, mb_oimage);
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References Filter::addvalue, LeFile::le_header_t::automatic_data_object, Filter::buf_len, LeFile::le_header_t::byte_order, LeFile::le_header_t::bytes_on_last_page, PackHeader::c_len, Packer::checkFinalCompressionRatio(), Packer::checkOverlay(), Packer::copyOverlay(), LeFile::le_header_t::cpu_type, LeFile::le_header_t::data_pages_offset, MemBuffer::dealloc(), Packer::defineDecompressorSymbols(), Packer::defineFilterSymbols(), encodeEntryTable(), encodeFixupPageTable(), encodeFixups(), encodeImage(), LeFile::encodeNonResidentNames(), encodeObjectTable(), encodePageMap(), LeFile::encodeResidentNames(), LeFile::le_header_t::exe_format_level, LeFile::exe_offset, PackerBase::file_size, find_le32(), LeFile::getImageSize(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), MemBuffer::getSize(), handleStub(), LeFile::ifixups, LeFile::ih, LeFile::le_header_t::imported_modules_count, LeFile::le_header_t::init_cs_object, LeFile::le_header_t::init_eip_offset, LeFile::le_header_t::init_esp_offset, LeFile::le_header_t::init_ss_object, iobject_desc, IOT, PackHeader::level, LeFile::mb_oimage, mem_size(), memcpy(), memmove(), LeFile::le_header_t::module_directives_entries, LeFile::le_header_t::module_type, mps, my_base_address, neweip, LeFile::le_header_t::non_resident_name_table_length, LeFile::le_header_t::object_iterate_data_map_offset, LeFile::le_header_t::object_table_entries, objects, LeFile::oh, OOT, opages, opt, PackHeader::overlap_overhead, pages, Packer::patchPackHeader(), PackerBase::ph, preprocessFixups(), raw_bytes(), LeFile::readEntryTable(), LeFile::readFixupPageTable(), LeFile::readFixups(), LeFile::readImage(), LeFile::readNonResidentNames(), readObjectTable(), LeFile::readPageMap(), LeFile::readResidentNames(), Packer::relocateLoader(), RESERVED, LeFile::le_header_t::resource_entries, set_le32(), LeFile::sofixups, LeFile::soimage, LeFile::le_header_t::target_os, throwAlreadyPacked(), throwCantPack(), throwNotCompressible(), PackHeader::u_len, UPX_MAGIC_LE32, UPX_MIN, Packer::verifyOverlappingDecompression(), LeFile::le_header_t::word_order, and LeFile::writeFile().
preprocessFixups()
void PackWcle::preprocessFixups () protected virtual
Definition at line 237 of file p_wcle.cpp.
{
    big_relocs = 0;
    unsigned ic, jc;
    Array(unsigned, counts, objects + 2);
    countFixups(counts);
    for (ic = jc = 0; ic < objects; ic++)
        jc += counts[ic];
    if (jc == 0) {
        // FIXME: implement this
        throwCantPack("files without relocations are not supported");
    }
    MemBuffer mb_relocs(jc);
    ByteArray(srf, counts[objects + 0] + 1);
    ByteArray(slf, counts[objects + 1] + 1);
    SPAN_S_VAR(byte, relocs, mb_relocs);
    SPAN_S_VAR(byte, selector_fixups, srf_membuf);
    SPAN_S_VAR(byte, selfrel_fixups, slf_membuf);
    unsigned relocnum = 0;
    byte *fix = ifixups;
    for (ic = jc = 0; ic < pages; ic++) {
        while (ptr_udiff_bytes(fix, ifixups) < get_le32(ifpage_table + (ic + 1))) {
            const int fixp2 = get_le16_signed(fix + 2);
            unsigned value;
            switch (*fix) {
            case 2: // selector fixup
                if (fixp2 < 0) {
                    // cross page selector fixup
                    dputc('S', stdout);
                    fix += 5;
                    break;
                }
                dputc('s', stdout);
                memcpy(selector_fixups, "\x8C\xCB\x66\x89\x9D",
                       5); // mov bx, cs ; mov [xxx+ebp], bx
                if (IOT(fix[4] - 1, flags) & LEOF_WRITE)
                    selector_fixups[1] = 0xDB; // ds
                set_le32(selector_fixups + 5, jc + fixp2);
                selector_fixups += 9;
                fix += 5;
                break;
            case 5: // 16-bit offset
                if ((unsigned) fixp2 < 4096 && IOT(fix[4] - 1, my_base_address) == jc)
                    dputc('6', stdout);
                else
                    throwCantPack("unsupported 16-bit offset relocation");
                fix += (fix[1] & 0x10) ? 9 : 7;
                break;
            case 6: // 16:32 pointer
                if (fixp2 < 0) {
                    // cross page pointer fixup
                    dputc('P', stdout);
                    fix += (fix[1] & 0x10) ? 9 : 7;
                    break;
                }
                dputc('p', stdout);
                memcpy(iimage + jc + fixp2, fix + 5, (fix[1] & 0x10) ? 4 : 2);
                set_le32(relocs + 4 * relocnum++, jc + fixp2);
                set_le32(iimage + jc + fixp2,
                         get_le32(iimage + jc + fixp2) + IOT(fix[4] - 1, my_base_address));
                memcpy(selector_fixups, "\x8C\xCA\x66\x89\x95", 5);
                if (IOT(fix[4] - 1, flags) & LEOF_WRITE)
                    selector_fixups[1] = 0xDA; // ds
                set_le32(selector_fixups + 5, jc + fixp2 + 4);
                selector_fixups += 9;
                fix += (fix[1] & 0x10) ? 9 : 7;
                break;
            case 7: // 32-bit offset
                if (fixp2 < 0) {
                    fix += (fix[1] & 0x10) ? 9 : 7;
                    break;
                }
                // if (memcmp(iimage+jc+fixp2,fix+5,(fix[1] & 0x10) ? 4 : 2))
                //    throwCantPack("illegal fixup offset");
                // work around a pmwunlite bug: remove duplicated fixups
                // FIXME: fix the other cases too
                if (relocnum == 0 || get_le32(relocs + 4 * relocnum - 4) != jc + fixp2) {
                    set_le32(relocs + 4 * relocnum++, jc + fixp2);
                    set_le32(iimage + jc + fixp2,
                             get_le32(iimage + jc + fixp2) + IOT(fix[4] - 1, my_base_address));
                }
                fix += (fix[1] & 0x10) ? 9 : 7;
                break;
            case 8: // 32-bit self relative fixup
                if (fixp2 < 0) {
                    // cross page self relative fixup
                    dputc('R', stdout);
                    fix += (fix[1] & 0x10) ? 9 : 7;
                    break;
                }
                value = get_le32(fix + 5);
                if (fix[1] == 0)
                    value &= 0xffff;
                set_le32(iimage + jc + fixp2,
                         (value + IOT(fix[4] - 1, my_base_address)) - jc - fixp2 - 4);
                set_le32(selfrel_fixups, jc + fixp2);
                selfrel_fixups += 4;
                dputc('r', stdout);
                fix += (fix[1] & 0x10) ? 9 : 7;
                break;
            default:
                throwCantPack("unsupported fixup record");
            }
        }
        jc += mps;
    }
    // resize ifixups if it's too small
    if (sofixups < 4 * relocnum + 8192) {
        delete[] ifixups;
        sofixups = 4 * relocnum + 8192;
        ifixups = New(byte, sofixups);
    }
    SPAN_S_VAR(byte, orelocs, ifixups, sofixups);
    fix =
        ifixups + optimizeReloc(relocnum, relocs, orelocs, iimage, soimage, 32, true, &big_relocs);
    has_extra_code = ptr_udiff_bytes(selector_fixups, srf) != 0;
    // FIXME: this could be removed if has_extra_code = false
    // but then we'll need a flag
    *selector_fixups++ = 0xC3;                               // ret
    memcpy(fix, srf, ptr_udiff_bytes(selector_fixups, srf)); // copy selector fixup code
    fix += ptr_udiff_bytes(selector_fixups, srf);
    memcpy(fix, slf, ptr_udiff_bytes(selfrel_fixups, slf)); // copy self-relative fixup positions
    fix += ptr_udiff_bytes(selfrel_fixups, slf);
    set_le32(fix, 0xFFFFFFFFUL);
    fix += 4;
    sofixups = ptr_udiff_bytes(fix, ifixups);
}
References Array, big_relocs, ByteArray, LeFile::countFixups(), dputc, get_le16_signed(), get_le32(), has_extra_code, LeFile::ifixups, LeFile::ifpage_table, IOT, LEOF_WRITE, memcpy(), mps, my_base_address, New, objects, Packer::optimizeReloc(), pages, ptr_udiff_bytes(), set_le32(), LeFile::sofixups, LeFile::soimage, SPAN_S_VAR, and throwCantPack().
Referenced by pack().
readObjectTable()
void PackWcle::readObjectTable () override protected virtual
Reimplemented from LeFile.
Definition at line 156 of file p_wcle.cpp.
{
    LeFile::readObjectTable();
    // temporary copy of the object descriptors
    if (!objects) // late detection, but protect against .alloc(0)
        throwCantPack("no objects");
    iobject_desc.alloc(objects * sizeof(*iobject_table));
    memcpy(iobject_desc, iobject_table, objects * sizeof(*iobject_table));
    unsigned ic, jc, virtual_size;
    for (ic = jc = virtual_size = 0; ic < objects; ic++) {
        jc += IOT(ic, npages);
        IOT(ic, my_base_address) = virtual_size;
        virtual_size += (IOT(ic, virtual_size) + mps - 1) & ~(mps - 1);
    }
    if (pages != jc)
        throwCantPack("bad page number");
}
References MemBuffer::alloc(), iobject_desc, LeFile::iobject_table, IOT, memcpy(), mps, my_base_address, objects, pages, LeFile::readObjectTable(), and throwCantPack().
Referenced by pack(), and unpack().
unpack()
void PackWcle::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 760 of file p_wcle.cpp.
{
    handleStub(fo);
    readObjectTable();
    iobject_desc.dealloc();
    readPageMap();
    readResidentNames();
    readEntryTable();
    readFixupPageTable();
    readFixups();
    readImage();
    readNonResidentNames();
    decodeImage();
    decodeObjectTable();
    // unfilter
    if (ph.filter) {
        const unsigned text_size = mem_size(mps, OOT(oh.init_cs_object - 1, npages));
        const unsigned text_vaddr = OOT(oh.init_cs_object - 1, my_base_address);
        Filter ft(ph.level);
        ft.init(ph.filter, text_vaddr);
        ft.cto = (byte) ph.filter_cto;
        if (ph.version < 11)
            ft.cto = (byte) (get_le32(oimage + ph.u_len - 9) >> 24);
        ft.unfilter(oimage + text_vaddr, text_size);
    }
    decodeFixupPageTable();
    decodeFixups();
    decodeEntryTable();
    decodePageMap();
    decodeResidentNames();
    decodeNonResidentNames();
    for (unsigned ic = 0; ic < soobject_table; ic++)
        OOT(ic, my_base_address) = 0;
    while (oimage[soimage - 1] == 0)
        soimage--;
    oh.bytes_on_last_page = soimage % mps;
    // write decompressed file
    if (fo)
        writeFile(fo, opt->watcom_le.le);
    // copy the overlay
    const unsigned overlaystart = ih.data_pages_offset + exe_offset + getImageSize();
    const unsigned overlay = file_size - overlaystart - ih.non_resident_name_table_length;
    checkOverlay(overlay);
    copyOverlay(fo, overlay, mb_oimage);
}
References LeFile::le_header_t::bytes_on_last_page, Packer::checkOverlay(), Packer::copyOverlay(), Filter::cto, LeFile::le_header_t::data_pages_offset, MemBuffer::dealloc(), decodeEntryTable(), decodeFixupPageTable(), decodeFixups(), decodeImage(), LeFile::decodeNonResidentNames(), decodeObjectTable(), LeFile::decodePageMap(), LeFile::decodeResidentNames(), LeFile::exe_offset, PackerBase::file_size, PackHeader::filter, PackHeader::filter_cto, get_le32(), LeFile::getImageSize(), handleStub(), LeFile::ih, Filter::init(), LeFile::le_header_t::init_cs_object, iobject_desc, PackHeader::level, LeFile::mb_oimage, mem_size(), mps, my_base_address, LeFile::le_header_t::non_resident_name_table_length, LeFile::oh, OOT, opt, PackerBase::ph, LeFile::readEntryTable(), LeFile::readFixupPageTable(), LeFile::readFixups(), LeFile::readImage(), LeFile::readNonResidentNames(), readObjectTable(), LeFile::readPageMap(), LeFile::readResidentNames(), LeFile::soimage, LeFile::soobject_table, PackHeader::u_len, Filter::unfilter(), PackHeader::version, and LeFile::writeFile().
virt2rela()
void PackWcle::virt2rela (const le_object_table_entry_t * entr, unsigned * objn, unsigned * addr) static protected
Definition at line 747 of file p_wcle.cpp.
{
    for (; *objn > 1; objn[0]--) {
        if (entr[*objn - 1].my_base_address > *addr)
            continue;
        *addr -= entr[*objn - 1].my_base_address;
        break;
    }
}
References my_base_address.
Referenced by decodeEntryTable(), decodeFixups(), and decodeObjectTable().
Member Data Documentation
big_relocs
int PackWcle::big_relocs = 0 protected
Definition at line 84 of file p_wcle.h.
Referenced by buildLoader(), and preprocessFixups().
has_extra_code
bool PackWcle::has_extra_code = false protected
Definition at line 85 of file p_wcle.h.
Referenced by buildLoader(), and preprocessFixups().
iobject_desc
MemBuffer PackWcle::iobject_desc protected
Definition at line 82 of file p_wcle.h.
Referenced by pack(), readObjectTable(), and unpack().
neweip
unsigned PackWcle::neweip = 0 protected
Definition at line 86 of file p_wcle.h.
Referenced by encodeFixups(), encodeObjectTable(), and pack().
The documentation for this class was generated from the following files:
src/p_wcle.h
src/p_wcle.cpp