My Project: PackLinuxI386sh Class Reference
PackLinuxI386sh Class Reference
linux/sh386
#include <p_lx_sh.h>
Public Member Functions
PackLinuxI386sh (InputFile *f)
virtual ~PackLinuxI386sh ()
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getFilters () const override
virtual void buildLoader (const Filter *) override
virtual void pack1 (OutputFile *fo, Filter &ft) override
virtual off_t pack3 (OutputFile *fo, Filter &ft) override
virtual tribool canPack () override
virtual bool canUnpackVersion (int version) const override
Public Member Functions inherited from PackLinuxI386
PackLinuxI386 (InputFile *f)
linux/386 (generic "execve" format)
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka)
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void buildLoader (const Filter *) override
virtual tribool canPack () override
Public Member Functions inherited from PackUnix
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual bool getShellName (char *buf)
virtual void patchLoader () override
Protected Member Functions inherited from PackLinuxI386
virtual void pack1 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
virtual Linker * newLinker () const override
virtual int getLoaderPrefixSize () const
virtual void buildLinuxLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const *ft)
virtual void patchLoader () override
virtual void patchLoaderChecksum () override
virtual void updateLoader (OutputFile *) override
virtual int checkEhdr (const Elf_LE32_Ehdr *ehdr) const
some ELF utility functions
packed_struct (cprElfHdr1)
packed_struct (cprElfHdr2)
packed_struct (cprElfHdr3)
Protected Member Functions inherited from PackUnixLe32
PackUnixLe32 (InputFile *f)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from PackUnix
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
int o_shname
int l_shname
Protected Attributes inherited from PackLinuxI386
unsigned n_mru
cprElfHdr3 elfout
struct PackLinuxI386::Elf32_Note elfnote
unsigned char ei_osabi
char const * osabi_note
Protected Attributes inherited from PackUnix
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef PackLinuxI386 super
Additional Inherited Members
Public Types inherited from PackUnix
typedef Packer super
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PackLinuxI386
enum { UPX_ELF_MAGIC = 0x5850557f }
Protected Types inherited from PackUnix
enum { OVERHEAD = 2048 }
Static Protected Member Functions inherited from PackLinuxI386
static void compileTimeAssertions ()
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
linux/sh386
Definition at line 42 of file p_lx_sh.h.
Member Typedef Documentation
super
typedef PackLinuxI386 PackLinuxI386sh::super private
Definition at line 44 of file p_lx_sh.h.
Constructor & Destructor Documentation
PackLinuxI386sh()
static const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT PackLinuxI386sh::PackLinuxI386sh (InputFile * f)
Definition at line 56 of file p_lx_sh.cpp.
                                             :
    super(f), o_shname(0), l_shname(0)
{
}
~PackLinuxI386sh()
PackLinuxI386sh::~PackLinuxI386sh () virtual
Definition at line 61 of file p_lx_sh.cpp.
{
}
Member Function Documentation
buildLoader()
void PackLinuxI386sh::buildLoader (const Filter * ft) override virtual
Reimplemented from PackLinuxI386.
Definition at line 66 of file p_lx_sh.cpp.
{
    unsigned const sz_fold = sizeof(stub_i386_linux_elf_shell_fold);
    MemBuffer buf(sz_fold);
    memcpy(buf, stub_i386_linux_elf_shell_fold, sz_fold);
    checkPatch(nullptr, 0, 0, 0);  // reset
    patch_le32(buf,sz_fold,"UPX3",l_shname);
    patch_le32(buf,sz_fold,"UPX2",o_shname);
    // get fresh filter
    Filter fold_ft = *ft;
    fold_ft.init(ft->id, ft->addvalue);
    int preferred_ctos[2] = { ft->cto, -1 };
    fold_ft.preferred_ctos = preferred_ctos;
    // filter
    optimizeFilter(&fold_ft, buf, sz_fold);
    unsigned fold_hdrlen = sizeof(l_info) + sizeof(Elf32_Ehdr) +
        sizeof(Elf32_Phdr) * get_te16(&((Elf32_Ehdr const *)(void *)buf)->e_phnum);
    if (0 == get_le32(buf + fold_hdrlen)) {
        // inconsistent SIZEOF_HEADERS in *.lds (ld, binutils)
        fold_hdrlen = upx::umax(0x80u, fold_hdrlen);
    }
    bool success = fold_ft.filter(buf + fold_hdrlen, sz_fold - fold_hdrlen);
    UNUSED(success);
    buildLinuxLoader(
        stub_i386_linux_elf_shell_entry, sizeof(stub_i386_linux_elf_shell_entry),
        buf, sz_fold, ft );
}
References Filter::addvalue, buf, PackLinuxI386::buildLinuxLoader(), Packer::checkPatch(), Filter::cto, Filter::filter(), get_le32(), Packer::get_te16(), Filter::id, Filter::init(), l_shname, memcpy(), o_shname, Packer::optimizeFilter(), Packer::patch_le32(), Filter::preferred_ctos, stub_i386_linux_elf_shell_entry, stub_i386_linux_elf_shell_fold, upx::umax(), and UNUSED.
canPack()
tribool PackLinuxI386sh::canPack () override virtual
Reimplemented from PackLinuxI386.
Definition at line 132 of file p_lx_sh.cpp.
{
#if defined(__linux__)  //{
    // only compress i386sh scripts when running under Linux
    char buf[512];
    fi->readx(buf, sizeof(buf));
    fi->seek(0, SEEK_SET);
    buf[sizeof(buf) - 1] = 0;
    if (!memcmp(buf, "#!/", 3)) {                       // #!/bin/sh
        o_shname = 2;
        return getShellName(&buf[o_shname]);
    }
    else if (!memcmp(buf, "#! /", 4)) {                 // #! /bin/sh
        o_shname = 3;
        return getShellName(&buf[o_shname]);
    }
#endif  //}
    return false;
}
References buf, PackerBase::fi, getShellName(), memcmp(), o_shname, InputFile::readx(), InputFile::seek(), and SEEK_SET.
canUnpackVersion()
virtual bool PackLinuxI386sh::canUnpackVersion (int version) const inline override virtual
Reimplemented from Packer.
Definition at line 60 of file p_lx_sh.h.
        { return (version >= 11); }
getFilters()
virtual const int * PackLinuxI386sh::getFilters () const inline override virtual
Reimplemented from PackLinuxI386.
Definition at line 52 of file p_lx_sh.h.
{ return nullptr; }
getFormat()
virtual int PackLinuxI386sh::getFormat () const inline override virtual
Reimplemented from PackLinuxI386.
Definition at line 49 of file p_lx_sh.h.
{ return UPX_F_LINUX_SH_i386; }
References UPX_F_LINUX_SH_i386.
getFullName()
virtual const char * PackLinuxI386sh::getFullName (const options_t *) const inline override virtual
Reimplemented from PackLinuxI386.
Definition at line 51 of file p_lx_sh.h.
{ return "i386-linux.elf.shell"; }
getName()
virtual const char * PackLinuxI386sh::getName () const inline override virtual
Reimplemented from PackLinuxI386.
Definition at line 50 of file p_lx_sh.h.
{ return "linux.sh/i386"; }
getShellName()
bool PackLinuxI386sh::getShellName (char * buf) protected virtual
Definition at line 101 of file p_lx_sh.cpp.
{
    exetype = -1;
    l_shname = (int) strcspn(buf, " \t\n\v\f\r");
    buf[l_shname] = 0;
    static char const *const shname[] = { // known shells that accept "-c" arg
        "ash", "bash", "bsh", "csh", "ksh", "pdksh", "sh", "tcsh", "zsh",
        "python", "python2", "python3",
        nullptr
    };
    const char *bname = strrchr(buf, '/');
    if (bname == nullptr)
        return false;
    for (int j = 0; nullptr != shname[j]; ++j) {
        if (0 == strcmp(shname[j], bname + 1)) {
            bool const s = bool(super::canPack());
            if (s) {
                opt->o_unix.blocksize = blocksize = file_size;
            }
            unsigned size = fi->st_size();
            if (size > (125<<10)) { // 128KB but allow 3KB for environment
                printWarn(fi->getName(), "Likely E2BIG for size=%u", size);
                return false;
            }
            return s;
        }
    }
    return false;
}
References PackUnix::blocksize, buf, PackLinuxI386::canPack(), PackUnix::exetype, PackerBase::fi, PackerBase::file_size, FileBase::getName(), l_shname, opt, printWarn(), size(), FileBase::st_size(), and strcmp().
Referenced by canPack().
getVersion()
virtual int PackLinuxI386sh::getVersion () const inline override virtual
Reimplemented from PackUnix.
Definition at line 48 of file p_lx_sh.h.
{ return 13; }
pack1()
void PackLinuxI386sh::pack1 (OutputFile * fo, Filter & ft) override virtual
Reimplemented from PackLinuxI386.
Definition at line 155 of file p_lx_sh.cpp.
{
    generateElfHdr(fo, stub_i386_linux_elf_shell_fold, 0x08048000);
}
References PackLinuxI386::generateElfHdr(), and stub_i386_linux_elf_shell_fold.
pack3()
off_t PackLinuxI386sh::pack3 (OutputFile * fo, Filter & ft) override virtual
Reimplemented from PackUnix.
Definition at line 161 of file p_lx_sh.cpp.
{
    return elfout.phdr[0].p_filesz = super::pack3(fo,ft);
}
References PackLinuxI386::elfout, and PackUnix::pack3().
patchLoader()
void PackLinuxI386sh::patchLoader () override protected virtual
Reimplemented from PackLinuxI386.
Definition at line 98 of file p_lx_sh.cpp.
{ }
Member Data Documentation
l_shname
int PackLinuxI386sh::l_shname protected
Definition at line 69 of file p_lx_sh.h.
Referenced by buildLoader(), and getShellName().
o_shname
int PackLinuxI386sh::o_shname protected
Definition at line 68 of file p_lx_sh.h.
Referenced by buildLoader(), and canPack().
The documentation for this class was generated from the following files:
src/p_lx_sh.h
src/p_lx_sh.cpp