My Project: PackCom Class Reference
PackCom Class Reference
dos/com
#include <p_com.h>
Public Member Functions
PackCom (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual Linker * newLinker () const override
void addFilter16 (int filter_id)
virtual unsigned getCallTrickOffset () const
virtual void buildLoader (const Filter *ft) override
virtual void patchLoader (OutputFile *fo, byte *, int, unsigned)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
Copy stub from exe.
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Detailed Description
dos/com
Definition at line 34 of file p_com.h.
Member Typedef Documentation
super
typedef Packer PackCom::super private
Definition at line 35 of file p_com.h.
Constructor & Destructor Documentation
PackCom()
PackCom::PackCom (InputFile * f) inline explicit
Definition at line 38 of file p_com.h.
: super(f) { bele = &N_BELE_RTP::le_policy; }
References Packer::bele, and N_BELE_RTP::le_policy.
Member Function Documentation
addFilter16()
void PackCom::addFilter16 (int filter_id) protected
Definition at line 83 of file p_com.cpp.
{
    assert(filter_id > 0);
    assert(isValidFilter(filter_id));
    if (filter_id % 3 == 0) {
        // clang-format off
        addLoader("CALLTR16",
                  filter_id < 4 ? "CT16SUB0" : "",
                  filter_id < 4 ? "" : (opt->cpu_x86 == opt->CPU_8086 ? "CT16I086" : "CT16I286,CT16SUB0"),
                  "CALLTRI2",
                  getFormat() == UPX_F_DOS_COM ? "CORETURN" : "");
        // clang-format on
    } else {
        // clang-format off
        addLoader(filter_id % 3 == 1 ? "CT16E800" : "CT16E900",
                 "CALLTRI5",
                 getFormat() == UPX_F_DOS_COM ? "CT16JEND" : "CT16JUL2",
                 filter_id < 4 ? "CT16SUB1" : "",
                 filter_id < 4 ? "" : (opt->cpu_x86 == opt->CPU_8086 ? "CT16I087" : "CT16I287,CT16SUB1"),
                 "CALLTRI6");
        // clang-format on
    }
}
References Packer::addLoader(), getFormat(), Packer::isValidFilter(), opt, and UPX_F_DOS_COM.
Referenced by buildLoader(), and PackSys::buildLoader().
buildLoader()
void PackCom::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Reimplemented in PackSys.
Definition at line 107 of file p_com.cpp.
{
    initLoader(stub_i086_dos16_com, sizeof(stub_i086_dos16_com));
    // clang-format off
    addLoader("COMMAIN1",
              ph.first_offset_found == 1 ? "COMSBBBP" : "",
              "COMPSHDI",
              ft->id ? "COMCALLT" : "",
              "COMMAIN2,UPX1HEAD,COMCUTPO,NRV2B160",
              ft->id ? "NRVDDONE" : "NRVDRETU",
              "NRVDECO1",
              ph.max_offset_found <= 0xd00 ? "NRVLED00" : "NRVGTD00",
              "NRVDECO2");
    // clang-format on
    if (ft->id) {
        assert(ft->calls > 0);
        addFilter16(ft->id);
    }
}
References addFilter16(), Packer::addLoader(), Filter::calls, PackHeader::first_offset_found, Filter::id, Packer::initLoader(), PackHeader::max_offset_found, PackerBase::ph, and stub_i086_dos16_com.
canPack()
tribool PackCom::canPack () override virtual
Implements PackerBase.
Reimplemented in PackSys.
Definition at line 61 of file p_com.cpp.
{
    byte buf[128];
    fi->readx(buf, sizeof(buf));
    if (memcmp(buf, "MZ", 2) == 0 || memcmp(buf, "ZM", 2) == 0) // .exe
        return false;
    if (memcmp(buf, "\xff\xff\xff\xff", 4) == 0) // .sys
        return false;
    if (!fn_has_ext(fi->getName(), "com")) // query file name
        return false;
    checkAlreadyPacked(buf, sizeof(buf));
    if (file_size < 1024)
        throwCantPack("file is too small for dos/com");
    if (file_size > 0xFF00)
        throwCantPack("file is too large for dos/com");
    return true;
}
References buf, Packer::checkAlreadyPacked(), PackerBase::fi, PackerBase::file_size, fn_has_ext(), FileBase::getName(), memcmp(), InputFile::readx(), and throwCantPack().
canUnpack()
tribool PackCom::canUnpack () override virtual
Implements PackerBase.
Definition at line 200 of file p_com.cpp.
{
    if (!readPackHeader(128)) // read "ph"
        return false;
    if (file_size_u <= ph.c_len)
        return false;
    return true;
}
References PackHeader::c_len, PackerBase::file_size_u, PackerBase::ph, and Packer::readPackHeader().
getCallTrickOffset()
virtual unsigned PackCom::getCallTrickOffset () const inline protected virtual
Reimplemented in PackSys.
Definition at line 56 of file p_com.h.
{ return 0x100; }
Referenced by pack(), and unpack().
getCompressionMethods()
const int * PackCom::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 44 of file p_com.cpp.
{
    static const int m_nrv2b[] = {M_NRV2B_LE16, M_END};
    UNUSED(method);
    UNUSED(level);
    return m_nrv2b;
}
References M_END, M_NRV2B_LE16, and UNUSED.
getFilters()
const int * PackCom::getFilters () const override virtual
Implements PackerBase.
Definition at line 51 of file p_com.cpp.
{
    // see class FilterImpl
    static const int filters[] = {0x06, 0x03, 0x04, 0x01, 0x05, 0x02, FT_END};
    return filters;
}
References FT_END.
getFormat()
virtual int PackCom::getFormat () const inline override virtual
Implements PackerBase.
Reimplemented in PackSys.
Definition at line 40 of file p_com.h.
{ return UPX_F_DOS_COM; }
References UPX_F_DOS_COM.
Referenced by addFilter16().
getFullName()
virtual const char * PackCom::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Reimplemented in PackSys.
Definition at line 42 of file p_com.h.
{ return "i086-dos16.com"; }
getName()
virtual const char * PackCom::getName () const inline override virtual
Implements PackerBase.
Reimplemented in PackSys.
Definition at line 41 of file p_com.h.
{ return "dos/com"; }
Referenced by patchLoader().
getVersion()
virtual int PackCom::getVersion () const inline override virtual
Implements PackerBase.
Reimplemented in PackSys.
Definition at line 39 of file p_com.h.
{ return 13; }
newLinker()
static const CLANG_FORMAT_DUMMY_STATEMENT Linker * PackCom::newLinker () const override protected virtual
Implements Packer.
Definition at line 42 of file p_com.cpp.
{ return new ElfLinkerX86(); }
pack()
void PackCom::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 165 of file p_com.cpp.
{
    // read file
    ibuf.alloc(file_size);
    obuf.allocForCompression(file_size);
    fi->seek(0, SEEK_SET);
    fi->readx(ibuf, file_size);
    // prepare packheader
    ph.u_len = file_size;
    // prepare filter
    Filter ft(ph.level);
    ft.addvalue = getCallTrickOffset();
    // compress
    const unsigned overlap_range = ph.u_len < 0xFE00 - ft.addvalue ? 32 : 0;
    compressWithFilters(&ft, overlap_range, NULL_cconf);
    const int lsize = getLoaderSize();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    const unsigned calls = ft.id % 3 ? ft.lastcall - 2 * ft.calls : ft.calls;
    patchLoader(fo, loader, lsize, calls);
    // verify
    verifyOverlappingDecompression();
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References Filter::addvalue, MemBuffer::alloc(), MemBuffer::allocForCompression(), Filter::calls, Packer::checkFinalCompressionRatio(), Packer::compressWithFilters(), PackerBase::fi, PackerBase::file_size, getCallTrickOffset(), Packer::getLoader(), Packer::getLoaderSize(), Packer::ibuf, Filter::id, Filter::lastcall, PackHeader::level, memcpy(), NULL_cconf, Packer::obuf, patchLoader(), PackerBase::ph, InputFile::readx(), InputFile::seek(), SEEK_SET, throwNotCompressible(), PackHeader::u_len, and Packer::verifyOverlappingDecompression().
patchLoader()
void PackCom::patchLoader (OutputFile * fo, byte * loader, int lsize, unsigned calls) protected virtual
Reimplemented in PackSys.
Definition at line 126 of file p_com.cpp.
{
    const int e_len = getLoaderSectionStart("COMCUTPO");
    const int d_len = lsize - e_len;
    assert(e_len > 0 && e_len < 128);
    assert(d_len > 0 && d_len < 256);
    const unsigned upper_end = ph.u_len + ph.overlap_overhead + d_len + 0x100;
    unsigned stacksize = 0x60;
    if (upper_end + stacksize > 0xfffe)
        stacksize = 0x56;
    if (upper_end + stacksize > 0xfffe)
        throwCantPack("file is too large for dos/com");
    linker->defineSymbol("calltrick_calls", calls);
    linker->defineSymbol("sp_limit", upper_end + stacksize);
    linker->defineSymbol("bytes_to_copy", ph.c_len + lsize);
    linker->defineSymbol("copy_source", ph.c_len + lsize + 0x100);
    linker->defineSymbol("copy_destination", upper_end);
    linker->defineSymbol("neg_e_len", 0 - e_len);
    linker->defineSymbol("NRV2B160", ph.u_len + ph.overlap_overhead);
    relocateLoader();
    loader = getLoader();
    // some day we could use the relocation stuff for patchPackHeader too..
    patchPackHeader(loader, e_len);
    // write loader + compressed file
    fo->write(loader, e_len);         // entry
    fo->write(obuf, ph.c_len);        // compressed
    fo->write(loader + e_len, d_len); // decompressor
    NO_printf("%-13s: entry        : %8u bytes\n", getName(), e_len);
    NO_printf("%-13s: compressed   : %8u bytes\n", getName(), ph.c_len);
    NO_printf("%-13s: decompressor : %8u bytes\n", getName(), d_len);
}
References PackHeader::c_len, Packer::getLoader(), Packer::getLoaderSectionStart(), getName(), NO_printf(), Packer::obuf, PackHeader::overlap_overhead, Packer::patchPackHeader(), PackerBase::ph, Packer::relocateLoader(), throwCantPack(), PackHeader::u_len, and OutputFile::write().
Referenced by pack().
unpack()
void PackCom::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 212 of file p_com.cpp.
{
    ibuf.alloc(file_size);
    obuf.allocForDecompression(ph.u_len);
    // read whole file
    fi->seek(0, SEEK_SET);
    fi->readx(ibuf, file_size);
    // get compressed data offset
    unsigned e_len = ph.buf_offset + ph.getPackHeaderSize();
    if (file_size_u <= e_len + ph.c_len)
        throwCantUnpack("file damaged");
    // decompress
    decompress(ibuf + e_len, obuf);
    // unfilter
    Filter ft(ph.level);
    ft.init(ph.filter, getCallTrickOffset());
    ft.unfilter(obuf, ph.u_len);
    // write decompressed file
    if (fo)
        fo->write(obuf, ph.u_len);
}
References MemBuffer::alloc(), MemBuffer::allocForDecompression(), PackHeader::buf_offset, PackHeader::c_len, Packer::decompress(), PackerBase::fi, PackerBase::file_size, PackerBase::file_size_u, PackHeader::filter, getCallTrickOffset(), PackHeader::getPackHeaderSize(), Packer::ibuf, Filter::init(), PackHeader::level, Packer::obuf, PackerBase::ph, InputFile::readx(), InputFile::seek(), SEEK_SET, throwCantUnpack(), PackHeader::u_len, Filter::unfilter(), and OutputFile::write().
The documentation for this class was generated from the following files:
src/p_com.h
src/p_com.cpp