My Project: PackVmlinuzARMEL Class Reference
PackVmlinuzARMEL Class Reference
vmlinuz/armel (gzip compressed Linux kernel image)
#include <p_vmlinz.h>
Public Member Functions
PackVmlinuzARMEL (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual int readFileHeader ()
virtual int decompressKernel ()
virtual void readKernel ()
virtual void buildLoader (const Filter *ft) override
virtual unsigned write_vmlinuz_head (OutputFile *fo)
virtual void defineDecompressorSymbols () override
virtual Linker * newLinker () const override
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
MemBuffer setup_buf
int setup_size
unsigned filter_len
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
vmlinuz/armel (gzip compressed Linux kernel image)
Definition at line 129 of file p_vmlinz.h.
Member Typedef Documentation
super
typedef Packer PackVmlinuzARMEL::super private
Definition at line 131 of file p_vmlinz.h.
Constructor & Destructor Documentation
PackVmlinuzARMEL()
PackVmlinuzARMEL::PackVmlinuzARMEL (InputFile * f)
Definition at line 719 of file p_vmlinz.cpp.
                                               :
    super(f), setup_size(0), filter_len(0)
{
    bele = &N_BELE_RTP::le_policy;
}
References Packer::bele, and N_BELE_RTP::le_policy.
Member Function Documentation
buildLoader()
static const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT void PackVmlinuzARMEL::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 934 of file p_vmlinz.cpp.
{
    // prepare loader; same as vmlinux (with 'x')
    initLoader(stub_arm_v5a_linux_kernel_vmlinux, sizeof(stub_arm_v5a_linux_kernel_vmlinux));
    addLoader("LINUX000", nullptr);
    if (ft->id) {
        assert(ft->calls > 0);
        addLoader("LINUX010", nullptr);
    }
    addLoader("LINUX020", nullptr);
    if (ft->id) {
        addFilter32(ft->id);
    }
    addLoader("LINUX030", nullptr);
         if (ph.method == M_NRV2E_8) addLoader("NRV2E", nullptr);
    else if (ph.method == M_NRV2B_8) addLoader("NRV2B", nullptr);
    else if (ph.method == M_NRV2D_8) addLoader("NRV2D", nullptr);
    else if (M_IS_LZMA(ph.method))   addLoader("LZMA_ELF00",
        (opt->small ? "LZMA_DEC10" : "LZMA_DEC20"), "LZMA_DEC30", nullptr);
    else throwBadLoader();
    addLoader("IDENTSTR,UPX1HEAD", nullptr);
    // To debug (2008-09-14):
    //   Build gdb-6.8-21.fc9.src.rpm; ./configure --target=arm-none-elf; make
    //     Contains the fix for http://bugzilla.redhat.com/show_bug.cgi?id=436037
    //   Install qemu-0.9.1-6.fc9.i386.rpm
    //   qemu-system-arm -s -S -kernel <file> -nographic
    //   (gdb) target remote localhost:1234
    //   A very small boot loader runs at pc=0x0; the kernel is at 0x10000 (64KiB).
}
References Packer::addFilter32(), Packer::addLoader(), Filter::calls, Filter::id, Packer::initLoader(), M_IS_LZMA, M_NRV2B_8, M_NRV2D_8, M_NRV2E_8, PackHeader::method, opt, PackerBase::ph, stub_arm_v5a_linux_kernel_vmlinux, and throwBadLoader().
canPack()
tribool PackVmlinuzARMEL::canPack () override virtual
Implements PackerBase.
Definition at line 743 of file p_vmlinz.cpp.
{
    return readFileHeader() == getFormat();
}
References getFormat(), and readFileHeader().
canUnpack()
tribool PackVmlinuzARMEL::canUnpack () override virtual
Implements PackerBase.
Definition at line 1037 of file p_vmlinz.cpp.
{
    if (readFileHeader() != getFormat())
        return false;
    fi->seek(setup_size, SEEK_SET);
    return readPackHeader(1024) ? 1 : -1;
}
References PackerBase::fi, getFormat(), readFileHeader(), Packer::readPackHeader(), InputFile::seek(), SEEK_SET, and setup_size.
decompressKernel()
int PackVmlinuzARMEL::decompressKernel () protected virtual
Definition at line 761 of file p_vmlinz.cpp.
{
    // read whole kernel image
    obuf.alloc(file_size);
    fi->seek(0, SEEK_SET);
    fi->readx(obuf, file_size);
    //checkAlreadyPacked(obuf + setup_size, UPX_MIN(file_size - setup_size, 1024LL));
    // Find head.S:
    //      bl decompress_kernel  # 0xeb......
    //      b call_kernel         # 0xea......
    //LC0: .word LC0              # self!
    unsigned decompress_kernel = 0;
    unsigned caller1 = 0;
    unsigned caller2 = 0;
    unsigned got_start = 0;
    unsigned got_end = 0;
    for (unsigned j = 0; j < 0x400; j+=4) {
        unsigned w;
        if (j!=get_te32(j + obuf)) {
            continue;
        }
        if (0xea000000!=(0xff000000&    get_te32(j - 4 + obuf))
        ||  0xeb000000!=(0xff000000&(w= get_te32(j - 8 + obuf))) ) {
            continue;
        }
        caller1 = j - 8;
        decompress_kernel = ((0x00ffffff & w)<<2) + 8+ caller1;
        for (unsigned k = 12; k<=128; k+=4) {
            w = get_te32(j - k + obuf);
            if (0xeb000000==(0xff000000 & w)
            &&  decompress_kernel==(((0x00ffffff & w)<<2) + 8+ j - k) ) {
                caller2 = j - k;
                break;
            }
        }
        got_start = get_te32(5*4 + j + obuf);
        got_end   = get_te32(6*4 + j + obuf);
#if 0  /*{*/
        printf("decompress_kernel=0x%x  got_start=0x%x  got_end=0x%x\n",
            decompress_kernel, got_start, got_end);
#endif  /*}*/
        break;
    }
    if (0==decompress_kernel) {
        return 0;
    }
    // Find first subroutine that is called by decompress_kernel,
    // which we will consider to be the start of the gunzip module
    // and the end of the non-gunzip modules.
    for (unsigned j = decompress_kernel; j < (unsigned)file_size; j+=4) {
        unsigned w = get_te32(j + obuf);
        if (0xeb800000==(0xff800000 & w)) {
            setup_size = 8+ ((0xff000000 | w)<<2) + j;
            // Move the GlobalOffsetTable.
            for (unsigned k = got_start; k < got_end; k+=4) {
                w = get_te32(k + obuf);
                // FIXME: must relocate w
                set_te32(k - got_start + setup_size + obuf, w);
            }
            setup_size += got_end - got_start;
            set_te32(&obuf[caller1], 0xeb000000 |
                (0x00ffffff & ((setup_size - (8+ caller1))>>2)) );
            set_te32(&obuf[caller2], 0xeb000000 |
                (0x00ffffff & ((setup_size - (8+ caller2))>>2)) );
            break;
        }
    }
    for (int gzoff = 0; gzoff < 0x4000; gzoff+=4) {
        // find gzip header (2 bytes magic + 1 byte method "deflated")
        int off = find(obuf + gzoff, file_size - gzoff, "\x1F\x8B\x08", 3);
        if (off < 0 || 0!=(3u & off))
            break;  // not found, or not word-aligned
        gzoff += off;
        const int gzlen = file_size - gzoff;
        if (gzlen < 256)
            break;
        // check gzip flag byte
        unsigned char flags = obuf[gzoff + 3];
        if ((flags & 0xe0) != 0)        // reserved bits set
            continue;
        //printf("found gzip header at offset %d\n", gzoff);
        // try to decompress
        int klen;
        int fd;
        upx_off_t fd_pos;
        for (;;)
        {
            klen = -1;
            fd_pos = -1;
            // open
            fi->seek(gzoff, SEEK_SET);
            fd = fi->dupFd();
            if (fd < 0)
                break;
            gzFile zf = gzdopen(fd, "rb");
            if (zf == nullptr)
                break;
            // estimate gzip-decompressed kernel size & alloc buffer
            if (ibuf.getSize() == 0)
                ibuf.alloc(gzlen * 3);
            // decompress
            klen = gzread(zf, ibuf, ibuf.getSize());
            fd_pos = lseek(fd, 0, SEEK_CUR);
            gzclose(zf);
            fd = -1;
            if (klen != (int)ibuf.getSize())
                break;
            // realloc and try again
            unsigned const s = ibuf.getSize();
            ibuf.dealloc();
            ibuf.alloc(3 * s / 2);
        }
        if (fd >= 0)
            (void) close(fd);
        if (klen <= 0)
            continue;
        if (klen <= gzlen)
            continue;
        if (opt->force > 0)
            return klen;
        // some checks
        if (fd_pos != file_size) {
            //printf("fd_pos: %ld, file_size: %ld\n", (long)fd_pos, (long)file_size);
        }
    //head_ok:
        // FIXME: more checks for special magic bytes in ibuf ???
        // FIXME: more checks for kernel architecture ???
        return klen;
    }
    return 0;
}
References MemBuffer::alloc(), close(), MemBuffer::dealloc(), InputFile::dupFd(), PackerBase::fi, PackerBase::file_size, find(), Packer::get_te32(), MemBuffer::getSize(), Packer::ibuf, lseek(), Packer::obuf, opt, InputFile::readx(), InputFile::seek(), SEEK_CUR, SEEK_SET, Packer::set_te32(), and setup_size.
Referenced by readKernel().
defineDecompressorSymbols()
void PackVmlinuzARMEL::defineDecompressorSymbols () override protected virtual
Reimplemented from Packer.
Definition at line 965 of file p_vmlinz.cpp.
{
    super::defineDecompressorSymbols();
    linker->defineSymbol(  "COMPRESSED_LENGTH", ph.c_len);
    linker->defineSymbol("UNCOMPRESSED_LENGTH", ph.u_len);
    linker->defineSymbol("METHOD", ph.method);
}
References PackHeader::c_len, Packer::defineDecompressorSymbols(), PackHeader::method, PackerBase::ph, and PackHeader::u_len.
Referenced by pack().
getCompressionMethods()
const int * PackVmlinuzARMEL::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 725 of file p_vmlinz.cpp.
{
    return Packer::getDefaultCompressionMethods_8(method, level);
}
References Packer::getDefaultCompressionMethods_8().
getFilters()
const int * PackVmlinuzARMEL::getFilters () const override virtual
Implements PackerBase.
Definition at line 730 of file p_vmlinz.cpp.
{
    static const int f50[] = { 0x50, FT_END };
    return f50;
}
References FT_END.
getFormat()
virtual int PackVmlinuzARMEL::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 135 of file p_vmlinz.h.
{ return UPX_F_VMLINUZ_ARM; }
References UPX_F_VMLINUZ_ARM.
Referenced by canPack(), and canUnpack().
getFullName()
virtual const char * PackVmlinuzARMEL::getFullName (const options_t *) const inline override virtual
Definition at line 137 of file p_vmlinz.h.
{ return "arm-linux.kernel.vmlinuz"; }
getName()
virtual const char * PackVmlinuzARMEL::getName () const inline override virtual
Implements PackerBase.
Definition at line 136 of file p_vmlinz.h.
{ return "vmlinuz/arm"; }
Referenced by pack().
getStrategy()
int PackVmlinuzARMEL::getStrategy (Filter &) virtual
Definition at line 736 of file p_vmlinz.cpp.
{
    // If user specified the filter, then use it (-2==filter_strategy).
    // Else try the first two filters, and pick the better (2==filter_strategy).
    return (opt->no_filter ? -3 : ((opt->filter > 0) ? -2 : 2));
}
References opt.
Referenced by pack().
getVersion()
virtual int PackVmlinuzARMEL::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 134 of file p_vmlinz.h.
{ return 13; }
newLinker()
Linker * PackVmlinuzARMEL::newLinker () const override protected virtual
Implements Packer.
Definition at line 924 of file p_vmlinz.cpp.
{
    return new ElfLinkerArmLE;
}
pack()
void PackVmlinuzARMEL::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 988 of file p_vmlinz.cpp.
{
    readKernel();
    // prepare filter
    Filter ft(ph.level);
    ft.buf_len = ph.u_len;
    ft.addvalue = 0;
    // compress
    upx_compress_config_t cconf; cconf.reset();
    // limit stack size needed for runtime decompression
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 5); // ushort: 52,844 byte stack
    compressWithFilters(&ft, 512, &cconf, getStrategy(ft));
    const unsigned lsize = getLoaderSize();
    defineDecompressorSymbols();
    defineFilterSymbols(&ft);
    relocateLoader();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, lsize);
//    boot_sect_t * const bs = (boot_sect_t *) ((unsigned char *) setup_buf);
//    bs->sys_size = ALIGN_UP(lsize + ph.c_len, 16u) / 16;
//    bs->payload_length = ph.c_len;
    fo->write(setup_buf, setup_buf.getSize());
    write_vmlinuz_head(fo);
    fo->write(obuf, ph.c_len);
    unsigned const zero = 0;
    fo->write((void const *)&zero, 3u & (0u - ph.c_len));
    fo->write(loader, lsize);
#if 0
    printf("%-13s: setup        : %8ld bytes\n", getName(), (long) setup_buf.getSize());
    printf("%-13s: loader       : %8ld bytes\n", getName(), (long) lsize);
    printf("%-13s: compressed   : %8ld bytes\n", getName(), (long) ph.c_len);
#endif
    // verify
    verifyOverlappingDecompression();
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References Filter::addvalue, Filter::buf_len, PackHeader::c_len, Packer::checkFinalCompressionRatio(), Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, defineDecompressorSymbols(), Packer::defineFilterSymbols(), Packer::getLoader(), Packer::getLoaderSize(), getName(), MemBuffer::getSize(), getStrategy(), PackHeader::level, lzma_compress_config_t::max_num_probs, memcpy(), Packer::obuf, Packer::patchPackHeader(), PackerBase::ph, readKernel(), Packer::relocateLoader(), upx_compress_config_t::reset(), setup_buf, throwNotCompressible(), PackHeader::u_len, Packer::verifyOverlappingDecompression(), OutputFile::write(), and write_vmlinuz_head().
readFileHeader()
int PackVmlinuzARMEL::readFileHeader () protected virtual
Definition at line 748 of file p_vmlinz.cpp.
{
    unsigned int hdr[8];
    fi->readx(hdr, sizeof(hdr));
    for (int j=0; j < 8; ++j) {
        if (0xe1a00000!=get_te32(&hdr[j])) {
            return 0;
        }
    }
    return UPX_F_VMLINUZ_ARM;
}
References PackerBase::fi, Packer::get_te32(), InputFile::readx(), and UPX_F_VMLINUZ_ARM.
Referenced by canPack(), and canUnpack().
readKernel()
void PackVmlinuzARMEL::readKernel () protected virtual
Definition at line 905 of file p_vmlinz.cpp.
{
    int klen = decompressKernel();
    if (klen <= 0)
        throwCantPack("kernel decompression failed");
    //OutputFile::dump("kernel.img", ibuf, klen);
    // copy the setup boot code
    setup_buf.alloc(setup_size);
    memcpy(setup_buf, obuf, setup_size);
    //OutputFile::dump("setup.img", setup_buf, setup_size);
    obuf.dealloc();
    obuf.allocForCompression(klen);
    ph.u_len = klen;
    ph.filter = 0;
}
References MemBuffer::alloc(), MemBuffer::allocForCompression(), MemBuffer::dealloc(), decompressKernel(), PackHeader::filter, memcpy(), Packer::obuf, PackerBase::ph, setup_buf, setup_size, throwCantPack(), and PackHeader::u_len.
Referenced by pack().
unpack()
void PackVmlinuzARMEL::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 1045 of file p_vmlinz.cpp.
{
    // no uncompression support for this format, so that
    // it is possible to remove the original deflate code (>10 KiB)
    // FIXME: but we could write the uncompressed "vmlinux" image
    ibuf.alloc(ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    fi->seek(setup_size + ph.buf_offset + ph.getPackHeaderSize(), SEEK_SET);
    fi->readx(ibuf, ph.c_len);
    // decompress
    decompress(ibuf, obuf);
    // unfilter
    Filter ft(ph.level);
    ft.init(ph.filter, 0);
    ft.cto = (unsigned char) ph.filter_cto;
    ft.unfilter(obuf, ph.u_len);
    // write decompressed file
    if (fo)
    {
        throwCantUnpack("build a new kernel instead :-)");
        //fo->write(obuf, ph.u_len);
    }
}
References MemBuffer::alloc(), MemBuffer::allocForDecompression(), PackHeader::buf_offset, PackHeader::c_len, Filter::cto, Packer::decompress(), PackerBase::fi, PackHeader::filter, PackHeader::filter_cto, PackHeader::getPackHeaderSize(), Packer::ibuf, Filter::init(), PackHeader::level, Packer::obuf, PackerBase::ph, InputFile::readx(), InputFile::seek(), SEEK_SET, setup_size, throwCantUnpack(), PackHeader::u_len, and Filter::unfilter().
write_vmlinuz_head()
unsigned PackVmlinuzARMEL::write_vmlinuz_head (OutputFile * fo) protected virtual
Definition at line 973 of file p_vmlinz.cpp.
{ // First word from vmlinuz-head.S
    fo->write(&stub_arm_v5a_linux_kernel_vmlinuz_head[0], 4);
    // Second word
    upx_uint32_t tmp_u32;
    unsigned const t = (0xff000000 &
            get_te32(&stub_arm_v5a_linux_kernel_vmlinuz_head[4]))
        | (0x00ffffff & (0u - 1 + ((3+ ph.c_len)>>2)));
    set_te32(&tmp_u32, t);
    fo->write(&tmp_u32, 4);
    return sizeof(stub_arm_v5a_linux_kernel_vmlinuz_head);
}
References PackHeader::c_len, Packer::get_te32(), PackerBase::ph, Packer::set_te32(), stub_arm_v5a_linux_kernel_vmlinuz_head, and OutputFile::write().
Referenced by pack().
Member Data Documentation
filter_len
unsigned PackVmlinuzARMEL::filter_len protected
Definition at line 167 of file p_vmlinz.h.
setup_buf
MemBuffer PackVmlinuzARMEL::setup_buf protected
Definition at line 162 of file p_vmlinz.h.
Referenced by pack(), and readKernel().
setup_size
int PackVmlinuzARMEL::setup_size protected
Definition at line 163 of file p_vmlinz.h.
Referenced by canUnpack(), decompressKernel(), readKernel(), and unpack().
The documentation for this class was generated from the following files:
src/p_vmlinz.h
src/p_vmlinz.cpp