My Project: PackDylibI386 Class Reference
PackDylibI386 Class Reference
#include <p_mach.h>
Public Member Functions
PackDylibI386 (InputFile *f)
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
Public Member Functions inherited from PackMachI386
PackMachI386 (InputFile *f)
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
Public Member Functions inherited from PackMachBase< MachClass_LE32 >
PackMachBase (InputFile *, unsigned cpuid, unsigned filetype, unsigned t_flavor, unsigned ts_word_cnt, unsigned tc_size, unsigned page_shift)
virtual ~PackMachBase ()
virtual int getVersion () const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual void pack1 (OutputFile *, Filter &) override
virtual int pack2 (OutputFile *, Filter &) override
virtual off_t pack3 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
virtual void pack4dylib (OutputFile *, Filter &, Addr init_address)
virtual int threado_size () const=0
virtual void threado_setPC (upx_uint64_t pc)=0
virtual void threado_rewrite (OutputFile *)=0
virtual void threado_write (OutputFile *)=0
virtual void pack1_setup_threado (OutputFile *const fo)=0
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
virtual upx_uint64_t get_mod_init_func (Mach_segment_command const *segptr)
virtual unsigned find_SEGMENT_gap (unsigned const k, unsigned pos_eof)
Public Member Functions inherited from PackUnix
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual off_t pack3 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
Protected Member Functions inherited from PackMachI386
virtual const int * getFilters () const override
virtual void pack1_setup_threado (OutputFile *const fo) override
virtual Linker * newLinker () const override
virtual void addStubEntrySections (Filter const *) override
packed_struct (Mach_thread_command)
int threado_size () const override
void threado_setPC (upx_uint64_t pc) override
void threado_rewrite (OutputFile *fo) override
void threado_write (OutputFile *fo) override
upx_uint64_t threadc_getPC (void const *ptr) override
Protected Member Functions inherited from PackMachBase< MachClass_LE32 >
virtual void patchLoader () override
virtual void patchLoaderChecksum () override
virtual void updateLoader (OutputFile *) override
virtual void buildLoader (const Filter *ft) override
virtual void buildMachLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const *ft)
virtual void defineSymbols (Filter const *)
virtual void addStubEntrySections (Filter const *)
virtual upx_uint64_t threadc_getPC (void const *)=0
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from PackUnix
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Private Types
typedef PackMachI386 super
Additional Inherited Members
Public Types inherited from PackUnix
typedef Packer super
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PackMachBase< MachClass_LE32 >
typedef MachClass_LE32 MachClass
typedef MachClass::BeLePolicy BeLePolicy
typedef MachClass::MachITypes MachITypes
typedef MachClass::TE16 TE16
typedef MachClass::TE32 TE32
typedef MachClass::TE64 TE64
typedef MachClass::Addr Addr
typedef MachClass::Mach_header Mach_header
typedef MachClass::Mach_command Mach_command
typedef MachClass::Mach_segment_command Mach_segment_command
typedef MachClass::Mach_section_command Mach_section_command
typedef MachClass::Mach_symtab_command Mach_symtab_command
typedef MachClass::Mach_dysymtab_command Mach_dysymtab_command
typedef MachClass::Mach_segsplit_info_command Mach_segsplit_info_command
typedef MachClass::Mach_routines_command Mach_routines_command
typedef MachClass::Mach_twolevel_hints_command Mach_twolevel_hints_command
typedef MachClass::Mach_linkedit_data_command Mach_linkedit_data_command
typedef MachClass::Mach_uuid_command Mach_uuid_command
typedef MachClass::Mach_main_command Mach_main_command
typedef MachClass::Mach_load_dylib_command Mach_load_dylib_command
typedef MachClass::Mach_dylib Mach_dylib
typedef MachClass::Mach_load_dylinker_command Mach_load_dylinker_command
typedef MachClass::Mach_dyld_info_only_command Mach_dyld_info_only_command
typedef MachClass::Mach_version_min_command Mach_version_min_command
typedef MachClass::Mach_source_version_command Mach_source_version_command
Protected Types inherited from PackUnix
enum { OVERHEAD = 2048 }
Static Protected Member Functions inherited from PackMachBase< MachClass_LE32 >
static int __acc_cdecl_qsort compare_segment_command (void const *aa, void const *bb)
static void compileTimeAssertions ()
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes inherited from PackMachI386
Mach_thread_command threado
Protected Attributes inherited from PackMachBase< MachClass_LE32 >
upx_uint64_t entryVMA
upx_uint64_t my_page_size
upx_uint64_t my_page_mask
unsigned my_cputype
unsigned my_cpusubtype
unsigned my_filetype
unsigned my_thread_flavor
unsigned my_thread_state_word_count
unsigned my_thread_command_size
unsigned n_segment
unsigned sz_segment
unsigned sz_mach_headers
unsigned sz_stub_entry
unsigned sz_stub_fold
unsigned sz_stub_main
upx_byte const * stub_entry
upx_byte const * stub_fold
upx_byte const * stub_main
MemBuffer rawmseg_buf
Mach_segment_command * rawmseg
MemBuffer msegcmd_buf
Mach_segment_command * msegcmd
unsigned o__mod_init_func
upx_uint64_t prev_mod_init_func
upx_uint64_t pagezero_vmsize
upx_uint64_t vma_max
Mach_header mhdri
Mach_header mhdro
Mach_segment_command segZERO
Mach_segment_command segXHDR
Mach_section_command secXHDR
Mach_segment_command segTEXT
Mach_section_command secTEXT
Mach_segment_command segLINK
Mach_linkedit_data_command linkitem
Mach_uuid_command cmdUUID
Mach_source_version_command cmdSRCVER
Mach_version_min_command cmdVERMIN
struct l_info linfo
Protected Attributes inherited from PackUnix
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Detailed Description
Definition at line 1051 of file p_mach.h.
Member Typedef Documentation
super
typedef PackMachI386 PackDylibI386::super private
Definition at line 1053 of file p_mach.h.
Constructor & Destructor Documentation
PackDylibI386()
PackDylibI386::PackDylibI386 (InputFile * f)
Definition at line 238 of file p_mach.cpp.
                                         : super(f)
{
    my_filetype = Mach_header::MH_DYLIB;
}
References PackMachBase< MachClass_LE32 >::my_filetype.
Member Function Documentation
getFormat()
virtual int PackDylibI386::getFormat () const inline override virtual
Reimplemented from PackMachI386.
Definition at line 1058 of file p_mach.h.
{ return UPX_F_DYLIB_i386; }
References UPX_F_DYLIB_i386.
Referenced by PackMachFat::canUnpack().
getFullName()
virtual const char * PackDylibI386::getFullName (const options_t *) const inline override virtual
Reimplemented from PackMachI386.
Definition at line 1060 of file p_mach.h.
{ return "i386-darwin.dylib"; }
getName()
virtual const char * PackDylibI386::getName () const inline override virtual
Reimplemented from PackMachI386.
Definition at line 1059 of file p_mach.h.
{ return "dylib/i386"; }
pack3()
off_t PackDylibI386::pack3 (OutputFile * fo, Filter & ft) override protected virtual
Reimplemented from PackMachBase< MachClass_LE32 >.
Definition at line 1008 of file p_mach.cpp.
{
    TE32 disp;
    upx_uint32_t const zero = 0;
    off_t len = fo->getBytesWritten();
    fo->write(&zero, 3& (0u-len));
    len += (3& (0u-len)) + 4*sizeof(disp);
    disp = prev_mod_init_func;
    fo->write(&disp, sizeof(disp));  // user .init_address
    disp = secTEXT.offset + sizeof(l_info) + sizeof(p_info);
    fo->write(&disp, sizeof(disp));  // src offset(compressed __TEXT)
    disp = len - disp - 3*sizeof(disp);
    fo->write(&disp, sizeof(disp));  // length(compressed __TEXT)
    unsigned const save_sz_mach_headers(sz_mach_headers);
    sz_mach_headers = 0;
    len = super::pack3(fo, ft);
    sz_mach_headers = save_sz_mach_headers;
    return len;
}
References OutputFile::getBytesWritten(), PackUnix::pack3(), PackMachBase< MachClass_LE32 >::prev_mod_init_func, PackMachBase< MachClass_LE32 >::secTEXT, PackMachBase< MachClass_LE32 >::sz_mach_headers, and OutputFile::write().
pack4()
void PackDylibI386::pack4 (OutputFile * fo, Filter & ft) override protected virtual
Reimplemented from PackMachBase< MachClass_LE32 >.
Definition at line 964 of file p_mach.cpp.
{
    pack4dylib(fo, ft, threado.state.eip);
}
References PackMachBase< MachClass_LE32 >::pack4dylib(), and PackMachI386::threado.
The documentation for this class was generated from the following files:
src/p_mach.h
src/p_mach.cpp