My Project: PackW32PeI386 Class Reference
PackW32PeI386 Class Reference final
win32/pe (i386)
#include <p_w32pe_i386.h>
Public Member Functions
PackW32PeI386 (InputFile *f)
virtual ~PackW32PeI386 () noexcept
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual bool needForceOption () const override
virtual void defineSymbols (unsigned ncsection, unsigned upxsection, unsigned sizeof_oh, unsigned isize_isplit, unsigned s1addr) override
virtual void addNewRelocations (Reloc &, unsigned upxsection) override
virtual void setOhDataBase (const pe_section_t *osection) override
virtual void setOhHeaderSize (const pe_section_t *osection) override
virtual void pack (OutputFile *fo) override
virtual tribool canPack () override
pack
Public Member Functions inherited from PeFile
virtual int getVersion () const override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual int readFileHeader () override
util
virtual void buildLoader (const Filter *ft) override
virtual Linker * newLinker () const override
Protected Member Functions inherited from PeFile32
PeFile32 (InputFile *f)
PeFile32.
virtual ~PeFile32 () noexcept
void pack0 (OutputFile *fo, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only)
virtual void unpack (OutputFile *fo) override
virtual tribool canUnpack () override
virtual void readPeHeader () override
virtual unsigned processImports () override
virtual void processRelocs () override
virtual void processTls (Interval *) override
virtual void processTls (Reloc *, const Interval *, unsigned) override
Protected Member Functions inherited from PeFile
PeFile (InputFile *f)
virtual ~PeFile () noexcept
void readSectionHeaders (unsigned objs, unsigned sizeof_ih)
pack
unsigned readSections (unsigned objs, unsigned usize, unsigned ih_filealign, unsigned ih_datasize)
void checkHeaderValues (unsigned subsystem, unsigned mask, unsigned ih_entry, unsigned ih_filealign)
unsigned handleStripRelocs (upx_uint64_t ih_imagebase, upx_uint64_t default_imagebase, LE16 &dllflags)
virtual bool needForceOption () const =0
virtual void callCompressWithFilters (Filter &, int filter_strategy, unsigned ih_codebase)
virtual void defineSymbols (unsigned ncsection, unsigned upxsection, unsigned sizeof_oh, unsigned isize_isplit, unsigned s1addr)=0
virtual void addNewRelocations (Reloc &, unsigned)
void callProcessStubRelocs (Reloc &rel, unsigned &ic)
void callProcessResources (Resource &res, unsigned &ic)
virtual unsigned getProcessImportParam (unsigned)
virtual void setOhDataBase (const pe_section_t *osection)=0
virtual void setOhHeaderSize (const pe_section_t *osection)=0
template<typename LEXX , typename ht >
void pack0 (OutputFile *fo, ht &ih, ht &oh, unsigned subsystem_mask, upx_uint64_t default_imagebase, bool last_section_rsrc_only)
Create UPX0 section with compressed full executable.
template<typename ht , typename LEXX , typename ord_mask_t >
void unpack0 (OutputFile *fo, const ht &ih, ht &oh, ord_mask_t ord_mask, bool set_oft)
virtual bool canUnpackVersion (int version) const override
int canUnpack0 (unsigned max_sections, unsigned objs, unsigned ih_entry, unsigned ih_size)
virtual int readFileHeader ()
virtual bool testUnpackVersion (int version) const override
virtual void readPeHeader ()=0
template<typename LEXX , typename ord_mask_t >
unsigned processImports0 (ord_mask_t ord_mask)
template<typename LEXX , typename ord_mask_t >
void rebuildImports (SPAN_S(byte) &extra_info, ord_mask_t ord_mask, bool set_oft)
virtual unsigned processImports ()=0
virtual void processImports2 (unsigned, unsigned)
SPAN_0 (byte) oimport
virtual const char * kernelDll () const
void addKernelImport (const char *)
virtual void addStubImports ()
upx_uint64_t ilinkerGetAddress (const char *, const char *) const
virtual void processRelocs ()=0
void rebuildRelocs (SPAN_S(byte) &, unsigned bits, unsigned flags, upx_uint64_t imagebase)
unpack
SPAN_0 (byte) orelocs
void processExports (Export *)
void processExports (Export *, unsigned)
void rebuildExports ()
SPAN_0 (byte) oexport
void processResources (Resource *)
void processResources (Resource *, unsigned)
void rebuildResources (SPAN_S(byte) &, unsigned)
SPAN_0 (byte) oresources
template<typename LEXX >
void processTls1 (Interval *iv, typename tls_traits< LEXX >::cb_value_t imagebase, unsigned imagesize)
template<typename LEXX >
void processTls2 (Reloc *rel, const Interval *iv, unsigned newaddr, typename tls_traits< LEXX >::cb_value_t imagebase)
virtual void processTls (Interval *iv)=0
virtual void processTls (Reloc *r, const Interval *iv, unsigned a)=0
void rebuildTls ()
SPAN_0 (byte) otls
void processLoadConf (Reloc *, const Interval *, unsigned)
void processLoadConf (Interval *)
Load Configuration handling.
unsigned stripDebug (unsigned)
LE32 & IDSIZE (unsigned x)
import handling
LE32 & IDADDR (unsigned x)
LE32 & ODSIZE (unsigned x)
LE32 & ODADDR (unsigned x)
const LE32 & IDSIZE (unsigned x) const
const LE32 & IDADDR (unsigned x) const
SPAN_0 (pe_section_t) isection
unsigned tryremove (unsigned, unsigned)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
Copy stub from exe.
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Private Types
typedef PeFile32 super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PeFile
enum {
IMAGE_FILE_MACHINE_UNKNOWN = 0 , IMAGE_FILE_MACHINE_AMD64 = 0x8664 , IMAGE_FILE_MACHINE_ARM = 0x01c0 , IMAGE_FILE_MACHINE_ARMNT = 0x01c4 ,
IMAGE_FILE_MACHINE_ARM64 = 0xaa64 , IMAGE_FILE_MACHINE_ARM64EC = 0xa641 , IMAGE_FILE_MACHINE_I386 = 0x014c , IMAGE_FILE_MACHINE_IA64 = 0x200 ,
IMAGE_FILE_MACHINE_LOONGARCH32 = 0x6232 , IMAGE_FILE_MACHINE_LOONGARCH64 = 0x6264 , IMAGE_FILE_MACHINE_RISCV32 = 0x5032 , IMAGE_FILE_MACHINE_RISCV64 = 0x5064 ,
IMAGE_FILE_MACHINE_RISCV128 = 0x5128 , IMAGE_FILE_MACHINE_THUMB = 0x01c2
}
enum {
PEDIR_EXPORT = 0 , PEDIR_IMPORT = 1 , PEDIR_RESOURCE = 2 , PEDIR_EXCEPTION = 3 ,
PEDIR_SECURITY = 4 , PEDIR_BASERELOC = 5 , PEDIR_DEBUG = 6 , PEDIR_ARCHITECTURE = 7 ,
PEDIR_GLOBALPTR = 8 , PEDIR_TLS = 9 , PEDIR_LOAD_CONFIG = 10 , PEDIR_BOUND_IMPORT = 11 ,
PEDIR_IAT = 12 , PEDIR_DELAY_IMPORT = 13 , PEDIR_COM_DESCRIPTOR = 14
}
enum : unsigned {
IMAGE_SCN_CNT_CODE = 0x00000020 , IMAGE_SCN_CNT_INITIALIZED_DATA = 0x00000040 , IMAGE_SCN_CNT_UNINITIALIZED_DATA = 0x00000080 , IMAGE_SCN_LNK_OTHER = 0x00000100 ,
IMAGE_SCN_LNK_INFO = 0x00000200 , IMAGE_SCN_LNK_REMOVE = 0x00000800 , IMAGE_SCN_LNK_COMDAT = 0x00001000 , IMAGE_SCN_GPREL = 0x00008000 ,
IMAGE_SCN_MEM_PURGEABLE = 0x00020000 , IMAGE_SCN_MEM_16BIT = 0x00020000 , IMAGE_SCN_MEM_LOCKED = 0x00040000 , IMAGE_SCN_MEM_PRELOAD = 0x00080000 ,
IMAGE_SCN_ALIGN_1BYTES = 0x00100000 , IMAGE_SCN_ALIGN_2BYTES = 0x00200000 , IMAGE_SCN_ALIGN_4BYTES = 0x00300000 , IMAGE_SCN_ALIGN_8BYTES = 0x00400000 ,
IMAGE_SCN_ALIGN_16BYTES = 0x00500000 , IMAGE_SCN_ALIGN_32BYTES = 0x00600000 , IMAGE_SCN_ALIGN_64BYTES = 0x00700000 , IMAGE_SCN_ALIGN_128BYTES = 0x00800000 ,
IMAGE_SCN_ALIGN_256BYTES = 0x00900000 , IMAGE_SCN_ALIGN_512BYTES = 0x00A00000 , IMAGE_SCN_ALIGN_1024BYTES = 0x00B00000 , IMAGE_SCN_ALIGN_2048BYTES = 0x00C00000 ,
IMAGE_SCN_ALIGN_4096BYTES = 0x00D00000 , IMAGE_SCN_ALIGN_8192BYTES = 0x00E00000 , IMAGE_SCN_LNK_NRELOC_OVFL = 0x01000000 , IMAGE_SCN_MEM_DISCARDABLE = 0x02000000 ,
IMAGE_SCN_MEM_NOT_CACHED = 0x04000000 , IMAGE_SCN_MEM_NOT_PAGED = 0x08000000 , IMAGE_SCN_MEM_SHARED = 0x10000000 , IMAGE_SCN_MEM_EXECUTE = 0x20000000 ,
IMAGE_SCN_MEM_READ = 0x40000000 , IMAGE_SCN_MEM_WRITE = 0x80000000
}
enum {
IMAGE_FILE_RELOCS_STRIPPED = 0x0001 , IMAGE_FILE_EXECUTABLE_IMAGE = 0x0002 , IMAGE_FILE_LINE_NUMS_STRIPPED = 0x0004 , IMAGE_FILE_LOCAL_SYMS_STRIPPED = 0x0008 ,
IMAGE_FILE_AGGRESSIVE_WS_TRIM = 0x0010 , IMAGE_FILE_LARGE_ADDRESS_AWARE = 0x0020 , IMAGE_FILE_BYTES_REVERSED_LO = 0x0080 , IMAGE_FILE_32BIT_MACHINE = 0x0100 ,
IMAGE_FILE_DEBUG_STRIPPED = 0x0200 , IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP = 0x0400 , IMAGE_FILE_NET_RUN_FROM_SWAP = 0x0800 , IMAGE_FILE_SYSTEM = 0x1000 ,
IMAGE_FILE_DLL = 0x2000 , IMAGE_FILE_UP_SYSTEM_ONLY = 0x4000 , IMAGE_FILE_BYTES_REVERSE_HI = 0x8000
}
enum {
IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA = 0x0020 , IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE = 0x0040 , IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY = 0x0080 , IMAGE_DLLCHARACTERISTICS_NX_COMPAT = 0x0100 ,
IMAGE_DLLCHARACTERISTICS_NO_ISOLATION = 0x0200 , IMAGE_DLLCHARACTERISTICS_NO_SEH = 0x0400 , IMAGE_DLLCHARACTERISTICS_NO_BIND = 0x0800 , IMAGE_DLLCHARACTERISTICS_APPCONTAINER = 0x1000 ,
IMAGE_DLLCHARACTERISTICS_WDM_DRIVER = 0x2000 , IMAGE_DLLCHARACTERISTICS_GUARD_CF = 0x4000 , IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = 0x8000
}
enum {
IMAGE_SUBSYSTEM_UNKNOWN = 0 , IMAGE_SUBSYSTEM_NATIVE = 1 , IMAGE_SUBSYSTEM_WINDOWS_GUI = 2 , IMAGE_SUBSYSTEM_WINDOWS_CUI = 3 ,
IMAGE_SUBSYSTEM_WINDOWS_OS2_CUI = 5 , IMAGE_SUBSYSTEM_WINDOWS_POSIX_CUI = 7 , IMAGE_SUBSYSTEM_NATIVE_WINDOWS = 8 , IMAGE_SUBSYSTEM_WINDOWS_CE_GUI = 9 ,
IMAGE_SUBSYSTEM_EFI_APPLICATION = 10 , IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER = 11 , IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER = 12 , IMAGE_SUBSYSTEM_EFI_ROM = 13 ,
IMAGE_SUBSYSTEM_XBOX = 14 , IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION = 16
}
enum {
RT_CURSOR = 1 , RT_BITMAP , RT_ICON , RT_MENU ,
RT_DIALOG , RT_STRING , RT_FONTDIR , RT_FONT ,
RT_ACCELERATOR , RT_RCDATA , RT_MESSAGETABLE , RT_GROUP_CURSOR ,
RT_GROUP_ICON = 14 , RT_VERSION = 16 , RT_DLGINCLUDE , RT_PLUGPLAY = 19 ,
RT_VXD , RT_ANICURSOR , RT_ANIICON , RT_HTML ,
RT_MANIFEST , RT_LAST
}
enum {
IMAGE_REL_BASED_ABSOLUTE = 0 , IMAGE_REL_BASED_IGNORE = 0 , IMAGE_REL_BASED_HIGH = 1 , IMAGE_REL_BASED_LOW = 2 ,
IMAGE_REL_BASED_HIGHLOW = 3 , IMAGE_REL_BASED_HIGHADJ = 4 , IMAGE_REL_BASED_MIPS_JMPADDR = 5 , IMAGE_REL_BASED_ARM_MOV32 = 5 ,
IMAGE_REL_BASED_THUMB_MOV32 = 7 , IMAGE_REL_BASED_MIPS_JMPADDR16 = 9 , IMAGE_REL_BASED_IA64_IMM64 = 9 , IMAGE_REL_BASED_DIR64 = 10
}
Static Protected Member Functions inherited from PeFile
static int checkMachine (unsigned cpu)
util
static unsigned virta2objnum (unsigned, SPAN_0(pe_section_t), unsigned)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes inherited from PeFile32
pe_header_t ih = {}
pe_header_t oh = {}
Protected Attributes inherited from PeFile
unsigned pe_offset
MemBuffer mb_oimport
unsigned soimport
byte * oimpdlls = nullptr
unsigned soimpdlls
ImportLinker * ilinker = nullptr
MemBuffer mb_orelocs
unsigned sorelocs
byte * oxrelocs = nullptr
unsigned soxrelocs
MemBuffer mb_oexport
unsigned soexport
MemBuffer mb_oresources
unsigned soresources
MemBuffer mb_otls
unsigned sotls
unsigned tlsindex
unsigned tlscb_ptr
unsigned tls_handler_offset = 0
bool use_tls_callbacks = false
MemBuffer mb_oloadconf
byte * oloadconf = nullptr
unsigned soloadconf
unsigned icondir_offset
int icondir_count
bool importbyordinal = false
bool kernel32ordinal = false
unsigned rvamin
unsigned cimports
unsigned crelocs
int big_relocs
ddirs_t * iddirs = nullptr
ddirs_t * oddirs = nullptr
MemBuffer mb_isection
bool isdll = false
bool isrtm = false
bool isefi = false
bool use_dep_hack = true
bool use_clear_dirty_stack = true
bool use_stub_relocs = true
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Detailed Description
win32/pe (i386)
Definition at line 34 of file p_w32pe_i386.h.
Member Typedef Documentation
super
typedef PeFile32 PackW32PeI386::super private
Definition at line 35 of file p_w32pe_i386.h.
Constructor & Destructor Documentation
PackW32PeI386()
static const CLANG_FORMAT_DUMMY_STATEMENT PackW32PeI386::PackW32PeI386 (InputFile * f) explicit
Definition at line 43 of file p_w32pe_i386.cpp.
: super(f) {}
~PackW32PeI386()
PackW32PeI386::~PackW32PeI386 () virtual noexcept
Definition at line 45 of file p_w32pe_i386.cpp.
{}
Member Function Documentation
addNewRelocations()
void PackW32PeI386::addNewRelocations (Reloc & rel, unsigned upxsection) override virtual
Reimplemented from PeFile.
Definition at line 236 of file p_w32pe_i386.cpp.
{
    if (use_stub_relocs)
        rel.add_reloc(upxsection + linker->getSymbolOffset("PESOCREL") + 1,
                      IMAGE_REL_BASED_HIGHLOW);
}
References PeFile::Reloc::add_reloc(), PeFile::IMAGE_REL_BASED_HIGHLOW, and PeFile::use_stub_relocs.
buildLoader()
void PackW32PeI386::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 87 of file p_w32pe_i386.cpp.
{
    // recompute tlsindex (see pack() below)
    unsigned tmp_tlsindex = tlsindex;
    const unsigned oam1 = ih.objectalign - 1;
    const unsigned newvsize = (ph.u_len + rvamin + ph.overlap_overhead + oam1) & ~oam1;
    if (tlsindex && ((newvsize - ph.c_len - 1024 + oam1) & ~oam1) > tlsindex + 4)
        tmp_tlsindex = 0;
    // prepare loader
    initLoader(stub_i386_win32_pe, sizeof(stub_i386_win32_pe), 2);
    if (isdll)
        addLoader("PEISDLL1");
    addLoader("PEMAIN01", use_stub_relocs ? "PESOCREL" : "PESOCPIC", "PESOUNC0",
              icondir_count > 1 ? (icondir_count == 2 ? "PEICONS1" : "PEICONS2") : "",
              tmp_tlsindex ? "PETLSHAK" : "", "PEMAIN02",
              ph.first_offset_found == 1 ? "PEMAIN03" : "", getDecompressorSections(),
              // multipass ? "PEMULTIP" : "",
              "PEMAIN10");
    addLoader(tmp_tlsindex ? "PETLSHAK2" : "");
    if (ft->id) {
        const unsigned texv = ih.codebase - rvamin;
        assert(ft->calls > 0);
        addLoader(texv ? "PECTTPOS" : "PECTTNUL");
        addFilter32(ft->id);
    }
    if (soimport)
        addLoader("PEIMPORT", importbyordinal ? "PEIBYORD" : "", kernel32ordinal ? "PEK32ORD" : "",
                  importbyordinal ? "PEIMORD1" : "", "PEIMPOR2", isdll ? "PEIERDLL" : "PEIEREXE",
                  "PEIMDONE");
    if (sorelocs) {
        addLoader(soimport == 0 || soimport + cimports != crelocs ? "PERELOC1" : "PERELOC2",
                  "PERELOC3,RELOC320", big_relocs ? "REL32BIG" : "", "RELOC32J");
        // FIXME: the following should be moved out of the above if
        addLoader(big_relocs & 6 ? "PERLOHI0" : "", big_relocs & 4 ? "PERELLO0" : "",
                  big_relocs & 2 ? "PERELHI0" : "");
    }
    if (use_dep_hack)
        addLoader("PEDEPHAK");
    // NEW: TLS callback support PART 1, the callback handler installation - Stefan Widmann
    if (use_tls_callbacks)
        addLoader("PETLSC");
    addLoader("PEMAIN20");
    if (use_clear_dirty_stack)
        addLoader("CLEARSTACK");
    addLoader("PEMAIN21");
    // NEW: last loader sections split up to insert TLS callback handler - Stefan Widmann
    addLoader(ih.entry || !ilinker ? "PEDOJUMP" : "PERETURN");
    // NEW: TLS callback support PART 2, the callback handler - Stefan Widmann
    if (use_tls_callbacks)
        addLoader("PETLSC2");
    addLoader("IDENTSTR,UPX1HEAD");
}
References Packer::addFilter32(), Packer::addLoader(), PeFile::big_relocs, PackHeader::c_len, Filter::calls, PeFile::cimports, PeFile32::pe_header_t::codebase, PeFile::crelocs, PeFile32::pe_header_t::entry, PackHeader::first_offset_found, Packer::getDecompressorSections(), PeFile::icondir_count, Filter::id, PeFile32::ih, PeFile::ilinker, PeFile::importbyordinal, Packer::initLoader(), PeFile::isdll, PeFile::kernel32ordinal, PeFile32::pe_header_t::objectalign, PackHeader::overlap_overhead, PackerBase::ph, PeFile::rvamin, PeFile::soimport, PeFile::sorelocs, stub_i386_win32_pe, PeFile::tlsindex, PackHeader::u_len, PeFile::use_clear_dirty_stack, PeFile::use_dep_hack, PeFile::use_stub_relocs, and PeFile::use_tls_callbacks.
canPack()
tribool PackW32PeI386::canPack () override virtual
pack
Implements PackerBase.
Definition at line 78 of file p_w32pe_i386.cpp.
{
    if (!readFileHeader())
        return false;
    checkMachine(ih.cpu);
    if (ih.cpu < IMAGE_FILE_MACHINE_I386 || ih.cpu > 0x150)
        return false;
    return true;
}
References PeFile::checkMachine(), PeFile32::pe_header_t::cpu, PeFile32::ih, PeFile::IMAGE_FILE_MACHINE_I386, and readFileHeader().
defineSymbols()
void PackW32PeI386::defineSymbols (unsigned ncsection, unsigned upxsection, unsigned sizeof_oh, unsigned isize_isplit, unsigned s1addr) override virtual
Implements PeFile.
Definition at line 158 of file p_w32pe_i386.cpp.
{
    const unsigned myimport = ncsection + soresources - rvamin;
    // patch loader
    linker->defineSymbol("original_entry", ih.entry);
    if (use_dep_hack) {
        // This works around a "protection" introduced in MSVCRT80, which
        // works like this:
        // When the compiler detects that it would link in some code from its
        // C runtime library which references some data in a read only
        // section then it compiles in a runtime check whether that data is
        // still in a read only section by looking at the pe header of the
        // file. If this check fails the runtime does "interesting" things
        // like not running the floating point initialization code - the result
        // is a R6002 runtime error.
        // These supposed to be read only addresses are covered by the sections
        // UPX0 & UPX1 in the compressed files, so we have to patch the PE header
        // in the memory. And the page on which the PE header is stored is read
        // only so we must make it rw, fix the flags (i.e. clear
        // IMAGE_SCN_MEM_WRITE of osection[x].flags), and make it ro again.
        // rva of the most significant byte of member "flags" in section "UPX0"
        const unsigned swri = pe_offset + sizeof_oh + sizeof(pe_section_t) - 1;
        // make sure we only touch the minimum number of pages
        const unsigned addr = 0u - rvamin + swri;
        linker->defineSymbol("swri", addr & 0xfff); // page offset
        // check whether osection[0].flags and osection[1].flags
        // are on the same page
        linker->defineSymbol(
            "vp_size", ((addr & 0xfff) + 0x28 >= 0x1000) ? 0x2000 : 0x1000); // 2 pages or 1 page
        linker->defineSymbol("vp_base", addr & ~0xfff);                      // page mask
        linker->defineSymbol("VirtualProtect",
                             0u - rvamin + ilinkerGetAddress("kernel32.dll", "VirtualProtect"));
    }
    linker->defineSymbol("reloc_delt", 0u - (unsigned) ih.imagebase - rvamin);
    linker->defineSymbol("start_of_relocs", crelocs);
    if (ilinker) {
        if (!isdll)
            linker->defineSymbol("ExitProcess",
                                 0u - rvamin + ilinkerGetAddress("kernel32.dll", "ExitProcess"));
        linker->defineSymbol("GetProcAddress",
                             0u - rvamin + ilinkerGetAddress("kernel32.dll", "GetProcAddress"));
        linker->defineSymbol("kernel32_ordinals", myimport);
        linker->defineSymbol("LoadLibraryA",
                             0u - rvamin + ilinkerGetAddress("kernel32.dll", "LoadLibraryA"));
        linker->defineSymbol("start_of_imports", myimport);
        linker->defineSymbol("compressed_imports", cimports);
    }
    defineDecompressorSymbols();
    linker->defineSymbol("filter_buffer_start", ih.codebase - rvamin);
    // in case of overlapping decompression, this hack is needed,
    // because windoze zeroes the word pointed by tlsindex before
    // it starts programs
    linker->defineSymbol("tls_value",
                         (tlsindex + 4 > s1addr) ? get_le32(obuf + tlsindex - s1addr - ic) : 0);
    linker->defineSymbol("tls_address", tlsindex - rvamin);
    linker->defineSymbol("icon_delta", icondir_count - 1);
    linker->defineSymbol("icon_offset", ncsection + icondir_offset - rvamin);
    const unsigned esi0 = s1addr + ic;
    linker->defineSymbol("start_of_uncompressed", 0u - esi0 + rvamin);
    linker->defineSymbol("start_of_compressed", use_stub_relocs ? esi0 + ih.imagebase : esi0);
    if (use_tls_callbacks) {
        // esi is ih.imagebase + rvamin
        linker->defineSymbol("tls_callbacks_ptr", tlscb_ptr);
        linker->defineSymbol("tls_module_base", 0u - rvamin);
    }
    linker->defineSymbol(isdll ? "PEISDLL1" : "PEMAIN01", upxsection);
    // linker->dumpSymbols();
}
References PeFile::cimports, PeFile32::pe_header_t::codebase, PeFile::crelocs, Packer::defineDecompressorSymbols(), PeFile32::pe_header_t::entry, get_le32(), PeFile::icondir_count, PeFile::icondir_offset, PeFile32::ih, PeFile::ilinker, PeFile::ilinkerGetAddress(), PeFile32::pe_header_t::imagebase, PeFile::isdll, Packer::obuf, PeFile::pe_offset, PeFile::rvamin, PeFile::soresources, PeFile::tlscb_ptr, PeFile::tlsindex, PeFile::use_dep_hack, PeFile::use_stub_relocs, and PeFile::use_tls_callbacks.
getCompressionMethods()
const int * PackW32PeI386::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 47 of file p_w32pe_i386.cpp.
{
    bool small = ih.codesize + ih.datasize <= 256 * 1024;
    return Packer::getDefaultCompressionMethods_le32(method, level, small);
}
References PeFile32::pe_header_t::codesize, PeFile32::pe_header_t::datasize, Packer::getDefaultCompressionMethods_le32(), and PeFile32::ih.
getFilters()
const int * PackW32PeI386::getFilters () const override virtual
Implements PackerBase.
Definition at line 52 of file p_w32pe_i386.cpp.
{
    static const int filters[] = {0x26, 0x24,           0x49, 0x46, 0x16, 0x13,  0x14,
                                  0x11, FT_ULTRA_BRUTE, 0x25, 0x15, 0x12, FT_END};
    return filters;
}
References FT_END, and FT_ULTRA_BRUTE.
getFormat()
virtual int PackW32PeI386::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 40 of file p_w32pe_i386.h.
{ return UPX_F_W32PE_I386; }
References UPX_F_W32PE_I386.
getFullName()
virtual const char * PackW32PeI386::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 42 of file p_w32pe_i386.h.
{ return "i386-win32.pe"; }
getName()
virtual const char * PackW32PeI386::getName () const inline override virtual
Implements PackerBase.
Definition at line 41 of file p_w32pe_i386.h.
{ return isrtm ? "rtm32/pe" : "win32/pe"; }
References PeFile::isrtm.
needForceOption()
bool PackW32PeI386::needForceOption () const override virtual
Implements PeFile.
Definition at line 144 of file p_w32pe_i386.cpp.
{
    // return true if we need `--force` to pack this file
    bool r = false;
    r |= (ih.opthdrsize != 0xe0);
    r |= ((ih.flags & IMAGE_FILE_EXECUTABLE_IMAGE) == 0);
    r |= ((ih.flags & IMAGE_FILE_32BIT_MACHINE) == 0); // 32 bit machine flag must be set
    r |= (ih.coffmagic != 0x10b);                      // COFF magic is 0x10B in PE files
    r |= (ih.entry == 0 && !isdll);
    r |= (ih.ddirsentries != 16);
    r |= (IDSIZE(PEDIR_EXCEPTION) != 0); // is this used on i386?
    return r;
}
References PeFile32::pe_header_t::coffmagic, PeFile32::pe_header_t::ddirsentries, PeFile32::pe_header_t::entry, PeFile32::pe_header_t::flags, PeFile::IDSIZE(), PeFile32::ih, PeFile::IMAGE_FILE_32BIT_MACHINE, PeFile::IMAGE_FILE_EXECUTABLE_IMAGE, PeFile::isdll, PeFile32::pe_header_t::opthdrsize, and PeFile::PEDIR_EXCEPTION.
newLinker()
Linker * PackW32PeI386::newLinker () const override protected virtual
Implements Packer.
Definition at line 58 of file p_w32pe_i386.cpp.
{ return new ElfLinkerX86; }
pack()
void PackW32PeI386::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 250 of file p_w32pe_i386.cpp.
{
    unsigned mask = (1u << IMAGE_SUBSYSTEM_WINDOWS_GUI) | (1u << IMAGE_SUBSYSTEM_WINDOWS_CUI) |
                    (1u << IMAGE_SUBSYSTEM_EFI_APPLICATION) |
                    (1u << IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER) |
                    (1u << IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER) | (1u << IMAGE_SUBSYSTEM_EFI_ROM);
    super::pack0(fo, mask, 0x400000, false);
}
References PeFile::IMAGE_SUBSYSTEM_EFI_APPLICATION, PeFile::IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER, PeFile::IMAGE_SUBSYSTEM_EFI_ROM, PeFile::IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER, PeFile::IMAGE_SUBSYSTEM_WINDOWS_CUI, PeFile::IMAGE_SUBSYSTEM_WINDOWS_GUI, and PeFile32::pack0().
readFileHeader()
int PackW32PeI386::readFileHeader () override protected virtual
util
Reimplemented from PeFile.
Definition at line 64 of file p_w32pe_i386.cpp.
{
    if (file_size >= 0x206) {
        byte buf[6];
        fi->seek(0x200, SEEK_SET);
        fi->readx(buf, 6);
        isrtm = memcmp(buf, "32STUB", 6) == 0;
    }
    return super::readFileHeader();
}
References buf, PackerBase::fi, PackerBase::file_size, PeFile::isrtm, memcmp(), PeFile::readFileHeader(), InputFile::readx(), InputFile::seek(), and SEEK_SET.
Referenced by canPack().
setOhDataBase()
void PackW32PeI386::setOhDataBase (const pe_section_t * osection) override virtual
Implements PeFile.
Definition at line 242 of file p_w32pe_i386.cpp.
{ oh.database = osection[2].vaddr; }
References PeFile32::pe_header_t::database, PeFile32::oh, and PeFile::pe_section_t::vaddr.
setOhHeaderSize()
void PackW32PeI386::setOhHeaderSize (const pe_section_t * osection) override virtual
Implements PeFile.
Definition at line 244 of file p_w32pe_i386.cpp.
{
    // SizeOfHeaders
    oh.headersize =
        ALIGN_UP(pe_offset + usizeof(oh) + usizeof(*osection) * oh.objects, oh.filealign);
}
References ALIGN_UP, PeFile32::pe_header_t::filealign, PeFile32::pe_header_t::headersize, PeFile32::pe_header_t::objects, PeFile32::oh, PeFile::pe_offset, and usizeof.
The documentation for this class was generated from the following files:
src/p_w32pe_i386.h
src/p_w32pe_i386.cpp