My Project: PackExe Class Reference
PackExe Class Reference final
dos/exe
#include <p_exe.h>
Classes
struct exe_header_t
Public Member Functions
PackExe (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
virtual bool canUnpackVersion (int version) const override
virtual bool canUnpackFormat (int format) const override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Types
enum {
NORELOC = 1 , USEJUMP = 2 , SS = 4 , SP = 8 ,
MINMEM = 16 , MAXMEM = 32
}
Protected Member Functions
int readFileHeader (void)
int fillExeHeader (struct exe_header_t *) const
virtual void buildLoader (const Filter *ft) override
virtual Linker * newLinker () const override
void addLoaderEpilogue (int flag)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
exe_header_t ih = {}
exe_header_t oh = {}
unsigned ih_exesize = 0
unsigned ih_imagesize = 0
unsigned ih_overlay = 0
unsigned relocsize = 0
bool has_9a = false
bool device_driver = false
unsigned stack_for_lzma = 0
bool use_clear_dirty_stack = false
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
dos/exe
Definition at line 34 of file p_exe.h.
Member Typedef Documentation
super
typedef Packer PackExe::super private
Definition at line 35 of file p_exe.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
NORELOC
USEJUMP
SS
SP
MINMEM
MAXMEM
Definition at line 99 of file p_exe.h.
{ NORELOC = 1, USEJUMP = 2, SS = 4, SP = 8, MINMEM = 16, MAXMEM = 32 };
Constructor & Destructor Documentation
PackExe()
PackExe::PackExe (InputFile * f) explicit
Definition at line 47 of file p_exe.cpp.
                             : super(f) {
    bele = &N_BELE_RTP::le_policy;
    COMPILE_TIME_ASSERT(sizeof(exe_header_t) == 32)
    COMPILE_TIME_ASSERT_ALIGNED1(exe_header_t)
}
References Packer::bele, COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, and N_BELE_RTP::le_policy.
Member Function Documentation
addLoaderEpilogue()
void PackExe::addLoaderEpilogue (int flag) protected
Definition at line 105 of file p_exe.cpp.
{
    addLoader("EXEMAIN5");
    if (relocsize)
        addLoader(ph.u_len <= DI_LIMIT || (ph.u_len & 0x7fff) >= relocsize ? "EXENOADJ"
                                                                           : "EXEADJUS",
                  "EXERELO1", has_9a ? "EXEREL9A" : "", "EXERELO2",
                  ih_exesize > 0xFE00 ? "EXEREBIG" : "", "EXERELO3");
    addLoader("EXEMAIN8", device_driver ? "DEVICEEND" : "", (flag & SS) ? "EXESTACK" : "",
              (flag & SP) ? "EXESTASP" : "", (flag & USEJUMP) ? "EXEJUMPF" : "");
    if (!(flag & USEJUMP))
        addLoader(ih.cs ? "EXERCSPO" : "", "EXERETIP");
    linker->defineSymbol("original_cs", ih.cs);
    linker->defineSymbol("original_ip", ih.ip);
    linker->defineSymbol("original_sp", ih.sp);
    linker->defineSymbol("original_ss", ih.ss);
    linker->defineSymbol(
        "reloc_size",
        (ph.u_len <= DI_LIMIT || (ph.u_len & 0x7fff) >= relocsize ? 0 : MAXRELOCSIZE) - relocsize);
}
References Packer::addLoader(), PackExe::exe_header_t::cs, device_driver, DI_LIMIT, has_9a, ih, ih_exesize, PackExe::exe_header_t::ip, MAXRELOCSIZE, PackerBase::ph, relocsize, PackExe::exe_header_t::sp, SP, PackExe::exe_header_t::ss, SS, PackHeader::u_len, and USEJUMP.
Referenced by buildLoader().
buildLoader()
void PackExe::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 126 of file p_exe.cpp.
{
    // get flag
    exe_header_t dummy_oh;
    int flag = fillExeHeader(&dummy_oh);
    initLoader(stub_i086_dos16_exe, sizeof(stub_i086_dos16_exe));
    if (M_IS_LZMA(ph.method)) {
        addLoader("LZMA_DEC00", opt->small ? "LZMA_DEC10" : "LZMA_DEC20", "LZMA_DEC30",
                  use_clear_dirty_stack ? "LZMA_DEC31" : "", "LZMA_DEC32",
                  ph.u_len > 0xffff ? "LZMA_DEC33" : "");
        addLoaderEpilogue(flag);
        defineDecompressorSymbols();
        const unsigned lsize0 = getLoaderSize();
        // Lzma decompression code starts at ss:0x10, and its size is
        // lsize bytes. It also needs getDecompressorWrkmemSize() bytes
        // during uncompression. It also uses some stack, so 0x100
        // more bytes are allocated
        stack_for_lzma = 0x10 + lsize0 + getDecompressorWrkmemSize() + 0x100;
        stack_for_lzma = ALIGN_UP(stack_for_lzma, 16u);
        unsigned clear_dirty_stack_low = 0x10 + lsize0;
        clear_dirty_stack_low = ALIGN_UP(clear_dirty_stack_low, 2u);
        if (use_clear_dirty_stack)
            linker->defineSymbol("clear_dirty_stack_low", clear_dirty_stack_low);
        relocateLoader();
        const unsigned lsize = getLoaderSize();
        assert(lsize0 == lsize);
        MemBuffer loader(lsize);
        memcpy(loader, getLoader(), lsize);
        MemBuffer compressed_lzma;
        compressed_lzma.allocForCompression(lsize);
        unsigned c_len_lzma = MemBuffer::getSizeForCompression(lsize);
        int r = upx_compress(loader, lsize, compressed_lzma, &c_len_lzma, nullptr, M_NRV2B_LE16, 9,
                             nullptr, nullptr);
        assert(r == UPX_E_OK);
        assert(c_len_lzma < lsize);
        info("lzma+relocator code compressed: %u -> %u", lsize, c_len_lzma);
        // reinit the loader
        initLoader(stub_i086_dos16_exe, sizeof(stub_i086_dos16_exe));
        // prepare loader
        if (device_driver)
            addLoader("DEVICEENTRY,LZMADEVICE,DEVICEENTRY2");
        linker->addSection("COMPRESSED_LZMA", compressed_lzma, c_len_lzma, 0);
        addLoader("LZMAENTRY,NRV2B160,NRVDDONE,NRVDECO1,NRVGTD00,NRVDECO2");
    } else if (device_driver)
        addLoader("DEVICEENTRY,DEVICEENTRY2");
    addLoader("EXEENTRY", M_IS_LZMA(ph.method) && device_driver ? "LONGSUB" : "SHORTSUB",
              "JNCDOCOPY", relocsize ? "EXERELPU" : "", "EXEMAIN4",
              M_IS_LZMA(ph.method) ? "" : "EXEMAIN4B", "EXEMAIN4C",
              M_IS_LZMA(ph.method) ? "COMPRESSED_LZMA_START,COMPRESSED_LZMA" : "",
              "+G5DXXXX,UPX1HEAD,EXECUTPO");
    if (ph.method == M_NRV2B_8)
        addLoader("NRV2B16S", // decompressor
                  ph.u_len > DI_LIMIT ? "N2B64K01" : "", "NRV2BEX1",
                  opt->cpu_x86 == opt->CPU_8086 ? "N2BX8601" : "N2B28601", "NRV2BEX2",
                  opt->cpu_x86 == opt->CPU_8086 ? "N2BX8602" : "N2B28602", "NRV2BEX3",
                  ph.c_len > 0xffff ? "N2B64K02" : "", "NRV2BEX9");
    else if (ph.method == M_NRV2D_8)
        addLoader("NRV2D16S", ph.u_len > DI_LIMIT ? "N2D64K01" : "", "NRV2DEX1",
                  opt->cpu_x86 == opt->CPU_8086 ? "N2DX8601" : "N2D28601", "NRV2DEX2",
                  opt->cpu_x86 == opt->CPU_8086 ? "N2DX8602" : "N2D28602", "NRV2DEX3",
                  ph.c_len > 0xffff ? "N2D64K02" : "", "NRV2DEX9");
    else if (ph.method == M_NRV2E_8)
        addLoader("NRV2E16S", ph.u_len > DI_LIMIT ? "N2E64K01" : "", "NRV2EEX1",
                  opt->cpu_x86 == opt->CPU_8086 ? "N2EX8601" : "N2E28601", "NRV2EEX2",
                  opt->cpu_x86 == opt->CPU_8086 ? "N2EX8602" : "N2E28602", "NRV2EEX3",
                  ph.c_len > 0xffff ? "N2E64K02" : "", "NRV2EEX9");
    else if M_IS_LZMA (ph.method)
        return;
    else
        throwInternalError("unknown compression method");
    addLoaderEpilogue(flag);
}
References Packer::addLoader(), addLoaderEpilogue(), ALIGN_UP, MemBuffer::allocForCompression(), PackHeader::c_len, Packer::defineDecompressorSymbols(), device_driver, DI_LIMIT, fillExeHeader(), Packer::getDecompressorWrkmemSize(), Packer::getLoader(), Packer::getLoaderSize(), MemBuffer::getSizeForCompression(), info(), Packer::initLoader(), M_IS_LZMA, M_NRV2B_8, M_NRV2B_LE16, M_NRV2D_8, M_NRV2E_8, memcpy(), PackHeader::method, opt, PackerBase::ph, Packer::relocateLoader(), relocsize, stack_for_lzma, stub_i086_dos16_exe, throwInternalError(), PackHeader::u_len, upx_compress(), UPX_E_OK, and use_clear_dirty_stack.
canPack()
tribool PackExe::canPack () override virtual
Implements PackerBase.
Definition at line 232 of file p_exe.cpp.
{
    if (fn_has_ext(fi->getName(), "sys")) // dos/sys
        return false;
    if (!readFileHeader())
        return false;
    if (file_size < 1024 || ih_imagesize < 512)
        throwCantPack("file is too small for dos/exe");
    fi->seek(0x3c, SEEK_SET);
    LE32 offs;
    fi->readx(&offs, sizeof(offs));
    if (ih.relocoffs >= 0x40 && offs) {
        if (opt->dos_exe.force_stub)
            opt->overlay = opt->COPY_OVERLAY;
        else
            throwCantPack("dos/exe: can't pack new-exe");
    }
    return true;
}
References PackerBase::fi, PackerBase::file_size, fn_has_ext(), FileBase::getName(), ih, ih_imagesize, opt, readFileHeader(), InputFile::readx(), PackExe::exe_header_t::relocoffs, InputFile::seek(), SEEK_SET, and throwCantPack().
canUnpack()
tribool PackExe::canUnpack () override virtual
Implements PackerBase.
Definition at line 575 of file p_exe.cpp.
{
    if (!readFileHeader())
        return false;
    const unsigned off = ih.headsize16 * 16;
    fi->seek(off, SEEK_SET);
    bool b = readPackHeader(4096);
    return b && (off + ph.c_len <= file_size_u);
}
References b, PackHeader::c_len, PackerBase::fi, PackerBase::file_size_u, PackExe::exe_header_t::headsize16, ih, PackerBase::ph, readFileHeader(), Packer::readPackHeader(), InputFile::seek(), and SEEK_SET.
canUnpackFormat()
virtual bool PackExe::canUnpackFormat (int format) const inline override virtual
Reimplemented from Packer.
Definition at line 57 of file p_exe.h.
{
        return (format == UPX_F_DOS_EXE || format == UPX_F_DOS_EXEH);
    }
References UPX_F_DOS_EXE, and UPX_F_DOS_EXEH.
canUnpackVersion()
virtual bool PackExe::canUnpackVersion (int version) const inline override virtual
Reimplemented from Packer.
Definition at line 53 of file p_exe.h.
{
        // NOTE: could adapt p_exe.cpp to support (version >= 8)
        return (version >= 10);
    }
fillExeHeader()
int PackExe::fillExeHeader (struct exe_header_t * eh) const protected
Definition at line 66 of file p_exe.cpp.
{
#define oh (*eh)
    // fill new exe header
    int flag = 0;
    if (!opt->dos_exe.no_reloc && !M_IS_LZMA(ph.method))
        flag |= USEJUMP;
    if (ih.relocs == 0)
        flag |= NORELOC;
    mem_clear(&oh);
    oh.ident = 'M' + 'Z' * 256;
    oh.headsize16 = 2;
    unsigned minsp = 0x200;
    if (M_IS_LZMA(ph.method))
        minsp = stack_for_lzma;
    minsp = ALIGN_UP(minsp, 16u);
    assert(minsp < 0xff00);
    if (oh.sp > minsp)
        minsp = oh.sp;
    if (minsp < 0xff00 - 2)
        minsp = ALIGN_UP(minsp, 2u);
    oh.sp = minsp;
    unsigned destpara = (ph.u_len + ph.overlap_overhead - ph.c_len + 31) / 16;
    oh.ss = ph.c_len / 16 + destpara;
    if (ih.ss * 16 + ih.sp < 0x100000 && ih.ss > oh.ss && ih.sp > 0x200)
        oh.ss = ih.ss;
    if (oh.ss * 16 + 0x50 < ih.ss * 16 + ih.sp && oh.ss * 16 + 0x200 > ih.ss * 16 + ih.sp)
        oh.ss += 0x20;
    if (oh.ss != ih.ss)
        flag |= SS;
    if (oh.sp != ih.sp || M_IS_LZMA(ph.method))
        flag |= SP;
    return flag;
#undef oh
}
References ALIGN_UP, PackHeader::c_len, PackExe::exe_header_t::headsize16, PackExe::exe_header_t::ident, ih, M_IS_LZMA, mem_clear(), PackHeader::method, NORELOC, oh, opt, PackHeader::overlap_overhead, PackerBase::ph, PackExe::exe_header_t::relocs, PackExe::exe_header_t::sp, SP, PackExe::exe_header_t::ss, SS, stack_for_lzma, PackHeader::u_len, and USEJUMP.
Referenced by buildLoader(), and pack().
getCompressionMethods()
const int * PackExe::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 55 of file p_exe.cpp.
{
    bool small = ih_imagesize <= 256 * 1024;
    // disable lzma for "--brute" unless explicitly given "--lzma"
    // (note that class PackMaster creates per-file local options)
    if (opt->all_methods_use_lzma == 1 && !opt->method_lzma_seen)
        opt->all_methods_use_lzma = 0;
    return Packer::getDefaultCompressionMethods_8(method, level, small);
}
References Packer::getDefaultCompressionMethods_8(), ih_imagesize, and opt.
getFilters()
const int * PackExe::getFilters () const override virtual
Implements PackerBase.
Definition at line 64 of file p_exe.cpp.
{ return nullptr; }
getFormat()
virtual int PackExe::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 40 of file p_exe.h.
{ return UPX_F_DOS_EXE; }
References UPX_F_DOS_EXE.
getFullName()
virtual const char * PackExe::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 42 of file p_exe.h.
{ return "i086-dos16.exe"; }
getName()
virtual const char * PackExe::getName () const inline override virtual
Implements PackerBase.
Definition at line 41 of file p_exe.h.
{ return "dos/exe"; }
Referenced by pack().
getVersion()
virtual int PackExe::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 39 of file p_exe.h.
{ return 13; }
newLinker()
Linker * PackExe::newLinker () const override protected virtual
Implements Packer.
Definition at line 53 of file p_exe.cpp.
{ return new ElfLinkerX86(); }
pack()
void PackExe::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 369 of file p_exe.cpp.
{
    unsigned ic;
    const unsigned relocnum = ih.relocs;
    if (relocnum > MAXRELOCSIZE) // early check
        throwCantPack("too many relocations");
    checkOverlay(ih_overlay);
    // read image
    // image + space for optimized relocs + safety/alignments
    ibuf.alloc(ih_imagesize + 4 * relocnum + 1024);
    fi->seek(ih.headsize16 * 16, SEEK_SET);
    fi->readx(ibuf, ih_imagesize);
    checkAlreadyPacked(ibuf, UPX_MIN(ih_imagesize, 127u));
    device_driver = get_le32(ibuf) == 0xffffffffu;
    // relocations
    relocsize = 0;
    has_9a = false;
    if (relocnum) {
        MemBuffer mb_relocs(4 * relocnum);
        SPAN_S_VAR(byte, relocs, mb_relocs);
        fi->seek(ih.relocoffs, SEEK_SET);
        fi->readx(relocs, 4 * relocnum);
        // dos/exe runs in real-mode, so convert to linear addresses
        for (ic = 0; ic < relocnum; ic++) {
            unsigned jc = get_le32(relocs + 4 * ic);
            set_le32(relocs + 4 * ic, ((jc >> 16) * 16 + (jc & 0xffff)) & 0xfffff);
        }
        upx_qsort(raw_bytes(relocs, 4 * relocnum), relocnum, 4, le32_compare);
        SPAN_S_VAR(byte, image, ibuf + 0, ih_imagesize);
        SPAN_S_VAR(byte, crel, ibuf + ih_imagesize, ibuf);
        relocsize = optimize_relocs(image, ih_imagesize, relocs, relocnum, crel, &has_9a);
        set_le16(crel + relocsize, relocsize + 2);
        relocsize += 2;
        assert(relocsize >= 11);
        if (relocsize > MAXRELOCSIZE) // optimize_relocs did not help
            throwCantPack("too many relocations");
#if TESTING && 0
        unsigned rout_len = MemBuffer::getSizeForCompression(relocsize);
        MemBuffer rout(rout_len);
        ucl_nrv2b_99_compress(raw_bytes(crel, relocsize), relocsize, rout, &rout_len, nullptr, 9,
                              nullptr, nullptr);
        printf("dos/exe reloc compress: %d -> %d\n", relocsize, rout_len);
#endif
    }
    // prepare packheader
    ph.u_len = ih_imagesize + relocsize;
    obuf.allocForCompression(ph.u_len);
    // prepare filter
    Filter ft(ph.level);
    // compress (max_match = 8192)
    upx_compress_config_t cconf;
    cconf.reset();
    cconf.conf_ucl.max_match = MAXMATCH;
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    compressWithFilters(&ft, 32, &cconf);
    if (M_IS_NRV2B(ph.method) || M_IS_NRV2D(ph.method) || M_IS_NRV2E(ph.method))
        if (ph.max_run_found + ph.max_match_found > 0x8000)
            throwCantPack("decompressor limit exceeded, send a bugreport");
#if TESTING
    if (opt->debug.debug_level) {
        printf("image+relocs %d -> %d\n", ih_imagesize + relocsize, ph.c_len);
        printf("offsets: %d - %d\nmatches: %d - %d\nruns: %d - %d\n", 0 /*ph.min_offset_found*/,
               ph.max_offset_found, 0 /*ph.min_match_found*/, ph.max_match_found,
               0 /*ph.min_run_found*/, ph.max_run_found);
    }
#endif
    int flag = fillExeHeader(&oh);
    const unsigned lsize = getLoaderSize();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    // OutputFile::dump("xxloader.dat", loader, lsize);
    // patch loader
    const unsigned packedsize = ph.c_len;
    const unsigned e_len = getLoaderSectionStart("EXECUTPO");
    const unsigned d_len = lsize - e_len;
    assert((e_len & 15) == 0);
    const unsigned copysize = (1 + packedsize + d_len) & ~1;
    const unsigned firstcopy = copysize % 0x10000 ? copysize % 0x10000 : 0x10000;
    // set oh.min & oh.max
    ic = ih.min * 16 + ih_imagesize;
    if (ic < oh.ss * 16u + oh.sp)
        ic = oh.ss * 16u + oh.sp;
    oh.min = (ic - (packedsize + lsize)) / 16;
    ic = oh.min + (ih.max - ih.min);
    oh.max = ic < 0xffff && ih.max != 0xffff ? ic : 0xffff;
    // set extra info
    byte extra_info[9];
    unsigned eisize = 0;
    if (oh.ss != ih.ss) {
        set_le16(extra_info + eisize, ih.ss);
        eisize += 2;
        assert((flag & SS) != 0); // set in fillExeHeader()
    }
    if (oh.sp != ih.sp) {
        set_le16(extra_info + eisize, ih.sp);
        eisize += 2;
        assert((flag & SP) != 0); // set in fillExeHeader()
    }
    if (ih.min != oh.min) {
        set_le16(extra_info + eisize, ih.min);
        eisize += 2;
        flag |= MINMEM;
    }
    if (ih.max != oh.max) {
        set_le16(extra_info + eisize, ih.max);
        eisize += 2;
        flag |= MAXMEM;
    }
    extra_info[eisize++] = (byte) flag;
    if (M_IS_NRV2B(ph.method) || M_IS_NRV2D(ph.method) || M_IS_NRV2E(ph.method))
        linker->defineSymbol("bx_magic", 0x7FFF + 0x10 * ((packedsize & 15) + 1));
    unsigned decompressor_entry = 1 + (packedsize & 15);
    if (M_IS_LZMA(ph.method))
        decompressor_entry = 0x10;
    linker->defineSymbol("decompressor_entry", decompressor_entry);
    // patch loader
    if (flag & USEJUMP) {
        // I use a relocation entry to set the original cs
        unsigned n = getLoaderSectionStart("EXEJUMPF") + 1;
        n += packedsize + 2;
        oh.relocs = 1;
        oh.firstreloc = (n & 0xf) + ((n >> 4) << 16);
    } else {
        oh.relocs = 0;
        oh.firstreloc = ih.cs * 0x10000 + ih.ip;
    }
    oh.relocoffs = offsetof(exe_header_t, firstreloc);
    linker->defineSymbol("destination_segment", oh.ss - ph.c_len / 16 - e_len / 16);
    linker->defineSymbol("source_segment", e_len / 16 + (copysize - firstcopy) / 16);
    linker->defineSymbol("copy_offset", firstcopy - 2);
    linker->defineSymbol("words_to_copy", firstcopy / 2);
    linker->defineSymbol("exe_stack_sp", oh.sp);
    linker->defineSymbol("exe_stack_ss", oh.ss);
    linker->defineSymbol("interrupt", get_le16(ibuf + 8));
    linker->defineSymbol("attribute", get_le16(ibuf + 4));
    linker->defineSymbol("orig_strategy", get_le16(ibuf + 6));
    const unsigned outputlen = sizeof(oh) + e_len + packedsize + d_len + eisize;
    oh.m512 = outputlen & 511;
    oh.p512 = (outputlen + 511) >> 9;
    const char *exeentry = M_IS_LZMA(ph.method) ? "LZMAENTRY" : "EXEENTRY";
    oh.ip = device_driver ? getLoaderSection(exeentry) - 2 : 0;
    defineDecompressorSymbols();
    relocateLoader();
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, e_len);
    NO_fprintf(stderr, "\ne_len=%x d_len=%x c_len=%x oo=%x ulen=%x copysize=%x imagesize=%x", e_len,
               d_len, packedsize, ph.overlap_overhead, ph.u_len, copysize, ih_imagesize);
    // write header + write loader + compressed file
#if TESTING
    if (opt->debug.debug_level)
        printf("\n%d %d %d %d\n", (int) sizeof(oh), e_len, packedsize, d_len);
#endif
    fo->write(&oh, sizeof(oh));       // program header
    fo->write(loader, e_len);         // entry code
    fo->write(obuf, packedsize);      // compressed data
    fo->write(loader + e_len, d_len); // decompressor code
    fo->write(extra_info, eisize);    // extra info for unpacking
    assert(eisize <= 9);
    NO_printf("%-13s: program hdr  : %8u bytes\n", getName(), usizeof(oh));
    NO_printf("%-13s: entry        : %8u bytes\n", getName(), e_len);
    NO_printf("%-13s: compressed   : %8u bytes\n", getName(), packedsize);
    NO_printf("%-13s: decompressor : %8u bytes\n", getName(), d_len);
    NO_printf("%-13s: extra info   : %8u bytes\n", getName(), eisize);
    // verify
    verifyOverlappingDecompression();
    // copy the overlay
    copyOverlay(fo, ih_overlay, obuf);
    NO_fprintf(stderr, "dos/exe %x %x\n", relocsize, ph.u_len);
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References MemBuffer::alloc(), MemBuffer::allocForCompression(), PackHeader::c_len, Packer::checkAlreadyPacked(), Packer::checkFinalCompressionRatio(), Packer::checkOverlay(), Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, upx_compress_config_t::conf_ucl, Packer::copyOverlay(), PackExe::exe_header_t::cs, Packer::defineDecompressorSymbols(), device_driver, PackerBase::fi, fillExeHeader(), PackExe::exe_header_t::firstreloc, get_le16(), get_le32(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), getName(), MemBuffer::getSizeForCompression(), has_9a, PackExe::exe_header_t::headsize16, Packer::ibuf, ih, ih_imagesize, ih_overlay, PackExe::exe_header_t::ip, le32_compare(), PackHeader::level, PackExe::exe_header_t::m512, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, PackExe::exe_header_t::max, PackHeader::max_match_found, lzma_compress_config_t::max_num_probs, PackHeader::max_offset_found, PackHeader::max_run_found, MAXMATCH, MAXMEM, MAXRELOCSIZE, memcpy(), PackHeader::method, PackExe::exe_header_t::min, MINMEM, n, NO_fprintf(), NO_printf(), Packer::obuf, oh, opt, optimize_relocs(), PackHeader::overlap_overhead, PackExe::exe_header_t::p512, Packer::patchPackHeader(), PackerBase::ph, raw_bytes(), InputFile::readx(), Packer::relocateLoader(), PackExe::exe_header_t::relocoffs, PackExe::exe_header_t::relocs, relocsize, upx_compress_config_t::reset(), InputFile::seek(), SEEK_SET, set_le16(), set_le32(), PackExe::exe_header_t::sp, SP, SPAN_S_VAR, PackExe::exe_header_t::ss, SS, throwCantPack(), throwNotCompressible(), PackHeader::u_len, UPX_MIN, upx_qsort, USEJUMP, usizeof, Packer::verifyOverlappingDecompression(), and OutputFile::write().
readFileHeader()
int PackExe::readFileHeader (void) protected
Definition at line 214 of file p_exe.cpp.
{
    ih_exesize = ih_imagesize = ih_overlay = 0;
    fi->readx(&ih, sizeof(ih));
    if (ih.ident != 'M' + 'Z' * 256 && ih.ident != 'Z' + 'M' * 256)
        return 0;
    ih_exesize = ih.m512 + ih.p512 * 512 - (ih.m512 ? 512 : 0);
    if (ih_exesize == 0)
        ih_exesize = file_size;
    ih_imagesize = ih_exesize - ih.headsize16 * 16;
    ih_overlay = file_size - ih_exesize;
    if (file_size_u < sizeof(ih) || ((ih.m512 | ih.p512) && ih.m512 + ih.p512 * 512u < sizeof(ih)))
        throwCantPack("illegal exe header");
    if (ih_exesize > file_size_u || ih_imagesize < 4 || ih_imagesize > ih_exesize)
        throwCantPack("exe header corrupted");
    NO_printf("dos/exe header: %d %d %d\n", ih_exesize, ih_imagesize, ih_overlay);
    return UPX_F_DOS_EXE;
}
References PackerBase::fi, PackerBase::file_size, PackerBase::file_size_u, PackExe::exe_header_t::headsize16, PackExe::exe_header_t::ident, ih, ih_exesize, ih_imagesize, ih_overlay, PackExe::exe_header_t::m512, NO_printf(), PackExe::exe_header_t::p512, InputFile::readx(), throwCantPack(), and UPX_F_DOS_EXE.
Referenced by canPack(), and canUnpack().
unpack()
void PackExe::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 588 of file p_exe.cpp.
{
    ibuf.alloc(file_size);
    obuf.allocForDecompression(ph.u_len);
    // read the file
    fi->seek(ih.headsize16 * 16, SEEK_SET);
    fi->readx(ibuf, ih_imagesize);
    // get compressed data offset
    unsigned e_len = ph.buf_offset + ph.getPackHeaderSize();
    if (ih_imagesize <= e_len + ph.c_len)
        throwCantUnpack("file damaged");
    checkOverlay(ih_overlay);
    // decompress
    decompress(ibuf + e_len, obuf);
    unsigned imagesize = ih_imagesize;
    imagesize -= 1;
    const byte flag = ibuf[imagesize];
    // relocations
    unsigned relocnum = 0;
    SPAN_S_VAR(const byte, relocstart, obuf + ph.u_len, obuf);
    MemBuffer mb_relocs;
    SPAN_0_VAR(byte, relocs, nullptr);
    if (!(flag & NORELOC)) {
        mb_relocs.alloc(4 * MAXRELOCSIZE);
        relocs = mb_relocs; // => now a SPAN_S
        relocsize = get_le16(obuf + ph.u_len - 2);
        ph.u_len -= 2;
        if (relocsize < 11 || relocsize > MAXRELOCSIZE || relocsize >= imagesize)
            throwCantUnpack("bad relocations");
        relocstart -= relocsize;
        // unoptimize_relocs
        unsigned ones = get_le16(relocstart);
        const unsigned seg_high = get_le16(relocstart + 2);
        SPAN_S_VAR(const byte, p, relocstart + 4);
        unsigned es = 0;
        while (ones) {
            unsigned di = get_le16(p);
            es += get_le16(p + 2);
            bool dorel = true;
            for (p += 4; ones && di < 0x10000; p++) {
                if (dorel) {
                    set_le16(relocs + (4 * relocnum + 0), di);
                    set_le16(relocs + (4 * relocnum + 2), es);
                    NO_printf("dos/exe unreloc %4d %6x\n", relocnum, es * 16 + di);
                    relocnum++;
                }
                dorel = true;
                if (*p == 0) {
                    SPAN_S_VAR(const byte, q, obuf + (es * 16 + di), obuf);
                    while (!(*q == 0x9a && get_le16(q + 3) <= seg_high))
                        q++;
                    di = ptr_udiff_bytes(q, obuf + (es * 16)) + 3;
                } else if (*p == 1) {
                    di += 254;
                    if (di < 0x10000)
                        ones--;
                    dorel = false;
                } else
                    di += *p;
            }
        }
    }
    // fill new exe header
    mem_clear(&oh);
    oh.ident = 'M' + 'Z' * 256;
    if (relocnum) {
        oh.relocs = relocnum;
        while (relocnum & 3) // paragraph align
            set_le32(relocs + (4 * relocnum++), 0);
    }
    unsigned outputlen = sizeof(oh) + 4 * relocnum + ptr_udiff_bytes(relocstart, obuf);
    oh.m512 = outputlen & 511;
    oh.p512 = (outputlen + 511) >> 9;
    oh.headsize16 = 2 + relocnum / 4;
    oh.max = ih.max;
    oh.min = ih.min;
    oh.sp = ih.sp;
    oh.ss = ih.ss;
    if (flag & MAXMEM) {
        imagesize -= 2;
        oh.max = get_le16(ibuf + imagesize);
    }
    if (flag & MINMEM) {
        imagesize -= 2;
        oh.min = get_le16(ibuf + imagesize);
    }
    if (flag & SP) {
        imagesize -= 2;
        oh.sp = get_le16(ibuf + imagesize);
    }
    if (flag & SS) {
        imagesize -= 2;
        oh.ss = get_le16(ibuf + imagesize);
    }
    unsigned ip = (flag & USEJUMP) ? get_le32(ibuf + imagesize - 4) : (unsigned) ih.firstreloc;
    oh.ip = ip & 0xffff;
    oh.cs = ip >> 16;
    oh.relocoffs = sizeof(oh);
    oh.firstreloc = 0;
    if (!fo)
        return;
    // write header + relocations + uncompressed file
    fo->write(&oh, sizeof(oh));
    if (relocnum)
        fo->write(relocs, 4 * relocnum);
    fo->write(obuf, ptr_udiff_bytes(relocstart, obuf));
    // copy the overlay
    copyOverlay(fo, ih_overlay, obuf);
}
References MemBuffer::alloc(), MemBuffer::allocForDecompression(), PackHeader::buf_offset, PackHeader::c_len, Packer::checkOverlay(), Packer::copyOverlay(), PackExe::exe_header_t::cs, Packer::decompress(), di, PackerBase::fi, PackerBase::file_size, PackExe::exe_header_t::firstreloc, get_le16(), get_le32(), PackHeader::getPackHeaderSize(), PackExe::exe_header_t::headsize16, Packer::ibuf, PackExe::exe_header_t::ident, ih, ih_imagesize, ih_overlay, PackExe::exe_header_t::ip, PackExe::exe_header_t::m512, PackExe::exe_header_t::max, MAXMEM, MAXRELOCSIZE, mem_clear(), PackExe::exe_header_t::min, MINMEM, NO_printf(), NORELOC, Packer::obuf, oh, PackExe::exe_header_t::p512, PackerBase::ph, ptr_udiff_bytes(), InputFile::readx(), PackExe::exe_header_t::relocoffs, PackExe::exe_header_t::relocs, relocsize, InputFile::seek(), SEEK_SET, set_le16(), set_le32(), PackExe::exe_header_t::sp, SP, SPAN_0_VAR, SPAN_S_VAR, PackExe::exe_header_t::ss, SS, throwCantUnpack(), PackHeader::u_len, USEJUMP, and OutputFile::write().
Member Data Documentation
device_driver
bool PackExe::device_driver = false protected
Definition at line 97 of file p_exe.h.
Referenced by addLoaderEpilogue(), buildLoader(), and pack().
has_9a
bool PackExe::has_9a = false protected
Definition at line 96 of file p_exe.h.
Referenced by addLoaderEpilogue(), and pack().
ih
exe_header_t PackExe::ih = {} protected
Definition at line 89 of file p_exe.h.
Referenced by addLoaderEpilogue(), canPack(), canUnpack(), fillExeHeader(), pack(), readFileHeader(), and unpack().
ih_exesize
unsigned PackExe::ih_exesize = 0 protected
Definition at line 91 of file p_exe.h.
Referenced by addLoaderEpilogue(), and readFileHeader().
ih_imagesize
unsigned PackExe::ih_imagesize = 0 protected
Definition at line 92 of file p_exe.h.
Referenced by canPack(), getCompressionMethods(), pack(), readFileHeader(), and unpack().
ih_overlay
unsigned PackExe::ih_overlay = 0 protected
Definition at line 93 of file p_exe.h.
Referenced by pack(), readFileHeader(), and unpack().
oh
exe_header_t PackExe::oh = {} protected
Definition at line 89 of file p_exe.h.
Referenced by fillExeHeader(), pack(), and unpack().
relocsize
unsigned PackExe::relocsize = 0 protected
Definition at line 94 of file p_exe.h.
Referenced by addLoaderEpilogue(), buildLoader(), pack(), and unpack().
stack_for_lzma
unsigned PackExe::stack_for_lzma = 0 protected
Definition at line 101 of file p_exe.h.
Referenced by buildLoader(), and fillExeHeader().
use_clear_dirty_stack
bool PackExe::use_clear_dirty_stack = false protected
Definition at line 102 of file p_exe.h.
Referenced by buildLoader().
The documentation for this class was generated from the following files:
src/p_exe.h
src/p_exe.cpp