My Project: LeFile Class Reference
LeFile Class Reference
#include <lefile.h>
Classes
struct le_header_t
struct le_object_table_entry_t
struct le_pagemap_entry_t
Protected Types
enum { FIXUP_EXTRA = 3 }
Protected Member Functions
LeFile (InputFile *) noexcept
virtual ~LeFile () noexcept
virtual bool readFileHeader ()
virtual void writeFile (OutputFile *, bool)
virtual void readObjectTable ()
virtual void writeObjectTable ()
virtual void readFixupPageTable ()
virtual void writeFixupPageTable ()
virtual void readPageMap ()
virtual void writePageMap ()
virtual void encodePageMap ()
virtual void decodePageMap ()
virtual void readResidentNames ()
virtual void writeResidentNames ()
virtual void encodeResidentNames ()
virtual void decodeResidentNames ()
virtual void readNonResidentNames ()
virtual void writeNonResidentNames ()
virtual void encodeNonResidentNames ()
virtual void decodeNonResidentNames ()
virtual void readEntryTable ()
virtual void writeEntryTable ()
virtual void readFixups ()
virtual void writeFixups ()
virtual void readImage ()
virtual void writeImage ()
void countFixups (unsigned *) const
unsigned getImageSize () const
SPAN_0 (byte) iimage
SPAN_0 (byte) oimage
Protected Attributes
InputFile * fif = nullptr
OutputFile * fof = nullptr
unsigned le_offset = 0
unsigned exe_offset = 0
le_header_t ih = {}
le_header_t oh = {}
le_object_table_entry_t * iobject_table = nullptr
le_object_table_entry_t * oobject_table = nullptr
unsigned * ifpage_table = nullptr
unsigned * ofpage_table = nullptr
le_pagemap_entry_t * ipm_entries = nullptr
le_pagemap_entry_t * opm_entries = nullptr
byte * ires_names = nullptr
byte * ores_names = nullptr
byte * ifixups = nullptr
byte * ofixups = nullptr
byte * inonres_names = nullptr
byte * ononres_names = nullptr
MemBuffer mb_iimage
MemBuffer mb_oimage
byte * ientries = nullptr
byte * oentries = nullptr
unsigned soobject_table = 0
unsigned sofpage_table = 0
unsigned sopm_entries = 0
unsigned sores_names = 0
unsigned sofixups = 0
unsigned sononres_names = 0
unsigned soimage = 0
unsigned soentries = 0
Detailed Description
Definition at line 39 of file lefile.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
FIXUP_EXTRA
Definition at line 48 of file lefile.h.
{ FIXUP_EXTRA = 3 };
Constructor & Destructor Documentation
LeFile()
LeFile::LeFile (InputFile * f) explicit protected noexcept
Definition at line 32 of file lefile.cpp.
                                    : fif(f) {
    COMPILE_TIME_ASSERT(sizeof(le_header_t) == 196)
    COMPILE_TIME_ASSERT(sizeof(le_object_table_entry_t) == 24)
    COMPILE_TIME_ASSERT(sizeof(le_pagemap_entry_t) == 4)
    mem_clear(&ih);
    mem_clear(&oh);
}
References COMPILE_TIME_ASSERT, mem_clear(), and oh.
~LeFile()
LeFile::~LeFile () protected virtual noexcept
Definition at line 40 of file lefile.cpp.
{
    delete[] iobject_table;
    delete[] oobject_table;
    delete[] ifpage_table;
    delete[] ofpage_table;
    delete[] ipm_entries;
    delete[] opm_entries;
    delete[] ires_names;
    delete[] ores_names;
    delete[] ifixups;
    delete[] ofixups;
    delete[] inonres_names;
    delete[] ononres_names;
    delete[] ientries;
    delete[] oentries;
}
References ientries, ifixups, ifpage_table, inonres_names, iobject_table, ipm_entries, ires_names, oentries, ofixups, ofpage_table, ononres_names, oobject_table, opm_entries, and ores_names.
Member Function Documentation
countFixups()
void LeFile::countFixups (unsigned * counts) const protected
Definition at line 265 of file lefile.cpp.
{
    const unsigned o = objects;
    memset(counts, 0, mem_size(sizeof(unsigned), o + 2));
    // counts[0..objects-1] - # of 32-bit offset relocations in for that objects
    // counts[objects]      - # of selector fixups
    // counts[objects+1]    - # of self-relative fixups
    const byte *fix = ifixups;
    const unsigned sfixups = get_le32(ifpage_table + pages);
    unsigned ll;
    while (ptr_udiff_bytes(fix, ifixups) < sfixups) {
        if ((fix[1] & ~0x10) != 0)
            throwCantPack("unsupported fixup record");
        switch (*fix) {
        case 2: // selector fixup
            counts[o] += 9;
            fix += 5;
            break;
        case 0x12: // alias selector
            throwCantPack("16-bit selector alias fixup not yet supported");
        case 5: // 16-bit offset
            fix += (fix[1] & 0x10) ? 9 : 7;
            break;
        case 6: // 16:32 pointer
            counts[o] += 9;
            // fall through
        case 7: // 32-bit offset
            counts[fix[4] - 1] += 4;
            fix += (fix[1] & 0x10) ? 9 : 7;
            break;
        case 0x27: // 32-bit offset list
            ll = fix[2];
            counts[fix[3] - 1] += ll * 4;
            fix += (fix[1] & 0x10) ? 6 : 4;
            fix += ll * 2;
            break;
        case 8: // 32-bit self relative fixup
            counts[o + 1] += 4;
            fix += (fix[1] & 0x10) ? 9 : 7;
            break;
        default:
            throwCantPack("unsupported fixup record");
        }
    }
    counts[o]++;        // extra space for 'ret'
    counts[o + 1] += 4; // extra space for 0xFFFFFFFF
}
References get_le32(), ifixups, ifpage_table, mem_size(), memset(), objects, pages, ptr_udiff_bytes(), and throwCantPack().
Referenced by PackWcle::preprocessFixups().
decodeNonResidentNames()
virtual void LeFile::decodeNonResidentNames () inline protected virtual
Definition at line 168 of file lefile.h.
{ encodeNonResidentNames(); }
References encodeNonResidentNames().
Referenced by PackWcle::unpack().
decodePageMap()
virtual void LeFile::decodePageMap () inline protected virtual
Definition at line 152 of file lefile.h.
{ encodePageMap(); }
References encodePageMap().
Referenced by PackWcle::unpack().
decodeResidentNames()
virtual void LeFile::decodeResidentNames () inline protected virtual
Definition at line 160 of file lefile.h.
{ encodeResidentNames(); }
References encodeResidentNames().
Referenced by PackWcle::unpack().
encodeNonResidentNames()
virtual void LeFile::encodeNonResidentNames () inline protected virtual
Definition at line 164 of file lefile.h.
{
        ononres_names = inonres_names;
        inonres_names = nullptr;
    }
References inonres_names, and ononres_names.
Referenced by decodeNonResidentNames(), and PackWcle::pack().
encodePageMap()
virtual void LeFile::encodePageMap () inline protected virtual
Reimplemented in PackWcle.
Definition at line 148 of file lefile.h.
{
        opm_entries = ipm_entries;
        ipm_entries = nullptr;
    }
References ipm_entries, and opm_entries.
Referenced by decodePageMap().
encodeResidentNames()
virtual void LeFile::encodeResidentNames () inline protected virtual
Definition at line 156 of file lefile.h.
{
        ores_names = ires_names;
        ires_names = nullptr;
    }
References ires_names, and ores_names.
Referenced by decodeResidentNames(), and PackWcle::pack().
getImageSize()
unsigned LeFile::getImageSize () const protected
Definition at line 137 of file lefile.cpp.
{
    unsigned n = 0;
    if (ih.memory_pages > 0) {
        n = (ih.memory_pages - 1) * ih.memory_page_size;
        n += ih.bytes_on_last_page;
    }
    return n;
}
References LeFile::le_header_t::bytes_on_last_page, ih, LeFile::le_header_t::memory_page_size, LeFile::le_header_t::memory_pages, and n.
Referenced by PackWcle::canUnpack(), PackWcle::pack(), and PackWcle::unpack().
readEntryTable()
void LeFile::readEntryTable () protected virtual
Definition at line 101 of file lefile.cpp.
{
    soentries = ih.fixup_page_table_offset - ih.entry_table_offset;
    fif->seek(le_offset + ih.entry_table_offset, SEEK_SET);
    ientries = New(byte, soentries);
    fif->readx(ientries, soentries);
}
References LeFile::le_header_t::entry_table_offset, fif, LeFile::le_header_t::fixup_page_table_offset, ientries, ih, le_offset, New, InputFile::readx(), InputFile::seek(), SEEK_SET, and soentries.
Referenced by PackWcle::pack(), and PackWcle::unpack().
readFileHeader()
bool LeFile::readFileHeader () protected virtual
Definition at line 186 of file lefile.cpp.
{
#define H(x) get_le16(header + (2 * (x)))
    byte header[0x40];
    le_offset = exe_offset = 0;
    int ic;
    for (ic = 0; ic < 20; ic++) {
        fif->seek(le_offset, SEEK_SET);
        fif->readx(header, sizeof(header));
        if (memcmp(header, "MZ", 2) == 0) // normal dos exe
        {
            exe_offset = le_offset;
            if (H(0x18 / 2) >= 0x40 && memcmp(header + 0x19, "TIPPACH", 7)) // new format exe
                le_offset += H(0x3c / 2) + H(0x3e / 2) * 65536;
            else {
                le_offset += H(2) * 512 + H(1);
                if (H(1))
                    le_offset -= 512;
                else if (H(2) == 0)
                    return false;
            }
        } else if (memcmp(header, "BW", 2) == 0) // used in dos4gw.exe
            le_offset += H(2) * 512 + H(1);
        else if (memcmp(header, "LE", 2) == 0)
            break; // success
        else if (memcmp(header, "PMW1", 4) == 0)
            throwCantPack("already packed with PMWLITE");
        else
            return false;
    }
    if (ic == 20)
        return false;
    fif->seek(le_offset, SEEK_SET);
    fif->readx(&ih, sizeof(ih));
    if (mps < 512 || mps > 2097152 || (mps & (mps - 1)) != 0)
        throwCantPack("LE file header invalid page size %u", (unsigned) mps);
    if (ih.bytes_on_last_page > mps || pages == 0)
        throwCantPack("bad LE file header");
    if (!mem_size_valid(mps, pages) || exe_offset > le_offset)
        throwCantPack("bad LE file header");
    return true;
#undef H
}
References LeFile::le_header_t::bytes_on_last_page, exe_offset, fif, H, ih, le_offset, mem_size_valid(), memcmp(), mps, pages, InputFile::readx(), InputFile::seek(), SEEK_SET, and throwCantPack().
Referenced by PackWcle::canPack(), and PackWcle::canUnpack().
readFixupPageTable()
void LeFile::readFixupPageTable () protected virtual
Definition at line 113 of file lefile.cpp.
{
    sofpage_table = 1 + pages;
    ifpage_table = New(unsigned, sofpage_table);
    fif->seek(le_offset + ih.fixup_page_table_offset, SEEK_SET);
    fif->readx(ifpage_table, 4 * sofpage_table);
}
References fif, LeFile::le_header_t::fixup_page_table_offset, ifpage_table, ih, le_offset, New, pages, InputFile::readx(), InputFile::seek(), SEEK_SET, and sofpage_table.
Referenced by PackWcle::pack(), and PackWcle::unpack().
readFixups()
void LeFile::readFixups () protected virtual
Definition at line 125 of file lefile.cpp.
{
    sofixups = get_le32(ifpage_table + pages) - get_le32(ifpage_table);
    ifixups = New(byte, sofixups);
    fif->seek(le_offset + ih.fixup_record_table_offset, SEEK_SET);
    fif->readx(ifixups, sofixups);
}
References fif, LeFile::le_header_t::fixup_record_table_offset, get_le32(), ifixups, ifpage_table, ih, le_offset, New, pages, InputFile::readx(), InputFile::seek(), SEEK_SET, and sofixups.
Referenced by PackWcle::pack(), and PackWcle::unpack().
readImage()
void LeFile::readImage () protected virtual
Definition at line 146 of file lefile.cpp.
                       {
    soimage = mem_size(mps, pages); // assert size
    if (!soimage)                   // late detection, but protect against .alloc(0)
        throwCantPack("no soimage");
    mb_iimage.alloc(soimage);
    mb_iimage.clear();
    iimage = mb_iimage; // => now a SPAN_S
    unsigned ic, jc;
    for (ic = jc = 0; ic < pages; ic++) {
        if ((ipm_entries[ic].type & 0xC0) == 0) {
            fif->seek(ih.data_pages_offset + exe_offset +
                          (ipm_entries[ic].m * 0x100 + ipm_entries[ic].l - 1) * mps,
                      SEEK_SET);
            unsigned bytes = ic != pages - 1 ? mps : ih.bytes_on_last_page;
            fif->readx(iimage + jc, bytes);
        }
        jc += mps;
    }
}
References MemBuffer::alloc(), LeFile::le_header_t::bytes_on_last_page, MemBuffer::clear(), LeFile::le_header_t::data_pages_offset, exe_offset, fif, ih, ipm_entries, LeFile::le_pagemap_entry_t::l, LeFile::le_pagemap_entry_t::m, mb_iimage, mem_size(), mps, pages, InputFile::readx(), InputFile::seek(), SEEK_SET, soimage, and throwCantPack().
Referenced by PackWcle::pack(), and PackWcle::unpack().
readNonResidentNames()
void LeFile::readNonResidentNames () protected virtual
Definition at line 172 of file lefile.cpp.
{
    if (ih.non_resident_name_table_length) {
        sononres_names = ih.non_resident_name_table_length;
        inonres_names = New(byte, sononres_names);
        fif->seek(exe_offset + ih.non_resident_name_table_offset, SEEK_SET);
        fif->readx(inonres_names, sononres_names);
    }
}
References exe_offset, fif, ih, inonres_names, New, LeFile::le_header_t::non_resident_name_table_length, LeFile::le_header_t::non_resident_name_table_offset, InputFile::readx(), InputFile::seek(), SEEK_SET, and sononres_names.
Referenced by PackWcle::pack(), and PackWcle::unpack().
readObjectTable()
void LeFile::readObjectTable () protected virtual
Reimplemented in PackWcle.
Definition at line 61 of file lefile.cpp.
{
    soobject_table = objects;
    iobject_table = New(le_object_table_entry_t, soobject_table);
    fif->seek(le_offset + ih.object_table_offset, SEEK_SET);
    fif->readx(iobject_table, sizeof(*iobject_table) * objects);
}
References fif, ih, iobject_table, le_offset, New, LeFile::le_header_t::object_table_offset, objects, InputFile::readx(), InputFile::seek(), SEEK_SET, and soobject_table.
Referenced by PackWcle::readObjectTable().
readPageMap()
void LeFile::readPageMap () protected virtual
Definition at line 73 of file lefile.cpp.
{
    sopm_entries = pages;
    ipm_entries = New(le_pagemap_entry_t, sopm_entries);
    fif->seek(le_offset + ih.object_pagemap_offset, SEEK_SET);
    fif->readx(ipm_entries, sizeof(*ipm_entries) * pages);
    for (unsigned ic = 0; ic < pages; ic++)
        if ((ipm_entries[ic].type & 0xC0) != 0 && (ipm_entries[ic].type & 0xC0) != 0xC0)
            throwCantPack("unexpected value in page map table");
}
References fif, ih, ipm_entries, le_offset, New, LeFile::le_header_t::object_pagemap_offset, pages, InputFile::readx(), InputFile::seek(), SEEK_SET, sopm_entries, and throwCantPack().
Referenced by PackWcle::pack(), and PackWcle::unpack().
readResidentNames()
void LeFile::readResidentNames () protected virtual
Definition at line 89 of file lefile.cpp.
{
    sores_names = ih.entry_table_offset - ih.resident_names_offset;
    ires_names = New(byte, sores_names);
    fif->seek(le_offset + ih.resident_names_offset, SEEK_SET);
    fif->readx(ires_names, sores_names);
}
References LeFile::le_header_t::entry_table_offset, fif, ih, ires_names, le_offset, New, InputFile::readx(), LeFile::le_header_t::resident_names_offset, InputFile::seek(), SEEK_SET, and sores_names.
Referenced by PackWcle::pack(), and PackWcle::unpack().
SPAN_0() [1/2]
LeFile::SPAN_0 (byte) protected
SPAN_0() [2/2]
LeFile::SPAN_0 (byte) protected
writeEntryTable()
void LeFile::writeEntryTable () protected virtual
Definition at line 108 of file lefile.cpp.
{
    if (fof && oentries)
        fof->write(oentries, soentries);
}
References fof, oentries, soentries, and OutputFile::write().
Referenced by writeFile().
writeFile()
void LeFile::writeFile (OutputFile * f, bool le) protected virtual
Definition at line 231 of file lefile.cpp.
{
    fof = f;
    memcpy(&oh, &ih,
           (charptr) &oh.memory_pages - (charptr) &oh); // copy some members of the orig. header
    oh.memory_page_size = mps;
    oh.object_table_offset = sizeof(oh);
    oh.object_table_entries = soobject_table;
    oh.object_pagemap_offset = oh.object_table_offset + soobject_table * sizeof(*iobject_table);
    oh.resident_names_offset = oh.object_pagemap_offset + sopm_entries * sizeof(*ipm_entries);
    oh.entry_table_offset = oh.resident_names_offset + sores_names;
    oh.fixup_page_table_offset = oh.entry_table_offset + soentries;
    oh.fixup_record_table_offset = oh.fixup_page_table_offset + sofpage_table * 4;
    oh.imported_modules_name_table_offset = oh.fixup_record_table_offset + sofixups - FIXUP_EXTRA;
    oh.imported_procedures_name_table_offset = oh.imported_modules_name_table_offset;
    oh.data_pages_offset =
        oh.fixup_record_table_offset + sofixups + (le ? 0 : le_offset - exe_offset);
    if (ih.non_resident_name_table_length) {
        oh.non_resident_name_table_offset = oh.data_pages_offset + soimage;
        oh.non_resident_name_table_length = sononres_names;
    }
    oh.fixup_size = sofixups + 4 * sofpage_table;
    oh.loader_size = oh.fixup_size + oh.fixup_page_table_offset - sizeof(oh);
    fof->write(&oh, sizeof(oh));
    writeObjectTable();
    writePageMap();
    writeResidentNames();
    writeEntryTable();
    writeFixupPageTable();
    writeFixups();
    writeImage();
    writeNonResidentNames();
}
References charptr, LeFile::le_header_t::data_pages_offset, LeFile::le_header_t::entry_table_offset, exe_offset, FIXUP_EXTRA, LeFile::le_header_t::fixup_page_table_offset, LeFile::le_header_t::fixup_record_table_offset, LeFile::le_header_t::fixup_size, fof, ih, LeFile::le_header_t::imported_modules_name_table_offset, LeFile::le_header_t::imported_procedures_name_table_offset, le_offset, LeFile::le_header_t::loader_size, memcpy(), LeFile::le_header_t::memory_page_size, LeFile::le_header_t::memory_pages, mps, LeFile::le_header_t::non_resident_name_table_length, LeFile::le_header_t::non_resident_name_table_offset, LeFile::le_header_t::object_pagemap_offset, LeFile::le_header_t::object_table_entries, LeFile::le_header_t::object_table_offset, oh, LeFile::le_header_t::resident_names_offset, soentries, sofixups, sofpage_table, soimage, sononres_names, soobject_table, sopm_entries, sores_names, OutputFile::write(), writeEntryTable(), writeFixupPageTable(), writeFixups(), writeImage(), writeNonResidentNames(), writeObjectTable(), writePageMap(), and writeResidentNames().
Referenced by PackWcle::pack(), and PackWcle::unpack().
writeFixupPageTable()
void LeFile::writeFixupPageTable () protected virtual
Definition at line 120 of file lefile.cpp.
{
    if (fof && ofpage_table)
        fof->write(ofpage_table, 4 * sofpage_table);
}
References fof, ofpage_table, sofpage_table, and OutputFile::write().
Referenced by writeFile().
writeFixups()
void LeFile::writeFixups () protected virtual
Definition at line 132 of file lefile.cpp.
{
    if (fof && ofixups)
        fof->write(ofixups, sofixups);
}
References fof, ofixups, sofixups, and OutputFile::write().
Referenced by writeFile().
writeImage()
void LeFile::writeImage () protected virtual
Definition at line 167 of file lefile.cpp.
{
    if (fof && oimage != nullptr)
        fof->write(oimage, soimage);
}
References fof, soimage, and OutputFile::write().
Referenced by writeFile().
writeNonResidentNames()
void LeFile::writeNonResidentNames () protected virtual
Definition at line 181 of file lefile.cpp.
{
    if (fof && ononres_names)
        fof->write(ononres_names, sononres_names);
}
References fof, ononres_names, sononres_names, and OutputFile::write().
Referenced by writeFile().
writeObjectTable()
void LeFile::writeObjectTable () protected virtual
Definition at line 68 of file lefile.cpp.
{
    if (fof && oobject_table)
        fof->write(oobject_table, sizeof(*iobject_table) * soobject_table);
}
References fof, iobject_table, oobject_table, soobject_table, and OutputFile::write().
Referenced by writeFile().
writePageMap()
void LeFile::writePageMap () protected virtual
Definition at line 84 of file lefile.cpp.
{
    if (fof && opm_entries)
        fof->write(opm_entries, sizeof(*ipm_entries) * sopm_entries);
}
References fof, ipm_entries, opm_entries, sopm_entries, and OutputFile::write().
Referenced by writeFile().
writeResidentNames()
void LeFile::writeResidentNames () protected virtual
Definition at line 96 of file lefile.cpp.
{
    if (fof && ores_names)
        fof->write(ores_names, sores_names);
}
References fof, ores_names, sores_names, and OutputFile::write().
Referenced by writeFile().
Member Data Documentation
exe_offset
unsigned LeFile::exe_offset = 0 protected
Definition at line 191 of file lefile.h.
Referenced by PackWcle::canUnpack(), PackWcle::pack(), readFileHeader(), readImage(), readNonResidentNames(), PackWcle::unpack(), and writeFile().
fif
InputFile* LeFile::fif = nullptr protected
Definition at line 188 of file lefile.h.
Referenced by readEntryTable(), readFileHeader(), readFixupPageTable(), readFixups(), readImage(), readNonResidentNames(), readObjectTable(), readPageMap(), and readResidentNames().
fof
OutputFile* LeFile::fof = nullptr protected
Definition at line 189 of file lefile.h.
Referenced by writeEntryTable(), writeFile(), writeFixupPageTable(), writeFixups(), writeImage(), writeNonResidentNames(), writeObjectTable(), writePageMap(), and writeResidentNames().
ientries
byte* LeFile::ientries = nullptr protected
Definition at line 211 of file lefile.h.
Referenced by PackWcle::decodeEntryTable(), PackWcle::encodeEntryTable(), readEntryTable(), and ~LeFile().
ifixups
byte* LeFile::ifixups = nullptr protected
Definition at line 203 of file lefile.h.
Referenced by countFixups(), PackWcle::encodeImage(), PackWcle::pack(), PackWcle::preprocessFixups(), readFixups(), and ~LeFile().
ifpage_table
unsigned* LeFile::ifpage_table = nullptr protected
Definition at line 197 of file lefile.h.
Referenced by countFixups(), PackWcle::preprocessFixups(), readFixupPageTable(), readFixups(), and ~LeFile().
ih
le_header_t LeFile::ih = {} protected
Definition at line 193 of file lefile.h.
Referenced by PackWcle::canUnpack(), PackWcle::decodeObjectTable(), getImageSize(), PackWcle::pack(), readEntryTable(), readFileHeader(), readFixupPageTable(), readFixups(), readImage(), readNonResidentNames(), readObjectTable(), readPageMap(), readResidentNames(), PackWcle::unpack(), and writeFile().
inonres_names
byte* LeFile::inonres_names = nullptr protected
Definition at line 205 of file lefile.h.
Referenced by encodeNonResidentNames(), readNonResidentNames(), and ~LeFile().
iobject_table
le_object_table_entry_t* LeFile::iobject_table = nullptr protected
Definition at line 195 of file lefile.h.
Referenced by readObjectTable(), PackWcle::readObjectTable(), writeObjectTable(), and ~LeFile().
ipm_entries
le_pagemap_entry_t* LeFile::ipm_entries = nullptr protected
Definition at line 199 of file lefile.h.
Referenced by encodePageMap(), readImage(), readPageMap(), writePageMap(), and ~LeFile().
ires_names
byte* LeFile::ires_names = nullptr protected
Definition at line 201 of file lefile.h.
Referenced by encodeResidentNames(), readResidentNames(), and ~LeFile().
le_offset
unsigned LeFile::le_offset = 0 protected
Definition at line 190 of file lefile.h.
Referenced by PackWcle::handleStub(), readEntryTable(), readFileHeader(), readFixupPageTable(), readFixups(), readObjectTable(), readPageMap(), readResidentNames(), and writeFile().
mb_iimage
MemBuffer LeFile::mb_iimage protected
Definition at line 207 of file lefile.h.
Referenced by PackWcle::decodeFixups(), and readImage().
mb_oimage
MemBuffer LeFile::mb_oimage protected
Definition at line 209 of file lefile.h.
Referenced by PackWcle::decodeImage(), PackWcle::encodeImage(), PackWcle::pack(), and PackWcle::unpack().
oentries
byte* LeFile::oentries = nullptr protected
Definition at line 212 of file lefile.h.
Referenced by PackWcle::decodeEntryTable(), PackWcle::encodeEntryTable(), writeEntryTable(), and ~LeFile().
ofixups
byte* LeFile::ofixups = nullptr protected
Definition at line 204 of file lefile.h.
Referenced by PackWcle::decodeFixups(), PackWcle::encodeFixups(), writeFixups(), and ~LeFile().
ofpage_table
unsigned* LeFile::ofpage_table = nullptr protected
Definition at line 198 of file lefile.h.
Referenced by PackWcle::decodeFixupPageTable(), PackWcle::decodeFixups(), PackWcle::encodeFixupPageTable(), writeFixupPageTable(), and ~LeFile().
oh
le_header_t LeFile::oh = {} protected
Definition at line 193 of file lefile.h.
Referenced by PackWcle::decodeFixups(), PackWcle::decodeImage(), PackWcle::decodeObjectTable(), PackWcle::encodeObjectTable(), PackWcle::pack(), PackWcle::unpack(), and writeFile().
ononres_names
byte* LeFile::ononres_names = nullptr protected
Definition at line 206 of file lefile.h.
Referenced by encodeNonResidentNames(), writeNonResidentNames(), and ~LeFile().
oobject_table
le_object_table_entry_t* LeFile::oobject_table = nullptr protected
Definition at line 196 of file lefile.h.
Referenced by PackWcle::decodeEntryTable(), PackWcle::decodeFixups(), PackWcle::decodeObjectTable(), PackWcle::encodeObjectTable(), writeObjectTable(), and ~LeFile().
opm_entries
le_pagemap_entry_t* LeFile::opm_entries = nullptr protected
Definition at line 200 of file lefile.h.
Referenced by encodePageMap(), PackWcle::encodePageMap(), writePageMap(), and ~LeFile().
ores_names
byte* LeFile::ores_names = nullptr protected
Definition at line 202 of file lefile.h.
Referenced by encodeResidentNames(), writeResidentNames(), and ~LeFile().
soentries
unsigned LeFile::soentries = 0 protected
Definition at line 221 of file lefile.h.
Referenced by PackWcle::decodeEntryTable(), PackWcle::encodeEntryTable(), readEntryTable(), writeEntryTable(), and writeFile().
sofixups
unsigned LeFile::sofixups = 0 protected
Definition at line 218 of file lefile.h.
Referenced by PackWcle::decodeFixups(), PackWcle::encodeFixupPageTable(), PackWcle::encodeFixups(), PackWcle::encodeImage(), PackWcle::encodeObjectTable(), PackWcle::pack(), PackWcle::preprocessFixups(), readFixups(), writeFile(), and writeFixups().
sofpage_table
unsigned LeFile::sofpage_table = 0 protected
Definition at line 215 of file lefile.h.
Referenced by PackWcle::decodeFixupPageTable(), PackWcle::encodeFixupPageTable(), readFixupPageTable(), writeFile(), and writeFixupPageTable().
soimage
unsigned LeFile::soimage = 0 protected
Definition at line 220 of file lefile.h.
Referenced by PackWcle::decodeFixups(), PackWcle::decodeImage(), PackWcle::encodeImage(), PackWcle::pack(), PackWcle::preprocessFixups(), readImage(), PackWcle::unpack(), writeFile(), and writeImage().
sononres_names
unsigned LeFile::sononres_names = 0 protected
Definition at line 219 of file lefile.h.
Referenced by readNonResidentNames(), writeFile(), and writeNonResidentNames().
soobject_table
unsigned LeFile::soobject_table = 0 protected
Definition at line 214 of file lefile.h.
Referenced by PackWcle::decodeEntryTable(), PackWcle::decodeFixups(), PackWcle::decodeObjectTable(), PackWcle::encodeObjectTable(), readObjectTable(), PackWcle::unpack(), writeFile(), and writeObjectTable().
sopm_entries
unsigned LeFile::sopm_entries = 0 protected
Definition at line 216 of file lefile.h.
Referenced by PackWcle::encodePageMap(), readPageMap(), writeFile(), and writePageMap().
sores_names
unsigned LeFile::sores_names = 0 protected
Definition at line 217 of file lefile.h.
Referenced by readResidentNames(), writeFile(), and writeResidentNames().
The documentation for this class was generated from the following files:
src/lefile.h
src/lefile.cpp