My Project: UiPacker Class Reference
UiPacker Class Reference final
#include <ui.h>
Classes
struct State
Public Member Functions
UiPacker (const PackerBase *)
virtual ~UiPacker () noexcept
virtual void uiPackStart (const OutputFile *fo)
pack
virtual void uiPackEnd (const OutputFile *fo)
virtual void uiUnpackStart (const OutputFile *fo)
unpack
virtual void uiUnpackEnd (const OutputFile *fo)
virtual void uiListStart ()
list
virtual void uiList ()
virtual void uiListEnd ()
virtual void uiTestStart ()
test
virtual void uiTestEnd ()
virtual bool uiFileInfoStart ()
info
virtual void uiFileInfoEnd ()
virtual void startCallback (unsigned u_len, unsigned step, int pass, int total_passes)
virtual void firstCallback ()
virtual void finalCallback (unsigned u_len, unsigned c_len)
virtual void endCallback ()
end callback
virtual void endCallback (bool done)
virtual upx_callback_t * getCallback ()
Static Public Member Functions
static void uiConfirmUpdate ()
static void uiPackTotal ()
static void uiUnpackTotal ()
static void uiListTotal (bool uncompress=false)
static void uiTestTotal ()
static void uiFileInfoTotal ()
static void uiHeader ()
util
static void uiFooter (const char *n)
Public Attributes
int ui_pass = 0
int ui_total_passes = 0
Protected Member Functions
virtual void doCallback (unsigned isize, unsigned osize)
virtual void uiUpdate (upx_off_t fc_len=-1, upx_off_t fu_len=-1)
virtual void printInfo (int nl=0)
start callback
OwningPointer (State) s
Static Protected Member Functions
static void __acc_cdecl progress_callback (upx_callback_t *, unsigned, unsigned)
the callback
Protected Attributes
const PackerBase *const pb
upx_callback_t cb = {}
Static Protected Attributes
static unsigned total_files = 0
static unsigned total_files_done = 0
static upx_uint64_t total_c_len = 0
static upx_uint64_t total_u_len = 0
static upx_uint64_t total_fc_len = 0
static upx_uint64_t total_fu_len = 0
static unsigned update_c_len = 0
static unsigned update_u_len = 0
static unsigned update_fc_len = 0
static unsigned update_fu_len = 0
Detailed Description
Definition at line 37 of file ui.h.
Constructor & Destructor Documentation
UiPacker()
UiPacker::UiPacker (const PackerBase * pb_) explicit
Definition at line 159 of file ui.cpp.
                                        : pb(pb_) {
    static upx_std_once_flag init_done;
    upx_std_call_once(init_done, init_global_constants);
    cb.reset();
    s = new State;
    mem_clear(s);
    s->msg_buf[0] = '\r';
#if defined(UI_USE_SCREEN)
    // FIXME - ugly hack
    s->screen = sobject_get_screen();
#endif
    if (opt->verbose < 0)
        s->mode = M_QUIET;
    else if (opt->verbose == 0 || !acc_isatty(STDOUT_FILENO))
        s->mode = M_INFO;
    else if (opt->verbose == 1 || opt->no_progress)
        s->mode = M_MSG;
    else if (s->screen == nullptr)
        s->mode = M_CB_TERM;
    else
        s->mode = M_CB_SCREEN;
}
References cb, init_global_constants(), M_CB_SCREEN, M_CB_TERM, M_INFO, M_MSG, M_QUIET, mem_clear(), opt, upx_callback_t::reset(), STDOUT_FILENO, upx_std_call_once(), and upx_std_once_flag.
~UiPacker()
UiPacker::~UiPacker () virtual noexcept
Definition at line 186 of file ui.cpp.
{
    cb.reset();
    // owner
    upx::owner_delete(s);
}
References cb, upx::owner_delete(), and upx_callback_t::reset().
Member Function Documentation
doCallback()
void UiPacker::doCallback (unsigned isize, unsigned osize) protected virtual
Definition at line 363 of file ui.cpp.
{
    int i;
    static const char spinner[] = "|/-\\";
    if (s->pass < 0) // no callback wanted
        return;
    if (s->u_len == 0 || isize > s->u_len)
        return;
    // check if we should update the display
    if (s->step > 0 && isize > 0 && isize < s->u_len) {
        if (isize < s->next_update)
            return;
        s->next_update += s->step;
    }
    // compute progress position
    int pos = -1;
    if (isize >= s->u_len)
        pos = s->bar_len;
    else if (isize > 0) {
        pos = get_ratio(s->u_len, isize) * s->bar_len / 1000000;
        assert(pos >= 0);
        assert(pos <= s->bar_len);
    }
#if 0
    printf("%6d %6d %6d %6d %3d %3d\n", isize, osize, s->step, s->next_update, pos, s->pos);
    return;
#endif
    if (pos < s->pos)
        return;
    if (pos < 0 && pos == s->pos)
        return;
    // fill the progress bar
    char *m = &s->msg_buf[s->bar_pos];
    *m++ = progress_filler[2];
    for (i = 0; i < s->bar_len; i++)
        *m++ = progress_filler[i <= pos ? 1 : 0];
    *m++ = progress_filler[3];
    // compute current compression ratio
    unsigned ratio = 1000000;
    if (osize > 0)
        ratio = get_ratio(isize, osize);
    int buflen = (int) (&s->msg_buf[sizeof(s->msg_buf)] - m);
    upx_safe_snprintf(m, buflen, "  %3d.%1d%%  %c ", ratio / 10000, (ratio % 10000) / 1000,
                      spinner[s->spin_counter & 3]);
    assert(strlen(s->msg_buf) < 1 + 80);
    s->pos = pos;
    s->spin_counter++;
    if (s->mode == M_CB_TERM) {
        const char *msg = &s->msg_buf[0];
        int fg = con_fg(stdout, FG_CYAN);
        con_fprintf(stdout, "%s", msg); // avoid backslash interpretation
        (void) con_fg(stdout, fg);
        fflush(stdout);
        printSetNl(1);
        UNUSED(fg);
        return;
    }
#if (UI_USE_SCREEN)
    if (s->mode == M_CB_SCREEN) {
        const char *msg = &s->msg_buf[1];
#if 0
        s->screen->putString(s->screen,msg,s->b_cx,s->b_cy);
#else
        // FIXME: this doesn't honor '--mono' etc.
        int attr = FG_CYAN | s->s_bg;
        s->screen->putStringAttr(s->screen, msg, attr, s->b_cx, s->b_cy);
#endif
        s->screen->refresh(s->screen);
    }
#endif /* UI_USE_SCREEN */
}
References con_fg, con_fprintf, get_ratio(), M_CB_SCREEN, M_CB_TERM, printSetNl(), progress_filler, strlen, UNUSED, and upx_safe_snprintf().
Referenced by finalCallback(), firstCallback(), and progress_callback().
endCallback() [1/2]
void UiPacker::endCallback () virtual
end callback
Definition at line 304 of file ui.cpp.
{
    bool done = (s->total_passes <= 0 || s->pass >= s->total_passes);
    endCallback(done);
}
References endCallback().
Referenced by endCallback().
endCallback() [2/2]
void UiPacker::endCallback (bool done) virtual
Definition at line 309 of file ui.cpp.
{
    if (s->pass < 0) // no callback wanted
        return;
    if (s->mode == M_CB_TERM) {
        if (done)
            printClearLine(stdout);
        else
            printSetNl(2);
    }
// restore screen
#if (UI_USE_SCREEN)
    if (s->mode == M_CB_SCREEN) {
        if (done) {
            int cx, cy, sy;
            assert(s->screen_init_done);
            s->screen_init_done = 0;
            assert(s->s_cx == 0 && s->b_cx == 0);
            s->screen->getCursor(s->screen, &cx, &cy);
            sy = UPX_MAX(0, s->s_cy - s->scroll_up);
            while (cy >= sy)
                s->screen->clearLine(s->screen, cy--);
            s->screen->setCursor(s->screen, s->s_cx, sy);
            s->screen->setFg(s->screen, s->s_fg);
            s->screen->setBg(s->screen, s->s_bg);
            if (s->cursor_shape > 0)
                s->screen->setCursorShape(s->screen, s->cursor_shape);
        } else {
            // not needed:
            //   s->screen->clearLine(s->screen, s->b_cy);
            //   s->screen->setCursor(s->screen, s->b_cx, s->b_cy);
        }
    }
#endif /* UI_USE_SCREEN */
    cb.reset();
#if 0
    printf("callback: pass %d, step %6d, updates %6d\n",
           s->pass, s->step, s->spin_counter);
#endif
}
References cb, cx, M_CB_SCREEN, M_CB_TERM, printClearLine(), printSetNl(), upx_callback_t::reset(), and UPX_MAX.
finalCallback()
void UiPacker::finalCallback (unsigned u_len, unsigned c_len) virtual
Definition at line 295 of file ui.cpp.
{
    s->next_update = u_len;
    doCallback(u_len, c_len);
}
References doCallback().
firstCallback()
void UiPacker::firstCallback () virtual
Definition at line 289 of file ui.cpp.
{
    if (s->pos == -2)
        doCallback(0, 0);
}
References doCallback().
getCallback()
virtual upx_callback_t * UiPacker::getCallback () inline virtual
Definition at line 69 of file ui.h.
{ return &cb; }
References cb.
OwningPointer()
UiPacker::OwningPointer (State) protected
printInfo()
void UiPacker::printInfo (int nl = 0) protected virtual
start callback
Definition at line 196 of file ui.cpp.
{
    if (opt->all_methods && s->total_passes > 1)
        con_fprintf(stdout, "Compressing %s [%s]%s", pb->fi->getName(), pb->getName(),
                    nl ? "\n" : "");
    else {
        char method_name[32 + 1];
        set_method_name(method_name, sizeof(method_name), pb->ph.method, pb->ph.level);
        con_fprintf(stdout, "Compressing %s [%s, %s]%s", pb->fi->getName(), pb->getName(),
                    method_name, nl ? "\n" : "");
    }
}
References con_fprintf, PackerBase::fi, PackerBase::getName(), FileBase::getName(), PackHeader::level, PackHeader::method, opt, pb, PackerBase::ph, and set_method_name().
Referenced by startCallback().
progress_callback()
void __acc_cdecl UiPacker::progress_callback (upx_callback_t * cb, unsigned isize, unsigned osize) static protected
the callback
Definition at line 357 of file ui.cpp.
{
    // printf("%6d %6d %d\n", isize, osize, state);
    UiPacker *self = (UiPacker *) cb->user;
    self->doCallback(isize, osize);
}
References cb, doCallback(), and upx_callback_t::user.
Referenced by startCallback().
startCallback()
void UiPacker::startCallback (unsigned u_len, unsigned step, int pass, int total_passes) virtual
Definition at line 208 of file ui.cpp.
{
    s->u_len = u_len;
    s->step = step;
    s->next_update = step;
    s->pass = pass;
    s->total_passes = total_passes;
    // printf("startCallback %d %d\n", s->pass, s->total_passes);
    s->bar_len = 64;
    s->pos = -2;
    s->spin_counter = 0;
    s->bar_pos = 1; // because of the leading '\r'
    s->pass_digits = 0;
    cb.reset();
    if (s->pass < 0) // no callback wanted
        return;
    if (s->mode <= M_INFO)
        return;
    if (s->mode == M_MSG) {
        if (pass <= 1) {
            printInfo(0);
            fflush(stdout);
            printSetNl(2);
        }
        return;
    }
    cb.nprogress = progress_callback;
    cb.user = this; // parameter for static function UiPacker::progress_callback()
    if (s->mode == M_CB_TERM) {
        const char *fname = fn_basename(pb->fi->getName());
        int l = (int) strlen(fname);
        if (l > 0 && l <= 30) {
            strcpy(&s->msg_buf[s->bar_pos], fname);
            s->bar_pos += l;
            s->msg_buf[s->bar_pos++] = ' ';
            s->msg_buf[s->bar_pos++] = ' ';
            s->bar_len -= l + 2;
        }
    }
    // set pass
    if (total_passes > 1) {
        int buflen, l;
        do {
            s->pass_digits++;
            total_passes /= 10;
        } while (total_passes > 0);
        buflen = sizeof(s->msg_buf) - s->bar_pos;
        l = upx_safe_snprintf(&s->msg_buf[s->bar_pos], buflen, "%*d/%*d  ", s->pass_digits, s->pass,
                              s->pass_digits, s->total_passes);
        if (l > 0 && s->bar_len - l > 10) {
            s->bar_len -= l;
            s->bar_pos += l;
        }
    }
#if (UI_USE_SCREEN)
    if (s->mode == M_CB_SCREEN) {
        if (!s->screen_init_done) {
            s->screen_init_done = 1;
            if (s->screen->hideCursor)
                s->cursor_shape = s->screen->hideCursor(s->screen);
            s->s_fg = s->screen->getFg(s->screen);
            s->s_bg = s->screen->getBg(s->screen);
            s->screen->getCursor(s->screen, &s->s_cx, &s->s_cy);
            s->scroll_up = s->screen->getScrollCounter(s->screen);
            printInfo(1);
            s->screen->getCursor(s->screen, &s->b_cx, &s->b_cy);
            s->scroll_up = s->screen->getScrollCounter(s->screen) - s->scroll_up;
        }
    }
#endif /* UI_USE_SCREEN */
}
References cb, PackerBase::fi, fn_basename(), FileBase::getName(), M_CB_SCREEN, M_CB_TERM, M_INFO, M_MSG, upx_callback_t::nprogress, pb, printInfo(), printSetNl(), progress_callback(), upx_callback_t::reset(), strcpy(), strlen, upx_safe_snprintf(), and upx_callback_t::user.
uiConfirmUpdate()
void UiPacker::uiConfirmUpdate () static
Definition at line 633 of file ui.cpp.
{
    total_files_done++;
    total_fc_len += update_fc_len;
    total_fu_len += update_fu_len;
    total_c_len += update_c_len;
    total_u_len += update_u_len;
}
References total_c_len, total_fc_len, total_files_done, total_fu_len, total_u_len, update_c_len, update_fc_len, update_fu_len, and update_u_len.
Referenced by do_one_file().
uiFileInfoEnd()
void UiPacker::uiFileInfoEnd () virtual
Definition at line 588 of file ui.cpp.
{ uiUpdate(); }
References uiUpdate().
uiFileInfoStart()
bool UiPacker::uiFileInfoStart () virtual
info
Definition at line 569 of file ui.cpp.
{
    total_files++;
    int fg = con_fg(stdout, FG_CYAN);
    con_fprintf(stdout, "%s [%s, %s]\n", pb->fi->getName(), pb->getFullName(opt), pb->getName());
    fg = con_fg(stdout, fg);
    UNUSED(fg);
    if (pb->ph.c_len > 0) {
        con_fprintf(stdout, "  %8llu bytes", pb->file_size_u);
        con_fprintf(stdout, ", compressed by UPX %d, method %d, level %d, filter 0x%02x/0x%02x\n",
                    pb->ph.version, pb->ph.method, pb->ph.level, pb->ph.filter, pb->ph.filter_cto);
        return false;
    } else {
        con_fprintf(stdout, "  %8llu bytes", pb->file_size_u);
        con_fprintf(stdout, ", not compressed by UPX\n");
        return true;
    }
}
References PackHeader::c_len, con_fg, con_fprintf, PackerBase::fi, PackerBase::file_size_u, PackHeader::filter, PackHeader::filter_cto, PackerBase::getFullName(), PackerBase::getName(), FileBase::getName(), PackHeader::level, PackHeader::method, opt, pb, PackerBase::ph, total_files, UNUSED, and PackHeader::version.
uiFileInfoTotal()
void UiPacker::uiFileInfoTotal () static
Definition at line 590 of file ui.cpp.
{}
Referenced by do_files().
uiFooter()
void UiPacker::uiFooter (const char * n) static
Definition at line 608 of file ui.cpp.
{
    static upx_std_atomic(bool) done;
    if (done)
        return;
    done = true;
    if (opt->verbose >= 1) {
        assert(total_files >= total_files_done);
        unsigned n1 = total_files;
        unsigned n2 = total_files_done;
        unsigned n3 = total_files - total_files_done;
        if (n3 == 0)
            con_fprintf(stdout, "\n%s %u file%s.\n", t, n1, n1 == 1 ? "" : "s");
        else
            con_fprintf(stdout, "\n%s %u file%s: %u ok, %u error%s.\n", t, n1, n1 == 1 ? "" : "s",
                        n2, n3, n3 == 1 ? "" : "s");
    }
}
References con_fprintf, opt, total_files, total_files_done, and upx_std_atomic.
Referenced by uiPackTotal(), uiTestTotal(), and uiUnpackTotal().
uiHeader()
void UiPacker::uiHeader () static
util
Definition at line 596 of file ui.cpp.
{
    static upx_std_atomic(bool) done;
    if (done)
        return;
    done = true;
    if (opt->cmd == CMD_TEST || opt->cmd == CMD_FILEINFO)
        return;
    if (opt->verbose >= 1) {
        con_fprintf(stdout, "%s%s", header_line1, header_line2);
    }
}
References CMD_FILEINFO, CMD_TEST, con_fprintf, header_line1, header_line2, opt, and upx_std_atomic.
Referenced by do_files().
uiList()
void UiPacker::uiList () virtual
Definition at line 518 of file ui.cpp.
                      {
    const char *name = pb->fi->getName();
    con_fprintf(
        stdout, "%s\n",
        mkline(pb->ph.u_file_size, pb->file_size, pb->ph.u_len, pb->ph.c_len, pb->getName(), name));
    printSetNl(0);
}
References PackHeader::c_len, con_fprintf, PackerBase::fi, PackerBase::file_size, PackerBase::getName(), FileBase::getName(), mkline(), pb, PackerBase::ph, printSetNl(), PackHeader::u_file_size, and PackHeader::u_len.
uiListEnd()
void UiPacker::uiListEnd () virtual
Definition at line 526 of file ui.cpp.
{ uiUpdate(); }
References uiUpdate().
uiListStart()
void UiPacker::uiListStart () virtual
list
Definition at line 516 of file ui.cpp.
{ total_files++; }
References total_files.
uiListTotal()
void UiPacker::uiListTotal (bool uncompress = false) static
Definition at line 528 of file ui.cpp.
{
    if (opt->verbose >= 1 && total_files >= 2) {
        char name[32];
        upx_safe_snprintf(name, sizeof(name), "[ %u file%s ]", total_files_done,
                          total_files_done == 1 ? "" : "s");
        con_fprintf(
            stdout, "%s%s\n", header_line2,
            mkline(total_fu_len, total_fc_len, total_u_len, total_c_len, "", name, decompress));
        printSetNl(0);
    }
}
References con_fprintf, header_line2, mkline(), opt, printSetNl(), total_c_len, total_fc_len, total_files, total_files_done, total_fu_len, total_u_len, and upx_safe_snprintf().
Referenced by do_files(), uiPackTotal(), and uiUnpackTotal().
uiPackEnd()
void UiPacker::uiPackEnd (const OutputFile * fo) virtual
Definition at line 454 of file ui.cpp.
{
    uiUpdate(fo->st_size());
    if (s->mode == M_QUIET)
        return;
    if (s->mode == M_MSG) {
        // We must put this here and not in endCallback() as we may
        // have multiple passes.
        printClearLine(stdout);
    }
    const char *name = pb->fi->getName();
    if (opt->output_name)
        name = opt->output_name;
    else if (opt->to_stdout)
        name = "<stdout>";
    con_fprintf(stdout, "%s\n",
                mkline(pb->ph.u_file_size, fo->st_size(), pb->ph.u_len, pb->ph.c_len, pb->getName(),
                       fn_basename(name)));
    printSetNl(0);
}
References PackHeader::c_len, con_fprintf, PackerBase::fi, fn_basename(), PackerBase::getName(), FileBase::getName(), M_MSG, M_QUIET, mkline(), opt, pb, PackerBase::ph, printClearLine(), printSetNl(), OutputFile::st_size(), PackHeader::u_file_size, PackHeader::u_len, and uiUpdate().
uiPackStart()
void UiPacker::uiPackStart (const OutputFile * fo) virtual
pack
Definition at line 449 of file ui.cpp.
{
    total_files++;
    UNUSED(fo);
}
References total_files, and UNUSED.
uiPackTotal()
void UiPacker::uiPackTotal () static
Definition at line 476 of file ui.cpp.
{
    uiListTotal();
    uiFooter("Packed");
}
References uiFooter(), and uiListTotal().
Referenced by do_files().
uiTestEnd()
void UiPacker::uiTestEnd () virtual
Definition at line 554 of file ui.cpp.
{
    if (opt->verbose >= 1) {
        con_fprintf(stdout, "[OK]\n");
        fflush(stdout);
        printSetNl(0);
    }
    uiUpdate();
}
References con_fprintf, opt, printSetNl(), and uiUpdate().
uiTestStart()
void UiPacker::uiTestStart () virtual
test
Definition at line 544 of file ui.cpp.
{
    total_files++;
    if (opt->verbose >= 1) {
        con_fprintf(stdout, "testing %s ", pb->fi->getName());
        fflush(stdout);
        printSetNl(1);
    }
}
References con_fprintf, PackerBase::fi, FileBase::getName(), opt, pb, printSetNl(), and total_files.
uiTestTotal()
void UiPacker::uiTestTotal () static
Definition at line 563 of file ui.cpp.
{ uiFooter("Tested"); }
References uiFooter().
Referenced by do_files().
uiUnpackEnd()
void UiPacker::uiUnpackEnd (const OutputFile * fo) virtual
Definition at line 490 of file ui.cpp.
{
    uiUpdate(-1, fo->getBytesWritten());
    if (s->mode == M_QUIET)
        return;
    const char *name = pb->fi->getName();
    if (opt->output_name)
        name = opt->output_name;
    else if (opt->to_stdout)
        name = "<stdout>";
    con_fprintf(stdout, "%s\n",
                mkline(fo->getBytesWritten(), pb->file_size, pb->ph.u_len, pb->ph.c_len,
                       pb->getName(), fn_basename(name), true));
    printSetNl(0);
}
References PackHeader::c_len, con_fprintf, PackerBase::fi, PackerBase::file_size, fn_basename(), OutputFile::getBytesWritten(), PackerBase::getName(), FileBase::getName(), M_QUIET, mkline(), opt, pb, PackerBase::ph, printSetNl(), PackHeader::u_len, and uiUpdate().
uiUnpackStart()
void UiPacker::uiUnpackStart (const OutputFile * fo) virtual
unpack
Definition at line 485 of file ui.cpp.
{
    total_files++;
    UNUSED(fo);
}
References total_files, and UNUSED.
uiUnpackTotal()
void UiPacker::uiUnpackTotal () static
Definition at line 507 of file ui.cpp.
{
    uiListTotal(true);
    uiFooter("Unpacked");
}
References uiFooter(), and uiListTotal().
Referenced by do_files().
uiUpdate()
void UiPacker::uiUpdate (upx_off_t fc_len = -1, upx_off_t fu_len = -1) protected virtual
Definition at line 626 of file ui.cpp.
{
    update_fc_len = (fc_len >= 0) ? fc_len : pb->file_size_u;
    update_fu_len = (fu_len >= 0) ? fu_len : pb->ph.u_file_size;
    update_c_len = pb->ph.c_len;
    update_u_len = pb->ph.u_len;
}
References PackHeader::c_len, PackerBase::file_size_u, pb, PackerBase::ph, PackHeader::u_file_size, PackHeader::u_len, update_c_len, update_fc_len, update_fu_len, and update_u_len.
Referenced by uiFileInfoEnd(), uiListEnd(), uiPackEnd(), uiTestEnd(), and uiUnpackEnd().
Member Data Documentation
cb
upx_callback_t UiPacker::cb = {} protected
Definition at line 90 of file ui.h.
Referenced by endCallback(), getCallback(), progress_callback(), startCallback(), UiPacker(), and ~UiPacker().
pb
const PackerBase* const UiPacker::pb protected
Definition at line 87 of file ui.h.
Referenced by printInfo(), startCallback(), uiFileInfoStart(), uiList(), uiPackEnd(), uiTestStart(), uiUnpackEnd(), and uiUpdate().
total_c_len
upx_uint64_t UiPacker::total_c_len = 0 static protected
Definition at line 99 of file ui.h.
Referenced by uiConfirmUpdate(), and uiListTotal().
total_fc_len
upx_uint64_t UiPacker::total_fc_len = 0 static protected
Definition at line 101 of file ui.h.
Referenced by uiConfirmUpdate(), and uiListTotal().
total_files
unsigned UiPacker::total_files = 0 static protected
Definition at line 97 of file ui.h.
Referenced by uiFileInfoStart(), uiFooter(), uiListStart(), uiListTotal(), uiPackStart(), uiTestStart(), and uiUnpackStart().
total_files_done
unsigned UiPacker::total_files_done = 0 static protected
Definition at line 98 of file ui.h.
Referenced by uiConfirmUpdate(), uiFooter(), and uiListTotal().
total_fu_len
upx_uint64_t UiPacker::total_fu_len = 0 static protected
Definition at line 102 of file ui.h.
Referenced by uiConfirmUpdate(), and uiListTotal().
total_u_len
upx_uint64_t UiPacker::total_u_len = 0 static protected
Definition at line 100 of file ui.h.
Referenced by uiConfirmUpdate(), and uiListTotal().
ui_pass
int UiPacker::ui_pass = 0
Definition at line 82 of file ui.h.
ui_total_passes
int UiPacker::ui_total_passes = 0
Definition at line 83 of file ui.h.
update_c_len
unsigned UiPacker::update_c_len = 0 static protected
Definition at line 103 of file ui.h.
Referenced by uiConfirmUpdate(), and uiUpdate().
update_fc_len
unsigned UiPacker::update_fc_len = 0 static protected
Definition at line 105 of file ui.h.
Referenced by uiConfirmUpdate(), and uiUpdate().
update_fu_len
unsigned UiPacker::update_fu_len = 0 static protected
Definition at line 106 of file ui.h.
Referenced by uiConfirmUpdate(), and uiUpdate().
update_u_len
unsigned UiPacker::update_u_len = 0 static protected
Definition at line 104 of file ui.h.
Referenced by uiConfirmUpdate(), and uiUpdate().
The documentation for this class was generated from the following files:
src/ui.h
src/ui.cpp