My Project: PackVmlinuxBase< TElfClass > Class Template Reference
PackVmlinuxBase< TElfClass > Class Template Reference abstract
vmlinx/i386 (bare binary Linux kernel image)
#include <p_vmlinx.h>
Public Member Functions
PackVmlinuxBase (InputFile *, unsigned, unsigned, unsigned, char const *)
virtual ~PackVmlinuxBase ()
virtual int getVersion () const override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Types
typedef TElfClass ElfClass
typedef ElfClass::BeLePolicy BeLePolicy
typedef ElfClass::ElfITypes ElfITypes
typedef ElfClass::TE16 TE16
typedef ElfClass::TE32 TE32
typedef ElfClass::TE64 TE64
typedef ElfITypes::Addr Addr
typedef ElfClass::Ehdr Ehdr
typedef ElfClass::Shdr Shdr
typedef ElfClass::Phdr Phdr
typedef ElfClass::Dyn Dyn
typedef ElfClass::Sym Sym
Protected Member Functions
virtual Shdr const * getElfSections ()
virtual int getStrategy (Filter &)
virtual bool is_valid_e_entry (Addr)=0
virtual bool has_valid_vmlinux_head ()=0
virtual tribool canPack () override
virtual void pack (OutputFile *fo) override
virtual tribool canUnpack () override
virtual void unpack (OutputFile *fo) override
virtual unsigned write_vmlinux_head (OutputFile *fo, Shdr *stxt)=0
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Static Protected Member Functions
static int __acc_cdecl_qsort compare_Phdr (void const *aa, void const *bb)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes
unsigned int const my_e_machine
unsigned char const my_elfclass
unsigned char const my_elfdata
char const *const my_boot_label
int n_ptload
unsigned sz_ptload
unsigned paddr_min
Phdr * phdri
Shdr * shdri
char * shstrtab
Shdr * p_text
Shdr * p_note0
Shdr * p_note1
Ehdr ehdri
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Detailed Description
template<class TElfClass>
class PackVmlinuxBase< TElfClass >
vmlinx/i386 (bare binary Linux kernel image)
Definition at line 41 of file p_vmlinx.h.
Member Typedef Documentation
Addr
template<class TElfClass > typedef ElfITypes::Addr PackVmlinuxBase< TElfClass >::Addr protected
Definition at line 52 of file p_vmlinx.h.
BeLePolicy
template<class TElfClass > typedef ElfClass::BeLePolicy PackVmlinuxBase< TElfClass >::BeLePolicy protected
Definition at line 46 of file p_vmlinx.h.
Dyn
template<class TElfClass > typedef ElfClass::Dyn PackVmlinuxBase< TElfClass >::Dyn protected
Definition at line 57 of file p_vmlinx.h.
Ehdr
template<class TElfClass > typedef ElfClass::Ehdr PackVmlinuxBase< TElfClass >::Ehdr protected
Definition at line 54 of file p_vmlinx.h.
ElfClass
template<class TElfClass > typedef TElfClass PackVmlinuxBase< TElfClass >::ElfClass protected
Definition at line 45 of file p_vmlinx.h.
ElfITypes
template<class TElfClass > typedef ElfClass::ElfITypes PackVmlinuxBase< TElfClass >::ElfITypes protected
Definition at line 47 of file p_vmlinx.h.
Phdr
template<class TElfClass > typedef ElfClass::Phdr PackVmlinuxBase< TElfClass >::Phdr protected
Definition at line 56 of file p_vmlinx.h.
Shdr
template<class TElfClass > typedef ElfClass::Shdr PackVmlinuxBase< TElfClass >::Shdr protected
Definition at line 55 of file p_vmlinx.h.
super
template<class TElfClass > typedef Packer PackVmlinuxBase< TElfClass >::super private
Definition at line 43 of file p_vmlinx.h.
Sym
template<class TElfClass > typedef ElfClass::Sym PackVmlinuxBase< TElfClass >::Sym protected
Definition at line 58 of file p_vmlinx.h.
TE16
template<class TElfClass > typedef ElfClass::TE16 PackVmlinuxBase< TElfClass >::TE16 protected
Definition at line 49 of file p_vmlinx.h.
TE32
template<class TElfClass > typedef ElfClass::TE32 PackVmlinuxBase< TElfClass >::TE32 protected
Definition at line 50 of file p_vmlinx.h.
TE64
template<class TElfClass > typedef ElfClass::TE64 PackVmlinuxBase< TElfClass >::TE64 protected
Definition at line 51 of file p_vmlinx.h.
Constructor & Destructor Documentation
PackVmlinuxBase()
template<class T > static const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const static CLANG_FORMAT_DUMMY_STATEMENT const CLANG_FORMAT_DUMMY_STATEMENT PackVmlinuxBase< T >::PackVmlinuxBase (InputFile * f, unsigned e_machine, unsigned elfclass, unsigned elfdata, char const * boot_label)
Definition at line 59 of file p_vmlinx.cpp.
                                                                  :
    super(f),
    my_e_machine(e_machine), my_elfclass(elfclass), my_elfdata(elfdata),
    my_boot_label(boot_label),
    n_ptload(0), phdri(nullptr), shdri(nullptr), shstrtab(nullptr)
{
    ElfClass::compileTimeAssertions();
    bele = N_BELE_CTP::getRTP((const BeLePolicy*) nullptr);
}
~PackVmlinuxBase()
template<class T > PackVmlinuxBase< T >::~PackVmlinuxBase virtual
Definition at line 72 of file p_vmlinx.cpp.
{
    delete [] phdri;
    delete [] shdri;
    delete [] shstrtab;
}
References shstrtab.
Member Function Documentation
canPack()
template<class T > tribool PackVmlinuxBase< T >::canPack override protected virtual
Implements PackerBase.
Definition at line 158 of file p_vmlinx.cpp.
{
    fi->seek(0, SEEK_SET);
    fi->readx(&ehdri, sizeof(ehdri));
    // now check the ELF header
    if (memcmp(&ehdri, "\x7f\x45\x4c\x46", 4)
    ||  ehdri.e_ident[Ehdr::EI_CLASS] != my_elfclass
    ||  ehdri.e_ident[Ehdr::EI_DATA] != my_elfdata
    ||  ehdri.e_ident[Ehdr::EI_VERSION] != Ehdr::EV_CURRENT
    ||  !memcmp(&ehdri.e_ident[8], "FreeBSD", 7)  // branded
    ||  ehdri.e_machine != my_e_machine
    ||  ehdri.e_version != 1  // version
    ||  ehdri.e_ehsize != sizeof(ehdri)  // different <elf.h> ?
    ) {
        return false;
    }
    // additional requirements for vmlinux
    if (ehdri.e_type != Ehdr::ET_EXEC
    ||  ehdri.e_phoff != sizeof(ehdri)  // Phdr not contiguous with Ehdr
    ||  ehdri.e_phentsize!=sizeof(Phdr)
    ||  !is_valid_e_entry(ehdri.e_entry)
    ) {
        return false;
    }
    // A Linux kernel must have a __ksymtab section. [??]
    Shdr const *p, *const shstrsec = getElfSections();
    if (nullptr==shstrsec) {
        return false;
    }
    {
        int j;
        for (p = shdri, j= ehdri.e_shnum; --j>=0; ++p) {
            if (Shdr::SHT_PROGBITS==p->sh_type
            && p->sh_name < shstrsec->sh_size
            && 0==strcmp("__ksymtab", p->sh_name + shstrtab)) {
                break;
            }
        }
        if (j < 0) {
            return false;
        }
    }
    phdri = new Phdr[(unsigned) ehdri.e_phnum];
    fi->seek(ehdri.e_phoff, SEEK_SET);
    fi->readx(phdri, ehdri.e_phnum * sizeof(*phdri));
    // Put PT_LOAD together at the beginning, ascending by .p_paddr.
    upx_qsort(phdri, ehdri.e_phnum, sizeof(*phdri), compare_Phdr);
    // Find convex hull of physical addresses, and count the PT_LOAD.
    // Ignore ".bss": .p_filesz < .p_memsz
    unsigned phys_lo= ~0u, phys_hi= 0u;
    for (unsigned j = 0; j < ehdri.e_phnum; ++j) {
        if (Phdr::PT_LOAD==phdri[j].p_type) {
            // Check for general sanity (not necessarily required.)
            if (0xfff & (phdri[j].p_offset | phdri[j].p_paddr
                       | phdri[j].p_align  | phdri[j].p_vaddr) ) {
                return false;
            }
            if (phys_lo > phdri[j].p_paddr) {
                phys_lo = phdri[j].p_paddr;
            }
            if (phys_hi < (phdri[j].p_filesz + phdri[j].p_paddr)) {
                phys_hi = (phdri[j].p_filesz + phdri[j].p_paddr);
            }
            ++n_ptload;
        }
    }
    paddr_min = phys_lo;
    sz_ptload = phys_hi - phys_lo;
    return 0 < n_ptload;
}
References memcmp(), SEEK_SET, shstrtab, strcmp(), and upx_qsort.
canUnpack()
template<class T > tribool PackVmlinuxBase< T >::canUnpack override protected virtual
Implements PackerBase.
Definition at line 568 of file p_vmlinx.cpp.
{
    fi->seek(0, SEEK_SET);
    fi->readx(&ehdri, sizeof(ehdri));
    // now check the ELF header
    if (memcmp(&ehdri, "\x7f\x45\x4c\x46", 4)
    ||  ehdri.e_ident[Ehdr::EI_CLASS] != my_elfclass
    ||  ehdri.e_ident[Ehdr::EI_DATA] != my_elfdata
    ||  ehdri.e_ident[Ehdr::EI_VERSION] != Ehdr::EV_CURRENT
    ||  !memcmp(&ehdri.e_ident[8], "FreeBSD", 7)  // branded
    ||  ehdri.e_machine != my_e_machine
    ||  ehdri.e_version != 1  // version
    ||  ehdri.e_ehsize != sizeof(ehdri)  // different <elf.h> ?
    )
        return false;
    if (ehdri.e_type != Ehdr::ET_REL
    //i386 fails  ||  ehdri.e_shoff != sizeof(ehdri)  // Shdr not contiguous with Ehdr
    ||  ehdri.e_shentsize!=sizeof(Shdr)
    ||  ehdri.e_shnum < 4
    ||  (unsigned)file_size < (ehdri.e_shnum * sizeof(Shdr) + ehdri.e_shoff)
    )
        return false;
    // find the .shstrtab section
    Shdr const *const shstrsec = getElfSections();
    if (nullptr==shstrsec) {
        return false;
    }
    // check for .text .note .note  and sane (.sh_size + .sh_offset)
    p_note0 = p_note1 = p_text = nullptr;
    int j;
    Shdr *p;
    for (p= shdri, j= ehdri.e_shnum; --j>=0; ++p) {
        if ((unsigned)file_size < (p->sh_size + p->sh_offset)
        || (5+ p->sh_name) < p->sh_name  // wrap: ignore malformed
        ||  shstrsec->sh_size < (5+ p->sh_name) ) {
            continue;
        }
        if (0==strcmp(".text", shstrtab + p->sh_name)) {
            p_text = p;
        }
        if (0==strcmp(".note", shstrtab + p->sh_name)) {
            if (nullptr==p_note0) {
                p_note0 = p;
            } else
            if (nullptr==p_note1) {
                p_note1 = p;
            }
        }
    }
    if (nullptr==p_text || nullptr==p_note0 || nullptr==p_note1) {
        return false;
    }
    char buf[1024];
    fi->seek(p_text->sh_offset + p_text->sh_size - sizeof(buf), SEEK_SET);
    fi->readx(buf, sizeof(buf));
    if (!getPackHeader(buf, sizeof(buf)))
        return -1; // format is known, but definitely is not packed
    return true;
}
References buf, memcmp(), SEEK_SET, shstrtab, and strcmp().
compare_Phdr()
template<class T > int __acc_cdecl_qsort PackVmlinuxBase< T >::compare_Phdr (void const * aa, void const * bb) static protected
Definition at line 92 of file p_vmlinx.cpp.
{
    Phdr const *const a = (Phdr const *)aa;
    Phdr const *const b = (Phdr const *)bb;
    unsigned const xa = a->p_type - Phdr::PT_LOAD;
    unsigned const xb = b->p_type - Phdr::PT_LOAD;
            if (xa < xb)         return -1;  // PT_LOAD first
            if (xa > xb)         return  1;
    if (a->p_paddr < b->p_paddr) return -1;  // ascending by .p_paddr
    if (a->p_paddr > b->p_paddr) return  1;
    // What could remain?
    // try to make sort order deterministic and just compare more fields
#define CMP(field) \
    if (a->field != b->field) return a->field < b->field ? -1 : 1
    CMP(p_offset);
    CMP(p_vaddr);
    CMP(p_filesz);
    CMP(p_memsz);
    CMP(p_flags);
    CMP(p_align);
#undef CMP
    return 0;
}
getElfSections()
template<class T > T::Shdr const * PackVmlinuxBase< T >::getElfSections protected virtual
Definition at line 117 of file p_vmlinx.cpp.
{
    unsigned const e_shnum = ehdri.e_shnum;
    if (ehdri.e_shentsize != sizeof(*shdri)
    ||  file_size_u < ehdri.e_shoff
    ||  file_size_u < ehdri.e_shoff + mem_size(ehdri.e_shentsize, e_shnum)) {
        infoWarning("bad ElfXX_Shdrs");
        return nullptr;
    }
    shdri = new Shdr[(unsigned) e_shnum];
    fi->seek(ehdri.e_shoff, SEEK_SET);
    fi->readx(shdri, e_shnum * sizeof(*shdri));
    unsigned const e_shstrndx = ehdri.e_shstrndx;
    if (e_shnum <= e_shstrndx) {
        infoWarning("bad .e_shstrndx %#x", e_shstrndx);
        return nullptr;
    }
    Shdr const *p = &shdri[e_shstrndx];
    if (Shdr::SHT_STRTAB==p->sh_type
    &&  p->sh_offset  <= (file_size_u - sizeof(*shdri))
    &&  p->sh_size    <= (file_size_u - p->sh_offset)
    &&  p->sh_name    <= (file_size_u - p->sh_offset)
    &&  10            <= (file_size_u - p->sh_name)
        // 10 == (1+ strlen(".shstrtab"))
    ) {
        if (p->sh_size <= p->sh_name) {
            infoWarning("bad .shstrtab _Shdr[%u]", (unsigned)ehdri.e_shstrndx);
            return nullptr;
        }
        shstrtab = new char[1+ p->sh_size];
        fi->seek(p->sh_offset, SEEK_SET);
        fi->readx(shstrtab, p->sh_size);
        shstrtab[p->sh_size] = '\0';
        if (0==strcmp(".shstrtab", shstrtab + p->sh_name)) {
            return p;
        }
    }
    return nullptr;
}
References infoWarning(), mem_size(), SEEK_SET, shstrtab, and strcmp().
getStrategy()
template<class T > int PackVmlinuxBase< T >::getStrategy (Filter &) protected virtual
Definition at line 80 of file p_vmlinx.cpp.
{
    // Called just before reading and compressing each block.
    // Might want to adjust blocksize, etc.
    // If user specified the filter, then use it (-2==strategy).
    // Else try the first two filters, and pick the better (2==strategy).
    return (opt->no_filter ? -3 : ((opt->filter > 0) ? -2 : 2));
}
getVersion()
template<class TElfClass > virtual int PackVmlinuxBase< TElfClass >::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 63 of file p_vmlinx.h.
{ return 13; }
has_valid_vmlinux_head()
template<class TElfClass > virtual bool PackVmlinuxBase< TElfClass >::has_valid_vmlinux_head () protected pure virtual
Implemented in PackVmlinuxI386, PackVmlinuxARMEL, PackVmlinuxARMEB, PackVmlinuxPPC32, PackVmlinuxPPC64LE, and PackVmlinuxAMD64.
is_valid_e_entry()
template<class TElfClass > virtual bool PackVmlinuxBase< TElfClass >::is_valid_e_entry (Addr) protected pure virtual
pack()
template<class T > void PackVmlinuxBase< T >::pack (OutputFile * fo) override protected virtual
Implements Packer.
Definition at line 238 of file p_vmlinx.cpp.
{
    unsigned fo_off = 0;
    Ehdr ehdro;
    TE32 tmp_u32;
    // nullptr
    // .text(PT_LOADs) .note(1st page) .note(rest)
    // .shstrtab .symtab .strtab
    Shdr shdro[1+3+3];
    memset(shdro, 0, sizeof(shdro));
    ibuf.alloc(file_size);
    obuf.allocForCompression(file_size);
    // .e_ident, .e_machine, .e_version, .e_flags
    memcpy(&ehdro, &ehdri, sizeof(ehdro));
    ehdro.e_type = Ehdr::ET_REL;
    ehdro.e_entry = 0;
    ehdro.e_phoff = 0;
    ehdro.e_shoff = sizeof(ehdro);
    ehdro.e_phentsize = 0;
    ehdro.e_phnum = 0;
    ehdro.e_shnum = 1+3+3;
    ehdro.e_shstrndx = 4;
    fo->write(&ehdro, sizeof(ehdro)); fo_off+= sizeof(ehdro);
    fo->write(shdro, sizeof(shdro)); fo_off+= sizeof(shdro);
// Notice overlap [containment] of physical PT_LOAD[2] into PTLOAD[1]
// in this vmlinux for x86_64 from Fedora Core 6 on 2007-01-07:
//Program Headers:
//  Type           Offset             VirtAddr           PhysAddr
//                 FileSiz            MemSiz              Flags  Align
//  LOAD           0x0000000000200000 0xffffffff80200000 0x0000000000200000
//                 0x000000000034bce8 0x000000000034bce8  R E    200000
//  LOAD           0x000000000054c000 0xffffffff8054c000 0x000000000054c000
//                 0x00000000000ed004 0x00000000001702a4  RWE    200000
//  LOAD           0x0000000000800000 0xffffffffff600000 0x00000000005f5000
//                 0x0000000000000c08 0x0000000000000c08  RWE    200000
//  NOTE           0x0000000000000000 0x0000000000000000 0x0000000000000000
//                 0x0000000000000000 0x0000000000000000  R      8
// Therefore we must "compose" the convex hull to be loaded.
    ph.u_len = sz_ptload;
    memset(ibuf, 0, sz_ptload);
    for (unsigned j = 0; j < ehdri.e_phnum; ++j) {
        if (Phdr::PT_LOAD==phdri[j].p_type) {
            fi->seek(phdri[j].p_offset, SEEK_SET);
            fi->readx(ibuf + ((unsigned) phdri[j].p_paddr - paddr_min), phdri[j].p_filesz);
        }
    }
    checkAlreadyPacked(ibuf + (ph.u_len - 1024), 1024);
    // prepare filter
    ph.filter = 0;
    Filter ft(ph.level);
    ft.buf_len = ph.u_len;
    ft.addvalue = 0;  // we are independent of actual runtime address; see ckt32
    upx_compress_config_t cconf; cconf.reset();
    // limit stack size needed for runtime decompression
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    unsigned ppc32_extra = 0;
    if (Ehdr::EM_PPC==my_e_machine) {
        // output layout:
        //      .long UPX_MAGIC_LE32
        //      .long L20 - L10
        // L10:
        //      b_info for Ehdr; compressed Ehdr; .balign 4  // one block only
        //      b_info for LOAD; compressed LOAD; .balign 4  // possibly many blocks
        //          // This allows per-block filters!
        // L20:
        //      b f_decompress
        // +4:  f_unfilter(char *buf, unsigned len, unsigned cto8, unsigned ftid)
        //          // Code for multiple filters can "daisy chain" on ftid.
        //      f_decompress(char const *src, unsigned  src_len,
        //                   char       *dst, unsigned *dst_len, int method)
        unsigned tmp;
        tmp = UPX_MAGIC_LE32; fo->write(&tmp, sizeof(tmp)); fo_off += sizeof(tmp);
        tmp = 0;              fo->write(&tmp, sizeof(tmp)); fo_off += sizeof(tmp);
        ppc32_extra += 2*sizeof(tmp);
        unsigned const len_unc = sizeof(ehdri) + sizeof(Phdr) * ehdri.e_phnum;
        MemBuffer unc_hdr(len_unc);
        MemBuffer cpr_hdr; cpr_hdr.allocForCompression(len_unc);
        memcpy(&unc_hdr[0],             &ehdri, sizeof(ehdri));
        memcpy(&unc_hdr[sizeof(ehdri)],  phdri, sizeof(Phdr) * ehdri.e_phnum);
        unsigned len_cpr = 0;
        int const r = upx_compress(unc_hdr, len_unc, cpr_hdr, &len_cpr,
            nullptr, ph.method, 10, nullptr, nullptr );
        if (UPX_E_OK!=r || len_unc<=len_cpr)  // FIXME: allow no compression
            throwInternalError("Ehdr compression failed");
        packed_struct(b_info) { // 12-byte header before each compressed block
            NE32 sz_unc;  // uncompressed_size
            NE32 sz_cpr;  //   compressed_size
            unsigned char b_method;  // compression algorithm
            unsigned char b_ftid;  // filter id
            unsigned char b_cto8;  // filter parameter
            unsigned char b_unused;  // FIXME: !=0  for partial-block unfilter
            // NE32 f_offset, f_len;  // only if    partial-block unfilter
        };
        struct b_info hdr_info;
        set_be32(&hdr_info.sz_unc, len_unc);
        set_be32(&hdr_info.sz_cpr, len_cpr);
        hdr_info.b_method = ph.method;
        hdr_info.b_ftid = 0;
        hdr_info.b_cto8 = 0;
        hdr_info.b_unused = 0;
        fo->write(&hdr_info, sizeof(hdr_info)); fo_off += sizeof(hdr_info);
        unsigned const frag = (3& (0u-len_cpr));
        ppc32_extra += sizeof(hdr_info) + len_cpr + frag;
        fo_off += len_cpr + frag;
        memset(&cpr_hdr[len_cpr], 0, frag);  // valgrind only
        fo->write(cpr_hdr, len_cpr + frag);
        // Partial filter: .text and following contiguous SHF_EXECINSTR
        upx_bytep f_ptr = ibuf;
        unsigned  f_len = 0;
        Shdr const *shdr = 1+ shdri;  // skip empty shdr[0]
        if (ft.buf_len==0  // not specified yet  FIXME: was set near construction
        && (Shdr::SHF_ALLOC     & shdr->sh_flags)
        && (Shdr::SHF_EXECINSTR & shdr->sh_flags)) {
            // shdr[1] is instructions (probably .text)
            f_ptr = ibuf + (unsigned) (shdr->sh_offset - phdri[0].p_offset);
            f_len = shdr->sh_size;
            ++shdr;
            for (int j= ehdri.e_shnum - 2; --j>=0; ++shdr) {
                unsigned prev_end = shdr[-1].sh_size + shdr[-1].sh_offset;
                prev_end += ~(0u-shdr[0].sh_addralign) & (0u-prev_end);  // align_up
                if ((Shdr::SHF_ALLOC     & shdr->sh_flags)
                &&  (Shdr::SHF_EXECINSTR & shdr->sh_flags)
                &&  shdr[0].sh_offset==prev_end) {
                    f_len += shdr->sh_size;
                }
                else {
                    break;
                }
            }
        }
        else { // ft.buf_len already specified, or Shdr[1] not instructions
            f_ptr = ibuf;
            f_len = ph.u_len;
        }
        compressWithFilters(ibuf, ph.u_len, obuf,
            f_ptr, f_len,  // filter range
            nullptr, 0,  // hdr_ptr, hdr_len
            &ft, 512, &cconf, getStrategy(ft));
        set_be32(&hdr_info.sz_unc, ph.u_len);
        set_be32(&hdr_info.sz_cpr, ph.c_len);
        hdr_info.b_ftid = ft.id;
        hdr_info.b_cto8 = ft.cto;
        if (ph.u_len!=f_len) {
            hdr_info.b_unused = 1;  // flag for partial filter
        }
        fo->write(&hdr_info, sizeof(hdr_info)); fo_off += sizeof(hdr_info);
        ppc32_extra += sizeof(hdr_info);
        if (ph.u_len!=f_len) {
            set_be32(&hdr_info.sz_unc, f_ptr - (upx_bytep) ibuf);
            set_be32(&hdr_info.sz_cpr, f_len);
            fo->write(&hdr_info, 2*sizeof(unsigned)); fo_off += 2*sizeof(unsigned);
            ppc32_extra += 2*sizeof(unsigned);
        }
    }
    else {
        compressWithFilters(&ft, 512, &cconf, getStrategy(ft));
    }
    unsigned const txt_c_len = ph.c_len;
    const unsigned lsize = getLoaderSize();
    defineDecompressorSymbols();
    defineFilterSymbols(&ft);
    relocateLoader();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, lsize);
#define shstrtab local_shstrtab // avoid -Wshadow warning
    char const shstrtab[]= "\0.text\0.note\0.shstrtab\0.symtab\0.strtab";
    char const *p = shstrtab;
    while (0!=*p++) ;
    shdro[1].sh_name = ptr_diff(p, shstrtab);
    shdro[1].sh_type = Shdr::SHT_PROGBITS;
    shdro[1].sh_flags = Shdr::SHF_ALLOC | Shdr::SHF_EXECINSTR;
    shdro[1].sh_offset = fo_off - ppc32_extra;
    shdro[1].sh_size = ppc32_extra + txt_c_len + lsize;  // plus more ...
    shdro[1].sh_addralign = 1;  // default
    fo_off += write_vmlinux_head(fo, &shdro[1]);
    fo->write(obuf, txt_c_len); fo_off += txt_c_len;
    unsigned const a = (shdro[1].sh_addralign -1) & (0u-(ppc32_extra + txt_c_len));
    if (0!=a) { // align
        fo_off += a;
        shdro[1].sh_size += a;
        fo->seek(a, SEEK_CUR);
    }
    fo->write(loader, lsize); fo_off += lsize;
#if 0
    printf("%-13s: compressed   : %8u bytes\n", getName(), txt_c_len);
    printf("%-13s: decompressor : %8u bytes\n", getName(), lsize);
#endif
    verifyOverlappingDecompression();
    // .note with 1st page --------------------------------
    ph.u_len = phdri[0].p_offset;
    fi->seek(0, SEEK_SET);
    fi->readx(ibuf, ph.u_len);
    compress(ibuf, ph.u_len, obuf, &cconf);
    while (0!=*p++) ;
    shdro[2].sh_name = ptr_diff(p, shstrtab);
    shdro[2].sh_type = Shdr::SHT_NOTE;
    shdro[2].sh_offset = fo_off;
    shdro[2].sh_size = sizeof(ph.u_len) + ph.c_len;
    shdro[2].sh_addralign = 1;
    tmp_u32 = ph.u_len; fo->write(&tmp_u32, 4);
    fo->write(obuf, ph.c_len); fo_off += shdro[2].sh_size;
    // .note with rest     --------------------------------
    ph.u_len = file_size - (sz_ptload + phdri[0].p_offset);
    fi->seek(sz_ptload + phdri[0].p_offset, SEEK_SET);
    fi->readx(ibuf, ph.u_len);
    // Temporarily decrease ph.level by about (1+ log2(sz_rest / sz_ptload))
    // to avoid spending unreasonable effort compressing large symbol tables
    // that are discarded 99.9% of the time anyway.
    int const old_level = ph.level;
    for (unsigned v = ((ph.u_len>>3) + ph.u_len) / sz_ptload; 0 < v; v>>=1) {
        if (0== --ph.level) {
            ph.level = 1;
        }
    }
    compress(ibuf, ph.u_len, obuf, &cconf);
    ph.level = old_level;
    // while (0!=*p++) ;  // name is the same
    shdro[3].sh_name = ptr_diff(p, shstrtab);
    shdro[3].sh_type = Shdr::SHT_NOTE;
    shdro[3].sh_offset = fo_off;
    shdro[3].sh_size = sizeof(ph.u_len) + ph.c_len;
    shdro[3].sh_addralign = 1;
    tmp_u32 = ph.u_len; fo->write(&tmp_u32, 4);
    fo->write(obuf, ph.c_len); fo_off += shdro[3].sh_size;
    while (0!=*p++) ;
    shdro[4].sh_name = ptr_diff(p, shstrtab);
    shdro[4].sh_type = Shdr::SHT_STRTAB;
    shdro[4].sh_offset = fo_off;
    shdro[4].sh_size = sizeof(shstrtab);  // already includes terminating '\0'
    shdro[4].sh_addralign = 1;
    fo->write(shstrtab, shdro[4].sh_size); fo_off += shdro[4].sh_size;
    fo_off = ~3 & (3+ fo_off); fo->seek(fo_off, SEEK_SET);
    while (0!=*p++) ;
    shdro[5].sh_name = ptr_diff(p, shstrtab);
    shdro[5].sh_type = Shdr::SHT_SYMTAB;
    shdro[5].sh_offset = fo_off;
    shdro[5].sh_size = ((Ehdr::EM_PPC==my_e_machine) + 5)*sizeof(Sym);
    //shdro[5].sh_flags = Shdr::SHF_INFO_LINK;
    shdro[5].sh_link = 6;  // to .strtab for symbols
    shdro[5].sh_info = 1+3;  // number of non-global symbols [binutils/bfd/elf.c]
    shdro[5].sh_addralign = 4;
    shdro[5].sh_entsize = sizeof(Sym);
    Sym sec_sym;
    // Symbol 0; no references, but bfd demands it.
    memset(&sec_sym, 0, sizeof(sec_sym));
    fo->write(&sec_sym, sizeof(sec_sym)); fo_off += sizeof(sec_sym);
    // Each section before .shstrtab needs a symbol.
    sec_sym.st_info = sec_sym.make_st_info(Sym::STB_LOCAL, Sym::STT_SECTION);
    sec_sym.st_other = Sym::STV_DEFAULT;
    sec_sym.st_shndx = 1;  // .text
    fo->write(&sec_sym, sizeof(sec_sym)); fo_off += sizeof(sec_sym);
    sec_sym.st_shndx = 2;  // .note
    fo->write(&sec_sym, sizeof(sec_sym)); fo_off += sizeof(sec_sym);
    sec_sym.st_shndx = 3;  // .note
    fo->write(&sec_sym, sizeof(sec_sym)); fo_off += sizeof(sec_sym);
    // the symbol we care about
    Sym unc_ker;
    unc_ker.st_name = 1;  // 1 byte into strtab
    unc_ker.st_value = 0;
    unc_ker.st_size = ppc32_extra + txt_c_len;
    unc_ker.st_info = unc_ker.make_st_info(Sym::STB_GLOBAL, Sym::STT_FUNC);
    unc_ker.st_other = Sym::STV_DEFAULT;
    unc_ker.st_shndx = 1;  // .text
    fo->write(&unc_ker, sizeof(unc_ker)); fo_off += sizeof(unc_ker);
    unsigned const lablen = strlen(my_boot_label);
    if (Ehdr::EM_PPC==my_e_machine) {
        unc_ker.st_name += 1+ lablen;
        unc_ker.st_value = unc_ker.st_size;
        unc_ker.st_size = 0;
        fo->write(&unc_ker, sizeof(unc_ker)); fo_off += sizeof(unc_ker);
    }
    while (0!=*p++) ;
    shdro[6].sh_name = ptr_diff(p, shstrtab);
    shdro[6].sh_type = Shdr::SHT_STRTAB;
    shdro[6].sh_offset = fo_off;
    shdro[6].sh_size = 2+ lablen + (Ehdr::EM_PPC==my_e_machine)*(1+ 12);  // '\0' before and after
    shdro[6].sh_addralign = 1;
    fo->seek(1, SEEK_CUR);  // the '\0' before
    fo->write(my_boot_label, 1+ lablen);  // include the '\0' terminator
    if (Ehdr::EM_PPC==my_e_machine) {
        fo->write("_vmlinux_end", 1+ 12); fo_off += 1+ 12;
    }
    fo_off += 2+ lablen;
    fo->seek(0, SEEK_SET);
    fo->write(&ehdro, sizeof(ehdro));
    fo->write(&shdro[0], sizeof(shdro));
    if (Ehdr::EM_PPC==my_e_machine) {
        fo->seek(sizeof(unsigned), SEEK_CUR);
        set_be32(&ppc32_extra, ppc32_extra - 2*sizeof(unsigned) + txt_c_len);
        fo->write(&ppc32_extra, sizeof(ppc32_extra));
    }
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
#undef shstrtab
}
References Filter::addvalue, MemBuffer::allocForCompression(), b_info::b_cto8, b_info::b_ftid, b_info::b_method, b_info::b_unused, Filter::buf_len, upx_compress_config_t::conf_lzma, Filter::cto, Filter::id, lzma_compress_config_t::max_num_probs, memcpy(), memset(), packed_struct, ptr_diff(), upx_compress_config_t::reset(), OutputFile::seek(), SEEK_CUR, SEEK_SET, set_be32(), shstrtab, strlen, b_info::sz_cpr, b_info::sz_unc, throwInternalError(), throwNotCompressible(), upx_bytep, upx_compress(), UPX_E_OK, UPX_MAGIC_LE32, and OutputFile::write().
unpack()
template<class T > void PackVmlinuxBase< T >::unpack (OutputFile * fo) override protected virtual
Implements Packer.
Definition at line 635 of file p_vmlinx.cpp.
{
    TE32 word;
    PackHeader const ph_tmp(ph);
    fi->seek(p_note0->sh_offset, SEEK_SET);
    fi->readx(&word, sizeof(word));
    ph.u_len = word;
    ph.c_len = p_note0->sh_size - sizeof(word);
    ibuf.alloc(ph.c_len);
    fi->readx(ibuf, ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    decompress(ibuf, obuf, false);
    fo->write(obuf, ph.u_len);
    obuf.dealloc();
    ibuf.dealloc();
    ph = ph_tmp;
    if (!has_valid_vmlinux_head()) {
        throwCantUnpack(".text corrupted");
    }
    ibuf.alloc(ph.c_len);
    fi->readx(ibuf, ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    decompress(ibuf, obuf);
    Filter ft(ph.level);
    ft.init(ph.filter, 0);
    ft.cto = (unsigned char) ph.filter_cto;
    ft.unfilter(obuf, ph.u_len);
    fo->write(obuf, ph.u_len);
    obuf.dealloc();
    ibuf.dealloc();
    fi->seek(p_note1->sh_offset, SEEK_SET);
    fi->readx(&word, sizeof(word));
    ph.u_len = word;
    ph.c_len = p_note1->sh_size - sizeof(word);
    ibuf.alloc(ph.c_len);
    fi->readx(ibuf, p_note1->sh_size - sizeof(ph.u_len));
    obuf.allocForDecompression(ph.u_len);
    decompress(ibuf, obuf, false);
    fo->write(obuf, ph.u_len);
    obuf.dealloc();
    ibuf.dealloc();
    ph = ph_tmp;
}
References Filter::cto, Filter::init(), SEEK_SET, throwCantUnpack(), Filter::unfilter(), and OutputFile::write().
write_vmlinux_head()
template<class TElfClass > virtual unsigned PackVmlinuxBase< TElfClass >::write_vmlinux_head (OutputFile * fo, Shdr * stxt) protected pure virtual
Member Data Documentation
ehdri
template<class TElfClass > Ehdr PackVmlinuxBase< TElfClass >::ehdri protected
Definition at line 80 of file p_vmlinx.h.
my_boot_label
template<class TElfClass > char const* const PackVmlinuxBase< TElfClass >::my_boot_label protected
Definition at line 69 of file p_vmlinx.h.
my_e_machine
template<class TElfClass > unsigned int const PackVmlinuxBase< TElfClass >::my_e_machine protected
Definition at line 66 of file p_vmlinx.h.
my_elfclass
template<class TElfClass > unsigned char const PackVmlinuxBase< TElfClass >::my_elfclass protected
Definition at line 67 of file p_vmlinx.h.
my_elfdata
template<class TElfClass > unsigned char const PackVmlinuxBase< TElfClass >::my_elfdata protected
Definition at line 68 of file p_vmlinx.h.
n_ptload
template<class TElfClass > int PackVmlinuxBase< TElfClass >::n_ptload protected
Definition at line 71 of file p_vmlinx.h.
p_note0
template<class TElfClass > Shdr* PackVmlinuxBase< TElfClass >::p_note0 protected
Definition at line 78 of file p_vmlinx.h.
p_note1
template<class TElfClass > Shdr* PackVmlinuxBase< TElfClass >::p_note1 protected
Definition at line 79 of file p_vmlinx.h.
p_text
template<class TElfClass > Shdr* PackVmlinuxBase< TElfClass >::p_text protected
Definition at line 77 of file p_vmlinx.h.
paddr_min
template<class TElfClass > unsigned PackVmlinuxBase< TElfClass >::paddr_min protected
Definition at line 73 of file p_vmlinx.h.
phdri
template<class TElfClass > Phdr* PackVmlinuxBase< TElfClass >::phdri protected
Definition at line 74 of file p_vmlinx.h.
shdri
template<class TElfClass > Shdr* PackVmlinuxBase< TElfClass >::shdri protected
Definition at line 75 of file p_vmlinx.h.
shstrtab
template<class TElfClass > char* PackVmlinuxBase< TElfClass >::shstrtab protected
Definition at line 76 of file p_vmlinx.h.
sz_ptload
template<class TElfClass > unsigned PackVmlinuxBase< TElfClass >::sz_ptload protected
Definition at line 72 of file p_vmlinx.h.
The documentation for this class was generated from the following files:
src/p_vmlinx.h
src/p_vmlinx.cpp