My Project: InputFile Class Reference
InputFile Class Reference final
#include <file.h>
Public Member Functions
InputFile () noexcept=default
void sopen (const char *name, int flags, int shflags)
InputFile.
void open (const char *name, int flags)
int read (SPAN_P(void) buf, upx_int64_t blen)
int readx (SPAN_P(void) buf, upx_int64_t blen)
virtual upx_off_t seek (upx_off_t off, int whence) override
upx_off_t st_size_orig () const
noinline int dupFd () may_throw
Public Member Functions inherited from FileBase
bool close_noexcept () noexcept
void closex () may_throw
bool isOpen () const noexcept
int getFd () const noexcept
const char * getName () const noexcept
virtual upx_off_t seek (upx_off_t off, int whence)
upx_off_t tell () const
virtual upx_off_t st_size () const
virtual void set_extent (upx_off_t offset, upx_off_t length)
Protected Attributes
upx_off_t _length_orig = 0
Protected Attributes inherited from FileBase
int _fd = -1
int _flags = 0
int _shflags = 0
int _mode = 0
const char * _name = nullptr
upx_off_t _offset = 0
upx_off_t _length = 0
Private Types
typedef FileBase super
Additional Inherited Members
Static Public Member Functions inherited from FileBase
static void chmod (const char *name, int mode) may_throw
static file-related util functions; will throw on error
static void rename (const char *old_, const char *new_) may_throw
static void unlink (const char *name) may_throw
static bool unlink_noexcept (const char *name) noexcept
Public Attributes inherited from FileBase
struct stat st = {}
Protected Member Functions inherited from FileBase
FileBase () noexcept=default
virtual ~FileBase () may_throw
FileBase.
bool do_sopen ()
Detailed Description
Definition at line 76 of file file.h.
Member Typedef Documentation
super
typedef FileBase InputFile::super private
Definition at line 77 of file file.h.
Constructor & Destructor Documentation
InputFile()
InputFile::InputFile () explicit default noexcept
Member Function Documentation
dupFd()
int InputFile::dupFd ()
Definition at line 217 of file file.cpp.
{
    if (!isOpen())
        throwIOException("bad dup");
#if defined(HAVE_DUP) && (HAVE_DUP + 0 == 0)
    errno = ENOSYS;
    int r = -1;
#else
    int r = ::dup(getFd());
#endif
    if (r < 0)
        throwIOException("dup", errno);
    return r;
}
References FileBase::getFd(), FileBase::isOpen(), and throwIOException().
Referenced by PackVmlinuzI386::decompressKernel(), and PackVmlinuzARMEL::decompressKernel().
open()
void InputFile::open (const char * name, int flags) inline
Definition at line 83 of file file.h.
{ sopen(name, flags, -1); }
References sopen().
read()
int InputFile::read (SPAN_P(void) buf, upx_int64_t blen)
Definition at line 190 of file file.cpp.
{
    if (!isOpen() || blen < 0)
        throwIOException("bad read");
    int len = (int) mem_size(1, blen); // sanity check
    errno = 0;
    long l = acc_safe_hread(_fd, raw_bytes(buf, len), len);
    if (errno)
        throwIOException("read error", errno);
    return (int) l;
}
References FileBase::_fd, buf, FileBase::isOpen(), mem_size(), raw_bytes(), and throwIOException().
Referenced by PeFile::canUnpack0(), anonymous_namespace{work.cpp}::copy_file_contents(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackDjgpp2::readFileHeader(), Packer::readPackHeader(), readx(), PackLinuxElf32::un_DT_INIT(), and PackLinuxElf64::un_DT_INIT().
readx()
int InputFile::readx (SPAN_P(void) buf, upx_int64_t blen)
Definition at line 201 of file file.cpp.
{
    int l = this->read(buf, blen);
    if (l != blen)
        throwEOFException();
    return l;
}
References read(), and throwEOFException().
Referenced by PackLinuxElf32::ARM_is_QNX(), PackCom::canPack(), PackExe::canPack(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), PackLinuxI386sh::canPack(), PackMachFat::canPack(), PackPs1::canPack(), PackSys::canPack(), PackTos::canPack(), PackUnix::canPack(), PackLinuxElf32::canPackOSABI(), PackMachFat::canUnpack(), PackUnix::canUnpack(), PeFile::canUnpack0(), Packer::copyOverlay(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), handle_allegropak(), Packer::handleStub(), PackVmlinuxI386::has_valid_vmlinux_head(), PackVmlinuxARMEL::has_valid_vmlinux_head(), PackVmlinuxARMEB::has_valid_vmlinux_head(), PackVmlinuxPPC32::has_valid_vmlinux_head(), PackVmlinuxPPC64LE::has_valid_vmlinux_head(), PackVmlinuxAMD64::has_valid_vmlinux_head(), is_dlm(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackMachFat::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32x86interp::pack1(), PackUnix::pack2(), PackUnix::packExtent(), PackLinuxElf32::PackLinuxElf32(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64(), PackLinuxElf64::PackLinuxElf64help1(), PackPs1::readBkupHeader(), LeFile::readEntryTable(), LeFile::readFileHeader(), PackDjgpp2::readFileHeader(), PackPs1::readFileHeader(), PackTmt::readFileHeader(), PackTos::readFileHeader(), PackVmlinuzI386::readFileHeader(), PackVmlinuzARMEL::readFileHeader(), PeFile::readFileHeader(), PackW32PeI386::readFileHeader(), PackExe::readFileHeader(), LeFile::readFixupPageTable(), LeFile::readFixups(), LeFile::readImage(), LeFile::readNonResidentNames(), LeFile::readObjectTable(), LeFile::readPageMap(), PeFile32::readPeHeader(), PeFile64::readPeHeader(), LeFile::readResidentNames(), PeFile::readSectionHeaders(), PeFile::readSections(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachFat::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackUnix::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), PeFile::unpack0(), and PackUnix::unpackExtent().
seek()
upx_off_t InputFile::seek (upx_off_t off, int whence) override virtual
Reimplemented from FileBase.
Definition at line 208 of file file.cpp.
{
    upx_off_t pos = super::seek(off, whence);
    if (_length < pos)
        throwIOException("bad seek 4");
    return pos;
}
References FileBase::_length, FileBase::seek(), and throwIOException().
Referenced by PackLinuxElf32::ARM_is_QNX(), PackExe::canPack(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), PackLinuxI386sh::canPack(), PackMachFat::canPack(), PackUnix::canPack(), PackLinuxElf32::canPackOSABI(), PackDjgpp2::canUnpack(), PackExe::canUnpack(), PackMachFat::canUnpack(), PackTmt::canUnpack(), PackUnix::canUnpack(), PackVmlinuzI386::canUnpack(), PackVmlinuzARMEL::canUnpack(), PackWcle::canUnpack(), PeFile::canUnpack0(), anonymous_namespace{work.cpp}::copy_file_contents(), Packer::copyOverlay(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), funpad4(), handle_allegropak(), Packer::handleStub(), PackVmlinuxI386::has_valid_vmlinux_head(), PackVmlinuxARMEL::has_valid_vmlinux_head(), PackVmlinuxARMEB::has_valid_vmlinux_head(), PackVmlinuxPPC32::has_valid_vmlinux_head(), PackVmlinuxPPC64LE::has_valid_vmlinux_head(), PackVmlinuxAMD64::has_valid_vmlinux_head(), is_dlm(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackMachFat::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32x86interp::pack1(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackUnix::packExtent(), PackLinuxElf32::PackLinuxElf32(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64(), PackLinuxElf64::PackLinuxElf64help1(), PackPs1::readBkupHeader(), LeFile::readEntryTable(), LeFile::readFileHeader(), PackDjgpp2::readFileHeader(), PackPs1::readFileHeader(), PackTmt::readFileHeader(), PackTos::readFileHeader(), PeFile::readFileHeader(), PackW32PeI386::readFileHeader(), LeFile::readFixupPageTable(), LeFile::readFixups(), LeFile::readImage(), LeFile::readNonResidentNames(), LeFile::readObjectTable(), LeFile::readPageMap(), LeFile::readResidentNames(), PeFile::readSectionHeaders(), PeFile::readSections(), try_can_pack(), try_can_unpack(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachFat::unpack(), PackPs1::unpack(), PackTmt::unpack(), PackTos::unpack(), PackUnix::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), and PeFile::unpack0().
sopen()
void InputFile::sopen (const char * name, int flags, int shflags)
InputFile.
Definition at line 171 of file file.cpp.
{
    closex();
    _name = name;
    _flags = flags;
    _shflags = shflags;
    _mode = 0;
    _offset = 0;
    _length = 0;
    if (!super::do_sopen()) {
        if (errno == ENOENT)
            throw FileNotFoundException(_name, errno);
        else if (errno == EEXIST)
            throw FileAlreadyExistsException(_name, errno);
        else
            throwIOException(_name, errno);
    }
    _length_orig = _length;
}
References FileBase::_flags, FileBase::_length, _length_orig, FileBase::_mode, FileBase::_name, FileBase::_offset, FileBase::_shflags, FileBase::closex(), FileBase::do_sopen(), ENOENT, and throwIOException().
Referenced by anonymous_namespace{work.cpp}::copy_file_contents(), do_one_file(), open(), and OutputFile::open().
st_size_orig()
upx_off_t InputFile::st_size_orig () const
Definition at line 215 of file file.cpp.
{ return _length_orig; }
References _length_orig.
Referenced by PackMachFat::check_fat_head().
Member Data Documentation
_length_orig
upx_off_t InputFile::_length_orig = 0 protected
Definition at line 94 of file file.h.
Referenced by sopen(), and st_size_orig().
The documentation for this class was generated from the following files:
src/file.h
src/file.cpp