My Project: PeFile::Export Class Reference
PeFile::Export Class Reference final
#include <pefile.h>
Classes
struct export_dir_t
Public Member Functions
Export (char *_base)
export handling
~Export () noexcept
void convert (unsigned eoffs, unsigned esize)
void build (char *base, unsigned newoffs)
unsigned getsize () const
Private Attributes
export_dir_t edir
char * ename
char * functionptrs
char * ordinals
char ** names
char * base
unsigned size
Interval iv
Additional Inherited Members
Private Member Functions inherited from upx::noncopyable
forceinline constexpr noncopyable () noexcept
forceinline ~noncopyable () noexcept=default
Detailed Description
Definition at line 517 of file pefile.h.
Constructor & Destructor Documentation
Export()
PeFile::Export::Export (char * _base) explicit
export handling
Definition at line 1190 of file pefile.cpp.
                                : base(_base), iv((byte *) _base) {
    COMPILE_TIME_ASSERT(sizeof(export_dir_t) == 40)
    COMPILE_TIME_ASSERT_ALIGNED1(export_dir_t)
    ename = functionptrs = ordinals = nullptr;
    names = nullptr;
    mem_clear(&edir);
    size = 0;
}
References COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, edir, ename, functionptrs, mem_clear(), names, ordinals, and size.
~Export()
PeFile::Export::~Export () noexcept
Definition at line 1199 of file pefile.cpp.
{
    ::free(ename);
    delete[] functionptrs;
    delete[] ordinals;
    if (names) {
        const unsigned limit = edir.names + edir.functions;
        for (unsigned ic = 0; ic < limit; ic++)
            if (names[ic])
                ::free(names[ic]); // allocated by strdup()
        delete[] names;
    }
}
Member Function Documentation
build()
void PeFile::Export::build (char * base, unsigned newoffs)
Definition at line 1271 of file pefile.cpp.
{
    char *const functionp = newbase + sizeof(edir);
    char *const namep = functionp + 4 * edir.functions;
    char *const ordinalp = namep + 4 * edir.names;
    char *const enamep = ordinalp + 2 * edir.names;
    char *exports = enamep + strlen(ename) + 1;
    edir.addrtable = newoffs + ptr_diff_bytes(functionp, newbase);
    edir.ordinaltable = newoffs + ptr_diff_bytes(ordinalp, newbase);
    assert(ordinals != nullptr); // pacify clang-tidy
    memcpy(ordinalp, ordinals, 2 * edir.names);
    edir.name = newoffs + ptr_diff_bytes(enamep, newbase);
    strcpy(enamep, ename);
    edir.nameptrtable = newoffs + ptr_diff_bytes(namep, newbase);
    unsigned ic;
    for (ic = 0; ic < edir.names; ic++) {
        strcpy(exports, names[ic]);
        set_le32(namep + 4 * ic, newoffs + ptr_diff_bytes(exports, newbase));
        exports += strlen(exports) + 1;
    }
    memcpy(functionp, functionptrs, 4 * edir.functions);
    for (ic = 0; ic < edir.functions; ic++)
        if (names[edir.names + ic]) {
            strcpy(exports, names[edir.names + ic]);
            set_le32(functionp + 4 * ic, newoffs + ptr_diff_bytes(exports, newbase));
            exports += strlen(exports) + 1;
        }
    memcpy(newbase, &edir, sizeof(edir));
    assert(exports - newbase == (int) size);
}
References memcpy(), ptr_diff_bytes(), set_le32(), size(), strcpy(), and strlen.
Referenced by PeFile::processExports().
convert()
void PeFile::Export::convert (unsigned eoffs, unsigned esize)
Definition at line 1212 of file pefile.cpp.
{
    memcpy(&edir, base + eoffs, sizeof(export_dir_t));
    size = sizeof(export_dir_t);
    iv.add_interval(eoffs, size);
    if (!edir.name || eoffs + esize <= (unsigned) edir.name) {
        char msg[50];
        snprintf(msg, sizeof(msg), "bad export directory name RVA %#x", (unsigned) edir.name);
        throwInternalError(msg);
    }
    unsigned len = strlen(base + edir.name) + 1;
    ename = strdup(base + edir.name);
    size += len;
    iv.add_interval(edir.name, len);
    len = 4 * edir.functions;
    functionptrs = New(char, len + 1);
    memcpy(functionptrs, base + edir.addrtable, len);
    size += len;
    iv.add_interval(edir.addrtable, len);
    unsigned ic;
    names = New(char *, edir.names + edir.functions + 1);
    for (ic = 0; ic < edir.names; ic++) {
        char *n = base + get_le32(base + edir.nameptrtable + ic * 4);
        len = strlen(n) + 1;
        names[ic] = strdup(n);
        size += len;
        iv.add_interval(get_le32(base + edir.nameptrtable + ic * 4), len);
    }
    iv.add_interval(edir.nameptrtable, 4 * edir.names);
    size += 4 * edir.names;
    LE32 *fp = (LE32 *) functionptrs;
    // export forwarders
    for (ic = 0; ic < edir.functions; ic++)
        if (fp[ic] >= eoffs && fp[ic] < eoffs + esize) {
            char *forw = base + fp[ic];
            len = strlen(forw) + 1;
            iv.add_interval(forw, len);
            size += len;
            names[ic + edir.names] = strdup(forw);
        } else
            names[ic + edir.names] = nullptr;
    len = 2 * edir.names;
    ordinals = New(char, len + 1);
    memcpy(ordinals, base + edir.ordinaltable, len);
    size += len;
    iv.add_interval(edir.ordinaltable, len);
    iv.flatten();
    if (iv.ivnum == 1)
        iv.clear();
#if TESTING
    else
        iv.dump();
#endif
}
References base, get_le32(), memcpy(), n, New, size(), snprintf, strlen, and throwInternalError().
Referenced by PeFile::processExports().
getsize()
unsigned PeFile::Export::getsize () const inline
Definition at line 545 of file pefile.h.
{ return size; }
References size().
Referenced by PeFile::processExports().
Member Data Documentation
base
char* PeFile::Export::base private
Definition at line 535 of file pefile.h.
edir
export_dir_t PeFile::Export::edir private
Definition at line 529 of file pefile.h.
Referenced by Export().
ename
char* PeFile::Export::ename private
Definition at line 530 of file pefile.h.
Referenced by Export().
functionptrs
char* PeFile::Export::functionptrs private
Definition at line 531 of file pefile.h.
Referenced by Export().
iv
Interval PeFile::Export::iv private
Definition at line 537 of file pefile.h.
names
char** PeFile::Export::names private
Definition at line 533 of file pefile.h.
Referenced by Export().
ordinals
char* PeFile::Export::ordinals private
Definition at line 532 of file pefile.h.
Referenced by Export().
size
unsigned PeFile::Export::size private
Definition at line 536 of file pefile.h.
Referenced by Export().
The documentation for this class was generated from the following files:
src/pefile.h
src/pefile.cpp