My Project: PackNetBSDElf32x86 Class Reference
PackNetBSDElf32x86 Class Reference
#include <p_lx_elf.h>
Public Member Functions
PackNetBSDElf32x86 (InputFile *f)
virtual ~PackNetBSDElf32x86 ()
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
Public Member Functions inherited from PackLinuxElf32x86
PackLinuxElf32x86 (InputFile *f)
virtual ~PackLinuxElf32x86 ()
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const options_t *) const override
virtual const int * getFilters () const override
virtual tribool canUnpack () override
Generic Unix canUnpack().
Public Member Functions inherited from PackLinuxElf32
PackLinuxElf32 (InputFile *f)
virtual ~PackLinuxElf32 ()
Public Member Functions inherited from PackLinuxElf
PackLinuxElf (InputFile *f)
virtual ~PackLinuxElf ()
virtual int getVersion () const override
virtual bool canUnpackVersion (int version) const override
virtual tribool canUnpack () override
Generic Unix canUnpack().
Public Member Functions inherited from PackUnix
~PackUnix ()
virtual int getVersion () const override
virtual const int * getFilters () const override
virtual int getStrategy (Filter &)
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
int find_overlay_offset (MemBuffer const &buf)
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual void buildLoader (const Filter *ft) override
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka) override
Protected Member Functions inherited from PackLinuxElf32x86
virtual void pack1 (OutputFile *, Filter &) override
virtual void buildLoader (const Filter *) override
virtual void addStubEntrySections (Filter const *, unsigned m_decompr) override
virtual Linker * newLinker () const override
virtual void defineSymbols (Filter const *) override
Protected Member Functions inherited from PackLinuxElf32Le
PackLinuxElf32Le (InputFile *f)
Protected Member Functions inherited from PackLinuxElf32
virtual void PackLinuxElf32help1 (InputFile *f)
virtual int checkEhdr (Elf32_Ehdr const *ehdr) const
virtual bool canPackOSABI (Elf32_Ehdr const *)
virtual tribool canPack () override
virtual tribool canUnpack () override
Generic Unix canUnpack().
virtual void ARM_defineSymbols (Filter const *ft)
virtual void ARM_updateLoader (OutputFile *)
virtual int ARM_is_QNX (void)
virtual upx_uint64_t canPack_Shdr (Elf32_Phdr const *pload_x0)
virtual void pack1 (OutputFile *, Filter &) override
virtual void asl_pack2_Shdrs (OutputFile *, unsigned pre_xct_top)
virtual void asl_slide_Shdrs ()
virtual int pack2 (OutputFile *, Filter &) override
virtual int pack2_shlib (OutputFile *fo, Filter &ft, unsigned pre_xct_top)
virtual off_t pack3 (OutputFile *, Filter &) override
virtual void pack4 (OutputFile *, Filter &) override
virtual unsigned forward_Shdrs (OutputFile *fo, Elf32_Ehdr *ehdro)
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual void un_asl_dynsym (unsigned orig_file_size, OutputFile *)
virtual void un_shlib_1 (OutputFile *const fo, MemBuffer &o_elfhdrs, unsigned &c_adler, unsigned &u_adler, unsigned const orig_file_size)
virtual void un_DT_INIT (unsigned old_dtinit, Elf32_Phdr const *phdro, Elf32_Phdr const *dynhdr, OutputFile *fo)
virtual void unRel32 (unsigned dt_rel, Elf32_Rel *rel0, unsigned relsz, MemBuffer &membuf, unsigned const load_off, OutputFile *fo)
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka) override
virtual void defineSymbols (Filter const *) override
virtual void buildLinuxLoader (upx_byte const *const proto, unsigned const szproto, upx_byte const *const fold, unsigned const szfold, Filter const *ft)
virtual off_t getbrk (const Elf32_Phdr *phdr, int e_phnum) const
virtual void patchLoader () override
virtual void updateLoader (OutputFile *fo) override
virtual unsigned find_LOAD_gap (Elf32_Phdr const *const phdri, unsigned const k, unsigned const e_phnum)
virtual off_t getbase (const Elf32_Phdr *phdr, int e_phnum) const
bool calls_crt1 (Elf32_Rel const *rel, int sz)
virtual Elf32_Sym const * elf_lookup (char const *) const
virtual unsigned elf_get_offset_from_address (unsigned) const
virtual unsigned elf_get_offset_from_Phdrs (unsigned, Elf32_Phdr const *phdr0) const
virtual Elf32_Phdr const * elf_find_Phdr_for_va (unsigned addr, Elf32_Phdr const *phdr, unsigned phnum)
Elf32_Phdr const * elf_find_ptype (unsigned type, Elf32_Phdr const *phdr0, unsigned phnum)
Elf32_Shdr const * elf_find_section_name (char const *) const
Elf32_Shdr * elf_find_section_type (unsigned) const
Elf32_Dyn * elf_find_dynptr (unsigned) const
unsigned elf_find_table_size (unsigned dt_type, unsigned sh_type)
void sort_DT32_offsets (Elf32_Dyn const *const dynp0)
int is_LOAD (Elf32_Phdr const *phdr) const
unsigned check_pt_load (Elf32_Phdr const *)
unsigned check_pt_dynamic (Elf32_Phdr const *)
void invert_pt_dynamic (Elf32_Dyn const *, unsigned dt_filesz)
void * elf_find_dynamic (unsigned) const
Elf32_Dyn const * elf_has_dynamic (unsigned) const
virtual upx_uint64_t elf_unsigned_dynamic (unsigned) const override
unsigned find_dt_ndx (unsigned rva)
virtual int adjABS (Elf32_Sym *sym, unsigned delta)
void add_phdrx (Elf32_Phdr const *)
char const * get_str_name (unsigned st_name, unsigned symnum) const
char const * get_dynsym_name (unsigned symnum, unsigned relnum) const
packed_struct (cprElfHdr1)
packed_struct (cprElfHdr2)
packed_struct (cprElfHdr3)
packed_struct (cprElfHdr4)
packed_struct (cprElfHdrNetBSD)
packed_struct (cprElfShdr3)
Protected Member Functions inherited from PackLinuxElf
virtual const int * getCompressionMethods (int method, int level) const override
virtual void pack1 (OutputFile *, Filter &) override=0
virtual int pack2 (OutputFile *, Filter &) override=0
virtual off_t pack3 (OutputFile *, Filter &) override=0
virtual unsigned pack2_shlib_overlay_init (OutputFile *fo)
virtual unsigned pack2_shlib_overlay_compress (MemBuffer &obuf, MemBuffer &ibuf, unsigned u_len)
virtual unsigned pack2_shlib_overlay_write (OutputFile *fo, MemBuffer &obuf, unsigned hdr_u_len, unsigned hdr_c_len)
virtual void generateElfHdr (OutputFile *, void const *proto, unsigned const brka)=0
virtual void defineSymbols (Filter const *)
virtual void addStubEntrySections (Filter const *, unsigned m_decompr)
virtual void unpack (OutputFile *fo) override
Generic Unix unpack().
virtual upx_uint64_t elf_unsigned_dynamic (unsigned) const =0
Protected Member Functions inherited from PackUnix
PackUnix (InputFile *f)
virtual void pack1 (OutputFile *, Filter &)
virtual int pack2 (OutputFile *, Filter &)
virtual off_t pack3 (OutputFile *, Filter &)
virtual void pack4 (OutputFile *, Filter &)
virtual void patchLoader ()=0
virtual void patchLoaderChecksum ()
virtual void updateLoader (OutputFile *)=0
virtual void writePackHeader (OutputFile *fo)
virtual bool checkCompressionRatio (unsigned, unsigned) const override
Generic Unix pack().
virtual void packExtent (const Extent &x, Filter *, OutputFile *, unsigned hdr_len=0, unsigned b_extra=0, bool inhibit_compression_check=false)
virtual unsigned unpackExtent (unsigned wanted, OutputFile *fo, unsigned &c_adler, unsigned &u_adler, bool first_PF_X, int is_rewrite=false)
packed_struct (b_info)
packed_struct (l_info)
packed_struct (p_info)
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Private Types
typedef PackLinuxElf32x86 super
Additional Inherited Members
Public Types inherited from PackUnix
typedef Packer super
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Protected Types inherited from PackUnix
enum { OVERHEAD = 2048 }
Static Protected Member Functions inherited from PackLinuxElf32
static void compileTimeAssertions ()
Static Protected Member Functions inherited from PackLinuxElf
static unsigned elf_hash (char const *)
static unsigned gnu_hash (char const *)
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Protected Attributes inherited from PackLinuxElf32
Elf32_Ehdr ehdri
Elf32_Phdr * phdri
Elf32_Shdr * shdri
Elf32_Shdr * shdro
Elf32_Phdr const * phdrx [END_PHDRX]
unsigned n_phdrx
unsigned sz_phdrx
unsigned e_phoff
unsigned e_shoff
unsigned sz_dynseg
unsigned n_jmp_slot
unsigned plt_off
unsigned page_mask
Elf32_Dyn * dynseg
unsigned int const * hashtab
unsigned int const * hashend
unsigned int const * gashtab
unsigned int const * gashend
Elf32_Sym * dynsym
Elf32_Sym const * jni_onload_sym
Elf32_Shdr * sec_strndx
Elf32_Shdr const * sec_dynsym
Elf32_Shdr const * sec_dynstr
Elf32_Shdr * sec_arm_attr
cprElfHdrNetBSD elfout
cprElfShdr3 shdrout
Protected Attributes inherited from PackLinuxElf
unsigned old_data_off
unsigned old_data_len
unsigned e_type
unsigned e_phnum
unsigned e_shnum
unsigned e_shstrndx
MemBuffer file_image
MemBuffer lowmem
MemBuffer mb_shdr
MemBuffer mb_dt_offsets
unsigned * dt_offsets
unsigned symnum_max
unsigned strtab_max
char const * dynstr
unsigned sz_phdrs
unsigned sz_elf_hdrs
unsigned sz_pack2
unsigned sz_pack2a
unsigned lg2_page
unsigned page_size
bool is_pie
unsigned is_asl
unsigned xct_off
unsigned hatch_off
unsigned o_binfo
upx_off_t so_slide
upx_uint64_t load_va
upx_uint64_t xct_va
upx_uint64_t jni_onload_va
upx_uint64_t user_init_va
void * user_init_rp
upx_uint64_t plt_va
upx_uint64_t plt_off
unsigned user_init_off
unsigned linfo_off
unsigned loader_offset
upx_uint16_t e_machine
unsigned char ei_class
unsigned char ei_data
unsigned char ei_osabi
unsigned char prev_method
char const * osabi_note
unsigned upx_dt_init
unsigned dt_table [DT_NUM]
MemBuffer mb_shstrtab
char const * shstrtab
MemBuffer jump_slots
MemBuffer buildid_data
MemBuffer note_body
unsigned note_size
int o_elf_shnum
Protected Attributes inherited from PackUnix
unsigned total_in
unsigned total_out
int exetype
unsigned blocksize
unsigned progid
unsigned overlay_offset
MemBuffer loader
int lsize
MemBuffer pt_dynamic
int sz_dynamic
unsigned b_len
unsigned methods_used
unsigned szb_info
unsigned saved_opt_android_shlib
struct l_info linfo
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Static Protected Attributes inherited from PackLinuxElf32
static unsigned const END_PHDRX = 5
Static Protected Attributes inherited from PackLinuxElf
static unsigned int const asl_delta = (1u<<12)
static unsigned const DT_NUM = 34
static const unsigned char o_shstrtab []
Detailed Description
Definition at line 665 of file p_lx_elf.h.
Member Typedef Documentation
super
typedef PackLinuxElf32x86 PackNetBSDElf32x86::super private
Definition at line 667 of file p_lx_elf.h.
Constructor & Destructor Documentation
PackNetBSDElf32x86()
PackNetBSDElf32x86::PackNetBSDElf32x86 (InputFile * f)
Definition at line 7987 of file p_lx_elf.cpp.
                                                   : super(f)
{
    ei_osabi  = Elf32_Ehdr::ELFOSABI_NETBSD;
    osabi_note = "NetBSD";
}
References PackLinuxElf::ei_osabi, and PackLinuxElf::osabi_note.
~PackNetBSDElf32x86()
PackNetBSDElf32x86::~PackNetBSDElf32x86 () virtual
Definition at line 7993 of file p_lx_elf.cpp.
{
}
Member Function Documentation
buildLoader()
void PackNetBSDElf32x86::buildLoader (const Filter * ft) override protected virtual
Reimplemented from PackLinuxElf32x86.
Definition at line 1906 of file p_lx_elf.cpp.
{
    unsigned char tmp[sizeof(stub_i386_netbsd_elf_fold)];
    memcpy(tmp, stub_i386_netbsd_elf_fold, sizeof(stub_i386_netbsd_elf_fold));
    checkPatch(nullptr, 0, 0, 0);  // reset
    if (opt->o_unix.is_ptinterp) {
        unsigned j;
        for (j = 0; j < sizeof(stub_i386_netbsd_elf_fold)-1; ++j) {
            if (0x60==tmp[  j]
            &&  0x47==tmp[1+j] ) {
                /* put INC EDI before PUSHA: inhibits auxv_up for PT_INTERP */
                tmp[  j] = 0x47;
                tmp[1+j] = 0x60;
                break;
            }
        }
    }
    buildLinuxLoader(
        stub_i386_netbsd_elf_entry, sizeof(stub_i386_netbsd_elf_entry),
        tmp,                        sizeof(stub_i386_netbsd_elf_fold), ft);
}
References PackLinuxElf32::buildLinuxLoader(), Packer::checkPatch(), memcpy(), opt, stub_i386_netbsd_elf_entry, and stub_i386_netbsd_elf_fold.
generateElfHdr()
void PackNetBSDElf32x86::generateElfHdr (OutputFile * fo, void const * proto, unsigned const brka) override protected virtual
Reimplemented from PackLinuxElf32.
Definition at line 3815 of file p_lx_elf.cpp.
{
    cprElfHdr2 *const h2 = (cprElfHdr2 *)(void *)&elfout;
    super::generateElfHdr(fo, proto, brka);
    sz_elf_hdrs = sizeof(*h2) - sizeof(linfo);
    unsigned note_offset = sz_elf_hdrs;
    // Find the NetBSD PT_NOTE and the PaX PT_NOTE.
    Elf32_Nhdr const *np_NetBSD = nullptr;  unsigned sz_NetBSD = 0;
    Elf32_Nhdr const *np_PaX    = nullptr;  unsigned sz_PaX    = 0;
    unsigned char *cp = (unsigned char *)note_body;
    unsigned j;
    for (j=0; j < note_size; ) {
        Elf32_Nhdr const *const np = (Elf32_Nhdr const *)(void *)cp;
        int k = sizeof(*np) + up4(get_te32(&np->namesz))
            + up4(get_te32(&np->descsz));
        if (NHDR_NETBSD_TAG == np->type && 7== np->namesz
        &&  NETBSD_DESCSZ == np->descsz
        &&  0==strcmp(ELF_NOTE_NETBSD_NAME,
                /* &np->body */ (char const *)(1+ np))) {
            np_NetBSD = np;
            sz_NetBSD = k;
        }
        if (NHDR_PAX_TAG == np->type && 4== np->namesz
        &&  PAX_DESCSZ==np->descsz
        &&  0==strcmp(ELF_NOTE_PAX_NAME,
                /* &np->body */ (char const *)(1+ np))) {
            np_PaX = np;
            sz_PaX = k;
        }
        cp += k;
        j += k;
    }
    // Add PT_NOTE for the NetBSD note and PaX note, if any.
    note_offset += (np_NetBSD ? sizeof(Elf32_Phdr) : 0);
    note_offset += (np_PaX    ? sizeof(Elf32_Phdr) : 0);
    Elf32_Phdr *phdr = &elfout.phdr[C_NOTE];
    if (np_NetBSD) {
        set_te32(&phdr->p_type, PT_NOTE32);
        set_te32(&phdr->p_offset, note_offset);
        set_te32(&phdr->p_vaddr, note_offset);
        set_te32(&phdr->p_paddr, note_offset);
        set_te32(&phdr->p_filesz, sz_NetBSD);
        set_te32(&phdr->p_memsz,  sz_NetBSD);
        set_te32(&phdr->p_flags, Elf32_Phdr::PF_R);
        set_te32(&phdr->p_align, 4);
        sz_elf_hdrs += sz_NetBSD + sizeof(*phdr);
        note_offset += sz_NetBSD;
        ++phdr;
    }
    if (np_PaX) {
        set_te32(&phdr->p_type, PT_NOTE32);
        set_te32(&phdr->p_offset, note_offset);
        set_te32(&phdr->p_vaddr, note_offset);
        set_te32(&phdr->p_paddr, note_offset);
        set_te32(&phdr->p_filesz, sz_PaX);
        set_te32(&phdr->p_memsz,  sz_PaX);
        set_te32(&phdr->p_flags, Elf32_Phdr::PF_R);
        set_te32(&phdr->p_align, 4);
        /* &np_PaX->body[4] */
        const unsigned char *p4 =  &(ACC_CCAST(const unsigned char *, (1+ np_PaX)))[4];
        unsigned bits = get_te32(p4);
        bits &= ~PAX_MPROTECT;
        bits |=  PAX_NOMPROTECT;
        set_te32(ACC_UNCONST_CAST(unsigned char *, p4), bits);
        sz_elf_hdrs += sz_PaX + sizeof(*phdr);
        note_offset += sz_PaX;
        ++phdr;
    }
    set_te32(&h2->phdr[C_TEXT].p_filesz, note_offset);
              h2->phdr[C_TEXT].p_memsz = h2->phdr[C_TEXT].p_filesz;
    if (ph.format==getFormat()) {
        set_te16(&h2->ehdr.e_phnum, !!sz_NetBSD + !!sz_PaX +
        get_te16(&h2->ehdr.e_phnum));
        fo->seek(0, SEEK_SET);
        fo->rewrite(h2, sizeof(*h2) - sizeof(h2->linfo));
        // The 'if' guards on these two calls to memcpy are required
        // because the C Standard Committee did not debug the Standard
        // before publishing.  An empty region (0==size) must nevertheless
        // have a valid (non-nullptr) pointer.
        if (sz_NetBSD) memcpy(&((char *)phdr)[0],         np_NetBSD, sz_NetBSD);
        if (sz_PaX)    memcpy(&((char *)phdr)[sz_NetBSD], np_PaX,    sz_PaX);
        fo->write(&elfout.phdr[C_NOTE],
            &((char *)phdr)[sz_PaX + sz_NetBSD] - (char *)&elfout.phdr[C_NOTE]);
        l_info foo; memset(&foo, 0, sizeof(foo));
        fo->rewrite(&foo, sizeof(foo));
    }
    else {
        assert(false);  // unknown ph.format, PackLinuxElf32
    }
}
References ACC_CCAST, ACC_UNCONST_CAST, C_NOTE, C_TEXT, PackLinuxElf32::Elf32_Nhdr::descsz, PackLinuxElf32::elfout, PackHeader::format, PackLinuxElf::generateElfHdr(), Packer::get_te16(), Packer::get_te32(), getFormat(), PackUnix::linfo, memcpy(), memset(), PackLinuxElf32::Elf32_Nhdr::namesz, PackLinuxElf::note_body, PackLinuxElf::note_size, Elf32_Phdr::p_align, Elf32_Phdr::p_filesz, Elf32_Phdr::p_flags, Elf32_Phdr::p_memsz, Elf32_Phdr::p_offset, Elf32_Phdr::p_paddr, Elf32_Phdr::p_type, Elf32_Phdr::p_vaddr, PackerBase::ph, PT_NOTE32, OutputFile::rewrite(), OutputFile::seek(), SEEK_SET, Packer::set_te16(), Packer::set_te32(), strcmp(), PackLinuxElf::sz_elf_hdrs, PackLinuxElf32::Elf32_Nhdr::type, up4(), and OutputFile::write().
getFormat()
virtual int PackNetBSDElf32x86::getFormat () const inline override virtual
Reimplemented from PackLinuxElf32x86.
Definition at line 671 of file p_lx_elf.h.
{ return UPX_F_BSD_ELF_i386; }
References UPX_F_BSD_ELF_i386.
Referenced by generateElfHdr().
getFullName()
virtual const char * PackNetBSDElf32x86::getFullName (const options_t *) const inline override virtual
Reimplemented from PackLinuxElf32x86.
Definition at line 673 of file p_lx_elf.h.
{ return "i386-netbsd.elf"; }
getName()
virtual const char * PackNetBSDElf32x86::getName () const inline override virtual
Reimplemented from PackLinuxElf32x86.
Definition at line 672 of file p_lx_elf.h.
{ return "netbsd/i386"; }
The documentation for this class was generated from the following files:
src/p_lx_elf.h
src/p_lx_elf.cpp