My Project: PackTos Class Reference
PackTos Class Reference final
atari/tos
#include <p_tos.h>
Classes
struct LinkerSymbols
struct tos_header_t
Public Member Functions
PackTos (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
virtual void fileInfo () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
virtual Linker * newLinker () const override
virtual void buildLoader (const Filter *ft) override
unsigned getDecomprOffset (int method, int small) const
int readFileHeader ()
util readFileHeader() reads ih and checks for illegal values checkFileHeader() checks ih for legal but unsupported values
bool checkFileHeader ()
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
Copy stub from exe.
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
tos_header_t ih = {}
tos_header_t oh = {}
LinkerSymbols symbols
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
Copy stub from exe.
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
atari/tos
Definition at line 34 of file p_tos.h.
Member Typedef Documentation
super
typedef Packer PackTos::super private
Definition at line 35 of file p_tos.h.
Constructor & Destructor Documentation
PackTos()
PackTos::PackTos (InputFile * f) explicit
Definition at line 49 of file p_tos.cpp.
                             : super(f) {
    bele = &N_BELE_RTP::be_policy;
    COMPILE_TIME_ASSERT(FH_SIZE == 28)
    COMPILE_TIME_ASSERT_ALIGNED1(tos_header_t)
}
References N_BELE_RTP::be_policy, Packer::bele, COMPILE_TIME_ASSERT, COMPILE_TIME_ASSERT_ALIGNED1, and FH_SIZE.
Member Function Documentation
buildLoader()
void PackTos::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 94 of file p_tos.cpp.
{
    assert(ft->id == 0);
    initLoader(stub_m68k_atari_tos, sizeof(stub_m68k_atari_tos));
    // linker->dumpSymbols();
    //
    // part 1a
    //
    addLoader("entry");
    if (symbols.up21_a6 <= 32767)
        addLoader("set_up21_a6.w");
    else if (symbols.up21_d4 <= 32767)
        addLoader("set_up21_d4.w");
    else
        addLoader("set_up21_d4.l");
    assert(symbols.loop1.count || symbols.loop2.count);
    if (symbols.loop1.count) {
        if (symbols.loop1.value <= 127)
            addLoader("loop1_set_count.b");
        else if (symbols.loop1.value <= 65535)
            addLoader("loop1_set_count.w");
        else
            addLoader("loop1_set_count.l");
        addLoader("loop1_label");
        addLoader(opt->small ? "loop1.small" : "loop1.fast");
        if (symbols.loop1.mode == symbols.LOOP_SUBQ_L)
            addLoader("loop1_subql");
        else if (symbols.loop1.mode == symbols.LOOP_SUBQ_W)
            addLoader("loop1_subqw");
        else if (symbols.loop1.mode == symbols.LOOP_DBRA)
            addLoader("loop1_dbra");
        else
            throwBadLoader();
    }
    if (symbols.loop2.count) {
        assert(symbols.loop2.mode == symbols.LOOP_DBRA);
        addLoader(opt->small ? "loop2.small" : "loop2.fast");
    }
    addLoader("copy_to_stack");
    if (M_IS_NRV2B(ph.method))
        addLoader("nrv2b.init");
    else if (M_IS_NRV2D(ph.method))
        addLoader("nrv2d.init");
    else if (M_IS_NRV2E(ph.method))
        addLoader("nrv2e.init");
    else if (M_IS_LZMA(ph.method))
        addLoader("lzma.init");
    else
        throwBadLoader();
    symbols.up31_d4 = symbols.up31_base_d4 + getDecomprOffset(ph.method, opt->small);
    symbols.up31_a6 = symbols.up31_base_a6 + getDecomprOffset(ph.method, opt->small);
    if (symbols.up31_a6 <= 32767)
        addLoader("jmp_decompressor_a6.w");
    else if (symbols.up31_d4 <= 32767)
        addLoader("jmp_decompressor_d4.w");
    else if (symbols.up31_a6 <= 65534)
        addLoader("jmp_decompressor_a6.w2");
    else
        addLoader("jmp_decompressor_d4.l");
    //
    // part 1b
    //
    addLoader("code_on_stack");
    addLoader("clear_dirty_bss");
    addLoader("loop3_label");
    addLoader(opt->small ? "loop3.small" : "loop3.fast");
    if (symbols.loop3.mode == symbols.LOOP_SUBQ_L)
        addLoader("loop3_subql");
    else if (symbols.loop3.mode == symbols.LOOP_SUBQ_W)
        addLoader("loop3_subqw");
    else if (symbols.loop3.mode == symbols.LOOP_DBRA)
        addLoader("loop3_dbra");
    else
        throwBadLoader();
    addLoader("flush_cache");
    addLoader("restore_stack");
#if 0
    addLoader("clear_dirty_stack");
#endif
    addLoader("start_program");
    addLoader("IDENTSTR,+40D,UPX1HEAD,CUTPOINT");
    //
    // part 2
    //
    if (M_IS_NRV2B(ph.method)) {
        addLoader(opt->small ? "nrv2b_8.small" : "nrv2b_8.fast");
    } else if (M_IS_NRV2D(ph.method)) {
        addLoader(opt->small ? "nrv2d_8.small" : "nrv2d_8.fast");
    } else if (M_IS_NRV2E(ph.method)) {
        addLoader(opt->small ? "nrv2e_8.small" : "nrv2e_8.fast");
    } else if (M_IS_LZMA(ph.method)) {
        addLoader("__mulsi3");
        addLoader(opt->small ? "lzma.small" : "lzma.fast");
        addLoader("lzma.finish");
    } else
        throwBadLoader();
    if (symbols.need_reloc)
        addLoader("reloc");
    assert(symbols.loop3.count);
    if (symbols.loop3.value <= 127)
        addLoader("loop3_set_count.b");
    else if (symbols.loop3.value <= 65535)
        addLoader("loop3_set_count.w");
    else
        addLoader("loop3_set_count.l");
    addLoader("jmp_stack");
}
References Packer::addLoader(), PackTos::LinkerSymbols::LoopInfo::count, getDecomprOffset(), Filter::id, Packer::initLoader(), PackTos::LinkerSymbols::loop1, PackTos::LinkerSymbols::loop2, PackTos::LinkerSymbols::loop3, PackTos::LinkerSymbols::LOOP_DBRA, PackTos::LinkerSymbols::LOOP_SUBQ_L, PackTos::LinkerSymbols::LOOP_SUBQ_W, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, PackHeader::method, PackTos::LinkerSymbols::LoopInfo::mode, PackTos::LinkerSymbols::need_reloc, opt, PackerBase::ph, stub_m68k_atari_tos, symbols, throwBadLoader(), PackTos::LinkerSymbols::up21_a6, PackTos::LinkerSymbols::up21_d4, PackTos::LinkerSymbols::up31_a6, PackTos::LinkerSymbols::up31_base_a6, PackTos::LinkerSymbols::up31_base_d4, PackTos::LinkerSymbols::up31_d4, and PackTos::LinkerSymbols::LoopInfo::value.
Referenced by pack().
canPack()
tribool PackTos::canPack () override virtual
Implements PackerBase.
Definition at line 345 of file p_tos.cpp.
{
    if (!readFileHeader())
        return false;
    byte buf[768];
    fi->readx(buf, sizeof(buf));
    checkAlreadyPacked(buf, sizeof(buf));
    if (!checkFileHeader())
        throwCantPack("unsupported header flags");
    if (file_size < 1024)
        throwCantPack("program is too small for atari/tos");
    return true;
}
References buf, Packer::checkAlreadyPacked(), checkFileHeader(), PackerBase::fi, PackerBase::file_size, readFileHeader(), InputFile::readx(), and throwCantPack().
canUnpack()
tribool PackTos::canUnpack () override virtual
Implements PackerBase.
Definition at line 676 of file p_tos.cpp.
{
    if (!readFileHeader())
        return false;
    if (!readPackHeader(768))
        return false;
    // check header as set by packer
    if ((ih.fh_text & 3) != 0 || (ih.fh_data & 3) != 0 || (ih.fh_bss & 3) != 0 || ih.fh_sym != 0 ||
        ih.fh_reserved != 0 || ih.fh_reloc > 1)
        throwCantUnpack("program header damaged");
    // generic check
    if (!checkFileHeader())
        throwCantUnpack("unsupported header flags");
    return true;
}
References checkFileHeader(), PackTos::tos_header_t::fh_bss, PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_reloc, PackTos::tos_header_t::fh_reserved, PackTos::tos_header_t::fh_sym, PackTos::tos_header_t::fh_text, ih, readFileHeader(), Packer::readPackHeader(), and throwCantUnpack().
checkFileHeader()
bool PackTos::checkFileHeader () protected
Definition at line 268 of file p_tos.cpp.
{
    const unsigned f = ih.fh_flag;
    // printf("flags: 0x%x, text: %d, data: %d, bss: %d, sym: %d\n", f, (int) ih.fh_text,
    //        (int) ih.fh_data, (int) ih.fh_bss, (int) ih.fh_sym);
    if ((ih.fh_text & 1) || (ih.fh_data & 1))
        throwCantPack("odd size values in text/data");
    if (f & F_OS_SPECIAL)
        throwCantPack("I won't pack F_OS_SPECIAL programs");
    if ((f & F_PROTMODE) > F_PROT_I)
        throwCantPack("invalid protection mode");
    if ((f & F_PROTMODE) != F_PROT_P) {
        if (opt->force < 1)
            throwCantPack("no private memory protection; use option '-f' to force packing");
    }
    if (f & F_SHTEXT) {
        if (opt->force < 1)
            throwCantPack("shared text segment; use option '-f' to force packing");
    }
#if 0
    // fh_reserved seems to be unused
    if (ih.fh_reserved != 0) {
        if (opt->force < 1)
            throwCantPack("reserved header field set; use option '-f' to force packing");
    }
#endif
    return true;
}
References F_OS_SPECIAL, F_PROT_I, F_PROT_P, F_PROTMODE, F_SHTEXT, PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_flag, PackTos::tos_header_t::fh_reserved, PackTos::tos_header_t::fh_text, ih, opt, and throwCantPack().
Referenced by canPack(), and canUnpack().
fileInfo()
void PackTos::fileInfo () override virtual
Reimplemented from Packer.
Definition at line 361 of file p_tos.cpp.
                       {
    if (!readFileHeader())
        return;
    con_fprintf(stdout, "    text: %d, data: %d, sym: %d, bss: %d, flags=0x%x\n", (int) ih.fh_text,
                (int) ih.fh_data, (int) ih.fh_sym, (int) ih.fh_bss, (int) ih.fh_flag);
}
References con_fprintf, PackTos::tos_header_t::fh_bss, PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_flag, PackTos::tos_header_t::fh_sym, PackTos::tos_header_t::fh_text, ih, and readFileHeader().
getCompressionMethods()
const int * PackTos::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 57 of file p_tos.cpp.
{
    bool small = ih.fh_text + ih.fh_data <= 256 * 1024;
    return Packer::getDefaultCompressionMethods_8(method, level, small);
}
References PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_text, Packer::getDefaultCompressionMethods_8(), and ih.
getDecomprOffset()
unsigned PackTos::getDecomprOffset (int method, int small) const protected
Definition at line 79 of file p_tos.cpp.
{
    UNUSED(small);
    if (M_IS_NRV2B(method))
        return 2; // FIXME: do not hardcode this value
    else if (M_IS_NRV2D(method))
        return 2; // FIXME: do not hardcode this value
    else if (M_IS_NRV2E(method))
        return 2; // FIXME: do not hardcode this value
    else if (M_IS_LZMA(method))
        return linker->getSectionSize("__mulsi3");
    else
        throwBadLoader();
    return 0;
}
References M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, throwBadLoader(), and UNUSED.
Referenced by buildLoader().
getFilters()
const int * PackTos::getFilters () const override virtual
Implements PackerBase.
Definition at line 62 of file p_tos.cpp.
{ return nullptr; }
getFormat()
virtual int PackTos::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 40 of file p_tos.h.
{ return UPX_F_ATARI_TOS; }
References UPX_F_ATARI_TOS.
getFullName()
virtual const char * PackTos::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 42 of file p_tos.h.
{ return "m68k-atari.tos"; }
getName()
virtual const char * PackTos::getName () const inline override virtual
Implements PackerBase.
Definition at line 41 of file p_tos.h.
{ return "atari/tos"; }
getVersion()
virtual int PackTos::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 39 of file p_tos.h.
{ return 13; }
newLinker()
Linker * PackTos::newLinker () const override protected virtual
Implements Packer.
Definition at line 55 of file p_tos.cpp.
{ return new ElfLinkerM68k; }
pack()
void PackTos::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 372 of file p_tos.cpp.
{
    unsigned t;
    unsigned relocnum = 0;
    unsigned relocsize = 0;
    unsigned overlay = 0;
    const unsigned i_text = ih.fh_text;
    const unsigned i_data = ih.fh_data;
    const unsigned i_sym = ih.fh_sym;
    const unsigned i_bss = ih.fh_bss;
    symbols.reset();
    symbols.need_reloc = false;
    // prepare symbols for buildLoader() - worst case
    symbols.loop1.init(65536 + 1);
    symbols.loop2.init((160 - 1) / 4);
    symbols.loop3.init(65536 + 1);
    symbols.up21_d4 = 65536 + 1;
    symbols.up21_a6 = 65536 + 1;
    symbols.up31_base_d4 = 65536 + 1;
    symbols.up31_base_a6 = 65536 + 1;
    // read file
    const unsigned isize = file_size_u - i_sym;
    ibuf.alloc(isize);
    fi->seek(FH_SIZE, SEEK_SET);
    // read text + data
    t = i_text + i_data;
    fi->readx(ibuf, t);
    // skip symbols
    if (i_sym && opt->exact)
        throwCantPackExact();
    fi->seek(i_sym, SEEK_CUR);
    // read relocations + overlay
    overlay = file_size_u - (FH_SIZE + i_text + i_data + i_sym);
    fi->readx(ibuf + t, overlay);
#if TESTING
    printf("text: %d, data: %d, sym: %d, bss: %d, flags=0x%x\n", i_text, i_data, i_sym, i_bss,
           (int) ih.fh_flag);
    printf("xx1 reloc: %d, overlay: %d, fixup: %d\n", relocsize, overlay,
           overlay >= 4 ? (int) get_be32(ibuf + t) : -1);
#endif
    // Check relocs (see load_and_reloc() in freemint/sys/memory.c).
    // Must work around TOS bugs and lots of broken programs.
    if (overlay < 4) {
        // Bug workaround: Whatever this is, silently keep it in
        // the (unused) relocations for byte-identical unpacking.
        relocsize = overlay;
        overlay = 0;
    } else if (get_be32(ibuf + t) == 0) {
        // Bug workaround - check the empty fixup before testing fh_reloc.
        relocsize = 4;
        overlay -= 4;
    } else if (ih.fh_reloc != 0)
        relocsize = 0;
    else {
        if (!check_relocs(ibuf + t, overlay, t, &relocnum, &relocsize, &overlay))
            throwCantPack("bad relocation table");
        symbols.need_reloc = true;
    }
#if TESTING
    printf("xx2: %d relocs: %d, overlay: %d, t: %d\n", relocnum, relocsize, overlay, t);
#endif
    checkOverlay(overlay);
    // Append original fileheader.
    t += relocsize;
    ih.fh_sym = 0; // we stripped all symbols
    memcpy(ibuf + t, &ih, FH_SIZE);
    t += FH_SIZE;
#if TESTING
    printf("xx3 reloc: %d, overlay: %d, t: %d\n", relocsize, overlay, t);
#endif
    assert(t <= isize);
    // Now the data in ibuf[0..t] looks like this:
    //   text + data + relocs + original file header
    // After compression this will become the first part of the
    // data segment. The second part will be the decompressor.
    // alloc buffer (4096 is for decompressor and the various alignments)
    obuf.allocForCompression(t, 4096);
    // prepare packheader
    ph.u_len = t;
    // prepare filter
    Filter ft(ph.level);
    // compress (max_match = 65535)
    upx_compress_config_t cconf;
    cconf.reset();
    cconf.conf_ucl.max_match = 65535;
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    compressWithFilters(&ft, 512, &cconf);
    //
    // multipass buildLoader()
    //
    // save initial loader
    const unsigned initial_lsize = getLoaderSize();
    unsigned last_lsize = initial_lsize;
    MemBuffer last_loader(last_lsize);
    memcpy(last_loader, getLoader(), last_lsize);
    unsigned o_text, o_data, o_bss;
    unsigned e_len, d_len, d_off;
    for (;;) {
        // The decompressed data will now get placed at this offset:
        unsigned offset = (ph.u_len + ph.overlap_overhead) - ph.c_len;
        // get loader
        const unsigned lsize = getLoaderSize();
        e_len = getLoaderSectionStart("CUTPOINT");
        d_len = lsize - e_len;
        assert((e_len & 3) == 0 && (d_len & 1) == 0);
        // compute section sizes
        o_text = e_len;
        o_data = ph.c_len;
        o_bss = i_bss;
        // word align len of compressed data
        while (o_data & 1) {
            obuf[o_data++] = 0;
            offset++;
        }
        // append decompressor (part 2 of loader)
        d_off = o_data;
        o_data += d_len;
        // dword align the len of the final data segment
        while (o_data & 3) {
            obuf[o_data++] = 0;
            offset++;
        }
        // dword align offset
        while (offset & 3)
            offset++;
        // new bss
        if (i_text + i_data + i_bss > o_text + o_data + o_bss)
            o_bss = (i_text + i_data + i_bss) - (o_text + o_data);
        // dirty bss
        unsigned dirty_bss = (o_data + offset) - (i_text + i_data);
        // printf("real dirty_bss: %d\n", dirty_bss);
        // dword align (or 16 - for speedup when clearing the dirty bss)
        const unsigned dirty_bss_align = opt->small ? 4 : 16;
        while (dirty_bss & (dirty_bss_align - 1))
            dirty_bss++;
        // adjust bss, assert room for some stack
        unsigned stack = 512 + getDecompressorWrkmemSize();
        if (dirty_bss + stack > o_bss)
            o_bss = dirty_bss + stack;
        // dword align the len of the final bss segment
        while (o_bss & 3)
            o_bss++;
        // update symbols for buildLoader()
        if (opt->small) {
            symbols.loop1.init(o_data / 4);
            symbols.loop2.init(0);
        } else {
            symbols.loop1.init(o_data / 160);
            symbols.loop2.init((o_data % 160) / 4);
        }
        symbols.loop3.init(dirty_bss / dirty_bss_align);
        symbols.up21_d4 = o_data + offset;
        symbols.up31_base_d4 = d_off + offset;
        symbols.up21_a6 = symbols.up21_d4 - (i_text + i_data);
        symbols.up31_base_a6 = symbols.up31_base_d4 - (i_text + i_data);
        assert((int) symbols.up21_a6 > 0);
        assert((int) symbols.up31_base_a6 > 0);
        const unsigned c = linker->getSymbolOffset("code_on_stack");
        unsigned d;
        d = linker->getSymbolOffset("flush_cache_rts") - c;
        symbols.flush_cache_rts_offset = d;
        d = linker->getSymbolOffset("clear_dirty_stack_loop") - c;
        symbols.clear_dirty_stack_len = (d + 3) / 4 + 32 - 1;
        d = linker->getSymbolOffset("code_on_stack_end") - c;
        symbols.copy_to_stack_len = d / 2 - 1;
        // now re-build loader
        buildLoader(&ft);
        unsigned new_lsize = getLoaderSize();
        // printf("buildLoader %d %d\n", new_lsize, initial_lsize);
        assert(new_lsize <= initial_lsize);
        if (new_lsize == last_lsize && memcmp(getLoader(), last_loader, last_lsize) == 0)
            break;
        last_lsize = new_lsize;
        memcpy(last_loader, getLoader(), last_lsize);
    }
    //
    // define symbols and reloc
    //
    defineDecompressorSymbols();
    linker->defineSymbol("loop1_count", symbols.loop1.value);
    linker->defineSymbol("loop2_count", symbols.loop2.value);
    linker->defineSymbol("loop3_count", symbols.loop3.value);
    linker->defineSymbol("orig_p_tlen", i_text);
    linker->defineSymbol("orig_p_dlen", i_data);
    linker->defineSymbol("orig_p_blen", i_bss);
    if (symbols.up21_a6 <= 32767)
        linker->defineSymbol("up21_a6", symbols.up21_a6);
    else
        linker->defineSymbol("up21_d4", symbols.up21_d4);
    if (symbols.up31_a6 <= 32767)
        linker->defineSymbol("up31_a6", symbols.up31_a6);
    else if (symbols.up31_d4 <= 32767)
        linker->defineSymbol("up31_d4", symbols.up31_d4);
    else if (symbols.up31_a6 <= 65534)
        linker->defineSymbol("up31_a6", symbols.up31_a6 - 32767);
    else
        linker->defineSymbol("up31_d4", symbols.up31_d4);
#if 0
    printf("relocsize = %d\n", relocsize);
    printf("upx21(d4) = %d\n", symbols.up21_d4);
    printf("upx21(a6) = %d\n", symbols.up21_a6);
    printf("upx31(d4) = %d\n", symbols.up31_d4);
    printf("upx31(a6) = %d\n", symbols.up31_a6);
#endif
    linker->defineSymbol("flush_cache_rts_offset", symbols.flush_cache_rts_offset);
    linker->defineSymbol("copy_to_stack_len", symbols.copy_to_stack_len);
    linker->defineSymbol("clear_dirty_stack_len", symbols.clear_dirty_stack_len);
    relocateLoader();
    //
    // write
    //
    // set new file_hdr
    memcpy(&oh, &ih, FH_SIZE);
    if (opt->atari_tos.split_segments) {
        oh.fh_text = o_text;
        oh.fh_data = o_data;
    } else {
        // put everything into the text segment
        oh.fh_text = o_text + o_data;
        oh.fh_data = 0;
    }
    oh.fh_bss = o_bss;
    oh.fh_sym = 0;
    oh.fh_reserved = 0;
    // only keep the following flags:
    oh.fh_flag = ih.fh_flag & (F_FASTLOAD | F_ALTALLOC | F_SMALLTPA | F_ALLOCZERO | F_KEEP);
    // add an empty relocation fixup to workaround a bug in some TOS versions
    oh.fh_reloc = 0;
#if TESTING
    printf("old text: %6d, data: %6d, bss: %6d, reloc: %d, overlay: %d\n", i_text, i_data, i_bss,
           relocsize, overlay);
    printf("new text: %6d, data: %6d, bss: %6d, flag=0x%x\n", o_text, o_data, o_bss,
           (int) oh.fh_flag);
    linker->dumpSymbols();
#endif
    // prepare loader
    MemBuffer loader(o_text);
    memcpy(loader, getLoader(), o_text);
    patchPackHeader(loader, o_text);
    // write new file header, loader and compressed file
    fo->write(&oh, FH_SIZE);
    fo->write(loader, o_text); // entry
    if (opt->debug.dump_stub_loader)
        OutputFile::dump(opt->debug.dump_stub_loader, loader, o_text);
    memcpy(obuf + d_off, getLoader() + e_len, d_len); // copy decompressor
    fo->write(obuf, o_data);                          // compressed + decompressor
    // write empty relocation fixup
    fo->write("\x00\x00\x00\x00", 4);
    // verify
    verifyOverlappingDecompression();
    // copy the overlay
    copyOverlay(fo, overlay, obuf);
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References MemBuffer::alloc(), MemBuffer::allocForCompression(), buildLoader(), PackHeader::c_len, check_relocs(), Packer::checkFinalCompressionRatio(), Packer::checkOverlay(), PackTos::LinkerSymbols::clear_dirty_stack_len, Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, upx_compress_config_t::conf_ucl, PackTos::LinkerSymbols::copy_to_stack_len, Packer::copyOverlay(), Packer::defineDecompressorSymbols(), OutputFile::dump(), F_ALLOCZERO, F_ALTALLOC, F_FASTLOAD, F_KEEP, F_SMALLTPA, PackTos::tos_header_t::fh_bss, PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_flag, PackTos::tos_header_t::fh_reloc, PackTos::tos_header_t::fh_reserved, FH_SIZE, PackTos::tos_header_t::fh_sym, PackTos::tos_header_t::fh_text, PackerBase::fi, PackerBase::file_size_u, PackTos::LinkerSymbols::flush_cache_rts_offset, get_be32(), Packer::getDecompressorWrkmemSize(), Packer::getLoader(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), Packer::ibuf, ih, PackTos::LinkerSymbols::LoopInfo::init(), PackHeader::level, PackTos::LinkerSymbols::loop1, PackTos::LinkerSymbols::loop2, PackTos::LinkerSymbols::loop3, lzma_compress_config_t::max_num_probs, memcmp(), memcpy(), PackTos::LinkerSymbols::need_reloc, Packer::obuf, oh, opt, PackHeader::overlap_overhead, Packer::patchPackHeader(), PackerBase::ph, InputFile::readx(), Packer::relocateLoader(), upx_compress_config_t::reset(), PackTos::LinkerSymbols::reset(), InputFile::seek(), SEEK_CUR, SEEK_SET, symbols, throwCantPack(), throwCantPackExact(), throwNotCompressible(), PackHeader::u_len, PackTos::LinkerSymbols::up21_a6, PackTos::LinkerSymbols::up21_d4, PackTos::LinkerSymbols::up31_a6, PackTos::LinkerSymbols::up31_base_a6, PackTos::LinkerSymbols::up31_base_d4, PackTos::LinkerSymbols::up31_d4, PackTos::LinkerSymbols::LoopInfo::value, Packer::verifyOverlappingDecompression(), and OutputFile::write().
readFileHeader()
int PackTos::readFileHeader () protected
util readFileHeader() reads ih and checks for illegal values checkFileHeader() checks ih for legal but unsupported values
Definition at line 258 of file p_tos.cpp.
{
    fi->seek(0, SEEK_SET);
    fi->readx(&ih, FH_SIZE);
    if (ih.fh_magic != 0x601a)
        return 0;
    if (0ull + FH_SIZE + ih.fh_text + ih.fh_data + ih.fh_sym > file_size_u)
        return 0;
    return UPX_F_ATARI_TOS;
}
References PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_magic, FH_SIZE, PackTos::tos_header_t::fh_sym, PackTos::tos_header_t::fh_text, PackerBase::fi, PackerBase::file_size_u, ih, InputFile::readx(), InputFile::seek(), SEEK_SET, and UPX_F_ATARI_TOS.
Referenced by canPack(), canUnpack(), and fileInfo().
unpack()
void PackTos::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 695 of file p_tos.cpp.
{
    ibuf.alloc(ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    fi->seek(FH_SIZE + ph.buf_offset + ph.getPackHeaderSize(), SEEK_SET);
    fi->readx(ibuf, ph.c_len);
    // decompress
    decompress(ibuf, obuf);
    // write original header & decompressed file
    if (fo) {
        unsigned overlay = file_size_u - (FH_SIZE + ih.fh_text + ih.fh_data);
        if (ih.fh_reloc == 0 && overlay >= 4)
            overlay -= 4; // this is our empty fixup
        checkOverlay(overlay);
        fo->write(obuf + ph.u_len - FH_SIZE, FH_SIZE); // orig. file_hdr
        fo->write(obuf, ph.u_len - FH_SIZE);           // orig. text+data+relocs
        // copy any overlay
        copyOverlay(fo, overlay, obuf);
    }
}
References MemBuffer::alloc(), MemBuffer::allocForDecompression(), PackHeader::buf_offset, PackHeader::c_len, Packer::checkOverlay(), Packer::copyOverlay(), Packer::decompress(), PackTos::tos_header_t::fh_data, PackTos::tos_header_t::fh_reloc, FH_SIZE, PackTos::tos_header_t::fh_text, PackerBase::fi, PackerBase::file_size_u, PackHeader::getPackHeaderSize(), Packer::ibuf, ih, Packer::obuf, PackerBase::ph, InputFile::readx(), InputFile::seek(), SEEK_SET, PackHeader::u_len, and OutputFile::write().
Member Data Documentation
ih
tos_header_t PackTos::ih = {} protected
Definition at line 74 of file p_tos.h.
Referenced by canUnpack(), checkFileHeader(), fileInfo(), getCompressionMethods(), pack(), readFileHeader(), and unpack().
oh
tos_header_t PackTos::oh = {} protected
Definition at line 74 of file p_tos.h.
Referenced by pack().
symbols
LinkerSymbols PackTos::symbols protected
Definition at line 104 of file p_tos.h.
Referenced by buildLoader(), and pack().
The documentation for this class was generated from the following files:
src/p_tos.h
src/p_tos.cpp