My Project: PeFile::Interval Class Reference
PeFile::Interval Class Reference final
#include <pefile.h>
Classes
struct interval
Public Member Functions
Interval (SPAN_P(byte))
interval handling
~Interval () noexcept
void add_interval (unsigned start, unsigned len)
void add_interval (const void *start, unsigned len)
void add_interval (const void *start, const void *end)
void add_interval (const Interval *other)
void flatten ()
void clear ()
void dump () const
Public Attributes
struct interval * ivarr = nullptr
unsigned ivnum = 0
Private Member Functions
SPAN_0 (byte) base
Private Member Functions inherited from upx::noncopyable
forceinline constexpr noncopyable () noexcept
forceinline ~noncopyable () noexcept=default
Static Private Member Functions
static int __acc_cdecl_qsort compare (const void *p1, const void *p2)
Private Attributes
unsigned ivcapacity = 0
Detailed Description
Definition at line 399 of file pefile.h.
Constructor & Destructor Documentation
Interval()
PeFile::Interval::Interval (SPAN_P(byte) b) explicit
interval handling
Definition at line 216 of file pefile.cpp.
: base(b) {}
~Interval()
PeFile::Interval::~Interval () noexcept
Definition at line 218 of file pefile.cpp.
{ ::free(ivarr); }
Member Function Documentation
add_interval() [1/4]
void PeFile::Interval::add_interval (const Interval * other)
Definition at line 253 of file pefile.cpp.
{
    for (unsigned ic = 0; ic < other->ivnum; ic++)
        add_interval(other->ivarr[ic].start, other->ivarr[ic].len);
}
References ivarr, ivnum, PeFile::Interval::interval::len, and PeFile::Interval::interval::start.
add_interval() [2/4]
void PeFile::Interval::add_interval (const void * start, const void * end)
Definition at line 249 of file pefile.cpp.
{
    add_interval(ptr_udiff_bytes(start, base), ptr_udiff_bytes(end, start));
}
References base, and ptr_udiff_bytes().
add_interval() [3/4]
void PeFile::Interval::add_interval (const void * start, unsigned len)
Definition at line 245 of file pefile.cpp.
{
    add_interval(ptr_udiff_bytes(start, base), len);
}
References base, and ptr_udiff_bytes().
add_interval() [4/4]
void PeFile::Interval::add_interval (unsigned start, unsigned len)
Definition at line 234 of file pefile.cpp.
{
    if (ivnum == ivcapacity) {
        ivcapacity += 15;
        ivarr = (interval *) realloc(ivarr, mem_size(sizeof(interval), ivcapacity));
        assert(ivarr != nullptr);
    }
    ivarr[ivnum].start = start;
    ivarr[ivnum].len = len;
    ivnum += 1;
}
References mem_size().
Referenced by PeFile::Resource::clear(), PeFile::processImports0(), PeFile::processLoadConf(), and PeFile::processTls1().
clear()
void PeFile::Interval::clear ()
Definition at line 274 of file pefile.cpp.
{
    for (unsigned ic = 0; ic < ivnum; ic++)
        memset(base + ivarr[ic].start, 0, ivarr[ic].len);
}
References base, and memset().
Referenced by PeFile::Resource::clear(), and PeFile::processImports0().
compare()
int __acc_cdecl_qsort PeFile::Interval::compare (const void * p1, const void * p2) static private
Definition at line 220 of file pefile.cpp.
{
    const interval *i1 = (const interval *) p1;
    const interval *i2 = (const interval *) p2;
    if (i1->start < i2->start)
        return -1;
    if (i1->start > i2->start)
        return 1;
    if (i1->len < i2->len)
        return 1;
    if (i1->len > i2->len)
        return -1;
    return 0;
}
References PeFile::Interval::interval::len, and PeFile::Interval::interval::start.
Referenced by flatten().
dump()
void PeFile::Interval::dump () const
Definition at line 279 of file pefile.cpp.
{
    printf("%d intervals:\n", ivnum);
    for (unsigned ic = 0; ic < ivnum; ic++)
        printf("%x %x\n", ivarr[ic].start, ivarr[ic].len);
}
Referenced by PeFile::Resource::clear().
flatten()
void PeFile::Interval::flatten ()
Definition at line 258 of file pefile.cpp.
{
    if (!ivnum)
        return;
    upx_qsort(ivarr, ivnum, sizeof(ivarr[0]), Interval::compare);
    for (unsigned ic = 0; ic < ivnum - 1; ic++) {
        unsigned jc;
        for (jc = ic + 1; jc < ivnum && ivarr[ic].start + ivarr[ic].len >= ivarr[jc].start; jc++)
            if (ivarr[ic].start + ivarr[ic].len < ivarr[jc].start + ivarr[jc].len)
                ivarr[ic].len = ivarr[jc].start + ivarr[jc].len - ivarr[ic].start;
        if (jc > ic + 1) {
            memmove(ivarr + ic + 1, ivarr + jc, sizeof(interval) * (ivnum - jc));
            ivnum -= jc - ic - 1;
        }
    }
}
References compare(), memmove(), and upx_qsort.
Referenced by PeFile::Resource::clear().
SPAN_0()
PeFile::Interval::SPAN_0 (byte) private
Member Data Documentation
ivarr
struct interval* PeFile::Interval::ivarr = nullptr
Definition at line 406 of file pefile.h.
Referenced by add_interval(), PeFile::processLoadConf(), and PeFile::processTls2().
ivcapacity
unsigned PeFile::Interval::ivcapacity = 0 private
Definition at line 401 of file pefile.h.
ivnum
unsigned PeFile::Interval::ivnum = 0
Definition at line 407 of file pefile.h.
Referenced by add_interval(), PeFile::Resource::clear(), PeFile::pack0(), PeFile::processLoadConf(), PeFile::processTls1(), and PeFile::processTls2().
The documentation for this class was generated from the following files:
src/pefile.h
src/pefile.cpp