My Project: PackTmt Class Reference
PackTmt Class Reference final
tmt/adam
#include <p_tmt.h>
Classes
struct tmt_header_t
Public Member Functions
PackTmt (InputFile *f)
virtual int getVersion () const override
virtual int getFormat () const override
virtual const char * getName () const override
virtual const char * getFullName (const Options *) const override
virtual const int * getCompressionMethods (int method, int level) const override
virtual const int * getFilters () const override
virtual void pack (OutputFile *fo) override
virtual void unpack (OutputFile *fo) override
virtual tribool canPack () override
virtual tribool canUnpack () override
Public Member Functions inherited from Packer
virtual ~Packer () noexcept
virtual void assertPacker () const override
virtual void initPackHeader () final override
packheader util
virtual void updatePackHeader () final override
virtual void doPack (OutputFile *fo) final override
public entries called from class PackMaster
virtual void doUnpack (OutputFile *fo) final override
virtual void doTest () final override
virtual void doList () final override
virtual void doFileInfo () final override
virtual bool canUnpackVersion (int version) const
virtual bool canUnpackFormat (int format) const
Public Member Functions inherited from PackerBase
virtual ~PackerBase () noexcept
virtual int getVersion () const =0
virtual int getFormat () const =0
virtual const char * getName () const =0
virtual const char * getFullName (const Options *) const =0
virtual const int * getCompressionMethods (int method, int level) const =0
virtual const int * getFilters () const =0
virtual tribool canPack ()=0
virtual tribool canUnpack ()=0
virtual void assertPacker () const =0
virtual void initPackHeader ()=0
virtual void updatePackHeader ()=0
virtual void doPack (OutputFile *fo)=0
virtual void doUnpack (OutputFile *fo)=0
virtual void doTest ()=0
virtual void doList ()=0
virtual void doFileInfo ()=0
Protected Member Functions
int readFileHeader ()
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const override
Find overhead for in-place decompression in a heuristic way (using a binary search).
virtual void buildLoader (const Filter *ft) override
virtual Linker * newLinker () const override
Protected Member Functions inherited from Packer
Packer (InputFile *f)
virtual bool testUnpackVersion (int version) const may_throw
virtual bool testUnpackFormat (int format) const may_throw
virtual void pack (OutputFile *fo)=0
virtual void unpack (OutputFile *fo)=0
virtual void test ()
default actions
virtual void list ()
virtual void fileInfo ()
bool compress (SPAN_P(byte) i_ptr, unsigned i_len, SPAN_P(byte) o_ptr, const upx_compress_config_t *cconf=nullptr)
compress - wrap call to low-level upx_compress()
void decompress (SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum=true, Filter *ft=nullptr)
decompress
virtual bool checkDefaultCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkCompressionRatio (unsigned u_len, unsigned c_len) const
virtual bool checkFinalCompressionRatio (const OutputFile *fo) const
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy=0, bool inhibit_compression_check=false)
void compressWithFilters (Filter *ft, const unsigned overlap_range, const upx_compress_config_t *cconf, int filter_strategy, unsigned filter_buf_off, unsigned compress_ibuf_off, unsigned compress_obuf_off, byte *const hdr_ptr, unsigned hdr_len, bool inhibit_compression_check=false)
void compressWithFilters (byte *i_ptr, unsigned i_len, byte *o_ptr, byte *f_ptr, unsigned f_len, byte *const hdr_ptr, unsigned hdr_len, Filter *parm_ft, unsigned overlap_range, upx_compress_config_t const *cconf, int filter_strategy, bool inhibit_compression_check=false)
virtual bool testOverlappingDecompression (const byte *buf, const byte *tbuf, unsigned overlap_overhead) const
overlapping decompression
virtual unsigned findOverlapOverhead (const byte *buf, const byte *tbuf, unsigned range=0, unsigned upper_limit=~0u) const
Find overhead for in-place decompression in a heuristic way (using a binary search).
void verifyOverlappingDecompression (Filter *ft=nullptr)
void verifyOverlappingDecompression (byte *o_ptr, unsigned o_size, Filter *ft=nullptr)
virtual int patchPackHeader (void *b, int blen) final
virtual bool getPackHeader (const void *b, int blen, bool allow_incompressible=false) final
virtual bool readPackHeader (int len, bool allow_incompressible=false) final
virtual void checkAlreadyPacked (const void *b, int blen) final
virtual void buildLoader (const Filter *ft)=0
virtual Linker * newLinker () const =0
virtual void relocateLoader ()
virtual byte * getLoader () const
virtual int getLoaderSize () const
virtual void initLoader (const void *pdata, int plen, int small=-1, int pextra=0)
void addLoader (C)
void addLoader (C, C)
void addLoader (C, C, C)
void addLoader (C, C, C, C)
void addLoader (C, C, C, C, C)
void addLoader (C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C)
void addLoader (C, C, C, C, C, C, C, C, C, C)
void addLoaderVA (const char *s,...)
virtual bool hasLoaderSection (const char *name) const
virtual int getLoaderSection (const char *name, int *slen=nullptr) const
virtual int getLoaderSectionStart (const char *name, int *slen=nullptr) const
const int * getDefaultCompressionMethods_8 (int method, int level, int small=-1) const
const int * getDefaultCompressionMethods_le32 (int method, int level, int small=-1) const
int prepareMethods (int *methods, int ph_method, const int *all_methods) const
void Packer::compressWithFilters(): Try compression with several methods and filters, choose the best / or first working one.
virtual const char * getDecompressorSections () const
virtual unsigned getDecompressorWrkmemSize () const
virtual void defineDecompressorSymbols ()
virtual bool isValidFilter (int filter_id) const
filter util; see class FilterImpl
virtual void optimizeFilter (Filter *, const byte *, unsigned) const
virtual void addFilter32 (int filter_id)
virtual void defineFilterSymbols (const Filter *ft)
virtual void checkOverlay (unsigned overlay)
virtual void copyOverlay (OutputFile *fo, unsigned overlay, MemBuffer &buf, bool do_seek=true)
virtual unsigned getRandomId () const
int patch_be16 (void *b, int blen, unsigned old, unsigned new_)
int patch_be16 (void *b, int blen, const void *old, unsigned new_)
int patch_be32 (void *b, int blen, unsigned old, unsigned new_)
int patch_be32 (void *b, int blen, const void *old, unsigned new_)
int patch_le16 (void *b, int blen, unsigned old, unsigned new_)
int patch_le16 (void *b, int blen, const void *old, unsigned new_)
int patch_le32 (void *b, int blen, unsigned old, unsigned new_)
int patch_le32 (void *b, int blen, const void *old, unsigned new_)
void checkPatch (void *b, int blen, int boff, int size)
patch util for loader
unsigned get_te16 (const void *p) const noexcept
unsigned get_te32 (const void *p) const noexcept
unsigned get_te64_32 (const void *p) const
upx_uint64_t get_te64 (const void *p) const noexcept
void set_te16 (void *p, unsigned v) noexcept
void set_te32 (void *p, unsigned v) noexcept
void set_te64 (void *p, upx_uint64_t v) noexcept
OwningPointer (UiPacker) uip
OwningPointer (Linker) linker
Protected Member Functions inherited from PackerBase
PackerBase (InputFile *f)
Protected Attributes
unsigned adam_offset = 0
int big_relocs = 0
tmt_header_t ih = {}
tmt_header_t oh = {}
Protected Attributes inherited from Packer
const N_BELE_RTP::AbstractPolicy * bele = nullptr
int ph_format = -1
int ph_version = -1
MemBuffer ibuf
MemBuffer obuf
unsigned ibufgood = 0
Protected Attributes inherited from PackerBase
InputFile *const fi
union {
const upx_int64_t file_size
const upx_uint64_t file_size_u
const upx_int64_t file_size_i64
const upx_uint64_t file_size_u64
};
union {
const upx_int32_t file_size_i32
const upx_uint32_t file_size_u32
};
PackHeader ph
Private Types
typedef Packer super
Additional Inherited Members
Static Public Member Functions inherited from Packer
static bool isValidCompressionMethod (int method)
compression method util
Static Public Attributes inherited from PackerBase
static constexpr unsigned MAX_METHODS = 8
static constexpr unsigned MAX_FILTERS = 16
Static Protected Member Functions inherited from Packer
static void handleStub (InputFile *fi, OutputFile *fo, unsigned size)
file i/o utils
static unsigned optimizeReloc (unsigned relocnum, SPAN_P(byte) relocs, SPAN_S(byte) out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap, int *big)
sort and delta-compress relocations with optional bswap within image returns number of bytes written to 'out'
static unsigned unoptimizeReloc (SPAN_S(const byte) &in, MemBuffer &out, SPAN_P(byte) image, unsigned image_size, int bits, bool bswap)
delta-decompress relocations advances 'in' allocates 'out' and returns number of relocs written to 'out'
Detailed Description
tmt/adam
Definition at line 34 of file p_tmt.h.
Member Typedef Documentation
super
typedef Packer PackTmt::super private
Definition at line 35 of file p_tmt.h.
Constructor & Destructor Documentation
PackTmt()
static const CLANG_FORMAT_DUMMY_STATEMENT PackTmt::PackTmt (InputFile * f) explicit
Definition at line 42 of file p_tmt.cpp.
                             : super(f) {
    bele = &N_BELE_RTP::le_policy;
    COMPILE_TIME_ASSERT(sizeof(tmt_header_t) == 44)
}
References Packer::bele, COMPILE_TIME_ASSERT, and N_BELE_RTP::le_policy.
Member Function Documentation
buildLoader()
void PackTmt::buildLoader (const Filter * ft) override protected virtual
Implements Packer.
Definition at line 67 of file p_tmt.cpp.
{
    // prepare loader
    initLoader(stub_i386_dos32_tmt, sizeof(stub_i386_dos32_tmt));
    addLoader("IDENTSTR,TMTMAIN1", ph.first_offset_found == 1 ? "TMTMAIN1A" : "", "TMTMAIN1B",
              ft->id ? "TMTCALT1" : "", "TMTMAIN2,UPX1HEAD,TMTCUTPO");
    // fake alignment for the start of the decompressor
    linker->defineSymbol("TMTCUTPO", 0x1000);
    addLoader(getDecompressorSections(), "TMTMAIN5");
    if (ft->id) {
        assert(ft->calls > 0);
        addLoader("TMTCALT2");
        addFilter32(ft->id);
    }
    addLoader("TMTRELOC,RELOC320", big_relocs ? "REL32BIG" : "", "RELOC32J,TMTJUMP1");
}
References Packer::addFilter32(), Packer::addLoader(), big_relocs, Filter::calls, PackHeader::first_offset_found, Packer::getDecompressorSections(), Filter::id, Packer::initLoader(), PackerBase::ph, and stub_i386_dos32_tmt.
canPack()
tribool PackTmt::canPack () override virtual
Implements PackerBase.
Definition at line 153 of file p_tmt.cpp.
{
    if (!readFileHeader())
        return false;
    return true;
}
References readFileHeader().
canUnpack()
tribool PackTmt::canUnpack () override virtual
Implements PackerBase.
Definition at line 268 of file p_tmt.cpp.
{
    if (!readFileHeader())
        return false;
    fi->seek(adam_offset, SEEK_SET);
    return readPackHeader(512) ? 1 : -1;
}
References adam_offset, PackerBase::fi, readFileHeader(), Packer::readPackHeader(), InputFile::seek(), and SEEK_SET.
findOverlapOverhead()
unsigned PackTmt::findOverlapOverhead (const byte * buf, const byte * tbuf, unsigned range = 0, unsigned upper_limit = ~0u) const override protected virtual
Find overhead for in-place decompression in a heuristic way (using a binary search).
Return 0 on error.
To speed up things:
you can pass the range of an acceptable interval (so that we can succeed early)
you can enforce an upper_limit (so that we can fail early)
Reimplemented from Packer.
Definition at line 59 of file p_tmt.cpp.
{
    // make sure the decompressor will be paragraph aligned
    unsigned o = super::findOverlapOverhead(buf, tbuf, range, upper_limit);
    o = ((o + 0x20) & ~0xf) - (ph.u_len & 0xf);
    return o;
}
References buf, Packer::findOverlapOverhead(), PackerBase::ph, and PackHeader::u_len.
getCompressionMethods()
const int * PackTmt::getCompressionMethods (int method, int level) const override virtual
Implements PackerBase.
Definition at line 49 of file p_tmt.cpp.
{
    return Packer::getDefaultCompressionMethods_le32(method, level);
}
References Packer::getDefaultCompressionMethods_le32().
getFilters()
const int * PackTmt::getFilters () const override virtual
Implements PackerBase.
Definition at line 53 of file p_tmt.cpp.
{
    static const int filters[] = {0x26, 0x24,           0x49, 0x46, 0x16, 0x13,  0x14,
                                  0x11, FT_ULTRA_BRUTE, 0x25, 0x15, 0x12, FT_END};
    return filters;
}
References FT_END, and FT_ULTRA_BRUTE.
getFormat()
virtual int PackTmt::getFormat () const inline override virtual
Implements PackerBase.
Definition at line 40 of file p_tmt.h.
{ return UPX_F_TMT_ADAM; }
References UPX_F_TMT_ADAM.
getFullName()
virtual const char * PackTmt::getFullName (const Options *) const inline override virtual
Implements PackerBase.
Definition at line 42 of file p_tmt.h.
{
        return "i386-dos32.tmt.adam";
    }
getName()
virtual const char * PackTmt::getName () const inline override virtual
Implements PackerBase.
Definition at line 41 of file p_tmt.h.
{ return "tmt/adam"; }
Referenced by readFileHeader().
getVersion()
virtual int PackTmt::getVersion () const inline override virtual
Implements PackerBase.
Definition at line 39 of file p_tmt.h.
{ return 13; }
newLinker()
Linker * PackTmt::newLinker () const override protected virtual
Implements Packer.
Definition at line 47 of file p_tmt.cpp.
{ return new ElfLinkerX86; }
pack()
void PackTmt::pack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 163 of file p_tmt.cpp.
{
    big_relocs = 0;
    Packer::handleStub(fi, fo, adam_offset);
    const unsigned usize = ih.imagesize;
    const unsigned rsize = ih.relocsize;
    const unsigned relocnum = rsize / 4;
    ibuf.alloc(usize + rsize + 128);
    obuf.allocForCompression(usize + rsize + 128);
    fi->seek(adam_offset + sizeof(ih), SEEK_SET);
    fi->readx(ibuf, usize);
    if (find_le32(ibuf, UPX_MIN(128u, usize), get_le32("UPX ")) >= 0)
        throwAlreadyPacked();
    if (rsize == 0)
        throwCantPack("file is already compressed with another packer");
    MemBuffer mb_relocs(rsize);
    SPAN_S_VAR(byte, relocs, mb_relocs);
    fi->readx(relocs, rsize);
    const unsigned overlay = file_size - fi->tell();
    checkOverlay(overlay);
    for (unsigned ic = 0; ic < relocnum; ic++)
        set_le32(relocs + 4 * ic, get_le32(relocs + 4 * ic) - 4);
    MemBuffer mb_orelocs(4 * relocnum + 8192); // relocations + extra_info
    SPAN_S_VAR(byte, orelocs, mb_orelocs);
    unsigned orelocsize =
        optimizeReloc(relocnum, relocs, orelocs, ibuf, usize, 32, true, &big_relocs);
    mb_relocs.dealloc(); // done
#if 1
    // write duplicate end marker; why is this here - historical oversight ???
    orelocs[orelocsize++] = 0;
#endif
    // extra_info
    set_le32(orelocs + orelocsize, ih.entry); // save original entry point
    orelocsize += 4;
    set_le32(orelocs + orelocsize, orelocsize + 4); // save orelocsize
    orelocsize += 4;
    memcpy(raw_index_bytes(ibuf, usize, orelocsize), orelocs, orelocsize);
    mb_orelocs.dealloc(); // done
    // prepare packheader
    ph.u_len = usize + orelocsize;
    // prepare filter
    Filter ft(ph.level);
    ft.buf_len = usize;
    // compress
    upx_compress_config_t cconf;
    cconf.reset();
    // limit stack size needed for runtime decompression
    cconf.conf_lzma.max_num_probs = 1846 + (768 << 4); // ushort: ~28 KiB stack
    compressWithFilters(&ft, 512, &cconf);
    const unsigned lsize = getLoaderSize();
    const unsigned s_point = getLoaderSection("TMTMAIN1");
    int e_len = getLoaderSectionStart("TMTCUTPO");
    const unsigned d_len = lsize - e_len;
    assert(e_len > 0 && s_point > 0);
    // patch loader
    linker->defineSymbol("original_entry", ih.entry);
    defineDecompressorSymbols();
    defineFilterSymbols(&ft);
    linker->defineSymbol("bytes_to_copy", ph.c_len + d_len);
    linker->defineSymbol("copy_dest", 0u - (ph.u_len + ph.overlap_overhead + d_len - 1));
    linker->defineSymbol("copy_source", ph.c_len + lsize - 1);
    linker->defineSymbol("TMTCUTPO", ph.u_len + ph.overlap_overhead);
    relocateLoader();
    MemBuffer loader(lsize);
    memcpy(loader, getLoader(), lsize);
    patchPackHeader(loader, e_len);
    memcpy(&oh, &ih, sizeof(oh));
    oh.imagesize = ph.c_len + lsize; // new size
    oh.entry = s_point;              // new entry point
    oh.relocsize = 4;
    // write loader + compressed file
    fo->write(&oh, sizeof(oh));
    fo->write(loader, e_len);
    fo->write(obuf, ph.c_len);
    fo->write(loader + lsize - d_len, d_len); // decompressor
    byte rel_entry[4];
    set_le32(rel_entry, 5 + s_point);
    fo->write(rel_entry, sizeof(rel_entry));
    // verify
    verifyOverlappingDecompression();
    // copy the overlay
    copyOverlay(fo, overlay, obuf);
    // finally check the compression ratio
    if (!checkFinalCompressionRatio(fo))
        throwNotCompressible();
}
References adam_offset, MemBuffer::alloc(), MemBuffer::allocForCompression(), big_relocs, Filter::buf_len, PackHeader::c_len, Packer::checkFinalCompressionRatio(), Packer::checkOverlay(), Packer::compressWithFilters(), upx_compress_config_t::conf_lzma, Packer::copyOverlay(), MemBuffer::dealloc(), Packer::defineDecompressorSymbols(), Packer::defineFilterSymbols(), PackTmt::tmt_header_t::entry, PackerBase::fi, PackerBase::file_size, find_le32(), get_le32(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), Packer::handleStub(), Packer::ibuf, ih, PackTmt::tmt_header_t::imagesize, PackHeader::level, lzma_compress_config_t::max_num_probs, memcpy(), Packer::obuf, oh, Packer::optimizeReloc(), PackHeader::overlap_overhead, Packer::patchPackHeader(), PackerBase::ph, raw_index_bytes(), InputFile::readx(), Packer::relocateLoader(), PackTmt::tmt_header_t::relocsize, upx_compress_config_t::reset(), InputFile::seek(), SEEK_SET, set_le32(), SPAN_S_VAR, FileBase::tell(), throwAlreadyPacked(), throwCantPack(), throwNotCompressible(), PackHeader::u_len, UPX_MIN, Packer::verifyOverlappingDecompression(), and OutputFile::write().
readFileHeader()
int PackTmt::readFileHeader () protected
Definition at line 89 of file p_tmt.cpp.
{
#define H(x)  get_le16(h + 2 * (x))
#define H4(x) get_le32(h + (x))
    byte h[0x40];
    int ic;
    unsigned exe_offset = 0;
    adam_offset = 0;
    for (ic = 0; ic < 20; ic++) {
        fi->seek(adam_offset, SEEK_SET);
        fi->readx(h, sizeof(h));
        if (memcmp(h, "MZ", 2) == 0) // dos/exe
        {
            exe_offset = adam_offset;
            adam_offset += H(2) * 512 + H(1);
            if (H(1))
                adam_offset -= 512;
            if (H(0x18 / 2) == 0x40 && H4(0x3c))
                adam_offset = H4(0x3c);
        } else if (memcmp(h, "BW", 2) == 0) {
            adam_offset += H(2) * 512 + H(1);
        } else if (memcmp(h, "PMW1", 4) == 0) {
            fi->seek(adam_offset + H4(0x18), SEEK_SET);
            adam_offset += H4(0x24);
            unsigned objs = H4(0x1c);
            while (objs--) {
                fi->readx(h, 0x18);
                adam_offset += H4(4);
            }
        } else if (memcmp(h, "LE", 2) == 0) {
            // + (memory_pages-1)*memory_page_size+bytes_on_last_page
            unsigned offs = exe_offset + (H4(0x14) - 1) * H4(0x28) + H4(0x2c);
            fi->seek(adam_offset + 0x80, SEEK_SET);
            fi->readx(h, 4);
            // + data_pages_offset
            adam_offset = offs + H4(0);
        } else if (memcmp(h, "Adam", 4) == 0) {
            break;
        } else
            return 0;
    }
    if (ic == 20)
        return 0;
    fi->seek(adam_offset, SEEK_SET);
    fi->readx(&ih, sizeof(ih));
    // TODO: could add more checks for the values in 'ih'
    const unsigned imagesize = ih.imagesize;
    const unsigned entry = ih.entry;
    const unsigned rsize = ih.relocsize;
    if (imagesize < sizeof(ih) || imagesize >= file_size_u || entry >= file_size_u ||
        rsize >= file_size_u) {
        throwCantPack("%s: bad header: imagesize=%#x entry=%#x relocsize=%#x", getName(), imagesize,
                      entry, rsize);
        return 0;
    }
    return UPX_F_TMT_ADAM;
#undef H4
#undef H
}
References adam_offset, PackTmt::tmt_header_t::entry, PackerBase::fi, PackerBase::file_size_u, getName(), H, H4, ih, PackTmt::tmt_header_t::imagesize, memcmp(), InputFile::readx(), PackTmt::tmt_header_t::relocsize, InputFile::seek(), SEEK_SET, throwCantPack(), and UPX_F_TMT_ADAM.
Referenced by canPack(), and canUnpack().
unpack()
void PackTmt::unpack (OutputFile * fo) override virtual
Implements Packer.
Definition at line 275 of file p_tmt.cpp.
{
    Packer::handleStub(fi, fo, adam_offset);
    ibuf.alloc(ph.c_len);
    obuf.allocForDecompression(ph.u_len);
    fi->seek(adam_offset + ph.buf_offset + ph.getPackHeaderSize(), SEEK_SET);
    fi->readx(ibuf, ph.c_len);
    // decompress
    decompress(ibuf, obuf);
    // read extra_info
    const unsigned orig_entry = mem_size(1, get_le32(obuf + ph.u_len - 8));
    const unsigned orelocsize = mem_size(1, get_le32(obuf + ph.u_len - 4));
    const unsigned osize = mem_size(1, ph.u_len - orelocsize);
    // unfilter
    if (ph.filter) {
        Filter ft(ph.level);
        ft.init(ph.filter, 0);
        ft.cto = (byte) ph.filter_cto;
        if (ph.version < 11)
            ft.cto = (byte) (get_le32(obuf + ph.u_len - 12) >> 24);
        ft.unfilter(obuf, osize);
    }
    // decode relocations
    SPAN_S_VAR(const byte, orelocs, raw_index_bytes(obuf, osize, orelocsize), orelocsize);
    SPAN_S_VAR(byte, reloc_image, raw_index_bytes(obuf, 0, osize), osize);
    MemBuffer mb_relocs;
    const unsigned relocnum = unoptimizeReloc(orelocs, mb_relocs, reloc_image, osize, 32, true);
    SPAN_S_VAR(byte, relocs, mb_relocs);
    for (unsigned ic = 0; ic < relocnum; ic++)
        set_le32(relocs + 4 * ic, get_le32(relocs + 4 * ic) + 4);
    memcpy(&oh, &ih, sizeof(oh));
    oh.imagesize = osize;
    oh.entry = orig_entry;
    oh.relocsize = relocnum * 4;
    const unsigned overlay = file_size - adam_offset - ih.imagesize - ih.relocsize - sizeof(ih);
    checkOverlay(overlay);
    // write decompressed file
    if (fo) {
        fo->write(&oh, sizeof(oh));
        fo->write(obuf, osize);
        fo->write(relocs, relocnum * 4);
    }
    // copy the overlay
    copyOverlay(fo, overlay, obuf);
}
References adam_offset, MemBuffer::alloc(), MemBuffer::allocForDecompression(), PackHeader::buf_offset, PackHeader::c_len, Packer::checkOverlay(), Packer::copyOverlay(), Filter::cto, Packer::decompress(), PackTmt::tmt_header_t::entry, PackerBase::fi, PackerBase::file_size, PackHeader::filter, PackHeader::filter_cto, get_le32(), PackHeader::getPackHeaderSize(), Packer::handleStub(), Packer::ibuf, ih, PackTmt::tmt_header_t::imagesize, Filter::init(), PackHeader::level, mem_size(), memcpy(), Packer::obuf, oh, PackerBase::ph, raw_index_bytes(), InputFile::readx(), PackTmt::tmt_header_t::relocsize, InputFile::seek(), SEEK_SET, set_le32(), SPAN_S_VAR, PackHeader::u_len, Filter::unfilter(), Packer::unoptimizeReloc(), PackHeader::version, and OutputFile::write().
Member Data Documentation
adam_offset
unsigned PackTmt::adam_offset = 0 protected
Definition at line 62 of file p_tmt.h.
Referenced by canUnpack(), pack(), readFileHeader(), and unpack().
big_relocs
int PackTmt::big_relocs = 0 protected
Definition at line 63 of file p_tmt.h.
Referenced by buildLoader(), and pack().
ih
tmt_header_t PackTmt::ih = {} protected
Definition at line 73 of file p_tmt.h.
Referenced by pack(), readFileHeader(), and unpack().
oh
tmt_header_t PackTmt::oh = {} protected
Definition at line 73 of file p_tmt.h.
Referenced by pack(), and unpack().
The documentation for this class was generated from the following files:
src/p_tmt.h
src/p_tmt.cpp