My Project: ElfLinker Class Reference
ElfLinker Class Reference
ElfLinker.
#include <linker.h>
Classes
struct Relocation
struct Section
struct Symbol
Public Member Functions
ElfLinker (const N_BELE_RTP::AbstractPolicy *b=&N_BELE_RTP::le_policy) noexcept
ElfLinker.
virtual ~ElfLinker () noexcept
void init (const void *pdata, int plen, unsigned pxtra=0)
int addLoader (const char *sname)
void addLoader (const char *s, va_list ap)
void addLoaderVA (const char *s,...)
Section * addSection (const char *sname, const void *sdata, int slen, unsigned p2align)
int getSection (const char *sname, int *slen=nullptr) const
int getSectionSize (const char *sname) const
byte * getLoader (int *llen=nullptr) const
void defineSymbol (const char *name, upx_uint64_t value)
Symbol * findSymbol (const char *name, bool fatal=true) const
upx_uint64_t getSymbolOffset (const char *) const
void dumpSymbol (const Symbol *, unsigned flags, FILE *fp) const
void dumpSymbols (unsigned flags=0, FILE *fp=nullptr) const
void alignWithByte (unsigned len, byte b)
virtual void alignCode (unsigned len)
virtual void alignData (unsigned len)
void defineSymbol (const char *name, int value)
void defineSymbol (const char *name, unsigned value)
void defineSymbol (const char *name, unsigned long value)
Public Attributes
const N_BELE_RTP::AbstractPolicy *const bele
Protected Member Functions
void preprocessSections (char *start, char const *end)
void preprocessSymbols (char *start, char const *end)
void preprocessRelocations (char *start, char const *end)
Section * findSection (const char *name, bool fatal=true) const
Symbol * addSymbol (const char *name, const char *section, upx_uint64_t offset)
Relocation * addRelocation (const char *section, unsigned off, const char *type, const char *symbol, upx_uint64_t add)
void relocate ()
virtual void relocate1 (const Relocation *, byte *location, upx_uint64_t value, const char *type)
Protected Attributes
byte * input = nullptr
int inputlen = 0
byte * output = nullptr
int outputlen = 0
unsigned output_capacity = 0
Section * head = nullptr
Section * tail = nullptr
Section ** sections = nullptr
Symbol ** symbols = nullptr
Relocation ** relocations = nullptr
unsigned nsections = 0
unsigned nsections_capacity = 0
unsigned nsymbols = 0
unsigned nsymbols_capacity = 0
unsigned nrelocations = 0
unsigned nrelocations_capacity = 0
bool reloc_done = false
Friends
class Packer
Additional Inherited Members
Private Member Functions inherited from upx::noncopyable
forceinline constexpr noncopyable () noexcept
forceinline ~noncopyable () noexcept=default
Detailed Description
ElfLinker.
Definition at line 34 of file linker.h.
Constructor & Destructor Documentation
ElfLinker()
ElfLinker::ElfLinker (const N_BELE_RTP::AbstractPolicy * b = &N_BELE_RTP::le_policy) explicit noexcept
ElfLinker.
Definition at line 110 of file linker.cpp.
: bele(b) {}
~ElfLinker()
ElfLinker::~ElfLinker () virtual noexcept
Definition at line 112 of file linker.cpp.
{
    delete[] input;
    delete[] output;
    free_array(sections, nsections);
    free_array(symbols, nsymbols);
    free_array(relocations, nrelocations);
}
References free_array(), input, nrelocations, nsections, nsymbols, output, relocations, sections, and symbols.
Member Function Documentation
addLoader() [1/2]
void ElfLinker::addLoader (const char * s, va_list ap)
Definition at line 425 of file linker.cpp.
{
    while (s != nullptr) {
        addLoader(s);
        s = va_arg(ap, const char *);
    }
}
References addLoader().
addLoader() [2/2]
int ElfLinker::addLoader (const char * sname)
Definition at line 364 of file linker.cpp.
{
    assert(sname != nullptr);
    if (!sname[0])
        return outputlen;
    char *begin = strdup(sname);
    char *end = begin + strlen(begin);
    for (char *sect = begin; sect < end;) {
        for (char *tokend = sect; *tokend; tokend++)
            if (*tokend == ' ' || *tokend == ',') {
                *tokend = 0;
                break;
            }
        if (sect[0] == '+') // alignment
        {
            assert(tail);
            unsigned l = hex(sect[2]) - tail->offset - tail->size;
            unsigned m = hex(sect[1]);
            if (m) {
                l %= hex(sect[1]);
            }
            if (l) {
                if (sect[3] == 'D')
                    alignData(l);
                else
                    alignCode(l);
                tail->size += l;
            }
        } else {
            Section *section = findSection(sect);
            if (section->p2align) {
                assert(tail);
                assert(tail != section);
                // .p2align must be < 32
                const unsigned v = ~0u << section->p2align;
                if (const unsigned l = ~v & (0u - (unsigned) (tail->offset + tail->size))) {
                    alignCode(l);
                    tail->size += l;
                }
            }
            // Section->output is not relocatable, and C++ has no realloc() anyway.
            assert((section->size + outputlen) <= output_capacity);
            memcpy(output + outputlen, section->input, section->size);
            section->output = output + outputlen; // FIXME: INVALIDATED by realloc()
            NO_printf("section added: 0x%04x %3d %s\n", outputlen, section->size, section->name);
            outputlen += section->size;
            if (head) {
                tail->next = section;
                section->offset = tail->offset + tail->size;
            } else
                head = section;
            tail = section;
        }
        sect += strlen(sect) + 1;
    }
    ::free(begin);
    return outputlen;
}
References alignCode(), alignData(), findSection(), head, hex(), ElfLinker::Section::input, memcpy(), ElfLinker::Section::name, ElfLinker::Section::next, NO_printf(), ElfLinker::Section::offset, output, ElfLinker::Section::output, output_capacity, outputlen, ElfLinker::Section::p2align, ElfLinker::Section::size, strlen, and tail.
Referenced by addLoader(), addLoaderVA(), PeFile::ImportLinker::build(), and init().
addLoaderVA()
void ElfLinker::addLoaderVA (const char * s, ...)
Definition at line 432 of file linker.cpp.
{
    va_list ap;
    va_start(ap, s);
    addLoader(s, ap);
    va_end(ap);
}
References addLoader().
addRelocation()
ElfLinker::Relocation * ElfLinker::addRelocation (const char * section, unsigned off, const char * type, const char * symbol, upx_uint64_t add) protected
Definition at line 348 of file linker.cpp.
{
    if (grow_capacity(nrelocations, &nrelocations_capacity))
        relocations = realloc_array(relocations, nrelocations_capacity);
    Relocation *rel = new Relocation(findSection(section), off, type, findSymbol(symbol), add);
    relocations[nrelocations++] = rel;
    return rel;
}
References findSection(), findSymbol(), grow_capacity(), nrelocations, nrelocations_capacity, realloc_array(), and relocations.
Referenced by PeFile::ImportLinker::add_import(), and preprocessRelocations().
addSection()
ElfLinker::Section * ElfLinker::addSection (const char * sname, const void * sdata, int slen, unsigned p2align)
Definition at line 319 of file linker.cpp.
{
    NO_printf("addSection: %s len=%d align=%d\n", sname, slen, p2align);
    if (!sdata && (!strcmp("ABS*", sname) || !strcmp("UND*", sname)))
        return nullptr;
    assert(sname && sname[0]);
    assert(sname[strlen(sname) - 1] != ':');
    assert(findSection(sname, false) == nullptr);
    if (grow_capacity(nsections, &nsections_capacity))
        sections = realloc_array(sections, nsections_capacity);
    Section *sec = new Section(sname, sdata, slen, p2align);
    sec->sort_id = nsections;
    sections[nsections++] = sec;
    return sec;
}
References findSection(), grow_capacity(), NO_printf(), nsections, nsections_capacity, realloc_array(), sections, ElfLinker::Section::sort_id, strcmp(), and strlen.
Referenced by PeFile::ImportLinker::add_import(), PeFile::ImportLinker::ImportLinker(), and preprocessSections().
addSymbol()
ElfLinker::Symbol * ElfLinker::addSymbol (const char * name, const char * section, upx_uint64_t offset) protected
Definition at line 335 of file linker.cpp.
{
    NO_printf("addSymbol: %s %s 0x%llx\n", name, section, offset);
    assert(name && name[0]);
    assert(name[strlen(name) - 1] != ':');
    assert(findSymbol(name, false) == nullptr);
    if (grow_capacity(nsymbols, &nsymbols_capacity))
        symbols = realloc_array(symbols, nsymbols_capacity);
    Symbol *sym = new Symbol(name, findSection(section), offset);
    symbols[nsymbols++] = sym;
    return sym;
}
References findSection(), findSymbol(), grow_capacity(), NO_printf(), nsymbols, nsymbols_capacity, realloc_array(), strlen, and symbols.
Referenced by PeFile::ImportLinker::add_import(), PeFile::ImportLinker::ImportLinker(), and preprocessSymbols().
alignCode()
virtual void ElfLinker::alignCode (unsigned len) inline virtual
Reimplemented in ElfLinkerAMD64, ElfLinkerM68k, ElfLinkerX86, and PeFile::ImportLinker.
Definition at line 101 of file linker.h.
{ alignWithByte(len, 0); }
References alignWithByte().
Referenced by addLoader().
alignData()
virtual void ElfLinker::alignData (unsigned len) inline virtual
Definition at line 102 of file linker.h.
{ alignWithByte(len, 0); }
References alignWithByte().
Referenced by addLoader().
alignWithByte()
void ElfLinker::alignWithByte (unsigned len, byte b)
Definition at line 543 of file linker.cpp.
{
    memset(output + outputlen, b, len);
    outputlen += len;
}
References b, memset(), output, and outputlen.
Referenced by alignCode(), PeFile::ImportLinker::alignCode(), and alignData().
defineSymbol() [1/4]
void ElfLinker::defineSymbol (const char * name, int value) inline
Definition at line 105 of file linker.h.
{ defineSymbol(name, upx_uint64_t(value)); }
References defineSymbol().
Referenced by defineSymbol().
defineSymbol() [2/4]
void ElfLinker::defineSymbol (const char * name, unsigned long value) inline
Definition at line 107 of file linker.h.
{
        defineSymbol(name, upx_uint64_t(value));
    }
References defineSymbol().
defineSymbol() [3/4]
void ElfLinker::defineSymbol (const char * name, unsigned value) inline
Definition at line 106 of file linker.h.
{ defineSymbol(name, upx_uint64_t(value)); }
References defineSymbol().
Referenced by defineSymbol().
defineSymbol() [4/4]
void ElfLinker::defineSymbol (const char * name, upx_uint64_t value)
Definition at line 488 of file linker.cpp.
{
    Symbol *symbol = findSymbol(name);
    if (strcmp(symbol->section->name, "*ABS*") == 0)
        throwInternalError("defineSymbol: symbol '%s' is *ABS*\n", name);
    else if (strcmp(symbol->section->name, "*UND*") == 0) // for undefined symbols
        symbol->offset = value;
    else if (strcmp(symbol->section->name, name) == 0) // for sections
    {
        for (Section *section = symbol->section; section; section = section->next) {
            assert(section->offset < value);
            section->offset = value;
            value += section->size;
        }
    } else
        throwInternalError("defineSymbol: symbol '%s' already defined\n", name);
}
References findSymbol(), ElfLinker::Section::name, ElfLinker::Section::next, ElfLinker::Symbol::offset, ElfLinker::Symbol::section, strcmp(), and throwInternalError().
Referenced by defineSymbol(), and PeFile::ImportLinker::relocate_import().
dumpSymbol()
void ElfLinker::dumpSymbol (const Symbol * symbol, unsigned flags, FILE * fp) const
Definition at line 506 of file linker.cpp.
{
    if ((flags & 1) && symbol->section->output == nullptr)
        return;
    char d0[16 + 1], d1[16 + 1];
    upx_safe_snprintf(d0, sizeof(d0), "%016llx", (upx_uint64_t) symbol->offset);
    upx_safe_snprintf(d1, sizeof(d1), "%016llx", (upx_uint64_t) symbol->section->offset);
    fprintf(fp, "%-28s 0x%-16s | %-28s 0x%-16s\n", symbol->name, d0, symbol->section->name, d1);
}
References ElfLinker::Section::name, ElfLinker::Symbol::name, ElfLinker::Section::offset, ElfLinker::Symbol::offset, ElfLinker::Section::output, ElfLinker::Symbol::section, and upx_safe_snprintf().
Referenced by dumpSymbols().
dumpSymbols()
void ElfLinker::dumpSymbols (unsigned flags = 0, FILE * fp = nullptr) const
Definition at line 514 of file linker.cpp.
{
    if (fp == nullptr)
        fp = stdout;
    if ((flags & 2) == 0) {
        // default: dump symbols in used section order
        for (const Section *section = head; section; section = section->next) {
            char d1[16 + 1];
            upx_safe_snprintf(d1, sizeof(d1), "%016llx", (upx_uint64_t) section->offset);
            fprintf(fp, "%-42s%-28s 0x%-16s\n", "", section->name, d1);
            for (unsigned ic = 0; ic < nsymbols; ic++) {
                const Symbol *symbol = symbols[ic];
                if (symbol->section == section && strcmp(symbol->name, section->name) != 0)
                    dumpSymbol(symbol, flags, fp);
            }
        }
    } else {
        // dump all symbols
        for (unsigned ic = 0; ic < nsymbols; ic++)
            dumpSymbol(symbols[ic], flags, fp);
    }
}
References dumpSymbol(), head, ElfLinker::Symbol::name, ElfLinker::Section::next, nsymbols, ElfLinker::Symbol::section, strcmp(), symbols, and upx_safe_snprintf().
findSection()
ElfLinker::Section * ElfLinker::findSection (const char * name, bool fatal = true) const protected
Definition at line 301 of file linker.cpp.
{
    for (unsigned ic = 0; ic < nsections; ic++)
        if (strcmp(sections[ic]->name, name) == 0)
            return sections[ic];
    if (fatal)
        throwInternalError("unknown section %s\n", name);
    return nullptr;
}
References nsections, sections, strcmp(), and throwInternalError().
Referenced by PeFile::ImportLinker::add_import(), addLoader(), addRelocation(), addSection(), addSymbol(), PeFile::ImportLinker::getAddress(), getSection(), getSectionSize(), PeFile::ImportLinker::getThunk(), PeFile::ImportLinker::hasDll(), and preprocessRelocations().
findSymbol()
ElfLinker::Symbol * ElfLinker::findSymbol (const char * name, bool fatal = true) const
Definition at line 310 of file linker.cpp.
{
    for (unsigned ic = 0; ic < nsymbols; ic++)
        if (strcmp(symbols[ic]->name, name) == 0)
            return symbols[ic];
    if (fatal)
        throwInternalError("unknown symbol %s\n", name);
    return nullptr;
}
References nsymbols, strcmp(), symbols, and throwInternalError().
Referenced by addRelocation(), addSymbol(), defineSymbol(), and getSymbolOffset().
getLoader()
byte * ElfLinker::getLoader (int * llen = nullptr) const
Definition at line 451 of file linker.cpp.
{
    if (llen)
        *llen = outputlen;
    return output;
}
References output, and outputlen.
Referenced by PeFile::processImports2().
getSection()
int ElfLinker::getSection (const char * sname, int * slen = nullptr) const
Definition at line 439 of file linker.cpp.
{
    const Section *section = findSection(sname);
    if (slen)
        *slen = section->size;
    return (int) (section->output - output);
}
References findSection(), output, ElfLinker::Section::output, and ElfLinker::Section::size.
getSectionSize()
int ElfLinker::getSectionSize (const char * sname) const
Definition at line 446 of file linker.cpp.
{
    const Section *section = findSection(sname);
    return section->size;
}
References findSection(), and ElfLinker::Section::size.
getSymbolOffset()
upx_uint64_t ElfLinker::getSymbolOffset (const char * name) const
Definition at line 536 of file linker.cpp.
{
    const Symbol *symbol = findSymbol(name);
    if (symbol->section->output == nullptr)
        return 0xdeaddead;
    return symbol->section->offset + symbol->offset;
}
References findSymbol(), ElfLinker::Section::offset, ElfLinker::Symbol::offset, ElfLinker::Section::output, and ElfLinker::Symbol::section.
init()
void ElfLinker::init (const void * pdata, int plen, unsigned pxtra = 0)
Definition at line 120 of file linker.cpp.
{
    const byte *pdata = (const byte *) pdata_v;
    if (plen >= 16 && memcmp(pdata, "UPX#", 4) == 0) {
        // decompress pre-compressed stub-loader
        int method;
        unsigned u_len, c_len;
        if (pdata[4]) {
            method = pdata[4];
            u_len = get_le16(pdata + 5);
            c_len = get_le16(pdata + 7);
            pdata += 9;
            assert(9 + c_len == (unsigned) plen);
        } else {
            method = pdata[5];
            u_len = get_le32(pdata + 6);
            c_len = get_le32(pdata + 10);
            pdata += 14;
            assert(14 + c_len == (unsigned) plen);
        }
        assert((unsigned) plen < u_len);
        inputlen = u_len;
        input = New(byte, inputlen + 1);
        unsigned new_len = u_len;
        int r = upx_decompress(pdata, c_len, input, &new_len, method, nullptr);
        if (r == UPX_E_OUT_OF_MEMORY)
            throwOutOfMemoryException();
        if (r != UPX_E_OK || new_len != u_len)
            throwBadLoader();
    } else {
        inputlen = plen;
        input = New(byte, inputlen + 1);
        if (inputlen)
            memcpy(input, pdata, inputlen);
    }
    input[inputlen] = 0; // NUL terminate
    output_capacity = (inputlen ? (inputlen + pxtra) : 0x4000);
    assert(output_capacity < (1 << 16)); // LE16 l_info.l_size
    output = New(byte, output_capacity);
    outputlen = 0;
    NO_printf("\nElfLinker::init %d @%p\n", output_capacity, output);
    // FIXME: bad compare when either symbols or relocs are absent
    if ((int) strlen("Sections:\n"
                     "SYMBOL TABLE:\n"
                     "RELOCATION RECORDS FOR ") < inputlen) {
        char const *const eof = (char const *) &input[inputlen];
        int pos = find(input, inputlen, "Sections:\n", 10);
        assert(pos != -1);
        char *const psections = (char *) input + pos;
        char *const psymbols = strstr(psections, "SYMBOL TABLE:\n");
        // assert(psymbols != nullptr);
        char *const prelocs = strstr((psymbols ? psymbols : psections), "RELOCATION RECORDS FOR ");
        // assert(prelocs != nullptr);
        preprocessSections(psections, (psymbols ? psymbols : (prelocs ? prelocs : eof)));
        if (psymbols)
            preprocessSymbols(psymbols, (prelocs ? prelocs : eof));
        if (prelocs)
            preprocessRelocations(prelocs, eof);
        addLoader("*UND*");
    }
}
References addLoader(), find(), get_le16(), get_le32(), input, inputlen, memcmp(), memcpy(), New, NO_printf(), output, output_capacity, outputlen, preprocessRelocations(), preprocessSections(), preprocessSymbols(), strlen, throwBadLoader(), throwOutOfMemoryException(), upx_decompress(), UPX_E_OK, and UPX_E_OUT_OF_MEMORY.
preprocessRelocations()
void ElfLinker::preprocessRelocations (char * start, char const * end) protected
Definition at line 245 of file linker.cpp.
{
    assert_noexcept(nrelocations == 0);
    Section *section = nullptr;
    char *nextl;
    for (; start < end; start = 1 + nextl) {
        nextl = strchr(start, '\n');
        assert(nextl != nullptr);
        *nextl = '\0'; // a record is a line
        {
            char sect[1024];
            if (sscanf(start, "RELOCATION RECORDS FOR [%[^]]", sect) == 1)
                section = findSection(sect);
        }
        unsigned offset;
        char type[100];
        char symbol[1024];
        if (sscanf(start, "%x %99s %1023s", &offset, type, symbol) == 3) {
            char *t = strstr(start, type);
            t[strlen(type)] = 0;
            upx_uint64_t add = 0;
            char *p = strstr(symbol, "+0x");
            if (p == nullptr)
                p = strstr(symbol, "-0x");
            if (p) {
                char sign = *p;
                *p = 0; // terminate the symbol name
                p += 3;
                assert(strlen(p) == 8 || strlen(p) == 16);
#if (ACC_CC_MSC && (_MSC_VER < 1800))
                unsigned a = 0, b = 0;
                if (sscanf(p, "%08x%08x", &a, &b) == 2)
                    add = ((upx_uint64_t) a << 32) | b;
                else
                    add = a;
#else
                char *endptr = nullptr;
                add = strtoull(p, &endptr, 16);
                assert(endptr && *endptr == '\0');
#endif
                if (sign == '-')
                    add = 0 - add;
            }
            if (section) {
                addRelocation(section->name, offset, t, symbol, add);
                NO_printf("relocation %s %s %x %llu preprocessed\n", section->name, symbol, offset,
                          (unsigned long long) add);
            }
        }
    }
}
References addRelocation(), assert_noexcept, b, findSection(), ElfLinker::Section::name, NO_printf(), nrelocations, and strlen.
Referenced by init().
preprocessSections()
void ElfLinker::preprocessSections (char * start, char const * end) protected
Definition at line 186 of file linker.cpp.
{
    assert_noexcept(nsections == 0);
    char *nextl;
    for (; start < end; start = 1 + nextl) {
        nextl = strchr(start, '\n');
        assert(nextl != nullptr);
        *nextl = '\0'; // a record is a line
        unsigned offset, size, align;
        char name[1024];
        if (sscanf(start, "%*d %1023s %x %*x %*x %x 2**%d", name, &size, &offset, &align) == 4) {
            char *n = strstr(start, name);
            n[strlen(name)] = 0;
            addSection(n, input + offset, size, align);
            NO_printf("section %s preprocessed\n", n);
        }
    }
    addSection("*ABS*", nullptr, 0, 0);
    addSection("*UND*", nullptr, 0, 0);
}
References addSection(), assert_noexcept, input, n, NO_printf(), nsections, size(), and strlen.
Referenced by init().
preprocessSymbols()
void ElfLinker::preprocessSymbols (char * start, char const * end) protected
Definition at line 208 of file linker.cpp.
{
    assert_noexcept(nsymbols == 0);
    char *nextl;
    for (; start < end; start = 1 + nextl) {
        nextl = strchr(start, '\n');
        assert(nextl != nullptr);
        *nextl = '\0'; // a record is a line
        unsigned value, offset;
        char section[1024];
        char symbol[1024];
        if (sscanf(start, "%x g *ABS* %x %1023s", &value, &offset, symbol) == 3) {
            char *s = strstr(start, symbol);
            s[strlen(symbol)] = 0;
            addSymbol(s, "*ABS*", value);
            assert(offset == 0);
        }
#if 0
        else if (sscanf(start, "%x%*8c %1023s %*x %1023s", &offset, section, symbol) == 3)
#else
        // work around broken scanf() implementations
        // https://bugs.winehq.org/show_bug.cgi?id=10401 (fixed in Wine 0.9.58)
        else if (sscanf(start, "%x%*c%*c%*c%*c%*c%*c%*c%*c %1023s %*x %1023s", &offset, section,
                        symbol) == 3)
#endif
        {
            char *s = strstr(start, symbol);
            s[strlen(symbol)] = 0;
            if (strcmp(section, "*UND*") == 0)
                offset = 0xdeaddead;
            assert(strcmp(section, "*ABS*") != 0);
            addSymbol(s, section, offset);
        }
    }
}
References addSymbol(), assert_noexcept, nsymbols, strcmp(), and strlen.
Referenced by init().
relocate()
void ElfLinker::relocate () protected
Definition at line 457 of file linker.cpp.
{
    assert(!reloc_done);
    reloc_done = true;
    for (unsigned ic = 0; ic < nrelocations; ic++) {
        const Relocation *rel = relocations[ic];
        upx_uint64_t value = 0;
        if (rel->section->output == nullptr)
            continue;
        if (strcmp(rel->value->section->name, "*ABS*") == 0) {
            value = rel->value->offset;
        } else if (strcmp(rel->value->section->name, "*UND*") == 0 &&
                   rel->value->offset == 0xdeaddead)
            throwInternalError("undefined symbol '%s' referenced\n", rel->value->name);
        else if (rel->value->section->output == nullptr)
            throwInternalError("can not apply reloc '%s:%x' without section '%s'\n",
                               rel->section->name, rel->offset, rel->value->section->name);
        else {
            value = rel->value->section->offset + rel->value->offset + rel->add;
        }
        byte *location = rel->section->output + rel->offset;
        NO_printf("%-28s %-28s %-10s %#16llx %#16llx\n", rel->section->name, rel->value->name,
                  rel->type, (long long) value,
                  (long long) value - rel->section->offset - rel->offset);
        NO_printf("  %llx %d %llx %d %llx :%d\n", (long long) value,
                  (int) rel->value->section->offset, rel->value->offset, rel->offset,
                  (long long) rel->add, *location);
        relocate1(rel, location, value, rel->type);
    }
}
References ElfLinker::Relocation::add, ElfLinker::Section::name, ElfLinker::Symbol::name, NO_printf(), nrelocations, ElfLinker::Section::offset, ElfLinker::Symbol::offset, ElfLinker::Relocation::offset, ElfLinker::Section::output, reloc_done, relocate1(), relocations, ElfLinker::Symbol::section, ElfLinker::Relocation::section, strcmp(), throwInternalError(), ElfLinker::Relocation::type, and ElfLinker::Relocation::value.
Referenced by PeFile::ImportLinker::relocate_import().
relocate1()
void ElfLinker::relocate1 (const Relocation * rel, byte * location, upx_uint64_t value, const char * type) protected virtual
Reimplemented in ElfLinkerAMD64, ElfLinkerArm64LE, ElfLinkerArmBE, ElfLinkerArmLE, ElfLinkerM68k, ElfLinkerMipsBE, ElfLinkerMipsLE, ElfLinkerPpc32, ElfLinkerPpc64, ElfLinkerPpc64le, and ElfLinkerX86.
Definition at line 548 of file linker.cpp.
{
    throwInternalError("unknown relocation type '%s\n'", rel->type);
}
References throwInternalError(), and ElfLinker::Relocation::type.
Referenced by relocate().
Friends And Related Function Documentation
Packer
friend class Packer friend
Definition at line 35 of file linker.h.
Member Data Documentation
bele
const N_BELE_RTP::AbstractPolicy* const ElfLinker::bele
Definition at line 38 of file linker.h.
Referenced by Packer::assertPacker().
head
Section* ElfLinker::head = nullptr protected
Definition at line 50 of file linker.h.
Referenced by addLoader(), and dumpSymbols().
input
byte* ElfLinker::input = nullptr protected
Definition at line 44 of file linker.h.
Referenced by init(), preprocessSections(), ~ElfLinker(), and ElfLinker::Section::~Section().
inputlen
int ElfLinker::inputlen = 0 protected
Definition at line 45 of file linker.h.
Referenced by init().
nrelocations
unsigned ElfLinker::nrelocations = 0 protected
Definition at line 61 of file linker.h.
Referenced by addRelocation(), preprocessRelocations(), relocate(), and ~ElfLinker().
nrelocations_capacity
unsigned ElfLinker::nrelocations_capacity = 0 protected
Definition at line 62 of file linker.h.
Referenced by addRelocation().
nsections
unsigned ElfLinker::nsections = 0 protected
Definition at line 57 of file linker.h.
Referenced by addSection(), PeFile::ImportLinker::build(), findSection(), preprocessSections(), PeFile::ImportLinker::relocate_import(), and ~ElfLinker().
nsections_capacity
unsigned ElfLinker::nsections_capacity = 0 protected
Definition at line 58 of file linker.h.
Referenced by addSection().
nsymbols
unsigned ElfLinker::nsymbols = 0 protected
Definition at line 59 of file linker.h.
Referenced by addSymbol(), dumpSymbols(), findSymbol(), preprocessSymbols(), and ~ElfLinker().
nsymbols_capacity
unsigned ElfLinker::nsymbols_capacity = 0 protected
Definition at line 60 of file linker.h.
Referenced by addSymbol().
output
byte* ElfLinker::output = nullptr protected
Definition at line 46 of file linker.h.
Referenced by addLoader(), ElfLinkerM68k::alignCode(), alignWithByte(), PeFile::ImportLinker::build(), getLoader(), getSection(), init(), PeFile::ImportLinker::relocate_import(), and ~ElfLinker().
output_capacity
unsigned ElfLinker::output_capacity = 0 protected
Definition at line 48 of file linker.h.
Referenced by addLoader(), PeFile::ImportLinker::build(), and init().
outputlen
int ElfLinker::outputlen = 0 protected
Definition at line 47 of file linker.h.
Referenced by addLoader(), ElfLinkerM68k::alignCode(), alignWithByte(), PeFile::ImportLinker::build(), getLoader(), and init().
reloc_done
bool ElfLinker::reloc_done = false protected
Definition at line 64 of file linker.h.
Referenced by relocate().
relocations
Relocation** ElfLinker::relocations = nullptr protected
Definition at line 55 of file linker.h.
Referenced by addRelocation(), relocate(), and ~ElfLinker().
sections
Section** ElfLinker::sections = nullptr protected
Definition at line 53 of file linker.h.
Referenced by addSection(), PeFile::ImportLinker::build(), findSection(), and ~ElfLinker().
symbols
Symbol** ElfLinker::symbols = nullptr protected
Definition at line 54 of file linker.h.
Referenced by addSymbol(), dumpSymbols(), findSymbol(), and ~ElfLinker().
tail
Section* ElfLinker::tail = nullptr protected
Definition at line 51 of file linker.h.
Referenced by addLoader().
The documentation for this class was generated from the following files:
src/linker.h
src/linker.cpp