My Project: src/compress/compress.cpp File Reference
compress.cpp File Reference
#include "../conf.h"
#include "compress.h"
#include "../util/membuffer.h"
Functions
unsigned upx_adler32 (const void *buf, unsigned len, unsigned adler)
int upx_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, upx_callback_t *cb, int method, int level, const upx_compress_config_t *cconf, upx_compress_result_t *cresult)
int upx_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
int upx_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
Function Documentation
upx_adler32()
unsigned upx_adler32 (const void * buf, unsigned len, unsigned adler)
Definition at line 35 of file compress.cpp.
{
    if (len == 0)
        return adler;
    assert(buf != nullptr);
#if 1
    return upx_ucl_adler32(buf, len, adler);
#else
    return upx_zlib_adler32(buf, len, adler);
#endif
}
References buf, and upx_ucl_adler32().
Referenced by Packer::compress(), Filter::filter(), PackPs1::getBkupHeader(), Packer::initPackHeader(), Packer::optimizeReloc(), PackUnix::pack2(), PackUnix::packExtent(), PackUnix::patchLoaderChecksum(), PackLinuxI386::patchLoaderChecksum(), PackMachBase< TMachClass >::patchLoaderChecksum(), ph_decompress(), PackPs1::putBkupHeader(), PackPs1::readBkupHeader(), Filter::unfilter(), Packer::unoptimizeReloc(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachBase< TMachClass >::unpack(), PackUnix::unpack(), PackUnix::unpackExtent(), and upx_compiler_sanity_check().
upx_compress()
int upx_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, upx_callback_t * cb, int method, int level, const upx_compress_config_t * cconf, upx_compress_result_t * cresult)
Definition at line 64 of file compress.cpp.
{
    int r = UPX_E_ERROR;
    upx_compress_result_t cresult_buffer;
    assert(method > 0);
    assert(level > 0);
#if 1
    // set available bytes in dst
    if (*dst_len == 0)
        *dst_len = MemBuffer::getSizeForCompression(src_len);
#else
    // force users to provide *dst_len
    assert(*dst_len != 0);
#endif
    // for UPX, we always require a reasonably sized output buffer
    assert(*dst_len >= MemBuffer::getSizeForCompression(src_len));
    if (!cresult)
        cresult = &cresult_buffer;
    cresult->reset();
#if 1
    // debugging aid
    cresult->debug.method = method;
    cresult->debug.level = level;
    cresult->debug.u_len = src_len;
    cresult->debug.c_len = 0;
#endif
    const unsigned orig_dst_len = *dst_len;
    if (__acc_cte(false)) {
    }
#if (WITH_BZIP2)
    else if (M_IS_BZIP2(method))
        r = upx_bzip2_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_LZMA)
    else if (M_IS_LZMA(method))
        r = upx_lzma_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_NRV)
    else if ((M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) && !opt->prefer_ucl)
        r = upx_nrv_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_UCL)
    else if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        r = upx_ucl_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_ZSTD)
    else if (M_IS_ZSTD(method))
        r = upx_zstd_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
    else {
        throwInternalError("unknown compression method %d", method);
    }
#if 1
    // debugging aid
    cresult->debug.c_len = *dst_len;
#endif
    assert_noexcept(*dst_len <= orig_dst_len);
    return r;
}
References __acc_cte, assert_noexcept, upx_compress_result_t::Debug::c_len, upx_compress_result_t::debug, MemBuffer::getSizeForCompression(), upx_compress_result_t::Debug::level, M_IS_BZIP2, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_IS_ZSTD, upx_compress_result_t::Debug::method, opt, upx_compress_result_t::reset(), throwInternalError(), upx_compress_result_t::Debug::u_len, UPX_E_ERROR, upx_lzma_compress(), and upx_ucl_compress().
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackExe::buildLoader(), PackPs1::buildLoader(), PackMachBase< TMachClass >::buildMachLoader(), Packer::compress(), Packer::compressWithFilters(), PackVmlinuxBase< TElfClass >::pack(), PackUnix::packExtent(), and PackPs1::putBkupHeader().
upx_decompress()
int upx_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 134 of file compress.cpp.
{
    int r = UPX_E_ERROR;
    assert(*dst_len > 0);
    assert(src_len < *dst_len); // must be compressed
    if (cresult && cresult->debug.method == 0)
        cresult = nullptr;
    const unsigned orig_dst_len = *dst_len;
    if (__acc_cte(false)) {
    }
#if (WITH_BZIP2)
    else if (M_IS_BZIP2(method))
        r = upx_bzip2_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_LZMA)
    else if (M_IS_LZMA(method))
        r = upx_lzma_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_NRV)
    else if ((M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) && !opt->prefer_ucl)
        r = upx_nrv_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_UCL)
    else if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        r = upx_ucl_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_ZLIB)
    else if (M_IS_DEFLATE(method))
        r = upx_zlib_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_ZSTD)
    else if (M_IS_ZSTD(method))
        r = upx_zstd_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
    else {
        throwInternalError("unknown compression method %d", method);
    }
    assert_noexcept(*dst_len <= orig_dst_len);
    return r;
}
References __acc_cte, assert_noexcept, upx_compress_result_t::debug, M_IS_BZIP2, M_IS_DEFLATE, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_IS_ZSTD, upx_compress_result_t::Debug::method, opt, throwInternalError(), UPX_E_ERROR, upx_lzma_decompress(), upx_ucl_decompress(), and upx_zlib_decompress().
Referenced by Packer::compress(), PackPs1::getBkupHeader(), ElfLinker::init(), and ph_decompress().
upx_test_overlap()
int upx_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 183 of file compress.cpp.
{
    int r = UPX_E_ERROR;
    if (cresult && cresult->debug.method == 0)
        cresult = nullptr;
    assert(*dst_len > 0);
    assert(src_len < *dst_len); // must be compressed
    unsigned overlap_overhead = src_off + src_len - *dst_len;
    assert((int) overlap_overhead > 0);
    const unsigned orig_dst_len = *dst_len;
    if (__acc_cte(false)) {
    }
#if (WITH_BZIP2)
    else if (M_IS_BZIP2(method))
        r = upx_bzip2_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_LZMA)
    else if (M_IS_LZMA(method))
        r = upx_lzma_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_NRV)
    else if ((M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) && !opt->prefer_ucl)
        r = upx_nrv_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_UCL)
    else if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        r = upx_ucl_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_ZSTD)
    else if (M_IS_ZSTD(method))
        r = upx_zstd_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
    else {
        throwInternalError("unknown compression method %d", method);
    }
    assert_noexcept(*dst_len <= orig_dst_len);
    return r;
}
References __acc_cte, assert_noexcept, buf, upx_compress_result_t::debug, M_IS_BZIP2, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_IS_ZSTD, upx_compress_result_t::Debug::method, opt, throwInternalError(), UPX_E_ERROR, upx_lzma_test_overlap(), and upx_ucl_test_overlap().
Referenced by ph_testOverlappingDecompression().