My Project: src/compress/compress_ucl.cpp File Reference
compress_ucl.cpp File Reference
#include "../conf.h"
#include "compress.h"
Functions
static int convert_errno_from_ucl (int r)
static void __UCL_CDECL wrap_nprogress_ucl (ucl_uint a, ucl_uint b, int state, ucl_voidp user)
int upx_ucl_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, upx_callback_t *cb_parm, int method, int level, const upx_compress_config_t *cconf_parm, upx_compress_result_t *cresult)
int upx_ucl_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
int upx_ucl_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
static ucl_voidp __UCL_CDECL my_malloc (ucl_uint n)
misc
static void __UCL_CDECL my_free (ucl_voidp p)
int upx_ucl_init (void)
const char * upx_ucl_version_string (void)
unsigned upx_ucl_adler32 (const void *buf, unsigned len, unsigned adler)
TEST_CASE ("upx_ucl_decompress")
doctest checks
Function Documentation
convert_errno_from_ucl()
static int convert_errno_from_ucl (int r) static
Definition at line 34 of file compress_ucl.cpp.
{
    switch (r) {
    case UCL_E_OK:
        return UPX_E_OK;
    case UCL_E_ERROR:
        return UPX_E_ERROR;
    case UCL_E_OUT_OF_MEMORY:
        return UPX_E_OUT_OF_MEMORY;
    case UCL_E_NOT_COMPRESSIBLE:
        return UPX_E_NOT_COMPRESSIBLE;
    case UCL_E_INPUT_OVERRUN:
        return UPX_E_INPUT_OVERRUN;
    case UCL_E_OUTPUT_OVERRUN:
        return UPX_E_OUTPUT_OVERRUN;
    case UCL_E_LOOKBEHIND_OVERRUN:
        return UPX_E_LOOKBEHIND_OVERRUN;
    case UCL_E_EOF_NOT_FOUND:
        return UPX_E_EOF_NOT_FOUND;
    case UCL_E_INPUT_NOT_CONSUMED:
        return UPX_E_INPUT_NOT_CONSUMED;
    case UCL_E_INVALID_ARGUMENT:
        return UPX_E_INVALID_ARGUMENT;
    // UCL extra:
    case UCL_E_OVERLAP_OVERRUN:
        return UPX_E_ERROR;
    default:
        break;
    }
    return UPX_E_ERROR;
}
References UPX_E_EOF_NOT_FOUND, UPX_E_ERROR, UPX_E_INPUT_NOT_CONSUMED, UPX_E_INPUT_OVERRUN, UPX_E_INVALID_ARGUMENT, UPX_E_LOOKBEHIND_OVERRUN, UPX_E_NOT_COMPRESSIBLE, UPX_E_OK, UPX_E_OUT_OF_MEMORY, and UPX_E_OUTPUT_OVERRUN.
Referenced by upx_ucl_compress(), upx_ucl_decompress(), and upx_ucl_test_overlap().
my_free()
static void __UCL_CDECL my_free (ucl_voidp p) static
Definition at line 247 of file compress_ucl.cpp.
{ free(p); }
Referenced by upx_ucl_init().
my_malloc()
static ucl_voidp __UCL_CDECL my_malloc (ucl_uint n) static
misc
Definition at line 246 of file compress_ucl.cpp.
{ return upx_calloc(n, 1); }
References n, and upx_calloc().
Referenced by upx_ucl_init().
TEST_CASE()
TEST_CASE ("upx_ucl_decompress")
doctest checks
Definition at line 335 of file compress_ucl.cpp.
{
    const byte *c_data;
    byte d_buf[16];
    unsigned d_len;
    int r;
    c_data = (const byte *) "\x92\xff\x10\x00\x00\x00\x00\x00\x48\xff";
    d_len = 16;
    r = upx_ucl_decompress(c_data, 10, d_buf, &d_len, M_NRV2B_8, nullptr);
    CHECK((r == 0 && d_len == 16));
    r = upx_ucl_decompress(c_data, 9, d_buf, &d_len, M_NRV2B_8, nullptr);
    CHECK(r == UPX_E_INPUT_OVERRUN);
    d_len = 15;
    r = upx_ucl_decompress(c_data, 10, d_buf, &d_len, M_NRV2B_8, nullptr);
    CHECK(r == UPX_E_OUTPUT_OVERRUN);
    c_data = (const byte *) "\x92\xff\x10\x92\x49\x24\x92\xa0\xff";
    d_len = 16;
    r = upx_ucl_decompress(c_data, 9, d_buf, &d_len, M_NRV2D_8, nullptr);
    CHECK((r == 0 && d_len == 16));
    r = upx_ucl_decompress(c_data, 8, d_buf, &d_len, M_NRV2D_8, nullptr);
    CHECK(r == UPX_E_INPUT_OVERRUN);
    d_len = 15;
    r = upx_ucl_decompress(c_data, 9, d_buf, &d_len, M_NRV2D_8, nullptr);
    CHECK(r == UPX_E_OUTPUT_OVERRUN);
    c_data = (const byte *) "\x90\xff\xb0\x92\x49\x24\x92\xa0\xff";
    d_len = 16;
    r = upx_ucl_decompress(c_data, 9, d_buf, &d_len, M_NRV2E_8, nullptr);
    CHECK((r == 0 && d_len == 16));
    r = upx_ucl_decompress(c_data, 8, d_buf, &d_len, M_NRV2E_8, nullptr);
    CHECK(r == UPX_E_INPUT_OVERRUN);
    d_len = 15;
    r = upx_ucl_decompress(c_data, 9, d_buf, &d_len, M_NRV2E_8, nullptr);
    CHECK(r == UPX_E_OUTPUT_OVERRUN);
    UNUSED(r);
}
References M_NRV2B_8, M_NRV2D_8, M_NRV2E_8, UNUSED, UPX_E_INPUT_OVERRUN, UPX_E_OUTPUT_OVERRUN, and upx_ucl_decompress().
upx_ucl_adler32()
unsigned upx_ucl_adler32 (const void * buf, unsigned len, unsigned adler)
Definition at line 265 of file compress_ucl.cpp.
{
    return ucl_adler32(adler, (const ucl_bytep) buf, len);
}
References buf.
Referenced by upx_adler32().
upx_ucl_compress()
int upx_ucl_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, upx_callback_t * cb_parm, int method, int level, const upx_compress_config_t * cconf_parm, upx_compress_result_t * cresult)
Definition at line 79 of file compress_ucl.cpp.
{
    int r;
    assert(level > 0);
    assert(cresult != nullptr);
    COMPILE_TIME_ASSERT(sizeof(ucl_compress_config_t) == sizeof(REAL_ucl_compress_config_t))
    ucl_progress_callback_t cb;
    cb.callback = nullptr;
    cb.user = nullptr;
    if (cb_parm && cb_parm->nprogress) {
        cb.callback = wrap_nprogress_ucl;
        cb.user = cb_parm;
    }
    ucl_compress_config_t cconf;
    cconf.reset();
    if (cconf_parm) {
        // cconf = cconf_parm->conf_ucl; // struct copy
        memcpy(&cconf, &cconf_parm->conf_ucl, sizeof(cconf));
    }
    ucl_uint *const res = cresult->result_ucl.result;
    // assume no info available - fill in worst case results
    // res[0] = 1;        // min_offset_found - NOT USED
    res[1] = src_len - 1; // max_offset_found
    // res[2] = 2;        // min_match_found - NOT USED
    res[3] = src_len - 1; // max_match_found
    // res[4] = 1;        // min_run_found - NOT USED
    res[5] = src_len; // max_run_found
    res[6] = 1;       // first_offset_found
    // res[7] = 999999;   // same_match_offsets_found - NOT USED
    // prepare bit-buffer settings
    cconf.bb_endian = 0;
    cconf.bb_size = 0;
    if (method >= M_NRV2B_LE32 && method <= M_NRV2E_LE16) {
        static const upx_uint8_t sizes[3] = {32, 8, 16};
        cconf.bb_size = sizes[(method - M_NRV2B_LE32) % 3];
    } else {
        throwInternalError("unknown compression method");
        return UPX_E_ERROR;
    }
    // optimize compression params
    if (level <= 3 && cconf.max_offset == UCL_UINT_MAX)
        cconf.max_offset = 8 * 1024 - 1;
    else if (level == 4 && cconf.max_offset == UCL_UINT_MAX)
        cconf.max_offset = 32 * 1024 - 1;
    if M_IS_NRV2B (method)
        r = ucl_nrv2b_99_compress(src, src_len, dst, dst_len, &cb, level, &cconf, res);
    else if M_IS_NRV2D (method)
        r = ucl_nrv2d_99_compress(src, src_len, dst, dst_len, &cb, level, &cconf, res);
    else if M_IS_NRV2E (method)
        r = ucl_nrv2e_99_compress(src, src_len, dst, dst_len, &cb, level, &cconf, res);
    else {
        throwInternalError("unknown compression method");
        return UPX_E_ERROR;
    }
    // make sure first_offset_found is set
    if (res[6] == 0)
        res[6] = 1;
    return convert_errno_from_ucl(r);
}
References COMPILE_TIME_ASSERT, upx_compress_config_t::conf_ucl, convert_errno_from_ucl(), M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_NRV2B_LE32, M_NRV2E_LE16, memcpy(), upx_callback_t::nprogress, ucl_compress_config_t::reset(), ucl_compress_result_t::result, upx_compress_result_t::result_ucl, throwInternalError(), UPX_E_ERROR, and wrap_nprogress_ucl().
Referenced by upx_compress().
upx_ucl_decompress()
int upx_ucl_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 153 of file compress_ucl.cpp.
{
    int r;
    switch (method) {
    case M_NRV2B_8:
        r = ucl_nrv2b_decompress_safe_8(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2B_LE16:
        r = ucl_nrv2b_decompress_safe_le16(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2B_LE32:
        r = ucl_nrv2b_decompress_safe_le32(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2D_8:
        r = ucl_nrv2d_decompress_safe_8(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2D_LE16:
        r = ucl_nrv2d_decompress_safe_le16(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2D_LE32:
        r = ucl_nrv2d_decompress_safe_le32(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2E_8:
        r = ucl_nrv2e_decompress_safe_8(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2E_LE16:
        r = ucl_nrv2e_decompress_safe_le16(src, src_len, dst, dst_len, nullptr);
        break;
    case M_NRV2E_LE32:
        r = ucl_nrv2e_decompress_safe_le32(src, src_len, dst, dst_len, nullptr);
        break;
    default:
        throwInternalError("unknown decompression method");
        return UPX_E_ERROR;
    }
    UNUSED(cresult);
    return convert_errno_from_ucl(r);
}
References convert_errno_from_ucl(), M_NRV2B_8, M_NRV2B_LE16, M_NRV2B_LE32, M_NRV2D_8, M_NRV2D_LE16, M_NRV2D_LE32, M_NRV2E_8, M_NRV2E_LE16, M_NRV2E_LE32, throwInternalError(), UNUSED, and UPX_E_ERROR.
Referenced by TEST_CASE(), and upx_decompress().
upx_ucl_init()
int upx_ucl_init (void)
Definition at line 250 of file compress_ucl.cpp.
                       {
#if (ACC_CC_MSC && ACC_ARCH_I386) && (_MSC_VER >= 1940)
    (void) ucl_init(); // TODO later
#else
    if (ucl_init() != UCL_E_OK)
        return -1;
#endif
    if (UCL_VERSION != ucl_version() || strcmp(UCL_VERSION_STRING, ucl_version_string()) != 0)
        return -2;
    ucl_set_malloc_hooks(my_malloc, my_free);
    return 0;
}
References my_free(), my_malloc(), and strcmp().
Referenced by upx_main().
upx_ucl_test_overlap()
int upx_ucl_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 198 of file compress_ucl.cpp.
{
    int r;
    UNUSED(tbuf); // not needed for UCL
    switch (method) {
    case M_NRV2B_8:
        r = ucl_nrv2b_test_overlap_8(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2B_LE16:
        r = ucl_nrv2b_test_overlap_le16(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2B_LE32:
        r = ucl_nrv2b_test_overlap_le32(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2D_8:
        r = ucl_nrv2d_test_overlap_8(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2D_LE16:
        r = ucl_nrv2d_test_overlap_le16(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2D_LE32:
        r = ucl_nrv2d_test_overlap_le32(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2E_8:
        r = ucl_nrv2e_test_overlap_8(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2E_LE16:
        r = ucl_nrv2e_test_overlap_le16(buf, src_off, src_len, dst_len, nullptr);
        break;
    case M_NRV2E_LE32:
        r = ucl_nrv2e_test_overlap_le32(buf, src_off, src_len, dst_len, nullptr);
        break;
    default:
        throwInternalError("unknown decompression method");
        return UPX_E_ERROR;
    }
    UNUSED(cresult);
    return convert_errno_from_ucl(r);
}
References buf, convert_errno_from_ucl(), M_NRV2B_8, M_NRV2B_LE16, M_NRV2B_LE32, M_NRV2D_8, M_NRV2D_LE16, M_NRV2D_LE32, M_NRV2E_8, M_NRV2E_LE16, M_NRV2E_LE32, throwInternalError(), UNUSED, and UPX_E_ERROR.
Referenced by upx_test_overlap().
upx_ucl_version_string()
const char * upx_ucl_version_string (void)
Definition at line 263 of file compress_ucl.cpp.
{ return ucl_version_string(); }
Referenced by show_version().
wrap_nprogress_ucl()
static void __UCL_CDECL wrap_nprogress_ucl (ucl_uint a, ucl_uint b, int state, ucl_voidp user) static
Definition at line 66 of file compress_ucl.cpp.
{
    if (state != -1 && state != 3)
        return;
    upx_callback_t *cb = (upx_callback_t *) user;
    if (cb && cb->nprogress)
        cb->nprogress(cb, a, b);
}
References b, and upx_callback_t::nprogress.
Referenced by upx_ucl_compress().