My Project: src/compress/compress_zlib.cpp File Reference
compress_zlib.cpp File Reference
#include "../conf.h"
#include "compress.h"
#include "../util/membuffer.h"
#include <zlib/zlib.h>
#include <zlib/deflate.h>
Macros
#define ZLIB_CONST 1
Functions
static int convert_errno_from_zlib (int zr)
int upx_zlib_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, upx_callback_t *cb_parm, int method, int level, const upx_compress_config_t *cconf_parm, upx_compress_result_t *cresult)
int upx_zlib_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
int upx_zlib_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
test_overlap - see <ucl/ucl.h> for semantics
int upx_zlib_init (void)
misc
const char * upx_zlib_version_string (void)
TEST_CASE ("upx_zlib_decompress")
doctest checks
Macro Definition Documentation
ZLIB_CONST
#define ZLIB_CONST 1
Definition at line 40 of file compress_zlib.cpp.
Function Documentation
convert_errno_from_zlib()
static int convert_errno_from_zlib (int zr) static
Definition at line 45 of file compress_zlib.cpp.
{
    switch (zr) {
    case Z_OK:
        return UPX_E_OK;
    // positive values
    case Z_STREAM_END:
        return UPX_E_ERROR;
    case Z_NEED_DICT:
        return UPX_E_ERROR;
    // negative values
    case Z_ERRNO:
        return UPX_E_ERROR;
    case Z_STREAM_ERROR:
        return UPX_E_ERROR;
    case Z_DATA_ERROR:
        return UPX_E_ERROR;
    case Z_MEM_ERROR:
        return UPX_E_OUT_OF_MEMORY;
    case Z_BUF_ERROR:
        return UPX_E_OUTPUT_OVERRUN;
    case Z_VERSION_ERROR:
        return UPX_E_ERROR;
    case -7: // UPX extra
        return UPX_E_INPUT_OVERRUN;
    default:
        break;
    }
    return UPX_E_ERROR;
}
References UPX_E_ERROR, UPX_E_INPUT_OVERRUN, UPX_E_OK, UPX_E_OUT_OF_MEMORY, and UPX_E_OUTPUT_OVERRUN.
Referenced by upx_zlib_compress(), and upx_zlib_decompress().
TEST_CASE()
TEST_CASE ("upx_zlib_decompress")
doctest checks
Definition at line 294 of file compress_zlib.cpp.
{
    const byte *c_data;
    byte d_buf[16];
    unsigned d_len;
    int r;
    c_data = (const byte *) "\xfb\xff\x1f\x15\x00\x00";
    d_len = 16;
    r = upx_zlib_decompress(c_data, 6, d_buf, &d_len, M_DEFLATE, nullptr);
    CHECK((r == 0 && d_len == 16));
    r = upx_zlib_decompress(c_data, 5, d_buf, &d_len, M_DEFLATE, nullptr);
    CHECK(r == UPX_E_INPUT_OVERRUN);
    d_len = 15;
    r = upx_zlib_decompress(c_data, 6, d_buf, &d_len, M_DEFLATE, nullptr);
    CHECK(r == UPX_E_OUTPUT_OVERRUN);
    UNUSED(r);
}
References M_DEFLATE, UNUSED, UPX_E_INPUT_OVERRUN, UPX_E_OUTPUT_OVERRUN, and upx_zlib_decompress().
upx_zlib_compress()
int upx_zlib_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, upx_callback_t * cb_parm, int method, int level, const upx_compress_config_t * cconf_parm, upx_compress_result_t * cresult)
Definition at line 79 of file compress_zlib.cpp.
{
    assert(method == M_DEFLATE);
    assert(level > 0);
    assert(cresult != nullptr);
    UNUSED(cb_parm);
    int r = UPX_E_ERROR;
    int zr;
    const zlib_compress_config_t *const lcconf = cconf_parm ? &cconf_parm->conf_zlib : nullptr;
    zlib_compress_result_t *const res = &cresult->result_zlib;
    res->reset();
    if (level == 10)
        level = 9;
    zlib_compress_config_t::mem_level_t mem_level;
    zlib_compress_config_t::window_bits_t window_bits;
    zlib_compress_config_t::strategy_t strategy;
    // cconf overrides
    if (lcconf) {
        upx::oassign(mem_level, lcconf->mem_level);
        upx::oassign(window_bits, lcconf->window_bits);
        upx::oassign(strategy, lcconf->strategy);
    }
    z_stream s;
    s.zalloc = (alloc_func) nullptr;
    s.zfree = (free_func) nullptr;
    s.next_in = src;
    s.avail_in = src_len;
    s.next_out = dst;
    s.avail_out = *dst_len;
    s.total_in = s.total_out = 0;
    zr = (int) deflateInit2(&s, level, Z_DEFLATED, 0 - (int) window_bits, mem_level, strategy);
    if (zr != Z_OK)
        goto error;
    assert(s.state->level == level);
    zr = deflate(&s, Z_FINISH);
    if (zr != Z_STREAM_END)
        goto error;
    zr = deflateEnd(&s);
    if (zr != Z_OK)
        goto error;
    r = UPX_E_OK;
    goto done;
error:
    (void) deflateEnd(&s);
    r = convert_errno_from_zlib(zr);
    if (r == UPX_E_OK)
        r = UPX_E_ERROR;
done:
    if (r == UPX_E_OK) {
        if (s.avail_in != 0 || s.total_in != src_len)
            r = UPX_E_ERROR;
    }
    assert(s.total_in <= src_len);
    assert(s.total_out <= *dst_len);
    *dst_len = s.total_out;
    return r;
}
References upx_compress_config_t::conf_zlib, convert_errno_from_zlib(), M_DEFLATE, zlib_compress_config_t::mem_level, upx::oassign(), zlib_compress_result_t::reset(), upx_compress_result_t::result_zlib, zlib_compress_config_t::strategy, UNUSED, UPX_E_ERROR, UPX_E_OK, and zlib_compress_config_t::window_bits.
upx_zlib_decompress()
int upx_zlib_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 146 of file compress_zlib.cpp.
{
    assert(method == M_DEFLATE);
    UNUSED(method);
    UNUSED(cresult);
    int r = UPX_E_ERROR;
    int zr;
    z_stream s;
    s.zalloc = (alloc_func) nullptr;
    s.zfree = (free_func) nullptr;
    s.next_in = src;
    s.avail_in = src_len;
    s.next_out = dst;
    s.avail_out = *dst_len;
    s.total_in = s.total_out = 0;
    zr = inflateInit2(&s, -15);
    if (zr != Z_OK)
        goto error;
    zr = inflate(&s, Z_FINISH);
    if (zr != Z_STREAM_END) {
        if (zr == Z_BUF_ERROR && s.avail_in == 0)
            zr = -7; // UPX extra
        goto error;
    }
    zr = inflateEnd(&s);
    if (zr != Z_OK)
        goto error;
    r = UPX_E_OK;
    goto done;
error:
    (void) inflateEnd(&s);
    r = convert_errno_from_zlib(zr);
    if (r == UPX_E_OK)
        r = UPX_E_ERROR;
done:
    if (r == UPX_E_OK) {
        if (s.avail_in != 0 || s.total_in != src_len)
            r = UPX_E_INPUT_NOT_CONSUMED;
    }
    assert(s.total_in <= src_len);
    assert(s.total_out <= *dst_len);
    *dst_len = s.total_out;
    return r;
}
References convert_errno_from_zlib(), M_DEFLATE, UNUSED, UPX_E_ERROR, UPX_E_INPUT_NOT_CONSUMED, and UPX_E_OK.
Referenced by TEST_CASE(), upx_decompress(), and upx_zlib_test_overlap().
upx_zlib_init()
int upx_zlib_init (void)
misc
Definition at line 223 of file compress_zlib.cpp.
{
    if (strcmp(ZLIB_VERSION, zlibVersion()) != 0)
        return -2;
    return 0;
}
References strcmp().
Referenced by upx_main().
upx_zlib_test_overlap()
int upx_zlib_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
test_overlap - see <ucl/ucl.h> for semantics
Definition at line 197 of file compress_zlib.cpp.
{
    assert(method == M_DEFLATE);
    MemBuffer b(src_off + src_len);
    memcpy(b + src_off, buf + src_off, src_len);
    unsigned saved_dst_len = *dst_len;
    int r = upx_zlib_decompress(raw_index_bytes(b, src_off, src_len), src_len,
                                raw_bytes(b, *dst_len), dst_len, method, cresult);
    if (r != UPX_E_OK)
        return r;
    if (*dst_len != saved_dst_len)
        return UPX_E_ERROR;
    // NOTE: there is a very tiny possibility that decompression has
    //   succeeded but the data is not restored correctly because of
    //   in-place buffer overlapping, so we use an extra memcmp().
    if (tbuf != nullptr && memcmp(tbuf, b, *dst_len) != 0)
        return UPX_E_ERROR;
    return UPX_E_OK;
}
References b, buf, M_DEFLATE, memcmp(), memcpy(), raw_bytes(), raw_index_bytes(), UPX_E_ERROR, UPX_E_OK, and upx_zlib_decompress().
upx_zlib_version_string()
const char * upx_zlib_version_string (void)
Definition at line 229 of file compress_zlib.cpp.
{ return zlibVersion(); }
Referenced by show_version().