My Project: src/conf.h File Reference
conf.h File Reference
#include "util/system_headers.h"
#include "util/system_undefs.h"
#include "version.h"
#include "util/cxxlib.h"
#include <ucl/include/ucl/uclconf.h>
#include <ucl/include/ucl/ucl.h>
#include "util/snprintf.h"
#include "util/util.h"
#include "options.h"
#include "except.h"
#include "bele.h"
#include "console/console.h"
#include "util/raw_bytes.h"
#include "util/xspan.h"
#include "util/system_check_predefs.h"
Classes
struct upx_is_integral< T >
struct upx_charptr_unit_type
struct upx_callback_t
struct bzip2_compress_config_t
compression - config_t
struct lzma_compress_config_t
struct ucl_compress_config_t
struct zlib_compress_config_t
struct zstd_compress_config_t
struct upx_compress_config_t
struct bzip2_compress_result_t
compression - result_t
struct lzma_compress_result_t
struct ucl_compress_result_t
struct zlib_compress_result_t
struct zstd_compress_result_t
struct upx_compress_result_t
struct upx_compress_result_t::Debug
Namespaces
namespace upx
some global overloads
Macros
#define __has_attribute(x) 0
init
#define __has_builtin(x) 0
#define __has_declspec_attribute(x) 0
#define __has_feature(x) 0
#define __has_include(x) 0
#define __has_warning(x) 0
#define upx_thread_local /*empty*/
#define upx_std_atomic(Type) Type
#define upx_std_once_flag upx_std_atomic(size_t)
#define upx_alignas_max alignas(std::max_align_t)
#define UPX_RSIZE_MAX UPX_RSIZE_MAX_MEM
#define UPX_RSIZE_MAX_MEM (768 * 1024 * 1024)
#define UPX_RSIZE_MAX_STR (256 * 1024)
#define upx_byte byte
#define upx_bytep byte *
#define charptr upx_charptr_unit_type *
#define off_t upx_off_t
#define forceinline __acc_forceinline
#define noinline __acc_noinline
#define noreturn noinline
#define forceinline_constexpr forceinline constexpr
#define likely __acc_likely
#define unlikely __acc_unlikely
#define very_likely __acc_very_likely
#define very_unlikely __acc_very_unlikely
#define may_throw noexcept(false)
#define COMPILE_TIME_ASSERT(e) ACC_COMPILE_TIME_ASSERT(e)
#define DELETED_FUNCTION = delete
#define UNUSED(var) ACC_UNUSED(var)
#define __unix__ 1
portab
#define STDIN_FILENO (fileno(stdin))
#define STDOUT_FILENO (fileno(stdout))
#define STDERR_FILENO (fileno(stderr))
#define bswap16 upx_bswap16
#define bswap32 upx_bswap32
#define bswap64 upx_bswap64
#define _base upx_renamed__base
#define basename upx_renamed_basename
#define index upx_renamed_index
#define outp upx_renamed_outp
#define O_BINARY 0
#define CLANG_FORMAT_DUMMY_STATEMENT /*empty*/
util
#define VALGRIND_CHECK_MEM_IS_ADDRESSABLE(addr, len) 0
#define VALGRIND_CHECK_MEM_IS_DEFINED(addr, len) 0
#define VALGRIND_MAKE_MEM_DEFINED(addr, len) 0
#define VALGRIND_MAKE_MEM_NOACCESS(addr, len) 0
#define VALGRIND_MAKE_MEM_UNDEFINED(addr, len) 0
#define attribute_format(a, b) /*empty*/
#define upx_memcmp_inline memcmp
#define upx_memcpy_inline memcpy
#define upx_return_address() nullptr
#define packed_struct(s) struct alignas(1) s
#define COMPILE_TIME_ASSERT_ALIGNOF_USING_SIZEOF__(a, b)
#define COMPILE_TIME_ASSERT_ALIGNOF__(a, b)
#define COMPILE_TIME_ASSERT_ALIGNED1(a) COMPILE_TIME_ASSERT_ALIGNOF__(a, char)
#define TABLESIZE(table) ((sizeof(table) / sizeof((table)[0])))
#define Array(type, var, n)
#define ByteArray(var, n) Array(byte, var, (n))
#define assert_noexcept assert
#define usizeof(expr) (upx::UnsignedSizeOf<sizeof(expr)>::value)
#define ALIGN_DOWN(a, b) (upx::align_down((a), (b)))
#define ALIGN_UP(a, b) (upx::align_up((a), (b)))
#define ALIGN_UP_GAP(a, b) (upx::align_up_gap((a), (b)))
#define UPX_MAX(a, b) (upx::max((a), (b)))
#define UPX_MIN(a, b) (upx::min((a), (b)))
#define EXIT_OK 0
constants
#define EXIT_ERROR 1
#define EXIT_WARN 2
#define EXIT_USAGE 1
#define EXIT_FILE_READ 1
#define EXIT_FILE_WRITE 1
#define EXIT_MEMORY 1
#define EXIT_CHECKSUM 1
#define EXIT_INIT 1
#define EXIT_INTERNAL 1
#define UPX_MAGIC_LE32 0x21585055 /* "UPX!" */
#define UPX_MAGIC2_LE32 0xD5D0D8A1
#define UPX_E_OK (0)
#define UPX_E_ERROR (-1)
#define UPX_E_OUT_OF_MEMORY (-2)
#define UPX_E_NOT_COMPRESSIBLE (-3)
#define UPX_E_INPUT_OVERRUN (-4)
#define UPX_E_OUTPUT_OVERRUN (-5)
#define UPX_E_LOOKBEHIND_OVERRUN (-6)
#define UPX_E_EOF_NOT_FOUND (-7)
#define UPX_E_INPUT_NOT_CONSUMED (-8)
#define UPX_E_NOT_YET_IMPLEMENTED (-9)
#define UPX_E_INVALID_ARGUMENT (-10)
#define UPX_F_DOS_COM 1
#define UPX_F_DOS_SYS 2
#define UPX_F_DOS_EXE 3
#define UPX_F_DJGPP2_COFF 4
#define UPX_F_WATCOM_LE 5
#define UPX_F_DOS_EXEH 7
#define UPX_F_TMT_ADAM 8
#define UPX_F_W32PE_I386 9
#define UPX_F_LINUX_i386 10
#define UPX_F_LINUX_ELF_i386 12
#define UPX_F_LINUX_SH_i386 14
#define UPX_F_VMLINUZ_i386 15
#define UPX_F_BVMLINUZ_i386 16
#define UPX_F_ELKS_8086 17
#define UPX_F_PS1_EXE 18
#define UPX_F_VMLINUX_i386 19
#define UPX_F_LINUX_ELFI_i386 20
#define UPX_F_WINCE_ARM 21
#define UPX_F_LINUX_ELF64_AMD64 22
#define UPX_F_LINUX_ELF32_ARM 23
#define UPX_F_BSD_i386 24
#define UPX_F_BSD_ELF_i386 25
#define UPX_F_BSD_SH_i386 26
#define UPX_F_VMLINUX_AMD64 27
#define UPX_F_VMLINUX_ARM 28
#define UPX_F_MACH_i386 29
#define UPX_F_LINUX_ELF32_MIPSEL 30
#define UPX_F_VMLINUZ_ARM 31
#define UPX_F_MACH_ARM 32
#define UPX_F_DYLIB_i386 33
#define UPX_F_MACH_AMD64 34
#define UPX_F_DYLIB_AMD64 35
#define UPX_F_W64PE_AMD64 36
#define UPX_F_MACH_ARM64 37
#define UPX_F_LINUX_ELF64_PPC64LE 39
#define UPX_F_VMLINUX_PPC64LE 40
#define UPX_F_LINUX_ELF64_ARM64 42
#define UPX_F_W64PE_ARM64 43
#define UPX_F_W64PE_ARM64EC 44
#define UPX_F_ATARI_TOS 129
#define UPX_F_MACH_PPC32 131
#define UPX_F_LINUX_ELF32_PPC32 132
#define UPX_F_LINUX_ELF32_ARMEB 133
#define UPX_F_MACH_FAT 134
#define UPX_F_VMLINUX_ARMEB 135
#define UPX_F_VMLINUX_PPC32 136
#define UPX_F_LINUX_ELF32_MIPS 137
#define UPX_F_DYLIB_PPC32 138
#define UPX_F_MACH_PPC64 139
#define UPX_F_LINUX_ELF64_PPC64 140
#define UPX_F_VMLINUX_PPC64 141
#define UPX_F_DYLIB_PPC64 142
#define M_NRV2B_LE32 2
#define M_NRV2B_8 3
#define M_NRV2B_LE16 4
#define M_NRV2D_LE32 5
#define M_NRV2D_8 6
#define M_NRV2D_LE16 7
#define M_NRV2E_LE32 8
#define M_NRV2E_8 9
#define M_NRV2E_LE16 10
#define M_LZMA 14
#define M_DEFLATE 15
#define M_ZSTD 16
#define M_BZIP2 17
#define M_ALL (-1)
#define M_END (-2)
#define M_NONE (-3)
#define M_SKIP (-4)
#define M_ULTRA_BRUTE (-5)
#define M_IS_NRV2B(x) ((x) >= M_NRV2B_LE32 && (x) <= M_NRV2B_LE16)
#define M_IS_NRV2D(x) ((x) >= M_NRV2D_LE32 && (x) <= M_NRV2D_LE16)
#define M_IS_NRV2E(x) ((x) >= M_NRV2E_LE32 && (x) <= M_NRV2E_LE16)
#define M_IS_LZMA(x) (((x) &255) == M_LZMA)
#define M_IS_DEFLATE(x) ((x) == M_DEFLATE)
#define M_IS_ZSTD(x) ((x) == M_ZSTD)
#define M_IS_BZIP2(x) ((x) == M_BZIP2)
#define FT_END (-1)
#define FT_NONE (-2)
#define FT_SKIP (-3)
#define FT_ULTRA_BRUTE (-4)
#define WITH_LZMA 1
compression - setup and callback_t
#define WITH_UCL 1
#define WITH_ZLIB 1
#define ucl_compress_config_t REAL_ucl_compress_config_t
#define NULL_cconf ((const upx_compress_config_t *) nullptr)
Typedefs
typedef size_t upx_rsize_t
core
typedef acc_int8_t upx_int8_t
typedef acc_uint8_t upx_uint8_t
typedef acc_int16_t upx_int16_t
typedef acc_uint16_t upx_uint16_t
typedef acc_int32_t upx_int32_t
typedef acc_uint32_t upx_uint32_t
typedef acc_int64_t upx_int64_t
typedef acc_uint64_t upx_uint64_t
typedef acc_uintptr_t upx_uintptr_t
typedef upx_uintptr_t upx_ptraddr_t
typedef std::make_signed_t< upx_ptraddr_t > upx_sptraddr_t
typedef std::make_unsigned_t< ptrdiff_t > upx_uptrdiff_t
typedef std::make_signed_t< size_t > upx_ssize_t
typedef unsigned char byte
typedef unsigned char uchar
typedef long long upx_off_t
typedef void(__acc_cdecl * upx_progress_func_t) (upx_callback_t *, unsigned, unsigned)
typedef ElfLinker Linker
Functions
template<class NoexceptCallable >
void upx_std_call_once (upx_std_once_flag &flag, NoexceptCallable &&f)
void NO_printf (const char *,...) noexcept attribute_format(1
void NO_fprintf (FILE *, const char *,...) noexcept attribute_format(2
template<class T >
void mem_clear (T *object) noexcept
template<class T >
void mem_clear (T(&array)[]) noexcept DELETED_FUNCTION
template<class T , size_t N>
void mem_clear (T(&array)[N]) noexcept DELETED_FUNCTION
noreturn void assertFailed (const char *expr, const char *file, int line, const char *func) noexcept
util
noreturn void throwAssertFailed (const char *expr, const char *file, int line, const char *func)
noinline void upx_compiler_sanity_check () noexcept
noinline int upx_doctest_check (int argc, char **argv)
upx_doctest_check()
int upx_doctest_check ()
void * membuffer_get_void_ptr (MemBuffer &mb) noexcept
unsigned membuffer_get_size (MemBuffer &mb) noexcept
bool main_set_exit_code (int ec)
int main_get_options (int argc, char **argv)
void main_get_envoptions ()
int upx_main (int argc, char *argv[]) may_throw
main entry point
void printSetNl (int need_nl) noexcept
void printClearLine (FILE *f=nullptr) noexcept
void printErr (const char *iname, const Throwable &e) noexcept
void printUnhandledException (const char *iname, const std::exception *e) noexcept
void printErr (const char *iname, const char *format,...) noexcept attribute_format(2
void void printWarn (const char *iname, const char *format,...) noexcept attribute_format(2
void void void infoWarning (const char *format,...) attribute_format(1
void void void void infoHeader (const char *format,...) attribute_format(1
void void void void void info (const char *format,...) attribute_format(1
void void void void void void infoHeader ()
void infoWriting (const char *what, upx_int64_t size)
void do_one_file (const char *iname, char *oname) may_throw
process one file
int do_files (int i, int argc, char *argv[]) may_throw
void show_header ()
void show_help (int verbose)
help
void show_license ()
license
void show_sysinfo (const char *options_var)
sysinfo undocumented and subject to change
void show_usage ()
usage
void show_version (bool one_line=false)
version
unsigned upx_adler32 (const void *buf, unsigned len, unsigned adler=1)
unsigned upx_crc32 (const void *buf, unsigned len, unsigned crc=0)
int upx_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, upx_callback_t *cb, int method, int level, const upx_compress_config_t *cconf, upx_compress_result_t *cresult)
int upx_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
int upx_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned *dst_len, int method, const upx_compress_result_t *cresult)
Variables
template<class T >
constexpr bool upx_is_integral_v = upx_is_integral<T>::value
const char * progname
const char gitrev []
header
Macro Definition Documentation
__has_attribute
#define __has_attribute (x) 0
init
Definition at line 39 of file conf.h.
__has_builtin
#define __has_builtin (x) 0
Definition at line 42 of file conf.h.
__has_declspec_attribute
#define __has_declspec_attribute (x) 0
Definition at line 45 of file conf.h.
__has_feature
#define __has_feature (x) 0
Definition at line 48 of file conf.h.
__has_include
#define __has_include (x) 0
Definition at line 51 of file conf.h.
__has_warning
#define __has_warning (x) 0
Definition at line 54 of file conf.h.
__unix__
#define __unix__ 1
portab
Definition at line 246 of file conf.h.
_base
#define _base upx_renamed__base
Definition at line 326 of file conf.h.
ALIGN_DOWN
#define ALIGN_DOWN (a, b) (upx::align_down((a), (b)))
Definition at line 485 of file conf.h.
ALIGN_UP
#define ALIGN_UP (a, b) (upx::align_up((a), (b)))
Definition at line 486 of file conf.h.
ALIGN_UP_GAP
#define ALIGN_UP_GAP (a, b) (upx::align_up_gap((a), (b)))
Definition at line 487 of file conf.h.
Array
#define Array (type, var, n)
Value:
    MemBuffer var##_membuf(mem_size(sizeof(type), (n)));                                           \
    type *const var = ACC_STATIC_CAST(type *, var##_membuf.getVoidPtr())
Definition at line 455 of file conf.h.
assert_noexcept
#define assert_noexcept assert
Definition at line 478 of file conf.h.
attribute_format
#define attribute_format (a, b) /*empty*/
Definition at line 370 of file conf.h.
basename
#define basename upx_renamed_basename
Definition at line 327 of file conf.h.
bswap16
#define bswap16 upx_bswap16
Definition at line 317 of file conf.h.
bswap32
#define bswap32 upx_bswap32
Definition at line 318 of file conf.h.
bswap64
#define bswap64 upx_bswap64
Definition at line 319 of file conf.h.
ByteArray
#define ByteArray (var, n) Array(byte, var, (n))
Definition at line 459 of file conf.h.
charptr
#define charptr upx_charptr_unit_type *
Definition at line 189 of file conf.h.
CLANG_FORMAT_DUMMY_STATEMENT
#define CLANG_FORMAT_DUMMY_STATEMENT /*empty*/
util
Definition at line 345 of file conf.h.
COMPILE_TIME_ASSERT
#define COMPILE_TIME_ASSERT (e) ACC_COMPILE_TIME_ASSERT(e)
Definition at line 237 of file conf.h.
COMPILE_TIME_ASSERT_ALIGNED1
#define COMPILE_TIME_ASSERT_ALIGNED1 (a) COMPILE_TIME_ASSERT_ALIGNOF__(a, char)
Definition at line 432 of file conf.h.
COMPILE_TIME_ASSERT_ALIGNOF__
#define COMPILE_TIME_ASSERT_ALIGNOF__ (a, b)
Value:
    COMPILE_TIME_ASSERT_ALIGNOF_USING_SIZEOF__(a, b)                                               \
    COMPILE_TIME_ASSERT(__acc_alignof(a) == sizeof(b))                                             \
    COMPILE_TIME_ASSERT(alignof(a) == sizeof(b))
Definition at line 428 of file conf.h.
COMPILE_TIME_ASSERT_ALIGNOF_USING_SIZEOF__
#define COMPILE_TIME_ASSERT_ALIGNOF_USING_SIZEOF__ (a, b)
Value:
    {                                                                                              \
        typedef a acc_tmp_a_t;                                                                     \
        typedef b acc_tmp_b_t;                                                                     \
        struct alignas(1) acc_tmp_t {                                                              \
            acc_tmp_b_t x;                                                                         \
            acc_tmp_a_t y;                                                                         \
            acc_tmp_b_t z;                                                                         \
        };                                                                                         \
        COMPILE_TIME_ASSERT(sizeof(struct acc_tmp_t) == 2 * sizeof(b) + sizeof(a))                 \
        COMPILE_TIME_ASSERT(sizeof(((acc_tmp_t *) nullptr)->x) +                                   \
                                sizeof(((acc_tmp_t *) nullptr)->y) +                               \
                                sizeof(((acc_tmp_t *) nullptr)->z) ==                              \
                            2 * sizeof(b) + sizeof(a))                                             \
    }
Definition at line 413 of file conf.h.
DELETED_FUNCTION
#define DELETED_FUNCTION = delete
Definition at line 238 of file conf.h.
EXIT_CHECKSUM
#define EXIT_CHECKSUM 1
Definition at line 504 of file conf.h.
EXIT_ERROR
#define EXIT_ERROR 1
Definition at line 497 of file conf.h.
EXIT_FILE_READ
#define EXIT_FILE_READ 1
Definition at line 501 of file conf.h.
EXIT_FILE_WRITE
#define EXIT_FILE_WRITE 1
Definition at line 502 of file conf.h.
EXIT_INIT
#define EXIT_INIT 1
Definition at line 505 of file conf.h.
EXIT_INTERNAL
#define EXIT_INTERNAL 1
Definition at line 506 of file conf.h.
EXIT_MEMORY
#define EXIT_MEMORY 1
Definition at line 503 of file conf.h.
EXIT_OK
#define EXIT_OK 0
constants
Definition at line 496 of file conf.h.
EXIT_USAGE
#define EXIT_USAGE 1
Definition at line 500 of file conf.h.
EXIT_WARN
#define EXIT_WARN 2
Definition at line 498 of file conf.h.
forceinline
#define forceinline __acc_forceinline
Definition at line 210 of file conf.h.
forceinline_constexpr
#define forceinline_constexpr forceinline constexpr
Definition at line 227 of file conf.h.
FT_END
#define FT_END (-1)
Definition at line 620 of file conf.h.
FT_NONE
#define FT_NONE (-2)
Definition at line 621 of file conf.h.
FT_SKIP
#define FT_SKIP (-3)
Definition at line 622 of file conf.h.
FT_ULTRA_BRUTE
#define FT_ULTRA_BRUTE (-4)
Definition at line 623 of file conf.h.
index
#define index upx_renamed_index
Definition at line 328 of file conf.h.
likely
#define likely __acc_likely
Definition at line 228 of file conf.h.
M_ALL
#define M_ALL (-1)
Definition at line 604 of file conf.h.
M_BZIP2
#define M_BZIP2 17
Definition at line 602 of file conf.h.
M_DEFLATE
#define M_DEFLATE 15
Definition at line 600 of file conf.h.
M_END
#define M_END (-2)
Definition at line 605 of file conf.h.
M_IS_BZIP2
#define M_IS_BZIP2 (x) ((x) == M_BZIP2)
Definition at line 617 of file conf.h.
M_IS_DEFLATE
#define M_IS_DEFLATE (x) ((x) == M_DEFLATE)
Definition at line 615 of file conf.h.
M_IS_LZMA
#define M_IS_LZMA (x) (((x) &255) == M_LZMA)
Definition at line 614 of file conf.h.
M_IS_NRV2B
#define M_IS_NRV2B (x) ((x) >= M_NRV2B_LE32 && (x) <= M_NRV2B_LE16)
Definition at line 610 of file conf.h.
M_IS_NRV2D
#define M_IS_NRV2D (x) ((x) >= M_NRV2D_LE32 && (x) <= M_NRV2D_LE16)
Definition at line 611 of file conf.h.
M_IS_NRV2E
#define M_IS_NRV2E (x) ((x) >= M_NRV2E_LE32 && (x) <= M_NRV2E_LE16)
Definition at line 612 of file conf.h.
M_IS_ZSTD
#define M_IS_ZSTD (x) ((x) == M_ZSTD)
Definition at line 616 of file conf.h.
M_LZMA
#define M_LZMA 14
Definition at line 599 of file conf.h.
M_NONE
#define M_NONE (-3)
Definition at line 606 of file conf.h.
M_NRV2B_8
#define M_NRV2B_8 3
Definition at line 588 of file conf.h.
M_NRV2B_LE16
#define M_NRV2B_LE16 4
Definition at line 589 of file conf.h.
M_NRV2B_LE32
#define M_NRV2B_LE32 2
Definition at line 587 of file conf.h.
M_NRV2D_8
#define M_NRV2D_8 6
Definition at line 591 of file conf.h.
M_NRV2D_LE16
#define M_NRV2D_LE16 7
Definition at line 592 of file conf.h.
M_NRV2D_LE32
#define M_NRV2D_LE32 5
Definition at line 590 of file conf.h.
M_NRV2E_8
#define M_NRV2E_8 9
Definition at line 594 of file conf.h.
M_NRV2E_LE16
#define M_NRV2E_LE16 10
Definition at line 595 of file conf.h.
M_NRV2E_LE32
#define M_NRV2E_LE32 8
Definition at line 593 of file conf.h.
M_SKIP
#define M_SKIP (-4)
Definition at line 607 of file conf.h.
M_ULTRA_BRUTE
#define M_ULTRA_BRUTE (-5)
Definition at line 608 of file conf.h.
M_ZSTD
#define M_ZSTD 16
Definition at line 601 of file conf.h.
may_throw
#define may_throw noexcept(false)
Definition at line 235 of file conf.h.
noinline
#define noinline __acc_noinline
Definition at line 216 of file conf.h.
noreturn
#define noreturn noinline
Definition at line 225 of file conf.h.
NULL_cconf
#define NULL_cconf ((const upx_compress_config_t *) nullptr)
Definition at line 720 of file conf.h.
O_BINARY
#define O_BINARY 0
Definition at line 338 of file conf.h.
off_t
#define off_t upx_off_t
Definition at line 206 of file conf.h.
outp
#define outp upx_renamed_outp
Definition at line 329 of file conf.h.
packed_struct
#define packed_struct (s) struct alignas(1) s
Definition at line 409 of file conf.h.
STDERR_FILENO
#define STDERR_FILENO (fileno(stderr))
Definition at line 264 of file conf.h.
STDIN_FILENO
#define STDIN_FILENO (fileno(stdin))
Definition at line 258 of file conf.h.
STDOUT_FILENO
#define STDOUT_FILENO (fileno(stdout))
Definition at line 261 of file conf.h.
TABLESIZE
#define TABLESIZE (table) ((sizeof(table) / sizeof((table)[0])))
Definition at line 434 of file conf.h.
ucl_compress_config_t
#define ucl_compress_config_t REAL_ucl_compress_config_t
Definition at line 635 of file conf.h.
unlikely
#define unlikely __acc_unlikely
Definition at line 229 of file conf.h.
UNUSED
#define UNUSED (var) ACC_UNUSED(var)
Definition at line 239 of file conf.h.
upx_alignas_max
#define upx_alignas_max alignas(std::max_align_t)
Definition at line 143 of file conf.h.
upx_byte
#define upx_byte byte
Definition at line 185 of file conf.h.
upx_bytep
#define upx_bytep byte *
Definition at line 186 of file conf.h.
UPX_E_EOF_NOT_FOUND
#define UPX_E_EOF_NOT_FOUND (-7)
Definition at line 520 of file conf.h.
UPX_E_ERROR
#define UPX_E_ERROR (-1)
Definition at line 514 of file conf.h.
UPX_E_INPUT_NOT_CONSUMED
#define UPX_E_INPUT_NOT_CONSUMED (-8)
Definition at line 521 of file conf.h.
UPX_E_INPUT_OVERRUN
#define UPX_E_INPUT_OVERRUN (-4)
Definition at line 517 of file conf.h.
UPX_E_INVALID_ARGUMENT
#define UPX_E_INVALID_ARGUMENT (-10)
Definition at line 523 of file conf.h.
UPX_E_LOOKBEHIND_OVERRUN
#define UPX_E_LOOKBEHIND_OVERRUN (-6)
Definition at line 519 of file conf.h.
UPX_E_NOT_COMPRESSIBLE
#define UPX_E_NOT_COMPRESSIBLE (-3)
Definition at line 516 of file conf.h.
UPX_E_NOT_YET_IMPLEMENTED
#define UPX_E_NOT_YET_IMPLEMENTED (-9)
Definition at line 522 of file conf.h.
UPX_E_OK
#define UPX_E_OK (0)
Definition at line 513 of file conf.h.
UPX_E_OUT_OF_MEMORY
#define UPX_E_OUT_OF_MEMORY (-2)
Definition at line 515 of file conf.h.
UPX_E_OUTPUT_OVERRUN
#define UPX_E_OUTPUT_OVERRUN (-5)
Definition at line 518 of file conf.h.
UPX_F_ATARI_TOS
#define UPX_F_ATARI_TOS 129
Definition at line 571 of file conf.h.
UPX_F_BSD_ELF_i386
#define UPX_F_BSD_ELF_i386 25
Definition at line 550 of file conf.h.
UPX_F_BSD_i386
#define UPX_F_BSD_i386 24
Definition at line 549 of file conf.h.
UPX_F_BSD_SH_i386
#define UPX_F_BSD_SH_i386 26
Definition at line 551 of file conf.h.
UPX_F_BVMLINUZ_i386
#define UPX_F_BVMLINUZ_i386 16
Definition at line 541 of file conf.h.
UPX_F_DJGPP2_COFF
#define UPX_F_DJGPP2_COFF 4
Definition at line 529 of file conf.h.
UPX_F_DOS_COM
#define UPX_F_DOS_COM 1
Definition at line 526 of file conf.h.
UPX_F_DOS_EXE
#define UPX_F_DOS_EXE 3
Definition at line 528 of file conf.h.
UPX_F_DOS_EXEH
#define UPX_F_DOS_EXEH 7
Definition at line 532 of file conf.h.
UPX_F_DOS_SYS
#define UPX_F_DOS_SYS 2
Definition at line 527 of file conf.h.
UPX_F_DYLIB_AMD64
#define UPX_F_DYLIB_AMD64 35
Definition at line 560 of file conf.h.
UPX_F_DYLIB_i386
#define UPX_F_DYLIB_i386 33
Definition at line 558 of file conf.h.
UPX_F_DYLIB_PPC32
#define UPX_F_DYLIB_PPC32 138
Definition at line 580 of file conf.h.
UPX_F_DYLIB_PPC64
#define UPX_F_DYLIB_PPC64 142
Definition at line 584 of file conf.h.
UPX_F_ELKS_8086
#define UPX_F_ELKS_8086 17
Definition at line 542 of file conf.h.
UPX_F_LINUX_ELF32_ARM
#define UPX_F_LINUX_ELF32_ARM 23
Definition at line 548 of file conf.h.
UPX_F_LINUX_ELF32_ARMEB
#define UPX_F_LINUX_ELF32_ARMEB 133
Definition at line 575 of file conf.h.
UPX_F_LINUX_ELF32_MIPS
#define UPX_F_LINUX_ELF32_MIPS 137
Definition at line 579 of file conf.h.
UPX_F_LINUX_ELF32_MIPSEL
#define UPX_F_LINUX_ELF32_MIPSEL 30
Definition at line 555 of file conf.h.
UPX_F_LINUX_ELF32_PPC32
#define UPX_F_LINUX_ELF32_PPC32 132
Definition at line 574 of file conf.h.
UPX_F_LINUX_ELF64_AMD64
#define UPX_F_LINUX_ELF64_AMD64 22
Definition at line 547 of file conf.h.
UPX_F_LINUX_ELF64_ARM64
#define UPX_F_LINUX_ELF64_ARM64 42
Definition at line 567 of file conf.h.
UPX_F_LINUX_ELF64_PPC64
#define UPX_F_LINUX_ELF64_PPC64 140
Definition at line 582 of file conf.h.
UPX_F_LINUX_ELF64_PPC64LE
#define UPX_F_LINUX_ELF64_PPC64LE 39
Definition at line 564 of file conf.h.
UPX_F_LINUX_ELF_i386
#define UPX_F_LINUX_ELF_i386 12
Definition at line 537 of file conf.h.
UPX_F_LINUX_ELFI_i386
#define UPX_F_LINUX_ELFI_i386 20
Definition at line 545 of file conf.h.
UPX_F_LINUX_i386
#define UPX_F_LINUX_i386 10
Definition at line 535 of file conf.h.
UPX_F_LINUX_SH_i386
#define UPX_F_LINUX_SH_i386 14
Definition at line 539 of file conf.h.
UPX_F_MACH_AMD64
#define UPX_F_MACH_AMD64 34
Definition at line 559 of file conf.h.
UPX_F_MACH_ARM
#define UPX_F_MACH_ARM 32
Definition at line 557 of file conf.h.
UPX_F_MACH_ARM64
#define UPX_F_MACH_ARM64 37
Definition at line 562 of file conf.h.
UPX_F_MACH_FAT
#define UPX_F_MACH_FAT 134
Definition at line 576 of file conf.h.
UPX_F_MACH_i386
#define UPX_F_MACH_i386 29
Definition at line 554 of file conf.h.
UPX_F_MACH_PPC32
#define UPX_F_MACH_PPC32 131
Definition at line 573 of file conf.h.
UPX_F_MACH_PPC64
#define UPX_F_MACH_PPC64 139
Definition at line 581 of file conf.h.
UPX_F_PS1_EXE
#define UPX_F_PS1_EXE 18
Definition at line 543 of file conf.h.
UPX_F_TMT_ADAM
#define UPX_F_TMT_ADAM 8
Definition at line 533 of file conf.h.
UPX_F_VMLINUX_AMD64
#define UPX_F_VMLINUX_AMD64 27
Definition at line 552 of file conf.h.
UPX_F_VMLINUX_ARM
#define UPX_F_VMLINUX_ARM 28
Definition at line 553 of file conf.h.
UPX_F_VMLINUX_ARMEB
#define UPX_F_VMLINUX_ARMEB 135
Definition at line 577 of file conf.h.
UPX_F_VMLINUX_i386
#define UPX_F_VMLINUX_i386 19
Definition at line 544 of file conf.h.
UPX_F_VMLINUX_PPC32
#define UPX_F_VMLINUX_PPC32 136
Definition at line 578 of file conf.h.
UPX_F_VMLINUX_PPC64
#define UPX_F_VMLINUX_PPC64 141
Definition at line 583 of file conf.h.
UPX_F_VMLINUX_PPC64LE
#define UPX_F_VMLINUX_PPC64LE 40
Definition at line 565 of file conf.h.
UPX_F_VMLINUZ_ARM
#define UPX_F_VMLINUZ_ARM 31
Definition at line 556 of file conf.h.
UPX_F_VMLINUZ_i386
#define UPX_F_VMLINUZ_i386 15
Definition at line 540 of file conf.h.
UPX_F_W32PE_I386
#define UPX_F_W32PE_I386 9
Definition at line 534 of file conf.h.
UPX_F_W64PE_AMD64
#define UPX_F_W64PE_AMD64 36
Definition at line 561 of file conf.h.
UPX_F_W64PE_ARM64
#define UPX_F_W64PE_ARM64 43
Definition at line 568 of file conf.h.
UPX_F_W64PE_ARM64EC
#define UPX_F_W64PE_ARM64EC 44
Definition at line 569 of file conf.h.
UPX_F_WATCOM_LE
#define UPX_F_WATCOM_LE 5
Definition at line 530 of file conf.h.
UPX_F_WINCE_ARM
#define UPX_F_WINCE_ARM 21
Definition at line 546 of file conf.h.
UPX_MAGIC2_LE32
#define UPX_MAGIC2_LE32 0xD5D0D8A1
Definition at line 510 of file conf.h.
UPX_MAGIC_LE32
#define UPX_MAGIC_LE32 0x21585055 /* "UPX!" */
Definition at line 509 of file conf.h.
UPX_MAX
#define UPX_MAX (a, b) (upx::max((a), (b)))
Definition at line 488 of file conf.h.
upx_memcmp_inline
#define upx_memcmp_inline memcmp
Definition at line 384 of file conf.h.
upx_memcpy_inline
#define upx_memcpy_inline memcpy
Definition at line 393 of file conf.h.
UPX_MIN
#define UPX_MIN (a, b) (upx::min((a), (b)))
Definition at line 489 of file conf.h.
upx_return_address
#define upx_return_address () nullptr
Definition at line 405 of file conf.h.
UPX_RSIZE_MAX
#define UPX_RSIZE_MAX UPX_RSIZE_MAX_MEM
Definition at line 155 of file conf.h.
UPX_RSIZE_MAX_MEM
#define UPX_RSIZE_MAX_MEM (768 * 1024 * 1024)
Definition at line 156 of file conf.h.
UPX_RSIZE_MAX_STR
#define UPX_RSIZE_MAX_STR (256 * 1024)
Definition at line 157 of file conf.h.
upx_std_atomic
#define upx_std_atomic (Type) Type
Definition at line 115 of file conf.h.
upx_std_once_flag
#define upx_std_once_flag upx_std_atomic(size_t)
Definition at line 116 of file conf.h.
upx_thread_local
#define upx_thread_local /*empty*/
Definition at line 114 of file conf.h.
usizeof
#define usizeof (expr) (upx::UnsignedSizeOf<sizeof(expr)>::value)
Definition at line 484 of file conf.h.
VALGRIND_CHECK_MEM_IS_ADDRESSABLE
#define VALGRIND_CHECK_MEM_IS_ADDRESSABLE (addr, len) 0
Definition at line 349 of file conf.h.
VALGRIND_CHECK_MEM_IS_DEFINED
#define VALGRIND_CHECK_MEM_IS_DEFINED (addr, len) 0
Definition at line 352 of file conf.h.
VALGRIND_MAKE_MEM_DEFINED
#define VALGRIND_MAKE_MEM_DEFINED (addr, len) 0
Definition at line 355 of file conf.h.
VALGRIND_MAKE_MEM_NOACCESS
#define VALGRIND_MAKE_MEM_NOACCESS (addr, len) 0
Definition at line 358 of file conf.h.
VALGRIND_MAKE_MEM_UNDEFINED
#define VALGRIND_MAKE_MEM_UNDEFINED (addr, len) 0
Definition at line 361 of file conf.h.
very_likely
#define very_likely __acc_very_likely
Definition at line 230 of file conf.h.
very_unlikely
#define very_unlikely __acc_very_unlikely
Definition at line 231 of file conf.h.
WITH_LZMA
#define WITH_LZMA 1
compression - setup and callback_t
Definition at line 629 of file conf.h.
WITH_UCL
#define WITH_UCL 1
Definition at line 630 of file conf.h.
WITH_ZLIB
#define WITH_ZLIB 1
Definition at line 632 of file conf.h.
Typedef Documentation
byte
typedef unsigned char byte
Definition at line 184 of file conf.h.
Linker
typedef ElfLinker Linker
Definition at line 794 of file conf.h.
uchar
typedef unsigned char uchar
Definition at line 187 of file conf.h.
upx_int16_t
typedef acc_int16_t upx_int16_t
Definition at line 162 of file conf.h.
upx_int32_t
typedef acc_int32_t upx_int32_t
Definition at line 164 of file conf.h.
upx_int64_t
typedef acc_int64_t upx_int64_t
Definition at line 166 of file conf.h.
upx_int8_t
typedef acc_int8_t upx_int8_t
Definition at line 160 of file conf.h.
upx_off_t
typedef long long upx_off_t
Definition at line 199 of file conf.h.
upx_progress_func_t
typedef void(__acc_cdecl * upx_progress_func_t) (upx_callback_t *, unsigned, unsigned)
Definition at line 643 of file conf.h.
upx_ptraddr_t
typedef upx_uintptr_t upx_ptraddr_t
Definition at line 176 of file conf.h.
upx_rsize_t
typedef size_t upx_rsize_t
core
Definition at line 154 of file conf.h.
upx_sptraddr_t
typedef std::make_signed_t<upx_ptraddr_t> upx_sptraddr_t
Definition at line 178 of file conf.h.
upx_ssize_t
typedef std::make_signed_t<size_t> upx_ssize_t
Definition at line 180 of file conf.h.
upx_uint16_t
typedef acc_uint16_t upx_uint16_t
Definition at line 163 of file conf.h.
upx_uint32_t
typedef acc_uint32_t upx_uint32_t
Definition at line 165 of file conf.h.
upx_uint64_t
typedef acc_uint64_t upx_uint64_t
Definition at line 167 of file conf.h.
upx_uint8_t
typedef acc_uint8_t upx_uint8_t
Definition at line 161 of file conf.h.
upx_uintptr_t
typedef acc_uintptr_t upx_uintptr_t
Definition at line 172 of file conf.h.
upx_uptrdiff_t
typedef std::make_unsigned_t<ptrdiff_t> upx_uptrdiff_t
Definition at line 179 of file conf.h.
Function Documentation
assertFailed()
noreturn void assertFailed (const char * expr, const char * file, int line, const char * func) noexcept
util
Definition at line 184 of file except.cpp.
{
    fflush(stdout);
    fprintf(stderr, "Assertion failed: %s (%s: %s: %d)\n", expr, file, func, line);
    std::terminate();
}
do_files()
int do_files (int i, int argc, char * argv[])
Definition at line 409 of file work.cpp.
{
    upx_compiler_sanity_check();
    if (opt->verbose >= 1) {
        show_header();
        UiPacker::uiHeader();
    }
    for (; i < argc; i++) {
        infoHeader();
        const char *const iname = argv[i];
        char oname[ACC_FN_PATH_MAX + 1];
        oname[0] = 0;
        try {
            do_one_file(iname, oname);
        } catch (const Exception &e) {
            unlink_ofile(oname);
            if (opt->verbose >= 1 || (opt->verbose >= 0 && !e.isWarning()))
                printErr(iname, e);
            main_set_exit_code(e.isWarning() ? EXIT_WARN : EXIT_ERROR);
            // this is not fatal, continue processing more files
        } catch (const Error &e) {
            unlink_ofile(oname);
            printErr(iname, e);
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (std::bad_alloc *e) {
            unlink_ofile(oname);
            printErr(iname, "out of memory");
            UNUSED(e);
            // delete e;
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (const std::bad_alloc &) {
            unlink_ofile(oname);
            printErr(iname, "out of memory");
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (std::exception *e) {
            unlink_ofile(oname);
            printUnhandledException(iname, e);
            // delete e;
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (const std::exception &e) {
            unlink_ofile(oname);
            printUnhandledException(iname, &e);
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (...) {
            unlink_ofile(oname);
            printUnhandledException(iname, nullptr);
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        }
    }
    if (opt->cmd == CMD_COMPRESS)
        UiPacker::uiPackTotal();
    else if (opt->cmd == CMD_DECOMPRESS)
        UiPacker::uiUnpackTotal();
    else if (opt->cmd == CMD_LIST)
        UiPacker::uiListTotal();
    else if (opt->cmd == CMD_TEST)
        UiPacker::uiTestTotal();
    else if (opt->cmd == CMD_FILEINFO)
        UiPacker::uiFileInfoTotal();
    return 0;
}
References CMD_COMPRESS, CMD_DECOMPRESS, CMD_FILEINFO, CMD_LIST, CMD_TEST, do_one_file(), EXIT_ERROR, EXIT_WARN, infoHeader(), Throwable::isWarning(), main_set_exit_code(), opt, printErr(), printUnhandledException(), show_header(), UiPacker::uiFileInfoTotal(), UiPacker::uiHeader(), UiPacker::uiListTotal(), UiPacker::uiPackTotal(), UiPacker::uiTestTotal(), UiPacker::uiUnpackTotal(), unlink_ofile(), UNUSED, and upx_compiler_sanity_check().
Referenced by upx_main().
do_one_file()
void do_one_file (const char * iname, char * oname)
process one file
Definition at line 207 of file work.cpp.
{
    oname[0] = 0; // make empty
    // check iname stat
    XStat xst = {};
    struct stat &st = xst.st;
#if HAVE_LSTAT
    int rr = lstat(iname, &st);
#else
    int rr = stat(iname, &st);
#endif
    if (rr != 0) {
        if (errno == ENOENT)
            throw FileNotFoundException(iname, errno);
        else
            throwIOException(iname, errno);
    }
#if HAVE_LSTAT
    if (S_ISLNK(st.st_mode))
        throwIOException("is a symlink -- skipped");
#endif
    if (S_ISDIR(st.st_mode))
        throwIOException("is a directory -- skipped");
    if (!(S_ISREG(st.st_mode)))
        throwIOException("not a regular file -- skipped");
#if defined(__unix__)
    // no special bits may be set
    if ((st.st_mode & (S_ISUID | S_ISGID | S_ISVTX)) != 0)
        throwIOException("file has special permissions -- skipped");
#endif
    if (st.st_size <= 0)
        throwIOException("empty file -- skipped");
    if (st.st_size < 512)
        throwIOException("file is too small -- skipped");
    if (!mem_size_valid_bytes(st.st_size))
        throwIOException("file is too large -- skipped");
    if ((st.st_mode & S_IWUSR) == 0) {
        bool skip = true;
        if (opt->output_name)
            skip = false;
        else if (opt->to_stdout)
            skip = false;
        else if (opt->backup)
            skip = false;
        if (skip)
            throwIOException("file is write protected -- skipped");
    }
    // open input file
    InputFile fi;
    fi.sopen(iname, get_open_flags(RO_MUST_EXIST), SH_DENYWR);
    if (opt->preserve_timestamp) {
#if USE_SETFILETIME
        if (GetFileTime((HANDLE) _get_osfhandle(fi.getFd()), nullptr, &xst.ft_atime,
                        &xst.ft_mtime) == 0)
            throwIOException("cannot determine file timestamp");
#elif USE_FTIME
        if (getftime(fi.getFd(), &xst.ft_ftime) != 0)
            throwIOException("cannot determine file timestamp");
#endif
    }
    // open output file
    // NOTE: only use "preserve_link" if you really need it, e.g. it can fail
    //   with ETXTBSY and other unexpected errors; renaming files is much safer
    OutputFile fo;
    bool preserve_link = opt->preserve_link;
    bool copy_timestamp_only = false;
    if (opt->cmd == CMD_COMPRESS || opt->cmd == CMD_DECOMPRESS) {
        if (opt->to_stdout) {
            preserve_link = false; // not needed
            if (!fo.openStdout(1, opt->force ? true : false))
                throwIOException("data not written to a terminal; Use '-f' to force.");
        } else {
            char tname[ACC_FN_PATH_MAX + 1];
            if (opt->output_name) {
                strcpy(tname, opt->output_name);
                if ((opt->force_overwrite || opt->force >= 2) && !preserve_link)
                    (void) FileBase::unlink_noexcept(tname); // IGNORE_ERROR
            } else {
                if (st.st_nlink < 2)
                    preserve_link = false; // not needed
                if (!maketempname(tname, sizeof(tname), iname, ".upx"))
                    throwIOException("could not create a temporary file name");
            }
            int flags = get_open_flags(WO_MUST_CREATE); // don't overwrite files by default
            if (opt->output_name && preserve_link) {
                flags = get_open_flags(WO_CREATE_OR_TRUNCATE);
#if HAVE_LSTAT
                struct stat ost = {};
                int r = lstat(tname, &ost);
                if (r == 0 && S_ISREG(ost.st_mode)) {
                    preserve_link = ost.st_nlink >= 2;
                } else if (r == 0 && S_ISLNK(ost.st_mode)) {
                    // output_name is a symlink (valid or dangling)
                    (void) FileBase::unlink_noexcept(tname); // IGNORE_ERROR
                    preserve_link = false;                   // not needed
                } else {
                    preserve_link = false; // not needed
                }
#endif
                if (preserve_link) {
                    flags = get_open_flags(WO_MUST_EXIST_TRUNCATE);
                    copy_timestamp_only = true;
                }
            } else if (opt->force_overwrite || opt->force) {
                flags = get_open_flags(WO_CREATE_OR_TRUNCATE);
            }
            int shmode = SH_DENYWR;
#if (ACC_ARCH_M68K && ACC_OS_TOS && ACC_CC_GNUC) && defined(__MINT__)
            // TODO later: check current mintlib if this hack is still needed
            flags |= O_TRUNC;
            shmode = O_DENYRW;
#endif
            // cannot rely on open() because of umask
            // int omode = st.st_mode | 0600;
            int omode = opt->preserve_mode ? 0600 : 0666; // affected by umask; only for O_CREAT
            fo.sopen(tname, flags, shmode, omode);
            // open succeeded - now set oname[]
            strcpy(oname, tname);
        }
    }
    // handle command - actual work starts HERE
    PackMaster pm(&fi, opt);
    if (opt->cmd == CMD_COMPRESS)
        pm.pack(&fo);
    else if (opt->cmd == CMD_DECOMPRESS)
        pm.unpack(&fo);
    else if (opt->cmd == CMD_TEST)
        pm.test();
    else if (opt->cmd == CMD_LIST)
        pm.list();
    else if (opt->cmd == CMD_FILEINFO)
        pm.fileInfo();
    else
        throwInternalError("invalid command");
    // copy time stamp
    if (oname[0] && opt->preserve_timestamp && fo.isOpen())
        set_fd_timestamp(fo.getFd(), &xst);
    // close files
    fi.closex();
    fo.closex();
    // rename or copy files
    if (oname[0] && !opt->output_name) {
        // both iname and oname do exist; rename oname to iname
        if (opt->backup) {
            char bakname[ACC_FN_PATH_MAX + 1];
            if (!makebakname(bakname, sizeof(bakname), iname))
                throwIOException("could not create a backup file name");
            if (preserve_link) {
                copy_file_contents(iname, bakname, WO_MUST_CREATE, &xst);
                copy_file_attributes(&xst, bakname, true, true, true);
                const XStat *xstamp = opt->preserve_timestamp ? &xst : nullptr;
                copy_file_contents(oname, iname, WO_MUST_EXIST_TRUNCATE, xstamp);
                FileBase::unlink(oname);
                copy_timestamp_only = true;
            } else {
                FileBase::rename(iname, bakname);
                FileBase::rename(oname, iname);
            }
        } else if (preserve_link) {
            const XStat *xstamp = opt->preserve_timestamp ? &xst : nullptr;
            copy_file_contents(oname, iname, WO_MUST_EXIST_TRUNCATE, xstamp);
            FileBase::unlink(oname);
            copy_timestamp_only = true;
        } else {
            FileBase::unlink(iname);
            FileBase::rename(oname, iname);
        }
        // now iname is the new packed/unpacked file and oname does not exist any longer
    }
    // copy file attributes
    if (oname[0]) {
        oname[0] = 0; // done with oname
        const char *name = opt->output_name ? opt->output_name : iname;
        if (copy_timestamp_only)
            copy_file_attributes(&xst, name, false, false, opt->preserve_timestamp);
        else
            copy_file_attributes(&xst, name, opt->preserve_mode, opt->preserve_ownership,
                                 opt->preserve_timestamp);
    }
    UiPacker::uiConfirmUpdate();
}
References FileBase::closex(), CMD_COMPRESS, CMD_DECOMPRESS, CMD_FILEINFO, CMD_LIST, CMD_TEST, anonymous_namespace{work.cpp}::copy_file_attributes(), anonymous_namespace{work.cpp}::copy_file_contents(), ENOENT, PackMaster::fileInfo(), anonymous_namespace{work.cpp}::get_open_flags(), FileBase::getFd(), FileBase::isOpen(), PackMaster::list(), makebakname(), maketempname(), mem_size_valid_bytes(), OutputFile::openStdout(), opt, PackMaster::pack(), FileBase::rename(), anonymous_namespace{work.cpp}::RO_MUST_EXIST, anonymous_namespace{work.cpp}::set_fd_timestamp(), SH_DENYWR, InputFile::sopen(), OutputFile::sopen(), strcpy(), PackMaster::test(), throwInternalError(), throwIOException(), UiPacker::uiConfirmUpdate(), FileBase::unlink(), FileBase::unlink_noexcept(), PackMaster::unpack(), anonymous_namespace{work.cpp}::WO_CREATE_OR_TRUNCATE, anonymous_namespace{work.cpp}::WO_MUST_CREATE, and anonymous_namespace{work.cpp}::WO_MUST_EXIST_TRUNCATE.
Referenced by do_files().
info()
void void void void void info (const char * format, ...)
Referenced by PackExe::buildLoader(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), Packer::checkOverlay(), Packer::copyOverlay(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PeFile::handleStripRelocs(), Packer::handleStub(), PackDjgpp2::handleStub(), PeFile::pack0(), PeFile::processImports0(), PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), PeFile::processTls1(), and PeFile::tryremove().
infoHeader() [1/2]
void void void void void void infoHeader ()
Definition at line 176 of file msg.cpp.
{ info_header = 0; }
References info_header.
Referenced by do_files(), PeFile::pack0(), PeFile::readSectionHeaders(), and PeFile::unpack0().
infoHeader() [2/2]
void void void void infoHeader (const char * format, ...)
infoWarning()
void void void infoWarning (const char * format, ...)
Referenced by PeFile::ImportLinker::add_import(), PackPs1::buildLoader(), PackMachBase< TMachClass >::canPack(), PackMachFat::canPack(), PackPs1::canPack(), PackMachBase< TMachClass >::canUnpack(), PackPs1::checkFileHeader(), Packer::copyOverlay(), PackVmlinuxBase< TElfClass >::getElfSections(), PackPs1::pack(), PeFile::processExports(), PeFile::processImports0(), PeFile32::processRelocs(), PeFile64::processRelocs(), PeFile::processResources(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), and PackMachBase< TMachClass >::unpack().
infoWriting()
void infoWriting (const char * what, upx_int64_t size)
Definition at line 214 of file msg.cpp.
{
    if (opt->info_mode <= 0)
        return;
    info("Writing %s: %lld bytes", what, size);
}
References info(), opt, and size().
Referenced by PeFile::pack0().
main_get_envoptions()
void main_get_envoptions ()
Definition at line 1019 of file main.cpp.
{
#if defined(OPTIONS_VAR)
    constexpr int *N = nullptr;
    /* only some options are allowed in the environment variable */
    static const struct mfx_option longopts[] = {
        // commands
        {"best", 0x10, N, 900},        // compress best
        {"brute", 0x10, N, 901},       // compress best, brute force
        {"ultra-brute", 0x10, N, 902}, // compress best, ultra-brute force
        {"fast", 0x10, N, '1'},        // compress faster
        // options
        {"info", 0, N, 'i'},        // info mode
        {"no-progress", 0, N, 516}, // no progress bar
        {"quiet", 0, N, 'q'},       // quiet mode
        {"silent", 0, N, 'q'},      // quiet mode
        {"verbose", 0, N, 'v'},     // verbose mode
        // debug options
        {"disable-random-id", 0x90, N, 545}, // for internal debugging
        // backup options
        {"backup", 0x10, N, 'k'},
        {"keep", 0x10, N, 'k'},
        {"no-backup", 0x10, N, 541},
        // overlay options
        {"overlay", 0x31, N, 551}, // --overlay=
        {"skip-overlay", 0x10, N, 552},
        {"no-overlay", 0x10, N, 552}, // old name
        {"copy-overlay", 0x10, N, 553},
        {"strip-overlay", 0x10, N, 554},
        // CPU options
        {"cpu", 0x31, N, 560}, // --cpu=
        {"8086", 0x10, N, 561},
        {"386", 0x10, N, 563},
        {"486", 0x10, N, 564},
        // color options
        {"no-color", 0x10, N, 512},
        {"mono", 0x10, N, 513},
        {"color", 0x10, N, 514},
        // compression settings
        {"exact", 0x10, N, 525}, // user requires byte-identical decompression
        // compression method
        {"nrv2b", 0x10, N, 702},   // --nrv2b
        {"nrv2d", 0x10, N, 704},   // --nrv2d
        {"nrv2e", 0x10, N, 705},   // --nrv2e
        {"lzma", 0x10, N, 721},    // --lzma
        {"no-lzma", 0x10, N, 722}, // disable all_methods_use_lzma
        {"prefer-nrv", 0x10, N, 723},
        {"prefer-ucl", 0x10, N, 724},
        // win32/pe
        {"compress-exports", 2, N, 630},
        {"compress-icons", 2, N, 631},
        {"compress-resources", 2, N, 632},
        {"strip-loadconf", 0x12, N, 633}, // OBSOLETE - IGNORED
        {"strip-relocs", 0x12, N, 634},
        {"keep-resource", 0x31, N, 635},
        {nullptr, 0, nullptr, 0}};
    char *env, *p;
    const char *var;
    int i, optc, longind;
    int targc;
    const char **targv = nullptr;
    static const char sep[] = " \t";
    char shortopts[256];
    var = upx_getenv(OPTIONS_VAR);
    if (var == nullptr || !var[0])
        return;
    env = strdup(var);
    if (env == nullptr)
        return;
    /* count arguments */
    for (p = env, targc = 1;;) {
        while (*p && strchr(sep, *p))
            p++;
        if (*p == '\0')
            break;
        targc++;
        while (*p && !strchr(sep, *p))
            p++;
        if (*p == '\0')
            break;
        p++;
    }
    /* alloc temp argv */
    if (targc > 1)
        targv = (const char **) upx_calloc(targc + 1, sizeof(char *));
    if (targv == nullptr) {
        ::free(env);
        return;
    }
    /* fill temp argv */
    targv[0] = argv0;
    for (p = env, targc = 1;;) {
        while (*p && strchr(sep, *p))
            p++;
        if (*p == '\0')
            break;
        targv[targc++] = p;
        while (*p && !strchr(sep, *p))
            p++;
        if (*p == '\0')
            break;
        *p++ = '\0';
    }
    targv[targc] = nullptr;
    /* check that only options are in temp argv */
    for (i = 1; i < targc; i++)
        if (targv[i][0] != '-' || !targv[i][1] || strcmp(targv[i], "--") == 0)
            e_envopt(targv[i]);
    /* handle options */
    prepare_shortopts(shortopts, "123456789", longopts);
    acc_getopt_init(&mfx_getopt, 1, targc, const_cast<char **>(targv));
    mfx_getopt.progname = progname;
    mfx_getopt.opterr = handle_opterr;
    while ((optc = acc_getopt(&mfx_getopt, shortopts, longopts, &longind)) >= 0) {
        if (do_option(optc, targv[mfx_optind - 1]) != 0)
            e_envopt(nullptr);
    }
    if (mfx_optind < targc)
        e_envopt(targv[mfx_optind]);
    /* clean up */
    ::free(targv); // NOLINT(bugprone-multi-level-implicit-pointer-conversion)
    ::free(env);
#endif /* defined(OPTIONS_VAR) */
}
References argv0, do_option(), e_envopt(), handle_opterr(), mfx_getopt, mfx_optind, mfx_option, N, OPTIONS_VAR, prepare_shortopts(), progname, strcmp(), upx_calloc(), and upx_getenv().
Referenced by upx_main().
main_get_options()
int main_get_options (int argc, char ** argv)
Definition at line 815 of file main.cpp.
{
    constexpr int *N = nullptr;
    static const struct mfx_option longopts[] = {
        // commands
        {"best", 0x10, N, 900},        // compress best
        {"brute", 0x10, N, 901},       // compress best, brute force
        {"ultra-brute", 0x10, N, 902}, // compress best, ultra-brute force
        {"decompress", 0, N, 'd'},     // decompress
        {"fast", 0x10, N, '1'},        // compress faster
        {"fileinfo", 0x10, N, 909},    // display info about file
        {"file-info", 0x10, N, 909},   // display info about file
        {"help", 0, N, 'h' + 256},     // give help
        {"license", 0, N, 'L'},        // display software license
        {"list", 0, N, 'l'},           // list compressed exe
        {"sysinfo", 0x90, N, 910},     // display system info // undocumented and subject to change
        {"sys-info", 0x90, N, 910},    // display system info // undocumented and subject to change
        {"test", 0, N, 't'},           // test compressed file integrity
        {"uncompress", 0, N, 'd'},     // decompress
        {"version", 0, N, 'V' + 256},  // display version number
        // options
        {"force", 0, N, 'f'},              // force overwrite of output files
        {"force-compress", 0, N, 'f'},     //   and compression of suspicious files
        {"force-overwrite", 0x90, N, 529}, // force overwrite of output files
        {"link", 0x90, N, 530},            // preserve hard link
        {"info", 0, N, 'i'},               // info mode
        {"no-env", 0x10, N, 519},          // no environment var
        {"no-link", 0x90, N, 531},         // do not preserve hard link [default]
        {"no-mode", 0x10, N, 526},         // do not preserve mode (permissions)
        {"no-owner", 0x10, N, 527},        // do not preserve ownership
        {"no-progress", 0, N, 516},        // no progress bar
        {"no-time", 0x10, N, 528},         // do not preserve timestamp
        {"output", 0x21, N, 'o'},
        {"quiet", 0, N, 'q'},  // quiet mode
        {"silent", 0, N, 'q'}, // quiet mode
#if 0
        // FIXME: to_stdout doesn't work because of console code mess
        {"stdout",           0x10, N, 517},     // write output on standard output
        {"to-stdout",        0x10, N, 517},     // write output on standard output
#endif
        {"verbose", 0, N, 'v'}, // verbose mode
        // debug options
        {"debug", 0x10, N, 'D'},
        {"dump-stub-loader", 0x31, N, 544},        // for internal debugging
        {"fake-stub-version", 0x31, N, 542},       // for internal debugging
        {"fake-stub-year", 0x31, N, 543},          // for internal debugging
        {"disable-random-id", 0x90, N, 545},       // for internal debugging
        {"debug-use-random-method", 0x90, N, 546}, // for internal debugging / fuzz testing
        {"debug-use-random-filter", 0x90, N, 547}, // for internal debugging / fuzz testing
        // backup options
        {"backup", 0x10, N, 'k'},
        {"keep", 0x10, N, 'k'},
        {"no-backup", 0x10, N, 541},
        // overlay options
        {"overlay", 0x31, N, 551}, // --overlay=
        {"skip-overlay", 0x10, N, 552},
        {"no-overlay", 0x10, N, 552}, // old name
        {"copy-overlay", 0x10, N, 553},
        {"strip-overlay", 0x10, N, 554},
        // CPU options
        {"cpu", 0x31, N, 560}, // --cpu=
        {"8086", 0x10, N, 561},
        {"386", 0x10, N, 563},
        {"486", 0x10, N, 564},
        // color options
        {"no-color", 0x10, N, 512},
        {"mono", 0x10, N, 513},
        {"color", 0x10, N, 514},
        // compression method
        {"nrv2b", 0x10, N, 702},   // --nrv2b
        {"nrv2d", 0x10, N, 704},   // --nrv2d
        {"nrv2e", 0x10, N, 705},   // --nrv2e
        {"lzma", 0x10, N, 721},    // --lzma
        {"no-lzma", 0x10, N, 722}, // disable all_methods_use_lzma
        {"prefer-nrv", 0x10, N, 723},
        {"prefer-ucl", 0x10, N, 724},
        // compression settings
        {"all-filters", 0x10, N, 523},
        {"all-methods", 0x10, N, 524},
        {"exact", 0x10, N, 525},  // user requires byte-identical decompression
        {"filter", 0x31, N, 521}, // --filter=
        {"no-filter", 0x10, N, 522},
        {"small", 0x10, N, 520},
        // CRP - Compression Runtime Parameters (undocumented and subject to change)
        {"crp-nrv-cf", 0x31, N, 801},
        {"crp-nrv-sl", 0x31, N, 802},
        {"crp-nrv-hl", 0x31, N, 803},
        {"crp-nrv-pl", 0x31, N, 804},
        {"crp-nrv-mo", 0x31, N, 805},
        {"crp-nrv-mm", 0x31, N, 806},
        {"crp-nrv-ms", 0x31, N, 807},
        {"crp-ucl-cf", 0x31, N, 801},
        {"crp-ucl-sl", 0x31, N, 802},
        {"crp-ucl-hl", 0x31, N, 803},
        {"crp-ucl-pl", 0x31, N, 804},
        {"crp-ucl-mo", 0x31, N, 805},
        {"crp-ucl-mm", 0x31, N, 806},
        {"crp-ucl-ms", 0x31, N, 807},
        {"crp-lzma-pb", 0x31, N, 811},
        {"crp-lzma-lp", 0x31, N, 812},
        {"crp-lzma-lc", 0x31, N, 813},
        {"crp-lzma-ds", 0x31, N, 814},
        {"crp-lzma-fb", 0x31, N, 816},
        {"crp-zlib-ml", 0x31, N, 821},
        {"crp-zlib-wb", 0x31, N, 822},
        {"crp-zlib-st", 0x31, N, 823},
        // atari/tos
        {"split-segments", 0x90, N, 650},
        // darwin/macho
        {"force-macos", 0x90, N, 690}, // undocumented temporary option until we do fix macOS 13+
        // djgpp2/coff
        {"coff", 0x90, N, 610}, // produce COFF output
        // dos/exe
        //{"force-stub", 0x10, N, 600},
        {"no-reloc", 0x10, N, 601}, // no reloc. record into packer dos/exe
        // o_unix
        {"blocksize", 0x31, N, 660},     // --blocksize=
        {"force-execve", 0x90, N, 661},  // force linux/386 execve format
        {"is_ptinterp", 0x10, N, 663},   // linux/elf386 PT_INTERP program
        {"use_ptinterp", 0x10, N, 664},  // linux/elf386 PT_INTERP program
        {"make_ptinterp", 0x10, N, 665}, // linux/elf386 PT_INTERP program
        {"Linux", 0x10, N, 666},
        {"linux", 0x10, N, 666},
        {"FreeBSD", 0x10, N, 667},
        {"freebsd", 0x10, N, 667},
        {"NetBSD", 0x10, N, 668},
        {"netbsd", 0x10, N, 668},
        {"OpenBSD", 0x10, N, 669},
        {"openbsd", 0x10, N, 669},
        {"unmap-all-pages", 0x10, N, 674}, // linux /proc/self/exe vanishes
        {"preserve-build-id", 0, N, 675},
        {"android-shlib", 0, N, 676},
        {"force-pie", 0x90, N, 677},
        // ps1/exe
        {"boot-only", 0x90, N, 670},
        {"no-align", 0x90, N, 671},
        {"8-bit", 0x90, N, 672},
        {"8mib-ram", 0x90, N, 673},
        {"8mb-ram", 0x90, N, 673},
        // watcom/le
        {"le", 0x90, N, 620}, // produce LE output
        // win32/pe
        {"compress-exports", 2, N, 630},
        {"compress-icons", 2, N, 631},
        {"compress-resources", 2, N, 632},
        {"strip-loadconf", 0x12, N, 633}, // OBSOLETE - IGNORED
        {"strip-relocs", 0x12, N, 634},
        {"keep-resource", 0x31, N, 635},
#if !defined(DOCTEST_CONFIG_DISABLE) // accept and ignore some doctest --dt-XXX options
        // [doctest] Query flags - the program quits after them. Available:
        {"dt-c", 0x10, N, 999},
        {"dt-count", 0x10, N, 999},
        {"dt-h", 0x10, N, 999},
        {"dt-help", 0x10, N, 999},
        {"dt-lr", 0x10, N, 999},
        {"dt-list-reporters", 0x10, N, 999},
        {"dt-ltc", 0x10, N, 999},
        {"dt-list-test-cases", 0x10, N, 999},
        {"dt-lts", 0x10, N, 999},
        {"dt-list-test-suites", 0x10, N, 999},
        {"dt-v", 0x10, N, 999},
        {"dt-version", 0x10, N, 999},
        // [doctest] Bool options - can be used like flags and true is assumed. Available:
        {"dt-d", 0x12, N, 999},
        {"dt-duration", 0x12, N, 999},
        {"dt-e", 0x12, N, 999},
        {"dt-exit", 0x12, N, 999},
        {"dt-m", 0x12, N, 999},
        {"dt-minimal", 0x12, N, 999},
        {"dt-nt", 0x12, N, 999},
        {"dt-no-throw", 0x12, N, 999},
        {"dt-nr", 0x12, N, 999},
        {"dt-no-run", 0x12, N, 999},
        {"dt-s", 0x12, N, 999},
        {"dt-success", 0x12, N, 999},
#endif
        {nullptr, 0, nullptr, 0}
    };
    int optc, longind;
    char shortopts[256];
    prepare_shortopts(shortopts, "123456789hH?V", longopts);
    acc_getopt_init(&mfx_getopt, 1, argc, argv);
    mfx_getopt.progname = progname;
    mfx_getopt.opterr = handle_opterr;
    while ((optc = acc_getopt(&mfx_getopt, shortopts, longopts, &longind)) >= 0) {
        if (do_option(optc, argv[mfx_optind - 1]) != 0)
            e_usage();
    }
    return mfx_optind;
}
References do_option(), e_usage(), handle_opterr(), mfx_getopt, mfx_optind, mfx_option, N, prepare_shortopts(), and progname.
Referenced by test_options(), and upx_main().
main_set_exit_code()
bool main_set_exit_code (int ec)
Definition at line 109 of file main.cpp.
{ return set_eec(ec, &exit_code); }
References exit_code, and set_eec().
Referenced by do_files(), and e_exit().
mem_clear() [1/3]
template<class T > void mem_clear (T * object) inline noexcept
Definition at line 437 of file conf.h.
{
    static_assert(std::is_class_v<T>); // UPX convention
    static_assert(std::is_standard_layout_v<T>);
    static_assert(std::is_trivially_copyable_v<T>);
    constexpr size_t size = sizeof(*object);
    static_assert(size >= 1 && size <= UPX_RSIZE_MAX_MEM);
    memset((void *) object, 0, size);
}
References memset(), size(), and UPX_RSIZE_MAX_MEM.
Referenced by anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check_core(), PeFile::Export::Export(), PackExe::fillExeHeader(), LeFile::LeFile(), PeFile::pack0(), upx_callback_t::reset(), bzip2_compress_config_t::reset(), zlib_compress_config_t::reset(), zstd_compress_config_t::reset(), bzip2_compress_result_t::reset(), lzma_compress_result_t::reset(), ucl_compress_result_t::reset(), zlib_compress_result_t::reset(), zstd_compress_result_t::reset(), upx_compress_result_t::Debug::reset(), Options::reset(), PackTos::LinkerSymbols::reset(), PackHeader::reset(), anonymous_namespace{dt_cxxlib.cpp}::TestTriBool< T >::test(), TEST_CASE(), UiPacker::UiPacker(), PackExe::unpack(), and upx_lzma_decompress().
mem_clear() [2/3]
template<class T > void mem_clear (T(&) array[]) inline noexcept
mem_clear() [3/3]
template<class T , size_t N> void mem_clear (T(&) array[N]) inline noexcept
membuffer_get_size()
unsigned membuffer_get_size (MemBuffer & mb) noexcept
Definition at line 36 of file membuffer.cpp.
{ return mb.getSize(); }
membuffer_get_void_ptr()
void * membuffer_get_void_ptr (MemBuffer & mb) noexcept
Definition at line 35 of file membuffer.cpp.
{ return mb.getVoidPtr(); }
NO_fprintf()
void void NO_fprintf (FILE * , const char * , ...) inline noexcept
Definition at line 377 of file conf.h.
{}
Referenced by PackExe::pack(), PeFile::pack0(), PackHeader::putPackHeader(), Throwable::Throwable(), PeFile::tryremove(), Packer::unoptimizeReloc(), anonymous_namespace{help.cpp}::PackerNames::visit(), OutputFile::write(), xspan_check_range(), and Throwable::~Throwable().
NO_printf()
void void NO_printf (const char * , ...) inline noexcept
Definition at line 375 of file conf.h.
{}
Referenced by ElfLinker::addLoader(), ElfLinker::addSection(), ElfLinker::addSymbol(), MemBuffer::alloc(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), Packer::compress(), Packer::compressWithFilters(), PackVmlinuzI386::decompressKernel(), Filter::filter(), ElfLinker::init(), PeFile::Reloc::next(), optimize_relocs(), PackExe::pack(), PackCom::patchLoader(), PackSys::patchLoader(), prepare_result(), prepareFilters(), Packer::prepareMethods(), ElfLinker::preprocessRelocations(), ElfLinker::preprocessSections(), PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile64::processRelocs(), PackExe::readFileHeader(), ElfLinker::relocate(), Filter::scan(), Filter::unfilter(), PackExe::unpack(), upx_lzma_compress(), upx_lzma_decompress(), and Filter::verifyUnfilter().
printClearLine()
void printClearLine (FILE * f = nullptr) noexcept
Definition at line 40 of file msg.cpp.
{
    static char clear_line_msg[1 + 79 + 1 + 1];
    if (!clear_line_msg[0]) {
        char *msg = clear_line_msg;
        msg[0] = '\r';
        memset(msg + 1, ' ', 79);
        msg[80] = '\r';
        msg[81] = 0;
    }
    fflush(stdout);
    fflush(stderr);
    if (f == nullptr)
        f = stdout;
    con_fprintf(f, "%s", clear_line_msg);
    fflush(f);
    printSetNl(0);
}
References con_fprintf, memset(), and printSetNl().
Referenced by UiPacker::endCallback(), info_print(), pr_error(), and UiPacker::uiPackEnd().
printErr() [1/2]
void printErr (const char * iname, const char * format, ...) noexcept
printErr() [2/2]
void printErr (const char * iname, const Throwable & e) noexcept
Definition at line 101 of file msg.cpp.
{
    char buf[1024];
    size_t l;
    upx_safe_snprintf(buf, sizeof(buf), "%s", prettyExceptionName(typeid(e).name()));
    l = strlen(buf);
    if (l < sizeof(buf) && e.getMsg())
        upx_safe_snprintf(buf + l, sizeof(buf) - l, ": %s", e.getMsg());
    l = strlen(buf);
    if (l < sizeof(buf) && e.getErrno()) {
        upx_safe_snprintf(buf + l, sizeof(buf) - l, ": %s", strerror(e.getErrno()));
#if 1
        // some compilers (e.g. Borland C++) put a trailing '\n'
        // into the strerror() result
        l = strlen(buf);
        while (l-- > 0 && (buf[l] == '\n' || buf[l] == ' '))
            buf[l] = 0;
#endif
    }
    pr_error(iname, buf, e.isWarning());
}
References buf, pr_error(), prettyExceptionName(), strlen, and upx_safe_snprintf().
Referenced by MemBuffer::dealloc(), do_files(), main(), and printUnhandledException().
printSetNl()
void printSetNl (int need_nl) noexcept
Definition at line 38 of file msg.cpp.
{ pr_need_nl = need_nl; }
References pr_need_nl.
Referenced by UiPacker::doCallback(), UiPacker::endCallback(), info_print(), pr_error(), printClearLine(), UiPacker::startCallback(), UiPacker::uiList(), UiPacker::uiListTotal(), UiPacker::uiPackEnd(), UiPacker::uiTestEnd(), UiPacker::uiTestStart(), and UiPacker::uiUnpackEnd().
printUnhandledException()
void printUnhandledException (const char * iname, const std::exception * e) noexcept
Definition at line 145 of file msg.cpp.
{
    if (e != nullptr)
        printErr(iname, "unhandled exception: %s\n", prettyExceptionName(e->what()));
    else
        printErr(iname, "internal error: unhandled exception!\n");
    if (opt->cmd != CMD_COMPRESS) {
        printErr(iname, "  this file has possibly been modified/hacked; take care!\n");
    }
}
References CMD_COMPRESS, opt, prettyExceptionName(), and printErr().
Referenced by do_files().
printWarn()
void void printWarn (const char * iname, const char * format, ...) noexcept
Referenced by PackLinuxI386sh::getShellName().
show_header()
void show_header ()
Definition at line 52 of file help.cpp.
                       {
    FILE *f = con_term;
    int fg;
    static bool header_done;
    if (header_done)
        return;
    header_done = true;
    fg = con_fg(f, FG_GREEN);
    // clang-format off
    con_fprintf(f,
                "                       Ultimate Packer for eXecutables\n"
                "                          Copyright (C) 1996 - " UPX_VERSION_YEAR "\n"
#if defined(UPX_VERSION_GITREV)
                "UPX git-%6.6s%c"
#else
                "UPX %-11s"
#endif
                " Markus Oberhumer, Laszlo Molnar & John Reiser  %14s\n\n",
#if defined(UPX_VERSION_GITREV)
                gitrev,
                (sizeof(gitrev)-1 > 6 && gitrev[sizeof(gitrev)-2] == '+') ? '+' : ' ',
#else
                UPX_VERSION_STRING,
#endif
                UPX_VERSION_DATE);
    // clang-format on
    fg = con_fg(f, fg);
    UNUSED(fg);
}
References con_fg, con_fprintf, con_term, gitrev, UNUSED, UPX_VERSION_DATE, UPX_VERSION_STRING, and UPX_VERSION_YEAR.
Referenced by do_files(), show_help(), show_license(), and show_sysinfo().
show_help()
void show_help (int verbose)
help
Definition at line 207 of file help.cpp.
{
    FILE *f = con_term;
    int fg;
    show_header();
    show_usage();
    // clang-format off
    fg = con_fg(f, FG_YELLOW);
    con_fprintf(f, "\nCommands:\n");
    fg = con_fg(f, fg);
    con_fprintf(f,
                "  -1     compress faster                   -9    compress better\n"
                "%s"
                "  -d     decompress                        -l    list compressed file\n"
                "  -t     test compressed file              -V    display version number\n"
                "  -h     give %s help                    -L    display software license\n%s",
                verbose == 0 ? "" : "  --best compress best (can be slow for big files)\n",
                verbose == 0 ? "more" : "this", verbose == 0 ? "" : "\n");
    fg = con_fg(f, FG_YELLOW);
    con_fprintf(f, "Options:\n");
    fg = con_fg(f, fg);
    con_fprintf(f,
                "  -q     be quiet                          -v    be verbose\n"
                "  -oFILE write output to 'FILE'\n"
                "  -f     force compression of suspicious files\n"
                "%s%s"
                , (verbose == 0) ? "  -k     keep backup files\n" : ""
#if 1
                , (verbose > 0) ? "  --no-color, --mono, --color, --no-progress   change look\n" : ""
#else
                , ""
#endif
                );
    if (verbose > 0)
    {
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "\nCompression tuning options:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --lzma              try LZMA [slower but tighter than NRV]\n"
                    "  --brute             try all available compression methods & filters [slow]\n"
                    "  --ultra-brute       try even more compression variants [very slow]\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Backup options:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  -k, --backup        keep backup files\n"
                    "  --no-backup         no backup files [default]\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Overlay options:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --overlay=copy      copy any extra data attached to the file [default]\n"
                    "  --overlay=strip     strip any extra data attached to the file [DANGEROUS]\n"
                    "  --overlay=skip      don't compress a file with an overlay\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "File system options:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --force-overwrite   force overwrite of output files\n"
#if defined(__unix__)
                    "  --link              preserve hard links (Unix only) [USE WITH CARE]\n"
                    "  --no-link           do not preserve hard links but rename files [default]\n"
#endif
                    "  --no-mode           do not preserve file mode (aka permissions)\n"
                    "  --no-owner          do not preserve file ownership\n"
                    "  --no-time           do not preserve file timestamp\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for djgpp2/coff:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --coff              produce COFF output [default: EXE]\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for dos/com:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --8086              make compressed com work on any 8086\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for dos/exe:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --8086              make compressed exe work on any 8086\n"
                    "  --no-reloc          put no relocations in to the exe header\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for dos/sys:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --8086              make compressed sys work on any 8086\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for ps1/exe:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --8-bit             uses 8 bit size compression [default: 32 bit]\n"
                    "  --8mib-ram          8 megabyte memory limit [default: 2 MiB]\n"
                    "  --boot-only         disables client/host transfer compatibility\n"
                    "  --no-align          don't align to 2048 bytes [enables: --console-run]\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for watcom/le:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --le                produce LE output [default: EXE]\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for win32/pe, win64/pe & rtm32/pe:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --compress-exports=0    do not compress the export section\n"
                    "  --compress-exports=1    compress the export section [default]\n"
                    "  --compress-icons=0      do not compress any icons\n"
                    "  --compress-icons=1      compress all but the first icon\n"
                    "  --compress-icons=2      compress all but the first icon directory [default]\n"
                    "  --compress-icons=3      compress all icons\n"
                    "  --compress-resources=0  do not compress any resources at all\n"
                    "  --keep-resource=list    do not compress resources specified by list\n"
                    "  --strip-relocs=0        do not strip relocations\n"
                    "  --strip-relocs=1        strip relocations [default]\n"
                    "\n");
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "Options for linux/elf:\n");
        fg = con_fg(f, fg);
        con_fprintf(f,
                    "  --preserve-build-id     copy .gnu.note.build-id to compressed output\n"
                    "\n");
    }
    // clang-format on
    con_fprintf(f, "file..   executables to (de)compress\n");
    if (verbose > 0) {
        fg = con_fg(f, FG_YELLOW);
        con_fprintf(f, "\nThis version supports:\n");
        fg = con_fg(f, fg);
        list_all_packers(f, verbose);
    } else {
        con_fprintf(f, "\nType '%s --help' for more detailed help.\n", progname);
    }
    con_fprintf(f, "\nUPX comes with ABSOLUTELY NO WARRANTY; "
                   "for details visit https://upx.github.io\n");
#if DEBUG || TESTING
    fg = con_fg(f, FG_RED);
    con_fprintf(f, "\nWARNING: this version is compiled with"
#if DEBUG
                   " -DDEBUG"
#endif
#if TESTING
                   " -DTESTING"
#endif
                   "\n");
    fg = con_fg(f, fg);
#endif
    UNUSED(fg);
}
References __unix__, con_fg, con_fprintf, con_term, list_all_packers(), progname, show_header(), show_usage(), and UNUSED.
Referenced by do_option(), e_help(), and upx_main().
show_license()
void show_license ()
license
Definition at line 380 of file help.cpp.
{
    FILE *f = con_term;
    show_header();
    // clang-format off
    con_fprintf(f,
        "   This program may be used freely, and you are welcome to\n"
        "   redistribute it under certain conditions.\n"
        "\n"
        "   This program is distributed in the hope that it will be useful,\n"
        "   but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
        "   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
        "   UPX License Agreements for more details.\n"
        "\n"
        "   You should have received a copy of the UPX License Agreements\n"
        "   along with this program; see the files COPYING and LICENSE.\n"
        "   If not, visit one of the following pages:\n"
        "\n"
    );
    int fg = con_fg(f, FG_CYAN);
    con_fprintf(f,
        "        https://upx.github.io\n"
        "        https://www.oberhumer.com/opensource/upx/\n"
    );
    (void) con_fg(f, FG_ORANGE);
    con_fprintf(f,
        "\n"
        "   Markus F.X.J. Oberhumer              Laszlo Molnar\n"
        "   <markus@oberhumer.com>               <ezerotven+github@gmail.com>\n"
    );
    // clang-format on
    fg = con_fg(f, fg);
    UNUSED(fg);
}
References con_fg, con_fprintf, con_term, show_header(), and UNUSED.
Referenced by upx_main().
show_sysinfo()
void show_sysinfo (const char * options_var)
sysinfo undocumented and subject to change
Definition at line 500 of file help.cpp.
{
    FILE *f = con_term;
    show_header();
    if (opt->verbose >= 1) {
        con_fprintf(f, "UPX version: ");
        fflush(f);
        show_version(true);
        con_fprintf(f, "UPX version internal: 0x%06x %s\n", UPX_VERSION_HEX, UPX_VERSION_STRING);
    }
    fflush(stdout);
    // Compilation Flags
    {
        size_t cf_count = 0;
        auto cf_print = [f, &cf_count](const char *name, const char *fmt, upx_int64_t v,
                                       int need_verbose = 2) noexcept {
            if (opt->verbose < need_verbose)
                return;
            if (cf_count++ == 0)
                con_fprintf(f, "\nCompilation flags:\n");
            con_fprintf(f, "  %s = ", name);
            con_fprintf(f, fmt, v);
            con_fprintf(f, "\n");
        };
        // language
        cf_print("__cplusplus", "%lld", __cplusplus + 0, 3);
#if defined(_MSVC_LANG)
        cf_print("_MSVC_LANG", "%lld", _MSVC_LANG + 0, 3);
#endif
#if defined(upx_is_constant_evaluated)
        cf_print("upx_is_constant_evaluated", "%lld", 1, 3);
#endif
        // compiler
#if defined(ACC_CC_CLANG)
        cf_print("ACC_CC_CLANG", "0x%06llx", ACC_CC_CLANG + 0, 3);
#endif
#if defined(ACC_CC_GNUC)
        cf_print("ACC_CC_GNUC", "0x%06llx", ACC_CC_GNUC + 0, 3);
#endif
#if defined(ACC_CC_MSC)
        cf_print("ACC_CC_MSC", "%lld", ACC_CC_MSC + 0, 3);
#endif
#if defined(__clang__)
        cf_print("__clang__", "%lld", __clang__ + 0);
#endif
#if defined(__clang_major__)
        cf_print("__clang_major__", "%lld", __clang_major__ + 0);
#endif
#if defined(__clang_minor__)
        cf_print("__clang_minor__", "%lld", __clang_minor__ + 0, 3);
#endif
#if defined(__clang_patchlevel__)
        cf_print("__clang_patchlevel__", "%lld", __clang_patchlevel__ + 0, 3);
#endif
#if defined(__GNUC__)
        cf_print("__GNUC__", "%lld", __GNUC__ + 0);
#endif
#if defined(__GNUC_MINOR__)
        cf_print("__GNUC_MINOR__", "%lld", __GNUC_MINOR__ + 0, 3);
#endif
#if defined(__GNUC_PATCHLEVEL__)
        cf_print("__GNUC_PATCHLEVEL__", "%lld", __GNUC_PATCHLEVEL__ + 0, 3);
#endif
#if defined(_MSC_VER)
        cf_print("_MSC_VER", "%lld", _MSC_VER + 0);
#endif
#if defined(_MSC_FULL_VER)
        cf_print("_MSC_FULL_VER", "%lld", _MSC_FULL_VER + 0);
#endif
        // architecture
#if defined(__CHERI__)
        cf_print("__CHERI__", "%lld", __CHERI__ + 0, 3);
#endif
#if defined(__CHERI_PURE_CAPABILITY__)
        cf_print("__CHERI_PURE_CAPABILITY__", "%lld", __CHERI_PURE_CAPABILITY__ + 0, 3);
#endif
#if defined(__mips_hard_float)
        cf_print("__mips_hard_float", "%lld", __mips_hard_float + 0);
#endif
#if defined(__mips_soft_float)
        cf_print("__mips_soft_float", "%lld", __mips_soft_float + 0);
#endif
#if defined(__wasm__)
        cf_print("__wasm__", "%lld", __wasm__ + 0);
#endif
#if defined(__wasm32__)
        cf_print("__wasm32__", "%lld", __wasm32__ + 0);
#endif
#if defined(__wasm64__)
        cf_print("__wasm64__", "%lld", __wasm64__ + 0);
#endif
        // OS and libc
#if defined(WINVER)
        cf_print("WINVER", "0x%04llx", WINVER + 0);
#endif
#if defined(_WIN32_WINNT)
        cf_print("_WIN32_WINNT", "0x%04llx", _WIN32_WINNT + 0);
        if (initial_win32_winnt != 0 && initial_win32_winnt != _WIN32_WINNT + 0)
            cf_print("INITIAL_WIN32_WINNT", "0x%04llx", initial_win32_winnt);
#endif
#if defined(__MSVCRT_VERSION__)
        cf_print("__MSVCRT_VERSION__", "0x%04llx", __MSVCRT_VERSION__ + 0);
#endif
#if defined(__MINGW64_VERSION_MAJOR)
        cf_print("__MINGW64_VERSION_MAJOR", "%lld", __MINGW64_VERSION_MAJOR + 0);
#endif
#if defined(__USE_MINGW_ANSI_STDIO)
        cf_print("__USE_MINGW_ANSI_STDIO", "%lld", __USE_MINGW_ANSI_STDIO + 0, 3);
#endif
#if defined(__ELF__)
        cf_print("__ELF__", "%lld", __ELF__ + 0, 3);
#endif
#if defined(__GLIBC__)
        cf_print("__GLIBC__", "%lld", __GLIBC__ + 0);
#endif
#if defined(__GLIBC_MINOR__)
        cf_print("__GLIBC_MINOR__", "%lld", __GLIBC_MINOR__ + 0);
#endif
#if defined(__wasi__)
        cf_print("__wasi__", "%lld", __wasi__ + 0);
#endif
        // misc compilation options
#if defined(__PIC__)
        cf_print("__PIC__", "%lld", __PIC__ + 0, 3);
#elif defined(__pic__)
        cf_print("__pic__", "%lld", __pic__ + 0, 3);
#endif
#if defined(__PIE__)
        cf_print("__PIE__", "%lld", __PIE__ + 0, 3);
#elif defined(__pie__)
        cf_print("__pie__", "%lld", __pie__ + 0, 3);
#endif
#if defined(__SIZEOF_INT128__)
        cf_print("__SIZEOF_INT128__", "%lld", __SIZEOF_INT128__ + 0, 3);
#endif
#if defined(__SIZEOF_LONG_LONG__) && (__SIZEOF_LONG_LONG__ + 0 > 8)
        cf_print("__SIZEOF_LONG_LONG__", "%lld", __SIZEOF_LONG_LONG__ + 0, 3);
#endif
#if defined(__SIZEOF_POINTER__) && (__SIZEOF_POINTER__ + 0 > 8)
        cf_print("__SIZEOF_POINTER__", "%lld", __SIZEOF_POINTER__ + 0, 3);
#endif
#if defined(UPX_CONFIG_DISABLE_WSTRICT)
        cf_print("UPX_CONFIG_DISABLE_WSTRICT", "%lld", UPX_CONFIG_DISABLE_WSTRICT + 0, 3);
#endif
#if defined(UPX_CONFIG_DISABLE_WERROR)
        cf_print("UPX_CONFIG_DISABLE_WERROR", "%lld", UPX_CONFIG_DISABLE_WERROR + 0, 3);
#endif
#if defined(WITH_THREADS)
        cf_print("WITH_THREADS", "%lld", WITH_THREADS + 0);
#endif
        UNUSED(cf_count);
        UNUSED(cf_print);
        UNUSED(initial_win32_winnt);
    }
    // run-time settings
#if defined(HAVE_LOCALTIME) && defined(HAVE_GMTIME)
    {
        auto tm2str = [](char *s, size_t size, const struct tm *tmp) noexcept {
            snprintf(s, size, "%04d-%02d-%02d %02d:%02d:%02d", (int) tmp->tm_year + 1900,
                     (int) tmp->tm_mon + 1, (int) tmp->tm_mday, (int) tmp->tm_hour,
                     (int) tmp->tm_min, (int) tmp->tm_sec);
        };
        char s[40];
        const time_t t = time(nullptr);
        tm2str(s, sizeof(s), localtime(&t));
        con_fprintf(f, "\n");
        con_fprintf(f, "Local time is:  %s\n", s);
        tm2str(s, sizeof(s), gmtime(&t));
        con_fprintf(f, "UTC time is:    %s\n", s);
    }
#endif
    // environment
    if (options_var && options_var[0]) {
        const char *e = upx_getenv(options_var);
        con_fprintf(f, "\n");
        if (e && e[0])
            con_fprintf(f, "Contents of environment variable %s: '%s'\n\n", options_var, e);
        else if (e)
            con_fprintf(f, "Environment variable '%s' is set but empty.\n\n", options_var);
        else
            con_fprintf(f, "Environment variable '%s' is not set.\n\n", options_var);
    }
}
References _WIN32_WINNT, con_fprintf, con_term, initial_win32_winnt, opt, show_header(), show_version(), size(), snprintf, UNUSED, upx_getenv(), UPX_VERSION_HEX, and UPX_VERSION_STRING.
Referenced by upx_main().
show_usage()
void show_usage ()
usage
Definition at line 88 of file help.cpp.
                      {
    FILE *f = con_term;
    con_fprintf(f, "Usage: %s [-123456789dlthVL] [-qvfk] [-o file] %sfile..\n", progname,
#if (ACC_OS_DOS32) && defined(__DJGPP__)
                "[@]");
#else
                "");
#endif
}
References con_fprintf, con_term, and progname.
Referenced by e_usage(), and show_help().
show_version()
void show_version (bool one_line = false)
version
Definition at line 420 of file help.cpp.
{
    FILE *f = stdout;
    const char *v;
#if defined(UPX_VERSION_GIT_DESCRIBE)
    fprintf(f, "upx %s\n", UPX_VERSION_GIT_DESCRIBE);
#elif defined(UPX_VERSION_GITREV)
    fprintf(f, "upx %s\n", UPX_VERSION_STRING "-git-" UPX_VERSION_GITREV);
#else
    fprintf(f, "upx %s\n", UPX_VERSION_STRING);
#endif
    if (one_line)
        return;
#if (WITH_NRV)
    v = upx_nrv_version_string();
    if (v != nullptr && v[0])
        fprintf(f, "NRV data compression library %s\n", v);
#endif
#if (WITH_UCL)
    v = upx_ucl_version_string();
    if (v != nullptr && v[0])
        fprintf(f, "UCL data compression library %s\n", v);
#endif
#if (WITH_ZLIB)
    v = upx_zlib_version_string();
    if (v != nullptr && v[0])
        fprintf(f, "zlib data compression library %s\n", v);
#endif
#if (WITH_LZMA)
    v = upx_lzma_version_string();
    if (v != nullptr && v[0])
        fprintf(f, "LZMA SDK version %s\n", v);
#endif
#if (WITH_ZSTD)
    v = upx_zstd_version_string();
    if (v != nullptr && v[0])
        fprintf(f, "zstd data compression library %s\n", v);
#endif
#if (WITH_BZIP2)
    v = upx_bzip2_version_string();
    if (v != nullptr && v[0])
        fprintf(f, "bzip2 data compression library %s\n", v);
#endif
#if !defined(DOCTEST_CONFIG_DISABLE)
    fprintf(f, "doctest C++ testing framework version %s\n", DOCTEST_VERSION_STR);
#endif
    // clang-format off
    fprintf(f, "Copyright (C) 1996-2024 Markus Franz Xaver Johannes Oberhumer\n");
    fprintf(f, "Copyright (C) 1996-2024 Laszlo Molnar\n");
    fprintf(f, "Copyright (C) 2000-2024 John F. Reiser\n");
#if (WITH_ZLIB)
    // see vendor/zlib/LICENSE
    fprintf(f, "Copyright (C) 1995" "-2024 Jean-loup Gailly and Mark Adler\n");
#endif
#if (WITH_LZMA)
    // see vendor/lzma-sdk
    fprintf(f, "Copyright (C) 1999" "-2006 Igor Pavlov\n");
#endif
#if (WITH_ZSTD)
    // see vendor/zstd/LICENSE; main author is Yann Collet
    fprintf(f, "Copyright (C) 2015" "-2024 Meta Platforms, Inc. and affiliates\n");
#endif
#if (WITH_BZIP2)
    // see vendor/bzip2/bzlib.h
    fprintf(f, "Copyright (C) 1996" "-2010 Julian Seward\n");
#endif
#if !defined(DOCTEST_CONFIG_DISABLE)
    // see vendor/doctest/LICENSE.txt
    fprintf(f, "Copyright (C) 2016" "-2023 Viktor Kirilov\n");
#endif
    // clang-format on
    fprintf(f, "UPX comes with ABSOLUTELY NO WARRANTY; for details type '%s -L'.\n", progname);
}
References progname, upx_lzma_version_string(), upx_ucl_version_string(), UPX_VERSION_STRING, and upx_zlib_version_string().
Referenced by do_option(), show_sysinfo(), and upx_main().
throwAssertFailed()
noreturn void throwAssertFailed (const char * expr, const char * file, int line, const char * func)
Definition at line 190 of file except.cpp.
{
    if (opt->debug.debug_level >= 1) {
        throwCantPack("corrupted file; details: %s (%s: %s: %d)", expr, file, func, line);
    } else {
        throwCantPack("corrupted file; try '--debug' for more details");
    }
}
References opt, and throwCantPack().
upx_adler32()
unsigned upx_adler32 (const void * buf, unsigned len, unsigned adler = 1)
Definition at line 35 of file compress.cpp.
{
    if (len == 0)
        return adler;
    assert(buf != nullptr);
#if 1
    return upx_ucl_adler32(buf, len, adler);
#else
    return upx_zlib_adler32(buf, len, adler);
#endif
}
References buf, and upx_ucl_adler32().
Referenced by Packer::compress(), Filter::filter(), PackPs1::getBkupHeader(), Packer::initPackHeader(), Packer::optimizeReloc(), PackUnix::pack2(), PackUnix::packExtent(), PackUnix::patchLoaderChecksum(), PackLinuxI386::patchLoaderChecksum(), PackMachBase< TMachClass >::patchLoaderChecksum(), ph_decompress(), PackPs1::putBkupHeader(), PackPs1::readBkupHeader(), Filter::unfilter(), Packer::unoptimizeReloc(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachBase< TMachClass >::unpack(), PackUnix::unpack(), PackUnix::unpackExtent(), and upx_compiler_sanity_check().
upx_compiler_sanity_check()
noinline void upx_compiler_sanity_check () noexcept
Definition at line 850 of file dt_check.cpp.
{
    check_basic_floating_point();
    if (is_envvar_true("UPX_DEBUG_DOCTEST_DISABLE", "UPX_DEBUG_DISABLE_DOCTEST")) {
        // If UPX_DEBUG_DOCTEST_DISABLE is set then we don't want to throw any
        // exceptions in order to improve debugging experience.
    } else {
        // check working C++ exception handling to early catch toolchain/qemu/wine/etc problems
        check_basic_cxx_exception_handling(throwSomeValue);
    }
    // check_basic_decltype()
    {
        auto a = +0;
        constexpr auto b = -0;
        const auto &c = -1;
        static_assert((std::is_same<int, decltype(a)>::value));
        static_assert((std::is_same<const int, decltype(b)>::value));
        static_assert((std::is_same<const int &, decltype(c)>::value));
        UNUSED(a);
        UNUSED(b);
        UNUSED(c);
    }
#define ACC_WANT_ACC_CHK_CH 1
#undef ACCCHK_ASSERT
#define ACCCHK_ASSERT(expr) ACC_COMPILE_TIME_ASSERT(expr)
#include "../util/miniacc.h"
#undef ACCCHK_ASSERT
    static_assert(sizeof(char) == 1);
    static_assert(sizeof(short) == 2);
    static_assert(sizeof(int) == 4);
    static_assert(sizeof(long) >= 4);
    static_assert(sizeof(long long) >= 8);
    static_assert(sizeof(void *) >= 4);
    static_assert(sizeof(upx_off_t) >= 8);
    static_assert(sizeof(upx_off_t) >= sizeof(long long));
// __int64
#if defined(_MSC_VER)
    {
        ASSERT_SAME_TYPE(long long, __int64);
        ASSERT_SAME_TYPE(unsigned long long, unsigned __int64);
        typedef __int64 my_int64;
        typedef unsigned __int64 my_uint64;
        ASSERT_SAME_TYPE(long long, my_int64);
        ASSERT_SAME_TYPE(unsigned long long, my_uint64);
    }
#endif
    static_assert(sizeof(BE16) == 2);
    static_assert(sizeof(BE32) == 4);
    static_assert(sizeof(BE64) == 8);
    static_assert(sizeof(LE16) == 2);
    static_assert(sizeof(LE32) == 4);
    static_assert(sizeof(LE64) == 8);
    COMPILE_TIME_ASSERT_ALIGNED1(BE16)
    COMPILE_TIME_ASSERT_ALIGNED1(BE32)
    COMPILE_TIME_ASSERT_ALIGNED1(BE64)
    COMPILE_TIME_ASSERT_ALIGNED1(LE16)
    COMPILE_TIME_ASSERT_ALIGNED1(LE32)
    COMPILE_TIME_ASSERT_ALIGNED1(LE64)
    // check that these types are not some multi-word macro
#define CHECK_TYPE(T) (void) (T())
    CHECK_TYPE(int8_t);
    CHECK_TYPE(uint8_t);
    CHECK_TYPE(int16_t);
    CHECK_TYPE(uint16_t);
    CHECK_TYPE(int32_t);
    CHECK_TYPE(uint32_t);
    CHECK_TYPE(int64_t);
    CHECK_TYPE(uint64_t);
    CHECK_TYPE(intmax_t);
    CHECK_TYPE(uintmax_t);
    CHECK_TYPE(ptrdiff_t);
    CHECK_TYPE(size_t);
    CHECK_TYPE(intptr_t);
    CHECK_TYPE(uintptr_t);
#if 0
    CHECK_TYPE(acc_int8_t);
    CHECK_TYPE(acc_uint8_t);
    CHECK_TYPE(acc_int16_t);
    CHECK_TYPE(acc_uint16_t);
    CHECK_TYPE(acc_int32_t);
    CHECK_TYPE(acc_uint32_t);
    CHECK_TYPE(acc_int64_t);
    CHECK_TYPE(acc_uint64_t);
    CHECK_TYPE(acc_intptr_t);
    CHECK_TYPE(acc_uintptr_t);
#endif
    CHECK_TYPE(upx_int8_t);
    CHECK_TYPE(upx_uint8_t);
    CHECK_TYPE(upx_int16_t);
    CHECK_TYPE(upx_uint16_t);
    CHECK_TYPE(upx_int32_t);
    CHECK_TYPE(upx_uint32_t);
    CHECK_TYPE(upx_int64_t);
    CHECK_TYPE(upx_uint64_t);
#if (__SIZEOF_INT128__ == 16)
    CHECK_TYPE(upx_int128_t);
    CHECK_TYPE(upx_uint128_t);
#endif
    CHECK_TYPE(upx_ptraddr_t);
    CHECK_TYPE(upx_uintptr_t);
    CHECK_TYPE(upx_uptrdiff_t);
    CHECK_TYPE(upx_ssize_t);
#undef CHECK_TYPE
    CheckIntegral<char>::check();
    CheckIntegral<signed char>::check();
    CheckIntegral<unsigned char>::check();
    CheckIntegral<short>::check();
    CheckIntegral<unsigned short>::check();
    CheckIntegral<int>::check();
    CheckIntegral<unsigned>::check();
    CheckIntegral<long>::check();
    CheckIntegral<unsigned long>::check();
    CheckIntegral<long long>::check();
    CheckIntegral<unsigned long long>::check();
    CheckIntegral<intmax_t>::check();
    CheckIntegral<uintmax_t>::check();
    CheckIntegral<upx_int8_t>::check();
    CheckIntegral<upx_uint8_t>::check();
    CheckIntegral<upx_int16_t>::check();
    CheckIntegral<upx_uint16_t>::check();
    CheckIntegral<upx_int32_t>::check();
    CheckIntegral<upx_uint32_t>::check();
    CheckIntegral<upx_int64_t>::check();
    CheckIntegral<upx_uint64_t>::check();
    CheckIntegral<upx_off_t>::check();
    CheckIntegral<ptrdiff_t>::check();
    CheckIntegral<size_t>::check();
    CheckIntegral<upx_ptraddr_t>::check();
#if defined(__CHERI__) && defined(__CHERI_PURE_CAPABILITY__)
    static_assert(sizeof(upx_ptraddr_t) == 8);
    static_assert(alignof(upx_ptraddr_t) == 8);
    static_assert(sizeof(void *) == 16);
    static_assert(alignof(void *) == 16);
    static_assert(sizeof(uintptr_t) == 16);
    static_assert(alignof(uintptr_t) == 16);
    // warning: binary expression on capability types 'unsigned __intcap' and 'unsigned __intcap'
    CheckIntegral<intptr_t>::check_core();
    CheckIntegral<uintptr_t>::check_core();
    CheckIntegral<upx_uintptr_t>::check_core();
#else
    CheckIntegral<intptr_t>::check();
    CheckIntegral<uintptr_t>::check();
    CheckIntegral<upx_uintptr_t>::check();
#endif
#if (__SIZEOF_INT128__ == 16)
#if defined(_CPP_VER) || defined(_WIN32) // int128 is not fully supported by MSVC libstdc++ yet
#else
    CheckIntegral<upx_int128_t>::check();
    CheckIntegral<upx_uint128_t>::check();
#endif
#endif
    CheckSignedness<char, false>::check(); // -funsigned-char
    CheckSignedness<signed char, true>::check();
    CheckSignedness<unsigned char, false>::check();
    CheckSignedness<short, true>::check();
    CheckSignedness<unsigned short, false>::check();
    CheckSignedness<int, true>::check();
    CheckSignedness<unsigned, false>::check();
    CheckSignedness<long, true>::check();
    CheckSignedness<unsigned long, false>::check();
    CheckSignedness<long long, true>::check();
    CheckSignedness<unsigned long long, false>::check();
    CheckSignedness<intmax_t, true>::check();
    CheckSignedness<uintmax_t, false>::check();
    CheckSignedness<upx_int8_t, true>::check();
    CheckSignedness<upx_uint8_t, false>::check();
    CheckSignedness<upx_int16_t, true>::check();
    CheckSignedness<upx_uint16_t, false>::check();
    CheckSignedness<upx_int32_t, true>::check();
    CheckSignedness<upx_uint32_t, false>::check();
    CheckSignedness<upx_int64_t, true>::check();
    CheckSignedness<upx_uint64_t, false>::check();
#if (__SIZEOF_INT128__ == 16)
#if defined(_CPP_VER) || defined(_WIN32) // int128 is not fully supported by MSVC libstdc++ yet
#else
    CheckSignedness<upx_int128_t, true>::check();
    CheckSignedness<upx_uint128_t, false>::check();
#endif
#endif
    CheckSignedness<upx_off_t, true>::check();
    CheckSignedness<ptrdiff_t, true>::check();
    CheckSignedness<size_t, false>::check();
    CheckSignedness<upx_ptraddr_t, false>::check();
    CheckSignedness<intptr_t, true>::check();
    CheckSignedness<uintptr_t, false>::check();
    CheckSignedness<upx_uintptr_t, false>::check();
#define CHECK_TYPE_PAIR(A, B)                                                                      \
    CheckTypePair<A, B>::check();                                                                  \
    static_assert(alignof(A) == alignof(B))
    CHECK_TYPE_PAIR(signed char, unsigned char);
    CHECK_TYPE_PAIR(short, unsigned short);
    CHECK_TYPE_PAIR(int, unsigned);
    CHECK_TYPE_PAIR(long, unsigned long);
    CHECK_TYPE_PAIR(long long, unsigned long long);
    CHECK_TYPE_PAIR(intmax_t, uintmax_t);
    CHECK_TYPE_PAIR(upx_int8_t, upx_uint8_t);
    CHECK_TYPE_PAIR(upx_int16_t, upx_uint16_t);
    CHECK_TYPE_PAIR(upx_int32_t, upx_uint32_t);
    CHECK_TYPE_PAIR(upx_int64_t, upx_uint64_t);
#if (__SIZEOF_INT128__ == 16)
#if defined(_CPP_VER) || defined(_WIN32) // int128 is not fully supported by MSVC libstdc++ yet
#else
    CHECK_TYPE_PAIR(upx_int128_t, upx_uint128_t);
#endif
#endif
    CHECK_TYPE_PAIR(ptrdiff_t, upx_uptrdiff_t);
    CHECK_TYPE_PAIR(upx_ssize_t, size_t);
    CHECK_TYPE_PAIR(upx_sptraddr_t, upx_ptraddr_t);
    CHECK_TYPE_PAIR(intptr_t, uintptr_t);
    CHECK_TYPE_PAIR(acc_intptr_t, acc_uintptr_t);
#undef CHECK_TYPE_PAIR
    static_assert(sizeof(upx_charptr_unit_type) == 1);
    COMPILE_TIME_ASSERT_ALIGNED1(upx_charptr_unit_type)
    static_assert(sizeof(*((charptr) nullptr)) == 1);
    // check UPX_VERSION_xxx
    {
        using upx::compile_time::mem_eq;
        using upx::compile_time::string_len;
        static_assert(string_len(UPX_VERSION_STRING4) == 4);
        static_assert(string_len(UPX_VERSION_YEAR) == 4);
        static_assert(string_len(UPX_VERSION_DATE_ISO) == 10);
        static_assert(string_len(UPX_VERSION_DATE) == 12 || string_len(UPX_VERSION_DATE) == 13);
        static_assert(mem_eq(UPX_VERSION_STRING4, UPX_VERSION_STRING, 3));
        static_assert(mem_eq(UPX_VERSION_YEAR, UPX_VERSION_DATE_ISO, 4));
        static_assert(mem_eq(UPX_VERSION_YEAR, &UPX_VERSION_DATE[sizeof(UPX_VERSION_DATE) - 5], 4));
        char buf[16];
        constexpr long long v = UPX_VERSION_HEX;
        upx_safe_snprintf(buf, sizeof(buf), "%lld.%lld.%lld", (v >> 16), (v >> 8) & 255, v & 255);
        assert_noexcept(strcmp(buf, UPX_VERSION_STRING) == 0);
        upx_safe_snprintf(buf, sizeof(buf), "%lld.%lld%lld", (v >> 16), (v >> 8) & 255, v & 255);
        assert_noexcept(strcmp(buf, UPX_VERSION_STRING4) == 0);
    }
    if (gitrev[0]) {
        size_t revlen = strlen(gitrev);
        if (strncmp(gitrev, "ERROR", 5) == 0) {
            assert_noexcept(revlen == 5 || revlen == 6);
        } else {
            assert_noexcept(revlen == 12 || revlen == 13);
        }
        if (revlen == 6 || revlen == 13) {
            assert_noexcept(gitrev[revlen - 1] == '+');
        }
    }
    assert_noexcept(UPX_RSIZE_MAX_MEM == 805306368);
#if DEBUG || 1
    assert_noexcept(TestBELE<LE16>::test());
    assert_noexcept(TestBELE<LE32>::test());
    assert_noexcept(TestBELE<LE64>::test());
    assert_noexcept(TestBELE<BE16>::test());
    assert_noexcept(TestBELE<BE32>::test());
    assert_noexcept(TestBELE<BE64>::test());
    {
        alignas(16) static constexpr byte dd[32] = {
            0, 0, 0, 0,    0,    0,    0,    0xff, 0xfe, 0xfd, 0xfc, 0xfb, 0xfa, 0xf9, 0xf8, 0,
            0, 0, 0, 0x7f, 0x7e, 0x7d, 0x7c, 0x7b, 0x7a, 0x79, 0x78, 0,    0,    0,    0,    0};
        constexpr const byte *d = dd + 7;
#if !defined(upx_fake_alignas_16)
        assert_noexcept(ptr_is_aligned<16>(dd));
        assert_noexcept(ptr_is_aligned(dd, 16));
#endif
        static_assert(upx::compile_time::get_be16(d) == 0xfffe);
        static_assert(upx::compile_time::get_be24(d) == 0xfffefd);
        static_assert(upx::compile_time::get_be32(d) == 0xfffefdfc);
        static_assert(upx::compile_time::get_be64(d) == 0xfffefdfcfbfaf9f8ULL);
        static_assert(upx::compile_time::get_le16(d) == 0xfeff);
        static_assert(upx::compile_time::get_le24(d) == 0xfdfeff);
        static_assert(upx::compile_time::get_le32(d) == 0xfcfdfeff);
        static_assert(upx::compile_time::get_le64(d) == 0xf8f9fafbfcfdfeffULL);
        const N_BELE_RTP::AbstractPolicy *bele;
        assert_noexcept(upx_adler32(d, 4) == 0x09f003f7);
        assert_noexcept(upx_adler32(d, 4, 0) == 0x09ec03f6);
        assert_noexcept(upx_adler32(d, 4, 1) == 0x09f003f7);
        bele = &N_BELE_RTP::be_policy;
        assert_noexcept(get_be16(d) == 0xfffe);
        assert_noexcept(bele->get16(d) == 0xfffe);
        assert_noexcept(get_be16_signed(d) == -2);
        assert_noexcept(get_be24(d) == 0xfffefd);
        assert_noexcept(bele->get24(d) == 0xfffefd);
        assert_noexcept(get_be24_signed(d) == -259);
        assert_noexcept(get_be32(d) == 0xfffefdfc);
        assert_noexcept(bele->get32(d) == 0xfffefdfc);
        assert_noexcept(get_be32_signed(d) == -66052);
        assert_noexcept(get_be64(d) == 0xfffefdfcfbfaf9f8ULL);
        assert_noexcept(get_be64_signed(d) == -283686952306184LL);
        bele = &N_BELE_RTP::le_policy;
        assert_noexcept(get_le16(d) == 0xfeff);
        assert_noexcept(bele->get16(d) == 0xfeff);
        assert_noexcept(get_le16_signed(d) == -257);
        assert_noexcept(get_le24(d) == 0xfdfeff);
        assert_noexcept(bele->get24(d) == 0xfdfeff);
        assert_noexcept(get_le24_signed(d) == -131329);
        assert_noexcept(get_le32(d) == 0xfcfdfeff);
        assert_noexcept(bele->get32(d) == 0xfcfdfeff);
        assert_noexcept(get_le32_signed(d) == -50462977);
        assert_noexcept(get_le64(d) == 0xf8f9fafbfcfdfeffULL);
        assert_noexcept(get_le64_signed(d) == -506097522914230529LL);
        static_assert(get_be24(d) == 0xfffefd);
        static_assert(get_le24(d) == 0xfdfeff);
#if defined(upx_is_constant_evaluated)
        static_assert(get_be24_signed(d) == -259);
        static_assert(get_le24_signed(d) == -131329);
        static_assert(get_be16(d) == 0xfffe);
        static_assert(get_be16_signed(d) == -2);
        static_assert(get_be32(d) == 0xfffefdfc);
        static_assert(get_be32_signed(d) == -66052);
        static_assert(get_be64(d) == 0xfffefdfcfbfaf9f8ULL);
        static_assert(get_be64_signed(d) == -283686952306184LL);
        static_assert(get_le16(d) == 0xfeff);
        static_assert(get_le16_signed(d) == -257);
        static_assert(get_le32(d) == 0xfcfdfeff);
        static_assert(get_le32_signed(d) == -50462977);
        static_assert(get_le64(d) == 0xf8f9fafbfcfdfeffULL);
        static_assert(get_le64_signed(d) == -506097522914230529LL);
#endif
        assert_noexcept(find_be16(d, 2, 0xfffe) == 0);
        assert_noexcept(find_le16(d, 2, 0xfeff) == 0);
        assert_noexcept(find_be32(d, 4, 0xfffefdfc) == 0);
        assert_noexcept(find_le32(d, 4, 0xfcfdfeff) == 0);
        constexpr const byte *e = d + 12;
        assert_noexcept(get_be16_signed(e) == 32638);
        assert_noexcept(get_be24_signed(e) == 8355453);
        assert_noexcept(get_be32_signed(e) == 2138996092);
        assert_noexcept(get_be64_signed(e) == 9186918263483431288LL);
#if defined(upx_is_constant_evaluated)
        static_assert(get_be16_signed(e) == 32638);
        static_assert(get_be24_signed(e) == 8355453);
        static_assert(get_be32_signed(e) == 2138996092);
        static_assert(get_be64_signed(e) == 9186918263483431288LL);
#endif
    }
#if defined(upx_is_constant_evaluated)
    {
        constexpr upx_uint16_t v16 = 0x0201;
        constexpr upx_uint32_t v32 = 0x04030201;
        constexpr upx_uint64_t v64 = 0x0807060504030201ull;
        constexpr BE16 be16 = BE16::make(v16);
        constexpr BE32 be32 = BE32::make(v32);
        constexpr BE64 be64 = BE64::make(v64);
        constexpr LE16 le16 = LE16::make(v16);
        constexpr LE32 le32 = LE32::make(v32);
        constexpr LE64 le64 = LE64::make(v64);
        using upx::compile_time::mem_eq;
        static_assert(mem_eq(be16.d, "\x02\x01", 2));
        static_assert(mem_eq(be32.d, "\x04\x03\x02\x01", 4));
        static_assert(mem_eq(be64.d, "\x08\x07\x06\x05\x04\x03\x02\x01", 8));
        static_assert(mem_eq(le16.d, "\x01\x02", 2));
        static_assert(mem_eq(le32.d, "\x01\x02\x03\x04", 4));
        static_assert(mem_eq(le64.d, "\x01\x02\x03\x04\x05\x06\x07\x08", 8));
        constexpr NE16 ne16 = NE16::make(v16);
        constexpr NE32 ne32 = NE32::make(v32);
        constexpr NE64 ne64 = NE64::make(v64);
        assert_noexcept(memcmp(&v16, ne16.d, 2) == 0);
        assert_noexcept(memcmp(&v32, ne32.d, 4) == 0);
        assert_noexcept(memcmp(&v64, ne64.d, 8) == 0);
    }
#endif
#if DEBUG >= 1
    {
        for (int i = 0; i < 256; i++) {
            {
                const unsigned u = i;
                assert_noexcept(sign_extend(u, 1) == ((i & 1) ? -1 : 0));
                assert_noexcept(sign_extend(u, 2) == ((i & 2) ? -2 + (i & 1) : (i & 1)));
                assert_noexcept(sign_extend(u, 3) == ((i & 4) ? -4 + (i & 3) : (i & 3)));
                assert_noexcept(sign_extend(u, 4) == ((i & 8) ? -8 + (i & 7) : (i & 7)));
                assert_noexcept(sign_extend(u, 5) == ((i & 16) ? -16 + (i & 15) : (i & 15)));
                assert_noexcept(sign_extend(u, 6) == ((i & 32) ? -32 + (i & 31) : (i & 31)));
                assert_noexcept(sign_extend(u, 7) == ((i & 64) ? -64 + (i & 63) : (i & 63)));
                assert_noexcept(sign_extend(u, 8) == ((i & 128) ? -128 + (i & 127) : (i & 127)));
                assert_noexcept(sign_extend(u, 32) == i);
                assert_noexcept(sign_extend(0u - u, 32) == -i);
            }
            {
                const upx_uint64_t u = i;
                assert_noexcept(sign_extend(u, 1) == ((i & 1) ? -1 : 0));
                assert_noexcept(sign_extend(u, 2) == ((i & 2) ? -2 + (i & 1) : (i & 1)));
                assert_noexcept(sign_extend(u, 3) == ((i & 4) ? -4 + (i & 3) : (i & 3)));
                assert_noexcept(sign_extend(u, 4) == ((i & 8) ? -8 + (i & 7) : (i & 7)));
                assert_noexcept(sign_extend(u, 5) == ((i & 16) ? -16 + (i & 15) : (i & 15)));
                assert_noexcept(sign_extend(u, 6) == ((i & 32) ? -32 + (i & 31) : (i & 31)));
                assert_noexcept(sign_extend(u, 7) == ((i & 64) ? -64 + (i & 63) : (i & 63)));
                assert_noexcept(sign_extend(u, 8) == ((i & 128) ? -128 + (i & 127) : (i & 127)));
                assert_noexcept(sign_extend(u, 64) == i);
                assert_noexcept(sign_extend(upx_uint64_t(0) - u, 64) == -i);
            }
        }
    }
#endif
    {
        unsigned dd;
        void *const d = &dd;
        dd = ne32_to_le32(0xf7f6f5f4);
        assert_noexcept(get_le26(d) == 0x03f6f5f4);
        set_le26(d, 0);
        assert_noexcept(get_le26(d) == 0);
        assert_noexcept(dd == ne32_to_le32(0xf4000000));
        set_le26(d, 0xff020304);
        assert_noexcept(get_le26(d) == 0x03020304);
        assert_noexcept(dd == ne32_to_le32(0xf7020304));
    }
    {
        upx_uint16_t a = 0;
        upx_uint32_t b = 0;
        upx_uint64_t c = 0;
        set_ne16(&a, 0x04030201); // ignore upper bits
        set_ne32(&b, 0x04030201);
        set_ne64(&c, 0x0807060504030201ull);
        assert_noexcept(a == 0x0201);
        assert_noexcept(b == 0x04030201);
        assert_noexcept(c == 0x0807060504030201ull);
        assert_noexcept(get_ne16(&a) == 0x0201);
        assert_noexcept(get_ne32(&b) == 0x04030201);
        assert_noexcept(get_ne64(&c) == 0x0807060504030201ull);
    }
#endif // DEBUG
    union {
        short v_short;
        int v_int;
        long v_long;
        long long v_llong;
        BE16 b16;
        BE32 b32;
        BE64 b64;
        LE16 l16;
        LE32 l32;
        LE64 l64;
    } u;
    assert_noexcept(testNoAliasing(&u.v_short, &u.b32));
    assert_noexcept(testNoAliasing(&u.v_short, &u.l32));
    assert_noexcept(testNoAliasing(&u.v_int, &u.b64));
    assert_noexcept(testNoAliasing(&u.v_int, &u.l64));
    // check working -fno-strict-aliasing
    assert_noexcept(testNoAliasing(&u.v_short, &u.v_int));
    assert_noexcept(testNoAliasing(&u.v_int, &u.v_long));
    assert_noexcept(testNoAliasing(&u.v_int, &u.v_llong));
    assert_noexcept(testNoAliasing(&u.v_long, &u.v_llong));
    assert_noexcept(TestIntegerWrap<unsigned>::inc_gt(0));
    assert_noexcept(!TestIntegerWrap<unsigned>::inc_gt(UINT_MAX));
    assert_noexcept(TestIntegerWrap<unsigned>::dec_lt(1));
    assert_noexcept(!TestIntegerWrap<unsigned>::dec_lt(0));
    assert_noexcept(TestIntegerWrap<unsigned>::neg_eq(0));
    assert_noexcept(!TestIntegerWrap<unsigned>::neg_eq(1));
    assert_noexcept(!TestIntegerWrap<unsigned>::neg_eq(UINT_MAX));
    // check working -fno-strict-overflow
    assert_noexcept(TestIntegerWrap<int>::inc_gt(0));
    assert_noexcept(!TestIntegerWrap<int>::inc_gt(INT_MAX));
    assert_noexcept(TestIntegerWrap<int>::dec_lt(0));
    assert_noexcept(!TestIntegerWrap<int>::dec_lt(INT_MIN));
    assert_noexcept(TestIntegerWrap<int>::neg_eq(0));
    assert_noexcept(!TestIntegerWrap<int>::neg_eq(1));
    assert_noexcept(!TestIntegerWrap<int>::neg_eq(INT_MAX));
    assert_noexcept(TestIntegerWrap<int>::neg_eq(INT_MIN)); // special case
}
References acc_int8_t, acc_intptr_t, acc_uint8_t, acc_uintptr_t, assert_noexcept, ASSERT_SAME_TYPE, b, N_BELE_RTP::be_policy, buf, charptr, anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check(), anonymous_namespace{dt_check.cpp}::CheckSignedness< T, T_is_signed >::check(), anonymous_namespace{dt_check.cpp}::check_basic_cxx_exception_handling(), anonymous_namespace{dt_check.cpp}::check_basic_floating_point(), anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check_core(), CHECK_TYPE, CHECK_TYPE_PAIR, COMPILE_TIME_ASSERT_ALIGNED1, BE16::d, LE16::d, BE32::d, LE32::d, BE64::d, LE64::d, anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::dec_lt(), find_be16(), find_be32(), find_le16(), find_le32(), upx::compile_time::get_be16(), get_be16(), get_be16_signed(), get_be24(), upx::compile_time::get_be24(), get_be24_signed(), upx::compile_time::get_be32(), get_be32(), get_be32_signed(), upx::compile_time::get_be64(), get_be64(), get_be64_signed(), upx::compile_time::get_le16(), get_le16(), get_le16_signed(), get_le24(), upx::compile_time::get_le24(), get_le24_signed(), get_le26(), upx::compile_time::get_le32(), get_le32(), get_le32_signed(), upx::compile_time::get_le64(), get_le64(), get_le64_signed(), get_ne16(), get_ne32(), get_ne64(), gitrev, anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::inc_gt(), is_envvar_true(), N_BELE_RTP::le_policy, BE16::make(), BE32::make(), BE64::make(), LE16::make(), LE32::make(), LE64::make(), upx::compile_time::mem_eq(), memcmp(), ne32_to_le32, anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::neg_eq(), ptr_is_aligned(), set_le26(), set_ne16(), set_ne32(), set_ne64(), sign_extend(), strcmp(), upx::compile_time::string_len(), strlen, anonymous_namespace{dt_check.cpp}::TestBELE< T >::test(), anonymous_namespace{dt_check.cpp}::testNoAliasing(), anonymous_namespace{dt_check.cpp}::throwSomeValue(), UNUSED, upx_adler32(), UPX_RSIZE_MAX_MEM, upx_safe_snprintf(), UPX_VERSION_DATE, UPX_VERSION_DATE_ISO, UPX_VERSION_HEX, UPX_VERSION_STRING, UPX_VERSION_STRING4, and UPX_VERSION_YEAR.
Referenced by do_files(), and upx_main().
upx_compress()
int upx_compress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, upx_callback_t * cb, int method, int level, const upx_compress_config_t * cconf, upx_compress_result_t * cresult)
Definition at line 64 of file compress.cpp.
{
    int r = UPX_E_ERROR;
    upx_compress_result_t cresult_buffer;
    assert(method > 0);
    assert(level > 0);
#if 1
    // set available bytes in dst
    if (*dst_len == 0)
        *dst_len = MemBuffer::getSizeForCompression(src_len);
#else
    // force users to provide *dst_len
    assert(*dst_len != 0);
#endif
    // for UPX, we always require a reasonably sized output buffer
    assert(*dst_len >= MemBuffer::getSizeForCompression(src_len));
    if (!cresult)
        cresult = &cresult_buffer;
    cresult->reset();
#if 1
    // debugging aid
    cresult->debug.method = method;
    cresult->debug.level = level;
    cresult->debug.u_len = src_len;
    cresult->debug.c_len = 0;
#endif
    const unsigned orig_dst_len = *dst_len;
    if (__acc_cte(false)) {
    }
#if (WITH_BZIP2)
    else if (M_IS_BZIP2(method))
        r = upx_bzip2_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_LZMA)
    else if (M_IS_LZMA(method))
        r = upx_lzma_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_NRV)
    else if ((M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) && !opt->prefer_ucl)
        r = upx_nrv_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_UCL)
    else if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        r = upx_ucl_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
#if (WITH_ZSTD)
    else if (M_IS_ZSTD(method))
        r = upx_zstd_compress(src, src_len, dst, dst_len, cb, method, level, cconf, cresult);
#endif
    else {
        throwInternalError("unknown compression method %d", method);
    }
#if 1
    // debugging aid
    cresult->debug.c_len = *dst_len;
#endif
    assert_noexcept(*dst_len <= orig_dst_len);
    return r;
}
References __acc_cte, assert_noexcept, upx_compress_result_t::Debug::c_len, upx_compress_result_t::debug, MemBuffer::getSizeForCompression(), upx_compress_result_t::Debug::level, M_IS_BZIP2, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_IS_ZSTD, upx_compress_result_t::Debug::method, opt, upx_compress_result_t::reset(), throwInternalError(), upx_compress_result_t::Debug::u_len, UPX_E_ERROR, upx_lzma_compress(), and upx_ucl_compress().
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackExe::buildLoader(), PackPs1::buildLoader(), PackMachBase< TMachClass >::buildMachLoader(), Packer::compress(), Packer::compressWithFilters(), PackVmlinuxBase< TElfClass >::pack(), PackUnix::packExtent(), and PackPs1::putBkupHeader().
upx_crc32()
unsigned upx_crc32 (const void * buf, unsigned len, unsigned crc = 0)
upx_decompress()
int upx_decompress (const upx_bytep src, unsigned src_len, upx_bytep dst, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 134 of file compress.cpp.
{
    int r = UPX_E_ERROR;
    assert(*dst_len > 0);
    assert(src_len < *dst_len); // must be compressed
    if (cresult && cresult->debug.method == 0)
        cresult = nullptr;
    const unsigned orig_dst_len = *dst_len;
    if (__acc_cte(false)) {
    }
#if (WITH_BZIP2)
    else if (M_IS_BZIP2(method))
        r = upx_bzip2_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_LZMA)
    else if (M_IS_LZMA(method))
        r = upx_lzma_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_NRV)
    else if ((M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) && !opt->prefer_ucl)
        r = upx_nrv_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_UCL)
    else if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        r = upx_ucl_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_ZLIB)
    else if (M_IS_DEFLATE(method))
        r = upx_zlib_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
#if (WITH_ZSTD)
    else if (M_IS_ZSTD(method))
        r = upx_zstd_decompress(src, src_len, dst, dst_len, method, cresult);
#endif
    else {
        throwInternalError("unknown compression method %d", method);
    }
    assert_noexcept(*dst_len <= orig_dst_len);
    return r;
}
References __acc_cte, assert_noexcept, upx_compress_result_t::debug, M_IS_BZIP2, M_IS_DEFLATE, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_IS_ZSTD, upx_compress_result_t::Debug::method, opt, throwInternalError(), UPX_E_ERROR, upx_lzma_decompress(), upx_ucl_decompress(), and upx_zlib_decompress().
Referenced by Packer::compress(), PackPs1::getBkupHeader(), ElfLinker::init(), and ph_decompress().
upx_doctest_check() [1/2]
int upx_doctest_check ()
Definition at line 93 of file dt_check.cpp.
{ return upx_doctest_check(0, nullptr); }
References upx_doctest_check().
Referenced by upx_doctest_check(), and upx_main().
upx_doctest_check() [2/2]
noinline int upx_doctest_check (int argc, char ** argv)
upx_doctest_check()
honors environment variables: UPX_DEBUG_DOCTEST_DISABLE UPX_DEBUG_DOCTEST_VERBOSE
HINT: set "UPX_DEBUG_DOCTEST_DISABLE=1" for improved debugging experience
Definition at line 44 of file dt_check.cpp.
{
#if defined(DOCTEST_CONFIG_DISABLE)
    UNUSED(argc);
    UNUSED(argv);
    return 0;
#else
    if (is_envvar_true("UPX_DEBUG_DOCTEST_DISABLE", "UPX_DEBUG_DISABLE_DOCTEST"))
        return 0;
    bool minimal = true;   // don't show summary
    bool duration = false; // don't show timings
    bool success = false;  // don't show all succeeding tests
#if DEBUG
    // default for debug builds: do show the [doctest] summary
    minimal = false;
#endif
    const char *e = upx_getenv("UPX_DEBUG_DOCTEST_VERBOSE");
    if (e && e[0]) {
        if (strcmp(e, "0") == 0) {
            minimal = true;
        } else if (strcmp(e, "1") == 0) {
            minimal = false;
        } else if (strcmp(e, "2") == 0) {
            minimal = false;
            duration = true;
        } else if (strcmp(e, "3") == 0) {
            minimal = false;
            duration = true;
            success = true;
        }
    }
    doctest::Context context;
    if (minimal)
        context.setOption("dt-minimal", true);
    if (duration)
        context.setOption("dt-duration", true);
    if (success)
        context.setOption("dt-success", true);
    // this requires that main_get_options() understands/ignores doctest "--dt-XXX" options
    if (argc > 0 && argv != nullptr)
        context.applyCommandLine(argc, argv);
    int r = context.run();
    if (r != 0)
        return 1;
    if (context.shouldExit())
        return 2;
    return 0;
#endif // DOCTEST_CONFIG_DISABLE
}
References is_envvar_true(), strcmp(), UNUSED, and upx_getenv().
upx_main()
int upx_main (int argc, char * argv[])
main entry point
Definition at line 1195 of file main.cpp.
{
    int i;
    static char default_argv0[] = "upx";
    assert(argc >= 1); // sanity check
    if (!argv[0] || !argv[0][0])
        argv[0] = default_argv0;
    argv0 = argv[0];
    upx_compiler_sanity_check();
    int dt_res = upx_doctest_check(argc, argv);
    if (dt_res != 0) {
        if (dt_res == 2)
            fprintf(stderr, "%s: doctest requested program exit; Stop.\n", argv0);
        else
            fprintf(stderr, "%s: internal error: doctest check failed\n", argv0);
        e_exit(EXIT_INIT);
    }
    // Allow serial re-use of upx_main() as a subroutine
    exit_code = EXIT_OK;
    opt->reset();
#if (ACC_OS_CYGWIN || ACC_OS_DOS16 || ACC_OS_DOS32 || ACC_OS_EMX || ACC_OS_TOS || ACC_OS_WIN16 ||  \
     ACC_OS_WIN32 || ACC_OS_WIN64)
    {
        char *prog = fn_basename(argv0);
        char *p;
        bool allupper = true;
        for (p = prog; *p; p++)
            if (islower((uchar) *p))
                allupper = false;
        if (allupper)
            fn_strlwr(prog);
        if (p - prog > 4) {
            p -= 4;
            if (fn_strcmp(p, ".exe") == 0 || fn_strcmp(p, ".ttp") == 0)
                *p = 0;
        }
        progname = prog;
    }
#else
    progname = fn_basename(argv0);
#endif
    while (progname[0] == '.' && progname[1] == '/' && progname[2])
        progname += 2;
    set_term(stderr);
#if (WITH_BZIP2)
    assert(upx_bzip2_init() == 0);
#endif
    assert(upx_lzma_init() == 0);
#if (WITH_NRV)
    assert(upx_nrv_init() == 0);
#endif
    assert(upx_ucl_init() == 0);
#if (WITH_ZLIB)
    assert(upx_zlib_init() == 0);
#endif
#if (WITH_ZSTD)
    assert(upx_zstd_init() == 0);
#endif
    /* get options */
    first_options(argc, argv);
    if (!opt->no_env)
        main_get_envoptions();
    i = main_get_options(argc, argv);
    assert(i <= argc);
    set_term(nullptr);
    switch (opt->cmd) {
    case CMD_NONE:
        /* default - compress */
        set_cmd(CMD_COMPRESS);
        break;
    case CMD_COMPRESS:
        break;
    case CMD_DECOMPRESS:
        break;
    case CMD_TEST:
        break;
    case CMD_LIST:
        break;
    case CMD_FILEINFO:
        break;
    case CMD_SYSINFO:
        show_sysinfo(OPTIONS_VAR);
        e_exit(EXIT_OK);
        break;
    case CMD_HELP:
        show_help(2);
        e_exit(EXIT_OK);
        break;
    case CMD_LICENSE:
        show_license();
        e_exit(EXIT_OK);
        break;
    case CMD_VERSION:
        show_version();
        e_exit(EXIT_OK);
        break;
    default:
        assert(false); // should not happen
        break;
    }
    /* check options */
    if (argc == 1)
        e_help();
    set_term(stderr);
    check_and_update_options(i, argc);
    int num_files = argc - i;
    if (num_files < 1) {
        if (opt->verbose >= 2)
            e_help();
        else
            e_usage();
    }
    /* start work */
    set_term(stdout);
    if (do_files(i, argc, argv) != 0) {
        assert(exit_code != 0);
        return exit_code;
    }
    if (gitrev[0]) {
        // also see UPX_CONFIG_DISABLE_GITREV in CMakeLists.txt
        bool warn_gitrev = true;
        if (is_envvar_true("UPX_DEBUG_DISABLE_GITREV_WARNING"))
            warn_gitrev = false;
        if (warn_gitrev) {
            FILE *f = stdout;
            int fg = con_fg(f, FG_RED);
            con_fprintf(
                f, "\nWARNING: this is an unstable beta version - use for testing only! Really.\n");
            fg = con_fg(f, fg);
            UNUSED(fg);
        }
    }
    return exit_code;
}
References argv0, check_and_update_options(), CMD_COMPRESS, CMD_DECOMPRESS, CMD_FILEINFO, CMD_HELP, CMD_LICENSE, CMD_LIST, CMD_NONE, CMD_SYSINFO, CMD_TEST, CMD_VERSION, con_fg, con_fprintf, do_files(), e_exit(), e_help(), e_usage(), exit_code, EXIT_INIT, EXIT_OK, first_options(), fn_basename(), fn_strcmp(), fn_strlwr(), gitrev, is_envvar_true(), main_get_envoptions(), main_get_options(), opt, OPTIONS_VAR, progname, set_cmd(), set_term(), show_help(), show_license(), show_sysinfo(), show_version(), UNUSED, upx_compiler_sanity_check(), upx_doctest_check(), upx_lzma_init(), upx_ucl_init(), and upx_zlib_init().
Referenced by main().
upx_std_call_once()
template<class NoexceptCallable > void upx_std_call_once (upx_std_once_flag & flag, NoexceptCallable && f) inline
Definition at line 118 of file conf.h.
{
    if (__acc_unlikely(!flag)) {
        flag = 1;
        f();
    }
}
References __acc_unlikely.
Referenced by FilterImpl::getFilter(), getIdentstr(), and UiPacker::UiPacker().
upx_test_overlap()
int upx_test_overlap (const upx_bytep buf, const upx_bytep tbuf, unsigned src_off, unsigned src_len, unsigned * dst_len, int method, const upx_compress_result_t * cresult)
Definition at line 183 of file compress.cpp.
{
    int r = UPX_E_ERROR;
    if (cresult && cresult->debug.method == 0)
        cresult = nullptr;
    assert(*dst_len > 0);
    assert(src_len < *dst_len); // must be compressed
    unsigned overlap_overhead = src_off + src_len - *dst_len;
    assert((int) overlap_overhead > 0);
    const unsigned orig_dst_len = *dst_len;
    if (__acc_cte(false)) {
    }
#if (WITH_BZIP2)
    else if (M_IS_BZIP2(method))
        r = upx_bzip2_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_LZMA)
    else if (M_IS_LZMA(method))
        r = upx_lzma_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_NRV)
    else if ((M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method)) && !opt->prefer_ucl)
        r = upx_nrv_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_UCL)
    else if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        r = upx_ucl_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
#if (WITH_ZSTD)
    else if (M_IS_ZSTD(method))
        r = upx_zstd_test_overlap(buf, tbuf, src_off, src_len, dst_len, method, cresult);
#endif
    else {
        throwInternalError("unknown compression method %d", method);
    }
    assert_noexcept(*dst_len <= orig_dst_len);
    return r;
}
References __acc_cte, assert_noexcept, buf, upx_compress_result_t::debug, M_IS_BZIP2, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, M_IS_ZSTD, upx_compress_result_t::Debug::method, opt, throwInternalError(), UPX_E_ERROR, upx_lzma_test_overlap(), and upx_ucl_test_overlap().
Referenced by ph_testOverlappingDecompression().
Variable Documentation
gitrev
const char gitrev[] extern
header
Definition at line 49 of file help.cpp.
Referenced by show_header(), upx_compiler_sanity_check(), and upx_main().
progname
const char* progname extern
Definition at line 47 of file main.cpp.
Referenced by main_get_envoptions(), main_get_options(), pr_error(), show_help(), show_usage(), show_version(), and upx_main().
upx_is_integral_v
template<class T > constexpr bool upx_is_integral_v = upx_is_integral<T>::value inline constexpr
Definition at line 130 of file conf.h.