My Project: src/filter/ct.h File Reference
ct.h File Reference
Macros
#define CT16(f, cond, addvalue, get, set)
16-bit calltrick ("naive")
#define CT32(f, cond, addvalue, get, set)
32-bit calltrick ("naive")
#define CT24ARM_LE(f, cond, addvalue, get, set)
24-bit ARM calltrick ("naive")
#define ARMCT_COND_le (((b[3] & 0x0f) == 0x0b))
#define CT24ARM_BE(f, cond, addvalue, get, set)
#define ARMCT_COND_be (((b[0] & 0x0f) == 0x0b))
#define CT26ARM_LE(f, cond, addvalue, get, set)
26-bit ARM calltrick ("naive")
#define ARMCT_COND (((b[3] & 0x7C) == 0x14))
Functions
static int f_ct16_e8 (Filter *f)
static int f_ct16_e9 (Filter *f)
static int f_ct16_e8e9 (Filter *f)
static int u_ct16_e8 (Filter *f)
static int u_ct16_e9 (Filter *f)
static int u_ct16_e8e9 (Filter *f)
static int s_ct16_e8 (Filter *f)
static int s_ct16_e9 (Filter *f)
static int s_ct16_e8e9 (Filter *f)
static int f_ct16_e8_bswap_le (Filter *f)
static int f_ct16_e9_bswap_le (Filter *f)
static int f_ct16_e8e9_bswap_le (Filter *f)
static int u_ct16_e8_bswap_le (Filter *f)
static int u_ct16_e9_bswap_le (Filter *f)
static int u_ct16_e8e9_bswap_le (Filter *f)
static int s_ct16_e8_bswap_le (Filter *f)
static int s_ct16_e9_bswap_le (Filter *f)
static int s_ct16_e8e9_bswap_le (Filter *f)
static int f_ct16_e8_bswap_be (Filter *f)
static int f_ct16_e9_bswap_be (Filter *f)
static int f_ct16_e8e9_bswap_be (Filter *f)
static int u_ct16_e8_bswap_be (Filter *f)
static int u_ct16_e9_bswap_be (Filter *f)
static int u_ct16_e8e9_bswap_be (Filter *f)
static int s_ct16_e8_bswap_be (Filter *f)
static int s_ct16_e9_bswap_be (Filter *f)
static int s_ct16_e8e9_bswap_be (Filter *f)
static int f_ct32_e8 (Filter *f)
static int f_ct32_e9 (Filter *f)
static int f_ct32_e8e9 (Filter *f)
static int u_ct32_e8 (Filter *f)
static int u_ct32_e9 (Filter *f)
static int u_ct32_e8e9 (Filter *f)
static int s_ct32_e8 (Filter *f)
static int s_ct32_e9 (Filter *f)
static int s_ct32_e8e9 (Filter *f)
static int f_ct32_e8_bswap_le (Filter *f)
static int f_ct32_e9_bswap_le (Filter *f)
static int f_ct32_e8e9_bswap_le (Filter *f)
static int u_ct32_e8_bswap_le (Filter *f)
static int u_ct32_e9_bswap_le (Filter *f)
static int u_ct32_e8e9_bswap_le (Filter *f)
static int s_ct32_e8_bswap_le (Filter *f)
static int s_ct32_e9_bswap_le (Filter *f)
static int s_ct32_e8e9_bswap_le (Filter *f)
static int f_ct32_e8_bswap_be (Filter *f)
static int f_ct32_e9_bswap_be (Filter *f)
static int f_ct32_e8e9_bswap_be (Filter *f)
static int u_ct32_e8_bswap_be (Filter *f)
static int u_ct32_e9_bswap_be (Filter *f)
static int u_ct32_e8e9_bswap_be (Filter *f)
static int s_ct32_e8_bswap_be (Filter *f)
static int s_ct32_e9_bswap_be (Filter *f)
static int s_ct32_e8e9_bswap_be (Filter *f)
static int f_ct24arm_le (Filter *f)
static int u_ct24arm_le (Filter *f)
static int s_ct24arm_le (Filter *f)
static int f_ct24arm_be (Filter *f)
static int u_ct24arm_be (Filter *f)
static int s_ct24arm_be (Filter *f)
static int f_ct26arm_le (Filter *f)
static int u_ct26arm_le (Filter *f)
static int s_ct26arm_le (Filter *f)
Macro Definition Documentation
ARMCT_COND
#define ARMCT_COND (((b[3] & 0x7C) == 0x14))
Definition at line 375 of file ct.h.
ARMCT_COND_be
#define ARMCT_COND_be (((b[0] & 0x0f) == 0x0b))
Definition at line 336 of file ct.h.
ARMCT_COND_le
#define ARMCT_COND_le (((b[3] & 0x0f) == 0x0b))
Definition at line 304 of file ct.h.
CT16
#define CT16 (f, cond, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 3;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b) + (addvalue));                                                           \
            f->calls++;                                                                            \
            b += 2 - 1;                                                                            \
        }                                                                                          \
    } while (++b < b_end);                                                                         \
    if (f->lastcall)                                                                               \
        f->lastcall += 2;                                                                          \
    return 0;
16-bit calltrick ("naive")
Definition at line 32 of file ct.h.
CT24ARM_BE
#define CT24ARM_BE (f, cond, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 4;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(1 + b, get(1 + b) + (addvalue));                                                   \
            f->calls++;                                                                            \
        }                                                                                          \
        b += 4;                                                                                    \
    } while (b < b_end);                                                                           \
    if (f->lastcall)                                                                               \
        f->lastcall += 4;                                                                          \
    return 0;
Definition at line 320 of file ct.h.
CT24ARM_LE
#define CT24ARM_LE (f, cond, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 4;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b) + (addvalue));                                                           \
            f->calls++;                                                                            \
        }                                                                                          \
        b += 4;                                                                                    \
    } while (b < b_end);                                                                           \
    if (f->lastcall)                                                                               \
        f->lastcall += 4;                                                                          \
    return 0;
24-bit ARM calltrick ("naive")
Definition at line 288 of file ct.h.
CT26ARM_LE
#define CT26ARM_LE (f, cond, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 4;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b) + (addvalue));                                                           \
            f->calls++;                                                                            \
        }                                                                                          \
        b += 4;                                                                                    \
    } while (b < b_end);                                                                           \
    if (f->lastcall)                                                                               \
        f->lastcall += 4;                                                                          \
    return 0;
26-bit ARM calltrick ("naive")
Definition at line 359 of file ct.h.
CT32
#define CT32 (f, cond, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 5;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b) + (addvalue));                                                           \
            f->calls++;                                                                            \
            b += 4 - 1;                                                                            \
        }                                                                                          \
    } while (++b < b_end);                                                                         \
    if (f->lastcall)                                                                               \
        f->lastcall += 4;                                                                          \
    return 0;
32-bit calltrick ("naive")
Definition at line 160 of file ct.h.
Function Documentation
f_ct16_e8()
static int f_ct16_e8 (Filter * f) static
Definition at line 50 of file ct.h.
{ CT16(f, (*b == 0xe8), a + f->addvalue, get_le16, set_le16) }
References Filter::addvalue, b, CT16, get_le16(), and set_le16().
f_ct16_e8_bswap_be()
static int f_ct16_e8_bswap_be (Filter * f) static
Definition at line 116 of file ct.h.
{
    CT16(f, (*b == 0xe8), a + f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CT16, get_be16(), and set_le16().
f_ct16_e8_bswap_le()
static int f_ct16_e8_bswap_le (Filter * f) static
Definition at line 77 of file ct.h.
{
    CT16(f, (*b == 0xe8), a + f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_be16().
f_ct16_e8e9()
static int f_ct16_e8e9 (Filter * f) static
Definition at line 54 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le16, set_le16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_le16().
f_ct16_e8e9_bswap_be()
static int f_ct16_e8e9_bswap_be (Filter * f) static
Definition at line 124 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CT16, get_be16(), and set_le16().
f_ct16_e8e9_bswap_le()
static int f_ct16_e8e9_bswap_le (Filter * f) static
Definition at line 85 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_be16().
f_ct16_e9()
static int f_ct16_e9 (Filter * f) static
Definition at line 52 of file ct.h.
{ CT16(f, (*b == 0xe9), a + f->addvalue, get_le16, set_le16) }
References Filter::addvalue, b, CT16, get_le16(), and set_le16().
f_ct16_e9_bswap_be()
static int f_ct16_e9_bswap_be (Filter * f) static
Definition at line 120 of file ct.h.
{
    CT16(f, (*b == 0xe9), a + f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CT16, get_be16(), and set_le16().
f_ct16_e9_bswap_le()
static int f_ct16_e9_bswap_le (Filter * f) static
Definition at line 81 of file ct.h.
{
    CT16(f, (*b == 0xe9), a + f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_be16().
f_ct24arm_be()
static int f_ct24arm_be (Filter * f) static
Definition at line 338 of file ct.h.
{
    CT24ARM_BE(f, ARMCT_COND_be, a / 4 + f->addvalue, get_be24, set_be24)
}
References Filter::addvalue, ARMCT_COND_be, CT24ARM_BE, get_be24(), and set_be24().
f_ct24arm_le()
static int f_ct24arm_le (Filter * f) static
Definition at line 306 of file ct.h.
{
    CT24ARM_LE(f, ARMCT_COND_le, a / 4 + f->addvalue, get_le24, set_le24)
}
References Filter::addvalue, ARMCT_COND_le, CT24ARM_LE, get_le24(), and set_le24().
f_ct26arm_le()
static int f_ct26arm_le (Filter * f) static
Definition at line 377 of file ct.h.
{
    CT26ARM_LE(f, ARMCT_COND, a / 4 + f->addvalue, get_le26, set_le26)
}
References Filter::addvalue, ARMCT_COND, CT26ARM_LE, get_le26(), and set_le26().
f_ct32_e8()
static int f_ct32_e8 (Filter * f) static
Definition at line 178 of file ct.h.
{ CT32(f, (*b == 0xe8), a + f->addvalue, get_le32, set_le32) }
References Filter::addvalue, b, CT32, get_le32(), and set_le32().
f_ct32_e8_bswap_be()
static int f_ct32_e8_bswap_be (Filter * f) static
Definition at line 244 of file ct.h.
{
    CT32(f, (*b == 0xe8), a + f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CT32, get_be32(), and set_le32().
f_ct32_e8_bswap_le()
static int f_ct32_e8_bswap_le (Filter * f) static
Definition at line 205 of file ct.h.
{
    CT32(f, (*b == 0xe8), a + f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_be32().
f_ct32_e8e9()
static int f_ct32_e8e9 (Filter * f) static
Definition at line 182 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le32, set_le32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_le32().
f_ct32_e8e9_bswap_be()
static int f_ct32_e8e9_bswap_be (Filter * f) static
Definition at line 252 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CT32, get_be32(), and set_le32().
f_ct32_e8e9_bswap_le()
static int f_ct32_e8e9_bswap_le (Filter * f) static
Definition at line 213 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_be32().
f_ct32_e9()
static int f_ct32_e9 (Filter * f) static
Definition at line 180 of file ct.h.
{ CT32(f, (*b == 0xe9), a + f->addvalue, get_le32, set_le32) }
References Filter::addvalue, b, CT32, get_le32(), and set_le32().
f_ct32_e9_bswap_be()
static int f_ct32_e9_bswap_be (Filter * f) static
Definition at line 248 of file ct.h.
{
    CT32(f, (*b == 0xe9), a + f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CT32, get_be32(), and set_le32().
f_ct32_e9_bswap_le()
static int f_ct32_e9_bswap_le (Filter * f) static
Definition at line 209 of file ct.h.
{
    CT32(f, (*b == 0xe9), a + f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_be32().
s_ct16_e8()
static int s_ct16_e8 (Filter * f) static
Definition at line 68 of file ct.h.
{ CT16(f, (*b == 0xe8), a + f->addvalue, get_le16, set_dummy) }
References Filter::addvalue, b, CT16, get_le16(), and set_dummy.
s_ct16_e8_bswap_be()
static int s_ct16_e8_bswap_be (Filter * f) static
Definition at line 142 of file ct.h.
{
    CT16(f, (*b == 0xe8), a + f->addvalue, get_le16, set_dummy)
}
References Filter::addvalue, b, CT16, get_le16(), and set_dummy.
s_ct16_e8_bswap_le()
static int s_ct16_e8_bswap_le (Filter * f) static
Definition at line 103 of file ct.h.
{
    CT16(f, (*b == 0xe8), a + f->addvalue, get_be16, set_dummy)
}
References Filter::addvalue, b, CT16, get_be16(), and set_dummy.
s_ct16_e8e9()
static int s_ct16_e8e9 (Filter * f) static
Definition at line 72 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le16, set_dummy)
}
References Filter::addvalue, b, CT16, get_le16(), and set_dummy.
s_ct16_e8e9_bswap_be()
static int s_ct16_e8e9_bswap_be (Filter * f) static
Definition at line 150 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le16, set_dummy)
}
References Filter::addvalue, b, CT16, get_le16(), and set_dummy.
s_ct16_e8e9_bswap_le()
static int s_ct16_e8e9_bswap_le (Filter * f) static
Definition at line 111 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_be16, set_dummy)
}
References Filter::addvalue, b, CT16, get_be16(), and set_dummy.
s_ct16_e9()
static int s_ct16_e9 (Filter * f) static
Definition at line 70 of file ct.h.
{ CT16(f, (*b == 0xe9), a + f->addvalue, get_le16, set_dummy) }
References Filter::addvalue, b, CT16, get_le16(), and set_dummy.
s_ct16_e9_bswap_be()
static int s_ct16_e9_bswap_be (Filter * f) static
Definition at line 146 of file ct.h.
{
    CT16(f, (*b == 0xe9), a + f->addvalue, get_le16, set_dummy)
}
References Filter::addvalue, b, CT16, get_le16(), and set_dummy.
s_ct16_e9_bswap_le()
static int s_ct16_e9_bswap_le (Filter * f) static
Definition at line 107 of file ct.h.
{
    CT16(f, (*b == 0xe9), a + f->addvalue, get_be16, set_dummy)
}
References Filter::addvalue, b, CT16, get_be16(), and set_dummy.
s_ct24arm_be()
static int s_ct24arm_be (Filter * f) static
Definition at line 346 of file ct.h.
{
    CT24ARM_BE(f, ARMCT_COND_be, a + f->addvalue, get_be24, set_dummy)
}
References Filter::addvalue, ARMCT_COND_be, CT24ARM_BE, get_be24(), and set_dummy.
s_ct24arm_le()
static int s_ct24arm_le (Filter * f) static
Definition at line 314 of file ct.h.
{
    CT24ARM_LE(f, ARMCT_COND_le, a + f->addvalue, get_le24, set_dummy)
}
References Filter::addvalue, ARMCT_COND_le, CT24ARM_LE, get_le24(), and set_dummy.
s_ct26arm_le()
static int s_ct26arm_le (Filter * f) static
Definition at line 385 of file ct.h.
{
    CT26ARM_LE(f, ARMCT_COND, a + f->addvalue, get_le26, set_dummy)
}
References Filter::addvalue, ARMCT_COND, CT26ARM_LE, get_le26(), and set_dummy.
s_ct32_e8()
static int s_ct32_e8 (Filter * f) static
Definition at line 196 of file ct.h.
{ CT32(f, (*b == 0xe8), a + f->addvalue, get_le32, set_dummy) }
References Filter::addvalue, b, CT32, get_le32(), and set_dummy.
s_ct32_e8_bswap_be()
static int s_ct32_e8_bswap_be (Filter * f) static
Definition at line 270 of file ct.h.
{
    CT32(f, (*b == 0xe8), a + f->addvalue, get_le32, set_dummy)
}
References Filter::addvalue, b, CT32, get_le32(), and set_dummy.
s_ct32_e8_bswap_le()
static int s_ct32_e8_bswap_le (Filter * f) static
Definition at line 231 of file ct.h.
{
    CT32(f, (*b == 0xe8), a + f->addvalue, get_be32, set_dummy)
}
References Filter::addvalue, b, CT32, get_be32(), and set_dummy.
s_ct32_e8e9()
static int s_ct32_e8e9 (Filter * f) static
Definition at line 200 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le32, set_dummy)
}
References Filter::addvalue, b, CT32, get_le32(), and set_dummy.
s_ct32_e8e9_bswap_be()
static int s_ct32_e8e9_bswap_be (Filter * f) static
Definition at line 278 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_le32, set_dummy)
}
References Filter::addvalue, b, CT32, get_le32(), and set_dummy.
s_ct32_e8e9_bswap_le()
static int s_ct32_e8e9_bswap_le (Filter * f) static
Definition at line 239 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), a + f->addvalue, get_be32, set_dummy)
}
References Filter::addvalue, b, CT32, get_be32(), and set_dummy.
s_ct32_e9()
static int s_ct32_e9 (Filter * f) static
Definition at line 198 of file ct.h.
{ CT32(f, (*b == 0xe9), a + f->addvalue, get_le32, set_dummy) }
References Filter::addvalue, b, CT32, get_le32(), and set_dummy.
s_ct32_e9_bswap_be()
static int s_ct32_e9_bswap_be (Filter * f) static
Definition at line 274 of file ct.h.
{
    CT32(f, (*b == 0xe9), a + f->addvalue, get_le32, set_dummy)
}
References Filter::addvalue, b, CT32, get_le32(), and set_dummy.
s_ct32_e9_bswap_le()
static int s_ct32_e9_bswap_le (Filter * f) static
Definition at line 235 of file ct.h.
{
    CT32(f, (*b == 0xe9), a + f->addvalue, get_be32, set_dummy)
}
References Filter::addvalue, b, CT32, get_be32(), and set_dummy.
u_ct16_e8()
static int u_ct16_e8 (Filter * f) static
Definition at line 59 of file ct.h.
{ CT16(f, (*b == 0xe8), 0 - a - f->addvalue, get_le16, set_le16) }
References Filter::addvalue, b, CT16, get_le16(), and set_le16().
u_ct16_e8_bswap_be()
static int u_ct16_e8_bswap_be (Filter * f) static
Definition at line 129 of file ct.h.
{
    CT16(f, (*b == 0xe8), 0 - a - f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_be16().
u_ct16_e8_bswap_le()
static int u_ct16_e8_bswap_le (Filter * f) static
Definition at line 90 of file ct.h.
{
    CT16(f, (*b == 0xe8), 0 - a - f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CT16, get_be16(), and set_le16().
u_ct16_e8e9()
static int u_ct16_e8e9 (Filter * f) static
Definition at line 63 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), 0 - a - f->addvalue, get_le16, set_le16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_le16().
u_ct16_e8e9_bswap_be()
static int u_ct16_e8e9_bswap_be (Filter * f) static
Definition at line 137 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), 0 - a - f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_be16().
u_ct16_e8e9_bswap_le()
static int u_ct16_e8e9_bswap_le (Filter * f) static
Definition at line 98 of file ct.h.
{
    CT16(f, (*b == 0xe8 || *b == 0xe9), 0 - a - f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CT16, get_be16(), and set_le16().
u_ct16_e9()
static int u_ct16_e9 (Filter * f) static
Definition at line 61 of file ct.h.
{ CT16(f, (*b == 0xe9), 0 - a - f->addvalue, get_le16, set_le16) }
References Filter::addvalue, b, CT16, get_le16(), and set_le16().
u_ct16_e9_bswap_be()
static int u_ct16_e9_bswap_be (Filter * f) static
Definition at line 133 of file ct.h.
{
    CT16(f, (*b == 0xe9), 0 - a - f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CT16, get_le16(), and set_be16().
u_ct16_e9_bswap_le()
static int u_ct16_e9_bswap_le (Filter * f) static
Definition at line 94 of file ct.h.
{
    CT16(f, (*b == 0xe9), 0 - a - f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CT16, get_be16(), and set_le16().
u_ct24arm_be()
static int u_ct24arm_be (Filter * f) static
Definition at line 342 of file ct.h.
{
    CT24ARM_BE(f, ARMCT_COND_be, 0 - a / 4 - f->addvalue, get_be24, set_be24)
}
References Filter::addvalue, ARMCT_COND_be, CT24ARM_BE, get_be24(), and set_be24().
u_ct24arm_le()
static int u_ct24arm_le (Filter * f) static
Definition at line 310 of file ct.h.
{
    CT24ARM_LE(f, ARMCT_COND_le, 0 - a / 4 - f->addvalue, get_le24, set_le24)
}
References Filter::addvalue, ARMCT_COND_le, CT24ARM_LE, get_le24(), and set_le24().
u_ct26arm_le()
static int u_ct26arm_le (Filter * f) static
Definition at line 381 of file ct.h.
{
    CT26ARM_LE(f, ARMCT_COND, 0 - a / 4 - f->addvalue, get_le26, set_le26)
}
References Filter::addvalue, ARMCT_COND, CT26ARM_LE, get_le26(), and set_le26().
u_ct32_e8()
static int u_ct32_e8 (Filter * f) static
Definition at line 187 of file ct.h.
{ CT32(f, (*b == 0xe8), 0 - a - f->addvalue, get_le32, set_le32) }
References Filter::addvalue, b, CT32, get_le32(), and set_le32().
u_ct32_e8_bswap_be()
static int u_ct32_e8_bswap_be (Filter * f) static
Definition at line 257 of file ct.h.
{
    CT32(f, (*b == 0xe8), 0 - a - f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_be32().
u_ct32_e8_bswap_le()
static int u_ct32_e8_bswap_le (Filter * f) static
Definition at line 218 of file ct.h.
{
    CT32(f, (*b == 0xe8), 0 - a - f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CT32, get_be32(), and set_le32().
u_ct32_e8e9()
static int u_ct32_e8e9 (Filter * f) static
Definition at line 191 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), 0 - a - f->addvalue, get_le32, set_le32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_le32().
u_ct32_e8e9_bswap_be()
static int u_ct32_e8e9_bswap_be (Filter * f) static
Definition at line 265 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), 0 - a - f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_be32().
u_ct32_e8e9_bswap_le()
static int u_ct32_e8e9_bswap_le (Filter * f) static
Definition at line 226 of file ct.h.
{
    CT32(f, (*b == 0xe8 || *b == 0xe9), 0 - a - f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CT32, get_be32(), and set_le32().
u_ct32_e9()
static int u_ct32_e9 (Filter * f) static
Definition at line 189 of file ct.h.
{ CT32(f, (*b == 0xe9), 0 - a - f->addvalue, get_le32, set_le32) }
References Filter::addvalue, b, CT32, get_le32(), and set_le32().
u_ct32_e9_bswap_be()
static int u_ct32_e9_bswap_be (Filter * f) static
Definition at line 261 of file ct.h.
{
    CT32(f, (*b == 0xe9), 0 - a - f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CT32, get_le32(), and set_be32().
u_ct32_e9_bswap_le()
static int u_ct32_e9_bswap_le (Filter * f) static
Definition at line 222 of file ct.h.
{
    CT32(f, (*b == 0xe9), 0 - a - f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CT32, get_be32(), and set_le32().