My Project: src/filter/ctoj.h File Reference
ctoj.h File Reference
Functions
static int F (Filter *f)
filter / scan
Function Documentation
F()
static int F (Filter * f) static
filter / scan
Definition at line 36 of file ctoj.h.
{
#ifdef U
    // filter
    byte *b = f->buf;
#else
    // scan
    const byte *b = f->buf;
#endif
    const unsigned addvalue = f->addvalue;
    const unsigned size = f->buf_len;
    unsigned ic, jc, kc;
    unsigned calls = 0, noncalls = 0, noncalls2 = 0;
    unsigned lastnoncall = size, lastcall = 0;
    // find a 16 MiB large empty address space
    {
        unsigned char buf[256];
        memset(buf, 0, 256);
        for (ic = 0; ic < size - 5; ic++) {
            if (!COND(b, ic, lastcall))
                continue;
            jc = get_le32(b + ic + 1) + ic + 1;
            if (jc < size) {
                if (jc + addvalue >= (1u << 24)) // hi 8 bits won't be cto8
                    return -1;
            } else
                buf[b[ic + 1]] |= 1;
        }
        if (getcto(f, buf) < 0)
            return -1;
    }
    const unsigned char cto8 = f->cto;
#ifdef U
    const unsigned cto = (unsigned) f->cto << 24;
#endif
    for (ic = 0; ic < size - 5; ic++) {
        if (!COND(b, ic, lastcall))
            continue;
        jc = get_le32(b + ic + 1) + ic + 1;
        // try to detect 'real' calls only
        if (jc < size) {
            assert(jc + addvalue < (1u << 24)); // hi 8 bits won't be cto8
#ifdef U
            set_be32(b + ic + 1, jc + addvalue + cto);
#endif
            if (ic - lastnoncall < 5) {
                // check the last 4 bytes before this call
                for (kc = 4; kc; kc--)
                    if (COND(b, ic - kc, lastcall) && b[ic - kc + 1] == cto8)
                        break;
                if (kc) {
#ifdef U
                    // restore original
                    set_le32(b + ic + 1, jc - ic - 1);
#endif
                    if (b[ic + 1] == cto8)
                        return 1; // fail - buffer not restored
                    lastnoncall = ic;
                    noncalls2++;
                    continue;
                }
            }
            calls++;
            ic += 4;
            lastcall = ic + 1;
        } else {
            assert(b[ic + 1] != cto8); // this should not happen
            lastnoncall = ic;
            noncalls++;
        }
    }
    f->calls = calls;
    f->noncalls = noncalls;
    f->lastcall = lastcall;
#if 0 || defined(TESTING)
    printf("\ncalls=%d noncalls=%d noncalls2=%d text_size=%x calltrickoffset=%x\n",calls,noncalls,noncalls2,size,cto);
#endif
    UNUSED(noncalls2);
    return 0;
}
References Filter::addvalue, b, Filter::buf, buf, Filter::buf_len, Filter::calls, COND, Filter::cto, get_le32(), getcto(), Filter::lastcall, memset(), Filter::noncalls, set_be32(), set_le32(), size(), and UNUSED.