My Project: src/filter/ctsw.h File Reference
ctsw.h File Reference
Macros
#define CTSW16(f, cond1, cond2, addvalue, get, set)
16-bit call-/swaptrick ("naive")
#define CTSW32(f, cond1, cond2, addvalue, get, set)
32-bit call-/swaptrick ("naive")
Functions
static int f_ctsw16_e8_e9 (Filter *f)
static int f_ctsw16_e9_e8 (Filter *f)
static int u_ctsw16_e8_e9 (Filter *f)
static int u_ctsw16_e9_e8 (Filter *f)
static int s_ctsw16_e8_e9 (Filter *f)
static int s_ctsw16_e9_e8 (Filter *f)
static int f_ctsw32_e8_e9 (Filter *f)
static int f_ctsw32_e9_e8 (Filter *f)
static int u_ctsw32_e8_e9 (Filter *f)
static int u_ctsw32_e9_e8 (Filter *f)
static int s_ctsw32_e8_e9 (Filter *f)
static int s_ctsw32_e9_e8 (Filter *f)
Macro Definition Documentation
CTSW16
#define CTSW16 (f, cond1, cond2, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 3;                                                              \
    do {                                                                                           \
        if (cond1) {                                                                               \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b) + (addvalue));                                                           \
            f->calls++;                                                                            \
            b += 2 - 1;                                                                            \
        } else if (cond2) {                                                                        \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b));                                                                        \
            f->calls++;                                                                            \
            b += 2 - 1;                                                                            \
        }                                                                                          \
    } while (++b < b_end);                                                                         \
    if (f->lastcall)                                                                               \
        f->lastcall += 2;                                                                          \
    return 0;
16-bit call-/swaptrick ("naive")
Definition at line 32 of file ctsw.h.
CTSW32
#define CTSW32 (f, cond1, cond2, addvalue, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 5;                                                              \
    do {                                                                                           \
        if (cond1) {                                                                               \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b) + (addvalue));                                                           \
            f->calls++;                                                                            \
            b += 4 - 1;                                                                            \
        } else if (cond2) {                                                                        \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b));                                                                        \
            f->calls++;                                                                            \
            b += 4 - 1;                                                                            \
        }                                                                                          \
    } while (++b < b_end);                                                                         \
    if (f->lastcall)                                                                               \
        f->lastcall += 4;                                                                          \
    return 0;
32-bit call-/swaptrick ("naive")
Definition at line 89 of file ctsw.h.
Function Documentation
f_ctsw16_e8_e9()
static int f_ctsw16_e8_e9 (Filter * f) static
Definition at line 57 of file ctsw.h.
{
    CTSW16(f, (*b == 0xe8), (*b == 0xe9), a + f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CTSW16, get_le16(), and set_be16().
f_ctsw16_e9_e8()
static int f_ctsw16_e9_e8 (Filter * f) static
Definition at line 61 of file ctsw.h.
{
    CTSW16(f, (*b == 0xe9), (*b == 0xe8), a + f->addvalue, get_le16, set_be16)
}
References Filter::addvalue, b, CTSW16, get_le16(), and set_be16().
f_ctsw32_e8_e9()
static int f_ctsw32_e8_e9 (Filter * f) static
Definition at line 114 of file ctsw.h.
{
    CTSW32(f, (*b == 0xe8), (*b == 0xe9), a + f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CTSW32, get_le32(), and set_be32().
f_ctsw32_e9_e8()
static int f_ctsw32_e9_e8 (Filter * f) static
Definition at line 118 of file ctsw.h.
{
    CTSW32(f, (*b == 0xe9), (*b == 0xe8), a + f->addvalue, get_le32, set_be32)
}
References Filter::addvalue, b, CTSW32, get_le32(), and set_be32().
s_ctsw16_e8_e9()
static int s_ctsw16_e8_e9 (Filter * f) static
Definition at line 75 of file ctsw.h.
{
    CTSW16(f, (*b == 0xe8), (*b == 0xe9), a + f->addvalue, get_le16, set_dummy)
}
References Filter::addvalue, b, CTSW16, get_le16(), and set_dummy.
s_ctsw16_e9_e8()
static int s_ctsw16_e9_e8 (Filter * f) static
Definition at line 79 of file ctsw.h.
{
    CTSW16(f, (*b == 0xe9), (*b == 0xe8), a + f->addvalue, get_le16, set_dummy)
}
References Filter::addvalue, b, CTSW16, get_le16(), and set_dummy.
s_ctsw32_e8_e9()
static int s_ctsw32_e8_e9 (Filter * f) static
Definition at line 132 of file ctsw.h.
{
    CTSW32(f, (*b == 0xe8), (*b == 0xe9), a + f->addvalue, get_le32, set_dummy)
}
References Filter::addvalue, b, CTSW32, get_le32(), and set_dummy.
s_ctsw32_e9_e8()
static int s_ctsw32_e9_e8 (Filter * f) static
Definition at line 136 of file ctsw.h.
{
    CTSW32(f, (*b == 0xe9), (*b == 0xe8), a + f->addvalue, get_le32, set_dummy)
}
References Filter::addvalue, b, CTSW32, get_le32(), and set_dummy.
u_ctsw16_e8_e9()
static int u_ctsw16_e8_e9 (Filter * f) static
Definition at line 66 of file ctsw.h.
{
    CTSW16(f, (*b == 0xe8), (*b == 0xe9), 0 - a - f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CTSW16, get_be16(), and set_le16().
u_ctsw16_e9_e8()
static int u_ctsw16_e9_e8 (Filter * f) static
Definition at line 70 of file ctsw.h.
{
    CTSW16(f, (*b == 0xe9), (*b == 0xe8), 0 - a - f->addvalue, get_be16, set_le16)
}
References Filter::addvalue, b, CTSW16, get_be16(), and set_le16().
u_ctsw32_e8_e9()
static int u_ctsw32_e8_e9 (Filter * f) static
Definition at line 123 of file ctsw.h.
{
    CTSW32(f, (*b == 0xe8), (*b == 0xe9), 0 - a - f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CTSW32, get_be32(), and set_le32().
u_ctsw32_e9_e8()
static int u_ctsw32_e9_e8 (Filter * f) static
Definition at line 127 of file ctsw.h.
{
    CTSW32(f, (*b == 0xe9), (*b == 0xe8), 0 - a - f->addvalue, get_be32, set_le32)
}
References Filter::addvalue, b, CTSW32, get_be32(), and set_le32().