My Project: src/check/dt_xspan.cpp File Reference
dt_xspan.cpp File Reference
#include "../conf.h"
Classes
struct anonymous_namespace{dt_xspan.cpp}::PointerTraits< T >
Namespaces
namespace anonymous_namespace{dt_xspan.cpp}
misc
Functions
TEST_CASE ("raw_bytes ptr")
raw_bytes
TEST_CASE ("raw_bytes bounded array")
TEST_CASE ("basic xspan usage")
basic xspan
TEST_CASE ("xspan array access")
Function Documentation
TEST_CASE() [1/4]
TEST_CASE ("basic xspan usage")
basic xspan
Definition at line 66 of file dt_xspan.cpp.
{
    alignas(4) char buf[4] = {0, 1, 2, 3};
    SUBCASE("XSPAN_x") {
        XSPAN_0(char) a0 = nullptr;
        XSPAN_0(char) b0 = buf;
        XSPAN_P(char) bp = buf;
        XSPAN_0(char) c0 = XSPAN_0_MAKE(char, buf);
        XSPAN_P(char) cp = XSPAN_P_MAKE(char, buf);
        XSPAN_S(char) cs = XSPAN_S_MAKE(char, buf, sizeof(buf));
        XSPAN_0(const char) const x0 = XSPAN_0_MAKE(const char, buf);
        XSPAN_P(const char) const xp = XSPAN_P_MAKE(const char, buf);
        XSPAN_S(const char) const xs = XSPAN_S_MAKE(const char, buf, sizeof(buf));
        XSPAN_P(const char) const yp = xs;
        XSPAN_0(const char) const z0p = yp;
        XSPAN_0(const char) const z0s = xs;
        CHECK((a0 == nullptr));
        CHECK(c0 == b0);
        CHECK(cp == bp);
        CHECK(cs == bp);
        CHECK(x0 == z0p);
        CHECK(xp == z0s);
        CHECK_NOTHROW(raw_bytes(a0, 0));
        CHECK_THROWS(raw_bytes(a0, 1));
        CHECK_THROWS(raw_index_bytes(a0, 0, 0));
        CHECK(raw_bytes(b0, 0) == buf);
        CHECK(raw_bytes(bp, 0) == buf);
        // info: these will fail if we ever add an overload for bounded-arrays
#if WITH_XSPAN >= 2
        CHECK(b0.raw_size_in_bytes() == 0u);
        CHECK(bp.raw_size_in_bytes() == 0u);
#endif
        CHECK(raw_bytes(b0, 999999) == buf);
        CHECK(raw_bytes(bp, 999999) == buf);
        CHECK(raw_bytes(c0, 4) == buf);
        CHECK(raw_index_bytes(c0, 1, 3) == buf + 1);
        CHECK(raw_bytes(cp, 4) == buf);
        CHECK(raw_index_bytes(cp, 1, 3) == buf + 1);
        CHECK(raw_bytes(cs, 4) == buf);
        CHECK(raw_index_bytes(cs, 1, 3) == buf + 1);
#if WITH_XSPAN >= 2
        CHECK_THROWS(raw_bytes(cs, 5));
        CHECK_THROWS(raw_index_bytes(cs, 1, 4));
#endif
        XSPAN_0(upx_uint16_t) c0_2 = XSPAN_TYPE_CAST(upx_uint16_t, c0 + 2);
        XSPAN_P(upx_uint16_t) cp_2 = XSPAN_TYPE_CAST(upx_uint16_t, cp + 2);
        XSPAN_S(upx_uint16_t) cs_2 = XSPAN_TYPE_CAST(upx_uint16_t, cs + 2);
        CHECK(ptr_udiff_bytes(c0_2, c0) == 2u);
        CHECK(ptr_udiff_bytes(cp_2, c0) == 2u);
        CHECK(ptr_udiff_bytes(cs_2, c0) == 2u);
        CHECK(ptr_udiff_bytes(c0_2, cp) == 2u);
        CHECK(ptr_udiff_bytes(cp_2, cp) == 2u);
        CHECK(ptr_udiff_bytes(cs_2, cp) == 2u);
        CHECK(ptr_udiff_bytes(c0_2, cs) == 2u);
        CHECK(ptr_udiff_bytes(cp_2, cs) == 2u);
        CHECK(ptr_udiff_bytes(cs_2, cs) == 2u);
        XSPAN_0(upx_uint16_t) c0_2b = XSPAN_TYPE_CAST(upx_uint16_t, c0) + 1;
        XSPAN_P(upx_uint16_t) cp_2b = XSPAN_TYPE_CAST(upx_uint16_t, cp) + 1;
        XSPAN_S(upx_uint16_t) cs_2b = XSPAN_TYPE_CAST(upx_uint16_t, cs) + 1;
        CHECK(c0_2 == c0_2b);
        CHECK(cp_2 == cp_2b);
        CHECK(cs_2 == cs_2b);
        CHECK(sizeof(*c0) == 1u);
        CHECK(sizeof(*c0_2) == 2u);
    }
    SUBCASE("XSPAN_x_VAR") {
        XSPAN_0_VAR(char, b0, buf);
        XSPAN_P_VAR(char, bp, buf);
        XSPAN_0_VAR(char, c0, buf, sizeof(buf));
        XSPAN_P_VAR(char, cp, buf, sizeof(buf));
        XSPAN_S_VAR(char, cs, buf, sizeof(buf));
        XSPAN_0_VAR(char, d0, buf + 1, sizeof(buf), buf);
        XSPAN_P_VAR(char, dp, buf + 1, sizeof(buf), buf);
        XSPAN_S_VAR(char, ds, buf + 1, sizeof(buf), buf);
        XSPAN_0_VAR(const char, const x0, buf, sizeof(buf));
        XSPAN_P_VAR(const char, const xp, buf, sizeof(buf));
        XSPAN_S_VAR(const char, const xs, buf, sizeof(buf));
        XSPAN_P_VAR(const char, const yp, xs);
        XSPAN_0_VAR(const char, const z0p, yp);
        XSPAN_0_VAR(const char, const z0s, xs);
        CHECK(c0 == b0);
        CHECK(cp == bp);
        CHECK(cs == bp);
        CHECK(d0 == dp);
        CHECK(d0 == ds);
        CHECK(x0 == z0p);
        CHECK(xp == z0s);
#if WITH_XSPAN >= 1 || __cplusplus >= 201103L
        XSPAN_0_VAR(char, a0, nullptr);
        CHECK((a0 == nullptr));
        CHECK_NOTHROW(raw_bytes(a0, 0));
        CHECK_THROWS(raw_bytes(a0, 1));
        CHECK_THROWS(raw_index_bytes(a0, 0, 0));
#endif
        CHECK(raw_bytes(b0, 0) == buf);
        CHECK(raw_bytes(bp, 0) == buf);
        // info: these will fail if we ever add an overload for bounded-arrays
#if WITH_XSPAN >= 2
        CHECK(b0.raw_size_in_bytes() == 0u);
        CHECK(bp.raw_size_in_bytes() == 0u);
#endif
        CHECK(raw_bytes(b0, 999999) == buf);
        CHECK(raw_bytes(bp, 999999) == buf);
        CHECK(raw_bytes(c0, 4) == buf);
        CHECK(raw_index_bytes(c0, 1, 3) == buf + 1);
        CHECK(raw_bytes(cp, 4) == buf);
        CHECK(raw_index_bytes(cp, 1, 3) == buf + 1);
        CHECK(raw_bytes(cs, 4) == buf);
        CHECK(raw_index_bytes(cs, 1, 3) == buf + 1);
#if WITH_XSPAN >= 2
        CHECK_THROWS(raw_bytes(cs, 5));
        CHECK_THROWS(raw_index_bytes(cs, 1, 4));
#endif
        XSPAN_0_VAR(upx_uint16_t, c0_2, XSPAN_TYPE_CAST(upx_uint16_t, c0 + 2));
        XSPAN_P_VAR(upx_uint16_t, cp_2, XSPAN_TYPE_CAST(upx_uint16_t, cp + 2));
        XSPAN_S_VAR(upx_uint16_t, cs_2, XSPAN_TYPE_CAST(upx_uint16_t, cs + 2));
        CHECK(ptr_udiff_bytes(c0_2, c0) == 2u);
        CHECK(ptr_udiff_bytes(cp_2, c0) == 2u);
        CHECK(ptr_udiff_bytes(cs_2, c0) == 2u);
        CHECK(ptr_udiff_bytes(c0_2, cp) == 2u);
        CHECK(ptr_udiff_bytes(cp_2, cp) == 2u);
        CHECK(ptr_udiff_bytes(cs_2, cp) == 2u);
        CHECK(ptr_udiff_bytes(c0_2, cs) == 2u);
        CHECK(ptr_udiff_bytes(cp_2, cs) == 2u);
        CHECK(ptr_udiff_bytes(cs_2, cs) == 2u);
        XSPAN_0_VAR(upx_uint16_t, c0_2b, XSPAN_TYPE_CAST(upx_uint16_t, c0) + 1);
        XSPAN_P_VAR(upx_uint16_t, cp_2b, XSPAN_TYPE_CAST(upx_uint16_t, cp) + 1);
        XSPAN_S_VAR(upx_uint16_t, cs_2b, XSPAN_TYPE_CAST(upx_uint16_t, cs) + 1);
        CHECK(c0_2 == c0_2b);
        CHECK(cp_2 == cp_2b);
        CHECK(cs_2 == cs_2b);
        CHECK(sizeof(*c0) == 1u);
        CHECK(sizeof(*c0_2) == 2u);
    }
    SUBCASE("xspan in class") {
        struct MyType {
            XSPAN_0(char) s0;
            XSPAN_P(char) sp;
            XSPAN_S(char) ss;
#if __cplusplus >= 201103L
            XSPAN_0(char) x0 = nullptr;
#endif
#if WITH_XSPAN >= 2
            // much nicer syntax when using fully checked xspan:
            MyType(char *b, size_t n, bool) : s0(b, n), sp(b, n), ss(b, n) {}
#endif
            MyType(char *b, size_t n)
                : s0(XSPAN_0_MAKE(char, b, n)), sp(XSPAN_P_MAKE(char, b, n)),
                  ss(XSPAN_S_MAKE(char, b, n)) {
                UNUSED(n);
            }
        };
        MyType x(buf, sizeof(buf));
        MyType y = MyType(buf, sizeof(buf));
        CHECK(x.s0 == y.sp);
    }
}
References a0, b, buf, n, ptr_udiff_bytes(), raw_bytes(), raw_index_bytes(), sp, UNUSED, XSPAN_0, XSPAN_0_MAKE, XSPAN_0_VAR, XSPAN_P, XSPAN_P_MAKE, XSPAN_P_VAR, XSPAN_S, XSPAN_S_MAKE, XSPAN_S_VAR, and XSPAN_TYPE_CAST.
TEST_CASE() [2/4]
TEST_CASE ("raw_bytes bounded array")
Definition at line 49 of file dt_xspan.cpp.
{
    upx_uint16_t buf[4];
    CHECK_NOTHROW(raw_bytes(buf, 8));
    CHECK_THROWS(raw_bytes(buf, 9));
    CHECK_NOTHROW(raw_index_bytes(buf, 4, 0));
    CHECK_THROWS(raw_index_bytes(buf, 4, 1));
    CHECK_NOTHROW(raw_index_bytes(buf, 3, 2));
    CHECK_THROWS(raw_index_bytes(buf, 3, 3));
    CHECK(ptr_udiff_bytes(raw_index_bytes(buf, 1, 1), buf) == 2u);
    CHECK(ptr_udiff_bytes(raw_index_bytes(buf, 4, 0), buf) == 8u);
    UNUSED(buf);
}
References buf, ptr_udiff_bytes(), raw_bytes(), raw_index_bytes(), and UNUSED.
TEST_CASE() [3/4]
TEST_CASE ("raw_bytes ptr")
raw_bytes
Definition at line 35 of file dt_xspan.cpp.
{
    upx_uint16_t *ptr = nullptr;
    CHECK_NOTHROW(raw_bytes(ptr, 0));
    CHECK_THROWS(raw_bytes(ptr, 1));
    CHECK_THROWS(raw_index_bytes(ptr, 0, 0));
    CHECK_THROWS(raw_index_bytes(ptr, 1, 0));
    CHECK_THROWS(raw_index_bytes(ptr, 0, 1));
    upx_uint16_t buf[4];
    ptr = buf;
    CHECK(ptr_udiff_bytes(raw_index_bytes(ptr, 1, 1), ptr) == 2u);
    CHECK(ptr_udiff_bytes(raw_index_bytes(ptr, 4, 0), ptr) == 8u);
    UNUSED(ptr);
}
References buf, ptr, ptr_udiff_bytes(), raw_bytes(), raw_index_bytes(), and UNUSED.
TEST_CASE() [4/4]
TEST_CASE ("xspan array access")
Definition at line 244 of file dt_xspan.cpp.
{
    const size_t N = 16;
    char buf[N];
    memset(buf, 0, sizeof(buf));
    XSPAN_0_VAR(char, c0, buf, sizeof(buf));
    XSPAN_P_VAR(char, cp, buf, sizeof(buf));
    XSPAN_S_VAR(char, cs, buf, sizeof(buf));
    for (size_t i = 0; i != N; ++i)
        c0[i] += 1;
    for (size_t i = 0; i != N; ++i)
        cp[i] += 1;
    for (size_t i = 0; i != N; ++i)
        cs[i] += 1;
#if __cplusplus >= 201103L
    for (auto ptr = c0; ptr != c0 + N; ++ptr)
        *ptr += 1;
    for (auto ptr = c0 + 0; ptr < c0 + N; ++ptr)
        *ptr += 1;
    for (auto ptr = cp; ptr != cp + N; ++ptr)
        *ptr += 1;
    for (auto ptr = cp + 0; ptr < cp + N; ++ptr)
        *ptr += 1;
    for (auto ptr = cs; ptr != cs + N; ++ptr)
        *ptr += 1;
    for (auto ptr = cs + 0; ptr < cs + N; ++ptr)
        *ptr += 1;
#endif
}
References buf, memset(), N, ptr, XSPAN_0_VAR, XSPAN_P_VAR, and XSPAN_S_VAR.