My Project: src/check/dt_check.cpp File Reference
dt_check.cpp File Reference
#include "../util/system_headers.h"
#include <cmath>
#include "../conf.h"
#include "../util/miniacc.h"
Classes
struct anonymous_namespace{dt_check.cpp}::CheckIntegral< T >
struct anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestT
struct anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >
struct anonymous_namespace{dt_check.cpp}::CheckAlignment< T >
struct anonymous_namespace{dt_check.cpp}::TestBELE< T >
struct anonymous_namespace{dt_check.cpp}::CheckSignedness< T, T_is_signed >
struct anonymous_namespace{dt_check.cpp}::CheckTypePair< A, B >
struct anonymous_namespace{dt_check.cpp}::TestNoAliasingStruct< A, B >
struct anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >
struct anonymous_namespace{dt_check.cpp}::TestDestructor
struct anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >
Namespaces
namespace anonymous_namespace{dt_check.cpp}
compile-time checks
Macros
#define ASSERT_COMPATIBLE_TYPE(A, B)
#define ASSERT_SAME_TYPE(A, B)
#define ACC_WANT_ACC_CHK_CH 1
#define ACC_WANT_ACC_CHK_CH 1
#define ACCCHK_ASSERT(expr) ACC_COMPILE_TIME_ASSERT(expr)
#define CHECK_TYPE(T) (void) (T())
#define CHECK_TYPE_PAIR(A, B)
Typedefs
typedef decltype((const char *) nullptr -(const char *) nullptr true_ptrdiff_t)
check fundamental types
typedef decltype(sizeof(0)) true_size_t
Functions
int upx_doctest_check (int argc, char **argv)
upx_doctest_check()
int upx_doctest_check ()
ASSERT_SAME_TYPE (ptrdiff_t, std::ptrdiff_t)
ASSERT_SAME_TYPE (size_t, std::size_t)
ASSERT_SAME_TYPE (intptr_t, std::intptr_t)
ASSERT_SAME_TYPE (uintptr_t, std::uintptr_t)
ASSERT_SAME_TYPE (ptrdiff_t, true_ptrdiff_t)
ASSERT_SAME_TYPE (size_t, true_size_t)
ASSERT_SAME_TYPE (signed char, upx_int8_t)
ASSERT_SAME_TYPE (unsigned char, upx_uint8_t)
ASSERT_SAME_TYPE (short, upx_int16_t)
ASSERT_SAME_TYPE (unsigned short, upx_uint16_t)
ASSERT_SAME_TYPE (int, upx_int32_t)
ASSERT_SAME_TYPE (unsigned, upx_uint32_t)
ASSERT_SAME_TYPE (long long, upx_int64_t)
ASSERT_SAME_TYPE (unsigned long long, upx_uint64_t)
template<class A , class B >
static forceinline bool anonymous_namespace{dt_check.cpp}::testNoAliasing (A *a, B *b) noexcept
static noinline void anonymous_namespace{dt_check.cpp}::throwSomeValue (int x) may_throw
static noinline void anonymous_namespace{dt_check.cpp}::check_exceptions_2 (void(*func)(int), int *x) may_throw
static noinline void anonymous_namespace{dt_check.cpp}::check_basic_cxx_exception_handling (void(*func)(int)) noexcept
static noinline float anonymous_namespace{dt_check.cpp}::i64_f32_add_div (upx_int64_t a, upx_int64_t b)
static noinline float anonymous_namespace{dt_check.cpp}::u64_f32_add_div (upx_uint64_t a, upx_uint64_t b)
static noinline float anonymous_namespace{dt_check.cpp}::i64_f32_sub_div (upx_int64_t a, upx_int64_t b)
static noinline float anonymous_namespace{dt_check.cpp}::u64_f32_sub_div (upx_uint64_t a, upx_uint64_t b)
static noinline double anonymous_namespace{dt_check.cpp}::i64_f64_add_div (upx_int64_t a, upx_int64_t b)
static noinline double anonymous_namespace{dt_check.cpp}::u64_f64_add_div (upx_uint64_t a, upx_uint64_t b)
static noinline double anonymous_namespace{dt_check.cpp}::i64_f64_sub_div (upx_int64_t a, upx_int64_t b)
static noinline double anonymous_namespace{dt_check.cpp}::u64_f64_sub_div (upx_uint64_t a, upx_uint64_t b)
static noinline void anonymous_namespace{dt_check.cpp}::check_basic_floating_point (void) noexcept
void upx_compiler_sanity_check (void) noexcept
TEST_CASE ("assert_noexcept")
some doctest test cases
TEST_CASE ("acc_vget")
TEST_CASE ("ptr_invalidate_and_poison")
TEST_CASE ("upx_getenv")
TEST_CASE ("working -fno-strict-aliasing")
TEST_CASE ("working -fno-strict-overflow")
TEST_CASE ("libc snprintf")
TEST_CASE ("libc qsort")
Macro Definition Documentation
ACC_WANT_ACC_CHK_CH [1/2]
#define ACC_WANT_ACC_CHK_CH 1
Definition at line 846 of file dt_check.cpp.
ACC_WANT_ACC_CHK_CH [2/2]
#define ACC_WANT_ACC_CHK_CH 1
Definition at line 846 of file dt_check.cpp.
ACCCHK_ASSERT
#define ACCCHK_ASSERT (expr) ACC_COMPILE_TIME_ASSERT(expr)
ASSERT_COMPATIBLE_TYPE
#define ASSERT_COMPATIBLE_TYPE (A, B)
Value:
    static_assert(std::is_integral<A>::value, "");                                                 \
    static_assert(std::is_integral<B>::value, "");                                                 \
    static_assert(std::is_signed<A>::value == std::is_signed<B>::value, "");                       \
    static_assert(std::is_unsigned<A>::value == std::is_unsigned<B>::value, "");                   \
    static_assert(std::is_signed<A>::value == !std::is_unsigned<A>::value, "");                    \
    static_assert(std::is_signed<B>::value == !std::is_unsigned<B>::value, "");                    \
    static_assert(sizeof(A) == sizeof(B), "");                                                     \
    static_assert(alignof(A) == alignof(B), "")
Definition at line 208 of file dt_check.cpp.
ASSERT_SAME_TYPE
#define ASSERT_SAME_TYPE (A, B)
Value:
    ASSERT_COMPATIBLE_TYPE(A, B);                                                                  \
    static_assert(std::is_same<A, B>::value, "")
Definition at line 218 of file dt_check.cpp.
CHECK_TYPE
#define CHECK_TYPE (T) (void) (T())
CHECK_TYPE_PAIR
#define CHECK_TYPE_PAIR (A, B)
Value:
    CheckTypePair<A, B>::check();                                                                  \
    static_assert(alignof(A) == alignof(B))
Typedef Documentation
true_ptrdiff_t
typedef decltype((const char *) nullptr - (const char *) nullptr true_ptrdiff_t)
check fundamental types
Definition at line 188 of file dt_check.cpp.
true_size_t
typedef decltype(sizeof(0)) true_size_t
Definition at line 189 of file dt_check.cpp.
Function Documentation
ASSERT_SAME_TYPE() [1/14]
ASSERT_SAME_TYPE (int , upx_int32_t)
ASSERT_SAME_TYPE() [2/14]
ASSERT_SAME_TYPE (intptr_t , std::intptr_t)
ASSERT_SAME_TYPE() [3/14]
ASSERT_SAME_TYPE (long long , upx_int64_t)
ASSERT_SAME_TYPE() [4/14]
ASSERT_SAME_TYPE (ptrdiff_t , std::ptrdiff_t)
ASSERT_SAME_TYPE() [5/14]
ASSERT_SAME_TYPE (ptrdiff_t , true_ptrdiff_t)
ASSERT_SAME_TYPE() [6/14]
ASSERT_SAME_TYPE (short , upx_int16_t)
ASSERT_SAME_TYPE() [7/14]
ASSERT_SAME_TYPE (signed char , upx_int8_t)
ASSERT_SAME_TYPE() [8/14]
ASSERT_SAME_TYPE (size_t , std::size_t)
ASSERT_SAME_TYPE() [9/14]
ASSERT_SAME_TYPE (size_t , true_size_t)
ASSERT_SAME_TYPE() [10/14]
ASSERT_SAME_TYPE (uintptr_t , std::uintptr_t)
ASSERT_SAME_TYPE() [11/14]
ASSERT_SAME_TYPE (unsigned char , upx_uint8_t)
ASSERT_SAME_TYPE() [12/14]
ASSERT_SAME_TYPE (unsigned long long , upx_uint64_t)
ASSERT_SAME_TYPE() [13/14]
ASSERT_SAME_TYPE (unsigned short , upx_uint16_t)
ASSERT_SAME_TYPE() [14/14]
ASSERT_SAME_TYPE (unsigned , upx_uint32_t)
TEST_CASE() [1/8]
TEST_CASE ("acc_vget")
Definition at line 1341 of file dt_check.cpp.
                      {
    CHECK_EQ(acc_vget_int(0, 0), 0);
    CHECK_EQ(acc_vget_long(1, -1), 1);
    CHECK_EQ(acc_vget_acc_int64l_t(2, 1), 2);
    CHECK_EQ(acc_vget_acc_hvoid_p(nullptr, 0), nullptr);
    if (acc_vget_int(1, 0) > 0)
        return;
    assert_noexcept(false);
}
References assert_noexcept.
TEST_CASE() [2/8]
TEST_CASE ("assert_noexcept")
some doctest test cases
Definition at line 1323 of file dt_check.cpp.
{
    // just to make sure that our own assert() macros do not trigger any compiler warnings
    byte dummy = 0;
    byte *ptr1 = &dummy;
    const byte *const ptr2 = &dummy;
    void *ptr3 = nullptr;
    assert(true);
    assert(1);
    assert(ptr1);
    assert(ptr2);
    assert(!ptr3);
    assert_noexcept(true);
    assert_noexcept(1);
    assert_noexcept(ptr1);
    assert_noexcept(ptr2);
    assert_noexcept(!ptr3);
}
References assert_noexcept.
TEST_CASE() [3/8]
TEST_CASE ("libc qsort")
Definition at line 1437 of file dt_check.cpp.
{
    // runtime check that libc qsort() never compares identical objects
    // UPDATE: while only poor implementations of qsort() would actually do this
    //   it is probably allowed by the standard, so skip this test by default
    if (!is_envvar_true("UPX_DEBUG_TEST_LIBC_QSORT"))
        return;
    struct Elem {
        upx_uint16_t id;
        upx_uint16_t value;
        static int __acc_cdecl_qsort compare(const void *aa, const void *bb) noexcept {
            const Elem *a = (const Elem *) aa;
            const Elem *b = (const Elem *) bb;
            assert_noexcept(a->id != b->id); // check not IDENTICAL
            return a->value == b->value ? 0 : (a->value < b->value ? -1 : 1);
        }
        static noinline bool check_sort(upx_sort_func_t sort, Elem *e, size_t n, bool is_stable) {
            upx_uint32_t x = 5381 + (upx_rand() & 255);
            for (size_t i = 0; i < n; i++) {
                e[i].id = (upx_uint16_t) i;
                x = x * 33 + 1 + (i & 255);
                e[i].value = (upx_uint16_t) ((x >> 4) & 15);
            }
            sort(e, n, sizeof(Elem), Elem::compare);
            // verify
            for (size_t i = 1; i < n; i++) {
                if very_unlikely (e[i - 1].value > e[i].value)
                    return false;
                if (is_stable)
                    if very_unlikely (e[i - 1].value == e[i].value && e[i - 1].id >= e[i].id)
                        return false;
            }
            return true;
        }
    };
    constexpr size_t N = 4096;
    Elem e[N];
    for (size_t n = 0; n <= N; n = 2 * n + 1) {
        // system sort functions
        CHECK(Elem::check_sort(::qsort, e, n, false)); // libc qsort()
#if UPX_CONFIG_USE_STABLE_SORT
        upx_sort_func_t wrap_stable_sort = [](void *aa, size_t nn, size_t, upx_compare_func_t cc) {
            upx_std_stable_sort<sizeof(Elem)>(aa, nn, cc);
        };
        CHECK(Elem::check_sort(wrap_stable_sort, e, n, true)); // std::stable_sort()
#endif
        // simple UPX sort functions
        CHECK(Elem::check_sort(upx_gnomesort, e, n, true));
        CHECK(Elem::check_sort(upx_shellsort_memswap, e, n, false));
        CHECK(Elem::check_sort(upx_shellsort_memcpy, e, n, false));
    }
}
References __acc_cdecl_qsort, assert_noexcept, b, is_envvar_true(), N, n, noinline, upx_gnomesort(), upx_rand(), upx_shellsort_memcpy(), upx_shellsort_memswap(), and very_unlikely.
TEST_CASE() [4/8]
TEST_CASE ("libc snprintf")
Definition at line 1410 of file dt_check.cpp.
{
    // runtime check that Windows/MinGW <stdio.h> works as expected
    char buf[64];
    long long ll = acc_vget_int(-1, 0);
    unsigned long long llu = (upx_uint64_t) (upx_int64_t) ll;
    snprintf(buf, sizeof(buf), "%d.%ld.%lld.%u.%lu.%llu", -3, -2L, ll, 3U, 2LU, llu);
    CHECK_EQ(strcmp(buf, "-3.-2.-1.3.2.18446744073709551615"), 0);
    intmax_t im = ll;
    uintmax_t um = llu;
    snprintf(buf, sizeof(buf), "%d.%d.%d.%d.%d.%d.%d.%d.%d.%jd", -4, 0, 0, 0, 0, 0, 0, 0, 4, im);
    CHECK_EQ(strcmp(buf, "-4.0.0.0.0.0.0.0.4.-1"), 0);
    snprintf(buf, sizeof(buf), "%d.%d.%d.%d.%d.%d.%d.%d.%d.%ju", -5, 0, 0, 0, 0, 0, 0, 0, 5, um);
    CHECK_EQ(strcmp(buf, "-5.0.0.0.0.0.0.0.5.18446744073709551615"), 0);
    snprintf(buf, sizeof(buf), "%d.%d.%d.%d.%d.%d.%d.%d.%d.%jx", -6, 0, 0, 0, 0, 0, 0, 0, 6, um);
    CHECK_EQ(strcmp(buf, "-6.0.0.0.0.0.0.0.6.ffffffffffffffff"), 0);
    snprintf(buf, sizeof(buf), "%d.%d.%d.%d.%d.%d.%d.%d.%d.%#jx", -7, 0, 0, 0, 0, 0, 0, 0, 7, um);
    CHECK_EQ(strcmp(buf, "-7.0.0.0.0.0.0.0.7.0xffffffffffffffff"), 0);
    snprintf(buf, sizeof(buf), "%#X %#lx %#llx", 26u, 27ul, 28ull);
    CHECK_EQ(strcmp(buf, "0X1A 0x1b 0x1c"), 0);
    snprintf(buf, sizeof(buf), "%#06x %#06lX %#06llx", 26u, 27ul, 28ull);
    CHECK_EQ(strcmp(buf, "0x001a 0X001B 0x001c"), 0);
    snprintf(buf, sizeof(buf), "%#6x %#6lx %#6llX", 26u, 27ul, 28ull);
    CHECK_EQ(strcmp(buf, "  0x1a   0x1b   0X1C"), 0);
    snprintf(buf, sizeof(buf), "%#-6X %#-6lx %#-6llx", 26u, 27ul, 28ull);
    CHECK_EQ(strcmp(buf, "0X1A   0x1b   0x1c  "), 0);
}
References buf, snprintf, strcmp(), and U.
TEST_CASE() [5/8]
TEST_CASE ("ptr_invalidate_and_poison")
Definition at line 1351 of file dt_check.cpp.
{
    int *ip = nullptr; // initialized
    ptr_invalidate_and_poison(ip);
    assert(ip != nullptr);
    (void) ip;
    double *dp; // not initialized
    ptr_invalidate_and_poison(dp);
    assert(dp != nullptr);
    (void) dp;
}
References ptr_invalidate_and_poison().
TEST_CASE() [6/8]
TEST_CASE ("upx_getenv")
Definition at line 1362 of file dt_check.cpp.
{
    CHECK_EQ(upx_getenv(nullptr), nullptr);
    CHECK_EQ(upx_getenv(""), nullptr);
}
References upx_getenv().
TEST_CASE() [7/8]
TEST_CASE ("working -fno-strict-aliasing")
Definition at line 1367 of file dt_check.cpp.
{
    bool ok;
    long v = 0;
    short *ps = ACC_STATIC_CAST(short *, acc_vget_acc_hvoid_p(&v, 0));
    int *pi = ACC_STATIC_CAST(int *, acc_vget_acc_hvoid_p(&v, 0));
    long *pl = ACC_STATIC_CAST(long *, acc_vget_acc_hvoid_p(&v, 0));
    *ps = 0;
    *pl = -1;
    ok = *ps == -1;
    CHECK(ok);
    *pi = 0;
    *pl = -1;
    ok = *pi == -1;
    CHECK(ok);
    *pl = 0;
    *ps = -1;
    ok = *pl != 0;
    CHECK(ok);
    *pl = 0;
    *pi = -1;
    ok = *pl != 0;
    CHECK(ok);
    UNUSED(ok);
}
References ACC_STATIC_CAST, and UNUSED.
TEST_CASE() [8/8]
TEST_CASE ("working -fno-strict-overflow")
Definition at line 1392 of file dt_check.cpp.
{
    CHECK_EQ(acc_vget_int(INT_MAX, 0) + 1, INT_MIN);
    CHECK_EQ(acc_vget_int(INT_MIN, 0) - 1, INT_MAX);
    CHECK_EQ(acc_vget_long(LONG_MAX, 0) + 1, LONG_MIN);
    CHECK_EQ(acc_vget_long(LONG_MIN, 0) - 1, LONG_MAX);
    bool ok;
    int i;
    i = INT_MAX;
    i += 1;
    ok = i == INT_MIN;
    CHECK(ok);
    i = INT_MIN;
    i -= 1;
    ok = i == INT_MAX;
    CHECK(ok);
    UNUSED(ok);
}
References UNUSED.
upx_compiler_sanity_check()
void upx_compiler_sanity_check (void) noexcept
Definition at line 850 of file dt_check.cpp.
{
    check_basic_floating_point();
    if (is_envvar_true("UPX_DEBUG_DOCTEST_DISABLE", "UPX_DEBUG_DISABLE_DOCTEST")) {
        // If UPX_DEBUG_DOCTEST_DISABLE is set then we don't want to throw any
        // exceptions in order to improve debugging experience.
    } else {
        // check working C++ exception handling to early catch toolchain/qemu/wine/etc problems
        check_basic_cxx_exception_handling(throwSomeValue);
    }
    // check_basic_decltype()
    {
        auto a = +0;
        constexpr auto b = -0;
        const auto &c = -1;
        static_assert((std::is_same<int, decltype(a)>::value));
        static_assert((std::is_same<const int, decltype(b)>::value));
        static_assert((std::is_same<const int &, decltype(c)>::value));
        UNUSED(a);
        UNUSED(b);
        UNUSED(c);
    }
#define ACC_WANT_ACC_CHK_CH 1
#undef ACCCHK_ASSERT
#define ACCCHK_ASSERT(expr) ACC_COMPILE_TIME_ASSERT(expr)
#include "../util/miniacc.h"
#undef ACCCHK_ASSERT
    static_assert(sizeof(char) == 1);
    static_assert(sizeof(short) == 2);
    static_assert(sizeof(int) == 4);
    static_assert(sizeof(long) >= 4);
    static_assert(sizeof(long long) >= 8);
    static_assert(sizeof(void *) >= 4);
    static_assert(sizeof(upx_off_t) >= 8);
    static_assert(sizeof(upx_off_t) >= sizeof(long long));
// __int64
#if defined(_MSC_VER)
    {
        ASSERT_SAME_TYPE(long long, __int64);
        ASSERT_SAME_TYPE(unsigned long long, unsigned __int64);
        typedef __int64 my_int64;
        typedef unsigned __int64 my_uint64;
        ASSERT_SAME_TYPE(long long, my_int64);
        ASSERT_SAME_TYPE(unsigned long long, my_uint64);
    }
#endif
    static_assert(sizeof(BE16) == 2);
    static_assert(sizeof(BE32) == 4);
    static_assert(sizeof(BE64) == 8);
    static_assert(sizeof(LE16) == 2);
    static_assert(sizeof(LE32) == 4);
    static_assert(sizeof(LE64) == 8);
    COMPILE_TIME_ASSERT_ALIGNED1(BE16)
    COMPILE_TIME_ASSERT_ALIGNED1(BE32)
    COMPILE_TIME_ASSERT_ALIGNED1(BE64)
    COMPILE_TIME_ASSERT_ALIGNED1(LE16)
    COMPILE_TIME_ASSERT_ALIGNED1(LE32)
    COMPILE_TIME_ASSERT_ALIGNED1(LE64)
    // check that these types are not some multi-word macro
#define CHECK_TYPE(T) (void) (T())
    CHECK_TYPE(int8_t);
    CHECK_TYPE(uint8_t);
    CHECK_TYPE(int16_t);
    CHECK_TYPE(uint16_t);
    CHECK_TYPE(int32_t);
    CHECK_TYPE(uint32_t);
    CHECK_TYPE(int64_t);
    CHECK_TYPE(uint64_t);
    CHECK_TYPE(intmax_t);
    CHECK_TYPE(uintmax_t);
    CHECK_TYPE(ptrdiff_t);
    CHECK_TYPE(size_t);
    CHECK_TYPE(intptr_t);
    CHECK_TYPE(uintptr_t);
#if 0
    CHECK_TYPE(acc_int8_t);
    CHECK_TYPE(acc_uint8_t);
    CHECK_TYPE(acc_int16_t);
    CHECK_TYPE(acc_uint16_t);
    CHECK_TYPE(acc_int32_t);
    CHECK_TYPE(acc_uint32_t);
    CHECK_TYPE(acc_int64_t);
    CHECK_TYPE(acc_uint64_t);
    CHECK_TYPE(acc_intptr_t);
    CHECK_TYPE(acc_uintptr_t);
#endif
    CHECK_TYPE(upx_int8_t);
    CHECK_TYPE(upx_uint8_t);
    CHECK_TYPE(upx_int16_t);
    CHECK_TYPE(upx_uint16_t);
    CHECK_TYPE(upx_int32_t);
    CHECK_TYPE(upx_uint32_t);
    CHECK_TYPE(upx_int64_t);
    CHECK_TYPE(upx_uint64_t);
#if (__SIZEOF_INT128__ == 16)
    CHECK_TYPE(upx_int128_t);
    CHECK_TYPE(upx_uint128_t);
#endif
    CHECK_TYPE(upx_ptraddr_t);
    CHECK_TYPE(upx_uintptr_t);
    CHECK_TYPE(upx_uptrdiff_t);
    CHECK_TYPE(upx_ssize_t);
#undef CHECK_TYPE
    CheckIntegral<char>::check();
    CheckIntegral<signed char>::check();
    CheckIntegral<unsigned char>::check();
    CheckIntegral<short>::check();
    CheckIntegral<unsigned short>::check();
    CheckIntegral<int>::check();
    CheckIntegral<unsigned>::check();
    CheckIntegral<long>::check();
    CheckIntegral<unsigned long>::check();
    CheckIntegral<long long>::check();
    CheckIntegral<unsigned long long>::check();
    CheckIntegral<intmax_t>::check();
    CheckIntegral<uintmax_t>::check();
    CheckIntegral<upx_int8_t>::check();
    CheckIntegral<upx_uint8_t>::check();
    CheckIntegral<upx_int16_t>::check();
    CheckIntegral<upx_uint16_t>::check();
    CheckIntegral<upx_int32_t>::check();
    CheckIntegral<upx_uint32_t>::check();
    CheckIntegral<upx_int64_t>::check();
    CheckIntegral<upx_uint64_t>::check();
    CheckIntegral<upx_off_t>::check();
    CheckIntegral<ptrdiff_t>::check();
    CheckIntegral<size_t>::check();
    CheckIntegral<upx_ptraddr_t>::check();
#if defined(__CHERI__) && defined(__CHERI_PURE_CAPABILITY__)
    static_assert(sizeof(upx_ptraddr_t) == 8);
    static_assert(alignof(upx_ptraddr_t) == 8);
    static_assert(sizeof(void *) == 16);
    static_assert(alignof(void *) == 16);
    static_assert(sizeof(uintptr_t) == 16);
    static_assert(alignof(uintptr_t) == 16);
    // warning: binary expression on capability types 'unsigned __intcap' and 'unsigned __intcap'
    CheckIntegral<intptr_t>::check_core();
    CheckIntegral<uintptr_t>::check_core();
    CheckIntegral<upx_uintptr_t>::check_core();
#else
    CheckIntegral<intptr_t>::check();
    CheckIntegral<uintptr_t>::check();
    CheckIntegral<upx_uintptr_t>::check();
#endif
#if (__SIZEOF_INT128__ == 16)
#if defined(_CPP_VER) || defined(_WIN32) // int128 is not fully supported by MSVC libstdc++ yet
#else
    CheckIntegral<upx_int128_t>::check();
    CheckIntegral<upx_uint128_t>::check();
#endif
#endif
    CheckSignedness<char, false>::check(); // -funsigned-char
    CheckSignedness<signed char, true>::check();
    CheckSignedness<unsigned char, false>::check();
    CheckSignedness<short, true>::check();
    CheckSignedness<unsigned short, false>::check();
    CheckSignedness<int, true>::check();
    CheckSignedness<unsigned, false>::check();
    CheckSignedness<long, true>::check();
    CheckSignedness<unsigned long, false>::check();
    CheckSignedness<long long, true>::check();
    CheckSignedness<unsigned long long, false>::check();
    CheckSignedness<intmax_t, true>::check();
    CheckSignedness<uintmax_t, false>::check();
    CheckSignedness<upx_int8_t, true>::check();
    CheckSignedness<upx_uint8_t, false>::check();
    CheckSignedness<upx_int16_t, true>::check();
    CheckSignedness<upx_uint16_t, false>::check();
    CheckSignedness<upx_int32_t, true>::check();
    CheckSignedness<upx_uint32_t, false>::check();
    CheckSignedness<upx_int64_t, true>::check();
    CheckSignedness<upx_uint64_t, false>::check();
#if (__SIZEOF_INT128__ == 16)
#if defined(_CPP_VER) || defined(_WIN32) // int128 is not fully supported by MSVC libstdc++ yet
#else
    CheckSignedness<upx_int128_t, true>::check();
    CheckSignedness<upx_uint128_t, false>::check();
#endif
#endif
    CheckSignedness<upx_off_t, true>::check();
    CheckSignedness<ptrdiff_t, true>::check();
    CheckSignedness<size_t, false>::check();
    CheckSignedness<upx_ptraddr_t, false>::check();
    CheckSignedness<intptr_t, true>::check();
    CheckSignedness<uintptr_t, false>::check();
    CheckSignedness<upx_uintptr_t, false>::check();
#define CHECK_TYPE_PAIR(A, B)                                                                      \
    CheckTypePair<A, B>::check();                                                                  \
    static_assert(alignof(A) == alignof(B))
    CHECK_TYPE_PAIR(signed char, unsigned char);
    CHECK_TYPE_PAIR(short, unsigned short);
    CHECK_TYPE_PAIR(int, unsigned);
    CHECK_TYPE_PAIR(long, unsigned long);
    CHECK_TYPE_PAIR(long long, unsigned long long);
    CHECK_TYPE_PAIR(intmax_t, uintmax_t);
    CHECK_TYPE_PAIR(upx_int8_t, upx_uint8_t);
    CHECK_TYPE_PAIR(upx_int16_t, upx_uint16_t);
    CHECK_TYPE_PAIR(upx_int32_t, upx_uint32_t);
    CHECK_TYPE_PAIR(upx_int64_t, upx_uint64_t);
#if (__SIZEOF_INT128__ == 16)
#if defined(_CPP_VER) || defined(_WIN32) // int128 is not fully supported by MSVC libstdc++ yet
#else
    CHECK_TYPE_PAIR(upx_int128_t, upx_uint128_t);
#endif
#endif
    CHECK_TYPE_PAIR(ptrdiff_t, upx_uptrdiff_t);
    CHECK_TYPE_PAIR(upx_ssize_t, size_t);
    CHECK_TYPE_PAIR(upx_sptraddr_t, upx_ptraddr_t);
    CHECK_TYPE_PAIR(intptr_t, uintptr_t);
    CHECK_TYPE_PAIR(acc_intptr_t, acc_uintptr_t);
#undef CHECK_TYPE_PAIR
    static_assert(sizeof(upx_charptr_unit_type) == 1);
    COMPILE_TIME_ASSERT_ALIGNED1(upx_charptr_unit_type)
    static_assert(sizeof(*((charptr) nullptr)) == 1);
    // check UPX_VERSION_xxx
    {
        using upx::compile_time::mem_eq;
        using upx::compile_time::string_len;
        static_assert(string_len(UPX_VERSION_STRING4) == 4);
        static_assert(string_len(UPX_VERSION_YEAR) == 4);
        static_assert(string_len(UPX_VERSION_DATE_ISO) == 10);
        static_assert(string_len(UPX_VERSION_DATE) == 12 || string_len(UPX_VERSION_DATE) == 13);
        static_assert(mem_eq(UPX_VERSION_STRING4, UPX_VERSION_STRING, 3));
        static_assert(mem_eq(UPX_VERSION_YEAR, UPX_VERSION_DATE_ISO, 4));
        static_assert(mem_eq(UPX_VERSION_YEAR, &UPX_VERSION_DATE[sizeof(UPX_VERSION_DATE) - 5], 4));
        char buf[16];
        constexpr long long v = UPX_VERSION_HEX;
        upx_safe_snprintf(buf, sizeof(buf), "%lld.%lld.%lld", (v >> 16), (v >> 8) & 255, v & 255);
        assert_noexcept(strcmp(buf, UPX_VERSION_STRING) == 0);
        upx_safe_snprintf(buf, sizeof(buf), "%lld.%lld%lld", (v >> 16), (v >> 8) & 255, v & 255);
        assert_noexcept(strcmp(buf, UPX_VERSION_STRING4) == 0);
    }
    if (gitrev[0]) {
        size_t revlen = strlen(gitrev);
        if (strncmp(gitrev, "ERROR", 5) == 0) {
            assert_noexcept(revlen == 5 || revlen == 6);
        } else {
            assert_noexcept(revlen == 12 || revlen == 13);
        }
        if (revlen == 6 || revlen == 13) {
            assert_noexcept(gitrev[revlen - 1] == '+');
        }
    }
    assert_noexcept(UPX_RSIZE_MAX_MEM == 805306368);
#if DEBUG || 1
    assert_noexcept(TestBELE<LE16>::test());
    assert_noexcept(TestBELE<LE32>::test());
    assert_noexcept(TestBELE<LE64>::test());
    assert_noexcept(TestBELE<BE16>::test());
    assert_noexcept(TestBELE<BE32>::test());
    assert_noexcept(TestBELE<BE64>::test());
    {
        alignas(16) static constexpr byte dd[32] = {
            0, 0, 0, 0,    0,    0,    0,    0xff, 0xfe, 0xfd, 0xfc, 0xfb, 0xfa, 0xf9, 0xf8, 0,
            0, 0, 0, 0x7f, 0x7e, 0x7d, 0x7c, 0x7b, 0x7a, 0x79, 0x78, 0,    0,    0,    0,    0};
        constexpr const byte *d = dd + 7;
#if !defined(upx_fake_alignas_16)
        assert_noexcept(ptr_is_aligned<16>(dd));
        assert_noexcept(ptr_is_aligned(dd, 16));
#endif
        static_assert(upx::compile_time::get_be16(d) == 0xfffe);
        static_assert(upx::compile_time::get_be24(d) == 0xfffefd);
        static_assert(upx::compile_time::get_be32(d) == 0xfffefdfc);
        static_assert(upx::compile_time::get_be64(d) == 0xfffefdfcfbfaf9f8ULL);
        static_assert(upx::compile_time::get_le16(d) == 0xfeff);
        static_assert(upx::compile_time::get_le24(d) == 0xfdfeff);
        static_assert(upx::compile_time::get_le32(d) == 0xfcfdfeff);
        static_assert(upx::compile_time::get_le64(d) == 0xf8f9fafbfcfdfeffULL);
        const N_BELE_RTP::AbstractPolicy *bele;
        assert_noexcept(upx_adler32(d, 4) == 0x09f003f7);
        assert_noexcept(upx_adler32(d, 4, 0) == 0x09ec03f6);
        assert_noexcept(upx_adler32(d, 4, 1) == 0x09f003f7);
        bele = &N_BELE_RTP::be_policy;
        assert_noexcept(get_be16(d) == 0xfffe);
        assert_noexcept(bele->get16(d) == 0xfffe);
        assert_noexcept(get_be16_signed(d) == -2);
        assert_noexcept(get_be24(d) == 0xfffefd);
        assert_noexcept(bele->get24(d) == 0xfffefd);
        assert_noexcept(get_be24_signed(d) == -259);
        assert_noexcept(get_be32(d) == 0xfffefdfc);
        assert_noexcept(bele->get32(d) == 0xfffefdfc);
        assert_noexcept(get_be32_signed(d) == -66052);
        assert_noexcept(get_be64(d) == 0xfffefdfcfbfaf9f8ULL);
        assert_noexcept(get_be64_signed(d) == -283686952306184LL);
        bele = &N_BELE_RTP::le_policy;
        assert_noexcept(get_le16(d) == 0xfeff);
        assert_noexcept(bele->get16(d) == 0xfeff);
        assert_noexcept(get_le16_signed(d) == -257);
        assert_noexcept(get_le24(d) == 0xfdfeff);
        assert_noexcept(bele->get24(d) == 0xfdfeff);
        assert_noexcept(get_le24_signed(d) == -131329);
        assert_noexcept(get_le32(d) == 0xfcfdfeff);
        assert_noexcept(bele->get32(d) == 0xfcfdfeff);
        assert_noexcept(get_le32_signed(d) == -50462977);
        assert_noexcept(get_le64(d) == 0xf8f9fafbfcfdfeffULL);
        assert_noexcept(get_le64_signed(d) == -506097522914230529LL);
        static_assert(get_be24(d) == 0xfffefd);
        static_assert(get_le24(d) == 0xfdfeff);
#if defined(upx_is_constant_evaluated)
        static_assert(get_be24_signed(d) == -259);
        static_assert(get_le24_signed(d) == -131329);
        static_assert(get_be16(d) == 0xfffe);
        static_assert(get_be16_signed(d) == -2);
        static_assert(get_be32(d) == 0xfffefdfc);
        static_assert(get_be32_signed(d) == -66052);
        static_assert(get_be64(d) == 0xfffefdfcfbfaf9f8ULL);
        static_assert(get_be64_signed(d) == -283686952306184LL);
        static_assert(get_le16(d) == 0xfeff);
        static_assert(get_le16_signed(d) == -257);
        static_assert(get_le32(d) == 0xfcfdfeff);
        static_assert(get_le32_signed(d) == -50462977);
        static_assert(get_le64(d) == 0xf8f9fafbfcfdfeffULL);
        static_assert(get_le64_signed(d) == -506097522914230529LL);
#endif
        assert_noexcept(find_be16(d, 2, 0xfffe) == 0);
        assert_noexcept(find_le16(d, 2, 0xfeff) == 0);
        assert_noexcept(find_be32(d, 4, 0xfffefdfc) == 0);
        assert_noexcept(find_le32(d, 4, 0xfcfdfeff) == 0);
        constexpr const byte *e = d + 12;
        assert_noexcept(get_be16_signed(e) == 32638);
        assert_noexcept(get_be24_signed(e) == 8355453);
        assert_noexcept(get_be32_signed(e) == 2138996092);
        assert_noexcept(get_be64_signed(e) == 9186918263483431288LL);
#if defined(upx_is_constant_evaluated)
        static_assert(get_be16_signed(e) == 32638);
        static_assert(get_be24_signed(e) == 8355453);
        static_assert(get_be32_signed(e) == 2138996092);
        static_assert(get_be64_signed(e) == 9186918263483431288LL);
#endif
    }
#if defined(upx_is_constant_evaluated)
    {
        constexpr upx_uint16_t v16 = 0x0201;
        constexpr upx_uint32_t v32 = 0x04030201;
        constexpr upx_uint64_t v64 = 0x0807060504030201ull;
        constexpr BE16 be16 = BE16::make(v16);
        constexpr BE32 be32 = BE32::make(v32);
        constexpr BE64 be64 = BE64::make(v64);
        constexpr LE16 le16 = LE16::make(v16);
        constexpr LE32 le32 = LE32::make(v32);
        constexpr LE64 le64 = LE64::make(v64);
        using upx::compile_time::mem_eq;
        static_assert(mem_eq(be16.d, "\x02\x01", 2));
        static_assert(mem_eq(be32.d, "\x04\x03\x02\x01", 4));
        static_assert(mem_eq(be64.d, "\x08\x07\x06\x05\x04\x03\x02\x01", 8));
        static_assert(mem_eq(le16.d, "\x01\x02", 2));
        static_assert(mem_eq(le32.d, "\x01\x02\x03\x04", 4));
        static_assert(mem_eq(le64.d, "\x01\x02\x03\x04\x05\x06\x07\x08", 8));
        constexpr NE16 ne16 = NE16::make(v16);
        constexpr NE32 ne32 = NE32::make(v32);
        constexpr NE64 ne64 = NE64::make(v64);
        assert_noexcept(memcmp(&v16, ne16.d, 2) == 0);
        assert_noexcept(memcmp(&v32, ne32.d, 4) == 0);
        assert_noexcept(memcmp(&v64, ne64.d, 8) == 0);
    }
#endif
#if DEBUG >= 1
    {
        for (int i = 0; i < 256; i++) {
            {
                const unsigned u = i;
                assert_noexcept(sign_extend(u, 1) == ((i & 1) ? -1 : 0));
                assert_noexcept(sign_extend(u, 2) == ((i & 2) ? -2 + (i & 1) : (i & 1)));
                assert_noexcept(sign_extend(u, 3) == ((i & 4) ? -4 + (i & 3) : (i & 3)));
                assert_noexcept(sign_extend(u, 4) == ((i & 8) ? -8 + (i & 7) : (i & 7)));
                assert_noexcept(sign_extend(u, 5) == ((i & 16) ? -16 + (i & 15) : (i & 15)));
                assert_noexcept(sign_extend(u, 6) == ((i & 32) ? -32 + (i & 31) : (i & 31)));
                assert_noexcept(sign_extend(u, 7) == ((i & 64) ? -64 + (i & 63) : (i & 63)));
                assert_noexcept(sign_extend(u, 8) == ((i & 128) ? -128 + (i & 127) : (i & 127)));
                assert_noexcept(sign_extend(u, 32) == i);
                assert_noexcept(sign_extend(0u - u, 32) == -i);
            }
            {
                const upx_uint64_t u = i;
                assert_noexcept(sign_extend(u, 1) == ((i & 1) ? -1 : 0));
                assert_noexcept(sign_extend(u, 2) == ((i & 2) ? -2 + (i & 1) : (i & 1)));
                assert_noexcept(sign_extend(u, 3) == ((i & 4) ? -4 + (i & 3) : (i & 3)));
                assert_noexcept(sign_extend(u, 4) == ((i & 8) ? -8 + (i & 7) : (i & 7)));
                assert_noexcept(sign_extend(u, 5) == ((i & 16) ? -16 + (i & 15) : (i & 15)));
                assert_noexcept(sign_extend(u, 6) == ((i & 32) ? -32 + (i & 31) : (i & 31)));
                assert_noexcept(sign_extend(u, 7) == ((i & 64) ? -64 + (i & 63) : (i & 63)));
                assert_noexcept(sign_extend(u, 8) == ((i & 128) ? -128 + (i & 127) : (i & 127)));
                assert_noexcept(sign_extend(u, 64) == i);
                assert_noexcept(sign_extend(upx_uint64_t(0) - u, 64) == -i);
            }
        }
    }
#endif
    {
        unsigned dd;
        void *const d = &dd;
        dd = ne32_to_le32(0xf7f6f5f4);
        assert_noexcept(get_le26(d) == 0x03f6f5f4);
        set_le26(d, 0);
        assert_noexcept(get_le26(d) == 0);
        assert_noexcept(dd == ne32_to_le32(0xf4000000));
        set_le26(d, 0xff020304);
        assert_noexcept(get_le26(d) == 0x03020304);
        assert_noexcept(dd == ne32_to_le32(0xf7020304));
    }
    {
        upx_uint16_t a = 0;
        upx_uint32_t b = 0;
        upx_uint64_t c = 0;
        set_ne16(&a, 0x04030201); // ignore upper bits
        set_ne32(&b, 0x04030201);
        set_ne64(&c, 0x0807060504030201ull);
        assert_noexcept(a == 0x0201);
        assert_noexcept(b == 0x04030201);
        assert_noexcept(c == 0x0807060504030201ull);
        assert_noexcept(get_ne16(&a) == 0x0201);
        assert_noexcept(get_ne32(&b) == 0x04030201);
        assert_noexcept(get_ne64(&c) == 0x0807060504030201ull);
    }
#endif // DEBUG
    union {
        short v_short;
        int v_int;
        long v_long;
        long long v_llong;
        BE16 b16;
        BE32 b32;
        BE64 b64;
        LE16 l16;
        LE32 l32;
        LE64 l64;
    } u;
    assert_noexcept(testNoAliasing(&u.v_short, &u.b32));
    assert_noexcept(testNoAliasing(&u.v_short, &u.l32));
    assert_noexcept(testNoAliasing(&u.v_int, &u.b64));
    assert_noexcept(testNoAliasing(&u.v_int, &u.l64));
    // check working -fno-strict-aliasing
    assert_noexcept(testNoAliasing(&u.v_short, &u.v_int));
    assert_noexcept(testNoAliasing(&u.v_int, &u.v_long));
    assert_noexcept(testNoAliasing(&u.v_int, &u.v_llong));
    assert_noexcept(testNoAliasing(&u.v_long, &u.v_llong));
    assert_noexcept(TestIntegerWrap<unsigned>::inc_gt(0));
    assert_noexcept(!TestIntegerWrap<unsigned>::inc_gt(UINT_MAX));
    assert_noexcept(TestIntegerWrap<unsigned>::dec_lt(1));
    assert_noexcept(!TestIntegerWrap<unsigned>::dec_lt(0));
    assert_noexcept(TestIntegerWrap<unsigned>::neg_eq(0));
    assert_noexcept(!TestIntegerWrap<unsigned>::neg_eq(1));
    assert_noexcept(!TestIntegerWrap<unsigned>::neg_eq(UINT_MAX));
    // check working -fno-strict-overflow
    assert_noexcept(TestIntegerWrap<int>::inc_gt(0));
    assert_noexcept(!TestIntegerWrap<int>::inc_gt(INT_MAX));
    assert_noexcept(TestIntegerWrap<int>::dec_lt(0));
    assert_noexcept(!TestIntegerWrap<int>::dec_lt(INT_MIN));
    assert_noexcept(TestIntegerWrap<int>::neg_eq(0));
    assert_noexcept(!TestIntegerWrap<int>::neg_eq(1));
    assert_noexcept(!TestIntegerWrap<int>::neg_eq(INT_MAX));
    assert_noexcept(TestIntegerWrap<int>::neg_eq(INT_MIN)); // special case
}
References acc_int8_t, acc_intptr_t, acc_uint8_t, acc_uintptr_t, assert_noexcept, ASSERT_SAME_TYPE, b, N_BELE_RTP::be_policy, buf, charptr, anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check(), anonymous_namespace{dt_check.cpp}::CheckSignedness< T, T_is_signed >::check(), anonymous_namespace{dt_check.cpp}::check_basic_cxx_exception_handling(), anonymous_namespace{dt_check.cpp}::check_basic_floating_point(), anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check_core(), CHECK_TYPE, CHECK_TYPE_PAIR, COMPILE_TIME_ASSERT_ALIGNED1, BE16::d, LE16::d, BE32::d, LE32::d, BE64::d, LE64::d, anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::dec_lt(), find_be16(), find_be32(), find_le16(), find_le32(), upx::compile_time::get_be16(), get_be16(), get_be16_signed(), get_be24(), upx::compile_time::get_be24(), get_be24_signed(), upx::compile_time::get_be32(), get_be32(), get_be32_signed(), upx::compile_time::get_be64(), get_be64(), get_be64_signed(), upx::compile_time::get_le16(), get_le16(), get_le16_signed(), get_le24(), upx::compile_time::get_le24(), get_le24_signed(), get_le26(), upx::compile_time::get_le32(), get_le32(), get_le32_signed(), upx::compile_time::get_le64(), get_le64(), get_le64_signed(), get_ne16(), get_ne32(), get_ne64(), gitrev, anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::inc_gt(), is_envvar_true(), N_BELE_RTP::le_policy, BE16::make(), BE32::make(), BE64::make(), LE16::make(), LE32::make(), LE64::make(), upx::compile_time::mem_eq(), memcmp(), ne32_to_le32, anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::neg_eq(), ptr_is_aligned(), set_le26(), set_ne16(), set_ne32(), set_ne64(), sign_extend(), strcmp(), upx::compile_time::string_len(), strlen, anonymous_namespace{dt_check.cpp}::TestBELE< T >::test(), anonymous_namespace{dt_check.cpp}::testNoAliasing(), anonymous_namespace{dt_check.cpp}::throwSomeValue(), UNUSED, upx_adler32(), UPX_RSIZE_MAX_MEM, upx_safe_snprintf(), UPX_VERSION_DATE, UPX_VERSION_DATE_ISO, UPX_VERSION_HEX, UPX_VERSION_STRING, UPX_VERSION_STRING4, and UPX_VERSION_YEAR.
Referenced by do_files(), and upx_main().
upx_doctest_check() [1/2]
int upx_doctest_check ()
Definition at line 93 of file dt_check.cpp.
{ return upx_doctest_check(0, nullptr); }
References upx_doctest_check().
Referenced by upx_doctest_check(), and upx_main().
upx_doctest_check() [2/2]
int upx_doctest_check (int argc, char ** argv)
upx_doctest_check()
honors environment variables: UPX_DEBUG_DOCTEST_DISABLE UPX_DEBUG_DOCTEST_VERBOSE
HINT: set "UPX_DEBUG_DOCTEST_DISABLE=1" for improved debugging experience
Definition at line 44 of file dt_check.cpp.
{
#if defined(DOCTEST_CONFIG_DISABLE)
    UNUSED(argc);
    UNUSED(argv);
    return 0;
#else
    if (is_envvar_true("UPX_DEBUG_DOCTEST_DISABLE", "UPX_DEBUG_DISABLE_DOCTEST"))
        return 0;
    bool minimal = true;   // don't show summary
    bool duration = false; // don't show timings
    bool success = false;  // don't show all succeeding tests
#if DEBUG
    // default for debug builds: do show the [doctest] summary
    minimal = false;
#endif
    const char *e = upx_getenv("UPX_DEBUG_DOCTEST_VERBOSE");
    if (e && e[0]) {
        if (strcmp(e, "0") == 0) {
            minimal = true;
        } else if (strcmp(e, "1") == 0) {
            minimal = false;
        } else if (strcmp(e, "2") == 0) {
            minimal = false;
            duration = true;
        } else if (strcmp(e, "3") == 0) {
            minimal = false;
            duration = true;
            success = true;
        }
    }
    doctest::Context context;
    if (minimal)
        context.setOption("dt-minimal", true);
    if (duration)
        context.setOption("dt-duration", true);
    if (success)
        context.setOption("dt-success", true);
    // this requires that main_get_options() understands/ignores doctest "--dt-XXX" options
    if (argc > 0 && argv != nullptr)
        context.applyCommandLine(argc, argv);
    int r = context.run();
    if (r != 0)
        return 1;
    if (context.shouldExit())
        return 2;
    return 0;
#endif // DOCTEST_CONFIG_DISABLE
}
References is_envvar_true(), strcmp(), UNUSED, and upx_getenv().