My Project: src/except.h File Reference
except.h File Reference
Classes
class Throwable
exceptions
struct Throwable::Stats
class Exception
class Error
class OutOfMemoryException
system exceptions
class IOException
class EOFException
class FileNotFoundException
class FileAlreadyExistsException
class OverlayException
application exceptions
class CantPackException
class UnknownExecutableFormatException
class AlreadyPackedException
class NotCompressibleException
class CantUnpackException
class NotPackedException
class InternalError
errors
Functions
const char * prettyExceptionName (const char *n) noexcept
util
noreturn void throwCantPack (const char *msg) may_throw
compression
noreturn void throwCantPackExact () may_throw
noreturn void throwUnknownExecutableFormat (const char *msg=nullptr, bool warn=false) may_throw
noreturn void throwNotCompressible (const char *msg=nullptr) may_throw
noreturn void throwAlreadyPacked (const char *msg=nullptr) may_throw
noreturn void throwAlreadyPackedByUPX (const char *msg=nullptr) may_throw
noreturn void throwCantUnpack (const char *msg) may_throw
decompression
noreturn void throwNotPacked (const char *msg=nullptr) may_throw
noreturn void throwFilterException () may_throw
noreturn void throwBadLoader () may_throw
noreturn void throwChecksumError () may_throw
noreturn void throwCompressedDataViolation () may_throw
noreturn void throwInternalError (const char *msg) may_throw
other
noreturn void throwOutOfMemoryException (const char *msg=nullptr) may_throw
noreturn void throwIOException (const char *msg=nullptr, int e=0) may_throw
noreturn void throwEOFException (const char *msg=nullptr, int e=0) may_throw
template<class T >
void throwCantPack (const T *,...) DELETED_FUNCTION
template<>
noreturn void throwCantPack (const char *format,...) may_throw attribute_format(1
template<class T >
noreturn void void throwCantUnpack (const T *,...) DELETED_FUNCTION
template<>
noreturn void throwCantUnpack (const char *format,...) may_throw attribute_format(1
template<class T >
noreturn void void throwInternalError (const T *,...) DELETED_FUNCTION
template<>
noreturn void throwInternalError (const char *format,...) may_throw attribute_format(1
Function Documentation
prettyExceptionName()
const char * prettyExceptionName (const char * n) noexcept
util
Definition at line 198 of file except.cpp.
{
    if (n == nullptr)
        return "(null)";
    while (*n) {
        if (*n >= '0' && *n <= '9') // Linux ABI
            n++;
        else if (*n == ' ')
            n++;
        else if (strncmp(n, "class ", 6) == 0) // Visual C++ (MSVC)
            n += 6;
        else
            break;
    }
    return n;
}
References n.
Referenced by printErr(), and printUnhandledException().
throwAlreadyPacked()
noreturn void throwAlreadyPacked (const char * msg = nullptr)
Definition at line 97 of file except.cpp.
{ throw AlreadyPackedException(msg); }
Referenced by PackDjgpp2::canPack(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), Packer::checkAlreadyPacked(), PackTmt::pack(), PackWcle::pack(), and throwAlreadyPackedByUPX().
throwAlreadyPackedByUPX()
noreturn void throwAlreadyPackedByUPX (const char * msg = nullptr)
Definition at line 99 of file except.cpp.
{
    if (msg == nullptr)
        msg = "already packed by UPX";
    throwAlreadyPacked(msg);
}
References throwAlreadyPacked().
Referenced by PeFile::checkHeaderValues().
throwBadLoader()
noreturn void throwBadLoader ()
Definition at line 130 of file except.cpp.
{ throwInternalError("bad loader"); }
References throwInternalError().
Referenced by PackTos::buildLoader(), PackVmlinuxARMEL::buildLoader(), PackVmlinuxARMEB::buildLoader(), PackVmlinuxPPC32::buildLoader(), PackVmlinuxPPC64LE::buildLoader(), PackVmlinuzARMEL::buildLoader(), Packer::checkPatch(), PackTos::getDecomprOffset(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), ElfLinker::init(), and PackHeader::putPackHeader().
throwCantPack() [1/3]
template<> noreturn void throwCantPack (const char * format, ...)
throwCantPack() [2/3]
noreturn void throwCantPack (const char * msg)
compression
Definition at line 75 of file except.cpp.
{
    // UGLY, but makes things easier
    if (opt->cmd == CMD_NONE)
        throw CantPackException(msg);
    else if (opt->cmd == CMD_COMPRESS)
        throw CantPackException(msg);
    else if (opt->cmd == CMD_FILEINFO)
        throw CantPackException(msg);
    else
        throw CantUnpackException(msg);
}
References CMD_COMPRESS, CMD_FILEINFO, CMD_NONE, and opt.
Referenced by PackLinuxElf32::add_phdrx(), PackLinuxElf64::add_phdrx(), PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), MemBufferBase< T >::begin(), PackPs1::buildLoader(), PackW64PeArm64::buildLoader(), PackCom::canPack(), PackDjgpp2::canPack(), PackExe::canPack(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackMachBase< TMachClass >::canPack(), PackPs1::canPack(), PackSys::canPack(), PackTos::canPack(), PackUnix::canPack(), PackW64PeArm64::canPack(), PackW64PeArm64EC::canPack(), PackLinuxElf32::canPack_Shdr(), PackLinuxElf64::canPack_Shdr(), PackLinuxElf32::canPackOSABI(), PackMachBase< TMachClass >::canUnpack(), MemBufferBase< T >::cbegin(), MemBufferBase< T >::cend(), PeFile::Resource::check(), PackMachFat::check_fat_head(), PackLinuxElf32::check_pt_dynamic(), PackLinuxElf64::check_pt_dynamic(), PackLinuxElf32::check_pt_load(), PackLinuxElf64::check_pt_load(), PackPs1::checkFileHeader(), PackTos::checkFileHeader(), PeFile::checkHeaderValues(), PeFile::checkMachine(), LeFile::countFixups(), PackWcle::decodeFixups(), PackVmlinuzI386::decompressKernel(), PackW64PeArm64::defineSymbols(), PackLinuxElf32::elf_find_section_name(), PackLinuxElf64::elf_find_section_name(), PackLinuxElf64::elf_get_offset_from_address(), PackLinuxElf32::elf_get_offset_from_Phdrs(), PackLinuxElf32::elf_lookup(), PackLinuxElf64::elf_lookup(), PackWcle::encodeEntryTable(), MemBufferBase< T >::end(), MemBuffer::fill(), PackLinuxElf32::find_LOAD_gap(), PackLinuxElf64::find_LOAD_gap(), PeFile::Reloc::finish(), PackLinuxElf32::generateElfHdr(), PackLinuxElf32::get_str_name(), PackLinuxElf64::get_str_name(), MemBuffer::getSizeForCompression(), MemBuffer::getSizeForDecompression(), PeFile::handleStripRelocs(), PackLinuxElf32::invert_pt_dynamic(), PackLinuxElf64::invert_pt_dynamic(), mem_size(), PackW64PeArm64::needForceOption(), MemBufferBase< T >::operator[](), optimize_relocs(), Packer::optimizeReloc(), PackDjgpp2::pack(), PackExe::pack(), PackTmt::pack(), PackTos::pack(), PackW64PeArm64::pack(), PackWcle::pack(), PeFile::pack0(), PackMachBase< TMachClass >::pack1(), PackMachBase< TMachClass >::pack4dylib(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), PackCom::patchLoader(), PackWcle::preprocessFixups(), PeFile::processImports0(), PackWinCeArm::processTls(), PeFile::processTls1(), ptr_diff_bytes(), ptr_udiff_bytes(), ptraddr_check_no_overlap(), MemBufferBase< T >::raw_bytes(), raw_bytes(), raw_index_bytes(), LeFile::readFileHeader(), PackDjgpp2::readFileHeader(), PackTmt::readFileHeader(), PeFile::readFileHeader(), PackExe::readFileHeader(), PeFile::Reloc::readFromRelocationBlock(), LeFile::readImage(), PackVmlinuzI386::readKernel(), PackVmlinuzARMEL::readKernel(), PackWcle::readObjectTable(), LeFile::readPageMap(), PeFile32::readPeHeader(), PeFile64::readPeHeader(), PeFile::readSectionHeaders(), PeFile::readSections(), reloc_entry_encode(), PackW64PeArm64::setOhHeaderSize(), PackLinuxElf32::sort_DT32_offsets(), PackLinuxElf64::sort_DT64_offsets(), MemBuffer::subref_impl(), throwAssertFailed(), throwCantPack(), throwCantPackExact(), throwCantUnpack(), throwFilterException(), xspan_fail_not_same_base(), xspan_fail_nullbase(), xspan_fail_nullptr(), xspan_fail_range_nullbase(), xspan_fail_range_nullptr(), and xspan_fail_range_range().
throwCantPack() [3/3]
template<class T > void throwCantPack (const T * , ...)
throwCantPackExact()
noreturn void throwCantPackExact ()
Definition at line 87 of file except.cpp.
{ throwCantPack("option '--exact' does not work with this file"); }
References throwCantPack().
Referenced by optimize_relocs(), Packer::optimizeReloc(), PackTos::pack(), and PeFile::pack0().
throwCantUnpack() [1/3]
template<> noreturn void throwCantUnpack (const char * format, ...)
throwCantUnpack() [2/3]
noreturn void throwCantUnpack (const char * msg)
decompression
Definition at line 109 of file except.cpp.
{
    // UGLY, but makes things easier
    throwCantPack(msg);
}
References throwCantPack().
Referenced by PeFile::Resource::build(), PackDjgpp2::canUnpack(), PackLinuxElf32::canUnpack(), PackLinuxElf64::canUnpack(), PackMachBase< TMachClass >::canUnpack(), PackPs1::canUnpack(), PackTos::canUnpack(), PeFile::canUnpack0(), PackWcle::decodeEntryTable(), PackHeader::decodePackHeaderFromBuf(), PackUnix::find_overlay_offset(), Packer::getPackHeader(), PackHeader::getPackHeaderSize(), PeFile::Resource::ibufcheck(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), ph_decompress(), PeFile32::processRelocs(), PeFile::rebuildResources(), Packer::testUnpackFormat(), Packer::testUnpackVersion(), PeFile::testUnpackVersion(), throwCantUnpack(), PackLinuxElf32::un_asl_dynsym(), PackLinuxElf64::un_asl_dynsym(), PackLinuxElf32::un_DT_INIT(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), Packer::unoptimizeReloc(), PackCom::unpack(), PackDjgpp2::unpack(), PackExe::unpack(), PackLinuxElf::unpack(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachBase< TMachClass >::unpack(), PackUnix::unpack(), PackVmlinuxBase< TElfClass >::unpack(), PackVmlinuzI386::unpack(), PackVmlinuzARMEL::unpack(), PeFile::unpack0(), PackUnix::unpackExtent(), and xcheck().
throwCantUnpack() [3/3]
template<class T > noreturn void void throwCantUnpack (const T * , ...)
throwChecksumError()
noreturn void throwChecksumError ()
Definition at line 120 of file except.cpp.
{ throw Exception("checksum error"); }
Referenced by ph_decompress(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), and PackUnix::unpack().
throwCompressedDataViolation()
noreturn void throwCompressedDataViolation ()
Definition at line 122 of file except.cpp.
{ throw Exception("compressed data violation"); }
Referenced by ph_decompress(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), and PackUnix::unpack().
throwEOFException()
noreturn void throwEOFException (const char * msg = nullptr, int e = 0)
Definition at line 140 of file except.cpp.
{
    if (msg == nullptr && e == 0)
        msg = "premature end of file";
    throw EOFException(msg, e);
}
Referenced by PackUnix::pack2(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackMachBase< TMachClass >::pack2(), InputFile::readx(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), and PackUnix::unpack().
throwFilterException()
noreturn void throwFilterException ()
Definition at line 89 of file except.cpp.
{ throwCantPack("filter problem"); }
References throwCantPack().
Referenced by Filter::filter(), and Filter::scan().
throwInternalError() [1/3]
template<> noreturn void throwInternalError (const char * format, ...)
throwInternalError() [2/3]
noreturn void throwInternalError (const char * msg)
other
Definition at line 128 of file except.cpp.
{ throw InternalError(msg); }
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackExe::buildLoader(), PackPs1::buildLoader(), PackMachBase< TMachClass >::buildMachLoader(), Packer::checkPatch(), MemBuffer::checkState(), Packer::compress(), Packer::compressWithFilters(), PeFile::Export::convert(), ElfLinker::defineSymbol(), do_one_file(), FileBase::do_sopen(), Filter::filter(), Packer::findOverlapOverhead(), ElfLinker::findSection(), ElfLinker::findSymbol(), PeFile::ImportLinker::getAddress(), PackPs1::getBkupHeader(), Packer::getDecompressorSections(), PackHeader::getPackHeaderSize(), PackPs1::pack(), PackVmlinuxBase< TElfClass >::pack(), PeFile::pack0(), PackLinuxElf::pack2_shlib_overlay_compress(), PackUnix::packExtent(), PackPs1::putBkupHeader(), PackHeader::putPackHeader(), raw_index_bytes(), PeFile::readSections(), ElfLinker::relocate(), ElfLinker::relocate1(), ElfLinkerAMD64::relocate1(), ElfLinkerPpc32::relocate1(), ElfLinkerPpc64::relocate1(), ElfLinkerPpc64le::relocate1(), ElfLinkerX86::relocate1(), Filter::scan(), FileBase::seek(), throwBadLoader(), throwInternalError(), Filter::unfilter(), PackLinuxElf64::unRela64(), upx_compress(), upx_decompress(), upx_test_overlap(), upx_ucl_compress(), upx_ucl_decompress(), and upx_ucl_test_overlap().
throwInternalError() [3/3]
template<class T > noreturn void void throwInternalError (const T * , ...)
throwIOException()
noreturn void throwIOException (const char * msg = nullptr, int e = 0)
Definition at line 138 of file except.cpp.
{ throw IOException(msg, e); }
Referenced by FileBase::chmod(), FileBase::closex(), do_one_file(), FileBase::do_sopen(), InputFile::dupFd(), OutputFile::openStdout(), InputFile::read(), FileBase::rename(), FileBase::seek(), InputFile::seek(), OutputFile::set_extent(), InputFile::sopen(), OutputFile::sopen(), OutputFile::st_size(), FileBase::tell(), FileBase::unlink(), OutputFile::unset_extent(), and OutputFile::write().
throwNotCompressible()
noreturn void throwNotCompressible (const char * msg = nullptr)
Definition at line 95 of file except.cpp.
{ throw NotCompressibleException(msg); }
Referenced by Packer::compressWithFilters(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackUnix::pack(), PackVmlinuxBase< TElfClass >::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), and PackSys::patchLoader().
throwNotPacked()
noreturn void throwNotPacked (const char * msg = nullptr)
Definition at line 114 of file except.cpp.
{
    if (msg == nullptr)
        msg = "not packed by UPX";
    throw NotPackedException(msg);
}
Referenced by PackMaster::getUnpacker().
throwOutOfMemoryException()
noreturn void throwOutOfMemoryException (const char * msg = nullptr)
Definition at line 132 of file except.cpp.
{
    if (msg == nullptr)
        msg = "out of memory";
    throw OutOfMemoryException(msg);
}
Referenced by MemBuffer::alloc(), Packer::compress(), PackPs1::getBkupHeader(), ElfLinker::init(), ph_decompress(), and ph_testOverlappingDecompression().
throwUnknownExecutableFormat()
noreturn void throwUnknownExecutableFormat (const char * msg = nullptr, bool warn = false)
Definition at line 91 of file except.cpp.
{
    throw UnknownExecutableFormatException(msg, warn);
}
Referenced by PackMachFat::check_fat_head(), PackMaster::fileInfo(), and PackMaster::getPacker().