My Project: src/file.cpp File Reference
file.cpp File Reference
#include "conf.h"
#include "file.h"
Functions
TEST_CASE ("file")
Function Documentation
TEST_CASE()
TEST_CASE ("file")
Definition at line 381 of file file.cpp.
                  {
    InputFile fi;
    CHECK(!fi.isOpen());
    CHECK(fi.getFd() == -1);
    CHECK(fi.st_size() == 0);
    OutputFile fo;
    CHECK(!fo.isOpen());
    CHECK(fo.getFd() == -1);
    CHECK(fo.getBytesWritten() == 0);
}
References OutputFile::getBytesWritten(), FileBase::getFd(), FileBase::isOpen(), and FileBase::st_size().