My Project: src/filter.cpp File Reference
filter.cpp File Reference
#include "conf.h"
#include "filter.h"
#include "file.h"
Functions
static void initFilter (Filter *f, byte *buf, unsigned buf_len) noexcept
util
Function Documentation
initFilter()
static void initFilter (Filter * f, byte * buf, unsigned buf_len) static noexcept
util
Definition at line 36 of file filter.cpp.
{
    f->buf = buf;
    f->buf_len = buf_len;
    // clear output parameters
    f->calls = f->wrongcalls = f->noncalls = f->firstcall = f->lastcall = 0;
}
References buf.
Referenced by Filter::filter(), Filter::init(), Filter::scan(), and Filter::unfilter().