My Project: src/linker.cpp File Reference
linker.cpp File Reference
#include "conf.h"
#include "linker.h"
Macros
#define MIPS_HI(a) (((a) >> 16) + (((a) &0x8000) >> 15))
#define MIPS_LO(a) ((a) &0xffff)
#define MIPS_PC16(a) ((a) >> 2)
#define MIPS_PC26(a) (((a) &0x0fffffff) >> 2)
#define MIPS_HI(a) (((a) >> 16) + (((a) &0x8000) >> 15))
#define MIPS_LO(a) ((a) &0xffff)
#define MIPS_PC16(a) ((a) >> 2)
#define MIPS_PC26(a) (((a) &0x0fffffff) >> 2)
Functions
static unsigned hex (uchar c)
static bool grow_capacity (unsigned size, unsigned *capacity)
template<class T >
static T ** realloc_array (T **array, size_t capacity) may_throw
template<class T >
static void free_array (T **array, size_t count) noexcept
Macro Definition Documentation
MIPS_HI [1/2]
#define MIPS_HI (a) (((a) >> 16) + (((a) &0x8000) >> 15))
MIPS_HI [2/2]
#define MIPS_HI (a) (((a) >> 16) + (((a) &0x8000) >> 15))
MIPS_LO [1/2]
#define MIPS_LO (a) ((a) &0xffff)
MIPS_LO [2/2]
#define MIPS_LO (a) ((a) &0xffff)
MIPS_PC16 [1/2]
#define MIPS_PC16 (a) ((a) >> 2)
MIPS_PC16 [2/2]
#define MIPS_PC16 (a) ((a) >> 2)
MIPS_PC26 [1/2]
#define MIPS_PC26 (a) (((a) &0x0fffffff) >> 2)
MIPS_PC26 [2/2]
#define MIPS_PC26 (a) (((a) &0x0fffffff) >> 2)
Function Documentation
free_array()
template<class T > static void free_array (T ** array, size_t count) static noexcept
Definition at line 53 of file linker.cpp.
{
    for (size_t i = 0; i < count; i++) {
        T *item = upx::atomic_exchange(&array[i], (T *) nullptr);
        delete item;
    }
    ::free(array); // NOLINT(bugprone-multi-level-implicit-pointer-conversion)
}
References upx::atomic_exchange().
Referenced by ElfLinker::~ElfLinker().
grow_capacity()
static bool grow_capacity (unsigned size, unsigned * capacity) static
Definition at line 33 of file linker.cpp.
{
    if (size < *capacity)
        return false;
    if (*capacity == 0)
        *capacity = 16;
    while (size >= *capacity)
        *capacity *= 2;
    return true;
}
References size().
Referenced by ElfLinker::addRelocation(), ElfLinker::addSection(), and ElfLinker::addSymbol().
hex()
static unsigned hex (uchar c) static
Definition at line 31 of file linker.cpp.
{ return (c & 0xf) + (c > '9' ? 9 : 0); }
Referenced by ElfLinker::addLoader().
realloc_array()
template<class T > static T ** realloc_array (T ** array, size_t capacity) static
Definition at line 44 of file linker.cpp.
{
    assert_noexcept(capacity > 0);
    // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
    void *p = realloc(array, mem_size(sizeof(T *), capacity));
    assert_noexcept(p != nullptr);
    return static_cast<T **>(p);
}
References assert_noexcept, and mem_size().
Referenced by ElfLinker::addRelocation(), ElfLinker::addSection(), and ElfLinker::addSymbol().