My Project: src/stub/src/include/linux.h File Reference
linux.h File Reference
Classes
struct timeval
struct timespec
struct Elf32_Ehdr
struct Elf64_Ehdr
struct Elf32_Phdr
struct Elf64_Phdr
struct Elf32_auxv_t
struct Elf64_auxv_t
struct b_info
struct l_info
struct p_info
Macros
#define ACC_UNUSED(var) ((void) var)
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define O_RDONLY 00
#define O_WRONLY 01
#define O_RDWR 02
#define O_CREAT 0100
#define O_EXCL 0200
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define F_OK 0
#define F_GETFD 1
#define F_SETFD 2
#define FD_CLOEXEC 1
#define ENOENT 2
#define EINTR 4
#define PROT_READ 0x1
#define PROT_WRITE 0x2
#define PROT_EXEC 0x4
#define PROT_NONE 0x0
#define MAP_SHARED 0x01
#define MAP_PRIVATE 0x02
#define MAP_FIXED 0x10
#define MAP_ANONYMOUS 0x20
#define MAP_DENYWRITE 0x0800 /* ETXTBSY */
#define PR_SET_MM 35
#define PR_SET_MM_START_BRK 6
#define PR_SET_MM_BRK 7
#define EI_NIDENT 16
#define AT_NULL 0
#define AT_IGNORE 1
#define AT_PHDR 3
#define AT_PHENT 4
#define AT_PHNUM 5
#define AT_PAGESZ 6
#define AT_BASE 7
#define AT_ENTRY 9
#define AT_RANDOM 25 /* Address of 16 random bytes. */
#define ET_EXEC 2
#define ET_DYN 3
#define PF_X 1
#define PF_W 2
#define PF_R 4
#define PT_LOAD 1
#define PT_INTERP 3
#define PT_PHDR 6
#define OVERHEAD 2048
UPX stuff.
#define UPX_MAGIC_LE32 0x21585055
#define UPX2 0x32585055
#define UPX3 0x33585055
#define UPX4 0x34585055
#define nrv_byte unsigned char
#define nrv_bytep unsigned char *
#define nrv_voidp void *
#define CONST_CAST(type, var) ((type) ((uintptr_t) (var)))
#define __attribute_cdecl /*empty*/
Typedefs
typedef long ptrdiff_t
typedef long ssize_t
typedef unsigned long size_t
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef int int32_t
typedef unsigned uint32_t
typedef long long int64_t
typedef unsigned long long uint64_t
typedef size_t uintptr_t
typedef long off_t
typedef void * caddr_t
typedef unsigned pid_t
typedef uint16_t Elf32_Half
<elf.h>
typedef uint16_t Elf64_Half
typedef uint32_t Elf32_Word
typedef int32_t Elf32_Sword
typedef uint32_t Elf64_Word
typedef int32_t Elf64_Sword
typedef uint64_t Elf32_Xword
typedef int64_t Elf32_Sxword
typedef uint64_t Elf64_Xword
typedef int64_t Elf64_Sxword
typedef uint32_t Elf32_Addr
typedef uint64_t Elf64_Addr
typedef uint32_t Elf32_Off
typedef uint64_t Elf64_Off
typedef uint16_t Elf32_Section
typedef uint16_t Elf64_Section
typedef Elf32_Half Elf32_Versym
typedef Elf64_Half Elf64_Versym
typedef int nrv_int
typedef int nrv_int32
typedef unsigned int nrv_uint
typedef unsigned int nrv_uint32
Functions
void * brk (void *)
i386 syscalls
int close (int)
void exit (int) __attribute__((__noreturn__
int ftruncate (int fd, size_t len)
off_t lseek (int fd, off_t offset, int whence)
int memfd_create (char const *, unsigned)
int munmap (void *, size_t)
int mprotect (void const *, size_t, int)
int open (char const *, unsigned, unsigned)
int openat (int fd, char const *, unsigned, unsigned)
ssize_t read (int, void *, size_t)
int unlink (char const *)
ssize_t write (int, void const *, size_t)
void __clear_cache (void *, void *)
void * mmap (void *, size_t, int, int, int, off_t)
Variables
void __nothrow__
Macro Definition Documentation
__attribute_cdecl
#define __attribute_cdecl /*empty*/
Definition at line 769 of file linux.h.
ACC_UNUSED
#define ACC_UNUSED (var) ((void) var)
Definition at line 44 of file linux.h.
AT_BASE
#define AT_BASE 7
Definition at line 676 of file linux.h.
AT_ENTRY
#define AT_ENTRY 9
Definition at line 677 of file linux.h.
AT_IGNORE
#define AT_IGNORE 1
Definition at line 671 of file linux.h.
AT_NULL
#define AT_NULL 0
Definition at line 670 of file linux.h.
AT_PAGESZ
#define AT_PAGESZ 6
Definition at line 675 of file linux.h.
AT_PHDR
#define AT_PHDR 3
Definition at line 672 of file linux.h.
AT_PHENT
#define AT_PHENT 4
Definition at line 673 of file linux.h.
AT_PHNUM
#define AT_PHNUM 5
Definition at line 674 of file linux.h.
AT_RANDOM
#define AT_RANDOM 25 /* Address of 16 random bytes. */
Definition at line 678 of file linux.h.
CONST_CAST
#define CONST_CAST (type, var) ((type) ((uintptr_t) (var)))
Definition at line 755 of file linux.h.
EI_NIDENT
#define EI_NIDENT 16
Definition at line 591 of file linux.h.
EINTR
#define EINTR 4
Definition at line 130 of file linux.h.
ENOENT
#define ENOENT 2
Definition at line 129 of file linux.h.
ET_DYN
#define ET_DYN 3
Definition at line 681 of file linux.h.
ET_EXEC
#define ET_EXEC 2
Definition at line 680 of file linux.h.
F_GETFD
#define F_GETFD 1
Definition at line 124 of file linux.h.
F_OK
#define F_OK 0
Definition at line 122 of file linux.h.
F_SETFD
#define F_SETFD 2
Definition at line 125 of file linux.h.
FD_CLOEXEC
#define FD_CLOEXEC 1
Definition at line 126 of file linux.h.
MAP_ANONYMOUS
#define MAP_ANONYMOUS 0x20
Definition at line 141 of file linux.h.
MAP_DENYWRITE
#define MAP_DENYWRITE 0x0800 /* ETXTBSY */
Definition at line 142 of file linux.h.
MAP_FIXED
#define MAP_FIXED 0x10
Definition at line 140 of file linux.h.
MAP_PRIVATE
#define MAP_PRIVATE 0x02
Definition at line 139 of file linux.h.
MAP_SHARED
#define MAP_SHARED 0x01
Definition at line 138 of file linux.h.
nrv_byte
#define nrv_byte unsigned char
Definition at line 723 of file linux.h.
nrv_bytep
#define nrv_bytep unsigned char *
Definition at line 724 of file linux.h.
nrv_voidp
#define nrv_voidp void *
Definition at line 725 of file linux.h.
O_CREAT
#define O_CREAT 0100
Definition at line 116 of file linux.h.
O_EXCL
#define O_EXCL 0200
Definition at line 117 of file linux.h.
O_RDONLY
#define O_RDONLY 00
Definition at line 113 of file linux.h.
O_RDWR
#define O_RDWR 02
Definition at line 115 of file linux.h.
O_WRONLY
#define O_WRONLY 01
Definition at line 114 of file linux.h.
OVERHEAD
#define OVERHEAD 2048
UPX stuff.
Definition at line 697 of file linux.h.
PF_R
#define PF_R 4
Definition at line 685 of file linux.h.
PF_W
#define PF_W 2
Definition at line 684 of file linux.h.
PF_X
#define PF_X 1
Definition at line 683 of file linux.h.
PR_SET_MM
#define PR_SET_MM 35
Definition at line 148 of file linux.h.
PR_SET_MM_BRK
#define PR_SET_MM_BRK 7
Definition at line 150 of file linux.h.
PR_SET_MM_START_BRK
#define PR_SET_MM_START_BRK 6
Definition at line 149 of file linux.h.
PROT_EXEC
#define PROT_EXEC 0x4
Definition at line 135 of file linux.h.
PROT_NONE
#define PROT_NONE 0x0
Definition at line 136 of file linux.h.
PROT_READ
#define PROT_READ 0x1
Definition at line 133 of file linux.h.
PROT_WRITE
#define PROT_WRITE 0x2
Definition at line 134 of file linux.h.
PT_INTERP
#define PT_INTERP 3
Definition at line 688 of file linux.h.
PT_LOAD
#define PT_LOAD 1
Definition at line 687 of file linux.h.
PT_PHDR
#define PT_PHDR 6
Definition at line 689 of file linux.h.
R_OK
#define R_OK 4
Definition at line 119 of file linux.h.
SEEK_CUR
#define SEEK_CUR 1
Definition at line 110 of file linux.h.
SEEK_END
#define SEEK_END 2
Definition at line 111 of file linux.h.
SEEK_SET
#define SEEK_SET 0
Definition at line 109 of file linux.h.
UPX2
#define UPX2 0x32585055
Definition at line 704 of file linux.h.
UPX3
#define UPX3 0x33585055
Definition at line 705 of file linux.h.
UPX4
#define UPX4 0x34585055
Definition at line 706 of file linux.h.
UPX_MAGIC_LE32
#define UPX_MAGIC_LE32 0x21585055
Definition at line 699 of file linux.h.
W_OK
#define W_OK 2
Definition at line 120 of file linux.h.
X_OK
#define X_OK 1
Definition at line 121 of file linux.h.
Typedef Documentation
caddr_t
typedef void* caddr_t
Definition at line 76 of file linux.h.
Elf32_Addr
typedef uint32_t Elf32_Addr
Definition at line 581 of file linux.h.
Elf32_Half
typedef uint16_t Elf32_Half
<elf.h>
Definition at line 571 of file linux.h.
Elf32_Off
typedef uint32_t Elf32_Off
Definition at line 583 of file linux.h.
Elf32_Section
typedef uint16_t Elf32_Section
Definition at line 585 of file linux.h.
Elf32_Sword
typedef int32_t Elf32_Sword
Definition at line 574 of file linux.h.
Elf32_Sxword
typedef int64_t Elf32_Sxword
Definition at line 578 of file linux.h.
Elf32_Versym
typedef Elf32_Half Elf32_Versym
Definition at line 587 of file linux.h.
Elf32_Word
typedef uint32_t Elf32_Word
Definition at line 573 of file linux.h.
Elf32_Xword
typedef uint64_t Elf32_Xword
Definition at line 577 of file linux.h.
Elf64_Addr
typedef uint64_t Elf64_Addr
Definition at line 582 of file linux.h.
Elf64_Half
typedef uint16_t Elf64_Half
Definition at line 572 of file linux.h.
Elf64_Off
typedef uint64_t Elf64_Off
Definition at line 584 of file linux.h.
Elf64_Section
typedef uint16_t Elf64_Section
Definition at line 586 of file linux.h.
Elf64_Sword
typedef int32_t Elf64_Sword
Definition at line 576 of file linux.h.
Elf64_Sxword
typedef int64_t Elf64_Sxword
Definition at line 580 of file linux.h.
Elf64_Versym
typedef Elf64_Half Elf64_Versym
Definition at line 588 of file linux.h.
Elf64_Word
typedef uint32_t Elf64_Word
Definition at line 575 of file linux.h.
Elf64_Xword
typedef uint64_t Elf64_Xword
Definition at line 579 of file linux.h.
int32_t
typedef int int32_t
Definition at line 58 of file linux.h.
int64_t
typedef long long int64_t
Definition at line 67 of file linux.h.
nrv_int
typedef int nrv_int
Definition at line 719 of file linux.h.
nrv_int32
typedef int nrv_int32
Definition at line 720 of file linux.h.
nrv_uint
typedef unsigned int nrv_uint
Definition at line 721 of file linux.h.
nrv_uint32
typedef unsigned int nrv_uint32
Definition at line 722 of file linux.h.
off_t
typedef long off_t
Definition at line 73 of file linux.h.
pid_t
typedef unsigned pid_t
Definition at line 77 of file linux.h.
ptrdiff_t
typedef long ptrdiff_t
Definition at line 52 of file linux.h.
size_t
typedef unsigned long size_t
Definition at line 54 of file linux.h.
ssize_t
typedef long ssize_t
Definition at line 53 of file linux.h.
uint16_t
typedef unsigned short uint16_t
Definition at line 57 of file linux.h.
uint32_t
typedef unsigned uint32_t
Definition at line 59 of file linux.h.
uint64_t
typedef unsigned long long uint64_t
Definition at line 68 of file linux.h.
uint8_t
typedef unsigned char uint8_t
Definition at line 56 of file linux.h.
uintptr_t
typedef size_t uintptr_t
Definition at line 70 of file linux.h.
Function Documentation
__clear_cache()
void __clear_cache (void * , void *)
brk()
void * brk (void *)
i386 syscalls
Because of different <asm/unistd.h> versions and subtle bugs in both gcc and egcs we define all syscalls manually.
Also, errno conversion is not necessary in our case, and we use optimized assembly statements to further decrease the size.
close()
int close (int)
exit()
void exit (int)
ftruncate()
int ftruncate (int fd, size_t len)
lseek()
off_t lseek (int fd, off_t offset, int whence)
Referenced by PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), FileBase::seek(), FileBase::tell(), and OutputFile::unset_extent().
memfd_create()
int memfd_create (char const * , unsigned)
mmap()
void * mmap (void * , size_t , int , int , int , off_t)
mprotect()
int mprotect (void const * , size_t , int)
munmap()
int munmap (void * , size_t)
open()
int open (char const * , unsigned , unsigned)
openat()
int openat (int fd, char const * , unsigned , unsigned)
read()
ssize_t read (int , void * , size_t)
unlink()
int unlink (char const *)
write()
ssize_t write (int , void const * , size_t)
Variable Documentation
__nothrow__
void __nothrow__
Definition at line 550 of file linux.h.