My Project: src/util/membuffer.h File Reference
membuffer.h File Reference
#include "xspan_fwd.h"
Classes
class MemBufferBase< T >
MemBufferBase provides some base functionality for treating a MemBuffer as a pointer.
class MemBuffer
MemBuffer.
struct MemBuffer::Stats
Macros
#define XSPAN_REQUIRES_CONVERTIBLE_ANY_DIRECTION(A, B, RType) typename std::enable_if<std::is_same<A, B>::value, RType>::type
#define C MemBufferBase
#define XSPAN_FWD_C_IS_MEMBUFFER 1
Functions
template<class T , class U >
std::enable_if< std::is_integral< U >::value, typenameMemBufferBase< T >::pointer >::type operator+ (U n, const MemBufferBase< T > &mbb) DELETED_FUNCTION
MemBufferBase global overloads.
template<class T >
MemBufferBase< T >::pointer raw_bytes (const MemBufferBase< T > &mbb, size_t size_in_bytes)
template<class T >
MemBufferBase< T >::pointer raw_index_bytes (const MemBufferBase< T > &mbb, size_t index, size_t size_in_bytes)
Macro Definition Documentation
C
#define C MemBufferBase
Definition at line 172 of file membuffer.h.
XSPAN_FWD_C_IS_MEMBUFFER
#define XSPAN_FWD_C_IS_MEMBUFFER 1
Definition at line 173 of file membuffer.h.
XSPAN_REQUIRES_CONVERTIBLE_ANY_DIRECTION
#define XSPAN_REQUIRES_CONVERTIBLE_ANY_DIRECTION (A, B, RType) typename std::enable_if<std::is_same<A, B>::value, RType>::type
Definition at line 169 of file membuffer.h.
Function Documentation
operator+()
template<class T , class U > std::enable_if< std::is_integral< U >::value, typenameMemBufferBase< T >::pointer >::type operator+ (U n, const MemBufferBase< T > & mbb) inline
MemBufferBase global overloads.
raw_bytes()
template<class T > MemBufferBase< T >::pointer raw_bytes (const MemBufferBase< T > & mbb, size_t size_in_bytes) inline
Definition at line 149 of file membuffer.h.
{
    return mbb.raw_bytes(size_in_bytes);
}
References raw_bytes(), MemBufferBase< T >::raw_bytes(), and size_in_bytes.
Referenced by Packer::compress(), data(), PackWcle::decodeFixups(), PackHeader::decodePackHeaderFromBuf(), OutputFile::dump(), PackWcle::encodeImage(), Filter::filter(), PeFile::Reloc::finish(), PeFile::Reloc::next(), Packer::optimizeReloc(), PackExe::pack(), PackWcle::pack(), ph_decompress(), PeFile::processExports(), PeFile::processTls2(), raw_bytes(), raw_index_bytes(), InputFile::read(), PeFile::rebuildImports(), PeFile::rebuildResources(), Filter::scan(), TEST_CASE(), Filter::unfilter(), Packer::unoptimizeReloc(), PackDjgpp2::unpack(), upx_lzma_test_overlap(), upx_zlib_test_overlap(), and OutputFile::write().
raw_index_bytes()
template<class T > MemBufferBase< T >::pointer raw_index_bytes (const MemBufferBase< T > & mbb, size_t index, size_t size_in_bytes) inline
Definition at line 154 of file membuffer.h.
{
    typedef typename MemBufferBase<T>::element_type element_type;
    return mbb.raw_bytes(mem_size(sizeof(element_type), index, size_in_bytes)) + index;
}
References index, mem_size(), MemBufferBase< T >::raw_bytes(), raw_index_bytes(), and size_in_bytes.
Referenced by PeFile::Reloc::finish(), PackTmt::pack(), raw_index_bytes(), TEST_CASE(), PackTmt::unpack(), upx_lzma_test_overlap(), and upx_zlib_test_overlap().