My Project: src/util/membuffer.cpp File Reference
membuffer.cpp File Reference
#include "../conf.h"
#include "membuffer.h"
Macros
#define debug_set(var, expr) /*empty*/
#define PTR_BITS32(p) ((upx_uint32_t) (ptr_get_address(p) & 0xffffffff))
#define MAGIC1(p) ((PTR_BITS32(p) ^ 0xfefdbeeb) | 1)
#define MAGIC2(p) ((PTR_BITS32(p) ^ 0xfefdbeeb ^ 0x88224411) | 1)
Functions
void * membuffer_get_void_ptr (MemBuffer &mb) noexcept
unsigned membuffer_get_size (MemBuffer &mb) noexcept
static forceinline constexpr bool use_simple_mcheck () noexcept
bool use_simple_mcheck()
TEST_CASE ("MemBuffer core")
TEST_CASE ("MemBuffer global overloads")
TEST_CASE ("MemBuffer unused 1")
TEST_CASE ("MemBuffer unused 2")
TEST_CASE ("MemBuffer array access")
TEST_CASE ("MemBuffer::getSizeForCompression")
Macro Definition Documentation
debug_set
#define debug_set (var, expr) /*empty*/
Definition at line 43 of file membuffer.cpp.
MAGIC1
#define MAGIC1 (p) ((PTR_BITS32(p) ^ 0xfefdbeeb) | 1)
Definition at line 152 of file membuffer.cpp.
MAGIC2
#define MAGIC2 (p) ((PTR_BITS32(p) ^ 0xfefdbeeb ^ 0x88224411) | 1)
Definition at line 153 of file membuffer.cpp.
PTR_BITS32
#define PTR_BITS32 (p) ((upx_uint32_t) (ptr_get_address(p) & 0xffffffff))
Definition at line 151 of file membuffer.cpp.
Function Documentation
membuffer_get_size()
unsigned membuffer_get_size (MemBuffer & mb) noexcept
Definition at line 36 of file membuffer.cpp.
{ return mb.getSize(); }
membuffer_get_void_ptr()
void * membuffer_get_void_ptr (MemBuffer & mb) noexcept
Definition at line 35 of file membuffer.cpp.
{ return mb.getVoidPtr(); }
TEST_CASE() [1/6]
TEST_CASE ("MemBuffer array access")
Definition at line 334 of file membuffer.cpp.
{
    constexpr size_t N = 16;
    MemBuffer mb(N);
    mb.clear();
    for (size_t i = 0; i != N; ++i)
        mb[i] += 1;
    for (byte *ptr = mb; ptr != mb + N; ++ptr)
        *ptr += 1;
    for (byte *ptr = mb + 0; ptr < mb + N; ++ptr)
        *ptr += 1;
    for (byte *ptr = &mb[0]; ptr != mb.end(); ++ptr)
        *ptr += 1;
    for (byte *ptr = mb.begin(); ptr < mb.end(); ++ptr)
        *ptr += 1;
    for (size_t i = 0; i != N; ++i)
        assert(mb[i] == 5);
    CHECK_NOTHROW((void) &mb[N - 1]);
    CHECK_THROWS((void) &mb[N]); // NOT legal for containers like std::vector or MemBuffer
}
References MemBufferBase< T >::begin(), MemBuffer::clear(), MemBufferBase< T >::end(), N, and ptr.
TEST_CASE() [2/6]
TEST_CASE ("MemBuffer core")
Definition at line 250 of file membuffer.cpp.
{
    constexpr size_t N = 64;
    MemBuffer mb;
    CHECK_THROWS(mb.checkState());
    CHECK_THROWS(mb.alloc(0x30000000 + 1));
    CHECK(raw_bytes(mb, 0) == nullptr);
    CHECK_THROWS(raw_bytes(mb, 1));
    CHECK_THROWS(mb.begin());
    CHECK_THROWS(mb.end());
    CHECK_THROWS(mb.cbegin());
    CHECK_THROWS(mb.cend());
    mb.alloc(N);
    mb.checkState();
    CHECK(mb.begin() == mb.cbegin());
    CHECK(mb.end() == mb.cend());
    CHECK(mb.begin() == &mb[0]);
    CHECK(mb.end() == &mb[0] + N);
    CHECK(mb.cbegin() == &mb[0]);
    CHECK(mb.cend() == &mb[0] + N);
    CHECK(raw_bytes(mb, N) != nullptr);
    CHECK(raw_bytes(mb, N) == mb.getVoidPtr());
    CHECK_THROWS(raw_bytes(mb, N + 1));
    CHECK_NOTHROW(mb + N);
    CHECK_THROWS(mb + (N + 1));
#if ALLOW_INT_PLUS_MEMBUFFER
    CHECK_NOTHROW(N + mb);
    CHECK_THROWS((N + 1) + mb);
#endif
    CHECK_NOTHROW(mb.subref("", 0, N));
    CHECK_NOTHROW(mb.subref("", N, 0));
    CHECK_THROWS(mb.subref("", 1, N));
    CHECK_THROWS(mb.subref("", N, 1));
    if (use_simple_mcheck()) {
        byte *p = raw_bytes(mb, 0);
        upx_uint32_t magic1 = get_ne32(p - 4);
        set_ne32(p - 4, magic1 ^ 1);
        CHECK_THROWS(mb.checkState());
        set_ne32(p - 4, magic1);
        mb.checkState();
    }
}
References MemBuffer::alloc(), MemBufferBase< T >::begin(), MemBufferBase< T >::cbegin(), MemBufferBase< T >::cend(), MemBuffer::checkState(), MemBufferBase< T >::end(), get_ne32(), MemBuffer::getVoidPtr(), N, raw_bytes(), set_ne32(), MemBuffer::subref(), and use_simple_mcheck().
TEST_CASE() [3/6]
TEST_CASE ("MemBuffer global overloads")
Definition at line 292 of file membuffer.cpp.
{
    MemBuffer mb(1);
    MemBuffer mb4(4);
    mb.clear();
    mb4.clear();
    CHECK(memcmp(mb, "\x00", 1) == 0);
    CHECK_THROWS(memcmp(mb, "\x00\x00", 2)); // NOLINT(bugprone-unused-return-value)
    CHECK_THROWS(memcmp("\x00\x00", mb, 2)); // NOLINT(bugprone-unused-return-value)
    CHECK_THROWS(memcmp(mb, mb4, 2));        // NOLINT(bugprone-unused-return-value)
    CHECK_THROWS(memcmp(mb4, mb, 2));        // NOLINT(bugprone-unused-return-value)
    CHECK_NOTHROW(memset(mb, 255, 1));
    CHECK_THROWS(memset(mb, 254, 2));
    CHECK(mb[0] == 255);
    CHECK_THROWS(get_be16(mb));
    CHECK_THROWS(get_be32(mb));
    CHECK_THROWS(get_be64(mb));
    CHECK_THROWS(get_le16(mb));
    CHECK_THROWS(get_le32(mb));
    CHECK_THROWS(get_le64(mb));
    CHECK_NOTHROW(get_be16(mb4));
    CHECK_NOTHROW(get_be32(mb4));
    CHECK_THROWS(get_be64(mb4));
    CHECK_NOTHROW(get_le16(mb4));
    CHECK_NOTHROW(get_le32(mb4));
    CHECK_THROWS(get_le64(mb4));
    CHECK_NOTHROW(set_be32(mb4, 0));
    CHECK_THROWS(set_be64(mb4, 0));
    CHECK_NOTHROW(set_le32(mb4, 0));
    CHECK_THROWS(set_le64(mb4, 0));
}
References MemBuffer::clear(), get_be16(), get_be32(), get_be64(), get_le16(), get_le32(), get_le64(), memcmp(), memset(), set_be32(), set_be64(), set_le32(), and set_le64().
TEST_CASE() [4/6]
TEST_CASE ("MemBuffer unused 1")
Definition at line 323 of file membuffer.cpp.
{
    MemBuffer mb;
    CHECK(mb.raw_ptr() == nullptr);
    CHECK(mb.raw_size_in_bytes() == 0);
}
References MemBufferBase< T >::raw_ptr(), and MemBufferBase< T >::raw_size_in_bytes().
TEST_CASE() [5/6]
TEST_CASE ("MemBuffer unused 2")
Definition at line 329 of file membuffer.cpp.
{
    MemBuffer mb;
    (void) mb;
}
TEST_CASE() [6/6]
TEST_CASE ("MemBuffer::getSizeForCompression")
Definition at line 354 of file membuffer.cpp.
{
    CHECK_THROWS(MemBuffer::getSizeForCompression(0));
    CHECK_THROWS(MemBuffer::getSizeForDecompression(0));
    CHECK(MemBuffer::getSizeForCompression(1) == 513);
    CHECK(MemBuffer::getSizeForCompression(256) == 800);
    CHECK(MemBuffer::getSizeForCompression(1024) == 1664);
    CHECK(MemBuffer::getSizeForCompression(1024 * 1024) == 1180160);         // 0x00100000
    CHECK(MemBuffer::getSizeForCompression(64 * 1024 * 1024) == 75497984);   // 0x04000000
    CHECK(MemBuffer::getSizeForCompression(512 * 1024 * 1024) == 603980288); // 0x20000000
    CHECK(MemBuffer::getSizeForCompression(640 * 1024 * 1024) == 754975232); // 0x28000000
    // "682 MiB Ought to be Enough for Anyone" --Markus F.X.J. Oberhumer, 2023 ;-)
    CHECK(MemBuffer::getSizeForCompression(682 * 1024 * 1024) == 804520448); // 0x2aa00000
    CHECK(MemBuffer::getSizeForCompression(715827428) == UPX_RSIZE_MAX);     // 0x2aaaa8e4
    CHECK_THROWS(MemBuffer::getSizeForCompression(715827428 + 1));           // 0x2aaaa8e4 + 1
}
References MemBuffer::getSizeForCompression(), MemBuffer::getSizeForDecompression(), and UPX_RSIZE_MAX.
use_simple_mcheck()
static forceinline constexpr bool use_simple_mcheck () static constexpr noexcept
bool use_simple_mcheck()
Definition at line 71 of file membuffer.cpp.
{ return true; }
Referenced by MemBuffer::alloc(), MemBuffer::checkState(), MemBuffer::dealloc(), and TEST_CASE().