My Project: src/msg.cpp File Reference
msg.cpp File Reference
#include "util/system_headers.h"
#include <typeinfo>
#include "conf.h"
Functions
void printSetNl (int need_nl) noexcept
void printClearLine (FILE *f) noexcept
static void pr_print (bool c, const char *msg) noexcept
static void pr_error (const char *iname, const char *msg, bool is_warning) noexcept
void printErr (const char *iname, const Throwable &e) noexcept
void printErr (const char *iname, const char *format,...) noexcept
void printWarn (const char *iname, const char *format,...) noexcept
void printUnhandledException (const char *iname, const std::exception *e) noexcept
static void info_print (const char *msg)
void infoHeader ()
void infoHeader (const char *format,...)
void info (const char *format,...)
void infoWarning (const char *format,...)
void infoWriting (const char *what, upx_int64_t size)
Variables
static int pr_need_nl = 0
static int info_header = 0
info
Function Documentation
info()
void info (const char * format, ...)
Definition at line 190 of file msg.cpp.
{
    if (opt->info_mode <= 0)
        return;
    va_list args;
    char buf[1024];
    const int n = 4 * info_header;
    memset(buf, ' ', n);
    va_start(args, format);
    upx_safe_vsnprintf(buf + n, sizeof(buf) - n, format, args);
    va_end(args);
    info_print(buf);
}
References buf, info_header, info_print(), memset(), n, opt, and upx_safe_vsnprintf().
Referenced by infoWarning(), and infoWriting().
info_print()
static void info_print (const char * msg) static
Definition at line 161 of file msg.cpp.
{
    if (opt->info_mode <= 0)
        return;
    FILE *f = opt->to_stdout ? stderr : stdout;
    if (pr_need_nl) {
        printClearLine(f);
        con_fprintf(f, "%s\n", msg);
    } else if (pr_need_nl)
        con_fprintf(f, "\n%s\n", msg);
    else
        con_fprintf(f, "%s\n", msg);
    fflush(f);
    printSetNl(0);
}
References con_fprintf, opt, pr_need_nl, printClearLine(), and printSetNl().
Referenced by info(), and infoHeader().
infoHeader() [1/2]
void infoHeader ()
Definition at line 176 of file msg.cpp.
{ info_header = 0; }
References info_header.
Referenced by do_files(), PeFile::pack0(), PeFile::readSectionHeaders(), and PeFile::unpack0().
infoHeader() [2/2]
void infoHeader (const char * format, ...)
Definition at line 178 of file msg.cpp.
{
    if (opt->info_mode <= 0)
        return;
    va_list args;
    char buf[1024];
    va_start(args, format);
    upx_safe_vsnprintf(buf, sizeof(buf), format, args);
    va_end(args);
    info_print(buf);
    info_header = 1;
}
References buf, info_header, info_print(), opt, and upx_safe_vsnprintf().
infoWarning()
void infoWarning (const char * format, ...)
Definition at line 203 of file msg.cpp.
{
    if (opt->info_mode <= 0)
        return;
    va_list args;
    char buf[1024];
    va_start(args, format);
    upx_safe_vsnprintf(buf, sizeof(buf), format, args);
    va_end(args);
    info("[WARNING] %s\n", buf);
}
References buf, info(), opt, and upx_safe_vsnprintf().
infoWriting()
void infoWriting (const char * what, upx_int64_t size)
Definition at line 214 of file msg.cpp.
{
    if (opt->info_mode <= 0)
        return;
    info("Writing %s: %lld bytes", what, size);
}
References info(), opt, and size().
Referenced by PeFile::pack0().
pr_error()
static void pr_error (const char * iname, const char * msg, bool is_warning) static noexcept
Definition at line 66 of file msg.cpp.
{
    fflush(stdout);
    fflush(stderr);
    char buf[1024];
    buf[0] = 0;
    if (pr_need_nl == 2)
        printClearLine(stdout);
    else if (pr_need_nl) {
        buf[0] = '\n';
        buf[1] = 0;
        printSetNl(0);
    }
    // This hack is needed, otherwise error messages may get lost
    // when the cursor is not yet at the bottom of the screen.
    // At least I can use some colors then...
    bool c = acc_isatty(STDERR_FILENO) ? 1 : 0;
    int fg = con_fg(stderr, FG_BRTRED);
    upx_safe_snprintf(buf + strlen(buf), sizeof(buf) - strlen(buf), "%s: ", progname);
    pr_print(c, buf);
    //(void)con_fg(stderr,FG_RED);
    upx_safe_snprintf(buf, sizeof(buf), "%s: ", iname);
    pr_print(c, buf);
    //(void)con_fg(stderr,FG_BRTRED);
    pr_print(c, msg);
    pr_print(c, "\n");
    fflush(stdout);
    fflush(stderr);
    fg = con_fg(stderr, fg);
    UNUSED(is_warning);
    UNUSED(fg);
}
References buf, con_fg, pr_need_nl, pr_print(), printClearLine(), printSetNl(), progname, STDERR_FILENO, strlen, UNUSED, and upx_safe_snprintf().
Referenced by printErr(), and printWarn().
pr_print()
static void pr_print (bool c, const char * msg) static noexcept
Definition at line 59 of file msg.cpp.
{
    if (c && !opt->to_stdout)
        con_fprintf(stderr, "%s", msg);
    else
        fprintf(stderr, "%s", msg);
}
References con_fprintf, and opt.
Referenced by pr_error().
printClearLine()
void printClearLine (FILE * f) noexcept
Definition at line 40 of file msg.cpp.
{
    static char clear_line_msg[1 + 79 + 1 + 1];
    if (!clear_line_msg[0]) {
        char *msg = clear_line_msg;
        msg[0] = '\r';
        memset(msg + 1, ' ', 79);
        msg[80] = '\r';
        msg[81] = 0;
    }
    fflush(stdout);
    fflush(stderr);
    if (f == nullptr)
        f = stdout;
    con_fprintf(f, "%s", clear_line_msg);
    fflush(f);
    printSetNl(0);
}
References con_fprintf, memset(), and printSetNl().
Referenced by UiPacker::endCallback(), info_print(), pr_error(), and UiPacker::uiPackEnd().
printErr() [1/2]
void printErr (const char * iname, const char * format, ...) noexcept
Definition at line 123 of file msg.cpp.
{
    va_list args;
    char buf[1024];
    va_start(args, format);
    upx_safe_vsnprintf(buf, sizeof(buf), format, args);
    va_end(args);
    pr_error(iname, buf, false);
}
References buf, pr_error(), and upx_safe_vsnprintf().
printErr() [2/2]
void printErr (const char * iname, const Throwable & e) noexcept
Definition at line 101 of file msg.cpp.
{
    char buf[1024];
    size_t l;
    upx_safe_snprintf(buf, sizeof(buf), "%s", prettyExceptionName(typeid(e).name()));
    l = strlen(buf);
    if (l < sizeof(buf) && e.getMsg())
        upx_safe_snprintf(buf + l, sizeof(buf) - l, ": %s", e.getMsg());
    l = strlen(buf);
    if (l < sizeof(buf) && e.getErrno()) {
        upx_safe_snprintf(buf + l, sizeof(buf) - l, ": %s", strerror(e.getErrno()));
#if 1
        // some compilers (e.g. Borland C++) put a trailing '\n'
        // into the strerror() result
        l = strlen(buf);
        while (l-- > 0 && (buf[l] == '\n' || buf[l] == ' '))
            buf[l] = 0;
#endif
    }
    pr_error(iname, buf, e.isWarning());
}
References buf, pr_error(), prettyExceptionName(), strlen, and upx_safe_snprintf().
Referenced by MemBuffer::dealloc(), do_files(), main(), and printUnhandledException().
printSetNl()
void printSetNl (int need_nl) noexcept
Definition at line 38 of file msg.cpp.
{ pr_need_nl = need_nl; }
References pr_need_nl.
Referenced by UiPacker::doCallback(), UiPacker::endCallback(), info_print(), pr_error(), printClearLine(), UiPacker::startCallback(), UiPacker::uiList(), UiPacker::uiListTotal(), UiPacker::uiPackEnd(), UiPacker::uiTestEnd(), UiPacker::uiTestStart(), and UiPacker::uiUnpackEnd().
printUnhandledException()
void printUnhandledException (const char * iname, const std::exception * e) noexcept
Definition at line 145 of file msg.cpp.
{
    if (e != nullptr)
        printErr(iname, "unhandled exception: %s\n", prettyExceptionName(e->what()));
    else
        printErr(iname, "internal error: unhandled exception!\n");
    if (opt->cmd != CMD_COMPRESS) {
        printErr(iname, "  this file has possibly been modified/hacked; take care!\n");
    }
}
References CMD_COMPRESS, opt, prettyExceptionName(), and printErr().
Referenced by do_files().
printWarn()
void printWarn (const char * iname, const char * format, ...) noexcept
Definition at line 134 of file msg.cpp.
{
    va_list args;
    char buf[1024];
    va_start(args, format);
    upx_safe_vsnprintf(buf, sizeof(buf), format, args);
    va_end(args);
    pr_error(iname, buf, true);
}
References buf, pr_error(), and upx_safe_vsnprintf().
Variable Documentation
info_header
int info_header = 0 static
info
Definition at line 159 of file msg.cpp.
Referenced by info(), and infoHeader().
pr_need_nl
int pr_need_nl = 0 static
Definition at line 36 of file msg.cpp.
Referenced by info_print(), pr_error(), and printSetNl().