My Project: upx::compile_time Namespace Reference
upx::compile_time Namespace Reference
compile_time
Functions
constexpr std::size_t string_len (const char *a) noexcept
constexpr bool string_eq (const char *a, const char *b) noexcept
constexpr bool string_lt (const char *a, const char *b) noexcept
forceinline constexpr bool string_ne (const char *a, const char *b) noexcept
forceinline constexpr bool string_gt (const char *a, const char *b) noexcept
forceinline constexpr bool string_le (const char *a, const char *b) noexcept
forceinline constexpr bool string_ge (const char *a, const char *b) noexcept
constexpr bool mem_eq (const char *a, const char *b, std::size_t n) noexcept
constexpr bool mem_eq (const unsigned char *a, const unsigned char *b, std::size_t n) noexcept
constexpr bool mem_eq (const char *a, const unsigned char *b, std::size_t n) noexcept
constexpr bool mem_eq (const unsigned char *a, const char *b, std::size_t n) noexcept
constexpr void mem_set (char *p, char c, std::size_t n) noexcept
constexpr void mem_set (unsigned char *p, unsigned char c, std::size_t n) noexcept
forceinline constexpr void mem_clear (char *p, std::size_t n) noexcept
forceinline constexpr void mem_clear (unsigned char *p, std::size_t n) noexcept
forceinline constexpr upx_uint16_t bswap16 (upx_uint16_t v) noexcept
forceinline constexpr upx_uint32_t bswap32 (upx_uint32_t v) noexcept
forceinline constexpr upx_uint64_t bswap64 (upx_uint64_t v) noexcept
forceinline constexpr upx_uint16_t get_be16 (const byte *p) noexcept
forceinline constexpr upx_uint32_t get_be24 (const byte *p) noexcept
forceinline constexpr upx_uint32_t get_be32 (const byte *p) noexcept
forceinline constexpr upx_uint64_t get_be64 (const byte *p) noexcept
forceinline constexpr void set_be16 (byte *p, upx_uint16_t v) noexcept
forceinline constexpr void set_be24 (byte *p, upx_uint32_t v) noexcept
forceinline constexpr void set_be32 (byte *p, upx_uint32_t v) noexcept
forceinline constexpr void set_be64 (byte *p, upx_uint64_t v) noexcept
forceinline constexpr upx_uint16_t get_le16 (const byte *p) noexcept
forceinline constexpr upx_uint32_t get_le24 (const byte *p) noexcept
forceinline constexpr upx_uint32_t get_le32 (const byte *p) noexcept
forceinline constexpr upx_uint64_t get_le64 (const byte *p) noexcept
forceinline constexpr void set_le16 (byte *p, upx_uint16_t v) noexcept
forceinline constexpr void set_le24 (byte *p, upx_uint32_t v) noexcept
forceinline constexpr void set_le32 (byte *p, upx_uint32_t v) noexcept
forceinline constexpr void set_le64 (byte *p, upx_uint64_t v) noexcept
forceinline constexpr upx_uint16_t get_ne16 (const byte *p) noexcept
forceinline constexpr upx_uint32_t get_ne24 (const byte *p) noexcept
forceinline constexpr upx_uint32_t get_ne32 (const byte *p) noexcept
forceinline constexpr upx_uint64_t get_ne64 (const byte *p) noexcept
forceinline constexpr void set_ne16 (byte *p, upx_uint16_t v) noexcept
forceinline constexpr void set_ne24 (byte *p, upx_uint32_t v) noexcept
forceinline constexpr void set_ne32 (byte *p, upx_uint32_t v) noexcept
forceinline constexpr void set_ne64 (byte *p, upx_uint64_t v) noexcept
Detailed Description
compile_time
Function Documentation
bswap16()
forceinline constexpr upx_uint16_t upx::compile_time::bswap16 (upx_uint16_t v) constexpr noexcept
Definition at line 433 of file cxxlib.h.
{
    typedef unsigned U;
    return (upx_uint16_t) ((((U) v >> 8) & 0xff) | (((U) v & 0xff) << 8));
}
References U.
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_bswap16(), and TEST_CASE().
bswap32()
forceinline constexpr upx_uint32_t upx::compile_time::bswap32 (upx_uint32_t v) constexpr noexcept
Definition at line 437 of file cxxlib.h.
{
    typedef upx_uint32_t U;
    return (upx_uint32_t) ((((U) v >> 24) & 0xff) | (((U) v >> 8) & 0xff00) |
                           (((U) v & 0xff00) << 8) | (((U) v & 0xff) << 24));
}
References U.
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_bswap32(), and TEST_CASE().
bswap64()
forceinline constexpr upx_uint64_t upx::compile_time::bswap64 (upx_uint64_t v) constexpr noexcept
Definition at line 442 of file cxxlib.h.
{
    return (upx_uint64_t) (((upx_uint64_t) bswap32((upx_uint32_t) v) << 32) |
                           bswap32((upx_uint32_t) (v >> 32)));
}
References bswap32.
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_bswap64(), and TEST_CASE().
get_be16()
forceinline constexpr upx_uint16_t upx::compile_time::get_be16 (const byte * p) constexpr noexcept
Definition at line 447 of file cxxlib.h.
{
    typedef unsigned U;
    return (upx_uint16_t) (((U) p[0] << 8) | ((U) p[1] << 0));
}
References U.
Referenced by get_ne16(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be16(), TEST_CASE(), and upx_compiler_sanity_check().
get_be24()
forceinline constexpr upx_uint32_t upx::compile_time::get_be24 (const byte * p) constexpr noexcept
Definition at line 451 of file cxxlib.h.
{
    typedef upx_uint32_t U;
    return (upx_uint32_t) (((U) p[0] << 16) | ((U) p[1] << 8) | ((U) p[2] << 0));
}
References U.
Referenced by get_be24(), get_ne24(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be24(), TEST_CASE(), and upx_compiler_sanity_check().
get_be32()
forceinline constexpr upx_uint32_t upx::compile_time::get_be32 (const byte * p) constexpr noexcept
Definition at line 455 of file cxxlib.h.
{
    typedef upx_uint32_t U;
    return (upx_uint32_t) (((U) p[0] << 24) | ((U) p[1] << 16) | ((U) p[2] << 8) | ((U) p[3] << 0));
}
References U.
Referenced by get_ne32(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be32(), TEST_CASE(), and upx_compiler_sanity_check().
get_be64()
forceinline constexpr upx_uint64_t upx::compile_time::get_be64 (const byte * p) constexpr noexcept
Definition at line 459 of file cxxlib.h.
{
    typedef upx_uint64_t U;
    return (upx_uint64_t) (((U) p[0] << 56) | ((U) p[1] << 48) | ((U) p[2] << 40) |
                           ((U) p[3] << 32) | ((U) p[4] << 24) | ((U) p[5] << 16) |
                           ((U) p[6] << 8) | ((U) p[7] << 0));
}
References U.
Referenced by get_ne64(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be64(), TEST_CASE(), and upx_compiler_sanity_check().
get_le16()
forceinline constexpr upx_uint16_t upx::compile_time::get_le16 (const byte * p) constexpr noexcept
Definition at line 492 of file cxxlib.h.
{
    typedef unsigned U;
    return (upx_uint16_t) (((U) p[0] << 0) | ((U) p[1] << 8));
}
References U.
Referenced by get_ne16(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le16(), TEST_CASE(), and upx_compiler_sanity_check().
get_le24()
forceinline constexpr upx_uint32_t upx::compile_time::get_le24 (const byte * p) constexpr noexcept
Definition at line 496 of file cxxlib.h.
{
    typedef upx_uint32_t U;
    return (upx_uint32_t) (((U) p[0] << 0) | ((U) p[1] << 8) | ((U) p[2] << 16));
}
References U.
Referenced by get_le24(), get_ne24(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le24(), TEST_CASE(), and upx_compiler_sanity_check().
get_le32()
forceinline constexpr upx_uint32_t upx::compile_time::get_le32 (const byte * p) constexpr noexcept
Definition at line 500 of file cxxlib.h.
{
    typedef upx_uint32_t U;
    return (upx_uint32_t) (((U) p[0] << 0) | ((U) p[1] << 8) | ((U) p[2] << 16) | ((U) p[3] << 24));
}
References U.
Referenced by get_ne32(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le32(), TEST_CASE(), and upx_compiler_sanity_check().
get_le64()
forceinline constexpr upx_uint64_t upx::compile_time::get_le64 (const byte * p) constexpr noexcept
Definition at line 504 of file cxxlib.h.
{
    typedef upx_uint64_t U;
    return (upx_uint64_t) (((U) p[0] << 0) | ((U) p[1] << 8) | ((U) p[2] << 16) | ((U) p[3] << 24) |
                           ((U) p[4] << 32) | ((U) p[5] << 40) | ((U) p[6] << 48) |
                           ((U) p[7] << 56));
}
References U.
Referenced by get_ne64(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le64(), TEST_CASE(), and upx_compiler_sanity_check().
get_ne16()
forceinline constexpr upx_uint16_t upx::compile_time::get_ne16 (const byte * p) constexpr noexcept
Definition at line 537 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    return get_be16(p);
#else
    return get_le16(p);
#endif
}
References get_be16(), and get_le16().
Referenced by get_ne16().
get_ne24()
forceinline constexpr upx_uint32_t upx::compile_time::get_ne24 (const byte * p) constexpr noexcept
Definition at line 544 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    return get_be24(p);
#else
    return get_le24(p);
#endif
}
References get_be24(), and get_le24().
get_ne32()
forceinline constexpr upx_uint32_t upx::compile_time::get_ne32 (const byte * p) constexpr noexcept
Definition at line 551 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    return get_be32(p);
#else
    return get_le32(p);
#endif
}
References get_be32(), and get_le32().
Referenced by get_ne32().
get_ne64()
forceinline constexpr upx_uint64_t upx::compile_time::get_ne64 (const byte * p) constexpr noexcept
Definition at line 558 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    return get_be64(p);
#else
    return get_le64(p);
#endif
}
References get_be64(), and get_le64().
Referenced by get_ne64().
mem_clear() [1/2]
forceinline constexpr void upx::compile_time::mem_clear (char * p, std::size_t n) constexpr noexcept
Definition at line 428 of file cxxlib.h.
{ mem_set(p, (char) 0, n); }
References mem_set(), and n.
Referenced by TEST_CASE().
mem_clear() [2/2]
forceinline constexpr void upx::compile_time::mem_clear (unsigned char * p, std::size_t n) constexpr noexcept
Definition at line 429 of file cxxlib.h.
{
    mem_set(p, (unsigned char) 0, n);
}
References mem_set(), and n.
mem_eq() [1/4]
constexpr bool upx::compile_time::mem_eq (const char * a, const char * b, std::size_t n) constexpr noexcept
Definition at line 409 of file cxxlib.h.
{
    return n == 0 || (*a == *b && mem_eq(a + 1, b + 1, n - 1));
}
References b, mem_eq(), and n.
Referenced by mem_eq(), BE16::operator==(), BE32::operator==(), BE64::operator==(), LE16::operator==(), LE32::operator==(), LE64::operator==(), TEST_CASE(), and upx_compiler_sanity_check().
mem_eq() [2/4]
constexpr bool upx::compile_time::mem_eq (const char * a, const unsigned char * b, std::size_t n) constexpr noexcept
Definition at line 415 of file cxxlib.h.
{
    return n == 0 || (*a == *b && mem_eq(a + 1, b + 1, n - 1));
}
References b, mem_eq(), and n.
mem_eq() [3/4]
constexpr bool upx::compile_time::mem_eq (const unsigned char * a, const char * b, std::size_t n) constexpr noexcept
Definition at line 418 of file cxxlib.h.
{
    return n == 0 || (*a == *b && mem_eq(a + 1, b + 1, n - 1));
}
References b, mem_eq(), and n.
mem_eq() [4/4]
constexpr bool upx::compile_time::mem_eq (const unsigned char * a, const unsigned char * b, std::size_t n) constexpr noexcept
Definition at line 412 of file cxxlib.h.
{
    return n == 0 || (*a == *b && mem_eq(a + 1, b + 1, n - 1));
}
References b, mem_eq(), and n.
mem_set() [1/2]
constexpr void upx::compile_time::mem_set (char * p, char c, std::size_t n) constexpr noexcept
Definition at line 422 of file cxxlib.h.
{
    (void) (n == 0 || (*p = c, mem_set(p + 1, c, n - 1), 0));
}
References mem_set(), and n.
Referenced by mem_clear(), mem_set(), and TEST_CASE().
mem_set() [2/2]
constexpr void upx::compile_time::mem_set (unsigned char * p, unsigned char c, std::size_t n) constexpr noexcept
Definition at line 425 of file cxxlib.h.
{
    (void) (n == 0 || (*p = c, mem_set(p + 1, c, n - 1), 0));
}
References mem_set(), and n.
set_be16()
forceinline constexpr void upx::compile_time::set_be16 (byte * p, upx_uint16_t v) constexpr noexcept
Definition at line 466 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 8) & 0xff);
    p[1] = (byte) ((v >> 0) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE16(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be16(), and set_ne16().
set_be24()
forceinline constexpr void upx::compile_time::set_be24 (byte * p, upx_uint32_t v) constexpr noexcept
Definition at line 470 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 16) & 0xff);
    p[1] = (byte) ((v >> 8) & 0xff);
    p[2] = (byte) ((v >> 0) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE24(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be24(), set_be24(), and set_ne24().
set_be32()
forceinline constexpr void upx::compile_time::set_be32 (byte * p, upx_uint32_t v) constexpr noexcept
Definition at line 475 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 24) & 0xff);
    p[1] = (byte) ((v >> 16) & 0xff);
    p[2] = (byte) ((v >> 8) & 0xff);
    p[3] = (byte) ((v >> 0) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE32(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be32(), and set_ne32().
set_be64()
forceinline constexpr void upx::compile_time::set_be64 (byte * p, upx_uint64_t v) constexpr noexcept
Definition at line 481 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 56) & 0xff);
    p[1] = (byte) ((v >> 48) & 0xff);
    p[2] = (byte) ((v >> 40) & 0xff);
    p[3] = (byte) ((v >> 32) & 0xff);
    p[4] = (byte) ((v >> 24) & 0xff);
    p[5] = (byte) ((v >> 16) & 0xff);
    p[6] = (byte) ((v >> 8) & 0xff);
    p[7] = (byte) ((v >> 0) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE64(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be64(), and set_ne64().
set_le16()
forceinline constexpr void upx::compile_time::set_le16 (byte * p, upx_uint16_t v) constexpr noexcept
Definition at line 511 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 0) & 0xff);
    p[1] = (byte) ((v >> 8) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE16(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le16(), and set_ne16().
set_le24()
forceinline constexpr void upx::compile_time::set_le24 (byte * p, upx_uint32_t v) constexpr noexcept
Definition at line 515 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 0) & 0xff);
    p[1] = (byte) ((v >> 8) & 0xff);
    p[2] = (byte) ((v >> 16) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE24(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le24(), set_le24(), and set_ne24().
set_le32()
forceinline constexpr void upx::compile_time::set_le32 (byte * p, upx_uint32_t v) constexpr noexcept
Definition at line 520 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 0) & 0xff);
    p[1] = (byte) ((v >> 8) & 0xff);
    p[2] = (byte) ((v >> 16) & 0xff);
    p[3] = (byte) ((v >> 24) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE32(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le32(), and set_ne32().
set_le64()
forceinline constexpr void upx::compile_time::set_le64 (byte * p, upx_uint64_t v) constexpr noexcept
Definition at line 526 of file cxxlib.h.
{
    p[0] = (byte) ((v >> 0) & 0xff);
    p[1] = (byte) ((v >> 8) & 0xff);
    p[2] = (byte) ((v >> 16) & 0xff);
    p[3] = (byte) ((v >> 24) & 0xff);
    p[4] = (byte) ((v >> 32) & 0xff);
    p[5] = (byte) ((v >> 40) & 0xff);
    p[6] = (byte) ((v >> 48) & 0xff);
    p[7] = (byte) ((v >> 56) & 0xff);
}
Referenced by anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE64(), anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le64(), and set_ne64().
set_ne16()
forceinline constexpr void upx::compile_time::set_ne16 (byte * p, upx_uint16_t v) constexpr noexcept
Definition at line 566 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    set_be16(p, v);
#else
    set_le16(p, v);
#endif
}
References set_be16(), and set_le16().
Referenced by set_ne16().
set_ne24()
forceinline constexpr void upx::compile_time::set_ne24 (byte * p, upx_uint32_t v) constexpr noexcept
Definition at line 573 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    set_be24(p, v);
#else
    set_le24(p, v);
#endif
}
References set_be24(), and set_le24().
set_ne32()
forceinline constexpr void upx::compile_time::set_ne32 (byte * p, upx_uint32_t v) constexpr noexcept
Definition at line 580 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    set_be32(p, v);
#else
    set_le32(p, v);
#endif
}
References set_be32(), and set_le32().
Referenced by set_ne32().
set_ne64()
forceinline constexpr void upx::compile_time::set_ne64 (byte * p, upx_uint64_t v) constexpr noexcept
Definition at line 587 of file cxxlib.h.
{
#if (ACC_ABI_BIG_ENDIAN)
    set_be64(p, v);
#else
    set_le64(p, v);
#endif
}
References set_be64(), and set_le64().
Referenced by set_ne64().
string_eq()
constexpr bool upx::compile_time::string_eq (const char * a, const char * b) constexpr noexcept
Definition at line 390 of file cxxlib.h.
{
    return *a == *b && (*a == '\0' || string_eq(a + 1, b + 1));
}
References b, and string_eq().
Referenced by string_eq(), and string_ne().
string_ge()
forceinline constexpr bool upx::compile_time::string_ge (const char * a, const char * b) constexpr noexcept
Definition at line 405 of file cxxlib.h.
{
    return !string_lt(a, b);
}
References b, and string_lt().
string_gt()
forceinline constexpr bool upx::compile_time::string_gt (const char * a, const char * b) constexpr noexcept
Definition at line 399 of file cxxlib.h.
{
    return string_lt(b, a);
}
References b, and string_lt().
string_le()
forceinline constexpr bool upx::compile_time::string_le (const char * a, const char * b) constexpr noexcept
Definition at line 402 of file cxxlib.h.
{
    return !string_lt(b, a);
}
References b, and string_lt().
string_len()
constexpr std::size_t upx::compile_time::string_len (const char * a) constexpr noexcept
Definition at line 387 of file cxxlib.h.
{
    return *a == '\0' ? 0 : 1 + string_len(a + 1);
}
References string_len().
Referenced by string_len(), and upx_compiler_sanity_check().
string_lt()
constexpr bool upx::compile_time::string_lt (const char * a, const char * b) constexpr noexcept
Definition at line 393 of file cxxlib.h.
{
    return (uchar) *a < (uchar) *b || (*a != '\0' && *a == *b && string_lt(a + 1, b + 1));
}
References b, and string_lt().
Referenced by string_ge(), string_gt(), string_le(), and string_lt().
string_ne()
forceinline constexpr bool upx::compile_time::string_ne (const char * a, const char * b) constexpr noexcept
Definition at line 396 of file cxxlib.h.
{
    return !string_eq(a, b);
}
References b, and string_eq().