My Project: anonymous_namespace{work.cpp} Namespace Reference
anonymous_namespace{work.cpp} Namespace Reference
file util
Classes
struct XStat
Enumerations
enum OpenMode { RO_MUST_EXIST , WO_MUST_EXIST_TRUNCATE , WO_MUST_CREATE , WO_CREATE_OR_TRUNCATE }
Functions
static constexpr int get_open_flags (OpenMode om) noexcept
static void set_fd_timestamp (int fd, const XStat *xst) noexcept
static void copy_file_contents (const char *iname, const char *oname, OpenMode om, const XStat *oname_timestamp) may_throw
static void copy_file_attributes (const XStat *xst, const char *oname, bool preserve_mode, bool preserve_ownership, bool preserve_timestamp) noexcept
Detailed Description
file util
Enumeration Type Documentation
OpenMode
enum anonymous_namespace{work.cpp}::OpenMode
Enumerator
RO_MUST_EXIST
WO_MUST_EXIST_TRUNCATE
WO_MUST_CREATE
WO_CREATE_OR_TRUNCATE
Definition at line 86 of file work.cpp.
{ RO_MUST_EXIST, WO_MUST_EXIST_TRUNCATE, WO_MUST_CREATE, WO_CREATE_OR_TRUNCATE };
Function Documentation
copy_file_attributes()
static void anonymous_namespace{work.cpp}::copy_file_attributes (const XStat * xst, const char * oname, bool preserve_mode, bool preserve_ownership, bool preserve_timestamp) static noexcept
Definition at line 145 of file work.cpp.
{
    const struct stat *const st = &xst->st;
    // copy time stamp
    if (preserve_timestamp) {
#if USE_UTIMENSAT && defined(AT_FDCWD)
        struct timespec times[2] = {};
#if HAVE_STRUCT_STAT_ST_MTIMESPEC_TV_NSEC
        // macOS
        times[0] = st->st_atimespec;
        times[1] = st->st_mtimespec;
#else
        // POSIX.1-2008
        times[0] = st->st_atim;
        times[1] = st->st_mtim;
#endif
        int r = utimensat(AT_FDCWD, oname, &times[0], 0);
        IGNORE_ERROR(r);
#elif USE_UTIME
        struct utimbuf u = {};
        u.actime = st->st_atime;
        u.modtime = st->st_mtime;
        int r = utime(oname, &u);
        IGNORE_ERROR(r);
#endif
    }
#if HAVE_CHOWN
    // copy the group ownership
    if (preserve_ownership) {
        int r = chown(oname, -1, st->st_gid);
        IGNORE_ERROR(r);
    }
#endif
#if HAVE_CHMOD
    // copy permissions
    if (preserve_mode) {
        int r = chmod(oname, st->st_mode);
        IGNORE_ERROR(r);
    }
#endif
#if HAVE_CHOWN
    // copy the user ownership
    if (preserve_ownership) {
        int r = chown(oname, st->st_uid, -1);
        IGNORE_ERROR(r);
    }
#endif
    // maybe unused
    UNUSED(xst);
    UNUSED(st);
    UNUSED(oname);
    UNUSED(preserve_mode);
    UNUSED(preserve_ownership);
    UNUSED(preserve_timestamp);
}
References IGNORE_ERROR, and UNUSED.
Referenced by do_one_file().
copy_file_contents()
static void anonymous_namespace{work.cpp}::copy_file_contents (const char * iname, const char * oname, OpenMode om, const XStat * oname_timestamp) static
Definition at line 121 of file work.cpp.
{
    InputFile fi;
    fi.sopen(iname, get_open_flags(RO_MUST_EXIST), SH_DENYWR);
    fi.seek(0, SEEK_SET);
    int flags = get_open_flags(om);
    int shmode = SH_DENYWR;
    int omode = 0600; // affected by umask; ignored unless O_CREAT
    OutputFile fo;
    fo.sopen(oname, flags, shmode, omode);
    fo.seek(0, SEEK_SET);
    MemBuffer buf(256 * 1024 * 1024);
    for (;;) {
        size_t bytes = fi.read(buf, buf.getSize());
        if (bytes == 0)
            break;
        fo.write(buf, bytes);
    }
    if (oname_timestamp != nullptr)
        set_fd_timestamp(fo.getFd(), oname_timestamp);
    fi.closex();
    fo.closex();
}
References buf, FileBase::closex(), get_open_flags(), FileBase::getFd(), InputFile::read(), RO_MUST_EXIST, InputFile::seek(), OutputFile::seek(), SEEK_SET, set_fd_timestamp(), SH_DENYWR, InputFile::sopen(), OutputFile::sopen(), and OutputFile::write().
Referenced by do_one_file().
get_open_flags()
static constexpr int anonymous_namespace{work.cpp}::get_open_flags (OpenMode om) static constexpr noexcept
Definition at line 88 of file work.cpp.
{
    constexpr int wo_flags = O_WRONLY | O_BINARY;
    if (om == WO_MUST_EXIST_TRUNCATE)
        return wo_flags | O_TRUNC; // will cause an error if file does not exist
    if (om == WO_MUST_CREATE)
        return wo_flags | O_CREAT | O_EXCL; // will cause an error if file already exists
    if (om == WO_CREATE_OR_TRUNCATE)
        return wo_flags | O_CREAT | O_TRUNC; // create if not exists, otherwise truncate
    // RO_MUST_EXIST
    return O_RDONLY | O_BINARY; // will cause an error if file does not exist
}
References O_BINARY, O_CREAT, O_EXCL, O_RDONLY, O_WRONLY, WO_CREATE_OR_TRUNCATE, WO_MUST_CREATE, and WO_MUST_EXIST_TRUNCATE.
Referenced by copy_file_contents(), and do_one_file().
set_fd_timestamp()
static void anonymous_namespace{work.cpp}::set_fd_timestamp (int fd, const XStat * xst) static noexcept
Definition at line 101 of file work.cpp.
{
#if USE_SETFILETIME
    BOOL r = SetFileTime((HANDLE) _get_osfhandle(fd), nullptr, &xst->ft_atime, &xst->ft_mtime);
    IGNORE_ERROR(r);
#elif USE_FTIME
    struct ftime ft_ftime = xst->ft_ftime; // djgpp2 libc bug/feature: not const, so use a copy
    int r = setftime(fd, &ft_ftime);
    IGNORE_ERROR(r);
#elif USE__FUTIME
    struct _utimbuf u = {};
    u.actime = xst->st.st_atime;
    u.modtime = xst->st.st_mtime;
    int r = _futime(fd, &u);
    IGNORE_ERROR(r);
#endif
    // maybe unused
    UNUSED(fd);
    UNUSED(xst);
}
References IGNORE_ERROR, and UNUSED.
Referenced by copy_file_contents(), and do_one_file().