My Project: upx Namespace Reference
upx Namespace Reference
some global overloads
Namespaces
namespace compile_time
compile_time
Classes
struct ArrayDeleter
struct is_bounded_array
<type_traits>
struct is_bounded_array< T[N]>
struct is_same_all
struct is_same_any
struct MallocDeleter
class noncopyable
struct ObjectDeleter
struct OptVar
OptVar and oassign.
struct remove_cvref
struct TriBool
TriBool - tri-state bool an enum with an underlying type and 3 values IsThirdTrue determines if Third is false or true.
struct type_identity
struct UnsignedSizeOf
util
Typedefs
template<class T >
using remove_cvref_t = typename remove_cvref< T >::type
template<class T >
using type_identity_t = typename type_identity< T >::type
typedef TriBool tribool
template<class T >
using OwningPointer = T *
OwningPointer(T) simple pointer type alias to explicitly mark ownership of objects; purely cosmetic to improve source code readability, no real functionality.
Functions
REQUIRE_UINT32 bele_constexpr T align_down (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_down (const BE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_down (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_down (const LE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_up (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_up (const LE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_up (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T align_up (const BE32 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const T &a, const BE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const BE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const BE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T min (const T &a, const BE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T min (const BE64 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const T &a, const LE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const LE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T min (const LE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T min (const T &a, const LE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T min (const LE64 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const T &a, const BE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const BE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const T &a, const BE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const BE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T max (const T &a, const BE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T max (const BE64 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const T &a, const LE16 &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const LE16 &a, const T &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const T &a, const LE32 &b) noexcept
REQUIRE_UINT32 bele_constexpr T max (const LE32 &a, const T &b) noexcept
REQUIRE_UINT64 bele_constexpr T max (const T &a, const LE64 &b) noexcept
REQUIRE_UINT64 bele_constexpr T max (const LE64 &a, const T &b) noexcept
template<class T >
forceinline constexpr bool has_single_bit (T x) noexcept
<bit> C++20
template<class T >
constexpr T align_down (const T &x, const T &alignment) noexcept
<algorithm>
template<class T >
constexpr T align_down_gap (const T &x, const T &alignment) noexcept
template<class T >
constexpr T align_up (const T &x, const T &alignment) noexcept
template<class T >
constexpr T align_up_gap (const T &x, const T &alignment) noexcept
template<class T >
forceinline constexpr T min (const T &a, const T &b) noexcept
template<class T >
forceinline constexpr T max (const T &a, const T &b) noexcept
template<class T , class = std::enable_if_t<is_uminmax_type<T>, T>>
forceinline constexpr T umin (const T &a, const T &b) noexcept
template<class T , class = std::enable_if_t<is_uminmax_type<T>, T>>
forceinline constexpr T umax (const T &a, const T &b) noexcept
template<class T >
forceinline constexpr T wrapping_add (const T &a, const T &b) noexcept
template<class T >
forceinline constexpr T wrapping_sub (const T &a, const T &b) noexcept
template<class Result , class From >
forceinline constexpr Result ptr_static_cast (From *ptr) noexcept
template<class Result , class From >
forceinline constexpr Result ptr_static_cast (const From *ptr) noexcept
template<class T >
forceinline T atomic_exchange (T *ptr, T new_value) noexcept
template<class T , T a, T b, T c>
void oassign (OptVar< T, a, b, c > &self, const OptVar< T, a, b, c > &other) noexcept
template<class T , T a, T b, T c>
void oassign (T &v, const OptVar< T, a, b, c > &other) noexcept
template<class T >
void owner_delete (OwningPointer(T)(&object)) noexcept
template<class T >
void owner_free (OwningPointer(T)(&object)) noexcept
template<class T >
void owner_delete (T(&array)[]) noexcept DELETED_FUNCTION
template<class T >
void owner_free (T(&array)[]) noexcept DELETED_FUNCTION
template<class T , std::size_t N>
void owner_delete (T(&array)[N]) noexcept DELETED_FUNCTION
template<class T , std::size_t N>
void owner_free (T(&array)[N]) noexcept DELETED_FUNCTION
Variables
template<class T >
constexpr bool is_bounded_array_v = is_bounded_array<T>::value
template<class T , class... Ts>
constexpr bool is_same_all_v = is_same_all<T, Ts...>::value
template<class T , class... Ts>
constexpr bool is_same_any_v = is_same_any<T, Ts...>::value
template<class T >
constexpr bool is_uminmax_type = std::is_integral_v<T> && std::is_unsigned_v<T>
Detailed Description
some global overloads
Typedef Documentation
OwningPointer
template<class T > using upx::OwningPointer = typedef T *
OwningPointer(T) simple pointer type alias to explicitly mark ownership of objects; purely cosmetic to improve source code readability, no real functionality.
Definition at line 730 of file cxxlib.h.
remove_cvref_t
template<class T > using upx::remove_cvref_t = typedef typename remove_cvref<T>::type
Definition at line 183 of file cxxlib.h.
tribool
typedef TriBool upx::tribool
Definition at line 657 of file cxxlib.h.
type_identity_t
template<class T > using upx::type_identity_t = typedef typename type_identity<T>::type
Definition at line 191 of file cxxlib.h.
Function Documentation
align_down() [1/5]
REQUIRE_UINT32 bele_constexpr T upx::align_down (const BE32 & a, const T & b) inline noexcept
Definition at line 969 of file bele.h.
{
    return align_down(T(a), b);
}
References align_down(), and b.
align_down() [2/5]
REQUIRE_UINT32 bele_constexpr T upx::align_down (const LE32 & a, const T & b) inline noexcept
Definition at line 977 of file bele.h.
{
    return align_down(T(a), b);
}
References align_down(), and b.
align_down() [3/5]
REQUIRE_UINT32 bele_constexpr T upx::align_down (const T & a, const BE32 & b) inline noexcept
Definition at line 965 of file bele.h.
{
    return align_down(a, T(b));
}
References align_down(), and b.
Referenced by align_down(), anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check(), and anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
align_down() [4/5]
REQUIRE_UINT32 bele_constexpr T upx::align_down (const T & a, const LE32 & b) inline noexcept
Definition at line 973 of file bele.h.
{
    return align_down(a, T(b));
}
References align_down(), and b.
align_down() [5/5]
template<class T > constexpr T upx::align_down (const T & x, const T & alignment) inline constexpr noexcept
<algorithm>
Definition at line 207 of file cxxlib.h.
{
    // assert_noexcept(has_single_bit(alignment)); // (not constexpr)
    T r = {};
    r = x - (x & (alignment - 1));
    return r;
}
align_down_gap()
template<class T > constexpr T upx::align_down_gap (const T & x, const T & alignment) inline constexpr noexcept
Definition at line 214 of file cxxlib.h.
{
    // assert_noexcept(has_single_bit(alignment)); // (not constexpr)
    T r = {};
    r = x & (alignment - 1);
    return r;
}
Referenced by anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
align_up() [1/5]
REQUIRE_UINT32 bele_constexpr T upx::align_up (const BE32 & a, const T & b) inline noexcept
Definition at line 988 of file bele.h.
{ return align_up(T(a), b); }
References align_up(), and b.
align_up() [2/5]
REQUIRE_UINT32 bele_constexpr T upx::align_up (const LE32 & a, const T & b) inline noexcept
Definition at line 984 of file bele.h.
{ return align_up(T(a), b); }
References align_up(), and b.
align_up() [3/5]
REQUIRE_UINT32 bele_constexpr T upx::align_up (const T & a, const BE32 & b) inline noexcept
Definition at line 986 of file bele.h.
{ return align_up(a, T(b)); }
References align_up(), and b.
align_up() [4/5]
REQUIRE_UINT32 bele_constexpr T upx::align_up (const T & a, const LE32 & b) inline noexcept
Definition at line 982 of file bele.h.
{ return align_up(a, T(b)); }
References align_up(), and b.
Referenced by align_up(), anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check(), and anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
align_up() [5/5]
template<class T > constexpr T upx::align_up (const T & x, const T & alignment) inline constexpr noexcept
Definition at line 221 of file cxxlib.h.
{
    // assert_noexcept(has_single_bit(alignment)); // (not constexpr)
    T r = {};
    constexpr T zero = {};
    r = x + ((zero - x) & (alignment - 1));
    return r;
}
align_up_gap()
template<class T > constexpr T upx::align_up_gap (const T & x, const T & alignment) inline constexpr noexcept
Definition at line 229 of file cxxlib.h.
{
    // assert_noexcept(has_single_bit(alignment)); // (not constexpr)
    T r = {};
    constexpr T zero = {};
    r = (zero - x) & (alignment - 1);
    return r;
}
Referenced by anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check(), and anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
atomic_exchange()
template<class T > forceinline T upx::atomic_exchange (T * ptr, T new_value) noexcept
Definition at line 317 of file cxxlib.h.
{
#if 1
    static_assert(sizeof(T) == sizeof(void *)); // UPX convention: restrict to pointer-size for now
#endif
    static_assert(std::is_standard_layout_v<T>);
    static_assert(std::is_trivially_copyable_v<T>);
#if !(WITH_THREADS)
    T old_value = *ptr;
    *ptr = new_value;
    return old_value;
#else
    static_assert(sizeof(T) <= sizeof(void *)); // UPX convention: restrict to fundamental types
    static_assert(alignof(T) == sizeof(T));     // UPX convention: require proper alignment
#if __has_builtin(__atomic_exchange_n) && defined(__ATOMIC_SEQ_CST)
    return __atomic_exchange_n(ptr, new_value, __ATOMIC_SEQ_CST);
#elif __has_builtin(__sync_swap)
    return __sync_swap(ptr, new_value);
#else
    return std::atomic_exchange(ptr_std_atomic_cast(ptr), new_value);
#endif
#endif
}
References ptr.
Referenced by upx::ObjectDeleter< T >::delete_items(), upx::ArrayDeleter< T >::delete_items(), upx::MallocDeleter< T >::delete_items(), free_array(), and TEST_CASE().
has_single_bit()
template<class T > forceinline constexpr bool upx::has_single_bit (T x) constexpr noexcept
<bit> C++20
Definition at line 198 of file cxxlib.h.
{
    return !(x == 0) && (x & (x - 1)) == 0;
}
Referenced by PeFile::checkHeaderValues(), PeFile::pack0(), ptr_is_aligned(), and anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
max() [1/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const BE16 & a, const T & b) inline noexcept
Definition at line 1018 of file bele.h.
{ return max(T(a), b); }
References b, and max().
max() [2/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const BE32 & a, const T & b) inline noexcept
Definition at line 1022 of file bele.h.
{ return max(T(a), b); }
References b, and max().
max() [3/13]
REQUIRE_UINT64 bele_constexpr T upx::max (const BE64 & a, const T & b) inline noexcept
Definition at line 1026 of file bele.h.
{ return max(T(a), b); }
References b, and max().
max() [4/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const LE16 & a, const T & b) inline noexcept
Definition at line 1030 of file bele.h.
{ return max(T(a), b); }
References b, and max().
max() [5/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const LE32 & a, const T & b) inline noexcept
Definition at line 1034 of file bele.h.
{ return max(T(a), b); }
References b, and max().
max() [6/13]
REQUIRE_UINT64 bele_constexpr T upx::max (const LE64 & a, const T & b) inline noexcept
Definition at line 1038 of file bele.h.
{ return max(T(a), b); }
References b, and max().
max() [7/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const T & a, const BE16 & b) inline noexcept
Definition at line 1016 of file bele.h.
{ return max(a, T(b)); }
References b, and max().
Referenced by anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check_core(), max(), and anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
max() [8/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const T & a, const BE32 & b) inline noexcept
Definition at line 1020 of file bele.h.
{ return max(a, T(b)); }
References b, and max().
max() [9/13]
REQUIRE_UINT64 bele_constexpr T upx::max (const T & a, const BE64 & b) inline noexcept
Definition at line 1024 of file bele.h.
{ return max(a, T(b)); }
References b, and max().
max() [10/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const T & a, const LE16 & b) inline noexcept
Definition at line 1028 of file bele.h.
{ return max(a, T(b)); }
References b, and max().
max() [11/13]
REQUIRE_UINT32 bele_constexpr T upx::max (const T & a, const LE32 & b) inline noexcept
Definition at line 1032 of file bele.h.
{ return max(a, T(b)); }
References b, and max().
max() [12/13]
REQUIRE_UINT64 bele_constexpr T upx::max (const T & a, const LE64 & b) inline noexcept
Definition at line 1036 of file bele.h.
{ return max(a, T(b)); }
References b, and max().
max() [13/13]
template<class T > forceinline constexpr T upx::max (const T & a, const T & b) constexpr noexcept
Definition at line 242 of file cxxlib.h.
{
    return a < b ? b : a;
}
References b.
min() [1/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const BE16 & a, const T & b) inline noexcept
Definition at line 993 of file bele.h.
{ return min(T(a), b); }
References b, and min().
min() [2/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const BE32 & a, const T & b) inline noexcept
Definition at line 997 of file bele.h.
{ return min(T(a), b); }
References b, and min().
min() [3/13]
REQUIRE_UINT64 bele_constexpr T upx::min (const BE64 & a, const T & b) inline noexcept
Definition at line 1001 of file bele.h.
{ return min(T(a), b); }
References b, and min().
min() [4/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const LE16 & a, const T & b) inline noexcept
Definition at line 1005 of file bele.h.
{ return min(T(a), b); }
References b, and min().
min() [5/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const LE32 & a, const T & b) inline noexcept
Definition at line 1009 of file bele.h.
{ return min(T(a), b); }
References b, and min().
min() [6/13]
REQUIRE_UINT64 bele_constexpr T upx::min (const LE64 & a, const T & b) inline noexcept
Definition at line 1013 of file bele.h.
{ return min(T(a), b); }
References b, and min().
min() [7/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const T & a, const BE16 & b) inline noexcept
Definition at line 991 of file bele.h.
{ return min(a, T(b)); }
References b, and min().
Referenced by anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check_core(), min(), and anonymous_namespace{dt_check.cpp}::TestBELE< T >::test().
min() [8/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const T & a, const BE32 & b) inline noexcept
Definition at line 995 of file bele.h.
{ return min(a, T(b)); }
References b, and min().
min() [9/13]
REQUIRE_UINT64 bele_constexpr T upx::min (const T & a, const BE64 & b) inline noexcept
Definition at line 999 of file bele.h.
{ return min(a, T(b)); }
References b, and min().
min() [10/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const T & a, const LE16 & b) inline noexcept
Definition at line 1003 of file bele.h.
{ return min(a, T(b)); }
References b, and min().
min() [11/13]
REQUIRE_UINT32 bele_constexpr T upx::min (const T & a, const LE32 & b) inline noexcept
Definition at line 1007 of file bele.h.
{ return min(a, T(b)); }
References b, and min().
min() [12/13]
REQUIRE_UINT64 bele_constexpr T upx::min (const T & a, const LE64 & b) inline noexcept
Definition at line 1011 of file bele.h.
{ return min(a, T(b)); }
References b, and min().
min() [13/13]
template<class T > forceinline constexpr T upx::min (const T & a, const T & b) constexpr noexcept
Definition at line 238 of file cxxlib.h.
{
    return b < a ? b : a;
}
References b.
oassign() [1/2]
template<class T , T a, T b, T c> void upx::oassign (OptVar< T, a, b, c > & self, const OptVar< T, a, b, c > & other) inline noexcept
Definition at line 703 of file cxxlib.h.
{
    if (other.is_set) {
        self.value = other.value;
        self.is_set = true;
    }
}
Referenced by Packer::compress(), prepare_result(), and upx_zlib_compress().
oassign() [2/2]
template<class T , T a, T b, T c> void upx::oassign (T & v, const OptVar< T, a, b, c > & other) inline noexcept
Definition at line 710 of file cxxlib.h.
{
    if (other.is_set)
        v = other.value;
}
owner_delete() [1/3]
template<class T > void upx::owner_delete (OwningPointer(T)& object) inline noexcept
Definition at line 766 of file cxxlib.h.
{
    static_assert(std::is_class_v<T>); // UPX convention
    static_assert(std::is_nothrow_destructible_v<T>);
    if (object != nullptr) {
        delete (T *) object; // single object delete
        object = nullptr;
    }
    assert_noexcept((T *) object == nullptr);
    assert_noexcept(object == nullptr);
}
References assert_noexcept.
Referenced by Packer::initLoader(), Packer::~Packer(), PackMaster::~PackMaster(), and UiPacker::~UiPacker().
owner_delete() [2/3]
template<class T > void upx::owner_delete (T(&) array[]) inline noexcept
owner_delete() [3/3]
template<class T , std::size_t N> void upx::owner_delete (T(&) array[N]) inline noexcept
owner_free() [1/3]
template<class T > void upx::owner_free (OwningPointer(T)& object) inline noexcept
Definition at line 778 of file cxxlib.h.
{
    static_assert(!std::is_class_v<T>); // UPX convention
    if (object != nullptr) {
        ::free((T *) object); // free memory from malloc()
        object = nullptr;
    }
    assert_noexcept((T *) object == nullptr);
    assert_noexcept(object == nullptr);
}
References assert_noexcept.
Referenced by Throwable::~Throwable().
owner_free() [2/3]
template<class T > void upx::owner_free (T(&) array[]) inline noexcept
owner_free() [3/3]
template<class T , std::size_t N> void upx::owner_free (T(&) array[N]) inline noexcept
ptr_static_cast() [1/2]
template<class Result , class From > forceinline constexpr Result upx::ptr_static_cast (const From * ptr) constexpr noexcept
Definition at line 293 of file cxxlib.h.
{
    static_assert(std::is_pointer_v<Result>);
    static_assert(std::is_const_v<std::remove_pointer_t<Result> >); // required
    // don't cast through "const void *" if type is convertible
    typedef std::conditional_t<std::is_convertible_v<decltype(ptr), Result>, Result, const void *>
        VoidPtr;
    // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
    return static_cast<Result>(static_cast<VoidPtr>(ptr));
}
References ptr.
ptr_static_cast() [2/2]
template<class Result , class From > forceinline constexpr Result upx::ptr_static_cast (From * ptr) constexpr noexcept
Definition at line 284 of file cxxlib.h.
{
    static_assert(std::is_pointer_v<Result>);
    // don't cast through "void *" if type is convertible
    typedef std::conditional_t<std::is_convertible_v<decltype(ptr), Result>, Result, void *>
        VoidPtr;
    // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
    return static_cast<Result>(static_cast<VoidPtr>(ptr));
}
References ptr.
Referenced by TEST_CASE().
umax()
template<class T , class = std::enable_if_t<is_uminmax_type<T>, T>> forceinline constexpr T upx::umax (const T & a, const T & b) constexpr noexcept
Definition at line 254 of file cxxlib.h.
{
    return a < b ? b : a;
}
References b.
Referenced by PackLinuxElf32::buildLinuxLoader(), PackLinuxI386::buildLinuxLoader(), PackLinuxI386sh::buildLoader(), MemBuffer::getSizeForCompression(), PeFile::readSections(), and PackUnix::unpack().
umin()
template<class T , class = std::enable_if_t<is_uminmax_type<T>, T>> forceinline constexpr T upx::umin (const T & a, const T & b) constexpr noexcept
Definition at line 250 of file cxxlib.h.
{
    return b < a ? b : a;
}
References b, and umin().
Referenced by PackMachBase< TMachClass >::canPack(), PackMachBase< TMachClass >::canUnpack(), F(), umin(), and PackMachBase< TMachClass >::unpack().
wrapping_add()
template<class T > forceinline constexpr T upx::wrapping_add (const T & a, const T & b) constexpr noexcept
Definition at line 259 of file cxxlib.h.
{
    static_assert(std::is_integral_v<T>);
    typedef std::make_unsigned_t<T> U;
    return T(U(a) + U(b));
}
References b, and U.
wrapping_sub()
template<class T > forceinline constexpr T upx::wrapping_sub (const T & a, const T & b) constexpr noexcept
Definition at line 266 of file cxxlib.h.
{
    static_assert(std::is_integral_v<T>);
    typedef std::make_unsigned_t<T> U;
    return T(U(a) - U(b));
}
References b, and U.
Variable Documentation
is_bounded_array_v
template<class T > constexpr bool upx::is_bounded_array_v = is_bounded_array<T>::value inline constexpr
Definition at line 165 of file cxxlib.h.
is_same_all_v
template<class T , class... Ts> constexpr bool upx::is_same_all_v = is_same_all<T, Ts...>::value inline constexpr
Definition at line 171 of file cxxlib.h.
is_same_any_v
template<class T , class... Ts> constexpr bool upx::is_same_any_v = is_same_any<T, Ts...>::value inline constexpr
Definition at line 175 of file cxxlib.h.
is_uminmax_type
template<class T > constexpr bool upx::is_uminmax_type = std::is_integral_v<T> && std::is_unsigned_v<T> inline constexpr
Definition at line 247 of file cxxlib.h.