My Project: N_Mach Namespace Reference
N_Mach Namespace Reference
Mach Mach Object executable; all structures are target-endian 'otool' is the Mach analog of 'readelf' (convert executable file to ASCII).
Classes
struct MachClass_32
struct MachClass_64
struct MachITypes
Functions
template<class TMachITypes >
packed_struct (Mach_header)
template<class TMachITypes >
packed_struct (Mach_header64)
template<class TMachITypes >
packed_struct (Mach_command)
template<class TMachITypes >
packed_struct (Mach_segment_command)
template<class TMachITypes >
packed_struct (Mach_section_command)
template<class TMachITypes >
packed_struct (Mach_section_command_64)
template<class TMachITypes >
packed_struct (Mach_symtab_command)
template<class TMachITypes >
packed_struct (Mach_dysymtab_command)
template<class TMachITypes >
packed_struct (Mach_segsplit_info_command)
template<class TMachITypes >
packed_struct (Mach_routines_command)
template<class TMachITypes >
packed_struct (Mach_routines_command_64)
template<class TMachITypes >
packed_struct (Mach_twolevel_hints_command)
template<class TMachITypes >
packed_struct (Mach_linkedit_data_command)
template<class TMachITypes >
packed_struct (Mach_uuid_command)
template<class TMachITypes , class TMachThreadState >
packed_struct (Mach_thread_command)
template<class TMachITypes >
packed_struct (Mach_main_command)
template<class TMachITypes >
packed_struct (Mach_source_version_command)
template<class TMachITypes >
packed_struct (Mach_version_min_command)
template<class TMachITypes >
packed_struct (Mach_dyld_info_only_command)
template<class TMachITypes >
packed_struct (Mach_load_dylinker_command)
template<class TMachITypes >
packed_struct (Mach_dylib)
template<class TMachITypes >
packed_struct (Mach_load_dylib_command)
Detailed Description
Mach Mach Object executable; all structures are target-endian 'otool' is the Mach analog of 'readelf' (convert executable file to ASCII).
Function Documentation
packed_struct() [1/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_command)
Definition at line 102 of file p_mach.h.
                            { // generic prefix
    typedef typename TMachITypes::Word Word;
    Word cmd;
    Word cmdsize;
    Word data[2];  // because cmdsize >= 16
#define WANT_MACH_SEGMENT_ENUM 1
#include "p_mach_enum.h"
};
References data().
packed_struct() [2/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_dyld_info_only_command)
Definition at line 349 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;  // LC_DYLD_INFO_ONLY
    Word cmdsize;  // 48
    Word rebase_off;
    Word rebase_size;
    Word bind_off;
    Word bind_size;
    Word weak_bind_off;
    Word weak_bind_size;
    Word lazy_bind_off;
    Word lazy_bind_size;
    Word export_off;
    Word export_size;
};
packed_struct() [3/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_dylib)
Definition at line 376 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word name;         /* library's path name */
    Word timestamp;         /* library's build time stamp */
    Word current_version;       /* library's current version number */
    Word compatibility_version; /* library's compatibility vers number*/
};
packed_struct() [4/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_dysymtab_command)
Definition at line 193 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Off  Off;
    typedef typename TMachITypes::Word Off32;
    Word cmd;           /* LC_DYSYMTAB */
    Word cmdsize;       /* sizeof(struct Mach_dysymtab_command) */
    Word ilocalsym;     /* index to local symbols */
    Word nlocalsym;     /* number of local symbols */
    Word iextdefsym;    /* index to externally defined symbols */
    Word nextdefsym;    /* number of externally defined symbols */
    Word iundefsym;     /* index to undefined symbols */
    Word nundefsym;     /* number of undefined symbols */
    Off32 tocoff;       /* file offset to table of contents */
    Word ntoc;          /* number of entries in table of contents */
    Off32 modtaboff;    /* file offset to module table */
    Word nmodtab;       /* number of module table entries */
    Off32 extrefsymoff; /* offset to referenced symbol table */
    Word nextrefsymoff; /* number of referenced symbol table entries */
    Off32 indirectsymoff; /* file offset to the indirect symbol table */
    Word nindirectsyms; /* number of indirect symbol table entries */
    Off32 extreloff;    /* offset to external relocation entries */
    Word nextrel;       /* number of external relocation entries */
    Off32 locreloff;      /* offset to local relocation entries */
    Word nlocrel;       /* number of local relocation entries */
};
packed_struct() [5/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_header)
Definition at line 70 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word magic;
    Word cputype;
    Word cpusubtype;
    Word filetype;
    Word ncmds;
    Word sizeofcmds;
    Word flags;
#define WANT_MACH_HEADER_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [6/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_header64)
Definition at line 85 of file p_mach.h.
{
    // only difference is padding to 0 mod 8
    typedef typename TMachITypes::Word Word;
    Word magic;
    Word cputype;
    Word cpusubtype;
    Word filetype;
    Word ncmds;
    Word sizeofcmds;
    Word flags;
    Word reserved;  // pad to 0 mod 8
#define WANT_MACH_HEADER_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [7/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_linkedit_data_command)
Definition at line 284 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;  // LC_CODE_SIGNATURE, LC_SEGMENT_SPLIT_INFO,
               // LC_FUNCTION_STARTS, LC_DATA_IN_CODE,
               // LC_DYLIB_CODE_SIGN_DRS, LC_LINKER_OPTIMIZATION_HINT
    Word cmdsize;
    Word dataoff;  // file offset of data in __LINKEDIT segment
    Word datasize;  // file size of data in __LINKEDIT segment
};
packed_struct() [8/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_load_dylib_command)
Definition at line 386 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;
    Word cmdsize;
    Mach_dylib<TMachITypes> dylib;
};
packed_struct() [9/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_load_dylinker_command)
Definition at line 367 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;
    Word cmdsize;
    Word name;
};
packed_struct() [10/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_main_command)
Definition at line 318 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Xword Xword;
    Word cmd;  // LC_MAIN;  MH_EXECUTE only
    Word cmdsize;  // 24
    Xword entryoff;  // file offset of main() [expected in __TEXT]
    Xword stacksize;  // non-default initial stack size
};
packed_struct() [11/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_routines_command)
Definition at line 232 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Addr Addr;
    Word cmd;
    Word cmdsize;
    Addr init_address;
    Word init_module;
    Word reserved1;
    Word reserved2;
    Word reserved3;
    Word reserved4;
    Word reserved5;
    Word reserved6;
#define WANT_MACH_SEGMENT_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [12/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_routines_command_64)
Definition at line 251 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Addr Addr;
    typedef typename TMachITypes::Xword Xword;
    Word cmd;
    Word cmdsize;
    Addr init_address;
    Xword init_module;
    Xword reserved1;
    Xword reserved2;
    Xword reserved3;
    Xword reserved4;
    Xword reserved5;
    Xword reserved6;
#define WANT_MACH_SEGMENT_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [13/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_section_command)
Definition at line 134 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Addr Addr;
    typedef typename TMachITypes::Off  Off;
    char sectname[16];
    char segname[16];
    Addr addr;   /* memory address */
    Addr size;   /* size in bytes */
    Word offset; /* file offset */
    Word align;  /* power of 2 */
    Word reloff; /* file offset of relocation entries */
    Word nreloc; /* number of relocation entries */
    Word flags;  /* section type and attributes */
    Word reserved1;  /* for offset or index */
    Word reserved2;  /* for count or sizeof */
#define WANT_MACH_SECTION_ENUM 1
#include "p_mach_enum.h"
};
References size().
packed_struct() [14/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_section_command_64)
Definition at line 155 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Addr Addr;
    typedef typename TMachITypes::Off  Off;
    typedef typename TMachITypes::Word Off32;
    typedef typename TMachITypes::Xword Xword;
    char sectname[16];
    char segname[16];
    Addr addr;   /* memory address */
    Addr size;   /* size in bytes */
    Off32 offset; /* file offset */
    Word align;  /* power of 2 */
    Word reloff; /* file offset of relocation entries */
    Word nreloc; /* number of relocation entries */
    Word flags;  /* section type and attributes */
    Word reserved1;  /* for offset or index */
    Word reserved2;  /* for count or sizeof */
    Word reserved3;  /* NOT IN 32-bit VERSION!! */
#define WANT_MACH_SECTION_ENUM 1
#include "p_mach_enum.h"
};
References size().
packed_struct() [15/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_segment_command)
Definition at line 113 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Addr Addr;
    typedef typename TMachITypes::Off  Off;
    Word cmd;
    Word cmdsize;
    char segname[16];
    Addr vmaddr;
    Addr vmsize;
    Off  fileoff;
    Off  filesize;
    Word maxprot;
    Word initprot;
    Word nsects;
    Word flags;
#define WANT_MACH_SEGMENT_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [16/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_segsplit_info_command)
Definition at line 221 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Off  Off;
    Word cmd;           /* LC_SEGMENT_SPLIT_INFO */
    Word cmdsize;       /* sizeof(struct Mach_segsplit_info_command) */
    Off dataoff;
    Word datasize;
};
packed_struct() [17/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_source_version_command)
Definition at line 329 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;  // LC_SOURCE_VERSION
    Word cmdsize;  // 16
    Word version;
    Word __pad;  // to 0 mod 8
};
packed_struct() [18/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_symtab_command)
Definition at line 179 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Off  Off;
    typedef typename TMachITypes::Word Off32;
    Word cmd;      /* LC_SYMTAB */
    Word cmdsize;  /* sizeof(struct Mach_symtab_command) */
    Off32 symoff;  /* symbol table offset */
    Word nsyms;    /* number of symbol table entries */
    Off32 stroff;  /* string table offset */
    Word strsize;  /* string table size in bytes */
};
packed_struct() [19/22]
template<class TMachITypes , class TMachThreadState > N_Mach::packed_struct (Mach_thread_command)
Definition at line 305 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;            /* LC_THREAD or  LC_UNIXTHREAD */
    Word cmdsize;        /* total size of this command */
    Word flavor;
    Word count;          /* sizeof(following_thread_state)/4 */
    TMachThreadState state;
#define WANT_MACH_THREAD_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [20/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_twolevel_hints_command)
Definition at line 271 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    typedef typename TMachITypes::Off  Off;
    Word cmd;
    Word cmdsize;
    Off offset;   /* offset to the hint table */
    Word nhints;  /* number of hints */
#define WANT_MACH_SEGMENT_ENUM 1
#include "p_mach_enum.h"
};
packed_struct() [21/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_uuid_command)
Definition at line 296 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;  // LC_UUID
    Word cmdsize;  // 24
    unsigned char uuid[16];
};
packed_struct() [22/22]
template<class TMachITypes > N_Mach::packed_struct (Mach_version_min_command)
Definition at line 339 of file p_mach.h.
{
    typedef typename TMachITypes::Word Word;
    Word cmd;  // LC_VERSION_MIN_MACOSX
    Word cmdsize;  // 16
    Word version;  // X.Y.Z ==> xxxx.yy.zz
    Word sdk;  // X.Y.Z ==> xxxx.yy.zz
};