My Project: anonymous_namespace{dt_check.cpp} Namespace Reference
anonymous_namespace{dt_check.cpp} Namespace Reference
compile-time checks
Classes
struct CheckAlignment
struct CheckIntegral
struct CheckSignedness
struct CheckTypePair
struct TestBELE
struct TestDestructor
struct TestFloat
struct TestIntegerWrap
struct TestNoAliasingStruct
Functions
template<class A , class B >
static forceinline bool testNoAliasing (A *a, B *b) noexcept
static noinline void throwSomeValue (int x) may_throw
static noinline void check_exceptions_2 (void(*func)(int), int *x) may_throw
static noinline void check_basic_cxx_exception_handling (void(*func)(int)) noexcept
static noinline float i64_f32_add_div (upx_int64_t a, upx_int64_t b)
static noinline float u64_f32_add_div (upx_uint64_t a, upx_uint64_t b)
static noinline float i64_f32_sub_div (upx_int64_t a, upx_int64_t b)
static noinline float u64_f32_sub_div (upx_uint64_t a, upx_uint64_t b)
static noinline double i64_f64_add_div (upx_int64_t a, upx_int64_t b)
static noinline double u64_f64_add_div (upx_uint64_t a, upx_uint64_t b)
static noinline double i64_f64_sub_div (upx_int64_t a, upx_int64_t b)
static noinline double u64_f64_sub_div (upx_uint64_t a, upx_uint64_t b)
static noinline void check_basic_floating_point (void) noexcept
Detailed Description
compile-time checks
upx_compiler_sanity_check() assert a sane architecture and compiler
Function Documentation
check_basic_cxx_exception_handling()
static noinline void anonymous_namespace{dt_check.cpp}::check_basic_cxx_exception_handling (void(*)(int) func) static noexcept
Definition at line 760 of file dt_check.cpp.
{
    bool cxx_exception_handling_works = false;
    int x = 1;
    try {
        TestDestructor d(&x, 3);
        check_exceptions_2(func, &x);
    } catch (const size_t &e) {
        if (e == 1 && x == 23)
            cxx_exception_handling_works = true;
    } catch (...) {
    }
    assert_noexcept(cxx_exception_handling_works);
}
References assert_noexcept, and check_exceptions_2().
Referenced by upx_compiler_sanity_check().
check_basic_floating_point()
static noinline void anonymous_namespace{dt_check.cpp}::check_basic_floating_point (void) static noexcept
Definition at line 825 of file dt_check.cpp.
{
    assert_noexcept(i64_f32_add_div(1000000, 1000000) == 2.0f);
    assert_noexcept(u64_f32_add_div(1000000, 1000000) == 2.0f);
    assert_noexcept(i64_f32_sub_div(3000000, 1000000) == 2.0f);
    assert_noexcept(u64_f32_sub_div(3000000, 1000000) == 2.0f);
    assert_noexcept(i64_f64_add_div(1000000, 1000000) == 2.0);
    assert_noexcept(u64_f64_add_div(1000000, 1000000) == 2.0);
    assert_noexcept(i64_f64_sub_div(3000000, 1000000) == 2.0);
    assert_noexcept(u64_f64_sub_div(3000000, 1000000) == 2.0);
    TestFloat<upx_int32_t, float>::check();
    TestFloat<upx_uint32_t, float>::check();
    TestFloat<upx_int64_t, float>::check();
    TestFloat<upx_uint64_t, float>::check();
    TestFloat<upx_int32_t, double>::check();
    TestFloat<upx_uint32_t, double>::check();
    TestFloat<upx_int64_t, double>::check();
    TestFloat<upx_uint64_t, double>::check();
}
References assert_noexcept, anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::check(), i64_f32_add_div(), i64_f32_sub_div(), i64_f64_add_div(), i64_f64_sub_div(), u64_f32_add_div(), u64_f32_sub_div(), u64_f64_add_div(), and u64_f64_sub_div().
Referenced by upx_compiler_sanity_check().
check_exceptions_2()
static noinline void anonymous_namespace{dt_check.cpp}::check_exceptions_2 (void(*)(int) func, int * x) static
Definition at line 755 of file dt_check.cpp.
{
    TestDestructor d(x, *x);
    func(*x);
}
Referenced by check_basic_cxx_exception_handling().
i64_f32_add_div()
static noinline float anonymous_namespace{dt_check.cpp}::i64_f32_add_div (upx_int64_t a, upx_int64_t b) static
Definition at line 778 of file dt_check.cpp.
{ return (a + b) / 1000000.0f; }
References b.
Referenced by check_basic_floating_point().
i64_f32_sub_div()
static noinline float anonymous_namespace{dt_check.cpp}::i64_f32_sub_div (upx_int64_t a, upx_int64_t b) static
Definition at line 782 of file dt_check.cpp.
{ return (a - b) / 1000000.0f; }
References b.
Referenced by check_basic_floating_point().
i64_f64_add_div()
static noinline double anonymous_namespace{dt_check.cpp}::i64_f64_add_div (upx_int64_t a, upx_int64_t b) static
Definition at line 787 of file dt_check.cpp.
{ return (a + b) / 1000000.0; }
References b.
Referenced by check_basic_floating_point().
i64_f64_sub_div()
static noinline double anonymous_namespace{dt_check.cpp}::i64_f64_sub_div (upx_int64_t a, upx_int64_t b) static
Definition at line 791 of file dt_check.cpp.
{ return (a - b) / 1000000.0; }
References b.
Referenced by check_basic_floating_point().
testNoAliasing()
template<class A , class B > static forceinline bool anonymous_namespace{dt_check.cpp}::testNoAliasing (A * a, B * b) static noexcept
Definition at line 727 of file dt_check.cpp.
{
    return TestNoAliasingStruct<A, B>::test(a, b);
}
References b, and anonymous_namespace{dt_check.cpp}::TestNoAliasingStruct< A, B >::test().
Referenced by upx_compiler_sanity_check().
throwSomeValue()
static noinline void anonymous_namespace{dt_check.cpp}::throwSomeValue (int x) static
Definition at line 748 of file dt_check.cpp.
{
    if (x < 0)
        throw int(x);
    else
        throw size_t(x);
}
Referenced by upx_compiler_sanity_check().
u64_f32_add_div()
static noinline float anonymous_namespace{dt_check.cpp}::u64_f32_add_div (upx_uint64_t a, upx_uint64_t b) static
Definition at line 779 of file dt_check.cpp.
{
    return (a + b) / 1000000.0f;
}
References b.
Referenced by check_basic_floating_point().
u64_f32_sub_div()
static noinline float anonymous_namespace{dt_check.cpp}::u64_f32_sub_div (upx_uint64_t a, upx_uint64_t b) static
Definition at line 783 of file dt_check.cpp.
{
    return (a - b) / 1000000.0f;
}
References b.
Referenced by check_basic_floating_point().
u64_f64_add_div()
static noinline double anonymous_namespace{dt_check.cpp}::u64_f64_add_div (upx_uint64_t a, upx_uint64_t b) static
Definition at line 788 of file dt_check.cpp.
{
    return (a + b) / 1000000.0;
}
References b.
Referenced by check_basic_floating_point().
u64_f64_sub_div()
static noinline double anonymous_namespace{dt_check.cpp}::u64_f64_sub_div (upx_uint64_t a, upx_uint64_t b) static
Definition at line 792 of file dt_check.cpp.
{
    return (a - b) / 1000000.0;
}
References b.
Referenced by check_basic_floating_point().