My Project: src/options.cpp File Reference
options.cpp File Reference
#include "conf.h"
Macros
#define opt ERROR_DO_NOT_USE_opt
#define opt ERROR_DO_NOT_USE_opt
Functions
TEST_CASE ("Options::reset")
doctest checks
template<size_t N>
static void test_options (const char *(&a)[N])
TEST_CASE ("getopt")
Variables
static Options global_options
Options * opt = &global_options
Macro Definition Documentation
opt [1/2]
#define opt ERROR_DO_NOT_USE_opt
opt [2/2]
#define opt ERROR_DO_NOT_USE_opt
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("getopt")
Definition at line 119 of file options.cpp.
                    {
#if WITH_THREADS
    std::lock_guard<std::mutex> lock(opt_lock_mutex);
#endif
    Options *const saved_opt = opt;
    Options local_options;
    opt = &local_options;
    opt->reset();
    opt->debug.getopt_throw_instead_of_exit = true;
    static const char a0[] = "<argv0>";
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--brute", "--lzma", nullptr};
        test_options(a);
        CHECK(opt->all_methods);
        CHECK(opt->all_methods_use_lzma == 1);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--lzma", "--brute", nullptr};
        test_options(a);
        CHECK(opt->all_methods);
        CHECK(opt->all_methods_use_lzma == 1);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--brute", "--no-lzma", nullptr};
        test_options(a);
        CHECK(opt->all_methods);
        CHECK(opt->all_methods_use_lzma == -1);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--no-lzma", "--brute", nullptr};
        test_options(a);
        CHECK(opt->all_methods);
        CHECK(opt->all_methods_use_lzma == -1);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--no-lzma", "--lzma", nullptr};
        test_options(a);
        CHECK(!opt->all_methods);
        CHECK(opt->all_methods_use_lzma == 1);
        CHECK(opt->method == M_LZMA);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--no-lzma", "--lzma", "--brute", nullptr};
        test_options(a);
        CHECK(opt->all_methods);
        CHECK(opt->all_methods_use_lzma == 1);
        CHECK(opt->method == -1);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--lzma", "--no-lzma", nullptr};
        test_options(a);
        CHECK(!opt->all_methods);
        CHECK(opt->all_methods_use_lzma == -1);
        CHECK(opt->method == -1);
    }
    SUBCASE("issue 587") {
        const char *a[] = {a0, "--lzma", "--no-lzma", "--brute", nullptr};
        test_options(a);
        CHECK(opt->all_methods);
        CHECK(opt->all_methods_use_lzma == -1);
        CHECK(opt->method == -1);
    }
    opt = saved_opt;
}
References a0, M_LZMA, opt, and test_options().
TEST_CASE() [2/2]
TEST_CASE ("Options::reset")
doctest checks
Definition at line 92 of file options.cpp.
{
#define opt ERROR_DO_NOT_USE_opt // self-protect against using the wrong variable
    COMPILE_TIME_ASSERT(std::is_standard_layout<Options>::value)
    COMPILE_TIME_ASSERT(std::is_nothrow_default_constructible<Options>::value)
    COMPILE_TIME_ASSERT(std::is_trivially_copyable<Options>::value)
    Options local_options;
    Options *const o = &local_options;
    o->reset();
    CHECK(o->o_unix.osabi0 == 3);
    static_assert(TABLESIZE(o->win32_pe.compress_rt) == 25); // 25 == RT_LAST
    CHECK(o->win32_pe.compress_exports);
    CHECK(o->win32_pe.compress_icons);
    CHECK(o->win32_pe.strip_relocs);
    // issue 728
    CHECK(o->win32_pe.compress_resources);
    for (size_t i = 0; i < 24; i++)
        CHECK(o->win32_pe.compress_rt[i]);
    CHECK(!o->win32_pe.compress_rt[24]); // 24 == RT_MANIFEST
#undef opt
}
References COMPILE_TIME_ASSERT, Options::compress_exports, Options::compress_icons, Options::compress_resources, Options::compress_rt, Options::o_unix, Options::osabi0, Options::reset(), Options::strip_relocs, TABLESIZE, and Options::win32_pe.
test_options()
template<size_t N> static void test_options (const char *(&) a[N]) inline static
Definition at line 115 of file options.cpp.
{
    (void) main_get_options((int) (N - 1), ACC_UNCONST_CAST(char **, a));
}
References ACC_UNCONST_CAST, main_get_options(), and N.
Referenced by TEST_CASE().
Variable Documentation
global_options
Options global_options static
Definition at line 30 of file options.cpp.
opt
Options* opt = &global_options
Definition at line 31 of file options.cpp.
Referenced by Options::reset().