My Project: src/p_djgpp2.cpp File Reference
p_djgpp2.cpp File Reference
#include "conf.h"
#include "file.h"
#include "filter.h"
#include "packer.h"
#include "p_djgpp2.h"
#include "linker.h"
#include "stub/i386-dos32.djgpp2.h"
#include "stub/i386-dos32.djgpp2-stubify.h"
Functions
static bool is_dlm (InputFile *fi, unsigned coff_offset)
static void handle_allegropak (InputFile *fi, OutputFile *fo)
Function Documentation
handle_allegropak()
static void handle_allegropak (InputFile * fi, OutputFile * fo) static
Definition at line 127 of file p_djgpp2.cpp.
{
    byte b[8];
    int pfsize = 0;
    try {
        fi->seek(-8, SEEK_END);
        fi->readx(b, 8);
        if (memcmp(b, "slh+", 4) != 0)
            return;
        pfsize = get_be32_signed(b + 4);
        if (pfsize <= 8 || pfsize >= fi->st.st_size)
            return;
        fi->seek(-pfsize, SEEK_END);
    } catch (const IOException &) {
        return;
    }
    MemBuffer buf(0x4000);
    while (pfsize > 0) {
        const int len = UPX_MIN(pfsize, (int) buf.getSize());
        fi->readx(buf, len);
        fo->write(buf, len);
        pfsize -= len;
    }
}
References b, buf, get_be32_signed(), memcmp(), InputFile::readx(), InputFile::seek(), SEEK_END, FileBase::st, UPX_MIN, and OutputFile::write().
Referenced by PackDjgpp2::pack(), and PackDjgpp2::unpack().
is_dlm()
static bool is_dlm (InputFile * fi, unsigned coff_offset) static
Definition at line 108 of file p_djgpp2.cpp.
{
    byte buf[4];
    unsigned off;
    try {
        fi->seek(coff_offset, SEEK_SET);
        fi->readx(buf, 4);
        off = get_le32(buf);
        if (off > coff_offset + 4)
            return false;
        fi->seek(off, SEEK_SET);
        fi->readx(buf, 4);
        if (memcmp(buf, "DLMF", 4) == 0)
            return true;
    } catch (const IOException &) {
    }
    return false;
}
References buf, get_le32(), memcmp(), InputFile::readx(), InputFile::seek(), and SEEK_SET.
Referenced by PackDjgpp2::canPack(), and PackDjgpp2::canUnpack().