My Project: src/p_lx_elf.cpp File Reference
p_lx_elf.cpp File Reference
#include "conf.h"
#include "file.h"
#include "filter.h"
#include "linker.h"
#include "packer.h"
#include "p_elf.h"
#include "p_unix.h"
#include "p_lx_exc.h"
#include "p_lx_elf.h"
#include "ui.h"
#include "p_elf_enum.h"
#include "stub/i386-linux.elf-entry.h"
#include "stub/i386-linux.elf-so_entry.h"
#include "stub/i386-linux.elf-fold.h"
#include "stub/i386-linux.elf-so_fold.h"
#include "stub/i386-linux.shlib-init.h"
#include "stub/i386-bsd.elf-entry.h"
#include "stub/i386-bsd.elf-fold.h"
#include "stub/i386-netbsd.elf-entry.h"
#include "stub/i386-netbsd.elf-fold.h"
#include "stub/i386-openbsd.elf-fold.h"
#include "stub/arm.v5a-linux.elf-entry.h"
#include "stub/arm.v5a-linux.elf-so_entry.h"
#include "stub/arm.v5a-linux.elf-fold.h"
#include "stub/arm.v5a-linux.elf-so_fold.h"
#include "stub/arm.v5t-linux.shlib-init.h"
#include "stub/arm.v4a-linux.elf-entry.h"
#include "stub/arm.v4a-linux.elf-so_entry.h"
#include "stub/arm.v4a-linux.elf-fold.h"
#include "stub/arm.v4a-linux.elf-so_fold.h"
#include "stub/armeb.v4a-linux.elf-entry.h"
#include "stub/armeb.v4a-linux.elf-fold.h"
#include "stub/mipsel.r3000-linux.elf-entry.h"
#include "stub/mipsel.r3000-linux.elf-fold.h"
#include "stub/mipsel.r3000-linux.shlib-init.h"
#include "stub/mips.r3000-linux.elf-entry.h"
#include "stub/mips.r3000-linux.elf-fold.h"
#include "stub/mips.r3000-linux.shlib-init.h"
#include "stub/powerpc-linux.elf-entry.h"
#include "stub/powerpc-linux.elf-fold.h"
#include "stub/powerpc64le-linux.elf-entry.h"
#include "stub/powerpc64le-linux.elf-fold.h"
#include "stub/powerpc64-linux.elf-entry.h"
#include "stub/powerpc64-linux.elf-fold.h"
#include "stub/amd64-linux.elf-entry.h"
#include "stub/amd64-linux.elf-fold.h"
#include "stub/amd64-linux.elf-so_entry.h"
#include "stub/amd64-linux.elf-so_fold.h"
#include "stub/amd64-linux.shlib-init.h"
#include "stub/arm64-linux.elf-entry.h"
#include "stub/arm64-linux.elf-so_entry.h"
#include "stub/arm64-linux.elf-fold.h"
#include "stub/arm64-linux.elf-so_fold.h"
#include "stub/arm64-linux.shlib-init.h"
Macros
#define ALLOW_INT_PLUS_MEMBUFFER 1
#define PT_LOAD Elf32_Phdr::PT_LOAD /* 64-bit PT_LOAD is the same */
#define PT_NOTE32 Elf32_Phdr::PT_NOTE
#define PT_NOTE64 Elf64_Phdr::PT_NOTE
#define PT_GNU_STACK32 Elf32_Phdr::PT_GNU_STACK
#define PT_GNU_STACK64 Elf64_Phdr::PT_GNU_STACK
#define PT_GNU_RELRO32 Elf32_Phdr::PT_GNU_RELRO
#define PT_GNU_RELRO64 Elf64_Phdr::PT_GNU_RELRO
#define WANT_EHDR_ENUM
#define WANT_REL_ENUM
#define WANT_NHDR_ENUM
#define WANT_SHDR_ENUM
#define MAP_PRIVATE 2 /* UNIX standard */
#define MAP_FIXED 0x10 /* UNIX standard */
#define MAP_ANONYMOUS 0x20 /* UNIX standard */
#define MAP_PRIVANON 3 /* QNX anonymous private memory */
#define MAP_PRIVATE 2 /* UNIX standard */
#define MAP_FIXED 0x10 /* UNIX standard */
#define MAP_ANONYMOUS 0x20 /* UNIX standard */
#define MAP_PRIVANON 3 /* QNX anonymous private memory */
Enumerations
enum { C_BASE = 0 , C_TEXT = 1 , C_NOTE = 2 , C_GSTK = 3 }
Functions
static unsigned up4 (unsigned x)
static unsigned up8 (unsigned x)
static off_t fpadN (OutputFile *fo, unsigned len)
static off_t fpad4 (OutputFile *fo, unsigned pos)
static off_t fpad8 (OutputFile *fo, unsigned pos)
static unsigned funpad4 (InputFile *fi)
static void alloc_file_image (MemBuffer &mb, off_t size)
static unsigned is_pow2 (u64_t x)
static int __acc_cdecl_qsort qcmp_unsigned (void const *const aa, void const *const bb)
static unsigned is_pow2 (unsigned x)
static const int * ARM_getFilters (bool const isBE)
Variables
static constexpr unsigned MAX_ELF_HDR_32 = 512
static constexpr unsigned MAX_ELF_HDR_64 = 1024
static unsigned const EF_ARM_EABI_VER4 = 0x04000000
static unsigned const EF_ARM_EABI_VER5 = 0x05000000
static unsigned const dt_keys []
static char const abs_symbol_names [][14]
Macro Definition Documentation
ALLOW_INT_PLUS_MEMBUFFER
#define ALLOW_INT_PLUS_MEMBUFFER 1
Definition at line 33 of file p_lx_elf.cpp.
MAP_ANONYMOUS [1/2]
#define MAP_ANONYMOUS 0x20 /* UNIX standard */
MAP_ANONYMOUS [2/2]
#define MAP_ANONYMOUS 0x20 /* UNIX standard */
MAP_FIXED [1/2]
#define MAP_FIXED 0x10 /* UNIX standard */
MAP_FIXED [2/2]
#define MAP_FIXED 0x10 /* UNIX standard */
MAP_PRIVANON [1/2]
#define MAP_PRIVANON 3 /* QNX anonymous private memory */
MAP_PRIVANON [2/2]
#define MAP_PRIVANON 3 /* QNX anonymous private memory */
MAP_PRIVATE [1/2]
#define MAP_PRIVATE 2 /* UNIX standard */
MAP_PRIVATE [2/2]
#define MAP_PRIVATE 2 /* UNIX standard */
PT_GNU_RELRO32
#define PT_GNU_RELRO32 Elf32_Phdr::PT_GNU_RELRO
Definition at line 58 of file p_lx_elf.cpp.
PT_GNU_RELRO64
#define PT_GNU_RELRO64 Elf64_Phdr::PT_GNU_RELRO
Definition at line 59 of file p_lx_elf.cpp.
PT_GNU_STACK32
#define PT_GNU_STACK32 Elf32_Phdr::PT_GNU_STACK
Definition at line 56 of file p_lx_elf.cpp.
PT_GNU_STACK64
#define PT_GNU_STACK64 Elf64_Phdr::PT_GNU_STACK
Definition at line 57 of file p_lx_elf.cpp.
PT_LOAD
#define PT_LOAD Elf32_Phdr::PT_LOAD /* 64-bit PT_LOAD is the same */
Definition at line 53 of file p_lx_elf.cpp.
PT_NOTE32
#define PT_NOTE32 Elf32_Phdr::PT_NOTE
Definition at line 54 of file p_lx_elf.cpp.
PT_NOTE64
#define PT_NOTE64 Elf64_Phdr::PT_NOTE
Definition at line 55 of file p_lx_elf.cpp.
WANT_EHDR_ENUM
#define WANT_EHDR_ENUM
Definition at line 376 of file p_lx_elf.cpp.
WANT_NHDR_ENUM
#define WANT_NHDR_ENUM
Definition at line 1901 of file p_lx_elf.cpp.
WANT_REL_ENUM
#define WANT_REL_ENUM
Definition at line 377 of file p_lx_elf.cpp.
WANT_SHDR_ENUM
#define WANT_SHDR_ENUM
Definition at line 2722 of file p_lx_elf.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
C_BASE
C_TEXT
C_NOTE
C_GSTK
Definition at line 506 of file p_lx_elf.cpp.
     { // ordinals in ELFxx_Phdr[] of compressed output
      C_BASE = 0  // reserve address space
    , C_TEXT = 1  // compressed data and stub
    , C_NOTE = 2  // PT_NOTE copied from input
    , C_GSTK = 3  // PT_GNU_STACK; will be 2 if no PT_NOTE
};
Function Documentation
alloc_file_image()
static void alloc_file_image (MemBuffer & mb, off_t size) static
Definition at line 138 of file p_lx_elf.cpp.
{
    assert(mem_size_valid_bytes(size));
    if (mb.getVoidPtr() == nullptr) {
        mb.alloc(size);
    } else {
        assert((u32_t)size <= mb.getSize());
    }
}
References MemBuffer::alloc(), MemBuffer::getSize(), MemBuffer::getVoidPtr(), mem_size_valid_bytes(), and size().
Referenced by PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxElf32::PackLinuxElf32help1(), and PackLinuxElf64::PackLinuxElf64help1().
ARM_getFilters()
static const int * ARM_getFilters (bool const isBE) static
Definition at line 5885 of file p_lx_elf.cpp.
{
    static const int f50[] = { 0x50, FT_END };
    static const int f51[] = { 0x51, FT_END };
    if (isBE)
        return f51;
    return f50;
}
References FT_END.
Referenced by PackLinuxElf32armLe::getFilters(), and PackLinuxElf32armBe::getFilters().
fpad4()
static off_t fpad4 (OutputFile * fo, unsigned pos) static
Definition at line 98 of file p_lx_elf.cpp.
{
    (void)pos;  // debug: compare 'pos' with "shell grep pos /proc/PID/fdinfo/FD"
    if (!fo) { // --test, --list
        return 0;
    }
    off_t len = fo->st_size();
    unsigned d = 3u & (0 - len);
    if (d) {
        unsigned zero = 0;
        fo->write(&zero, d);
    }
    return d + len;
}
References OutputFile::st_size(), and OutputFile::write().
Referenced by PackLinuxElf32::forward_Shdrs(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxElf::pack3(), PackLinuxElf32::pack4(), and PackLinuxElf64::pack4().
fpad8()
static off_t fpad8 (OutputFile * fo, unsigned pos) static
Definition at line 114 of file p_lx_elf.cpp.
{
    (void)pos;  // debug: compare 'pos' with "shell grep pos /proc/PID/fdinfo/FD"
    if (!fo) { // --test, --list
        return 0;
    }
    off_t len = fo->st_size();
    unsigned d = 7u & (0 - len);
    if (d) {
        upx_uint64_t zero = 0;
        fo->write(&zero, d);
    }
    return d + len;
}
References OutputFile::st_size(), and OutputFile::write().
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), and PackLinuxElf64::forward_Shdrs().
fpadN()
static off_t fpadN (OutputFile * fo, unsigned len) static
Definition at line 88 of file p_lx_elf.cpp.
{
    if (len) {
        MemBuffer pad(len); pad.clear();
        fo->write(pad, len);
    }
    return fo->st_size();
}
References MemBuffer::clear(), OutputFile::st_size(), and OutputFile::write().
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf32::pack3(), and PackLinuxElf64::pack3().
funpad4()
static unsigned funpad4 (InputFile * fi) static
Definition at line 130 of file p_lx_elf.cpp.
{
    unsigned d = 3u & (0 - fi->tell());
    if (d)
        fi->seek(d, SEEK_CUR);
    return d;
}
References InputFile::seek(), SEEK_CUR, and FileBase::tell().
Referenced by PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), and PackLinuxElf64::unpack().
is_pow2() [1/2]
static unsigned is_pow2 (u64_t x) static
Definition at line 447 of file p_lx_elf.cpp.
{
    return !((-1+ x) & x);
}
Referenced by PackVmlinuzI386::decompressKernel(), PackLinuxElf32::elf_find_Phdr_for_va(), PackLinuxElf64::elf_find_Phdr_for_va(), PackLinuxElf32::generateElfHdr(), and PackLinuxElf64::generateElfHdr().
is_pow2() [2/2]
static unsigned is_pow2 (unsigned x) static
Definition at line 3667 of file p_lx_elf.cpp.
{
    return !((-1 + x) & x);
}
qcmp_unsigned()
static int __acc_cdecl_qsort qcmp_unsigned (void const *const aa, void const *const bb) static
Definition at line 2166 of file p_lx_elf.cpp.
{
    unsigned a = *(unsigned const *)aa;
    unsigned b = *(unsigned const *)bb;
    if (a < b) return -1;
    if (a > b) return  1;
    return  0;
}
References b.
Referenced by PackLinuxElf32::sort_DT32_offsets(), and PackLinuxElf64::sort_DT64_offsets().
up4()
static unsigned up4 (unsigned x) static
Definition at line 76 of file p_lx_elf.cpp.
{
    return ~3u & (3+ x);
}
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackNetBSDElf32x86::generateElfHdr(), PackLinuxElf32::pack2(), PackLinuxElf64::pack2(), PackLinuxElf::pack3(), PackLinuxElf32::unpack(), and PackLinuxElf64::unpack().
up8()
static unsigned up8 (unsigned x) static
Definition at line 82 of file p_lx_elf.cpp.
{
    return ~7u & (7+ x);
}
Referenced by PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf32::pack2_shlib(), and PackLinuxElf64::pack2_shlib().
Variable Documentation
abs_symbol_names
char const abs_symbol_names[][14] static
Initial value:
= {
      "__bss_end__"
    ,  "_bss_end__"
    , "__bss_start"
    , "__bss_start__"
    ,  "_edata"
    ,  "_end"
    , "__end__"
    , ""
}
Definition at line 4130 of file p_lx_elf.cpp.
Referenced by PackLinuxElf32::adjABS(), and PackLinuxElf64::adjABS().
dt_keys
unsigned const dt_keys[] static
Initial value:
= {
        Elf64_Dyn::DT_SYMTAB,
        Elf64_Dyn::DT_VERSYM,
        Elf64_Dyn::DT_VERNEED,
        Elf64_Dyn::DT_HASH,
        Elf64_Dyn::DT_GNU_HASH,
        Elf64_Dyn::DT_STRTAB,
        Elf64_Dyn::DT_VERDEF,
        Elf64_Dyn::DT_REL,
        Elf64_Dyn::DT_RELA,
        Elf64_Dyn::DT_FINI_ARRAY,
        Elf64_Dyn::DT_INIT_ARRAY,
        Elf64_Dyn::DT_PREINIT_ARRAY,
        0,
}
Definition at line 2149 of file p_lx_elf.cpp.
Referenced by PackLinuxElf32::sort_DT32_offsets(), and PackLinuxElf64::sort_DT64_offsets().
EF_ARM_EABI_VER4
unsigned const EF_ARM_EABI_VER4 = 0x04000000 static
Definition at line 66 of file p_lx_elf.cpp.
Referenced by PackLinuxElf32::canPackOSABI().
EF_ARM_EABI_VER5
unsigned const EF_ARM_EABI_VER5 = 0x05000000 static
Definition at line 67 of file p_lx_elf.cpp.
Referenced by PackLinuxElf32::canPackOSABI().
MAX_ELF_HDR_32
constexpr unsigned MAX_ELF_HDR_32 = 512 static constexpr
Definition at line 62 of file p_lx_elf.cpp.
Referenced by PackLinuxElf32::canPack(), PackLinuxElf32::canPackOSABI(), and PackLinuxElf32::unpack().
MAX_ELF_HDR_64
constexpr unsigned MAX_ELF_HDR_64 = 1024 static constexpr
Definition at line 63 of file p_lx_elf.cpp.
Referenced by PackLinuxElf64::canPack(), and PackLinuxElf64::unpack().