My Project: src/packer_f.cpp File Reference
packer_f.cpp File Reference
#include "conf.h"
#include "packer.h"
#include "filter.h"
#include "linker.h"
Macros
#define NOFILT 0
addFilter32
#define FNOMRU 1
#define MRUFLT 2
Functions
static unsigned f80_call (int filter_id)
static unsigned f80_jmp1 (int filter_id)
static unsigned f80_jcc2 (int filter_id)
Macro Definition Documentation
FNOMRU
#define FNOMRU 1
Definition at line 46 of file packer_f.cpp.
MRUFLT
#define MRUFLT 2
Definition at line 47 of file packer_f.cpp.
NOFILT
#define NOFILT 0
addFilter32
Definition at line 45 of file packer_f.cpp.
Function Documentation
f80_call()
static unsigned f80_call (int filter_id) inline static
Definition at line 49 of file packer_f.cpp.
{ return (1 + (0x0f & filter_id)) % 3; }
Referenced by Packer::addFilter32(), and F().
f80_jcc2()
static unsigned f80_jcc2 (int filter_id) inline static
Definition at line 53 of file packer_f.cpp.
{ return f80_jmp1(filter_id); }
References f80_jmp1().
Referenced by Packer::addFilter32(), and F().
f80_jmp1()
static unsigned f80_jmp1 (int filter_id) inline static
Definition at line 51 of file packer_f.cpp.
{ return ((1 + (0x0f & filter_id)) / 3) % 3; }
Referenced by Packer::addFilter32(), F(), and f80_jcc2().