My Project: src/packer.cpp File Reference
packer.cpp File Reference
#include "conf.h"
#include "file.h"
#include "packer.h"
#include "filter.h"
#include "linker.h"
#include "ui.h"
Macros
#define C const char *
#define N ACC_STATIC_CAST(void *, nullptr)
Functions
static const char * getIdentstr (unsigned *size, int small)
loader util (interface to linker)
static int prepareFilters (int *filters, int &filter_strategy, const int *all_filters)
Macro Definition Documentation
C
#define C const char *
Definition at line 771 of file packer.cpp.
N
#define N ACC_STATIC_CAST(void *, nullptr)
Definition at line 772 of file packer.cpp.
Function Documentation
getIdentstr()
static const char * getIdentstr (unsigned * size, int small) static
loader util (interface to linker)
Definition at line 708 of file packer.cpp.
{
    // IMPORTANT: we do NOT change "http://upx.sf.net"
    static char identbig[] =
        "\n\0"
        "$Info: "
        "This file is packed with the UPX executable packer http://upx.sf.net $"
        "\n\0"
        "$Id: UPX " UPX_VERSION_STRING4 " Copyright (C) 1996-" UPX_VERSION_YEAR
        " the UPX Team. All Rights Reserved. $"
        "\n";
    static char identsmall[] =
        "\n"
        "$Id: UPX "
        "(C) 1996-" UPX_VERSION_YEAR " the UPX Team. All Rights Reserved. http://upx.sf.net $"
        "\n";
    static char identtiny[] = UPX_VERSION_STRING4;
    static upx_std_once_flag init_done;
    upx_std_call_once(init_done, []() noexcept {
        if (opt->debug.fake_stub_version[0] || opt->debug.fake_stub_year[0]) {
            struct Ident {
                char *s;
                int len;
            };
            static const Ident idents[] = {{identbig, (int) sizeof(identbig) - 1},
                                           {identsmall, (int) sizeof(identsmall) - 1},
                                           {identtiny, (int) sizeof(identtiny) - 1},
                                           {nullptr, 0}};
            for (const Ident *iter = idents; iter->s; ++iter) {
                if (opt->debug.fake_stub_version[0])
                    mem_replace(iter->s, iter->len, UPX_VERSION_STRING4, 4,
                                opt->debug.fake_stub_version);
                if (opt->debug.fake_stub_year[0])
                    mem_replace(iter->s, iter->len, UPX_VERSION_YEAR, 4, opt->debug.fake_stub_year);
            }
        }
    });
    if (small < 0)
        small = opt->small;
    if (small >= 2) {
        *size = sizeof(identtiny);
        return identtiny;
    } else if (small >= 1) {
        *size = sizeof(identsmall);
        return identsmall;
    } else {
        *size = sizeof(identbig);
        return identbig;
    }
}
References mem_replace(), opt, upx_std_call_once(), upx_std_once_flag, UPX_VERSION_STRING4, and UPX_VERSION_YEAR.
Referenced by PackLinuxI386::generateElfHdr(), and Packer::initLoader().
prepareFilters()
static int prepareFilters (int * filters, int & filter_strategy, const int * all_filters) static
Definition at line 939 of file packer.cpp.
{
    int nfilters = 0;
    // setup filter filter_strategy
    if (filter_strategy == 0) {
        if (opt->all_filters)
            // choose best from all available filters
            filter_strategy = INT_MAX;
        else if (opt->filter >= 0 && Filter::isValidFilter(opt->filter, all_filters))
            // try opt->filter
            filter_strategy = -2;
        else
            // try the first working filter
            filter_strategy = -1;
    }
    assert(filter_strategy != 0);
    if (filter_strategy <= -3)
        goto done;
    if (filter_strategy == -2) {
        if (opt->filter >= 0 && Filter::isValidFilter(opt->filter, all_filters)) {
            filters[nfilters++] = opt->filter;
            goto done;
        }
        filter_strategy = -1;
    }
    assert(filter_strategy >= -1);
    while (all_filters && *all_filters != FT_END) {
        int filter_id = *all_filters++;
        if (filter_id == FT_ULTRA_BRUTE && !opt->ultra_brute)
            break;
        if (filter_id == FT_SKIP || filter_id == FT_ULTRA_BRUTE)
            continue;
        if (filter_id == 0)
            continue;
        // check duplicate
        assert(Filter::isValidFilter(filter_id));
        for (int i = 0; i < nfilters; i++)
            assert(filter_id != filters[i]);
        // use this filter
        filters[nfilters++] = filter_id;
        if (filter_strategy >= 0 && nfilters >= filter_strategy)
            break;
    }
done:
    // filter_strategy now only means "stop after first successful filter"
    filter_strategy = (filter_strategy < 0) ? -1 : 0;
    // make sure that we have a "no filter" fallback
    bool have_filter0 = false;
    for (int i = 0; i < nfilters; i++)
        if (filters[i] == 0) {
            have_filter0 = true;
            break;
        }
    if (!have_filter0)
        filters[nfilters++] = 0;
    // debug
    if (opt->debug.use_random_filter && nfilters >= 3 && filters[nfilters - 1] == 0) {
        int filter_id = filters[upx_rand() % (nfilters - 1)];
        if (filter_id > 0) {
            NO_printf("\nuse_random_filter = %#x (%d)\n", filter_id, nfilters - 1);
            filters[0] = filter_id;
            filters[1] = 0;
            nfilters = 2;
        }
    }
    return nfilters;
}
References FT_END, FT_SKIP, FT_ULTRA_BRUTE, Filter::isValidFilter(), NO_printf(), opt, and upx_rand().
Referenced by Packer::compressWithFilters().