My Project: src/packhead.cpp File Reference
packhead.cpp File Reference
#include "conf.h"
#include "packhead.h"
#include "filter.h"
Functions
static upx_uint8_t get_packheader_checksum (SPAN_S(const byte) buf, int blen)
extremely simple checksum for the header itself (since version 10)
bool ph_is_forced_method (int method) noexcept
ph method util
int ph_force_method (int method) noexcept
int ph_forced_method (int method) noexcept
bool ph_skipVerify (const PackHeader &ph) noexcept
void ph_decompress (PackHeader &ph, SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum, Filter *ft)
ph decompress util
bool ph_testOverlappingDecompression (const PackHeader &ph, const byte *buf, const byte *tbuf, unsigned overlap_overhead)
ph overlapping decompression util
Function Documentation
get_packheader_checksum()
static upx_uint8_t get_packheader_checksum (SPAN_S(const byte) buf, int blen) static
extremely simple checksum for the header itself (since version 10)
Definition at line 52 of file packhead.cpp.
{
    assert(blen >= 4);
    assert(get_le32(buf) == UPX_MAGIC_LE32);
    buf += 4;
    blen -= 4;
    unsigned c = 0;
    while (blen-- > 0)
        c += *buf++;
    c %= 251;
    return (upx_uint8_t) c;
}
References buf, get_le32(), and UPX_MAGIC_LE32.
Referenced by PackHeader::decodePackHeaderFromBuf(), and PackHeader::putPackHeader().
ph_decompress()
void ph_decompress (PackHeader & ph, SPAN_P(const byte) in, SPAN_P(byte) out, bool verify_checksum, Filter * ft)
ph decompress util
Definition at line 322 of file packhead.cpp.
{
    // verify checksum of compressed data
    if (verify_checksum) {
        unsigned adler = upx_adler32(raw_bytes(in, ph.c_len), ph.c_len, ph.saved_c_adler);
        if (adler != ph.c_adler)
            throwChecksumError();
    }
    // decompress
    if (ph.u_len < ph.c_len)
        throwCantUnpack("header corrupted");
    unsigned new_len = ph.u_len;
    int r = upx_decompress(raw_bytes(in, ph.c_len), ph.c_len, raw_bytes(out, ph.u_len), &new_len,
                           ph_forced_method(ph.method), &ph.compress_result);
    if (r == UPX_E_OUT_OF_MEMORY)
        throwOutOfMemoryException();
    if (r != UPX_E_OK || new_len != ph.u_len)
        throwCompressedDataViolation();
    // verify checksum of decompressed data
    if (verify_checksum) {
        if (ft)
            ft->unfilter(out, ph.u_len);
        unsigned adler = upx_adler32(raw_bytes(out, ph.u_len), ph.u_len, ph.saved_u_adler);
        if (adler != ph.u_adler)
            throwChecksumError();
    }
}
References PackHeader::c_adler, PackHeader::c_len, PackHeader::compress_result, PackHeader::method, ph_forced_method(), raw_bytes(), PackHeader::saved_c_adler, PackHeader::saved_u_adler, throwCantUnpack(), throwChecksumError(), throwCompressedDataViolation(), throwOutOfMemoryException(), PackHeader::u_adler, PackHeader::u_len, Filter::unfilter(), upx_adler32(), upx_decompress(), UPX_E_OK, and UPX_E_OUT_OF_MEMORY.
Referenced by Packer::decompress().
ph_force_method()
int ph_force_method (int method) noexcept
Definition at line 295 of file packhead.cpp.
{
    return method | (0x80u << 24);
}
Referenced by PackLinuxElf32::pack1(), and PackLinuxElf64::pack1().
ph_forced_method()
int ph_forced_method (int method) noexcept
Definition at line 300 of file packhead.cpp.
{
    if (ph_is_forced_method(method))
        method &= ~(0x80u << 24);
    assert_noexcept(method > 0);
    return method;
}
References assert_noexcept, and ph_is_forced_method().
Referenced by PackLinuxElf::addStubEntrySections(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), Packer::compress(), Packer::getDecompressorSections(), PackUnix::packExtent(), ph_decompress(), ph_testOverlappingDecompression(), and Packer::prepareMethods().
ph_is_forced_method()
bool ph_is_forced_method (int method) noexcept
ph method util
PackHeader ph util functions.
Definition at line 290 of file packhead.cpp.
{
    return (method >> 24) == -0x80;
}
Referenced by Packer::compressWithFilters(), and ph_forced_method().
ph_skipVerify()
bool ph_skipVerify (const PackHeader & ph) noexcept
Definition at line 308 of file packhead.cpp.
{
    if (M_IS_DEFLATE(ph.method))
        return false;
    if (M_IS_LZMA(ph.method))
        return false;
    if (ph.level > 1)
        return false;
    return true;
}
References M_IS_DEFLATE, and M_IS_LZMA.
Referenced by Packer::compress(), and Packer::verifyOverlappingDecompression().
ph_testOverlappingDecompression()
bool ph_testOverlappingDecompression (const PackHeader & ph, const byte * buf, const byte * tbuf, unsigned overlap_overhead)
ph overlapping decompression util
Definition at line 356 of file packhead.cpp.
{
    if (ph.c_len >= ph.u_len)
        return false;
    assert((int) overlap_overhead >= 0);
    assert((int) (ph.u_len + overlap_overhead) >= 0);
    const int method = ph_forced_method(ph.method);
    // Because upx_test_overlap() does not use the asm_fast decompressor
    // we must account for extra 3 bytes that asm_fast does use,
    // or else we may fail at runtime decompression.
    unsigned extra = 0;
    if (M_IS_NRV2B(method) || M_IS_NRV2D(method) || M_IS_NRV2E(method))
        extra = 3;
    if (overlap_overhead <= 4 + extra) // don't waste time here
        return false;
    overlap_overhead -= extra;
    unsigned src_off = ph.u_len + overlap_overhead - ph.c_len;
    unsigned new_len = ph.u_len;
    int r = upx_test_overlap(buf - src_off, tbuf, src_off, ph.c_len, &new_len, method,
                             &ph.compress_result);
    if (r == UPX_E_OUT_OF_MEMORY)
        throwOutOfMemoryException();
    return (r == UPX_E_OK && new_len == ph.u_len);
}
References buf, PackHeader::c_len, PackHeader::compress_result, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, PackHeader::method, ph_forced_method(), throwOutOfMemoryException(), PackHeader::u_len, UPX_E_OK, UPX_E_OUT_OF_MEMORY, and upx_test_overlap().
Referenced by Packer::testOverlappingDecompression().