My Project: src/pefile.cpp File Reference
pefile.cpp File Reference
#include "conf.h"
#include "file.h"
#include "filter.h"
#include "packer.h"
#include "pefile.h"
#include "linker.h"
Classes
class PeFile::ImportLinker
struct PeFile::ImportLinker::TStr
struct PeFile::tls_traits< LE32 >
TLS handling.
struct PeFile::tls_traits< LE32 >::tls
struct PeFile::tls_traits< LE64 >
struct PeFile::tls_traits< LE64 >::tls
struct PeFile::Resource::res_dir_entry
resource handling
struct PeFile::Resource::res_dir
struct PeFile::Resource::res_data
struct PeFile::Resource::upx_rnode
struct PeFile::Resource::upx_rbranch
struct PeFile::Resource::upx_rleaf
struct anonymous_namespace{pefile.cpp}::VPtr< T >
Namespaces
namespace anonymous_namespace{pefile.cpp}
Macros
#define FILLVAL 0
#define import my_import
#define IPTR_VAR(type, var, first) SPAN_S_VAR(type, var, first, ibuf)
#define OPTR_VAR(type, var, first) SPAN_S_VAR(type, var, first, obuf)
#define IPTR_VAR_OFFSET(type, var, offset) SPAN_S_VAR(type, var, ibuf + (offset), ibuf.getSize() - (offset), ibuf + (offset))
#define ICHECK(p, bytes) xcheck(raw_bytes(p, 0), bytes, ibuf, ibuf.getSize())
#define OCHECK(p, bytes) xcheck(raw_bytes(p, 0), bytes, obuf, obuf.getSize())
#define omemcpy(a, b, c) OCHECK(a, c), memcpy(a, b, c)
#define omemmove(a, b, c) OCHECK(a, c), memmove(a, b, c)
Functions
static void xcheck (const void *p)
static void xcheck (const void *p, size_t plen, const void *b, size_t blen)
static void reloc_entry_encode (SPAN_P(byte) buf, unsigned pos, unsigned reloc_type)
static void reloc_entry_decode (SPAN_P(const byte) buf, unsigned *pos, unsigned *reloc_type)
static int __acc_cdecl_qsort reloc_entry_compare (const void *a, const void *b)
static void lame_print_unicode (const byte *p)
static bool match (unsigned itype, const byte *ntype, unsigned iname, const byte *nname, const char *keep)
Variables
static constexpr bool ALWAYS_CHECK_STRICT_RELOCS = true
relocation handling
static constexpr size_t RELOC_INPLACE_OFFSET = 64 * 1024
static constexpr size_t RELOC_ENTRY_SIZE = 5
Macro Definition Documentation
FILLVAL
#define FILLVAL 0
Definition at line 35 of file pefile.cpp.
ICHECK
#define ICHECK (p, bytes) xcheck(raw_bytes(p, 0), bytes, ibuf, ibuf.getSize())
Definition at line 57 of file pefile.cpp.
import
#define import my_import
Definition at line 36 of file pefile.cpp.
IPTR_VAR
#define IPTR_VAR (type, var, first) SPAN_S_VAR(type, var, first, ibuf)
Definition at line 42 of file pefile.cpp.
IPTR_VAR_OFFSET
#define IPTR_VAR_OFFSET (type, var, offset) SPAN_S_VAR(type, var, ibuf + (offset), ibuf.getSize() - (offset), ibuf + (offset))
Definition at line 44 of file pefile.cpp.
OCHECK
#define OCHECK (p, bytes) xcheck(raw_bytes(p, 0), bytes, obuf, obuf.getSize())
Definition at line 58 of file pefile.cpp.
omemcpy
#define omemcpy (a, b, c) OCHECK(a, c), memcpy(a, b, c)
Definition at line 63 of file pefile.cpp.
omemmove
#define omemmove (a, b, c) OCHECK(a, c), memmove(a, b, c)
Definition at line 64 of file pefile.cpp.
OPTR_VAR
#define OPTR_VAR (type, var, first) SPAN_S_VAR(type, var, first, obuf)
Definition at line 43 of file pefile.cpp.
Function Documentation
lame_print_unicode()
static void lame_print_unicode (const byte * p) static
Definition at line 1818 of file pefile.cpp.
{
    for (unsigned ic = 0; ic < get_le16(p); ic++)
        printf("%c", (char) p[ic * 2 + 2]);
}
References get_le16().
Referenced by PeFile::Resource::dump().
match()
static bool match (unsigned itype, const byte * ntype, unsigned iname, const byte * nname, const char * keep) static
Definition at line 1879 of file pefile.cpp.
{
    // format of string keep: type1[/name1],type2[/name2], ....
    // typex and namex can be string or number
    // hopefully resource names do not have '/' or ',' characters inside
    struct Helper final {
        static bool match(unsigned num, const byte *unistr, const char *mkeep) {
            if (!unistr)
                return (unsigned) atoi(mkeep) == num;
            unsigned ic;
            for (ic = 0; ic < get_le16(unistr); ic++)
                if (unistr[2 + ic * 2] != (byte) mkeep[ic])
                    return false;
            return mkeep[ic] == 0 || mkeep[ic] == ',' || mkeep[ic] == '/';
        }
    };
    // FIXME this comparison is not too exact
    for (;;) {
        const char *delim1 = strchr(keep, '/');
        const char *delim2 = strchr(keep, ',');
        if (Helper::match(itype, ntype, keep)) {
            if (!delim1)
                return true;
            if (delim2 && delim2 < delim1)
                return true;
            if (Helper::match(iname, nname, delim1 + 1))
                return true;
        }
        if (delim2 == nullptr)
            break;
        keep = delim2 + 1;
    }
    return false;
}
References get_le16(), and match().
Referenced by match(), and PeFile::processResources().
reloc_entry_compare()
static int __acc_cdecl_qsort reloc_entry_compare (const void * a, const void * b) static
Definition at line 313 of file pefile.cpp.
{
    const unsigned pos1 = get_ne32(a);
    const unsigned pos2 = get_ne32(b);
    if (pos1 != pos2)
        return pos1 < pos2 ? -1 : 1;
    const unsigned reloc_type1 = ((const upx_uint8_t *) a)[4];
    const unsigned reloc_type2 = ((const upx_uint8_t *) b)[4];
    if (reloc_type1 != reloc_type2)
        return reloc_type1 < reloc_type2 ? -1 : 1;
    return 0;
}
References b, and get_ne32().
Referenced by PeFile::Reloc::finish().
reloc_entry_decode()
static void reloc_entry_decode (SPAN_P(const byte) buf, unsigned * pos, unsigned * reloc_type) static
Definition at line 308 of file pefile.cpp.
{
    *pos = get_ne32(buf);
    *reloc_type = buf[4];
    assert(*reloc_type > 0 && *reloc_type < 16);
}
References buf, and get_ne32().
Referenced by PeFile::Reloc::finish().
reloc_entry_encode()
static void reloc_entry_encode (SPAN_P(byte) buf, unsigned pos, unsigned reloc_type) static
Definition at line 302 of file pefile.cpp.
{
    if (reloc_type == 0 || reloc_type >= 16)
        throwCantPack("bad reloc_type %#x %u", pos, reloc_type);
    set_ne32(buf, pos);
    buf[4] = (upx_uint8_t) reloc_type;
}
References buf, set_ne32(), and throwCantPack().
Referenced by PeFile::Reloc::add_reloc().
xcheck() [1/2]
static void xcheck (const void * p) static
Definition at line 47 of file pefile.cpp.
{
    if very_unlikely (p == nullptr)
        throwCantUnpack("xcheck unexpected nullptr pointer; take care!");
}
References throwCantUnpack(), and very_unlikely.
Referenced by PeFile::Resource::build(), PeFile::Resource::convert(), and PeFile::Resource::destroy().
xcheck() [2/2]
static void xcheck (const void * p, size_t plen, const void * b, size_t blen) static
Definition at line 51 of file pefile.cpp.
{
    const charptr pp = (const charptr) p;
    const charptr bb = (const charptr) b;
    if very_unlikely (pp < bb || pp > bb + blen || pp + plen > bb + blen)
        throwCantUnpack("xcheck pointer out of range; take care!");
}
References b, charptr, throwCantUnpack(), and very_unlikely.
Variable Documentation
ALWAYS_CHECK_STRICT_RELOCS
constexpr bool ALWAYS_CHECK_STRICT_RELOCS = true static constexpr
relocation handling
Definition at line 290 of file pefile.cpp.
Referenced by PeFile::Reloc::finish(), and PeFile::Reloc::readFromRelocationBlock().
RELOC_ENTRY_SIZE
constexpr size_t RELOC_ENTRY_SIZE = 5 static constexpr
Definition at line 301 of file pefile.cpp.
Referenced by PeFile::Reloc::add_reloc(), PeFile::Reloc::finish(), and PeFile::Reloc::Reloc().
RELOC_INPLACE_OFFSET
constexpr size_t RELOC_INPLACE_OFFSET = 64 * 1024 static constexpr
Definition at line 299 of file pefile.cpp.
Referenced by PeFile::Reloc::add_reloc(), PeFile::Reloc::finish(), and PeFile::Reloc::Reloc().