My Project: src/filter/ppcbxx.h File Reference
ppcbxx.h File Reference
Macros
#define W_CTO 4 /* width of cto; must match stub/ppc_bxx.S */
filter / scan
Functions
static int F (Filter *f)
Macro Definition Documentation
W_CTO
#define W_CTO 4 /* width of cto; must match stub/ppc_bxx.S */
filter / scan
Definition at line 36 of file ppcbxx.h.
Function Documentation
F()
static int F (Filter * f) static
Definition at line 38 of file ppcbxx.h.
{
#ifdef U
    // filter
    byte *b = f->buf;
    const unsigned addvalue = f->addvalue;
#else
    // scan
    const byte *b = f->buf;
#endif
    const unsigned size = upx::umin(f->buf_len, 0u - (~0u << (32 - (6 + W_CTO))));
    const unsigned size4 = size - 4;
    unsigned ic;
    unsigned calls = 0, noncalls = 0;
    unsigned lastnoncall = size, lastcall = 0;
    // find 26-2-W_CTO bits of displacements that contain no targets
    {
        unsigned char buf[256];
        unsigned short wbuf[256];
        const size_t WW = (size_t) 0 - ((~(size_t) 0) << W_CTO); // ???
        memset(wbuf, 0, sizeof(wbuf));
        memset(buf, 0, WW);
        memset(buf + WW, 1, 256 - WW);
        for (ic = 0; ic <= size4; ic += 4)
            if (COND(b, ic)) {
                unsigned const off = (int) (get_be32(b + ic) << 6) >> 6;
                if (size <= (off & (~0u << 2)) + ic) {
                    buf[(~(~0u << W_CTO)) & (off >> (26 - W_CTO))] |= 1;
                    ++wbuf[0xff & (off >> 18)];
                }
            }
        if (getcto(f, buf) < 0) {
#if (W_CTO != 0)
            return -1;
#else
            f->cto = 0;
#endif
        }
    }
    const unsigned char cto8 = f->cto;
#ifdef U
    const unsigned cto = (unsigned) f->cto << (24 + 2 - W_CTO);
#endif
    for (ic = 0; ic <= size4; ic += 4)
        if (COND(b, ic)) {
            unsigned const word = get_be32(b + ic);
            unsigned const off = (int) (word << 6) >> 6;
            unsigned const jc = (off & (~0u << 2)) + ic;
            // try to detect 'real' calls only
            if (jc < size) {
#ifdef U
                set_be32(b + ic, (0xfc000003 & word) | (jc + addvalue + cto));
#endif
                calls++;
                lastcall = ic;
            } else {
#if (W_CTO != 0)
                assert((~(~0u << W_CTO) & (word >> (24 + 2 - W_CTO))) !=
                       (unsigned) cto8); // this should not happen
#endif
                lastnoncall = ic;
                noncalls++;
            }
        }
    f->calls = calls;
    f->noncalls = noncalls;
    f->lastcall = lastcall;
    ACC_UNUSED(lastnoncall);
#if 0 || defined(TESTING)
    printf("\ncalls=%d noncalls=%d text_size=%x calltrickoffset=%x\n",
        calls,noncalls,size,cto8);
#endif
    return 0;
}
References ACC_UNUSED, Filter::addvalue, b, Filter::buf, buf, Filter::buf_len, Filter::calls, COND, Filter::cto, get_be32(), getcto(), Filter::lastcall, memset(), Filter::noncalls, set_be32(), size(), upx::umin(), and W_CTO.