My Project: src/util/raw_bytes.h File Reference
raw_bytes.h File Reference
Functions
template<class T >
std::enable_if< std::is_pointer< T >::value &&!upx::is_bounded_array< T >::value, T >::type raw_bytes (T ptr, size_t size_in_bytes) may_throw
raw_bytes() - get underlying memory from checked buffers/pointers.
template<class T >
std::enable_if< std::is_pointer< T >::value &&!upx::is_bounded_array< T >::value &&!std::is_void< typenamestd::remove_pointer< T >::type >::value, T >::type raw_index_bytes (T ptr, size_t index, size_t size_in_bytes) may_throw
template<class T , size_t N>
T * raw_bytes (T(&array)[N], size_t size_in_bytes) may_throw
template<class T , size_t N>
T * raw_index_bytes (T(&array)[N], size_t index, size_t size_in_bytes) may_throw
Function Documentation
raw_bytes() [1/2]
template<class T > std::enable_if< std::is_pointer< T >::value &&!upx::is_bounded_array< T >::value, T >::type raw_bytes (T ptr, size_t size_in_bytes) inline
raw_bytes() - get underlying memory from checked buffers/pointers.
This is overloaded by various utility classes like MemBuffer and XSpan.
Note that the pointer type is retained, the "_bytes" hints size_in_bytes
Definition at line 40 of file raw_bytes.h.
{
    if (size_in_bytes > 0) {
        if very_unlikely (ptr == nullptr)
            throwCantPack("raw_bytes unexpected NULL ptr");
        if very_unlikely (__acc_cte(VALGRIND_CHECK_MEM_IS_ADDRESSABLE(ptr, size_in_bytes) != 0))
            throwCantPack("raw_bytes valgrind-check-mem");
    }
    return ptr;
}
References __acc_cte, ptr, raw_bytes(), size_in_bytes, throwCantPack(), VALGRIND_CHECK_MEM_IS_ADDRESSABLE, and very_unlikely.
raw_bytes() [2/2]
template<class T , size_t N> T * raw_bytes (T(&) array[N], size_t size_in_bytes) inline
Definition at line 69 of file raw_bytes.h.
{
    typedef T element_type;
    if very_unlikely (size_in_bytes > mem_size(sizeof(element_type), N))
        throwCantPack("raw_bytes out of range");
    return array;
}
References mem_size(), N, raw_bytes(), size_in_bytes, throwCantPack(), and very_unlikely.
raw_index_bytes() [1/2]
template<class T > std::enable_if< std::is_pointer< T >::value &&!upx::is_bounded_array< T >::value &&!std::is_void< typenamestd::remove_pointer< T >::type >::value, T >::type raw_index_bytes (T ptr, size_t index, size_t size_in_bytes) inline
Definition at line 56 of file raw_bytes.h.
{
    typedef typename std::remove_pointer<T>::type element_type;
    if very_unlikely (ptr == nullptr)
        throwCantPack("raw_index_bytes unexpected NULL ptr");
    size_in_bytes = mem_size(sizeof(element_type), index, size_in_bytes); // assert size
    if very_unlikely (__acc_cte(VALGRIND_CHECK_MEM_IS_ADDRESSABLE(ptr, size_in_bytes) != 0))
        throwCantPack("raw_index_bytes valgrind-check-mem");
    UNUSED(size_in_bytes);
    return ptr + index;
}
References __acc_cte, index, mem_size(), ptr, raw_index_bytes(), size_in_bytes, throwCantPack(), UNUSED, VALGRIND_CHECK_MEM_IS_ADDRESSABLE, and very_unlikely.
raw_index_bytes() [2/2]
template<class T , size_t N> T * raw_index_bytes (T(&) array[N], size_t index, size_t size_in_bytes) inline
Definition at line 77 of file raw_bytes.h.
{
    typedef T element_type;
    return raw_bytes(array, mem_size(sizeof(element_type), index, size_in_bytes)) + index;
}
References index, mem_size(), raw_bytes(), raw_index_bytes(), and size_in_bytes.