My Project: src/util/snprintf.h File Reference
snprintf.h File Reference
Macros
#define strlen upx_safe_strlen
#define snprintf upx_safe_snprintf
#define sprintf ERROR_sprintf_IS_DANGEROUS_USE_snprintf
#define vsnprintf upx_safe_vsnprintf
Functions
upx_rsize_t upx_safe_strlen (const char *) may_throw
UPX version of string functions, with assertions and sane limits.
int upx_safe_vsnprintf (char *str, upx_rsize_t max_size, const char *format, va_list ap) may_throw
int upx_safe_snprintf (char *str, upx_rsize_t max_size, const char *format,...) may_throw attribute_format(3
int int upx_safe_vasprintf (char **ptr, const char *format, va_list ap) may_throw
int upx_safe_asprintf (char **ptr, const char *format,...) may_throw attribute_format(2
int char * upx_safe_xprintf (const char *format,...) may_throw attribute_format(1
int char upx_rsize_t upx_safe_strlen_noexcept (const char *) noexcept
int upx_safe_vsnprintf_noexcept (char *str, upx_rsize_t max_size, const char *format, va_list ap) noexcept
forceinline upx_rsize_t upx_safe_strlen (const uchar *s) may_throw
some uchar string support functions to avoid casts
forceinline uchar * strcpy (uchar *s1, const uchar *s2) noexcept
forceinline int strcmp (const uchar *s1, const char *s2) noexcept
forceinline int strcmp (const char *s1, const uchar *s2) noexcept
forceinline int strcmp (const uchar *s1, const uchar *s2) noexcept
forceinline int strcasecmp (const uchar *s1, const char *s2) noexcept
forceinline int strcasecmp (const char *s1, const uchar *s2) noexcept
forceinline int strcasecmp (const uchar *s1, const uchar *s2) noexcept
Macro Definition Documentation
snprintf
#define snprintf upx_safe_snprintf
Definition at line 61 of file snprintf.h.
sprintf
#define sprintf ERROR_sprintf_IS_DANGEROUS_USE_snprintf
Definition at line 62 of file snprintf.h.
strlen
#define strlen upx_safe_strlen
Definition at line 56 of file snprintf.h.
vsnprintf
#define vsnprintf upx_safe_vsnprintf
Definition at line 63 of file snprintf.h.
Function Documentation
strcasecmp() [1/3]
forceinline int strcasecmp (const char * s1, const uchar * s2) noexcept
Definition at line 90 of file snprintf.h.
{
    return strcasecmp(s1, (const char *) s2);
}
References strcasecmp().
strcasecmp() [2/3]
forceinline int strcasecmp (const uchar * s1, const char * s2) noexcept
Definition at line 87 of file snprintf.h.
{
    return strcasecmp((const char *) s1, s2);
}
References strcasecmp().
Referenced by fn_has_ext(), PeFile::processImports0(), PackWinCeArm::processImports2(), and strcasecmp().
strcasecmp() [3/3]
forceinline int strcasecmp (const uchar * s1, const uchar * s2) noexcept
Definition at line 93 of file snprintf.h.
{
    return strcasecmp((const char *) s1, (const char *) s2);
}
References strcasecmp().
strcmp() [1/3]
forceinline int strcmp (const char * s1, const uchar * s2) noexcept
Definition at line 80 of file snprintf.h.
{
    return strcmp(s1, (const char *) s2);
}
References strcmp().
strcmp() [2/3]
forceinline int strcmp (const uchar * s1, const char * s2) noexcept
Definition at line 77 of file snprintf.h.
{
    return strcmp((const char *) s1, s2);
}
References strcmp().
Referenced by ElfLinker::addSection(), PackLinuxElf32::adjABS(), PackLinuxElf64::adjABS(), PackLinuxElf32::calls_crt1(), PackLinuxElf64::calls_crt1(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackLinuxI386::canPack(), PackMachBase< TMachClass >::canPack(), PackVmlinuxBase< TElfClass >::canPack(), PackLinuxElf32::canPackOSABI(), PackMachBase< TMachClass >::canUnpack(), PackVmlinuxBase< TElfClass >::canUnpack(), PeFile::ImportLinker::compare(), anonymous_namespace{help.cpp}::PackerNames::compare_fname(), ElfLinker::defineSymbol(), do_option(), ElfLinker::dumpSymbols(), PackLinuxElf32::elf_find_section_name(), PackLinuxElf64::elf_find_section_name(), PackLinuxElf32::elf_lookup(), PackLinuxElf64::elf_lookup(), ElfLinker::findSection(), ElfLinker::findSymbol(), first_options(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackNetBSDElf32x86::generateElfHdr(), PackMachBase< TMachClass >::get_mod_init_func(), PackVmlinuxBase< TElfClass >::getElfSections(), PackLinuxI386sh::getShellName(), is_envvar_true(), main_get_envoptions(), PackMachBase< TMachClass >::pack1(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackMachBase< TMachClass >::pack4(), ElfLinker::preprocessSymbols(), PeFile::processImports0(), ElfLinker::relocate(), ElfLinkerAMD64::relocate1(), ElfLinkerArm64LE::relocate1(), ElfLinkerArmBE::relocate1(), ElfLinkerArmLE::relocate1(), ElfLinkerM68k::relocate1(), ElfLinkerMipsBE::relocate1(), ElfLinkerMipsLE::relocate1(), ElfLinkerPpc32::relocate1(), ElfLinkerPpc64::relocate1(), ElfLinkerPpc64le::relocate1(), ElfLinkerX86::relocate1(), strcmp(), TEST_CASE(), PackMachBase< TMachClass >::unpack(), upx_compiler_sanity_check(), upx_doctest_check(), upx_ucl_init(), and upx_zlib_init().
strcmp() [3/3]
forceinline int strcmp (const uchar * s1, const uchar * s2) noexcept
Definition at line 83 of file snprintf.h.
{
    return strcmp((const char *) s1, (const char *) s2);
}
References strcmp().
strcpy()
forceinline uchar * strcpy (uchar * s1, const uchar * s2) noexcept
Definition at line 73 of file snprintf.h.
{
    return (uchar *) strcpy((char *) s1, (const char *) s2);
}
References strcpy().
Referenced by PeFile::Export::build(), do_one_file(), init_global_constants(), makebakname(), maketempname(), mkline(), PeFile::pack0(), UiPacker::startCallback(), and strcpy().
upx_safe_asprintf()
int upx_safe_asprintf (char ** ptr, const char * format, ...)
upx_safe_snprintf()
int upx_safe_snprintf (char * str, upx_rsize_t max_size, const char * format, ...)
upx_safe_strlen() [1/2]
upx_rsize_t upx_safe_strlen (const char * s)
UPX version of string functions, with assertions and sane limits.
Definition at line 34 of file snprintf.cpp.
{
#undef strlen
    assert(s != nullptr);
    size_t len = strlen(s);
    assert(len < UPX_RSIZE_MAX_STR);
    return len;
#define strlen upx_safe_strlen
}
References strlen, and UPX_RSIZE_MAX_STR.
Referenced by PeFile::processImports0(), and upx_safe_strlen().
upx_safe_strlen() [2/2]
forceinline upx_rsize_t upx_safe_strlen (const uchar * s)
some uchar string support functions to avoid casts
Definition at line 69 of file snprintf.h.
{
    return upx_safe_strlen((const char *) s);
}
References upx_safe_strlen().
upx_safe_strlen_noexcept()
int char upx_rsize_t upx_safe_strlen_noexcept (const char * s) noexcept
Definition at line 43 of file snprintf.cpp.
{
#undef strlen
    assert_noexcept(s != nullptr);
    size_t len = strlen(s);
    assert_noexcept(len < UPX_RSIZE_MAX_STR);
    return len;
#define strlen upx_safe_strlen
}
References assert_noexcept, strlen, and UPX_RSIZE_MAX_STR.
upx_safe_vasprintf()
int int upx_safe_vasprintf (char ** ptr, const char * format, va_list ap)
Definition at line 119 of file snprintf.cpp.
{
    int len;
    assert(ptr != nullptr);
    *ptr = nullptr;
    va_list ap_copy;
    va_copy(ap_copy, ap);
    len = upx_safe_vsnprintf(nullptr, 0, format, ap_copy);
    va_end(ap_copy);
    if (len >= 0) {
        *ptr = (char *) ::malloc(len + 1);
        assert(*ptr != nullptr);
        if (*ptr == nullptr)
            return -1;
        int len2 = upx_safe_vsnprintf(*ptr, len + 1, format, ap);
        assert(len2 == len);
    }
    return len;
}
References ptr, and upx_safe_vsnprintf().
Referenced by upx_safe_asprintf(), and upx_safe_xprintf().
upx_safe_vsnprintf()
int upx_safe_vsnprintf (char * str, upx_rsize_t max_size, const char * format, va_list ap)
Definition at line 52 of file snprintf.cpp.
{
#undef vsnprintf
    size_t size;
    // preconditions
    assert(max_size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr)
        assert(max_size > 0);
    else
        assert(max_size == 0);
    long long len = vsnprintf(str, max_size, format, ap);
    assert(len >= 0);
    assert(len < UPX_RSIZE_MAX_STR);
    size = (size_t) len + 1;
    // postconditions
    assert(size > 0);
    assert(size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr) {
        assert(size <= max_size);
        assert(str[size - 1] == '\0');
    }
    return ACC_ICONV(int, size - 1); // snprintf() returns length, not size
#define vsnprintf upx_safe_vsnprintf
}
References ACC_ICONV, size(), UPX_RSIZE_MAX_STR, and vsnprintf.
Referenced by info(), infoHeader(), infoWarning(), printErr(), printWarn(), upx_safe_snprintf(), and upx_safe_vasprintf().
upx_safe_vsnprintf_noexcept()
int upx_safe_vsnprintf_noexcept (char * str, upx_rsize_t max_size, const char * format, va_list ap) noexcept
Definition at line 80 of file snprintf.cpp.
{
#undef vsnprintf
    size_t size;
    // preconditions
    assert_noexcept(max_size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr)
        assert_noexcept(max_size > 0);
    else
        assert_noexcept(max_size == 0);
    long long len = vsnprintf(str, max_size, format, ap);
    assert_noexcept(len >= 0);
    assert_noexcept(len < UPX_RSIZE_MAX_STR);
    size = (size_t) len + 1;
    // postconditions
    assert_noexcept(size > 0);
    assert_noexcept(size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr) {
        assert_noexcept(size <= max_size);
        assert_noexcept(str[size - 1] == '\0');
    }
    return ACC_ICONV(int, size - 1); // snprintf() returns length, not size
#define vsnprintf upx_safe_vsnprintf
}
References ACC_ICONV, assert_noexcept, size(), UPX_RSIZE_MAX_STR, and vsnprintf.
Referenced by throwCantPack(), throwCantUnpack(), and throwInternalError().
upx_safe_xprintf()
int char * upx_safe_xprintf (const char * format, ...)