My Project: src/util/snprintf.cpp File Reference
snprintf.cpp File Reference
#include "../conf.h"
Macros
#define strlen upx_safe_strlen
#define strlen upx_safe_strlen
#define vsnprintf upx_safe_vsnprintf
#define vsnprintf upx_safe_vsnprintf
Functions
upx_rsize_t upx_safe_strlen (const char *s)
UPX version of string functions, with assertions and sane limits.
upx_rsize_t upx_safe_strlen_noexcept (const char *s) noexcept
int upx_safe_vsnprintf (char *str, upx_rsize_t max_size, const char *format, va_list ap)
int upx_safe_vsnprintf_noexcept (char *str, upx_rsize_t max_size, const char *format, va_list ap) noexcept
int upx_safe_snprintf (char *str, upx_rsize_t max_size, const char *format,...)
int upx_safe_vasprintf (char **ptr, const char *format, va_list ap)
int upx_safe_asprintf (char **ptr, const char *format,...)
char * upx_safe_xprintf (const char *format,...)
Macro Definition Documentation
strlen [1/2]
#define strlen upx_safe_strlen
strlen [2/2]
#define strlen upx_safe_strlen
vsnprintf [1/2]
#define vsnprintf upx_safe_vsnprintf
vsnprintf [2/2]
#define vsnprintf upx_safe_vsnprintf
Function Documentation
upx_safe_asprintf()
int upx_safe_asprintf (char ** ptr, const char * format, ...)
Definition at line 141 of file snprintf.cpp.
{
    va_list ap;
    int len;
    va_start(ap, format);
    len = upx_safe_vasprintf(ptr, format, ap);
    va_end(ap);
    return len;
}
References ptr, and upx_safe_vasprintf().
upx_safe_snprintf()
int upx_safe_snprintf (char * str, upx_rsize_t max_size, const char * format, ...)
Definition at line 109 of file snprintf.cpp.
{
    va_list ap;
    int len;
    va_start(ap, format);
    len = upx_safe_vsnprintf(str, max_size, format, ap);
    va_end(ap);
    return len;
}
References upx_safe_vsnprintf().
Referenced by PeFile::ImportLinker::add_import(), PeFile::checkHeaderValues(), UiPacker::doCallback(), ElfLinker::dumpSymbol(), ElfLinker::dumpSymbols(), PeFile::ImportLinker::getAddress(), makebakname(), maketempname(), mkline(), PeFile::ImportLinker::name_for_proc(), pr_error(), printErr(), PeFile::processResources(), set_method_name(), UiPacker::startCallback(), MemBuffer::subref_impl(), UiPacker::uiListTotal(), and upx_compiler_sanity_check().
upx_safe_strlen()
upx_rsize_t upx_safe_strlen (const char * s)
UPX version of string functions, with assertions and sane limits.
Definition at line 34 of file snprintf.cpp.
{
#undef strlen
    assert(s != nullptr);
    size_t len = strlen(s);
    assert(len < UPX_RSIZE_MAX_STR);
    return len;
#define strlen upx_safe_strlen
}
References strlen, and UPX_RSIZE_MAX_STR.
Referenced by PeFile::processImports0(), and upx_safe_strlen().
upx_safe_strlen_noexcept()
upx_rsize_t upx_safe_strlen_noexcept (const char * s) noexcept
Definition at line 43 of file snprintf.cpp.
{
#undef strlen
    assert_noexcept(s != nullptr);
    size_t len = strlen(s);
    assert_noexcept(len < UPX_RSIZE_MAX_STR);
    return len;
#define strlen upx_safe_strlen
}
References assert_noexcept, strlen, and UPX_RSIZE_MAX_STR.
upx_safe_vasprintf()
int upx_safe_vasprintf (char ** ptr, const char * format, va_list ap)
Definition at line 119 of file snprintf.cpp.
{
    int len;
    assert(ptr != nullptr);
    *ptr = nullptr;
    va_list ap_copy;
    va_copy(ap_copy, ap);
    len = upx_safe_vsnprintf(nullptr, 0, format, ap_copy);
    va_end(ap_copy);
    if (len >= 0) {
        *ptr = (char *) ::malloc(len + 1);
        assert(*ptr != nullptr);
        if (*ptr == nullptr)
            return -1;
        int len2 = upx_safe_vsnprintf(*ptr, len + 1, format, ap);
        assert(len2 == len);
    }
    return len;
}
References ptr, and upx_safe_vsnprintf().
Referenced by upx_safe_asprintf(), and upx_safe_xprintf().
upx_safe_vsnprintf()
int upx_safe_vsnprintf (char * str, upx_rsize_t max_size, const char * format, va_list ap)
Definition at line 52 of file snprintf.cpp.
{
#undef vsnprintf
    size_t size;
    // preconditions
    assert(max_size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr)
        assert(max_size > 0);
    else
        assert(max_size == 0);
    long long len = vsnprintf(str, max_size, format, ap);
    assert(len >= 0);
    assert(len < UPX_RSIZE_MAX_STR);
    size = (size_t) len + 1;
    // postconditions
    assert(size > 0);
    assert(size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr) {
        assert(size <= max_size);
        assert(str[size - 1] == '\0');
    }
    return ACC_ICONV(int, size - 1); // snprintf() returns length, not size
#define vsnprintf upx_safe_vsnprintf
}
References ACC_ICONV, size(), UPX_RSIZE_MAX_STR, and vsnprintf.
Referenced by info(), infoHeader(), infoWarning(), printErr(), printWarn(), upx_safe_snprintf(), and upx_safe_vasprintf().
upx_safe_vsnprintf_noexcept()
int upx_safe_vsnprintf_noexcept (char * str, upx_rsize_t max_size, const char * format, va_list ap) noexcept
Definition at line 80 of file snprintf.cpp.
{
#undef vsnprintf
    size_t size;
    // preconditions
    assert_noexcept(max_size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr)
        assert_noexcept(max_size > 0);
    else
        assert_noexcept(max_size == 0);
    long long len = vsnprintf(str, max_size, format, ap);
    assert_noexcept(len >= 0);
    assert_noexcept(len < UPX_RSIZE_MAX_STR);
    size = (size_t) len + 1;
    // postconditions
    assert_noexcept(size > 0);
    assert_noexcept(size <= UPX_RSIZE_MAX_STR);
    if (str != nullptr) {
        assert_noexcept(size <= max_size);
        assert_noexcept(str[size - 1] == '\0');
    }
    return ACC_ICONV(int, size - 1); // snprintf() returns length, not size
#define vsnprintf upx_safe_vsnprintf
}
References ACC_ICONV, assert_noexcept, size(), UPX_RSIZE_MAX_STR, and vsnprintf.
Referenced by throwCantPack(), throwCantUnpack(), and throwInternalError().
upx_safe_xprintf()
char * upx_safe_xprintf (const char * format, ...)
Definition at line 151 of file snprintf.cpp.
{
    char *ptr = nullptr;
    va_list ap;
    int len;
    va_start(ap, format);
    len = upx_safe_vasprintf(&ptr, format, ap);
    va_end(ap);
    UNUSED(len);
    assert(ptr != nullptr);
    return ptr;
}
References ptr, UNUSED, and upx_safe_vasprintf().