My Project: upx_callback_t Struct Reference
upx_callback_t Struct Reference final
#include <conf.h>
Public Member Functions
void reset () noexcept
Public Attributes
upx_progress_func_t nprogress
void * user
Detailed Description
Definition at line 645 of file conf.h.
Member Function Documentation
reset()
void upx_callback_t::reset () inline noexcept
Definition at line 649 of file conf.h.
{ mem_clear(this); }
References mem_clear().
Referenced by UiPacker::endCallback(), UiPacker::startCallback(), UiPacker::UiPacker(), and UiPacker::~UiPacker().
Member Data Documentation
nprogress
upx_progress_func_t upx_callback_t::nprogress
Definition at line 646 of file conf.h.
Referenced by MyLzma::ProgressInfo::SetRatioInfo(), UiPacker::startCallback(), upx_ucl_compress(), and wrap_nprogress_ucl().
user
void* upx_callback_t::user
Definition at line 647 of file conf.h.
Referenced by UiPacker::progress_callback(), and UiPacker::startCallback().
The documentation for this struct was generated from the following file:
src/conf.h