My Project: upx_compress_result_t Struct Reference
upx_compress_result_t Struct Reference final
#include <conf.h>
Classes
struct Debug
Public Member Functions
void reset () noexcept
Public Attributes
Debug debug
bzip2_compress_result_t result_bzip2
lzma_compress_result_t result_lzma
ucl_compress_result_t result_ucl
zlib_compress_result_t result_zlib
zstd_compress_result_t result_zstd
Detailed Description
Definition at line 763 of file conf.h.
Member Function Documentation
reset()
void upx_compress_result_t::reset () inline noexcept
Definition at line 778 of file conf.h.
{
        debug.reset();
        result_bzip2.reset();
        result_lzma.reset();
        result_ucl.reset();
        result_zlib.reset();
        result_zstd.reset();
    }
References bzip2_compress_result_t::reset(), lzma_compress_result_t::reset(), ucl_compress_result_t::reset(), zlib_compress_result_t::reset(), zstd_compress_result_t::reset(), and upx_compress_result_t::Debug::reset().
Referenced by PackHeader::reset(), and upx_compress().
Member Data Documentation
debug
Debug upx_compress_result_t::debug
Definition at line 770 of file conf.h.
Referenced by upx_compress(), upx_decompress(), upx_lzma_decompress(), and upx_test_overlap().
result_bzip2
bzip2_compress_result_t upx_compress_result_t::result_bzip2
Definition at line 772 of file conf.h.
result_lzma
lzma_compress_result_t upx_compress_result_t::result_lzma
Definition at line 773 of file conf.h.
Referenced by PackLinuxI386::buildLinuxLoader(), Packer::defineDecompressorSymbols(), Packer::getDecompressorWrkmemSize(), PackBvmlinuzI386::pack(), upx_lzma_compress(), and upx_lzma_decompress().
result_ucl
ucl_compress_result_t upx_compress_result_t::result_ucl
Definition at line 774 of file conf.h.
Referenced by Packer::compress(), and upx_ucl_compress().
result_zlib
zlib_compress_result_t upx_compress_result_t::result_zlib
Definition at line 775 of file conf.h.
Referenced by upx_zlib_compress().
result_zstd
zstd_compress_result_t upx_compress_result_t::result_zstd
Definition at line 776 of file conf.h.
The documentation for this struct was generated from the following file:
src/conf.h