My Project: LE16 Struct Reference
LE16 Struct Reference final
#include <bele.h>
Public Types
typedef unsigned integral_conversion_type
Public Member Functions
forceinline bele_constexpr operator unsigned () const noexcept
forceinline bele_constexpr LE16 & operator= (unsigned v) noexcept
LE16 & operator+= (unsigned v) noexcept
LE16 & operator-= (unsigned v) noexcept
LE16 & operator*= (unsigned v) noexcept
LE16 & operator/= (unsigned v) noexcept
LE16 & operator&= (unsigned v) noexcept
LE16 & operator|= (unsigned v) noexcept
LE16 & operator^= (unsigned v) noexcept
LE16 & operator<<= (unsigned v) noexcept
LE16 & operator>>= (unsigned v) noexcept
bele_constexpr bool operator== (const LE16 &x) const noexcept
bele_constexpr bool operator< (const LE16 &x) const noexcept
Static Public Member Functions
static forceinline constexpr LE16 make (const LE16 &x) noexcept
static forceinline bele_constexpr LE16 make (unsigned v) noexcept
Public Attributes
byte d [2]
Detailed Description
Definition at line 689 of file bele.h.
Member Typedef Documentation
integral_conversion_type
typedef unsigned LE16::integral_conversion_type
Definition at line 690 of file bele.h.
Member Function Documentation
make() [1/2]
static forceinline constexpr LE16 LE16::make (const LE16 & x) inline static constexpr noexcept
Definition at line 693 of file bele.h.
{ return x; }
Referenced by upx_compiler_sanity_check().
make() [2/2]
static forceinline bele_constexpr LE16 LE16::make (unsigned v) inline static noexcept
Definition at line 694 of file bele.h.
{
        LE16 x = {};
        set_le16(x.d, v);
        return x;
    }
References d, and set_le16().
operator unsigned()
forceinline bele_constexpr LE16::operator unsigned () const inline noexcept
Definition at line 700 of file bele.h.
{ return get_le16(d); }
References d, and get_le16().
operator&=()
LE16 & LE16::operator&= (unsigned v) inline noexcept
Definition at line 722 of file bele.h.
{
        set_le16(d, get_le16(d) & v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator*=()
LE16 & LE16::operator*= (unsigned v) inline noexcept
Definition at line 714 of file bele.h.
{
        set_le16(d, get_le16(d) * v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator+=()
LE16 & LE16::operator+= (unsigned v) inline noexcept
Definition at line 706 of file bele.h.
{
        set_le16(d, get_le16(d) + v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator-=()
LE16 & LE16::operator-= (unsigned v) inline noexcept
Definition at line 710 of file bele.h.
{
        set_le16(d, get_le16(d) - v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator/=()
LE16 & LE16::operator/= (unsigned v) inline noexcept
Definition at line 718 of file bele.h.
{
        set_le16(d, get_le16(d) / v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator<()
bele_constexpr bool LE16::operator< (const LE16 & x) const inline noexcept
Definition at line 751 of file bele.h.
{
        return unsigned(*this) < unsigned(x);
    }
operator<<=()
LE16 & LE16::operator<<= (unsigned v) inline noexcept
Definition at line 734 of file bele.h.
{
        set_le16(d, get_le16(d) << v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator=()
forceinline bele_constexpr LE16 & LE16::operator= (unsigned v) inline noexcept
Definition at line 702 of file bele.h.
{
        set_le16(d, v);
        return *this;
    }
References d, and set_le16().
operator==()
bele_constexpr bool LE16::operator== (const LE16 & x) const inline noexcept
Definition at line 743 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
        if (upx_is_constant_evaluated())
            return upx::compile_time::mem_eq(d, x.d, sizeof(d));
        else
#endif
            return upx_memcmp_inline(d, x.d, sizeof(d)) == 0;
    }
References d, upx::compile_time::mem_eq(), and upx_memcmp_inline.
operator>>=()
LE16 & LE16::operator>>= (unsigned v) inline noexcept
Definition at line 738 of file bele.h.
{
        set_le16(d, get_le16(d) >> v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator^=()
LE16 & LE16::operator^= (unsigned v) inline noexcept
Definition at line 730 of file bele.h.
{
        set_le16(d, get_le16(d) ^ v);
        return *this;
    }
References d, get_le16(), and set_le16().
operator|=()
LE16 & LE16::operator|= (unsigned v) inline noexcept
Definition at line 726 of file bele.h.
{
        set_le16(d, get_le16(d) | v);
        return *this;
    }
References d, get_le16(), and set_le16().
Member Data Documentation
d
byte LE16::d[2]
Definition at line 691 of file bele.h.
Referenced by make(), operator unsigned(), operator&=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), and upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/bele.h