My Project: ucl_compress_config_t Struct Reference
ucl_compress_config_t Struct Reference final
#include <conf.h>
Public Member Functions
void reset () noexcept
Detailed Description
Definition at line 682 of file conf.h.
Member Function Documentation
reset()
void ucl_compress_config_t::reset () inline noexcept
Definition at line 683 of file conf.h.
{ memset(this, 0xff, sizeof(*this)); }
References memset().
Referenced by upx_compress_config_t::reset(), and upx_ucl_compress().
The documentation for this struct was generated from the following file:
src/conf.h