My Project: BE32 Struct Reference
BE32 Struct Reference final
#include <bele.h>
Public Types
typedef unsigned integral_conversion_type
Public Member Functions
forceinline bele_constexpr operator unsigned () const noexcept
forceinline bele_constexpr BE32 & operator= (unsigned v) noexcept
BE32 & operator+= (unsigned v) noexcept
BE32 & operator-= (unsigned v) noexcept
BE32 & operator*= (unsigned v) noexcept
BE32 & operator/= (unsigned v) noexcept
BE32 & operator&= (unsigned v) noexcept
BE32 & operator|= (unsigned v) noexcept
BE32 & operator^= (unsigned v) noexcept
BE32 & operator<<= (unsigned v) noexcept
BE32 & operator>>= (unsigned v) noexcept
bele_constexpr bool operator== (const BE32 &x) const noexcept
bele_constexpr bool operator< (const BE32 &x) const noexcept
Static Public Member Functions
static forceinline constexpr BE32 make (const BE32 &x) noexcept
static forceinline bele_constexpr BE32 make (unsigned v) noexcept
Public Attributes
byte d [4]
Detailed Description
Definition at line 555 of file bele.h.
Member Typedef Documentation
integral_conversion_type
typedef unsigned BE32::integral_conversion_type
Definition at line 556 of file bele.h.
Member Function Documentation
make() [1/2]
static forceinline constexpr BE32 BE32::make (const BE32 & x) inline static constexpr noexcept
Definition at line 559 of file bele.h.
{ return x; }
Referenced by upx_compiler_sanity_check().
make() [2/2]
static forceinline bele_constexpr BE32 BE32::make (unsigned v) inline static noexcept
Definition at line 560 of file bele.h.
{
        BE32 x = {};
        set_be32(x.d, v);
        return x;
    }
References d, and set_be32().
operator unsigned()
forceinline bele_constexpr BE32::operator unsigned () const inline noexcept
Definition at line 566 of file bele.h.
{ return get_be32(d); }
References d, and get_be32().
operator&=()
BE32 & BE32::operator&= (unsigned v) inline noexcept
Definition at line 588 of file bele.h.
{
        set_be32(d, get_be32(d) & v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator*=()
BE32 & BE32::operator*= (unsigned v) inline noexcept
Definition at line 580 of file bele.h.
{
        set_be32(d, get_be32(d) * v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator+=()
BE32 & BE32::operator+= (unsigned v) inline noexcept
Definition at line 572 of file bele.h.
{
        set_be32(d, get_be32(d) + v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator-=()
BE32 & BE32::operator-= (unsigned v) inline noexcept
Definition at line 576 of file bele.h.
{
        set_be32(d, get_be32(d) - v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator/=()
BE32 & BE32::operator/= (unsigned v) inline noexcept
Definition at line 584 of file bele.h.
{
        set_be32(d, get_be32(d) / v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator<()
bele_constexpr bool BE32::operator< (const BE32 & x) const inline noexcept
Definition at line 617 of file bele.h.
{
        return unsigned(*this) < unsigned(x);
    }
operator<<=()
BE32 & BE32::operator<<= (unsigned v) inline noexcept
Definition at line 600 of file bele.h.
{
        set_be32(d, get_be32(d) << v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator=()
forceinline bele_constexpr BE32 & BE32::operator= (unsigned v) inline noexcept
Definition at line 568 of file bele.h.
{
        set_be32(d, v);
        return *this;
    }
References d, and set_be32().
operator==()
bele_constexpr bool BE32::operator== (const BE32 & x) const inline noexcept
Definition at line 609 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
        if (upx_is_constant_evaluated())
            return upx::compile_time::mem_eq(d, x.d, sizeof(d));
        else
#endif
            return upx_memcmp_inline(d, x.d, sizeof(d)) == 0;
    }
References d, upx::compile_time::mem_eq(), and upx_memcmp_inline.
operator>>=()
BE32 & BE32::operator>>= (unsigned v) inline noexcept
Definition at line 604 of file bele.h.
{
        set_be32(d, get_be32(d) >> v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator^=()
BE32 & BE32::operator^= (unsigned v) inline noexcept
Definition at line 596 of file bele.h.
{
        set_be32(d, get_be32(d) ^ v);
        return *this;
    }
References d, get_be32(), and set_be32().
operator|=()
BE32 & BE32::operator|= (unsigned v) inline noexcept
Definition at line 592 of file bele.h.
{
        set_be32(d, get_be32(d) | v);
        return *this;
    }
References d, get_be32(), and set_be32().
Member Data Documentation
d
byte BE32::d[4]
Definition at line 557 of file bele.h.
Referenced by make(), operator unsigned(), operator&=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), and upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/bele.h