My Project: upx_compress_config_t Struct Reference
upx_compress_config_t Struct Reference final
#include <conf.h>
Public Member Functions
void reset () noexcept
Public Attributes
bzip2_compress_config_t conf_bzip2
lzma_compress_config_t conf_lzma
ucl_compress_config_t conf_ucl
zlib_compress_config_t conf_zlib
zstd_compress_config_t conf_zstd
Detailed Description
Definition at line 704 of file conf.h.
Member Function Documentation
reset()
void upx_compress_config_t::reset () inline noexcept
Definition at line 711 of file conf.h.
{
        conf_bzip2.reset();
        conf_lzma.reset();
        conf_ucl.reset();
        conf_zlib.reset();
        conf_zstd.reset();
    }
References bzip2_compress_config_t::reset(), lzma_compress_config_t::reset(), ucl_compress_config_t::reset(), zlib_compress_config_t::reset(), and zstd_compress_config_t::reset().
Referenced by PackWinCeArm::callCompressWithFilters(), Packer::compress(), PackWcle::encodeImage(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuxBase< TElfClass >::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), and PackVmlinuzARMEL::pack().
Member Data Documentation
conf_bzip2
bzip2_compress_config_t upx_compress_config_t::conf_bzip2
Definition at line 705 of file conf.h.
conf_lzma
lzma_compress_config_t upx_compress_config_t::conf_lzma
Definition at line 706 of file conf.h.
Referenced by PackWinCeArm::callCompressWithFilters(), Packer::compress(), PackWcle::encodeImage(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuxBase< TElfClass >::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), and upx_lzma_compress().
conf_ucl
ucl_compress_config_t upx_compress_config_t::conf_ucl
Definition at line 707 of file conf.h.
Referenced by Packer::compress(), PackExe::pack(), PackPs1::pack(), PackTos::pack(), and upx_ucl_compress().
conf_zlib
zlib_compress_config_t upx_compress_config_t::conf_zlib
Definition at line 708 of file conf.h.
Referenced by Packer::compress(), and upx_zlib_compress().
conf_zstd
zstd_compress_config_t upx_compress_config_t::conf_zstd
Definition at line 709 of file conf.h.
The documentation for this struct was generated from the following file:
src/conf.h