My Project: upx::MallocDeleter< T > Struct Template Reference
upx::MallocDeleter< T > Struct Template Reference final
#include <cxxlib.h>
Public Member Functions
MallocDeleter (T **p, std::size_t n) noexcept
~MallocDeleter () noexcept
void delete_items () noexcept
Public Attributes
T ** items
std::size_t count
Detailed Description
template<class T>
struct upx::MallocDeleter< T >
Definition at line 368 of file cxxlib.h.
Constructor & Destructor Documentation
MallocDeleter()
template<class T > upx::MallocDeleter< T >::MallocDeleter (T ** p, std::size_t n) inline explicit noexcept
Definition at line 371 of file cxxlib.h.
: items(p), count(n) {}
~MallocDeleter()
template<class T > upx::MallocDeleter< T >::~MallocDeleter () inline noexcept
Definition at line 372 of file cxxlib.h.
{ delete_items(); }
References upx::MallocDeleter< T >::delete_items().
Member Function Documentation
delete_items()
template<class T > void upx::MallocDeleter< T >::delete_items () inline noexcept
Definition at line 373 of file cxxlib.h.
{
        for (std::size_t i = 0; i < count; i++) {
            T *item = atomic_exchange(&items[i], (T *) nullptr);
            ::free(item); // free memory from malloc()
        }
    }
References upx::atomic_exchange(), upx::MallocDeleter< T >::count, and upx::MallocDeleter< T >::items.
Referenced by upx::MallocDeleter< T >::~MallocDeleter().
Member Data Documentation
count
template<class T > std::size_t upx::MallocDeleter< T >::count
Definition at line 370 of file cxxlib.h.
Referenced by upx::MallocDeleter< T >::delete_items().
items
template<class T > T** upx::MallocDeleter< T >::items
Definition at line 369 of file cxxlib.h.
Referenced by upx::MallocDeleter< T >::delete_items().
The documentation for this struct was generated from the following file:
src/util/cxxlib.h