My Project: LE32 Struct Reference
LE32 Struct Reference final
#include <bele.h>
Public Types
typedef unsigned integral_conversion_type
Public Member Functions
forceinline bele_constexpr operator unsigned () const noexcept
forceinline bele_constexpr LE32 & operator= (unsigned v) noexcept
LE32 & operator+= (unsigned v) noexcept
LE32 & operator-= (unsigned v) noexcept
LE32 & operator*= (unsigned v) noexcept
LE32 & operator/= (unsigned v) noexcept
LE32 & operator&= (unsigned v) noexcept
LE32 & operator|= (unsigned v) noexcept
LE32 & operator^= (unsigned v) noexcept
LE32 & operator<<= (unsigned v) noexcept
LE32 & operator>>= (unsigned v) noexcept
bele_constexpr bool operator== (const LE32 &x) const noexcept
bele_constexpr bool operator< (const LE32 &x) const noexcept
Static Public Member Functions
static forceinline constexpr LE32 make (const LE32 &x) noexcept
static forceinline bele_constexpr LE32 make (unsigned v) noexcept
Public Attributes
byte d [4]
Detailed Description
Definition at line 756 of file bele.h.
Member Typedef Documentation
integral_conversion_type
typedef unsigned LE32::integral_conversion_type
Definition at line 757 of file bele.h.
Member Function Documentation
make() [1/2]
static forceinline constexpr LE32 LE32::make (const LE32 & x) inline static constexpr noexcept
Definition at line 760 of file bele.h.
{ return x; }
Referenced by upx_compiler_sanity_check().
make() [2/2]
static forceinline bele_constexpr LE32 LE32::make (unsigned v) inline static noexcept
Definition at line 761 of file bele.h.
{
        LE32 x = {};
        set_le32(x.d, v);
        return x;
    }
References d, and set_le32().
operator unsigned()
forceinline bele_constexpr LE32::operator unsigned () const inline noexcept
Definition at line 767 of file bele.h.
{ return get_le32(d); }
References d, and get_le32().
operator&=()
LE32 & LE32::operator&= (unsigned v) inline noexcept
Definition at line 789 of file bele.h.
{
        set_le32(d, get_le32(d) & v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator*=()
LE32 & LE32::operator*= (unsigned v) inline noexcept
Definition at line 781 of file bele.h.
{
        set_le32(d, get_le32(d) * v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator+=()
LE32 & LE32::operator+= (unsigned v) inline noexcept
Definition at line 773 of file bele.h.
{
        set_le32(d, get_le32(d) + v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator-=()
LE32 & LE32::operator-= (unsigned v) inline noexcept
Definition at line 777 of file bele.h.
{
        set_le32(d, get_le32(d) - v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator/=()
LE32 & LE32::operator/= (unsigned v) inline noexcept
Definition at line 785 of file bele.h.
{
        set_le32(d, get_le32(d) / v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator<()
bele_constexpr bool LE32::operator< (const LE32 & x) const inline noexcept
Definition at line 818 of file bele.h.
{
        return unsigned(*this) < unsigned(x);
    }
operator<<=()
LE32 & LE32::operator<<= (unsigned v) inline noexcept
Definition at line 801 of file bele.h.
{
        set_le32(d, get_le32(d) << v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator=()
forceinline bele_constexpr LE32 & LE32::operator= (unsigned v) inline noexcept
Definition at line 769 of file bele.h.
{
        set_le32(d, v);
        return *this;
    }
References d, and set_le32().
operator==()
bele_constexpr bool LE32::operator== (const LE32 & x) const inline noexcept
Definition at line 810 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
        if (upx_is_constant_evaluated())
            return upx::compile_time::mem_eq(d, x.d, sizeof(d));
        else
#endif
            return upx_memcmp_inline(d, x.d, sizeof(d)) == 0;
    }
References d, upx::compile_time::mem_eq(), and upx_memcmp_inline.
operator>>=()
LE32 & LE32::operator>>= (unsigned v) inline noexcept
Definition at line 805 of file bele.h.
{
        set_le32(d, get_le32(d) >> v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator^=()
LE32 & LE32::operator^= (unsigned v) inline noexcept
Definition at line 797 of file bele.h.
{
        set_le32(d, get_le32(d) ^ v);
        return *this;
    }
References d, get_le32(), and set_le32().
operator|=()
LE32 & LE32::operator|= (unsigned v) inline noexcept
Definition at line 793 of file bele.h.
{
        set_le32(d, get_le32(d) | v);
        return *this;
    }
References d, get_le32(), and set_le32().
Member Data Documentation
d
byte LE32::d[4]
Definition at line 758 of file bele.h.
Referenced by make(), operator unsigned(), operator&=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), and upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/bele.h