My Project: anonymous_namespace{dt_check.cpp}::TestBELE< T > Struct Template Reference
anonymous_namespace{dt_check.cpp}::TestBELE< T > Struct Template Reference
Static Public Member Functions
static noinline bool test (void) noexcept
Detailed Description
template<class T>
struct anonymous_namespace{dt_check.cpp}::TestBELE< T >
Definition at line 498 of file dt_check.cpp.
Member Function Documentation
test()
template<class T > static noinline bool anonymous_namespace{dt_check.cpp}::TestBELE< T >::test (void) inline static noexcept
Definition at line 499 of file dt_check.cpp.
{
        static_assert(upx::is_same_any_v<T, BE16, BE32, BE64, LE16, LE32, LE64>);
        static_assert(
            upx::is_same_any_v<typename T::integral_conversion_type, upx_uint32_t, upx_uint64_t>);
        CheckIntegral<T>::check();
        CheckAlignment<T>::check();
        // arithmetic checks
        {
            T all_bits = {}; // == zero
            assert_noexcept(all_bits == 0);
            assert_noexcept(!upx::has_single_bit(all_bits));
            all_bits += 1;
            assert_noexcept(upx::has_single_bit(all_bits));
            all_bits -= 2;
            assert_noexcept(!upx::has_single_bit(all_bits));
            T v1;
            v1 = 1;
            v1 *= 4;
            v1 /= 2;
            v1 -= 1;
            T v2;
            v2 = 1;
            assert_noexcept((v1 == v2));
            assert_noexcept(!(v1 != v2));
            assert_noexcept((v1 <= v2));
            assert_noexcept((v1 >= v2));
            assert_noexcept(!(v1 < v2));
            assert_noexcept(!(v1 > v2));
            v2 ^= all_bits;
            assert_noexcept(!(v1 == v2));
            assert_noexcept((v1 != v2));
            assert_noexcept((v1 <= v2));
            assert_noexcept(!(v1 >= v2));
            assert_noexcept((v1 < v2));
            assert_noexcept(!(v1 > v2));
            v2 += 2;
            assert_noexcept(v1 == 1);
            assert_noexcept(v2 == 0);
            v1 <<= 1;
            v1 |= v2;
            v1 >>= 1;
            v2 &= v1;
            v2 /= v1;
            v2 *= v1;
            v1 += v2;
            v1 -= v2;
            assert_noexcept(v1 == 1);
            assert_noexcept(v2 == 0);
            if ((v1 ^ v2) != 1)
                return false;
        }
        // min/max
        {
            constexpr T a = {}; // == zero
            typedef typename T::integral_conversion_type U;
            constexpr U b = 1;
            assert_noexcept(upx::min(a, a) == 0);
            assert_noexcept(upx::min(a, a) == a);
            assert_noexcept(upx::min(a, b) == 0);
            assert_noexcept(upx::min(a, b) == a);
            assert_noexcept(upx::min(b, a) == 0);
            assert_noexcept(upx::min(b, a) == a);
            assert_noexcept(upx::min(b, b) == 1);
            assert_noexcept(upx::min(b, b) == b);
            assert_noexcept(upx::max(a, a) == 0);
            assert_noexcept(upx::max(a, a) == a);
            assert_noexcept(upx::max(a, b) == 1);
            assert_noexcept(upx::max(a, b) == b);
            assert_noexcept(upx::max(b, a) == 1);
            assert_noexcept(upx::max(b, a) == b);
            assert_noexcept(upx::max(b, b) == 1);
            assert_noexcept(upx::max(b, b) == b);
            T minus_one_t = {}, minus_two_t = {};
            minus_one_t -= 1;
            minus_two_t -= 2;
            const U minus_one_u = minus_one_t;
            const U minus_two_u = minus_two_t;
            assert_noexcept(upx::min(minus_one_t, minus_one_t) == minus_one_t);
            assert_noexcept(upx::min(minus_one_t, minus_one_t) == minus_one_u);
            assert_noexcept(upx::min(minus_one_u, minus_one_t) == minus_one_t);
            assert_noexcept(upx::min(minus_one_u, minus_one_t) == minus_one_u);
            assert_noexcept(upx::min(minus_one_t, minus_one_u) == minus_one_t);
            assert_noexcept(upx::min(minus_one_t, minus_one_u) == minus_one_u);
            assert_noexcept(upx::min(minus_two_t, minus_one_t) == minus_two_t);
            assert_noexcept(upx::min(minus_two_t, minus_one_t) == minus_two_u);
            assert_noexcept(upx::min(minus_two_u, minus_one_t) == minus_two_t);
            assert_noexcept(upx::min(minus_two_u, minus_one_t) == minus_two_u);
            assert_noexcept(upx::min(minus_two_t, minus_one_u) == minus_two_t);
            assert_noexcept(upx::min(minus_two_t, minus_one_u) == minus_two_u);
            assert_noexcept(upx::min(minus_one_t, minus_two_t) == minus_two_t);
            assert_noexcept(upx::min(minus_one_t, minus_two_t) == minus_two_u);
            assert_noexcept(upx::min(minus_one_u, minus_two_t) == minus_two_t);
            assert_noexcept(upx::min(minus_one_u, minus_two_t) == minus_two_u);
            assert_noexcept(upx::min(minus_one_t, minus_two_u) == minus_two_t);
            assert_noexcept(upx::min(minus_one_t, minus_two_u) == minus_two_u);
            assert_noexcept(upx::max(minus_one_t, minus_one_t) == minus_one_t);
            assert_noexcept(upx::max(minus_one_t, minus_one_t) == minus_one_u);
            assert_noexcept(upx::max(minus_one_u, minus_one_t) == minus_one_t);
            assert_noexcept(upx::max(minus_one_u, minus_one_t) == minus_one_u);
            assert_noexcept(upx::max(minus_one_t, minus_one_u) == minus_one_t);
            assert_noexcept(upx::max(minus_one_t, minus_one_u) == minus_one_u);
            assert_noexcept(upx::max(minus_two_t, minus_one_t) == minus_one_t);
            assert_noexcept(upx::max(minus_two_t, minus_one_t) == minus_one_u);
            assert_noexcept(upx::max(minus_two_u, minus_one_t) == minus_one_t);
            assert_noexcept(upx::max(minus_two_u, minus_one_t) == minus_one_u);
            assert_noexcept(upx::max(minus_two_t, minus_one_u) == minus_one_t);
            assert_noexcept(upx::max(minus_two_t, minus_one_u) == minus_one_u);
            assert_noexcept(upx::max(minus_one_t, minus_two_t) == minus_one_t);
            assert_noexcept(upx::max(minus_one_t, minus_two_t) == minus_one_u);
            assert_noexcept(upx::max(minus_one_u, minus_two_t) == minus_one_t);
            assert_noexcept(upx::max(minus_one_u, minus_two_t) == minus_one_u);
            assert_noexcept(upx::max(minus_one_t, minus_two_u) == minus_one_t);
            assert_noexcept(upx::max(minus_one_t, minus_two_u) == minus_one_u);
        }
        // constexpr
        {
            constexpr T zero = {};
            constexpr T zero_copy = T::make(zero);
            assert_noexcept(zero_copy == 0);
            assert_noexcept(!upx::has_single_bit(zero));
#if defined(upx_is_constant_evaluated)
            static_assert(zero_copy == 0);
            static_assert(zero_copy == zero);
            static_assert(!upx::has_single_bit(zero));
            static_assert(!upx::has_single_bit(zero_copy));
#endif
        }
#if defined(upx_is_constant_evaluated)
        {
            typedef typename T::integral_conversion_type U;
            constexpr T one = T::make(1);
            static_assert(one == 1);
            static_assert(upx::has_single_bit(one));
            constexpr T four = T::make(one + 3);
            static_assert(four == 4);
            static_assert(upx::has_single_bit(four));
            constexpr U all_bits_u = (U) T::make(U(0) - U(1));
            constexpr T all_bits = T::make(all_bits_u);
            static_assert(all_bits == all_bits_u);
            static_assert(all_bits == T::make(one - 2));
            static_assert(!upx::has_single_bit(all_bits));
            static_assert(one == one);
            static_assert(!(one == four));
            static_assert(!(one == all_bits));
            static_assert(one < four);
            static_assert(one < all_bits);
            static_assert(upx::min(one, four) == 1);
            static_assert(upx::min(one, four) == one);
            static_assert(upx::min(U(1), four) == 1);
            static_assert(upx::min(one, U(4)) == 1);
            static_assert(upx::max(one, four) == 4);
            static_assert(upx::max(one, four) == four);
            static_assert(upx::max(U(1), four) == 4);
            static_assert(upx::max(one, U(4)) == 4);
            static_assert(upx::align_down(one, four) == 0);
            static_assert(upx::align_up(one, four) == 4);
            static_assert(upx::align_up(one, four) == four);
            static_assert(upx::align_up_gap(one, four) == 3);
            static_assert(upx::align_up_gap(one, four) == T::make(four - 1));
            static_assert(upx::align_up_gap(one, four) == T::make(four - one));
            static_assert(upx::align_up_gap(one, four) == T::make(four + one - one - one));
            static_assert(upx::align_up_gap(one, four) == T::make(four + one - 2 * one));
            static_assert(upx::align_down_gap(T::make(4), four) == 0);
            static_assert(upx::align_down_gap(T::make(5), four) == 1);
            static_assert(upx::align_down_gap(T::make(6), four) == 2);
            static_assert(upx::align_down_gap(T::make(7), four) == 3);
            static_assert(upx::align_down_gap(T::make(8), four) == 0);
            constexpr T one_copy = T::make(one);
            static_assert(one_copy == one);
            static_assert(one_copy == 1);
        }
#endif
        return true;
    }
References upx::align_down(), upx::align_down_gap(), upx::align_up(), upx::align_up_gap(), assert_noexcept, b, upx::has_single_bit(), upx::max(), upx::min(), and U.
Referenced by upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/check/dt_check.cpp