My Project: MyLzma::InStream Struct Reference
MyLzma::InStream Struct Reference final
Public Member Functions
virtual ~InStream ()
void Init (const Byte *data, size_t size)
STDMETHOD() Read (void *data, UInt32 size, UInt32 *processedSize) override
Public Attributes
MY_UNKNOWN_IMP const Byte * b_buf = nullptr
size_t b_size
size_t b_pos
Detailed Description
Definition at line 198 of file compress_lzma.cpp.
Constructor & Destructor Documentation
~InStream()
virtual MyLzma::InStream::~InStream () inline virtual
Definition at line 199 of file compress_lzma.cpp.
{}
Member Function Documentation
Init()
void MyLzma::InStream::Init (const Byte * data, size_t size) inline
Definition at line 204 of file compress_lzma.cpp.
{
        b_buf = data;
        b_size = size;
        b_pos = 0;
    }
References b_buf, b_pos, b_size, data(), and size().
Referenced by upx_lzma_compress().
Read()
STDMETHODIMP MyLzma::InStream::Read (void * data, UInt32 size, UInt32 * processedSize) override
Definition at line 212 of file compress_lzma.cpp.
{
    size_t remain = b_size - b_pos;
    if (size > remain)
        size = (UInt32) remain;
    memmove(data, b_buf + b_pos, size);
    b_pos += size;
    if (processedSize != nullptr)
        *processedSize = size;
    return S_OK;
}
References b_buf, b_pos, b_size, data(), memmove(), and size().
Member Data Documentation
b_buf
MY_UNKNOWN_IMP const Byte* MyLzma::InStream::b_buf = nullptr
Definition at line 201 of file compress_lzma.cpp.
Referenced by Init(), and Read().
b_pos
size_t MyLzma::InStream::b_pos
Definition at line 203 of file compress_lzma.cpp.
Referenced by Init(), Read(), and upx_lzma_compress().
b_size
size_t MyLzma::InStream::b_size
Definition at line 202 of file compress_lzma.cpp.
Referenced by Init(), and Read().
The documentation for this struct was generated from the following file:
src/compress/compress_lzma.cpp