My Project: LE64 Struct Reference
LE64 Struct Reference final
#include <bele.h>
Public Types
typedef upx_uint64_t integral_conversion_type
Public Member Functions
forceinline bele_constexpr operator upx_uint64_t () const noexcept
forceinline bele_constexpr LE64 & operator= (upx_uint64_t v) noexcept
LE64 & operator+= (upx_uint64_t v) noexcept
LE64 & operator-= (upx_uint64_t v) noexcept
LE64 & operator*= (upx_uint64_t v) noexcept
LE64 & operator/= (upx_uint64_t v) noexcept
LE64 & operator&= (upx_uint64_t v) noexcept
LE64 & operator|= (upx_uint64_t v) noexcept
LE64 & operator^= (upx_uint64_t v) noexcept
LE64 & operator<<= (unsigned v) noexcept
LE64 & operator>>= (unsigned v) noexcept
bele_constexpr bool operator== (const LE64 &x) const noexcept
bele_constexpr bool operator< (const LE64 &x) const noexcept
Static Public Member Functions
static forceinline constexpr LE64 make (const LE64 &x) noexcept
static forceinline bele_constexpr LE64 make (upx_uint64_t v) noexcept
Public Attributes
byte d [8]
Detailed Description
Definition at line 823 of file bele.h.
Member Typedef Documentation
integral_conversion_type
typedef upx_uint64_t LE64::integral_conversion_type
Definition at line 824 of file bele.h.
Member Function Documentation
make() [1/2]
static forceinline constexpr LE64 LE64::make (const LE64 & x) inline static constexpr noexcept
Definition at line 827 of file bele.h.
{ return x; }
Referenced by upx_compiler_sanity_check().
make() [2/2]
static forceinline bele_constexpr LE64 LE64::make (upx_uint64_t v) inline static noexcept
Definition at line 828 of file bele.h.
{
        LE64 x = {};
        set_le64(x.d, v);
        return x;
    }
References d, and set_le64().
operator upx_uint64_t()
forceinline bele_constexpr LE64::operator upx_uint64_t () const inline noexcept
Definition at line 834 of file bele.h.
{ return get_le64(d); }
References d, and get_le64().
operator&=()
LE64 & LE64::operator&= (upx_uint64_t v) inline noexcept
Definition at line 856 of file bele.h.
{
        set_le64(d, get_le64(d) & v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator*=()
LE64 & LE64::operator*= (upx_uint64_t v) inline noexcept
Definition at line 848 of file bele.h.
{
        set_le64(d, get_le64(d) * v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator+=()
LE64 & LE64::operator+= (upx_uint64_t v) inline noexcept
Definition at line 840 of file bele.h.
{
        set_le64(d, get_le64(d) + v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator-=()
LE64 & LE64::operator-= (upx_uint64_t v) inline noexcept
Definition at line 844 of file bele.h.
{
        set_le64(d, get_le64(d) - v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator/=()
LE64 & LE64::operator/= (upx_uint64_t v) inline noexcept
Definition at line 852 of file bele.h.
{
        set_le64(d, get_le64(d) / v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator<()
bele_constexpr bool LE64::operator< (const LE64 & x) const inline noexcept
Definition at line 885 of file bele.h.
{
        return upx_uint64_t(*this) < upx_uint64_t(x);
    }
operator<<=()
LE64 & LE64::operator<<= (unsigned v) inline noexcept
Definition at line 868 of file bele.h.
{
        set_le64(d, get_le64(d) << v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator=()
forceinline bele_constexpr LE64 & LE64::operator= (upx_uint64_t v) inline noexcept
Definition at line 836 of file bele.h.
{
        set_le64(d, v);
        return *this;
    }
References d, and set_le64().
operator==()
bele_constexpr bool LE64::operator== (const LE64 & x) const inline noexcept
Definition at line 877 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
        if (upx_is_constant_evaluated())
            return upx::compile_time::mem_eq(d, x.d, sizeof(d));
        else
#endif
            return upx_memcmp_inline(d, x.d, sizeof(d)) == 0;
    }
References d, upx::compile_time::mem_eq(), and upx_memcmp_inline.
operator>>=()
LE64 & LE64::operator>>= (unsigned v) inline noexcept
Definition at line 872 of file bele.h.
{
        set_le64(d, get_le64(d) >> v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator^=()
LE64 & LE64::operator^= (upx_uint64_t v) inline noexcept
Definition at line 864 of file bele.h.
{
        set_le64(d, get_le64(d) ^ v);
        return *this;
    }
References d, get_le64(), and set_le64().
operator|=()
LE64 & LE64::operator|= (upx_uint64_t v) inline noexcept
Definition at line 860 of file bele.h.
{
        set_le64(d, get_le64(d) | v);
        return *this;
    }
References d, get_le64(), and set_le64().
Member Data Documentation
d
byte LE64::d[8]
Definition at line 825 of file bele.h.
Referenced by make(), operator upx_uint64_t(), operator&=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), and upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/bele.h