My Project: anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T > Struct Template Reference
anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T > Struct Template Reference
Static Public Member Functions
static bool inc_gt (const T x) noexcept
static bool dec_lt (const T x) noexcept
static bool neg_eq (const T x) noexcept
Detailed Description
template<class T>
struct anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >
Definition at line 731 of file dt_check.cpp.
Member Function Documentation
dec_lt()
template<class T > static bool anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::dec_lt (const T x) inline static noexcept
Definition at line 733 of file dt_check.cpp.
{ return x - 1 < x; }
Referenced by upx_compiler_sanity_check().
inc_gt()
template<class T > static bool anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::inc_gt (const T x) inline static noexcept
Definition at line 732 of file dt_check.cpp.
{ return x + 1 > x; }
Referenced by upx_compiler_sanity_check().
neg_eq()
template<class T > static bool anonymous_namespace{dt_check.cpp}::TestIntegerWrap< T >::neg_eq (const T x) inline static noexcept
Definition at line 734 of file dt_check.cpp.
{ return T(T(0) - x) == x; }
Referenced by upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/check/dt_check.cpp