My Project: upx::ObjectDeleter< T > Struct Template Reference
upx::ObjectDeleter< T > Struct Template Reference final
#include <cxxlib.h>
Public Member Functions
ObjectDeleter (T **p, std::size_t n) noexcept
~ObjectDeleter () noexcept
void delete_items () noexcept
Public Attributes
T ** items
std::size_t count
Detailed Description
template<class T>
struct upx::ObjectDeleter< T >
Definition at line 342 of file cxxlib.h.
Constructor & Destructor Documentation
ObjectDeleter()
template<class T > upx::ObjectDeleter< T >::ObjectDeleter (T ** p, std::size_t n) inline explicit noexcept
Definition at line 345 of file cxxlib.h.
: items(p), count(n) {}
~ObjectDeleter()
template<class T > upx::ObjectDeleter< T >::~ObjectDeleter () inline noexcept
Definition at line 346 of file cxxlib.h.
{ delete_items(); }
References upx::ObjectDeleter< T >::delete_items().
Member Function Documentation
delete_items()
template<class T > void upx::ObjectDeleter< T >::delete_items () inline noexcept
Definition at line 347 of file cxxlib.h.
{
        for (std::size_t i = 0; i < count; i++) {
            T *item = atomic_exchange(&items[i], (T *) nullptr);
            delete item; // single object delete
        }
    }
References upx::atomic_exchange(), upx::ObjectDeleter< T >::count, and upx::ObjectDeleter< T >::items.
Referenced by upx::ObjectDeleter< T >::~ObjectDeleter().
Member Data Documentation
count
template<class T > std::size_t upx::ObjectDeleter< T >::count
Definition at line 344 of file cxxlib.h.
Referenced by upx::ObjectDeleter< T >::delete_items().
items
template<class T > T** upx::ObjectDeleter< T >::items
Definition at line 343 of file cxxlib.h.
Referenced by upx::ObjectDeleter< T >::delete_items().
The documentation for this struct was generated from the following file:
src/util/cxxlib.h