My Project: BE64 Struct Reference
BE64 Struct Reference final
#include <bele.h>
Public Types
typedef upx_uint64_t integral_conversion_type
Public Member Functions
forceinline bele_constexpr operator upx_uint64_t () const noexcept
forceinline bele_constexpr BE64 & operator= (upx_uint64_t v) noexcept
BE64 & operator+= (upx_uint64_t v) noexcept
BE64 & operator-= (upx_uint64_t v) noexcept
BE64 & operator*= (upx_uint64_t v) noexcept
BE64 & operator/= (upx_uint64_t v) noexcept
BE64 & operator&= (upx_uint64_t v) noexcept
BE64 & operator|= (upx_uint64_t v) noexcept
BE64 & operator^= (upx_uint64_t v) noexcept
BE64 & operator<<= (unsigned v) noexcept
BE64 & operator>>= (unsigned v) noexcept
bele_constexpr bool operator== (const BE64 &x) const noexcept
bele_constexpr bool operator< (const BE64 &x) const noexcept
Static Public Member Functions
static forceinline constexpr BE64 make (const BE64 &x) noexcept
static forceinline bele_constexpr BE64 make (upx_uint64_t v) noexcept
Public Attributes
byte d [8]
Detailed Description
Definition at line 622 of file bele.h.
Member Typedef Documentation
integral_conversion_type
typedef upx_uint64_t BE64::integral_conversion_type
Definition at line 623 of file bele.h.
Member Function Documentation
make() [1/2]
static forceinline constexpr BE64 BE64::make (const BE64 & x) inline static constexpr noexcept
Definition at line 626 of file bele.h.
{ return x; }
Referenced by upx_compiler_sanity_check().
make() [2/2]
static forceinline bele_constexpr BE64 BE64::make (upx_uint64_t v) inline static noexcept
Definition at line 627 of file bele.h.
{
        BE64 x = {};
        set_be64(x.d, v);
        return x;
    }
References d, and set_be64().
operator upx_uint64_t()
forceinline bele_constexpr BE64::operator upx_uint64_t () const inline noexcept
Definition at line 633 of file bele.h.
{ return get_be64(d); }
References d, and get_be64().
operator&=()
BE64 & BE64::operator&= (upx_uint64_t v) inline noexcept
Definition at line 655 of file bele.h.
{
        set_be64(d, get_be64(d) & v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator*=()
BE64 & BE64::operator*= (upx_uint64_t v) inline noexcept
Definition at line 647 of file bele.h.
{
        set_be64(d, get_be64(d) * v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator+=()
BE64 & BE64::operator+= (upx_uint64_t v) inline noexcept
Definition at line 639 of file bele.h.
{
        set_be64(d, get_be64(d) + v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator-=()
BE64 & BE64::operator-= (upx_uint64_t v) inline noexcept
Definition at line 643 of file bele.h.
{
        set_be64(d, get_be64(d) - v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator/=()
BE64 & BE64::operator/= (upx_uint64_t v) inline noexcept
Definition at line 651 of file bele.h.
{
        set_be64(d, get_be64(d) / v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator<()
bele_constexpr bool BE64::operator< (const BE64 & x) const inline noexcept
Definition at line 684 of file bele.h.
{
        return upx_uint64_t(*this) < upx_uint64_t(x);
    }
operator<<=()
BE64 & BE64::operator<<= (unsigned v) inline noexcept
Definition at line 667 of file bele.h.
{
        set_be64(d, get_be64(d) << v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator=()
forceinline bele_constexpr BE64 & BE64::operator= (upx_uint64_t v) inline noexcept
Definition at line 635 of file bele.h.
{
        set_be64(d, v);
        return *this;
    }
References d, and set_be64().
operator==()
bele_constexpr bool BE64::operator== (const BE64 & x) const inline noexcept
Definition at line 676 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
        if (upx_is_constant_evaluated())
            return upx::compile_time::mem_eq(d, x.d, sizeof(d));
        else
#endif
            return upx_memcmp_inline(d, x.d, sizeof(d)) == 0;
    }
References d, upx::compile_time::mem_eq(), and upx_memcmp_inline.
operator>>=()
BE64 & BE64::operator>>= (unsigned v) inline noexcept
Definition at line 671 of file bele.h.
{
        set_be64(d, get_be64(d) >> v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator^=()
BE64 & BE64::operator^= (upx_uint64_t v) inline noexcept
Definition at line 663 of file bele.h.
{
        set_be64(d, get_be64(d) ^ v);
        return *this;
    }
References d, get_be64(), and set_be64().
operator|=()
BE64 & BE64::operator|= (upx_uint64_t v) inline noexcept
Definition at line 659 of file bele.h.
{
        set_be64(d, get_be64(d) | v);
        return *this;
    }
References d, get_be64(), and set_be64().
Member Data Documentation
d
byte BE64::d[8]
Definition at line 624 of file bele.h.
Referenced by make(), operator upx_uint64_t(), operator&=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), and upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/bele.h