My Project: Span< T > Struct Template Reference
Span< T > Struct Template Reference
Span.
#include <xspan_impl_span.h>
Public Member Functions
CSelf (pointer first) XSPAN_DELETED_FUNCTION
CSelf (const Self &other)
template<class U >
CSelf (const CSelf< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
CSelf (std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanCount, const void *) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanSizeInBytes, const void *) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, size_type, const void *) XSPAN_DELETED_FUNCTION
Self & operator= (std::nullptr_t) XSPAN_DELETED_FUNCTION
bool operator== (std::nullptr_t) const
bool operator!= (std::nullptr_t) const
Private Types
enum { configRequirePtr = true }
enum { configRequireBase = true }
typedef CSelf< T > Self
Detailed Description
template<class T>
struct Span< T >
Span.
invariants: ptr != null, base != null ptr is valid in base
Definition at line 40 of file xspan_impl_span.h.
Member Typedef Documentation
Self
template<class T > typedef CSelf<T> Span< T >::Self private
Definition at line 43 of file xspan_impl_span.h.
Member Enumeration Documentation
anonymous enum
template<class T > anonymous enum private
Enumerator
configRequirePtr
Definition at line 49 of file xspan_impl_span.h.
{ configRequirePtr = true };
anonymous enum
template<class T > anonymous enum private
Enumerator
configRequireBase
Definition at line 50 of file xspan_impl_span.h.
{ configRequireBase = true };
Member Function Documentation
CSelf() [1/7]
template<class T > template<class U > Span< T >::CSelf (const CSelf< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 64 of file xspan_impl_span.h.
        : ptr(other.ensurePtr()), base(other.ensureBase()), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [2/7]
template<class T > Span< T >::CSelf (const Self & other) inline
Definition at line 59 of file xspan_impl_span.h.
        : ptr(other.ensurePtr()), base(other.ensureBase()), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [3/7]
template<class T > Span< T >::CSelf (pointer first)
CSelf() [4/7]
template<class T > Span< T >::CSelf (std::nullptr_t)
CSelf() [5/7]
template<class T > Span< T >::CSelf (std::nullptr_t , size_type , const void *)
CSelf() [6/7]
template<class T > Span< T >::CSelf (std::nullptr_t , XSpanCount , const void *)
CSelf() [7/7]
template<class T > Span< T >::CSelf (std::nullptr_t , XSpanSizeInBytes , const void *)
operator!=()
template<class T > bool Span< T >::operator!= (std::nullptr_t) const inline
Definition at line 117 of file xspan_impl_span.h.
{
        assertInvariants();
        return true;
    }
References assertInvariants().
operator=()
template<class T > Self & Span< T >::operator= (std::nullptr_t)
operator==()
template<class T > bool Span< T >::operator== (std::nullptr_t) const inline
Definition at line 113 of file xspan_impl_span.h.
{
        assertInvariants();
        return false;
    }
References assertInvariants().
The documentation for this struct was generated from the following file:
src/util/xspan_impl_span.h