My Project: BEPolicy Struct Reference
BEPolicy Struct Reference final
#include <bele_policy.h>
Public Types
typedef BE16 U16
typedef BE32 U32
typedef BE64 U64
Public Member Functions
BEPolicy () noexcept=default
VV bool isBE () C
VV bool isLE () C
V unsigned get16 (const void *p) C
V unsigned get24 (const void *p) C
V unsigned get32 (const void *p) C
V upx_uint64_t get64 (const void *p) C
V void set16 (void *p, unsigned v) C
V void set24 (void *p, unsigned v) C
V void set32 (void *p, unsigned v) C
V void set64 (void *p, upx_uint64_t v) C
V int get16_signed (const void *p) C
V int get24_signed (const void *p) C
V int get32_signed (const void *p) C
V upx_int64_t get64_signed (const void *p) C
S u16_compare (const void *a, const void *b) C
S u24_compare (const void *a, const void *b) C
S u32_compare (const void *a, const void *b) C
S u64_compare (const void *a, const void *b) C
S u16_compare_signed (const void *a, const void *b) C
S u24_compare_signed (const void *a, const void *b) C
S u32_compare_signed (const void *a, const void *b) C
S u64_compare_signed (const void *a, const void *b) C
Static Public Member Functions
static void compileTimeAssertions ()
Detailed Description
Definition at line 95 of file bele_policy.h.
Member Typedef Documentation
U16
typedef BE16 BEPolicy::U16
Definition at line 109 of file bele_policy.h.
U32
typedef BE32 BEPolicy::U32
Definition at line 110 of file bele_policy.h.
U64
typedef BE64 BEPolicy::U64
Definition at line 111 of file bele_policy.h.
Constructor & Destructor Documentation
BEPolicy()
BEPolicy::BEPolicy () inline explicit default noexcept
Member Function Documentation
compileTimeAssertions()
static void BEPolicy::compileTimeAssertions () inline static
Definition at line 138 of file bele_policy.h.
{
        COMPILE_TIME_ASSERT(sizeof(U16) == 2)
        COMPILE_TIME_ASSERT(sizeof(U32) == 4)
        COMPILE_TIME_ASSERT(sizeof(U64) == 8)
        COMPILE_TIME_ASSERT_ALIGNED1(U16)
        COMPILE_TIME_ASSERT_ALIGNED1(U32)
        COMPILE_TIME_ASSERT_ALIGNED1(U64)
    }
References COMPILE_TIME_ASSERT, and COMPILE_TIME_ASSERT_ALIGNED1.
get16()
V unsigned BEPolicy::get16 (const void * p) inline
Definition at line 113 of file bele_policy.h.
{ return get_be16(p); }
References get_be16().
get16_signed()
V int BEPolicy::get16_signed (const void * p) inline
Definition at line 123 of file bele_policy.h.
{ return get_be16_signed(p); }
References get_be16_signed().
get24()
V unsigned BEPolicy::get24 (const void * p) inline
Definition at line 114 of file bele_policy.h.
{ return get_be24(p); }
References get_be24().
get24_signed()
V int BEPolicy::get24_signed (const void * p) inline
Definition at line 124 of file bele_policy.h.
{ return get_be24_signed(p); }
References get_be24_signed().
get32()
V unsigned BEPolicy::get32 (const void * p) inline
Definition at line 115 of file bele_policy.h.
{ return get_be32(p); }
References get_be32().
get32_signed()
V int BEPolicy::get32_signed (const void * p) inline
Definition at line 125 of file bele_policy.h.
{ return get_be32_signed(p); }
References get_be32_signed().
get64()
V upx_uint64_t BEPolicy::get64 (const void * p) inline
Definition at line 116 of file bele_policy.h.
{ return get_be64(p); }
References get_be64().
get64_signed()
V upx_int64_t BEPolicy::get64_signed (const void * p) inline
Definition at line 126 of file bele_policy.h.
{ return get_be64_signed(p); }
References get_be64_signed().
isBE()
VV bool BEPolicy::isBE () inline
Definition at line 106 of file bele_policy.h.
{ return true; }
isLE()
VV bool BEPolicy::isLE () inline
Definition at line 107 of file bele_policy.h.
{ return false; }
set16()
V void BEPolicy::set16 (void * p, unsigned v) inline
Definition at line 118 of file bele_policy.h.
{ set_be16(p, v); }
References set_be16().
set24()
V void BEPolicy::set24 (void * p, unsigned v) inline
Definition at line 119 of file bele_policy.h.
{ set_be24(p, v); }
References set_be24().
set32()
V void BEPolicy::set32 (void * p, unsigned v) inline
Definition at line 120 of file bele_policy.h.
{ set_be32(p, v); }
References set_be32().
set64()
V void BEPolicy::set64 (void * p, upx_uint64_t v) inline
Definition at line 121 of file bele_policy.h.
{ set_be64(p, v); }
References set_be64().
u16_compare()
S BEPolicy::u16_compare (const void * a, const void * b) inline
Definition at line 128 of file bele_policy.h.
{ return be16_compare(a, b); }
References b, and be16_compare().
u16_compare_signed()
S BEPolicy::u16_compare_signed (const void * a, const void * b) inline
Definition at line 133 of file bele_policy.h.
{ return be16_compare_signed(a, b); }
References b, and be16_compare_signed().
u24_compare()
S BEPolicy::u24_compare (const void * a, const void * b) inline
Definition at line 129 of file bele_policy.h.
{ return be24_compare(a, b); }
References b, and be24_compare().
u24_compare_signed()
S BEPolicy::u24_compare_signed (const void * a, const void * b) inline
Definition at line 134 of file bele_policy.h.
{ return be24_compare_signed(a, b); }
References b, and be24_compare_signed().
u32_compare()
S BEPolicy::u32_compare (const void * a, const void * b) inline
Definition at line 130 of file bele_policy.h.
{ return be32_compare(a, b); }
References b, and be32_compare().
u32_compare_signed()
S BEPolicy::u32_compare_signed (const void * a, const void * b) inline
Definition at line 135 of file bele_policy.h.
{ return be32_compare_signed(a, b); }
References b, and be32_compare_signed().
u64_compare()
S BEPolicy::u64_compare (const void * a, const void * b) inline
Definition at line 131 of file bele_policy.h.
{ return be64_compare(a, b); }
References b, and be64_compare().
u64_compare_signed()
S BEPolicy::u64_compare_signed (const void * a, const void * b) inline
Definition at line 136 of file bele_policy.h.
{ return be64_compare_signed(a, b); }
References b, and be64_compare_signed().
The documentation for this struct was generated from the following file:
src/bele_policy.h