My Project: anonymous_namespace{dt_check.cpp}::CheckIntegral< T > Struct Template Reference
anonymous_namespace{dt_check.cpp}::CheckIntegral< T > Struct Template Reference
Classes
struct TestT
struct TestU
Static Public Member Functions
template<class U >
static void checkU (void) noexcept
static void check_core (void) noexcept
static void check (void) noexcept
Detailed Description
template<class T>
struct anonymous_namespace{dt_check.cpp}::CheckIntegral< T >
Definition at line 334 of file dt_check.cpp.
Member Function Documentation
check()
template<class T > static void anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check (void) inline static noexcept
Definition at line 434 of file dt_check.cpp.
{
        check_core();
        {
            T zero, one, three, four;
            zero = 0;
            one = 1;
            three = 3;
            four = 4;
            // align - needs binary expressions which do not work
            // on CHERI uintptr_t because of pointer provenance
            assert_noexcept(upx::align_down(zero, four) == 0);
            assert_noexcept(upx::align_down(zero, four) == zero);
            assert_noexcept(upx::align_down(one, four) == 0);
            assert_noexcept(upx::align_down(one, four) == zero);
            assert_noexcept(upx::align_down(three, four) == 0);
            assert_noexcept(upx::align_down(three, four) == zero);
            assert_noexcept(upx::align_down(four, four) == 4);
            assert_noexcept(upx::align_down(four, four) == four);
            assert_noexcept(upx::align_up(zero, four) == 0);
            assert_noexcept(upx::align_up(zero, four) == zero);
            assert_noexcept(upx::align_up(one, four) == 4);
            assert_noexcept(upx::align_up(one, four) == four);
            assert_noexcept(upx::align_up(three, four) == 4);
            assert_noexcept(upx::align_up(three, four) == four);
            assert_noexcept(upx::align_up(four, four) == 4);
            assert_noexcept(upx::align_up(four, four) == four);
            assert_noexcept(upx::align_up_gap(zero, four) == 0);
            assert_noexcept(upx::align_up_gap(zero, four) == zero);
            assert_noexcept(upx::align_up_gap(one, four) == 3);
            assert_noexcept(upx::align_up_gap(one, four) == three);
            assert_noexcept(upx::align_up_gap(three, four) == 1);
            assert_noexcept(upx::align_up_gap(three, four) == one);
            assert_noexcept(upx::align_up_gap(four, four) == 0);
            assert_noexcept(upx::align_up_gap(four, four) == zero);
        }
    }
References upx::align_down(), upx::align_up(), upx::align_up_gap(), and assert_noexcept.
Referenced by upx_compiler_sanity_check().
check_core()
template<class T > static void anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::check_core (void) inline static noexcept
Definition at line 393 of file dt_check.cpp.
{
        {
            TestT t = {};
            assert_noexcept(t.a == 0);
            assert_noexcept(t.x[0] == 0 && t.x[1] == 0);
        }
        {
            const TestT t = {};
            assert_noexcept(t.a == 0);
            assert_noexcept(t.x[0] == 0 && t.x[1] == 0);
        }
        {
            constexpr TestT t = {};
            assert_noexcept(t.a == 0);
            assert_noexcept(t.x[0] == 0 && t.x[1] == 0);
        }
        {
            TestT t;
            mem_clear(&t);
            assert_noexcept(t.a == 0);
            assert_noexcept(t.x[0] == 0 && t.x[1] == 0);
        }
        checkU<T>();
        checkU<typename std::add_const<T>::type>();
        {
            T zero, one, three, four;
            zero = 0;
            one = 1;
            three = 3;
            four = 4;
            assert_noexcept(zero == 0);
            assert_noexcept(one == 1);
            assert_noexcept(three == 3);
            assert_noexcept(four == 4);
            // min / max
            assert_noexcept(upx::min(one, four) == 1);
            assert_noexcept(upx::min(one, four) == one);
            assert_noexcept(upx::max(one, four) == 4);
            assert_noexcept(upx::max(one, four) == four);
        }
    }
References anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestT::a, assert_noexcept, upx::max(), mem_clear(), upx::min(), and anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestT::x.
Referenced by upx_compiler_sanity_check().
checkU()
template<class T > template<class U > static void anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::checkU (void) inline static noexcept
Definition at line 351 of file dt_check.cpp.
{
        {
            U a = {};
            const U b = {};
            constexpr U c = {};
            U x[2] = {};
            const U y[2] = {};
            constexpr U z[2] = {};
            assert_noexcept(a == 0);
            assert_noexcept(b == 0);
            assert_noexcept(c == 0);
            assert_noexcept(x[0] == 0 && x[1] == 0);
            assert_noexcept(y[0] == 0 && y[1] == 0);
            assert_noexcept(z[0] == 0 && z[1] == 0);
#if defined(upx_is_constant_evaluated)
            static_assert(c == 0);
            static_assert(z[0] == 0 && z[1] == 0);
#endif
        }
        {
            TestU<U> t;
            assert_noexcept(t.a == 0);
            assert_noexcept(t.b == 0);
            assert_noexcept(t.c == 0);
            assert_noexcept(t.x[0] == 0 && t.x[1] == 0);
            assert_noexcept(t.y[0] == 0 && t.y[1] == 0);
            assert_noexcept(t.z[0] == 0 && t.z[1] == 0);
        }
#if __cplusplus <= 201703L
        static_assert(std::is_pod<U>::value); // std::is_pod is deprecated in C++20
#endif
        static_assert(std::is_standard_layout<U>::value);
        static_assert(std::is_trivial<U>::value);
        // more checks, these are probably implied by std::is_trivial
        static_assert(std::is_nothrow_default_constructible<U>::value);
        static_assert(std::is_nothrow_destructible<U>::value);
        static_assert(std::is_trivially_copyable<U>::value);
        static_assert(std::is_trivially_default_constructible<U>::value);
        // UPX extras
        static_assert(upx_is_integral<U>::value);
        static_assert(upx_is_integral_v<U>);
    }
References anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >::a, assert_noexcept, anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >::b, b, anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >::c, U, anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >::x, anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >::y, and anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::TestU< U >::z.
The documentation for this struct was generated from the following file:
src/check/dt_check.cpp