My Project: upx::ArrayDeleter< T > Struct Template Reference
upx::ArrayDeleter< T > Struct Template Reference final
#include <cxxlib.h>
Public Member Functions
ArrayDeleter (T **p, std::size_t n) noexcept
~ArrayDeleter () noexcept
void delete_items () noexcept
Public Attributes
T ** items
std::size_t count
Detailed Description
template<class T>
struct upx::ArrayDeleter< T >
Definition at line 355 of file cxxlib.h.
Constructor & Destructor Documentation
ArrayDeleter()
template<class T > upx::ArrayDeleter< T >::ArrayDeleter (T ** p, std::size_t n) inline explicit noexcept
Definition at line 358 of file cxxlib.h.
: items(p), count(n) {}
~ArrayDeleter()
template<class T > upx::ArrayDeleter< T >::~ArrayDeleter () inline noexcept
Definition at line 359 of file cxxlib.h.
{ delete_items(); }
References upx::ArrayDeleter< T >::delete_items().
Member Function Documentation
delete_items()
template<class T > void upx::ArrayDeleter< T >::delete_items () inline noexcept
Definition at line 360 of file cxxlib.h.
{
        for (std::size_t i = 0; i < count; i++) {
            T *item = atomic_exchange(&items[i], (T *) nullptr);
            delete[] item; // array delete
        }
    }
References upx::atomic_exchange(), upx::ArrayDeleter< T >::count, and upx::ArrayDeleter< T >::items.
Referenced by upx::ArrayDeleter< T >::~ArrayDeleter().
Member Data Documentation
count
template<class T > std::size_t upx::ArrayDeleter< T >::count
Definition at line 357 of file cxxlib.h.
Referenced by upx::ArrayDeleter< T >::delete_items().
items
template<class T > T** upx::ArrayDeleter< T >::items
Definition at line 356 of file cxxlib.h.
Referenced by upx::ArrayDeleter< T >::delete_items().
The documentation for this struct was generated from the following file:
src/util/cxxlib.h