My Project: PtrOrSpan< T > Struct Template Reference
PtrOrSpan< T > Struct Template Reference
PtrOrSpan.
#include <xspan_impl_ptr_or_span.h>
Public Member Functions
CSelf (pointer first)
CSelf (const Self &other)
template<class U >
CSelf (const CSelf< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
template<class U >
CSelf (const Span< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
template<class U >
operator= (const Span< U > &other)
CSelf (std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanCount, const void *) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanSizeInBytes, const void *) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, size_type, const void *) XSPAN_DELETED_FUNCTION
Self & operator= (std::nullptr_t) XSPAN_DELETED_FUNCTION
bool operator== (std::nullptr_t) const
bool operator!= (std::nullptr_t) const
Private Types
enum { configRequirePtr = true }
enum { configRequireBase = false }
typedef CSelf< T > Self
Detailed Description
template<class T>
struct PtrOrSpan< T >
PtrOrSpan.
invariants: ptr != null if base != null then ptr is valid in base
Definition at line 40 of file xspan_impl_ptr_or_span.h.
Member Typedef Documentation
Self
template<class T > typedef CSelf<T> PtrOrSpan< T >::Self private
Definition at line 43 of file xspan_impl_ptr_or_span.h.
Member Enumeration Documentation
anonymous enum
template<class T > anonymous enum private
Enumerator
configRequirePtr
Definition at line 49 of file xspan_impl_ptr_or_span.h.
{ configRequirePtr = true };
anonymous enum
template<class T > anonymous enum private
Enumerator
configRequireBase
Definition at line 50 of file xspan_impl_ptr_or_span.h.
{ configRequireBase = false };
Member Function Documentation
CSelf() [1/8]
template<class T > template<class U > PtrOrSpan< T >::CSelf (const CSelf< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 66 of file xspan_impl_ptr_or_span.h.
        : ptr(other.ensurePtr()), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [2/8]
template<class T > PtrOrSpan< T >::CSelf (const Self & other) inline
Definition at line 61 of file xspan_impl_ptr_or_span.h.
        : ptr(other.ensurePtr()), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [3/8]
template<class T > template<class U > PtrOrSpan< T >::CSelf (const Span< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 73 of file xspan_impl_ptr_or_span.h.
        : ptr(other.ensurePtr()), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [4/8]
template<class T > PtrOrSpan< T >::CSelf (pointer first) inline
Definition at line 56 of file xspan_impl_ptr_or_span.h.
                         : ptr(makePtr(first)), base(nullptr), size_in_bytes(0) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [5/8]
template<class T > PtrOrSpan< T >::CSelf (std::nullptr_t)
CSelf() [6/8]
template<class T > PtrOrSpan< T >::CSelf (std::nullptr_t , size_type , const void *)
CSelf() [7/8]
template<class T > PtrOrSpan< T >::CSelf (std::nullptr_t , XSpanCount , const void *)
CSelf() [8/8]
template<class T > PtrOrSpan< T >::CSelf (std::nullptr_t , XSpanSizeInBytes , const void *)
operator!=()
template<class T > bool PtrOrSpan< T >::operator!= (std::nullptr_t) const inline
Definition at line 117 of file xspan_impl_ptr_or_span.h.
{
        assertInvariants();
        return true;
    }
References assertInvariants().
operator=() [1/2]
template<class T > template<class U > PtrOrSpan< T >::operator= (const Span< U > & other) inline
Definition at line 89 of file xspan_impl_ptr_or_span.h.
{
        return assign(Self(other));
    }
References assign().
operator=() [2/2]
template<class T > Self & PtrOrSpan< T >::operator= (std::nullptr_t)
operator==()
template<class T > bool PtrOrSpan< T >::operator== (std::nullptr_t) const inline
Definition at line 113 of file xspan_impl_ptr_or_span.h.
{
        assertInvariants();
        return false;
    }
References assertInvariants().
The documentation for this struct was generated from the following file:
src/util/xspan_impl_ptr_or_span.h