My Project: anonymous_namespace{help.cpp}::PackerNames Struct Reference
anonymous_namespace{help.cpp}::PackerNames Struct Reference final
Classes
struct Entry
Public Member Functions
PackerNames () noexcept=default
~PackerNames () noexcept=default
void add (const PackerBase *pb)
Static Public Member Functions
static tribool visit (PackerBase *pb, void *user)
static int __acc_cdecl_qsort compare_fname (const void *aa, const void *bb)
Public Attributes
Entry names_array [MAX_NAMES]
Entry * names [MAX_NAMES]
unsigned names_count = 0
const Options * o = nullptr
Static Public Attributes
static constexpr unsigned MAX_NAMES = 64
Detailed Description
Definition at line 104 of file help.cpp.
Constructor & Destructor Documentation
PackerNames()
anonymous_namespace{help.cpp}::PackerNames::PackerNames () explicit default noexcept
~PackerNames()
anonymous_namespace{help.cpp}::PackerNames::~PackerNames () default noexcept
Member Function Documentation
add()
void anonymous_namespace{help.cpp}::PackerNames::add (const PackerBase * pb) inline
Definition at line 122 of file help.cpp.
{
        assert_noexcept(names_count < MAX_NAMES);
        Entry &e = names_array[names_count];
        names[names_count++] = &e;
        e.fname = pb->getFullName(o);
        e.sname = pb->getName();
        e.methods_count = e.filters_count = 0;
        for (const int *m = pb->getCompressionMethods(M_ALL, 10); *m != M_END; m++) {
            if (*m >= 0) {
                assert_noexcept(Packer::isValidCompressionMethod(*m));
                assert_noexcept(e.methods_count < PackerBase::MAX_METHODS);
                e.methods[e.methods_count++] = *m;
            }
        }
        for (const int *f = pb->getFilters(); f != nullptr && *f != FT_END; f++) {
            if (*f >= 0) {
                assert_noexcept(Filter::isValidFilter(*f));
                assert_noexcept(e.filters_count < PackerBase::MAX_FILTERS);
                e.filters[e.filters_count++] = *f;
            }
        }
        upx_gnomesort(e.methods, e.methods_count, sizeof(e.methods[0]), ne32_compare);
        upx_gnomesort(e.filters, e.filters_count, sizeof(e.filters[0]), ne32_compare);
    }
References assert_noexcept, anonymous_namespace{help.cpp}::PackerNames::Entry::filters, anonymous_namespace{help.cpp}::PackerNames::Entry::filters_count, anonymous_namespace{help.cpp}::PackerNames::Entry::fname, FT_END, PackerBase::getCompressionMethods(), PackerBase::getFilters(), PackerBase::getFullName(), PackerBase::getName(), Packer::isValidCompressionMethod(), Filter::isValidFilter(), M_ALL, M_END, PackerBase::MAX_FILTERS, PackerBase::MAX_METHODS, anonymous_namespace{help.cpp}::PackerNames::Entry::methods, anonymous_namespace{help.cpp}::PackerNames::Entry::methods_count, ne32_compare, anonymous_namespace{help.cpp}::PackerNames::Entry::sname, and upx_gnomesort().
Referenced by visit().
compare_fname()
static int __acc_cdecl_qsort anonymous_namespace{help.cpp}::PackerNames::compare_fname (const void * aa, const void * bb) inline static
Definition at line 152 of file help.cpp.
{
        const Entry *a = *(const Entry *const *) aa;
        const Entry *b = *(const Entry *const *) bb;
        return strcmp(a->fname, b->fname);
    }
References b, anonymous_namespace{help.cpp}::PackerNames::Entry::fname, and strcmp().
Referenced by list_all_packers().
visit()
static tribool anonymous_namespace{help.cpp}::PackerNames::visit (PackerBase * pb, void * user) inline static
Definition at line 146 of file help.cpp.
{
        NO_fprintf(stderr, "visit %s\n", pb->getFullName(nullptr));
        PackerNames *self = (PackerNames *) user;
        self->add(pb);
        return false;
    }
References add(), PackerBase::getFullName(), and NO_fprintf().
Referenced by list_all_packers().
Member Data Documentation
MAX_NAMES
constexpr unsigned anonymous_namespace{help.cpp}::PackerNames::MAX_NAMES = 64 static constexpr
Definition at line 108 of file help.cpp.
names
Entry* anonymous_namespace{help.cpp}::PackerNames::names[MAX_NAMES]
Definition at line 118 of file help.cpp.
names_array
Entry anonymous_namespace{help.cpp}::PackerNames::names_array[MAX_NAMES]
Definition at line 117 of file help.cpp.
names_count
unsigned anonymous_namespace{help.cpp}::PackerNames::names_count = 0
Definition at line 119 of file help.cpp.
o
const Options* anonymous_namespace{help.cpp}::PackerNames::o = nullptr
Definition at line 120 of file help.cpp.
The documentation for this struct was generated from the following file:
src/help.cpp