My Project: BE16 Struct Reference
BE16 Struct Reference final
classes for portable unaligned access
#include <bele.h>
Public Types
typedef unsigned integral_conversion_type
Public Member Functions
forceinline bele_constexpr operator unsigned () const noexcept
forceinline bele_constexpr BE16 & operator= (unsigned v) noexcept
BE16 & operator+= (unsigned v) noexcept
BE16 & operator-= (unsigned v) noexcept
BE16 & operator*= (unsigned v) noexcept
BE16 & operator/= (unsigned v) noexcept
BE16 & operator&= (unsigned v) noexcept
BE16 & operator|= (unsigned v) noexcept
BE16 & operator^= (unsigned v) noexcept
BE16 & operator<<= (unsigned v) noexcept
BE16 & operator>>= (unsigned v) noexcept
bele_constexpr bool operator== (const BE16 &x) const noexcept
bele_constexpr bool operator< (const BE16 &x) const noexcept
Static Public Member Functions
static forceinline constexpr BE16 make (const BE16 &x) noexcept
static forceinline bele_constexpr BE16 make (unsigned v) noexcept
Public Attributes
byte d [2]
Detailed Description
classes for portable unaligned access
Note: these classes must be PODs (Plain Old Data), i.e. no constructor, no destructor, no virtual functions and no default assignment operator, and all fields must be public
Definition at line 488 of file bele.h.
Member Typedef Documentation
integral_conversion_type
typedef unsigned BE16::integral_conversion_type
Definition at line 489 of file bele.h.
Member Function Documentation
make() [1/2]
static forceinline constexpr BE16 BE16::make (const BE16 & x) inline static constexpr noexcept
Definition at line 492 of file bele.h.
{ return x; }
Referenced by upx_compiler_sanity_check().
make() [2/2]
static forceinline bele_constexpr BE16 BE16::make (unsigned v) inline static noexcept
Definition at line 493 of file bele.h.
{
        BE16 x = {};
        set_be16(x.d, v);
        return x;
    }
References d, and set_be16().
operator unsigned()
forceinline bele_constexpr BE16::operator unsigned () const inline noexcept
Definition at line 499 of file bele.h.
{ return get_be16(d); }
References d, and get_be16().
operator&=()
BE16 & BE16::operator&= (unsigned v) inline noexcept
Definition at line 521 of file bele.h.
{
        set_be16(d, get_be16(d) & v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator*=()
BE16 & BE16::operator*= (unsigned v) inline noexcept
Definition at line 513 of file bele.h.
{
        set_be16(d, get_be16(d) * v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator+=()
BE16 & BE16::operator+= (unsigned v) inline noexcept
Definition at line 505 of file bele.h.
{
        set_be16(d, get_be16(d) + v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator-=()
BE16 & BE16::operator-= (unsigned v) inline noexcept
Definition at line 509 of file bele.h.
{
        set_be16(d, get_be16(d) - v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator/=()
BE16 & BE16::operator/= (unsigned v) inline noexcept
Definition at line 517 of file bele.h.
{
        set_be16(d, get_be16(d) / v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator<()
bele_constexpr bool BE16::operator< (const BE16 & x) const inline noexcept
Definition at line 550 of file bele.h.
{
        return unsigned(*this) < unsigned(x);
    }
operator<<=()
BE16 & BE16::operator<<= (unsigned v) inline noexcept
Definition at line 533 of file bele.h.
{
        set_be16(d, get_be16(d) << v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator=()
forceinline bele_constexpr BE16 & BE16::operator= (unsigned v) inline noexcept
Definition at line 501 of file bele.h.
{
        set_be16(d, v);
        return *this;
    }
References d, and set_be16().
operator==()
bele_constexpr bool BE16::operator== (const BE16 & x) const inline noexcept
Definition at line 542 of file bele.h.
{
#if defined(upx_is_constant_evaluated)
        if (upx_is_constant_evaluated())
            return upx::compile_time::mem_eq(d, x.d, sizeof(d));
        else
#endif
            return upx_memcmp_inline(d, x.d, sizeof(d)) == 0;
    }
References d, upx::compile_time::mem_eq(), and upx_memcmp_inline.
operator>>=()
BE16 & BE16::operator>>= (unsigned v) inline noexcept
Definition at line 537 of file bele.h.
{
        set_be16(d, get_be16(d) >> v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator^=()
BE16 & BE16::operator^= (unsigned v) inline noexcept
Definition at line 529 of file bele.h.
{
        set_be16(d, get_be16(d) ^ v);
        return *this;
    }
References d, get_be16(), and set_be16().
operator|=()
BE16 & BE16::operator|= (unsigned v) inline noexcept
Definition at line 525 of file bele.h.
{
        set_be16(d, get_be16(d) | v);
        return *this;
    }
References d, get_be16(), and set_be16().
Member Data Documentation
d
byte BE16::d[2]
Definition at line 490 of file bele.h.
Referenced by make(), operator unsigned(), operator&=(), operator*=(), operator+=(), operator-=(), operator/=(), operator<<=(), operator=(), operator==(), operator>>=(), operator^=(), operator|=(), and upx_compiler_sanity_check().
The documentation for this struct was generated from the following file:
src/bele.h