My Project: anonymous_namespace{dt_cxxlib.cpp}::TestCT Struct Reference
anonymous_namespace{dt_cxxlib.cpp}::TestCT Struct Reference final
Static Public Member Functions
static constexpr TestCT makeBE16 (upx_uint16_t v) noexcept
static constexpr TestCT makeBE24 (upx_uint32_t v) noexcept
static constexpr TestCT makeBE32 (upx_uint32_t v) noexcept
static constexpr TestCT makeBE64 (upx_uint64_t v) noexcept
static constexpr TestCT makeLE16 (upx_uint16_t v) noexcept
static constexpr TestCT makeLE24 (upx_uint32_t v) noexcept
static constexpr TestCT makeLE32 (upx_uint32_t v) noexcept
static constexpr TestCT makeLE64 (upx_uint64_t v) noexcept
static noinline upx_uint16_t noinline_bswap16 (upx_uint16_t v) noexcept
static noinline upx_uint32_t noinline_bswap32 (upx_uint32_t v) noexcept
static noinline upx_uint64_t noinline_bswap64 (upx_uint64_t v) noexcept
static noinline upx_uint16_t noinline_get_be16 (const byte *p) noexcept
static noinline upx_uint32_t noinline_get_be24 (const byte *p) noexcept
static noinline upx_uint32_t noinline_get_be32 (const byte *p) noexcept
static noinline upx_uint64_t noinline_get_be64 (const byte *p) noexcept
static noinline upx_uint16_t noinline_get_le16 (const byte *p) noexcept
static noinline upx_uint32_t noinline_get_le24 (const byte *p) noexcept
static noinline upx_uint32_t noinline_get_le32 (const byte *p) noexcept
static noinline upx_uint64_t noinline_get_le64 (const byte *p) noexcept
static noinline void noinline_set_be16 (byte *p, upx_uint16_t v) noexcept
static noinline void noinline_set_be24 (byte *p, upx_uint32_t v) noexcept
static noinline void noinline_set_be32 (byte *p, upx_uint32_t v) noexcept
static noinline void noinline_set_be64 (byte *p, upx_uint64_t v) noexcept
static noinline void noinline_set_le16 (byte *p, upx_uint16_t v) noexcept
static noinline void noinline_set_le24 (byte *p, upx_uint32_t v) noexcept
static noinline void noinline_set_le32 (byte *p, upx_uint32_t v) noexcept
static noinline void noinline_set_le64 (byte *p, upx_uint64_t v) noexcept
Public Attributes
byte d [8]
Detailed Description
Definition at line 662 of file dt_cxxlib.cpp.
Member Function Documentation
makeBE16()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE16 (upx_uint16_t v) inline static constexpr noexcept
Definition at line 665 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_be16(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_be16().
makeBE24()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE24 (upx_uint32_t v) inline static constexpr noexcept
Definition at line 670 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_be24(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_be24().
makeBE32()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE32 (upx_uint32_t v) inline static constexpr noexcept
Definition at line 675 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_be32(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_be32().
makeBE64()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeBE64 (upx_uint64_t v) inline static constexpr noexcept
Definition at line 680 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_be64(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_be64().
makeLE16()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE16 (upx_uint16_t v) inline static constexpr noexcept
Definition at line 685 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_le16(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_le16().
makeLE24()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE24 (upx_uint32_t v) inline static constexpr noexcept
Definition at line 690 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_le24(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_le24().
makeLE32()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE32 (upx_uint32_t v) inline static constexpr noexcept
Definition at line 695 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_le32(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_le32().
makeLE64()
static constexpr TestCT anonymous_namespace{dt_cxxlib.cpp}::TestCT::makeLE64 (upx_uint64_t v) inline static constexpr noexcept
Definition at line 700 of file dt_cxxlib.cpp.
{
        TestCT x = {};
        upx::compile_time::set_le64(x.d, v);
        return x;
    }
References d, and upx::compile_time::set_le64().
noinline_bswap16()
static noinline upx_uint16_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_bswap16 (upx_uint16_t v) inline static noexcept
Definition at line 707 of file dt_cxxlib.cpp.
{
        return upx::compile_time::bswap16(v);
    }
References upx::compile_time::bswap16().
noinline_bswap32()
static noinline upx_uint32_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_bswap32 (upx_uint32_t v) inline static noexcept
Definition at line 710 of file dt_cxxlib.cpp.
{
        return upx::compile_time::bswap32(v);
    }
References upx::compile_time::bswap32().
noinline_bswap64()
static noinline upx_uint64_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_bswap64 (upx_uint64_t v) inline static noexcept
Definition at line 713 of file dt_cxxlib.cpp.
{
        return upx::compile_time::bswap64(v);
    }
References upx::compile_time::bswap64().
noinline_get_be16()
static noinline upx_uint16_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be16 (const byte * p) inline static noexcept
Definition at line 717 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_be16(p);
    }
References upx::compile_time::get_be16().
noinline_get_be24()
static noinline upx_uint32_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be24 (const byte * p) inline static noexcept
Definition at line 720 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_be24(p);
    }
References upx::compile_time::get_be24().
noinline_get_be32()
static noinline upx_uint32_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be32 (const byte * p) inline static noexcept
Definition at line 723 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_be32(p);
    }
References upx::compile_time::get_be32().
noinline_get_be64()
static noinline upx_uint64_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_be64 (const byte * p) inline static noexcept
Definition at line 726 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_be64(p);
    }
References upx::compile_time::get_be64().
noinline_get_le16()
static noinline upx_uint16_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le16 (const byte * p) inline static noexcept
Definition at line 729 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_le16(p);
    }
References upx::compile_time::get_le16().
noinline_get_le24()
static noinline upx_uint32_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le24 (const byte * p) inline static noexcept
Definition at line 732 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_le24(p);
    }
References upx::compile_time::get_le24().
noinline_get_le32()
static noinline upx_uint32_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le32 (const byte * p) inline static noexcept
Definition at line 735 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_le32(p);
    }
References upx::compile_time::get_le32().
noinline_get_le64()
static noinline upx_uint64_t anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_get_le64 (const byte * p) inline static noexcept
Definition at line 738 of file dt_cxxlib.cpp.
{
        return upx::compile_time::get_le64(p);
    }
References upx::compile_time::get_le64().
noinline_set_be16()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be16 (byte * p, upx_uint16_t v) inline static noexcept
Definition at line 742 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_be16(p, v);
    }
References upx::compile_time::set_be16().
noinline_set_be24()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be24 (byte * p, upx_uint32_t v) inline static noexcept
Definition at line 745 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_be24(p, v);
    }
References upx::compile_time::set_be24().
noinline_set_be32()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be32 (byte * p, upx_uint32_t v) inline static noexcept
Definition at line 748 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_be32(p, v);
    }
References upx::compile_time::set_be32().
noinline_set_be64()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_be64 (byte * p, upx_uint64_t v) inline static noexcept
Definition at line 751 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_be64(p, v);
    }
References upx::compile_time::set_be64().
noinline_set_le16()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le16 (byte * p, upx_uint16_t v) inline static noexcept
Definition at line 754 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_le16(p, v);
    }
References upx::compile_time::set_le16().
noinline_set_le24()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le24 (byte * p, upx_uint32_t v) inline static noexcept
Definition at line 757 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_le24(p, v);
    }
References upx::compile_time::set_le24().
noinline_set_le32()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le32 (byte * p, upx_uint32_t v) inline static noexcept
Definition at line 760 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_le32(p, v);
    }
References upx::compile_time::set_le32().
noinline_set_le64()
static noinline void anonymous_namespace{dt_cxxlib.cpp}::TestCT::noinline_set_le64 (byte * p, upx_uint64_t v) inline static noexcept
Definition at line 763 of file dt_cxxlib.cpp.
{
        upx::compile_time::set_le64(p, v);
    }
References upx::compile_time::set_le64().
Member Data Documentation
d
byte anonymous_namespace{dt_cxxlib.cpp}::TestCT::d[8]
Definition at line 663 of file dt_cxxlib.cpp.
Referenced by makeBE16(), makeBE24(), makeBE32(), makeBE64(), makeLE16(), makeLE24(), makeLE32(), and makeLE64().
The documentation for this struct was generated from the following file:
src/check/dt_cxxlib.cpp