My Project: PtrOrSpanOrNull< T > Struct Template Reference
PtrOrSpanOrNull< T > Struct Template Reference
PtrOrSpanOrNull.
#include <xspan_impl_ptr_or_null.h>
Public Member Functions
CSelf (pointer first)
CSelf (const Self &other)
template<class U >
CSelf (const CSelf< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
template<class U >
CSelf (const PtrOrSpan< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
template<class U >
CSelf (const Span< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
template<class U >
operator= (const PtrOrSpan< U > &other)
template<class U >
operator= (const Span< U > &other)
forceinline CSelf (std::nullptr_t) noexcept
forceinline Self & operator= (std::nullptr_t) noexcept
Private Types
enum { configRequirePtr = false }
enum { configRequireBase = false }
typedef CSelf< T > Self
Detailed Description
template<class T>
struct PtrOrSpanOrNull< T >
PtrOrSpanOrNull.
invariants: ptr can be null if ptr != null && base != null then ptr is valid in base
Definition at line 40 of file xspan_impl_ptr_or_null.h.
Member Typedef Documentation
Self
template<class T > typedef CSelf<T> PtrOrSpanOrNull< T >::Self private
Definition at line 43 of file xspan_impl_ptr_or_null.h.
Member Enumeration Documentation
anonymous enum
template<class T > anonymous enum private
Enumerator
configRequirePtr
Definition at line 49 of file xspan_impl_ptr_or_null.h.
{ configRequirePtr = false };
anonymous enum
template<class T > anonymous enum private
Enumerator
configRequireBase
Definition at line 50 of file xspan_impl_ptr_or_null.h.
{ configRequireBase = false };
Member Function Documentation
CSelf() [1/6]
template<class T > template<class U > PtrOrSpanOrNull< T >::CSelf (const CSelf< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 64 of file xspan_impl_ptr_or_null.h.
        : ptr(other.ptr), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [2/6]
template<class T > template<class U > PtrOrSpanOrNull< T >::CSelf (const PtrOrSpan< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 71 of file xspan_impl_ptr_or_null.h.
        : ptr(other.ptr), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [3/6]
template<class T > PtrOrSpanOrNull< T >::CSelf (const Self & other) inline
Definition at line 59 of file xspan_impl_ptr_or_null.h.
        : ptr(other.ptr), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [4/6]
template<class T > template<class U > PtrOrSpanOrNull< T >::CSelf (const Span< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 76 of file xspan_impl_ptr_or_null.h.
        : ptr(other.ptr), base(other.base), size_in_bytes(other.size_in_bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [5/6]
template<class T > PtrOrSpanOrNull< T >::CSelf (pointer first) inline
Definition at line 56 of file xspan_impl_ptr_or_null.h.
: ptr(first), base(nullptr), size_in_bytes(0) { assertInvariants(); }
References assertInvariants().
CSelf() [6/6]
template<class T > forceinline PtrOrSpanOrNull< T >::CSelf (std::nullptr_t) inline noexcept
Definition at line 94 of file xspan_impl_ptr_or_null.h.
: ptr(nullptr), base(nullptr), size_in_bytes(0) {}
operator=() [1/3]
template<class T > template<class U > PtrOrSpanOrNull< T >::operator= (const PtrOrSpan< U > & other) inline
Definition at line 84 of file xspan_impl_ptr_or_null.h.
{
        return assign(Self(other));
    }
References assign().
operator=() [2/3]
template<class T > template<class U > PtrOrSpanOrNull< T >::operator= (const Span< U > & other) inline
Definition at line 89 of file xspan_impl_ptr_or_null.h.
{
        return assign(Self(other));
    }
References assign().
operator=() [3/3]
template<class T > forceinline Self & PtrOrSpanOrNull< T >::operator= (std::nullptr_t) inline noexcept
Definition at line 95 of file xspan_impl_ptr_or_null.h.
{
        ptr = nullptr;
        return *this;
    }
References ptr.
The documentation for this struct was generated from the following file:
src/util/xspan_impl_ptr_or_null.h