My Project: LEPolicy Struct Reference
LEPolicy Struct Reference final
#include <bele_policy.h>
Public Types
typedef LE16 U16
typedef LE32 U32
typedef LE64 U64
Public Member Functions
LEPolicy () noexcept=default
VV bool isBE () C
VV bool isLE () C
V unsigned get16 (const void *p) C
V unsigned get24 (const void *p) C
V unsigned get32 (const void *p) C
V upx_uint64_t get64 (const void *p) C
V void set16 (void *p, unsigned v) C
V void set24 (void *p, unsigned v) C
V void set32 (void *p, unsigned v) C
V void set64 (void *p, upx_uint64_t v) C
V int get16_signed (const void *p) C
V int get24_signed (const void *p) C
V int get32_signed (const void *p) C
V upx_int64_t get64_signed (const void *p) C
S u16_compare (const void *a, const void *b) C
S u24_compare (const void *a, const void *b) C
S u32_compare (const void *a, const void *b) C
S u64_compare (const void *a, const void *b) C
S u16_compare_signed (const void *a, const void *b) C
S u24_compare_signed (const void *a, const void *b) C
S u32_compare_signed (const void *a, const void *b) C
S u64_compare_signed (const void *a, const void *b) C
Static Public Member Functions
static void compileTimeAssertions ()
Detailed Description
Definition at line 154 of file bele_policy.h.
Member Typedef Documentation
U16
typedef LE16 LEPolicy::U16
Definition at line 168 of file bele_policy.h.
U32
typedef LE32 LEPolicy::U32
Definition at line 169 of file bele_policy.h.
U64
typedef LE64 LEPolicy::U64
Definition at line 170 of file bele_policy.h.
Constructor & Destructor Documentation
LEPolicy()
LEPolicy::LEPolicy () inline explicit default noexcept
Member Function Documentation
compileTimeAssertions()
static void LEPolicy::compileTimeAssertions () inline static
Definition at line 197 of file bele_policy.h.
{
        COMPILE_TIME_ASSERT(sizeof(U16) == 2)
        COMPILE_TIME_ASSERT(sizeof(U32) == 4)
        COMPILE_TIME_ASSERT(sizeof(U64) == 8)
        COMPILE_TIME_ASSERT_ALIGNED1(U16)
        COMPILE_TIME_ASSERT_ALIGNED1(U32)
        COMPILE_TIME_ASSERT_ALIGNED1(U64)
    }
References COMPILE_TIME_ASSERT, and COMPILE_TIME_ASSERT_ALIGNED1.
get16()
V unsigned LEPolicy::get16 (const void * p) inline
Definition at line 172 of file bele_policy.h.
{ return get_le16(p); }
References get_le16().
get16_signed()
V int LEPolicy::get16_signed (const void * p) inline
Definition at line 182 of file bele_policy.h.
{ return get_le16_signed(p); }
References get_le16_signed().
get24()
V unsigned LEPolicy::get24 (const void * p) inline
Definition at line 173 of file bele_policy.h.
{ return get_le24(p); }
References get_le24().
get24_signed()
V int LEPolicy::get24_signed (const void * p) inline
Definition at line 183 of file bele_policy.h.
{ return get_le24_signed(p); }
References get_le24_signed().
get32()
V unsigned LEPolicy::get32 (const void * p) inline
Definition at line 174 of file bele_policy.h.
{ return get_le32(p); }
References get_le32().
get32_signed()
V int LEPolicy::get32_signed (const void * p) inline
Definition at line 184 of file bele_policy.h.
{ return get_le32_signed(p); }
References get_le32_signed().
get64()
V upx_uint64_t LEPolicy::get64 (const void * p) inline
Definition at line 175 of file bele_policy.h.
{ return get_le64(p); }
References get_le64().
get64_signed()
V upx_int64_t LEPolicy::get64_signed (const void * p) inline
Definition at line 185 of file bele_policy.h.
{ return get_le64_signed(p); }
References get_le64_signed().
isBE()
VV bool LEPolicy::isBE () inline
Definition at line 165 of file bele_policy.h.
{ return false; }
isLE()
VV bool LEPolicy::isLE () inline
Definition at line 166 of file bele_policy.h.
{ return true; }
set16()
V void LEPolicy::set16 (void * p, unsigned v) inline
Definition at line 177 of file bele_policy.h.
{ set_le16(p, v); }
References set_le16().
set24()
V void LEPolicy::set24 (void * p, unsigned v) inline
Definition at line 178 of file bele_policy.h.
{ set_le24(p, v); }
References set_le24().
set32()
V void LEPolicy::set32 (void * p, unsigned v) inline
Definition at line 179 of file bele_policy.h.
{ set_le32(p, v); }
References set_le32().
set64()
V void LEPolicy::set64 (void * p, upx_uint64_t v) inline
Definition at line 180 of file bele_policy.h.
{ set_le64(p, v); }
References set_le64().
u16_compare()
S LEPolicy::u16_compare (const void * a, const void * b) inline
Definition at line 187 of file bele_policy.h.
{ return le16_compare(a, b); }
References b, and le16_compare().
u16_compare_signed()
S LEPolicy::u16_compare_signed (const void * a, const void * b) inline
Definition at line 192 of file bele_policy.h.
{ return le16_compare_signed(a, b); }
References b, and le16_compare_signed().
u24_compare()
S LEPolicy::u24_compare (const void * a, const void * b) inline
Definition at line 188 of file bele_policy.h.
{ return le24_compare(a, b); }
References b, and le24_compare().
u24_compare_signed()
S LEPolicy::u24_compare_signed (const void * a, const void * b) inline
Definition at line 193 of file bele_policy.h.
{ return le24_compare_signed(a, b); }
References b, and le24_compare_signed().
u32_compare()
S LEPolicy::u32_compare (const void * a, const void * b) inline
Definition at line 189 of file bele_policy.h.
{ return le32_compare(a, b); }
References b, and le32_compare().
u32_compare_signed()
S LEPolicy::u32_compare_signed (const void * a, const void * b) inline
Definition at line 194 of file bele_policy.h.
{ return le32_compare_signed(a, b); }
References b, and le32_compare_signed().
u64_compare()
S LEPolicy::u64_compare (const void * a, const void * b) inline
Definition at line 190 of file bele_policy.h.
{ return le64_compare(a, b); }
References b, and le64_compare().
u64_compare_signed()
S LEPolicy::u64_compare_signed (const void * a, const void * b) inline
Definition at line 195 of file bele_policy.h.
{ return le64_compare_signed(a, b); }
References b, and le64_compare_signed().
The documentation for this struct was generated from the following file:
src/bele_policy.h