My Project: upx::OptVar< T, default_value_, min_value_, max_value_ > Struct Template Reference
upx::OptVar< T, default_value_, min_value_, max_value_ > Struct Template Reference final
OptVar and oassign.
#include <cxxlib.h>
Public Types
typedef T value_type
Public Member Functions
constexpr operator T () const noexcept
void assertValue () const noexcept
constexpr OptVar () noexcept
OptVar & operator= (const T &other) noexcept
void reset () noexcept
Static Public Member Functions
static void assertValue (const T &value) noexcept
Public Attributes
value_type value = default_value
bool is_set = false
Static Public Attributes
static constexpr T default_value = default_value_
static constexpr T min_value = min_value_
static constexpr T max_value = max_value_
Detailed Description
template<class T, T default_value_, T min_value_, T max_value_>
struct upx::OptVar< T, default_value_, min_value_, max_value_ >
OptVar and oassign.
Definition at line 664 of file cxxlib.h.
Member Typedef Documentation
value_type
template<class T , T default_value_, T min_value_, T max_value_> typedef T upx::OptVar< T, default_value_, min_value_, max_value_ >::value_type
Definition at line 666 of file cxxlib.h.
Constructor & Destructor Documentation
OptVar()
template<class T , T default_value_, T min_value_, T max_value_> constexpr upx::OptVar< T, default_value_, min_value_, max_value_ >::OptVar () inline constexpr noexcept
Definition at line 683 of file cxxlib.h.
{}
Member Function Documentation
assertValue() [1/2]
template<class T , T default_value_, T min_value_, T max_value_> void upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue () const inline noexcept
Definition at line 681 of file cxxlib.h.
{ assertValue(value); }
References upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue(), and upx::OptVar< T, default_value_, min_value_, max_value_ >::value.
Referenced by upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue(), upx::OptVar< T, default_value_, min_value_, max_value_ >::operator=(), and prepare_result().
assertValue() [2/2]
template<class T , T default_value_, T min_value_, T max_value_> static void upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue (const T & value) inline static noexcept
Definition at line 675 of file cxxlib.h.
{
        // info: this generates annoying warnings "unsigned >= 0 is always true"
        // assert_noexcept(value >= min_value);
        assert_noexcept(value == min_value || value >= min_value + 1);
        assert_noexcept(value <= max_value);
    }
References assert_noexcept, upx::OptVar< T, default_value_, min_value_, max_value_ >::max_value, upx::OptVar< T, default_value_, min_value_, max_value_ >::min_value, and upx::OptVar< T, default_value_, min_value_, max_value_ >::value.
operator T()
template<class T , T default_value_, T min_value_, T max_value_> constexpr upx::OptVar< T, default_value_, min_value_, max_value_ >::operator T () const inline constexpr noexcept
Definition at line 673 of file cxxlib.h.
{ return value; }
References upx::OptVar< T, default_value_, min_value_, max_value_ >::value.
operator=()
template<class T , T default_value_, T min_value_, T max_value_> OptVar & upx::OptVar< T, default_value_, min_value_, max_value_ >::operator= (const T & other) inline noexcept
Definition at line 684 of file cxxlib.h.
                                               { // copy constructor
        assertValue(other);
        value = other;
        is_set = true;
        return *this;
    }
References upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue(), upx::OptVar< T, default_value_, min_value_, max_value_ >::is_set, and upx::OptVar< T, default_value_, min_value_, max_value_ >::value.
reset()
template<class T , T default_value_, T min_value_, T max_value_> void upx::OptVar< T, default_value_, min_value_, max_value_ >::reset () inline noexcept
Definition at line 691 of file cxxlib.h.
{
        value = default_value;
        is_set = false;
    }
References upx::OptVar< T, default_value_, min_value_, max_value_ >::default_value, upx::OptVar< T, default_value_, min_value_, max_value_ >::is_set, and upx::OptVar< T, default_value_, min_value_, max_value_ >::value.
Referenced by lzma_compress_config_t::reset(), and zlib_compress_config_t::reset().
Member Data Documentation
default_value
template<class T , T default_value_, T min_value_, T max_value_> constexpr T upx::OptVar< T, default_value_, min_value_, max_value_ >::default_value = default_value_ static constexpr
Definition at line 667 of file cxxlib.h.
Referenced by prepare_result(), and upx::OptVar< T, default_value_, min_value_, max_value_ >::reset().
is_set
template<class T , T default_value_, T min_value_, T max_value_> bool upx::OptVar< T, default_value_, min_value_, max_value_ >::is_set = false
Definition at line 697 of file cxxlib.h.
Referenced by upx::OptVar< T, default_value_, min_value_, max_value_ >::operator=(), and upx::OptVar< T, default_value_, min_value_, max_value_ >::reset().
max_value
template<class T , T default_value_, T min_value_, T max_value_> constexpr T upx::OptVar< T, default_value_, min_value_, max_value_ >::max_value = max_value_ static constexpr
Definition at line 669 of file cxxlib.h.
Referenced by upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue().
min_value
template<class T , T default_value_, T min_value_, T max_value_> constexpr T upx::OptVar< T, default_value_, min_value_, max_value_ >::min_value = min_value_ static constexpr
Definition at line 668 of file cxxlib.h.
Referenced by upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue().
value
template<class T , T default_value_, T min_value_, T max_value_> value_type upx::OptVar< T, default_value_, min_value_, max_value_ >::value = default_value
Definition at line 696 of file cxxlib.h.
Referenced by upx::OptVar< T, default_value_, min_value_, max_value_ >::assertValue(), upx::OptVar< T, default_value_, min_value_, max_value_ >::operator T(), upx::OptVar< T, default_value_, min_value_, max_value_ >::operator=(), and upx::OptVar< T, default_value_, min_value_, max_value_ >::reset().
The documentation for this struct was generated from the following file:
src/util/cxxlib.h