My Project: Ptr< T > Struct Template Reference
Ptr< T > Struct Template Reference
Ptr.
#include <xspan_impl_ptr.h>
Public Types
typedef T element_type
typedef std::add_lvalue_reference< T >::type reference
typedef std::add_pointer< T >::type pointer
Public Member Functions
operator pointer () const noexcept
forceinline ~CSelf () noexcept
noinline void invalidate ()
CSelf ()
CSelf (pointer p)
template<class U >
CSelf (U *p, XSPAN_REQUIRES_CONVERTIBLE_A)
CSelf (const Self &other)
template<class U >
CSelf (const CSelf< U > &other, XSPAN_REQUIRES_CONVERTIBLE_A)
Self & assign (const Self &other)
Self & operator= (const Self &other)
template<class U >
operator= (U *other)
template<class U >
operator= (const CSelf< U > &other)
template<class U >
CSelf< U > type_cast () const
bool operator== (pointer other) const noexcept
template<class U >
operator== (U *other) const noexcept
template<class U >
operator== (const Ptr< U > &other) const noexcept
reference operator* () const
reference operator[] (ptrdiff_t i) const
pointer operator-> () const
Self & operator++ ()
Self operator++ (int)
Self & operator-- ()
Self operator-- (int)
Self & operator+= (ptrdiff_t n)
Self & operator-= (ptrdiff_t n)
Self operator+ (ptrdiff_t n) const
Self operator- (ptrdiff_t n) const
pointer raw_ptr () const noexcept
pointer raw_bytes (size_t bytes) const
Private Types
typedef CSelf< T > Self
Private Member Functions
pointer ensurePtr () const
forceinline void assertInvariants () const noexcept
Static Private Member Functions
static pointer makePtr (pointer p)
static forceinline pointer check_deref (pointer p) noexcept
static forceinline pointer check_deref (pointer p, ptrdiff_t n) noexcept
static forceinline pointer check_add (pointer p, ptrdiff_t n) noexcept
Private Attributes
pointer ptr
Friends
template<class >
struct CSelf
Detailed Description
template<class T>
struct Ptr< T >
Ptr.
Definition at line 36 of file xspan_impl_ptr.h.
Member Typedef Documentation
element_type
template<class T > typedef T Ptr< T >::element_type
Definition at line 46 of file xspan_impl_ptr.h.
pointer
template<class T > typedef std::add_pointer<T>::type Ptr< T >::pointer
Definition at line 48 of file xspan_impl_ptr.h.
reference
template<class T > typedef std::add_lvalue_reference<T>::type Ptr< T >::reference
Definition at line 47 of file xspan_impl_ptr.h.
Self
template<class T > typedef CSelf<T> Ptr< T >::Self private
Definition at line 39 of file xspan_impl_ptr.h.
Constructor & Destructor Documentation
~CSelf()
template<class T > forceinline Ptr< T >::~CSelf () inline noexcept
Definition at line 76 of file xspan_impl_ptr.h.
{}
Member Function Documentation
assertInvariants()
template<class T > forceinline void Ptr< T >::assertInvariants () const inline private noexcept
Definition at line 58 of file xspan_impl_ptr.h.
{}
Referenced by Ptr< T >::assign(), Ptr< T >::CSelf(), Ptr< T >::invalidate(), and Ptr< T >::raw_bytes().
assign()
template<class T > Self & Ptr< T >::assign (const Self & other) inline
Definition at line 99 of file xspan_impl_ptr.h.
{
        assertInvariants();
        other.assertInvariants();
        ptr = other.ptr;
        assertInvariants();
        return *this;
    }
References Ptr< T >::assertInvariants(), and Ptr< T >::ptr.
Referenced by Ptr< T >::operator=().
check_add()
template<class T > static forceinline pointer Ptr< T >::check_add (pointer p, ptrdiff_t n) inline static private noexcept
Definition at line 202 of file xspan_impl_ptr.h.
{ return p + n; }
References n.
Referenced by Ptr< T >::operator+(), Ptr< T >::operator++(), Ptr< T >::operator+=(), Ptr< T >::operator-(), Ptr< T >::operator--(), and Ptr< T >::operator-=().
check_deref() [1/2]
template<class T > static forceinline pointer Ptr< T >::check_deref (pointer p) inline static private noexcept
Definition at line 200 of file xspan_impl_ptr.h.
{ return p; }
Referenced by Ptr< T >::operator*(), Ptr< T >::operator->(), and Ptr< T >::operator[]().
check_deref() [2/2]
template<class T > static forceinline pointer Ptr< T >::check_deref (pointer p, ptrdiff_t n) inline static private noexcept
Definition at line 201 of file xspan_impl_ptr.h.
{ return p + n; }
References n.
CSelf() [1/5]
template<class T > Ptr< T >::CSelf () inline
Definition at line 83 of file xspan_impl_ptr.h.
{ assertInvariants(); }
References Ptr< T >::assertInvariants().
CSelf() [2/5]
template<class T > template<class U > Ptr< T >::CSelf (const CSelf< U > & other, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 95 of file xspan_impl_ptr.h.
                                                               : ptr(other.ptr) {
        assertInvariants();
    }
References Ptr< T >::assertInvariants().
CSelf() [3/5]
template<class T > Ptr< T >::CSelf (const Self & other) inline
Definition at line 93 of file xspan_impl_ptr.h.
: ptr(other.ptr) { assertInvariants(); }
References Ptr< T >::assertInvariants().
CSelf() [4/5]
template<class T > Ptr< T >::CSelf (pointer p) inline
Definition at line 86 of file xspan_impl_ptr.h.
: ptr(makePtr(p)) { assertInvariants(); }
References Ptr< T >::assertInvariants().
CSelf() [5/5]
template<class T > template<class U > Ptr< T >::CSelf (U * p, XSPAN_REQUIRES_CONVERTIBLE_A) inline
Definition at line 88 of file xspan_impl_ptr.h.
                                              : ptr(makePtr(p)) {
        assertInvariants();
    }
References Ptr< T >::assertInvariants().
ensurePtr()
template<class T > pointer Ptr< T >::ensurePtr () const inline private
Definition at line 56 of file xspan_impl_ptr.h.
{ return ptr; }
References Ptr< T >::ptr.
invalidate()
template<class T > noinline void Ptr< T >::invalidate () inline
Definition at line 78 of file xspan_impl_ptr.h.
{
        assertInvariants();
        ptr_invalidate_and_poison(ptr); // point to non-null invalid address
        assertInvariants();
    }
References Ptr< T >::assertInvariants(), Ptr< T >::ptr, and ptr_invalidate_and_poison().
makePtr()
template<class T > static pointer Ptr< T >::makePtr (pointer p) inline static private
Definition at line 54 of file xspan_impl_ptr.h.
{ return p; }
operator pointer()
template<class T > Ptr< T >::operator pointer () const inline noexcept
Definition at line 64 of file xspan_impl_ptr.h.
{ return ptr; }
References Ptr< T >::ptr.
operator*()
template<class T > reference Ptr< T >::operator* () const inline
Definition at line 149 of file xspan_impl_ptr.h.
{ return *check_deref(ptr); }
References Ptr< T >::check_deref(), and Ptr< T >::ptr.
operator+()
template<class T > Self Ptr< T >::operator+ (ptrdiff_t n) const inline
Definition at line 185 of file xspan_impl_ptr.h.
{
        pointer p = check_add(ptr, n);
        return Self(p);
    }
References Ptr< T >::check_add(), n, and Ptr< T >::ptr.
operator++() [1/2]
template<class T > Self & Ptr< T >::operator++ () inline
Definition at line 157 of file xspan_impl_ptr.h.
                       {
        ptr = check_add(ptr, 1);
        return *this;
    }
References Ptr< T >::check_add(), and Ptr< T >::ptr.
operator++() [2/2]
template<class T > Self Ptr< T >::operator++ (int) inline
Definition at line 161 of file xspan_impl_ptr.h.
{
        Self tmp = *this;
        ++*this;
        return tmp;
    }
operator+=()
template<class T > Self & Ptr< T >::operator+= (ptrdiff_t n) inline
Definition at line 176 of file xspan_impl_ptr.h.
{
        ptr = check_add(ptr, n);
        return *this;
    }
References Ptr< T >::check_add(), n, and Ptr< T >::ptr.
operator-()
template<class T > Self Ptr< T >::operator- (ptrdiff_t n) const inline
Definition at line 189 of file xspan_impl_ptr.h.
{
        pointer p = check_add(ptr, -n);
        return Self(p);
    }
References Ptr< T >::check_add(), n, and Ptr< T >::ptr.
operator--() [1/2]
template<class T > Self & Ptr< T >::operator-- () inline
Definition at line 166 of file xspan_impl_ptr.h.
                       {
        ptr = check_add(ptr, -1);
        return *this;
    }
References Ptr< T >::check_add(), and Ptr< T >::ptr.
operator--() [2/2]
template<class T > Self Ptr< T >::operator-- (int) inline
Definition at line 170 of file xspan_impl_ptr.h.
{
        Self tmp = *this;
        --*this;
        return tmp;
    }
operator-=()
template<class T > Self & Ptr< T >::operator-= (ptrdiff_t n) inline
Definition at line 180 of file xspan_impl_ptr.h.
{
        ptr = check_add(ptr, -n);
        return *this;
    }
References Ptr< T >::check_add(), n, and Ptr< T >::ptr.
operator->()
template<class T > pointer Ptr< T >::operator-> () const inline
Definition at line 155 of file xspan_impl_ptr.h.
{ return check_deref(ptr); }
References Ptr< T >::check_deref(), and Ptr< T >::ptr.
operator=() [1/3]
template<class T > template<class U > Ptr< T >::operator= (const CSelf< U > & other) inline
Definition at line 121 of file xspan_impl_ptr.h.
{
        // assert(0);
        return assign(Self(other));
    }
References Ptr< T >::assign().
operator=() [2/3]
template<class T > Self & Ptr< T >::operator= (const Self & other) inline
Definition at line 108 of file xspan_impl_ptr.h.
{ return assign(other); }
References Ptr< T >::assign().
operator=() [3/3]
template<class T > template<class U > Ptr< T >::operator= (U * other) inline
Definition at line 113 of file xspan_impl_ptr.h.
{
        // assert(0);
        return assign(Self(other));
    }
References Ptr< T >::assign().
operator==() [1/3]
template<class T > template<class U > Ptr< T >::operator== (const Ptr< U > & other) const inline noexcept
Definition at line 144 of file xspan_impl_ptr.h.
{
        return ptr == other.ptr;
    }
References Ptr< T >::ptr.
operator==() [2/3]
template<class T > bool Ptr< T >::operator== (pointer other) const inline noexcept
Definition at line 136 of file xspan_impl_ptr.h.
{ return ptr == other; }
References Ptr< T >::ptr.
operator==() [3/3]
template<class T > template<class U > Ptr< T >::operator== (U * other) const inline noexcept
Definition at line 139 of file xspan_impl_ptr.h.
{
        return ptr == other;
    }
References Ptr< T >::ptr.
operator[]()
template<class T > reference Ptr< T >::operator[] (ptrdiff_t i) const inline
Definition at line 152 of file xspan_impl_ptr.h.
{ return *check_deref(ptr, i); }
References Ptr< T >::check_deref(), and Ptr< T >::ptr.
raw_bytes()
template<class T > pointer Ptr< T >::raw_bytes (size_t bytes) const inline
Definition at line 207 of file xspan_impl_ptr.h.
{
        assertInvariants();
        if (bytes > 0) {
            if very_unlikely (ptr == nullptr)
                xspan_fail_nullptr();
        }
        return ptr;
    }
References Ptr< T >::assertInvariants(), Ptr< T >::ptr, very_unlikely, and xspan_fail_nullptr().
Referenced by raw_bytes(), and raw_index_bytes().
raw_ptr()
template<class T > pointer Ptr< T >::raw_ptr () const inline noexcept
Definition at line 205 of file xspan_impl_ptr.h.
{ return ptr; }
References Ptr< T >::ptr.
Referenced by raw_index_bytes().
type_cast()
template<class T > template<class U > CSelf< U > Ptr< T >::type_cast () const inline
Definition at line 128 of file xspan_impl_ptr.h.
{
        typedef CSelf<U> R;
        typedef typename R::pointer rpointer;
        return R(upx::ptr_static_cast<rpointer>(ptr));
    }
References Ptr< T >::ptr.
Friends And Related Function Documentation
CSelf
template<class T > template<class > friend struct CSelf friend
Definition at line 44 of file xspan_impl_ptr.h.
Member Data Documentation
ptr
template<class T > pointer Ptr< T >::ptr private
Definition at line 51 of file xspan_impl_ptr.h.
Referenced by Ptr< T >::assign(), Ptr< T >::ensurePtr(), Ptr< T >::invalidate(), Ptr< T >::operator pointer(), Ptr< T >::operator*(), Ptr< T >::operator+(), Ptr< T >::operator++(), Ptr< T >::operator+=(), Ptr< T >::operator-(), Ptr< T >::operator--(), Ptr< T >::operator-=(), Ptr< T >::operator->(), Ptr< T >::operator==(), Ptr< T >::operator[](), Ptr< T >::raw_bytes(), Ptr< T >::raw_ptr(), and Ptr< T >::type_cast().
The documentation for this struct was generated from the following file:
src/util/xspan_impl_ptr.h