My Project: src/filter/sw.h File Reference
sw.h File Reference
Macros
#define SW16(f, cond, get, set)
16-bit swaptrick ("naive")
#define SW32(f, cond, get, set)
32-bit swaptrick ("naive")
Functions
static int f_sw16_e8 (Filter *f)
static int f_sw16_e9 (Filter *f)
static int f_sw16_e8e9 (Filter *f)
static int u_sw16_e8 (Filter *f)
static int u_sw16_e9 (Filter *f)
static int u_sw16_e8e9 (Filter *f)
static int s_sw16_e8 (Filter *f)
static int s_sw16_e9 (Filter *f)
static int s_sw16_e8e9 (Filter *f)
static int f_sw32_e8 (Filter *f)
static int f_sw32_e9 (Filter *f)
static int f_sw32_e8e9 (Filter *f)
static int u_sw32_e8 (Filter *f)
static int u_sw32_e9 (Filter *f)
static int u_sw32_e8e9 (Filter *f)
static int s_sw32_e8 (Filter *f)
static int s_sw32_e9 (Filter *f)
static int s_sw32_e8e9 (Filter *f)
Macro Definition Documentation
SW16
#define SW16 (f, cond, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 3;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b));                                                                        \
            f->calls++;                                                                            \
            b += 2 - 1;                                                                            \
        }                                                                                          \
    } while (++b < b_end);                                                                         \
    if (f->lastcall)                                                                               \
        f->lastcall += 2;                                                                          \
    return 0;
16-bit swaptrick ("naive")
Definition at line 32 of file sw.h.
SW32
#define SW32 (f, cond, get, set)
Value:
    byte *b = f->buf;                                                                              \
    byte *b_end = b + f->buf_len - 5;                                                              \
    do {                                                                                           \
        if (cond) {                                                                                \
            b += 1;                                                                                \
            unsigned a = (unsigned) (b - f->buf);                                                  \
            f->lastcall = a;                                                                       \
            set(b, get(b));                                                                        \
            f->calls++;                                                                            \
            b += 4 - 1;                                                                            \
        }                                                                                          \
    } while (++b < b_end);                                                                         \
    if (f->lastcall)                                                                               \
        f->lastcall += 4;                                                                          \
    return 0;
32-bit swaptrick ("naive")
Definition at line 76 of file sw.h.
Function Documentation
f_sw16_e8()
static int f_sw16_e8 (Filter * f) static
Definition at line 50 of file sw.h.
{ SW16(f, (*b == 0xe8), get_le16, set_be16) }
References b, get_le16(), set_be16(), and SW16.
f_sw16_e8e9()
static int f_sw16_e8e9 (Filter * f) static
Definition at line 54 of file sw.h.
{ SW16(f, (*b == 0xe8 || *b == 0xe9), get_le16, set_be16) }
References b, get_le16(), set_be16(), and SW16.
f_sw16_e9()
static int f_sw16_e9 (Filter * f) static
Definition at line 52 of file sw.h.
{ SW16(f, (*b == 0xe9), get_le16, set_be16) }
References b, get_le16(), set_be16(), and SW16.
f_sw32_e8()
static int f_sw32_e8 (Filter * f) static
Definition at line 94 of file sw.h.
{ SW32(f, (*b == 0xe8), get_le32, set_be32) }
References b, get_le32(), set_be32(), and SW32.
f_sw32_e8e9()
static int f_sw32_e8e9 (Filter * f) static
Definition at line 98 of file sw.h.
{ SW32(f, (*b == 0xe8 || *b == 0xe9), get_le32, set_be32) }
References b, get_le32(), set_be32(), and SW32.
f_sw32_e9()
static int f_sw32_e9 (Filter * f) static
Definition at line 96 of file sw.h.
{ SW32(f, (*b == 0xe9), get_le32, set_be32) }
References b, get_le32(), set_be32(), and SW32.
s_sw16_e8()
static int s_sw16_e8 (Filter * f) static
Definition at line 64 of file sw.h.
{ SW16(f, (*b == 0xe8), get_le16, set_dummy) }
References b, get_le16(), set_dummy, and SW16.
s_sw16_e8e9()
static int s_sw16_e8e9 (Filter * f) static
Definition at line 68 of file sw.h.
{ SW16(f, (*b == 0xe8 || *b == 0xe9), get_le16, set_dummy) }
References b, get_le16(), set_dummy, and SW16.
s_sw16_e9()
static int s_sw16_e9 (Filter * f) static
Definition at line 66 of file sw.h.
{ SW16(f, (*b == 0xe9), get_le16, set_dummy) }
References b, get_le16(), set_dummy, and SW16.
s_sw32_e8()
static int s_sw32_e8 (Filter * f) static
Definition at line 108 of file sw.h.
{ SW32(f, (*b == 0xe8), get_le32, set_dummy) }
References b, get_le32(), set_dummy, and SW32.
s_sw32_e8e9()
static int s_sw32_e8e9 (Filter * f) static
Definition at line 112 of file sw.h.
{ SW32(f, (*b == 0xe8 || *b == 0xe9), get_le32, set_dummy) }
References b, get_le32(), set_dummy, and SW32.
s_sw32_e9()
static int s_sw32_e9 (Filter * f) static
Definition at line 110 of file sw.h.
{ SW32(f, (*b == 0xe9), get_le32, set_dummy) }
References b, get_le32(), set_dummy, and SW32.
u_sw16_e8()
static int u_sw16_e8 (Filter * f) static
Definition at line 57 of file sw.h.
{ SW16(f, (*b == 0xe8), get_be16, set_le16) }
References b, get_be16(), set_le16(), and SW16.
u_sw16_e8e9()
static int u_sw16_e8e9 (Filter * f) static
Definition at line 61 of file sw.h.
{ SW16(f, (*b == 0xe8 || *b == 0xe9), get_be16, set_le16) }
References b, get_be16(), set_le16(), and SW16.
u_sw16_e9()
static int u_sw16_e9 (Filter * f) static
Definition at line 59 of file sw.h.
{ SW16(f, (*b == 0xe9), get_be16, set_le16) }
References b, get_be16(), set_le16(), and SW16.
u_sw32_e8()
static int u_sw32_e8 (Filter * f) static
Definition at line 101 of file sw.h.
{ SW32(f, (*b == 0xe8), get_be32, set_le32) }
References b, get_be32(), set_le32(), and SW32.
u_sw32_e8e9()
static int u_sw32_e8e9 (Filter * f) static
Definition at line 105 of file sw.h.
{ SW32(f, (*b == 0xe8 || *b == 0xe9), get_be32, set_le32) }
References b, get_be32(), set_le32(), and SW32.
u_sw32_e9()
static int u_sw32_e9 (Filter * f) static
Definition at line 103 of file sw.h.
{ SW32(f, (*b == 0xe9), get_be32, set_le32) }
References b, get_be32(), set_le32(), and SW32.