My Project: src/ui.cpp File Reference
ui.cpp File Reference
#include "conf.h"
#include "file.h"
#include "packer.h"
#include "ui.h"
#include "console/screen.h"
Classes
struct UiPacker::State
Enumerations
enum {
M_QUIET , M_INFO , M_MSG , M_CB_TERM ,
M_CB_SCREEN
}
Functions
static void init_global_constants (void) noexcept
static const char * mkline (upx_uint64_t fu_len, upx_uint64_t fc_len, upx_uint64_t u_len, upx_uint64_t c_len, const char *format_name, const char *filename, bool decompress=false)
Variables
static const char header_line1 [] = " File size Ratio Format Name\n"
constants
static const char header_line2 [] = " -------------------- ------ ----------- -----------\n"
static const char progress_filler [4+1] = ".*[]"
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
M_QUIET
M_INFO
M_MSG
M_CB_TERM
M_CB_SCREEN
Definition at line 41 of file ui.cpp.
     {
    M_QUIET,    // nothing at all '-qqq'
    M_INFO,     // print a one line info after compression '-qq'
    M_MSG,      // print "compressing", then "\r" and M_INFO
    M_CB_TERM,  // 1 line callback using stdout
    M_CB_SCREEN // 2 line callback using screen
};
Function Documentation
init_global_constants()
static void init_global_constants (void) static noexcept
Definition at line 103 of file ui.cpp.
{
#if 0 && (ACC_OS_DOS16 || ACC_OS_DOS32)
    // FIXME: should test codepage here
#if 1 && (ACC_OS_DOS32) && defined(__DJGPP__)
    /* check for Windows NT/2000/XP */
    if (_get_dos_version(1) == 0x0532)
        return;
#endif
    char *p;
    for (p = header_line2; *p; p++)
        if (*p == '-')
            *p = '\xc4';
    //strcpy(progress_filler, "\x07\xb0[]");
    //strcpy(progress_filler, "\x07\xb1[]");
    strcpy(progress_filler, "\xf9\xfe[]");
#endif
}
References header_line2, progress_filler, and strcpy().
Referenced by UiPacker::UiPacker().
mkline()
static const char * mkline (upx_uint64_t fu_len, upx_uint64_t fc_len, upx_uint64_t u_len, upx_uint64_t c_len, const char * format_name, const char * filename, bool decompress = false) static
Definition at line 128 of file ui.cpp.
{
    static char buf[2048]; // static! // TODO later: check if affected by WITH_THREADS
    char r[7 + 1];
    char fn[15 + 1];
    const char *f;
    // Large ratios can happen because of overlays that are
    // appended after a program is packed.
    unsigned ratio = get_ratio(fu_len, fc_len);
    if (ratio >= 1000 * 1000)
        strcpy(r, "overlay");
    else
        upx_safe_snprintf(r, sizeof(r), "%3u.%02u%%", ratio / 10000, (ratio % 10000) / 100);
    if (decompress)
        f = "%10lld <-%10lld  %7s %15s %s";
    else
        f = "%10lld ->%10lld  %7s %15s %s";
    center_string(fn, sizeof(fn), format_name);
    assert(strlen(fn) == 15);
    upx_safe_snprintf(buf, sizeof(buf), f, (long long) fu_len, (long long) fc_len, r, fn, filename);
    UNUSED(u_len);
    UNUSED(c_len);
    return buf;
}
References buf, center_string(), get_ratio(), strcpy(), strlen, UNUSED, and upx_safe_snprintf().
Referenced by UiPacker::uiList(), UiPacker::uiListTotal(), UiPacker::uiPackEnd(), and UiPacker::uiUnpackEnd().
Variable Documentation
header_line1
const char header_line1[] = " File size Ratio Format Name\n" static
constants
Definition at line 98 of file ui.cpp.
Referenced by UiPacker::uiHeader().
header_line2
const char header_line2[] = " -------------------- ------ ----------- -----------\n" static
Definition at line 99 of file ui.cpp.
Referenced by init_global_constants(), UiPacker::uiHeader(), and UiPacker::uiListTotal().
progress_filler
const char progress_filler[4+1] = ".*[]" static
Definition at line 101 of file ui.cpp.
Referenced by UiPacker::doCallback(), and init_global_constants().