My Project: src/util/util.h File Reference
util.h File Reference
Macros
#define New(type, n) new type[mem_size_get_n(sizeof(type), (n))]
#define upx_qsort ::qsort
Typedefs
typedef int(__acc_cdecl_qsort * upx_compare_func_t) (const void *, const void *)
typedef void(* upx_sort_func_t) (void *array, size_t n, size_t element_size, upx_compare_func_t)
Functions
bool mem_size_valid_bytes (upx_uint64_t bytes) noexcept
upx_rsize_t and mem_size: assert sane memory buffer sizes to protect against integer overflows and malicious header fields see C 11 standard, Annex K
bool mem_size_valid (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1=0, upx_uint64_t extra2=0) noexcept
upx_rsize_t and mem_size: assert sane memory buffer sizes to protect against integer overflows and malicious header fields see C 11 standard, Annex K
upx_rsize_t mem_size (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1, upx_uint64_t extra2=0) may_throw
upx_rsize_t mem_size (upx_uint64_t element_size, upx_uint64_t n) may_throw
upx_rsize_t mem_size_get_n (upx_uint64_t element_size, upx_uint64_t n) may_throw
void mem_size_assert (upx_uint64_t element_size, upx_uint64_t n) may_throw
forceinline upx_ptraddr_t ptr_get_address (const void *p) noexcept
ptr util
forceinline upx_ptraddr_t ptr_get_address (upx_uintptr_t p) noexcept
forceinline upx_sptraddr_t ptraddr_diff (const void *a, const void *b) noexcept
template<size_t Alignment>
forceinline bool ptr_is_aligned (const void *p) noexcept
forceinline bool ptr_is_aligned (const void *p, size_t alignment) noexcept
int ptr_diff_bytes (const void *a, const void *b) may_throw
ptr util
unsigned ptr_udiff_bytes (const void *a, const void *b) may_throw
template<class T , class U >
std::enable_if< sizeof(T)==1 &&sizeof(U)==1, int >::type ptr_diff (const T *a, const U *b) may_throw
template<class T , class U >
std::enable_if< sizeof(T)==1 &&sizeof(U)==1, unsigned >::type ptr_udiff (const T *a, const U *b) may_throw
noinline void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size) may_throw
noinline void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size, upx_ptraddr_t c, size_t c_size) may_throw
forceinline void ptr_check_no_overlap (const void *a, size_t a_size, const void *b, size_t b_size) may_throw
forceinline void ptr_check_no_overlap (const void *a, size_t a_size, const void *b, size_t b_size, const void *c, size_t c_size) may_throw
template<class T >
void ptr_invalidate_and_poison (T *(&ptr)) noexcept
noinline void * upx_calloc (size_t n, size_t element_size) may_throw
stdlib
noinline const char * upx_getenv (const char *envvar) noexcept
stdlib
noinline void upx_memswap (void *a, void *b, size_t bytes) noexcept
noinline void upx_rand_init (void) noexcept
noinline int upx_rand (void) noexcept
void upx_gnomesort (void *array, size_t n, size_t element_size, upx_compare_func_t compare)
void upx_shellsort_memswap (void *array, size_t n, size_t element_size, upx_compare_func_t compare)
void upx_shellsort_memcpy (void *array, size_t n, size_t element_size, upx_compare_func_t compare)
template<size_t ElementSize>
void upx_std_stable_sort (void *array, size_t n, upx_compare_func_t compare)
int find (const void *b, int blen, const void *what, int wlen) noexcept
misc support functions
int find_be16 (const void *b, int blen, unsigned what) noexcept
int find_be32 (const void *b, int blen, unsigned what) noexcept
int find_be64 (const void *b, int blen, upx_uint64_t what) noexcept
int find_le16 (const void *b, int blen, unsigned what) noexcept
int find_le32 (const void *b, int blen, unsigned what) noexcept
int find_le64 (const void *b, int blen, upx_uint64_t what) noexcept
int mem_replace (void *b, int blen, const void *what, int wlen, const void *r) noexcept
char * fn_basename (const char *name)
int fn_strcmp (const char *n1, const char *n2)
char * fn_strlwr (char *n)
bool fn_has_ext (const char *name, const char *ext, bool ignore_case=true)
bool file_exists (const char *name)
bool maketempname (char *ofilename, size_t size, const char *ifilename, const char *ext, bool force=true)
bool makebakname (char *ofilename, size_t size, const char *ifilename, bool force=true)
bool is_envvar_true (const char *envvar, const char *alternate_name=nullptr) noexcept
misc
unsigned get_ratio (upx_uint64_t u_len, upx_uint64_t c_len)
return compression ratio, where 100% == 1000*1000 == 1e6
bool set_method_name (char *buf, size_t size, int method, int level)
void center_string (char *buf, size_t size, const char *s)
Macro Definition Documentation
New
#define New (type, n) new type[mem_size_get_n(sizeof(type), (n))]
Definition at line 89 of file util.h.
upx_qsort
#define upx_qsort ::qsort
Definition at line 205 of file util.h.
Typedef Documentation
upx_compare_func_t
typedef int(__acc_cdecl_qsort * upx_compare_func_t) (const void *, const void *)
Definition at line 187 of file util.h.
upx_sort_func_t
typedef void(* upx_sort_func_t) (void *array, size_t n, size_t element_size, upx_compare_func_t)
Definition at line 188 of file util.h.
Function Documentation
center_string()
void center_string (char * buf, size_t size, const char * s)
Definition at line 891 of file util.cpp.
{
    size_t l1 = size - 1;
    size_t l2 = strlen(s);
    assert(size > 0);
    assert(l2 < size);
    memset(buf, ' ', l1);
    memcpy(buf + (l1 - l2) / 2, s, l2);
    buf[l1] = 0;
}
References buf, memcpy(), memset(), size(), and strlen.
Referenced by mkline().
file_exists()
bool file_exists (const char * name)
Definition at line 901 of file util.cpp.
{
    int fd, r;
    struct stat st;
    /* return true if we can open it */
    fd = open(name, O_RDONLY | O_BINARY, 0);
    if (fd >= 0) {
        (void) close(fd);
        return true;
    }
    /* return true if we can stat it */
    // mem_clear(&st);
    r = stat(name, &st);
    if (r != -1)
        return true;
/* return true if we can lstat it */
#if HAVE_LSTAT
    // mem_clear(&st);
    r = lstat(name, &st);
    if (r != -1)
        return true;
#endif
    return false;
}
References close(), O_BINARY, O_RDONLY, and open().
Referenced by makebakname(), and maketempname().
find()
int find (const void * buf, int blen, const void * what, int wlen) noexcept
misc support functions
misc support functions
Definition at line 669 of file util.cpp.
{
    // nullptr is explicitly allowed here
    if (buf == nullptr || blen < wlen || what == nullptr || wlen <= 0)
        return -1;
    const byte *b = (const byte *) buf;
    const byte first_byte = *(const byte *) what;
    blen -= wlen;
    for (int i = 0; i <= blen; i++, b++)
        if (*b == first_byte && memcmp(b, what, wlen) == 0)
            return i;
    return -1;
}
References b, buf, and memcmp().
Referenced by PeFile::canUnpack0(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), find_be16(), find_be32(), find_be64(), find_le16(), find_le32(), find_le64(), ElfLinker::init(), mem_replace(), Packer::patch_be16(), Packer::patch_be32(), Packer::patch_le16(), Packer::patch_le32(), and TEST_CASE().
find_be16()
int find_be16 (const void * b, int blen, unsigned what) noexcept
Definition at line 685 of file util.cpp.
{
    byte w[2];
    set_be16(w, what);
    return find(b, blen, w, 2);
}
References b, find(), and set_be16().
Referenced by Packer::patch_be16(), TEST_CASE(), and upx_compiler_sanity_check().
find_be32()
int find_be32 (const void * b, int blen, unsigned what) noexcept
Definition at line 691 of file util.cpp.
{
    byte w[4];
    set_be32(w, what);
    return find(b, blen, w, 4);
}
References b, find(), and set_be32().
Referenced by Packer::patch_be32(), TEST_CASE(), and upx_compiler_sanity_check().
find_be64()
int find_be64 (const void * b, int blen, upx_uint64_t what) noexcept
Definition at line 697 of file util.cpp.
{
    byte w[8];
    set_be64(w, what);
    return find(b, blen, w, 8);
}
References b, find(), and set_be64().
Referenced by TEST_CASE().
find_le16()
int find_le16 (const void * b, int blen, unsigned what) noexcept
Definition at line 703 of file util.cpp.
{
    byte w[2];
    set_le16(w, what);
    return find(b, blen, w, 2);
}
References b, find(), and set_le16().
Referenced by Packer::patch_le16(), TEST_CASE(), and upx_compiler_sanity_check().
find_le32()
int find_le32 (const void * b, int blen, unsigned what) noexcept
Definition at line 709 of file util.cpp.
{
    byte w[4];
    set_le32(w, what);
    return find(b, blen, w, 4);
}
References b, find(), and set_le32().
Referenced by Packer::checkAlreadyPacked(), PackHeader::decodePackHeaderFromBuf(), PackTmt::pack(), PackWcle::pack(), Packer::patch_le32(), Packer::patchPackHeader(), TEST_CASE(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), and upx_compiler_sanity_check().
find_le64()
int find_le64 (const void * b, int blen, upx_uint64_t what) noexcept
Definition at line 715 of file util.cpp.
{
    byte w[8];
    set_le64(w, what);
    return find(b, blen, w, 8);
}
References b, find(), and set_le64().
Referenced by TEST_CASE().
fn_basename()
char * fn_basename (const char * name)
Definition at line 808 of file util.cpp.
{
    const char *n, *nn;
    name = fn_skip_drive(name);
    for (nn = n = name; *nn; nn++)
        if (fn_is_sep(*nn))
            n = nn + 1;
    return ACC_UNCONST_CAST(char *, n);
}
References ACC_UNCONST_CAST, fn_is_sep, fn_skip_drive, and n.
Referenced by fn_has_ext(), makebakname(), maketempname(), PeFile::readSectionHeaders(), UiPacker::startCallback(), UiPacker::uiPackEnd(), UiPacker::uiUnpackEnd(), and upx_main().
fn_has_ext()
bool fn_has_ext (const char * name, const char * ext, bool ignore_case = true)
Definition at line 818 of file util.cpp.
{
    const char *n, *e;
    name = fn_basename(name);
    for (n = e = name; *n; n++)
        if (*n == '.')
            e = n;
    if (ignore_case)
        return (strcasecmp(ext, e + 1) == 0);
    else
        return (fn_strcmp(ext, e + 1) == 0);
}
References fn_basename(), fn_strcmp(), n, and strcasecmp().
Referenced by PackCom::canPack(), PackExe::canPack(), PackSys::canPack(), and PeFile::processResources().
fn_strcmp()
int fn_strcmp (const char * n1, const char * n2)
Definition at line 838 of file util.cpp.
{
    for (;;) {
        if (*n1 != *n2) {
            int c = fn_tolower(*n1) - fn_tolower(*n2);
            if (c)
                return c;
        }
        if (*n1 == 0)
            return 0;
        n1++;
        n2++;
    }
}
References fn_tolower.
Referenced by fn_has_ext(), and upx_main().
fn_strlwr()
char * fn_strlwr (char * n)
Definition at line 831 of file util.cpp.
{
    char *p;
    for (p = n; *p; p++)
        *p = (char) fn_tolower(*p);
    return n;
}
References fn_tolower, and n.
Referenced by upx_main().
get_ratio()
unsigned get_ratio (upx_uint64_t u_len, upx_uint64_t c_len)
return compression ratio, where 100% == 1000*1000 == 1e6
Definition at line 996 of file util.cpp.
{
    constexpr unsigned N = 1000 * 1000;
    if (u_len == 0)
        return c_len == 0 ? 0 : N;
    upx_uint64_t x = c_len * N;
    assert(x / N == c_len); // sanity check
    x /= u_len;
    x += 50;         // rounding; cannot overflow
    if (x >= 10 * N) // >= "1000%"
        x = 10 * N - 1;
    return ACC_ICONV(unsigned, x);
}
References ACC_ICONV, and N.
Referenced by UiPacker::doCallback(), mkline(), and TEST_CASE().
is_envvar_true()
bool is_envvar_true (const char * envvar, const char * alternate_name = nullptr) noexcept
misc
Definition at line 857 of file util.cpp.
{
    const char *e = upx_getenv(envvar);
    if (e != nullptr && e[0])
        return strcmp(e, "0") != 0;
    if (alternate_name != nullptr) {
        e = upx_getenv(alternate_name);
        if (e != nullptr && e[0])
            return strcmp(e, "0") != 0;
    }
    return false;
}
References strcmp(), and upx_getenv().
Referenced by PackMachBase< TMachClass >::canPack(), anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::check(), TEST_CASE(), upx_compiler_sanity_check(), upx_doctest_check(), and upx_main().
makebakname()
bool makebakname (char * ofilename, size_t size, const char * ifilename, bool force = true)
Definition at line 959 of file util.cpp.
{
    char *ofext = nullptr, *ofname;
    int ofile;
    if (size <= 0)
        return false;
    strcpy(ofilename, ifilename);
    for (ofname = fn_basename(ofilename); *ofname; ofname++) {
        if (*ofname == '.')
            ofext = ofname;
    }
    if (ofext == nullptr) {
        ofext = ofilename + strlen(ofilename);
        strcpy(ofext, ".~");
    } else if (strlen(ofext) < 1 + 3)
        strcat(ofilename, "~");
    else
        ofext[strlen(ofext) - 1] = '~';
    for (ofile = 0; ofile < 1000; ofile++) {
        assert(strlen(ofilename) < size);
        if (!file_exists(ofilename))
            return true;
        if (!force)
            break;
        upx_safe_snprintf(ofext, 5, ".%03d", ofile);
    }
    ofilename[0] = 0;
    return false;
}
References file_exists(), fn_basename(), size(), strcpy(), strlen, and upx_safe_snprintf().
Referenced by do_one_file().
maketempname()
bool maketempname (char * ofilename, size_t size, const char * ifilename, const char * ext, bool force = true)
Definition at line 929 of file util.cpp.
{
    char *ofext = nullptr, *ofname;
    int ofile;
    if (size <= 0)
        return false;
    strcpy(ofilename, ifilename);
    for (ofname = fn_basename(ofilename); *ofname; ofname++) {
        if (*ofname == '.')
            ofext = ofname;
    }
    if (ofext == nullptr)
        ofext = ofilename + strlen(ofilename);
    strcpy(ofext, ext);
    for (ofile = 0; ofile < 1000; ofile++) {
        assert(strlen(ofilename) < size);
        if (!file_exists(ofilename))
            return true;
        if (!force)
            break;
        upx_safe_snprintf(ofext, 5, ".%03d", ofile);
    }
    ofilename[0] = 0;
    return false;
}
References file_exists(), fn_basename(), size(), strcpy(), strlen, and upx_safe_snprintf().
Referenced by do_one_file().
mem_replace()
int mem_replace (void * b, int blen, const void * what, int wlen, const void * r) noexcept
Definition at line 743 of file util.cpp.
{
    byte *const b = (byte *) buf;
    int boff = 0;
    int count = 0;
    while (blen - boff >= wlen) {
        int off = find(b + boff, blen - boff, what, wlen);
        if (off < 0)
            break;
        boff += off;
        memcpy(b + boff, replacement, wlen);
        boff += wlen;
        count++;
    }
    return count;
}
References b, buf, find(), and memcpy().
Referenced by getIdentstr(), and TEST_CASE().
mem_size() [1/2]
upx_rsize_t mem_size (upx_uint64_t element_size, upx_uint64_t n) inline
Definition at line 50 of file util.h.
{
    upx_uint64_t bytes = element_size * n;
    if very_unlikely (element_size == 0 || element_size > UPX_RSIZE_MAX || n > UPX_RSIZE_MAX ||
                      bytes > UPX_RSIZE_MAX)
        return mem_size(element_size, n, 0, 0); // this will throw
    return ACC_ICONV(upx_rsize_t, bytes);
}
References ACC_ICONV, mem_size(), n, UPX_RSIZE_MAX, and very_unlikely.
mem_size() [2/2]
upx_rsize_t mem_size (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1, upx_uint64_t extra2 = 0)
Definition at line 73 of file util.cpp.
{
    assert(element_size > 0);
    if very_unlikely (element_size == 0 || element_size > UPX_RSIZE_MAX)
        throwCantPack("mem_size 1; take care");
    if very_unlikely (n > UPX_RSIZE_MAX)
        throwCantPack("mem_size 2; take care");
    if very_unlikely (extra1 > UPX_RSIZE_MAX)
        throwCantPack("mem_size 3; take care");
    if very_unlikely (extra2 > UPX_RSIZE_MAX)
        throwCantPack("mem_size 4; take care");
    upx_uint64_t bytes = element_size * n + extra1 + extra2; // cannot overflow
    if very_unlikely (bytes > UPX_RSIZE_MAX)
        throwCantPack("mem_size 5; take care");
    return ACC_ICONV(upx_rsize_t, bytes);
}
References ACC_ICONV, n, throwCantPack(), UPX_RSIZE_MAX, and very_unlikely.
Referenced by PeFile::Interval::add_interval(), PeFile::Reloc::add_reloc(), MemBuffer::alloc(), PeFile::canUnpack0(), LeFile::countFixups(), PackWcle::decodeFixups(), PackWcle::encodeObjectTable(), PeFile::Reloc::finish(), PackVmlinuxBase< TElfClass >::getElfSections(), MemBuffer::getSizeForCompression(), MemBuffer::getSizeForDecompression(), mem_size(), mem_size_assert(), mem_size_get_n(), MemBufferBase< T >::operator+(), MemBufferBase< T >::operator[](), PackDjgpp2::pack(), PackWcle::pack(), PeFile32::processRelocs(), PeFile64::processRelocs(), ptraddr_check_no_overlap(), raw_bytes(), raw_index_bytes(), InputFile::read(), LeFile::readImage(), PeFile::readSectionHeaders(), realloc_array(), PeFile::rebuildImports(), PeFile::rebuildRelocs(), PeFile::Reloc::Reloc(), PeFile::Resource::res_dir::Sizeof(), TEST_CASE(), Packer::unoptimizeReloc(), PackDjgpp2::unpack(), PackTmt::unpack(), PackWcle::unpack(), upx_calloc(), and OutputFile::write().
mem_size_assert()
void mem_size_assert (upx_uint64_t element_size, upx_uint64_t n) inline
Definition at line 65 of file util.h.
{
    (void) mem_size(element_size, n); // assert size
}
References mem_size(), and n.
Referenced by Packer::optimizeReloc(), PackerBase::PackerBase(), FileBase::seek(), OutputFile::seek(), Packer::unoptimizeReloc(), upx_shellsort_memcpy(), upx_shellsort_memswap(), and upx_std_stable_sort().
mem_size_get_n()
upx_rsize_t mem_size_get_n (upx_uint64_t element_size, upx_uint64_t n) inline
Definition at line 59 of file util.h.
{
    (void) mem_size(element_size, n); // assert size
    return ACC_ICONV(upx_rsize_t, n); // and return n
}
References ACC_ICONV, mem_size(), and n.
Referenced by anonymous_namespace{pefile.cpp}::VPtr< T >::SPAN_S().
mem_size_valid()
bool mem_size_valid (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1 = 0, upx_uint64_t extra2 = 0) noexcept
upx_rsize_t and mem_size: assert sane memory buffer sizes to protect against integer overflows and malicious header fields see C 11 standard, Annex K
Definition at line 56 of file util.cpp.
{
    assert_noexcept(element_size > 0);
    if very_unlikely (element_size == 0 || element_size > UPX_RSIZE_MAX)
        return false;
    if very_unlikely (n > UPX_RSIZE_MAX)
        return false;
    if very_unlikely (extra1 > UPX_RSIZE_MAX)
        return false;
    if very_unlikely (extra2 > UPX_RSIZE_MAX)
        return false;
    upx_uint64_t bytes = element_size * n + extra1 + extra2; // cannot overflow
    if very_unlikely (bytes > UPX_RSIZE_MAX)
        return false;
    return true;
}
References assert_noexcept, n, UPX_RSIZE_MAX, and very_unlikely.
Referenced by LeFile::readFileHeader(), TEST_CASE(), PackLinuxElf32::unpack(), and PackLinuxElf64::unpack().
mem_size_valid_bytes()
bool mem_size_valid_bytes (upx_uint64_t bytes) inline noexcept
upx_rsize_t and mem_size: assert sane memory buffer sizes to protect against integer overflows and malicious header fields see C 11 standard, Annex K
Definition at line 36 of file util.h.
{ return bytes <= UPX_RSIZE_MAX; }
References UPX_RSIZE_MAX.
Referenced by alloc_file_image(), PackHeader::decodePackHeaderFromBuf(), do_one_file(), and ptr_diff_bytes().
ptr_check_no_overlap() [1/2]
forceinline void ptr_check_no_overlap (const void * a, size_t a_size, const void * b, size_t b_size)
Definition at line 146 of file util.h.
              {
    ptraddr_check_no_overlap(ptr_get_address(a), a_size, ptr_get_address(b), b_size);
}
References b, ptr_get_address(), and ptraddr_check_no_overlap().
Referenced by optimize_relocs(), Packer::optimizeReloc(), and Packer::unoptimizeReloc().
ptr_check_no_overlap() [2/2]
forceinline void ptr_check_no_overlap (const void * a, size_t a_size, const void * b, size_t b_size, const void * c, size_t c_size)
Definition at line 150 of file util.h.
{
    ptraddr_check_no_overlap(ptr_get_address(a), a_size, ptr_get_address(b), b_size,
                             ptr_get_address(c), c_size);
}
References b, ptr_get_address(), and ptraddr_check_no_overlap().
ptr_diff()
template<class T , class U > std::enable_if< sizeof(T)==1 &&sizeof(U)==1, int >::type ptr_diff (const T * a, const U * b) inline
Definition at line 129 of file util.h.
              {
    return ptr_diff_bytes(a, b);
}
References b, and ptr_diff_bytes().
Referenced by PackVmlinuxBase< TElfClass >::pack(), and TEST_CASE().
ptr_diff_bytes()
int ptr_diff_bytes (const void * a, const void * b)
ptr util
Definition at line 109 of file util.cpp.
{
    if very_unlikely (a == nullptr)
        throwCantPack("ptr_diff_bytes null 1; take care");
    if very_unlikely (b == nullptr)
        throwCantPack("ptr_diff_bytes null 2; take care");
    upx_sptraddr_t d = ptraddr_diff(a, b);
    if (a >= b) {
        if very_unlikely (!mem_size_valid_bytes(d))
            throwCantPack("ptr_diff_bytes-1; take care");
    } else {
        if very_unlikely (!mem_size_valid_bytes(0ll - d))
            throwCantPack("ptr_diff_bytes-2; take care");
    }
    assert_noexcept(d == ((const charptr) a - (const charptr) b));
    return ACC_ICONV(int, d);
}
References ACC_ICONV, assert_noexcept, b, charptr, mem_size_valid_bytes(), ptraddr_diff(), throwCantPack(), and very_unlikely.
Referenced by PeFile::Export::build(), PackWcle::decodeFixups(), PeFile::Reloc::finish(), PeFile::pack0(), PeFile::processImports0(), PeFile::processResources(), ptr_diff(), ptr_udiff_bytes(), and TEST_CASE().
ptr_get_address() [1/2]
forceinline upx_ptraddr_t ptr_get_address (const void * p) noexcept
ptr util
Definition at line 104 of file util.h.
{ return (upx_uintptr_t) p; }
Referenced by ptr_check_no_overlap(), ptr_is_aligned(), and ptraddr_diff().
ptr_get_address() [2/2]
forceinline upx_ptraddr_t ptr_get_address (upx_uintptr_t p) noexcept
Definition at line 105 of file util.h.
{ return p; }
ptr_invalidate_and_poison()
template<class T > void ptr_invalidate_and_poison (T *& ptr) inline noexcept
Definition at line 164 of file util.h.
{
#if defined(__CHERI__) && defined(__CHERI_PURE_CAPABILITY__)
    // TODO later: examine __builtin_cheri_bounds_set()
    ptr = upx::ptr_static_cast<T *>(&ptr); // FIXME: HACK: point to address of self
#else
    // pretend there is some memory-mapped I/O at address 0x00000200
    ptr = (T *) (void *) 512; // NOLINT(performance-no-int-to-ptr)
#endif
}
References ptr.
Referenced by PeFile::Reloc::finish(), invalidate(), Ptr< T >::invalidate(), and TEST_CASE().
ptr_is_aligned() [1/2]
template<size_t Alignment> forceinline bool ptr_is_aligned (const void * p) noexcept
Definition at line 113 of file util.h.
{
    static_assert(upx::has_single_bit(Alignment));
    return (ptr_get_address(p) & (Alignment - 1)) == 0;
}
References upx::has_single_bit(), and ptr_get_address().
Referenced by upx_compiler_sanity_check().
ptr_is_aligned() [2/2]
forceinline bool ptr_is_aligned (const void * p, size_t alignment) noexcept
Definition at line 117 of file util.h.
{
    assert_noexcept(upx::has_single_bit(alignment));
    return (ptr_get_address(p) & (alignment - 1)) == 0;
}
References assert_noexcept, upx::has_single_bit(), and ptr_get_address().
ptr_udiff()
template<class T , class U > std::enable_if< sizeof(T)==1 &&sizeof(U)==1, unsigned >::type ptr_udiff (const T * a, const U * b) inline
Definition at line 136 of file util.h.
{
    return ptr_udiff_bytes(a, b);
}
References b, and ptr_udiff_bytes().
Referenced by TEST_CASE().
ptr_udiff_bytes()
unsigned ptr_udiff_bytes (const void * a, const void * b)
Definition at line 126 of file util.cpp.
{
    int d = ptr_diff_bytes(a, b);
    if very_unlikely (d < 0)
        throwCantPack("ptr_udiff_bytes; take care");
    return ACC_ICONV(unsigned, d);
}
References ACC_ICONV, b, ptr_diff_bytes(), throwCantPack(), and very_unlikely.
Referenced by PeFile::Interval::add_interval(), LeFile::countFixups(), PackWcle::decodeEntryTable(), PackWcle::decodeFixups(), PackWcle::encodeEntryTable(), PeFile::Reloc::finish(), PackMachBase< TMachClass >::get_mod_init_func(), optimize_relocs(), Packer::optimizeReloc(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackWcle::preprocessFixups(), PeFile::processImports0(), ptr_udiff(), PeFile::Reloc::readFromRelocationBlock(), PeFile::rebuildImports(), TEST_CASE(), Packer::unoptimizeReloc(), PackExe::unpack(), and PackMachBase< TMachClass >::unpack().
ptraddr_check_no_overlap() [1/2]
noinline void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size)
Definition at line 147 of file util.cpp.
{
    if very_unlikely (a == 0 || b == 0)
        throwCantPack("ptr_check_no_overlap-nullptr");
    upx_ptraddr_t a_end = a + mem_size(1, a_size);
    upx_ptraddr_t b_end = b + mem_size(1, b_size);
    if very_unlikely (a_end < a || b_end < b) // wrap-around
        throwCantPack("ptr_check_no_overlap-overflow");
    // simple, but a little bit mind bending:
    //   same as (!(a >= b_end || b >= a_end))
    //   same as (!(a_end <= b || b_end <= a))
    if very_unlikely (a < b_end && b < a_end)
        throwCantPack("ptr_check_no_overlap-ab");
}
References b, mem_size(), throwCantPack(), and very_unlikely.
Referenced by ptr_check_no_overlap().
ptraddr_check_no_overlap() [2/2]
noinline void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size, upx_ptraddr_t c, size_t c_size)
Definition at line 162 of file util.cpp.
{
    if very_unlikely (a == 0 || b == 0 || c == 0)
        throwCantPack("ptr_check_no_overlap-nullptr");
    upx_ptraddr_t a_end = a + mem_size(1, a_size);
    upx_ptraddr_t b_end = b + mem_size(1, b_size);
    upx_ptraddr_t c_end = c + mem_size(1, c_size);
    if very_unlikely (a_end < a || b_end < b || c_end < c) // wrap-around
        throwCantPack("ptr_check_no_overlap-overflow");
    if very_unlikely (a < b_end && b < a_end)
        throwCantPack("ptr_check_no_overlap-ab");
    if very_unlikely (a < c_end && c < a_end)
        throwCantPack("ptr_check_no_overlap-ac");
    if very_unlikely (b < c_end && c < b_end)
        throwCantPack("ptr_check_no_overlap-bc");
}
References b, mem_size(), throwCantPack(), and very_unlikely.
ptraddr_diff()
forceinline upx_sptraddr_t ptraddr_diff (const void * a, const void * b) noexcept
Definition at line 108 of file util.h.
{
    return ptr_get_address(a) - ptr_get_address(b);
}
References b, and ptr_get_address().
Referenced by ptr_diff_bytes(), and xspan_check_range().
set_method_name()
bool set_method_name (char * buf, size_t size, int method, int level)
Definition at line 869 of file util.cpp.
{
    bool r = true;
    const char *alg;
    if (M_IS_NRV2B(method))
        alg = "NRV2B";
    else if (M_IS_NRV2D(method))
        alg = "NRV2D";
    else if (M_IS_NRV2E(method))
        alg = "NRV2E";
    else if (M_IS_LZMA(method))
        alg = "LZMA";
    else {
        alg = "???";
        r = false;
    }
    if (level > 0)
        upx_safe_snprintf(buf, size, "%s/%d", alg, level);
    else
        upx_safe_snprintf(buf, size, "%s", alg);
    return r;
}
References buf, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, size(), and upx_safe_snprintf().
Referenced by PackPs1::pack(), and UiPacker::printInfo().
upx_calloc()
noinline void * upx_calloc (size_t n, size_t element_size)
stdlib
Definition at line 285 of file util.cpp.
{
    size_t bytes = mem_size(element_size, n); // assert size
    void *p = ::malloc(bytes);
    if (p != nullptr)
        memset(p, 0, bytes);
    return p;
}
References mem_size(), memset(), and n.
Referenced by main_get_envoptions(), and my_malloc().
upx_getenv()
noinline const char * upx_getenv (const char * envvar) noexcept
stdlib
Definition at line 256 of file util.cpp.
{
    if (envvar != nullptr && envvar[0])
        return ::getenv(envvar);
    return nullptr;
}
Referenced by is_envvar_true(), main_get_envoptions(), Options::reset(), show_sysinfo(), TEST_CASE(), and upx_doctest_check().
upx_gnomesort()
void upx_gnomesort (void * array, size_t n, size_t element_size, upx_compare_func_t compare)
Definition at line 346 of file util.cpp.
{
    for (size_t i = 1; i < n; i++) {
        byte *a = (byte *) array + element_size * i;               // a := &array[i]
        if (i != 0 && compare(a - element_size, a) > 0) {          // if a[-1] > a[0] then
            memswap_no_overlap(a - element_size, a, element_size); //   swap elements a[-1] <=> a[0]
            i -= 2;                                                //   and decrease i
        }
    }
}
References memswap_no_overlap(), and n.
Referenced by anonymous_namespace{help.cpp}::PackerNames::add(), list_all_packers(), TEST_CASE(), and upx_std_stable_sort().
upx_memswap()
noinline void upx_memswap (void * a, void * b, size_t bytes) noexcept
Definition at line 296 of file util.cpp.
{
    if (aa != bb && bytes != 0) {
        byte *a = (byte *) aa;
        byte *b = (byte *) bb;
        do {
            // strange clang-analyzer-15 false positive when compiling in Debug mode
            // clang-analyzer-core.uninitialized.Assign
            byte tmp = *a; // NOLINT(*core.uninitialized.Assign) // bogus clang-analyzer warning
            *a++ = *b;
            *b++ = tmp;
        } while (--bytes != 0);
    }
}
References b.
Referenced by memswap_no_overlap(), and TEST_CASE().
upx_rand()
noinline int upx_rand (void) noexcept
Definition at line 263 of file util.cpp.
{
    return ::rand(); // NOLINT(clang-analyzer-security.insecureAPI.rand)
}
Referenced by Packer::getRandomId(), prepareFilters(), Packer::prepareMethods(), and TEST_CASE().
upx_rand_init()
noinline void upx_rand_init (void) noexcept
Definition at line 267 of file util.cpp.
{
    unsigned seed = 0;
    seed ^= UPX_VERSION_HEX;
#if (!HAVE_GETTIMEOFDAY || (ACC_OS_DOS32 && defined(__DJGPP__))) && !defined(__wasi__)
    seed ^= (unsigned) time(nullptr);
    seed ^= ((unsigned) clock()) << 12;
#else
    struct timeval tv = {};
    (void) gettimeofday(&tv, nullptr);
    seed ^= (unsigned) tv.tv_sec;
    seed ^= ((unsigned) tv.tv_usec) << 12;
#endif
#if HAVE_GETPID
    seed ^= ((unsigned) getpid()) << 4;
#endif
    ::srand(seed);
}
References getpid(), gettimeofday(), timeval::tv_sec, timeval::tv_usec, and UPX_VERSION_HEX.
Referenced by main().
upx_shellsort_memcpy()
void upx_shellsort_memcpy (void * array, size_t n, size_t element_size, upx_compare_func_t compare)
Definition at line 374 of file util.cpp.
{
    mem_size_assert(element_size, n); // check size
    constexpr size_t MAX_INLINE_ELEMENT_SIZE = 256;
    upx_alignas_max byte tmp_buf[MAX_INLINE_ELEMENT_SIZE]; // buffer for one element
    byte *tmp = tmp_buf;
    if (element_size > MAX_INLINE_ELEMENT_SIZE) {
        tmp = (byte *) ::malloc(element_size);
        assert(tmp != nullptr);
    }
    size_t gap = 0;         // 0, 1, 4, 13, 40, 121, 364, 1093, ...
    while (gap * 3 + 1 < n) // cannot overflow because of size check above
        gap = gap * 3 + 1;
    for (; gap > 0; gap = (gap - 1) / 3) {
        const size_t gap_bytes = element_size * gap;
        byte *p = (byte *) array + gap_bytes;
        for (size_t i = gap; i < n; i += gap, p += gap_bytes) // invariant: p == &array[i]
            if (compare(p - gap_bytes, p) > 0) {
                byte *a = p;
                memcpy(tmp, a, element_size);
                do {
                    memcpy(a, a - gap_bytes, element_size);
                    a -= gap_bytes;
                } while (a != array && compare(a - gap_bytes, tmp) > 0);
                memcpy(a, tmp, element_size);
            }
    }
    if (element_size > MAX_INLINE_ELEMENT_SIZE)
        ::free(tmp);
}
References mem_size_assert(), memcpy(), n, and upx_alignas_max.
Referenced by TEST_CASE().
upx_shellsort_memswap()
void upx_shellsort_memswap (void * array, size_t n, size_t element_size, upx_compare_func_t compare)
Definition at line 358 of file util.cpp.
{
    mem_size_assert(element_size, n); // check size
    size_t gap = 0;                   // 0, 1, 4, 13, 40, 121, 364, 1093, ...
    while (gap * 3 + 1 < n)           // cannot overflow because of size check above
        gap = gap * 3 + 1;
    for (; gap > 0; gap = (gap - 1) / 3) {
        const size_t gap_bytes = element_size * gap;
        byte *p = (byte *) array + gap_bytes;
        for (size_t i = gap; i < n; i += gap, p += gap_bytes) // invariant: p == &array[i]
            for (byte *a = p; a != array && compare(a - gap_bytes, a) > 0; a -= gap_bytes)
                memswap_no_overlap(a - gap_bytes, a, element_size);
    }
}
References mem_size_assert(), memswap_no_overlap(), and n.
Referenced by TEST_CASE().
upx_std_stable_sort()
template<size_t ElementSize> void upx_std_stable_sort (void * array, size_t n, upx_compare_func_t compare)
Definition at line 406 of file util.cpp.
{
    static_assert(ElementSize >= 1 && ElementSize <= UPX_RSIZE_MAX);
    mem_size_assert(ElementSize, n); // check size
#if 0
    // just for testing
    upx_gnomesort(array, n, ElementSize, compare);
#else
    struct alignas(1) element_type { byte data[ElementSize]; };
    static_assert(sizeof(element_type) == ElementSize);
    static_assert(alignof(element_type) == 1);
    auto less = [compare](const element_type &a, const element_type &b) -> bool {
        return compare(&a, &b) < 0;
    };
    std::stable_sort((element_type *) array, (element_type *) array + n, less);
#endif
}
References b, data(), mem_size_assert(), n, upx_gnomesort(), and UPX_RSIZE_MAX.