My Project: src/util/util.cpp File Reference
util.cpp File Reference
#include "system_headers.h"
#include "miniacc.h"
#include "../conf.h"
Namespaces
namespace N_BELE_CTP
Provide namespaces and classes to abstract endianness policies.
namespace N_BELE_RTP
Macros
#define WANT_WINDOWS_LEAN_H 1
#define ACC_WANT_ACC_INCI_H 1
#define ACC_WANT_ACCLIB_GETOPT 1
#define ACC_WANT_ACCLIB_HSREAD 1
#define ACC_WANT_ACCLIB_MISC 1
#define ACC_WANT_ACCLIB_VGET 1
#define ACC_WANT_ACCLIB_WILDARGV 1
#define SWAP(n)
#define fn_is_drive(s) (0)
fn - FileName util
#define fn_is_sep(c) ((c) == '/')
#define fn_skip_drive(s) (s)
#define fn_tolower(c) (c)
Functions
bool mem_size_valid (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1, upx_uint64_t extra2) noexcept
upx_rsize_t and mem_size: assert sane memory buffer sizes to protect against integer overflows and malicious header fields see C 11 standard, Annex K
upx_rsize_t mem_size (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1, upx_uint64_t extra2)
TEST_CASE ("mem_size")
int ptr_diff_bytes (const void *a, const void *b) may_throw
ptr util
unsigned ptr_udiff_bytes (const void *a, const void *b) may_throw
TEST_CASE ("ptr_diff")
void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size)
void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size, upx_ptraddr_t c, size_t c_size)
const char * upx_getenv (const char *envvar) noexcept
stdlib
int upx_rand (void) noexcept
void upx_rand_init (void) noexcept
void * upx_calloc (size_t n, size_t element_size) may_throw
stdlib
void upx_memswap (void *aa, void *bb, size_t bytes) noexcept
static void memswap_no_overlap (byte *a, byte *b, size_t bytes) noexcept
void upx_gnomesort (void *array, size_t n, size_t element_size, upx_compare_func_t compare)
void upx_shellsort_memswap (void *array, size_t n, size_t element_size, upx_compare_func_t compare)
void upx_shellsort_memcpy (void *array, size_t n, size_t element_size, upx_compare_func_t compare)
template<size_t ElementSize>
void upx_std_stable_sort (void *array, size_t n, upx_compare_func_t compare)
TEST_CASE ("upx_memswap")
int __acc_cdecl_qsort be16_compare (const void *e1, const void *e2)
qsort() util
int __acc_cdecl_qsort be24_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort be32_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort be64_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort le16_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort le24_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort le32_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort le64_compare (const void *e1, const void *e2)
int __acc_cdecl_qsort be16_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort be24_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort be32_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort be64_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort le16_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort le24_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort le32_compare_signed (const void *e1, const void *e2)
int __acc_cdecl_qsort le64_compare_signed (const void *e1, const void *e2)
int find (const void *buf, int blen, const void *what, int wlen) noexcept
find and mem_replace util
int find_be16 (const void *b, int blen, unsigned what) noexcept
int find_be32 (const void *b, int blen, unsigned what) noexcept
int find_be64 (const void *b, int blen, upx_uint64_t what) noexcept
int find_le16 (const void *b, int blen, unsigned what) noexcept
int find_le32 (const void *b, int blen, unsigned what) noexcept
int find_le64 (const void *b, int blen, upx_uint64_t what) noexcept
TEST_CASE ("find")
int mem_replace (void *buf, int blen, const void *what, int wlen, const void *replacement) noexcept
TEST_CASE ("mem_replace")
char * fn_basename (const char *name)
bool fn_has_ext (const char *name, const char *ext, bool ignore_case)
char * fn_strlwr (char *n)
int fn_strcmp (const char *n1, const char *n2)
bool is_envvar_true (const char *envvar, const char *alternate_name) noexcept
misc
bool set_method_name (char *buf, size_t size, int method, int level)
void center_string (char *buf, size_t size, const char *s)
bool file_exists (const char *name)
bool maketempname (char *ofilename, size_t size, const char *ifilename, const char *ext, bool force)
bool makebakname (char *ofilename, size_t size, const char *ifilename, bool force)
unsigned get_ratio (upx_uint64_t u_len, upx_uint64_t c_len)
return compression ratio, where 100% == 1000*1000 == 1e6
TEST_CASE ("get_ratio")
Macro Definition Documentation
ACC_WANT_ACC_INCI_H
#define ACC_WANT_ACC_INCI_H 1
Definition at line 30 of file util.cpp.
ACC_WANT_ACCLIB_GETOPT
#define ACC_WANT_ACCLIB_GETOPT 1
Definition at line 32 of file util.cpp.
ACC_WANT_ACCLIB_HSREAD
#define ACC_WANT_ACCLIB_HSREAD 1
Definition at line 33 of file util.cpp.
ACC_WANT_ACCLIB_MISC
#define ACC_WANT_ACCLIB_MISC 1
Definition at line 34 of file util.cpp.
ACC_WANT_ACCLIB_VGET
#define ACC_WANT_ACCLIB_VGET 1
Definition at line 35 of file util.cpp.
ACC_WANT_ACCLIB_WILDARGV
#define ACC_WANT_ACCLIB_WILDARGV 1
Definition at line 36 of file util.cpp.
fn_is_drive
#define fn_is_drive (s) (0)
fn - FileName util
Definition at line 801 of file util.cpp.
fn_is_sep
#define fn_is_sep (c) ((c) == '/')
Definition at line 802 of file util.cpp.
fn_skip_drive
#define fn_skip_drive (s) (s)
Definition at line 803 of file util.cpp.
fn_tolower
#define fn_tolower (c) (c)
Definition at line 804 of file util.cpp.
SWAP
#define SWAP (n)
Value:
    do {                                                                                           \
        upx_memcpy_inline(tmp_buf, a, n);                                                          \
        upx_memcpy_inline(a, b, n);                                                                \
        upx_memcpy_inline(b, tmp_buf, n);                                                          \
        a += n;                                                                                    \
        b += n;                                                                                    \
    } while (0)
WANT_WINDOWS_LEAN_H
#define WANT_WINDOWS_LEAN_H 1
Definition at line 28 of file util.cpp.
Function Documentation
be16_compare()
int __acc_cdecl_qsort be16_compare (const void * e1, const void * e2)
qsort() util
misc support
Definition at line 569 of file util.cpp.
{
    const unsigned d1 = get_be16(e1);
    const unsigned d2 = get_be16(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be16().
Referenced by BEPolicy::u16_compare().
be16_compare_signed()
int __acc_cdecl_qsort be16_compare_signed (const void * e1, const void * e2)
Definition at line 617 of file util.cpp.
{
    const int d1 = get_be16_signed(e1);
    const int d2 = get_be16_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be16_signed().
Referenced by BEPolicy::u16_compare_signed().
be24_compare()
int __acc_cdecl_qsort be24_compare (const void * e1, const void * e2)
Definition at line 575 of file util.cpp.
{
    const unsigned d1 = get_be24(e1);
    const unsigned d2 = get_be24(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be24().
Referenced by BEPolicy::u24_compare().
be24_compare_signed()
int __acc_cdecl_qsort be24_compare_signed (const void * e1, const void * e2)
Definition at line 623 of file util.cpp.
{
    const int d1 = get_be24_signed(e1);
    const int d2 = get_be24_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be24_signed().
Referenced by BEPolicy::u24_compare_signed().
be32_compare()
int __acc_cdecl_qsort be32_compare (const void * e1, const void * e2)
Definition at line 581 of file util.cpp.
{
    const unsigned d1 = get_be32(e1);
    const unsigned d2 = get_be32(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be32().
Referenced by BEPolicy::u32_compare().
be32_compare_signed()
int __acc_cdecl_qsort be32_compare_signed (const void * e1, const void * e2)
Definition at line 629 of file util.cpp.
{
    const int d1 = get_be32_signed(e1);
    const int d2 = get_be32_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be32_signed().
Referenced by BEPolicy::u32_compare_signed().
be64_compare()
int __acc_cdecl_qsort be64_compare (const void * e1, const void * e2)
Definition at line 587 of file util.cpp.
{
    const upx_uint64_t d1 = get_be64(e1);
    const upx_uint64_t d2 = get_be64(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be64().
Referenced by BEPolicy::u64_compare().
be64_compare_signed()
int __acc_cdecl_qsort be64_compare_signed (const void * e1, const void * e2)
Definition at line 635 of file util.cpp.
{
    const upx_int64_t d1 = get_be64_signed(e1);
    const upx_int64_t d2 = get_be64_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_be64_signed().
Referenced by BEPolicy::u64_compare_signed().
center_string()
void center_string (char * buf, size_t size, const char * s)
Definition at line 891 of file util.cpp.
{
    size_t l1 = size - 1;
    size_t l2 = strlen(s);
    assert(size > 0);
    assert(l2 < size);
    memset(buf, ' ', l1);
    memcpy(buf + (l1 - l2) / 2, s, l2);
    buf[l1] = 0;
}
References buf, memcpy(), memset(), size(), and strlen.
Referenced by mkline().
file_exists()
bool file_exists (const char * name)
Definition at line 901 of file util.cpp.
{
    int fd, r;
    struct stat st;
    /* return true if we can open it */
    fd = open(name, O_RDONLY | O_BINARY, 0);
    if (fd >= 0) {
        (void) close(fd);
        return true;
    }
    /* return true if we can stat it */
    // mem_clear(&st);
    r = stat(name, &st);
    if (r != -1)
        return true;
/* return true if we can lstat it */
#if HAVE_LSTAT
    // mem_clear(&st);
    r = lstat(name, &st);
    if (r != -1)
        return true;
#endif
    return false;
}
References close(), O_BINARY, O_RDONLY, and open().
Referenced by makebakname(), and maketempname().
find()
int find (const void * buf, int blen, const void * what, int wlen) noexcept
find and mem_replace util
misc support functions
Definition at line 669 of file util.cpp.
{
    // nullptr is explicitly allowed here
    if (buf == nullptr || blen < wlen || what == nullptr || wlen <= 0)
        return -1;
    const byte *b = (const byte *) buf;
    const byte first_byte = *(const byte *) what;
    blen -= wlen;
    for (int i = 0; i <= blen; i++, b++)
        if (*b == first_byte && memcmp(b, what, wlen) == 0)
            return i;
    return -1;
}
References b, buf, and memcmp().
Referenced by PeFile::canUnpack0(), PackVmlinuzI386::decompressKernel(), PackVmlinuzARMEL::decompressKernel(), find_be16(), find_be32(), find_be64(), find_le16(), find_le32(), find_le64(), ElfLinker::init(), mem_replace(), Packer::patch_be16(), Packer::patch_be32(), Packer::patch_le16(), Packer::patch_le32(), and TEST_CASE().
find_be16()
int find_be16 (const void * b, int blen, unsigned what) noexcept
Definition at line 685 of file util.cpp.
{
    byte w[2];
    set_be16(w, what);
    return find(b, blen, w, 2);
}
References b, find(), and set_be16().
Referenced by Packer::patch_be16(), TEST_CASE(), and upx_compiler_sanity_check().
find_be32()
int find_be32 (const void * b, int blen, unsigned what) noexcept
Definition at line 691 of file util.cpp.
{
    byte w[4];
    set_be32(w, what);
    return find(b, blen, w, 4);
}
References b, find(), and set_be32().
Referenced by Packer::patch_be32(), TEST_CASE(), and upx_compiler_sanity_check().
find_be64()
int find_be64 (const void * b, int blen, upx_uint64_t what) noexcept
Definition at line 697 of file util.cpp.
{
    byte w[8];
    set_be64(w, what);
    return find(b, blen, w, 8);
}
References b, find(), and set_be64().
Referenced by TEST_CASE().
find_le16()
int find_le16 (const void * b, int blen, unsigned what) noexcept
Definition at line 703 of file util.cpp.
{
    byte w[2];
    set_le16(w, what);
    return find(b, blen, w, 2);
}
References b, find(), and set_le16().
Referenced by Packer::patch_le16(), TEST_CASE(), and upx_compiler_sanity_check().
find_le32()
int find_le32 (const void * b, int blen, unsigned what) noexcept
Definition at line 709 of file util.cpp.
{
    byte w[4];
    set_le32(w, what);
    return find(b, blen, w, 4);
}
References b, find(), and set_le32().
Referenced by Packer::checkAlreadyPacked(), PackHeader::decodePackHeaderFromBuf(), PackTmt::pack(), PackWcle::pack(), Packer::patch_le32(), Packer::patchPackHeader(), TEST_CASE(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), and upx_compiler_sanity_check().
find_le64()
int find_le64 (const void * b, int blen, upx_uint64_t what) noexcept
Definition at line 715 of file util.cpp.
{
    byte w[8];
    set_le64(w, what);
    return find(b, blen, w, 8);
}
References b, find(), and set_le64().
Referenced by TEST_CASE().
fn_basename()
char * fn_basename (const char * name)
Definition at line 808 of file util.cpp.
{
    const char *n, *nn;
    name = fn_skip_drive(name);
    for (nn = n = name; *nn; nn++)
        if (fn_is_sep(*nn))
            n = nn + 1;
    return ACC_UNCONST_CAST(char *, n);
}
References ACC_UNCONST_CAST, fn_is_sep, fn_skip_drive, and n.
Referenced by fn_has_ext(), makebakname(), maketempname(), PeFile::readSectionHeaders(), UiPacker::startCallback(), UiPacker::uiPackEnd(), UiPacker::uiUnpackEnd(), and upx_main().
fn_has_ext()
bool fn_has_ext (const char * name, const char * ext, bool ignore_case)
Definition at line 818 of file util.cpp.
{
    const char *n, *e;
    name = fn_basename(name);
    for (n = e = name; *n; n++)
        if (*n == '.')
            e = n;
    if (ignore_case)
        return (strcasecmp(ext, e + 1) == 0);
    else
        return (fn_strcmp(ext, e + 1) == 0);
}
References fn_basename(), fn_strcmp(), n, and strcasecmp().
Referenced by PackCom::canPack(), PackExe::canPack(), PackSys::canPack(), and PeFile::processResources().
fn_strcmp()
int fn_strcmp (const char * n1, const char * n2)
Definition at line 838 of file util.cpp.
{
    for (;;) {
        if (*n1 != *n2) {
            int c = fn_tolower(*n1) - fn_tolower(*n2);
            if (c)
                return c;
        }
        if (*n1 == 0)
            return 0;
        n1++;
        n2++;
    }
}
References fn_tolower.
Referenced by fn_has_ext(), and upx_main().
fn_strlwr()
char * fn_strlwr (char * n)
Definition at line 831 of file util.cpp.
{
    char *p;
    for (p = n; *p; p++)
        *p = (char) fn_tolower(*p);
    return n;
}
References fn_tolower, and n.
Referenced by upx_main().
get_ratio()
unsigned get_ratio (upx_uint64_t u_len, upx_uint64_t c_len)
return compression ratio, where 100% == 1000*1000 == 1e6
Definition at line 996 of file util.cpp.
{
    constexpr unsigned N = 1000 * 1000;
    if (u_len == 0)
        return c_len == 0 ? 0 : N;
    upx_uint64_t x = c_len * N;
    assert(x / N == c_len); // sanity check
    x /= u_len;
    x += 50;         // rounding; cannot overflow
    if (x >= 10 * N) // >= "1000%"
        x = 10 * N - 1;
    return ACC_ICONV(unsigned, x);
}
References ACC_ICONV, and N.
Referenced by UiPacker::doCallback(), mkline(), and TEST_CASE().
is_envvar_true()
bool is_envvar_true (const char * envvar, const char * alternate_name) noexcept
misc
Definition at line 857 of file util.cpp.
{
    const char *e = upx_getenv(envvar);
    if (e != nullptr && e[0])
        return strcmp(e, "0") != 0;
    if (alternate_name != nullptr) {
        e = upx_getenv(alternate_name);
        if (e != nullptr && e[0])
            return strcmp(e, "0") != 0;
    }
    return false;
}
References strcmp(), and upx_getenv().
Referenced by PackMachBase< TMachClass >::canPack(), anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::check(), TEST_CASE(), upx_compiler_sanity_check(), upx_doctest_check(), and upx_main().
le16_compare()
int __acc_cdecl_qsort le16_compare (const void * e1, const void * e2)
Definition at line 593 of file util.cpp.
{
    const unsigned d1 = get_le16(e1);
    const unsigned d2 = get_le16(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le16().
Referenced by LEPolicy::u16_compare().
le16_compare_signed()
int __acc_cdecl_qsort le16_compare_signed (const void * e1, const void * e2)
Definition at line 641 of file util.cpp.
{
    const int d1 = get_le16_signed(e1);
    const int d2 = get_le16_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le16_signed().
Referenced by LEPolicy::u16_compare_signed().
le24_compare()
int __acc_cdecl_qsort le24_compare (const void * e1, const void * e2)
Definition at line 599 of file util.cpp.
{
    const unsigned d1 = get_le24(e1);
    const unsigned d2 = get_le24(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le24().
Referenced by LEPolicy::u24_compare().
le24_compare_signed()
int __acc_cdecl_qsort le24_compare_signed (const void * e1, const void * e2)
Definition at line 647 of file util.cpp.
{
    const int d1 = get_le24_signed(e1);
    const int d2 = get_le24_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le24_signed().
Referenced by LEPolicy::u24_compare_signed().
le32_compare()
int __acc_cdecl_qsort le32_compare (const void * e1, const void * e2)
Definition at line 605 of file util.cpp.
{
    const unsigned d1 = get_le32(e1);
    const unsigned d2 = get_le32(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le32().
Referenced by Packer::optimizeReloc(), PackExe::pack(), PeFile32::processRelocs(), PeFile64::processRelocs(), and LEPolicy::u32_compare().
le32_compare_signed()
int __acc_cdecl_qsort le32_compare_signed (const void * e1, const void * e2)
Definition at line 653 of file util.cpp.
{
    const int d1 = get_le32_signed(e1);
    const int d2 = get_le32_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le32_signed().
Referenced by LEPolicy::u32_compare_signed().
le64_compare()
int __acc_cdecl_qsort le64_compare (const void * e1, const void * e2)
Definition at line 611 of file util.cpp.
{
    const upx_uint64_t d1 = get_le64(e1);
    const upx_uint64_t d2 = get_le64(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le64().
Referenced by LEPolicy::u64_compare().
le64_compare_signed()
int __acc_cdecl_qsort le64_compare_signed (const void * e1, const void * e2)
Definition at line 659 of file util.cpp.
{
    const upx_int64_t d1 = get_le64_signed(e1);
    const upx_int64_t d2 = get_le64_signed(e2);
    return (d1 < d2) ? -1 : ((d1 > d2) ? 1 : 0);
}
References get_le64_signed().
Referenced by LEPolicy::u64_compare_signed().
makebakname()
bool makebakname (char * ofilename, size_t size, const char * ifilename, bool force)
Definition at line 959 of file util.cpp.
{
    char *ofext = nullptr, *ofname;
    int ofile;
    if (size <= 0)
        return false;
    strcpy(ofilename, ifilename);
    for (ofname = fn_basename(ofilename); *ofname; ofname++) {
        if (*ofname == '.')
            ofext = ofname;
    }
    if (ofext == nullptr) {
        ofext = ofilename + strlen(ofilename);
        strcpy(ofext, ".~");
    } else if (strlen(ofext) < 1 + 3)
        strcat(ofilename, "~");
    else
        ofext[strlen(ofext) - 1] = '~';
    for (ofile = 0; ofile < 1000; ofile++) {
        assert(strlen(ofilename) < size);
        if (!file_exists(ofilename))
            return true;
        if (!force)
            break;
        upx_safe_snprintf(ofext, 5, ".%03d", ofile);
    }
    ofilename[0] = 0;
    return false;
}
References file_exists(), fn_basename(), size(), strcpy(), strlen, and upx_safe_snprintf().
Referenced by do_one_file().
maketempname()
bool maketempname (char * ofilename, size_t size, const char * ifilename, const char * ext, bool force)
Definition at line 929 of file util.cpp.
{
    char *ofext = nullptr, *ofname;
    int ofile;
    if (size <= 0)
        return false;
    strcpy(ofilename, ifilename);
    for (ofname = fn_basename(ofilename); *ofname; ofname++) {
        if (*ofname == '.')
            ofext = ofname;
    }
    if (ofext == nullptr)
        ofext = ofilename + strlen(ofilename);
    strcpy(ofext, ext);
    for (ofile = 0; ofile < 1000; ofile++) {
        assert(strlen(ofilename) < size);
        if (!file_exists(ofilename))
            return true;
        if (!force)
            break;
        upx_safe_snprintf(ofext, 5, ".%03d", ofile);
    }
    ofilename[0] = 0;
    return false;
}
References file_exists(), fn_basename(), size(), strcpy(), strlen, and upx_safe_snprintf().
Referenced by do_one_file().
mem_replace()
int mem_replace (void * buf, int blen, const void * what, int wlen, const void * replacement) noexcept
Definition at line 743 of file util.cpp.
{
    byte *const b = (byte *) buf;
    int boff = 0;
    int count = 0;
    while (blen - boff >= wlen) {
        int off = find(b + boff, blen - boff, what, wlen);
        if (off < 0)
            break;
        boff += off;
        memcpy(b + boff, replacement, wlen);
        boff += wlen;
        count++;
    }
    return count;
}
References b, buf, find(), and memcpy().
Referenced by getIdentstr(), and TEST_CASE().
mem_size()
upx_rsize_t mem_size (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1, upx_uint64_t extra2)
Definition at line 73 of file util.cpp.
{
    assert(element_size > 0);
    if very_unlikely (element_size == 0 || element_size > UPX_RSIZE_MAX)
        throwCantPack("mem_size 1; take care");
    if very_unlikely (n > UPX_RSIZE_MAX)
        throwCantPack("mem_size 2; take care");
    if very_unlikely (extra1 > UPX_RSIZE_MAX)
        throwCantPack("mem_size 3; take care");
    if very_unlikely (extra2 > UPX_RSIZE_MAX)
        throwCantPack("mem_size 4; take care");
    upx_uint64_t bytes = element_size * n + extra1 + extra2; // cannot overflow
    if very_unlikely (bytes > UPX_RSIZE_MAX)
        throwCantPack("mem_size 5; take care");
    return ACC_ICONV(upx_rsize_t, bytes);
}
References ACC_ICONV, n, throwCantPack(), UPX_RSIZE_MAX, and very_unlikely.
Referenced by PeFile::Interval::add_interval(), PeFile::Reloc::add_reloc(), MemBuffer::alloc(), PeFile::canUnpack0(), LeFile::countFixups(), PackWcle::decodeFixups(), PackWcle::encodeObjectTable(), PeFile::Reloc::finish(), PackVmlinuxBase< TElfClass >::getElfSections(), MemBuffer::getSizeForCompression(), MemBuffer::getSizeForDecompression(), mem_size(), mem_size_assert(), mem_size_get_n(), MemBufferBase< T >::operator+(), MemBufferBase< T >::operator[](), PackDjgpp2::pack(), PackWcle::pack(), PeFile32::processRelocs(), PeFile64::processRelocs(), ptraddr_check_no_overlap(), raw_bytes(), raw_index_bytes(), InputFile::read(), LeFile::readImage(), PeFile::readSectionHeaders(), realloc_array(), PeFile::rebuildImports(), PeFile::rebuildRelocs(), PeFile::Reloc::Reloc(), PeFile::Resource::res_dir::Sizeof(), TEST_CASE(), Packer::unoptimizeReloc(), PackDjgpp2::unpack(), PackTmt::unpack(), PackWcle::unpack(), upx_calloc(), and OutputFile::write().
mem_size_valid()
bool mem_size_valid (upx_uint64_t element_size, upx_uint64_t n, upx_uint64_t extra1, upx_uint64_t extra2) noexcept
upx_rsize_t and mem_size: assert sane memory buffer sizes to protect against integer overflows and malicious header fields see C 11 standard, Annex K
Definition at line 56 of file util.cpp.
{
    assert_noexcept(element_size > 0);
    if very_unlikely (element_size == 0 || element_size > UPX_RSIZE_MAX)
        return false;
    if very_unlikely (n > UPX_RSIZE_MAX)
        return false;
    if very_unlikely (extra1 > UPX_RSIZE_MAX)
        return false;
    if very_unlikely (extra2 > UPX_RSIZE_MAX)
        return false;
    upx_uint64_t bytes = element_size * n + extra1 + extra2; // cannot overflow
    if very_unlikely (bytes > UPX_RSIZE_MAX)
        return false;
    return true;
}
References assert_noexcept, n, UPX_RSIZE_MAX, and very_unlikely.
Referenced by LeFile::readFileHeader(), TEST_CASE(), PackLinuxElf32::unpack(), and PackLinuxElf64::unpack().
memswap_no_overlap()
static void memswap_no_overlap (byte * a, byte * b, size_t bytes) inline static noexcept
Definition at line 311 of file util.cpp.
{
#if defined(__clang__) && (__clang_major__ < 15) && !defined(__CHERI__)
    // work around a clang < 15 ICE (Internal Compiler Error)
    // @COMPILER_BUG @CLANG_BUG
    upx_memswap(a, b, bytes);
#else // clang bug
    upx_alignas_max byte tmp_buf[16];
#define SWAP(n)                                                                                    \
    do {                                                                                           \
        upx_memcpy_inline(tmp_buf, a, n);                                                          \
        upx_memcpy_inline(a, b, n);                                                                \
        upx_memcpy_inline(b, tmp_buf, n);                                                          \
        a += n;                                                                                    \
        b += n;                                                                                    \
    } while (0)
    for (; bytes >= 16; bytes -= 16)
        SWAP(16);
    if (bytes & 8)
        SWAP(8);
    if (bytes & 4)
        SWAP(4);
    if (bytes & 2)
        SWAP(2);
    if (bytes & 1) {
        byte tmp = *a;
        *a = *b;
        *b = tmp;
    }
#undef SWAP
#endif // clang bug
}
References b, SWAP, upx_alignas_max, and upx_memswap().
Referenced by TEST_CASE(), upx_gnomesort(), and upx_shellsort_memswap().
ptr_diff_bytes()
int ptr_diff_bytes (const void * a, const void * b)
ptr util
Definition at line 109 of file util.cpp.
{
    if very_unlikely (a == nullptr)
        throwCantPack("ptr_diff_bytes null 1; take care");
    if very_unlikely (b == nullptr)
        throwCantPack("ptr_diff_bytes null 2; take care");
    upx_sptraddr_t d = ptraddr_diff(a, b);
    if (a >= b) {
        if very_unlikely (!mem_size_valid_bytes(d))
            throwCantPack("ptr_diff_bytes-1; take care");
    } else {
        if very_unlikely (!mem_size_valid_bytes(0ll - d))
            throwCantPack("ptr_diff_bytes-2; take care");
    }
    assert_noexcept(d == ((const charptr) a - (const charptr) b));
    return ACC_ICONV(int, d);
}
References ACC_ICONV, assert_noexcept, b, charptr, mem_size_valid_bytes(), ptraddr_diff(), throwCantPack(), and very_unlikely.
Referenced by PeFile::Export::build(), PackWcle::decodeFixups(), PeFile::Reloc::finish(), PeFile::pack0(), PeFile::processImports0(), PeFile::processResources(), ptr_diff(), ptr_udiff_bytes(), and TEST_CASE().
ptr_udiff_bytes()
unsigned ptr_udiff_bytes (const void * a, const void * b)
Definition at line 126 of file util.cpp.
{
    int d = ptr_diff_bytes(a, b);
    if very_unlikely (d < 0)
        throwCantPack("ptr_udiff_bytes; take care");
    return ACC_ICONV(unsigned, d);
}
References ACC_ICONV, b, ptr_diff_bytes(), throwCantPack(), and very_unlikely.
Referenced by PeFile::Interval::add_interval(), LeFile::countFixups(), PackWcle::decodeEntryTable(), PackWcle::decodeFixups(), PackWcle::encodeEntryTable(), PeFile::Reloc::finish(), PackMachBase< TMachClass >::get_mod_init_func(), optimize_relocs(), Packer::optimizeReloc(), PackLinuxElf32::pack4(), PackLinuxElf64::pack4(), PackWcle::preprocessFixups(), PeFile::processImports0(), ptr_udiff(), PeFile::Reloc::readFromRelocationBlock(), PeFile::rebuildImports(), TEST_CASE(), Packer::unoptimizeReloc(), PackExe::unpack(), and PackMachBase< TMachClass >::unpack().
ptraddr_check_no_overlap() [1/2]
void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size)
Definition at line 147 of file util.cpp.
{
    if very_unlikely (a == 0 || b == 0)
        throwCantPack("ptr_check_no_overlap-nullptr");
    upx_ptraddr_t a_end = a + mem_size(1, a_size);
    upx_ptraddr_t b_end = b + mem_size(1, b_size);
    if very_unlikely (a_end < a || b_end < b) // wrap-around
        throwCantPack("ptr_check_no_overlap-overflow");
    // simple, but a little bit mind bending:
    //   same as (!(a >= b_end || b >= a_end))
    //   same as (!(a_end <= b || b_end <= a))
    if very_unlikely (a < b_end && b < a_end)
        throwCantPack("ptr_check_no_overlap-ab");
}
References b, mem_size(), throwCantPack(), and very_unlikely.
Referenced by ptr_check_no_overlap().
ptraddr_check_no_overlap() [2/2]
void ptraddr_check_no_overlap (upx_ptraddr_t a, size_t a_size, upx_ptraddr_t b, size_t b_size, upx_ptraddr_t c, size_t c_size)
Definition at line 162 of file util.cpp.
{
    if very_unlikely (a == 0 || b == 0 || c == 0)
        throwCantPack("ptr_check_no_overlap-nullptr");
    upx_ptraddr_t a_end = a + mem_size(1, a_size);
    upx_ptraddr_t b_end = b + mem_size(1, b_size);
    upx_ptraddr_t c_end = c + mem_size(1, c_size);
    if very_unlikely (a_end < a || b_end < b || c_end < c) // wrap-around
        throwCantPack("ptr_check_no_overlap-overflow");
    if very_unlikely (a < b_end && b < a_end)
        throwCantPack("ptr_check_no_overlap-ab");
    if very_unlikely (a < c_end && c < a_end)
        throwCantPack("ptr_check_no_overlap-ac");
    if very_unlikely (b < c_end && c < b_end)
        throwCantPack("ptr_check_no_overlap-bc");
}
References b, mem_size(), throwCantPack(), and very_unlikely.
set_method_name()
bool set_method_name (char * buf, size_t size, int method, int level)
Definition at line 869 of file util.cpp.
{
    bool r = true;
    const char *alg;
    if (M_IS_NRV2B(method))
        alg = "NRV2B";
    else if (M_IS_NRV2D(method))
        alg = "NRV2D";
    else if (M_IS_NRV2E(method))
        alg = "NRV2E";
    else if (M_IS_LZMA(method))
        alg = "LZMA";
    else {
        alg = "???";
        r = false;
    }
    if (level > 0)
        upx_safe_snprintf(buf, size, "%s/%d", alg, level);
    else
        upx_safe_snprintf(buf, size, "%s", alg);
    return r;
}
References buf, M_IS_LZMA, M_IS_NRV2B, M_IS_NRV2D, M_IS_NRV2E, size(), and upx_safe_snprintf().
Referenced by PackPs1::pack(), and UiPacker::printInfo().
TEST_CASE() [1/6]
TEST_CASE ("find")
Definition at line 721 of file util.cpp.
                  {
    CHECK(find(nullptr, -1, nullptr, -1) == -1);
    static const byte b[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
    CHECK(find(b, 16, b, 0) == -1);
    for (int i = 0; i < 16; i++) {
        CHECK(find(b, 16, b + i, 1) == i);
    }
    for (int i = 1; i <= 16; i++) {
        CHECK(find(b, 16, b, i) == 0);
    }
    CHECK(find(b, 16, b, 17) == -1);
    CHECK(find_be16(b, 16, 0x0203) == 2);
    CHECK(find_le16(b, 16, 0x0302) == 2);
    CHECK(find_be32(b, 16, 0x04050607) == 4);
    CHECK(find_le32(b, 16, 0x07060504) == 4);
    CHECK(find_be64(b, 16, 0x08090a0b0c0d0e0fULL) == 8);
    CHECK(find_le64(b, 16, 0x0f0e0d0c0b0a0908ULL) == 8);
    CHECK(find_be64(b, 15, 0x08090a0b0c0d0e0fULL) == -1);
    CHECK(find_le64(b, 15, 0x0f0e0d0c0b0a0908ULL) == -1);
    UNUSED(b);
}
References b, find(), find_be16(), find_be32(), find_be64(), find_le16(), find_le32(), find_le64(), and UNUSED.
TEST_CASE() [2/6]
TEST_CASE ("get_ratio")
Definition at line 1009 of file util.cpp.
                       {
    CHECK(get_ratio(0, 0) == 0);
    CHECK(get_ratio(0, 1) == 1000000);
    CHECK(get_ratio(1, 0) == 50);
    CHECK(get_ratio(1, 1) == 1000050);
    CHECK(get_ratio(1, 9) == 9000050);
    CHECK(get_ratio(1, 10) == 9999999);
    CHECK(get_ratio(1, 11) == 9999999);
    CHECK(get_ratio(100000, 100000) == 1000050);
    CHECK(get_ratio(100000, 200000) == 2000050);
    CHECK(get_ratio(UPX_RSIZE_MAX, UPX_RSIZE_MAX) == 1000050);
    CHECK(get_ratio(2 * UPX_RSIZE_MAX, 2 * UPX_RSIZE_MAX) == 1000050);
    CHECK(get_ratio(2 * UPX_RSIZE_MAX, 1024ull * UPX_RSIZE_MAX) == 9999999);
}
References get_ratio(), and UPX_RSIZE_MAX.
TEST_CASE() [3/6]
TEST_CASE ("mem_replace")
Definition at line 760 of file util.cpp.
{
    char b[16 + 1] = "aaaaaaaaaaaaaaaa";
    CHECK(mem_replace(b, 16, "a", 0, "x") == 0);
    CHECK(mem_replace(b, 16, "a", 1, "b") == 16);
    CHECK(mem_replace(b, 8, "bb", 2, "cd") == 4);
    CHECK(mem_replace(b + 8, 8, "bbb", 3, "efg") == 2);
    CHECK(mem_replace(b, 16, "b", 1, "h") == 2);
    CHECK(strcmp(b, "cdcdcdcdefgefghh") == 0);
    UNUSED(b);
}
References b, mem_replace(), strcmp(), and UNUSED.
TEST_CASE() [4/6]
TEST_CASE ("mem_size")
Definition at line 90 of file util.cpp.
                      {
    CHECK(mem_size_valid(1, 0));
    CHECK(mem_size_valid(1, 0x30000000));
    CHECK(!mem_size_valid(1, 0x30000000 + 1));
    CHECK(!mem_size_valid(1, 0x30000000, 1));
    CHECK(!mem_size_valid(1, 0x30000000, 0, 1));
    CHECK(!mem_size_valid(1, 0x30000000, 0x30000000, 0x30000000));
    CHECK_NOTHROW(mem_size(1, 0));
    CHECK_NOTHROW(mem_size(1, 0x30000000));
    CHECK_THROWS(mem_size(1, 0x30000000 + 1));
    CHECK_THROWS(mem_size(1, 0x30000000, 1));
    CHECK_THROWS(mem_size(1, 0x30000000, 0, 1));
    CHECK_THROWS(mem_size(1, 0x30000000, 0x30000000, 0x30000000));
}
References mem_size(), and mem_size_valid().
TEST_CASE() [5/6]
TEST_CASE ("ptr_diff")
Definition at line 133 of file util.cpp.
                      {
    byte buf[4] = {0, 1, 2, 3};
    CHECK_THROWS(ptr_diff_bytes(nullptr, buf));
    CHECK_THROWS(ptr_diff_bytes(buf, nullptr));
    CHECK(ptr_diff(buf, buf) == 0);
    CHECK(ptr_diff(buf + 1, buf) == 1);
    CHECK(ptr_diff(buf, buf + 1) == -1);
    CHECK(ptr_udiff(buf, buf) == 0);
    CHECK(ptr_udiff(buf + 1, buf) == 1);
    CHECK_THROWS(ptr_udiff(buf, buf + 1));
    UNUSED(buf);
}
References buf, ptr_diff(), ptr_diff_bytes(), ptr_udiff(), and UNUSED.
TEST_CASE() [6/6]
TEST_CASE ("upx_memswap")
Definition at line 423 of file util.cpp.
{
    auto check4 = [](int off1, int off2, int len, int a, int b, int c, int d) {
        byte p[4] = {0, 1, 2, 3};
        assert_noexcept(a + b + c + d == 0 + 1 + 2 + 3);
        upx_memswap(p + off1, p + off2, len);
        CHECK((p[0] == a && p[1] == b && p[2] == c && p[3] == d));
    };
    // identical
    check4(0, 0, 4, 0, 1, 2, 3);
    // non-overlapping
    check4(0, 1, 1, 1, 0, 2, 3);
    check4(1, 0, 1, 1, 0, 2, 3);
    check4(0, 2, 2, 2, 3, 0, 1);
    check4(2, 0, 2, 2, 3, 0, 1);
    // overlapping
    check4(0, 1, 2, 1, 2, 0, 3);
    check4(1, 0, 2, 1, 2, 0, 3);
    check4(0, 1, 3, 1, 2, 3, 0);
    check4(1, 0, 3, 1, 2, 3, 0);
    // pointer array
    {
        typedef byte element_type;
        element_type a = 11, b = 22;
        element_type *array[4];
        // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
        memset(array, 0xfb, sizeof(array));
        array[1] = &a;
        array[3] = &b;
        CHECK(*array[1] == 11);
        CHECK(*array[3] == 22);
#if defined(__CHERI__) && defined(__CHERI_PURE_CAPABILITY__)
        // TODO later: CHERI clang-14 bug/miscompilation with upx_memswap(); or
        //   maybe caused by tagged-memory issues ???
        // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
        memswap_no_overlap((byte *) array, (byte *) (array + 2), 2 * sizeof(array[0]));
#else
        // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
        upx_memswap(array, array + 2, 2 * sizeof(array[0]));
#endif
        CHECK(array[1] == &b);
        CHECK(array[3] == &a);
        CHECK(*array[1] == 22);
        CHECK(*array[3] == 11);
        // NOLINTNEXTLINE(bugprone-multi-level-implicit-pointer-conversion)
        memswap_no_overlap((byte *) array, (byte *) (array + 2), 2 * sizeof(array[0]));
        CHECK(array[1] == &a);
        CHECK(array[3] == &b);
        CHECK(*array[1] == 11);
        CHECK(*array[3] == 22);
    }
}
References assert_noexcept, b, memset(), memswap_no_overlap(), and upx_memswap().
upx_calloc()
void * upx_calloc (size_t n, size_t element_size)
stdlib
Definition at line 285 of file util.cpp.
{
    size_t bytes = mem_size(element_size, n); // assert size
    void *p = ::malloc(bytes);
    if (p != nullptr)
        memset(p, 0, bytes);
    return p;
}
References mem_size(), memset(), and n.
Referenced by main_get_envoptions(), and my_malloc().
upx_getenv()
const char * upx_getenv (const char * envvar) noexcept
stdlib
Definition at line 256 of file util.cpp.
{
    if (envvar != nullptr && envvar[0])
        return ::getenv(envvar);
    return nullptr;
}
Referenced by is_envvar_true(), main_get_envoptions(), Options::reset(), show_sysinfo(), TEST_CASE(), and upx_doctest_check().
upx_gnomesort()
void upx_gnomesort (void * array, size_t n, size_t element_size, upx_compare_func_t compare)
Definition at line 346 of file util.cpp.
{
    for (size_t i = 1; i < n; i++) {
        byte *a = (byte *) array + element_size * i;               // a := &array[i]
        if (i != 0 && compare(a - element_size, a) > 0) {          // if a[-1] > a[0] then
            memswap_no_overlap(a - element_size, a, element_size); //   swap elements a[-1] <=> a[0]
            i -= 2;                                                //   and decrease i
        }
    }
}
References memswap_no_overlap(), and n.
Referenced by anonymous_namespace{help.cpp}::PackerNames::add(), list_all_packers(), TEST_CASE(), and upx_std_stable_sort().
upx_memswap()
void upx_memswap (void * aa, void * bb, size_t bytes) noexcept
Definition at line 296 of file util.cpp.
{
    if (aa != bb && bytes != 0) {
        byte *a = (byte *) aa;
        byte *b = (byte *) bb;
        do {
            // strange clang-analyzer-15 false positive when compiling in Debug mode
            // clang-analyzer-core.uninitialized.Assign
            byte tmp = *a; // NOLINT(*core.uninitialized.Assign) // bogus clang-analyzer warning
            *a++ = *b;
            *b++ = tmp;
        } while (--bytes != 0);
    }
}
References b.
Referenced by memswap_no_overlap(), and TEST_CASE().
upx_rand()
int upx_rand (void) noexcept
Definition at line 263 of file util.cpp.
{
    return ::rand(); // NOLINT(clang-analyzer-security.insecureAPI.rand)
}
Referenced by Packer::getRandomId(), prepareFilters(), Packer::prepareMethods(), and TEST_CASE().
upx_rand_init()
void upx_rand_init (void) noexcept
Definition at line 267 of file util.cpp.
{
    unsigned seed = 0;
    seed ^= UPX_VERSION_HEX;
#if (!HAVE_GETTIMEOFDAY || (ACC_OS_DOS32 && defined(__DJGPP__))) && !defined(__wasi__)
    seed ^= (unsigned) time(nullptr);
    seed ^= ((unsigned) clock()) << 12;
#else
    struct timeval tv = {};
    (void) gettimeofday(&tv, nullptr);
    seed ^= (unsigned) tv.tv_sec;
    seed ^= ((unsigned) tv.tv_usec) << 12;
#endif
#if HAVE_GETPID
    seed ^= ((unsigned) getpid()) << 4;
#endif
    ::srand(seed);
}
References getpid(), gettimeofday(), timeval::tv_sec, timeval::tv_usec, and UPX_VERSION_HEX.
Referenced by main().
upx_shellsort_memcpy()
void upx_shellsort_memcpy (void * array, size_t n, size_t element_size, upx_compare_func_t compare)
Definition at line 374 of file util.cpp.
{
    mem_size_assert(element_size, n); // check size
    constexpr size_t MAX_INLINE_ELEMENT_SIZE = 256;
    upx_alignas_max byte tmp_buf[MAX_INLINE_ELEMENT_SIZE]; // buffer for one element
    byte *tmp = tmp_buf;
    if (element_size > MAX_INLINE_ELEMENT_SIZE) {
        tmp = (byte *) ::malloc(element_size);
        assert(tmp != nullptr);
    }
    size_t gap = 0;         // 0, 1, 4, 13, 40, 121, 364, 1093, ...
    while (gap * 3 + 1 < n) // cannot overflow because of size check above
        gap = gap * 3 + 1;
    for (; gap > 0; gap = (gap - 1) / 3) {
        const size_t gap_bytes = element_size * gap;
        byte *p = (byte *) array + gap_bytes;
        for (size_t i = gap; i < n; i += gap, p += gap_bytes) // invariant: p == &array[i]
            if (compare(p - gap_bytes, p) > 0) {
                byte *a = p;
                memcpy(tmp, a, element_size);
                do {
                    memcpy(a, a - gap_bytes, element_size);
                    a -= gap_bytes;
                } while (a != array && compare(a - gap_bytes, tmp) > 0);
                memcpy(a, tmp, element_size);
            }
    }
    if (element_size > MAX_INLINE_ELEMENT_SIZE)
        ::free(tmp);
}
References mem_size_assert(), memcpy(), n, and upx_alignas_max.
Referenced by TEST_CASE().
upx_shellsort_memswap()
void upx_shellsort_memswap (void * array, size_t n, size_t element_size, upx_compare_func_t compare)
Definition at line 358 of file util.cpp.
{
    mem_size_assert(element_size, n); // check size
    size_t gap = 0;                   // 0, 1, 4, 13, 40, 121, 364, 1093, ...
    while (gap * 3 + 1 < n)           // cannot overflow because of size check above
        gap = gap * 3 + 1;
    for (; gap > 0; gap = (gap - 1) / 3) {
        const size_t gap_bytes = element_size * gap;
        byte *p = (byte *) array + gap_bytes;
        for (size_t i = gap; i < n; i += gap, p += gap_bytes) // invariant: p == &array[i]
            for (byte *a = p; a != array && compare(a - gap_bytes, a) > 0; a -= gap_bytes)
                memswap_no_overlap(a - gap_bytes, a, element_size);
    }
}
References mem_size_assert(), memswap_no_overlap(), and n.
Referenced by TEST_CASE().
upx_std_stable_sort()
template<size_t ElementSize> void upx_std_stable_sort (void * array, size_t n, upx_compare_func_t compare)
Definition at line 406 of file util.cpp.
{
    static_assert(ElementSize >= 1 && ElementSize <= UPX_RSIZE_MAX);
    mem_size_assert(ElementSize, n); // check size
#if 0
    // just for testing
    upx_gnomesort(array, n, ElementSize, compare);
#else
    struct alignas(1) element_type { byte data[ElementSize]; };
    static_assert(sizeof(element_type) == ElementSize);
    static_assert(alignof(element_type) == 1);
    auto less = [compare](const element_type &a, const element_type &b) -> bool {
        return compare(&a, &b) < 0;
    };
    std::stable_sort((element_type *) array, (element_type *) array + n, less);
#endif
}
References b, data(), mem_size_assert(), n, upx_gnomesort(), and UPX_RSIZE_MAX.