My Project: src/work.cpp File Reference
work.cpp File Reference
#include "util/system_headers.h"
#include "conf.h"
#include "file.h"
#include "packmast.h"
#include "ui.h"
#include "util/membuffer.h"
Classes
struct anonymous_namespace{work.cpp}::XStat
Namespaces
namespace anonymous_namespace{work.cpp}
file util
Macros
#define WANT_WINDOWS_LEAN_H 1
#define USE_UTIME 1
#define SH_DENYRW (-1)
#define SH_DENYWR (-1)
#define IGNORE_ERROR(var) ACC_UNUSED(var)
Enumerations
enum anonymous_namespace{work.cpp}::OpenMode { anonymous_namespace{work.cpp}::RO_MUST_EXIST , anonymous_namespace{work.cpp}::WO_MUST_EXIST_TRUNCATE , anonymous_namespace{work.cpp}::WO_MUST_CREATE , anonymous_namespace{work.cpp}::WO_CREATE_OR_TRUNCATE }
Functions
static constexpr int anonymous_namespace{work.cpp}::get_open_flags (OpenMode om) noexcept
static void anonymous_namespace{work.cpp}::set_fd_timestamp (int fd, const XStat *xst) noexcept
static void anonymous_namespace{work.cpp}::copy_file_contents (const char *iname, const char *oname, OpenMode om, const XStat *oname_timestamp) may_throw
static void anonymous_namespace{work.cpp}::copy_file_attributes (const XStat *xst, const char *oname, bool preserve_mode, bool preserve_ownership, bool preserve_timestamp) noexcept
void do_one_file (const char *const iname, char *const oname) may_throw
process one file
static void unlink_ofile (char *oname) noexcept
process all files from the commandline
int do_files (int i, int argc, char *argv[]) may_throw
Macro Definition Documentation
IGNORE_ERROR
#define IGNORE_ERROR (var) ACC_UNUSED(var)
Definition at line 84 of file work.cpp.
SH_DENYRW
#define SH_DENYRW (-1)
Definition at line 61 of file work.cpp.
SH_DENYWR
#define SH_DENYWR (-1)
Definition at line 64 of file work.cpp.
USE_UTIME
#define USE_UTIME 1
Definition at line 57 of file work.cpp.
WANT_WINDOWS_LEAN_H
#define WANT_WINDOWS_LEAN_H 1
Definition at line 36 of file work.cpp.
Function Documentation
do_files()
int do_files (int i, int argc, char * argv[])
Definition at line 409 of file work.cpp.
{
    upx_compiler_sanity_check();
    if (opt->verbose >= 1) {
        show_header();
        UiPacker::uiHeader();
    }
    for (; i < argc; i++) {
        infoHeader();
        const char *const iname = argv[i];
        char oname[ACC_FN_PATH_MAX + 1];
        oname[0] = 0;
        try {
            do_one_file(iname, oname);
        } catch (const Exception &e) {
            unlink_ofile(oname);
            if (opt->verbose >= 1 || (opt->verbose >= 0 && !e.isWarning()))
                printErr(iname, e);
            main_set_exit_code(e.isWarning() ? EXIT_WARN : EXIT_ERROR);
            // this is not fatal, continue processing more files
        } catch (const Error &e) {
            unlink_ofile(oname);
            printErr(iname, e);
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (std::bad_alloc *e) {
            unlink_ofile(oname);
            printErr(iname, "out of memory");
            UNUSED(e);
            // delete e;
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (const std::bad_alloc &) {
            unlink_ofile(oname);
            printErr(iname, "out of memory");
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (std::exception *e) {
            unlink_ofile(oname);
            printUnhandledException(iname, e);
            // delete e;
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (const std::exception &e) {
            unlink_ofile(oname);
            printUnhandledException(iname, &e);
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        } catch (...) {
            unlink_ofile(oname);
            printUnhandledException(iname, nullptr);
            main_set_exit_code(EXIT_ERROR);
            return -1; // fatal error
        }
    }
    if (opt->cmd == CMD_COMPRESS)
        UiPacker::uiPackTotal();
    else if (opt->cmd == CMD_DECOMPRESS)
        UiPacker::uiUnpackTotal();
    else if (opt->cmd == CMD_LIST)
        UiPacker::uiListTotal();
    else if (opt->cmd == CMD_TEST)
        UiPacker::uiTestTotal();
    else if (opt->cmd == CMD_FILEINFO)
        UiPacker::uiFileInfoTotal();
    return 0;
}
References CMD_COMPRESS, CMD_DECOMPRESS, CMD_FILEINFO, CMD_LIST, CMD_TEST, do_one_file(), EXIT_ERROR, EXIT_WARN, infoHeader(), Throwable::isWarning(), main_set_exit_code(), opt, printErr(), printUnhandledException(), show_header(), UiPacker::uiFileInfoTotal(), UiPacker::uiHeader(), UiPacker::uiListTotal(), UiPacker::uiPackTotal(), UiPacker::uiTestTotal(), UiPacker::uiUnpackTotal(), unlink_ofile(), UNUSED, and upx_compiler_sanity_check().
Referenced by upx_main().
do_one_file()
void do_one_file (const char *const iname, char *const oname)
process one file
Definition at line 207 of file work.cpp.
{
    oname[0] = 0; // make empty
    // check iname stat
    XStat xst = {};
    struct stat &st = xst.st;
#if HAVE_LSTAT
    int rr = lstat(iname, &st);
#else
    int rr = stat(iname, &st);
#endif
    if (rr != 0) {
        if (errno == ENOENT)
            throw FileNotFoundException(iname, errno);
        else
            throwIOException(iname, errno);
    }
#if HAVE_LSTAT
    if (S_ISLNK(st.st_mode))
        throwIOException("is a symlink -- skipped");
#endif
    if (S_ISDIR(st.st_mode))
        throwIOException("is a directory -- skipped");
    if (!(S_ISREG(st.st_mode)))
        throwIOException("not a regular file -- skipped");
#if defined(__unix__)
    // no special bits may be set
    if ((st.st_mode & (S_ISUID | S_ISGID | S_ISVTX)) != 0)
        throwIOException("file has special permissions -- skipped");
#endif
    if (st.st_size <= 0)
        throwIOException("empty file -- skipped");
    if (st.st_size < 512)
        throwIOException("file is too small -- skipped");
    if (!mem_size_valid_bytes(st.st_size))
        throwIOException("file is too large -- skipped");
    if ((st.st_mode & S_IWUSR) == 0) {
        bool skip = true;
        if (opt->output_name)
            skip = false;
        else if (opt->to_stdout)
            skip = false;
        else if (opt->backup)
            skip = false;
        if (skip)
            throwIOException("file is write protected -- skipped");
    }
    // open input file
    InputFile fi;
    fi.sopen(iname, get_open_flags(RO_MUST_EXIST), SH_DENYWR);
    if (opt->preserve_timestamp) {
#if USE_SETFILETIME
        if (GetFileTime((HANDLE) _get_osfhandle(fi.getFd()), nullptr, &xst.ft_atime,
                        &xst.ft_mtime) == 0)
            throwIOException("cannot determine file timestamp");
#elif USE_FTIME
        if (getftime(fi.getFd(), &xst.ft_ftime) != 0)
            throwIOException("cannot determine file timestamp");
#endif
    }
    // open output file
    // NOTE: only use "preserve_link" if you really need it, e.g. it can fail
    //   with ETXTBSY and other unexpected errors; renaming files is much safer
    OutputFile fo;
    bool preserve_link = opt->preserve_link;
    bool copy_timestamp_only = false;
    if (opt->cmd == CMD_COMPRESS || opt->cmd == CMD_DECOMPRESS) {
        if (opt->to_stdout) {
            preserve_link = false; // not needed
            if (!fo.openStdout(1, opt->force ? true : false))
                throwIOException("data not written to a terminal; Use '-f' to force.");
        } else {
            char tname[ACC_FN_PATH_MAX + 1];
            if (opt->output_name) {
                strcpy(tname, opt->output_name);
                if ((opt->force_overwrite || opt->force >= 2) && !preserve_link)
                    (void) FileBase::unlink_noexcept(tname); // IGNORE_ERROR
            } else {
                if (st.st_nlink < 2)
                    preserve_link = false; // not needed
                if (!maketempname(tname, sizeof(tname), iname, ".upx"))
                    throwIOException("could not create a temporary file name");
            }
            int flags = get_open_flags(WO_MUST_CREATE); // don't overwrite files by default
            if (opt->output_name && preserve_link) {
                flags = get_open_flags(WO_CREATE_OR_TRUNCATE);
#if HAVE_LSTAT
                struct stat ost = {};
                int r = lstat(tname, &ost);
                if (r == 0 && S_ISREG(ost.st_mode)) {
                    preserve_link = ost.st_nlink >= 2;
                } else if (r == 0 && S_ISLNK(ost.st_mode)) {
                    // output_name is a symlink (valid or dangling)
                    (void) FileBase::unlink_noexcept(tname); // IGNORE_ERROR
                    preserve_link = false;                   // not needed
                } else {
                    preserve_link = false; // not needed
                }
#endif
                if (preserve_link) {
                    flags = get_open_flags(WO_MUST_EXIST_TRUNCATE);
                    copy_timestamp_only = true;
                }
            } else if (opt->force_overwrite || opt->force) {
                flags = get_open_flags(WO_CREATE_OR_TRUNCATE);
            }
            int shmode = SH_DENYWR;
#if (ACC_ARCH_M68K && ACC_OS_TOS && ACC_CC_GNUC) && defined(__MINT__)
            // TODO later: check current mintlib if this hack is still needed
            flags |= O_TRUNC;
            shmode = O_DENYRW;
#endif
            // cannot rely on open() because of umask
            // int omode = st.st_mode | 0600;
            int omode = opt->preserve_mode ? 0600 : 0666; // affected by umask; only for O_CREAT
            fo.sopen(tname, flags, shmode, omode);
            // open succeeded - now set oname[]
            strcpy(oname, tname);
        }
    }
    // handle command - actual work starts HERE
    PackMaster pm(&fi, opt);
    if (opt->cmd == CMD_COMPRESS)
        pm.pack(&fo);
    else if (opt->cmd == CMD_DECOMPRESS)
        pm.unpack(&fo);
    else if (opt->cmd == CMD_TEST)
        pm.test();
    else if (opt->cmd == CMD_LIST)
        pm.list();
    else if (opt->cmd == CMD_FILEINFO)
        pm.fileInfo();
    else
        throwInternalError("invalid command");
    // copy time stamp
    if (oname[0] && opt->preserve_timestamp && fo.isOpen())
        set_fd_timestamp(fo.getFd(), &xst);
    // close files
    fi.closex();
    fo.closex();
    // rename or copy files
    if (oname[0] && !opt->output_name) {
        // both iname and oname do exist; rename oname to iname
        if (opt->backup) {
            char bakname[ACC_FN_PATH_MAX + 1];
            if (!makebakname(bakname, sizeof(bakname), iname))
                throwIOException("could not create a backup file name");
            if (preserve_link) {
                copy_file_contents(iname, bakname, WO_MUST_CREATE, &xst);
                copy_file_attributes(&xst, bakname, true, true, true);
                const XStat *xstamp = opt->preserve_timestamp ? &xst : nullptr;
                copy_file_contents(oname, iname, WO_MUST_EXIST_TRUNCATE, xstamp);
                FileBase::unlink(oname);
                copy_timestamp_only = true;
            } else {
                FileBase::rename(iname, bakname);
                FileBase::rename(oname, iname);
            }
        } else if (preserve_link) {
            const XStat *xstamp = opt->preserve_timestamp ? &xst : nullptr;
            copy_file_contents(oname, iname, WO_MUST_EXIST_TRUNCATE, xstamp);
            FileBase::unlink(oname);
            copy_timestamp_only = true;
        } else {
            FileBase::unlink(iname);
            FileBase::rename(oname, iname);
        }
        // now iname is the new packed/unpacked file and oname does not exist any longer
    }
    // copy file attributes
    if (oname[0]) {
        oname[0] = 0; // done with oname
        const char *name = opt->output_name ? opt->output_name : iname;
        if (copy_timestamp_only)
            copy_file_attributes(&xst, name, false, false, opt->preserve_timestamp);
        else
            copy_file_attributes(&xst, name, opt->preserve_mode, opt->preserve_ownership,
                                 opt->preserve_timestamp);
    }
    UiPacker::uiConfirmUpdate();
}
References FileBase::closex(), CMD_COMPRESS, CMD_DECOMPRESS, CMD_FILEINFO, CMD_LIST, CMD_TEST, anonymous_namespace{work.cpp}::copy_file_attributes(), anonymous_namespace{work.cpp}::copy_file_contents(), ENOENT, PackMaster::fileInfo(), anonymous_namespace{work.cpp}::get_open_flags(), FileBase::getFd(), FileBase::isOpen(), PackMaster::list(), makebakname(), maketempname(), mem_size_valid_bytes(), OutputFile::openStdout(), opt, PackMaster::pack(), FileBase::rename(), anonymous_namespace{work.cpp}::RO_MUST_EXIST, anonymous_namespace{work.cpp}::set_fd_timestamp(), SH_DENYWR, InputFile::sopen(), OutputFile::sopen(), strcpy(), PackMaster::test(), throwInternalError(), throwIOException(), UiPacker::uiConfirmUpdate(), FileBase::unlink(), FileBase::unlink_noexcept(), PackMaster::unpack(), anonymous_namespace{work.cpp}::WO_CREATE_OR_TRUNCATE, anonymous_namespace{work.cpp}::WO_MUST_CREATE, and anonymous_namespace{work.cpp}::WO_MUST_EXIST_TRUNCATE.
Referenced by do_files().
unlink_ofile()
static void unlink_ofile (char * oname) static noexcept
process all files from the commandline
Definition at line 402 of file work.cpp.
{
    if (oname && oname[0]) {
        (void) FileBase::unlink_noexcept(oname); // IGNORE_ERROR
        oname[0] = 0;                            // done with oname
    }
}
References FileBase::unlink_noexcept().
Referenced by do_files().