My Project: src/util/xspan_impl_common.h File Reference
xspan_impl_common.h File Reference
Typedefs
typedef T element_type
typedef std::add_lvalue_reference< T >::type reference
typedef std::add_pointer< T >::type pointer
typedef size_t size_type
Enumerations
enum ModeUnchecked { Unchecked }
Functions
forceinline void assertInvariants () const noexcept
static pointer makeNotNull (pointer p)
static pointer makePtr (pointer p)
static pointer makeBase (pointer b)
pointer ensurePtr () const
pointer ensureBase () const
forceinline ~CSelf () noexcept
noinline void invalidate ()
CSelf (pointer first, XSpanCount count)
CSelf (pointer first, XSpanSizeInBytes bytes)
template<class U >
CSelf (U *first, size_type count, XSPAN_REQUIRES_SIZE_1_A)
CSelf (pointer first, XSpanCount count, pointer base_)
CSelf (pointer first, XSpanSizeInBytes bytes, pointer base_)
template<class U >
CSelf (pointer first, size_type count, U *base_, XSPAN_REQUIRES_SIZE_1_A)
CSelf (std::nullptr_t, XSpanCount) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanCount, std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (const void *, XSpanCount, std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanSizeInBytes) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, XSpanSizeInBytes, std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (const void *, XSpanSizeInBytes, std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, size_type) XSPAN_DELETED_FUNCTION
CSelf (std::nullptr_t, size_type, std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (const void *, size_type, std::nullptr_t) XSPAN_DELETED_FUNCTION
CSelf (ModeUnchecked, pointer p, size_type bytes, pointer b)
Self & assign (ModeUnchecked, pointer p, size_type bytes, pointer b)
Self & assign (pointer other)
Self & assign (const Self &other)
Self & operator= (pointer other)
Self & operator= (const Self &other)
template<class U >
operator= (const CSelf< U > &other)
Self subspan (ptrdiff_t offset, ptrdiff_t count) const
Self subspan (ptrdiff_t offset) const
template<class U >
CSelf< U > type_cast () const
bool operator== (pointer other) const noexcept
template<class U >
operator== (U *other) const noexcept
bool operator!= (pointer other) const noexcept
template<class U >
operator!= (U *other) const noexcept
template<class U >
operator== (const PtrOrSpan< U > &other) const noexcept
template<class U >
operator== (const PtrOrSpanOrNull< U > &other) const noexcept
template<class U >
operator== (const Span< U > &other) const noexcept
template<class U >
operator!= (const PtrOrSpan< U > &other) const noexcept
template<class U >
operator!= (const PtrOrSpanOrNull< U > &other) const noexcept
template<class U >
operator!= (const Span< U > &other) const noexcept
bool operator< (std::nullptr_t) const XSPAN_DELETED_FUNCTION
bool operator< (pointer other) const
template<class U >
operator< (const PtrOrSpan< U > &other) const
template<class U >
operator< (const PtrOrSpanOrNull< U > &other) const
template<class U >
operator< (const Span< U > &other) const
reference operator* () const
reference operator[] (ptrdiff_t i) const
pointer operator-> () const
Self & operator++ ()
Self operator++ (int)
Self & operator-- ()
Self operator-- (int)
Self & operator+= (ptrdiff_t n)
Self & operator-= (ptrdiff_t n)
Self operator+ (ptrdiff_t n) const
Self operator- (ptrdiff_t n) const
pointer check_deref (pointer p) const
pointer check_deref (pointer p, ptrdiff_t n) const
pointer check_add (pointer p, ptrdiff_t n) const
Self * operator& () const XSPAN_DELETED_FUNCTION
pointer raw_ptr () const noexcept
pointer raw_base () const noexcept
size_type raw_size_in_bytes () const noexcept
pointer raw_bytes (size_t bytes) const
pointer data () const noexcept
pointer data (size_t bytes) const
size_type size () const
size_type size_bytes () const
Variables
pointer ptr
pointer base
size_type size_in_bytes
Typedef Documentation
element_type
typedef T element_type
Definition at line 37 of file xspan_impl_common.h.
pointer
typedef std::add_pointer<T>::type pointer
Definition at line 39 of file xspan_impl_common.h.
reference
typedef std::add_lvalue_reference<T>::type reference
Definition at line 38 of file xspan_impl_common.h.
size_type
typedef size_t size_type
Definition at line 40 of file xspan_impl_common.h.
Enumeration Type Documentation
ModeUnchecked
enum ModeUnchecked protected
Enumerator
Unchecked
Definition at line 194 of file xspan_impl_common.h.
{ Unchecked };
Function Documentation
assertInvariants()
forceinline void assertInvariants () const private noexcept
Definition at line 72 of file xspan_impl_common.h.
{}
Referenced by assign(), check_add(), check_deref(), Span< T >::CSelf(), PtrOrSpanOrNull< T >::CSelf(), PtrOrSpan< T >::CSelf(), CSelf(), invalidate(), PtrOrSpan< T >::operator!=(), Span< T >::operator!=(), PtrOrSpan< T >::operator==(), Span< T >::operator==(), raw_bytes(), and size_bytes().
assign() [1/3]
Self & assign (const Self & other)
Definition at line 231 of file xspan_impl_common.h.
{
        assertInvariants();
        other.assertInvariants();
        if __acc_cte (!configRequireBase && base == nullptr) {
            // magic 1: if base is unset, automatically set base/size_in_bytes from other
            if __acc_cte ((configRequirePtr || other.ptr != nullptr) &&
                          (configRequireBase || other.base != nullptr))
                xspan_check_range(other.ptr, other.base, other.size_in_bytes);
            // ok
            ptr = other.ptr;
            base = other.base;
            size_in_bytes = other.size_in_bytes;
        } else {
            // magic 2: assert same base (but ignore size_in_bytes !)
            if __acc_cte (configRequireBase || other.base != nullptr)
                if very_unlikely (base != other.base)
                    xspan_fail_not_same_base();
            if __acc_cte ((configRequirePtr || other.ptr != nullptr) &&
                          (configRequireBase || base != nullptr))
                xspan_check_range(other.ptr, base, size_in_bytes);
            // ok
            ptr = other.ptr;
        }
        assertInvariants();
        return *this;
    }
References __acc_cte, assertInvariants(), base, ptr, size_in_bytes, very_unlikely, xspan_check_range(), and xspan_fail_not_same_base().
assign() [2/3]
Self & assign (ModeUnchecked , pointer p, size_type bytes, pointer b) protected
Definition at line 200 of file xspan_impl_common.h.
{
        ptr = p;
        base = b;
        size_in_bytes = bytes;
        assertInvariants();
        return *this;
    }
References assertInvariants(), b, base, ptr, and size_in_bytes.
Referenced by PtrOrSpanOrNull< T >::operator=(), PtrOrSpan< T >::operator=(), and operator=().
assign() [3/3]
Self & assign (pointer other)
Definition at line 220 of file xspan_impl_common.h.
{
        assertInvariants();
        other = makePtr(other);
        if __acc_cte ((configRequirePtr || other != nullptr) &&
                      (configRequireBase || base != nullptr))
            xspan_check_range(other, base, size_in_bytes);
        // ok
        ptr = other;
        assertInvariants();
        return *this;
    }
References __acc_cte, assertInvariants(), base, makePtr(), ptr, size_in_bytes, and xspan_check_range().
check_add()
pointer check_add (pointer p, ptrdiff_t n) const private
Definition at line 425 of file xspan_impl_common.h.
{
        assertInvariants();
        if __acc_cte (!configRequirePtr && p == nullptr)
            xspan_fail_nullptr();
        xspan_mem_size_assert_ptrdiff<T>(n);
        p += n;
        if __acc_cte (configRequireBase || base != nullptr)
            xspan_check_range(p, base, size_in_bytes);
        return p;
    }
References __acc_cte, assertInvariants(), base, n, size_in_bytes, xspan_check_range(), and xspan_fail_nullptr().
Referenced by operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), and subspan().
check_deref() [1/2]
pointer check_deref (pointer p) const private
Definition at line 407 of file xspan_impl_common.h.
{
        assertInvariants();
        if __acc_cte (!configRequirePtr && p == nullptr)
            xspan_fail_nullptr();
        if __acc_cte (configRequireBase || base != nullptr)
            xspan_check_range(p, base, size_in_bytes - sizeof(T));
        return p;
    }
References __acc_cte, assertInvariants(), base, size_in_bytes, xspan_check_range(), and xspan_fail_nullptr().
Referenced by operator*(), operator->(), and operator[]().
check_deref() [2/2]
pointer check_deref (pointer p, ptrdiff_t n) const private
Definition at line 415 of file xspan_impl_common.h.
{
        assertInvariants();
        if __acc_cte (!configRequirePtr && p == nullptr)
            xspan_fail_nullptr();
        xspan_mem_size_assert_ptrdiff<T>(n);
        p += n;
        if __acc_cte (configRequireBase || base != nullptr)
            xspan_check_range(p, base, size_in_bytes - sizeof(T));
        return p;
    }
References __acc_cte, assertInvariants(), base, n, size_in_bytes, xspan_check_range(), and xspan_fail_nullptr().
CSelf() [1/16]
CSelf (const void * , size_type , std::nullptr_t) private
CSelf() [2/16]
CSelf (const void * , XSpanCount , std::nullptr_t) private
CSelf() [3/16]
CSelf (const void * , XSpanSizeInBytes , std::nullptr_t) private
CSelf() [4/16]
CSelf (ModeUnchecked , pointer p, size_type bytes, pointer b) protected
Definition at line 195 of file xspan_impl_common.h.
        : ptr(p), base(b), size_in_bytes(bytes) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [5/16]
template<class U > CSelf (pointer first, size_type count, U * base_, XSPAN_REQUIRES_SIZE_1_A)
Definition at line 161 of file xspan_impl_common.h.
        : ptr(makePtr(first)), base(makeBase(base_)), size_in_bytes(xspan_mem_size<T>(count)) {
        // check invariants
        if __acc_cte ((configRequirePtr || ptr != nullptr) &&
                      (configRequireBase || base != nullptr))
            xspan_check_range(ptr, base, size_in_bytes);
        // double sanity check
        assertInvariants();
    }
References __acc_cte, assertInvariants(), base, ptr, size_in_bytes, and xspan_check_range().
CSelf() [6/16]
CSelf (pointer first, XSpanCount count)
Definition at line 123 of file xspan_impl_common.h.
        : ptr(makePtr(first)), base(makeBase(first)),
          size_in_bytes(xspan_mem_size<T>(count.count)) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [7/16]
CSelf (pointer first, XSpanCount count, pointer base_)
Definition at line 139 of file xspan_impl_common.h.
        : ptr(makePtr(first)), base(makeBase(base_)),
          size_in_bytes(xspan_mem_size<T>(count.count)) {
        // check invariants
        if __acc_cte ((configRequirePtr || ptr != nullptr) &&
                      (configRequireBase || base != nullptr))
            xspan_check_range(ptr, base, size_in_bytes);
        // double sanity check
        assertInvariants();
    }
References __acc_cte, assertInvariants(), base, ptr, size_in_bytes, and xspan_check_range().
CSelf() [8/16]
CSelf (pointer first, XSpanSizeInBytes bytes)
Definition at line 128 of file xspan_impl_common.h.
        : ptr(makePtr(first)), base(makeBase(first)),
          size_in_bytes(xspan_mem_size<char>(bytes.size_in_bytes)) {
        assertInvariants();
    }
References assertInvariants().
CSelf() [9/16]
CSelf (pointer first, XSpanSizeInBytes bytes, pointer base_)
Definition at line 149 of file xspan_impl_common.h.
        : ptr(makePtr(first)), base(makeBase(base_)),
          size_in_bytes(xspan_mem_size<char>(bytes.size_in_bytes)) {
        // check invariants
        if __acc_cte ((configRequirePtr || ptr != nullptr) &&
                      (configRequireBase || base != nullptr))
            xspan_check_range(ptr, base, size_in_bytes);
        // double sanity check
        assertInvariants();
    }
References __acc_cte, assertInvariants(), base, ptr, size_in_bytes, and xspan_check_range().
CSelf() [10/16]
CSelf (std::nullptr_t , size_type) private
CSelf() [11/16]
CSelf (std::nullptr_t , size_type , std::nullptr_t) private
CSelf() [12/16]
CSelf (std::nullptr_t , XSpanCount) private
CSelf() [13/16]
CSelf (std::nullptr_t , XSpanCount , std::nullptr_t) private
CSelf() [14/16]
CSelf (std::nullptr_t , XSpanSizeInBytes) private
CSelf() [15/16]
CSelf (std::nullptr_t , XSpanSizeInBytes , std::nullptr_t) private
CSelf() [16/16]
template<class U > CSelf (U * first, size_type count, XSPAN_REQUIRES_SIZE_1_A)
Definition at line 135 of file xspan_impl_common.h.
        : ptr(makePtr(first)), base(makeBase(first)), size_in_bytes(xspan_mem_size<T>(count)) {
        assertInvariants();
    }
References assertInvariants().
data() [1/2]
pointer data () const noexcept
Definition at line 458 of file xspan_impl_common.h.
{ return ptr; }
References ptr.
Referenced by MyLzma::OutStream::Init(), MyLzma::InStream::Init(), PackMachBase< TMachClass >::pack4dylib(), N_Mach::packed_struct(), MyLzma::InStream::Read(), PackMachBase< TMachClass >::unpack(), upx_std_stable_sort(), and MyLzma::OutStream::Write().
data() [2/2]
pointer data (size_t bytes) const
Definition at line 459 of file xspan_impl_common.h.
{ return raw_bytes(bytes); } // UPX extra
References raw_bytes().
ensureBase()
pointer ensureBase () const inline private
Definition at line 97 of file xspan_impl_common.h.
{
        if __acc_cte (!configRequireBase && base == nullptr)
            xspan_fail_nullbase();
        return base;
    }
References __acc_cte, base, and xspan_fail_nullbase().
ensurePtr()
pointer ensurePtr () const inline private
Definition at line 92 of file xspan_impl_common.h.
{
        if __acc_cte (!configRequirePtr && ptr == nullptr)
            xspan_fail_nullptr();
        return ptr;
    }
References __acc_cte, ptr, and xspan_fail_nullptr().
Referenced by operator<().
invalidate()
noinline void invalidate ()
Definition at line 115 of file xspan_impl_common.h.
{
        assertInvariants();
        ptr_invalidate_and_poison(ptr); // point to non-null invalid address
        base = ptr;                     // point to non-null invalid address
        size_in_bytes = 0;
        assertInvariants();
    }
References assertInvariants(), base, ptr, ptr_invalidate_and_poison(), and size_in_bytes.
makeBase()
static pointer makeBase (pointer b) inline static private
Definition at line 86 of file xspan_impl_common.h.
{
        if __acc_cte (configRequireBase && b == nullptr)
            xspan_fail_nullbase();
        return b;
    }
References __acc_cte, b, and xspan_fail_nullbase().
makeNotNull()
static pointer makeNotNull (pointer p) inline static private
Definition at line 75 of file xspan_impl_common.h.
{
        if very_unlikely (p == nullptr)
            xspan_fail_nullptr();
        return p;
    }
References very_unlikely, and xspan_fail_nullptr().
Referenced by operator<().
makePtr()
static pointer makePtr (pointer p) inline static private
Definition at line 81 of file xspan_impl_common.h.
{
        if __acc_cte (configRequirePtr && p == nullptr)
            xspan_fail_nullptr();
        return p;
    }
References __acc_cte, and xspan_fail_nullptr().
Referenced by assign().
operator!=() [1/5]
template<class U > operator!= (const PtrOrSpan< U > & other) const noexcept
Definition at line 326 of file xspan_impl_common.h.
{
        return ptr != other.ptr;
    }
References ptr.
operator!=() [2/5]
template<class U > operator!= (const PtrOrSpanOrNull< U > & other) const noexcept
Definition at line 331 of file xspan_impl_common.h.
{
        return ptr != other.ptr;
    }
References ptr.
operator!=() [3/5]
template<class U > operator!= (const Span< U > & other) const noexcept
Definition at line 336 of file xspan_impl_common.h.
{
        return ptr != other.ptr;
    }
References ptr.
operator!=() [4/5]
bool operator!= (pointer other) const noexcept
Definition at line 301 of file xspan_impl_common.h.
{ return ptr != other; }
References ptr.
operator!=() [5/5]
template<class U > operator!= (U * other) const noexcept
Definition at line 304 of file xspan_impl_common.h.
{
        return ptr != other;
    }
References ptr.
operator&()
Self * operator& () const private
operator*()
reference operator* () const
Definition at line 361 of file xspan_impl_common.h.
{ return *check_deref(ptr); }
References check_deref(), and ptr.
operator+()
Self operator+ (ptrdiff_t n) const
Definition at line 397 of file xspan_impl_common.h.
{
        pointer first = check_add(ptr, n);
        return Self(Unchecked, first, size_in_bytes, base);
    }
References base, check_add(), n, ptr, size_in_bytes, and Unchecked.
operator++() [1/2]
Self & operator++ ()
Definition at line 369 of file xspan_impl_common.h.
                       {
        ptr = check_add(ptr, 1);
        return *this;
    }
References check_add(), and ptr.
operator++() [2/2]
Self operator++ (int)
Definition at line 373 of file xspan_impl_common.h.
{
        Self tmp = *this;
        ++*this;
        return tmp;
    }
operator+=()
Self & operator+= (ptrdiff_t n)
Definition at line 388 of file xspan_impl_common.h.
{
        ptr = check_add(ptr, n);
        return *this;
    }
References check_add(), n, and ptr.
operator-()
Self operator- (ptrdiff_t n) const
Definition at line 401 of file xspan_impl_common.h.
{
        pointer first = check_add(ptr, -n);
        return Self(Unchecked, first, size_in_bytes, base);
    }
References base, check_add(), n, ptr, size_in_bytes, and Unchecked.
operator--() [1/2]
Self & operator-- ()
Definition at line 378 of file xspan_impl_common.h.
                       {
        ptr = check_add(ptr, -1);
        return *this;
    }
References check_add(), and ptr.
operator--() [2/2]
Self operator-- (int)
Definition at line 382 of file xspan_impl_common.h.
{
        Self tmp = *this;
        --*this;
        return tmp;
    }
operator-=()
Self & operator-= (ptrdiff_t n)
Definition at line 392 of file xspan_impl_common.h.
{
        ptr = check_add(ptr, -n);
        return *this;
    }
References check_add(), n, and ptr.
operator->()
pointer operator-> () const
Definition at line 367 of file xspan_impl_common.h.
{ return check_deref(ptr); }
References check_deref(), and ptr.
operator<() [1/5]
template<class U > operator< (const PtrOrSpan< U > & other) const
Definition at line 342 of file xspan_impl_common.h.
{
        return ensurePtr() < other.ensurePtr();
    }
operator<() [2/5]
template<class U > operator< (const PtrOrSpanOrNull< U > & other) const
Definition at line 342 of file xspan_impl_common.h.
{
        return ensurePtr() < other.ensurePtr();
    }
operator<() [3/5]
template<class U > operator< (const Span< U > & other) const
Definition at line 342 of file xspan_impl_common.h.
{
        return ensurePtr() < other.ensurePtr();
    }
operator<() [4/5]
bool operator< (pointer other) const
Definition at line 342 of file xspan_impl_common.h.
{ return ensurePtr() < makeNotNull(other); }
References ensurePtr(), and makeNotNull().
operator<() [5/5]
bool operator< (std::nullptr_t) const
operator=() [1/3]
template<class U > operator= (const CSelf< U > & other)
Definition at line 265 of file xspan_impl_common.h.
{
        // assert(0);
        return assign(Self(other));
    }
References assign().
operator=() [2/3]
Self & operator= (const Self & other)
Definition at line 260 of file xspan_impl_common.h.
{ return assign(other); }
References assign().
operator=() [3/3]
Self & operator= (pointer other)
Definition at line 258 of file xspan_impl_common.h.
{ return assign(other); }
References assign().
operator==() [1/5]
template<class U > operator== (const PtrOrSpan< U > & other) const noexcept
Definition at line 310 of file xspan_impl_common.h.
{
        return ptr == other.ptr;
    }
References ptr.
operator==() [2/5]
template<class U > operator== (const PtrOrSpanOrNull< U > & other) const noexcept
Definition at line 315 of file xspan_impl_common.h.
{
        return ptr == other.ptr;
    }
References ptr.
operator==() [3/5]
template<class U > operator== (const Span< U > & other) const noexcept
Definition at line 320 of file xspan_impl_common.h.
{
        return ptr == other.ptr;
    }
References ptr.
operator==() [4/5]
bool operator== (pointer other) const noexcept
Definition at line 295 of file xspan_impl_common.h.
{ return ptr == other; }
References ptr.
operator==() [5/5]
template<class U > operator== (U * other) const noexcept
Definition at line 298 of file xspan_impl_common.h.
{
        return ptr == other;
    }
References ptr.
operator[]()
reference operator[] (ptrdiff_t i) const
Definition at line 364 of file xspan_impl_common.h.
{ return *check_deref(ptr, i); }
References check_deref(), and ptr.
raw_base()
pointer raw_base () const noexcept
Definition at line 442 of file xspan_impl_common.h.
{ return base; }
References base.
raw_bytes()
pointer raw_bytes (size_t bytes) const
Definition at line 445 of file xspan_impl_common.h.
{
        assertInvariants();
        if (bytes > 0) {
            if __acc_cte (!configRequirePtr && ptr == nullptr)
                xspan_fail_nullptr();
            if __acc_cte (configRequireBase || base != nullptr) {
                xspan_check_range(ptr, base, size_in_bytes - bytes);
            }
        }
        return ptr;
    }
References __acc_cte, assertInvariants(), base, ptr, raw_bytes(), size_in_bytes, xspan_check_range(), and xspan_fail_nullptr().
raw_ptr()
pointer raw_ptr () const noexcept
Definition at line 441 of file xspan_impl_common.h.
{ return ptr; }
References ptr.
raw_size_in_bytes()
size_type raw_size_in_bytes () const noexcept
Definition at line 443 of file xspan_impl_common.h.
{ return size_in_bytes; }
References size_in_bytes.
size()
size_type size () const
Definition at line 460 of file xspan_impl_common.h.
{ return size_bytes() / sizeof(element_type); }
References size_bytes().
Referenced by alloc_file_image(), PeFile::ImportLinker::build(), PeFile::Export::build(), PackWinCeArm::buildLoader(), PackMachFat::canPack(), PackMachFat::canUnpack(), center_string(), PackMachFat::check_fat_head(), Packer::checkPatch(), PeFile::Export::convert(), PackHeader::decodePackHeaderFromBuf(), F(), Packer::getDecompressorWrkmemSize(), Packer::getLoader(), Packer::getLoaderSection(), Packer::getLoaderSectionStart(), Packer::getLoaderSize(), PackLinuxI386sh::getShellName(), PeFile::Export::getsize(), grow_capacity(), Packer::handleStub(), infoWriting(), MyLzma::OutStream::Init(), MyLzma::InStream::Init(), Packer::initLoader(), makebakname(), maketempname(), mem_clear(), PackDjgpp2::pack(), packed_struct(), N_Mach::packed_struct(), Packer::patchPackHeader(), ElfLinker::preprocessSections(), PackHeader::putPackHeader(), MyLzma::InStream::Read(), PeFile::readSections(), set_method_name(), show_sysinfo(), PeFile::stripDebug(), subspan(), PeFile::tryremove(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackMachBase< TMachClass >::unpack(), PeFile::unpack0(), upx_safe_vsnprintf(), upx_safe_vsnprintf_noexcept(), and MyLzma::OutStream::Write().
size_bytes()
size_type size_bytes () const
Definition at line 461 of file xspan_impl_common.h.
{
        assertInvariants();
        if __acc_cte (!configRequirePtr && ptr == nullptr)
            return 0;
        if __acc_cte (!configRequireBase && base == nullptr)
            return 0;
        const charptr p_begin = (const charptr) ptr;
        const charptr p_end = (const charptr) base + size_in_bytes;
        return p_end - p_begin;
    }
References __acc_cte, assertInvariants(), base, charptr, ptr, and size_in_bytes.
Referenced by size().
subspan() [1/2]
Self subspan (ptrdiff_t offset) const
Definition at line 284 of file xspan_impl_common.h.
{ return subspan(offset, size() - offset); }
References size(), and subspan().
subspan() [2/2]
Self subspan (ptrdiff_t offset, ptrdiff_t count) const
Definition at line 275 of file xspan_impl_common.h.
{
        pointer p_begin = check_add(ptr, offset);
        pointer p_end = check_add(p_begin, count);
        if (p_begin <= p_end)
            return Self(Unchecked, p_begin, (p_end - p_begin) * sizeof(T), p_begin);
        else
            return Self(Unchecked, p_end, (p_begin - p_end) * sizeof(T), p_end);
    }
References check_add(), ptr, and Unchecked.
Referenced by subspan().
type_cast()
template<class U > CSelf< U > type_cast () const inline
Definition at line 288 of file xspan_impl_common.h.
{
        typedef CSelf<U> R;
        typedef typename R::pointer rpointer;
        return R(R::Unchecked, upx::ptr_static_cast<rpointer>(ptr), size_in_bytes,
                 upx::ptr_static_cast<rpointer>(base));
    }
References base, ptr, and size_in_bytes.
~CSelf()
forceinline ~CSelf () noexcept
Definition at line 113 of file xspan_impl_common.h.
{}
Variable Documentation
base
pointer base private
Definition at line 57 of file xspan_impl_common.h.
Referenced by PeFile::Interval::add_interval(), assign(), check_add(), check_deref(), PeFile::Interval::clear(), PeFile::Export::convert(), CSelf(), PackVmlinuzI386::decompressKernel(), ensureBase(), PackLinuxElf32::getbase(), invalidate(), operator+(), operator-(), PackMachFat::pack(), PackLinuxElf32x86interp::pack3(), raw_base(), raw_bytes(), size_bytes(), anonymous_namespace{pefile.cpp}::VPtr< T >::SPAN_S(), type_cast(), PackMachFat::unpack(), and xspan_check_range().
ptr
pointer ptr private
Definition at line 56 of file xspan_impl_common.h.
size_in_bytes
size_type size_in_bytes private
Definition at line 58 of file xspan_impl_common.h.
Referenced by MemBuffer::alloc(), assign(), check_add(), check_deref(), CSelf(), invalidate(), operator+(), operator-(), raw_bytes(), raw_index_bytes(), raw_size_in_bytes(), size_bytes(), type_cast(), and xspan_check_range().