My Project: src/util/xspan_impl_ptr_or_null.h File Reference
xspan_impl_ptr_or_null.h File Reference
#include "xspan_impl_common.h"
#include "xspan_fwd.h"
Classes
struct PtrOrSpanOrNull< T >
PtrOrSpanOrNull.
Macros
#define CSelf PtrOrSpanOrNull
#define C XSPAN_NS(PtrOrSpanOrNull)
#define D XSPAN_NS(PtrOrSpan)
#define E XSPAN_NS(Span)
Functions
template<class T >
PtrOrSpanOrNull< T >::pointer raw_bytes (const PtrOrSpanOrNull< T > &a, size_t size_in_bytes)
template<class T >
PtrOrSpanOrNull< T >::pointer raw_index_bytes (const PtrOrSpanOrNull< T > &a, size_t index, size_t size_in_bytes)
Macro Definition Documentation
C
#define C XSPAN_NS(PtrOrSpanOrNull)
Definition at line 125 of file xspan_impl_ptr_or_null.h.
CSelf
#define CSelf PtrOrSpanOrNull
Definition at line 42 of file xspan_impl_ptr_or_null.h.
D
#define D XSPAN_NS(PtrOrSpan)
Definition at line 126 of file xspan_impl_ptr_or_null.h.
E
#define E XSPAN_NS(Span)
Definition at line 127 of file xspan_impl_ptr_or_null.h.
Function Documentation
raw_bytes()
template<class T > PtrOrSpanOrNull< T >::pointer raw_bytes (const PtrOrSpanOrNull< T > & a, size_t size_in_bytes) inline
Definition at line 104 of file xspan_impl_ptr_or_null.h.
{
    return a.raw_bytes(size_in_bytes);
}
References raw_bytes(), and size_in_bytes.
raw_index_bytes()
template<class T > PtrOrSpanOrNull< T >::pointer raw_index_bytes (const PtrOrSpanOrNull< T > & a, size_t index, size_t size_in_bytes) inline
Definition at line 109 of file xspan_impl_ptr_or_null.h.
{
    typedef typename PtrOrSpanOrNull<T>::element_type element_type;
    if very_unlikely (a.raw_ptr() == nullptr)
        throwInternalError("raw_index_bytes unexpected NULL ptr");
    return a.raw_bytes(mem_size(sizeof(element_type), index, size_in_bytes)) + index;
}
References index, mem_size(), raw_index_bytes(), size_in_bytes, throwInternalError(), and very_unlikely.