My Project: src/util/xspan_impl_ptr.h File Reference
xspan_impl_ptr.h File Reference
#include "xspan_fwd.h"
Classes
struct Ptr< T >
Ptr.
Macros
#define CSelf Ptr
#define C XSPAN_NS(Ptr)
#define D MemBufferBase
Functions
template<class T >
Ptr< T >::pointer raw_bytes (const Ptr< T > &a, size_t size_in_bytes)
template<class T >
Ptr< T >::pointer raw_index_bytes (const Ptr< T > &a, size_t index, size_t size_in_bytes)
Macro Definition Documentation
C
#define C XSPAN_NS(Ptr)
Definition at line 241 of file xspan_impl_ptr.h.
CSelf
#define CSelf Ptr
Definition at line 38 of file xspan_impl_ptr.h.
D
#define D MemBufferBase
Definition at line 244 of file xspan_impl_ptr.h.
Function Documentation
raw_bytes()
template<class T > Ptr< T >::pointer raw_bytes (const Ptr< T > & a, size_t size_in_bytes) inline
Definition at line 221 of file xspan_impl_ptr.h.
{
    return a.raw_bytes(size_in_bytes);
}
References raw_bytes(), Ptr< T >::raw_bytes(), and size_in_bytes.
raw_index_bytes()
template<class T > Ptr< T >::pointer raw_index_bytes (const Ptr< T > & a, size_t index, size_t size_in_bytes) inline
Definition at line 225 of file xspan_impl_ptr.h.
{
    typedef typename Ptr<T>::element_type element_type;
    if very_unlikely (a.raw_ptr() == nullptr)
        throwInternalError("raw_index_bytes unexpected NULL ptr");
    return a.raw_bytes(mem_size(sizeof(element_type), index, size_in_bytes)) + index;
}
References index, mem_size(), Ptr< T >::raw_bytes(), raw_index_bytes(), Ptr< T >::raw_ptr(), size_in_bytes, throwInternalError(), and very_unlikely.