My Project: src/util/xspan_impl_span.h File Reference
xspan_impl_span.h File Reference
#include "xspan_impl_common.h"
#include "xspan_fwd.h"
Classes
struct Span< T >
Span.
Macros
#define CSelf Span
#define C XSPAN_NS(Span)
#define D XSPAN_NS(PtrOrSpanOrNull)
#define E XSPAN_NS(PtrOrSpan)
Functions
template<class T >
Span< T >::pointer raw_bytes (const Span< T > &a, size_t size_in_bytes)
template<class T >
Span< T >::pointer raw_index_bytes (const Span< T > &a, size_t index, size_t size_in_bytes)
Macro Definition Documentation
C
#define C XSPAN_NS(Span)
Definition at line 145 of file xspan_impl_span.h.
CSelf
#define CSelf Span
Definition at line 42 of file xspan_impl_span.h.
D
#define D XSPAN_NS(PtrOrSpanOrNull)
Definition at line 146 of file xspan_impl_span.h.
E
#define E XSPAN_NS(PtrOrSpan)
Definition at line 147 of file xspan_impl_span.h.
Function Documentation
raw_bytes()
template<class T > Span< T >::pointer raw_bytes (const Span< T > & a, size_t size_in_bytes) inline
Definition at line 127 of file xspan_impl_span.h.
{
    return a.raw_bytes(size_in_bytes);
}
References raw_bytes(), and size_in_bytes.
raw_index_bytes()
template<class T > Span< T >::pointer raw_index_bytes (const Span< T > & a, size_t index, size_t size_in_bytes) inline
Definition at line 131 of file xspan_impl_span.h.
{
    typedef typename Span<T>::element_type element_type;
    return a.raw_bytes(mem_size(sizeof(element_type), index, size_in_bytes)) + index;
}
References index, mem_size(), raw_index_bytes(), and size_in_bytes.