My Project: src/util/xspan.cpp File Reference
xspan.cpp File Reference
#include "../conf.h"
Classes
struct XSpanStats
Functions
void xspan_fail_nullptr ()
void xspan_fail_nullbase ()
void xspan_fail_not_same_base ()
void xspan_fail_range_nullptr ()
void xspan_fail_range_nullbase ()
void xspan_fail_range_range ()
void xspan_check_range (const void *ptr, const void *base, ptrdiff_t size_in_bytes)
Variables
static XSpanStats xspan_stats
Function Documentation
xspan_check_range()
void xspan_check_range (const void * ptr, const void * base, ptrdiff_t size_in_bytes)
Definition at line 73 of file xspan.cpp.
{
    xspan_stats.check_range_counter += 1;
    if very_unlikely (ptr == nullptr)
        xspan_fail_range_nullptr();
    if very_unlikely (base == nullptr)
        xspan_fail_range_nullbase();
    upx_sptraddr_t off = ptraddr_diff(ptr, base);
    if very_unlikely (off < 0 || off > size_in_bytes || size_in_bytes > UPX_RSIZE_MAX)
        xspan_fail_range_range();
    NO_fprintf(stderr, "xspan_check_range done\n");
}
References base, NO_fprintf(), ptr, ptraddr_diff(), size_in_bytes, UPX_RSIZE_MAX, very_unlikely, xspan_fail_range_nullbase(), xspan_fail_range_nullptr(), xspan_fail_range_range(), and xspan_stats.
Referenced by assign(), check_add(), check_deref(), CSelf(), and raw_bytes().
xspan_fail_not_same_base()
void xspan_fail_not_same_base ()
Definition at line 55 of file xspan.cpp.
{
    xspan_stats.fail_not_same_base += 1;
    throwCantPack("xspan unexpected base pointer; take care!");
}
References throwCantPack(), and xspan_stats.
Referenced by assign().
xspan_fail_nullbase()
void xspan_fail_nullbase ()
Definition at line 51 of file xspan.cpp.
{
    xspan_stats.fail_nullbase += 1;
    throwCantPack("xspan unexpected NULL base; take care!");
}
References throwCantPack(), and xspan_stats.
Referenced by ensureBase(), and makeBase().
xspan_fail_nullptr()
void xspan_fail_nullptr ()
Definition at line 47 of file xspan.cpp.
{
    xspan_stats.fail_nullptr += 1;
    throwCantPack("xspan unexpected NULL pointer; take care!");
}
References throwCantPack(), and xspan_stats.
Referenced by check_add(), check_deref(), ensurePtr(), makeNotNull(), makePtr(), raw_bytes(), and Ptr< T >::raw_bytes().
xspan_fail_range_nullbase()
void xspan_fail_range_nullbase ()
Definition at line 64 of file xspan.cpp.
{
    xspan_stats.fail_range_nullbase += 1;
    throwCantPack("xspan_check_range: unexpected NULL base; take care!");
}
References throwCantPack(), and xspan_stats.
Referenced by xspan_check_range().
xspan_fail_range_nullptr()
void xspan_fail_range_nullptr ()
Definition at line 60 of file xspan.cpp.
{
    xspan_stats.fail_range_nullptr += 1;
    throwCantPack("xspan_check_range: unexpected NULL pointer; take care!");
}
References throwCantPack(), and xspan_stats.
Referenced by xspan_check_range().
xspan_fail_range_range()
void xspan_fail_range_range ()
Definition at line 68 of file xspan.cpp.
{
    xspan_stats.fail_range_range += 1;
    throwCantPack("xspan_check_range: pointer out of range; take care!");
}
References throwCantPack(), and xspan_stats.
Referenced by xspan_check_range().
Variable Documentation
xspan_stats
XSpanStats xspan_stats static
Definition at line 44 of file xspan.cpp.
Referenced by xspan_check_range(), xspan_fail_not_same_base(), xspan_fail_nullbase(), xspan_fail_nullptr(), xspan_fail_range_nullbase(), xspan_fail_range_nullptr(), and xspan_fail_range_range().