My Project: src/util/xspan_fwd.h File Reference
xspan_fwd.h File Reference
Macros
#define XSPAN_FWD_TU_CONVERTIBLE(RType)
#define XSPAN_FWD_TU_VOIDPTR(RType)
Functions
template<class T , class U >
std::enable_if< std::is_integral< U >::value, void * >::type operator+ (U, const C< T > &) XSPAN_DELETED_FUNCTION
overloads of global operators
template<class T >
void * memchr (const C< T > &a, int v, size_t n)
overloads for standard functions
template<class T >
const void * memchr (const C< const T > &a, int v, size_t n)
template<class T >
int memcmp (const C< T > &a, const void *b, size_t n)
template<class T >
int memcmp (const void *a, const C< T > &b, size_t n)
XSPAN_FWD_TU_VOIDPTR (int) memcmp(const C< T > &a
template<class T >
void * memcpy (C< T > a, const void *b, size_t n)
template<class T >
void * memcpy (void *a, const C< T > &b, size_t n)
XSPAN_FWD_TU_VOIDPTR (void *) memcpy(const C< T > &a
template<class T >
void * memmove (C< T > a, const void *b, size_t n)
template<class T >
void * memmove (void *a, const C< T > &b, size_t n)
template<class T >
void * memset (const C< T > &a, int v, size_t n)
template<class T >
int ptr_diff_bytes (const C< T > &a, const void *b)
overloads for UPX extras 1
template<class T >
int ptr_diff_bytes (const void *a, const C< T > &b)
template<class T >
unsigned ptr_udiff_bytes (const C< T > &a, const void *b)
template<class T >
unsigned ptr_udiff_bytes (const void *a, const C< T > &b)
XSPAN_FWD_TU_VOIDPTR (unsigned) ptr_udiff_bytes(const C< T > &a
Variables
const C< U > & b
const C< U > size_t n
Macro Definition Documentation
XSPAN_FWD_TU_CONVERTIBLE
#define XSPAN_FWD_TU_CONVERTIBLE (RType)
Value:
    template <class T, class U>                                                                    \
    inline XSPAN_REQUIRES_CONVERTIBLE_ANY_DIRECTION(T, U, RType)
Definition at line 38 of file xspan_fwd.h.
XSPAN_FWD_TU_VOIDPTR
#define XSPAN_FWD_TU_VOIDPTR (RType)
Value:
    template <class T, class U>                                                                    \
    inline RType
Definition at line 42 of file xspan_fwd.h.
Function Documentation
memchr() [1/2]
template<class T > const void * memchr (const C< const T > & a, int v, size_t n) inline
Definition at line 68 of file xspan_fwd.h.
{
    return memchr(a.raw_bytes(n), v, n);
}
References memchr(), and n.
memchr() [2/2]
template<class T > void * memchr (const C< T > & a, int v, size_t n) inline
overloads for standard functions
Definition at line 64 of file xspan_fwd.h.
{
    return memchr(a.raw_bytes(n), v, n);
}
References memchr(), and n.
Referenced by PackWcle::decodeFixups(), and memchr().
memcmp() [1/2]
template<class T > int memcmp (const C< T > & a, const void * b, size_t n) inline
Definition at line 73 of file xspan_fwd.h.
{
    return memcmp(a.raw_bytes(n), b, n);
}
References b, memcmp(), and n.
Referenced by PackLinuxElf32::ARM_is_QNX(), PackCom::canPack(), PackLinuxI386::canPack(), PackLinuxI386sh::canPack(), PackSys::canPack(), PackVmlinuxBase< TElfClass >::canPack(), PackVmlinuxBase< TElfClass >::canUnpack(), PeFile::canUnpack0(), PackLinuxI386::checkEhdr(), PackLinuxElf32::checkEhdr(), PackLinuxElf64::checkEhdr(), PeFile::checkHeaderValues(), PackWcle::decodeFixups(), PackVmlinuzI386::decompressKernel(), find(), PackLinuxElf32::generateElfHdr(), handle_allegropak(), ElfLinker::init(), is_dlm(), memcmp(), PackTos::pack(), PackLinuxElf32::PackLinuxElf32help1(), PackLinuxElf64::PackLinuxElf64help1(), LeFile::readFileHeader(), PackDjgpp2::readFileHeader(), PackPs1::readFileHeader(), PackTmt::readFileHeader(), PackVmlinuzI386::readFileHeader(), PackW32PeI386::readFileHeader(), TEST_CASE(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), upx_compiler_sanity_check(), upx_lzma_test_overlap(), and upx_zlib_test_overlap().
memcmp() [2/2]
template<class T > int memcmp (const void * a, const C< T > & b, size_t n) inline
Definition at line 77 of file xspan_fwd.h.
{
    return memcmp(a, b.raw_bytes(n), n);
}
References b, memcmp(), and n.
memcpy() [1/2]
template<class T > void * memcpy (C< T > a, const void * b, size_t n) inline
Definition at line 95 of file xspan_fwd.h.
{
    return memcpy(a.raw_bytes(n), b, n);
}
References b, memcpy(), and n.
Referenced by ElfLinker::addLoader(), PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PeFile::Export::build(), PeFile::Resource::build(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackLinuxElf32x86::buildLoader(), PackBSDElf32x86::buildLoader(), PackLinuxI386::buildLoader(), PackBSDI386::buildLoader(), PackLinuxI386sh::buildLoader(), PackExe::buildLoader(), PackNetBSDElf32x86::buildLoader(), PackOpenBSDElf32x86::buildLoader(), PackMachBase< TMachClass >::buildMachLoader(), PackLinuxElf32::canPack(), PackLinuxElf64::canPack(), PackMachBase< TMachClass >::canPack(), center_string(), Packer::compressWithFilters(), PeFile::Resource::convert(), PeFile::Export::convert(), PackWcle::decodeObjectTable(), do_option(), PackWcle::encodeImage(), PackLinuxI386::generateElfHdr(), PackLinuxElf32::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), PackPs1::getBkupHeader(), ElfLinker::init(), mem_replace(), memcpy(), PackCom::pack(), PackDjgpp2::pack(), PackExe::pack(), PackPs1::pack(), PackTmt::pack(), PackTos::pack(), PackVmlinuxBase< TElfClass >::pack(), PackVmlinuzI386::pack(), PackBvmlinuzI386::pack(), PackVmlinuzARMEL::pack(), PackWcle::pack(), PeFile::pack0(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32armLe::pack1(), PackLinuxElf32armBe::pack1(), PackLinuxElf32mipseb::pack1(), PackLinuxElf32mipsel::pack1(), PackLinuxElf32x86interp::pack1(), PackMachBase< TMachClass >::pack1(), PackLinuxElf32::pack2_shlib(), PackLinuxElf64::pack2_shlib(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackMachBase< TMachClass >::pack4(), PackMachBase< MachClass_LE64 >::pack4dylib(), PackMachBase< TMachClass >::pack4dylib(), PackUnix::packExtent(), PackMaster::PackMaster(), PackWcle::preprocessFixups(), PeFile::processImports0(), PeFile::processLoadConf(), PeFile32::processRelocs(), PeFile::processResources(), PeFile::processTls1(), PackPs1::putBkupHeader(), PackVmlinuzI386::readKernel(), PackVmlinuzARMEL::readKernel(), PackWcle::readObjectTable(), ElfLinker::Section::Section(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackMachBase< TMachClass >::unpack(), PackPs1::unpack(), PackTmt::unpack(), PeFile::unpack0(), upx_lzma_test_overlap(), upx_shellsort_memcpy(), upx_ucl_compress(), upx_zlib_test_overlap(), LeFile::writeFile(), and XSPAN_FWD_TU_VOIDPTR().
memcpy() [2/2]
template<class T > void * memcpy (void * a, const C< T > & b, size_t n) inline
Definition at line 99 of file xspan_fwd.h.
{
    return memcpy(a, b.raw_bytes(n), n);
}
References b, memcpy(), and n.
memmove() [1/2]
template<class T > void * memmove (C< T > a, const void * b, size_t n) inline
Definition at line 117 of file xspan_fwd.h.
{
    return memmove(a.raw_bytes(n), b, n);
}
References b, memmove(), and n.
Referenced by PackVmlinuzI386::decompressKernel(), PackMachBase< MachClass_LE64 >::find_SEGMENT_gap(), PeFile::Interval::flatten(), memmove(), PackWcle::pack(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), MyLzma::InStream::Read(), PackUnix::unpackExtent(), Packer::verifyOverlappingDecompression(), and MyLzma::OutStream::Write().
memmove() [2/2]
template<class T > void * memmove (void * a, const C< T > & b, size_t n) inline
Definition at line 121 of file xspan_fwd.h.
{
    return memmove(a, b.raw_bytes(n), n);
}
References b, memmove(), and n.
memset()
template<class T > void * memset (const C< T > & a, int v, size_t n) inline
Definition at line 139 of file xspan_fwd.h.
{
    return memset(a.raw_bytes(n), v, n);
}
References memset(), and n.
Referenced by ElfLinker::alignWithByte(), MemBuffer::alloc(), PackLinuxElf32::asl_pack2_Shdrs(), PackLinuxElf64::asl_pack2_Shdrs(), PackLinuxElf32::buildLinuxLoader(), PackLinuxElf64::buildLinuxLoader(), PackMachBase< TMachClass >::buildMachLoader(), PackLinuxI386::canPack(), PackLinuxElf32::canPackOSABI(), PeFile::canUnpack0(), center_string(), PeFile::Interval::clear(), LeFile::countFixups(), PackWcle::encodeFixups(), PackWcle::encodeObjectTable(), F(), MemBuffer::fill(), PackLinuxElf32::forward_Shdrs(), PackLinuxElf64::forward_Shdrs(), PackLinuxI386::generateElfHdr(), PackLinuxElf32::generateElfHdr(), PackLinuxElf64::generateElfHdr(), PackNetBSDElf32x86::generateElfHdr(), PackOpenBSDElf32x86::generateElfHdr(), FilterImpl::getFilter(), info(), mem_clear(), memset(), optimize_relocs(), PackUnix::pack(), PackVmlinuxBase< TElfClass >::pack(), PackBvmlinuzI386::pack(), PeFile::pack0(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), PackLinuxElf32x86interp::pack1(), PackMachBase< TMachClass >::pack1(), PackMachPPC32::pack1_setup_threado(), PackMachPPC64::pack1_setup_threado(), PackMachI386::pack1_setup_threado(), PackMachAMD64::pack1_setup_threado(), PackMachARMEL::pack1_setup_threado(), PackMachARM64EL::pack1_setup_threado(), PackUnix::pack2(), PackLinuxElf::pack2_shlib_overlay_write(), PackLinuxElf32::pack3(), PackLinuxElf64::pack3(), PackLinuxI386::pack4(), PackMachBase< TMachClass >::pack4(), PackUnix::packExtent(), PackLinuxElf::PackLinuxElf(), PackLinuxElf32::PackLinuxElf32(), PackLinuxElf64::PackLinuxElf64(), PackMachBase< TMachClass >::PackMachBase(), printClearLine(), PeFile::processImports0(), PeFile32::processRelocs(), PeFile64::processRelocs(), PackPs1::putBkupHeader(), ucl_compress_config_t::reset(), PackDjgpp2::stripDebug(), TEST_CASE(), PackMachPPC32::threado_setPC(), PackMachPPC64::threado_setPC(), PackMachI386::threado_setPC(), PackMachAMD64::threado_setPC(), PackMachARMEL::threado_setPC(), PackMachARM64EL::threado_setPC(), PackLinuxElf64::un_DT_INIT(), PackLinuxElf32::unpack(), PackLinuxElf64::unpack(), PackLinuxElf32x86interp::unpack(), PackMachBase< TMachClass >::unpack(), PackUnix::unpack(), PackUnix::unpackExtent(), upx_calloc(), and PackUnix::writePackHeader().
operator+()
template<class T , class U > std::enable_if< std::is_integral< U >::value, void * >::type operator+ (U , const C< T > &) inline
overloads of global operators
ptr_diff_bytes() [1/2]
template<class T > int ptr_diff_bytes (const C< T > & a, const void * b) inline
overloads for UPX extras 1
Definition at line 148 of file xspan_fwd.h.
{
    return ptr_diff_bytes(a.raw_bytes(0), b);
}
References b, and ptr_diff_bytes().
Referenced by ptr_diff_bytes().
ptr_diff_bytes() [2/2]
template<class T > int ptr_diff_bytes (const void * a, const C< T > & b) inline
Definition at line 152 of file xspan_fwd.h.
{
    return ptr_diff_bytes(a, b.raw_bytes(0));
}
References b, and ptr_diff_bytes().
ptr_udiff_bytes() [1/2]
template<class T > unsigned ptr_udiff_bytes (const C< T > & a, const void * b) inline
Definition at line 170 of file xspan_fwd.h.
{
    return ptr_udiff_bytes(a.raw_bytes(0), b);
}
References b, and ptr_udiff_bytes().
Referenced by ptr_udiff_bytes(), and XSPAN_FWD_TU_VOIDPTR().
ptr_udiff_bytes() [2/2]
template<class T > unsigned ptr_udiff_bytes (const void * a, const C< T > & b) inline
Definition at line 174 of file xspan_fwd.h.
{
    return ptr_udiff_bytes(a, b.raw_bytes(0));
}
References b, and ptr_udiff_bytes().
XSPAN_FWD_TU_VOIDPTR() [1/3]
XSPAN_FWD_TU_VOIDPTR (int) const &
XSPAN_FWD_TU_VOIDPTR() [2/3]
XSPAN_FWD_TU_VOIDPTR (unsigned) const &
References b, and ptr_udiff_bytes().
XSPAN_FWD_TU_VOIDPTR() [3/3]
XSPAN_FWD_TU_VOIDPTR (void *) const &
References b, memcpy(), and n.
Variable Documentation
b
const C< U > & b
Initial value:
{
    return ptr_diff_bytes(a.raw_bytes(0), b.raw_bytes(0))
Definition at line 80 of file xspan_fwd.h.
Referenced by anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::add_div(), anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::add_div_x(), Packer::addLoader(), upx::align_down(), upx::align_up(), ElfLinker::alignWithByte(), assign(), PeFile::Resource::build(), PackExe::canUnpack(), PackMachBase< TMachClass >::canUnpack(), anonymous_namespace{dt_check.cpp}::CheckAlignment< T >::check(), Packer::checkAlreadyPacked(), Packer::checkPatch(), anonymous_namespace{dt_check.cpp}::CheckIntegral< T >::checkU(), PeFile::ImportLinker::compare(), anonymous_namespace{help.cpp}::PackerNames::compare_fname(), PackMachBase< TMachClass >::compare_segment_command(), F(), f_ct16_e8(), f_ct16_e8_bswap_be(), f_ct16_e8_bswap_le(), f_ct16_e8e9(), f_ct16_e8e9_bswap_be(), f_ct16_e8e9_bswap_le(), f_ct16_e9(), f_ct16_e9_bswap_be(), f_ct16_e9_bswap_le(), f_ct32_e8(), f_ct32_e8_bswap_be(), f_ct32_e8_bswap_le(), f_ct32_e8e9(), f_ct32_e8e9_bswap_be(), f_ct32_e8e9_bswap_le(), f_ct32_e9(), f_ct32_e9_bswap_be(), f_ct32_e9_bswap_le(), f_ctsw16_e8_e9(), f_ctsw16_e9_e8(), f_ctsw32_e8_e9(), f_ctsw32_e9_e8(), f_sw16_e8(), f_sw16_e8e9(), f_sw16_e9(), f_sw32_e8(), f_sw32_e8e9(), f_sw32_e9(), find(), find_be16(), find_be32(), find_be64(), find_le16(), find_le32(), find_le64(), PackLinuxElf32::getbrk(), PackLinuxElf64::getbrk(), Packer::getPackHeader(), handle_allegropak(), anonymous_namespace{dt_check.cpp}::i64_f32_add_div(), anonymous_namespace{dt_check.cpp}::i64_f32_sub_div(), anonymous_namespace{dt_check.cpp}::i64_f64_add_div(), anonymous_namespace{dt_check.cpp}::i64_f64_sub_div(), makeBase(), upx::max(), upx::compile_time::mem_eq(), mem_replace(), memcmp(), memcpy(), memmove(), memswap_no_overlap(), upx::min(), PackLinuxElf32::pack1(), PackLinuxElf64::pack1(), Packer::patch_be16(), Packer::patch_be32(), Packer::patch_le16(), Packer::patch_le32(), Packer::patchPackHeader(), ElfLinker::preprocessRelocations(), PeFile::processImports0(), ptr_check_no_overlap(), ptr_diff(), ptr_diff_bytes(), ptr_udiff(), ptr_udiff_bytes(), ptraddr_check_no_overlap(), ptraddr_diff(), qcmp_unsigned(), reloc_entry_compare(), s_ct16_e8(), s_ct16_e8_bswap_be(), s_ct16_e8_bswap_le(), s_ct16_e8e9(), s_ct16_e8e9_bswap_be(), s_ct16_e8e9_bswap_le(), s_ct16_e9(), s_ct16_e9_bswap_be(), s_ct16_e9_bswap_le(), s_ct32_e8(), s_ct32_e8_bswap_be(), s_ct32_e8_bswap_le(), s_ct32_e8e9(), s_ct32_e8e9_bswap_be(), s_ct32_e8e9_bswap_le(), s_ct32_e9(), s_ct32_e9_bswap_be(), s_ct32_e9_bswap_le(), s_ctsw16_e8_e9(), s_ctsw16_e9_e8(), s_ctsw32_e8_e9(), s_ctsw32_e9_e8(), s_sw16_e8(), s_sw16_e8e9(), s_sw16_e9(), s_sw32_e8(), s_sw32_e8e9(), s_sw32_e9(), Filter::scan(), upx::compile_time::string_eq(), upx::compile_time::string_ge(), upx::compile_time::string_gt(), upx::compile_time::string_le(), upx::compile_time::string_lt(), upx::compile_time::string_ne(), anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::sub_div(), anonymous_namespace{dt_check.cpp}::TestFloat< Int, Float >::sub_div_x(), anonymous_namespace{dt_check.cpp}::TestNoAliasingStruct< A, B >::test(), anonymous_namespace{dt_check.cpp}::TestBELE< T >::test(), TEST_CASE(), anonymous_namespace{dt_check.cpp}::testNoAliasing(), BEPolicy::u16_compare(), LEPolicy::u16_compare(), BEPolicy::u16_compare_signed(), LEPolicy::u16_compare_signed(), BEPolicy::u24_compare(), LEPolicy::u24_compare(), BEPolicy::u24_compare_signed(), LEPolicy::u24_compare_signed(), BEPolicy::u32_compare(), LEPolicy::u32_compare(), BEPolicy::u32_compare_signed(), LEPolicy::u32_compare_signed(), BEPolicy::u64_compare(), LEPolicy::u64_compare(), BEPolicy::u64_compare_signed(), LEPolicy::u64_compare_signed(), anonymous_namespace{dt_check.cpp}::u64_f32_add_div(), anonymous_namespace{dt_check.cpp}::u64_f32_sub_div(), anonymous_namespace{dt_check.cpp}::u64_f64_add_div(), anonymous_namespace{dt_check.cpp}::u64_f64_sub_div(), u_ct16_e8(), u_ct16_e8_bswap_be(), u_ct16_e8_bswap_le(), u_ct16_e8e9(), u_ct16_e8e9_bswap_be(), u_ct16_e8e9_bswap_le(), u_ct16_e9(), u_ct16_e9_bswap_be(), u_ct16_e9_bswap_le(), u_ct32_e8(), u_ct32_e8_bswap_be(), u_ct32_e8_bswap_le(), u_ct32_e8e9(), u_ct32_e8e9_bswap_be(), u_ct32_e8e9_bswap_le(), u_ct32_e9(), u_ct32_e9_bswap_be(), u_ct32_e9_bswap_le(), u_ctsw16_e8_e9(), u_ctsw16_e9_e8(), u_ctsw32_e8_e9(), u_ctsw32_e9_e8(), u_sw16_e8(), u_sw16_e8e9(), u_sw16_e9(), u_sw32_e8(), u_sw32_e8e9(), u_sw32_e9(), upx::umax(), upx::umin(), PackLinuxElf32::un_shlib_1(), PackLinuxElf64::un_shlib_1(), upx_compiler_sanity_check(), upx_lzma_test_overlap(), upx_memswap(), upx_std_stable_sort(), upx_zlib_test_overlap(), wrap_nprogress_ucl(), upx::wrapping_add(), upx::wrapping_sub(), xcheck(), and XSPAN_FWD_TU_VOIDPTR().
n
const C< U > size_t n
Initial value:
{
    return memcmp(a.raw_bytes(n), b.raw_bytes(n), n)
Definition at line 80 of file xspan_fwd.h.
Referenced by PackLinuxElf32::canPack_Shdr(), PackLinuxElf64::canPack_Shdr(), check_add(), Ptr< T >::check_add(), check_deref(), Ptr< T >::check_deref(), PeFile::Resource::clear(), PeFile::Export::convert(), PackWcle::decodeEntryTable(), e_envopt(), e_optarg(), e_optval(), PackWcle::encodeEntryTable(), first_options(), fn_basename(), fn_has_ext(), fn_strlwr(), getcto(), LeFile::getImageSize(), getoptvar(), PackHeader::getPackHeaderSize(), PeFile::ilinkerGetAddress(), info(), upx::compile_time::mem_clear(), upx::compile_time::mem_eq(), upx::compile_time::mem_set(), mem_size(), mem_size_assert(), mem_size_get_n(), mem_size_valid(), memchr(), memcmp(), memcpy(), memmove(), memset(), my_malloc(), PeFile::ImportLinker::name_for_dll(), operator+(), Ptr< T >::operator+(), MemBufferBase< T >::operator+(), operator+=(), Ptr< T >::operator+=(), operator-(), Ptr< T >::operator-(), operator-=(), Ptr< T >::operator-=(), PackExe::pack(), PeFile::pack0(), prepare_result(), prepare_shortopts(), ElfLinker::preprocessSections(), prettyExceptionName(), ElfLinker::Section::Section(), set_output_name(), anonymous_namespace{pefile.cpp}::VPtr< T >::SPAN_S(), ElfLinker::Symbol::Symbol(), TEST_CASE(), upx_calloc(), upx_gnomesort(), upx_shellsort_memcpy(), upx_shellsort_memswap(), upx_std_stable_sort(), and XSPAN_FWD_TU_VOIDPTR().